### ISSUE TITLE
Latest posts not trimming topic/author/board name

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1001]
![capture](https://f.cloud.github.com/assets/1669995/1698104/d3ae7498-5f27-11e3-92df-6395cc0a7761.PNG)

**Comment by Oldiesmann** [comment]
How many characters do you think is reasonable for the topic/author/board names? We can do the standard SMF thing of "trim it, put '...' at the end and put the full name in the title attribute".

**Comment by Arantor** [comment]
We could always do it in CSS...

**Comment by Oldiesmann** [comment]
That works too

**Comment by MissAllSunday** [comment]
Can't reproduce, the text doesn't extend beyond. Unless you mean you don't want a second line, in that case word-wrap: break-word doesn't work too well with widths as percentage.

**Comment by Arantor** [comment]
Yup, he doesn't want it to wrap to a second line, ideally in any of the columns...

**Comment by MissAllSunday** [comment]
I still can't reproduce this or the desire behavior.

**Comment by Oldiesmann** [comment]
I still think the best way is to trim it after so many characters, add "..." and put the full subject in the title attribute like we do many other places.

**Comment by PhuriousGeorge** [comment]
Seems a good enough approach to me.

**Comment by Oldiesmann** [comment]
Just going to shorten the subject for consistency and such. The admin can deal with long display names and/or board names as they wish.
