### ISSUE TITLE
Installation Blocker (Settings_bak.php)

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1010]
Just the first thing I noticed while playing around with the most recent snapshot.

When I'm installing a fresh install from git, I'm getting the below error, there are two things here.

1) Unable to connect error is an incorrect error as I'm connecting via FTP and it's checking the file permissions, I've double checked this by entering in invalid details and it gives a different 'unable to connect' message.

2) 'Settings_back.php', it's saying it couldn't change permissions for this file, this is due to the file not existing on the server. The same error is gotten if the 'Settings.php' file is missing.
Maybe not for the 'Settings.php' file but there should be a check to make sure that the 'Settings_bak.php' file exists before trying to change it's permissions and also this file not existing shouldn't stop the installation process, it should create it based of the 'Settings.php' file and continue on in the installation process without the user ever noticing.

```
Unable to connect to FTP server with this combination of details.

550 Could not change perms on Settings_bak.php: No such file or directory -> Settings_bak.php
```

**Comment by illori** [comment]
maybe this is why emanuele had suggested to make a copy of Settings.php and rename it Settings_bak.php in the install directions for 2.1?

**Comment by Arantor** [comment]
The installation instructions are quite clear on this point - the alpha files on Github are not the same as the pre-made installation packages we normally published.

As far as I'm concerned - and this is going to be blunt - if you can't follow the instructions for them, you shouldn't really be playing with the alpha.

This will, naturally, not occur with pre-made packages because the package builder will do this for you.

**Comment by ghost** [comment]
No worries, I had read the installation guide and was fully aware of the installer situation. Just posting issues I'm finding in the 2.1 Alpha to help and so there not lost in the process.

**Comment by Arantor** [comment]
Except as stated this is not something that needs to be fixed in the GH repo because it is dealt with automatically at package building.
