### ISSUE TITLE
Installation Bar Colour

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1011]
Just a topic to bring up the UI of the installation screens, it works and flows grand the only thing I would say is the colour of progress bar is a bit odd, yellow gives the impression of not quite finished or partially done.

Was there a specific reason it was changed? I would suggest going back to a shade of green as it's a universal colour so to speak with progress bars.

**Comment by illori** [comment]
i believe last it was changed was due to a disagreement over what color it should be.
