### ISSUE TITLE
Link Styling Issue

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1012]
Minor issue. But under 'My Community - Info Center' the title links for 'Forum Stats' & 'Users Online' are the same colour as the background so there not visible.

**Comment by illori** [comment]
seems fault of https://github.com/SimpleMachines/SMF2.1/commit/0c472bcfee79fbbd353d7060e0e5a20db5d94a20 which changed the color of the links

**Comment by MissAllSunday** [comment]
Ah yeah, my bad, I thought that was the only place where that specific class used.

I suppose the theme section will have to use some other class and revert to the black color on .titlebg

I'll get it fixed.

**Comment by Oldiesmann** [comment]
@Arantor is going to fix it at some point, so don't worry about it. The infocenter does some strange things to the styles, so that's why it's causing problems there.

**Comment by Arantor** [comment]
Not just the info centre. There's a whole slew of places where h3.titlebg and h4.titlebg (amongst others) have totally different layout properties to the normal which is why this is a problem.

**Comment by illori** [comment]
the text on the "Attachments and other options" bar when making a post or the "Load drafts" bar still suffers from this issue. [just noting it anyway]
