### ISSUE TITLE
last/first post preview on the message index does not work

### ISSUE THREAD

**Issue by Hristo-** [SimpleMachines/SMF#1015]
I remember it worked a year ago. Set the characters to 100/200 with no effect, that is - there is no Preview. Using Wamp if that plays a role.

**Comment by Oldiesmann** [comment]
What browser are  you using? It works fine for me on my test board (http://smfgit.oldiesmann.us) using the latest version of Firefox.

**Comment by Hristo-** [comment]
Hmm, probably it is due to Wamp/localhost. Tried it on 5 browsers, so it's not the browser. Or maybe there is more than one "switch". I only set the characters, is this enough?

**Comment by Oldiesmann** [comment]
Admin -> Configuration -> Current Theme

Scroll down to the bottom and make sure "Show post previews on the message index" is checked.

**Comment by Hristo-** [comment]
Ah, my bad. Works well. Wanted to test whether or not the preview still includes the quotes. As I see there is no change.

BTW Using the admin search for "preview" showed only the other setting, while searching for "previews" says "No results found."

**Comment by Oldiesmann** [comment]
Yeah, theme settings don't show up in the admin search. I'll have to see if there's a way I can change that though.

**Comment by Arantor** [comment]
The theme setting system needs an overhaul in an ideal world. But there's really no good way to do that with the current architecture of admin search.

**Comment by Hristo-** [comment]
In that case do you mind to add a hint to the help menu of "Maximum length of last/first post preview" setting. Something similar to the one bellow, but of course with a better English :)

This option sets the number of available characters for the first and last message topic preview. Note this only makes the information available to the theme, the theme must support the message_index_preview setting.<b> If it does then you can enable/disable it from Admin -> Configuration -> Current Theme.</b>

**Comment by MissAllSunday** [comment]
Can someone write the proper hint sentence so it can be added.

**Comment by PhuriousGeorge** [comment]
Honestly, I think Hristo's suggestions works well IMHO.

**Comment by MissAllSunday** [comment]
I also ain't a native English speaker so I always ask for further assistance with strings :)

**Comment by PhuriousGeorge** [comment]
Fair enough, though you seem to write in English effectively :)
