### ISSUE TITLE
Time to wrap-up?

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#102]
We have several things in place and several pending, we are also "a bit" behind the schedule (not that there was any schedule :P), so maybe it's time to put a stop and wrap-up what we have.

Any objection if from Monday only bug-fixes will be accepted? (pull requests pending will be processed)

BTW I'm not the one that has to decide. :P

**Comment by Trekkie101** [comment]
Are Ant's changes considered bug fixes, as his Curve fixes are a damn help to 2.1 :P

**Comment by emanuele45** [comment]
Curve is already there, it needs to be fixed so... :P

(BTW I have almost no idea what he is doing, I didn't follow the theme)

**Comment by Trekkie101** [comment]
Ok :) he's ripping up some parts of the code and making it look a bit better. I just see whats on the board. But I fully agree on feature blocking and then bug fixing campaign :)

**Comment by Spuds** [comment]
Its a mystery for sure (well other than a few screen pics), but my guess is it will not be drop and play.   It started as cleanup as was in the 2.1 goals, now its appears to be curve 2, the return of the penguin dressed in curve :P

**Comment by IchBin** [comment]
I'd like an exception for features(s) to handle the mobile stuff. For example, we'll probably need to add code to auto-detect and display the mobile theme. Things like that.

**Comment by Spuds** [comment]
I think thats fine ... it was part of 2.1 goals and should only require source tweaks at this point

**Comment by mikemill** [comment]
I'm fine with it as long as you start a new branch for things that won't be going into SMF 2.1 :D

**Comment by live627** [comment]
Will there be a 2.2, out  of curiosity?

**Comment by joshuaadickerson** [comment]
I want to continue the 2.x line as long as it takes to get a new major version out. There should always be a branch for the next minor version.

As for wrapping up, I am all for it. I think we should look to push this out. Out of curiosity, there has been some talk about the pass-by-references in hooks, is that considered a bug or a feature? I think it will take a lot of work to get that working without issues but they make it so PHP 5.4 isn't really supported.

**Comment by ghost** [comment]
Re this: "Its a mystery for sure (well other than a few screen pics), but my guess is it will not be drop and play. It started as cleanup as was in the 2.1 goals, now its appears to be curve 2, the return of the penguin dressed in curve :P"

Yeah it's a little bit like that, but with the important difference that, outside of a few key templates, the minor changes that are made in a range of templates shouldn't affect existing themes and mods. Basically I've just added more classes for styling existing useful elements, while getting rid of unnecessary old spans, etc.

It will still require some CSS revision in old themes, but not a lot. I can create a checklist against 2.0 Curve once Return of the Son of Penguin is sorted. :P

**Comment by Spuds** [comment]
Good to hear, I think a checklist will be a big help to the community ... between the template redo and the editor redo things are somewhat different to say the least ...... and OMG Ant's on GitHub !

**Comment by emanuele45** [comment]
> Out of curiosity, there has been some talk about the pass-by-references in hooks, is that considered a bug or a feature?

The way I'm currently using to define a bug is: is the relevant code in the current codebase?
If the answer is yes: then it's a bug.
If the answer is no: then it's a new feature.

If you want to add a new hook that doesn't exists that's a new feature, if you want to fix the behaviour of a present hook it's a bug-fixing.

**Comment by ghost** [comment]
I must say that doing the theming this time has been an absolute joy compared to doing it for 2.0, when I still had to contend with IE6 and IE7. 95% + of stuff just works now, in all browsers (apart from CSS3 frills not showing in IE8).

Note that I still haven't touched RTL, but that's just a bit donkey work once LTR is sorted. Not a big deal. I'll get a demo up today so the crew can start freaking about stuff. :D

**Comment by jdarwood007** [comment]
Is this the feature set we want?  I feel we could do some more work on this still.
What are we aiming for?  Beta 1 or just a feature lock at this point?

It almost feels too early to do a Beta 1 release.  I wanted to see some features make it to 2.1 still.  I will work on those ideas as I can, hopefully having a pull request for one of them next week.

**Comment by emanuele45** [comment]
Feature lock and start public testing.

If we lock "now" we **should** (if we are lucky) be able to ship before Christmas, continue adding features and wait more means we will directly aiming at 2013.

Personally I would really really like to ship 2.1 final before the end of the year...

**Comment by jdarwood007** [comment]
Ok, so you are looking to lock and go stable.  So basically we are looking to get a beta released soon.  Feature locks mean no no features, however as a beta it means we still can do significate changes if need be.

In the playpen Josh and I had with 2.1 originally, we had a test of fixing up the $context['browser'] to a function and had it using some better detection which reduced the amount of checks we performed, which is less variables being used.  Of course that means that themes can't use $context['browser'] anymore, but isBrowser('firefox') would be the same as $context['browser']['is_firefox'].  Benefits come from the fact that we do detection for the basics, such as browser.  Then once a browser was detected we would drill down to specifics, such as version (ie for things like is_ie8).  While it contains a lot of changes to the code, I think its something we should push into the code.

**Comment by ghost** [comment]
Theme is in my repo now. Still needs some rationalisation for consistency and brevity in some places, but nothing that's a big deal. It's basically just join the dots now. So I'm calling the theme "feature locked" and ready for the mob. I already have a private hitlist of things it needs sorted, but no doubt everyone will tell me about them anyway. :D

**Comment by Spuds** [comment]
All of the isBrowser() stuff is in there, has been for quite some time.  

The detection functions were moved to Class-BrowserDetect.php which TBH was put together rather quickly so feel free to tune that up (the detection is output is part of the debug stuff now to make test spoofing a bit easier), actually noticed a simple miss in it yesterday while looking at some of our less than clever easter eggs,

Please note that it still populates the old $context['browser'][''] since we really don't want to break things that are easily preventable.  That part of the function should be flagged as depreciated and targeted to be removed in 2.2 (IMO), this gives the community time to adapt before we pull the rug out.

ETA: Any updates to function are in my somefixes branch in my playpen repo

**Comment by jdarwood007** [comment]
Oh I didn't even see that.  Good to know that made it in.

**Comment by joshuaadickerson** [comment]
Jeremy, if you still have that code that we did, you could setup a fork so we incorporate it in 2.2 although that might be a little soon.

**Comment by emanuele45** [comment]
Okay, we have to give a bit more time to Spuds to allow him to align the drafts code to the latest changes in the code (including the theme), apart from that we can start thinking to pack the first public release with what we have.

**Comment by Spuds** [comment]
> Jeremy, if you still have that code that we did, you could setup a fork so we incorporate it in 2.2 although that might 
> be a little soon.

What code are you talking about ?

Before you start with a 2.2 don't you _think_ it would be a good idea to spend some time on what it will be from a feature standpoint or has that already been decided without the rest of the team ?.  

With a published feature list on GitHub, we could be helping others to focus on whats needed, so time could be spend on code we need, or we can just have a giant cluster if thats whats indeed wanted.

> Okay, we have to give a bit more time to Spuds to allow him to align the drafts code to the latest changes in the code
> (including the theme), apart from that we can start thinking to pack the first public release with what we have.

Working on it now ... but for some reason the repo keeps changing :P

**Comment by emanuele45** [comment]
> Working on it now ... but for some reason the repo keeps changing :P

/me doesn't have any clue. :P

**Comment by ghost** [comment]
Hey yorta drop the penguin folder out of the main repo before we call this thing beta. Wont be shipping it anyway, so time to get rid of it methinks. It's all stashed anyway, so no point having it bloating the main branch.

**Comment by Spuds** [comment]
> Hey yorta drop the penguin folder out of the main repo before we call this thing beta. Wont be shipping it anyway, so
> time to get rid of it methinks. It's all stashed anyway, so no point having it bloating the main branch.
> I don't see it in the repo master branch, where are you seeing it?

Also frame_repeat, main_block and menu_gfx are no longer needed correct?

**Comment by ghost** [comment]
Yup, they can go. Also the browser-specific css files: webkit.css, ie6.css, ie7.css. We can probably ditch editor_ie.css and editor.css too (not sure how css works for SCE).

I keep getting penguin coming back every time I pull in stuff from upstream. Unless it has been deleted in the last day. If it's gone, no problem.

ETA: Oh and just a FYI. I'll probably knock about 10-15kb off admin.css by the time I'm finished, since it will no longer have to override the old default theme. Index.css will stay roughly the same size, give or take a litttle bit.

**Comment by Spuds** [comment]
I'll remove the old files in a clearnup commit I'm working on ...

The new editors look is done in jquery.sceditor.css ... 

Note that the file in the repo is from the 1.3.1 editor version, the latest on the site is 1.3.5 I think (css, the editor is later version and the css in in theme files).  You would have to merge in the SMF specific things in the 1.3.1 (bb code things), but 1.3.5 has some new classes you could make use of.  Or you could beg Ema :P

**Comment by emanuele45** [comment]
> I keep getting penguin coming back every time I pull in stuff from upstream. Unless it has been deleted in the last day. If it's gone, no problem.

You removed it once, then I [removed a piece of it again](https://github.com/emanuele45/playpen/commit/ad2888185350b9e2056817ebf92584223e61fbfd), it should be gone, but it's hard to remove...The [repo](https://github.com/SimpleMachines/SMF2.1/tree/master/Themes) seems clean though.

**Comment by emanuele45** [comment]
Okay, apart from a couple of my PRs (and another couple I have to fix) all the other at the moment don't merge cleanly.

@sicommnend I sent you a pull request that should fix the line endings problem, if you accept it it would be easier to merge the request (of course if you want to align the code with the latest version would be even better! :P)

Kays is fixing a couple of things on the attachments handling, I will check at what point he is.
Ant is working on the theme.
At the moment I'm not sure if these two are mandatory for an alpha or we can just pack it and send it out in the wild waiting to add these changes later for the beta (I tend to think option 2 would be fine with a "known issues" note :P)

**Comment by Trekkie101** [comment]
Is @IchBin at a state where the mobile theme could be in and considered alpha? :D?

**Comment by IchBin** [comment]
I wouldn't consider it ready for any type of release yet.

**Comment by emanuele45** [comment]
Okay, branches created and updated the [readme](https://github.com/SimpleMachines/SMF2.1) with some instructions.

From now on, the branch **release-2.1** will accept only bug-fixes related to the version 2.1, the branch **development** will accept new features, the branch **master** will not accept any pull request.
If you have a bug fix for 2.1 that should be ported to development submit it to 2.1 and mention in the PR message to bring it also to development.

cc @Antes and @marcusforsberg so they are aware of that too.
