### ISSUE TITLE
Undefined index: server

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#1025]
![error log](https://f.cloud.github.com/assets/1280380/1725099/379a4d3c-627b-11e3-8673-11e200647223.png)

**Comment by Arantor** [comment]
Using the most recent files on Github? (i.e. the copy of Load.php I updated in the last day or so)

**Comment by NanoSector** [comment]
Yes, I am.

**Comment by Arantor** [comment]
Oh. I know what the problem is. I forgot to commit something that would make this work.
