### ISSUE TITLE
Space between information bar and "Settings saved" box

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#1027]
Replace every instance of:

```
    if (!empty($context['saved_successful']))
        echo '
                    <div class="infobox">', $txt['settings_saved'], '</div>';
```

with:

```
    if (!empty($context['saved_successful']))
        echo '
                    <br /><div class="infobox">', $txt['settings_saved'], '</div>';
```

You could also add a < br /> after the description box I guess, but some areas might get too wide by that.

The message should also IMO get some kind of punctuation.

![warnings](https://f.cloud.github.com/assets/1280380/1725201/9d41ff44-627c-11e3-8d2f-6e16405c951e.png)

**Comment by Arantor** [comment]
Why not add a margin to the top instead? That seems a more proper course of action to me.

**Comment by NanoSector** [comment]
That makes it a global change, even in places that don't need extra space.

**Comment by Arantor** [comment]
Except pretty much everywhere that needs an infobox needs that extra space...

**Comment by NanoSector** [comment]
Then add the margin.

**Comment by Hristo-** [comment]
.infobox looks OK on other places, like profile area, i.e. adding margin will break it there.

**Comment by NanoSector** [comment]
That's what I was saying, however I didn't check it somewhere else. Thanks for confirming.

**Comment by felipeva** [comment]
¿por que solo no editas el css? algun margin-top..

2013/12/11 Rick Kerkhof notifications@github.com

**Comment by NanoSector** [comment]
As stated above, it would break other areas.
(Como se indicó anteriormente, se rompería otras áreas.)

**Comment by Hristo-** [comment]
Or maybe the infobox on admin center is misplaced at the moment? Maybe it should be like this:
![infobox](https://f.cloud.github.com/assets/6107569/1726346/cb485954-628d-11e3-8269-b28c2af5e64b.png)

That way it will be similar to profile area as of now:
![infobox_profile](https://f.cloud.github.com/assets/6107569/1726349/e9724de0-628d-11e3-962d-c6bfc5d705d9.png)

**Comment by Arantor** [comment]
That may be difficult to do, because of the differences between how the profile and the admin code work but it's certainly something we can look at.

**Comment by NanoSector** [comment]
Why would it be difficult? Why not add a generic box to the Admin template which is triggered everywhere once a certain $context variable is set? That also gets rid of the problem where the same code is repeated like 10 times.

**Comment by Arantor** [comment]
Because that template isn't controlled by the admin template but both the tabs and the header there are controlled by the generic menu template (which is also used in other places outside the admin area)

**Comment by Xarcell** [comment]
From a theme designer's perspective, <BR> should be avoided. In this case, it shouldn't be used and margin should be.

**Comment by Xarcell** [comment]
Would it be cumbersome to add additional class to the body per section? <body class="action_admin members". This would give more styling control.

**Comment by Hristo-** [comment]
Not exactly the same, but similar http://www.simplemachines.org/community/index.php?topic=515307.0 ;)

**Comment by Arantor** [comment]
You say it will give more styling control and when I ask for examples, I get one that requires changing the markup and one example I don't see even a tiny fraction of theme or mod authors using. I'm not asking for much, just some evidence that it's really worth doing.

**Comment by Hristo-** [comment]
That topic is closed for me. I just gave the answer to Xarcell's question. As for it's potential popularity, seems your right looking that no themer joined saying "Yea, I would like that too". Either this, or most known smf members just do not like to argue with top staff members. I'm not sure, but do not care much it's not something of such a big importance (the request).

**Comment by Arantor** [comment]
I'd be happy for people to argue with me if they're going to present me with an argument. ;) I just need to be sure that it's going to benefit more than it's going to hurt, if that makes sense.

**Comment by Xarcell** [comment]
I agree Arantor. Changes like this should be debated and considered carefully.
