### ISSUE TITLE
Undefined variable: board

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1043]
Search.php line 1845

```
    $context['can_restore'] = allowedTo('move_any') && !empty($modSettings['recycle_enable']) && $modSettings['recycle_board'] == $board;
```

Except that $board doesn't exist at that point, because this is a generic context rather than a per message context. I'm not entirely sure what that variable is used for right now, so logging it and will investigate when able (if someone else doesn't first)

**Comment by Xarcell** [comment]
This might be a stupid comment, just ignore if it is, but isn't $board the custom board that the admin selects for the topics to be recycled to?

**Comment by Arantor** [comment]
No. $board is generally 'the board we are currently in'. Except in the search page you're not in any board, therefore the variable has no meaning and doesn't exist anyway.

**Comment by Oldiesmann** [comment]
It would only make sense to define that there if you were searching a specific board, but even then, $board isn't specified in the global variables list.

It should also be noted that $context['can_restore'] is never used, nor are $context['can_send_email'] or $context['can_send_pm'], which are also defined in that area. It would make sense to define those on a per-topic basis in prepareSearchContext(), though I'm not sure when we'd use them.
