### ISSUE TITLE
Use of .smf_swaptip in other areas

### ISSUE THREAD

**Issue by mcblaber** [SimpleMachines/SMF#1058]
Team Reference: http://www.simplemachines.org/community/index.php?topic=515804.msg3647756#msg3647756

Similarly to the tooltip with profiles on the messageindex, we should begin using .smf_swaptip in other areas.

**Comment by Xarcell** [comment]
Hover effects should be avoided because of touch devices. Some devices work ok, most don't, and none work great. Click events should be used.

**Comment by Arantor** [comment]
Except the things this applies to would not generally be appropriate for such things.

**Comment by XinYenFon** [comment]
afaik smf_swaptip only used in messageindex when preview on topic title enabled. Personally speaking I don't see any real use of smf_swaptip inside any other area, but surely we are open for suggestions.

@live627
