### ISSUE TITLE
merge topics vs move topics

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1065]
i wonder why when we merge topics the list of boards includes the category but the move topics function does not include the category listing. i think it would be easier to not include the category in the listing.

**Comment by Arantor** [comment]
I'd rather include it actually. If you have a lot of boards, the extra is worth having for context.

**Comment by illori** [comment]
either way, they should be the same.

also it is annoying when merging topics if you change the board the topic id you put in before is removed from the box.

**Comment by Oldiesmann** [comment]
Why is it a problem that the topic ID is removed when you switch boards? Makes perfect sense to me. If you already know the ID of the topic, you shouldn't need to select a board.

I do agree with including categories in the list of boards for moving topics. Oddly enough, the mass-move-topics interface in the admin center does include category names.

**Comment by illori** [comment]
well if it works like moving a topic, you enter the topic ID then select the board to merge and _poof_ there goes the topic ID and you need to enter it again.

**Comment by Oldiesmann** [comment]
I'm not sure what you're expecting it to do.

If you know the ID of the target topic, then you enter that ID and click "Merge Topics".
If you don't, you choose the board that the target topic is in and click the merge icon to the left of that topic.

**Comment by illori** [comment]
and if you are thinking like _moving_ the topic to another board, you may also select the board. so the topic id gets deleted from the box once you change the board.

**Comment by Oldiesmann** [comment]
Why would you select a board if you know the ID of the target topic? There is no reason to do so.

If you know the ID of the target topic, enter it in the box and click "Merge Topics".
If you don't, select the board that the target topic is in and click the merge icon to the left of the appropriate topic.

**Comment by illori** [comment]
because if you are thinking like it is a move you always need to select the board.

**Comment by Oldiesmann** [comment]
There's nothing we can do about that. Short of writing fancy JavaScript to remember the value of that textbox between page loads, it's not possible. There are two separate forms. Selecting a board causes the first form to be submitted (`onchange="this.form.submit();"`).

Also, upon further inspection, categories are actually loaded on the move topics form - they're just displayed differently there (bold and italicized - using HTML's `<optgroup>` tag).

**Comment by illori** [comment]
but the category is not shown in the same way on the move topics form. IMO they should show the same.

**Comment by Oldiesmann** [comment]
I agree. The question here is which way do we want to do it - grayed out with dashed lines above and below it, or using HTML's optgroup?

The optgroup method uses less code:

``` html
<optgroup label="Category Name">
...
</optgroup>
```

Vs

``` html
<option disabled="disabled">--------------------------------------</option>
<option disabled="disabled">Category Name</option>
<option disabled="disabled">--------------------------------------</option>
```

**Comment by illori** [comment]
i like the format that the move topics page has, but it is not always obvious that the category is listed especially if it has many boards in it.

**Comment by Arantor** [comment]
We really should be using optgroups.

We should also really make sure we include the current board in the move dialogue, but disabled - something that is also currently inconsistently applied.

**Comment by Oldiesmann** [comment]
I fixed a couple of places with #1067. The only major place left is the jumpTo list, which will require some javascript rewriting. I'm not entirely sure how to do this, though, as it's a rather complicated setup.

**Comment by Arantor** [comment]
I'm actually thinking about rewriting the jumpto to be nicer, like a nice popup with friendly looking navigation (simpler JS, customisable layout, no issues with pretty URLs mods)... which would fix that entirely.

**Comment by jdarwood007** [comment]
@illori Whether I move or Merge a topic, the list provided is consistent for the boards drop down and shows categories and boards.
Is this still a problem?

**Comment by illori** [comment]
looks like it has been corrected over the years. the drop downs look a good bit different then they did in the past.
