### ISSUE TITLE
Login options inconsistent

### ISSUE THREAD

**Issue by HoverClub** [SimpleMachines/SMF#1087]
.... ?action=login

The header login input session time shows a select dropdown whereas the main login page has "Minutes to stay logger in" as a text input and "Always stay logged in" as a checkbox - this is inconsistent and may be a source of confusion for some users.

The main login page could be simplified by using the select box OR just get rid of the login time altogether and just have a "Stay logged in" option (I'll bet most users have no idea what the time actually means anyway)?  Maybe there is a good reason for having a user-defined time?

**Comment by illori** [comment]
what if you are on a public computer and forget to log out? you can set the logged in time for a short time and it will time out and log you out automatically.

**Comment by HoverClub** [comment]
The cookie expiry would be set to the default session expiry if the user hasn't selected "Stay logged in" and then reset on every page.  It seems overly complicated from a user's point of view having an option that isn't easily understood for most (almost no other sites ask for this at login - most just have a simple "remember me" option).

**Comment by Xarcell** [comment]
Not everyone wants to "stay logged in". However, I do see the inconsistency and they both should be the same. Both places should offer "time logged in".

I personally don't like having to re-login, although I do see the security benefit of having a session expiration regardless. However, if the session is going to expire regardless, then there is no point in having the option of being logged in various minutes.

Having said that and thinking it through, now I agree with Hoverclub. There just should be an option to "stay logged in", which text should probably be changed to "remember me". The user has to accept responsibility at some point for using the "stay logged in" feature. Having optional minutes is just bloat...

**Comment by Arantor** [comment]
Actually there's a minor architectural issue. SMF's cookie code doesn't particularly like the idea of a session of variable length that will expire when you close the tab. But that's fixable.

In other news... users who do forget to log out, are likely to forget to set 'remember me' in the first place. I'm inclined to make the change to a simple 'remember me' option.

**Comment by Arantor** [comment]
Note that there is now only one login method so it is inherently consistent. But I am not averse to changing it to be 'remember me' as a tickbox and do away with the time factor.

**Comment by Xarcell** [comment]
Fine by me. I'm concerned about bigger issues.

**Comment by Oldiesmann** [comment]
If we get rid of the "how long to stay logged in" option, how do we handle the "log me out as soon as I close the browser" functionality?

**Comment by illori** [comment]
where is the option to log you out when you close the browser? i dont see that.

**Comment by Oldiesmann** [comment]
There isn't one at the moment. My point is, if we get rid of the "time to stay logged in" option, we either need to pick a default length or somehow force the session to end as soon as the browser is closed.

**Comment by XinYenFon** [comment]
default length is a good solution ?

**Comment by Oldiesmann** [comment]
After looking around at other forums and such, I think the best option, if we disable the login length, is to just use session cookies, which will automatically expire when the browser is closed. Whether or not we'd need to rewrite SMF's cookie-handling stuff to handle that though is another question.

**Comment by Gwenwyfar** [comment]
If the main problem is having two options, why not only leave a select for "time to stay logged in", and then include "always stay logged in" as an option inside it? (No checkbox then, and you could have some default times set there, like 1 hour, 1 week, 1 month, etc.). This way you have clear information of how long you'll stay logged in for, and you can still choose something more in line with what you want for any particular session. Clearing a session after browser closure could be an option too (although I think 4-5 options in the select would be an ideal number).

**Comment by jdarwood007** [comment]
@HoverClub 
I can't reproduce this.  All login pages I know of look consistent

<img width="344" alt="screen shot 2018-07-15 at 11 20 21 am" src="https://user-images.githubusercontent.com/732116/42736839-a4204bf2-8821-11e8-8344-0356869bf408.png">
<img width="512" alt="screen shot 2018-07-15 at 11 20 34 am" src="https://user-images.githubusercontent.com/732116/42736840-a6180eb8-8821-11e8-827f-bea8ea0b4857.png">
<img width="893" alt="screen shot 2018-07-15 at 11 20 49 am" src="https://user-images.githubusercontent.com/732116/42736841-a7ae796a-8821-11e8-91f3-4f4d6cd3ed9e.png">

**Comment by Gwenwyfar** [comment]
I think the issue only refers to the "minutes to stay logged in" vs "always stay logged in" checkbox, not that the logins are different among themselves.

**Comment by jdarwood007** [comment]
Since this is a theme/layout design issue then.  Do you want to tackle it?

**Comment by Gwenwyfar** [comment]
Sure. Seems simple enough.

**Comment by Arantor** [comment]
Quick question: if you then fail to log in, do you still get the 'time to stay logged in' option come up as a textbox with an absurdly large number in it? (Because that was a really weird 2.0 bug that never really went away.)

**Comment by jdarwood007** [comment]
It was only a bug I think because the checkbox would actually change the time and it got represented back on the login page if it failed.

This seems to forget the time you selected if you fail a login.  Not in the scope of this issue but could be fixed code side.
