### ISSUE TITLE
CSS in Info Center 

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#1089]
Text "Forum Stats" and "Users Online" is virtually invisible in the info center.  CSS needs a tweak. Screenshots provided below.

How it is now.
![21fssg1](https://f.cloud.github.com/assets/6047983/1793936/fe7c71c6-69bc-11e3-86e6-d097058731c2.jpg)

How it was.
![21fssg2](https://f.cloud.github.com/assets/6047983/1793939/0892d04c-69bd-11e3-838b-5c99aa6630a9.jpg)

**Comment by Arantor** [comment]
Duplicate of https://github.com/SimpleMachines/SMF2.1/issues/1012
