### ISSUE TITLE
Remove theme bug

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#1093]
Create a copy of default theme.  disable it, and then click remove. Gives error 

"Database error, given array of string values is empty. (query_where)"

Had to do a complete reinstall, and new database to get forum working again.  Tried it again and got the same result.

**Comment by MissAllSunday** [comment]
Prob my bad :P I'll take a look at it, thanks for the report!

**Comment by live627** [comment]
ups, beat ya to it :P

**Comment by MissAllSunday** [comment]
Hey! I'm suppose to be the meanie here :P

Thanks!

**Comment by live627** [comment]
har har har
