### ISSUE TITLE
Requesting Default Avatar Be Moved To The Default Theme

### ISSUE THREAD

**Issue by Xarcell** [SimpleMachines/SMF#1098]
This is a request to move the default avatar to the default theme so a custom default avatar can be used with a custom theme. This just a little thing that gives themer's more play room.

BTW, I cannot figure out how to add the enhancement label to this issue.

**Comment by Hristo-** [comment]
I think only team members can use the labels.

**Comment by Arantor** [comment]
Correct, only team members can use labels.

Thing is, there isn't a default avatar yet...

**Comment by Xarcell** [comment]
Working on it. ;)

**Comment by Arantor** [comment]
Closing this issue because we'll implement it that way when we get to actually implementing a default avatar.
