### ISSUE TITLE
Admin panel error

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#1099]
Visiting admin panel results in the following error.

Type of error: General
2: sprintf() [<a href='function.sprintf'>function.sprintf</a>]: Too few arguments 
http://localhost/smf2.16/index.php?action=admin 
File: C:/xampp/xampp/htdocs/smf2.16/Sources/Who.php
Line: 772

**Comment by Arantor** [comment]
Oops. I'll fix this one shortly.

**Comment by lurkalot** [comment]
Thanks. ;)
