### ISSUE TITLE
Closing a report does not get logged

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1101]
As per http://www.simplemachines.org/community/index.php?topic=516050 the moderation log does not cover who closed a report or when.

Should it cover ignoring a report too?

**Comment by Oldiesmann** [comment]
Personally I've never understood the "ignore" option. If you don't want to deal with it, fine, but one person shouldn't be able to ignore the report for everyone.

**Comment by illori** [comment]
the ignore option has caused issues before on sm.org, maybe changing ignore to per user would be best if not remove it totally.

**Comment by Oldiesmann** [comment]
According to Arantor, ignoring a report temporarily closes it, but if the post is reported again, the info gets added to the ignored report. Closing a report causes a new report to get opened if you report a previously-reported post.

Either way, all of this info will get logged now.

**Comment by illori** [comment]
that still does not solve the issue of ignoring a report applying to everyone and not just the person that clicked ignore.

**Comment by Arantor** [comment]
That's the point of ignore, though: to ignore the reports for that topic. See, closing a report means future reports about the same message will be new messages. Ignoring a report means ignoring future reports about the same message.

As I outlined on IRC, by ignoring, you're saying "OK, so the members don't like it but we as a moderation team don't see that action is necessary"

**Comment by illori** [comment]
then maybe the name should be changed a bit so the moderators are aware that it ignores the report for all moderators.

**Comment by Xarcell** [comment]
I don't think ignore would be a proper word to use. Having read how Arantor describes it, and it ignores for all moderators. To me "ignore" sounds like a individual action, not a group action. Not sure what term would be proper, but here are a few off the top of my head:

Omit, Note, Disregard, Bypass, Duck, just to name a few.

**Comment by Arantor** [comment]
Disregard sounds good

**Comment by Xarcell** [comment]
I'm thinking Disregard is the best choice also from the ones I've mentioned.

**Comment by illori** [comment]
yep disregard sounds better, but i would not object to a help popup that explains how it works as well.

**Comment by Oldiesmann** [comment]
We can change it to disregard, but "un-disregard" sounds weird (and using "regard" there would also be a bit awkward).

**Comment by illori** [comment]
how about stop notify or stop watch like we have for the "unwatch" feature.

**Comment by Arantor** [comment]
We could, of course, always have the button as 'Care' and 'Don't Care' :tongue:

**Comment by Xarcell** [comment]
"Undo Disregard", not "un-disregard".

**Comment by PhuriousGeorge** [comment]
"Undo Disregard" sounds better than the previous options
