### ISSUE TITLE
File versions

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#1102]
When checking file versions via the Detailed Version Check

Sources.  RemoveTopic.php  is still at version 2.0 instead of 2.1 Alpha 1

Language files.  Drafts.english.php and Editor.english.php  are both version ?? (I'm guessing these are still being worked on).

But you guys probably already know this. ;)

**Comment by Arantor** [comment]
Commented upon in #334

**Comment by lurkalot** [comment]
Sorry Arantor.  I'm not getting the hang of this git thing at all am I.  I'm being more of a pain than a help.

**Comment by XinYenFon** [comment]
Actually @Arantor https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/RemoveTopic.php

**Comment by Arantor** [comment]
@lurkalot You're doing fine :) I mostly linked that other issue because there is a broad issue with this, not that it was a duplicate issue (since it wasn't entirely a duplicate)
