### ISSUE TITLE
Set Default Theme To Default

### ISSUE THREAD

**Issue by Xarcell** [SimpleMachines/SMF#1107]
Bringing back up a 3 year old topic.

Shouldn't the "default theme" be called something other than "default theme"? When reading or writing documentation, giving or requesting support, I think it is confusing to new users. For example:

1.| Support Statement: "set the default theme to default."
2.| Support Statement: "it uses the default theme's files & images"; but the user has set the default to a custom theme, thus the confusion when it doesn't work.
3.| Support Statement: "put it in your default theme"; again, the user has set the default theme to a custom one.
4.| Support Question: "how do I change (something) in my default theme?"; user is talking about their custom theme that is set to default.

Etc...

Other terms that could be used are: Master Theme, Starter Theme, Primary Theme, just to name a few off the topic of my head.

I'm in more favor of the "Master Theme" term, because it's just that, a master copy: http://www.thefreedictionary.com/master+copy .

Since a variable is used for the location of the default theme, I don't think it would cause backwards compatibility issues would it?

**Comment by Arantor** [comment]
It does have a name. It's currently called Curve2.

**Comment by Xarcell** [comment]
The problem here isn't the name if the theme. The problem here is what it's called. The theme directory says "default". Again, confusion.

**Comment by illori** [comment]
i really dont see it an issue. if we change it we will confuse more people that are used to, what 10 years of, calling the theme that comes with smf as the default theme.

**Comment by Arantor** [comment]
I don't see how we can, practically, change it anyway in 2.1.
