### ISSUE TITLE
"Enable unwatch topics"

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1111]
i think this text string needs a bit of work... when enabled we have buttons that read "Stop Watching" and "Watch" why not use "Enable watching topics" or similar?

unwatch just seems a bit out of place here.

[could say the same about the url used when watching/unwatching a topic http://localhost:8080/github2.1/index.php?action=unwatchtopic;topic=6.0;sa=off;fa1e77e64f95=11c0a91083e8ac334f0e4f81e572f45c ]

**Comment by Oldiesmann** [comment]
"Enable watching topics" doesn't make sense because that's not what that setting does. You can always watch topics - you just can't "unwatch" them if that setting isn't enabled.

**Comment by illori** [comment]
it still seems a bit odd wording to me. and not consistent. then why not enable stop watching topics?

**Comment by Oldiesmann** [comment]
Why didn't this come up when the decision was made months ago to change it from "disregarded topics" to "unwatched topics"?

I think it's fine the way it is at the moment. We can consider changing it in the future (eg sometime before final) if it ends up confusing a lot of people.

**Comment by illori** [comment]
we were only talking about the public face of this feature at that time, not the setting in the admin panel.

**Comment by Xarcell** [comment]
I think the terms "watch" and "unwatch" are fine. Although I prefer "follow" and "unfollow".

"Enable unwatch topics" would be best as "Enable unwatched topics".
