### ISSUE TITLE
unused userlog strings

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1120]
the $helptxt['userlog']  seems to exist but is not actually used, along with this apparently we have $txt['userlog_enabled'] which is not used either. there are some references to userlog in the source files but it seems no choice for admin to enable/disable this feature

**Comment by Arantor** [comment]
Both strings are used. Try Admin > Maintenance > Logs > Log Settings > Enable the profile edits log, including the help text for it.

**Comment by illori** [comment]
strange, i had done a search and it did not show up. better safe then sorry ;)

**Comment by Arantor** [comment]
That's because helptext strings never ever show up directly, you need to find those by way of action=helpadmin links. As far as the other one, IIRC the log settings page does it via a loop.
