### ISSUE TITLE
width of .ignoreboards at lower screen resolutions

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1124]
![Alt text](http://imageshack.us/a/img546/9008/075s.png)

this was changed before in https://github.com/SimpleMachines/SMF2.1/commit/da03714a0dd5df3a2c8546850f0eef6b76001cc9

if the width is a bit larger then this is no issue at smaller resolutions.

**Comment by Oldiesmann** [comment]
That's a weird one. The width of that CSS class was originally changed to make the boards list show up in two columns in the profile (at least based on the commit message for the change you linked to), but it looks really weird that way, and I have no idea why we're doing that in the admin center. For what it's worth, even at 1280x800, the "All boards in this category" text wraps to a second line. I'll see what I can do about fixing the layout of both areas.

**Comment by illori** [comment]
we need to define a new class for it in the admin panel... maybe even adding it to the admin.css file instead of index.css

**Comment by Arantor** [comment]
The reason for doing it in the profile is because if you have a ton of boards you really need it in two columns, e.g. as on sm.org to prevent the page being very very narrow and long.
