### ISSUE TITLE
Send out Newsletter fails

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#1137]
Possible fix:
https://github.com/emanuele45/Dialogo/commit/304e22dd368c6386428c1b65583a4da593a32215

**Comment by Arantor** [comment]
I don't see how the suggested fix would necessarily change things. All it's doing is extra validation that a field is non empty before processing it. If it's failing, it should be failing for another reason.

**Comment by Archer70** [comment]
Is this... still an issue?
Steps to reproduce (the issue, specifically)?

**Comment by jdarwood007** [comment]
@emanuele45 I can't reproduce this.  From what I see you are ensuring we are only processing the groups/excluded groups if the string isn't empty.  However the explode should return a empty array in this case resulting in the foreach not occurring.

If you are able to provide some reproducible steps then we can look into this.
