### ISSUE TITLE
Delete membergroup never updates subscriptions table

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1141]
If a member group is deleted, its deletion is never checked against the subscriptions table, so if a group is either added to an account as a subscription, or added after the subscription finishes, that group can be deleted without updating the subscription.

**Comment by Arantor** [comment]
Perhaps we should block deletion if it is in use because this has repercussions that we can't always safely fix (unlike deleting a paid sub, when we can always undo the changes a sub would make)... if you delete the group a user is in as the result of a promotion, as the primary group, you can't just delete the subscription because there might be secondary group changes too... hmm.

**Comment by Oldiesmann** [comment]
I'd be inclined to just prevent deleting of groups tied to paid subscriptions. It's much easier to bail out than to try and figure out all the group changes.
