### ISSUE TITLE
Cancelling a paid sub doesn't notify PayPal

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1170]
http://www.simplemachines.org/community/index.php?topic=390543.0

Cancelling a paid sub doesn't notify PayPal that the paid sub is done, so an auto-renew sub will carry on renewing.

**Comment by Arantor** [comment]
Also I seem to remember that SMF also won't process the notification from PayPal to notify it that the sub is being cancelled (just throws the unknown transaction type error)

**Comment by PhuriousGeorge** [comment]
I'm curious, I have't used subscriptions myself, but if a subscriber cancels the sub through PayPal, rather through the forum, is the forum notified & update appropriately?

Edit: I think Arantor beat me to it.

**Comment by Arantor** [comment]
That's just it, I'm not entirely sure they are. That said, when renewal comes around, SMF won't renew it because PayPal handles that part of it - PP notifies SMF and says 'hey, payment received, update your records'.

**Comment by Arantor** [comment]
http://thereforei.am/2012/07/03/cancelling-subscriptions-created-with-paypal-standard-via-the-express-checkout-api/ seems like a useful article.

**Comment by aldobarr** [comment]
From what I recall, SMF relies on paypal notifying it of renewals every so often. If it doesn't get notified, then the subscription must have been cancelled, so it expires normally.

On the other hand, a system like Google Wallet sets up an auto renew subscription by notifying the server that a subscription was created. Google Wallet won't provide any further notification, except for a cancellation notification when the user cancels their subscription on Google Wallet's end. Therefore, it would be SMF's responsibility to apply renewals until cancellation.

**Comment by Arantor** [comment]
Except you're looking at it from the other perspective. If you cancel it in PayPal, sure, SMF won't get notified. But if you cancel a recurring sub in SMF... PayPal carries on paying anyway. So SMF needs to notify PayPal when this happens.

Like I have already said, SMF's entire paid subs architecture is built around how PayPal works, not how anything else works, and changing it to work how Google Wallet works first and foremost will break how PayPal works.

**Comment by aldobarr** [comment]
I'm not saying it should change from one api to the other, I was contrasting how paypal does things with how someone else does things and nothing else really...

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
