### ISSUE TITLE
Message Index Icons Not Displaying

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1172]
Looks like `.generic_icons.lock`is causing the images not to display for:
- Locked Topics
- Stickey Topics

And `.generic_icons.poll` is affecting the icons displaying for:
- Poll

These is on the icon legend at the bottom of the message index, seems to only be affecting Firefox,

**Comment by ghost** [comment]
Looks like it was being caused on version 24 of Firefox, it isn't happening now on the latest version 26 so I'm going to close this.

**Comment by Arantor** [comment]
That would indicate something is very, very wrong with Firefox 24...
