### ISSUE TITLE
BBC breaks page layout

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1175]
## **Old Bug Report**

BBC breaks when put inside a code BBC element in post.

This is the code supplied on the original bug report.

```
[code]
[table][tr][td]
[table][tr][td]
[/center]
[/td][/tr][/table][/td][/tr][/table][/code]
[table][tr][td]
[table][tr][td]
[/center]
[/td][/tr][/table][/td][/tr][/table]
[img]http://media.simplemachinesweb.com/smf/smsite2/images/site/smsite_logo.jpg?rc2.1.1[/img]
[table][tr][td]
[table][tr][td]
[/center]
[/td][/tr][/table][/td][/tr][/table]
[img]http://media.simplemachinesweb.com/smf/smsite2/images/site/smsite_logo.jpg?rc2.1.1[/img]
[/code]
```

**Comment by Oldiesmann** [comment]
So if you put table tags inside code it breaks? The main issue I see there is you have a couple of stray [/center] tags...

**Comment by Arantor** [comment]
The code part, I assume was for replication purposes. There are so many issues driven by SMF's trying to be helpful in the preparser where it tries to fix bad tags especially table tags.

**Comment by Xarcell** [comment]
Could the BBC code itself be the problem? Why are there closing center tags within the table tags, rather than inside the table-cell's. Are you doing this during live preview I assume? Need more specific's on how you created this issue.

**Comment by Arantor** [comment]
This is a bug report from the main bug reports board. But I'm well aware of some of these issues as some of them go back _years_. The preparser tries to do certain validations and enforcements, for example forcing a td to be inside a tr to be inside a table, and vice versa that a table contains a tr contains a td. Amongst other things it prevents introducing th tags for nicer tables, but there are so many issues that relate to this hierarchy it's unreal.
