### ISSUE TITLE
SiteMap

### ISSUE THREAD

**Issue by snrj** [SimpleMachines/SMF#1177]

**Comment by MissAllSunday** [comment]
So... SiteMap

:confused: 

Gonna take a huge risk here and vaguely assume you want SMF to have a sitemap as a core feature, this is of course pure speculation on my part...

**Comment by Arantor** [comment]
I'm going to take a bigger leap of faith and assume this is about an XML site map.

The big question, core or not? I'm not actually fussed either way and can make great arguments on both sides.

**Comment by MissAllSunday** [comment]
Yeah, this is one of those things I can live with or without it been core, I do use a sitemap but other than that I have no real arguments for or against so I'm cool with whatever is decided.

**Comment by Xarcell** [comment]
I would like to see a XML sitemap, but don't have to have it. I guess it would depend on how much work is involved, and if anyone has the time to do it.

**Comment by snrj** [comment]
I  accidentally open topic
I guess was the beneficial

**Comment by snrj** [comment]
![adsz](https://f.cloud.github.com/assets/1269557/1916142/f6a2d5f2-7d72-11e3-8ff5-9c3d3ce722a3.jpg)
![adsz1](https://f.cloud.github.com/assets/1269557/1916146/faf6460c-7d72-11e3-93b1-3f9d48460083.jpg)
![adsz2](https://f.cloud.github.com/assets/1269557/1916147/fcb60c7a-7d72-11e3-9445-ac5fbd71dcfa.jpg)
![adsz3](https://f.cloud.github.com/assets/1269557/1916148/fe64aab8-7d72-11e3-9721-7e62e6044832.jpg)
http://custom.simplemachines.org/mods/index.php?action=download;mod=755;id=160006

**Comment by Arantor** [comment]
Except that we still would have to rewrite it from scratch if we wanted to include it in SMF. Also note that that would not work properly on larger sites (sm.org itself for example could not use it)

**Comment by XinYenFon** [comment]
TBH, don't know what you guys think but, Sitemap is extra for a site, since we all share our links on social networks (Reddit/FB/Twitter/G+/Slashdot etc...) they already bringing bots along with them. Plus a request doesn't fit for general use (according to Arantor big site's not), i see no real usage for this in CORE (I'm not saying Sitemap's are bad or useless).

**Comment by Oldiesmann** [comment]
Sitemaps are useful, but including something like that in SMF by default would be a lot of work, and we'd have to ensure it's done properly and such. I'm fine with leaving it as a mod for now.

**Comment by live627** [comment]
So then can this be closed?

**Comment by MissAllSunday** [comment]
yep :)
