### ISSUE TITLE
Guests Can't Reply to Own Topic

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1179]
## *\* Old Bug Report **

Once guests are allowed to post topics they are unable to reply to the topic they started, this was considered a valid bug when originally reported, still functions this way in 2.1 alpha.

**Comment by Arantor** [comment]
More details: http://www.simplemachines.org/community/index.php?topic=472533.0 (original topic now moved to closed bug reports, just to so that we can keep the BR board for staging purposes)

**Comment by Oldiesmann** [comment]
Just tested and this bug still occurs in the latest build. Will look into it and see if I can figure out what's causing it.

**Comment by Arantor** [comment]
I'm not actually sure that works properly, on the basis that you don't seem to be checking that the topic in question is a guest topic for purposes of reply to own (i.e. guest replying to guest topic)
