### ISSUE TITLE
Maintenance Mode Bug

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1180]
## *\* Old Bug Report **

Tested in 2.1 alpha, still present.

Steps from original bug report:
Go to: Administration Center » Server Settings » General
Enable Maintenance Mode

Now go to: Administration Center » Server Settings » Database and Paths
Save settings (don't change anything)

Go to: Administration Center » Server Settings » General
Maintenance Mode is disabled.

**Comment by Oldiesmann** [comment]
Looks like it's leftover from the days when all the server settings were on one page. Testing a fix now.

**Comment by Arantor** [comment]
Random question: we pass $config_vars to saveSettings, so we know what variables this page is expecting to save... why not just go from that?
