### ISSUE TITLE
Guest Calendar Post Button Displyed Even If Guest Can't Post

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1182]
## *\* Old Bug Report **

Tested in 2.1 alpha, still present. The thinking/discussion behind it is that if guests cannot post topics they shouldn't see the button.

Original bug report description:
Calendar enabled, added permission for guests: Create events in the calendar

Guests see button, but when they try to add event they see: Sorry, you cannot post new topics in this board.

So I think that would be nice to hide it in this situation

**Comment by Oldiesmann** [comment]
Theoretically they can still post events even if they can't post new topics, but only if the admin has enabled the "allow events not linked to posts" in the admin center. This needs to be checked, and we should probably add something in the calendar settings and/or permissions area indicating this.

**Comment by Arantor** [comment]
Actually...this doesn't work properly.

Even if the admin has enabled 'allow events not linked to posts', the code flow through Calendar.php::CalendarPost() still demands the user be able to post in at least one board. The button behaviour itself is theoretically correct insofar that they would theoretically be able to post if that test weren't there to stop them.

**Comment by Oldiesmann** [comment]
That should fix the other issue you brought up. I think part of that code is a holdover from 2.0, when that portion of code was called when you were forced to link things to a topic (that situation is handled in Post() now).

**Comment by Arantor** [comment]
Sounds good to me :)
