### ISSUE TITLE
Deleting a user should delete their poll votes

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1185]
Currently, deleting an account converts all their poll votes to guest votes, even if guests could not vote.

This should be changed so that deleting an account deletes their votes (and updates the various polls they voted on, it's kind of complicated)

Previously tracked as http://www.simplemachines.org/community/index.php?topic=466310.0 and Mantis 4178.

**Comment by Xarcell** [comment]
Agreed.

**Comment by Arantor** [comment]
As per the original topic on the subject, it was observed that this wouldn't be desirable behaviour either. What I think we might need to do is alter the form where we handle deletion and offer the option to delete/not delete poll votes (like we offer the option to delete/not delete all the posts of a user)

**Comment by Xarcell** [comment]
Sounds good too.

**Comment by PhuriousGeorge** [comment]
I believe this is the best approach, but I may be tainted as personally for my sites I'd prefer to maintain my poll counts even if the user no longer exists.

**Comment by XinYenFon** [comment]
Delete users posts & poll votes, otherwise you need to made a system recovers user's posts as well as poll votes.

**Comment by Arantor** [comment]
There's already a system for recovering user's posts if not deleted ;)

But it's a tough one to balance between 'keeping the votes to keep an accurate record' and 'cleaning the votes to make it look accurate'

**Comment by Oldiesmann** [comment]
One solution to this could simply be to add a third option to the list of what to delete - "Posts", "Topics and Posts" and a new one "Topics, Posts and Poll Votes". That way the admin could choose whether the user's poll votes are worth keeping or not.

**Comment by Arantor** [comment]
Yup, as I said a few weeks ago, that's definitely an option, probably the best option.

**Comment by Oldiesmann** [comment]
After thinking about this some more, I think a better option would simply be a separate checkbox for "Delete poll votes", as there may be situations where you want to keep their topics and/or posts but you want to delete their poll votes anyway. I'm going to add it in that way and we can change it later if desired.
