### ISSUE TITLE
'Link to Calendar' button available for any registered member

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1190]
## *\* Old Bug Report **

Still occurs in 2.1 alpha.

When the calendar is enabled the 'Link to Calendar' option is visible to any registered member regardless if the have permissions on the topic or not.

There should be a check to see if the member has relevant permission on the topic and if not, then not show the 'Link to Calendar' option.

**Comment by Oldiesmann** [comment]
Unable to reproduce on my 2.1 test board. It's based on the "calendar_post" permission. I removed that permission from the "regular users" group, then logged in as a regular user, and the button was not shown.

**Comment by ghost** [comment]
Must have left out a bit of the description, once the 'calendar_post' permission is selected the button is displayed regardless if the user has permissions on the post, if another user goes to a topic they haven't created they have the option displaying but when they click on it they get an error saying they don't have permissions to do that. Hope that makes it clearer.

**Comment by MissAllSunday** [comment]
I was looking into this today and wasn't able to reproduce either

**Comment by MissAllSunday** [comment]
whats the exact permission on the post?  to actually post on the topic or modify the topic?

I suspect is the modify topic permission.

**Comment by Oldiesmann** [comment]
@MissAllSunday You're making this more complicated than it needs to be.

Adding this line will handle it:
`$context['calendar_post'] &= allowedTo('modify_any') || (allowedTo('modify_own') && $context['user']['started']);`
