### ISSUE TITLE
User changing email address issues

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1191]
## *\* Old Bug Report **

Still present in 2.1 alpha, tested and confirmed.

1) When `Require reactivation after email change` is enabled and a user changes their email address they are logged out, it isn't entirely clear that when a user changes their email that they will be logged out.

2) After the user changes their email and are logged out the 'Modify Profile' and 'Actions' options are still visible.

**Comment by Oldiesmann** [comment]
That should be intended behavior. SMF doesn't let you login if your email address hasn't been activated yet, so I don't see why this should be an exception.

**Comment by ghost** [comment]
Maybe a change in the text displayed to say you will be logged out either a popup just before you confirm your email change or a change to the text displayed once you've changed your email and have been logged out as it's not entirely clear.

**Comment by MissAllSunday** [comment]
I'll take care, does a pop up when saving would be enough?

I don't know about changing the 

$txt['valid_email'] = 'This must be a valid email address.';

Since it might be used somewhere else.

**Comment by Arantor** [comment]
Yah I wouldn't modify that string.

**Comment by emanuele45** [comment]
Actually the original report was that the moderate button was still visible even if logged out after the email change, not that you are logged out.

Suggestion: a link to the original report would help in tracking all the conditions, questions, tests and possible fixes already tried/proposed.

**Comment by ghost** [comment]
Very true, my fault for missing this bit, the 'Modify Profile' and 'Actions' options are still available when the user is logged out after changing their email, it was suggested in the original bug report that it's a missing redirectexit somewhere by yourself emanuele45.

With that said it still should be noted that it's still not clear that you will be logged out upon changing your email.

I'll update the original issue here to cover both items.

**Comment by NanoSector** [comment]
For reference with screenshots since there seems to be confusion:
http://www.simplemachines.org/community/index.php?topic=488949.0
