### ISSUE TITLE
Token Error Activating/Approving Members Through Profile

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1194]
If a member needs to be activated/approved for whatever reason, if you try to activate/approve them through their profile it will give you a token error and wont activate/approve the member account.

`Admin > Members > View All Members`, click on the member to view their profile and now click on the activate/approve option.

You should get the following error: Token verification failed. Please go back and try again

**Comment by Xarcell** [comment]
Good catch, I thought all of these had been resolved.
