### ISSUE TITLE
BBCode Issues

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1197]
## *\* Old Bug Report **

Original report:
Look at this message, bbcodes does not work:

```
[size=14pt][center]TEST[/center][/size]
```

While here if it works:

```
[center][size=14pt]TEST[/size][/center]
```

This is inline with valid markup, maybe something can be done to check for incorrectly entered bbcode by a user and adjust for it!?

---

Other issue raised was some tags not being closed properly.

Steps to reproduce:
1) write 4 lines of text,
2) select all of them and change size and color using the formatting tools (i.e. the drop down lists, or otherwise put a color and/or size tag around the entire text),
3) select the second line and change the color (same as above with the drop down list, or put a color tag around the second line),
4) select the third line and apply the code tag with the code button (or put code tags around the third line)
5) (optional) select the last line and change color (again with the tool or putting color tags)
It will end up with some tags improperly closed.

**Comment by Arantor** [comment]
Ref: http://dev.simplemachines.org/mantis/view.php?id=3553
