### ISSUE TITLE
Post content is lost when using back button

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1204]
## *\* Old Bug Report **

Still present in 2.1 alpha, tested in and occurs in, topic title is kept, post body isn't:

Firefox 26
IE 10
Chrome 32

Original report:
My problem is, sometimes when I starting a new topic or replying a post, I just suddenly click the Back button at the browser. When I go Forward, SMF doesn't save my post. So I have to start all over again especially a long post/reply.

**Comment by illori** [comment]
i believe at the time this was reported it was a browser issue with firefox, i would guess that the current issue is related to the new editor and not at all similar to the old report.

**Comment by Arantor** [comment]
Ref. http://www.simplemachines.org/community/index.php?topic=427739.0 and http://www.simplemachines.org/community/index.php?topic=363292

**Comment by Arantor** [comment]
Also useful comments to be found in http://dev.simplemachines.org/mantis/view.php?id=4346

**Comment by FearThe1337** [comment]
Just going to update this with newer browser versions tested with the current git version of SMF2.1.

| Browser | Quick reply | Quick reply w/post | Create Post | Create post w/post |
| --- | --- | --- | --- | --- |
| Chrome 43.0.2357.65 | Forgets | Remembers | Forgets | Remembers |
| Firefox 38.0 | Forgets | Forgets | Forgets | Forgets |
| Internet explorer 11.0.9600.17801 | OK | OK | OK | OK |
- w/post = With a post request, then going back. e.g. submit post or preview.

**Comment by jdarwood007** [comment]
This isn't fixable in SMF.  This is a bug in SCEditor.  I've submitted a PR to SCeditor for this to be fixed in https://github.com/samclarke/SCEditor/pull/701

**Comment by Arantor** [comment]
Eh? This was a problem dating back to 2.0 RC2 that won't necessarily be just related to SCEditor.

**Comment by jdarwood007** [comment]
The SCEditor is now in place though so not relevant for 2.1.  This could have been solved with the original editor as well by handling similar to what needs done in SCEditor.   SCEditor has a action that on loading will pull from the textarea and then parse to rich content in a html iframe (just like how ours worked).  All that needs to be done for the original editor would be to have us prior to unload of the page is capture the iframe and send it back to plain text/bbc and then dump it into the textarea.

**Comment by Arantor** [comment]
Except this routinely happened on quick reply as well - which had nothing to do with the rich editor in 2.0.

Not sure this is solely the province of SCEditor here.

**Comment by jdarwood007** [comment]
The QuickReply is also SCEditor now in 2.1.  If I disable javascript, it works fine as the browser handles it.

This is all based on whether the browser handles remembering entered content or not when you go back.  If the browser doesn't support it, neither should we.  It would be possible for us to remember it by using local storage, but that is outside of the scope of this issue I believe.
