### ISSUE TITLE
PM rules doesn't handle sender properly

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1212]
As per http://www.simplemachines.org/community/index.php?topic=477217.0

If creating a rule and the rule is for a sender that doesn't exist, the criteria will be deleted without any warning to the user (except if it's the only criteria, in which case "A rule must have at least one criteria and one action set." will be the error thrown at the user)

This might also be worth implementing the auto suggest if it's not too much of a pain to make happen.

**Comment by snrj** [comment]
hi
pm \n no url
![pm](https://f.cloud.github.com/assets/1269557/1945976/c24bee58-7fe1-11e3-95b8-637b5cbb1c78.jpg)

**Comment by Arantor** [comment]
Please create a new issue. Your problem is totally unrelated to this bug. I would prefer you to create new issues rather than just replying to an existing one, because now it confuses things because now I can't mark this issue solved until I've solved BOTH problems. (which really makes my job more difficult than it already is)

It's also not like I have a split-topic button here.

**Comment by Arantor** [comment]
Before we get derailed any further, whatever language you're using has not been updated properly. Check the entry for $txt['show_personal_messages'] in the index.{language}.php file for your language. The master English version has < br > tags as it should, yours does not.

EDIT to add: Your version is also very clearly out of date in other respects. The copyright still says 2013, and that means the index file hasn't been updated with the changes I made to the copyright.

**Comment by snrj** [comment]
thanks 
recovered
