### ISSUE TITLE
Upgrader Progress Bars Layout Issues

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1214]
Came across two layout issues when testing another bug, upgraded from 1.1.9 and 2.0.6 to 2.1 alpha and came across these two.

1) The step progress bar doesn't seem to move, looks to just stay at 0.2%

2) When there is a third/sub-progress bar it is partially hidden behind the step progress bar and overflows over the progress steps on the right of the screen.
Screen shot at the below link:
http://i39.tinypic.com/2mrxtad.png

**Comment by Xarcell** [comment]
I haven't tested this recently, but when 2.1 alpha first came out I seen this bug when upgrading from 2.0 - 2.1. I was merely testing fresh installed on my localhost(I did this about 4 times give or take). There were even moments when no bars appeared at all, but the percentage number was there.

**Comment by Arantor** [comment]
Since the other issue is merged, this should be able to be closed now.

**Comment by ghost** [comment]
There is still an issue with the step progress bar percentage which isn't resolved, I didn't have time to look at it earlier, will try later but it's still stuck at 0.2% when upgrading from 1.1.x or 2.0.x.
