### ISSUE TITLE
Void Elements - Removing ending slash

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1215]
Topic to discuss removing the unnecessary ending slash on void elements as 2.1 is going to be HTML5 compliment. There are between 2000 and 3000 of these instances, it wont have any real performance impact but it will remove between 2000 - 3000 unnecessary characters from the codebase.

**Comment by Arantor** [comment]
Better than that, it's actually 4000-6000 unnecessary characters since convention is to put a space in front of them!

Though, what's to discuss? It's going to get done :tongue:

**Comment by ghost** [comment]
Great, didn't know it was on the list :+1:

**Comment by Arantor** [comment]
It's on my mental list but a reminder is always good. :)

**Comment by Oldiesmann** [comment]
This should be good now, but I'll leave it open in case any issues with my PR or this thing in general pop up.

**Comment by ghost** [comment]
Haven't come across any issues to date since this PR was merged.

**Comment by Arantor** [comment]
We've seen a few but honestly at this point we should be closing the issue and resolving any as we come across them.
