### ISSUE TITLE
code inside table

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1217]
Mantis references: http://dev.simplemachines.org/mantis/view.php?id=3553 and http://dev.simplemachines.org/mantis/view.php?id=4431

```
[table]
[tr]
[td][code]1[/code][/td]
[td][code]2[/code][/td]
[td][code]3[/code][/td]
[/tr]
[/table]
```

Becomes

```
[table]
[tr]
[td][/td][/tr][/table][code]1[/code]
[code]2[/code]
[code]3[/code]
```

**Comment by live627** [comment]
preparsecode() [lines 184 - 234](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Post.php#L184)
