### ISSUE TITLE
Force line endings

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#122]
Since this has popped up a few times with some of the contributors, we need to investigate setting this up.

https://help.github.com/articles/dealing-with-line-endings

This seems simple to setup, we simply add the .gitattributes file with the attributes they mention in the document to force line endings to be correct.

**Comment by emanuele45** [comment]
Ohh...now I got it!
The first time I read it very quickly and didn't pay attention to the "details", so I didn't understand what it was about, but that's indeed wonderful! :D

**Comment by jdarwood007** [comment]
Yes it will be wonderful, it will help ensure that contributors code is sent using the proper line endings.  Which ensures a proper diff file.

**Comment by norv** [comment]
Just to note. All repos should do this, if it isn't already.

**Comment by jdarwood007** [comment]
Can we pull this?  Should still merge because it creates a new git file.

**Comment by Oldiesmann** [comment]
Go for it

**Comment by Arantor** [comment]
Does this need pulling or closing? I've been told separately that the repo does force line endings already...

**Comment by MissAllSunday** [comment]
It doesn't hurt to add this so I went ahead and cherrypicked his commit to be able to pull it.
