### ISSUE TITLE
Cannot create new topic for existing event

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1224]
If an event was created, but without a linked topic, there's no way to do it (not with either topic->link to calendar or from the modify calendar event screen)

**Comment by Oldiesmann** [comment]
I looked into this a bit further and unfortunately it's not an easy fix.

When you get to Post(), it assumes that if you're editing an event, you're editing one already linked to a topic:

``` php
        // Editing an event?  (but NOT previewing!?)
        if (empty($context['event']['new']) && !isset($_REQUEST['subject']))
        {
            // If the user doesn't have permission to edit the post in this topic, redirect them.
            if ((empty($id_member_poster) || $id_member_poster != $user_info['id'] || !allowedTo('modify_own')) && !allowedTo('modify_any'))
```
