### ISSUE TITLE
Error log does not open file in some cases.

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#1226]
When File is:
File: C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/projects/smf21/Sources/Load.php(83) : runtime-created function

When you click that link, it pops up a box saying:
Sorry but the file specified could not be opened: C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/projects/smf21/Sources/Load.php(83) : runtime-created function

**Comment by Arantor** [comment]
Not using latest files?

**Comment by NanoSector** [comment]
Nope.
