### ISSUE TITLE
Preg_replace and /e

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#1227]
Looks like the errors are still haunting 2.1.

8192: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead
File: C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/projects/smf21/Sources/Load.php(83) : runtime-created function
Line: 3

8192: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead
File: C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/projects/smf21/Sources/Subs.php
Line: 2485

8192: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead
File: C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/projects/smf21/Sources/Class-Package.php
Line: 590

**Comment by Arantor** [comment]
Load.php line 83 as per your error does not have a ~e instruction. Suggest you are using old files.

**Comment by NanoSector** [comment]
Apparently, yes. Got the wrong package I suppose.
