### ISSUE TITLE
PMs: Cosmetic issues

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#1229]
![2014-01-18 16_11_13-personal messages index](https://f.cloud.github.com/assets/1280380/1947403/dfd86872-8052-11e3-9ef6-fd8ddbe2aeec.png)
![2014-01-18 16_12_26-personal messages index](https://f.cloud.github.com/assets/1280380/1947405/fe3a7530-8052-11e3-8e11-08f5e9aa5671.png)
(doesn't seem to switch between windowbg and windowbg2)

**Comment by Arantor** [comment]
Looks like you've got old files there again.

**Comment by NanoSector** [comment]
Yep.
