### ISSUE TITLE
Calendar: Parse error

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#1230]
Parse error: syntax error, unexpected '=', expecting ')' in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\smf21\Sources\Subs-Calendar.php on line 920

``` php
    $event_columns = array(
        'start_date' = '{date:start_date}',
        'end_date' = '{date:end_date}',
        'title' = 'SUBSTRING({string:title}, 1, 60)',
        'id_board' = '{int:id_board}',
        'id_topic' = '{int:id_topic}'
    );
```

Wasn't this fixed before?

**Comment by Arantor** [comment]
Was fixed in https://github.com/SimpleMachines/SMF2.1/commit/7865e9a7c25eb77816f87f7d7db0b0359ade7792

**Comment by NanoSector** [comment]
Dafuq, I just downloaded and installed 2.1... Anyway, closing this then.
