### ISSUE TITLE
Hooks: Integration Hooks Control always says a hook is not found, even if it does exist.

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#1231]
![2014-01-18 16_21_22-integration hooks](https://f.cloud.github.com/assets/1280380/1947420/42aec756-8054-11e3-8e4a-e954125e0ef0.png)

**Comment by MissAllSunday** [comment]
Are you using functions or methods?

**Comment by NanoSector** [comment]
Bug not present in the later files; I was using old files.
