### ISSUE TITLE
Core Features: Drafts icon is not as wide as the other icons

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#1232]
This makes the text look misaligned.
![2014-01-18 16_22_28-core features](https://f.cloud.github.com/assets/1280380/1947423/6ed54f26-8054-11e3-9b28-b52d4733a567.png)

**Comment by Arantor** [comment]
Uh, core features page has been removed for ages?

**Comment by NanoSector** [comment]
Yeap I was using old files.
