### ISSUE TITLE
Package manager: Database error upon installing a package

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#1237]
Database Error
Table 'smf21.smf_log_actions' doesn't exist
File: C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\smf21\Sources\Logging.php
Line: 537

**Comment by Arantor** [comment]
That would be because of bug #1235

**Comment by NanoSector** [comment]
Oh, yeah I forgot that the table wasn't created lol. So close this and handle it from the other?

**Comment by Arantor** [comment]
Nah, grab the latest files, retest that the installer doesn't fart an error and this should be fixed as well.

**Comment by Arantor** [comment]
As #1235 is fixed, this should also be fixed now.
