### ISSUE TITLE
Package manager: Errors upon installing package

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#1241]
```
file_exists() expects parameter 1 to be a valid path, string given
File: /Sources/Subs-Package.php
Line: 185
```

and

```
is_dir() expects parameter 1 to be a valid path, string given
File: /Sources/Subs-Package.php
Line: 1720
```

**Comment by Oldiesmann** [comment]
What values were passed to those functions?

**Comment by Arantor** [comment]
Can't reproduce. Would love to know what was going on with this.

**Comment by Xarcell** [comment]
I'm guessing this is a local install. Are you using the IP "127.0.0.1" or "Localhost"?

**Comment by Oldiesmann** [comment]
That shouldn't matter at all because the directories should be actual paths not URLs.

**Comment by NanoSector** [comment]
Local install indeed, and trying to install http://custom.simplemachines.org/mods/index.php?mod=3481

**Comment by Oldiesmann** [comment]
It would be really helpful to know what values were passed to those functions. What does this give you in the error log?

Subs-Package.php

Find
`if (!file_exists($destination . '/' . $current['filename']))`

Add before that
`log_error($current['filename'], 'debug');`

Find
`if (is_dir($strPath))`

Add before that
`log_error($strPath, 'debug');`

**Comment by NanoSector** [comment]
I'll take a look if I have time later tonight.

**Comment by Oldiesmann** [comment]
Note that there's a typo in the above comment. It should be `log_error($destination . '/' . $current['filename'], 'debug');`, not `log_error($current['filename'], 'debug');`

**Comment by Arantor** [comment]
I had totally forgotten about the debug error type. Also note that you can edit your comments.

**Comment by Oldiesmann** [comment]
You can actually throw anything in there as the error type. If there's no text string defined for it, SMF just uses whatever was passed as the type. I also know I can edit my comments. I just wasn't sure if he'd see it if I edited it.

**Comment by Arantor** [comment]
Actually, no, you can't. The type is validated and if not known, will be converted to 'general'.

**Comment by Arantor** [comment]
Given the package that caused this, I cannot reproduce the issue in question. I'm wondering if there's file permission issues on Yoshi's machine. Though I definitely get the feeling that we should be realpath()'ing everything anyway.

In Yoshi's case it's trying to check whether C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\smf21/Packages/temp/files// - and since it's inside Program Files (x86) permissions may well be troublesome due to UAC.

**Comment by NanoSector** [comment]
Happens again but now in C:\wamp. Welp.

I'll log_error it later tonight.
