### ISSUE TITLE
Top level PM/Alert box size problem on long text

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1243]
I knew it! :)
![capture](https://f.cloud.github.com/assets/1669995/1948520/e6822c50-8096-11e3-8dff-b5566d905153.PNG)

**Comment by Oldiesmann** [comment]
What's the problem here? The top link running partially over the link below it?

**Comment by Arantor** [comment]
It's not 'partially running over', there's two chunks of text, one left-aligned, one right-aligned. In English it all fits on one line, but in Turkish it doesn't.

Been trying to decide how best to deal with this, perhaps switching some to icons (but that has issues in itself if not careful)

**Comment by illori** [comment]
why not increase the width of the box a bit? although that may not fix the issue for all languages

**Comment by Arantor** [comment]
Aside from the fact it might not fix it for all languages, all 3 popup menus share the same size - 25em - so changing one would potentially affect the others and if not, it's not stylistically consistent :(

**Comment by Xarcell** [comment]
After some thought, I think icons may be the way to go. You never know if any mods will add to that as well, and icons would save more space. I hate seeing more icons, but this is a perfect example of why we use them to begin with. I dunno, what do you think?

**Comment by Arantor** [comment]
I don't expect mods to really add to that area, partly because there's not _that_ much you can do, partly because there's no easy facility for it (back to file edits if you did)

The one problem I'm thinking with our icons is that we will need to space the icons out if we want to have any hope of mobile use.

**Comment by illori** [comment]
what type of icon could you really use in this area that people will understand what it represents?

**Comment by Arantor** [comment]
Pretty much the same as all the others; envelope with a plus for sending, notepad with pencil for drafts etc.

**Comment by illori** [comment]
and would we then need to do the same for the alerts area? i am not sure that will work out too well there.

**Comment by Arantor** [comment]
The alerts area needs more work anyway as it currently doesn't work properly because it's on my things-to-finish-writing list.
