### ISSUE TITLE
No way to edit/delete moderator comments

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1248]
If you comment on a report, there's no way to edit your own comments, and no way to delete them either.

I'm thinking normal moderators should be able to edit/delete their own comments (only), while admins should be able to edit/delete any comments. Very reluctant to add permissions to this more than necessary and more than own/any in this fashion seems overkill.

**Comment by Oldiesmann** [comment]
That sounds good to me, and I agree on the permissions thing.

**Comment by Xarcell** [comment]
I concur. Keep it simple.
