### ISSUE TITLE
Only 29 days available when posting a new calendar event

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1250]
When posting a new events on the calendar, regardless of what month or year you select, there is only 29 days available on the day dropdown list so a user can never post an events for the 30 or 31 is needs be.
http://i40.tinypic.com/2088fft.png

This is due to the url that has been clicked on so if I follow the post event from Feb then it will only ever allow a max of 28/29 days depending on leap year etc. regardless if I change the month in the dropdown list, The day list is populated based off the url.

Might be an idea that if the month is changed that the day dropdown is regenerated instead of being based off the url on page load.

**Comment by Arantor** [comment]
It should be, there is a whole raft of JS there for that purpose...

**Comment by Arantor** [comment]
Cannot reproduce in Chrome 33 - changing the month and year, regardless of month I start from - works consistently.

**Comment by XinYenFon** [comment]
Works for me too FF26.0 - IE11.0.2 - metroIE but also all months has 31 days. SMF currently is not correcting Feb to 28/29 days - April 30 days etc...

**Comment by Arantor** [comment]
Check for JavaScript errors.

**Comment by ghost** [comment]
I'm using FF 26 and this is in the browser console.

```
Timestamp: 20/01/2014 15:32:51
Error: TypeError: yearElement is null
Source File: /Themes/default/scripts/script.js?alph21
Line: 1552
```

**Comment by Arantor** [comment]
That's... unexpected.

**Comment by ghost** [comment]
Getting the same error when changing the year drop down also, most likely expected as the error is related to the yearElement. Also getting the error in IE9.

```
SCRIPT5007: Unable to get value of the property 'options': object is null or undefined 
script.js?alph21, line 1552 character 2
```
