### ISSUE TITLE
show_member_bar

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1252]
`INSERT INTO {$db_prefix}themes (id_theme, variable, value) VALUES (1, 'show_member_bar', '1');`

`'show_member_bar' => @$GLOBALS['Show_MemberBar'],` [upgrade.php and install sql's]

this seems to be a left over from 1.1\* and not an actual function in 2.1

**Comment by illori** [comment]
`'show_member_bar' => @$GLOBALS['Show_MemberBar'],` in upgrade.php is left behind... is that related?

**Comment by Arantor** [comment]
It might even be intentional.
