### ISSUE TITLE
Subscription limits

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1274]
As discussed in http://www.simplemachines.org/community/index.php?topic=509084.0

PayPal does not accept 365 days as a subscription length. As per https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/#id08A6HI00JQU

It's complaining about an invalid a3/p3/t3 and that's correct:

> D – for days; allowable range for p3 is 1 to 90
> W – for weeks; allowable range for p3 is 1 to 52
> M – for months; allowable range for p3 is 1 to 24
> Y – for years; allowable range for p3 is 1 to 5

So yeah, 365 days won't be valid. I'm thinking we should probably restrict these values in SMF because even though there's other payment processors, the same restrictions probably apply.

**Comment by Oldiesmann** [comment]
Sounds good to me.
