### ISSUE TITLE
Time To Update Genders

### ISSUE THREAD

**Issue by Xarcell** [SimpleMachines/SMF#1275]
I think it's about time we update our gender selection. Not everyone is "Male" or "Female". Even countries are starting to officially recognize a third gender. Here are a few:

Germany: http://www.theatlantic.com/health/archive/2013/11/germany-has-an-official-third-gender/281254/

Nepal: http://www.undp.org/content/undp/en/home/ourwork/hiv-aids/successstories/Nepal_third_gender_census_recognition/

Bangladesh: http://www.pinknews.co.uk/2013/11/12/bangladesh-third-gender-hijra-to-be-recognised-in-official-documents/

Australia: http://www.dailymail.co.uk/news/article-2037662/Third-sex-official-Australian-passports-gender-options--male-female-x.html

India: http://thesocietypages.org/sexuality/2009/11/13/india-officially-recognizes-third-sexgender/

I'm not sure of which term to use as a third gender, but I would assume it would be "Intersex": http://en.wikipedia.org/wiki/Intersex , since this is the most commonly used term officially.

**Comment by Arantor** [comment]
We have already been through this before. We are not updating this in the core software as previously stated because while some countries freely accept these terms, a LOT of people will be put off using the software because they find it offensive.

**Comment by Xarcell** [comment]
A LOT of people eh? Like who? What about those who are intersex? Shouldn't they be offended? We're not talking about TRANSGENDER here, we are talking about people who are BORN with with both sexual organs/parts. That's not something can be helped, nor is it even considered sacrilegious.

**Comment by Arantor** [comment]
I'm not going to get into this with you. We already decided that we were not changing it in 2.1, period.

**Comment by PhuriousGeorge** [comment]
Make a mod if you want it. Not meant to offend anyone, but If it got added in, I'd be modding it out personally.

**Comment by Xarcell** [comment]
To say it won't be added to SMF 2.1 because of compatibility issues I can accept. Even to say because no one has time, or it's not a top priority I can accept, but to say it won't be added because it's offensive, is offensive to me. Why would you force someone to choose a gender, when by birth they are neither/both?

Come on, help me with my reasoning here. I'm open minded. Why would it be offensive, and who would it offend?

**Comment by MissAllSunday** [comment]
And this is why we truly need a genderless avatar, no matter what we chose we will be steeping on someone else toes, as in, bad if we stay with only 2 genders, bad if we add more, the only safe way is not to get into this kinds of arguments.

I'll go as far as removing the gender feature altogether but I understand we must keep it for compatibility purposes. So, keep the genders as they are right now, add a genderless avatar and make mods for extra genders (there is one already available) and another mod for adding custom gender default avatars.
