### ISSUE TITLE
"Ban group"

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#1278]
In SMF2.1 two new strings mention "ban group". These are the only two instances of this expression in the whole translation.

I'm just wondering why "group" is used there. I can't see an option anywhere to set up a "ban group". I presume it's referring to the same thing as "Add new ban". Well, I was thinking of not including "group" in the translation as it seems confusing - everywhere else we just call them "bans". Or have I misunderstood something?

These are the two strings:
1. (errors.language.php) $txt['ban_group_id_empty'] = 'Ban group id missing';
2. (admin.language.php) $txt['ban_errors_detected'] = 'The following error or errors occurred while saving or editing the ban group or trigger';

I reported the same thing at the SMF forum: http://www.simplemachines.org/community/index.php?topic=517430.msg3660483#msg3660483

**Comment by illori** [comment]
if you really want to report issues, it would help to post the issue completely so even those not on the team can view and possibly comment on the issue. [or even make a PR to fix the issue]

**Comment by ChainyEO** [comment]
I've updated the first post to include all the info.

**Comment by illori** [comment]
and the same for #1280 ?
