### ISSUE TITLE
ManagePermissions.php, $txt['permissions_post_moderation_desc']

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#1280]
ManagePermissions.php, $txt['permissions_post_moderation_desc']:

> **Post Moderation is the situation where posts are "moderated"**, where the **author** and the moderation team can view posts and decide whether to permit them to be visible to other users or not. From this page you can easily change which groups have their posts moderated for a particular permissions profile. 
- The first sentence sounds a bit odd, like saying a blue house is blue. 
- I'm not too sure about the mention of 'author'.

How about:

> From this page you can easily change which groups in a particular permissions profile require the approval of moderators before their posts will appear in the forum.

I first reported this here: http://www.simplemachines.org/community/index.php?topic=497767.msg3633405#msg3633405

**Comment by ChainyEO** [comment]
I've updated the first post here to include all the info.

**Comment by Arantor** [comment]
Several things present.
1. People may not actually know what post moderation is.
2. The author can see their own posts that are moderated.
3. Post moderation is indeed about viewing posts and deciding upon them being visible to others; the more brief version implies the user actually knows in advance what post moderation means and implies that the user will not be able to see their own posts.

**Comment by Arantor** [comment]
I've changed the wording in the next commit, see if that works better for you.
