### ISSUE TITLE
Ability to see moderation reports about a user

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1286]
Ability to see moderation reports made by a user, and to see reports made about the posts of a user - to see serial complainants or troublemakers.

Not sure if this should be in the moderation center or the profile area of a user though.

**Comment by Oldiesmann** [comment]
How easy would it be to just add filtering capabilities to the mod reports instead? That might be a better way to handle this if it's not too much work.

**Comment by Arantor** [comment]
The problem with that is how it's already handled - you're presented with a mashup of open and disregarded reports and closed reports are elsewhere... there's no good way to present that currently.

Besides if a user makes a lot of reports you might want to just have a simple list in their profile...

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
