### ISSUE TITLE
Unapproved post issues - collection of issues that need dealing with

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1292]
- [x] Unapproved posts don't generate notifications of replies
- [ ] They're not in the unread column on the board index if they are the most recent reply
- [ ] They do not trigger the board to be marked unread
- [ ] They're not in the user's profile
- [ ] Topics don't show as new under some circumstances
- [ ] Recent posts does not always take it into account either

Refs:
http://dev.simplemachines.org/mantis/view.php?id=4964
http://dev.simplemachines.org/mantis/view.php?id=4426 (which refers to http://www.simplemachines.org/community/index.php?topic=366450.0 as well)
http://www.simplemachines.org/community/index.php?topic=482262.0

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.

**Comment by frandominguezl** [comment]
Was this really necessary, Arantor?

**Comment by Arantor** [comment]
Yes, see the discussion on old issues.
