### ISSUE TITLE
Make sure mime_type is populated correctly

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1294]
When running the upgrader, make sure all mime_type entries are filled because this can have some issues for maintenance as well as the nosniff header.

Also, if a non image has a width or height specified, remove them.

**Comment by AaronVanGeffen** [comment]
Using `getimagesize` won't find a mime-type for non-images. I'm not sure what the current minimum PHP version for SMF 2.1 is, but perhaps the `finfo_` functions are worth considering here? They're available in 5.3.0+.

```
    $finfo = finfo_open(FILEINFO_MIME_TYPE);
    $mimetype = finfo_file($finfo, $destination);
    finfo_close($finfo);
```

**Comment by Arantor** [comment]
I was just going off the mainline code that gets MIME types, like application/shockwave, thought that gets truncated... Thanks though, I'll investigate our options.

**Comment by Arantor** [comment]
Though, thinking about it it isn't "as bad" a problem as it might seem. Images NEED their MIME type because lack of it screws up use of the no sniff header. Other files don't need it so much, and since it's cropped to 20 characters, MIME type for other files may not be saved properly rendering them useless >_<

**Comment by Arantor** [comment]
So I looked up what we did, and no wonder I didn't do anything else beyond this... it's primarily taken from what the browser provides.

finfo_open isn't really an option because we're still at 5.1+ unfortunately. But the only places the MIME type is actually used for _sending_ is when it's for an image, because if it's sending an attachment otherwise, it's sent as application/octetstream (or application/octet-stream)

Beginning to think this isn't actually necessary beyond what is done thus far... hmm.

**Comment by Oldiesmann** [comment]
If you don't mind using deprecated functions, you can use mime_content_type on older versions of PHP. http://www.php.net/mime_content_type

**Comment by Arantor** [comment]
Well... on the environments where that's an issue, we'd have finfo anyway. But I'm actually thinking there's no reason to hold MIME types for non image files, since I don't see anywhere we use that for non images.

**Comment by Arantor** [comment]
Yeah, I realised that there really is no need to fix up _all_ the MIME types, only images where we actually _need_ that information to be available.
