### ISSUE TITLE
Missing index on sessions table - last_update column

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1305]
As discussed on http://www.simplemachines.org/community/index.php?topic=461154.0

Adding an index may help performance - or may not - on systems with lower numbers of online users, but when getting to 1k users online or more, probably should be using memcache anyway so this may not need anything doing.

Needs benchmarking really on both lower and middle sized forums to make a judgement.

**Comment by Xarcell** [comment]
Is there any kind of toolset that I can use for bench-marking SMF? Or does it just have to be done the hard way?

**Comment by Arantor** [comment]
There is no toolset that would really help you with this one.

**Comment by Oldiesmann** [comment]
What's the best way to test this? I'm not familiar with benchmarking, so I'm not sure if we should just add this and ask users for feedback, or if there's a better way to test this.

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
