### ISSUE TITLE
Unable to change theme for user if 'allow users to choose themes' is disabled

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1306]
Originally from http://www.simplemachines.org/community/index.php?topic=348480.0 with some back and forth.

Primary argument: other things are 'don't let the user choose but allow admin to override', e.g. display name, custom title.

So this would make it consistent with that behaviour (i.e. only enforce the permission when allowing/not allowing the user to pick a theme in their profile)

Alternatively, make it clear that the option means, irrevocably, 'all users will see the theme picked in admin' and disallow choosing.

Behaviour does need to change, both of these options are valid changes, I'm leaning towards the first one (which would solve the bug report and be consistent with the behaviour of other systems)

**Comment by Xarcell** [comment]
I think consistency between behavior with other systems takes a priority here. IMO of course.

**Comment by Oldiesmann** [comment]
So admins should be able to choose themes for users even if you don't allow users to change their themes? Sounds good to me.

**Comment by Arantor** [comment]
Well, we do for other things, just not themes. Right now it just says 'if users can't pick their own themes, go with the default'

**Comment by PhuriousGeorge** [comment]
I was not aware this was the current behavior. Do like the suggested change.
