### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1319]
I think one of the best small enchantments for this version is Help - T&R (added) moved to footer, i believe we can do the same for Print button. As much as i think "Social Share" place can be better for SMF 2.1 but that seems not possible or not likely be used by our users.

**Comment by Arantor** [comment]
Printable view only works for topics, would be unintuitive to have it in the footer when it applies to only a limited subset of pages.

**Comment by illori** [comment]
how about moving it to the line with the moderation buttons below the messages but above the quick reply?

**Comment by Arantor** [comment]
Because it's a user-level operation and belongs with the other user-level options rather than being part of the moderation-level operations.

**Comment by XinYenFon** [comment]
If there is not intention to add "social share" place like IP.Board, please close this issue :) I understand the reasons not to make print on footer :paw_prints:

**Comment by Xarcell** [comment]
@Antes by social share you mean with Facebook, Google, Twitter, etc? If so, I personally hate that, because it slows down page load significantly. Things like this are better off as a mod.

**Comment by XinYenFon** [comment]
@Xarcell yes, and not the way you think... I didn't suggest the like box type things but more like buttons and static links (sharer.php Facebook etc...)

**Comment by Oldiesmann** [comment]
I've never seen like/tweet/+1 buttons "slow down the page load significantly". They're used on millions of sites around the world, so it can't be that bad.

**Comment by Xarcell** [comment]
@Oldiesmann you must be using a desktop with broadband. Even so, on desktop/broadband I've seen plusone.js hang so many times it's not funny.

**Comment by PhuriousGeorge** [comment]
Depends on the definition of "hang". I've noticed a very minimal amount of additional loading time required, but it doesn't hinder being able to access the content at all unless the few milliseconds waiting for the additional buttons to load is too distracting.

**Comment by Arantor** [comment]
Solution: we add in a two click operation. First click is on a static image that we serve ourselves and loads the real YouTwitPinFaceGoogBookTube icons, whatever we have (yes, we need that many for all the different services out there :tongue: ), and then the second click to do whatever. Aside from preserving speed it also has the privacy implication already dealt with a la http://www.zdnet.com/blog/facebook/german-website-creates-two-click-like-button-facebook-not-amused/3247

**Comment by XinYenFon** [comment]
"Enable/Disable Social Share" as a setting on "Forum Profile". ? :paw_prints:

**Comment by Arantor** [comment]
That doesn't solve the problems outlined of causing slow speed while still having the functionality available.
