### ISSUE TITLE
$txt['package_will_fail_warning'] (Accusative problem?)

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#1324]
Just wondering whether the use of **%1$s** might make it difficult for translators. Some languages use the form "continue sth" rather than "continue with sth", so the accusative is needed. This might well mean a different grammatical form of the word. In the case of Esperanto, I can just add "n" after **%1$s** and the problem is solved. Not so sure about other languages, though.

> At least one error was encountered during a test **%1$s** of this package.<br>It is <strong>strongly</strong> recommended that you do not continue with **%1$s** unless you know what you are doing, and have made a backup very recently.<br><br>This error may be caused by a conflict between the package you're trying to install and another package you have already installed, an error in the package, a package which requires another package that you have not installed yet, or a package designed for another version of SMF.

**Comment by Arantor** [comment]
I really hate stuff like this. As far as I'm concerned the only proper way to solve this string is to have two of them.

**Comment by ChainyEO** [comment]
Come to think of it, I suppose one way of getting round this particular problem would be to use the passive form in a translation:

> It is strongly recommended that the **%1$s** not be continued unless...

**Comment by ChainyEO** [comment]
Just out of interest, would the **%1$s** still work if I added "n" right on the end of it, eg. **%1$sn**, or would that cause it to fail?

**Comment by Arantor** [comment]
No, it would work fine. However injecting strings like that should really only be done unless you specifically cannot do it any other way precisely because of the issue you're raising.

**Comment by XinYenFon** [comment]
This is language specific so please close this issue and continue discussing this type of issues on our Localization board with our translators. We can't fix the problems language to language but do general fixes on strings.

**Comment by ChainyEO** [comment]
@Antes 
This isn't a case of trying to fix things language to language. It's a question of making it suitable for translation in general.

I opened a thread about this in the Localization Board on 30th Jan (http://www.simplemachines.org/community/index.php?topic=517802.msg3663460#msg3663460)

**Comment by NanoSector** [comment]
So what exactly needs to happen here?

**Comment by jdarwood007** [comment]
@d3vcho, 
```
sprintf($txt['package_will_fail_warning'], $txt['package_' . ($context['uninstalling'] ? 'uninstall' : 'install')]),

$txt['package_will_fail_warning'] = 'At least one error was encountered during a test %1$s of this package.<br>It is <strong>strongly</strong> recommended that you do not continue with %1$s unless you know what you are doing, and have made a backup very recently.<br><br>This error may be caused by a conflict between the package you\'re trying to install and another package you have already installed, an error in the package, a package which requires another package that you have not installed yet, or a package designed for another version of SMF.';
$txt['package_install'] = 'installation';
$txt['package_uninstall'] = 'removal';
````

We can fix this by either leaving this as is.  Or by splitting this into 2 strings to handle this better.

Thoughts?

**Comment by frandominguezl** [comment]
@jdarwood007 I'd say leave it as it is, but I have no problems on splitting it into 2 strings.

**Comment by jdarwood007** [comment]
Going to close this.  This is best fixed in a future release of SMF where we can handle languages better by using some sort of nth control.  Don't think we can make this in the release without breaking things or needing lots of testing.
