### ISSUE TITLE
$modSettings['custom_avatar_dir'] undefined

### ISSUE THREAD

**Issue by jasonclemons** [SimpleMachines/SMF#1327]
[Profile-Modify.php line 2954](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Profile-Modify.php#L2954) `$modSettings['custom_avatar_dir']` is not defined by default, and will thrown an undefined error when attempting to modify a forum profile. I didn't submit a fix because I don't know how you want this handled, whether it be by defining the variable on install/upgrade, or by defining a default in the code.

A simple `empty()` check will prevent the error, but will not allow the avatar to save.

**Comment by Arantor** [comment]
Eh? It really should be in the installer now... because saving to custom folder is very explicitly the default behaviour (hence /custom_avatar folder)

**Comment by jasonclemons** [comment]
I see it in the installer, and in the upgrader. However, it's still not being set for some reason. I couldn't reproduce it on a vanilla install, but I could on an upgrade from 2.0 using last nights build.

**Comment by Oldiesmann** [comment]
Looks like a bug, as there's no call to updateSettings to fix it if it isn't already set.
