### ISSUE TITLE
Request Membergroup Alert

### ISSUE THREAD

**Issue by Xarcell** [SimpleMachines/SMF#1339]
I noticed that when a user requests to join a membergroup, the moderator is not alerted. I'm not sure if this was intentional or not, if so I'll just close the topic. Although, I'll have to admit I think they should get some kind of notification of such request. The user might not check the moderation page often, if he is just a moderator of the group only.

**Comment by Arantor** [comment]
1. They have to be a group moderator for that group, 2. They have to have turned on alerts, 3. You need to be running a build from the last week or so where cron.php actually gets called, 4. It is possible there is a bug.

**Comment by Xarcell** [comment]
The build I was running, I downloaded last night. I have all alerts turned on for the group moderator. Although, in the alert permission via profile, it doesn't show anything about showing alerts for membergroup requests. I dunno if this type alert was supposed to be included in the reported posts alert or not. If so, it should be added to the description at least.

Anyway, it's not throwing any kind of alert when a user requests membership.

Also, I really like the alert permissions BTW. Nice job.

**Comment by Oldiesmann** [comment]
There should be a "Someone requests to join a group that I moderate" option in a "Members" section of the notification settings for the group moderator. It shows up fine for me when I make my "regular user" test account the moderator of a requestable group (though I haven't tested with other group types, but the code to determine whether or not that option shows up doesn't filter by group type - it just checks to see if they can "manage_membergroups" or if they're a moderator of at least one group).

**Comment by Xarcell** [comment]
Here is my process of how the issue is created.

1.| As admin, I create a "Test 1" regular user, and make it  the moderator of a requestable membergroup. 
2.| Then log out of admin, login as "Test 1", and check ALL alert permissions via profile.
3.| I logout of "Test 1" and login back in again as the admin.
4.| I create the user "Test 2" regular user.
5.| I logout of admin and login as "Test 2".
6.| I go to profile > group membership > request membership to the requestable membergroup.
7.| I logout "Test 2" and login back in again as "Test 1". There are no alerts that "Test 2" requested to join a membergroup.

**Comment by Oldiesmann** [comment]
Works fine on my test board...
![alert](https://f.cloud.github.com/assets/89023/2058202/d0a70f4a-8b63-11e3-8e37-a77d9ea8acfb.png)

In your comment above though you said it didn't even show any option for receiving alerts when someone requested to join a group in the profile.

**Comment by Xarcell** [comment]
When you receive a PM there is an indication beside "My Messages", either a 1, 2, 3, or whatever. For alerts, there are no indications.

![screenshot_smf-alerts-indication](https://f.cloud.github.com/assets/6114450/2058512/624cb9ac-8b75-11e3-9534-043b4918f305.jpg)

**Comment by Arantor** [comment]
That is called a bug because the alerts count isn't being updated by the background task like it should be. I'll add that since it wasn't in the original GroupReq-Notify task code.

**Comment by Xarcell** [comment]
I thought it might be, but I know you said you was still working on it. So I don't want to be going around screaming BUG unless I think I'm  sure. Thanks for fixing it.
