### ISSUE TITLE
Cannot Add Visible Boards To Group

### ISSUE THREAD

**Issue by Xarcell** [SimpleMachines/SMF#1341]
Serious Bug

Edit Membergroup > Select Visible Boards > Save = removes all selections.

I noticed this today, using last night's build. If you try to edit a membergroup's visible boards, it un-checks all selections after save. If you add a new board, then the board is selected & viewable by that membergroup. So this problem only happens when you edit the membergroup visible board permissions.

**Comment by Arantor** [comment]
Does the group have manage-boards permission?

**Comment by Xarcell** [comment]
I'm not sure what you mean by that.

As admin, I created a new membergroup with all default settings. Then, I went back changed what boards that membergroup can see/access. It does not save, and removes all previous selections.

When you create the group, and select boards, it saves. When you EDIT the membergroup on what boards it can see that the selected boards do not save.

**Comment by Arantor** [comment]
If that group has the manage-boards permission, things explicitly work differently for it...

**Comment by Xarcell** [comment]
It does not matter what "Group Type" it is. Private, Protected, Requestable, Free, or even Post Based. It does not matter what permissions the membergroup inherits. Unique Permissions, Guests, Regular Members, or Global Moderators. If you edit what boards is visible to that group, they will NOT be able to any ANY boards. No matter if you select "Check All", upon saving, none will be checked.

![screenshot_membergroup-edit](https://f.cloud.github.com/assets/6114450/2061001/cf456e02-8c3b-11e3-8d0a-ae9e5ad820d0.jpg)

**Comment by Arantor** [comment]
And I wasn't talking about that. But permissions DO make a difference, if a group has manage boards, they will never be able to change that anyway...

**Comment by Xarcell** [comment]
I don't know what else to tell you. I've explained this the best I can, and I'm lost on what your trying to explain to me. You say if a group has "manage boards, they will never be able to make that change anyway". 

What are they trying to change? They are not trying to change anything. As the admin I am creating the membergroup, and editing what boards the membergroup can see. When I edit what boards the membergroup can see, after saving they cannot see any.

What does "manage boards" have to do with not being able to see them?

FYI, this is a fresh install, downloaded from the repo this morning.

**Comment by Arantor** [comment]
I was trying to establish whether you had set up manage-boards permission for that group because other things happen with manage boards specifically. If a group has manage boards, they always have access to all boards at all times. I appear to have confused you, that's fine, I won't bother trying to gather relevant details or narrow down the likely course of action with you in future, I'll just spend more time investigating rather than actually trying to make my life more efficient rather than confusing you with relevance.

**Comment by Xarcell** [comment]
@Arantor no need to be a jerk, I'm just trying to help. Your the one not understanding what's happening here. If you read my posts more carefully, it's not an issue of having access, it's an issue of NOT having access. Furthermore, the MAIN issue is that it DOES NOT SAVE CHANGES, and removes all visible boards. As I have explained more than once.

Perhaps I shouldn't bother trying to explain it to you?

**Comment by Xarcell** [comment]
In all seriousness, maybe I should just create a YouTube channel and start making videos. Would that help? No sarcasm intended...
