### ISSUE TITLE
More subscription gateways

### ISSUE THREAD

**Issue by aldobarr** [SimpleMachines/SMF#1349]
If I remember correctly, SMF 2.0 released subscriptions with a promise (was it stated or implied? I don't remember) that more gateways aside from paypal would be released. Since then, not a single one (as far as I know) has been released save for my googlewallet gateway mod that is pending approval.

Aside from providing people with more options to accept multiple payments gateways, loads of people absolutely HATE paypal, myself included, and would rather lose revenue than use paypal. At least, that's how I feel. If SMF is going to actually have a subscription system that implies multi-gateway support, there should be more than a single gateway, and the worst possible one at that.

**Comment by Arantor** [comment]
It wasn't stated or implied. There was merely a 'we'd like to' IIRC. At least two other gateways were at least partially developed, but I don't know the state of either of them right now. I know at least one fork published the files from SMF's SVN repo without permission, though.

There are a lot of hurdles to implementing other gateways, as you've discovered - but a lot of that problem stems out of the fact that the entire subs setup is basically built around how PayPal works anyway...

**Comment by aldobarr** [comment]
It's not really that bad, one simple db edit and a scheduled task was all it took to get the subscription system to work properly with Google Wallet. If the team won't allow more gateways to be included, then it should be renamed to a something that doesn't imply it to be something it's not.

In any case, I'm fine with contributing the google wallet gateway towards 2.1

**Comment by Arantor** [comment]
Well, it is that - but that's the point: the _entire_ processing paradigm that SMF operates under is of paid subscriptions that just notify SMF when a payment has been made, i.e. how PayPal works.

The problem isn't about 'allowing other gateways', never has been, it's been about testing them, ensuring they work and having people to maintain them. It's been hard enough debugging PayPal thus far :( Better to do one thing passably than many things badly, and so on.

If you're really OK with including it in 2.1, please do submit a PR for it (though I'd note, you might as well build your scheduled task into the daily one for paid subs anyway in that situation)

**Comment by aldobarr** [comment]
Google Wallet is a fairly easy system to follow, PayPal is incredibly overly complicated for unknown reasons to me. Maintaining Google Wallet shouldn't be too much of an issue. I'll probably submit a pr later, if you'd like, you can have a look at the api:

https://developers.google.com/wallet/digital/docs/postback

**Comment by aldobarr** [comment]
Oh, also I'm of the opinion that this entire system should be a mod and not a default feature anyway, so another option would be to convert this into a team mod or something of the sort. After all, this is a forum, not an ecommerce script.

**Comment by Arantor** [comment]
Bad idea, judging by the level of maintenance existing team mods get...

**Comment by aldobarr** [comment]
I meant, that my goal isn't to give the team more work and/or make SMF more feature rich _cough_ bloated _cough_ but rather that I don't quite feel the way it's currently implemented is the right way of going about this.

**Comment by Arantor** [comment]
There isn't one universal way that would actually work best. But seriously, look at the mods listed as handled by the team and a quick glance will tell you what will happen if paid subs is hived off. At least if it's in the core, it motivates people to fix stuff when it breaks. Well, that's the theory. Several years of experience kind of dumps on that too but at least someone is trying to fix the issues with it...

**Comment by aldobarr** [comment]
I know there isn't a universal way to integrate a bunch of different apis together, that's fairly obvious I didn't mean I feel the system is done wrong, I meant the way it's gone about, so to speak. I don't like that it's called a subscription system, when it's really a paypal subscription handler at this point. It should either be renamed, or some sort of attempt at adding at least one more gateway should be done, which I'll do when I get some free time as I'm currently working on a fairly big project of my own at the moment.

Hopefully the users will appreciate being offered an alternative, as it's sorely needed in the SMF environment where everyone relying on SMF mods or the core paid subs system is stuck with paypal.

**Comment by Arantor** [comment]
It was always intended to support more, that has never changed. Complaining about the fact it hasn't happened won't change the fact that that's what happened. It needs more people to contribute, not to complain.

**Comment by aldobarr** [comment]
Is that how I'm coming across? I don't think so, I already stated I'd do the pr, as a matter of fact I originally intended to just do the pr and be done with it, but then I decided to start this discussion instead on the off chance that you lot would have wanted a discussion before hand. _shrugs_

In any case, I'm not complaining, I'm stating I think there's an issue, and I'm offering to contribute towards resolving it =/

**Comment by Arantor** [comment]
That is kind of how it's coming across. We got the message the first time... reiterating what you think is wrong with it isn't going to change any of it. The 2CO and Authorize.net gateways were written years ago but never tested enough to be safe enough for use (and the only person who did actually finish 2CO up won't release it anyway and then wonders why we won't let him back on the team... maybe it's because we don't want to encourage this whole mercenary thing he's got going on)
