### ISSUE TITLE
$txt['profile_error_bad_avatar_fail_reencode']

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#1355]
This sentence needs editing a little:

> The image you uploaded was corrupted and the **attempt to restored failed to do so**.

**Comment by Xarcell** [comment]
The image you uploaded was corrupted, and the attempt to restore failed.

That sound better?

**Comment by ChainyEO** [comment]
Is "restore" the correct word? How about "recover"? And I think the sentence needs "it":

> The image you uploaded was corrupted and the attempt to recover **it** failed.

**Comment by Xarcell** [comment]
@ChainyEO that does sound better.

Do a Pull Request
