### ISSUE TITLE
MySQL 5.6 - what needs to be done?

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#1366]
Just leaving this here for discussion of what needs to be done with MySQL 5.6. WHM started offering support for 5.6 yesterday, so we're probably going to be seeing a lot more people using it in the next year or so.

**Comment by Arantor** [comment]
It should be just https://github.com/SimpleMachines/SMF2.1/issues/887

**Comment by Bendolfc** [comment]
I've been running 5.6 since September and not noticed any issues.

**Comment by Arantor** [comment]
Trust me, it does not work properly on 5.6 on either MyISAM or InnoDB without tweaking. You are basically just lucky.

**Comment by Dragooon** [comment]
Bumping this, is everything covered?

**Comment by XinYenFon** [comment]
I'm using mySQL 5.6.x for such long time with SMF 2.1 Alpha builds, no weird activity i seek since @Dragooon 's fixes...

**Comment by Arantor** [comment]
If you're able to create boards and they work as expected and don't randomly rearrange when you add new posts, then it probably works.

**Comment by XinYenFon** [comment]
they don't anymore ^^

**Comment by Dragooon** [comment]
I fixed random board orders a long while ago, closing this for now
