### ISSUE TITLE
Find/repair doesn't do attachments

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1372]
The main find/repair page doesn't actually list what it fixes or doesn't fix, and it certainly doesn't touch attachments. Per http://dev.simplemachines.org/mantis/view.php?id=3626

Grudge sums it up best, though whether it's feasible to do now is anyone's guess:

> Personally, I think this is something best addressed in 2.1. I personally would rewrite the whole repair function in 2.1 and have the repair page start with a load of check boxes like follows:
> Repair Attachments [X]
> Repair Topics [X]
> Repair Logs [X]
> Repair Profiles [X]
> Recount Statistics [X](always checked by default)

**Comment by Oldiesmann** [comment]
It doesn't actually list what it repairs, but if it finds any issues, it will let you know what it found and offer to fix them for you. It probably could be improved some, though I'm not sure if a checklist is the way to do it since the user might not know what's broken. It's a fairly complex process as I recall.

**Comment by Arantor** [comment]
That's kind of the problem though, find/repair doesn't do attachments. You have to go to the attachments area to get _that_ maintenance.

And honestly, there are other advantages to doing it in chunks like this rather than just going gung-ho on all of them.

**Comment by Oldiesmann** [comment]
My main concern was that users might get confused by having so many options, but if we can add something like a helptxt popup for each one that explains what it checks for or what the symptoms of that issue are, that shouldn't be too much of a problem. I definitely agree with moving attachment repair there.

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
