### ISSUE TITLE
Unwatched Topics throws db error on Postgres

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#1373]
I have spent a good 20-30 minutes trying to debug this but haven't been able to figure it out at all.

When I try to unwatch a topic, I get "The database value you're trying to insert does not exist: 0".

After a bunch of digging I managed to track it down, sort of.

This starts with the query in UnwatchTopics in Display.php
It then does its thing and goes through and ends up calling smf_db_quote on line 735 of Subs-Db-postgresql. This runs things through preg_replace_callback on line 246 of Subs-Db-postgresql,php, which calls smf_db_replacement__callback.

When it gets that far, $matches is as follows:

```
Array
(
[0] => {int:0}
[1] => int
[2] => 0
)
```

$values however is this:

```
Array
(
[id_member] => 1
[id_topic] => 1
[id_msg] => 0
[unwatched] => 1
)
```

This causes it to complain because `$values[0]` doesn't exist. However, I cannot for the life of me figure out why this is happening.

**Comment by Oldiesmann** [comment]
This is still an issue as of the latest build. @Dragooon  or @tinoest - either of you have any ideas on this? The same functionality works fine on MySQL.

**Comment by Dragooon** [comment]
I don't have PgSQL to test but try this, in Subs-Db-postgresql.php

Find (around line 677):

```
            if (strpos($type, 'string-') !== false)  
                $actualType = sprintf($columnName . ' = SUBSTRING({string:%1$s}, 1, ' . substr($type, 7) . '), ', $count);  
            else  
                $actualType = sprintf($columnName . ' = {%1$s:%2$s}, ', $type, $count);
```

Replace with:

```
            if (strpos($type, 'string-') !== false)  
                $actualType = sprintf($columnName . ' = SUBSTRING({string:%1$s}, 1, ' . substr($type, 7) . '), ', $columnName);  
            else  
                $actualType = sprintf($columnName . ' = {%1$s:%2$s}, ', $type, $columnName);
```

**Comment by Oldiesmann** [comment]
That results in every query giving you "The database value you're trying to insert does not exist: x" (x being the variable name).

**Comment by Oldiesmann** [comment]
After reverting that code I'm now getting "The value you're trying to insert does not exist: id_member" and also "array_combine(): Both parameters should have an equal number of values" (line 721 of Subs-Db-Postgresql.php)
