### ISSUE TITLE
Topic starter being able to delete posts in a locked topic

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1379]
As per http://dev.simplemachines.org/mantis/view.php?id=4488

A user cannot edit their own post in a locked topic without suitably high permissions. But they can delete their own post in a locked topic without anything more than delete-own-post permissions.

On the one hand, the permission is 'delete own post' and deleting a post doesn't permit 'the conversation to continue' in the way editing posts can. There are also legal obligations about users being able to remove their own content.

On the other hand, locking a topic is intended to put an end to whatever issue was at hand. That it is effectively read-only once locked without suitable external reason.

Possible solutions:
1. Leave it as is, not a bug
2. Make the deletion rules respect the lock, much as editing does
3. Create a new permission 'delete own even while in a locked topic' (not a fan, personally)

**Comment by Oldiesmann** [comment]
I personally think enforcing the lock is the best option. We should basically use the logic from LockTopic to determine whether or not they can unlock the topic, and not allow deletion if you don't have permission to unlock it (I'd even go as far as to enforce that for those who have "delete_any" as well since deleting it basically makes the lock irrelevant).

**Comment by smfbigguy** [comment]
I also think enforcing it is the best way to go. If it's locked it's locked. There should be no way around that.

**Comment by Xarcell** [comment]
Like Arantor said, there is a legal obligation to always allow a user to remove their content. However, there is not a legal obligation to provide them with the ability to edit it. Last long as whatever solution doesn't stop them from removing their content, it shouldn't matter much.

Another "If it were me" situation, I wouldn't allow anyone to edit their posts after two minutes for SEO purposes anyway. Only those with certain extensive permissions should be allowed to.

Just my opinion.
