### ISSUE TITLE
Auto saving draft in QR mode without full editor causes errors

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1380]
To reproduce, have auto saving drafts enabled, do not use the full editor in QR mode, and go to write a message.

```
Uncaught TypeError: Cannot read property 'contentWindow' of undefined drafts.js?alp21:25
smf_DraftAutoSave.init drafts.js?alp21:25
(anonymous function)
```

This refers to:

```
var oIframeWindow = oIframe.contentWindow || oIframe.contentDocument;
```

but without the full editor defined, oIframe doesn't exist. This also means drafts will not be saved automatically.

**Comment by live627** [comment]
Fixed by #1964
