### ISSUE TITLE
Use of message vs post in language files

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1381]
As per http://dev.simplemachines.org/mantis/view.php?id=4560

We have a variety of 'messages' uses in the language strings but in some languages, the translation does not make proper sense because the context is different. As pointed out 'No messages in time frame' vs 'No posts in time frame' - one applies to PMs, one to posts.

$txt['remove_message'] and $txt['error_no_messages_in_time_frame'] are the two cited but probably others too.

**Comment by Xarcell** [comment]
How about "nothing to report" :P

**Comment by ChainyEO** [comment]
Just to find out how many translators are affected by this, I've raised the issue in the Localization Board at SMF: http://www.simplemachines.org/community/index.php?topic=518330.msg3667637#msg3667637
