### ISSUE TITLE
Ban triggers list can consume a lot of memory

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1382]
http://dev.simplemachines.org/mantis/view.php?id=4627

A ban with > 2700 triggers caused a memory issue with 16M limit. While 2k+ triggers in a ban is possibly not useful, it certainly isn't good if it's causing OOM issues. (10k+ triggers is fine on a 128M or 256M limit though, note)

Unilaterally raising the memory limit in the ban area is doable but a more elegant solution like using createList must be possible.

**Comment by emanuele45** [comment]
Actually this page is already using createList. :angel:

**Comment by Arantor** [comment]
I was going off your comment in the original Mantis report :tongue:
