### ISSUE TITLE
Removing attachments from a post doesn't fix the icon

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1388]
When an attachment is added to a post, the icon is forced to 'clip', and never reverted back to xx or other default if the attachment is removed.

The simple answer would be to simply revert the icon to xx, but perhaps a smarter option would be to track the number of attachments on a message and use that to dynamically update the message index/post view as appropriate. Sort of like a soft override.

Consolidates http://dev.simplemachines.org/mantis/view.php?id=1652 and http://dev.simplemachines.org/mantis/view.php?id=4291

**Comment by Xarcell** [comment]
I know alot of people are against what I'm about to say, but this is a good example of why message icons are a waste. They were good back in the day, but nowadays I think they are bloat.

**Comment by live627** [comment]
@Xarcell +1

**Comment by matthew-kerle** [comment]
So what are the thoughts on this? Are message icons actually going to stay in SMF 2.1, or is there a possibility of removing them? I'd rather not provide a PR for this if it's just going to be removed - in which case, I would rather spend time removing message icons.

**Comment by XinYenFon** [comment]
Message icons will be staying for this version :) 

-----Original Message-----

**Comment by Oldiesmann** [comment]
As we discussed elsewhere here on GH, it might be best in this situation to add a column to the messages table to indicate whether a post has attachments, then just determine the icon based on that - if we have attachments, set it to "clip" in the code, otherwise use whatever is in the database.

**Comment by matthew-kerle** [comment]
As a little side note...I found some code that I think could be improved on slightly.

./Sources/Subs-Post.php

``` php
    // Set optional parameters to the default value.
    $msgOptions['icon'] = empty($msgOptions['icon']) ? 'xx' : $msgOptions['icon'];
    $msgOptions['smileys_enabled'] = !empty($msgOptions['smileys_enabled']);
    $msgOptions['attachments'] = empty($msgOptions['attachments']) ? array() : $msgOptions['attachments'];
```

If there are attachments, we're forcing the message icon to 'clip' (I assume it's actually key'd as clip). So why not by default do this:

``` php
    // Set optional parameters to the default value.
    $msgOptions['smileys_enabled'] = !empty($msgOptions['smileys_enabled']);
    $msgOptions['attachments'] = empty($msgOptions['attachments']) ? array() : $msgOptions['attachments'];
    $msgOptions['icon'] = !empty($msgOptions['attachments']) ? 'clip' : (empty($msgOptions['icon']) ? 'xx' : $msgOptions['icon']);
```

**Comment by Oldiesmann** [comment]
Upon further investigation, it looks like the icon is only changed if it's "xx".

Sources/Post.php, line 1790:
`$_POST['icon'] = !empty($attachIDs) && $_POST['icon'] == 'xx' ? 'clip' : $_POST['icon'];`

Either way, changing it on the fly instead of forcing it to be that way in the database should work fine.

**Comment by matthew-kerle** [comment]
That's how I thought it'd react, sounds good. I'm playing with something on a local branch, we'll see what I can come up with.
