### ISSUE TITLE
Drafts doesn't seem to auto save.

### ISSUE THREAD

**Issue by Trekkie101** [SimpleMachines/SMF#139]
I set the drafts auto save to 60 seconds, made a new topic and waited a few minutes however no auto save. Didn't seem to auto save, and when I navigated away it didn't have a draft in the show drafts section.

**Comment by Trekkie101** [comment]
Should have said:

Safari 6, Mountain Lion on Mac :)

**Comment by Spuds** [comment]
Was this done with the admin account (meaning no permission issues)?

**Comment by Trekkie101** [comment]
Yeah, I tried twice, only have an admin account on the forum.

Any ideas on what to try further? Does it use Ajax or page refresh?

**Comment by Spuds** [comment]
Its uses ajax .. tried it on windows safari and it worked.  I'd open up the development console and see if there are any JS errors that might give a clue (also check the page source to see that drafts.js and a new smf_DraftAutoSave are in there, if not then its a template/perm issue)   .. but I only have safari 5.1.7 on this box .. not sure what the most recent is for windows.

**Comment by Trekkie101** [comment]
Doesn't load drafts.js, I looked through the page options, it enabled QuoteFast from Display.template.php but then seems to miss the drafts bit, however drafts are set to 1 in the settings table for sure. The logic is complex for me but I'll keep looking at the file.

**Comment by illori** [comment]
the setting is not set by default as enabled on install.

drafts_autosave_enabled
drafts_show_saved_enabled

those need to be added to the correct sql files to let them be enabled by default

also those need to be added to the members options configure guest and new user options for this theme and change current options for all members using this theme page.
