### ISSUE TITLE
Entering an invalid board moderator doesn't provide a warning

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1390]
As per http://dev.simplemachines.org/mantis/view.php?id=1459

If an invalid name is entered in the board moderator box, no warning is thrown. Now, it's (far) less of an issue because now there is the auto suggester, but it's still possible to enter a name that doesn't exist and submit the form even without the auto suggester getting stroppy about it.

**Comment by Xarcell** [comment]
Being a piss poor typer that I am, I'm done this quite a few times. This fix would be helpful.

**Comment by Arantor** [comment]
Like I said, in 2.1 it is better because auto-suggest is properly used (not sure it is in 2.0) which should help with that.

**Comment by Oldiesmann** [comment]
Auto-suggest is used with board moderators at least as far back as 1.1 (I don't remember if 1.0 had auto-suggest or not).

**Comment by MissAllSunday** [comment]
Do we really need to fix this?  modifyBoard already checks if the users entered are indeed valid users and removes them if they are not. Users added via autosuggest are automatically added and doesn't face this issue.

The current code does not handle errors and the check is pretty buried on modifyBoard()  so if we really want to do this we need to implement an error system.

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
