### ISSUE TITLE
Migrate some fields to custom fields

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1391]
Some of the fields we have currently as hardcoded would be better being migrated to custom fields. The upgrader could do this - it would only create (say) ICQ if any users had an ICQ field previously. It would end up decluttering the memberlist and the topic display and the members table itself, while allowing for better control from the admin in the long run.

ICQ, AIM, YIM and Skype are obvious candidates, Location is another, and potentially so is Gender (which would also deal with the issues around multiple genders as we have seen before). This would also cover off http://dev.simplemachines.org/mantis/view.php?id=1402 at the same time.

**Comment by Arantor** [comment]
Also, http://dev.simplemachines.org/mantis/view.php?id=1971 is worth taking into consideration here and cleaning up the fields would enable cleaning up the destination of the links.

Of course, they do not necessarily need to become links by default, as other systems do not necessarily do this. It might become feasible instead to create a 'Contact Details' section in the profile and place Skype etc. there. But that's kind of out of scope for the core issue.

**Comment by live627** [comment]
An oldie, maybe not too moldy #204
