### ISSUE TITLE
$db_show_debug can reveal real paths outside $boarddir if used

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1393]
Some setups move $sourcedir and some other folders outside of $boarddir, potentially even outside normal document-root.

While $boarddir is sanitised in the depths of displayDebug(), other paths are not. It might be nice to actually flatten it to a smaller string anyway since collapsing $boarddir to a single period isn't just about sanitisation but also keeping it down to the useful information.

As per http://dev.simplemachines.org/mantis/view.php?id=1903

**Comment by Arantor** [comment]
I'd have preferred if it wasn't just $sourcedir that was cleaned up. $cachedir and other dirs could be similarly out of $boarddir, as per Mantis.

**Comment by NanoSector** [comment]
I could never see any cached files mentioned in that same spot, where should those be subsituted?

**Comment by Arantor** [comment]
Same place as this change. If you have file caching turned on, get_included_files() should be listing all cache files in the list too. Does for me, anyway.
