### ISSUE TITLE
Continue on upgrader error

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1394]
In the event of an error in the upgrader, it may not be possible to continue.

Further reading:
http://dev.simplemachines.org/mantis/view.php?id=4057
http://www.simplemachines.org/community/index.php?topic=346867

**Comment by sbulen** [comment]
I believe the 'click here to continue' link has worked for me recently.   Can this be closed?

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
