### ISSUE TITLE
Custom fields on memberlist

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1395]
In concert with #1391 having the option to place custom fields on the memberlist would be very useful, especially also as that would imply displaying them as the results of searching.

This would cover off http://dev.simplemachines.org/mantis/view.php?id=2110 and especially http://dev.simplemachines.org/mantis/view.php?id=1646

**Comment by Acans** [comment]
It's the little things :)

**Comment by Xarcell** [comment]
I concur with this one.
