### ISSUE TITLE
Support for Atom 2.0 feeds

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1397]
Some feed validators choke on Atom 1.0 as is currently provided. More details in http://dev.simplemachines.org/mantis/view.php?id=4053

**Comment by Xarcell** [comment]
Ditto...

**Comment by Oldiesmann** [comment]
The problem is the feeds were horribly messed up in 2.0 and 1.1. There is no such thing as version 2.0 of Atom. The feed validates just fine in 2.1 with the recent fixes.

**Comment by frandominguezl** [comment]
This one also @colinschoen

**Comment by colinschoen** [comment]
Thanks, closed.
