### ISSUE TITLE
Deleting stuff moves it to the recycle bin - and marks it new

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1398]
Things entering the recycle bin, for various reasons, can end up marking it new and under very specific circumstances can end up preventing it from being marked read afterwards even when the user specifically elects to do so.

http://www.simplemachines.org/community/index.php?topic=437566.0
http://dev.simplemachines.org/mantis/view.php?id=3918

**Comment by Oldiesmann** [comment]
Would simply telling SMF never to consider that board or topics in it as "new" be enough to fix this, or does this need more tweaking? I know it updates maxMsgId, but that's used in so many places that I'm reluctant to change that behavior.

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
