### ISSUE TITLE
Max image size during posting

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1401]
There are several issues with this.

Firstly: overly large images may never get processed to have their size read.
http://www.simplemachines.org/community/index.php?topic=505111.0
http://www.simplemachines.org/community/index.php?topic=505050.msg3555178#msg3555178

Secondly: much as it's still not _quite_ a bug that it's not behaving 'as expected' (it IS behaving as designed, but the design is from some years before CSS had things like max-width)
http://www.simplemachines.org/community/index.php?topic=518083.0

Basically, the use of size should probably be generally dropped from SMF's bbc. There's the legacy thing to consider, but forcing the size in the code just isn't going to work out so well.

Now, the resized image details (as to whether the full vs resized toggle is necessary) can be determined via the naturalWidth and naturalHeight properties of said image, which are accessible in all good HTML5 browsers. IE8 of course needs help, http://www.jacklmoore.com/notes/naturalwidth-and-naturalheight-in-ie/

Thirdly, there's no way to prevent over-sized images, e.g. for mobile users. There may not be a good way to solve that.

**Comment by Arantor** [comment]
There are existing issues with the enforcing of image size through the bbc parameters, namely that it's entirely possible to ignore/override it - http://dev.simplemachines.org/mantis/view.php?id=3758 and the only real way to fix that is to not depend on having a size in the first place.

**Comment by Gwenwyfar** [comment]
I think we should just change both to `max-height` and `max-width` and let css do its thing. I also recall setting both height & width caused proportion issues on some images. I removed this function on my forum and it works much better without it.

For mobile we could force a `max-width: 100%`.

**Comment by Gwenwyfar** [comment]
When clicking to increase the size of an image, we could use the "popup" we now have: just make the image appear there and use only as much screen as is available if the image is too large. If the user really wants to see the full size, browsers have that function, they can use it. Maybe put a link in the corner for full size that simply links directly to the image, we don't need to break the layout for the occasional use of the full size.
