### ISSUE TITLE
Installer does not handle DB ports properly (or at all)

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1402]
If there is a database issue during installation for MySQL, the port will be appended to the hostname (in normal MySQL connection style)

So you end up with localhost:3306, then localhost:3306:3306 and so on, as reported in http://www.simplemachines.org/community/index.php?topic=516836.0

Also, there is no support for running PostgreSQL on a custom port, as reported in http://www.simplemachines.org/community/index.php?topic=397030.0

These can be combined into a single item: create a separate standalone item in the installer for DB port, default to whatever the platform's defaults are (hide for SQLite). If the platform's default is used, don't bother saving to $db_port in Settings.php, if not save it to that and everything else should, theoretically, work.

**Comment by Oldiesmann** [comment]
The changes made by #1421 should fix this. I also added code to upgrade.php to split the host and port if you have "localhost:3306" or something similar as the db_server value. Before I pull all this in I want to do some testing to make sure it works properly with default ports (I don't have any instances of db servers running on non-standard ports) and also need to double-check as to how things are currently handled in 2.0.

**Comment by Oldiesmann** [comment]
Going to close this for now as the above PR should take care of everything here. Feel free to reopen this or open a new issue if it's discovered that anything further needs to be done in this area.

**Comment by Arantor** [comment]
Like the comment I left in the PR, you mean...
