### ISSUE TITLE
Signature Preview

### ISSUE THREAD

**Issue by Acans** [SimpleMachines/SMF#1404]
When you press the signature preview with nothing in your signature and nothing in your previous, it shows two lines saying No signature set.

More of nit picking than an actual bug, but perhaps it should just have one line saying No signature set.

**Comment by illori** [comment]
maybe No Signature to preview?

**Comment by illori** [comment]
also i am not sure why we need a preview of the existing sig compared to the new sig... just the new i think would be enough.

**Comment by XinYenFon** [comment]
Comparing old/new good but i find it unnecessary too :/

**Comment by Xarcell** [comment]
Unnecessary +1
