### ISSUE TITLE
Info Centre

### ISSUE THREAD

**Issue by Acans** [SimpleMachines/SMF#1405]
Latest Revision

Forum Stats and Users Online text for hyperlink is set to #ffffff

When not logged in, Users Online isn't a hyperlink and is the correct colour.

Edit: Attachments and other options when post a new topic/reply is the same.

**Comment by XinYenFon** [comment]
I think i solved it with #1377 - I'll take a look at posts/topics things now.

**Comment by illori** [comment]
duplicate of #1012 please close
