### ISSUE TITLE
Max avatar file size

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1406]
Should be possible to set a limit on how large uploaded avatars are (e.g. to stop very large animated avatars)

Such a limit should be applied to files once uploaded, as it is quite possible an uploaded avatar could get resized and then sit under the limit.

Originally reported as http://dev.simplemachines.org/mantis/view.php?id=2137

**Comment by Oldiesmann** [comment]
I agree with having a filesize limit on uploaded avatars, but I think it would be better to apply that before the file is uploaded for consistency. How do we handle a situation where an avatar fits within the specified maximum dimensions but its filesize is still too large? We also have to take into account the fact that server capabilities could determine filesize - GD doesn't support animated GIFs, but ImageMagick does. I would imagine an animated GIF would be bigger than a non-animated one of the same size (although for what it's worth the size difference probably wouldn't be that much).

**Comment by Arantor** [comment]
If it doesn't fit all the limits, it gets booted. But... if you have an avatar that's very large but will be OK once resized, it doesn't make sense to continue to refuse it if it would end up being within the size limit anyway...

Especially as GD's resizing of avatars invariably makes them smaller (especially for animated GIFs where only the first frame will be preserved anyway)

**Comment by Oldiesmann** [comment]
My concern is that it will confuse people, especially with ImageMagick resizing being an option in 2.1 (IM does support animated GIFs, unlike GD)

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
