### ISSUE TITLE
Email notifications involving parsed BBC can be in the wrong language

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1407]
There are several instances where BBC gets parsed before sending out notifications/announcements/whatever. It is always done so that parsing occurs before language files get reloaded (and in most cases, index.lang.php never gets reloaded anyway)

While minor, it does mean that if the sender and recipient have different languages, the sender's language is used, not the recipient's. E.g. the quote bbc uses 'Quote from: <name>' - but if the sender is English and the recipient is, say, German, the English text gets used.

Solution: when switching language, force reload index+Modifications for the new language and reset back to whatever language it was on beforehand.

Originally reported in 2006 (and still valid) in http://dev.simplemachines.org/mantis/view.php?id=52

**Comment by MissAllSunday** [comment]
Does anyone has like a list or something of actions where this happens?  might be easier than me going through every source file...

**Comment by illori** [comment]
only example i can think of would be maybe a newsletter.

one other sm.org specific would be the cust site posting a pm that was sent or received at times can have text in another language.

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.

**Comment by Sesquipedalian** [comment]
Actually, I have been working on a fix for this one. It's just not done yet.
