### ISSUE TITLE
Signature Settings

### ISSUE THREAD

**Issue by Trekkie101** [SimpleMachines/SMF#141]
On the signature settings page, you can "click here" to apply rules to current signatures.

Throughout SMF we have no "click here" to do anything, instead in the maintenance areas it will use buttons with "Run now", we should for consistency make this the same.

Also there is no green verification that the action is complete, as with other actions.

**Comment by emanuele45** [comment]
What do you think about simply:

```
Note that settings are not applied to existing signatures by default. Run the process now
```

with the link around "Run the process now"?

**Comment by Trekkie101** [comment]
Sounds better :) :+1:

**Comment by emanuele45** [comment]
Both fixed then!
Thanks Trekkie! ;D

**Comment by Trekkie101** [comment]
Perfect :D see you on the boards soon, not long back from holidays! :)

**Comment by emanuele45** [comment]
Holidays?
Now that's explain a lot of things! :tongue:
