### ISSUE TITLE
Newsletter Success Message

### ISSUE THREAD

**Issue by mcblaber** [SimpleMachines/SMF#1410]
After sending out newsletter there is no confirmation message that the newsletters were actually sent. It just redirects back to the admin panel homepage. This is something that existed in 2.0 so it should probably exist in 2.1 as well. :)

**Comment by illori** [comment]
it depends on how many users you are sending the newsletter to, if you get the progress bar. it acts the same as in 2.0 otherwise.

**Comment by Oldiesmann** [comment]
There's no confirmation message or progress bar in 2.1 since we're always using the mail queue now. I'm not sure what we can do here - maybe just add something saying the messages have been added to the mail queue and will be sent according to its settings?

**Comment by mcblaber** [comment]
That works, an administrator just needs some form of confirmation that what they did is being done. Being redirected back to the admin panel frontpage gives no indication if the task was even submitted.

**Comment by MissAllSunday** [comment]
is this enough?  https://github.com/MissAllSunday/SMF2.1/commit/f5c10d405f5b133a3dea9cc65d465cf04da2465c

I changed the redirect to action=admin;area=news;sa=mailingmembers  and the text string should be checked

**Comment by Oldiesmann** [comment]
I would suggest "... added to the mail queue ..." instead of "added to the main queue", but it looks good otherwise.

**Comment by MissAllSunday** [comment]
Yep, change it already but haven't push it to my repo :smile:
