### ISSUE TITLE
Newsletter editor & help popup overlay issues

### ISSUE THREAD

**Issue by mcblaber** [SimpleMachines/SMF#1411]
A picture is worth a thousand words:
![screen shot 2014-02-10 at 3 12 23 am](https://f.cloud.github.com/assets/3847907/2123473/ad23715a-922d-11e3-96c5-be5f50dfce9e.png)

Seems there is some conflict with sceditor and the inline help popup. I'm tempted to say we should just get rid of that inline popup and move those listed newsletter variables as clickable links within the page itself. It would definitely help boost usability and simplicity. For a description of the links (which are already pretty self explanatory) we can make use of something like .smf_swaptip .

**Comment by illori** [comment]
i cant duplicate this issue using firefox 27.

also if these variables require the html checkbox checked, it should state it.

**Comment by XinYenFon** [comment]
I can duplicate this issue on Win8.1 FF27, as well as on IE11 (11.0.2)

**Comment by illori** [comment]
can not duplicate on IE 11 either, win 7. maybe a win 8 issue?

**Comment by Oldiesmann** [comment]
Not sure what the common factor is. Tried it in IE11 and FF 28 beta on my laptop (also Win 8.1) and couldn't reproduce it.

**Comment by mcblaber** [comment]
That's odd, I would have thought this would be a common issue on all browsers.

I'm on Mac OSX 10.9.1 and I've been able to reproduce it on Chrome/Firefox/Safari. I'll test one of my campus computers and see if it occurs there.

**Comment by illori** [comment]
it cant hurt in this case to move those shortcuts to the actual UI when sending the newsletter, i bet a lot of people miss that it exists.

maybe at the bottom of the page after the add &lt;br />s text... also why does that exist? why not enabled by default.

**Comment by Oldiesmann** [comment]
I'm honestly not sure why that's an option or why even not sending it in HTML is still an option since we have an editor there now. The presence of an editor makes it easier to compose nicely-formatted HTML emails without having to copy and paste code from another program, yet it's pointless to have it there if you're not sending it in HTML since none of that code will get parsed into HTML in that situation (I'm not sure if it will strip the bbcode or leave it as is though).

Having links or a dropdown list of some sort to insert the variables is always an option as well.

**Comment by ChainyEO** [comment]
This issue also affects Iceweasel 27 (Debian version of Firefox 27). As far as I know, Iceweasel should behave in the same way as Firefox on any other Linux system.

**Comment by Xarcell** [comment]
I see this problem in Windows 7 and Chrome on a Wamp Installation. I also see the fix for it and will submit a PR request, if I can figure out how to manage more than one PR request on Github/Sourcetree.

**Comment by Xarcell** [comment]
Not unless someone else wants to do it, which I would prefer because I am currently in the middle of factory restoring my PC.

To fix the problem, in index.css...

Find: 

```
.popup_container {
display: none;
position: fixed;
top: 0;
left: 0;
width: 100%;
height: 100%;
background: rgba(40,64,80,0.5);
}
```

Add:

```
z-index: 3;
```

So that it looks like this:

```
.popup_container {
display: none;
position: fixed;
top: 0;
left: 0;
width: 100%;
height: 100%;
background: rgba(40,64,80,0.5);
z-index: 3;
}
```
