### ISSUE TITLE
Cookies and Sessions page?

### ISSUE THREAD

**Issue by Trekkie101** [SimpleMachines/SMF#142]
Was looking at the Cookies and Sessions settings page, it breaks style with all the other pages, what do you all think about moving the random comments like

(SSI wont work well on this)

(enable subdomain independent cookies first!
The domain could be for example: "website.com" or "website.co.uk" without http:// or slashes)

to the help file and accessing them by clicking the ?.

**Comment by emanuele45** [comment]
Yes, it's a bit "different"...
I think that with the help of a bit of javascript (for example hiding what cannot be used in certain conditions) would make easier to remove most of the warnings.

For example with a bit of js that hides the section about "subdomain independent cookies" when local storage is on would allow to remove the "(turn off local cookies first!".

**Comment by Trekkie101** [comment]
Yeah thats probably a better option, plus a little more professional text added to it :P
