### ISSUE TITLE
Smiley Settings not setting default

### ISSUE THREAD

**Issue by Trekkie101** [SimpleMachines/SMF#143]
Admin -> Forum -> Smileys and Message Icons

Click Modify on any of the sets, try and set it as the default set using the checkbox. Doesn't seem to work.

Workaround is use the settings tab.

**Comment by Spuds** [comment]
the submit button in the template_modifyset is missing name="smiley_save"

**Comment by emanuele45** [comment]
Fixed [here](https://github.com/Spuds/Playpen/commit/7e860b74704d99ef76deb659e34dd9acc71240c1)
