### ISSUE TITLE
Error log issues on visiting every admin page

### ISSUE THREAD

**Issue by Trekkie101** [SimpleMachines/SMF#144]
Some error log reports from visiting each page:

 Invalid argument supplied for foreach()
File: /Users/graemespence/Sites/SMF2.1/SMF2.1/Sources/Subs-List.php
Line: 112
    http://localhost/~graemespence/SMF2.1/SMF2.1/index.php?action=admin;area=languages;sa=add;c38ed7fc3a6a=6ca0f475f35ffa58c6b1032fe48b286f
(Tried to search for "English British")

---

```
 File: /Users/graemespence/Sites/SMF2.1/SMF2.1/Themes/default/languages/Drafts.english.php (showDrafts sub template - eval?)
```

Line: 460
Invalid argument supplied for foreach()
    http://localhost/~graemespence/SMF2.1/SMF2.1/index.php?action=profile;area=showdrafts;u=1

**Comment by Spuds** [comment]
This was (should have been at least) caused when there were no drafts for a user ... its been fixed Fixed [here](https://github.com/Spuds/Playpen/commit/6f00a61c31b4e43dc5c585da7918e1905aa7ed7b)
