### ISSUE TITLE
Search for languages broken

### ISSUE THREAD

**Issue by Trekkie101** [SimpleMachines/SMF#146]
Searching for languages is broken from SM.org.

Admin -> Configuration -> Add Language.

Do a search and itll return:

The Simple Machines site is not responding. Please try again later.

**Comment by emanuele45** [comment]
This is a "site" issue I think.
The database of available versions should be updated at sm.org **I think**.

@jdarwood007 is it correct?

**Comment by Spuds** [comment]
Seems so ... its requesting 2.1 languge files via the search and not finding any .... should say that instead of "The Simple Machines site is not responding. Please try again later." though

**Comment by jdarwood007** [comment]
I am certain that its happening because there is no language files on our site yet.  Changing it could break 2.0 language search if we are not careful, but returning a error messsage or empty xml array(I think thats what it uses) should fix that.

**Comment by emanuele45** [comment]
Since it's an sm.org site issue, I'll close this.

**Comment by Spuds** [comment]
Note I did update the error to say "no files found" vs "site not responding" unless of course the site was not responding :P  At least I remember doing it, pretty sure I committed it as well
