### ISSUE TITLE
group moderator unable to search for members

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1462]
currently there is no way for a group moderator to verify if a specific member if in their group without manually checking each page of the list of members from the moderation panel. if the group is not a primary group this task could take a long time. could it be possible to add at least username search to the moderation panel member list per group?

**Comment by Oldiesmann** [comment]
We can certainly consider adding that feature, but wouldn't it be easier to ask someone with appropriate permissions to check for you?

**Comment by illori** [comment]
that would take longer

**Comment by jdarwood007** [comment]
@illori 
Is this still an issue?  What do you suggest to do to fix this?

The way I see it working right now is you can sort the group list.  So if your searching for a member, you can sort by name, and navigate through the pages.  Yes its more work, but it still works properly.

**Comment by illori** [comment]
yes you can go page by page, but what if your group has a few thousand members? it cant hurt to have a search by name to speed up the process.

**Comment by Sesquipedalian** [comment]
I agree that this would be nice to have for large forums, but I don't think it is important enough to hold back getting SMF 2.1 out the door. Perhaps for 3.0.
