### ISSUE TITLE
Upgrade Error (Msgr)

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1464]
Executing: "Messenger fields" (17 of 31)

Adding login history...done
Copying the current package backup setting...done
Copying the current "allow users to disable word censor" setting...done
Adding new "topic_move_any" setting...done
Adding new "browser_cache" setting...done
Converting legacy attachments...done
Fixing invalid sizes on attachments...done
Adding new columns to ban items...done
Changing existing columns to ban items...done
Adding new columns to log_group_requests...done
Adjusting the indexes for log_group_requests...done
Adding new columns to log_packages ...done
Altering the session_id columns...done
Adding new columns to topics ...done
Adding new scheduled tasks...done
Adding the new table...done
Adding new columns to boards...done
Updating board access rules...done
Adding new columns to categories...done
Adding the count to the members table...done
Adding the new table for alerts...done
Adding alert preferences...done
Adding new columns to boards...done
Fixing column name change...done
Altering mil_queue table...done
Altering the membergroup stars to icons...done
Renaming default theme...done
Adding the enableThemes setting...done
Setting "default" as the default...done
Checking for "core" and removing it if necessary...done
Insert fields...done

Error!
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''cust_gender', 'Gender', 'Your gender.', 'text', 50, '', 'email', 0, 1, 'forumpr' at line 1

**Comment by Oldiesmann** [comment]
I'm guessing this is the same issue that was fixed for the installer with #1463.

**Comment by MissAllSunday** [comment]
Nope :(   this is one of the bugs I introduced on my previous PR.

I already solved it but I can't cherry-pick the commit since I have mixed code with the PR for adding an order_field for custom profile fields  so this is going to wait until I finish that PR

**Comment by nwsw** [comment]
Posted a very basic fix at e73bd602fb900a736eaeb39e85c9c4efea06dcbc which allows the upgrade to continue
