### ISSUE TITLE
WYSIWYG: not possible to split quotes up

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#1473]
With WYSIWYG enabled it's not possible to use the return key to split (divide) quotes. The quote shows up in the light blue box, but if you click inside this quote box and press "return" then the quote remains as one whole unit. This means that you can only add to the quote, but not split it up in order to reply to the quote in separate parts.

I've included two attachments:
- This is what happens at the moment. When clicking after "Welcome to Simple Machines Forum!" and then pressing "return" several times, you just end up with loads of line breaks within the quote.

![no_split](https://f.cloud.github.com/assets/3731638/2431452/33424c5e-ad2f-11e3-9de1-5130e799bed7.png)
- Expected behaviour: the quote has been split up, enabling me to respond to specific parts separately. At the moment it's only possible to do this if you turn WYSIWYG off and then manually add the [/quote], followed by the [quote author=name....] to start the second part (this is how I achieved this screenshot).

![expected split](https://f.cloud.github.com/assets/3731638/2431454/44d182dc-ad2f-11e3-9d47-a1a9ab225d23.png)

**Comment by XinYenFon** [comment]
I think this can be solved with three different methods;
1) Add special key for desktop users (Shift or alike) Shift+Enter will split the quote/code blocks
2) Do it SMF 2 way, don't convert Quote/Code inside textarea on toggle(source mode or what you call it :P)
3) Leave it as is :D :D

**Comment by Oldiesmann** [comment]
If you click inside a quote box and hit enter, you're inside the quote tags, therefore you're going to add additional lines to the existing quote. There is no way to do what you want in WYSIWYG mode.
