### ISSUE TITLE
Inconsistency

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#1481]
"Preferences" or "Look and Layout".
"Modify Profile" or "Forum profile".
Pick one of the two IMHO. ;)

**Comment by emanuele45** [comment]
There would be also "Ignore people" VS "Ignore list".

**Comment by XinYenFon** [comment]
I leave that to @Oldiesmann because i don't remember it exactly (some changes done on it -can't really remember-)

**Comment by illori** [comment]
i had brought up the preferences issue with arantor and he said it may be more confusing to change it... i think he missed my point at the time.
