### ISSUE TITLE
Inconsistency 2

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#1482]
In the admin and the moderation panels the third level menu entries have an arrow (and should not).
In the profile the second menu doesn't have arrow when there is a third-level (and they should).

**Comment by XinYenFon** [comment]
third level menu thing is known, but couldn't reproduce the profile thing (or I'm missing).

**Comment by emanuele45** [comment]
![screen_211](https://f.cloud.github.com/assets/1095308/2490623/2bc723f8-b1b9-11e3-8608-c5f3a8d2256a.png)
Notifications and Buddy/Ignore list have a 3rd level menu.
If you want the link I can provide it but registrations are disabled (it's a testing site) so tell me and I can enable them.

**Comment by emanuele45** [comment]
And since it's a matter of layout, buddy and ignore lists have two different layouts (hit: add button).

**Comment by XinYenFon** [comment]
I think you are using old build because in my build those menus also have their arrows.

![untitled](https://f.cloud.github.com/assets/1669995/2490757/92046122-b1c2-11e3-8df4-d74964350890.png)

**Comment by Oldiesmann** [comment]
Both of them have arrows on my test board as well.

**Comment by emanuele45** [comment]
Then if everything works fine for everybody, you may not need #1517 :angel:

**Comment by XinYenFon** [comment]
3rd level menus still broken

**Comment by XinYenFon** [comment]
Can we close this, all bugs mentioned here fixed :)
