### ISSUE TITLE
Type of error: Undefined

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#1484]
Undefined index: allow_user_email
index.php?action=profile;area=theme;u=1
File: /Sources/Profile-Modify.php
Line: 202

**Comment by emanuele45** [comment]
And:
index.php?action=pm;sa=settings
File: /Sources/Profile-Modify.php
Line: 202

**Comment by XinYenFon** [comment]
I think related to #1475 - Oldiesmann will finish removing and it solves the undefined problems as well :paw_prints:

**Comment by Oldiesmann** [comment]
Fixed with #1492.
