### ISSUE TITLE
Installer layout broken

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#1485]
downloaded the latest files.

http://i.imgur.com/umSCQga.png

**Comment by MissAllSunday** [comment]
Can you please be more specific?

What exactly do you consider it to be broken?

**Comment by XinYenFon** [comment]
Its not really broken actually, installer script is not adapting itself to bigger screens.

**Comment by NanoSector** [comment]
The screenshot doesn't say enough...?

**Comment by MissAllSunday** [comment]
> The screenshot doesn't say enough...?
> 
> —

Sigh...

So, I suppose "reading minds" will be added to the never ending list of  
things devs "must do"...

**Comment by XinYenFon** [comment]
tbh its very clear enough, if you are having difficulties to understand the issue, i suggest download Firefox (not sure other browsers can do it) go dev mod (F12) click Responsive and set resolution to 1920x900 then you can see. :)

**Comment by MissAllSunday** [comment]
.___.

Its not about that.... I already know it and was already aware of it. Its the vague report.

**Comment by NanoSector** [comment]
So if it was already known why not say so in the first place? Either way, good to know it's being worked on.

**Comment by matthew-kerle** [comment]
Yoshi is trying to help report things...the issue is with the padding on #header from index.css.

I also found the same thing using Chrome on a good sized display. Removing the padding on #header (just for install / upgrade) seems to be a viable solution: http://prntscr.com/36d1sm

Kind regards

**Comment by Oldiesmann** [comment]
That still doesn't explain what the actual issue is. Other than the fact that the installer doesn't adapt itself to wider displays (which isn't a big deal really), I don't see what's broken or how removing the padding fixes whatever the problem is.

**Comment by emanuele45** [comment]
Compare the two images and look where the cursor is in the screenshot posted by @Yoshi2889.
Do you see the light blue bar in the middle of the dark blue footer?
And than the same bar doesn't show up in the screen posted by @Labradoodle-360?

**Comment by NanoSector** [comment]
The HTML is different for the installer and the actual forum.
In the installer, everything is wrapped inside #header. In the forum, #header is its own element.

I'll get round fixing this in a bit.
