### ISSUE TITLE
Installer: Un-uncheckable option

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#1486]
What is the point of keeping the UTF8 setting if it can't be changed?

**Comment by MissAllSunday** [comment]
http://www.simplemachines.org/community/index.php?topic=518146.0

**Comment by NanoSector** [comment]
That does not answer my concern.

ETA:

@Antes what is your question / concern about #1486
@Antes I think its bit clear
@FatalException Why the setting exists
@Antes for SQLite 2.8
@FatalException If it automatically toggles, make it a background variable
@Antes hmm true
@Antes but you should say those to Suki as well
@FatalException Don't provide users with a setting they can't toggle.

**Comment by XinYenFon** [comment]
Its not a urgent problem (its not really a problem) but it might be better if we hide the un-checkable checkbox to non-SQLite 2.8 users.
