### ISSUE TITLE
Accented members group names causes empty forms

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1503]
Hello and thanks for a great piece of software.

Member groups names, when contqaining accented characters (French forum here), cause the modification form to be empty, so when validating the changes, the names are simply dropped and lost.

SMF 2.0.7, no plugins or mods on the members groups section, always reproducible.
Thanks! Any extra info needes ? Just ask.

**Comment by margarett** [comment]
Hi,

This is just for 2.1 development, please post in sm.org forum support if you haven't done so yet.

**Comment by XinYenFon** [comment]
How can we reproduce this @appzer0 ?

@margarett agreed but what if its effecting SMF 2.1 too ? :paw_prints:

**Comment by ghost** [comment]
@Antes Juste go to Admin > Members groups > modify a group name so it contains accented characters, like éèêàâ. Now go modify that accented member group name a second time: the form is empty, any accented string (name, description, and so on) is dropped. If you validate the form at tha moment, you lose everything.

**Comment by margarett** [comment]
Actually there was a recent topic in PT boards with a similar issue with boards, not membergroups. But the user only got this issue after changing hosts and I couldn't reproduce it, so I imagine something server related.

**Comment by XinYenFon** [comment]
I can't reproduce it on my local copy of SMF 2.1 (nightly) as well.

**Comment by live627** [comment]
Can this be closed then?

**Comment by ghost** [comment]
Yes, close it, as seen on the SMF forums this must be an encoding issue in the MySQL server when it has latin_swedish_ci database encoding by default
