### ISSUE TITLE
User > Member

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1504]
This was planned in SMF 2.0 but due to compatibility pushed to SMF 3.0, since we are changing things, i think its better to eliminate it now.

Ref: http://dev.simplemachines.org/mantis/view.php?id=3411

**Comment by live627** [comment]
@Oldiesmann do we move forward with this mass rename or sweep it under the rug?

**Comment by XinYenFon** [comment]
This was part of moving mantis to github thing, I actually thought (in that time) it was a good idea to sweep this issue but (I'd love to see Localizers comment on this as well), I find not so needed at this  moment due to SMF 3.0 probably change a lot and this can be eliminated more easily.

**Comment by frandominguezl** [comment]
What's the final decission on this? @Oldiesmann

**Comment by Oldiesmann** [comment]
At this point I think it's best to just leave it the way it is.
