### ISSUE TITLE
Gender - "show enclosed within text"

### ISSUE THREAD

**Issue by Akyhne** [SimpleMachines/SMF#1510]
Custom profile fields -> Gender.

HTML is...
< span class=" generic_icons gender_{INPUT}" alt="{INPUT}" title="{INPUT}">

There's no closing of the span and alt tag is not allowed on spans.

**Comment by Akyhne** [comment]
You still need the </span> closing tag.
< span class=" generic_icons gender_{INPUT}" alt="{INPUT}" title="{INPUT}"></ span>

**Comment by MissAllSunday** [comment]
oh yeah :tongue:
