### ISSUE TITLE
0004364: URLs with brackets not supported

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1514]
[url=http://www.tttth.com/[alt-coin-talk/]Talk[/url] > Works ok
[url=http://"http://www.tttth.com/ablt-co]-tak"]Talk[/url] > Works as closure tag and breaks the link.

I think we can fix this issue with changing systematic [url=] to [url=""]

**Comment by MissAllSunday** [comment]
Duplicate of https://github.com/SimpleMachines/SMF2.1/issues/1187
