### ISSUE TITLE
like when ignored

### ISSUE THREAD

**Issue by Akyhne** [SimpleMachines/SMF#1519]
Haven't checked if this is the same in SMF 2.0.x

When you're ignoring a user, you'll not see the post from the user, until You click the "Show me the post" in display view.
However, You can still like the post, even before clicking the "Show me the post".

The "Like" hand icon should also be hidden, until You choose to see the post.

**Comment by MissAllSunday** [comment]
TBH I don't see any harm in keeping the way it is right now, I mean, you can do pretty much anything to a post from an ignored user already, including quoting the whole message. So in that context, hiding the like option won't do much.

I agree the whole ignore this user feature isn't the best but at this stage I rather prefer not to mess with it.

**Comment by Akyhne** [comment]
As default, the user's post as well as quote button is hidden until clicking the "Show me the post".
Why not include the "Like" button as well to be hidden? Makes sense to me you can't like a hidden post, until revealed.

**Comment by MissAllSunday** [comment]
oh yeah, forgot the whole thing was changed, I OK either way.
