### ISSUE TITLE
Error after upload

### ISSUE THREAD

**Issue by Matthew2D** [SimpleMachines/SMF#1521]
I get this after I upload the smf21 files.

Warning: require_once(/home3/mcwh/public_html/xxx/forum/testbed/smf21/Settings.php) [function.require-once]: failed to open stream: No such file or directory in /home3/mcwh/public_html/xxx/forum/testbed/smf21/index.php on line 42

Fatal error: require_once() [function.require]: Failed opening required '/home3/mcwh/public_html/xxx/forum/testbed/smf21/Settings.php' (include_path='.:/opt/php53/lib/php') in /home3/mcwh/public_html/xxx/forum/testbed/smf21/index.php on line 42

**Comment by MissAllSunday** [comment]
Please take a look at this: http://wiki.simplemachines.org/smf/Contributing_to_SMF#How_to_install_SMF_from_github
