### ISSUE TITLE
0004940: sending pm to user with quotes in name

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1524]
Ref: http://dev.simplemachines.org/mantis/view.php?id=4940

How to reproduce;
1) Change your display name to "Antes" the Black Cat
2) Try to send pm to "Antes" the Black Cat

You'll get: Unable to find member 'the black cat'.

**Comment by FearThe1337** [comment]
As far as I can see clicking the PM button seems to work fine, but manually filling in the name does not.

**Comment by colinschoen** [comment]
Fixed.
