### ISSUE TITLE
register.template.php - flow_auto

### ISSUE THREAD

**Issue by Akyhne** [SimpleMachines/SMF#1527]
Around line #300...

< div id="confirm_buttons flow_auto">';

should be...
< div id="confirm_buttons" class="flow_auto">';

EDIT: How the hell do I post code here, without it being parsed?!

**Comment by MissAllSunday** [comment]
Heres a guide for getting used to Markdown https://help.github.com/articles/github-flavored-markdown

**Comment by Akyhne** [comment]
Test...

```
<div id="confirm_buttons flow_auto">';
```
