### ISSUE TITLE
Inst. of theme fails on theme version

### ISSUE THREAD

**Issue by Akyhne** [SimpleMachines/SMF#1532]
What ever You do, if You install a theme via file or via "From a directory on the server", installation fails.

To reproduce:
1) Create a copy of Default from admin center.
2)
Either...
     Zip it and try uploading it as a new theme
or..
copy it in themes folder as a new theme.

In both cases the intallation will fail on theme version. Copying the Default theme, generates this:

```
<install for="2.1 - 2.1.99, 2.1 Alpha 1">
```

... which should be good enough.

Even correcting to 

```
<install for="2.1 Alpha 1">
```

... doesn't help and You're still told the theme is not compatible with 2.1 Alpha 1

**Comment by MissAllSunday** [comment]
Yes, this is intentional to prevent themes for other versions to be installed.

A downside of it is the annoyance of testing themes for an alpha version but then again, themes shouldn't be made for alpha versions anyway.

If you want to test your theme, change the SMF version to 2.1.

**Comment by Akyhne** [comment]
NP... thought it was a bug.
