### ISSUE TITLE
0004955: Calendar button

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1542]
If you enable/disable the Calendar, the Button is not show/show until you clear the cache (APC Level 2)

Tried with SMF 2.1 Alpha (latest build) 

> SMF file based caching L2

Mantis: http://dev.simplemachines.org/mantis/view.php?id=4955

**Comment by Oldiesmann** [comment]
So basically, anything that causes changes to any $modSettings variable should also cause the cache for that to be cleared? Sounds reasonable to me.

**Comment by live627** [comment]
No.

**Comment by Oldiesmann** [comment]
"No"? No the cache shouldn't be cleared? Please explain.

**Comment by live627** [comment]
Clearing the cache every time $modSettings is changed is unnecessary.

**Comment by Oldiesmann** [comment]
What solution would you propose then?

**Comment by live627** [comment]
Anything that modifies the menu should clear the cache. SMF caches its menu
at level 2 or higher.

**Comment by Arantor** [comment]
The problem with clearing the cache like that is that you end up potentially clearing the cache every page load, meaning you might as well not bother caching it in the first place.

**Comment by Arantor** [comment]
You might as well at least change Subs.php to check settings_updated _before_ trying to hit the cache, only to throw the result away...

**Comment by Oldiesmann** [comment]
Good point.
