### ISSUE TITLE
Odd issue with cat order after upgrade

### ISSUE THREAD

**Issue by Akyhne** [SimpleMachines/SMF#1544]
Haven't tried to replicate this.
I have a test forum with 3 cats:

"Admins"
"General Category"
"Second Category"

... and in that order.

Alpha version was 1 month old (new install.), then I downloaded the newest Alpha and ran the upgrade.

After upgrade, the order was:

"General Category"
"Second Category"
"Admins"

Looking in the admin center, the "Admins" cat. was still said to be the first. It said "In first place" under [Order].
Just clicking the [Modify] button, sorted Things out.

Fortunately, I had backed up the tables and nothing was changed at any point in the {db_prefix}categories table

**Comment by XinYenFon** [comment]
Duplicate: https://github.com/SimpleMachines/SMF2.1/issues/887

**Comment by MissAllSunday** [comment]
Yeah, is the same issue, so closing this to try and keep this thing trimmed and neat.
