### ISSUE TITLE
Registration form - undefined index:registration_form

### ISSUE THREAD

**Issue by Akyhne** [SimpleMachines/SMF#1557]
Register.php - line # 90

```
    $context['page_title'] = $current_step == 1 ? $txt['registration_agreement'] : $txt['registration_form'];
```

$txt['registration_form'] is currently in Errors.[language].php. It should probably just be in Login.[language].php.

Also, I just noticed this:
Line # 46:

```
    loadLanguage('Login');
```

... and line # 76:

```
            // Are they saying they're under age, while under age registration is disabled?
            if (empty($modSettings['coppaType']) && empty($_SESSION['skip_coppa']))
            {
                loadLanguage('Login');
                fatal_lang_error('under_age_registration_prohibited', false, array($modSettings['coppaAge']));
            }
```

loadLanguage('Login') is loaded twice...

**Comment by XinYenFon** [comment]
According to https://github.com/SimpleMachines/SMF2.1/commit/b6f2b66df25c5ce4f467a5dbd0f49fbda9902f44, they need to be in errors language file.

**Comment by Akyhne** [comment]
I don't see why the text "registration form" should be in errors file. But if that's the case, it's needed in both files as duplicates.

**Comment by XinYenFon** [comment]
tbh i don't either... and yes $txt['registration_form'] needs to be in login.lng file as well.

**Comment by Oldiesmann** [comment]
I'm wondering if someone thought that was an error or something. $txt['registration_form'] is not used anyplace in an error message, so it should be put back in the login language file in my opinion.
