### ISSUE TITLE
allowedTo, multiple issues

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1561]
I had previously reported this privately but since there's no apparent inclination to fix, I guess I'll make a formal report.

There are three bugs in allowedTo(), all three relating to making an allowedTo() call with a board specified.

In the queries used therein, the wrong table alias is used for the moderator-groups join, same join also fails to have the correct number of brackets, and also injects strings directly into the query with manual quoting; the proper quoting systems are completely bypassed.

**Comment by Oldiesmann** [comment]
Actually, I just forgot about the issues as I was quite tired when you initially reported them. Thanks for taking the time to report them again, and I will definitely get this fixed ASAP.
