### ISSUE TITLE
Gross inefficiency in Display.php

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1562]
There is, in the admin panel, a feature for listing the number of days since the last reply in a topic, in order for displaying a warning to users.

As such, in Display.php a query is run to fetch the time of last post in order to be able to display the warning. Consequently, this query is run on every page view.

Here's the kicker: the query is still run even if the current user cannot reply. It is still run even if the topic is locked (and the user cannot reply). It is even still run if the setting is set to 0 which the admin panel outright indicates is 'disabled'.

While on sites with lots of recent topics with guest posting this might not be so useful, on the _vast_ majority of forums this is a non trivial performance enhancement, all for moving a query further down the code and into an if() test once $context['can_reply'] is defined.

**Comment by Arantor** [comment]
Your fix does not address the very most important part of this bug. Please take the time to read the whole report before posting. While you've fixed the first issues (it being off or topic being locked), you're still running it for all guests. For this to be done properly, you have to move the entire query further down the file, after $context['can_reply'] is declared and then incorporate that into the test specifically so that you only run the query if the user can actually reply.

Having to repeat myself on something like this is incredibly frustrating, but I know by now I should not expect to actually be listened to for at least the first three times I mention anything.

**Comment by XinYenFon** [comment]
Posting this snip here because my logic lead me this way. If its still not the solution sorry for taking your time.

``` php
$context['can_reply'] = empty($topicinfo['locked']) || allowedTo('moderate_board');
$context['can_reply_unapproved'] = $modSettings['postmod_active'] && $context['can_reply'];
// When was the last time this topic was replied to?  Should we warn them about it?
if (!empty($modSettings['oldTopicDays']) && ($context['can_reply'] || $context['can_reply_unapproved']) && empty($topicinfo['is_sticky']))
```

This still runs for mods/admins and mod-likes :/ but I'm currently not sure about how to prevent this.

**Comment by Arantor** [comment]
That's where you put it, yes, after line 1113 will work fine and you only need to do it off $context['can_reply'] because that's all that's used in the display template to show the QR area. You need to do the query if the person can reply to the topic (because that's when they will see the message) which includes moderators and admins, but you specifically need to have done the check for can_reply so you exclude guests and so on to save not doing that query.

Mods and admins can reply to locked topics so it should logically check in those cases. IOW, any time the user could reply to the topic, that's the circumstance in which you need to get the last post's date.

**Comment by XinYenFon** [comment]
Moved the code to pointed spot (thanks).
