### ISSUE TITLE
RemoveTopic does not delegate removal information to search APIs

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1563]
Applies to both removeTopics and removeMessage.

The entire point of having search APIs is to abstract away behaviour from the core to different backends depending on their behaviour. 2.0 didn't do this particularly well, 2.1 is better but still has major issues, especially this one.

Standard and Fulltext backends require no explicit work in order to remove topics or messages; the actual act of modifying the DB will remove the relevant indexing. Custom on the other hand has explicit code branches in those routines to be called.

Now that's fine - except if you happen to have something else like Sphinx, Sphinx cannot be updated (it has long since supported realtime index changes) because the process is never delegated to the search API to handle it itself.

The fix would be to create a new method in the search API to receive deletion of topics and deletion of messages, instantiate the backend class at the right time and delegate through Tell, Don't Ask principles. The core code gets simplified and easier to follow, and extra backends can actually work properly.

There are other instances where this is the case, but this is a major one.

**Comment by Dragooon** [comment]
What about the messages and topics that are being recycled?

**Comment by Arantor** [comment]
Better question: what happens when a topic is moved? When a topic is moved to another board, does the API get notified? (Again, fulltext and standard need do nothing about it)

All a deletion-to-recycle does, from a search perspective, is change the board a message/topic lives in. Whatever method is used for moved topics is all that's needed for that.

**Comment by Dragooon** [comment]
Are moved topics a concern? Because I don't think the board is accounted by the search queries?

**Comment by Arantor** [comment]
Sure they are. Firstly you can limit searches by board, secondly and way more importantly: it's a privacy issue. You need to not search in things that the user can't see. In things like Sphinx and ElasticSearch it's so much more efficient to push filtering to _them_ to deal with rather than doing it when having received the posts.

**Comment by Dragooon** [comment]
Hmm, I was (obviously) aware of board filtering itself but that's a good point that an API should probably be aware of when a topic is moved. I guess the following methods should be added:

```
/**
 * Callback when a post is removed
 * 
 * @access public
 * @param int $id_msg
 * @return void
 */
public function postRemoved($id_msg);

/**
 * Callback when a topic is removed
 * 
 * @accesc public
 * @param int $id_topic
 * @return void
 */
public function topicRemoved($id_topic);

/**
 * Callback when a topic is moved
 * 
 * @access public
 * @param int $id_topic
 * @param int $board_from
 * @param int $Board_to
 * @return void
 */
public function topicMoved($id_topic, $board_from, $board_to);
```

The idea being that the API should be aware of what's going on even if it may or may not require the information

**Comment by Arantor** [comment]
That's kind of the underlying point. It is not the core logic's code to make this decision (even though the core logic still has bits of search logic in it!) The main logic should not care what the search index needs to do with a post or not, wherever possible, it should just say 'this post has changed' or 'this topic has changed' and the search API should work out what it needs to do, not the core logic.

**Comment by Dragooon** [comment]
This should be closed since the PR was merged

**Comment by Dragooon** [comment]
Closing this as it was covered by #1632
