### ISSUE TITLE
Auto optimise DB scheduled task

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1566]
With the growing trend of InnoDB use, this should be disabled. Under MyISAM it can have improvements in performance, but under InnoDB it is very much NOT a good idea to do because it will pretty much guarantee things being slower when it comes to editing existing rows.

**Comment by Oldiesmann** [comment]
What's the best option here - just disabling it (and preventing it from being enabled) under InnoDB, or disabling/removing the option altogether?

**Comment by Arantor** [comment]
I'd suggest removing it entirely, to be honest.

**Comment by Oldiesmann** [comment]
Sounds good to me.
