### ISSUE TITLE
Fulltext indexes are supported on mediumtext columns

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1571]
There is code internally to juggle the body column around based on post size but it refuses to upgrade the column size to mediumtext if there's a fulltext index on it.

Both MyISAM and InnoDB at least in MySQL 5.5 support fulltext indexes on mediumtext columns, very likely that extends to at least MySQL 5.1 and probably even 5.0 (the documentation is somewhat unclear on this point; testing would be required)

Switching it to mediumtext permanently would solve at least one outstanding bug around posts potentially being truncated inappropriately.

**Comment by Oldiesmann** [comment]
The only thing I can really find regarding fulltext indexes on mediumtext columns is this bug report from 2007: http://bugs.mysql.com/bug.php?id=26677. That seems to prove that MySQL 5 does indeed support fulltext indexes on MEDIUMTEXT columns.

However, fulltext indexes are not supported for InnoDB tables prior to 5.6, per the MySQL manual (http://dev.mysql.com/doc/refman/5.5/en/fulltext-search.html ).

**Comment by Arantor** [comment]
Could have sworn it worked on 5.5/InnoDB rather than 5.6... in any case, your installer still brute forces everything to MyISAM anyway currently so what's the problem?

**Comment by Oldiesmann** [comment]
Just making sure we cover everything I guess. Plus, I could have sworn we went through and changed the installer so that you can specify a preferred engine for a table and have it fall back to MyISAM if that engine wasn't available.

**Comment by Arantor** [comment]
Nope, #772 lists that as a thing to be done.

**Comment by albertlast** [comment]
Can we close this issue?
because this min mysql version is to low to look at this topic.

**Comment by Arantor** [comment]
But it isn't. If the installer still forces things to MyISAM, the minimum of 5.0.3 would allow this to simplify all the code away.

And if it goes InnoDB, the existing behaviour is still wrong anyway.

**Comment by albertlast** [comment]
The Installer Force innodb.


________________________________
Von: Arantor <notifications@github.com>
Gesendet: 22.08.2017 7:39 nachm.
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] Fulltext indexes are supported on mediumtext columns (#1571)


But it isn't. If the installer still forces things to MyISAM, the minimum of 5.0.3 would allow this to simplify all the code away.

And if it goes InnoDB, the existing behaviour is still wrong anyway.

**Comment by Arantor** [comment]
OK, so the entire thing is differently broken then. If you're forcing InnoDB where it is available, that means it's being potentially called for on 5.0.3+ but the full text search doesn't even work on 5.0 through 5.5 out of the box under this situation and I can find no reference that the user will be told about this, it'll just fail without a good explanation.

-shrug- Might as well close it, it's broken but I see far too little dev effort going on the use case that literally 99.99% of the 2.1 userbase actually has, i.e. MySQL.

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
