### ISSUE TITLE
Search result with to many options

### ISSUE THREAD

**Issue by Akyhne** [SimpleMachines/SMF#1574]
If you make a search result and chooses to have the result shown as messages, you have 3 options below each result - "Reply", "Quote" & "Notify".

I really don't see the point of being able to reply directly on a search result. For that matter, the post could be on page 2 of 100 in a topic.
_If_ You choose to click the "Reply" or the "Quote" button, You are redirected to the editor in that topic. So You can't really see what other people replied, hence it's an odd situation to be in.
I know You can see the resent few posts in that topic, but there's no guaranty You can actually get a view about the Whole conversation in the topic.

**Comment by XinYenFon** [comment]
It seems a long shot to me as well. But it 'll be better if we ask this to end-user.

**Comment by NanoSector** [comment]
Any results?

**Comment by illori** [comment]
2.0 has the same set of buttons and i dont recall anyone complaining about them.

**Comment by Akyhne** [comment]
Does that make it any better?

**Comment by Kindred-999** [comment]
Actually, I agree - I think the reply and quote buttons are potentially inappropriate in the location mentioned. Are they there only because it's a message view, which is standard or does this have its own view?  If the latter, I would recommend removing them

**Comment by illori** [comment]
i believe only visible in the message view

**Comment by illori** [comment]
i dont think this was to be closed, reopening.

**Comment by jdarwood007** [comment]
Yea I accidentally tagged it.  I had this open as well.

For this, Its actually designed in the template this way.  We could either remove all the reply/quote options or make it a setting (Such as: Allow replies/quotes from Search Results).

**Comment by illori** [comment]
i would suggest removing it. we have too many settings as it is. it is easier/faster to remove it then add a setting anyway right?
