### ISSUE TITLE
Upgrade.php locking up on "Cleaning Old Email Settings"

### ISSUE THREAD

**Issue by mcblaber** [SimpleMachines/SMF#1580]
I haven't tested this in any other environments yet so this report could be specific to me. But when running the upgrade script on my test site it stops at -- 

Executing: "Cleaning up old email settings" (31 of 32)
"Server has not responded for 30 seconds. It may be worth waiting a little longer or otherwise please click here to try this step again"

**Comment by XinYenFon** [comment]
Duplicate: https://github.com/SimpleMachines/SMF2.1/issues/1533 :paw_prints: :)

**Comment by mcblaber** [comment]
Woops missed that.
