### ISSUE TITLE
Saving PM as draft makes it impossible to send

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1587]
After saving a PM as draft, TO place no longer recommending or adding someone and removes already added people/person.

![pm-error-draft](https://cloud.githubusercontent.com/assets/1669995/2823011/d3271f18-cf19-11e3-9c0c-b5a8b97155d2.png)

**Comment by Oldiesmann** [comment]
This is a bug of some sort. Either the recipient info isn't getting passed to the SavePMDraft function like it should, or something else goofy is happening. It's definitely supposed to save that information though.

**Comment by Oldiesmann** [comment]
Looked at this a bit further and it's actually just a display bug. If you go to your PM drafts after you've saved the draft, it will show the recipient info. I'll look into why it's not showing it on that screen though.
