### ISSUE TITLE
Delete personal messages

### ISSUE THREAD

**Issue by Akyhne** [SimpleMachines/SMF#1589]
There's an option in PMs to prune messages older than x days. It runs via the sub action sa=prune.

However looking through the code, there's also an option to delete all PMs. It runs via sa=removeall.
But there's no reference to sa=removeall via a button or anything else. The only thing You can find, is reference to confirm the removal via sa=removeall2.

The feature to remove all PMs seems to Work, when browsing manually to sa=removeall, template is there and all. It's actually the same story in SMF 2.0.x. Maybe it's old stuff from SMF 1 or maybe devs just forgot about adding a "Delete all" button under "Prune Messages".

**Comment by Ant59** [comment]
How should this be? I would assume it would be sufficient to change "Delete" to "Prune" and add a "Delete All" button next to it?

**Comment by Akyhne** [comment]
Yes, but not to confuse people, I would make a hr or an extra windowbg and then another text "Empty Your inbox completely" and a button "Delete all".

**Comment by Akyhne** [comment]
Something like this:
![prune-delete all](https://cloud.githubusercontent.com/assets/2752715/2827677/ce53fba6-cf86-11e3-8e1d-d56f87268525.png)

**Comment by XinYenFon** [comment]
I'll do it after return back to dorm nice catch

-----Original Message-----

**Comment by Ant59** [comment]
Done.

**Comment by XinYenFon** [comment]
Actually function template_ask_delete() there. And this needs to know where user clicking it, inbox/sent. Otherwise you'll get undefined error.

You can check; function MessageKillAllQuery() & function MessageKillAll() on PersonalMessages.php.
But first #1585 & #1586 needs to be resolved.
