### ISSUE TITLE
Harmonise installer/upgrader with $smcFunc use

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1599]
I see commits and subsequent bugfix commits due to dropping a column from the upgrader, e.g. because $smcFunc['db_query'] was getting upset when an error occurred.

I did actually comment on this at the time but due to the joys of Github it fell through the cracks, so I'll reiterate. (Though I only stated point 2, briefly. Might as well be thorough though.)
1. You can catch otherwise-fatal errors with $smcFunc['db_query']. In the optional array parameter for options for the query, you can supply 'db_error_skip' => true, and magically it will not throw a fatal error at that point. You can check the result of the $smcFunc['db_query'] to know whether or not the query succeeded (regardless of the type of query). If you must do database-schema operations with $smcFunc['db_query'] you should probably also provide 'security_override' => true, like the installer does when trying to create the database.
2. More importantly, there is actually a dedicated function in the Packages extension of $smcFunc specifically for handling removing columns. It's totally agnostic of database and will even correctly deal with it on SQLite 2.8. $smcFunc['db_remove_column'] won't bite. In fact, it'll even be smart and not issue the DROP COLUMN if the column does not exist (thus not having to suppress the inevitable error).
3. I'm sorry but changing a query from $smcFunc to the tangled mess that is a bare query just to avoid having a fatal error is bad form. At minimum, it should have db_error_skip to indicate that you're completely aware it can fail and that the consequences of failing are not significant enough to deal with. (Note that the upgrader's error handling is messed up enough, actively adding to the problem makes your life harder in the long run. Be smarter about how you deal with it up front and you make your life simpler especially if it is a practice you actively have.) It is always preferable to express intent through the code itself if such facilities are present.
4. As a general rule, using $smcFunc in place of bare queries will vastly simplify your life. Almost all of the database agnostic code can be handled with $smcFunc cleanly, meaning that you can write once and if you must have one file per backend, you can at least have the same code in each. Which means the ideal is to then have a common install or upgrade script and then have specifics for MySQL, PostgreSQL and SQLite if you genuinely can't handle it through the agnostic layer. For example, the bulk inserts that get done at install time could be moved safely to a common file and use $smcFunc['db_insert'] which is quite happy to do multi-row inserts without having to manually phrase them differently. Pretty much all of the semantics around table structures can be captured, even down to specifying indexes. In fact, the only thing that does come to mind as a possible problem is for MySQL itself where you might want to run something akin to the board reorder query at upgrade time (not that you _would_ do that because that's not the proper solution, but it's the sort of thing you _might_ want to do in a backend-specific installation) The point, of course, is to get to the stage where you're not writing and maintaining three almost but not quite identical clones of the same code, which may be subsequently maintained by people not intimately familiar with the semantics attached. (I would be the first to admit I was not familiar with either PostgreSQL or SQLite.)

IOW: You have this fantastic, battle-tested library, which will make your life easier if used properly. Please stop reinventing (and subsequently debugging) the wheel.

**Comment by Oldiesmann** [comment]
Thanks for your input. I guess I'm not as familiar with $smcFunc['db_query'] as I should be. I will definitely look into converting bare queries to using that (and probably the ones that use "upgrade_query" as well).

As far as point 2 goes - the only problem there is that $smcFunc['db_remove_column'] doesn't exist unless you're using SQLite 2.8. I'm not entirely sure why, but I did look into that at first before giving up and going with a bare query for MySQL, SQLite3 and Postgres.

I like the idea of point 4 as well, but am not sure how easy it would be to do that given what a mess the installer/upgrade things are at the moment. It's definitely something I'll look into if I get a chance.

**Comment by Arantor** [comment]
That's funny because, for example, DbPackages-mysql.php adds the assignment for db_remove_column to $smcFunc with the definition on line 38, and smf_db_remove_column, the function which will be called, is defined on line 266. Lines 38 and 319 of DbPackages-postgresql.php respectively.

**Comment by Oldiesmann** [comment]
I'll look at it more closely then. When I tried to use it, the upgrade script broke and gave me an "undefined index: db_remove_column" error in the command line.

**Comment by Arantor** [comment]
I was fairly sure that db_extend('packages') was run which is what defines it.

**Comment by Oldiesmann** [comment]
It is run in upgrade.php, but only in the parse_sql function, which might not be called for PHP code. I'll look into it further this week and see what's going on.

**Comment by sbulen** [comment]
The smc functions appear to work great, & are db agnostic.   dbpackages-mysql & subs-db-mysql (or their pg counterparts) are invoked in the upgrader.  

Today, the upgrader runs parse_sql() to read thru the whole ".sql" file.  It will basically do one of two things, depending on what it finds:
- Code it finds between ---#s (without {}s) it assumes are SQL and runs thru upgrade_query(), which runs a generic smcfunc for db_query on line 1871.   
- Code it finds nested within ---{ and ---} it assumes are php and runs thru an eval on line 1791.  The php logic that flows thru here by & large uses smcfunc['db_query'] to interact with the DB.   

So basically all sql ultimately runs thru the smcfunc['db_query'].   Just not the way Arantor hoped...   

If the sql were invoked using the _function-specific_ smcFuncs, such as smcFunc['db_drop_column'], you could conceivably eliminate the need for db-specific .sql files.  Instead, it is much more common to use the more generic smcFunc['db_query'], either by entering the sql directly in the .sql file between ---#s, or, by using the generic smcFunc['db_query'] call in your php & providing the db-specific syntax to drop the column.   

The big question in my mind is - can you _always_ use the more specific function calls?  Can you really write one pure db-agnostic upgrader?   A lot of that code is pretty different between the mysql and its pg counterpart today...   For example, there is logic in there to choose different approaches depending on which version of pg is loaded (line 2008+ in upgrade_2-1_postgresql.sql file).   If this were purely db-agnostic, that db-specific logic should be in the DbPackages-xxx or  Subs-db-xxx, but not in your .sql file.  

I think this is definitely do-able, but requires a lot of discipline - and a lot of rewriting.  

This feels like a noble cause...   And it also feels like the ship has sailed...  Maybe for 3.0?

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
