### ISSUE TITLE
Merging topics is a bit confusing

### ISSUE THREAD

**Issue by Akyhne** [SimpleMachines/SMF#1600]
I find the merging process a bit confusing. As You can see on the first image, You can either choose an ID of the target topic or click a target topic at the bottom.
Well, that's what I figured out after half an hour, never been using the merge feature much.
![merge_original](https://cloud.githubusercontent.com/assets/2752715/2863840/dda8d8e4-d209-11e3-9aa3-6b7aaa4a7add.png)

I sugges a change to the layout like something like on the next image below.
![merge_new](https://cloud.githubusercontent.com/assets/2752715/2863846/e364e156-d209-11e3-96d1-b389f6d9882e.png)

**Comment by XinYenFon** [comment]
Seems better indeed, I'll change it once I fix my PC :)

-----Original Message-----

**Comment by Akyhne** [comment]
Well, if I could figure out how to keep my fork updated here on Github, it would be much easier for me to provide fixes.

**Comment by XinYenFon** [comment]
https://gist.github.com/CristinaSolana/1885435 will help you :)

-----Original Message-----

**Comment by Akyhne** [comment]
Yeah, if I knew how and where to use those commands.

**Comment by XinYenFon** [comment]
I'm using git-GUI it also has git-bash you can use this command there or source tree app has command line feature (windows) if you are on Linux or Mac OS I have no idea :/

-----Original Message-----

**Comment by Akyhne** [comment]
I just want to update online, not locally. I'm not using any kind of local software, don't see the point doing so.

**Comment by XinYenFon** [comment]
You need to delete your fork and re do it

-----Original Message-----

**Comment by Akyhne** [comment]
Every time I do a commit?!

**Comment by Arantor** [comment]
I would also encourage not allowing merges to MOVED redirection notices.

**Comment by Akyhne** [comment]
Sounds reasonably

**Comment by XinYenFon** [comment]
I'm bit confused how you gonna do commit without local changes sorry I'm on phone and can't really do search and point you :|

-----Original Message-----

**Comment by Oldiesmann** [comment]
Not allowing merges to redirection notices is actually pretty simple, at least for topics moved after upgrading to 2.1 (if they're the "old style" there's not a lot we can do except maybe filter out topics with certain subjects) - the topics table has an "id_redirection_topic" column which will be set to the ID of the topic that the notice is referring to. If this is 0, then it's not a redirection topic (or it's an old-style one :tongue: ).

**Comment by Arantor** [comment]
Or you could check for the message's icon being 'moved' or not, which would cover all cases. But it's only really important for cases where the redirection topic is really a redirection topic, and/or it's going to be removed at some point in the future.
