### ISSUE TITLE
$txt['excamation_point']

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1601]
Typo. Should be exclamation_point. (Installer possibly should take this into account but doesn't set the default icons to use whichever language file they should be using.)

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Editor.php#L1380
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/languages/Post.english.php#L20

**Comment by Oldiesmann** [comment]
I'm amazed the typo made it into both files. I'll go ahead and fix it in the files, then look into the installer thing.
