### ISSUE TITLE
Lock/sticky while replying don't work

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1603]
To reproduce:
1. Create topic (not stickied or locked)
2. Use the full reply to topic, select sticky or locked (or both) while replying
3. Observe that none of these have been taken into account.

Applies in both regular and WYSIWYG editor. Modifying messages in the topic is fine, it's only if you try to lock or sticky a topic while you are replying to it that it does not appear to work.

Also note the comments regarding http://www.simplemachines.org/community/index.php?topic=521671.0 with respect to moderation logging being incorrect.

**Comment by Arantor** [comment]
Reason: createPost creates $topics_columns but ends up not appending the extra values onto the end of it so neither locked nor is_sticky ever get passed to the update function.

**Comment by Arantor** [comment]
Further information: this is actually a bug I didn't fix properly the first time around, since I forgot the slightly inconsistent behaviours of += on arrays when dealing with indexed arrays vs hashed arrays, though it was broken before that and the circumstances required to identify it were somewhat complex at the time since it was a bug fix while fixing something else broken.

**Comment by Arantor** [comment]
There's a typo in the commit.

**Comment by live627** [comment]
3f839970f3955f39465250c0851e53f5a47cb5ce
