### ISSUE TITLE
Potentially unnecessary query in Calendar.php

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1617]
Beginning with:

```
// There could be already a topic you are not allowed to modify
```

The values for id_board and id_topic aren't used. Not only that, but the $modSettings variable doesn't even appear to be defined anywhere.

Presumably the intent is to update a linked topic and in the process check if you could do so but as it stands, it does the query for no benefit as it doesn't use what it queries. It should either be removed or the values made use of.

That said, the subject of an event is separate from the linked topic so it probably could just be removed. Not clear, really. I just know it needs dealing with (as PHPMD is complaining about it)

**Comment by Oldiesmann** [comment]
That one is a mystery to me. Your assumptions are correct - the variable isn't set anywhere else and it appears to be there to prevent you from editing events linked to a post if you can't edit that post. I'm not entirely sure why that code is there though or what the intended usage of that $modSettings variable is. I'll have to look into this further and see what I can do about it.

**Comment by Arantor** [comment]
They weren't assumptions :tongue: It's amazing what you find when you run the source through static code analysis tools that can detect unused local variables.
