### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1623]
https://github.com/SimpleMachines/SMF2.1/commit/5b06558542fbb19e67e3200ceeec5fdfed48eaef has a typo.

Should be:

```
$topics_columns[] = 'is_sticky = {int:is_sticky}';
```

instead of

```
$topics_column[]s = 'is_sticky = {int:is_sticky}';
```

This is also the sort of thing any automated lint test being run on the code would be able to spot. Git makes it quite easy to set such things up.

**Comment by live627** [comment]
3f839970f3955f39465250c0851e53f5a47cb5ce

**Comment by Arantor** [comment]
My bad. Github is great at making it unclear as to what has been included and what hasn't.
