### ISSUE TITLE
Possible for a hidden board's existence to be leaked

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1629]
Consider the following scenario: boards A and B. B is a child of A.

User X is in groups that do not permit them to see board A but see board B. Board A will not appear on the board index, and by definition neither will board B. This has always been accepted as a design limitation (and I don't disagree)

Where it becomes interesting: if user X accesses board B or any topic in board B, the link tree will tell them about board A. They can't see it, they will receive an error if they attempt to access it - but its existence is shown to them nonetheless. The moderators for that board will also be divulged.

In fact the entire board hierarchy will be traversed, so if we're dealing with A > B > C > D > E and only board E is visible to the current user, if the user is in board E in any fashion, the entire hierarchy will be shown to them, including all the moderators thereof.

getBoardParents() is where this fun happens, and because of its performance connotations (recursive queries whose result is cached), just inserting query_see_board into the queries is no help to you, especially since you'd have to rewrite the function anyway as it correctly concludes that if it can't find the parent of a board it should have a parent of, that something is drastically wrong.

**Comment by Dragooon** [comment]
How should the behavioru be, explicitly show something like Forum Name > _Restricted Board_ > _Restricted Board_ > Your Board or simply go Forum Name > Your Board.

This is something I noticed while having the apprenticeship in SM

**Comment by Dragooon** [comment]
One quick fix would be to add a secondary test instead against groups field of boards to match against $user_info['groups'] and filter out linktree boards that way. Won't require drastic changes but would fix the issue at hand

**Comment by Arantor** [comment]
I'm not dictating how the behaviour should be. I'm merely outlining that there is a problem and that the obvious solution to that problem is problematic at best. I don't trust my own opinions as to what the 'best' solution is at present.

**Comment by Oldiesmann** [comment]
One possible option would be to somehow cache the info about which boards the user can see (if that isn't already done somewhere), then loop through each portion of the link tree, see if it's a board and if they can't see that board, unset that section of it.

I'm not sure how easy that would be, or if it's reliable, but that's definitely something we can look into.

**Comment by Dragooon** [comment]
Why can't we compare board's groups against user's groups? Might not be clean though

**Comment by Arantor** [comment]
Because if you have A > B > C where only C is visible to the current user, you will get a fatal error because the board parent 'can't be found'.

**Comment by Dragooon** [comment]
You're assuming I'm talking about the $board_info['parent_boards'] array, but I'm simply talking about filtering the array passed to the linktree (like I did in the PR)

**Comment by Arantor** [comment]
I didn't actually look at the PR. I just wasn't quite sure where you were going to be performing that check... the natural assumption is to do it inside getBoardParents() which would fail because it's called recursively. If it's done outside, where the linktree actually uses it, that would probably work.

Also note that the jumpto is going to have issues where the higher up boards won't be listed but the child level of sub-boards will be indicated. All good fun this.

**Comment by Dragooon** [comment]
Jumpto behaves fairly okay, they indicate the child level of the board which seems to be enough.

**Comment by Arantor** [comment]
It does - but if the board hierarchy is A > B > C > D and you can only see D, you're going to be shown a hierarchy that doesn't seem right. It's also not consistent with the restricted board idea going on.

I dunno.

**Comment by Dragooon** [comment]
Showing a "Restricted Board" in jumtp would probably add to the confusion

**Comment by Arantor** [comment]
That's what I said "I dunno." :tongue:
