### ISSUE TITLE
Defer all JS to footer

### ISSUE THREAD

**Issue by Dragooon** [SimpleMachines/SMF#1630]
Moving all JS to footer is probably a good idea, I don't see any reason why any scripts should be loaded in head. It makes the initial page load much faster without any disadvantages I believe

**Comment by NanoSector** [comment]
Would it not cause issues if there is anything that loads directly on the page, like a function? Or will that also need to be moved into the footer, or delayed till the page is finished loading.

**Comment by Dragooon** [comment]
Ideally there should not be anything loading directly on the page, but into a separate JS file. Or we can leave jQuery at top and allow document.ready usage.

**Comment by NanoSector** [comment]
Fair point, though my concern was any mod that adds such functionality.

**Comment by Dragooon** [comment]
Mods should be using the load JS functions, otherwise their problem :P

**Comment by XinYenFon** [comment]
I just moved all CSS/JS to function template_html_below, first load gets bit weird? (one sec white page etc...). I assume template_javascript(true); won't be needed anymore.

```
function template_html_below()
{
    global $settings;
    // load in any css from mods or themes so they can overwrite if wanted
    template_css();
    // load in any javascript files from mods and themes
    template_javascript();
    // load in any javascipt that could be deferred to the end of the page
    template_javascript(true);
    // Till someone finds a better solution slider's loader script will stay here.
    echo '
    <script>
        jQuery("#smf_slider").slippry({
            speed: ', $settings['newsfader_time'],'
        });
    </script>
</body>
</html>';
}
```

**Comment by Dragooon** [comment]
This would break a lot of inline JS

**Comment by XinYenFon** [comment]
then either we need to move inline-js to files or? move those inline-JS into function will parse after template_javascript.

**Comment by XinYenFon** [comment]
okay how about we move all inline js to function on their respected files.

function_context['current_action']_inline, and parse that after template_javascript ?

@MissAllSunday @live627

**Comment by live627** [comment]
`script` tags have `defer` as a Boolean attribute... can we use that and be done with it?

**Comment by MissAllSunday** [comment]
Theres a lot of inline js vars and theres a lot of vars that depend on another vars already been set.  Can't really get rid of all the inline js stuff either or move it to the footer.

This isn't feasible, perhaps if we have some test or there was any more uniformity in the code but thats not the case.

**Comment by Kindred-999** [comment]
I suggest closing this as a 2.1 issue. I don't see any major benefit in doing this and see potential issues that would require some fairly major template redesigns. This is Out of scope as a 2.1 request, IMO
