### ISSUE TITLE
Can not show WYSIWYG editor on post page!

### ISSUE THREAD

**Issue by smfvn** [SimpleMachines/SMF#1633]
SMF cannot show WYSIWYG editor on post page. It just shows Smileys and an Arrow Touch button, not the full editor! Even I turn on "Show WYSIWYG editor on post page by default" in Theme Setting => Member Options

**Comment by smfvn** [comment]
I also can't use "Quick Edit" while viewing a topic/post

**Comment by XinYenFon** [comment]
My fault, i forgot to add default on stuff to installer/upgrade.

Admin > Forum > Post and Topics > Post Settings > 
Show BBC Buttons on Posting and PM Send Pages

**Comment by XinYenFon** [comment]
Edit: I saw the problem and fixed with latest commit on #1634
