### ISSUE TITLE
Recycle boards and Recent.php

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1661]
Recent.php lines 119 through 133.

There's a variable, $recycling, for deciding whether recycling is used or not - except that's not the variable in the immediately-following query, which is $recycle - but hilariously even if it were used, it would be wrong because the test should be that $modSettings['recycle_enable'] is !empty, rather than the empty test it currently has. Additionally, $modSettings['recycle_board'] is explicitly assumed to exist, which isn't necessarily a safe assumption.

Oh, and the concatenation doesn't work either since concat has a higher priority than ternary, meaning that the first half the query is appended to $recycle (should be $recycling) before it's tested, meaning it's always true and then makes an invalid query.

**Comment by Dragooon** [comment]
I fixes this, also, this was hilariously bad
