### ISSUE TITLE
Error checking failure in logActions()

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1664]
logActions in Logging.php was built out of logAction, and one of the tests it does is that $log['extra'] is set.

Previously, the action was supplied directly as a parameter to logAction() but it's now wrapped... trouble is, $action is still used directly even though it doesn't exist, lines 443-444.

```
        if (!is_array($log['extra']))
            trigger_error('logActions(): data is not an array with action \'' . $action . '\'', E_USER_NOTICE);
```

Should be $log['action'] instead.

**Comment by Dragooon** [comment]
I fixes this.
