### ISSUE TITLE
Undeclared variable in Subs-Attachments.php

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#1667]
Subs-Attachments.php, line 548, makes use of $attachmentOptions, except $attachmentOptions doesn't exist elsewhere in scope. First guess is that instead of $attachmentOptions['tmp_name'] it probably means $_SESSION['temp_attachments'][$attachID]['tmp_name'] but don't quote me on that.

**Comment by Dragooon** [comment]
I fixes this
