### ISSUE TITLE
download packages page broken

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1678]
looks like the section under download new packages is not showing

**Comment by MissAllSunday** [comment]
It was deliberately made it hidden:

https://github.com/SimpleMachines/SMF2.1/issues/1458
https://github.com/MissAllSunday/SMF2.1/commit/22f493a2f36f8e882a9ddabb805efe0a682dc4cd

**Comment by illori** [comment]
it worked fine when you did that but now it is broken, the lower half of the page does not exist any longer.

**Comment by illori** [comment]
oh i see... the collapse was changed? it is now the text with no arrow or anything to show that it is collapsed.

that makes it really hard to tell there is something else on the page

**Comment by MissAllSunday** [comment]
I just tested it with the latest release branch and re-tested it with the recent merge from Antes, it still works as intented on Opera 12 Firefox and Chrome

**Comment by illori** [comment]
yea it works, but there is no visible way to tell that clicking on the text does anything. i believe it used to have an arrow to show it was collapsed.

**Comment by XinYenFon** [comment]
Agree it needs a collapse button. But not a big deal.

**Comment by MissAllSunday** [comment]
We can add two classes, collapsed and uncollapsed each with a small arrow and then just add that class next to the link, since this collapsed option isn't controlled by an user setting, we can just change the class to uncollapsed when the link is clicked

**Comment by illori** [comment]
sounds good to me, it has the visual which will solve the problem.
