### ISSUE TITLE
Remove useless/unused bbc's

### ISSUE THREAD

**Issue by mcblaber** [SimpleMachines/SMF#1684]
Old discussion URL - http://www.simplemachines.org/community/index.php?topic=516416

I think its about time we really remove the obsolute bbc's that 99.9% of SMF users don't use. Such as glow, shadow, marquee, and FTP. This will help make the slow parse_bbc a bit faster and can open up the possibility for more useful bbc's in the future. (Like a spoiler bbc for instance.)

**Comment by illori** [comment]
i thought @dragooon did some work on the parser that would make this a non-issue. [or not so much of an issue]

**Comment by Dragooon** [comment]
The parser work was mostly for memory issues, this might help speed up things a bit.

**Comment by mcblaber** [comment]
Regardless I don't think we should have something practically no one uses. Hasn't the marquee tag been non-html compliant for years now?

**Comment by illori** [comment]
do you mean the move tag? it does use marquee

although it is not completely valid

Line 230, Column 48: Element marquee not allowed as child of element div in this context. (Suppressing further errors from this subtree.)

```
                            <div class="inner" id="msg_94"><marquee>test</marquee></div>
```

**Comment by mcblaber** [comment]
Yes the move tag, forgot SMF used different terminology for it. :P

**Comment by Oldiesmann** [comment]
The marquee tag isn't valid HTML and never has been, but is just something that most browsers have come to support over the years. Wikipedia has more details: https://en.wikipedia.org/wiki/Marquee_tag

**Comment by mcblaber** [comment]
Regardless of validity, I don't think it's needed. I can't think of 1 forum that has actually used it once. (Along with glow and FTP)

**Comment by margarett** [comment]
And it's being unsupported fast... There was a support topic (more or less recently) where that question emerged.

**Comment by Oldiesmann** [comment]
If we do remove it, we should offer it as a mod so those who do use it (as few as they may be) can still have it.

**Comment by XinYenFon** [comment]
This is actually duplicate of #1545 can be closed :)
