### ISSUE TITLE
Installation/Upgrade (minor)

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#1708]
1- The "Continue" button stays active, even when the system is actually doing work. The button should not be an active button until the system is ready for the user to hit continue.
(I know that clicking it while the upgrade is running has no effect, but if the button can't be used, it should look inactive)

2- The Upgrade "progress" does not move. it went from 20%, starting the database stuff...   which ran for a minute or two with no movement to the progress bar), stayed at 20% while continue was pressed several times and then jumped to 100% right at the end.

3- the "delete upgrade and go to your installation" link does not appear to work,,,   It does delete the upgrade,php file... but never resolves the website. (However, clicking STOP and then reloading the page works just fine and allows access to the site)

**Comment by Dragooon** [comment]
Quick question, what were you upgrading from?

**Comment by illori** [comment]
i have not had issues with the delete upgrade and go to your install. it has always worked for me on my localhost install.

the issue with the percentage i think has been reported before... #1214

**Comment by Kindred-999** [comment]
I was doing an upgrade form a previous Alpha install

**Comment by Kindred-999** [comment]
the first issue on the list above seems to still be there...

and it looks like the second issue has never been officially addressed (or if it was, the fix was never tagged to either of the open issues)

**Comment by live627** [comment]
2 took WAYYY too long to debug

**Comment by albertlast** [comment]
Can be closed?

**Comment by MissAllSunday** [comment]
yup
