### ISSUE TITLE
cron.php only working on timestamps which are multiple of 15

### ISSUE THREAD

**Issue by Dragooon** [SimpleMachines/SMF#1723]
This is mostly a question for @Arantor, is there any particular reason you made it so that the web requested cron.php works on timestamps which are multiples of 15?

**Comment by Arantor** [comment]
Yes. The idea is to avoid hammering a server with many concurrent requests by suggesting to the browser that it might already have it. Cache headers might need to be tweaked to help with this though.

**Comment by Dragooon** [comment]
This is a pain to test with, hmm, there should be a better middle ground

**Comment by Arantor** [comment]
In an ideal world you'd call cron.php properly from a cronjob which doesn't perform any tests. But the rest is simply about trying - not ideally! - to throttle calls to it, after I saw comments about XenForo's deferred system having similar issues.
