### ISSUE TITLE
Hardcoded text in Upgrade.php

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1725]
Whole upgrade.php hardcoded :P I'll deal with it later today or don't know week :paw_prints:

**Comment by ghost** [comment]
That has always been and if memory is right their is a reason ...

**Comment by Oldiesmann** [comment]
Trying to internationalize the status messages would be a real chore because of the way the upgrade script works.

**Comment by ghost** [comment]
that is what I thought it was but couldnt remember and didnt wanna seem dumber than usual ... their was a topic on this I saw it once but cant remember where :/

**Comment by Arantor** [comment]
I'd argue it doesn't really matter that it isn't translated.

**Comment by ghost** [comment]
so in essence you agree with me :P

**Comment by Arantor** [comment]
Well, there's certainly a reason for it, and it has always been the case. As to whether it _needs_ to be translated, I don't think you ever actually said either way on the subject :tongue:

**Comment by ghost** [comment]
thought it was evident next time ill spell it out for you... :P

**Comment by Arantor** [comment]
Like you, subtle is not my strong point :tongue:
