### ISSUE TITLE
Register vs Sign Up

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1728]
Their is a topic in friends board regarding the usage of Sign Up instead of Register, if memory is correct (albeit its not the best) it seemed that people were in favor of doing this, its only a few changes in index.english.php maybe this should be done?

**Comment by Arantor** [comment]
http://www.simplemachines.org/community/index.php?topic=494707.0 for reference. Not a lot of discussion, but the few that did were positive about it.

I'd argue it is more likely to encourage registrations.

**Comment by Oldiesmann** [comment]
How much should we change this - should it just be a language string change or should we also change the "action" and other things associated with it?

**Comment by ghost** [comment]
why would you have a forum if not for people to register and post for most cases.  Its really only on the slim chance you will go to  forum that isnt open to people registering.

As for how much that's really up to you, Aesthetically its simple, question should be asked to people really look at the url?

**Comment by Arantor** [comment]
I'd change the URL personally. But that's because I have other reasons for suggesting the change I don't want to make public. :tongue:

**Comment by ghost** [comment]
Not really a hard change either way :D

**Comment by AngelinaBelle** [comment]
Tell or tell not. There is no tease.

**Comment by Arantor** [comment]
Providing the reason draws undue attention to the change which is precisely something I do not wish to do.

**Comment by ghost** [comment]
Soo this then goes back to the original question, @AngelinaBelle whats your opinion?

**Comment by AngelinaBelle** [comment]
If actual data shows that sign up is more inviting and leads to better community growth, then that is better evidence than a few geeks arguing about what they themselves prefer.

To change or not change the url matters only to a few geek devs.
And I assume the teasing is meant to motivate a few geeks to read the code.

**Comment by ghost** [comment]
well if no-one does this before i get back then ill make a commit to do this :)
