### ISSUE TITLE
	0000908: Child boards get marked new where their is a new post in a grand child that isn't visible.

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1734]
For example the dev board here gets marked new when posts are made in child boards of it that we can't see.

Ref: http://dev.simplemachines.org/mantis/view.php?id=908

**Comment by albertlast** [comment]
Got a board with 2 sub layer
1 the mainboard
2 the first sub board
3 the sub board below 2

Create a user with view rights of board 1 only,
create with a different one topics in board 2 and 3 and make some replay in ther.

With the limited user i see no new flag of board 1,
issue got fixed?

**Comment by Sesquipedalian** [comment]
No, the problem still exists. If the user can see boards 1 and 2, but not board 3, then a post in board 3 will result in a "new" link appearing next to board 2 in the Sub-boards list on the board index.
<img width="320" alt="screen shot 2018-04-24 at 12 14 15 pm" src="https://user-images.githubusercontent.com/191731/39205844-1bf0dcfe-47b9-11e8-80dc-76609bba35ab.png">
