### ISSUE TITLE
SMF Error's during clean SQLite3 install

### ISSUE THREAD

**Issue by tinoest** [SimpleMachines/SMF#1740]
```
[Mon Jun 02 20:52:20 2014] [error] [client 127.0.0.1] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to open database: unable to open database file' in /Users/tino/SMF2.1/Sources/Subs-Db-sqlite3.php:65\nStack trace:\n#0 /Users/tino/SMF2.1/Sources/Subs-Db-sqlite3.php(65): SQLite3->__construct('/Library/Docume...')\n#1 /Users/tino/SMF2.1/Sources/Load.php(2732): smf_db_initiate('localhost', '/Library/Docume...', '', '', 'smf_', Array)\n#2 /Users/tino/SMF2.1/index.php(63): loadDatabase()\n#3 {main}\n  thrown in /Users/tino/SMF2.1/Sources/Subs-Db-sqlite3.php on line 65, referer: http://127.0.0.1/SMF2.1/index.php
```

The above just resulted in a blank screen via the web browser, I checked the logs and got the above and deduced that it was due to permissions. If something could be returned to the screen that would be useful. 

```
[Mon Jun 02 20:57:11 2014] [error] [client 127.0.0.1] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 130968 bytes) in /Users/tino/SMF2.1/Sources/Subs-Db-sqlite3.php on line 1154, referer: http://127.0.0.1/SMF2.1/install.php?step=5
```

It was previously complaining at 128M , I don't see how it needs that much memory to do anything mind. I can't allocate any more as the VM only has 384M allocated to it.

**Comment by tinoest** [comment]
```
[Mon Jun 02 21:09:20 2014] [error] [client 127.0.0.1] PHP Fatal error:  Call to a member function finalize() on a non-object in /Library/WebServer/Documents/SMF2.1/Sources/Subs-Db-sqlite3.php on line 747, referer: http://127.0.0.1/SMF2.1/install.php?step=2
```

I forgot the above first time round, not sure what's calling that at the moment.

**Comment by Oldiesmann** [comment]
We can probably add code to catch common exceptions like that, but the fact that the error wasn't displayed at all is due to the PHP configuration - specifically PHP's "display_errors" setting. In most cases you don't want errors displayed to the end user like that.

Are you sure the file and line number are correct for that second error? My copy of that file only has 976 lines of code. Step 5 of the install script is the part where you set up the admin account, but there shouldn't be anything in that function (AdminAccount() in install.php) that would cause it to run out of memory.

I'm not sure what's causing the second error either. That function is smf_db_free_result, but $smcFunc['db_free_result'] isn't called anywhere in the function for step 2 of the installer (DatabaseSettings()).

**Comment by tinoest** [comment]
My file also has 976 lines of code, I assumed PHP was having a bit of a fit and getting itself very confused. I'll try and replicate the error again. 

It all seemed to compound itself from the first set of error's though.

**Comment by tinoest** [comment]
Different error's this time, same clean install. 

```
[Tue Jun 03 21:22:58 2014] [error] [client 127.0.0.1] PHP Fatal error:  Call to a member function fetchArray() on a non-object in /Users/tino/SMF2.1/Sources/Subs-Db-sqlite3.php on line 498
[Tue Jun 03 21:23:16 2014] [error] [client 127.0.0.1] PHP Fatal error:  Call to a member function fetchArray() on a non-object in /Users/tino/SMF2.1/Sources/Subs-Db-sqlite3.php on line 308, referer: http://127.0.0.1/SMF2.1/install.php?step=2
```

All seems to be relating to $handle not being a SQLite3 object resource for some reason.

**Comment by tinoest** [comment]
Got through the above by changing the following functions...

```
/**
 * free_result
 *
 * @param resource $handle = false
 */
function smf_db_free_result($handle = false)
{
  if(!is_resource($handle))       
    return false;

  return $handle->finalize();
}
```

An the following 

```
/**
 * 
 * @param resource $handle
 */
function smf_db_fetch_array($handle)
{
  if(!is_resource($handle))
    return false;

  return $handle->fetchArray();
}
```

Still getting this final error. 

```
[Tue Jun 03 21:46:01 2014] [error] [client 127.0.0.1] PHP Notice:  Undefined index: theme_dir in /Library/WebServer/Documents/SMF2.1/Sources/ScheduledTasks.php on line 1175, referer: http://127.0.0.1/SMF2.1/install.php?step=4
[Tue Jun 03 21:46:01 2014] [error] [client 127.0.0.1] PHP Notice:  Undefined index: default_theme_dir in /Library/WebServer/Documents/SMF2.1/Sources/ScheduledTasks.php on line 1175, referer: http://127.0.0.1/SMF2.1/install.php?step=4
[Tue Jun 03 21:46:05 2014] [error] [client 127.0.0.1] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 130968 bytes) in /Library/WebServer/Documents/SMF2.1/Sources/Subs-Db-sqlite3.php on line 1154, referer: http://127.0.0.1/SMF2.1/install.php?step=4
```

**Comment by tinoest** [comment]
Tried increasing the VM to 756M and allocating 512M to php but it still runs out of ram, with a error to a line that doesn't exist. 

```
[Tue Jun 03 22:40:46 2014] [error] [client 127.0.0.1] PHP Notice:  Undefined index: theme_dir in /Library/WebServer/Documents/SMF2.1/Sources/ScheduledTasks.php on line 1175, referer: http://127.0.0.1/SMF2.1/install.php?step=5
[Tue Jun 03 22:40:46 2014] [error] [client 127.0.0.1] PHP Notice:  Undefined index: default_theme_dir in /Library/WebServer/Documents/SMF2.1/Sources/ScheduledTasks.php on line 1175, referer: http://127.0.0.1/SMF2.1/install.php?step=5
[Tue Jun 03 22:40:54 2014] [error] [client 127.0.0.1] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 130968 bytes) in /Library/WebServer/Documents/SMF2.1/Sources/Subs-Db-sqlite3.php on line 1154, referer: http://127.0.0.1/SMF2.1/install.php?step=5
```

**Comment by tinoest** [comment]
Fixed the above, should of been the following for the functions, this fix's all the aforementioned error's. Not sure how I can commit a file with these changes though. 

```
/**
 * 
 * @param resource $handle
 */
function smf_db_fetch_array($handle)
{
  if(!is_object($handle))
    return false;

  return $handle->fetchArray();
}
```

```
/**
 * free_result
 *
 * @param resource $handle = false
 */
function smf_db_free_result($handle = false)
{
  if(!is_object($handle))       
    return false;

  return $handle->finalize();
}
```

**Comment by Oldiesmann** [comment]
To commit a file with the changes:
1. Fork this repo (click "Fork" at the top right of the page)
2. Download your changes to a computer or server (either use a client such as GitHub for Windows or SourceTree or use the command line - search documentation here for further details).
3. Make changes to the file and commit them locally, making sure to sign-off.
4. Push changes to GitHub (the method for this depends on what client you're using)
5. Create a Pull Request here. From your repo's page, click the green button in the upper left corner. It should come up and show what changes have been made.
6. Confirm that the details are correct and click "Create Pull Request".

Then we will review the changes and merge them in.
