### ISSUE TITLE
undefined variables in template issues...

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#1742]
Build as of 4-June 9:00 EDT (responsive theme included in build)

When making a new post...
Type of error: Undefined
8: Undefined index: url
...../index.php?action=post;board=4.0
File: /....../Themes/default/index.template.php
Line: 384

When viewing a post

Type of error: Undefined
8: Undefined index: colname
..../index.php?topic=24.0
File: /..../Themes/default/Display.template.php
Line: 653

Type of error: Undefined
8: Undefined index: colname
...../index.php?topic=24.0
File: /...../Themes/default/Display.template.php
Line: 616

**Comment by illori** [comment]
i am also getting 

Type of error: Undefined
8: Undefined index: show_modify
github2.1/index.php?topic=21.0
File: F:/wamp/www/github2.1/Themes/default/Display.template.php
Line: 407

**Comment by illori** [comment]
Type of error: Undefined
8: Undefined index: show_profile_buttons
github2.1/index.php?action=pm;f=sent
File: F:/wamp/www/github2.1/Sources/PersonalMessage.php
Line: 1108
