### ISSUE TITLE
MIssing editor buttons

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#1743]
Responsive theme build 4-Jun

Post screen and edit scree have no buttons at all above the post-box.

**Comment by illori** [comment]
fix is to remove call to superfish in theme.js [also need to remove superfish from who.php]

**Comment by Kindred-999** [comment]
confirmed that works... Someone wanna commit that?

**Comment by illori** [comment]
@antes should as he did the removal of superfish and missed this one
