### ISSUE TITLE
Checkbox next to first topic in board index

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1744]
Browser: iPad, Safari or chrome.
Should be checkbox next to every topic?

![image](https://cloud.githubusercontent.com/assets/3267025/3174374/2706b2d0-ebf1-11e3-9eff-0c6b246c3014.jpg)

**Comment by illori** [comment]
that does not look like the board index, do you mean the message index?

**Comment by AngelinaBelle** [comment]
Doh! Typo.  To me, it is the index of this board.  Just like the index within a book is the book's index.  Hence my typo.  Fixed title.

**Comment by illori** [comment]
in your profile do you have checkboxes enabled for quick moderation?

**Comment by XinYenFon** [comment]
The problem is that checkbox doesn't belong there... Its outside of the container, and I hide all the moderation box on small screens (weird :P)

**Comment by AngelinaBelle** [comment]
quick moderation enabled as check boxes. That's the default on the turtleshell demo.
Quick moderation stuff is present at the bottom of the topic index. 

If I switch to icons, all quick moderation stuff goes away.
If I switch to none, all quick moderation stuff goes away.

iPad screen is not too small for quick moderation. Mini might be. Don't know.

**Comment by Oldiesmann** [comment]
That checkbox is appearing because it's for quick moderation. I would imagine it only appears next to that topic because you don't have permission to delete other users' posts.

**Comment by AngelinaBelle** [comment]
I is admin.  All your posts are belong to me.

**Comment by Arantor** [comment]
Btw, Mini is not too small to have quick moderation icons. Also note that there are situations even non-moderators will be able to make use of quick moderation (namely: unread/unreadreplies being able to mark individual or all topics read without browsing)

**Comment by AngelinaBelle** [comment]
This does not appear to be fixed.  Please reopen.
the "quick moderation" stuff at the bottom of the list of topics is there, as well (as it was from the beginning)

**Comment by XinYenFon** [comment]
yea after the last debug :P i see @AngelinaBelle 's device is way over our current test resolutions (we are focusing on 480p - 720p because lack of device), I applied a little patch to my test site. I think that 'll resolve the problem. heh actually I can use my old (very old) pc to test changes. Its 1024x768 or something :paw_prints:

**Comment by AngelinaBelle** [comment]
Ios devices seem to be a little different than the others.

http://www.javascriptkit.com/dhtmltutors/cssmediaqueries2.shtml
