### ISSUE TITLE
Below-Post More "button" requires mouseover? hover?  Does not work on iphone or ipad

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1745]
On the ipad, I can click on the more button, but nothing happens.  
The "More" is not a button and has no javascript applied to its events. On devices with mouse pointing, "mouseover" is enough to reveal the concealed &lt;ul&gt; list.
This behavior appeared June 4 on the turtleshellprod test site.  According to the site notes, the previous update before june 4 was may 14.
What could have affected the more button behavior between may 14 and june 4?

**Comment by illori** [comment]
you mean the button to show more smileys? it seems to work fine for me once i fix the full editor showing.

**Comment by AngelinaBelle** [comment]
No.  The one below the post.  The one that is supposed to allow me to modify my post, <s>add attachments</s>, that sort of thing.

Fixed title for clarity

**Comment by illori** [comment]
you mean attachments and other options? does it work in the desktop browser?

**Comment by Kindred-999** [comment]
I think she means the "More" dropdown that is under each post...   allows you to select - modify, remove, split, issue warning

And yes, that button works on a desktop browser (FF, Chrome tested)

**Comment by illori** [comment]
works for me on my android phone using chrome.

**Comment by XinYenFon** [comment]
Menu buttons both main & quick on post needs more testing that's for sure.

**Comment by AngelinaBelle** [comment]
I have updated the first comment after investigating a little further -- the problem seems to be with hover behavior.  What was on Turtleshell on June 3 (build from May 14?) allowed me to "click" on that "More" button-looking-thing to make the &lt;ul&gt; list visible

**Comment by AngelinaBelle** [comment]
This seems to work now, as of 9c2fb73fc2ddd96d18c669fcc54e5f47df305454 and probably a little earlier.
