### ISSUE TITLE
Cannot tell when wysiwyg button is pushed -- contrast too low

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1746]
This dates to an earlier version, before the editor buttons all went away :)
I see this problem on an iPad, chrome or safari.

Need more contrast.  Old eyes.  Dirty glasses. Whatever.

![image](https://cloud.githubusercontent.com/assets/3267025/3174522/6ed581bc-ebf2-11e3-95e0-04d6c70a1712.jpg)
![image](https://cloud.githubusercontent.com/assets/3267025/3174523/6ed8a82e-ebf2-11e3-9a7f-ec891c945fb0.jpg)

**Comment by Dragooon** [comment]
Ehm...oh wow, I had no idea that's what that button did :P. It really should be clearer that that is the WYSIWYG button.

**Comment by AngelinaBelle** [comment]
It is the same icon used in the CURVE theme.
You got a better one?  WYSIWYG just won't fit. :)

**Comment by Dragooon** [comment]
Shouldn't be with the BBC buttons IMO, and I never knew that button was supposed to toggle WYSIWYG. This should ideally be placed somewhere else.

**Comment by illori** [comment]
@dragoon it has always been there, i am not sure we should really move it anywhere else. maybe change the icon ... but that could confuse users too.

**Comment by Oldiesmann** [comment]
Every WYSIWYG editor I've ever seen has the "switch modes" button in the same place as all the formatting buttons. I'm not sure we can really put it anywhere else without making things look weird.

**Comment by Kindred-999** [comment]
actually, that is a fairly standard icon for code/non-code view, I think...

and that is the standard placement in every editor. :)

**Comment by XinYenFon** [comment]
I already fixed this :) just looking for other issues and general stuff.

**Comment by AngelinaBelle** [comment]
Looks much better as of  June 8.  Thanks.
