### ISSUE TITLE
iPhone, Safari or chrome -- login popup hard to use

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1748]
The login box is hard to use from safari or chrome on the iPhone because it cannot be shrunk and is difficult to scroll.  The page beneath scrolls readily, but the login popup won't move very far, no matter how I try. That means parts of it are often cut off, and it is especially hard to get to the "always stay logged in" checkbox.  And the login button is impossible to get to in landscape mode.

Portrait mode is a bit better.

**Comment by XinYenFon** [comment]
On small screens its really hard to use /blame NanoSector (aka Yoshi) :P I'll look into it.

**Comment by AngelinaBelle** [comment]
If is easy to fix, then good.  Otherwise, well, it works, even if it is awkward.
Less important than missing nav bar. Maybe
