### ISSUE TITLE
[Display] Edit button tooltips don't work on touch screens

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1753]
These depend on mouse over.  But there is no mouse over on a touch screen.
Can they also give tooltips when I rest my finger on the button for a long time, rather than clicking?

**Comment by illori** [comment]
what edit button tooltip?

**Comment by AngelinaBelle** [comment]
Ok. Back to the desktop for me.  I thought they were there, though I never use them.

**Comment by illori** [comment]
so that means they are not there? so this is not a bug?

**Comment by XinYenFon** [comment]
tbh I don't understand the issue here :/

**Comment by AngelinaBelle** [comment]
OK.  I get to a desktop.

On the desktop, when I hover over edit buttons, I get tooltips like "Bold" and "Show Source".
I cannot get these on an ipad; I assume this is true for all touchscreen devices.

Is there anything to be done, or do we just have to note that this doesn't work?

**Comment by illori** [comment]
i would think the image on the button would be enough to explain what the function is that the title text is not needed to be present on a mobile device.

**Comment by AngelinaBelle** [comment]
I wouldn't know what to think about some of those button icons(especially the last 2)
I am merely reporting the difference between designed behavior and observed behavior.

**Comment by illori** [comment]
which last 2? the remove formatting icon and WYSIWYG? those are not used often enough IMO to need them to work on a mobile device.

**Comment by AngelinaBelle** [comment]
I am merely reporting bugs -- cases where observed behavior differs from designed behavior.
I have no actual data on whether any users ever need to use these features, or those buttons, for that matter.

**Comment by Kindred-999** [comment]
I don't think tooltips work on touch devices...

**Comment by AngelinaBelle** [comment]
That's a shame because the last two buttons -- I would pnt even know how to come up with a self-explanatory icon.

"Known issue" then.  No fix.

**Comment by Oldiesmann** [comment]
If you press and hold the button for about a second it should show the tooltip. That's how you replicate "hover" on touch devices.

**Comment by AngelinaBelle** [comment]
Yes.  It is a long hold.  No way to make it quicker.  No plan to change this behavior.

Close this?
