### ISSUE TITLE
Are there any things that depend on hovering or mouse over?  They might not work on touch screens.

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1754]
Other than edit button tool tips, what are these?
Is there another event that can be substituted?

(edited for clarity, I hope)

**Comment by illori** [comment]
onMouseOver is only found in some comments in smf_jquery_plugins.js. where are you finding this an issue?

**Comment by AngelinaBelle** [comment]
I don't know where it might be an issue. 
But I am willing to test parts of the app on a touchscreen device.

Anything that might depend on hover or onMouseover behavior might not work as expected on touchscreen devices.

**Comment by illori** [comment]
my point is it is not in the smf source but in some comments. how can you test something that does not exist in smf?

**Comment by AngelinaBelle** [comment]
Not sure what you mean about comments and things that do not exist,  I am merely asking if there is any code that exists in SMF that depends on the user doing some kind of mouse over or hovering 

The editor button tooltips are done with title=, for example, and don't work on an ipad. 
So that's not a actual event, but an example of some intended feature of SMF which will not work on touch screens.  It is not nonexistent, and it is not in comments.

My question is -- is there anything else besides those button titles that uses title or some kind of mouse over or hover event?  Are there any jQuery hover or mouse over things, or css :hover   Things that I should be testing on a touch screen?

**Comment by illori** [comment]
you specifically asked about onMouseOver, this function is not found in smf at all. if you mean mouse hover functions that is different from onMouseOver.

**Comment by AngelinaBelle** [comment]
I didn't have room in the title for 
"Anything in SMF that involves some kind of hovering or mouse over or something like that, whether it is caused by actual onMouseover events or title= or alt= or some kind of css or something that I don't know about because I don't know jQuery and I am not a dev please let me know so I can test becau it might not work as designed on touchscreen devices"

**Comment by illori** [comment]
i would think, that questions on what needs to be tested may be better asked on the forum and then report the issues on github. this way we dont build up a list of questions that may never be resolved on github.

**Comment by AngelinaBelle** [comment]
Closed
