### ISSUE TITLE
Reply to message exceeds subject maximum length

### ISSUE THREAD

**Issue by jwit** [SimpleMachines/SMF#1759]
This issue was already present in versions 2.0.x but I never got around to posting it earlier. 

If a message has a subject that is between 78 and 80 characters long and you reply to it then RE: is added to the subject to make the total length of the subject longer than 80 characters. In version 2.0.x users received an error about exceeding the maximum allowed length and had to manually change it. In my tests with 2.1 I see the error in a flash but it goes away and the message is saved with the longer subject. 

A solution I think would be to trim the subject when RE: is added.

**Comment by Oldiesmann** [comment]
I'd be in favor of silently ignoring the problem and just allowing a slightly longer subject if "Re: " is added to it.

**Comment by NanoSector** [comment]
SMF 2.1 trims the subject if it is too long. I see no errors of any sort.

**Comment by AngelinaBelle** [comment]
Here is the behavior I can see in 2.1, as of June 28:
1) when editing a subject line (new topic, reply, or. Kiddy topic)-- the input files has max length 80, which means the user cannot enter more than 80 chars.
2) reply subject line: can have up to 84 char when "re: " is added, but is still shown in an 80character input field. Behavior during editing might be browser dependent. 
  -- example (chrome, iPad) "re: " . 80 char.  Can delete 1 char.  The remaining 83 char are saved and appear the next time I check, but I cannot add any more char to the subject.

This behavior seems reasonable enough, if we are sure it is consistent across browsers.  If this is not the case,mso me other workaround might be required to achieve consistency.  Allowing 84 chars in subject for reply in html, for example.

Is the trend in SMF to phase out subject-per-message in favor of subject-per-topic?

**Comment by illori** [comment]
there are still per message subjects, they just dont show by default for some reason and are an option to show.

**Comment by AngelinaBelle** [comment]
Ok, so whatever the trend, the subject has to be supported properly.
1) there are no error messages
2) 2.1 seems to handle this somewhat gracefully, not trip uncapping subject lines to add re: 
3) the only quibble is that it is stuffing 84 characters into an 80 character input field on edit, which seems like a non-standard html thing to do, and could lead to slightly broken results some day on some browser.

Is 3) an issue?
