### ISSUE TITLE
Alerts needs to be finished

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#1766]
We need to finish the alerts system. At the very least, the "All Alerts" link needs to work (show all alerts sorted by date in descending order), though we may want to see if there are other areas that can be improved as well.

**Comment by Dragooon** [comment]
To add to this, I want to add Desktop notifications.

**Comment by live627** [comment]
More info http://www.simplemachines.org/community/index.php?topic=523484.msg3704694#msg3704694

**Comment by live627** [comment]
@Dragooon how's it going?

**Comment by Dragooon** [comment]
I got quite a bit done, not sure if it's finished yet though

**Comment by smfvn** [comment]
There is a mistake in the file: other/install_2-1_mysql.sql line 1857: ('enable_ajax_alerts', '1')); excess a ')' .
It should be ('enable_ajax_alerts', '1');

**Comment by Dragooon** [comment]
@smfvn Yeah I'm aware, I'll fix this later

**Comment by Oldiesmann** [comment]
Some other stuff related to this that we need to handle:
PMs - there are notification options for emails when you receive a new PM or get a reply to a PM you sent, but neither has any effect. The old PM notification options still take effect here.

Moderation stuff - There's still a scheduled task related to notifying moderators of content requiring approval. This should be moved to alerts as well (adding another task to CreatePost-Notify.php should do the trick here - just need to modify the data sent to that task class to include whether or not the post/topic is approved probably)

Also, we need to figure out what to do with alerts in regards to #2118

**Comment by BitFros7y** [comment]
Didn't feel like opening new ticket as i can see system is not finished yet.
Problems i noticed:

Turn notification on when you post or reply to a topic. (These setting can not be saved)
When someone reply to your topic you dont get an alert (Guess its affected by bug above)

**Comment by illori** [comment]
which button are you clicking to turn on the notification? do you have the alerts enabled under notifications in your profile? have you browsed your forum for sometime after to see that the alert shows up?

you are talking about the options on the notifications page? "Turn notification on when you post or reply to a topic." and  "When sending notification of a reply to a topic, send the post in the email (but please don't reply to these emails.)" i think this is a separate issue, the alerts system should replace that function but it has not yet and maybe that was left as a reminder to convert that over.

**Comment by illori** [comment]
actually it seems to work just fine if you use the options lower on the notifications page for following a topic. we need to remove the checkboxes at the top of the page

**Comment by Dragooon** [comment]
Closing this, pretty sure we finished Alerts
