### ISSUE TITLE
Text pasted into post can create bad font BBC

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1768]
I copied the Chrome version from another browser window into the WYSIWYG post editor.
The result was 
[font='Segoe UI', Tahoma, sans-serif]33.0.1750.146, Windows 7[/font]

Which rendered as shown above, because the font BBC cannot accept parameters in that format.
It kind of spoils the wysiwyg thing.  It always looks fine in the wysiwyg editor, but never after parse_BBC gets hold of it.

http://test2.turtleshellprod.com/index.php?topic=34.0

**Comment by Oldiesmann** [comment]
That sounds like more of an issue with the bbcode parser/editor itself rather than SMF's implementation of the editor. Might want to file an issue on the SBBCodeParser project (https://github.com/samclarke/SBBCodeParser) instead.

**Comment by AngelinaBelle** [comment]
Me?  I am not sure how to tell whether this is an SBBCodeParser issue or whether it has to do with how SMF has implemented it, defined the font tag, or what have you.

I can't even find add_bbcode in the repo here...

If anyplace, the html -> bbcode magic seems to happen in jquery.sceditor.bbcode.js on line 941 (?). I don't understand how the html attribute got so hashed,though.  It is as though additional string were inserted later, and the quotes were not stripped.

**Comment by AngelinaBelle** [comment]
So [font='Segoe UI', Tahoma, sans-serif]Version[/font] is bad, but
[font=Segoe UI, Tahoma, sans-serif]Version[/font] is better, and results in <font style="font-family: Segoe UI, Tahoma, sans-serif;" ... >.  

Perhaps the rule for creating the [font] tag from html could be re-defined to strip all single-quotes since parse_bbc clearly does not like them.

I don't know if this is actually designed behavior in the sBBCodeParser or not, so I have started with a question at http://www.sceditor.com/documentation/plugins/bbcode/#comment-1432547366

**Comment by AngelinaBelle** [comment]
This is designed behavior for sceditor.
Because some font names contain spaces, they must be enclosed in quotes.
Giving a comma-separated list of several font families is valid CSS -- http://www.w3schools.com/CSSref/pr_font_font-family.asp

Because the SMF font tag is designed for only one font family, there is an incompatibility between  SBBCodeparser and  SMF.
There are two choices to fix it:  change parse_bbc or change SBBcodeparser.

Sam Clark suggested one simple approach -- simply to strip out the quotes.  That could create invalid CSS, but at least would create something parse_bbc could handle gracefully.

I think that another option would be logic to. 1) if the shortest match for '._'   Or "._" matches the entire string, then do nothing 2) otherwise, remove every instance of quote-enclosed string, as will as the comma that follows (if any) -- a slightly fussy (for me, anyway) piece of regex.

Here is a "strip quotes" solution mentioned by Sam Clark:

```
$.sceditor.plugins.bbcode.bbcode.set('font', {
    format: function ($element, content) {
        var font;

        // Get the raw font value from the DOM
        if (!$element.is('font') || !(font = $element.attr('face'))) {
            font = $element.css('font-family');
        }

        // Strip all quotes
        font = font.replace(/['"]/g, '');

        return '[font=' + font + ']' + content + '[/font]';
    }
});
```

He also provided a fiddle to demonstrate it:
Demo: http://jsfiddle.net/samc/3a2ZH/

**Comment by Oldiesmann** [comment]
Font tag is completely broken now. Nothing I throw at it will work.

**Comment by illori** [comment]
can we get the font tag fixed?
