### ISSUE TITLE
Drop menu fix

### ISSUE THREAD

**Issue by Mavn** [SimpleMachines/SMF#178]
This fix needed for proper view with long words
index.css
.dropmenu li ul  
    width: 17em;

sample issue view with russian language
http://simple-machines.ru/04.091.png
http://simple-machines.ru/04.09.png

**Comment by XinYenFon** [comment]
Can you try 

min-width: 16em; ?

**Comment by Mavn** [comment]
I am tried and it doesn't work

**Comment by emanuele45** [comment]
Seems that has been applied at some point.

Thanks for the report Mavn
