### ISSUE TITLE
Broken html when not-approved user requests password-change email

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1780]
![image](https://cloud.githubusercontent.com/assets/3267025/3211260/9045d556-ef0b-11e3-85b5-05b8de8f9208.jpg)

p.S.

Also -- user actions should not be met with an error response.  
"I'm sorry, user, you can't do that" is not a software error, and shouldn't look like one.

**Comment by Oldiesmann** [comment]
I don't see why there's a problem with displaying an error here. Why allow someone to reset their password if their account isn't even active yet? They'll just get another error when they try to login anyway. The only other option would be to rewrite a bunch of stuff to make un-activated users its own special group like some systems do (and I'd rather not go that route as that just makes things a lot more complicated).

**Comment by illori** [comment]
if you look more closely at the error message you will see "class='padding'> showing in the error, html should not show.

**Comment by XinYenFon** [comment]
Something wrong with that error code (ID), normally smf does id="an_error_you_see" but in this error it outputs whole text string.

**Comment by AngelinaBelle** [comment]
I understand  that forbidding unapproved users from changing password might be the appropriate response.  I only think that the user should not be told that the software has encountered some kind if a error -- I think this is a normal outcome of a somewhat-normal request, and some kind of "you don't have permission to do that" message is appropriate instead of an error message.

However -- I don't know whether it would be wise at this point in the release cycle to discuss that kind of change, as that kind of change might require other changes that risk breaking other things.
I have rearranged my original message for clarity.

**Comment by illori** [comment]
what action were your doing when you got this error? i could only get this error when trying to log in when the user had not done the email validation.

**Comment by AngelinaBelle** [comment]
Very much like that, except admin approval required instead of email validation.
- registered
- admin approval required 
- attempted to log in later, was told password was wrong.
- attempted "forgot password"
- got message

**Comment by illori** [comment]
```
$context['error_code'] = isset($error_code) ? 'id="' . $error_code . '" ' : '';
```

removing this line from Errors.php will remove the visible html.

https://github.com/SimpleMachines/SMF2.1/commit/cf87e450f54bf5475ec3b513e79690079b1f8e11 commit added this line. no idea what other effect it may have to remove this line, but it was not preset in 2.0.

**Comment by AngelinaBelle** [comment]
Somehow, that $error_code turns out to be an error message. The html contains:
&lt;div id="Sorry, this account has not yet been approved. If you need to change your email address please click &lt;a href=" http="":="" www="".choppix="".com="" holymoly="" index="".php=""?action="activate;user=Xxxxxxxx@outlook.com""&gt;here." class="padding"&gt;
