### ISSUE TITLE
Don't show login/register to banned

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1781]
If user is banned there is no reason to show those buttons/links.

**Comment by Arantor** [comment]
What kind of ban are we talking about exactly?

**Comment by XinYenFon** [comment]
Not the warning thing, I mean full ban (with/without expire date).

**Comment by Arantor** [comment]
There are multiple kinds of ban: cannot post, cannot register, cannot login. Which did you mean exactly?

**Comment by XinYenFon** [comment]
well actually isn't it very clear?

cannot register > don't show register
cannot login > don't show login
full ban > don't show both

**Comment by Oldiesmann** [comment]
This really will only work for IP and hostname bans. Otherwise there's no way to tell that the ban applies until they try to register and/or login.
