### ISSUE TITLE
Minor:  New User - pending activation still shows up as the newest user

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#1788]
http://test2.turtleshellprod.com/index.php

Newest user: "A Test" is pending admin activation - but still shows up as the newest user in the info center.  I believe that a user pending activation should not display as an actual user yet

This would enable someone to sign up with an offensive name and have it appear in the user's info centers until the admin has checked in and deleted said user.

**Comment by illori** [comment]
on my test install i have 2 users waiting approval one via email and one by admin, neither of them show up in the info center as the latest member

**Comment by Kindred-999** [comment]
hmmm....   well, the "pending admin activation" user definitely shows up on my site.

**Comment by AngelinaBelle** [comment]
I think that user is pending a delete request approval.

**Comment by illori** [comment]
in that case the user should show up as they are still a valid member of the forum.

**Comment by Kindred-999** [comment]
well, for X sake...

DOH!   We have to come up with a better way of marking Accounts pending activation approval versus accounts pending deleting approval!

Close this darned ticket as user mistake
