### ISSUE TITLE
Merge Topics Error

### ISSUE THREAD

**Issue by Morsyl** [SimpleMachines/SMF#1792]
I get a session verification error when trying to merge topics:
1) View topic, click "Merge Topics"
2) In the following page, select a a board to list topics from (a different board from the one that's selected)
3) Session verification error.

Also, if I'm Viewing a topic from a board with only one topic in it and click "Merge Topic" I get the following error: "Merge topics require at least two topics to merge."
Is that correct? Given that there are other boards containing possible topics to be merged with.

**Comment by Oldiesmann** [comment]
Thanks for the report. The session error is a bug due to the session info never being passed to that function (either from a form or in the URL).

We can look into the other issue as well.
