### ISSUE TITLE
[Display] Reported post disregard button -- if I cancel "disregard" the button still appears depressed

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1793]
This is a fairly minor display issue, I think, but it could be nice to return the button to its "unpressed" state when disregard is cancelled.

**Comment by illori** [comment]
in what browser are you seeing this? i can not duplicate in ff 29.0.1

**Comment by AngelinaBelle** [comment]
iPad / Safari.   iPad/chrome

**Comment by AngelinaBelle** [comment]
Can this be tagged "display", "minor bug" and maybe "won't fix".

**Comment by XinYenFon** [comment]
Can you still reproduce this ? I can't reproduce it on my mobileIE11 (WP8.1 Update1)

**Comment by XinYenFon** [comment]
Can this be closed? Disregard no longer a button but drop-select.
