### ISSUE TITLE
Three questions in relation to SMF 2.1

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1797]
Hi, I've three questions in relation to SMF 2.1
1. Will you introduce option of switching the panel of the administrator, I mean about such a system like in SMF 2.x, that on left side will be a column of blocks with options

Screen:
http://files.tinypic.pl/i/00539/hlgmvpchqkbr.png
1. Instalation SMF 2.1 doesn't work, appear the bug:

Parse error: syntax error, unexpected T_FUNCTION in /home/XXX/domains/XXX/public_html/smf/install.php on line 1344

Soon will be possible to install SMF 2.1?
1. Maybe this too early question, but when more or less will be SMF 2.1 to use in stable version? For year? For two years? Or maybe you release SMF 2.1 earlier? It would be great.

**Comment by Dragooon** [comment]
This is not a place to ask questions, please use 2.1 board on forums. Closed

**Comment by AngelinaBelle** [comment]
as per #1762 make sure php version is at least 5.3.8 to avoid this syntax error
