### ISSUE TITLE
User profile time -- multiple issues.

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1802]
Tested on windows vista, Chrome 35

![timeformaterrors2](https://cloud.githubusercontent.com/assets/3267025/3244755/9abefe42-f16b-11e3-9212-05bbd6a90316.jpg)
- Nothing in the time format dropdow
- Anything saved in the time format field does not get saved
- The time offset arrow works in tenths of hours.  That is odd.  There are a couple .5 hour time zones in the world, but not any 6-minute time zones
- The auto detect button does not work -- sets offset back to 0, even on a forum that is 4 hours behind my local time. (or else the forum time is set funny and the autodetect is correct -- there is no way for me to tell, actually, so that is possibly a bug)
- The "forum time" is blank.

**Comment by XinYenFon** [comment]
Software wide problem.

**Comment by ChainyEO** [comment]
The "Overall time offset" still accepts 0.25hr time differences. Is that necessary?
