### ISSUE TITLE
[Display] user profile look and layout -- autodetect in square brackets

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1803]
Square brackets are used around [auto detect] to bring attention to it.
This is an old-fashioned way of making a text link look like a button.
But that is looking very old fashioned.

Please remove the square brackets from the text.
If the link under the text is not enough, please consider styling it to look like a button.

**Comment by XinYenFon** [comment]
I'll give it a button class :) It look like our generic buttons.
