### ISSUE TITLE
[Display] board permission profile list -- brackets on profile name

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1805]
The brackets around the permission profile name in this list are an inconsistancy, and cause a confusing user experience.
Please get rid of them.
- The link under the board name is to "modify board"
- The link under the bracketed permission profile name is to "manage permissions" for that profile.

Why is one thing bracketed and the other not bracketed?  The difference in appearance implies some difference in what to expect.  But this is not consistent with what actually happens.

(a really useful addition would be "choose new profile for this board" to allow choosing profile from list. but that might be feature creep, and so best left for the next update).

**Comment by illori** [comment]
in all the years that 2.0 has been out with this the same, no one that i know of has complained. so i would not say this is a bad or confusing UI.

**Comment by illori** [comment]
also related thread on the forum http://www.simplemachines.org/community/index.php?topic=523669.0

**Comment by AngelinaBelle** [comment]
out with the old, in with the new.

**Comment by illori** [comment]
the package manager has these same brackets around install mod, list files, and delete. no one has complained about them

**Comment by AngelinaBelle** [comment]
I suppose it is worth a more general discussion
