### ISSUE TITLE
Extra Drafts saved and not cleaned up

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1815]
Simplest case of extra drafts hanging around:

Start a new topic, subject "1" save draft.  
change subject line to "2" save draft. load drafts. -- see 2 drafts, "1" and "2"
change subject line to "3".  save draft.  load drafts -- see "1" and "3"
change subject line to "4".  save draft.  load drafts -- see "1" and "4"

post.  go to profile and see drafts -- see "4".

---

Other weird things happen when you edit an existing topic or reply and start with the draft button.  Looks like, sometimes, a draft is saved twice.

http://www.simplemachines.org/community/index.php?topic=523790

**Comment by AngelinaBelle** [comment]
Could forbid drafts on modify post, but that leaves a problem on new reply:
Hit "reply"
Click "save draft" -- 2 drafts are saved.
Make a change, save draft again-- the second draft is cleaned up, but not the first.
The first draft is not cleaned up when the reply is finally posted.

Problem seems to be an extra save the first time through

**Comment by AngelinaBelle** [comment]
I can no longer reproduce this issue.
Is anyone else seeing the issue?

**Comment by live627** [comment]
Now that your PR is merged in, is this no longer applicable?

**Comment by AngelinaBelle** [comment]
I did no work on this issue.
I think somebody else must have done, however, as I can no longer reproduce the issue.

Nobody else is seeing the problem.  I will close it, and reopen if it reappears.
