### ISSUE TITLE
"Load Drafts" missing after "Save Draft"

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1816]
to reproduce:
- Start a new topic
- Use the "save draft button"
- look for the "load drafts" header below the post.
  <hr>

-- This feature was working fine as of 23:15 EDT 8-Jun-2014, when Kindred did the last update to his demo site.
-- Antes' demo, as of 10 june 2014, is not showing "load drafts". (please verify with him that he did not turn off the "show drafts in post" feature).
-- feature seems to be missing from 47eb4bb7129a751ea001378d8629128f8429c945 
-- feature seems to be missing from 317ba2e0d2ae95a4793f00187686047fafe7e0c3,

**Comment by illori** [comment]
i just tested this with the latest zip from the main page, no issues load drafts shows up without issue after clicking save draft.

**Comment by AngelinaBelle** [comment]
This is going to be hard to reproduce, then.
Can it just be me?

**Comment by illori** [comment]
are you testing this on desktop browser or mobile?

**Comment by illori** [comment]
maybe related to this

Type of error: Undefined
8: Undefined index: drafts_autosave_frequency
/index.php?action=post;topic=21.0;last_msg=70
File: F:/wamp/www/github2.1/Themes/default/GenericControls.template.php
Line: 181

**Comment by illori** [comment]
can you test this after the fixes oldies has made today?

**Comment by Oldiesmann** [comment]
On my test board (just updated about 15 minutes ago), I'm still seeing load drafts on the full reply/post screen (I don't remember if it's supposed to show up on the quick reply or not).

**Comment by illori** [comment]
it has never shown up on the quick reply, which mean that those that only use quick reply would never know they have drafts for that topic unless they go to the full reply page or into their profile.

**Comment by AngelinaBelle** [comment]
I just tested the latest version. 
393e0fae5b86bce8355a8dea76bc84afcc5117f4
The problem now appears to be fixed

**Comment by illori** [comment]
but this does not take into account the quick reply and no notification of saved drafts being there.
