### ISSUE TITLE
group badge for moderators overwrites admin & global mods

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#1825]
Apparently, this bug has existed in place for a LONG LONG time and no one noticed (or assumed it was FAD, cause we didn't look at the code)

It is still present in 2.1
discussion and discovery http://www.simplemachines.org/community/index.php?topic=523833

Dragooon's fix:

```
    foreach ($temp_mods as $id)
    {
        // By popular demand, don't show admins or global moderators as moderators.
        if ($user_profile[$id]['id_group'] != 1 && $user_profile[$id]['id_group'] != 2)
            $user_profile[$id]['member_group'] = $row['member_group'];

        // If the Moderator group has no color or stars, but their group does... don't overwrite.
        if (!empty($row['stars']))
            $user_profile[$id]['stars'] = $row['stars'];
        if (!empty($row['member_group_color']))
            $user_profile[$id]['member_group_color'] = $row['member_group_color'];
    }
```

replace with

```
    foreach ($temp_mods as $id)
    {
        // By popular demand, don't show admins or global moderators as moderators.
        if ($user_profile[$id]['id_group'] == 1 || $user_profile[$id]['id_group'] == 2)
            continue;

        $user_profile[$id]['member_group'] = $row['member_group'];

        // If the Moderator group has no color or icons, but their group does... don't overwrite.
        if (!empty($row['icons']))
            $user_profile[$id]['icons'] = $row['icons'];
        if (!empty($row['member_group_color']))
            $user_profile[$id]['member_group_color'] = $row['member_group_color'];
    }
```

This should retain their Global Moderator/Admin status including the badge.

**Comment by XinYenFon** [comment]
Actually we discussed this with @Oldiesmann before and we decided not to call it bug, he was going to write a modification for smorg to fix primary group badge issue & multiple badge. If we call this bug (which I'm also ok with that), it must show primary member group not just Admin/Glob. Mod.

**Comment by Kindred-999** [comment]
Why - it should not override the admin.global mod -- those are global positions of power.
it SHOULD override any normal membergroup

(and yes, I know there are cases where someone has set up global power groups that are NOT groupID1 or 2...   but work with what we've got.)

I do think this is actually a bug now that it has been pointed out.

Of course, it we still displayed the primary and/or multiple badges - then this would be a non-issue

**Comment by XinYenFon** [comment]
Actually, it should be regardless of badge (except Admin/G.Mod) it should show: Primary badge & Local Mod badge.

**Comment by Kindred-999** [comment]
I will agree with that
