### ISSUE TITLE
Someone broke the hooks...again...

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#1828]
@MissAllSunday I corrected your mistake once, and I will NOT do it again.

**Comment by MissAllSunday** [comment]
Yes, please don't do it :)

**Comment by live627** [comment]
What are you hiding?

**Comment by MissAllSunday** [comment]
file|class::method#
file|function

**Comment by live627** [comment]
how nice. Did you test it?

**Comment by MissAllSunday** [comment]
Did you?

**Comment by live627** [comment]
yes

**Comment by MissAllSunday** [comment]
<?php

$hook = 'file|function';

list($file, $func) = explode('|', $hook);  // mine
list($func, $file) = explode('|', $hook); // yours

echo 'this is suppose to say file: ';print_r($file);
echo '<br>this is suppose to say function : ';print_r($func);

Please check and compare.

**Comment by live627** [comment]
Test It with a mod.

**Comment by MissAllSunday** [comment]
https://github.com/MissAllSunday/Breeze
https://github.com/MissAllSunday/Breeze/blob/develop/hooks.php

**Comment by live627** [comment]
yeah, no...

Your handling of hooks is flawed. Use the functions properly.

This really is a valid issue and should be reopened.

**Comment by Dragooon** [comment]
If anyone would actually say what the issue is...that'll be great.

**Comment by live627** [comment]
8b38f35d9c6ba15418930e9fed1d03c922565442

**Comment by Dragooon** [comment]
What's wrong with it? If it's file|function then that should be fine

**Comment by live627** [comment]
I don't see that specific order in add_integration_function()

**Comment by Dragooon** [comment]
@MissAllSunday If you want file|function, you also gotta change [this line](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs.php#L4134)

**Comment by MissAllSunday** [comment]
The $file param on add_integration_function should be nuked as it has no real purpose anymore. The same with the $object param.

**Comment by Dragooon** [comment]
Kinda clumsy to cram multiple things into a single parameter, don't you
think?

**Comment by MissAllSunday** [comment]
Yes and that was the reason why I added those extra params in the first place but it really doesn't make any sense to have those extra params and broke compatibility with 2.0 and to be honest, very, very few mod authors will take advantage of loading their files and even less mod authors will work with classes.

Not to mention they will be cramped when saved to the db anyways...

There should be a separate table for hooks with more columns such as priority and the name and number of arguments that hook calls to avoid the expensive call_user_func_array()
