### ISSUE TITLE
"Reject user" popup hangs browser -- iPad Safari, Chrome

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1831]
iPad 7.1, Safari, Chrome ( but not Opera Mini)
- admin> members awaiting approval
- checkbox next to a member name
- choose "reject" from list of actions
- popup offers "cancel" or "ok" -- but nothing happens on clicking those buttons
- browser cannot do anything -- no switching tabs.  No closing current tab.
- use home button to exit app.  Of resume -- app still stuck
- to use the browser again, must remove app from memory.  This seems to work only because SMF then requires admin to enter password again.

![image](https://cloud.githubusercontent.com/assets/3267025/3301345/75d00dec-f62a-11e3-8ec6-89e63a2dd9bd.jpg)
^ Safari.  Looks about the same in Chrome

![image](https://cloud.githubusercontent.com/assets/3267025/3301350/917bc1da-f62a-11e3-88c0-7dcee8bd208e.jpg)
^ no problem in Opera Mini

**Comment by AngelinaBelle** [comment]
It should be noted that there is no problem with the popup in delete member:
![image](https://cloud.githubusercontent.com/assets/3267025/3301372/b87f6c3c-f62a-11e3-849d-8c1731880be2.jpg)

**Comment by illori** [comment]
http://stackoverflow.com/questions/18903525/alert-and-confirm-not-working-with-apple-mobile-web-app-capable seems to suggest this is a browser/os issue

**Comment by AngelinaBelle** [comment]
It may be an issue in iOS.  And yet -- how great would it be to have SMF accomodate the iPad?
- "Delete this user" works just fine
- "Manage Mambers" pop-up triggered from the list does not work.

Something is different.
The stackoverflow you reference suggests 2 simple workarounds that fix the problem for iOS mobile devices.

**Comment by Oldiesmann** [comment]
So the selftimeout thing will fix it for mobile devices without making things act as if you hit cancel?

**Comment by AngelinaBelle** [comment]
What you say is all Greek to me, but if you give me a file I will test it.

**Comment by Oldiesmann** [comment]
Try this and see if it fixes the issue

ManageMembers.template.php (line 232)

Find

```
        <form id="admin_form_wrapper" action="', $scripturl, '?action=admin;area=viewmembers" method="post" accept-charset="', $context['character_set'], '" name="postFormOutstanding" id="postFormOutstanding" onsubmit="return onOutstandingSubmit();">
```

Replace

```
        <form id="admin_form_wrapper" action="', $scripturl, '?action=admin;area=viewmembers" method="post" accept-charset="', $context['character_set'], '" name="postFormOutstanding" id="postFormOutstanding" onsubmit="return setTimeOut(onOutstandingSubmit, 200);">
```

**Comment by AngelinaBelle** [comment]
No difference.

**Comment by AngelinaBelle** [comment]
Why doesn't the dialog box in "disregard post" hang the browser? Is it because there are more layers of things popping out of the page, or is it just handled differently?

**Comment by Oldiesmann** [comment]
I have no idea why some confirmation things work while others don't.
