### ISSUE TITLE
Deprecated jQuery SCE function causes js error for backward compat of BBC mods

### ISSUE THREAD

**Issue by Underdog-01** [SimpleMachines/SMF#1845]
SMF 2.1 is currently using the SCE v1.4 plugin to add BBC to posts. 
Certain functions have been deprecated and completely removed from the plugin since v1.3.5.

  With this report I am referring to the use of the setCommand function which is currently being used to add to the BBC toolbar from BBC mods that use the older hook. Since this function no longer exists in the SCE infrastructure the javascript for adding the BBC toolbar completely crashes when the code attempts to use setCommand to add the "before" key from the array.

File: ../Sources/Subs-Editor.php

code:
                        if (isset($tag['before']))
                        {
                               $context['bbcodes_handlers'] .= '
                $.sceditor.setCommand(
                    ' . javaScriptEscape($tag['code']) . ',
                    function () {  
                        $(this).wysiwygEditorInsertHtml(' . javaScriptEscape($tag['before']) . (isset($tag['after']) ? ', ' . javaScriptEscape($tag['after']) : '') . ');
                    },
                    ' . javaScriptEscape($tag['description']) . ',
                    null,
                    [' . javaScriptEscape($tag['before']) . (isset($tag['after']) ? ', ' . javaScriptEscape($tag['after']) : '') . ']
                );';
                        } 

The documentation stating the code has been deprecated & completely dropped is here:
http://www.sceditor.com/posts/version-1-4-0-released/

Possible newer implementation? ...
http://www.sceditor.com/posts/how-to-add-custom-commands/

Regards.

**Comment by Underdog-01** [comment]
See the edit shown in this PR: https://github.com/SimpleMachines/SMF2.1/pull/1846/files

Closed.

**Comment by Dragooon** [comment]
As a future pointer, don't close an issue until the PR is merged. This issue still exists in the upstream repository and should remain open until then

**Comment by AngelinaBelle** [comment]
#1846 (to complete the reference)
