### ISSUE TITLE
Cannot type in empty wysiwyg editor on iPad

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1850]
Have to switch to non- wysiwyg

**Comment by AngelinaBelle** [comment]
In wysiwyg mode, I can now get focus by tapping within a populated line, but not after the last line.
I can tap in the first line, but often have trouble hitting the right spot in the empty box

**Comment by Oldiesmann** [comment]
Any suggestions on a possible fix, or is this just going to have to be another known issue that we can't do much about?

**Comment by XinYenFon** [comment]
I don't have any problem with my WP8.1 - IE11 (Mobile) so probably iOS fault again...

**Comment by AngelinaBelle** [comment]
What is different? 
And wouldn't it be awesome if SMF COULD support iOS

**Comment by XinYenFon** [comment]
This is not about SMF actually(?), we are using SCEditor, maybe its better to ask the author?

**Comment by live627** [comment]
@AngelinaBelle does the demo at http://www.sceditor.com/ work?

**Comment by AngelinaBelle** [comment]
@live627  Yes.  In the sceditor demo, I can tap anywhere in the box, in either mode, and the keyboard comes up.  I even tried deleting all text in the textarea before testing.

In SMF2.1, I have to tap in the last line with text, or else in the very top line if the text area is empty.
If I add text, then delete it again,this is still true.

This is not a problem in SMF2.0.7, for example

**Comment by live627** [comment]
> In SMF2.1, I have to tap in the last line with text, or else in the very
> top line if the text area is empty.

I think I've encountered this before. I do not have iOS.

> This is not a problem in SMF2.0.7, for example

It uses a totally different solution.

**Comment by AngelinaBelle** [comment]
Bingo!  You did it!
Score one for a mobile-friendly SMF!

**Comment by live627** [comment]
YES!!
