### ISSUE TITLE
upgrade.php issues with sqlite3

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1852]
Notice: Undefined index: sqlite3 in F:\wamp\www\github2.111111\upgrade.php on line 2325
Call Stack
# Time    Memory  Function    Location

1   0.0220  1262264 {main}( )   ..\upgrade.php:0
2   0.2560  2923352 WelcomeLogin( ) ..\upgrade.php:675
3   0.2570  2924080 db_version_check( ) ..\upgrade.php:1000

( ! ) Notice: Undefined index: sqlite3 in F:\wamp\www\github2.111111\upgrade.php on line 2328
Call Stack
# Time    Memory  Function    Location

1   0.0220  1262264 {main}( )   ..\upgrade.php:0
2   0.2560  2923352 WelcomeLogin( ) ..\upgrade.php:675
3   0.2570  2924080 db_version_check( ) ..\upgrade.php:1000

@Oldiesmann not exactly working...

need to add

```
    'sqlite3' => array(
        'name' => 'SQLite3',
        'version' => '1',
        'function_check' => 'SQLite3::version',
        'version_check' => 'return 1;',
        'supported' => is_callable(array('sqlite3', 'version')),
        'always_has_db' => true,
        'utf8_default' => true,
        'utf8_required' => true,
        'utf8_support' => true,
        'validate_prefix' => create_function('&$value', '
            global $incontext, $txt;

            $value = preg_replace(\'~[^A-Za-z0-9_\$]~\', \'\', $value);

            // Is it reserved?
            if ($value == \'sqlite_\')
                return $txt[\'error_db_prefix_reserved\'];

            // Is the prefix numeric?
            if (preg_match(\'~^\d~\', $value))
                return $txt[\'error_db_prefix_numeric\'];

            return true;
        '),
    ),
```

after that...

```
Error!
near "auto_increment": syntax error
```

once you get beyond this there are many other errors.... this was a 2.1 install to start with so maybe some errors are related to not finding columns?

**Comment by Oldiesmann** [comment]
Does it tell you exactly what it's doing when there's an error near "auto_increment"?

**Comment by illori** [comment]
that phrase is found 2 times in the sql, i believe sqlite does not support auto_increment so both need to be fixed. once you fix that there are more errors after.

**Comment by Oldiesmann** [comment]
According to the sqlite website, it's AUTOINCREMENT with no underscore. What other errors are you getting? I'd like to fix as many of them as possible in one go.

**Comment by illori** [comment]
cant you go ahead and test your fixes as you go? if so then you would find more then i can as i am not a developer and can not fix them all myself and it does not really progress past the first entry.

**Comment by Oldiesmann** [comment]
Fixed the undefined index and auto_increment issues and am . Now getting this:
-  +++  Adding login history...Error: SQLite3::exec(): near ")": syntax error File: /.../Sources/Subs-Db-sqlite3.php Line: 443

This is after changing the "KEY <name> (column)" statements to CREATE INDEX statements... I will look further into this when I get home from work tonight.

**Comment by Oldiesmann** [comment]
That error turned out to be due to a stray comma at the end of the create table statement. Getting much further now...

**Comment by Oldiesmann** [comment]
Just a note on my progress here...

At this point I am going to continue my work to get upgrade working on SQLite3, but I would like to try and get the install/upgrade stuff rewritten to only use $smcFunc at some point soon, as this is turning out to be a much larger change than I had initially planned.

Among the issues I've run into in my testing so far:
- Errors due to syntax differences
- Duplicate content errors (adding a column/index that already exists, trying to insert a setting that already exists ["column 'variable' is not unique"])
- Syntax limitation issues (all those raw queries to change the existing ip_low/ip_high columns in the ban_items table have to be replaced with PHP code to run $smcFunc['db_change_column'] instead)

**Comment by illori** [comment]
Adding login history...done
Copying the current package backup setting...done
Copying the current "allow users to disable word censor" setting...done

!!
Error!
no such column: id_theme

**Comment by illori** [comment]
```
$request = upgrade_query("
        SELECT value
        FROM {$db_prefix}settings
        WHERE variable='allow_no_censored'
        AND id_theme = 1 OR id_theme = '$modSettings[theme_default]'
    ");
```

should be the themes table not settings

**Comment by illori** [comment]
```
---# Adding alert preferences.
CREATE TABLE IF NOT EXISTS {$db_prefix}user_alerts_prefs (
  id_member int unsigned NOT NULL default '0',
  alert_pref varchar(32) NOT NULL default '',
  alert_value tinyint(3) NOT NULL default '0',
  PRIMARY KEY (id_member, alert_pref)
);
```

it does not like the '' it should be '0'

**Comment by illori** [comment]
actually that did not fix it...

```
!!
Error!
Error retrieving information on step: Adding alert preferences. (Item: 54)
```

**Comment by Oldiesmann** [comment]
Thanks for the report. I did have it fully working yesterday but some things may have gotten missed due to me redoing everything while trying to fix the merge conflicts. I'll keep testing and see if I can figure out what's going on there.

**Comment by Oldiesmann** [comment]
Try again now :)

**Comment by Oldiesmann** [comment]
Closing since we decided to drop support for SQLite in #1916.
