### ISSUE TITLE
BBC abruptly ends HTML tags

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#1861]
http://www.simplemachines.org/community/index.php?topic=422791.msg3402151#msg3402151

If you have a [url] tag within a < blockquote>, the blockquote is abruptly ended at the url tag. An < a href> HTML tag works fine there (does not end the blockquote).

**Comment by AngelinaBelle** [comment]
Parse_bbc is not designed to interpret bbc mixed in with html.  Should you be able to put an html tag inside an html tag? How deep should that nesting go?

It seems as though it interprets the url tag as though it were preceded by [/html], and attempt to properly close any open html tags, as open tags will break the html of the entire page.  Any remaining html would be cleaned out, and the [/html] tag would be ignored.

Instead, you would like to see the parser have  some kind of nested [bbc] mode?  
   [bbc][url=http:a.com]text[/bbc][/url]

**Comment by live627** [comment]
> Instead, you would like to see the parser have some kind of nested [bbc]
> mode?

Enter [nobbc]

**Comment by AngelinaBelle** [comment]
Currently, 2.1 demo sites show that bbc tags within html tags are not interpreted as bbc

For example,
http://test2.turtleshellprod.com/index.php?topic=59.msg175#msg175
