### ISSUE TITLE
Check for certain functions in installer and upgrader

### ISSUE THREAD

**Issue by Dragooon** [SimpleMachines/SMF#1869]
Currently we only check for php and mysql versions, we should also check for GD2 (and make it mandatory), hash and maybe even mbstring and json (not sure if we're using it)

**Comment by Oldiesmann** [comment]
GD2 - Check for it, and, if it's not available, also check for ImageMagick support via imagick or magickwand (using PHP's extension_loaded() function). If you don't have GD2 but do have ImageMagick, the only thing that won't entirely work properly is CAPTCHA - ImageMagick can be used for resizing images, generating thumbnails, etc.

hash - Probably a good idea despite the fact that it's not likely to be disabled (it's enabled by default - the only way it can be disabled is by specifying --disable-hash when compiling PHP).

mbstring - Not entirely sure on this one. I do see that we make use of it in various places if it's available, but I'm not sure what the consequences are of not having it.

I don't think we actually use json anywhere.

**Comment by sbulen** [comment]
This item may be closed out - discussion was picked up in #4148

**Comment by sbulen** [comment]
This one can be closed, too.
