### ISSUE TITLE
$.sceditorBBCodePlugin.bbcode.set() now deprecated

### ISSUE THREAD

**Issue by Underdog-01** [SimpleMachines/SMF#1871]
The SCEditor function of $.sceditorBBCodePlugin.bbcode.set() has been deprecated in favor of $.sceditor.plugins.bbcode.bbcode.set()
ref. http://www.sceditor.com/documentation/custom-bbcodes/

When I am finished working with a necessary edit to Subs-Editor.php to allow hooked BBC's to use the WYSIWYG editor properly I will amend the use of the deprecated function to the new syntax.

So far I have seen it in ../Themes/default/scripts/jquery.sceditor.smf.js

.. edits pending

**Comment by illori** [comment]
would it not be better to upgrade the editor if a new version is released rather then editing the version we are using?

**Comment by AngelinaBelle** [comment]
Underdog -- are you talking about editing sc code, or about SMF calls to sceditor?

**Comment by Underdog-01** [comment]
../Themes/default/scripts/jquery.sceditor.smf.js is not a sceditor file, it is a smf js file that uses sceditor functions to set the various bb codes so it has to be updated/edited to the newer syntax.

**Comment by illori** [comment]
but what version has this change? does it really effect the version we are using at this time?

**Comment by AngelinaBelle** [comment]
would it not be better to upgrade the editor if a new version is released, and make the changes to where SMF calls the sceditor functions?

**Comment by Underdog-01** [comment]
the version currently being used for SMF 2.1  is not stipulated at the onset of the library file. Although comments further into the file suggest v1.4.4 whereas the current version is v1.4.5. 
The function being used has not been dropped just yet but is flagged as deprecated whereas the author will indeed drop it shortly. 
The new function will work with this version.& I am going to PR the changes.
I will also test applying the v1.4.5 SCE library and if it does not break anything in the process I will also apply it.

**Comment by AngelinaBelle** [comment]
Let me know; I can test on iPad.
Probably wont make a difference, but worth checking.

I'd like it to be easier for tablet users to type in the WYSIWYG editor

**Comment by Underdog-01** [comment]
Imo the WYSIWYG editor was not thought out properly by its devs. Each BBC on the screen should have surrounding span with a unique class (ie. bbc name) whereas the internal content of the unique class is the only thing triggered (ie. images, links, etc.). As it is right now if you have a custom BBC with let's say an image contained within it the WYSIWYG will toggle it back to a img bbc which is incorrect behavior. This is what I experience while testing anyhow. 
I am going to mention this to the SCE developers as I think my idea would work much better. 
Having class="unique_bbc_name" will allow all like BBC to behave the same without effecting other BBC's within editing the post.

People creating custom BBC mods will have to opt the WYSIWYG only for those tags that do not conflict with defaults. Imo give the user an option to enable/disable that option. I am about to post an edit that will allow Customizers to take advantage of the WYSIWYG feature. Hopefully the devs here will like what I propose.. I just need to test it a bit further prior to posting that PR.. then I will do the edits I described here.

Regards.

**Comment by AngelinaBelle** [comment]
Changes to the Sam Clarke editor and concomitant changes to SMF to take advantage of that sounds like interesting separate issues

**Comment by Underdog-01** [comment]
Sam's editor is ever changing as he is actively developing it. I sent him an email with my ideas with hope that he may agree and perhaps implement some of them in the future.

**Comment by Oldiesmann** [comment]
We're using the latest version of the editor as far as I know, as it was upgraded last year when I realized we were way behind (I didn't do the upgrade though - I believe Spuds and/or emanuele did).

I'm fine with replacing deprecated code as well. I just tested this change on my board and it seems to work fine.
