### ISSUE TITLE
Language strings too fine-grained in default theme's forum statistics

### ISSUE THREAD

**Issue by texttheater** [SimpleMachines/SMF#1872]
The issue is with this line in `Themes/default/BoardIndex.template.php`:

```
', $context['common_stats']['total_posts'], ' ', $txt['posts_made'], ' ', $txt['in'], ' ', $context['common_stats']['total_topics'], ' ', $txt['topics'], ' ', $txt['by'], ' ', $context['common_stats']['total_members'], ' ', $txt['members'], '. ', !empty($settings['show_latest_member']) ? $txt['latest_member'] . ': <strong> ' . $context['common_stats']['latest_member']['link'] . '</strong>' : '', '<br />
```

Correct translation to, say, German is impossible because a different inflected form of `$txt['members']` is required in this context than in others. I guess the whole message should be a single string.

This has been discussed before, and similar issues have apparently been resolved in other places: http://dev.simplemachines.org/mantis/view.php?id=4822

**Comment by MissAllSunday** [comment]
Would merging all the text strings into a single one and use sprintf() work for you?  I know it will work for Spanish.

Something like:

$txt['blabla'] = '%1$d Posts in %2$d Topics by %3$d Members - Latest Member %4$s'

**Comment by Dragooon** [comment]
That's what I was thinking as well

**Comment by texttheater** [comment]
Yes, that would work.

**Comment by Oldiesmann** [comment]
Sounds good to me as well.

**Comment by MissAllSunday** [comment]
It seems this has already been solved:

https://github.com/SimpleMachines/SMF2.1/commit/c99b41d4b3e6f3ee61996ad916db4a56418acc52

or is there another place where the sprintf() needs to be applied?

**Comment by texttheater** [comment]
Oh, you're right! I was looking at the 2.0.8 sources. Sorry for the noise.
