### ISSUE TITLE
track user in others profile visible

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1885]
i can see the option to track user in the profile menu, then an empty option shows as its sub-menu which goes to github2.1/index.php?action=profile;area=tracking;sa=;u=6 and the user is granted with an error that they can not access that page

**Comment by illori** [comment]
this only happens if the user is a group moderator 

```
'groupreq' => array($txt['trackGroupRequests'], 'approve_group_requests', 'enabled' => !empty($modSettings['show_group_membership'])),
```

**Comment by illori** [comment]
this is not related to the moderation center, it is an error in the profile.

**Comment by Oldiesmann** [comment]
Closing this since everything seems to be working as intended after further investigation.
