### ISSUE TITLE
notify on reported user

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1891]
if a user is reported the admin does not get an email or alert for it.

**Comment by NanoSector** [comment]
Confirmed.

**Comment by Oldiesmann** [comment]
I did get an alert for it, but it wasn't instant (it only showed up after cron.php was run again about 15 minutes later).

**Comment by illori** [comment]
and do you get an email about it? emails dont see to work for the alerts.

**Comment by live627** [comment]
> emails dont see to work for the alerts.

I fixed that just now.

**Comment by illori** [comment]
i got an email for a mention, not for a pm sent and not for a quote.

**Comment by illori** [comment]
opened new issue for pm's and i did get an email for a quote, it was delayed.

**Comment by illori** [comment]
... they are delayed until a user makes a post, they are not sent when cron.php is called/run.

so if no user makes a post for hours after a mod report was made the email for it will never arrive.

**Comment by illori** [comment]
upon further testing it is not a post that makes it run. it seems somewhat random even when cron.php is modified to run at 1 minute.

**Comment by Dragooon** [comment]
Is this issue still reproducible? Wouldn't it fall under standard cron.php testing limitations?

**Comment by NanoSector** [comment]
It works for alerts.
http://i.imgur.com/UKnVczO.png

Will try with e-mail in a bit.

**Comment by NanoSector** [comment]
Works as well. http://i.imgur.com/2kgtNcQ.png

**Comment by Dragooon** [comment]
Seems to be working fine
