### ISSUE TITLE
call static method in ManageSettings.php

### ISSUE THREAD

**Issue by interlab** [SimpleMachines/SMF#1895]
SMF 2.0.8
php 5.4

error: Fatal error: Call to undefined function MyClass::mystaticmethod() in ...\Sources\ManageSettings.php on line 198

find:

``` php
    // Call the right function for this sub-acton.
    $subActions[$_REQUEST['sa']]();
```

replace:

``` php
    $func = strpos($subActions[$_REQUEST['sa']], '::') !== false ? explode('::', $subActions[$_REQUEST['sa']]) : $subActions[$_REQUEST['sa']];
    // Call the right function for this sub-acton.
    if (is_array($func))
        call_user_func($func);
    else
        $func();
```

**Comment by MissAllSunday** [comment]
Thanks for the report.

I will change the behavior of Subs::call_hook_helper()  to allow executing the given string instead of returning the formated string, that way we can used it on all the places SMF uses the $subAction system.

**Comment by interlab** [comment]
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/ManageSettings.php#L131

**Comment by MissAllSunday** [comment]
lol
