### ISSUE TITLE
number of reported members does not show in moderate menu

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1896]
if there is more then 1 reported members there should be a 1 in the moderate menu, currently there is nothing.

**Comment by NanoSector** [comment]
It does after a while. Investigating this issue.

**Comment by illori** [comment]
i believe this is fixed. @Yoshi2889 can you confirm?

**Comment by illori** [comment]
seems still an issue, reopening. after a while it seems that the number of reported members is not counted

**Comment by NanoSector** [comment]
It looks as though they're cached or something.

**Comment by illori** [comment]
this seems to still be an issue. for me right now the count of reported members is not even showing in the drop down menu, so not shown in the top menu count.

this is with level 1 cache enabled.

**Comment by MissAllSunday** [comment]
$modSettings['last_mod_report_action'] gets updated everytime theres a post or an user reported. The count gets stored on a SESSION var for performance, I would rather prefer to stay as it is than getting a real time statistic.

I dunno why theres a check on moderate_forum, try to change:

elseif (allowedTo('moderate_forum'))

to

elseif ($_SESSION['mc']['bq'] != '0=1')

on Sources/Security.php, it should at least force the recount if the conditions are met and avoid a call to allowedTo() which it seems its to early to call it in the process.

**Comment by illori** [comment]
i made that change, so far no difference seen. i checked i have 1 reported member and 6 topics awaiting approval. the 6 topics awaiting approval dont show up in the drop down. no including the number of posts awaiting approval. the number of moderation reports shows the correct number. cleared cache and no change, just the 3 moderation reports are listed.

**Comment by MissAllSunday** [comment]
Yes, there shouldn't be any difference, I'm not talking about showing the correct number of reported members, that won't be fixed, I'm more curious about the call to allowedTo() that earlier in the process.

**Comment by illori** [comment]
that has me confused, what exactly am i to test then? i dont know what that code does or how to test it or what you want done then.

**Comment by live627** [comment]
I'm going to defer this to RC1.

**Comment by sbulen** [comment]
Got it...  PR #4144 submitted.
