### ISSUE TITLE
"Show gender images in message view" has no effect.

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1898]
Whether checked or not checked, gender icon is shown below avatar when viewing a topic.

**Comment by NanoSector** [comment]
Confirmed. Looking into this.

**Comment by MissAllSunday** [comment]
Since the gender is now a custom profile field, this setting needs to be removed.

**Comment by NanoSector** [comment]
I figured as much. Hang on tight for a commit :)
