### ISSUE TITLE
Custom field show on topic view checkbox ignored

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1899]
Custom profile field

 Show on Topic View:  -- not checked

The text shows up under the avatar with the wrong Title text
Getting rid of it seems to require:
1) check that option ( now shows with correct title text)
2) uncheck that option (now the text is not shown under avatar)

**Comment by AngelinaBelle** [comment]
This may be an artifact.  Needs to be tested on a fresh install; cannot reproduce with a newly created profile field

**Comment by NanoSector** [comment]
I can't reproduce this on my test site either, sorry.

**Comment by live627** [comment]
> This may be an artifact. 

Quiite possibly.
