### ISSUE TITLE
No options to restore a topic

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#1901]
Once you have removed a topic into the trash, there is nothing to restore the topic.

**Comment by illori** [comment]
i see a restore topic button to the right of link to calendar

**Comment by NanoSector** [comment]
I don't. http://imgur.com/PNhrD1b

**Comment by illori** [comment]
i think 2.0 even suffers from this. i dont know if there is really a way to track down what happens. most of the time the button shows but sometimes it does not.

**Comment by NanoSector** [comment]
Fault on my side. I trashed a MOVED: topic which redirected me back to the original topic. The restore button is there.
