### ISSUE TITLE
Missing information on deleted topics in moderator log

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1906]
Topic title is blank
Board name is missing

![image](https://cloud.githubusercontent.com/assets/3267025/3366315/6dbdfbdc-fb43-11e3-805d-d4d88c51228f.jpg)

**Comment by AngelinaBelle** [comment]
Is this one still a problem, or has it been fixed lately?

**Comment by illori** [comment]
cant duplicate this on my install.

**Comment by AngelinaBelle** [comment]
Although no dev has mentioned this issue in a PR, it seems to have been addressed.
