### ISSUE TITLE
Recycled items going to wrong board

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1917]
1) start with fresh install
2) create board id 2 as a redirect
3) create board id 3 for the recycle board
4) turn on recycling, set board id 3 as the recycle board
5) remove topic id 1
6) see the moderator log, follow the link -- look in link tree -- name of board is board id 2
7) review in phpmyadmin -- see that topic 1 is now in board 2.

If you start adding boards and topics and categories and choosing different trash boards, eventually, the recycled topics start going into the correct board, and all changes of trash board seem to "work" after that.

**Comment by AngelinaBelle** [comment]
Confirmed: this is an issue with the latest commit
2a30f2604f041cb4a3c1eecda92a4382afe0bbac
available at 10:26 EDT 25 June 2014

**Comment by live627** [comment]
Uhh, wrong link? That commit doesn't affect the core functionality that I
can see.

**Comment by XinYenFon** [comment]
She probably mean i tried after that commit too still exist.

**Comment by AngelinaBelle** [comment]
Correct. The had been several commits since my last download, and I was confirming that it is a problem as of the most recent version.

**Comment by Oldiesmann** [comment]
Looks like something is screwing up the values for the select list. On my board I have this:

``` html
                                        <select name="recycle_board" id="recycle_board" >
                                            <option value="0"></option>
                                            <option value="1">General Category - General Discussion</option>
                                            <option value="2">General Category - Sub-board</option>
                                            <option value="3">General Category - New Board 2</option>
                                            <option value="4" selected>General Category - Recycling bin</option>
                                        </select>
```

However, the values do not correspond with the board IDs in all cases:
General Discussion - 1
Sub-board - 3
New Board 2 - 5
Recycling Bin - 2

So now the trick is to figure out where those IDs are being set and why they're wrong.
