### ISSUE TITLE
Add a CONTRIBUTING file

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#192]
I noticed we have confusion over how to contribute to the SMF code.  It seems like we could do something to make this easier.

First,
https://github.com/blog/1184-contributing-guidelines

This seems like a good idea and could help clear up questions and problems with how to contribute to the code.

Secondly,
If master is not going to be our development branch, we should set the development branch as our default branch.  This can be done via the admin area.

**Comment by joshuaadickerson** [comment]
Sounds great

**Comment by Spuds** [comment]
agreed ... looking forward to your addition

**Comment by joshuaadickerson** [comment]
Here are some links for inspiration:
https://github.com/CloudMade/Leaflet/blob/master/CONTRIBUTING.md
https://github.com/square/dagger/commit/85edf3d7812889c46819d30b010fb2ec8eb887da
https://github.com/thoughtbot/factory_girl_rails/blob/master/CONTRIBUTING.md
http://brad.livejournal.com/2409049.html
https://github.com/Fyrd/caniuse/blob/master/Contributing.md

https://www.google.com/search?q=github+contributing+file

**Comment by norv** [comment]
> If master is not going to be our development branch, we should set the development branch as our default branch. This can be done via the admin area.

I agree. Any reason why it isn't yet?

**Comment by Spuds** [comment]
Need to ask someone with Admin privileges ...

**Comment by joshuaadickerson** [comment]
I did it. Can you check it? Spuds, I will set you up as an admin.

**Comment by Spuds** [comment]
At one time I had admin on the repo but it was removed which is :cool:  with me .... l, would have like to have been informed but thats another story for another day.  So please no need to make me an admin, someone had an issue/concern with that and I can do what I need to get done w/o that access :smiley:

**Comment by norv** [comment]
Pretty sure I left ya admin when I made 2.1 repo and didn't change it.

@joshuaadickerson actually, my apologies for the confusion: the current development branch is not 'development', it's 'release-2.1'. I think that is better off set as default for now. It will be the first to appear when you make a PR, it's simply easier. And busier for a while, as it should be.

**Comment by joshuaadickerson** [comment]
Spuds, you are an admin already. I'll let you set the repository to what you feel is best.

**Comment by Fustrate** [comment]
iirc, I removed Spuds as an admin because the group controls _everything_, not just this repository. I'm fine with leaving it, but that's the reason why (again, iirc).

Also, SleePy should be removed from the administrators, since he's not on the team anymore?

**Comment by Spuds** [comment]
Like I said, no need to add me back ... or now since its done remove me (again) :smile: Its all good

**Comment by norv** [comment]
@Fustrate, not having as admins the developers in charge while having non-developers as admins to code repositories themselves, for some odd reasoning with historical bias, is off topic and as far as I can see, it's detracting from solving very simple issues at hand:

> the current development branch is not 'development', it's 'release-2.1'. I think that is better off set as default for now. It will be the first to appear when you make a PR, it's simply easier. And busier for a while, as it should be.

I'd appreciate an answer that has something to do with _solving the problem_. :) It is relevant for contributors and potential contributors from the community.
It's fine if you disagree, however do consider the context (current focus of development, user community around the project, starting up contributions, set up but not fully understood process, starting up with git and github), when taking this little detail into account. Thank you.
