### ISSUE TITLE
Token verification fails on admin and task logs

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#1934]
Intermittently you will get a token verification failed message when clearing out the `Administration Log` and the `Task Log` when they are already empty.

Error:
`Token verification failed. Please go back and try again.`

**Comment by Oldiesmann** [comment]
I'm unable to duplicate this error. Are you sure you're not going back and trying to resubmit a form from a cached page? That's usually what causes that error.

**Comment by FearThe1337** [comment]
Can't duplicate and there has been no responses here for almost a year. I assume this should be closed?

**Comment by albertlast** [comment]
@colinschoen canb you close this issue?
I didn't notice this issue.

**Comment by colinschoen** [comment]
Thanks
