### ISSUE TITLE
Unknown column mem.timezone in 'field list'

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1940]
Just got the latest files and got this error while clicking on my alerts
Has there been a change to the database, or is this a typo?
Load.php
Line: 1041
![image](https://cloud.githubusercontent.com/assets/3267025/3403231/3a2d3418-fd64-11e3-98f9-cdf8311b19d3.png)

**Comment by AngelinaBelle** [comment]
related errors?

Undefined index: time_offset 
     File: /home/u163902403/public_html/p4/Sources/Subs.php 
Line: 710
Line: 842
Line: 1238

**Comment by tekkla** [comment]
Had to add the missing field to members table by hand. Second error comes from empty timezone setting in forum profile. A check for not set member timezone is missing or not working. Will timezone be set to server timezone as default on upgrade or new installs?

IMHO an ajax error should not return a complete rendered page. :)

**Comment by AngelinaBelle** [comment]
Is this new field in install.php and upgrade.php?

What SMF should return if there is a fatal error during an XML action is a separate issue, I think.

**Comment by tekkla** [comment]
Yep. Both. And a default value will be set to UTC.

**Comment by AngelinaBelle** [comment]
So -- can I run upgrade.php on my existing test forum to get this field added?

**Comment by tekkla** [comment]
I think so. Just  tried it. Worked seamless.

**Comment by AngelinaBelle** [comment]
Hmm.. Not from iPad...  I keep winding up at step 1, over and over again.
