### ISSUE TITLE
Uploaded avatar from computer isn't shown

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#1951]
I'm report a bug:

Loaded avatar from computer isn't shown in the user profile and in the user profile in the post. Avatar added from the http link - is working correctly.

**Comment by MissAllSunday** [comment]
Is this from a clean install or an upgrade?

**Comment by jsqx** [comment]
From clean installation.

**Comment by illori** [comment]
i have uploaded an avatar on my 2.1 install and it works fine.

can you verify that the avatar is actually in the custom_avatar folder?

**Comment by jsqx** [comment]
Avatar after loaded is in custom_avatar folder.

Avatar isn't shown in these profiles:

![av1](https://cloud.githubusercontent.com/assets/8003629/3414060/c45cc3e4-fe11-11e3-974c-5b8450f92b27.png)

![av2](https://cloud.githubusercontent.com/assets/8003629/3414062/c7deff3c-fe11-11e3-8f0f-9fae1325ee63.png)

But in popup window in the top of the forum, is shown.

**Comment by illori** [comment]
is your forum using ssl? [https]

**Comment by jsqx** [comment]
I'm not using ssl on forum.
