### ISSUE TITLE
Empty field above the quote and big space under the quote

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#1952]
The quoted post which is appear in full editor of quick reply has a space, there is empty field above it, it shouldn't be in this way, because quote should be higher, there is one space. If the editor isn't fully turn on, so there is no space. 

Screen from not fully editor:

![itsok](https://cloud.githubusercontent.com/assets/8003629/3409042/e79f8b4a-fdd3-11e3-9e8c-48de20660264.png)

Screen from fully editor:

![isntok](https://cloud.githubusercontent.com/assets/8003629/3409058/0f07b89c-fdd4-11e3-9e49-7d307dd86985.png)

Correctly quote in the editor should look this way:

![likesmf](https://cloud.githubusercontent.com/assets/8003629/3409062/1efb1bfe-fdd4-11e3-8a67-5d6120e52d43.png)

After adding the post with the space in the editor, can see the space in the post.

View space in post (at the top) and (at the bottom) also is a big empty field. It shouldn't be in this way. It isn't look nice.

![space](https://cloud.githubusercontent.com/assets/8003629/3409014/bad653b4-fdd3-11e3-8c31-a6b623e8836f.png)

Fix it.

**Comment by live627** [comment]
> Fix it.

Yes, boss.

**Comment by jsqx** [comment]
Why now the Quick Reply has automatically enable full editor? Why you removed option with Look and Layout which enable and disable full editor? Still you don't fix space which I showed on screens.

**Comment by illori** [comment]
there was a bug and the developer decided to fix that bug by leaving the full editor enabled and no option to disable it.

**Comment by jsqx** [comment]
Ok, but still empty space isn't fixed. 

Still empty field is over the quote (red frame show it!) 

![isntok](https://cloud.githubusercontent.com/assets/8003629/3454590/81e5ed86-01d3-11e4-8d07-1d488da0a26e.png)

Correctly quote should be arranged this way:

![itsok](https://cloud.githubusercontent.com/assets/8003629/3454626/c86147e2-01d3-11e4-89e2-6c8fffb2d1e6.png)

Do you understand?

Because over the quote is empty field and if  quotation somebody and don't  moved this quote higher then after send a post it looks like this: 

![emptyfield](https://cloud.githubusercontent.com/assets/8003629/3454675/75c3c73e-01d4-11e4-85ec-cfe1bd38348b.png)

And by the way I report that at the bottom under the quote if adding text to the post then after sending the post is too big empty field over the text! Look at the orange frame! It shouldn't be like this, it's look bad.

**Comment by illori** [comment]
it is not fixed yet because the developer have more important bugs to fix then one that they are being demanded to fix.

**Comment by jsqx** [comment]
All right, I hope that will be fixed. And what if I don't want to have enable quick reply? Won't it be possible generally speaking disable quick reply?

**Comment by illori** [comment]
nope, the ability to disable quick reply has been removed

**Comment by XinYenFon** [comment]
Second one is not a bug actually, if you write
[quote]something[/quote]
something

You won't see too much margin, because quote tag adding one line by itself. But since you are doing 

[quote]something[/quote]

something

System putting two lines so you see big margin.

**Comment by jsqx** [comment]
@illori 
It's not good, I don't understand why to off-load disable option, you just making it difficult for users of SMF action on forum. If someone who use SMF don't want to enable quick reply that should have possibility to disable it and you intrude your rules.

@Antes 

I know that, but in SMF 2.0 isn't so big empty field under quote, if I'm add text with space one from quote. And in SMF 2.1 is bigger space and I'm mean that it wasn't so big.

![smf2](https://cloud.githubusercontent.com/assets/8003629/3461061/25d7ceb0-021e-11e4-8184-34231dc521d8.png)

**Comment by illori** [comment]
our developers thought it was a good idea to have the quick reply showing all the time, if you dont want to use it dont. if you want it hidden create a mod for it. we cant please everyone.

**Comment by jsqx** [comment]
Look at this, if I want to quote someone post in topic so the quote is automatically create in quick reply, but no in basic editor of the forum and now how it has sense of using of basic editor in SMF 2.1 if the quick reply is enable? And the quoting is in quick reply no more in basic editor. So the basic editor by this quick reply is less functional.

**Comment by Oldiesmann** [comment]
Why is it a problem that quotes now go to the quick reply instead of the regular reply screen? You can click "Preview" to get to the full reply screen and you can enable the full editor in the quick reply screen...

**Comment by illori** [comment]
quick reply does have the full editor, you need to enable it in your profile -> look and layout. but this actually has nothing to do with your main issue, you could discuss this on the forum or in another dedicated issue.

**Comment by jsqx** [comment]
If you think that should be in this way so this is your decision thought over and ok. 

Therefore I'm don't be writing here on this topic, I'm wait as far as the empty space above the quote will be fixed and low will be fixed.

**Comment by AngelinaBelle** [comment]
Thanks for sticking to one issue per issue. This makes it easier for devs.  For more general discussion, you can use the forum.

**Comment by NanoSector** [comment]
Looking into this, the JS is an undocumented mess.

**Comment by Oldiesmann** [comment]
Good luck Yoshi.

**Comment by XinYenFon** [comment]
Adding extra <br> to upside of Quote is SCEditor bug it seems (Ref: https://github.com/samclarke/SCEditor/issues/321). I still say other is not a bug.
