### ISSUE TITLE
custom_avatar folder lacks index.php and .htaccess

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1953]
should the custom_avatar folder have index.php and .htaccess files?

**Comment by MissAllSunday** [comment]
An index.php yes, an .htaccess prob nope.

**Comment by MissAllSunday** [comment]
On the other hand, custom_avatar already have an index.php file.

**Comment by illori** [comment]
i have an older 2.1 install [upgraded over time] where i had defined the custom avatar folder as /ava and it has no index.php file

**Comment by MissAllSunday** [comment]
The report says custom_avatar folder which does have an index.php

Custom created ones have never had any index.php or .htaccess files.

**Comment by illori** [comment]
should we force the custom ones to have index.php?
