### ISSUE TITLE
Quick reply  -- cannot get focus in wysiwyg mode in iPad

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1955]
This problem is similar to #1850.  Perhaps there is a similar solution. @live627  can you work the same magic here?

**Comment by live627** [comment]
I need to find out how to enable this. Any hints?

**Comment by live627** [comment]
Oh, found it.

**Comment by live627** [comment]
The code path is the same. Does it work when text is present (a la quote)?

**Comment by AngelinaBelle** [comment]
Again, this occurs only in WYSIWYG mode.
I can get focus by tapping anywhere up to the last line of text, but not by tapping AFTER the last line.
I can get focus by tapping in the very first line, but this is very non-intuitive for our users

**Comment by illori** [comment]
since the full editor was removed from quick reply,  i guess this is no longer an issue.

**Comment by AngelinaBelle** [comment]
Wait what? Why?  When?  Since the 27th?

**Comment by XinYenFon** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/1964

**Comment by AngelinaBelle** [comment]
Darn!  Is a great feature.  I wants it back!
Closing this issue. Irrelevant until some future version with sc editor in quick reply.

**Comment by illori** [comment]
i think there should be another way to fix that issue then removing a feature...

**Comment by XinYenFon** [comment]
To me problem is the feature, QReply is not designed for fully functional reply. If user wishes to reply with BBCode(s) etc... They must go to "Reply"

**Comment by illori** [comment]
per #1982 it seems that the full editor does still exist and is not removed, just option to not use it was removed.

**Comment by Oldiesmann** [comment]
Isn't there a way we can fix the spellcheck and draft-saving issues without forcing people to always use the full editor on quick reply?

**Comment by AngelinaBelle** [comment]
That is a separate issue - please see #1964 for that.

**Comment by AngelinaBelle** [comment]
This problem still exists, and it is difficult to understand why, if the same code is being used to show to wysiwyg editor in both places.
