### ISSUE TITLE
[Mobile]Spell check cannot be dismissed, and does not work in chrome, opera mini  -- iPad. 

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1957]
There is no way to dismiss the spell check pop-up on the iPad, the chrome browser.

Also, it comes up empty in chrome, and opens an additional blank tab for good measure.
![image](https://cloud.githubusercontent.com/assets/3267025/3414160/9b7284d6-fe12-11e3-983b-96c2b0c8a0f2.jpg)
![image](https://cloud.githubusercontent.com/assets/3267025/3414161/9b78762a-fe12-11e3-91ac-b6c818cf4c18.jpg)

The problem in chrome seems to be that the spell checker comes up in the same tab as the post behind edited, instead of in the new tab.  The only way to dismiss is to use the back button which goes back to before the spellcheck.

(This is not a problem in Safari.  In Safari The spellcheck comes up in a new tab, and makes the appropriate changes in the post being edited.)

**Comment by NanoSector** [comment]
![screenshot_2014-06-29-14-03-06](https://cloud.githubusercontent.com/assets/1280380/3423170/7c97aacc-ff85-11e3-9958-162e5c81a877.png)
![screenshot_2014-06-29-14-06-31](https://cloud.githubusercontent.com/assets/1280380/3423177/f3978e6c-ff85-11e3-9e97-4773a91b9099.png)

Works on my phone, in both Chrome and the stock HTC browser. Issue with iOS?

**Comment by AngelinaBelle** [comment]
iPad 3.5, ios v 7.1, latest version of Chrome

Works on iPad with Safari.
Don't know if it is an issue with the ios, an issue with the version of chrome for ios7.1, if there is some kind of workaround.

**Comment by live627** [comment]
Try here please http://livemods.net/21/index.php?topic=1.msg2#new

**Comment by AngelinaBelle** [comment]
No change
In yoshi's android examples, the spell check for Safari appears to pop up in the same tab, whereas in chrome it starts a new tab. In both cases, he reports the spell check works ok (did you test with some properly-spelled words?)

On iPad ios 7.1, 
- Safari starts a new tab with the spellcheck in it.  
- chrome starts the spell check in the same tab, with no content, and also starts a new blank tab

**Comment by AngelinaBelle** [comment]
Opera mini behavior is like chrome behavior

**Comment by NanoSector** [comment]
@AngelinaBelle the spell check does open in its own tab. On the stock HTC browser it just presents it as an overlay on the current tab. In Chrome it does use a different tab.

I checked a properly spelled post and it just said nothing was wrong and closed the tab when hitting OK.

**Comment by AngelinaBelle** [comment]
@Yoshi2889 if you re-enable spell checking on your test site I will be happy to test in ios/chrome and ios/opera mini.  Live627 fixed the issue with Safari, but not, as far as I can tell, with chrome.

**Comment by NanoSector** [comment]
Re-enabled. You should be able to test now, let me know if you need
dictionaries added or if something doesn't work.

**Comment by AngelinaBelle** [comment]
Thank you Yoshi.
It now appears to work in chrome, except for creating an extra blank tab, which remains when the spell check window closes itself.
![image](https://cloud.githubusercontent.com/assets/3267025/3682426/838dbaec-12cc-11e4-9254-fcb6e6d29f95.jpg)

In opera mini, nothing at all seems to happen when I hit the spell check button.
