### ISSUE TITLE
Alerts Errors

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1981]
Type of error: Undefined
8: Undefined index: alerts_no_unread
/Themes/default/Profile.template.php
Line: 145 
http://next.mmobrowser.com/index.php?action=profile;area=alerts_popup;counter=1

---

Type of error: Undefined
8: Undefined index: all_alerts
/Themes/default/Profile.template.php
Line: 99 
 http://next.mmobrowser.com/index.php?action=profile;area=alerts_popup;counter=1 

---

Type of error: Undefined
8: Undefined index: alert_settings
/Themes/default/Profile.template.php
Line: 96 
http://next.mmobrowser.com/index.php?action=profile;area=alerts_popup;counter=1 

---

Type of error: Undefined
8: Undefined index: mark_alerts_read
/Themes/default/Profile.template.php
Line: 95 
http://next.mmobrowser.com/index.php?action=profile;area=alerts_popup;counter=1

**Comment by illori** [comment]
also the alerts dont send email when the option is selected to send email and receive alert
