### ISSUE TITLE
notification page has text in curly brackets

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1988]
in older rev's there was no text in curly brackets

for example we have {member_link} liked your post {msg_msg}

before it was When a message of mine is liked

**Comment by illori** [comment]
{member_link} reported a post - {msg_msg} reported a post links to urlhere/github2.1/%7Bscripturl%7D%7Breport_link%7D this is not the correct link.

**Comment by NanoSector** [comment]
Can't reproduce: http://i.imgur.com/E5W4Rs6.png

**Comment by illori** [comment]
i see those language strings in profile.english.php just like that...

**Comment by NanoSector** [comment]
I don't: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/languages/Profile.english.php#L143
It's the same in my language file.

**Comment by illori** [comment]
seems like oldies fixed this already
