### ISSUE TITLE
Spell check finds all words misspelled, no change-to or suggestions-- iPad Safari

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1993]
In Safari on the iPad, spell check appears to start up ok, but does not actually do spell checking.

![image](https://cloud.githubusercontent.com/assets/3267025/3429353/a81347ba-0052-11e4-8647-6598f53086cc.jpg)
![image](https://cloud.githubusercontent.com/assets/3267025/3429354/a81b0284-0052-11e4-94d9-789d9d6271a3.jpg)

**Comment by NanoSector** [comment]
No issue on my phone nor my desktop. iOS bug.

We should tag these things with iOS and submit them to Apple...

**Comment by AngelinaBelle** [comment]
We would first how to figure out WHY it fails, or they will be uninterested.
Why does it fail?

Spell check fails differently in SMF 2.0.7, for example

**Comment by NanoSector** [comment]
I actually was ironic with the submitting to Apple thing,  it's just that most of the reports from your ipad are not an issue in SMF itself.

**Comment by live627** [comment]
Is this on my test site?

**Comment by AngelinaBelle** [comment]
Exactly the same EXCEPT THAT your website serves opera mini a 403 error, so I cannot test spell check

**Comment by live627** [comment]
The PHP module it uses is broken there. I opened a support ticket to try
and fix.

**Comment by live627** [comment]
ok, Enchant is installed, it should work now (I get suggestions)

**Comment by NanoSector** [comment]
I tried it on my test site and it failed to work.

**Comment by NanoSector** [comment]
Derp,  I mean it did work

**Comment by live627** [comment]
Yeah, it was broken on my site because Enchant wasn't installed.

**Comment by AngelinaBelle** [comment]
Seems to work well at http://livemods.net/21/index.php?action=post;topic=1.0;last_msg=2
On safari

**Comment by AngelinaBelle** [comment]
But it does not work on chrome
