### ISSUE TITLE
Email activation is broken

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#2002]
Follow the link in your email.  Nothing happens.

files from 28 june

**Comment by illori** [comment]
it works just fine for me.

**Comment by Oldiesmann** [comment]
What URL is it giving you?

**Comment by AngelinaBelle** [comment]
index.php?action=activate;u=2;code=a4f49f73bf

I also tried the alternate index.php?action=activate;u=2

In both cases, I was routed to the site home.

**Comment by AngelinaBelle** [comment]
Has this been fixed since 28 june?

**Comment by illori** [comment]
i doubt it since no one has reported any issues with it for the developers to look into fixing it.

**Comment by AngelinaBelle** [comment]
Seems fine now.
I am willing to believe this was user error.  Plausible: Thought I was logged out, but was not.
