### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by mashbychoppix** [SimpleMachines/SMF#2005]
With  Visual verification image to display set to Very Simple, the image is displaying 5 characters, but the audio is suggested there are 6 characters which isn't good.
![registration form](https://cloud.githubusercontent.com/assets/8038853/3445370/bfa59c72-0136-11e4-85d5-ad114f99f2b5.png)

**Comment by AngelinaBelle** [comment]
as of 28 june, Antes' last build, this was working just fine, so it may have gotten broken since then.

**Comment by illori** [comment]
the CAPTCHA has not been modified in i would say about a year.

**Comment by AngelinaBelle** [comment]
I just tested an install from files I got this morning 1 July.
I see 6 letters in the image.
Something unusual about the host setup at this test site?
Any errors in the log?

What other settings might be relevent?

**Comment by illori** [comment]
browser/device being used?

**Comment by AngelinaBelle** [comment]
I also visited the referenced test site.
I used IE9/Vista and Chrome 35/Vista and observed the same behavior -- only 5 letters in the image.

**Comment by mashbychoppix** [comment]
Originally discovered on Firefox. Confirmed in IE9.

**Comment by illori** [comment]
looks like it is only an issue when using very simple [or what i tested] the field needs to be increased in length. this requires a code edit in subs-graphics.php from what i can see. although i am not sure where exactly the change has to be made.

**Comment by illori** [comment]
actually it is line 903, maybe worth making it a bit too wide better then too short?

```
$total_width = $character_spacing * strlen($code) + 60;
```

**Comment by Oldiesmann** [comment]
Does increasing the width fix it at all? I don't have access to a machine with IE9 so I have no way to test the fix.

**Comment by AngelinaBelle** [comment]
I don't think this is a totally ie9 thing.  @mashbychoppix what platform did you observe this behavior on?
And why does this not happen on EVERY SMF2.1 test server?

**Comment by illori** [comment]
you can duplicate the issue in FF, i think just about any browser can when using the very simple setting for CAPTCHA.

**Comment by AngelinaBelle** [comment]
Good. it will be easy to test.

**Comment by Oldiesmann** [comment]
Changing the width on line 903 of Subs-Graphics.php to 50 (instead of 40) fixes it for "Extremely Simple", but the code is still cut off a bit if you have it set to "High" or "Extreme". It might be worth setting the width differently depending on the complexity. I'll take a further look at it after work tonight and see what I can come up with.

**Comment by XinYenFon** [comment]
``` php
    // Determine the dimensions of each character.
    if (($modSettings['visual_verification_type'] == 4) || ($modSettings['visual_verification_type'] == 5))
        $extra = 75;
    elseif ($modSettings['visual_verification_type'] == 1)
        $extra = 45;
    else
        $extra = 40;

    $total_width = $character_spacing * strlen($code) + $extra;
```

This fixes the problem but still admin panel gets the box-size as latest (saved) setting's value. Maybe a little css hack fix that too not really going deep.

**Comment by Oldiesmann** [comment]
We should be able to somehow dynamically change the width of the image since we're already changing the image style via JS.

**Comment by illori** [comment]
Can we tag this as a beta 1 issue? the CAPTCHA should be fixed before a beta release.
