### ISSUE TITLE
[Low Priority]Members waiting for admn approval are "lost" if admin switches to email activation

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#2006]
1) set admin approval needed for registration
2) get some new members registered; see them listed waiting for approval
3) switch to "email activation"
4) new members do not receive email
5) new members waiting for admin approval do not turn up <s>anywhere in the admin center.</s> in the "admin alerts"

6) switch back to "admin aproval" -- members awaiting approval are still there.

<s>Proposed fix:
- decision on whether to show the list of members awaiting admin approval depends NOT on current state of the setting but on whether there are any members on that list.</s>

**Comment by illori** [comment]
cant duplicate this, if a user is still awaiting approval they are still listed in the correct area in the membership list in the admin panel

![alt text](http://imageshack.com/a/img849/210/ajbm.png)

**Comment by AngelinaBelle** [comment]
I have amended my report, because it was very unclear and misleading.
It is in the "admin alerts" that they no longer show up.
I think they should show up in the admin alerts area if there are any, not just if there are users waiting for something related to the current state of the option.

Currently, an admin who has come to rely on "admin alerts" would miss the fact that she needs to go hunting in "members".

![image](https://cloud.githubusercontent.com/assets/3267025/3448130/802893aa-0155-11e4-8a65-9893e40703d9.png)

**Comment by illori** [comment]
you mean admin alerts in the alerts menu? going along with 2.0 the notice in the header goes away once the method of registration goes away. i dont think this really needs to be changed.

**Comment by AngelinaBelle** [comment]
It is an edge case, for sure, that could be brought on by a race condition (new member signs up just moments before/while admin changes approval method).

**Comment by illori** [comment]
i think there are more important bugs/issues to be resolved then this.

**Comment by AngelinaBelle** [comment]
I would not argue with a "low priority" tag on this.

**Comment by illori** [comment]
actually in my testing, those users that registered and required some type of activation do show in the alerts menu.

**Comment by AngelinaBelle** [comment]
that's funny -- not mine.  see pic above.

**Comment by illori** [comment]
its in the alerts menu not the admin menu.

**Comment by AngelinaBelle** [comment]
When "admin approve" is set, there is an alert in the navigation menu, not in the alerts at the top of the  page.
![image](https://cloud.githubusercontent.com/assets/3267025/3451324/6b8011f6-0193-11e4-9d04-3446f5fbb395.jpg)

**Comment by illori** [comment]
maybe you need to check your alert settings, as i am getting it as an alert. either way this is very minor.

**Comment by Arantor** [comment]
One could make the argument that if an admin changes from admin approval to anything else, that any floating accounts in that situation should also be updated anyway.

**Comment by albertlast** [comment]
Just for better understanding what should be happen,
when you change the mode from e-mail to admin with the pending regestration and
what should be happen when you change the mode to disable with pending regestration?

**Comment by jdarwood007** [comment]
I'm looking at this and think it shouldn't be fixed.  If they have changed the registration type, then we don't need to handle anything or show unapproved members.

At most, I think we could provide a help description reminder with a link to the member approval section letting them know any members who haven't been approved prior to these changes will remain that way.

Such as: Any members unapproved when changing from "Admin Approval" will remain unapproved.  Approve these members from [url=?action=admin;area=viewmembers;sa=browse;type=approve]Awaiting Approval[/url] section.

**Comment by illori** [comment]
as long as we can still access the section that lists these members, i dont think it is a big deal to leave it as is.

**Comment by jdarwood007** [comment]
Yes the section is still accessible through navigation to it.

Going to close then.  If there is enough requests to fix this, then we can look into my suggestion.
