### ISSUE TITLE
should users that require email activation show up in alerts?

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2008]
should a user that requires email activation show up in the alerts menu?

in 2.0 you dont get a message about users that require email activation [on the board index]

IMO the only alert that should show up is that a user requires admin approval, not email activation.

**Comment by Oldiesmann** [comment]
Maybe we could reword it a bit? It's really just telling you that a new member has registered.

**Comment by illori** [comment]
no it is not just telling you a new member has registered, it is telling you a member needs to be activated.

**Comment by Oldiesmann** [comment]
So again we just tweak the alert to only say that they registered even if they require email activation... Not a big deal

**Comment by illori** [comment]
no. we should only show if the user requires admin action, which means admin activation. we never told the admin that a user was waiting for email activation in 2.0, why should we in 2.1?

**Comment by Oldiesmann** [comment]
As I said above, we can tweak the alert so it won't say that they require email activation - only that a new member has registered. It's pointless to have a "notify me when a new member registers" option if we're not going to notify them unless admin action is required.

**Comment by illori** [comment]
i guess we may not agree on this.

also the admin is not receiving an email for this as well as any other alerts they request email on... generally all alerts dont send email.

**Comment by Oldiesmann** [comment]
The alert is "When a new person registers". If you don't think it should say that they require email activation, we can tweak the alert so that it doesn't say that. I'm not sure what the problem is. The forum is doing exactly what you wanted it to do there - telling you when a new person registers. If you don't want that, you can disable that alert in your profile.

I'm not sure what's going on with the emails. I'll have to look into that further.

**Comment by illori** [comment]
now i see. i was relating this to #2006 where AB says there is no notification. i guess i got a bit confused since in 2.0 we dont exactly get the same type of notice for those waiting for email approval.

**Comment by live627** [comment]
> I'm not sure what's going on with the emails. 

I might have fixed this in passing....

**Comment by MissAllSunday** [comment]
Whats the exact issue here?

If there is a setting to notify when an user registers then an alert should be issued every time theres a new member, regardless of the user's account state.  SMF shouldn't take any admin decisions, just show the alert and let the admin to ignore it or do what they want with it.

**Comment by illori** [comment]
It was a question. If you think it is working as expected them go ahead and
close it.

**Comment by colinschoen** [comment]
Bump, this seems resolved.
