### ISSUE TITLE
Force Gravatars to be used instead of normal avatars?

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2009]
if you select this option in the admin panel, then you have no option to input a url to your gravatar. is this what we want?

**Comment by live627** [comment]
Logic.

**Comment by illori** [comment]
and what does that mean?

**Comment by XinYenFon** [comment]
Actually with "force" she meant as default option, not the removing other avatar options.

**Comment by live627** [comment]
My bad, read the request wrong.

Definitely a bug.

**Comment by illori** [comment]
that did not fix it. now if you have gravatars enabled then you can not give the option to select a local avatar or a linked avatar, nothing shows.

**Comment by illori** [comment]
actually i was wrong, but this still does not fix the issue. if you force gravatar to be used you can not put in the link to the gravatar.

**Comment by illori** [comment]
nvm this is fixed, my script ran before this was committed.
