### ISSUE TITLE
default avatar not showing

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2010]
when you select an option for default image to show when an email address has no matching gravatar, you should see an avatar for the user but nothing is showing up.

**Comment by illori** [comment]
the default gravatar shows up only when you force gravatars to used instead of normal avatars.

**Comment by NanoSector** [comment]
Can't reproduce.

**Comment by illori** [comment]
i can still reproduce. if you dont force gravatar you dont have a default avatar for anyone.

**Comment by NanoSector** [comment]
Okay that I can reproduce.

**Comment by Oldiesmann** [comment]
It's the default avatar for those choosing a gravatar, not the default avatar for all users regardless of what the avatar options are

**Comment by NanoSector** [comment]
I think we need a setting for a default avatar, then, and possibly rename the Gravatar setting.

**Comment by illori** [comment]
sounds good to me.

**Comment by XinYenFon** [comment]
If user has no avatar it should fallback to Gravatar, if user has no gravatar then display nothing.

**Comment by illori** [comment]
then why have the option for a default gravatar? your proposal means no avatar if they have no gravatar. that is the opposite of what we are trying to do.

**Comment by XinYenFon** [comment]
yea it shouldn't be. tbh even you can go one step forward and remove uploading avatar/avatar gallery. Only allow linking external images as avatar & gravatar.

**Comment by Oldiesmann** [comment]
What benefit would that give people besides using less disk space/bandwidth?

**Comment by illori** [comment]
i think pushing everything to gravatar would piss off more users and we still need to support those that have linked/uploaded avatars from 2.0 and earlier.

**Comment by MissAllSunday** [comment]
Gravatar should be another option for the users along with linked and uploaded avatars.

There should be a default avatar for newly created users of those who don't want to use any of the options provided.

**Comment by illori** [comment]
currently if you do not have an avatar you dont have one, unless gravatar is forced to be the only option available. so this has to be changed.

**Comment by MissAllSunday** [comment]
the avatar code is already pretty convulsive and full of inline ternaries, why on earth would we want to make it worst?

I don't like the idea of forcing gravatar but if that would be the case then I suggest splitting the logic into 2 versions, one for gravatar (which also neds to include a default for users without a gravatar registered email anyway)  and our current convulsive code for displaying a linked, gallery, gravatar and/or uploaded avatar.

Since this is getting bigger and bigger, a bunch of ternaries just won't cut it anymore and another solution will have to be applied.

**Comment by illori** [comment]
currently as this bug says, you only get a default avatar if you enable the option to "Force Gravatars to be used instead of normal avatars?" to be used. so this has to be changed to not require the force option to be used to get a default avatar.

**Comment by live627** [comment]
The ternaries were already removed IIRC.
