### ISSUE TITLE
Undefined index errors related to quote notifications

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#2018]
Quoted a post that had a couple of quotes in it, and these errors show up in the error log related to the handleQuoteNotifications function...

Undefined index: id
.../CreatePost-Notify.php, line 206

Undefined index: mentioned_by
.../CreatePost-Notify.php, line 216

Undefined index: real_name
.../CreatePost-Notify.php, line 217

Note that none of the posts quoted were made by guests.

**Comment by Oldiesmann** [comment]
@Dragooon Any ideas?

**Comment by NanoSector** [comment]
Lookng at getQuotedMembers...
id => id_member on line 206
real_name isn't gathered.
mentioned_by is set nowhere.

**Comment by Oldiesmann** [comment]
@live627 Submit a PR for that please :)
