### ISSUE TITLE
Rewording a setting

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2022]
Show most recent posts at the top.

This setting string confused me at once too, it means like showing the most recent on boardindex at top. I suggest change to

Show most recent posts at the top in the topic. or something like that...

**Comment by illori** [comment]
it may be slightly confusing, but i dont think many actually use it to be a problem.

if we were to reword it something like

```
Show most recent posts at the top in topic view
```

may be slightly better.

**Comment by NanoSector** [comment]
I don't see the issue, SMF doesn't display posts outside of the topic view.

**Comment by live627** [comment]
> I don't see the issue, SMF doesn't display posts outside of the topic view.

O0

Profile, Recent, RSS...

**Comment by NanoSector** [comment]
Profile, yes. Has its own order.
RSS, yes, own order.
Recent shows topics, not posts.
