### ISSUE TITLE
Enable colorization for whole forum

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2025]
Since SMF colorize ranked members in some places (online/who etc...) this could be a nice addition to move to whole forum since SMF has $member['color']/$row['online_color'] etc...

**Comment by MissAllSunday** [comment]
It will create another set of options since no everyone would want to have that, you will end up using an ugly ternary on several files,  mostly template files since in a lot of places SMF just passes $memberContext straight to the template.

**Comment by XinYenFon** [comment]
Understand thx :)
