### ISSUE TITLE
$modSettings['defaultMaxMessages'] overusage

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2028]
this setting is used not only for max messages on the message index, but various other locations. i think it is a bit over used and other areas may want to be shown with more or less items per page.

this is used for attachments in the admin panel, why?
this is used for the number of PMs per page why?

etc, maybe a seperate setting or a hard coded value would make it easier to change for those admin want to have it at some other number.

**Comment by NanoSector** [comment]
> this is used for the number of PMs per page why?

Probably the original author thought PMs need to be handled like messages.

**Comment by Oldiesmann** [comment]
I can see how it could apply to PMs as well as they technically are messages. Looking through the code though, I see a couple of problems:
1. It's used in various other lists throughout SMF
2. In some places, the user option applies as well (inconsistently at that)

I think our best option here would be the following:
1. Make sure defaultMaxMessages applies to anything related to "messages" (recent posts, PMs, message index, etc.)
2. Add a new admin setting for "Max items per page in lists" (or similar), with an appropriate help popup that explains what it does, then apply this to other lists throughout SMF (attachments, warnings, ban items, etc. - pretty much any list that doesn't already have its own "max items per page" setting [so it wouldn't apply to the error log for instance]).

I really don't see a need for a separate "Max PMs per page" setting though.

**Comment by illori** [comment]
i think that is a good compromise.
