### ISSUE TITLE
Delete Upgrade

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2030]
in upgrade.php it tells the users to Delete Upgrade as step 5, it should say Delete Upgrade.php instead.

**Comment by XinYenFon** [comment]
actually its not just deleting upgrade.php but also upgrade related sql files.

**Comment by illori** [comment]
right, but you cant run the sql files without upgrade.php so they are not a security risk if left in place.

**Comment by XinYenFon** [comment]
"Delete this upgrade.php and its data files now. (doesn't work on all servers.)"

my upgrade.php Step 5 :P I'm not sure what's wrong with yours.

**Comment by illori** [comment]
user reported on sm.org that it did not include the .php, and it does not in the steps list on the right side.
![Alt text](http://imageshack.com/a/img856/3370/93ge.png)

**Comment by XinYenFon** [comment]
oh i see, added :)
