### ISSUE TITLE
cant disable maintenance mode from admin panel

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2032]
you can easily enable maintenance mode from the admin panel, but when you try to turn it off you get a message your changes were saved and are still in maintenance mode.

**Comment by XinYenFon** [comment]
Its also adding $maintenance to end of the file. That means its getting removed & re-added.

**Comment by NanoSector** [comment]
Not the case here @Antes. Fixed, committing fix.

**Comment by illori** [comment]
upgrade.php is adding $maintenance = 2; to the bottom of Settings.php. also i can duplicate that the setting in the admin panel is adding another entry to the bottom of Settings.php
