### ISSUE TITLE
email for message liked

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2037]
why can we not get an email if a message is liked? the checkbox can not be checked to get this alert emailed.

**Comment by MissAllSunday** [comment]
This was done on purpose and I prefer to stay that way.

**Comment by illori** [comment]
care to explain why?

**Comment by MissAllSunday** [comment]
The person who originally wrote that feature explained why on the code.

**Comment by illori** [comment]
and what file would that be in?

**Comment by MissAllSunday** [comment]
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/tasks/Likes-Notify.php#L74

**Comment by illori** [comment]
if it could lead to too many emails, it could not hurt to explain that to the user via a help popup so they dont have to ask why they cant check that box.

**Comment by Oldiesmann** [comment]
We can, but I don't see that preventing people from asking about it anyway (both because people don't read stuff in general and because people will still say they or their users won't care about the number of emails it generates, without even thinking about how it will affect the server side of things).

**Comment by illori** [comment]
they may ask but i would hope the team members would read new help popup's and this would help to inform them, and maybe some admin would read it too and can inform their users if the question comes up.

**Comment by MissAllSunday** [comment]
Highly unlikely I'm afraid.

This is exactly as other recurrent request regarding getting emails from specific events, it often is the admin him(her)self the one who ask how can the OP get an email when someone reply to his(her) topics, this is exactly the same request.

**Comment by MissAllSunday** [comment]
This can be closed I suppose.
