### ISSUE TITLE
profile -> notifications for PM email

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2038]
there is a help popup stating that the settings for PM's is set via the my messages list. you can still set the checkbox for receive email for pm's here anyway.

if you go to your settings for pm's you can additionally set if you want to be emailed for pm's received. seems like only the option in the PM area controls when you get the email.

so the additional option for "When a personal message I sent gets replied to" does not seem to work.

**Comment by Oldiesmann** [comment]
Looks like nobody remembered to code the appropriate background tasks for the options on the notifications page, though if we're going to put the options for board notifications there we should put the ones for PM notifications there as well.

**Comment by MissAllSunday** [comment]
Do we really need a notification for an email? seems redundant to me, it would be enough to set a notification for a pm and when a pm is read.

**Comment by illori** [comment]
the issue is the new notification page in the profile lists that you should get emails for pm's received, yet if you use those options you get no email and have to use the old setting in the pm area.
