### ISSUE TITLE
8: Undefined index: page_index

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2040]
/index.php?topic=1569.0;wap2
Sources/Subs.php
Line: 654 
Line: 624 
Line: 572
Line: 571 

Same link - same file different lines.

**Comment by illori** [comment]
on message index
Notice: Undefined index: page_index in F:\wamp\www\github2.1\Sources\Subs.php on line 571

Notice: Undefined index: page_index in F:\wamp\www\github2.1\Sources\Subs.php on line 572

Notice: Undefined index: page_index in F:\wamp\www\github2.1\Sources\Subs.php on line 624

Notice: Undefined index: page_index in F:\wamp\www\github2.1\Sources\Subs.php on line 639

Notice: Undefined index: page_index in F:\wamp\www\github2.1\Sources\Subs.php on line 652

Notice: Undefined index: page_index in F:\wamp\www\github2.1\Sources\Subs.php on line 654

Notice: Undefined index: page_index in F:\wamp\www\github2.1\Sources\Subs.php on line 571

Notice: Undefined index: page_index in F:\wamp\www\github2.1\Sources\Subs.php on line 572

Notice: Undefined index: page_index in F:\wamp\www\github2.1\Sources\Subs.php on line 654

Notice: Undefined index: page_index in F:\wamp\www\github2.1\Sources\Subs.php on line 571

Notice: Undefined index: page_index in F:\wamp\www\github2.1\Sources\Subs.php on line 572

Notice: Undefined index: page_index in F:\wamp\www\github2.1\Sources\Subs.php on line 654

**Comment by Oldiesmann** [comment]
$settings['page_index'] is set in index.template.php, so really we just need to set that in the Wireless template as well.

**Comment by live627** [comment]
Does anyone still use these age-old protocols? Is anyone opposed to removing this support, seeing as we now have a mobile-ready theme?

**Comment by illori** [comment]
i believe oldies would object to removing these modes.

**Comment by Oldiesmann** [comment]
I believe they're still used in some developing countries (particularly in parts of Africa). It certainly isn't hurting anything to leave them in, and we'd need to remove/rewrite a ton of code to actually get rid of them entirely.

**Comment by XinYenFon** [comment]
yeap i agree since this means bit lot code changes, I suggest leave it for SMF 2.1, we'll get rid of it in 3.0

**Comment by live627** [comment]
And removing SQLite wasn't? Riiight.

**Comment by illori** [comment]
if you could get sqlite to work correctly and the upgrade script to not error out, maybe we could add it back. it was something oldies decided was not worth spending more hours trying to fix for little benefit.

**Comment by live627** [comment]
Pfft. Fuck that. I'm actually glad it's gone.
