### ISSUE TITLE
guests can vote in polls

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2042]
the help string for vote in polls permission needs to be updated

"This permission allows a (registered) user to cast one vote. It doesn't apply to guests."

**Comment by Oldiesmann** [comment]
How does this sound as an addition to the text (in addition to removing the parts about it not applying to guests):

```
<strong>Note on guest voting:</strong> SMF uses cookies to attempt to prevent guests from voting multiple times. However, it should be noted that nothing can be done to completely prevent guests from voting twice, and as such, results many not be reliable. Also note that guest voting must be enabled on a per-poll basis.
```

**Comment by illori** [comment]
sounds good to me

**Comment by ChainyEO** [comment]
> ...results many not be reliable.

results **may** not be reliable.
