### ISSUE TITLE
Anti spam Q&A has a strange side effect under some circumstances

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#2064]
If an admin creates anti-spam questions for installed languages but neglects to set them up for the default language, the CAPTCHA will fail for users using the default language.

While other languages can be safely excluded, the default language should really have something set otherwise the CAPTCHA will just drop to a no_access error.

**Comment by Arantor** [comment]
Just to add, the backported mod solves this one by doing slightly different checks on $_POST['qa_verification_number'] and other stuff... in place of the existing choice. ManageSettings.php line 782 or thereabouts in 2.1 trunk.

```
        // Lastly, the count of messages needs to be no more than the lowest number of questions for any one language.
        $_POST['qa_verification_number'] = isset($_POST['qa_verification_number']) && (int) $_POST['qa_verification_number'] >= 0 ? $_POST['qa_verification_number'] : 0;
        $count_questions = empty($qs_per_lang) ? 0 : min($qs_per_lang);
        if (empty($count_questions) || $_POST['qa_verification_number'] > $count_questions)
            $_POST['qa_verification_number'] = $count_questions;
        // What if they didn't set any for their default language? Daft, I know, but you never know with users.
        if ($_POST['qa_verification_number'] > 0 && empty($qs_per_lang[strtr($language, array('-utf8' => ''))]))
            $_SESSION['qa_lang_error'] = true;
```

2.0 doesn't have any standardised way to handle errors on return - and you'll notice this is a _soft_ error. In 2.1 you'd interrupt the setting of `$_SESSION['adm-save']` to set the error message, assuming you wanted to do the same sort of thing. In my case the error message used is:

```
$txt['question_not_defined'] = 'You need to add a question and answer for your forum\'s default language (%1$s) otherwise users will not be able to fill in a CAPTCHA, meaning no registration.';
```

so it's clear what language the user needs to fill in. But it is not handled in the mod as a hard error - and I strongly suggest it isn't done as a hard error here! - because the dynamically added elements may not be preserved on browser back.

**Comment by live627** [comment]
I finally reproduced the error. Turns out that " Number of verification questions user must answer" cannot be zero.

**Comment by live627** [comment]
> In 2.1 you'd interrupt the setting of $_SESSION['adm-save'] to set the error message

Problem: Everything's still saved. Is that the desired behavior?

**Comment by live627** [comment]
Assuming the above behavior is wanted, will the following code work?

```
if (empty($context['qa_by_lang'][strtr($language, array('-utf8' => ''))]) && !empty($context['question_answers']))
{
    if (empty($context['settings_insert_above']))
        $context['settings_insert_above'] = '';

    $context['settings_insert_above'] .= '<div class="noticebox">' . sprintf($txt['question_not_defined'], $context['languages'][$language]['name']) . '</div>';
}
```

This way, it'll show when the user isn't saving.

Thoughts?

**Comment by Arantor** [comment]
Well, of course it is, you still need to keep what the user has already done, surely?
