### ISSUE TITLE
Saving quick edit puts the title back on the post

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#2072]
While it should be hidden. Will upload a screenshot once I'm on a computer.

**Comment by illori** [comment]
admin -> posts and topics -> topic settings do you have show subjects in topics enabled or disabled?

**Comment by NanoSector** [comment]
Disabled. The subject doesn't show on any post except the first.

**Comment by illori** [comment]
confirmed... actually the subject does not show on the first post it shows above the first post.

**Comment by Oldiesmann** [comment]
This is mostly fixed now. It will still show and allow you to edit the subject of each post during quick edit, but it won't actually show that subject above each post. I did try to get it to hide that as well, but doing that caused it to not save properly (the edit was going through, but it wasn't going back to showing the modified message afterwards for whatever reason).
