### ISSUE TITLE
pm setting show a popup does not work

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2077]
the pm setting show a popup when i receive new messages when checked does not seem to work in 2.1.

**Comment by Oldiesmann** [comment]
We can probably kill that setting since we have the "My Messages" box now.

**Comment by illori** [comment]
if you are not used to looking there then you can miss that you have any pms at all

**Comment by live627** [comment]
> We can probably kill that setting since we have the "My Messages" box now.

No, just no.

**Comment by live627** [comment]
I just tried it and it works.

**Comment by illori** [comment]
strange. it had not worked for me... i will have to test again.

**Comment by illori** [comment]
yep it worked that time.
