### ISSUE TITLE
namespace in ManageScheduledTasks.php

### ISSUE THREAD

**Issue by interlab** [SimpleMachines/SMF#2092]
I suggest:

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/ManageScheduledTasks.php#L145

find:

``` php
$completed = call_user_func('scheduled_' . $row['task']);
```

replace:

``` php
$completed = call_user_func($row['task'] . '_scheduled');
```

why?
To use the namespace: \mynamespace\myfunction_sheduled

**Comment by Oldiesmann** [comment]
The problem here is it results in us having to rename 11 existing functions in SMF, and the vast majority of users would never benefit from or take advantage of such a change.

**Comment by Dragooon** [comment]
Plus there's no point in implementing namespacing now for a single set of functions, this'll be in 3.0 when we get to it.

**Comment by MissAllSunday** [comment]
@interlab https://github.com/MissAllSunday/SMF2.1/commit/632d7a81a0eba0150fd0c9477d3ac5c1d25c7b01
Allows usage of your own methods.

Not exactly the same but at least it will let you toy with namespaces if you really want them.

**Comment by live627** [comment]
Nice!

**Comment by interlab** [comment]
@MissAllSunday, thanks
