### ISSUE TITLE
Big Sprite

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2095]
Can we create one big sprite for all images this will allow us to remove duplicated ones.

Except;
- Big (HD) icons (can be sprited on its own).
- Post icons
- BBC icons (can be sprited on its own).

**Comment by live627** [comment]
You and I have the same idea.

**Comment by XinYenFon** [comment]
my suggestion;
- create main sprite contains everything (generic_icons)
- create bbc sprite (bbc_icons)
- create hd sprite (hd_icons)
  remove rest (folders etc...) put all sprites to main images folder

**Comment by live627** [comment]
Thanks, will do.

I'm also thinking the large admin icons could get their own. Should the
small menu icons in the admin be in the same image, or their own?

**Comment by XinYenFon** [comment]
large icons called hd on SMF. yes they need to be separate. Lots of general items we can use. Its better to load one big sprite on each page, it won' look so optimal but, still better in general.

**Comment by live627** [comment]
I know what sprites are for and why. But - not looking optimal? I'm
confused here. I added three images to the sprite yesterday (the  warning
icons) and the display on the page didn't change for the worse.

**Comment by XinYenFon** [comment]
no i mean, we can create extra admin_icons (sprite) smaller sprites and on-demand loads (small size better loading speed). :P

**Comment by Oldiesmann** [comment]
What exactly is the point of this?

Spriting is good in some ways, but I would prefer to avoid spriting every thing that's currently a separate icon, because it makes themeing a pain in the rear (at least for those not familiar with the concept of spriting and how to do it).

**Comment by XinYenFon** [comment]
Well, more images more request, if you do one sprite that means one simple request. I see some sprites are takes less space. I think people should level up, we can't struggle with old fashion theming methods.

**Comment by XinYenFon** [comment]
When I bring this idea, i didn't ask for more inconsistency in SMF @live627 ...

**Comment by Akyhne** [comment]
I did something similar in my mobile theme. Feel free to steal as You like.

**Comment by XinYenFon** [comment]
Thanks to Arantor, i manage to do my ideal sprite image. Please use this (Sorry I'm uber busy with real life).

![generic_icons](https://cloud.githubusercontent.com/assets/1669995/3748592/4821ecc2-17df-11e4-9fca-d44c32cc2853.png)

**Comment by XinYenFon** [comment]
nvm I'll fix this myself.
