### ISSUE TITLE
Unable to set error headers

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#2110]
Would be useful upon fatal errors to be able to indicate an HTTP error. For example, a topic that was previously public that is now no longer public would issue a 403 Forbidden or even better a 410 Gone to indicate the URL shouldn't be recrawled. Of course it's always a bit tricky to judge that it wasn't a mistake and as such 403 or 404 might be better, but anything's better than a 200 for an error message.

**Comment by Oldiesmann** [comment]
So adding an extra parameter to fatal_error and/or fatal_lang_error for an optional HTTP status code should do (along with adding code to those functions to spit out said status code of course)
