### ISSUE TITLE
admin_icons_hd.png missing

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2116]
the admin panel icons seem to be missing

also the icons in the admin menu seem to be missing? the admin folder in the images folder is gone.

**Comment by XinYenFon** [comment]
yes sprite version of them will be added by @live627 
Ref: #2111

**Comment by illori** [comment]
so he removed the images and forgot to replace them...

**Comment by illori** [comment]
the icons for the menu are still missing

```
.dropmenu li li.subsections > a:after {
    background: url("../images/admin/subsection.png") no-repeat scroll 0 0 rgba(0, 0, 0, 0);
    content: "";
    height: 12px;
    position: absolute;
    right: 2px;
    top: 0.4em;
    width: 12px;
}
```
