### ISSUE TITLE
Stop touching Load.php

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#2120]
Can you please stop using the filemtime of Load.php as a cache invalidation trigger?

I don't recall care what you do with it - I'd suggest an empty file in $cachedir personally - but using filemtime(Load.php) means you have to leave access writable for it to work reliably _and_ you're bumping the mtime of a core file in a way that looks suspicious.

**Comment by Oldiesmann** [comment]
We can always just use the existing index.php in the cache directory, since its only purpose is to prevent people from accessing that directory directly (or at least on servers that don't support .htaccess).

**Comment by Arantor** [comment]
This isn't fixed. Now caching is just unable to be invalidated.

**Comment by Oldiesmann** [comment]
Should be fixed now, so closing this again.
