### ISSUE TITLE
rtl.css

### ISSUE THREAD

**Issue by islam2hamy** [SimpleMachines/SMF#2124]
in the path "\Themes\default\css" there is the "rtl.css" file
which is used to overwrite the "index.css" ,During using RTL language 
i have editing the file by delete , edit , and adding some lines to make it work with the smf2.1 new default theme

and now i need some one to review it , to public it when it is ready ,

http://www.speedyshare.com/5uszc/rtl.rar

thank you

**Comment by illori** [comment]
you would be best to open a PR with this. as it is this can not easily be merged and requires you to sign off the changes anyway.

**Comment by islam2hamy** [comment]
Sorry , i didn't know that

Thank you illori.
