### ISSUE TITLE
buttons in editor not displaying correctly

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2128]
the buttons in the editor seem to half not show up since the recent changes

@live627 can you look into this?

**Comment by illori** [comment]
seems an issue of another image file gone missing

```
div.sceditor-grip, .sceditor-button div {
    background-image: url("../images/editor_icons.png");
    background-repeat: no-repeat;
    height: 16px;
    width: 16px;
}
```

only those images that are not a part of editor_icons.png show up.

also we have gained a new button to insert an emotion, i am not sure we really need that one.

**Comment by illori** [comment]
so now we have a youtube icon showing... click it and you get pre tags showing in the editor. also now our toggle between modes is not showing the correct icon, it is a piece of paper?

**Comment by Oldiesmann** [comment]
Also, we've never had an editor button for emoticons before.

**Comment by illori** [comment]
when you do use the editor toggle, now we can no longer see which mode we are in.

also the icons used to have a white background not gray as they do now.

**Comment by illori** [comment]
in quick reply without the full editor showing you get the button for emoticons showing which should not be showing at all.

**Comment by illori** [comment]
why have we lost our list of smileys and stuck with the drop down? the more button in it does not even work. please reopen and put the list that is always displayed back.

**Comment by XinYenFon** [comment]
Did you count? SMF displaying 16 smileys on the list I removed, drop also shows 16...

**Comment by illori** [comment]
and the more button does not work with the drop down that is there. so we are adding more bugs then we are fixing. the old method had no problems, so why remove it and break more things?

**Comment by XinYenFon** [comment]
Nothing is broken, but "more" button does not doing its job (probably SCEditor bug but not sure). With those changes we require less code (extra). If you don't like the drop-down you can always ask someone to create a mod for you.

**Comment by illori** [comment]
if it is not working then it is broken. no other way around it.

**Comment by XinYenFon** [comment]
But the thing here, drop menu showing the smileys you add (via Subs-Editor.php). So drop menu has no major issues but a small problem it shouldn't be showing more than X smileys on first open (More button should show all or X more).

**Comment by illori** [comment]
more as defined in the admin panel, should open a popup not just add more to the list.

**Comment by Oldiesmann** [comment]
Why are we suddenly changing the way smileys are displayed? They should display in rows and/or in a popup like they always have, not in a dropdown list.

**Comment by XinYenFon** [comment]
I think @live627 already fixed some of the problems with editor, rest reported #2169

**Comment by XinYenFon** [comment]
I have to ask before request close on this, what else is needed? Please take a look at #2169 first.

**Comment by illori** [comment]
no one has decided for certain if the smileys stay as they are now or if changes are required in anyway. that seems covered in the other issue.
