### ISSUE TITLE
Package backup is broken

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#2141]
The routine that creates a backup of the installation prior to installing a mod is broken. The archive files produced are damaged where 7zip reports an error due to content being after the end of file marker. Simply the file becomes too big for the original routine to handle and it seems to mash the tar headers (since the gzip part is fine, it's the inner tar that's broken)

This applies to 2.0 and 2.1 as far as I can tell.

**Comment by Oldiesmann** [comment]
Any suggestions on how to fix this? Would using PEAR's Archive_Tar work better perhaps?

**Comment by Arantor** [comment]
I got nothing. I don't actually know _why_ it's broken, only that it is.

**Comment by Oldiesmann** [comment]
It probably can't hurt to at least try Archive_Tar. If anything it'd at least be simpler than the current code.

**Comment by margarett** [comment]
I was testing this and it I can unpack the files with winrar or Total Commander's built-in unpacker without issues...
(Testing in 2.0.8)

**Comment by Arantor** [comment]
How big is the archive? Once it stretches past 8MB unpacked, it seems to fall over.

**Comment by margarett** [comment]
Yeah, not quite
The tar file is 6.773.760 bytes
I guess I have to add some more trash to my test board :tongue: 
Also on 2.0.8 ;)

**Comment by margarett** [comment]
Update: I installed a bunch of themes so that the backup grows up to 8,20Mb unpacked. I can still unpack it with Winrar or Total Commander...

**Comment by live627** [comment]
Would it depend on memory_limit (I haven't looked at the code)?

**Comment by Arantor** [comment]
Not memory_limit related as far as I could tell.

**Comment by live627** [comment]
Am now looking into this. Strangely enough, I have no backups from this year. I wonder if it's incompatible with PHP 5.6...

**Comment by live627** [comment]
Hah, had the option off.

**Comment by margarett** [comment]
Did you manage to reproduce this? I wasn't able to reproduce it at the time (with 2.0.8, I don't think I have enough trash to throw at 2.1 :tongue: )

**Comment by live627** [comment]
Oh yes..

**Comment by margarett** [comment]
Oh yes like, you were able to reproduce? Can you give me a "how to reproduce" guide? :tongue:

**Comment by live627** [comment]
Yes, open the tarball within the gzipped  file :tongue:
