### ISSUE TITLE
Redirect boards can be posted in if not set to 'read-only'

### ISSUE THREAD

**Issue by jasonclemons** [SimpleMachines/SMF#2158]
This issue can be replicated in both 2.0 and 2.1. Simply navigate to http://www.example.com/forum/index.php?action=post;board={redirect_board_id} and it will let you post new topics.

Evidence of this can be found both at http://jasonclemons.me/smf-mobile (2.0.8) and http://jasonclemons.me/smf (2.1)

This can be fixed by forcing redirect boards to have the 'read-only' profile upon creation, however, that does not remove the ability of Admin's to create posts there.

**Comment by Oldiesmann** [comment]
The easiest way is to just see if it's a redirect board and throw an error if it is.
