### ISSUE TITLE
UTF-8 mb4 characters not supported

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#2162]
As per http://www.simplemachines.org/community/index.php?topic=525846.0 it is not possible to store 4-byte UTF-8 characters in the current setup for MySQL.

Switching to UTF-8 mb4 (utf8mb4 character set, probably utf8mb4_unicode_ci collation) will allow you to store even the 4 byte characters, however it may also have unwanted side effects. PGSQL in particular doesn't support it being listed as utf8mb4 but its native UTF-8 support seems to support 4 byte characters anyway, and you would have to update the SET NAMES query to match.

In theory you could probably re-represent the 4 byte code points as entities, but you're going to be hitting some of the internal entity checking; while most of the entity tests accept 7-digit entities (e.g. `&#1000000;`) I'm pretty sure that's not the case everywhere and I don't know how if there are edge cases to be taken care of there too.

**Comment by live627** [comment]
This requires MySQL 5.5.3.

**Comment by Arantor** [comment]
In which case you either need to look at raising the version or figuring out a way to re-encode that stuff in 7-bit safe entity form.

**Comment by Oldiesmann** [comment]
The MySQL 5.1 branch is 8 years old at this point (though MySQL continued releasing patches and bugfixes for it until late last year), and MySQL officially "encouraged" people to upgrade to 5.5 when they stopped patches for 5.0 in January of 2012. Is 5.1 still widely used at this point?

**Comment by Arantor** [comment]
On the presumption that you're going to deal with this the hard way (by not going to MySQL 5.5 and going utf8mb4), you will instead have to decode the entities yourself and parse them back to numeric entities.

This is a very complex task with bitshifting, but it is certainly possible to do. You'll be looking in UTF-8 cases for bytes in the range of 240 to 247 (4 byte UTF-8 is always denoted by a byte whose value is 11110xxx where the three bits are the topmost bits of the codepoint) which you can't do safely with preg_\* functions meaning a scrape byte by byte. It isn't pretty.

From there, you rebuild the codepoint's value by appropriate bitshifting from those three bits, plus the 6 least significant bits of the following three bytes, to build a complete 21 bit number that makes up the code point. Having obtained the code point it is a trivial matter then to wrap it as an entity and transpose it back in.

This shouldn't be difficult to write as a single function and ideally probably should be fused inside the $smcFunc functions but this is something I would not encourage doing lightly.

**Comment by BitFros7y** [comment]
And that would be unnecessary to bother with, if it can be fixed with pushing requirements to Mysql 5.5 as it is stable for quite some time and already have been recommended by MySql developers.

**Comment by Arantor** [comment]
5.5 would appear to be quite a high bar to mandate given that pretty much all the other forum systems don't require it yet.

**Comment by XinYenFon** [comment]
Due to time period of, mods/themes adaptation to SMF 2.1 and ofc gold release etc... This period will/may take at least 2 years to my calculations. I can only speak as Marketing side.

**Comment by Arantor** [comment]
That's a shame, because that would make 2.1 take a full 5 years like 2.0 told. If it takes longer than a year, I would assume something is already terribly wrong.

**Comment by Oldiesmann** [comment]
I sincerely doubt it will take us 2 years to get to gold for 2.1. One year maybe, but definitely not 2.

**Comment by XinYenFon** [comment]
This is not just about development (software) also modifications/themes, I'm talking about whole system of SMF. It probably take 2 years or 3... Some people struggle to move SMF 2.0 from SMF 1.1, this probably happen in 2.0 to 2.1 as well.

**Comment by Arantor** [comment]
If you're talking about the whole system of SMF, there are still many mods that don't even work on stable 2.0 properly - 3 years after it launched. You cannot reliably include them in the discussion of the ecosystem for something that is purely contained as a core function and core requirement.

**Comment by tekkla** [comment]
Every mod which is not maintained anymore should be flagged in some way as abandoned. Try to keep compatibility to mods created for minimum 2.0 final. Inform your active modcreators about the changes that are relevant for them and the idea of being more future oriented with this change. Write better now than later a regular (more than a few times in many months) techblog about the coding changes relevant for mod creation. Inform modcreators that only a mod for final versions will make it's way into the official mod page. When version of SMF changes they have to recheck their mods within 4 or 8 weeks to flag them as compatible with this release. If they do not react, assume this mod as abandoned. 
When you don't have the (wo)manpower to provide backward compatibility back to stoneage and future at the same time, you should rethink your priorities and the mod version (compatibility) handling in general.

**Comment by Arantor** [comment]
Given that 1.1 is still technically supported, that would have to be factored in.

Additionally, virtually any mod for 2.0 RC4 and up will work on 2.0 final and later - but there are specific exceptions. Pretty URLs for example conflicted with changes in 2.0.7/8.

The largest problem is that it's not actually up to the team to manage it. They don't claim responsibility over mods and therefore cannot legitimately claim compatibility or not - that's up to the author. Though I would agree that marking 'not maintained' is probably not a bad thing, and there are facilities for such, but given that mods which haven't been touched in years still work just fine, it's a bit of a blunt instrument to do such.

**Comment by tekkla** [comment]
I think it's not the teams job to manage compatibility checks of older and not for the current version released mods. Softwaredevelopment needs to move forward. Remember "good old" IE 6 times and what it takes to proper webcontent for it? Now IE 6 is gone and even IE7 and 8 are not really important anymore. If a developer wants it's stuff running on modern browsers, he had to change his old code to make it compatible. The weddev not MS.

My thoughts are about getting more room for future oriented decisions. Following the 2.1 development over the last year and the statetment in this discussion about another 2 or 3 years to become gold, made it clear to me, that the dev team is to small to take care of all this backward compat stuff. Do yourself a favor and break some chains to get more room for the really cool stuff of today and tomorrow. 

Do not understand this as a blame, please. I do no want it to be understood like this. See it more like a good minded hint from outside of the inner circle.

**Comment by XinYenFon** [comment]
To clear something, i didn't say gold release will be in 2 or 3 years, i said community (mods/themes/tips-tricks/sites) will be converted and adapted to SMF 2.1 in that time period.

**Comment by live627** [comment]
heh

**Comment by tekkla** [comment]
Even one year as Oldiesmanm mentioned is some sort of "smells like Debian". When will nebulous 3.0 be released then? 2020?

**Comment by live627** [comment]
3030 :P

You said nebulous...

Maybe that could be it's codename not.

**Comment by Arantor** [comment]
Saguaro is the codename for 3.0 and has been for years.

I see where Antes is coming from, but in all honesty that's not the team's problem. Yes adoption of the system will take time beyond the release but _none of that matters_. This issue is about the core, and the timescale to deploy core, everything else is irrelevant.

Actually I suggested in jest that 2020 would be the release of 3.0, but it seems less and less like jest these days :frowning:

Whatever the deployment cycle of 2.1 though, it doesn't actually affect this issue. If in the next year MySQL 5.5 adoption is common, this issue can be dealt with by bumping minimum requirements. If not, figure out a software patch for it. It must be doable.
