### ISSUE TITLE
After SCEditor Update

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2169]
So here is some problems we face after upgrading the SCEditor.
- [ ] SCEditor smiley pop does not show all smileys in one row; this is problem when you sort smileys (7 smileys on first line 5 in second etc...)
- [ ] Smiley pop respects the line (sort in admin) but cannot create new line instead inserting -0 / -1
- [x] More button does not functioning
- [x] Quote has different styling on toggle mod inside SCEditor textarea
- [x] Quote has different behavior on [quote]Something[/quote] and

**Comment by illori** [comment]
more button does not show more smileys, also that does not fix the language string issue that the admin panel says we are showing smileys in a popup.

**Comment by XinYenFon** [comment]
Live fixed that, update your build and move some smileys to "popup/more" place (yes you are right language strings needs to change to reflect that).

**Comment by illori** [comment]
ok, it is fixed but this also does not seem to do anything about the smiley post form order, the admin panel shows them all in one row but the post drop down does not. i think with this change to the drop down in general will make users think smf dropped support for smileys completely.

**Comment by XinYenFon** [comment]
I listed those in the report, they'll be fixed and users will be noticed with a blog post about those changes.

**Comment by illori** [comment]
i really dont think they should be changed... and what if you have a ton of smileys? 100+ they will not easily fit in this box.

**Comment by illori** [comment]
if you add the lots o smileys pack, move those to the more/popup you end up with something like this:
![](https://imagizer.imageshack.us/v2/426x528q90/673/XSiys9.png)

**Comment by BitFros7y** [comment]
And why would you have so many smileys? In any case if someone have so many smileys its gonna be a mess ether way you display them...

**Comment by XinYenFon** [comment]
Is this 51% ? Minority problems not really a problem unless its a proven bug. This is not a bug. You still see the smileys in the list.

**Comment by Oldiesmann** [comment]
Again, why are we changing how smileys are displayed? SMF has always displayed them either inline on the editor or in a popup when a "[more]" link is clicked. It should remain that way in my opinion.

**Comment by BitFros7y** [comment]
Why you even bother with these? Popup, Dropdown or inline...its all the same...point is: "Its working perfect!". If someone dont like the way smileys are displayed, modification can fix it.. Leave these GUI things for beta and minor versions when you will have much more feedback...

**Comment by live627** [comment]
> It should remain that way in my opinion.

Then you fix it, because I won't. Bloody hell.
