### ISSUE TITLE
Faulty topic links in message index (board view)

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#2171]
When you click on the title of a topic (in the message index) you get taken to the topic, but to the wrong part of the page. 

For example, if there's a poll, you'd expect to be able to see the poll when clicking on the link, but you have to scroll upwards to find it...

Even in the case of the default topic "Welcome to SMF!", when you click on the topic title, you see the message, but the username "Simple Machines" and the date of the message are not visible, unless you scroll up a bit.

**Comment by illori** [comment]
i have had issues with this for some time, even the new button does not take you to the correct place everytime, or clicking the topic link.
