### ISSUE TITLE
conflicting moderation actions

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2173]
is there a way SMF can warn a moderator when a moderation action was already completed on a thread while you are on the thread?

for example if you are on thread A and moderator is on the same thread and locks the thread before you do, there is nothing to tell you that you have unlocked the thread instead of locking it. same applies to moving a thread.

**Comment by Oldiesmann** [comment]
If a topic is moved while you're replying, you'll get an error (lines 1285-1287 of Post.php):

``` php
        // Did this topic suddenly move? Just checking...
        if ($topic_info['id_board'] != $board)
            fatal_lang_error('not_a_topic');
```

The lock thing (and the similar issue with stickying) should be pretty easy to handle - add a hidden input field indicating whether or not the topic was locked when you loaded the reply form, then throw a warning message at you if the topic's lock status is different when you go to post a reply (similar to what we do for "new replies posted while you were typing").

**Comment by emanuele45** [comment]
> same applies to moving a thread.

http://dev.simplemachines.org/mantis/view.php?id=4910

**Comment by Oldiesmann** [comment]
Locking/stickying has been dealt with now. Not really sure we can do anything about topics being moved while you're posting, since you should already get an error if that happens (I haven't tested to see what actually triggers that error though).

**Comment by illori** [comment]
What about if you are not posting and just lock a thread?

**Comment by Oldiesmann** [comment]
I think it's fine the way it is now. It's highly unlikely that multiple moderators would attempt the same action on the same topic(s) at nearly the same time. I don't think it's worth the effort to address this any further.

**Comment by illori** [comment]
Well it has happened recently. I do think it may happen again.

**Comment by Oldiesmann** [comment]
Yes, it can happen, but I don't think it happens often enough that it's worth adding several dozen more lines of code to handle it (the changes made to handle it during posting are relatively simple compared to what we'd need to do to handle it in the other three places where you can sticky/lock a topic).
