### ISSUE TITLE
Create an entire backup (excluding smileys, avatars and attachments) of the SMF install.

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2182]
this feature is listed on the options page under package manager. is this a way to disable the auto backup that is created when you install a mod? if so the string of it is misleading. i would think that when i save this page it will create a backup, but it does not. also if this is the package manager backup it does not include every file, for example the Settings.php file is not backed up when you install a mod.

**Comment by Oldiesmann** [comment]
Yes, that's a way to disable the backup. We can tweak the wording slightly to include "when a package is installed, uninstalled or upgraded" or something similar.

It only backs up files that a mod would touch - template/language/js/css files, the Sources directory, index.php, agreement.txt, the SSI files (SSI.php, ssi_examples.php and ssi_examples.shtml) and subscriptions.php (though we should add cron.php to that list for 2.1). This creates a smaller package size and uses less memory. There's really no need to back up Settings.php as no mod should ever be editing that file, and you've already got Settings_bak.php anyway.

**Comment by illori** [comment]
you might not want a mod to edit Settings.php but we have seen a few [i dont know if they actually got approved], it cant hurt to backup a very important file like Settings.php.

yes changing the wording like that would work.

**Comment by margarett** [comment]
Here's one :tongue: 
http://custom.simplemachines.org/mods/index.php?mod=3919

I don't recall any guidelines about not using Settings.php so I'd say we either explicitly deny it in the guidelines or this auto-backup should probably include Settings.php.

**Comment by Oldiesmann** [comment]
That's a special case, but really nothing should be touching Settings.php directly. If new settings are needed, they should be added via saveSettings, which will automatically back up Settings.php before saving changes.

**Comment by margarett** [comment]
So that really has to go into the guidelines... ;)

Can saveSettings be used in a package?

**Comment by Arantor** [comment]
In theory, sure, but there are surprisingly few good reasons to edit Settings.php. Without seeing the package I couldn't tell you if this was done for a good reason or not. Usually not necessary though.

**Comment by sbulen** [comment]
I submitted a PR to change the wording of the prompt per suggestions above.

I couldn't tell if y'all ended up aligned on backing up settings.php or not.   I did not do that.  I can add it to the backup if desired.   Let me know.  

I have a (slight) learning towards NOT backing it up, because that's just another place to worry about security-wise, given that it has critical logon information embedded within.

**Comment by sbulen** [comment]
@illori - let me know if this is sufficient to close the issue.

**Comment by illori** [comment]
i would leave out the part about upgrade as that is still an install of a package. otherwise i think it is ok. i still think we should include Settings.php in the backup it is a very important file and even if we do tell users to do a backup they dont always, this way they do have a backup of this file as well.

**Comment by sbulen** [comment]
Will do.

**Comment by sbulen** [comment]
Also fixing problem where the duplicate file logic doesn't work...   An install, de-install, & install again fails on file exists error...  

![backupmsg](https://cloud.githubusercontent.com/assets/23568484/24641968/b17afc68-18b8-11e7-8207-a9e9bd5386ad.JPG)

![backupmsg-log](https://cloud.githubusercontent.com/assets/23568484/24641974/b502f656-18b8-11e7-8418-8c0580ed07e7.JPG)
