### ISSUE TITLE
Minutes to stay logged in: negative values

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#2185]
In the box for "Minutes to stay logged in" there's an up and down arrow. Maybe it would be a good idea to prevent the down arrow from taking us into negative values:

![negative_mins_login](https://cloud.githubusercontent.com/assets/3731638/3912190/81d185b4-2328-11e4-8ae5-ee6ad3b82330.png)

EDIT: Or maybe "Minutes to stay logged in" won't remain as an option? (https://github.com/SimpleMachines/SMF2.1/issues/1087)

**Comment by Oldiesmann** [comment]
Right now we'll keep it the way it is, as changing how login cookies are handled is a big task which will only further delay getting a beta out...
