### ISSUE TITLE
Login dropdown box: display problems

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#2186]
When the session has timed out and you try clicking on the username, the dropdown login box is fully visible, but the userbox under it doesn't expand with it (well, it does downwards, but not to the right):

![login_dropdown1](https://cloud.githubusercontent.com/assets/3731638/3912781/a8dcb6f0-232e-11e4-9dc0-323635314583.png)

If you click on "My Messages", then you can only see part of the login box:

![login_dropdown2](https://cloud.githubusercontent.com/assets/3731638/3912783/aff210c0-232e-11e4-83ac-b1ce1c2281db.png)

And the same goes for when you click on "Alerts":

![login_dropdown3](https://cloud.githubusercontent.com/assets/3731638/3912785/b5efc8b4-232e-11e4-9540-8b4bfdb71911.png)

**Comment by XinYenFon** [comment]
Yeap, messages & alerts has jQ scroll plugin (with overflow: hidden). It could be better to redirect to login page. I'll think proper fix for this.
