### ISSUE TITLE
Three different login displays: inconsistent?

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#2187]
Is it a good idea to have three different ways of displaying the login? Maybe it would be better to stick with one?

We currently have:
1. Popup box:
   ![login popup](https://cloud.githubusercontent.com/assets/3731638/3913267/ed4088bc-2333-11e4-89da-a62462b58394.png)
2. Dropdown box:
   ![login_dropdown1](https://cloud.githubusercontent.com/assets/3731638/3913276/0b3b9ba4-2334-11e4-90fd-c5cb0654606c.png)
3. Traditional login display:

![traditional login](https://cloud.githubusercontent.com/assets/3731638/3913302/47c85f76-2334-11e4-8e70-11f98c6aeb67.png)

**Comment by XinYenFon** [comment]
Actually 2 & 3 same. and first one getting some part of 3, not inconsistency :P

**Comment by XinYenFon** [comment]
Can we close this? There is no inconsistency in it. This is how its designed. To clear things, those popup login boxes are not actually coded, they are taken from login action. So we either need to change login popup to take more of that page (which is not needed) or rewrite the login action UI. None of those really needed and not worth it.

**Comment by BitFros7y** [comment]
Yeah 1 and 2 are actually ONE (thats actually fast/quick login from older versions than 2.1) and 3 is actual login page. If your credentials are not accepted than you will be redirected to 3 where possible errors will be displayed.

**Comment by ChainyEO** [comment]
Just an extra note as I'm not sure you understood the point I was trying to make.

1 and 2 are apparently drawn from the same code, but they are still displayed on the page in different ways. Version 1 is shown in the drop-down menu when you click on items in "Username/My Messages/Alerts", whereas version 2 is displayed as a pop-up. How about displaying both of these as a pop-up? (maybe a pop-up could also replace the third version, too?). 

The point I was trying to make was one of consistency. I don't necessarily support the idea of the pop-up version being used everywhere, but I think it might be good to stick to one display method.

**Comment by live627** [comment]
oh I get it, however, the top drop downs only show login forms in abnormal
situations.  In theory, anyway...
