### ISSUE TITLE
SMF won't let you delete first smiley set in the list

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#2195]
Due to the way SMF works, you cannot delete the smiley set that's listed first in the database. This is in part to prevent you from being able to delete a set if it's the only one installed, but at the same time this means if another set is default, you can only delete the other sets if they're not first in the list in the database.

**Comment by illori** [comment]
this is the same idea that you can not delete the default theme, it is a safety fallback. i think it would a really bad idea to disable this and allow that set to be deleted.

it is possible to force the forum members to only use the set that is default, or to select others. i dont really think this is an issue.

**Comment by Oldiesmann** [comment]
The problem is it doesn't matter which set you've got marked as default - if it's the first one in the list in the database, you can't delete it. If it's not, you can delete it (even if it's the one you have marked as default - SMF will simply fall back to the first one in the database in that situation). The order of the sets in the database never changes.

I think a better solution would be to not allow you to delete the set you've got marked as default. That way you always have at least one set installed and you don't end up with multiple sets when you only want one specific set.
