### ISSUE TITLE
spider log in wrong order?

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2199]
since this was added in 2.0 it has always listed the _oldest_ entries in the list on the first page. can we have it list the most recent items first?

**Comment by Arantor** [comment]
Better question: what use does the spider log serve? Would it not be better to rip out the configuration aspect of it, rip out the logging and simply have it all turned on (because if it's hardcoded + a hook you find yourself with _better_ performance than where you are now)

**Comment by illori** [comment]
i find it useful at times to know i am getting hits from the spiders, but i may be rare in that respect

**Comment by XinYenFon** [comment]
for all those years I never used that actually, if i really need to collect data (and do marketing) I use GA. I'm 75% sure lots of people enabling it because of misunderstanding (SE != SEO) ;)

**Comment by Oldiesmann** [comment]
Arantor: If we rip out the logging aspect, what exactly would we have turned on? Also, the settings currently allow you to choose how much info is logged, so ripping out the configuration means we'd have to settle on a default level of info and rely on mods for adding other stuff back in.

**Comment by illori** [comment]
Part of it is showing spiders in who's online and to who

**Comment by Arantor** [comment]
You would have the showing of spiders in the who's online area. You would also have $user_info['possibly_robot'] also be correct.

The thing is, if you don't make it configurable, you can have more info by default because you don't have the overhead of deciding what you're logging - and not have any performance quirks out of it.

**Comment by smfbigguy** [comment]
Just asking but is this an issue any more. I find the logs useful and nice to view once and awhile. The order could be changed though I guess, but really it seems fine, why mess with it. (Just my opinion)
