### ISSUE TITLE
About beta

### ISSUE THREAD

**Issue by BitFros7y** [SimpleMachines/SMF#2203]
I didnt find any clear guidelines for beta. So my question is will someone push them to github as milestone? These way we cant know anything...

Also i think 2.1 must go beta as fast as possible, its much awaited and developed for a long time. If its not going to be beta soon at least make clear list of features for it and announce features freeze so that people can apply fixes and speed up process...

**Comment by live627** [comment]
I'm hoping @Oldiesmann will. I already started this discussion internally...

**Comment by XinYenFon** [comment]
This is not open for discussion, please wait for team to decide when beta will be released.

**Comment by Dragooon** [comment]
Not an issue, if you have general comments/question please use http://simplemachines.org
