### ISSUE TITLE
Rename section in Package Manager to "Upload Packages"?

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#2204]
Following https://github.com/SimpleMachines/SMF2.1/issues/1458, maybe it would be better to rename the menu item in the Admin Center to "Upload Packages". At the moment, it's still called "Download Packages" (_Admin > Main > Package Manager > Download Packages_)

**Comment by NanoSector** [comment]
For the forum, it makes more sense to call it download packages, because the forum downloads the packages from the user. But, the forum is talking to the user and not to itself so yes, I think this should be changed as well :)

**Comment by live627** [comment]
Obtain Packages... whyam I up at 3 n the morning? :P

**Comment by NanoSector** [comment]
Obtain Packages, Add Packages, Upload Packages... The first two would work, the latter doesn't describe the page in full.

**Comment by ChainyEO** [comment]
@Yoshi2889 

I quite like your suggestion of "Add Packages". It covers uploads and downloads. I don't think "obtain" is suitable, as in the case of the upload section, you obtain the packages separately (not via this section).

Initially, I suggested "Upload Packages" just because this has now been made the prominent feature of this section (https://github.com/SimpleMachines/SMF2.1/commit/22f493a2f36f8e882a9ddabb805efe0a682dc4cd). The Download part has now been collapsed by default. However, maybe "Add Packages" would indeed be even better.

**Comment by Arantor** [comment]
Add Packages is suitably generic and covers all three aspects concerning getting packages to an installation.
