### ISSUE TITLE
(+2.0) Workaround for signature images bigger than allowed size

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#2205]
Steps to reproduce:
(needs a REGULAR user account. Admins seem to always allow images regardless of size)
1. Put in an image of lesser or equal than allowed size. The forum will not apply any resizing (the image passed the size validation).
2. Save the signature.
3. Replace the image with an image of bigger size than allowed size. Do not modify signature. Because the forum previously allowed the image, it will not re-check it and show the bigger image anyway.

Examples:
https://nanosector.ddns.net/smf20/index.php?action=profile;area=summary;u=5
https://nanosector.ddns.net/smf21/index.php?action=profile;area=summary;u=2
Both forums have the max size set at 50x50. And that's clearly not 50x50 :P
(as you can see, it also applies in 2.0)

**Comment by Oldiesmann** [comment]
Signature validation is only done when the signature is previewed, when it's saved or when the admin chooses to re-validate signatures in the admin center. The only way we can fix this is to re-validate the signature each time it's loaded, which is way more trouble than it's worth.

**Comment by Arantor** [comment]
Alternatively, drop the configuration entirely and do it in CSS with max-width and max-height. Then it doesn't matter what they put in.

I'd suggest doing the same thing with the img bbc in general if it wasn't such a mess in terms of backwards compatibility to have that since you'd largely have to reprocess every tag in terms of if it had width or height...

**Comment by NanoSector** [comment]
Can't we just enforce it for everything, even those that were previously posted? If the [img] bbc has a class applied we can attach to that, same with signature images.

**Comment by Oldiesmann** [comment]
CSS should be fine with signature images at least.

**Comment by Arantor** [comment]
Yup :)

Tie it to the signature area (and the signature preview area) and you get to solve that part and fix the compatibility. The biggest headache you then have is signatures with sizes inside them...

**Comment by XinYenFon** [comment]
I think solves the problem in signature but I'm not entirely sure... :/

`.signature img {
    max-height: 90%;
    max-width: 90%;
}`

**Comment by Oldiesmann** [comment]
That just means images won't be displayed any taller and/or wider than 90% of height and/or width of the parent container. That doesn't do much of anything to prevent people from getting around the image height/width restrictions.

**Comment by XinYenFon** [comment]
``` php
    if (!empty($modSettings['max_image_width']) || !empty($modSettings['max_image_height']))
    echo '<style>.signature img {
        ', $modSettings['max_image_width'] ? 'max-height: '. $modSettings['max_image_width'].';' : '',';
        ', $modSettings['max_image_height'] ? 'max-width: '. $modSettings['max_image_height'].';' : '',';
    }
    </style>';
```

maybe? :P ... sh.. I revised that code for 5 times note to myself don't do stuff after wake up! :/

**Comment by Oldiesmann** [comment]
If that's output in $context['html_headers'] it should work just fine (since you can't have a <style> tag outside of the <head> section).
