### ISSUE TITLE
File cache problem with php file opcache in 2.0*

### ISSUE THREAD

**Issue by psrustik** [SimpleMachines/SMF#2207]
In admin area after any settings update i see old values in form input fields. But after refreshing page  1-2 seconds i see actual settings values. It scares users.

To repeat it need PHP + file opcache extension and SMF 2.0.\* file caching.

When SMF used file caching and PHP has file opcache extensions (Zend Opcache, APC, XCache and other) function **cache_get_data** return old (invalid) data from sources/Load.php:

``` php
@include($cachedir . '/data_' . $key . '.php');
```

This is due to the fact that opcache invalidate file cache by default every 2 seconds [Opcache](http://php.net/manual/en/opcache.configuration.php#ini.opcache.revalidate-freq), [APC](http://php.net/manual/en/apc.configuration.php#ini.apc.file-update-protection)

**Comment by Arantor** [comment]
The APC support is very mature (and we have not encountered this before with APC) but the whole thing with Zend OpCache is fairly new and it has not been battle tested in serious production environments yet.

What is more interesting is that the filemtime being updated should cause the Opcache to be invalidated as per Zend Opcache's documentation, and that makes me wonder if there is some subcaching going on, perhaps the statcache.

Does adding a call to `clearstatcache();` during the save process (cache_put_data) mitigate it in your testing? Reason I ask is that I've not been able to get an environment where I can repeatably test opcache related issues.

**Comment by Arantor** [comment]
Failing that, the following code in cache_put_data just after the file is saved should purge the relevant caches on saving:

```
if (function_exists('opcache_invalidate'))
    opcache_invalidate($cachedir . '/data_' . $key . '.php', true);
if (function_exists('apc_delete_file'))
    @apc_delete_file($cachedir . '/data_' . $key . '.php');
```

(I'm not a fan of @ suppression but I don't see any way to get around it for apc_delete_file since I don't see any easy way to see if a _file_ is cached, the docs aren't great on this one.)

**Comment by psrustik** [comment]
Thanks for reply.
This problem more actual for PHP 5.5 with enabled Zend Opcache.
Call function opcache_invalidate resolved this problem.

**Comment by Arantor** [comment]
Awesome. In which case I'd be recommending this be included in 2.1 as standard.

@Oldiesmann I'd also encourage this be included in any upcoming 2.0 patch too but I wouldn't hold up one if it's in the works as long as it makes it into 2.0 branch at some point.

**Comment by Oldiesmann** [comment]
Seems reasonable to include it since we already know it works. I'll go ahead and throw it into the patch and add a fix to 2.1 as well.

**Comment by Arantor** [comment]
Not including the APC caching too? Fair enough, though, because I couldn't prove it was making a difference (when I know we've encountered that issue during the installer with OpCache)

**Comment by Dragooon** [comment]
Pretty much, plus we haven't had any complaints of that so far unlike the
Zend opcache one.

**Comment by Arantor** [comment]
Sounds about right. Thanks for getting it included.
