### ISSUE TITLE
Package Manager: hide "Delete" for installed mods?

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#2211]
In the "Browse Packages" section of the Package Manager, would it be a good idea to hide the "Delete" button next to mods that the user has actually installed on the forum? This would force users to remove the mods in a safe way, that is by using the "Uninstall" button.

I might be wrong, but I think many users might make the mistake of using "Delete" when they actually want to uninstall! They then end up deleting the package along with the uninstall script, which can create confusion.

In this scenario, the "Delete" button would only be visible for mods that have been uploaded/downloaded onto the forum, but are currently _not installed_.

**Comment by ChainyEO** [comment]
I've just realised one situation where you might want to keep the "Delete" button visible for installed mods - for SMF updates. So that you can clean up the "Browse Packages" list (to prevent the SMF updates from cluttering up the list). 

Still, I wonder if there's another way of doing this, as the risk of "deleting" other mods from the list is still present. Is a clutter-free mod list worth this risk?

**Comment by Oldiesmann** [comment]
There's no reason to change it in my opinion. When you click delete for a package that's already installed, SMF warns you that deleting it might prevent you from being able to uninstall it later. In addition, to remedy the situation, all you have to do is upload the package to the Packages directory again (I'm not sure if uploading it through the package manager will work or not), though for older versions that might not be possible.

**Comment by ChainyEO** [comment]
@Oldiesmann 

yes, I think I must have clicked "Delete" for an uninstalled mod during my testing and so that's why I didn't see the warning message. This warning message is indeed a good solution.

I think we could have a bit more info about this "Delete" button in the SMF wiki (that's what got me started on this). I'll see if I can find a spot for your solution to "accidental" deletion of a mod.
