### ISSUE TITLE
Incorrect description in installer

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#2217]
As Mstcool points out in http://www.simplemachines.org/community/index.php?topic=526768.0

Install.english.php

```
$txt['user_settings_username_info'] = 'Choose the name you want to login with.<br>This can\'t be changed later, but your display name can be.';
```

Admins can always change their usernames.

**Comment by Mstcool** [comment]
Yay, I helped! Woot Woot! :D

**Comment by SSPMark** [comment]
@MissAllSunday - Looks like you pushed a fix for this issue to your fork, but didn't create a pull request.

**Comment by MissAllSunday** [comment]
Yes, thats because I still want to fix a few other things before doing a PR.

**Comment by SSPMark** [comment]
Ah, okay. I just figured since you fixed it, you'd want to create a PR solely for the fix and not mix it with other changes.:wink:

**Comment by MissAllSunday** [comment]
The other changes are all related to languages.

**Comment by live627** [comment]
A PR can have multiple fixes too.

**Comment by XinYenFon** [comment]
It would be better if devs assign themselves to issues, so that won't create a confusion and conflicts.

**Comment by MissAllSunday** [comment]
It shouldn't create any conflicts.

I mention the report on my commits, that creates a notificaiton for everyone who has posted on that report (unless they deliverately turned off notifications, in that case thats not really my fault) and every persons who has been added as collaborator, thats enough for people to realize someone else is working on it.

**Comment by Arantor** [comment]
The thing about assigning people is that people know who's working on what and it means people don't end up overlapping so much. It's nice to know what people are working on. For example I wouldn't have tried to make that commit if I'd noticed it was assigned to someone, I just didn't notice the commit before.

Communication was something I'm not especially good at, and it really made a mess of things.

**Comment by MissAllSunday** [comment]
The thing about making a reference in a commit is that its absolutely the same thing as assigning...  it creates a notification for all the people involved as well as any collaborator and it also avoids having to go to github and assign the report yourself, you only have to type # + the report number and that's it...  gets the job done in less time.

Assigning should be done for bigger issues, issues that will require more days of work or even a new branch with several commits on it, banal 1 line fixes shouldn't really need all of that  but oh boy, why do I know... I'm always wrong.

**Comment by live627** [comment]
That would be a nice feature.... if it existed.

On Thu, Aug 28, 2014 at 10:23 AM, Jessica González <notifications@github.com

**Comment by MissAllSunday** [comment]
![Imgur](http://i.imgur.com/ceyFea5.jpg)

**Comment by Arantor** [comment]
Actually making a reference is not the same thing as outright assigning it. You're completely right, one line fixes shouldn't, but on the other hand, I honestly didn't realise you'd already taken care of it, which is totally my fault.

All I was trying to say is that it might be easier to get one-liners dealt with out of the way rather than making them part of bigger commits, or assigning it to yourself so people know you've got it done - we've all made commits that don't necessarily fix an issue and it's not always clear what needs doing or not doing. I'm sorry to cause an issue here, just trying to figure out something that means everyone can work together better without tripping over anyone's toes.

I'd like to help a little, just I don't want to do anything you're already working on, but I have no idea what you're working on, I'd much rather let you do what you're doing and so - I'm sure - would everyone else. But it requires people talking to each other to let them know what's going on. And like I said, this is not something I've been good at in the past, and I'd like to get better at it.
