### ISSUE TITLE
SEF urls should go away

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2222]
we are not promoting users to use SEF urls any longer. why not hide the checkbox unless SEF is already enabled?

**Comment by XinYenFon** [comment]
I think somewhere we talked with @MissAllSunday about ripping old SEF feature off and integrating SSEF into it, can't really remember how it ended :P

**Comment by Arantor** [comment]
Could not recommend SSEF by default.

If you're going to do proper SEF URLs, do it properly, not by abusing the buffer. Major rewrite - not something I could remotely encourage for 2.1. In any case I would suggest SSEF's licence is incompatible with SMF's.

**Comment by XinYenFon** [comment]
ah thanks ^ suki said something similar to that as well.

**Comment by Oldiesmann** [comment]
Hiding the checkbox unless the feature is already enabled will only cause confusion. I don't see any problem with leaving it the way it is now and properly fixing it for 3.0.

**Comment by illori** [comment]
It would keep people from using a useless feature and allow those that use
it to disable it.

**Comment by Oldiesmann** [comment]
I still think the best solution is to leave it alone and deal with it for 3.0. If we hide it we'll likely confuse people (regardless if we just hide it for those that don't have it enabled or if we hide it for everyone [requiring a DB query to disable it as well]). If we rip it out entirely, then we hurt those who are still using it (which is probably a very small subset of SMF users, but still not something I want to deal with).

I really don't see too many people enabling this anymore anyway, with the popularity of packages like SimpleSEF and the like.

**Comment by XinYenFon** [comment]
I agree, also this will bring a little bit more question, "I don't see SEF option but my still using SEF links is it a bug?", best to leave this to SMF 3.0 and write some basic SEO items (title support/maybe sitemap etc... too soon to discuss).

**Comment by ChainyEO** [comment]
One way of solving this issue would be to make a few changes to the help file for this option. Make it clear there that "SEF URLs" are not really needed these days etc... And the option itself could be renamed to "Enable Queryless URLs", which would draw less attention to it (compared to "Search Engine Friendly", which sounds very attractive to someone that doesn't know the full story!)
