### ISSUE TITLE
A lot of bugs I found in the current package..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#2230]
1) In routine list_integration_hooks() the icons for status and remove not exists.
The images are pointed to a non exist folder in the theme ( /images/admin/).

2) during install/uninstall a package the hook for integrate_buffer is called (why? .. seem like from jquery, the top of the theme user dropdown), so the error log is filled with messages can't call a callable hook)

3) in the index template the line
    `<meta http-equiv="Content-Type" content="text/html; charset=', $context['character_set'], '">`
must be moved immediate after the `<head>` line, because the content type must in the first 512 bytes from top (html 5).

More bug's I reporting after found it ;-)

**Comment by live627** [comment]
Fixed code formatting :P

**Comment by PortaMx** [comment]
Do you mean ... what?
Sorry .. I don't understsnd :-(

**Comment by MissAllSunday** [comment]
Can you please elaborate on point 2?  whats the package you're trying to install?  what are the hooks this package is trying to use? how this package is calling those hooks? how and when do you require your files?

There are a few places where a full call to the server is been made, the profile dropdown, messages, likes, help pop ups, etc.  This request are plain normal request so the buffer hook is called as it will normally be called.

**Comment by PortaMx** [comment]
The package is our own work (PortaMx 2.0 Virgo .. you find it on Github) and we use many hooks.

We use the hook integrate_buffer in our own file to modify the buffer a) for change links to a SEF format and b) to add our copyright yust after the SMF copyright.

Because the package manager remove installed files and code changes before the code part is run, they do remove the installed hook.

In SMF 2.0.x this works without any problem or error, with 2.1 is gives error becuse the hook is also called after the file is delete. This is the problem and it works also not, if i remove the hook direct in the package file (i don't known it's a bug or fearure .. or i use a bad syntax, because this is not do documentet yet)

**Comment by MissAllSunday** [comment]
If it happens on uninstall, try to call remove_integration_function() before deleting any file, that should get rid of the problem.

Its the same behaviour on 2.0 the only difference is that now 2.1 shows an error about it while 2.0 did not.

On install you can now specify a file to be loaded when your hook is been called, there are 2 ways to do this, but they all come down to a string with some widlcards, check out Subs::function load_file()  and add_integration_function() it had some doc blocks to help understand its usage.

yeah, at some point I would have to write some docs about this, its on my to do list :)
