### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#2233]
I reported this on SMF in the private development section but was told to try here. So, here it goes. I have a board on my forum with about 62 pages. When you press the 3 small dots to expand the page numbers something weird happens. See screenshot please.
![archives](https://cloud.githubusercontent.com/assets/3620111/4110763/4cce270e-31f7-11e4-93ed-1764ba25cad2.png)

**Comment by live627** [comment]
53c1577fc52ecdad20d954736d5b859a09f99696
