### ISSUE TITLE
Personal Messages misses icons

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#2259]
http://i.imgur.com/GEkK9YA.png
http://i.imgur.com/7eYWrKM.png
http://i.imgur.com/Ppk6jo8.png
No CSS is defined for those icons, and there's no pm-menu-icon class.

**Comment by illori** [comment]
they never used to have icons, maybe they should not?

**Comment by NanoSector** [comment]
Almost every other menu does have them.

**Comment by illori** [comment]
the main menu that is used by most does not have it. the admin panel menu does as well as the drop downs in the top bar, as a result the profile menu does. that leaves out the pm page menu and the main menu.
