### ISSUE TITLE
Meta charset

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#2260]
2.1 is using a HTML5 doctype. Instead of http-equiv="Content-Type" with the charset parameter, it really should be using `<meta charset="UTF-8">` or similar as the first item.

It's also being sent with the headers as far as I can tell meaning that you may not even actually _need_ it.

**Comment by MissAllSunday** [comment]
Aren't they equivalent? the only difference is <meta charset="UTF-8"> been a HTML5 only but thats about it. I wound't say so much as "should" but anyway, I'll add it.

It might also been sent by the headers but we also need to declare a meta for it, for those isolated cases when a page is saved as a HTML page for example and yes, I do know several people who actually save entire topic pages.

**Comment by Arantor** [comment]
Just to answer your question: they are mostly equivalent, but since the more compact form has a tangible bandwidth saving (since it's every single page), might as well. Thanks for taking care of this.
