### ISSUE TITLE
Unknown table 'smf_openid_assoc'

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2262]
Today did my regular upgrades on my forum, and i got this error :/

**Comment by NanoSector** [comment]
That's because it tries to remove that table in case you're upgrading from 2.0 or 2.1 Alpha.

**Comment by NanoSector** [comment]
For the record there's a lot of stuff like this, take a look at http://nanosector.ddns.net/smf21/latestupgrade.txt

**Comment by Oldiesmann** [comment]
The rename issues should be fixable by adding an @ in front of the function call. I'll fix the database issue in a bit.

**Comment by illori** [comment]
now we have new error in upgrade.php

```
Parse error: syntax error, unexpected '@' in F:\wamp\www\github2.1\upgrade.php(2585) : eval()'d code on line 31

Call Stack:
    0.0050    1231208   1. {main}() F:\wamp\www\github2.1\upgrade.php:0
    0.4690    3165984   2. DatabaseChanges() F:\wamp\www\github2.1\upgrade.php:667
    0.4690    3170608   3. parse_sql() F:\wamp\www\github2.1\upgrade.php:1620

Error in upgrade script upgrade_2-1_mysql.sql on line 321!
```

**Comment by NanoSector** [comment]
Can't confirm, or has been fixed in the meantime.

**Comment by illori** [comment]
has been fixed.
