### ISSUE TITLE
Source Code CSS Improvement

### ISSUE THREAD

**Issue by mashbychoppix** [SimpleMachines/SMF#2267]
In this file here, Themes/default/css/jquery.sceditor.css, we have this declaration:
.sceditor-container iframe, .sceditor-container textarea {
    line-height: 1;
    border: 0;
    outline: 0;
    font-family: Verdana, Arial, Helvetica, sans-serif;
    font-size: 13px;
    color: #111;
    padding: 0;
    margin: 5px;
    resize: none;
    background: #fff;
    display: block;
}

I think that line-height should be 1.25. I've attached Before and After images of View source. With a line height of 1 and using View source, the text lines sit on each other.
![after](https://cloud.githubusercontent.com/assets/8038853/4195835/3907db8a-37c8-11e4-911f-a43631d65a96.png)
![before](https://cloud.githubusercontent.com/assets/8038853/4195836/390865fa-37c8-11e4-9262-01ecbb15dbf8.png)

**Comment by live627** [comment]
What if you remove the property? I think the resulting spacing is ideal then...

**Comment by XinYenFon** [comment]
I think 1.25 is good.

If you remove, it becomes equal to 1.5 (bit much).
