### ISSUE TITLE
Generic lists call for items even when there aren't any

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#2269]
Applies to both 2.0 and 2.1

Some lists don't bother to specify a number of get-count function, because they don't need to paginate, so the items must always be fetched. That's fine.

But if $list_context['total_num_items'] is defined, we already know how many items there are, and if this is 0, there's no point in calling $listOptions['get_items']['function'], might as well avoid the query in that case, since we already know there won't be any rows from it.

It's not a huge deal but every little helps when it comes to performance, right?

**Comment by NanoSector** [comment]
Nice find! :)
