### ISSUE TITLE
PM conversation between multiple people needs better UI

### ISSUE THREAD

**Issue by Dragooon** [SimpleMachines/SMF#2271]
Currently the Reply to All button is in a pretty hidden place and quoting while replying to all is almost non existent, this needs some improvements.

**Comment by XinYenFon** [comment]
Seems good enough for me, what is in your mind as "improvement" ?
![screenshot-localhost 2014-09-10 11-40-52](https://cloud.githubusercontent.com/assets/1669995/4214675/39fbe0aa-38c6-11e4-9de7-530082c8955e.png)

**Comment by illori** [comment]
```
ul.quickbuttons li a.reply_all_button {
    background: url("../images/quickbuttons.png") no-repeat scroll 0 -180px rgba(0, 0, 0, 0);
}
```

seems that in all at once view the reply all button has its image overlapping the text, so it does not show like it does in your screenshot.
