### ISSUE TITLE
report to admin from pm

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2273]
why is the option to report a pm to admin in the mini profile? it looks out of place and hard to find.

**Comment by XinYenFon** [comment]
I always tempted to use HD (big) icons on PM area, with no text...

**Comment by illori** [comment]
i think the pm view should as closely match the topic display as possible. it is mostly there just a few tweaks needed.

**Comment by Oldiesmann** [comment]
I agree. The two areas need to match as closely as possible, for consistency and to make things less confusing.
