### ISSUE TITLE
Version emulation doesn't include 2.1

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#2279]
Which means that "Revert" does nothing.

Also, 2.0.8 doesn't show up on that list.

**Comment by smfbigguy** [comment]
If 2.0.9 is out before 2.1 then it should be added I think. And, thanks for posting this.

**Comment by illori** [comment]
the drop down is filled from http://www.simplemachines.org/smf/latest-versions.txt which does not include 2.1. it needs to be updated.

**Comment by XinYenFon** [comment]
That list will be updated with SMF 2.1 Beta 1, we talked about this before with @Oldiesmann , he said we are not going to add Alpha 1 to that list.

**Comment by illori** [comment]
not a major issue considering that 2.1 supports auto emulation, so you really dont need to use that drop down at all.

**Comment by NanoSector** [comment]
Should the Beta 1 milestone be added to this?

**Comment by illori** [comment]
IMO yes it should be fixed for beta 1, we just need oldies to fix it on sm.org.

**Comment by XinYenFon** [comment]
This will be fixed when we add Beta 1 to latest-version.txt file 😊

From: Illori
Sent: ‎Sunday‎, ‎September‎ ‎21‎, ‎2014 ‎4‎:‎45‎ ‎PM
To: SimpleMachines/SMF2.1
Cc: Mert Alınbay

IMO yes it should be fixed for beta 1, we just need oldies to fix it on sm.org.

**Comment by Oldiesmann** [comment]
This should be fixed now. You may need to run the "Fetch Simple Machines Files" task to get the latest files if the task hasn't been run since 2.0.9 was released yesterday.
