### ISSUE TITLE
Cache directory not writable warning even with cache disabled

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#2280]
My test forum shows a cache not writable warning, even though caching is fully disabled on my forum (to avoid problems).

I know this is an issue with my permissions, but should it be showing an error when the cache is disabled?

**Comment by XinYenFon** [comment]
It would be better, to show user the error even they are not using it.

**Comment by NanoSector** [comment]
No, that's illogical. Why show a warning for something you aren't even using? (at least allow the user to dismiss it or something?)

**Comment by XinYenFon** [comment]
Well, I see your point. But I think if something broken/not working no matter its enabled or disabled errors should be shown to users. This will prevent us getting "Dafuq i didn't have any error, after enabling it I started to get XXXX error..." :P

**Comment by NanoSector** [comment]
Yeah, but we can also do the same as we do with settings which have to be written to Settings.php - disallow changing the Cache settings because the cache directory is not writable.

**Comment by NanoSector** [comment]
Opinions?

**Comment by colinschoen** [comment]
It agree with  @Yoshi2889 , it makes sense to hide the error if it is not relevant (they are not using caching)

**Comment by Oldiesmann** [comment]
That's the way it should be already...

`if (!empty($modSettings['cache_enable']) && !is_writable($cachedir))`

**Comment by NanoSector** [comment]
Seems not an issue anymore.
