### ISSUE TITLE
Female gender icon needs to move 1px

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#2281]
-16 to -17, or else it has a tiny piece of the previous image on it. -18 gets it a piece on the other side, -17 seems to work.

I'll look into it once I get time and my dev environment up again. :)

**Comment by NanoSector** [comment]
Thank you Antes :)

**Comment by NanoSector** [comment]
Sorry to put this in here, but the Like icon needs to be moved a row of 1px now :)

**Comment by XinYenFon** [comment]
Np I'll handle it

-----Original Message-----
