### ISSUE TITLE
Menu touch issues

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#2283]
In IE and Firefox on my laptop, tapping the screen to open a menu opens the link before it opens the menu. Chrome and Opera are fine.

On my phone Chrome and Firefox work fine. Haven't tested anything else.

**Comment by XinYenFon** [comment]
Hmm better you report this under https://github.com/joeldbirch/superfish/

**Comment by live627** [comment]
Can't you install Chromium, or w/e it's called?

**Comment by NanoSector** [comment]
Are you telling me to avoid the problem by switching my browser? ???

**Comment by live627** [comment]
Actually, I was responding to Xarcell. Should have made it clearer... sorry.

**Comment by Xarcell** [comment]
Errr.... I'm guessing someone deleted my comment? That's nice.

**Comment by NanoSector** [comment]
@live627 Not a problem, I understand now :) Missed Xarcells comment after it was removed, so my fault, my apologies. :)

Though now that this is reported to the SuperFish repo, should we close this here or leave it open until they found a solution?

**Comment by XinYenFon** [comment]
@Yoshi2889 you can close this, since we gonna wait fix from SuperFish team. Either way (if we do a fix) we'll contribute back to SuperFish's main repo. :)

**Comment by NanoSector** [comment]
Aight, closing this :)
