### ISSUE TITLE
Another space in quote on left side

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#2284]
I don't know if it's a bug but it looks strange, quoted text on left has empty field

![smf21a](https://cloud.githubusercontent.com/assets/8003629/4235710/c0706092-39c1-11e4-9d19-80f768b1a46e.png)

![smf21b](https://cloud.githubusercontent.com/assets/8003629/4235713/c4c3a488-39c1-11e4-8788-cd22b2919e19.png)

Why at the beginning of the text at the top is the created a paragraph?

**Comment by XinYenFon** [comment]
Its not a space, we'll insert quote image in there. Just converting images more to CSS/Sprite.

**Comment by jsqx** [comment]
I understand, but will you insert something like in smf 2.0?

![quote](https://cloud.githubusercontent.com/assets/8003629/4236180/3e2a0d1e-39c5-11e4-818d-d75f2cfc6f56.png)

**Comment by XinYenFon** [comment]
yeap

**Comment by Xarcell** [comment]
Instead of adding more images, have you considered using something like this: http://jsfiddle.net/qjw8y7gu/

**Comment by live627** [comment]
Been experimenting with that. this is what I have. 

![fireshot screen capture 156 - automated test 727 - page 2 - localhost_smf2_1_index_php_topic 730_new new](https://cloud.githubusercontent.com/assets/431799/4245413/9e0c35fa-3a37-11e4-8df9-8b64d9805e7c.png)

**Comment by XinYenFon** [comment]
nice :)
