### ISSUE TITLE
Size of font in user profile

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#2285]
I would like to also ask about font in user profile:

![adminprofile](https://cloud.githubusercontent.com/assets/8003629/4236766/8e7f0874-39c9-11e4-8760-d22d40d38ad7.png)

"Custom Title" - size of font is smaller than "Personal Text" - why in this way?

**Comment by margarett** [comment]
There's a font-size: 0.9em in Custom Title, where it doesn't exist in the other "li" classes...
Not sure if that's on purpose or not.

**Comment by live627** [comment]
I'm thinking that it should go.

**Comment by Xarcell** [comment]
I see the inconsistency here. If it were me, I would replace:

```
.poster>ul>li.icons, .poster li.membergroup, .poster li.title, .poster li.poster_online, .poster li.warning,  .poster>ul>li.icons:hover, .poster li.membergroup:hover, .poster li.title:hover, .poster li.poster_online:hover, .poster li.warning:hover {
/* font-size: 0.9em; */
line-height: 1.4em;
padding: 0;
margin: 3px 0 0 0;
}
```

With:

```
.user_info > li  {
font-size: 1em;
line-height: 1.4em;
padding: 0;
margin: 3px 0 0 0;
}
```

Much cleaner. Then again, I don't know what side effects it could cause elsewhere.

**Comment by live627** [comment]
Much cleaner, indeed. Needs testing...

**Comment by live627** [comment]
Please confirm if my recent commit 45c8d95d651e074f5237d00320eb037c7373a147 fixes this.

**Comment by Xarcell** [comment]
Confirmed.
