### ISSUE TITLE
Certain bugs...

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#2289]
I don't want to be a pesky but if I'm testing I'm reporting it what I think that it should be reported.

Firstly during the installation, appears an error:

Parse error: syntax error, unexpected '$task_string' (T_VARIABLE) in /home/XX/domains/XX/public_html/smf/Sources/ScheduledTasks.php on line 93

Secondly, when is clicking in quoting at the top Loading is being hung...
BBCode buttons aren't shown in the editor of writing the post.

Thirdly, this sign of the quotation is too big:
This sign of quote looks like glasses.

Look:

![smf21a](https://cloud.githubusercontent.com/assets/8003629/4248785/9e67d714-3a6b-11e4-91d2-cfa0254a3194.png)

![smf21b](https://cloud.githubusercontent.com/assets/8003629/4248786/a0f4fd54-3a6b-11e4-846b-4d07fac18b75.png)

The text should be moved a little bit on left, cause has a small empty field.

I'm sorry for such a tittle of topic, but I don't know how to call this topic.

**Comment by Xarcell** [comment]
What browser are you using? IE?

**Comment by live627** [comment]
It looks like that on IE 11. Ugly bloated character.

Note to self: Must test in other browsers, dammit!

**Comment by jsqx** [comment]
Yes I'm using IE11 browser, but it looks the same on Opera 24. In quick reply isn't shown full editor although I enable it, in normal reply editor is empty, lack all of functions.

![smf21beta1](https://cloud.githubusercontent.com/assets/8003629/4259875/7ec1d9d4-3b18-11e4-9a4f-d4e17fea4ba6.png)

**Comment by Oldiesmann** [comment]
Parse error is fixed with #2307. Looking into the JS issues with IE.

**Comment by Oldiesmann** [comment]
@jsgrom Can you update your build and see if you're still experiencing problems with quote and the editor in IE? On my computer, the problems went away after I merged in #2296.

**Comment by jsqx** [comment]
Quote icon is still big.
IE 11

![smf21ie11](https://cloud.githubusercontent.com/assets/8003629/4261275/358e1fee-3b67-11e4-84a1-4a46e4e8a930.png)

Opera 24

![smf21opera24](https://cloud.githubusercontent.com/assets/8003629/4261276/39e6395a-3b67-11e4-81b8-9f0b58449e05.png)

Editor work correctly already, BBCode buttons are shown.

**Comment by Oldiesmann** [comment]
Yeah, just wanted to make sure the editor and quote stuff was working. @live627 should be handling the quote icon issue.

**Comment by jsqx** [comment]
Ok I hope that he'll reduce this quote icon, cause currently looks like it were glasses. :)

**Comment by live627** [comment]
I can reduce the size, but it might still remind you of glasses...

**Comment by jsqx** [comment]
You should make this icon smaller. Like it is in SMF 2.0

![quotesmf20](https://cloud.githubusercontent.com/assets/8003629/4263805/09cee730-3c02-11e4-815d-084fc5b90401.png)

And look at text "test" that should be set in SMF 2.1 that there is no space between quote icon and text, in this way it looks correctly.

**Comment by Xarcell** [comment]
What I've always found funny is in the past the quote img is upside down. I'm not complaining, I just think it's funny.

**Comment by Xarcell** [comment]
@live627 what font did you use?

**Comment by live627** [comment]
The default (I don't remember it offhand)
