### ISSUE TITLE
tracking logins

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2290]
seems that logging logins is not working in 2.1 [viewable from their profile->profile info -> track user -> logins

**Comment by Oldiesmann** [comment]
It's disabled by default. Go to Admin -> Maintenance -> Server Settings -> Security and set "Days to keep login history" to something other than 0.

**Comment by illori** [comment]
the help text says "The number of days to keep login history under user profile tracking. The default is 30 days." so if i had just logged in a user and the default 0=30 days it should show the log in?

i changed it to 30 days and now the login shows [for today]. if 0 means it is disabled then the logins section of tracking should not show.

**Comment by Oldiesmann** [comment]
Oy. Gotta love consistency. Will be fixed shortly.
