### ISSUE TITLE
package manager errors

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2291]
if there are no packages showing in the package manager [but there are in the packages folder??] the following errors are showing in the error log.

Type of error: General
2: implode(): Invalid arguments passed
github2.1/index.php?action=admin;area=packages
File: F:/wamp/www/github2.1/Themes/default/Packages.template.php
Line: 534

Type of error: Undefined
8: Undefined index: installed_mods
github2.1/index.php?action=admin;area=packages
File: F:/wamp/www/github2.1/Themes/default/Packages.template.php
Line: 534

i dont understand why the package manager is not showing any packages at all, since i do have several in the packages folder.

**Comment by MissAllSunday** [comment]
Is this related to the createList fiasco?

What other issues you created about it?

**Comment by illori** [comment]
i am not sure if the errors would happen now that it is fixed as i have some packages that show now.

**Comment by NanoSector** [comment]
Can't reproduce; fixed?

**Comment by illori** [comment]
if you cant reproduce with no mods then i would say related to changes MAS made and i will close this.
