### ISSUE TITLE
Token verification error on Load Balancing page

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#2298]
Try saving the page, you'll get a token verification error.

**Comment by MissAllSunday** [comment]
meh... I thought that the commit I added to prepareDBSettingContext was the one to blame here but its not....  anyway, it was better to remove the createToken from there and leave the creation to the actual page thats calling saveDBSettings()

Funny enough, theres a bunch of admin functions, pretty much all of them that doesn't even create the needed token even though saveDBSettings is been called...

**Comment by MissAllSunday** [comment]
I just leave things as they are... this is a complete mess...

the createToken I introduces on prepareDBSettingContext actually fixes a few token verifications on some admin settings...

prepareServerSettingsContex() also creates the same tokens...   there isn't any consistency on this, some functions declare their tokens themselfs while others relies on the tokens created by the prepare functions...
