### ISSUE TITLE
Moderation reports misses icons

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#2299]
Screenshots say more than words do: http://i.imgur.com/XHPWfBu.png

**Comment by XinYenFon** [comment]
Weird because disregard already has icon probably different class I'll look once this trip over

-----Original Message-----

**Comment by XinYenFon** [comment]
it would be better if you post whole page...

**Comment by illori** [comment]
`<span class="generic_icons ignore.png" alt="Disregard"></span>
<strong>Disregard</strong>`
`<span class="generic_icons close.png" alt="Close"></span>
<strong>Close</strong>`

these 2 have the wrong icon showing. also why has ignore been changed to disregard? i think ignore is a better word in this location.

**Comment by NanoSector** [comment]
http://imgur.com/ktfjPOP

That's the only part of the page it happens on.
