### ISSUE TITLE
Undefined indexes on cron

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#2302]
I think I reported this before... Not sure, can't find it.

The database value you're trying to insert does not exist: id_member
File: /mnt/data/Web/smf21/Sources/Mentions.php
Line: 93

Undefined index: id
File: /mnt/data/Web/smf21/Sources/tasks/CreatePost-Notify.php
Line: 44

Both are called from the cron.php url.

**Comment by XinYenFon** [comment]
I'm sure I reported it check my issues

-----Original Message-----

**Comment by Oldiesmann** [comment]
Duplicate of #1980.
