### ISSUE TITLE
Content Slider Errors

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#2304]
TypeError: jQuery(...).slippry is not a function
http://localhost/SMF2.1/Themes/default/scripts/smf_jquery_plugins.js?alph21
Line 707
- [x] I get the above JS error on every single page load
- [ ] Does not respect the interval set in the admin panel -  to test, set it to 15000 (15 seconds)

**Comment by XinYenFon** [comment]
My pr should fix first one
That's something I forgot
Nope its better w/o toggle, we can add something if user base requires or asks :)

-----Original Message-----

**Comment by Oldiesmann** [comment]
First one was fixed in #2296.
Not sure about the second one.
If we're going to be replacing the news fader, we should still have a toggle as the news fader has always been optional.
