### ISSUE TITLE
Parse error: syntax error, unexpected '$task_string' (T_VARIABLE)

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#2305]
Hello,

/install.php?step=5     error ;

Parse error: syntax error, unexpected '$task_string' (T_VARIABLE) in C:\wamp\www\smf\Sources\ScheduledTasks.php on line 93
![untitled 1](https://cloud.githubusercontent.com/assets/5096676/4260705/189de3aa-3b4a-11e4-89ac-f4fda45eda30.png)

**Comment by MissAllSunday** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/2297
