### ISSUE TITLE
05-11-2012 installation

### ISSUE THREAD

**Issue by Akyhne** [SimpleMachines/SMF#231]
IE9:
When you are on step 2 in the installation, there's no 'Continue' button.. well it's hidden in a div that is hidden.
Unhide it, and you can continue installation.

**Comment by emanuele45** [comment]
@Labradoodle-360 should have fixed it at some point, if my memory serves me right.

**Comment by matthew-kerle** [comment]
Yep! I resolved this a while back :) Closing.
