### ISSUE TITLE
Text cursor is badly shown

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#2311]
I just noticed the bug, I'm using the IE11 browser and entering into creating the new topic, the text cursor isn't flashing in the text editor, only next to BBCode buttons.

![smf21](https://cloud.githubusercontent.com/assets/8003629/4261481/159885a8-3b71-11e4-8234-2b4c1ea74c58.png)

**Comment by XinYenFon** [comment]
I noticed this after IE 11.0.12 which version you are using? Maybe worth reporting SCEditor too.

**Comment by live627** [comment]
Same here

**Comment by jsqx** [comment]
My version it: IE 11.0.9600.17239

**Comment by NanoSector** [comment]
Confirmed, though it goes away after I click the main text field.
