### ISSUE TITLE
reported posts, ban this user [moderation center list]

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2316]
i can see why you can ban a user on a user report but why does the admin have the button to ban this user on the reported posts page? we did not have this in 2.0 and i dont see the advantage of it in 2.1.

**Comment by Oldiesmann** [comment]
What's wrong with having it there? You might want to ban someone for spamming or something...

**Comment by illori** [comment]
it is only there because the user report uses the same templates. i really dont see the point in having it there. most of the time you dont need to ban a user because a post was reported, also we are telling users not to use the ban system in smf on the forum and this is telling them the opposite.

**Comment by Oldiesmann** [comment]
If we're going to use the same template for both, we really should show the same options for both. That was part of the reason for creating a generic "reported content" setup rather than having user reports and post reports separate - to ensure both features work the same way and decrease confusion.

**Comment by NanoSector** [comment]
I agree with having the button there, it can prove to be useful.

**Comment by illori** [comment]
given that we tell users not to use the ban system in smf this is really the opposite of that. if we want people to use the ban system then we should make it less resource intensive so it can easily be used.

**Comment by Oldiesmann** [comment]
If someone can figure out a way to do that, we can change it, but the queries used in the ban system are far from simple. Hiding a ban button in one area isn't going to help the situation in my opinion.

**Comment by live627** [comment]
Drop IP bans?

**Comment by illori** [comment]
The issue is with the tracking of hits not banning by IP

**Comment by illori** [comment]
http://dev.simplemachines.org/mantis/view.php?id=4027

**Comment by MissAllSunday** [comment]
So, can this be closed then?  the slow ban query is a totally different issue that should be treated separately.

**Comment by illori** [comment]
i dont think it should be closed. and this does relate to the slow bans issue as we are promoting admin to use the ban system.

**Comment by MissAllSunday** [comment]
This issue reference solely the button been displayed to admins on x page and why you think it shouldn't be. It has been decided to keep it like it is, thus needs to be closed.

Slow queries on banning system has nothing to do with UI and needs a separate bug report altogether.

I agree with Oldiesmann, hiding a button won't make any difference, people already use the ban system, one more or less button won't make any difference.

**Comment by illori** [comment]
lets see what feedback we get from the users.

**Comment by XinYenFon** [comment]
I agree with @MissAllSunday focus must be on query, I can ban the user going to user's profile. So its just clicking two more buttons or less.

**Comment by FearThe1337** [comment]
About the queries, just some idea I had about the current ban system:
https://github.com/FearThe1337/Files/blob/master/bans_idea.txt

**Comment by XinYenFon** [comment]
Can we close this ?

**Comment by jdarwood007** [comment]
I'm going to close this.  If we get feedback that this is a bad UI design then we can open it up again.

Bans are far from efficient but not highly inefficient.  The bans we have at simplemachines.org should be a example to the fact that proper usage can make bans run fairly well.

Tips for banning:
1.  Avoid creating a entire ban group for a single ban.  My personal mod to add to existing ban group is a great usage of this and allows adding bans such as spammers to existing groups.  This is mostly a UI improvement mostly.
2. Highly Avoid banning based on hostname.  This is slow, not SMF issue but it has to do a reverse lookup on the IP, which takes time.
3. Avoid banning on IP if possible.  IP based bans are useless with IPv6 opening the size of bans wide open.  As well with Carrier Grade NAT (GCNAT) and some countries having few IPs means you could have tons of legit users behind that IP address.  This should only be used as a last resort.
4. If this is something like a spammer or another account that will be deleted, ban on the email address and prevent from registering.  This means the ban check is only applied when attempting a registration action or when attempting to change the email address.  If you use login or post, the ban check does have to apply when they visit the forum.
5. If its just a registered member,  just ban their account.  This is fast for SMF to process if they are banned or not.  If they are getting around the ban, deal with it then.
