### ISSUE TITLE
strong css

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2317]
why does strong define a color as well as the weight of the font?

```
strong {
    color: #444;
    font-weight: bold;
}
```

on the details of a moderation report if Enable shorthand date display is set to today [and maybe today and yesterday] the today part of the date in the moderation comment is in black/bold where the rest is white.

https://imagizer.imageshack.us/v2/249x113q90/907/bIidmw.png

**Comment by NanoSector** [comment]
I agree it doesn't look very pretty.
