### ISSUE TITLE
delete comment on moderation report

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2318]
if you try to delete a comment on a moderation report you get an error that you are not allowed to delete the comment [as admin and the comment was made by the same user]

![Alt text](https://imagizer.imageshack.us/v2/697x130q90/537/KsKUQy.png)

also the error that you can not delete the comment shows in the error log, i dont think this should show in the error log.

the following error also shows at the top of the page
Notice: Undefined index: comment in F:\wamp\www\github2.1\Sources\ReportedContent.php on line 476

there is also one more error in the log

```
Type of error: Undefined
```

8: Undefined variable: context
/github2.1/index.php?action=moderate;area=reportedposts;sa=handlecomment;rid=8
File: F:/wamp/www/github2.1/Sources/Subs-ReportedContent.php
Line: 590

**Comment by Oldiesmann** [comment]
The "undefined variable: context" issue has already been fixed. The other one will be fixed shortly.

**Comment by illori** [comment]
not fixed. Notice: Undefined variable: user_info in F:\wamp\www\github2.1\Sources\Subs-ReportedContent.php on line 509

if the user is not the author of the comments

**Comment by illori** [comment]
also with this change the user can not edit their own comment, the buttons dont show up. they only show up for the admin.

please test this with an account that is not an admin.

**Comment by illori** [comment]
so we have a missing global $user_info in subs-reportedcontent.php. we also have one other issue.

```
'can_edit' => allowedTo('admin_forum') || (($user_info['id'] == $row['id_member']) && allowedTo('moderate_forum')),
```

why have a comment edit feature when only those that can moderate forum members can edit the comments they have made?

**Comment by illori** [comment]
related to this, editing comments does not work either for non-admin users.
