### ISSUE TITLE
topic view, cat_bar missing?

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2319]
seems that the cat_bar has been removed in the topic view along with how many views/reads a topic has had. i think this takes away a lot on the look of the page. it is a lot more bland and you cant as easily find the subject line of the topic.

also related to this, since the car_bar is gone the previous topic/next topic links are now out of place and now found on the bottom of the page near the reply button

**Comment by NanoSector** [comment]
I agree with this, it was better as it was before.

**Comment by XinYenFon** [comment]
I don't agree with this. Topic view seems more clear and better in this shape.

**Comment by illori** [comment]
i really can not agree with this as being clearer especially with the misplaced previous/next topic links

**Comment by NanoSector** [comment]
If it was only the title in big it might work. But currently it looks like a pile of text scrambled together, I'm sorry.

**Comment by live627** [comment]
how does this look?[image: Inline image 1]

**Comment by live627** [comment]
![fireshot screen capture 159 - the update system now working without issues___ - nanosector_ddns_net_smf21_index_php_topic 7_0_html](https://cloud.githubusercontent.com/assets/431799/4265976/6b04bce8-3c69-11e4-9d10-7c0379733b2a.png)

**Comment by illori** [comment]
it is still missing the count of views and does not fix the issue with the next/previous topic links that are at the bottom of the page. it is a little better then what we have now though.

**Comment by Oldiesmann** [comment]
It still looks cramped with "started by" and "who's viewing" being so close to the subject, especially given the difference in font size between the subject and those other two lines.

**Comment by live627** [comment]
Playing some more
![fireshot screen capture 160 - the update system now working without issues___ - nanosector_ddns_net_smf21_index_php_topic 7_0_html](https://cloud.githubusercontent.com/assets/431799/4267659/21b57406-3ca0-11e4-9f7d-6be816e8f230.png)

**Comment by illori** [comment]
why do we even need the started by stuff? i am not sold that it is all that useful. we did not have it in 2.0 so why in 2.1?

**Comment by XinYenFon** [comment]
Agreed, why we are even releasing SMF 2.1, we did not have it in 2.0…

From: Illori
Sent: ‎Monday‎, ‎September‎ ‎15‎, ‎2014 ‎12‎:‎09‎ ‎PM
To: SimpleMachines/SMF2.1
Cc: Mert Alınbay

why do we even need the started by stuff? i am not sold that it is all that useful. we did not have it in 2.0 so why in 2.1?

**Comment by illori** [comment]
just if we did not have that, it would make solving this easier. or just put it back to how it was.

**Comment by illori** [comment]
looking at lives changes it looks better, i would add the top part of the curve [corners] and it may look a bit better.

**Comment by Oldiesmann** [comment]
Looks much better with the latest changes.

**Comment by NanoSector** [comment]
Is it possible to remove the gap and make it look like it is integrated with the linktree? That'd be a cool effect I think.
