### ISSUE TITLE
Forum Stats Plural

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#2324]
SMF2.1
The plural is not true in the statistics.

![statistik-english-plural](https://cloud.githubusercontent.com/assets/2753863/4267517/16b7e590-3c9e-11e4-8acf-fac980224cc5.PNG)

**Comment by illori** [comment]
same issue basically as #2020

**Comment by Oldiesmann** [comment]
I'll look into what can be done about this and #2020, but this is an issue that has plagued SMF for years, and it's not always something that can be fixed easily due to i18n.

**Comment by NanoSector** [comment]
And usually you want a forum with more than one topic, post and member anyway :)

**Comment by Arantor** [comment]
Yes but different languages handle this in different ways. The distinction is not always 'is 1' or 'is not 1'.

I'd link to a related discussion but 1) it's private and 2) it trails off very badly, very quickly and I'd rather not go there since it involves an epic ranty smackdown from me.

**Comment by wintstar** [comment]
Same solution could be used as issue https://github.com/SimpleMachines/SMF2.1/issues/3650  here. Text before total number.

**Comment by Oldiesmann** [comment]
Closing this one so we don't have multiple related issues open. Please keep all discussion related to this at #2020
