### ISSUE TITLE
05-11-2012 profile

### ISSUE THREAD

**Issue by Akyhne** [SimpleMachines/SMF#233]
action=profile
Throws this error:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OR ((62 BETWEEN bi.ip_low1 AND bi.ip_high1)
 AND (107 BETWEEN bi.ip_low2 AND b' at line 5
File: /home/www/mysite.com/Sources/Profile-View.php
Line: 150

```
    // So... are they banned?  Dying to know!
    $request = $smcFunc['db_query']('', '
        SELECT bg.id_ban_group, bg.name, bg.cannot_access, bg.cannot_post, bg.cannot_register,
            bg.cannot_login, bg.reason
        FROM {db_prefix}ban_items AS bi
            INNER JOIN {db_prefix}ban_groups AS bg ON (bg.id_ban_group = bi.id_ban_group AND (bg.expire_time IS NULL OR bg.expire_time > {int:time}))
        WHERE (' . implode(' OR ', $ban_query) . ')',
        $ban_query_vars
    );
```

It is apparently only an issue in the frontpage of the profile.

**Comment by Spuds** [comment]
It was a problem introduced in the last commit .... see
https://github.com/Spuds/Playpen/commit/bf712c2cf4cee1f448ba1a90f5e8c796ae3b2785#L0L1112
if you need a fix before it gets PRed and merged

**Comment by matthew-kerle** [comment]
I do believe that this was resolved in one of the more recent commits.
