### ISSUE TITLE
Cannot Register as a new User in the Lister Engine Forum

### ISSUE THREAD

**Issue by matthew001** [SimpleMachines/SMF#2342]
Hello, 

  I have been trying to register in the listerengine.com forum.  

Repro Steps:
1) enter all information into registration page
    Email: Matthew_001@hotmail.com
    UserName: Matthew_001
    Passwords, Catchpa, 
2) answer all 3 questions, by copy and pasting answers from the question to the right
3)   Click I Agree with the term
4)  Click the Register button
5) I am taken to a new page that displays "an error has occurred"  but there is not information in the box as to what the error is.

Workaround:  If I don't paste the answers to the questions in the boxes and actually type them in, then I can register just fine.

**Comment by matthew001** [comment]
"copy and pasting answers from the question to the right"
should read
copy and pasting answers from the question to the left

**Comment by live627** [comment]
this is not an issue related to SMF 2.1.

**Comment by matthew001** [comment]
How did you determine that?

**Comment by Dragooon** [comment]
That forum isn't running 2.1...

**Comment by wintstar** [comment]
2.1 still gets bugs and should not be used as a live board. I'm assuming that there is no support for them until now. Also, I would not e-mail addresses published here.
