### ISSUE TITLE
replying to a report on a member errors

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2343]
Type of error: Undefined
8: Undefined variable: reason
/github2.1/index.php?action=moderate;area=reportedmembers;sa=handlecomment;rid=3
File: F:/wamp/www/github2.1/Sources/Subs-ReportedContent.php
Line: 599

 Type of error: Undefined
8: Undefined variable: user_name
/github2.1/index.php?action=moderate;area=reportedmembers;sa=handlecomment;rid=3
File: F:/wamp/www/github2.1/Sources/Subs-ReportedContent.php
Line: 596

 Type of error: Undefined
8: Undefined variable: user
/github2.1/index.php?action=moderate;area=reportedmembers;sa=handlecomment;rid=3
File: F:/wamp/www/github2.1/Sources/Subs-ReportedContent.php
Line: 595

Type of error: Undefined
8: Undefined variable: id_report
/github2.1/index.php?action=moderate;area=reportedmembers;sa=handlecomment;rid=3
File: F:/wamp/www/github2.1/Sources/Subs-ReportedContent.php
Line: 594

also it seems that even if you are the only person that can be notified of the reply it gets sent to the alerts system anyway causing a number of errors

i think the others can be resolved when this is resolved

Type of error: Cron
8: Undefined index: comment_id
/github2.1/cron.php
File: F:/wamp/www/github2.1/Sources/tasks/MemberReportReply-Notify.php
Line: 33

i dont know why it is trying to alert someone as there is only one admin that replied to a comment they made.

**Comment by NanoSector** [comment]
Confirmed.

**Comment by Oldiesmann** [comment]
The errors will be fixed shortly. Also, the background task determines who should be notified. That's how the system works.

**Comment by illori** [comment]
yep that seems to fix it. no idea why it was populating the background task.
