### ISSUE TITLE
$txt['msg_alert_none'] = 'No messages...'; general usage

### ISSUE THREAD

**Issue by Akyhne** [SimpleMachines/SMF#235]
$txt['msg_alert_none'] is used in general to tell there's no new messages and no new posts.

It is used in the recent files, the messageindex & the personalmessage.

It doesn't mean the same in English (or at least isn't the most correct to use) and it doesn't work at all in Danish.

I haven't exactly checked what it is used for in the Recent template, but in messageindex it's used to tell there are no topics in an empty board. It should really say "No topics" or "No posts".

Then keep $txt['msg_alert_none'] for PMs.

PS: This is of course also a SMF 2.0.x issue.

**Comment by emanuele45** [comment]
So you are proposing to have a:
msg_alert_none
topic_alert_none
pm_alert_none
right?

@Antes something to add?

**Comment by XinYenFon** [comment]
Nothing to add. This can clear things up.

**Comment by joshuaadickerson** [comment]
If we are going to use the same for all of them in English, just assign the
variable as one of the other variables. Seems easier for English speakers
than having to do it multiple times.

**Comment by XinYenFon** [comment]
btw i forgot to mention in Turkish language we don't need extra strings but if we are going to add topic/pm alert that make things bit more clear just it.

**Comment by ghost** [comment]
Has it been decided to split this label into 3 separate labels?

**Comment by ghost** [comment]
it wouldnt be much of change in file size, and if it helps other languages then i see why not.

**Comment by Oldiesmann** [comment]
I agree. Seems like a good decision to me.

**Comment by Oldiesmann** [comment]
Closing this for now since the split has been merged in. If there's anything else to add, please do so :)
