### ISSUE TITLE
Cannot Change Cookie Name

### ISSUE THREAD

**Issue by ahrasis** [SimpleMachines/SMF#2350]
I cannot change cookie name. Page (?action=admin;area=serversettings;sa=cookie;save) when blank when save button is pressed.

Type of error: Undefined
Undefined variable: smcFunc
ManageServer.php - Line 987

However, can return or go to other page safely.

**Comment by ahrasis** [comment]
It seems that I also cannot change forum name. Similarly, page (?action=admin;area=serversettings;sa=general;save) when blank when save button is pressed.

Type of error: Undefined
Undefined variable: smcFunc
ManageServer.php - Line 987

However, can return or go to other page safely.

**Comment by wintstar** [comment]
I can confirm and the bug is also used to change the settings "Enable compressed"
Error messages:
Fatal error: Function name must be a string in xxx\Sources\ManageServer.php on line 987
