### ISSUE TITLE
Website to custom profile field

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#2356]
Would it be an issue to move it to an optional profile field? It should not be integrated in SMF too much.

**Comment by illori** [comment]
i think it might be an issue since it is 2 fields, the title and url. all other custom profile fields are 1 field only.

**Comment by Oldiesmann** [comment]
Yeah, that's the reason it was never moved. There's no way to link two custom profile fields like that to my knowledge.

**Comment by NanoSector** [comment]
Okay, closing this then :)
