### ISSUE TITLE
Show others my online status?

### ISSUE THREAD

**Issue by ahrasis** [SimpleMachines/SMF#2357]
When admin edit other's account settings, it still shows - Show others my online status which is a little bit confusing.  Simply change "Show online status to others", I think will be less confusing and can be used for both admin and profile owner.

**Comment by illori** [comment]
either way it is still the others profile and the admin should know that if they are editing it. IMO it is fine the way it is.

**Comment by XinYenFon** [comment]
Also this type of things needs to be opened under community. This is not an issue but a discussion topic.

**Comment by ahrasis** [comment]
Simply odd but it is ok with me. Not a big issue anyway.
