### ISSUE TITLE
10 Pages of Recent Post?

### ISSUE THREAD

**Issue by ahrasis** [SimpleMachines/SMF#2359]
A new install of SMF2.1 will show 10 pages of recent post though there are only two posts. (action=recent)

**Comment by Oldiesmann** [comment]
Happens on my test board as well with 40 posts. Will look into it in the coming days if nobody else gets to it before I do.

**Comment by Arantor** [comment]
Related to https://github.com/SimpleMachines/SMF2.1/issues/1378
