### ISSUE TITLE
Default avatar not showing in the topheader miniprofile

### ISSUE THREAD

**Issue by ahrasis** [SimpleMachines/SMF#2360]
Profile and display page do show default avatar automatically but topheader miniprofile doesn't show it automatically. It has to be chosen in profile page. Is this intended?

**Comment by XinYenFon** [comment]
Not really sure (can't remember) but isn't better not to show default avatar on that place, that'll remind user that they don't have avatar? (or I'm thinking soooo weird which is a very normal thing)...

**Comment by ahrasis** [comment]
Not weirdo or something but I just think that would defeat the purpose of default avatar. Might as well do not show it elsewhere too.

**Comment by jsqx** [comment]
People bring back display avatar in mini popup. In SMF 2.0 avatar is display at top profile, here should be the same, this miniature, which is now isn't fine.

![avatar](https://cloud.githubusercontent.com/assets/8003629/4377563/106733ea-4350-11e4-9a54-f472dae63b39.png)

**Comment by XinYenFon** [comment]
It was like that but changed. I don't think we revert again.

**Comment by Oldiesmann** [comment]
It should be left where it is for now. If after the first beta more people prefer it where it was, we can change it back later.

**Comment by jsqx** [comment]
Why you off-load something what looks good? Mini Popup is empty now without display avatar and bring it back soon.

**Comment by ahrasis** [comment]
This already fixed but awaiting PR to be completed. Please close this once it is completed or I will close it, whoever the earlier.

**Comment by Oldiesmann** [comment]
Fixed in #2428
