### ISSUE TITLE
Modifying css files shows error message on first save

### ISSUE THREAD

**Issue by ahrasis** [SimpleMachines/SMF#2362]
I was modifying index.css (and other css files) via ACP Modify Themes, while other template files can be modified just fine, but for css files, red error message was shown after the save button is pressed for the first time.

Message: Your session timed out while posting. Please try to re-submit your message.

But the second time the save button is pressed, it is saved and it go back to the list of the files.

No problem for modifying template files so far.

**Comment by NanoSector** [comment]
I still don't see why we keep these functions. They're not useful for average Joe, and anyone with knowledge on the subject knows better than to use that.

**Comment by XinYenFon** [comment]
+1 @Yoshi2889

**Comment by margarett** [comment]
I can reproduce this.
Furthermore, the buttons "Preview" and "Save Changes" are misaligned

**Comment by Oldiesmann** [comment]
The problem is that the token isn't included in that form. When you try to save it the first time, it loads a different page entirely, and the form on _that_ page _does_ have the token in it.
