### ISSUE TITLE
Quote icon

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#2366]
So I noticed, that the quote icon on IE11 browser is bigger and next to it is space (empty field).  However on the Opera 24 that icon is smaller and hasn't this space. So something is wrong, it should be adapted to Internet Explorer browser. It's my opinion. You should testing it on different browsers to know how it look like on some browser.

IE11

![ie11](https://cloud.githubusercontent.com/assets/8003629/4368438/f3c571b0-42ec-11e4-934a-bfcd3b118737.png)

Opera 24

![opera24](https://cloud.githubusercontent.com/assets/8003629/4368440/f924e53c-42ec-11e4-8630-e5e3145e6491.png)

At all that icon cannot be more reduced? Must be so big?

**Comment by XinYenFon** [comment]
Seems IE & Opera does not respecting em, I'll change it to 22px.
