### ISSUE TITLE
Add Packages via Server General gzinflate(): data error

### ISSUE THREAD

**Issue by ahrasis** [SimpleMachines/SMF#2367]
I get general gzinflate(): data error when accessing action=admin;area=packages;get;sa=browse;server=1;relative=feature_enhancement

Details
Type of error: General
2: gzinflate(): data error
Subs-Package.php
Line: 311

Cannot reproduce for others like administrative or theme_enhancements. But the above can be reproduced.

**Comment by Oldiesmann** [comment]
I can't reproduce this on my test board.

**Comment by illori** [comment]
are you going to the feature enhancement section? the others dont have the issue. i think it may be due to the number that are in this category. the error shows in the header and in the error log.

**Comment by Oldiesmann** [comment]
The error does show up in the error log, but it's not showing anywhere else for me.

**Comment by margarett** [comment]
I don't think this is related to the sheer quantity of MODs in that section. New features has much more and that error doesn't pop up.

For the record, in 2.0 that error is not shown. But, in 2.0, Subs-Packages has gzinflate with suppressor:
`// Only inflate it if we need to ;).
        if ($file_info['compressed_size'] != $file_info['size'])
            $file_info['data'] = @gzinflate($file_info['data']);`

I removed the "@" and it still returns no error (in 2.0)

Adding the @ in 2.1 also suppresses the error. Not sure if this is the best way to do it, though....
@Oldiesmann: the error pops in the log and in the page header if db_show_debug is active ;-)

**Comment by Oldiesmann** [comment]
Yeah, I do see the error for that section in the error log on my forum. I still don't know what's causing this, but at this point if throwing an @ in front of it suppresses the error, that will probably be the easiest option at the moment.

**Comment by illori** [comment]
@live627 this seems to be fixed.

**Comment by live627** [comment]
Excellent, thank you.
