### ISSUE TITLE
top border missing from package description

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2370]
if you browse one of the package servers and look at the description of one of the mods you will see that part way down the description starts and it is missing a top border.

```
.information {
    background: #F8F8F8;
    overflow: auto;
    padding-bottom: .5em;
    border: 1px solid #ddd;
    border-radius: 7px 7px 7px 7px;
    margin: 0 0 10px 0;
    padding: 12px 9px 8px 9px;
    box-sizing: border-box;
}
```

this will fix it, but i am not sure if this will effect anything else important so i am not putting in a PR for the change.

**Comment by XinYenFon** [comment]
Its better to use different class there.
