### ISSUE TITLE
Registration Agreement language select no work

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#2375]
Last pull request #2374 from Underdog-01/patch-5 
The language select no work in Registration Agreement. The file agreement.german_informal-utf8.txt is present in root/

![reg-language-select](https://cloud.githubusercontent.com/assets/2753863/4384142/3e04e3b8-43b1-11e4-9181-27a2a231b2a9.PNG)

**Comment by Underdog-01** [comment]
I tested that section and find no errors. 
You do realize that the agreement is manually typed in and saved to the database on the page you just referenced? Imo perhaps the drop down menu does not function because there is nothing to change on that specific page and it is just showing your default language for reference.
I could be wrong because I only test SMF in English but it appears that way to me,

Regards.

**Comment by XinYenFon** [comment]
I can reproduce the issue but its not about the changes done by @Underdog-01 something else.

**Comment by Oldiesmann** [comment]
What exactly isn't working with this? Is it not loading the proper agreement? I can't see anything in the code that appears broken.

**Comment by XinYenFon** [comment]
yeap

**Comment by wintstar** [comment]
In 2.0.8 is loaded with the drop down after selecting a different language, this other language. And the text then appears in that language. And this text is in the file agreement.txt or in German agreement.german_informal-utf8.txt. And this does not work in 2.1. Or the file agreement.txt or in German agreement.german_informal-utf8.txt is no longer needed in 2.1?

**Comment by Oldiesmann** [comment]
No, it should still be loading that file.

I'm honestly not sure why it's not working for you, as the code for that functionality in 2.1 is nearly identical to what's in 2.0 - there are just some minor changes, but nothing that would prevent it from loading the proper file.

**Comment by wintstar** [comment]
It does not work with Internet Explorer and not Firefox. Click on Change, the selection jumps back to Default.

**Comment by wintstar** [comment]
The bug is in the file Register.template.php. If this file is replace with the from SMF 2.0.8 is the bug fixed.

**Comment by wintstar** [comment]
Open Register.template.php
![bug](https://cloud.githubusercontent.com/assets/2753863/4429925/2275228e-460e-11e4-95fe-10e789949425.PNG)

**Comment by Oldiesmann** [comment]
Ah. Amazing how minor things like that can cause such weird problems.
