### ISSUE TITLE
"Undefined variable: condition" when searching for members

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#2399]
Searching for members triggers the following errors in my error log:
(errors appear after pressing "search")

```
Type of error: Undefined
8: Undefined variable: condition
http://localhost/smf21/index.php?action=mlist;sa=search
File: C:/xampp/htdocs/smf21/Sources/Memberlist.php
Line: 510

Type of error: Undefined
8: Undefined variable: condition
http://localhost/smf21/index.php?action=mlist;sa=search
File: C:/xampp/htdocs/smf21/Sources/Memberlist.php
Line: 493
```

**Comment by margarett** [comment]
Hummm $condition isn't really used anywhere in this file so why just don't remove it from the query completely?

**Comment by Oldiesmann** [comment]
It looks like the memberlist search changes that we made in 2.0.7 somehow got removed from 2.1. Still looking into it though.
