### ISSUE TITLE
Questions in relation functions SMF 2.1

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#2413]
Please understand my questions and attach this subject below up to the Question category.

I. Question in relation to gender

Now in SMF 2.1 in the profile the gender of user will be shown as icon on the left? Whether perhaps you will make this information as the text: "Gender" above the age? This way like is in SMF 2.0

Gender: N/A
Age: N/A

![gender](https://cloud.githubusercontent.com/assets/8003629/4547686/1adceb9e-4e4f-11e4-8562-24bc5ecbd3b6.png)

II. Question in relation to mini icons

Whether these icons is a really good solution? How do you think? These mini icons doesn’t fit here at all, of course it’s my personal opinion. These icons are ruining the look of this theme, it looks a little bit childishly.

![icons](https://cloud.githubusercontent.com/assets/8003629/4547889/b6510ab4-4e50-11e4-95ee-9b2532087682.png)

III. Question in relation to the system of emails

In SMF 2.0 it is possible to send the e-mail through the forum, SMF 2.0 has a system of sending emails through the own editor for writing the title and contents, as I can see SMF 2.1 doesn't have it, only is a function: mailto. Whether it will already stay or system of sending emails will return?

IV. Question in relation to BBCode

You are planning perhaps adding BBCode: hide - the hidden text or the spoiler? Whether these options aren't simply nothing worth.

**Comment by XinYenFon** [comment]
Please ask questions related to SMF 2.1 in http://www.simplemachines.org/community/index.php?board=252.0 - We'd like to keep this place for issues only.

Thank you for your understanding.
