### ISSUE TITLE
Accessing an unexisting area in admin triggers 2 errors in log

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#2414]
Today at 10:06 pm
Type of error: Undefined
8: Undefined index: label
http://localhost/smf21/index.php?action=admin;area=yabadaba
File: C:/xampp/htdocs/smf21/Themes/default/Admin.template.php
Line: 95

Today at 10:06 pm
Type of error: Undefined
8: Undefined index: icon_class
http://localhost/smf21/index.php?action=admin;area=yabadaba
File: C:/xampp/htdocs/smf21/Themes/default/Admin.template.php
Line: 95

**Comment by XinYenFon** [comment]
Weird why SMF trying to add that page as icon to Admin Center (main page).
