### ISSUE TITLE
PHP Version incorrectly detected on Ubuntu

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#2423]
While running the upgrade via CLI, I got this:
Error: PHP 5.3.10-1ubuntu3.14 does not match version requirements.

Changing the curversion to this resolves this, but there may be a better fix:
    $curver = explode('.', substr(PHP_VERSION, strpos(PHP_VERSION, '-')));

Why are we not using version_compare here instead?

**Comment by Oldiesmann** [comment]
I have no idea why version_compare isn't used there. To my knowledge the code to check the version in the upgrade hasn't changed at all in 2.1.
