### ISSUE TITLE
Error 8: Undefined index: class Display.template.php Line 159

### ISSUE THREAD

**Issue by ahrasis** [SimpleMachines/SMF#2430]
Type of error: Undefined
8: Undefined index: class
.../Themes/default/Display.template.php
Line: 159

<span id="top_subject" class="topic-icon topic-icon-', $context['class'], '">', $txt['topic'], ': ', $context['subject'], '&nbsp;<span>(', $context['num_views_text'], ')</span></span>

Anybody got the same error?

**Comment by margarett** [comment]
Not that I remember (just trashed another installation of 2.1 :tongue: )
What are you doing when that happens? In my just-downloaded Display.template.php, around line 159 there isn't really nothing related to that (more around calendar events)

**Comment by ahrasis** [comment]
Sorry, I just checked that this was taken from 21/9 package. The latest on 12/10 doesn't have this. Case is closed.
