### ISSUE TITLE
Still avatar isn't shown in miniprofile

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#2439]
Still avatar isn't shown in miniprofile:

![avatar](https://cloud.githubusercontent.com/assets/8003629/4377563/106733ea-4350-11e4-9a54-f472dae63b39.png)

Previous application was closed because of fixing it.

**Comment by XinYenFon** [comment]
I probably create a modification for that, I was going to add that back there but after give a little thought its best to keep core theme simple.

**Comment by jsqx** [comment]
But I don't understand, why you and other bother show avatar in miniprofile? In the same way avatar is shown in SMF 2.0 in tophead profile of forum. So why in SMF 2.0 it stayed and here can't in miniprofile? Understand, that you are not only creating this software for yourselves, but also for hundreds people and this what you like in this software, necessarily to will  appeal someone else I don't understand your thinking, how it is possible to get rid of basic functions from the software. SMF is heading in wrong direction, because even show a avatar bother to you. This mini avatar, which you gave is suck. Forgive man, if I offense you, but I had to write it.
