### ISSUE TITLE
rogue smiley

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2445]
installed http://custom.simplemachines.org/mods/index.php?mod=77 ran query

```
UPDATE smf_smileys SET hidden=2
WHERE smf_smileys.ID_SMILEY>20;
```

to set them to show in the more window

i am getting an extra smiley -0 that shows before the cry smiley in the normal set of smileys. if i remove the lots o smileys pack and their smileys the extra one goes away. when i add the smileys back and run the query the extra will return. 

if i examine the extra smiley it has the following code in firebug

```
<img src="" alt="-0" title="-0" unselectable="on">
```

**Comment by NanoSector** [comment]
Can't reproduce, can someone else maybe?

**Comment by XinYenFon** [comment]
Its one of the problems in new pop, its respecting new line but instead adding <br> (or alike) going for something like this. All those -0/-1/-2 means new line.

@Yoshi2889 set smiley order, put one or two smiley to new line.

**Comment by Oldiesmann** [comment]
At this point it would probably just be best to put smileys back the way they used to be. That would solve this problem and assorted other issues that come with the current layout.
