### ISSUE TITLE
smileys issues

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2453]
old smileys drop down should go away.
"These smileys will appear in the popup smiley box, when posting a new forum message or Personal Message. " text in admin panel needs to be corrected.
ideally the [more] button should look like a button, same with the close link
the popup should be more centered in the window rather then left aligned.
on mobile browser the scroll bar in the popup does not show, could we add the same that shows for alerts so users will know they can scroll?

also is it possible to allow the popup to be moved and resized?

**Comment by XinYenFon** [comment]
Removed
Actually that's the original text, I reverted that back to original in my smiley fix PR
More button & close button now has button class they are now looking like a real button too
Pop actually centered but there is a calc. issue in JS on mobile we can solve this with extra CSS rules in Responsive.css
I'm not good with scrollable JS maybe @live627 take a look at it.
Yes possible but I'm not really sure its worth, it requires some changes.

**Comment by illori** [comment]
might also be useful that the smileys that show by default show the hand when you mouse over them like the other bbc buttons do.

**Comment by illori** [comment]
also the close button in the popup seems a bit large compared to the other buttons.

**Comment by XinYenFon** [comment]
oh yea pointer, I knew I forgot something :/ I'll add it back totally my bad... Close button is good (in size) to me but we can edit its size not a big deal but I'm favor of keeping it that way.

**Comment by illori** [comment]
the close button size really does not look similar in size to other buttons...
![](http://imagizer.imageshack.us/v2/139x57q90/746/BZSrgh.png)

**Comment by XinYenFon** [comment]
Its size is fine for UX especially for smaller screens, It needs to stay that way.

**Comment by illori** [comment]
i think the text strings need to be updated. if you are not fixing the size of the close button then this can be closed after the text strings get fixed.
