### ISSUE TITLE
display on tablet (vertical orientation)

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#2460]
When viewing a 2.1 forum on a tablet, horizontal - the screen displays fine. Pretty much just like the desktop display. On a phone, in either vertical or horizontal, the main index page displays with only the icon, the board name and description. (correctly, nice layout)
In vertical configuration, however, the main index displays oddly.

it displays all 4 columns - icon, board name and description, post numbers, and recent post...
but recent post is right justified, below the other stuff.  it looks odd....

**Comment by XinYenFon** [comment]
Devices (names/models) and if possible screen shot :)

**Comment by Kindred-999** [comment]
iPad air... 
![image](https://cloud.githubusercontent.com/assets/4106630/4781796/ae586186-5cbf-11e4-9072-9b0ff8f9fd5b.jpg)

**Comment by XinYenFon** [comment]
Can you try again with this https://github.com/Antes/kittenground/blob/responsive/Themes/default/css/responsive.css :)
