### ISSUE TITLE
New Settings in Themes

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#2461]
If you go to add a new setting to a theme it does not work for example this code

in 2.0 add the following to index.template

';
if(!empty($settings['randomsetting']))

```
    echo '
   <li> [img alt=]http://www.bryandeakin.com/forum/Themes/Studio002/images/theme/logo.png[/img]</li>';
```

echo'

and this to Settings.template

```
    array(
        'id' => 'randomsetting',
        'label' => 'Random Setting',
    ),
```

They work fine, add them to 2.1 or any other setting to the default theme or copy then it does not work.

**Comment by Oldiesmann** [comment]
What exactly isn't working? I tried adding a new setting on my test board and it showed up just fine in the appropriate area of the admin center.

**Comment by margarett** [comment]
I also tried this and it works fine.

What doesn't work is this:
`[img alt=]http://www.bryandeakin.com/forum/Themes/Studio002/images/theme/logo.png[/img]`
It should be a regular img, not a BBC-like thing...
But it echoes the line as expected.

This is on SMF default theme. Are you trying it in a custom theme?

**Comment by XinYenFon** [comment]
I added extra setting to Lunarfall but I can't reproduce any weird stuff. Can be closed?

**Comment by live627** [comment]
Yeah. Looks as if he's confusing theme settings and member options.
