### ISSUE TITLE
Cursor is bad showing in IE 11 again

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#2462]
Hi, back turned up a bug at the IE11 browser, the cursor isn't in his place.

![fulleditor](https://cloud.githubusercontent.com/assets/8003629/4782539/48953a96-5cfa-11e4-8e96-0b02bdc99699.png)

![quickreply](https://cloud.githubusercontent.com/assets/8003629/4782540/4b6b6204-5cfa-11e4-8d91-2189633999a9.png)

The cursor badly is shown in a quick reply, right after refreshing. Also during creating a new post/edition post the cursor badly is shown not on place in the editor of writing.

**Comment by Oldiesmann** [comment]
Unfortunately there doesn't seem to be a good solution to this. Enabling auto-focus for the editor fixes the problem, but doing that will also make the quick reply box become auto-focused on the topic display. I'll look into this further and see if there's a way we can selectively enable auto-focus (eg enable it for the main post form but not for quick reply).

**Comment by MissAllSunday** [comment]
Passing the autofocus option when the editor is instantiated on GenericControls.template.

A ternary could be used to know if this is for the quick reply or the main post form.

Currently both the quick reply and the main form has the same id:

``` php
$editorOptions = array(
        'id' => 'message',
```

The quick reply one can be changed to

``` php
$editorOptions = array(
        'id' => 'quickReply',
```

or whatever, then on genericControls add a ternary:

``` php
$("#', $editor_id, '").sceditor({
                    ',( $editor_id != 'quickReply' ? 'autofocus : true,' : '' ),'
```

That way the autofocus won't be active on quickreply.

If the editor_id var isn't enough, we can even add an extra param array to template_control_richedit so mod authors can apply their own sceditor options as they see fit.

This also avoids having to modify the sceditor.js file directly.

**Comment by Oldiesmann** [comment]
Disabling it based on the ID should be enough for now.
