### ISSUE TITLE
Some bug during the installation

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#2483]
During the installation in finish stage showing such a bug:

![smferror](https://cloud.githubusercontent.com/assets/8003629/4860543/6ae40b4c-60f9-11e4-9bb3-c8af57bfe731.png)

**Comment by Oldiesmann** [comment]
Can you provide more details about where this bug is happening (such as what's displayed by the file or what the "step" info is from the query string)? That's from the function un_htmlspecialchars(), but that function is never called directly by the installer.

**Comment by jsqx** [comment]
After set up a account of the administrator in the final stage this bug shown in the top part of installation.

Installation bar has a 100 per cent.

Don't you see this bug in installer?

**Comment by MissAllSunday** [comment]
Looks like $context['character_set'] hasn't been set when un_htmlspecialchars is been called. Makes sense since loadTheme() doesn't get called on install or upgrading.

upgrade.php does have its own version of un_htmlspecialchars, perhaps install.php should do the same.

**Comment by Oldiesmann** [comment]
That wouldn't help since un_htmlspecialchars is never called directly from the installer. I'm trying to figure out where exactly it's called.

**Comment by MissAllSunday** [comment]
Maybe not directly but def indirectly.

The upgrade is calling it, doesn't really matter why or when, I vote for going the same way install.php does and create a vanilla version of un_htmlspecialchars without $context['character_set'] or replace it with whatever we are using on upgrade to get the charset.

That way we don't mess up with the real un_htmlspecialchars and we don't have to load extra files on upgrade just to use a var.

**Comment by Oldiesmann** [comment]
I was thinking the easiest solution would be to simply modify un_htmlspecialchars to use UTF-8 as the character set if $context['character_set'] isn't defined. It's highly unlikely that someone would be installing 2.1 with a different character set at this point.

**Comment by MissAllSunday** [comment]
Yes, but its pretty possibly that someone upgrading from 2.0 doesn't have utf8 as charset :(

We don't really need to modify un_htmlspecialchars() we only need to define one for upgrading purposes.

Upgrading is something that will be done only once, there is little point on modifying un_htmlspecialchars just to handle that single time, better create a new one for that specific purpose.

**Comment by Oldiesmann** [comment]
I thought you said upgrade had its own version of un_htmlspecialchars and didn't use the $smcFunc one. This issue, as far as I know, just applies to new installs.

**Comment by MissAllSunday** [comment]
oh yeah, :P my bad, got confused, but still, will be better to use a specific function for installing and leaving the regular un_htmlspecialchars  unmodified.

**Comment by Oldiesmann** [comment]
That won't work though since it's never called directly by any of the install files...

**Comment by Underdog-01** [comment]
I did not spot this prior to it being closed.

Shall I emend the edit to perhaps default the setting to UTF-8 if $context['character_set']  is empty or was this resolved by another edit somewhere else?

**Comment by Oldiesmann** [comment]
Changing it to use UTF-8 if the character set isn't defined should fix the issue.
