### ISSUE TITLE
show_email and code clean up needed

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2500]
https://github.com/SimpleMachines/SMF2.1/commit/b443bb82ae18959075eb1a3c40475fa0a56e9de7

the ability to email users directly from SMF was removed, but not completely

search SMF for show_email and you will find parts left over in Display.php, Load.php, News.php, PersonalMessage.php, Display.template.php, PersonalMessage.template.php, Profile.template.php

**Comment by MissAllSunday** [comment]
The send mail page was indeed removed.  The "show_email" part only shows a mailto anchor tag and it only appears if you can moderate that board.

**Comment by illori** [comment]
even if you are admin you can not view the email address, it is no longer in the display template.

if the email address is not shown on display.template.php why do we need code in display.php for email?

```
$memberContext[$message['id_member']]['show_email'] = allowedTo('moderate_forum');
```

only part that is close to showing the email address in display.template.php is 

```
// Otherwise, show the guest's email.
    elseif (!empty($message['member']['email']) && $message['member']['show_email'])
        echo '
                                <li class="email"><a href="mailto:' . $message['member']['email'] . '" rel="nofollow">', ($settings['use_image_buttons'] ? '<span class="generic_icons mail centericon" title="' . $txt['email'] . '"></span>' : $txt['email']), '</a></li>';
```

if i give my test user moderate_forum permission they can not view the email address of the user in the mini-profile. they can view the email address on the users full profile though.

show_email only seems to show the email address in the pm template in the sent folder. for a moderator to view the email address that is in the profile only and only if they have moderate_forum permission per the comment on line 153. which according to load.php line 1217 seems correct.

**Comment by MissAllSunday** [comment]
Thats only for the guest accounts. I see no bug here, the send mail page was removed and the mail only shows for people who can moderate a forum and posting guest members.

If the pm template wasn't updated then thats all we need to do, change that template to follow what Display.template already does.

**Comment by illori** [comment]
display.template.php has 

```
    elseif (!empty($message['member']['email']) && $message['member']['show_email'])
```

the last part about show_email has to be removed as that setting no longer exists.

Profile.template.php

```

    if ($context['member']['show_email'])
    {
        echo '
                <dt>', $txt['email'], ': </dt>
                <dd><a href="mailto:', $context['member']['email'], '">', $context['member']['email'], '</a></dd>';
    }
```

that has to be removed as the setting no longer exists.

maybe i am wrong but i think with this setting being removed there is some code left behind that could be cleaned up and made easier to use, why have 

```
if ($context['member']['show_email'])
```

when you could just put in 

```
if (allowedTo('moderate_forum')) 
```

instead?

**Comment by Oldiesmann** [comment]
$context['member']['show_email'] is leftover from the old behavior, but it should allow you to see your own email address too.

```
    'show_email' => !$user_info['is_guest'] && ($user_info['id'] == $profile['id_member'] || allowedTo('moderate_forum')),
```
