### ISSUE TITLE
Image Proxy Secret default too small?

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#2507]
Seems like image proxy secret is too small. Only using 8 characters with sha1 which limits it to numbers and lower case letters...

'image_proxy_secret' => substr(sha1(mt_rand()), 0, 8),

**Comment by Dragooon** [comment]
It's simply a salt to reset links in case some user abuses it and to prevent unnecessary linking, the admin can reset it from ACP.

**Comment by VBGAMER45** [comment]
If it can be abused should be increased no reason to keep it small. In theory you could craft a request to proxy.php and just use up the disk space.

Also possible to use a well crafted image with php code/other executable which could be called since it only checks content type of the storing the remote image. if another unknown security issue discovered that allows calling of files.  Granted it is small requires image proxy to be enabled.

// Make sure the url is returning an image
        $contentParts = explode('/', !empty($headers['content-type']) ? $headers['content-type'] : '');
        if ($contentParts[0] != 'image')
            return false;

**Comment by Dragooon** [comment]
Eh, sorry for the triple mention in commits. Anyways, my PR should fix your concerns.

**Comment by VBGAMER45** [comment]
Thanks
