### ISSUE TITLE
Undefined index in upgrade.php

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#2514]
I'm trying to convert a user's forum. Since I don't have the admin password, I used the "disable_security=true" thing.
At second screen, I get this:
Notice: Undefined index: passwrd in C:\xampp\htdocs\work\upgrade.php on line 1178
It seems to come from here:
.......name : ''), $_REQUEST['passwrd'], (!empty($password)...........

**Comment by NanoSector** [comment]
Are you still experiencing this issue?

**Comment by margarett** [comment]
Yes. I can reproduce it easily with an upgrade from a clean 2.0.9 install in my localhost. Even with the package just downladed from here ;-)

edit: line is now 1180

edit2: this easily fixed by changing the check of "!$disable_security" to the beggining of the "if"

```
if ((empty($sha_passwd) || (!empty($password) ? $password : '') != $sha_passwd) && !hash_verify_password((!empty($name) ? $name : ''), $_REQUEST['passwrd'], (!empty($password) ? $password : '')) && empty($upcontext['username_incorrect']) && !$disable_security)
```

To

```
if (!$disable_security && (empty($sha_passwd) || (!empty($password) ? $password : '') != $sha_passwd) && !hash_verify_password((!empty($name) ? $name : ''), $_REQUEST['passwrd'], (!empty($password) ? $password : '')) && empty($upcontext['username_incorrect']))
```

I would send a PR for this but I don't have SourceTree in this computer, sorry :(

**Comment by NanoSector** [comment]
I'll look into this once I have access to my laptop again, thanks :)
