### ISSUE TITLE
Lot of bugs in the first Beta

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#2515]
Bugs I found today...
Message index: no icons or ckeckboxes for sticking and so on.
Topic: Quick Edit don't work (do nothing).
Message edit: Smileys are not shown as image if you switch to source view and back to WYSIWYG.
A lot of "session timeouts" if you go to admin page. After ckick on "back" he go's to Admin ... 
Display.php on line 1372 gives a error "Undefined index: member"

More come I found more ;-)

**Comment by illori** [comment]
you cant go back to an admin page any longer to edit, you need to refresh the page. this is due to the new tokens.

**Comment by XinYenFon** [comment]
I can see both checkboxes & icons for moderation
Quick Edit working on display

**Comment by live627** [comment]
so negative...

Switch to the default theme.

**Comment by Oldiesmann** [comment]
The Display.php issue was fixed recently.

**Comment by PortaMx** [comment]
I See that the first TD is very long (50%). That is a little bit to great if you usw a smaller screen. I change this to 45% and all works perfectly...

**Comment by Oldiesmann** [comment]
I am able to reproduce the issue with smileys in the editor when editing a post. We'll look into that.

I can't reproduce the issues with quick mod checkboxes/icons, and quick edit works fine for me as well. I'm also not getting any session timeout errors in the admin center.

Which TD are you referring to?

**Comment by PortaMx** [comment]
Messageindex if i remeber that correct. the first td who the messagetitle and username didplayed.
Quickedit works now, it was mine issue.
