### ISSUE TITLE
cookie bugs...

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#2517]
smf do not use local cookies .. even is this set.
not for sessionid and also not for expand/collapse cookies (script.js).
I replace the cookie routine with my own, they use local cookies and checks also for ECL accepte ;-)

**Comment by MissAllSunday** [comment]
I'm sorry, I couldn't understand what you're trying to say.

Wikipedia shows a lot of results for ECL: http://en.wikipedia.org/wiki/ECL

Maybe some code examples?

**Comment by PortaMx** [comment]
ECL = European Cookie Law .. means do not set any Cookie until this is accepted by the viditor...

**Comment by PortaMx** [comment]
What I not unterstand ...
SMF habe a Routine for correct cookie handling .. located ihn the Subs-Auth i mean (smf_setcookie). Why not move thise Routine to a file what is loaded any time and (best) Front of any other? This function then can also called from JavaScript to set vor get a cookie by a simple Ajax post call...
Exactly that I habe implemented i  my Portal for SMF 2.1 ...

**Comment by MissAllSunday** [comment]
OK, just to clarify...

Do you want SMF to abstract cookie code so mod authors can handle/use/modify it better or do you want SMF to implement full support for the ECL stuff?

I'm all for abstracting code and make life easier to mod authors. With that said, Subs-Auth is already available pretty early on the process and its  loaded all the time.

Having JS to be able to call the server requires an extra action though, this means a good bunch of files and processes has to be run already before we even reach that action.

It would be far, far more easier if you just provide code examples, if you already did all of this stuff then why not simply create a pull request with the necessary changes?

**Comment by Oldiesmann** [comment]
It sounds like she wants us to move the setCookie() call so it can be handled by JavaScript if the user agrees to accept cookies, which seems like a lot of work to me.

**Comment by XinYenFon** [comment]
SMF is not an European registered organization so it does not need to compile with it's laws.

-----Original Message-----

**Comment by tekkla** [comment]
It's not about SMF and European law. It's about European law when setting a cookie without giving information to the user that you are using cookies on your site. See http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm

**Comment by MissAllSunday** [comment]
All we can do is make it easier for mod authors to create a mod for it. We cannot and really shouldn't comply with any local laws each admin needs to comply with.

**Comment by PortaMx** [comment]
The point is, that the SMF cookie handling is not correct at all points.
Parts use set_cookie other usw smf_setcookie, here with the correct parameters.
So I think, its correct to usw smf_setcookie at all.... also on JS script in toggle as example...

**Comment by MissAllSunday** [comment]
I did a quick scan on all Source files and there is no trace of set_cookie. Every file uses setLoginCookie()  which is using smf_setcookie()

There is also no trace of setcookie() either.  Can you please be more specific and tell us exactly where you think theres something that needs to be addressed?  file/line would be highly appreciated.
