### ISSUE TITLE
here a todo..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#2521]
for local cookies...

in Session.php:
    // @todo Set the session cookie path?
    if (!empty($modSettings['localCookies']))
    @ini_set('session.cookie_path', $parsed_url['path'] . '/');

works..

But .. I don't know how the template return a false even if the ckeckbox ckecked...

**Comment by Dragooon** [comment]
This is a direct duplicate of #2516, post it there.
