### ISSUE TITLE
Check boxes too narrow on mobile

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#2523]
Check boxes are too narrow, to the point where I can barely see them on my phone.

![screenshot_2014-11-24-01-33-06](https://cloud.githubusercontent.com/assets/89023/5161577/e8af6786-737a-11e4-8af2-1711ef6304ce.png)

**Comment by XinYenFon** [comment]
I thougt @illori opened issue for this guess I'm wrong :P I'll look into this after I wake up properly :D :D

**Comment by illori** [comment]
i never opened an issue but i did mention it on irc sometime ago. which i believe you said you would look into it then :P .

**Comment by XinYenFon** [comment]
Oh I be bad kitty then :P (still my eyes are burning)...
