### ISSUE TITLE
Wap, Wap2, Imode

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#2524]
.. don't works.
Always a error is reported:

---

An Error Has Occurred
Sorry, this section isn't available for wireless users at this time.
[0] Board index

---

I see in the souces, that a sub_template must be load for WIRELESS? 
But .. normaly it is nothig loaded.

Also WAP shows as xml source view ...

**Comment by Oldiesmann** [comment]
WML, the language used for regular WAP, isn't supported by desktop browsers, so that's why it shows up as source code.

WAP2 and iMode both work fine on my test board.

**Comment by live627** [comment]
Need a link. Until then, I'm tagging this as Bogus/Won't Fix..

**Comment by PortaMx** [comment]
I found the problem .. it was the different handling of custom action hook since SMF 2.0...
