### ISSUE TITLE
xcache

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#2525]
So once again I will try this as I have been told I am no help at all. There is a token verification failure with xcache. Also, the xcache user and pass need inputting everytime you wanna run xcache. Would be nice to see that changed.

**Comment by Oldiesmann** [comment]
For the username/password issue, make sure "xcache.admin.enable_auth" is turned off in php.ini.

I have XCache enabled on my server and am not running into any token verification issues.

**Comment by smfbigguy** [comment]
I'll try what you say for the user/pass but this has been an issue for me on two servers now. I have mentioned it before in a thread on SM and you yourself said that it was an issue, dragoon knew of it and it would be fixed soon.

http://www.simplemachines.org/community/index.php?topic=527041.msg3751464#msg3751464

**Comment by Oldiesmann** [comment]
That token issue has already been fixed though. If I go to Admin -> Maintenance -> Server Settings -> Cache and click "Run Now" for emptying the file cache, it works fine. I have tested it on two different forums (one that is based on the latest Git code and one that is 2.1 Beta 1 as released). Also note that that just empties the SMF file cache. It does not affect xcache.

**Comment by smfbigguy** [comment]
It has already been fixed.....hmm, cause I still get it on mine. Ok, I'll see what I can do to figure out what is wrong with my site then.

**Comment by smfbigguy** [comment]
Maybe it has something to do with fastcgi. 

Xcache authentication will not work with CGI or FastCGI. This is not an issue unique to Xcache; it is a limitation of PHP in CGI mode, as the PHP_AUTH variables are not available.

**Comment by smfbigguy** [comment]
I turned off xcache.admin.enable_auth in the php.ini file on my server and now all works fine. Guess it was my error. I will close this now.
