### ISSUE TITLE
Fatal Error: Call Time Reference

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#254]
I get this on the forum message index. As of PHP 4, call time reference passing is illegal. Unfortunately, making a call_integration_hook() argument a reference may have unintended consequences. 

```
Fatal error: Call-time pass-by-reference has been removed; If you would like to pass argument by reference, modify the declaration of call_integration_hook(). in /opt/lampp/htdocs/SMF2.1/Sources/MessageIndex.php on line 665
```

**Comment by emanuele45** [comment]
Duplicate of #54
