### ISSUE TITLE
Profile fields (aim, icq, msn, yim, location, gender) problems

### ISSUE THREAD

**Issue by nwsw** [SimpleMachines/SMF#2545]
There are a couple of issues with the custom profile fields:
1. None of the new custom profile fields stored in `{db_prefix}themes` get migrated over during an upgrade.
2. The gender field apparently needs to be specifically converted from an integer to a string.
3. When a user changes their profile, all of the custom profile fields get added to the database, even if they are all empty.

**Comment by nwsw** [comment]
The primary upgrade problem is caused by the following code in the 2.1 database upgrade scripts:

``` php
// We cannot do this twice
if (@$modSettings['smfVersion'] < '2.1')
```

The `$modSettings['smfVersion']` is actually set to **2.1 dev0**, which will not pass this test. This check appears in multiple locations in the 2.1 database upgrade script.

With regard to the custom profile fields, the following check seems to be a satisfactory replacement:

``` php
// We cannot do this twice
// First see if we still have a gender column
$results = $smcFunc['db_list_columns']('{db_prefix}members');
if (in_array('gender', $results))
```

**Comment by Dragooon** [comment]
The fix for this was merged
