### ISSUE TITLE
Wrong link in "View all attachments"

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#2548]
Just to track it, reported in sm.org by Dav999
http://www.simplemachines.org/community/index.php?topic=530662.0

> Not sure if this has ever been reported, but on the page in the admin center to view all attachments, the links to posts containing the attachments look like this: > (...)/index.php?topic=123.0.msg12345#msg12345. As a result, the link always leads to the first page of the topic. Nothing really major, as you can just remove the 0 from the URL, but I thought I'd point it out so it can be fixed. :)
> 
> This happens in both 2.0.x and the 2.1 beta (and probably 1.1.x too but I haven't tested it on that).

**Comment by Arantor** [comment]
Same fix as documented in thread, currently line 535.
