### ISSUE TITLE
"Quote from:" link

### ISSUE THREAD

**Issue by apiweb** [SimpleMachines/SMF#2550]
It would also be necessary to take some care to avoid "useless redirects". 

Explain:
If the post (original post) is referred on the same page, just scroll the screen to the quote, and only if the message is mentioned on another page, the redirect happens, it can leave the most dynamic forum for those who want to follow the quotes to accompany posts .
I think that it is possible, IPB and XenForo implement this option.

**Comment by colinschoen** [comment]
Seems like a good idea however, I don't know how often people will link to the original post in the same thread rather than just quote it.

**Comment by XinYenFon** [comment]
Good ideas but It needs to be in [Feature Request](http://www.simplemachines.org/community/index.php?board=3.0) page.

**Comment by Arantor** [comment]
Actually, quoting a post in-thread is very, very common. apiweb is not talking about the 'original post', but simply a quoted post.

Wouldn't be that hard if the quote bbc had a suitable identifier on it to pick up in JavaScript.

**Comment by colinschoen** [comment]
I understand, I was thinking rather than quoting, he meant directly linking too. That makes sense for the link above the quoted element.

**Comment by Arantor** [comment]
Well, he is. A quote includes a link back to the post, albeit with an index.php?msg=id link that counts as a redirection in itself. But he's right, if it's elsewhere on the same page it would be possible to grab that and just scroll the page rather than reloading it.

**Comment by colinschoen** [comment]
Yep, I got that. I was just explaining my previous misunderstanding.
