### ISSUE TITLE
Crash when sending email notifications

### ISSUE THREAD

**Issue by matteosuppo** [SimpleMachines/SMF#2561]
The function `loadEmailTemplate` at https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Post.php#L2696 tries to fetch the template by appending `_subject` and `_body` to the variable `$template`

``````
if (!isset($txt[$template . '_subject']) || !isset($txt[$template . '_body']))
    fatal_lang_error('email_no_template', 'template', array($template));```
``````

However, in the file https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/tasks/CreatePost-Notify.php#L132

the function may be called with the `_body` suffix already appended.

``````
if (!empty($prefs[$member]['msg_receive_body']) && in_array($type, array('topic', 'reply')))
$message_type .= '_body';```
[...]
$emaildata = loadEmailTemplate($message_type, $replacements, empty($data['lngfile']) || empty($modSettings['userLanguage']) ? $language : $data['lngfile']);```
``````

and of course it crashes

**Comment by NanoSector** [comment]
How does it crash, exactly?

**Comment by Oldiesmann** [comment]
It shouldn't crash at all. The templates "notification_reply_body" and "notification_topic_body" exist as well. The reason for the extra "_body" is because we use a separate template when we're including the message body in the email.

**Comment by matteosuppo** [comment]
You're right...

It doesn't crash there. I'll have to investigate further.

By crash I mean that the process stops without sending any error.

**Comment by matteosuppo** [comment]
I cannot reproduce it anymore. Sorry for wasting your time
