### ISSUE TITLE
Duplicate CSS properities in index.css

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#2564]
Appears to be some duplicate CSS properties unless it was done for some reason but from what I read only the last CSS property is executed.

Issue  border property

.quickbuttons li ul li, .quickbuttons li:hover ul li{
    display: block;
    background: none;
    border: none;
    box-shadow: none;
    width: 12em;
    border: 1px solid transparent;
    border-radius: 3px;
}

Issue  background color

.activity_stats li div.bar div {
    background: #6294CE;
    background: orange;
    box-shadow: 4px -4px 4px rgba(0,0,0,0.1) inset, 4px 4px 4px rgba(255,255,255,0.3) inset;
}

Issue padding/margin repeated need to know which one is good
# poll_options dl.options dd {

```
margin: 0 0 0 15px;
padding: 1px 0 0 0;
width: 60%;
max-width: 45em;
float: left;
margin: 0 0 4px 0;
padding: 0;
line-height: 1.4em;
min-height: 1.4em;
background: #fff;
border: 1px solid #aaa;
border-radius: 2px;
position: relative;
```

}

**Comment by XinYenFon** [comment]
border: none;
background: #6294CE;

needs to go, I have to test the last (effect wise) to see which parts needs to go.
