### ISSUE TITLE
[UX] Disable - Remove Theme

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2582]
Generally SMF supports text with icons, but remove theme page has different functions (disable/remove) next to each other.

This creates two problems;
- users start to ask how to remove a theme.
- users actually delete themes as thinking of disabling them (even it has pop message).

**Comment by NanoSector** [comment]
What exactly is the issue here?

**Comment by XinYenFon** [comment]
Sorry @Yoshi2889 I actually forgot to write -reminder to myself- note in this issue. I wrote this for myself so I can comeback later and fix the issue(s) I forgot :P
