### ISSUE TITLE
Theme Creating

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2583]
While I was working on my theme, one thing so badly blocked my way... and created extra work to me. It was menu items.

I think menu items needs to be controlled by GenericMenu.template, with that theme authors don't need to edit source part.

Second part was some files are forced to use default theme, which also giving limitation to theme authors, for example I want to edit SCEditor but JS (which also contains most of the UI) is forced to open in default theme.

**Comment by live627** [comment]
> for example I want to edit SCEditor but JS (which also contains most of the UI) is forced to open in default theme.

My theme also edits that file, but how many people will do the same? I'm guessing virtually nobody...

Maybe SCE is a bad example? Have you found any other files that should be used in other themes, eg. calendar.css?

**Comment by XinYenFon** [comment]
Unless you are making Curve2 variant, you have to change things inside calendar.css, but you don't have to touch responsive.css/slider.min.css because I mostly used generic classes in SMF.

is it possible to check the file in theme if not exist fall to default? Like language system. So we can include/exclude any file we want from our theme and it still falls to default.

**Comment by live627** [comment]
```
    loadCSSFile('jquery.sceditor.css', array('force_current' => false, 'validate' => true));
    loadJavascriptFile('jquery.sceditor.js', array('force_current' => false, 'validate' => true));
```

**Comment by XinYenFon** [comment]
But that just not loads the file completely if not exist. Its not loading from default. Also there are lots of icons embedded into source part.

![source-theme](https://cloud.githubusercontent.com/assets/1669995/5333848/143cf536-7e8d-11e4-8d8d-122b90f1faf6.PNG)

**Comment by XinYenFon** [comment]
+dozens of hardcoded css forces from source, like class & style

``` php
        'additional_rows' => array(
            array(
                'position' => 'after_title',
                'value' => $txt['errors_desc'],
                'class' => 'windowbg2',
                'style' => 'padding: 1ex 2ex;',
            ),
        ),
```

**Comment by Oldiesmann** [comment]
The list system was designed specifically so you could have custom styles for additional rows. I don't see why that's a problem. Most themers aren't going to want to change that.

**Comment by live627** [comment]
I think the issue here is with the hardcoded style... surely we can convert
it into a CSS class.

**Comment by Oldiesmann** [comment]
Yes,  you can move those to a CSS class, then replace style with class there, but it's not something most theme authors would touch and it's a bit pointless to make a class that's only used in that one place in the code.

**Comment by XinYenFon** [comment]
those extra classes are not a big deal, but still things in Subs-Menu needs to go GenericMenu.template. Otherwise we need to release modification(s) to fix things for our themes.

**Comment by Dragooon** [comment]
Menu items as in the Home, Search, Login/Logout etc buttons? How were they being blocked?

**Comment by XinYenFon** [comment]
Not really the menu items but icons they have, menu icons controlled in subs-menu.

-----Original Message-----

**Comment by Oldiesmann** [comment]
What exactly needs to be "fixed" for themes that can't be done with menus currently?

As far as loadCSSFile/loadJavaScriptFile go - just make sure `'validate' => true` is in the parameters array (along with `'force_current' => false`) and it should work the way you want it to.

**Comment by XinYenFon** [comment]
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Menu.php#L123

L123-147 controlling menu icons. If possible move that to template.

**Comment by Oldiesmann** [comment]
I'm still confused here as to why that needs to be moved to the template. I don't really see much there that can't be overridden by the theme author in some way or form.

Ignoring the comment and the first two lines afterwards for semi-obvious reasons...
Lines 125-128: If an icon is specified for that area and the image exists, use it (current theme first, then default theme)
Lines 129 and 130: If an icon is specified for that area but no corresponding image exists, set a class of "generic_icons {icon}" for that item.
Lines 131 and 132: No icon specified, so just set a class of "generic_icons {area_id}" for that item

Continuing on...
Lines 135 and 136: If an icon class is specified and no "icon" is specified, set the icon class to "{current_action}_menu_icon {icon_class}"
Lines 137 and following:
If an icon is specified:
 -- If "icon" ends in ".png" or ".gif" and a "big" image with that name exists, use that as the icon file (trying current theme first, then default theme)
 -- Set the icon class to "{current_action}_menu_icon {area_id minus ".gif" or ".png"}"

I'm not against moving things, but I'm just trying to figure out what advantage it would have over the current system. The current setup gives you consistency for one thing - the icon and icon class are set the same for each theme (though you can still override them in the template if you really want to - just change them to whatever you want before the actual menu HTML is output).

**Comment by XinYenFon** [comment]
Actually after investing some, I totally missed the $area['icon_class'] which is the only thing I need from source. :P sorry for being bit pita :D
