### ISSUE TITLE
Problems Upgrading

### ISSUE THREAD

**Issue by Tikkuy** [SimpleMachines/SMF#2584]
I've recently been trying to upgrade from 2.0.9 to 2.1 on a test forum, and everything seems to be working pretty great until we get to an upgrade function called 'Updating membergroup icons' or something like that. The whole process gets stuck on there, and the server stops responding. I waited for around fifteen minutes and still it seemed like nothing was happening. Is this a common issue?

**Comment by illori** [comment]
are you using the most recent source from github? i believe this issue has been fixed.

**Comment by Tikkuy** [comment]
I think I actually used the one over on the official SMF page at http://download.simplemachines.org/. Apologies for doing this the wrong way! I'll try out the GitHub version and let you know if it's still occurring.

**Comment by Oldiesmann** [comment]
It's a known issue with the version on the download page. I don't know if it's been fixed since then though.

**Comment by XinYenFon** [comment]
Upgrade working fine on latest build.

**Comment by Tikkuy** [comment]
Yup, it's working fine with the GitHub version. Thanks all.
