### ISSUE TITLE
Issue When Posting Unusual Characters

### ISSUE THREAD

**Issue by Tikkuy** [SimpleMachines/SMF#2592]
I'm having a problem when posting unusual characters in forum posts, like the character é. The post will simply cut off at the character before the unusual one and the work will be lost. In quick edit, the post will appear to be saved fully but when refreshing the page the portion of the post after the character will disappear. Is anyone else having this issue?

**Comment by MissAllSunday** [comment]
What charset are you using?

**Comment by Tikkuy** [comment]
settings.php is telling me UTF8.

**Comment by Tikkuy** [comment]
In a vaguely related issue, I seem to be having a similar problem with regular posts without unusual characters. I just made one of these posts and it cut off after about ten words or so. However, when I copied and pasted the text back into quick edit, it did save this time.

**Comment by MissAllSunday** [comment]
Did you did an upgrade or is it a clean install?

Can you post a text example?

**Comment by Tikkuy** [comment]
It was an upgrade from 2.0.9.

One example came up when I was speaking about a Beyoncé song. The post cut off right at "Beyonc" without including the é or anything after it. I can take a screenshot of the issue if you'd like?

**Comment by Tikkuy** [comment]
Just an update on the second issue not involving unusual characters - it seems like this has only happened so far with two posts I've made. In both cases, I've been copying and pasting text in from another website, and the post will cut off after the first apostrophe (') used.

**Comment by MissAllSunday** [comment]
Without enough details it would be nearly impossible to take a look and try to fix this I'm afraid.

A screenshot would not help, I need the original source this text was copied from, to see the charset used to post it, the charset that page was using and the charset you are using when trying to copy/paste the text.

Are you really using UTF8?

**Comment by Tikkuy** [comment]
Yes, I am using UTF8.

An example of the second issue I was having: I attempted to copy and paste the block quote from the first post on this page (http://www.spillitnow.com/viewtopic.php?t=273326) into a post on my website (http://pophatesfags.org/forum/index.php?topic=3441.msg35008). As I said, the post cut off at the first apostrophe (at "Fox's") when I first posted it. When I copied and pasted the entire post I had written back into Quick Edit and saved the post, it worked again.

Thank you for your help.

**Comment by MissAllSunday** [comment]
Your source code indicates you are using ISO-8859-1 on your pages which can cause conflicts if your DB is using utf8.

**Comment by Tikkuy** [comment]
Really? My apologies for that...I did check the settings.php file and it told me I was using UTF8. I'll try converting it over now and let you know how it goes. Thanks again.

**Comment by MissAllSunday** [comment]
Settings.php indicates your DB charset, the language pack you use indicates the charset your pages are been displayed.

The two of them needs to be in sync, ie, if your DB uses utf8, use a language pack suitable for utf8.

**Comment by Oldiesmann** [comment]
In 2.1, if the DB is UTF-8, the character set for the language is automatically forced to UTF-8 regardless of what the language pack specifies.

**Comment by Tikkuy** [comment]
Thanks for letting me know MAS. I'm a bit clueless when it comes to charsets.

Is that where the issue could be stemming from Oldies?

EDIT: I've managed to convert the database over. Just waiting to see if the error is persistent.

**Comment by Tikkuy** [comment]
I'm pretty sure this has resolved itself with the conversion! Thanks for your help.
