### ISSUE TITLE
Silverlight XAP files in mod packages break zip files in the package manager

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#2593]
I have a mod that bundles a Silverlight component as a fallback for missing browser functionality; this is a dependency in my package that I am not able or willing to change.

Now, 2.1 had a rewrite of read_zip_data. Previously it was done by stepping through the file but there were issues with this for some reason, and it was rewritten in 2.1 to explode() the data on the PK file header magic bytes.

Ordinarily this wouldn't be a huge problem, but a Silverlight XAP bundle is really a renamed zip file, so this gets caught up in the explode(), meaning that the zip files contains x files but x+2 (or more) files will be reported as there are additional file entries returned, and the comparison of $file_sections to $zip_info['files'] around line 265 of Subs-Package will then fail accordingly.

Now, I can package my bundle as a tar.gz which would work - but as far as I'm concerned this is a regression from 2.0.

Note that any mod that contains zip files in it for any reason, while unlikely, will have the same problem - this includes actual .zip files, Open Office XML files, OpenOffice/LibreOffice files and of course, Silverlight files.

**Comment by NanoSector** [comment]
Why don't we simply use the/a PHP ZIP library?

**Comment by Arantor** [comment]
Well, using ZipArchive sort of relies on it being available on the server, which is far from certain. The PEAR package is unmaintained and may not work properly on current PHP versions.

What might be an idea is basing something off the library I wrote originally for Wedge which should be immune to these issues but it will be some work to be suited to the job read_zip_data does; I built mine with the intention of extracting each file as a string so it could be uploaded via FTP (where I didn't want files on the filesystem), rather than just dumping to the filesystem. But it should be immune to this bug and also the bug that caused SMF to originally rewrite this component in the first place ;)

**Comment by live627** [comment]
This, I assume?

https://github.com/Wedge/wedge/blob/master/core/app/Class-ZipExtract.php

**Comment by Arantor** [comment]
Yup, that's the one. I don't think anything's been changed in it but it's impossible to know since the history prior to its relocation is broken. But yes, that worked with everything threw at it, including zip files that SMF choked on and it doesn't do it by way of exploding on zip file markers, but examines them one by one as the spec dictates - at least, that's my memory of it, it was a while ago I wrote it.
