### ISSUE TITLE
 8: Undefined variable: completed

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#2595]
guests are triggering this

 8: Undefined variable: completed

File: /.../test2/Sources/ScheduledTasks.php
Line: 109 

107:    // Log that we did it ;)
108:    if ($completed)
==>109:     {

**Comment by MissAllSunday** [comment]
Should have been solved with this: https://github.com/SimpleMachines/SMF2.1/pull/2587

**Comment by NanoSector** [comment]
Can't reproduce.
