### ISSUE TITLE
cookie problems (with fix)

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#2605]
I don't known if it's a php bug or other (I use php 5.5.15 on a window 8.1 server) ..
The problem:
If the hostname set and if it same as default (or as saved in $modSettings['globalCookiesDomain']), the cookie is not set !!
I change the code in the function url_parts($local, $global) from:

```
if (!empty($modSettings['globalCookiesDomain']) && strpos($boardurl, $modSettings['globalCookiesDomain']) !== false)
    $modSettings['globalCookiesDomain'];
```

to:

```
if (!empty($modSettings['globalCookiesDomain']) && strpos($boardurl, $modSettings['globalCookiesDomain']) !== false)
    $parsed_url['host'] = '';
```

now all works correct.

Seond change I made for the Session cookie:

```
// @todo Set the session cookie path?
if (!empty($modSettings['localCookies']))
    @ini_set('session.cookie_path', $parsed_url['path'] . '/');
@ini_set('session.cookie_httponly', !empty($modSettings['httponlyCookies']));
@ini_set('session.cookie_secure', !empty($modSettings['secureCookies']));
```

this works also perfect...

Also I wonder me, why not can set local cookies AND subdomin independet cookies?
That is possible and a good point to do that ...

EDIT:
I change the follow function, so all combinations (local and global) cookies will work for me:

```
function url_parts($local, $global)
{
    global $boardurl, $modSettings;

    // Parse the URL with PHP to make life easier.
    $parsed_url = parse_url($boardurl);

    // Is local cookies off?
    if (empty($parsed_url['path']) || !$local)
        $parsed_url['path'] = '';

    // Globalize cookies across domains (filter out IP-addresses)?
    if ($global && preg_match('~^\d{1,3}(\.\d{1,3}){3}$~', $parsed_url['host']) == 0 && preg_match('~(?:[^\.]+\.)?([^\.]{2,}\..+)\z~i', $parsed_url['host'], $parts) == 1)
        $parsed_url['host'] = '.' . $parts[1];

    else
        $parsed_url['host'] = '';

    return array($parsed_url['host'], $parsed_url['path'] . '/');
}
```

**Comment by Oldiesmann** [comment]
What exactly is the problem?

Why does setting $parsed_url['host'] to an empty string when the board URL contains the domain found in $modSettings['globalCookiesDomain'] fix things?

What specific changes did you make to the other sections of code you posted? Saying that you changed it without explaining what you changed doesn't help, especially when it's not clear what the problem is in the first place.

**Comment by PortaMx** [comment]
Well .. I found the first problem ..
I changed the domain on my local machine from "pmx.loc" to "pmx2.loc" 
AFTER install of SMF.
Also I changed the Apache, php config, the Settings.php and do a attempt 
to reset all themes.

But .. SMF do not change $modSettings['globalCookiesDomain'], and I 
found nothing in the admin section to change that. Today I do that in 
the database and now the Cookie is set correct.

For the PHPSESSID settings I add follow code to make this compatible 
with the cookie settings;
In the Session.php i add follow code;

```
 // @todo Set the session cookie path?
 if (!empty($modSettings['localCookies']))
     @ini_set('session.cookie_path', $parsed_url['path'] . '/');
 @ini_set('session.cookie_httponly', 
```

!empty($modSettings['httponlyCookies']));
     @ini_set('session.cookie_secure', 
!empty($modSettings['secureCookies']));

That do works perfectly.

Also I think it's good option that we can set GlobalCokkies AND 
LocalCookies ..this make sense if you use Modifikations line our 
SubForums modifiation and on other situations. I do set both always for 
more secure and also I set http cookies.
For this you ave to change the code, because it's currently not possible 
to set both cookie modes.

Also I reportet a bug (I think in the template), because the local 
cookie is never set, if I checked that and save.

Greetings
Feline, PortaMx CO

Am 15.12.2014 um 22:06 schrieb Michael Eshom:

**Comment by PortaMx** [comment]
I have changed the part in Session.php now as follow:

```
 // @todo Set the session cookie path?
 $parts = url_parts(!empty($modSettings['localCookies']), 
```

!empty($modSettings['globalCookies']));
     @ini_set('session.cookie_domain', $parts[0]);
     @ini_set('session.cookie_path', $parts[1]);
     @ini_set('session.cookie_httponly', 
!empty($modSettings['httponlyCookies']));
     @ini_set('session.cookie_secure', 
!empty($modSettings['secureCookies']));

I have tested with both (localCookies AND globalCookies) ON (manually in 
the datebase)
Works perfect .. the domain Cookie is saved as ".pmx2.loc", any 
subdoamain worked...

The function url_parts($local, $global) is unchanged.

Feline

Am 15.12.2014 um 22:06 schrieb Michael Eshom:

**Comment by Oldiesmann** [comment]
The "globalCookiesDomain" setting can be changed when you have "Use subdomain independent cookies" enabled.

You cannot have both "local cookies" and "global cookies" enabled at the same time. Local cookies means the cookie is stored only for the specific path to the forum (eg yourdomain.com/smf), while global cookies means that it's stored for the specific domain (yourdomain.com). The "subdomain independent cookies" option means that if you have a forum at smf.yourdomain.com, the cookie will be stored for "yourdomain.com" (or whichever domain you specify) rather than "smf.yourdomain.com".

**Comment by PortaMx** [comment]
You are not right.. you CAN have both enabled and that is the best Option if you have more installations of SMS in the same domain and you use subdomains for different configurations  like our Subforums modification.
This is also published in the cookie RFC's ....

**Comment by MissAllSunday** [comment]
@PortaMx Can you not enable both at install as in, when the user install your mod? 

Seems to me this request will only ever be usable for your mod or other similar ones but lets be honest, there is a small percentage of people who will actually use this.
