### ISSUE TITLE
Background change on hover in board index

### ISSUE THREAD

**Issue by sagamusix** [SimpleMachines/SMF#2610]
A few years ago, I posted some custom CSS for SMF2 (http://www.simplemachines.org/community/index.php?topic=443742.5) that would change the background color of a board index row when hovering it. This can greatly help when navigating around, especially when using a wide screen where the thread title might be very far away from the other columns.
It would be really nice if SMF2.1 had this functionality built right into the default theme.

EDIT: Alternatively, having alternating row background colours would also be very helpful for achieving the same goal.

**Comment by XinYenFon** [comment]
Did you tried `.up_contain:hover{background: #color;}`

**Comment by sagamusix** [comment]
This is actually a suggestion to include this usability enhancement it in the default theme, not a question how to do it in SMF2.1. The exact same CSS snippet from my original post won't work in SMF2.1 of course (and the colours would be off), but it should serve as a good starting point.

**Comment by XinYenFon** [comment]
Its very easy to make and I don't think this should be in default.

**Comment by sagamusix** [comment]
Then please give some reason why it shouldn't be there - In my eyes, the usability on SMF's topic index has always been rather bad (especially on big screens), since it neither changes the background colour on hover, NOR has alternating row colours. Adding either of those two options would lead to a definitive usability enhancement and SMF would by far not be the first software to implement it. Just for the reference, the default themes of most popular forums implement one of the two techniques (a quick check shows that e.g. phpBB3 and WBB have hover colours, MyBB, IP Board and WBB have alternating row colours).

If you still don't see a reason to make use of either of the two techniques, then please explain me how you don't get lost when wanting to jump to the latest post of a given thread or making use of quick moderation. You need to mentally map the thread title on the left to the correct link or checkbox on the right of the screen, and SMF does not give you any guidance there.

**Comment by illori** [comment]
this IMO is something specific to you and your needs. this is a custom theme issue not something we need to include in the default theme.

we can not include every requested feature in SMF by default, this is one of those.

**Comment by sagamusix** [comment]
illori: we're talking about an improvement from usability perspective here, not a random feature. Why do you think that almost every other forum software, or indeed even this issue tracker we are writing on right now uses alternating row columns or hover effects? Why are you objecting so much against either of the two techniques?
Again - please tell me how you don't get lost on a widescreen monitor when wanting to quick-moderate a topic or jump to its latest post. Both of these links are far away from the thread title on such monitors, and it is difficult to figure out which item to click.

**Comment by illori** [comment]
some people not everyone want this feature, that makes it not worthy of a default feature.

this is something you want, you specially want this. we can not add every feature asked even if it is for usability, there are many usability features out there we can never add or want to add.
