### ISSUE TITLE
Something messy here!

### ISSUE THREAD

**Issue by Akyhne** [SimpleMachines/SMF#2613]
Post.template.php - line #398

`', $context['can_lock'] ? '<li><input type="hidden" name="already_locked" value="' . $context['already_locked'] . '"><input type="hidden" name="lock" value="0"><label for="check_lock"><input type="checkbox" name="lock" id="check_lock"' . ($context['locked'] ? ' checked' : '') . ' value="1" class="input_check"> ' . $txt['lock_topic'] . '</label></li>' : '', '`

name tags aren't correct and there's 2 hidden inputs.

**Comment by Arantor** [comment]
No, that's quite normal throughout SMF actually.

The way HTML works, if a checkbox is unticked, no value gets provided whatsoever. This ensures $_POST['lock'] is defined regardless of whether the user ticks it or not.
