### ISSUE TITLE
GenericList template 

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#2623]
Line 112

```
                <tr class="windowbg', $alternate ? '2' : '', $row['class'], '"', $row['style'], ' id="list_', $list_id, '_', $id, '">';
```

$row['class'] should be changed to isset($row['class']) ? (' ' . $row['class']) : ''
If not at least make sure there is a space between it in the HTML as specifying a class will otherwise break things.

On line 114 we assume that $row['data'] exists.  Can we make it so SMF can ignore that if it doesn't?  I know having a empty `<tr>` isn't valid HTML, but it appears we have usage cases in the LE that are more complex to fix than having SMF cleanly bypass it.

Both of these issues relate fixing some LE bugs for 2.1

**Comment by Oldiesmann** [comment]
The first one is definitely doable...

Where in the language editor do we have rows with no data? The easiest thing to do there would probably be to just output an empty &lt;td&gt; instead of leaving the tr empty.

**Comment by jdarwood007** [comment]
I am not entirely sure Oldiesmann.  I just know it happens and generates an error.  I haven't setup a LE dev environment with 2.1 myself.  Fixing the LE code is complicated due to its nature

**Comment by Oldiesmann** [comment]
I understand that the code is a mess, but I think this instance is something worth looking into further.

**Comment by XinYenFon** [comment]
btw this is not really fixed, you no longer get errors on screen but output is also empty.

**Comment by live627** [comment]
I've got something else for you to try:

./Themes/default/GenericList.template.php 

Kill `if (!empty($row['data']))`

Find `foreach ($row['data'] as $row_data)`

Add after  `if (!empty($row_data))`

**Comment by Antes** [comment]
nope it 'll bring back the errors on screen... :( I actually wrote that bit long ago, but @Oldiesmann asked me to wait if we find a solution from LE side. I'm sorry I was bit busy with weird stuff in RL and forgot to post that to you (kinda assumed you already see this snip in site stuff board).

```
	// Show the list rows.
	elseif (!empty($cur_list['rows']))
	{
		foreach ($cur_list['rows'] as $id => $row)
		{
			// This is needed for integrations which uses this template
			if (!empty($row['class']))
			{
				echo '
					<tr class="windowbg', $row['class'], '"', $row['style'], ' id="list_', $list_id, '_', $id, '">';

				foreach ($row['data'] as $row_data)
					echo '
						<td', empty($row_data['class']) ? '' : ' class="' . $row_data['class'] . '"', empty($row_data['style']) ? '' : ' style="' . $row_data['style'] . '"', '>', $row_data['value'], '</td>';

				echo '
					</tr>';
			}
			else
			{
				echo '
					<tr class="windowbg">';

					foreach ($row as $row_data)
					echo '
						<td>', $row_data['value'], '</td>';

				echo '
					</tr>';
			}
		}
	}
```

**Comment by XinYenFon** [comment]
Nope that's not working unfortunately. Snip i posted kinda working but it breaks the non-classed SMF td elements.

**Comment by Oldiesmann** [comment]
This is something that should be fixed on the LE side of things. If this were due to a third-party script that we had no control over, I could see possibly doing it in SMF, but since we have full control over the LE, we need to fix it there instead.

**Comment by XinYenFon** [comment]
If @Oldiesmann allows I suggest just using this code and resolve the issue;

```
    // Show the list rows.
    elseif (!empty($cur_list['rows']))
    {
        foreach ($cur_list['rows'] as $id => $row)
        {
                echo '
                    <tr class="windowbg', empty($row['class']) ? '' : $row['class'], '"', empty($row['style']) ? '' : $row['style'], ' id="list_', $list_id, '_', $id, '">';

            if (!empty($row['data']))
            {
                foreach ($row['data'] as $row_data)
                    echo '
                        <td', empty($row_data['class']) ? '' : ' class="' . $row_data['class'] . '"', empty($row_data['style']) ? '' : ' style="' . $row_data['style'] . '"', '>', $row_data['value'], '</td>';
            }
            // Little backward compatibility.
            else
            {
                foreach ($row as $row_data)
                    echo '
                        <td>', $row_data['value'], '</td>';
            }
                echo '
                    </tr>';
        }
    }
```

I know its better to resolve issues from LE side but its not looking basic work.

**Comment by XinYenFon** [comment]
What we gonna do here? Any decision?

**Comment by jdarwood007** [comment]
As of now I was able to fix some things with the Language Editor in regards to that.  But the data change does cause compatibility issues that I work around by filling the row array with double values in order to make the Language Editor work on both 2.0 and 2.1
