### ISSUE TITLE
language icon in admin menu changed

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2628]
the icon was this
![](https://raw.githubusercontent.com/yusukekamiyamane/fugue-icons/master/icons/blue-documents-stack.png)

and now is a different icon. i think this one did not end up in the latest sprite.

@antes can you look into this?

**Comment by XinYenFon** [comment]
I changed that icon because it was looking too much like "reports/logs".

**Comment by illori** [comment]
The icon we have now looks very strange. I don't even know what it is.

**Comment by Arantor** [comment]
Hmm.

The old icon wasn't great, the new icon is actually more confusing, I think. I know it's 'language' in the Fugue set but it doesn't strike me as being that identifiable for users.

In an ideal world we'd have a small version of the normal icon, something that indicated languages but in absence of that I'd have to suggest something like highlighter-text (the idea of highlighting the text to indicate language) or globe--pencil (to indicate the world nature of it)

While we're on the subject, why is the icon for the boards/categories options a Go board? Surely something like blue-folder-tree would be more appropriate.

**Comment by BitFros7y** [comment]
Just add some flag (British is used by most softwares...) and that means language for sure...If you are afraid that someone is gonna complain why is there British flag instead of Chinese than maybe add flag for current default language? (Yeah that would mean including icons in language pack's...)

**Comment by Oldiesmann** [comment]
Adding a flag of some sort should suffice, or what Arantor suggested. Using an icon based on the current language though is more trouble than it's worth.

**Comment by BitFros7y** [comment]
Yeah its a little of trouble that most users wont even use but we can make it and also use it for language switcher at frontend... that would be useful...

Maybe if not for 2.1 (if to much has to change) than for later versions.

In any case just a flag would be fine by me, and not because i suggested it but because globe always remind me on some kind of networking... (And that pencil wont help :D)

**Comment by live627** [comment]
Could we use http://www.languageicon.org/ ?

**Comment by illori** [comment]
i am not sure that is much better then what we have now. i have never seen it before to say it is easy to define what is for.

**Comment by XinYenFon** [comment]
no, simple reason: its not a playground there must be some consistency between icons.

**Comment by XinYenFon** [comment]
Can we move on this ? I'm rebuilding generic_icons, how about one of those ?
![locale](https://cloud.githubusercontent.com/assets/1669995/7003612/1da37910-dc66-11e4-83f0-163367f03a3a.png)
![locale-alternate](https://cloud.githubusercontent.com/assets/1669995/7003613/1da4faf6-dc66-11e4-8d94-1b7efae205c2.png)

**Comment by illori** [comment]
Can we just go back to what we had before? Then we don't need to agree on a
new icon :P .

**Comment by XinYenFon** [comment]
I hate that icon, I'm scratching it daily and burning it :/ (I'll revert to it :P)

btw I also need Green - Red exclamation & Thumb-tack (blue) version... my backup somehow lost. Can you please mail them to my mail antes@...

**Comment by illori** [comment]
I can try to look for them later.
