### ISSUE TITLE
"receive alerts" email sent for moved topic

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2631]
i have the option to receive alerts selected for a topic, another user moved the topic to another board and an email was sent out to the first user. if receive alerts is selected the user should never get any email about the action but an alert instead.

Notify me of: moderation only if i started the topic is selected in profile

**Comment by Oldiesmann** [comment]
An email was sent to the person who moved the topic?

**Comment by illori** [comment]
No to the person who started it.

**Comment by Oldiesmann** [comment]
But they've only got it set to receive alerts and not email?

**Comment by illori** [comment]
Correct. It seems to me that the moderation action emails have not been
moved to the alerts system.

**Comment by illori** [comment]
seems that if a topic is moved the topic starter never receives an alert if that option is selected.
if that same topic is locked/unlocked they get an alert, but not for a move.

those alerts were only "sent" when the user that started the topic did those tasks, if another user did no alert showed up.
