### ISSUE TITLE
moderation emails name moderator

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2632]
why do we need to tell users who exactly moved etc a topic/post? on most forums there is a way to tell who are moderators/staff and users can contact those to find out why an action was taken without pointing fingers at the moderator that did the action because an email was sent to them with the persons name.

IMO easiest way to fix for now is remove {POSTERNAME} from the email templates related to moderation.

**Comment by Kindred-999** [comment]
agreed...

**Comment by Oldiesmann** [comment]
Should we also handle unlock, sticky, merge and split? I've removed " by {POSTERNAME}" from templates for moving, removing and locking.

**Comment by illori** [comment]
yes, those are moderation tasks.
