### ISSUE TITLE
Shoving things up the appropriate channel now ma'am :D

### ISSUE THREAD

**Issue by StealthWombat** [SimpleMachines/SMF#2636]
http://www.simplemachines.org/community/index.php?topic=531791.0

tl:dr; version is it's bonkers to declare font sizes under 12px.

**Comment by XinYenFon** [comment]
I'll look at this tomorrow :D :D sorry can't stop laughing...

**Comment by StealthWombat** [comment]
You know me. Genteel and diplomatic and all that.
