### ISSUE TITLE
Overly specific CSS makes God kill kittenz

### ISSUE THREAD

**Issue by StealthWombat** [SimpleMachines/SMF#2637]
Lotsa stuff: http://www.simplemachines.org/community/index.php?topic=531736.0

**Comment by XinYenFon** [comment]
oh noez not the kittenz :(

**Comment by live627** [comment]
Save the kittens!

**Comment by XinYenFon** [comment]
No worries Hero Kitty is here to save teh kittenz!

**Comment by live627** [comment]
oh goodz :)
