### ISSUE TITLE
News fader/slideshow stuffz

### ISSUE THREAD

**Issue by StealthWombat** [SimpleMachines/SMF#2638]
Ok, first point: at the moment the php conditionals allow for both the random news lines and the fader/slideshow to be enabled at the same time. This seems rather bonkers, and it should be one or the other, IMO. Howz about changing the php to something like:

`
    // Show a random news item? (or you could pick one from news_lines...)
    if (!empty($settings['enable_news']) && !empty($settings['show_newsfader']) && !empty($context['random_news_line']))
`

for the random lines and:

`
    // Show the news fader?  (assuming there are things to show...)
    if (!empty($settings['show_newsfader']) && empty($settings['enable_news']) && !empty($context['news_lines']))
`

for the fader. Makes sense to me.

**Comment by StealthWombat** [comment]
Second point is that the nifty responsive slideshow aint all that responsive. If someone puts a nice big image banner in said slidey contraption (which is very likely to happen) the image will be cropped if the available screen width is less than the image width. This really should be handled by auto scaling via CSS, which shouldn't be hard to arrange.

**Comment by StealthWombat** [comment]
Third point is that the default changeover time of 500 ms is so fast it'll drive people bonkers. Why not something like 5000 instead? Might as well get it close to what people will actually want.

**Comment by XinYenFon** [comment]
1) Interesting point but fader(slider) only enabled in main page, while random news is everywhere.
2) That needs some work, actually its 100% responsive but since we can use smileys in news area, its makes things lot worse. (originally img tag has 100% width).
3) Actually its 3000, you need to run upgrade.php :) or I may forgot to add that to install sqls :/ my bad soz.

**Comment by StealthWombat** [comment]
Ok, fair nuffz. If you use max-width instead of width on the image CSS it should be fine. That won't screw up smileys but will scale banners.

The one I installed has 500 ms delay straight from scratch. Maybe look at the installer sometime.

**Comment by XinYenFon** [comment]
I have exam tomorrow then I have 5 days to focus on SMF 2.1, I'll surely go in install/upgrade & ssi.

yea that actually eliminates the problem :)
