### ISSUE TITLE
split topic broken?

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2643]
try to split a topic, go to a topic with many replies and click split in the more drop down from one of the replies. you are brought to a page to select the replies to split. click the arrow to move the replies and nothing happens.

if i refresh this page the replies get moved to the right side but they do not until i refresh the page. in 2.0 the replies would move to the right without a page refresh required.

a few related errors

 8: Undefined index: page_index
/github2.1/index.php?action=splittopics;sa=selectTopics;subname=test;topic=6.0;start2=0;move=down;msg=29;xml
File: F:/wamp/www/github2.1/Sources/Subs.php
Line: 572

this error shows on several different line numbers, 572, 571,654,624 all in Subs.php

**Comment by Oldiesmann** [comment]
The AJAX functionality is working fine, though I am getting the "undefined index: page_index" errors. Will look into that.

**Comment by illori** [comment]
now i am getting Type of error: Undefined
8: Undefined variable: txt
/github2.1/index.php?action=splittopics;sa=selectTopics;subname=Re%3A+test;topic=70.0;start2=0;move=down;msg=132;xml
File: F:/wamp/www/github2.1/Sources/Subs.php
Line: 576

also i still can not get the messages to move to the right, tested in opera 12.\* and ff 34.0.5

**Comment by Oldiesmann** [comment]
In Firefox, open up the console (CTRL+SHIFT+I then click "Console"). What JS errors (if any) are displayed when you click the right arrow?

**Comment by illori** [comment]
i updated again and it seems to be working.
just still have that error message about the undefined variable: txt

**Comment by Oldiesmann** [comment]
#2647 should fix the undefined variable issue, so it's possible you updated prior to me pushing that in.

**Comment by illori** [comment]
I updated right before I tested and commented on this. I will try to test
again.

**Comment by illori** [comment]
tested again, seems to be fixed no errors.

but you can not split a topic and leave only the first message behind on the pick your posts screen. you receive an error 
"You cannot split a topic at the first post." what is the reason for this? 2.0 does this as well.

**Comment by Oldiesmann** [comment]
It should only be doing that if you click "split" on the first message in the topic.

**Comment by illori** [comment]
If you are splitting any of the other messages in the topic I don't
understand why this message is there. Seems this happens when you split the
topic and only leave the first post behind using the pick the posts page

**Comment by Oldiesmann** [comment]
Yeah, it shouldn't be doing it in that case. I'll look into it when I get a chance.

**Comment by Gwenwyfar** [comment]
After trying to split the first message of a post (using the choose messages method), and then trying to click the "Back" button on the error message, this error appears:
This field only accepts numbers from 0-9

And after pressing back again, this one: Your session timed out while posting. Please go back and try again.

It repeats and never goes back to the split page.


Also, I'm getting the "You cannot split a topic at the first post." even if I am splitting only the last message, leaving the first post plus another post together. This is only with the "select posts" method, the other two work fine.

**Comment by jdarwood007** [comment]
@Gwenwyfar I'm not able to reproduce, can you provide all the steps you are doing to get this?

**Comment by Gwenwyfar** [comment]
I'm just going to "split topic" (from quickbuttons if it makes any difference) -> select messages to split -> select 3rd/4th messages. Still happening here.

**Comment by jdarwood007** [comment]
Are the 3rd and 4th messages the last 2?

My test
1. Topic with 20 replies
2. Use Quick Mod to select replies 3 and 4
3. Choose split
4. Sent to split page.  Click split
5. Success.

**Comment by Gwenwyfar** [comment]
No, I used a topic with 11 posts this time. But upon further testing, this actually seems to be two separate bugs. The first is that the back page does not work when there is an error, and the second is that the post order is not correct when splitting a topic:

![split](https://user-images.githubusercontent.com/28991853/42791032-668d46f4-8944-11e8-804e-336a2508851b.png)

These numbers are the same as their post order. Moving posts back and forth create even further misalignment.

**Comment by jdarwood007** [comment]
Was able to reproduce now.
1. Topic with 20 replies
2. Use QuickMod Icons and choose any reply, not the first msg
3. Choose "Select posts to split"
4. Click Reset Selection
5. Choose the first message and any others
6. Receive error you can't split first message
7. Wait 10 seconds, click Back
8. Receive error about session timing out.
9. Receive error about 0-9 numbers.
10. Loop occurs here.

This is because $topic info is lost due to the back button actually just taking us back a page and the session check having kicked in and telling us that you can't revisit the page that was already submitted.

Not a easy solution here.  Only simple solution here is to append to the url when going back something like "fromErrorPage" or similar to the URL.  If that is detected on another error page, don't show the back button (or only show a home button).  We could optionally show a message stating that navigation was from  a previous error message.

**Comment by albertlast** [comment]
Is the way how the pr #5389 fix the issue a possible good way?
