### ISSUE TITLE
Remove MOVED: redirection topics

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2644]
when manually attempting to run the scheduled task Remove MOVED: redirection topics, it seems to do nothing at all. i have at least 5 moved redirection topics, some are over a year old and the task does not seem to remove any of them automatically.

does it make a difference if never is selected to automatically remove the redirection topic?
even when 1 day is selected the task did nothing, maybe because it is less then 1 day?

if we can not remove the redirection topics if never was selected maybe a way to list those topics that are left behind so they can be manually removed?

**Comment by XinYenFon** [comment]
If I'm not wrong, there was a setting for redirect topics on redirect (set expiration time), since its not there system cannot calculate (or set) the expiration date for redirect topics and task cannot execute itself.

**Comment by illori** [comment]
i think part of the issue here was that the board 1 was missing and my moved topic redirects are in board 1, i will need to retest since @Dragooon seems to have fixed that.

**Comment by margarett** [comment]
I just found a nasty bug in this, which seems to be why it doesn't work. I'll submit a PR later today

**Comment by margarett** [comment]
@Illori, now I tested and this works.
Anyway it might not solve and delete your existing topics, if on the table they have "redirect_expires" = 0 (which some might have)
