### ISSUE TITLE
access manage attachments could be impossible

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#265]
Due to a recent issue at sm.org, me, CoreISP and @The-Craw find out that in certain cases this bit of code can make the server very sad:

```
    // Everything is okay so far, start to scan through the directory.
    $num_files = 0;
    $dir_handle = dir($dir);
    while ($file = $dir_handle->read())
    {
        // Now do we have a real file here?
        if (in_array($file, array('.', '..', '.htaccess', 'index.php')))
            continue;

        $num_files++;
    }
    $dir_handle->close();
```

This is used to count the attachments in each and every attachments directory at once without take any break for a coffee.

A way to pause the count and continue later would be nice I think.

**Comment by jdarwood007** [comment]
We should try to see if we can do a "ls dir | wc -l" first and if not then fall back.  Perhaps move this to a scheduled task once a day and then rely on updating the cache values to keep a semi-accurate count.

**Comment by joshuaadickerson** [comment]
Where is that code at?

**Comment by joshuaadickerson** [comment]
Oh yeah, besides that, we are using PHP 5 now... let's use scandir() instead. I found that using ls is also faster when I had similar issues at work.

**Comment by ghost** [comment]
@joshuaadickerson It's at the bottom of ManageAttachments.php

I should think that something like this would be far more efficient than looping through all the files.

``` php
// Get approximate file size of the entire directory.
echo round(filesize($boarddir. '/attachments' ) / 1024);

// Count all the files except three (.htaccess, back/current dot-files)
echo count(scandir($boarddir. '/attachments')) - 3;
```

**Comment by emanuele45** [comment]
Good point Josh, that could be a solution.

**Comment by joshuaadickerson** [comment]
I like @The-Craw's method. Get the file size of the files you want to exclude and subtract them if you want to be more precise but I don't think that is necessary.

**Comment by butch2k** [comment]
use 

``` php
echo count(glob($boarddir. '/attachments/*',GLOB_NOSORT));
```

rather than scandir it's a bit much faster.
18007 files
500 scandir: 10.132883071899
18007 files
500 glob: 8.8571441173553

**Comment by emanuele45** [comment]
50k files (20 times):

```
current: 3.9553589820862
glob: 3.5812120437622
scandir: 3.2565090656281
```

...I feel it really depends on many factors...

On the other hand, if I simply remove the `if (in_array(blabla))`

```
current: 1.9055411815643
glob: 3.5589849948883
scandir: 3.1512770652771
```

**Comment by butch2k** [comment]
low end server using PHP 5.4.9
1788 files
500 scandir: 3.1955649852753
1788 files
500 scandir (NO SORT): 2.4955389499664
1788 files
500 glob: 3.3973519802094
1788 files
500 dir read (NO in_array): 2.971538066864

on PHP5.4 scandir with SCANDIR_SORT_NONE seems the fatest of the lot.

need to check memory consumption as well especially for large directories.

**Comment by emanuele45** [comment]
Memory used (peak from memory_get_peak_usage) by scandir for 55k files is about 9 MB. Nothing important.

But the real issue is that from that figures there is no real difference from one or another.
A 5% doesn't change anything if the issue is a timeout.

**Comment by emanuele45** [comment]
It seems there is not much difference and probably the issue was server side.

Closing this one.
