### ISSUE TITLE
Undefined lt.unwatched

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#2650]
http://www.simplemachines.org/community/index.php?topic=532020.0

As per my comments, log_topics_unread is a temporary table that doesn't contain that column.

**Comment by MissAllSunday** [comment]
I'm not that familiar with the "unwatched" feature so I don't know if it would be feasible to also add the unwatched column to the temp table.

**Comment by Oldiesmann** [comment]
Looking at the code, we can just drop that part of the query as the one to pull the data for that table already handles that ("unwatched" is a column in log_topics that indicates whether the user has chosen to ignore the topic). I'll commit a fix shortly.

**Comment by MissAllSunday** [comment]
oh yeah, you're right.
