### ISSUE TITLE
Error at install

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#2651]
Trying to install with today's package from here, got this at step 5 (after entering admin account details)

Notice: Undefined index: htmlspecialchars in C:\xampp\htdocs\smf21\Sources\Errors.php on line 69
Fatal error: Function name must be a string in C:\xampp\htdocs\smf21\Sources\Errors.php on line 69

Although it's not possible to continue the installation process (white page), everything seems to be in place.
(didn't we go through a similar error before?)

**Comment by Oldiesmann** [comment]
The problem is an error is occurring somewhere within the install process, which eventually leads to log_error getting called, but none of the $smcFunc stuff has been loaded at that point. Is there an error_log file in your forum directory? If so, is there anything else in there besides the two errors mentioned above?

**Comment by margarett** [comment]
Nop, it's a local XAMPP install so I have access to PHP's logs. And I only have this

```
[06-Jan-2015 10:47:11 Etc/GMT-1] PHP Notice:  Undefined index: htmlspecialchars in C:\xampp\htdocs\smf21\Sources\Errors.php on line 69

[06-Jan-2015 10:47:11 Etc/GMT-1] PHP Fatal error:  Function name must be a string in C:\xampp\htdocs\smf21\Sources\Errors.php on line 69
```

**Comment by Oldiesmann** [comment]
That's not going to help unfortunately. Your best bet is to hack Errors.php there and have it die with an error message instead of trying to write it to the database. That will at least let us see what error is being generated.

**Comment by margarett** [comment]
Eh. Just downloaded the latest GH and tried to install 4x in a row. Never got the error...

**Comment by Oldiesmann** [comment]
Ok. Let me know if you run into it again and I'll look into it further.
