### ISSUE TITLE
alert for moderation actions

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2663]
you can now get an alert for a moderation action.

the avatar that shows is the avatar for the moderator that did the action. it should show the default avatar or a different one so the user does not know who did the action.

there also seems no alert for deleting a topic.

also it seems and i could be wrong that you dont get an alert for the moderation action unless you selected to receive alerts on that topic, so this overrides the setting somewhat in your profile that does not give you an option for email or alert just to let you know a moderation action has been done on a topic you started.

**Comment by Dragooon** [comment]
> also it seems and i could be wrong that you dont get an alert for the moderation action unless you selected to receive alerts on that topic, so this overrides the setting somewhat in your profile that does not give you an option for email or alert just to let you know a moderation action has been done on a topic you started.

This is intended, it says "Moderation only if I started the topic" which is kind of wrong, I'll fix the language.

**Comment by live627** [comment]
Hey long  time no see :)

That setting notifies of moderation only if the user has started and is
watching the topic.
