### ISSUE TITLE
Wrong gender stats

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#2666]
Details here:
http://www.simplemachines.org/community/index.php?topic=532209.msg3781872#msg3781872
In short: choosing "Male" as gender doesn't count towards the males totals.

Statistics say that there are far less man than women on Earth, and SMF is not helping us here... :tongue:

**Comment by bperry921** [comment]
Ok, I have a solid fix for the main sql structure and manipulations in the Sources/Stats.php page routine that handles gender tracking counts, its been running completely error free on my 2.1 site, it works great so far, about 3 days I think... However, to save myself a lot of unwanted confusion and additional hair pulling and cursing, sometimes I really get bent when arrays fool me repeatedly, not to mention exasperating syntax errors that you "know" should work lol, so I removed the beginning and ending cache manipulations temporarily... I'm old school concerning sql statements, so might not be perfectly elegant as you folks may be accustomed to, you'd be shocked to see the first custom hack I did for SMF platform in the stats page with the "Add Social Icons to Profile" module that HCFwesker? did, its ugly as hell but works great too, tho that mod not installed on my new 2.1 production site yet, but I'm pretty good at SQL for the most part after I commit myself to fixing a problem, I have not learned how to submit these things further up the chain in here yet, so feel free to take what's here and re-insert the two cache statements and the associated conditional tree, shouldn't affect anything inside the tree much if I'm not mistaken... after the last 36 hours I feel like sleeping for two days straight so not gonna mess with completing the rest of it anytime soon, so have at it yall  it functions perfectly on my install as is...

```
// Let's calculate gender stats only every four minutes.
$disabled_fields = isset($modSettings['disabled_profile_fields']) ? explode(',', $modSettings['disabled_profile_fields']) : array();
if (!in_array('gender', $disabled_fields))
{
    //additional custom gender fields could easily be inserted here if needed, but why?
            $context['gender']['Not Set'] = comma_format($modSettings['totalMembers']);
    $context['gender']['Female'] = 0;
    $context['gender']['Disabled'] = 0;
    $context['gender']['Male'] = 0;

    $result = $smcFunc['db_query']('', '
        SELECT COUNT(m.id_member) AS notset, COUNT(c.value) AS cnt, c.value AS genderhit
        FROM {db_prefix}members AS m
        LEFT JOIN {db_prefix}themes AS c ON c.variable = "cust_gender"
        WHERE m.id_member > {int:select} AND m.id_member = c.id_member
        GROUP BY c.value',
        array(
            'select' => 0,
        )
    );
    while ($row = $smcFunc['db_fetch_assoc']($result))
    {
        $context['gender']['Not Set'] = $context['gender']['Not Set'] - $row['notset'];

        // Assuming we're telling the genders in the forum...
        if (!empty($row['genderhit']))
        {
            $context['gender'][$row['genderhit']] = $row['cnt'];
        }
    }
    $smcFunc['db_free_result']($result);
}
```

**Comment by Oldiesmann** [comment]
Thanks for the suggestion. I'll take a look at your code and the existing code and see if I can figure out what's going on.

**Comment by Oldiesmann** [comment]
Turns out the fixed code is actually much simpler than what's been suggested here... I'll commit a fix for this shortly.

**Comment by bperry921** [comment]
Hey Oldiesmann,

After I finally figured out (stumbling around on here too much, bear with me as I learn how github works), anyway, I finally discovered where your version of the fix could be displayed... after looking at it for a minute I said duh why not... when I was stuggling to get my version working I actually considered removing that join and having separate queries like you did, but for some reason it got stuck in my mind that it would be more resource saving and speedier to make the one query function correctly so the thought was just fleeting at the time because i was too stubborn to consider it further... how do I go about downloading the most recent version with fixes?

**Comment by Oldiesmann** [comment]
Forgot to merge my changes in, but they're part of the repo here now.  
You can click "Download ZIP" on the right hand side of the main SMF 2.1 
GitHub page to download an archive containing all the latest files.

**Comment by bperry921** [comment]
Heads up man.... I don't know if you monitor everything that gets posted in that 2.1 support board on SMF, but I've been kinda miffed at some rather snippy replies I got and voiced same in responses but up until several hours ago I was going to let it go and keep to myself for a while... those folks need a keeper man!!..,  Arantor is the only one who knows what's up, so I wanted to warn ya that the gender thing is still broken, after examining the code it is not the same as what I saw here before you closed this, looks like you forgot to include the separate member table query cause its still broke after downloading/updating and testing on a completely module free 2.1 testing site located at http://www.rjventure.com/WPC_testsite2 

also, that same issue regarding the undefined index on field "member" that was affecting PersonalMessage.php when sending pms has appeared in the Display.php file too, when viewing a posted topics, same fix should correct it, I'll open a new issue about it in a few... first I'm going to lay into someone over there, and try to be as gentle as I can, but it won't be easy lol

**Comment by bperry921** [comment]
ok, not entirely broken, but after getting squared away with a clean 2.1 testing site finally, the counts are indeed being tracked accurately when changes occur, BUT there is still another fact that will crop its ugly head up forcing a rethinking of the issue being "fixed"... after we reach a public release, is it not a fact that after they update their site to 2.1 there will be a vast number of pre-existing members that will not have anything set? I tested it on the test site by manually blanking out my own entry, the results are ugly but easily remedied in the current fix as well I think... haven't checked if a tweak to your code is easy yet, but there's always mine and I know it accounts for that contingency... whichever, but it's going to pop up again later if ignored, yes?

**Comment by bperry921** [comment]
OK, tweaking your code kinda tricky but I came up with this which works pretty well...

```
// Let's calculate gender stats only every four minutes.
$disabled_fields = isset($modSettings['disabled_profile_fields']) ? explode(',', $modSettings['disabled_profile_fields']) : array();
if (!in_array('gender', $disabled_fields))
{
    if (($context['gender'] = cache_get_data('stats_gender', 240)) == null)
    {
        $result = $smcFunc['db_query']('', '
            SELECT COUNT(id_member) AS total_members, value AS gender
            FROM {db_prefix}themes
            WHERE variable = {string:gender_var}
            GROUP BY value',
            array(
                'gender_var' => 'cust_gender',
            )
        );
        $context['gender'] = array();
        while ($row = $smcFunc['db_fetch_assoc']($result))
        {
            if (!empty($row['gender']) AND $row['gender'] != ' ')
                $context['gender'][$row['gender']] = $row['total_members'];
            else
            {
                $row['gender'] = 'Not Set Yet';
                $context['gender'][$row['gender']] = $row['total_members'];
                $row['gender'] = null;
            }
        }
        $smcFunc['db_free_result']($result);

        cache_put_data('stats_gender', $context['gender'], 240);
    }
}
```

**Comment by Oldiesmann** [comment]
We can add a condition to ignore empty strings like that, but that situation should never occur.

From the upgrade script:
`$genderTypes = array(1 => 'Male', 2 => 'Female');`

Then a bit later

```
        if (!empty($row['gender']) && isset($genderTypes[intval($row['gender'])]))
            $inserts[] = array($row['id_member'], -1, 'cust_gender', $genderTypes[intval($row['gender'])]);
```

We're specifically only showing stats for members who have actually selected a gender (and we don't set it to "None" for those who haven't selected one).
