### ISSUE TITLE
action register not cought by dont allow guests to browse the forum

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2667]
if in the admin panel you select not to allow guests to browse the forum and go to the old register action github2.1/index.php?action=register you can still view the board index, this should not be possible.

other actions lead to the correct error page telling the user to register.

some cleanup still required for the old register action?

**Comment by margarett** [comment]
Yes, index.php

```
    // If guest access is off, a guest can only do one of the very few following actions.
    elseif (empty($modSettings['allow_guestAccess']) && $user_info['is_guest'] && (!isset($_REQUEST['action']) || !in_array($_REQUEST['action'], array('coppa', 'login', 'login2', 'register', 'register2', 'reminder', 'activate', 'help', 'helpadmin', 'smstats', 'verificationcode', 'signup', 'signup2'))))
        return 'KickGuest';
```

register and register2 should be removed from this.
