### ISSUE TITLE
upgrade.php does not finish running

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2669]
-  +++  We no longer call on several files. done.
  +++  But we do need new files.Duplicate entry '255' for key 'PRIMARY'

my update script runs upgrade.php even if it is not required. yesterday there were no issues that i recall but today i get the above.

my admin_info_files table has latest-versions.txt multiple times. maybe this is part of the issue?

**Comment by illori** [comment]
there are 247 rows for the entry latest-versions.txt

removing all those entries let the upgrade.php complete.

**Comment by NanoSector** [comment]
No issues here with upgrading though my admin_info_files table has multiple entries for this as well.

**Comment by Oldiesmann** [comment]
Not sure why it's duplicating latest-versions.txt. I'll look into that though.
