### ISSUE TITLE
glitch with who's who in notification email after "mention"

### ISSUE THREAD

**Issue by bperry921** [SimpleMachines/SMF#2678]
when someone uses mentioning, the email notification, if enabled, that is being constructed is misinterpreting who is who, receiver has wrong username in body salutation, confusing the recipient...

also a question, does mentioning not function in quick reply?

finally got latest release to load in my testing site, its been running over an hour 1/2 or so and I've been actively trying to force trigger an error log entry somewhere, nothing so far... cool beans

**Comment by illori** [comment]
mention from quick reply works fine on my install.

**Comment by illori** [comment]
for the first issue, line 942 in EmailTemplates.english.php should be

```
$txt['msg_mention_body'] = 'Hello {MEMBERNAME},
```

it was {MENTIONNAME} which is wrong.

**Comment by Oldiesmann** [comment]
Mentioning might take a bit because all alerts are handled via a background task rather than being done instantly. Still, the task should run at some point within 30 minutes.

**Comment by bperry921** [comment]
Glad I didn't close this yet, need to add something, a question... glad the original post is fixed but noticed something else with mentions... is anyone else getting this? When i mention someone it sends the email all cool now, but if i edit the topic that the mention was executed in and remove that mention... the system continues to attempt sending that same user a notice, it keeps popping up in the queue even if i remove the mention and reset the user its sent to so that they DO NOT receive any notices??

**Comment by illori** [comment]
IMO that is a separate issue from what you started this with. i would close this and open a new issue so we can keep things separate.

**Comment by bperry921** [comment]
yea i think you're right, stand by
