### ISSUE TITLE
advertised feature not functioning?

### ISSUE THREAD

**Issue by bperry921** [SimpleMachines/SMF#2679]
just noticed someone on my production site, also 2.1, viewing the help page... so drilled down through where that goes out of curiosity and discovered that at least one of the advertised features isn't functioning in latest 2.1, confirmed by non-production testing "clean" site... when a user hovers cursor over topic subject line in message index its suppose to preview topic, nope there's nothing, the hover on poster name works fine though, cool

will check some of those other advertised features in a few minutes...

**Comment by illori** [comment]
on admin -> forum -> posts and topics do you have a value greater then 0 in maximum length of last/first post preview? if it is 0 it is disabled.

**Comment by bperry921** [comment]
Ah yes, thank you. That is it...

**Comment by bperry921** [comment]
I will post this question in the support forum so the others will see it too... probably should have started there...

**Comment by illori** [comment]
can you go ahead and close this issue then?

**Comment by bperry921** [comment]
sure
