### ISSUE TITLE
reply to topic that is not approved

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2681]
in 2.0 and i assume still in 2.1 if a reply is made to an unapproved topic there is really no notification to the person that started the topic or those that replied that a reply has been made. anyway we can try to work around this so replies are known if they have been made?

**Comment by live627** [comment]
What do you think should happen? An alert/email? Should the notifications end once the topic has been approved?

Do such topics not appear in the unread list actions?

**Comment by illori** [comment]
Alert or email would work. Yes the alert would disable when approved unless
the user has requested otherwise. They do partially end up on the unread
list... The reply that is not approved will show for all at least in 2.0.
It should not. Not everyone uses the unread list so may miss the replies.
Also board index shows no replies to the board, maybe a performance issue
there.

Semi related, if you don't get email about unapproved topics/posts you may
never know that more than one topic/post exists.

**Comment by live627** [comment]
> Semi related, if you don't get email about unapproved topics/posts you may never know that more than one topic/post exists

Added in #2739
