### ISSUE TITLE
tempImage.src

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2683]
tempImage.src = '/github2.1' + "/cron.php?ts=1421534670";

i think the + is not necessary in this location.

**Comment by Oldiesmann** [comment]
It's weird string concatenation, but it is necessary.

```
        tempImage.src = ' . JavaScriptEscape($boardurl) . ' + "/cron.php?ts=' . $ts . '";
```

**Comment by illori** [comment]
Why is it necessary?

**Comment by Arantor** [comment]
It's done that way to curtail bot scraping and adding old timestamped cron requests to the index (which would be hit forever more even though not actually desired or honoured, meaning more server load than necessary)

This first came to light years ago with the old method that was used for handling the pageindex links that got added in JS where they had %msg_id% placeholders (at least I think that was how it was done in 1.1) and this kept getting scraped by bots and generating 404s.
