### ISSUE TITLE
Suggestion? just wondering about alert settings

### ISSUE THREAD

**Issue by bperry921** [SimpleMachines/SMF#2684]
I notice that initially most of the profile settings in notifications are off, and I am curious whether there are any plans to have an easy way to set default values for these on new registrations?

**Comment by Oldiesmann** [comment]
It's definitely doable - just something we haven't gotten around to adding yet. I'll look into this when I'm done working on redirection topic stuff.

**Comment by bperry921** [comment]
Take your time & get on more important stuff, I know how busy you must be, this can wait...
