### ISSUE TITLE
Renewal of subscriptions should have a different cost

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#269]
It would be really useful if admins could specify a different cost when a member wants to renew their subscription than when a member is going to get one for the first time. That would encourage people to keep paying for the same service.

I've no idea of how to mark this as a feature request.

**Comment by colinschoen** [comment]
I'm sorry I can't understand what you mean by this -> "This encourages people to update and to know that they money is no lost, that they actually earn something for pay before the new people,"

**Comment by ghost** [comment]
In other words: People who already paid would be encourage to renew as the price is lower than the price set for people who is paying the subscription for their first time.

**Comment by colinschoen** [comment]
So you are suggesting adding the ability to have a onetime initiating fee when starting the subscription?

**Comment by ghost** [comment]
I'm suggesting one fee for initial subscription and another fee for renewal of subscription

**Comment by colinschoen** [comment]
Exactly so there wouldn't need to be two additional values, only one, the additional initiation cost. The subscription cost stays the same; the initiation fee is just added on top of that for the first payment.

**Comment by ghost** [comment]
That would be a good alternative too

**Comment by colinschoen** [comment]
I could definitely see that being useful. Let's see if anyone else wants to give the thumbs up or down. Either way I am going to take a peak at the paid subscription code and get my bearings and see if I can pump out a commit.

**Comment by joshuaadickerson** [comment]
Make a mod of it first. This shouldn't go into 2.1 at this point

**Comment by Oldiesmann** [comment]
I can definitely see it as being useful as well, but before we decide one way or the other we should at least look into it a bit more:

Which payment gateways support it? I'm fairly certain Paypal does.
How much work would be involved with adding this feature?

**Comment by ghost** [comment]
2CheckOut supports recurrent payments too, and almost all major vendors do it too.

**Comment by mikemill** [comment]
@NIBOGO do they support recurring payments at a different price point than the original?

**Comment by Oldiesmann** [comment]
It appears they do.

From https://www.2checkout.com/blog/knowledge-base/merchants/tech-support/recurring-charges/selling-recurring-products-with-2checkout/

> If you need to add a charge for any reason you can set a start-up fee, which will be added to your products price on
> the first billing only. This start up fee will only be charged at the initial purchase. Setting a $10 startup fee would
> allow you to bill your customer, for example, monthly for $20, but charge the customer $30 the first billing.

PayPal supports this in the form of an "InitialAmount" that you can set when defining the recurring payment profile.

**Comment by ghost** [comment]
At the moment SMF is only officially supporting PayPal, so there should not be any problem implementing this, in fact I think it is quite easy to implement. Just add a new field for each subscription with the initial fee, and use PayPal/2CO initialAmount/start-up to handle the rest

**Comment by Oldiesmann** [comment]
The only thing we have to deal with as far as implementing this is the interface stuff - how do we describe it, how do we make sure to let users know that it's optional and should only be used if they know what they're doing, etc.

We also need to do it in such a way that it won't mess up existing subscriptions.

**Comment by Arantor** [comment]
Actually there is a simpler way to handle this, if you think about it, and in a way that doesn't mess up existing subscriptions and works cleanly across all payment gateways.

Just set it up so that subscriptions also have a group access level, i.e. configure which group or groups can purchase a subscription. The main subscription grants access to a premium group, renewals can only be purchased while you are in that group, job done. It may not be as elegant but it is absolutely stable and backwards compatible.

**Comment by ghost** [comment]
Bad idea. You'd need two groups for each subscription (awful) and you would need a way to handle members that paid, let the subscription expire and later want to renew it. I totally disagree with that approach.

**Comment by Arantor** [comment]
No, you don't. You need two subscriptions, one group.

Subscription 1, open to regular users, adds user to Premium Group
Subscription 2, open to Premium Group, adds user to Premium Group

And in almost every situation, if the subscription has lapsed, they wouldn't be able to get a cheap renewal anyway.

**Comment by ghost** [comment]
People on premium group would see both unless you also implement a Deny permission, and you are wrong there, must websites I visit allow you to renew your subscription after expires to respect their previous purchase. Overall it seems like a really bad implementation, I simple first time fee would work a lot better.

**Comment by Arantor** [comment]
You go to very different places to me, then, I have yet to see anywhere that allows a cheaper renewal without an existing subscription.

And yes, doing it this way would require a deny but that's not exactly a challenge.

Seriously, though, don't like what I'm suggesting? Fine: you want it done a certain way, go ahead and write it, and I'm sure the community will be grateful. It would also be nice if you would supply the 2CheckOut gateway you have on smfpacks.com, again I'm sure the community will be grateful.

**Comment by ghost** [comment]
Check IPB, vBulletin, Laneros.com, and I'm pretty sure a lot others do the same, and yes I don't like the way you proposed, and I think that as a dev instead of getting angry you should try to get as many feedbacks as possible.

**Comment by Arantor** [comment]
You're saying you don't like what I'm proposing, and you have the power to change that. There is little chance of this making it into 2.1 (because we have more important things to do) but as I said if you're dead set on it being a feature the way you think it should be, please do submit it. We're trying to concentrate on bug fixing in 2.1, not new features at this point in time, so instead of telling us how it should be done, you could contribute.

I didn't say what I was suggesting was how it should be done, simply an alternative that you don't like. (Incidentally, I'm trying to find the subscriptions system in IPB to be able to see how they do it, IPB 3.4 doesn't seem to have it as a built in feature... and vB 3 at least does it how I outlined, haven't looked at vB 4 or 5 yet)

If it were possible to leave someone in a group after the subscription ended (e.g. a Past Subscriber type group), even what you're asking for would be possible.

Let's ask the community, shall we?

**Comment by Kindred-999** [comment]
Actually, I like Arantor's suggestion
make the display of subscriptions like the board display
Determine which groups can see which subscriptions options.

That way, a 100 post count group could have a reduced price subscription, etc...

**Comment by ghost** [comment]
Those websites I posted were for reference about paying with a
discount without an existing subscription (but if the person had one that
already expired). I'm still concerned about the idea of having two
subscriptions for each one of the current ones, and I also don't think this
would be intuitive for admins either as a new group would be required for
past subscribers. Arantor's idea would be good for somethings, but I don't
really think it's the best solution for this problem.

**Comment by Arantor** [comment]
Then you go build it and then show me when you're done.

**Comment by ghost** [comment]
LOL you must be drunk or something if you think I'll do what you ask me to.
Happy xmas btw :)

PD: it's still a bad approach.

**Comment by Arantor** [comment]
I'm not drunk. I'm just highlighting what you're doing, telling me something is a bad idea but you don't dislike it enough to actually do something about it. It is much easier to complain than to actually contribute, of course.

**Comment by Xarcell** [comment]
Being someone who offers web hosting, I've seen plenty of renewels being cheaper than the initial subscription. I'm sure it would be desired in SMF. As someone who sales subscription services, I like being able to offer a a reward to subscribers who are renewing, but lowing it's rate.

Like NIBOGO says, I think there should be an initial fee for when you first subscribe, then an option for a lower fee for renewals. Although, I think Arantor's method would work too, but is undesired.

The thing I find strange, is that NIBOGO is fully capable of coding this himself and contributing it to SMF via Github. Why request someone else do it? Although, if I had to guess, I would say that if NIBOGO would code it himself, he would charge for it.  I can only hope he's willing to contribute to the community.

**Comment by Arantor** [comment]
No, he's not.

**Comment by ghost** [comment]
Yeah, I can do it, in fact I'll as I need it, but if isn't going to be
accepted I can't see the point of it, I'm also contribuiting to the
community giving feedbacks and mentioning possible features (this is an
example) as it would help other not just myself. I don't even care if you
implement it or not, I already did my part bringing this issue here.

**Comment by ghost** [comment]
I also tried to help joining the development team and even asking for a
return to the customization one, both were rejected so I cannot see how I'm
"not able to contribute".

**Comment by Xarcell** [comment]
I can understand not wanting to do the work, if it's not going to get approved. Been there already with some graphics. However, your doing to do it anyway as you said you need it.

Sorry to hear about your rejected request to the team. Most likely, there was a good reason for it. Although, that doesn't mean indefinite, so perhaps at a later time.

**Comment by XinYenFon** [comment]
Just because you refused from the team, doesn't mean you can't contribute anymore... You can fork SMF2.1 and work on it, then send PR and our dev team can consider it. Its that simple ;)

**Comment by Arantor** [comment]
Yup, if a PR is submitted, we'll review it regardless of who contributes it. Don't need to be a team member to contribute. But we do have standards that we expect to get followed.

**Comment by ghost** [comment]
I don't see the point of doing that if the team don't want me there. I
won't code for someone that doesn't think I can join them.

**Comment by Arantor** [comment]
Which suggests to me that your reasons for trying to rejoin the team are not for the betterment of the project.

**Comment by ghost** [comment]
I'd like to see you doing something for soneone who rejected you twice :)

**Comment by XinYenFon** [comment]
I don't think the topic here is "doing something for someone who is rejected you" i think the topic should be "why I'm rejected". Its better to look at yourself before trying to _blame_ people or project(s).

I don't want to go off-topic here but nvm... I don't see any mid way with you from now on truly sorry to say that...

**Comment by Arantor** [comment]
Are you honestly surprised that you were rejected with this attitude?

If you genuinely wanted to better SMF, you'd be willing to contribute. Makes me think you're only interested in a badge to help your mod sales.

**Comment by ghost** [comment]
I won't contribute in anything different than feedbacks and ideas, as I
already did it here I guess there isn't much else to be done here.

**Comment by Arantor** [comment]
Indeed.

**Comment by Dababi** [comment]
All of this for a feature request.

> Yup, if a PR is submitted, we'll review it regardless of who contributes

Thats not the 100% case at all, for xmp. you do not have reviews done on your code, you just demand it of others.

> Are you honestly surprised that you were rejected with this attitude?

Funny coming from someone who put down SMF and its members for YEARS, purposely trying to hurt and drive others away.  Maybe at one point you, in your mind, thought you were helping, but long ago it became ugly since you did not get your way.  The SMF project would be in much better shape if you have never ever shown up at the site.  There was no reason you should have been allowed back on team if the same standards were applied to you.

> Which suggests to me that your reasons for trying to rejoin the team are not for the betterment of the project

You only contribute because you do not have to answer to anyone, no reviews no input  You can't work on a team and few are willing to put up with you.  This is not unique to SMF, your history of project and personal attacks is well documented, just use Google.  Here your involvement is 100% about your ego because you could not get your way / were not worshiped enough on your last project.  Don't ask us to believe you are here for project betterment, you don't care about the project or others.

**Comment by ghost** [comment]
I fully agree with above post, Arantor is not even near to a team member, personally I was not surprised when he wasn't able to finish Wedge, I was expecting that as working with him must be painful and trying to do something against his way of thinking must be really hard. This is a perfect example, closing a feature request and not even asking others or waiting additional replies just because he thinks he has the answer. I really hope SMF can live even with someone like him in their team.

**Comment by LiroyvH** [comment]
May I remind everyone that this is certainly not the place to make unfounded accusations, especially when said attacks are based on ill informed nonsense? Please keep it clean, we're not interested in trolling. Thank you in advance...

**Comment by Xarcell** [comment]
Way off topic. Please close.
