### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#2690]
This is just a reminder of stuff I've noticed while working on mods, a reminder for myself so I don't forget about them:
- Some hooks do not pass enough info or are located on an inconvenient place. Some can be split into two, before and after the event. 
- The "after" event hooks does not need to pass the values by reference since the event has already occurred. Might break a couple of mods but its an easy fix anyway.
- Add some doc blocks.  At least in the functions most commonly used by mod authors. 
- Make the avatar on the profile menu on the top click-able. For consistency and because it can be annoying having to click on a small link to go to the user's profile, specially if you use that menu constantly.

**Comment by MissAllSunday** [comment]
As per this http://www.simplemachines.org/community/index.php?topic=532796.msg3786474#msg3786474

Need to fix the based on stuff

**Comment by Oldiesmann** [comment]
I actually have an older copy of 2.1 where I added docblocks to everything. I just need to copy all the docblocks to a current version as that version has merge conflicts.

**Comment by bperry921** [comment]
I've noticed also that an upgrade.php  run doesn't keep the old set of "date/time" formatting setup properly, it keeps lopping off the last few characters where i put the :%S, it keeps the front ones fine where i added %a, however...

**Comment by bperry921** [comment]
Just a suggestion but I'd also like to see a "Go Down" button in the header just like the corresponding "Go Up" button in the footer... would be very handy for long pages such as posts with a lot of replies and if there's a lot of boards in the index page listing...

**Comment by illori** [comment]
IMO your last 2 comments here should be separate issues as they dont relate to what MAS wants to do. if you want a go down button you can always add one or look for a theme that has one. i dont really see the need for it in the default theme.
