### ISSUE TITLE
forgot your password email reset

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2691]
https://github.com/SimpleMachines/SMF2.1/commit/ed439823221286a3631e110f774b5be1e937334e

@Oldiesmann tried to fix this in the above commit. i still can not get the email to be sent. nothing in the error log related to this. the email does not appear in the mail queue.

**Comment by illori** [comment]
this is using the link from the login page for forgot your password

**Comment by bperry921** [comment]
Here's what I find in my testing of this issue... on mine the password reminder is not sending either... but related possibly is another issue related to email, on my site the registration email is indeed being sent to proper address, and the activation link functions correctly, however, the "From" address in the header reads web@missing_domain on that email... hope this is helpful

**Comment by illori** [comment]
seems we need to use sendmail to get the mail to send...

around line 141 in reminder.php

```
$emaildata = loadEmailTemplate('forgot_password', $replacements, empty($row['lngfile']) || empty($modSettings['userLanguage']) ? $language : $row['lngfile']);
// Then send the actual email.
sendmail($row['email_address'], $emaildata['subject'], $emaildata['body'], null, null, false, 1);
```
