### ISSUE TITLE
required custom profile fields on registration

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2692]
there is nothing that lets the user know that a field is required on the registration form. you get an error after you submitted the form, but nothing ahead of time to tell you a field is required.

**Comment by MissAllSunday** [comment]
If a custom field is marked as required then it will show inside the "Required Information" block on registration.

If not the custom field will be printed on the "Additional Information" block.

**Comment by bperry921** [comment]
Confirmed, works great, but I would suggest adding the word "Unrequired" in front of the section title "Additional Information" in the language file...

**Comment by illori** [comment]
this is a required field on the registration form in firefox 35.0.1 there is nothing that shows it is required.
![](http://imagizer.imageshack.us/v2/773x74q90/673/Edwzcc.png)

even though it is in a section that says it is required information, it is still not apparent it is required when looking at the field. people will ignore the headers for the sections and look for some sign that says means it is required.

**Comment by MissAllSunday** [comment]
Yes, its the same on Opera and IE, that field is included within the "Required Information" block.

I honestly don't know whats better than that. Been inside the "Required Information" block means that field IS required.

**Comment by illori** [comment]
maybe a red \* as that means required in other online forms.

**Comment by MissAllSunday** [comment]
Then the whole "Required Information" block becomes redundant.

**Comment by illori** [comment]
somewhat, but i think we may see an increase in people not seeing the required fields even if they are in that block. i guess we could wait and see if we see people asking for this and go from there.

**Comment by Oldiesmann** [comment]
If people don't understand that a field inside a "required information" box is required, adding redundant indicators likely won't help.
