### ISSUE TITLE
drafts.english.php version string

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2700]
the version string in this file reads // Version: 2.1 Beta 1; Profile it is not the Profile language string page, as a result it does not show a version in the detailed version check

```
// Version: 2.1 Beta 1; Drafts
```

that seems to make it show up in the list.

**Comment by MissAllSunday** [comment]
I incidentally fixed this while working on removing unused globals from language files

https://github.com/MissAllSunday/SMF2.1/commit/7afa550e351b12ee82435ffd2882e3bbc331f3c8
