### ISSUE TITLE
Issue with child-boards display when having posts or not

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#2710]
As reported here
http://www.simplemachines.org/community/index.php?topic=533020.0

This can easily be reproduced:
_Parent board
*_ Child
**\* Grand-child 1
**\* Grand-child 2
(everything with no posts)
You create a topic in Grand-child 1, then go back to "Parent". Grand-child 1 disappeared as child of "Child"
You create a topic in "Child", everything is back in place :)

**Comment by XinYenFon** [comment]
I can't reproduce this. If I'm not mistaken, this should be board structure, and post needs to made to Grand Child or 2

![screenshot-localhost 2015-02-03 05-18-38](https://cloud.githubusercontent.com/assets/1669995/6013940/55bd6f46-ab64-11e4-8dbb-f98776e7da7b.png)

**Comment by Emperornero** [comment]
Hi, I'm the one that originally created the bug report.

In order to reproduce the bug, there must be a post in the Grand Child board, but no posts in the Child board.  This causes the sub-board listing while viewing the Parent board to not display the Grand-Child  board that has a topic in it in the sub-board listing, however the Grand Child with no topics will still be displayed.

Examples can be found with explanations at the following addresses:
http://98.145.133.152/index.php?board=57.0
http://98.145.133.152/index.php?board=60.0
http://98.145.133.152/index.php?board=67.0

**Comment by margarett** [comment]
@Antes, that's the structure. Now go into your "Parent" board. You'll see "Child", and that having 2 sub-boards. As it should.
Now go and create a post in "Grand Child". Then come back to "Parent". Grand child disappeared from "Child", Grand Child 2 is still there ;)

**Comment by XinYenFon** [comment]
No, Grand Child still there.

See: http://next.mmobrowser.com/index.php?board=15.0

**Comment by margarett** [comment]
How strange... To me it disappears :scream:

**Comment by XinYenFon** [comment]
Are you sure you both are on latest build ? @margarett @Emperornero

**Comment by margarett** [comment]
Yes, the test was made on yesterday's zip and I downloaded it again before replying. Although I just overwrote the files. Were there any database changes?

**Comment by Emperornero** [comment]
This is very odd.

The only reason I posted the bug report was because this occurred on multiple installs with builds downloaded weeks apart.

Perhaps the bug is not directly related to SMF, but something with wampserver?

**Comment by XinYenFon** [comment]
I'm running WAMP 2.5 (probably same as your version @Emperornero ). There should be? dunno :P I always run upgrade.php after build updates but weird :P

**Comment by margarett** [comment]
I am running latest XAMPP with PHP 5.6 and MySQL 5.6.21 btw

**Comment by XinYenFon** [comment]
This shouldn't be related to PHP MySQL since I'm using the same PHP version with reporter.

-----Original Message-----

**Comment by margarett** [comment]
I found the problem, but I don't know if the fix is proper...

It's in Subs-BoardIndex.php, in the first query where the child info is fetched...
If there are no posts in grand-child 1/2, then the child rows are fetched sequentially. So, while looking at MessageIndex from "Parent", the following boards are fetched, by order
Child
Grand-child1
Grand-child2
And everything is in place.

Now, when one of the grand-childs has 1 post, this order fails. Eg, post in Grand-child 1, now this is the fetched order
Grand-child1
Child
Grand-child2

Then, in the massive while loop that follows this query, the first board analysed is Grand-child1. There is no valid "parent" for it so it seems to be discarded.

If I add a
ORDER BY b.board_order
Everything seems to be in place :laughing:
