### ISSUE TITLE
board #1 missing?

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2712]
on the topics maintenance page board # 1 is missing from the specific boards expanded area for remove old posts, it is also missing from the move topics drop downs at the bottom of that page.

@Oldiesmann was looking at the top part last week.

**Comment by margarett** [comment]
This is somewhat related to #2710 
The board #1 _IS_ retrieved by the query but it is lost in the while loop after.

Again, add a ORDER BY b.board_order fixes the issue...

**Comment by margarett** [comment]
Been lurking around this a bit more. It seems awkward indeed but not only for this reason...
Now I can't really find where in the code the logics fail :(

My current boards layout is (damn markup!!!):

```
- Cat2 (id_cat=2)
-- Parent board (id_board = 3)
--- Child board (id_board = 4)
---- Grand child 1 (id_child = 5)
---- Grand child 2 (id_child = 6)
- General Category (id_cat = 1)
-- General Disciussion (id_board = 1)
-- New Board 1 (id_board = 2)
```

And this is now Topics Maintenance shows up
![img1](https://cloud.githubusercontent.com/assets/5584935/6052137/225be902-acc7-11e4-8d9c-261f861aceb8.png)
