### ISSUE TITLE
new issue with mentions, could be affecting other email features too, not sure yet

### ISSUE THREAD

**Issue by bperry921** [SimpleMachines/SMF#2714]
need to add something, a question... glad the original post I made about mention's emails is fixed but noticed something else with mentions... is anyone else getting this? When i mention someone it sends the email all cool now, but if i edit the topic that the mention was executed in and remove that mention... the system continues to attempt sending that same user a notice, it keeps popping up in the queue even if i remove the mention and reset the user its sent to so that they DO NOT receive any notices??

Sorta related maybe, I've also noticed that it takes forever for anything (any feature where it notifies me personally) being emailed to me to arrive, and certain ones that I expect to get never arrive... however the actual system response times are pretty good for most everything I test, so far...

and vice versa, as an admin, if some feature i test notifies my fake user accounts, those emails arrive lickety split, no problem...

**Comment by bperry921** [comment]
Update: Looks like email is fine... but still question what's happening with mentions, will continue to dig deeper...

**Comment by Dragooon** [comment]
If a user is mentioned and then removed, it won't stop the mention from being sent. That's by design, it'll be kind of hard to override that. Are you receiving multiple mentions though?

**Comment by FearThe1337** [comment]
Any news on this? Is this validated yet, or any other updates?
