### ISSUE TITLE
IMO I would like to see...

### ISSUE THREAD

**Issue by bperry921** [SimpleMachines/SMF#2716]
Just a suggestion, but for "consistency sake" mostly, I'd also like to see a "Go Down" button in the header just like the corresponding "Go Up" button in the footer... would be very handy for long pages such as posts with a lot of replies and if there's a lot of boards in the index page listing...

yea yea I am capable of adding it myself, but why should i have to do that? If structured exactly the same as the up button, its soooo un-intrusive, just saying...

**Comment by illori** [comment]
i really dont see a use for a go down button, if you really want one it is not too hard to put it in your own custom theme or find one that may have it.

also i dont see anywhere in the header where it could possibly go.

**Comment by XinYenFon** [comment]
+1 illori

**Comment by illori** [comment]
also a go down button would not put you at the bottom of the page, you would have the footer at the bottom of the screen but you would not actually be just looking there, there would be a ton of other stuff above the footer you would see first. the go up option works fine because you end up with the header at the top of the page, you cant do the same with the footer.

**Comment by Arantor** [comment]
There used to be one for consistency, I don't know when it was removed.

**Comment by illori** [comment]
looking at several old installs even back to 2013, i dont see a go down button in the header.

**Comment by bperry921** [comment]
Ok, so let's forget the terminology confusion, whatever the area is coined, up where the welcome area is it should be a really easy task to put in, I haven't checked yet just what would be involved, but i do know that I may have to buy a new mouse soon as I'm wearing the hell out of the scolling thumb wheel, not to mention my arthritis is uncomfortable with so much use of the thumb wheel too...

**Comment by BitFros7y** [comment]
As far as i know that is a feature you need to enable...(at least in 2.0...) I rely dont remember where it is but im 100% percent sure 2.0 has these (and i dont see a reason for 2.1 not to have these)

Try checking look and layout as many handy things are there

**Comment by illori** [comment]
yes 2.0 has go up/down buttons on a topic view. 2.1 has that as well but it can not be disabled like it can in 2.0.

this is not what is being requested though.

**Comment by smfbigguy** [comment]
There is a mod that does this very nicely.
