### ISSUE TITLE
Top menu mini avatar disallows opening profile drop

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2721]
I noticed that before with using Font-Awesome in my theme, but with normal avatar image (img tag) I can also reproduce it. If you put an avatar on your account and try to click on it at top-bar, its not opening the drop-menu.

**Comment by Oldiesmann** [comment]
No idea why it's doing that but it's something we can look into. It happens on my test board as well (so it's not related to Font-Awesome at all).

**Comment by live627** [comment]
f74825d084594483df675160c880ef9cf20fccc3

EDIT: Nope different issue.
