### ISSUE TITLE
Moderation checkboxes

### ISSUE THREAD

**Issue by BurkeKnight** [SimpleMachines/SMF#2725]
When set to see moderation as checkmarks, only the first topic has the box, and no others.
![checkboxes](https://cloud.githubusercontent.com/assets/4885967/6182177/7c69fb00-b30c-11e4-92b9-e05fdbfd74fc.png)

**Comment by illori** [comment]
they all show for me.
![](http://imagizer.imageshack.us/v2/131x596q90/910/FPtX4h.png)

what browser are you using? admin user or moderator? even a user that is not a moderator of a board i checked can see the checkboxes.

**Comment by XinYenFon** [comment]
What is your resolution?
