### ISSUE TITLE
PostgreSQL Native Fulltext Search

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#273]
It might be a bit late in the development to implement this, but it's definitely something we should consider. As of version 9.0, PostgreSQL has native support for full text searching.

From the original entry on Mantis ( http://dev.simplemachines.org/mantis/view.php?id=4657 ) :

> On a moderately large forum, the custom search index does not work well -- it literally takes weeks
> to construct, and the resulting index is an order of magnitude larger than the original messages,
> and takes so long to search that just doing a brute search can have better performance. It would 
> greatly benefit Postgresql database users to have a native full text search index (documentation
> here http://www.postgresql.org/docs/9.0/static/textsearch.html)

**Comment by emanuele45** [comment]
What would be needed?
Complete PSQL noob here...I know how to set it up and use it a bit for debugging, but not much more.

**Comment by Oldiesmann** [comment]
We'd simply need to create another file containing the appropriate queries for the fulltext search (like we have one for fulltext in MySQL), then modify the SMF code (if necessary) to detect whether or not it's possible. The documentation linked to above gives some good examples about setting it up and searching, though it's still somewhat complicated.

**Comment by jdarwood007** [comment]
Oldies,
Would this be able to make any beta of 2.1?  Your the native PostgreSQL user and know the most about it, so implanting it would be the easiest for you to do.

**Comment by Oldiesmann** [comment]
I've looked at the manual info on fulltext searching and don't have a 
cluewhere to start. Postgres' implementation is much different than 
MySQL's. However, Tinoestsaid he's worked with it and is going to look 
into it for us.
Michael "Oldiesmann" Eshom
Christian Oldies Fan
Cincinnati, Ohio

**Comment by tinoest** [comment]
I don't run a forum large enough to test the performance benefits of switching to this searching , however do we wish to create your own index's and if so would you prefer a GiST or a GIN? The following link explains it better than I could http://www.postgresql.org/docs/8.4/static/textsearch-indexes.html , the other option is just using the default full text engine and not creating any index as an addition to that.

**Comment by Oldiesmann** [comment]
Based on what's outlined there, I think a GiN index would be better, particularly due to GiST producing false positives.

**Comment by Arantor** [comment]
This would also mean bumping the minimum PGSQL version from 8.0 to 9.0, though I presume that's not a problem here?

I am concerned at the amount of work this would generate this late in the 2.1 day.

**Comment by tinoest** [comment]
Full text search is available in pgSQL version 8.4 I believe. Not sure what version it was released in mind. 9.0 Does has some additional features over 8.4.

**Comment by Arantor** [comment]
That's still above our current minimum of 8.0. But I know how small the PGSQL userbase is for SMF (very tiny, probably only just in double-digits of users), so if we do want to run with it, I don't expect that to be a huge issue, but I am concerned at the workload for such a small relative pay-off.

**Comment by Oldiesmann** [comment]
My plan was to just code it such that SMF will only show it as supported if you're on a version of Postgres that supports it. I'm not sure we can safely bump the minimum version because CentOS 5 is still on PostgreSQL 8.1 (CentOS 6 is on 8.4 now).

**Comment by Arantor** [comment]
That works, the search API does support that sort of thing.

**Comment by shawjef3** [comment]
Postgresql 9 is available for CentOS 5 and 6 from the official postgresql yum repository http://yum.postgresql.org/repopackages.php

**Comment by Oldiesmann** [comment]
Unfortunately what's available directly from PostgreSQL and what's available through official CentOS channels is different. Our search API provides options for specifying a minimum required DB version, so simply specifying that it won't work on anything older than 8.4 is pretty simple.

**Comment by Oldiesmann** [comment]
@tinoest Have you made any progress on this?

**Comment by tinoest** [comment]
I started and then life took over I'm afraid. I'll try and allocate some time to this, but I can't promise anything. If someone else wants to take it on ( as they thought i was ) then feel free.
