### ISSUE TITLE
Package Manager --> White page

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#2737]
Subject says it all. Trying to open PackMan returns a white page (after some seconds "Waiting for localhost), nothing in SMF's error log, nothing in PHP's log

**Comment by smfbigguy** [comment]
I did get one error on the white screen:

Fatal error: Maximum execution time of 60 seconds exceeded in /home/****/public_html/community/Sources/Class-ZipExtract.php on line 264

**Comment by smfbigguy** [comment]
Was just playin around with this and I commented out these lines in Class-ZipExtract.php below line 262 and I am in the package manager now.

```
        //$buffer = '';
        //while (!feof($this->zip_fd))
            //$buffer .= @fread($this->zip, 8192);
```

Not sure if this means anything to anyone but I thought I would post it.

**Comment by live627** [comment]
It probably means support for ZIP files is broken. >.<

Replace that commented code with `$buffer = @fread($this->zip, $file_size);` and let me know what happens.

**Comment by margarett** [comment]
$buffer =
OR
$buffer .=

:question: 

BTW: wasn't that the purpose of this class, to handle zip files? :tongue:

**Comment by live627** [comment]
No dot

**Comment by smfbigguy** [comment]
Works good here. I can get to the package manager and no errors in the logs. Almost every package has a modification parse error though but at least getting to the package manager with out error is doable.

**Comment by live627** [comment]
Looks like the library won't read PHP files, while other formats are okay.
I don't understand what's going on... @Arantor can you provide some insight?

**Comment by smfbigguy** [comment]
I did get one package installed but that was it.

**Comment by illori** [comment]
i reported some of this here https://github.com/SimpleMachines/SMF2.1/issues/2730

**Comment by margarett** [comment]
Yeah, it's probably the same issue ;)

**Comment by smfbigguy** [comment]
What file is it that is responsible for parsing the modification. I was thinking maybe a mistake was made in it or something.

**Comment by live627** [comment]
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Package.php

**Comment by smfbigguy** [comment]
That is what is used before the package actually gets installed ? What I don't get is why I can get one mod installed but nothing else. Tbh, I have no idea what I am lookin for, I'm just tryin to throw out ideas that's all.

**Comment by smfbigguy** [comment]
well I have more than one mod installed now...I have two, lol. Also, not that I was going to find anything in that file you linked me to and I didn't I just wanted to take a look and was throwing out ideas and such.  :)
