### ISSUE TITLE
Are you really sure you want to delete old posts now?\n\nThis cannot be undone!

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2744]
in the text above the \n\n should not show in the popup.

**Comment by MissAllSunday** [comment]
ugh, I'm afraid we will have to either enter a pseudo tag and do a .replace() or just remove all the \n on those language strings.

**Comment by MissAllSunday** [comment]
OK, I just found out an equally hackish method:

$txt['maintain_old_confirm'] = 'Are you really sure you want to delete old posts now?' . "\n\n" . 'This cannot be undone!';

This means passing the literal character, as in, literally a new line char.

**Comment by MissAllSunday** [comment]
So, @Oldiesmann what should we do? a pseudo tag or use PHP's weird behavior to literally print a new line?

**Comment by Oldiesmann** [comment]
Is there any advantage to using the pseudo tag, other than the whole weird concatenation with double quotes thing?

**Comment by MissAllSunday** [comment]
Nope it will only serve to tell jquery to replace it with an actual new line when the message is going to be displayed, saving us the need to display the actual new line on the HTML source.
