### ISSUE TITLE
undefined index

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2746]
Undefined index: draft_save_warning
github2.1/index.php?action=post;board=2.0
File: F:/wamp/www/github2.1/Themes/default/Post.template.php
Line: 128

 Undefined index: draft_saved
github2.1/index.php?action=post;board=2.0
File: F:/wamp/www/github2.1/Themes/default/Post.template.php
Line: 127

**Comment by margarett** [comment]
What were you doing to get that error? I can't seem to be able to reproduce it...

**Comment by illori** [comment]
when making a new post. with a non-admin user.

**Comment by margarett** [comment]
Nop, nothing here yet :(

**Comment by illori** [comment]
strange, maybe my localhost was playing tricks on me with this and my other bug i reported with approval.

**Comment by Oldiesmann** [comment]
Those strings are both in the Drafts language file, but it appears that file is never loaded anywhere in the posting process, so that's why.

**Comment by Oldiesmann** [comment]
Does this fix it at all?

Sources/Post.php

Find

```
    loadLanguage('Post');
```

Add after that

```
    if (!empty($modSettings['drafts_post_enabled']))
        loadLanguage('Drafts');
```

**Comment by illori** [comment]
that does seem to fix it.
