### ISSUE TITLE
new topics not set unapproved

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2747]
if you have a board/group set to have posts hidden until approved, they get the message on the post screen but the message is posted as approved.

**Comment by illori** [comment]
same applies for replies that should be hidden, they are shown as approved when posted.

**Comment by live627** [comment]
Right, it works fine when I try it. Are you sure that you set the board
permissions correctly?

**Comment by illori** [comment]
strange it works now, but did not before... all i changed was from a profile to the default profile.

**Comment by illori** [comment]
i see the issue, the user that made the post that is unapproved gets no visual notice that the topic is not approved on the message index. in 2.0 they did see (awaiting approval) in 2.1 there is nothing at all.

**Comment by margarett** [comment]
Got it :)
Submitting a PR ;)
