### ISSUE TITLE
Notice: Undefined offset: 0 in ...ManageScheduledTasks.php

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2752]
Notice: Undefined offset: 0 in C:\wamp\www\kittenground\Sources\ManageScheduledTasks.php on line 118

Edit: Enable birthday mails in ScheduledTasks, maybe related to #2753

**Comment by margarett** [comment]
True. You don't even need to enable anything, just click save and the error pops...

edit: well, this is enough to fix the error

```
        //list($task_disabled) = $smcFunc['db_fetch_assoc']($get_info);
        $row = $smcFunc['db_fetch_assoc']($get_info);
        $task_disabled = $row['disabled'];
```

**Comment by MissAllSunday** [comment]
remove_redirect is a new scheduled task and it was added recently so the error could be related to your installation missing that row in the scheduled_tasks table.

**Comment by MissAllSunday** [comment]
Oh, nevermind, it looks like I'm confusing scheduled tasks names.

**Comment by MissAllSunday** [comment]
Remove the list() should be enough but for some servers casting the var as int and declaring $task_disabled are also needed so:

``` php
        $task_disabled = 0;
        $task_disabled = (int) $smcFunc['db_fetch_assoc']($get_info);
```

**Comment by margarett** [comment]
I had the PR ready with my suggestion above but yours if better so up we go!
