### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in ManageMail.php

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2753]
Warning: Invalid argument supplied for foreach() in C:\wamp\www\kittenground\Sources\ManageMail.php on line 294

Notice: Undefined index: happy_birthday in C:\wamp\www\kittenground\Sources\ManageMail.php on line 316

**Comment by margarett** [comment]
No it is unrelated it seems. Looking into it, see if something comes up...

edit: got it. For some reason, $txtBirthdayEmails comes up empty... :open_mouth: 

edit2: got it. EmailTemplates.english.php needs to global $txtBirthdayEmails

**Comment by live627** [comment]
Question: Why use $txtBirthdayEmails? This is little better than $birthdayEmails, as it still isn't compatible with the language editor.

I also cannot view the issue mentioned in 43a7e709f2bd121993d5b941b3400cb48f809f87 because I'm not awesome enough to discover the reasoning behind that change.
