### ISSUE TITLE
Language install errors

### ISSUE THREAD

**Issue by BitFros7y** [SimpleMachines/SMF#2759]
Tried to install serbian latin utf8 language pack.
Page frozen during install and just timed out.
Here are errors i got (Every error is caused when trying to install language (total count 16) 

NegativeIQ
 Today at 03:35 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
8: fwrite(): send of 80 bytes failed with errno=32 Broken pipe  http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 867

 NegativeIQ
 Today at 03:35 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
2: strpos(): Offset not contained in string http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 940

 NegativeIQ
 Today at 03:35 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
2: strpos(): Offset not contained in string http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 940

 NegativeIQ
 Today at 03:35 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
2: strpos(): Offset not contained in string http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 940

 NegativeIQ
 Today at 03:35 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
2: strpos(): Offset not contained in string http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 940

 NegativeIQ
 Today at 03:35 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
2: strpos(): Offset not contained in string http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 940

 NegativeIQ
 Today at 03:35 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
2: strpos(): Offset not contained in string http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 940

 NegativeIQ
 Today at 03:34 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
8: fwrite(): send of 42 bytes failed with errno=32 Broken pipe  http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 867

 NegativeIQ
 Today at 03:34 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
8: fwrite(): send of 42 bytes failed with errno=32 Broken pipe  http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 867

 NegativeIQ
 Today at 03:34 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
8: fwrite(): send of 71 bytes failed with errno=32 Broken pipe  http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 867

 NegativeIQ
 Today at 03:34 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
8: fwrite(): send of 71 bytes failed with errno=32 Broken pipe  http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 867

 NegativeIQ
 Today at 03:34 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
2: strpos(): Offset not contained in string http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 940

 NegativeIQ
 Today at 03:34 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
2: strpos(): Offset not contained in string http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 940

 NegativeIQ
 Today at 03:34 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
2: strpos(): Offset not contained in string http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 940

 NegativeIQ
 Today at 03:34 am
 xxx.xxx.xxx.xxx
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
2: strpos(): Offset not contained in string http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 940

 NegativeIQ
 Today at 03:34 am
 79.143.111.150
 438ededf8ae5e4cf1645ad84bce45628
 Type of error: General
2: strpos(): Offset not contained in string http://mysite.com/index.php?action=admin;area=languages;sa=downloadlang;did=9327;d48e4c47=438ededf8ae5e4cf1645ad84bce45628
File: /var/www/Sources/Class-Package.php
Line: 940

**Comment by margarett** [comment]
I downloaded both Portuguese as well as Serbian and they both installed fine.
Are you using the latest version from here?

**Comment by BitFros7y** [comment]
Maybe im a few commits behind, when i say few i mean not more than 10...

**Comment by margarett** [comment]
Dunno, worked fine here, although there was a more-or-less-recent commit by @live627 that affects Package Manager and might help you.

In any case, you should update to the latest files when reporting an issue ;)

**Comment by live627** [comment]
Indeed.. 5379e463a390689c62b5596b4146fd97c68fe0d2 specifically fixes this.
