### ISSUE TITLE
2FA "Please wait for about 2 minutes before attempting to log in via 2FA again"

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#2761]
Trying to login twice with 2FA enabled in a short amount of time produces that error.

The problem is that the "Back" button sends you to the same page, therefore to the same error :tongue: 

Not a big problem on its own, it's just annoying.

**Comment by Dragooon** [comment]
It's to prevent brute force attacks, I'm not sure what you're asking?

**Comment by margarett** [comment]
Yeah it makes sense. But it's just that the "back" button goes to the same error until the 2 minutes are elapsed. Maybe no button or "cancel login"?
