### ISSUE TITLE
Change the order in the pm list and make the new ones more visible

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#2767]
I just realized that I missed a few pms on my site because the new pms gets added to the end of the list so everytime I clicked on the "my messages" link I saw the same pms over and over again as there is no visual indication that the new pm is listed at the bottom of that list rather than the beginning of it.

Would be nice if the new pms gets listed first and probably with some visual indication that there are indeed new, something that separates them from the rest of pms.

I also thought that there was a way to mark pms as unread but I cannot find that option.

**Comment by XinYenFon** [comment]
Maybe separate Unread / Read (as tabs) and add pm_unread class to td/div with different background.
