### ISSUE TITLE
drop down with value --------------------- can be clicked on

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2779]
why in the drop down in the moderation center for approving users to join a group is the second entry --------------------- ?

in other locations where this shows it is disabled so you cant click on it

```
<option value="" disabled>-----------------------------</option>';
```

but in Groups.php it is not disabled

```
<option value="0">---------------------</option>
```

this is similar in the issue warning page where it has

```
<option value="-1">------------------------------</option>';
```

you can still click on it and it does nothing.

maybe an option to just remove these as they are somewhat unnecessary?

**Comment by illori** [comment]
this does not fix the issue in profile.template.php

```
<option value="-1">------------------------------</option>';
```

**Comment by margarett** [comment]
Ups :tongue:

I'll fix the other one tomorrow ;)
