### ISSUE TITLE
Allow exclusion of a board(s) from public forum stats

### ISSUE THREAD

**Issue by srepetsk** [SimpleMachines/SMF#2783]
For some sites there may be both public and private forums, as well as forum stats enabled. I think a reasonable enhancement to SMF would be to add an option per-board in order to allow exclusion of the board from the overall forum stats in order for those boards to stay private. This could be a configuration option for the board, which the stats query then filters out when it runs. Several individuals solved this a few years ago by manually editing the SQL queries to exclude a particular ID (http://www.simplemachines.org/community/index.php?topic=236038.0), but that's neither scalable nor easy for the "average" person.

**Comment by MissAllSunday** [comment]
This might be better as a mod than as a core feature TBH.
