### ISSUE TITLE
Notice: Uninitialized string offset: 715 in ...\Sources\Subs.php on line 2048

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2787]
using latest build

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs.php#L2048

**Comment by margarett** [comment]
What were you doing? That line seems to exist for a long time.

**Comment by XinYenFon** [comment]
oh sorry :P just enable debug and navigate a page. you'll see it at header.

**Comment by margarett** [comment]
$db_show_debug? I have it enabled all the time... Don't see it :(

**Comment by illori** [comment]
i cant duplicate this either. i have db_show_debug enabled all the time as well and no errors related to this.

**Comment by XinYenFon** [comment]
Tried with fresh set of files. :/

![screenshot-localhost 2015-03-24 00-03-08](https://cloud.githubusercontent.com/assets/1669995/6791629/384955d0-d1b9-11e4-9a6f-96bc55fb39c0.png)

**Comment by illori** [comment]
what version of php are you using? 5.5.12 here.

**Comment by margarett** [comment]
@Antes, maybe you can try with a complete new install? Dunno, something missing in the DB or whatever...

Another thing: that error has to be related to BBCs. Do you have any custom ones?

**Comment by XinYenFon** [comment]
My php version: 5.5.12
@margarett Its a complete clean set of files & there is no integration hook left.

I'll close this because my other repo does not giving the same output. :( weird!
