### ISSUE TITLE
tfa error in upgrade.php 

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2789]
+++  Force 2FA per membergroup?Error in upgrade script - line 1758!
 done.
Error in upgrade script - line 1761!
 +++  Add tfa_mode settingError in upgrade script - line 1762!

Parse error: syntax error, unexpected 'TABLE' (T_STRING) in D:\wamp\www\github2.1\upgrade.php(2587) : eval()'d code on line 1

Call Stack:
    0.0100    1238656   1. {main}() D:\wamp\www\github2.1\upgrade.php:0
    1.1525    3344304   2. DatabaseChanges() D:\wamp\www\github2.1\upgrade.php:667
    1.1525    3348928   3. parse_sql() D:\wamp\www\github2.1\upgrade.php:1628

Error in upgrade script upgrade_2-1_mysql.sql on line 1770!
 done.
 Successful.

@margarett i think this is on you.

**Comment by margarett** [comment]
Most likely :tongue:

I seem to remember having tested that... Oh memory, why do you fail on me :)

**Comment by illori** [comment]
Because your memory likes to be forgetful? Haha
