### ISSUE TITLE
  Two-Factor Authentication enabled?

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2792]
i have not enabled this feature but on the cookies and sessions page the drop down shows "enabled". it should not show enabled if i have not selected it to be enabled.

why have a drop down when the only options are enable/disable? a checkbox could do that easily.

i did try to log in and i was not redirected to the config page for 2fa.

does the admin really need to setup their own account for 2fa before others can?

the text says "Please enable 2FA in your account in order to be able to force 2FA on other users!"

**Comment by Dragooon** [comment]
> i have not enabled this feature but on the cookies and sessions page the drop down shows "enabled". it should not show enabled if i have not selected it to be enabled.

It's enabled by default

> why have a drop down when the only options are enable/disable? a checkbox could do that easily.

It gives a third option to force 2fa when the admin has enabled it

> i did try to log in and i was not redirected to the config page for 2fa.

That's only when you're forcing 2FA

> does the admin really need to setup their own account for 2fa before others can?

Yes, this it to prevent admins from locking themselves out.

**Comment by illori** [comment]
Maybe some additional information would be useful. Right now if seems that
most admin will not know what this feature is or how it works.

**Comment by margarett** [comment]
I would say that it's more or less self-explanatory, if you know what you're searching for. And I would say that if the admin doesn't know what he's dealing with, he should leave 2FA disabled...

I do agree that this does require a wiki article ;)

**Comment by illori** [comment]
or maybe a help popup to explain a bit more? we could add a bit to the wiki but i would not say it is the first stop.

**Comment by margarett** [comment]
What do you think about this?
https://github.com/margarett/SMF2.1/commit/82d29533acda8f56106bb89cde0fd9171d06bfd6
(no PR yet, I think that it might require some "love" regarding proper English)

**Comment by illori** [comment]
looks good to me. that should help with this issue.

**Comment by ChainyEO** [comment]
I left a comment about the language: #2803
