### ISSUE TITLE
language drop down visible on phone

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2793]
with only one language installed [english] the language drop down should never show. it is visible on my phone.

@Antes can you look into this?

**Comment by XinYenFon** [comment]
I can't reproduce it :/ weird...

**Comment by illori** [comment]
Strange I went back and it is gone.

**Comment by illori** [comment]
Figured it out. Go to account settings then you will see it in the header.

**Comment by illori** [comment]
this also shows on desktop browser, if only one language is installed the drop down should not show anywhere.

**Comment by margarett** [comment]
Yeah, and it happens in more than one place, actually.
In admin, even if you have disabled the option to allow language change, the drop down shows up in some places.
IMO the code that triggers this is kinda "fragile"...
Basically any place that calls getLanguages() _AFTER_ Load.php calls it will have the drop down visible. I would say that we should remove the unset to $context['languages'] in Load.php and, index.template.php, use if (count($context['languages']) > 1) to show (or not) the dropdown...

edit: yeah, works fine like this, submitting a PR ;)
