### ISSUE TITLE
firefox 36.0.4 login fails with Session verification failed on first login

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2794]
on first attempt to log in you get Session verification failed error, try to log in again and no error and you get logged in just fine.

**Comment by margarett** [comment]
I still can't reproduce this. I installed 2.1 in my localhost at least 3x today :tongue:

**Comment by illori** [comment]
i dont have many extensions... if i test logging in in a private tab i cant duplicate the issue.

i can log in fine in IE on desktop and chrome on my phone.

**Comment by margarett** [comment]
Nop. Not with private tab, not logging out, emptying cache, cookies, close browser, reboot computer...

**Comment by Oldiesmann** [comment]
No problems with 36.0.4 on this end either (it worked fine on a newly-installed copy of 2.1 earlier that I had not previously logged into), at least on Linux (openSuSE 13.2). If I remember I'll try it on Windows tomorrow.

**Comment by illori** [comment]
a user on sm.org also reported the same thing. http://www.simplemachines.org/community/index.php?topic=535155.msg3802300#msg3802300 but not sure what browser.

**Comment by FearThe1337** [comment]
Not sure if relevant, but I had a php page with the following code (sort of, exact code would be too long)

```
$scripturl = ''; //Somewhere read that doing this before including SSI would benefit speed...
#include "forum/SSI.php";
ssi_login();
```

The script would return a form going to http://example.com/forum while the forums were set to always use SSL. As a result people would always get the session error.

**Comment by Oldiesmann** [comment]
Is this still an issue? I never was able to reproduce it.

**Comment by illori** [comment]
cant duplicate it.
