### ISSUE TITLE
Paid subs not working?

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#2795]
http://www.simplemachines.org/community/index.php?topic=535039.0

This looks like a legit report. Any ideas?

**Comment by margarett** [comment]
An issue identified by Krash
http://www.simplemachines.org/community/index.php?topic=535070.0

**Comment by live627** [comment]
94fe7b488103ef998a2ca646eb4b2f0ded3d818a

**Comment by Oldiesmann** [comment]
live627, what does that commit have to do with the issue Krash reported?

**Comment by FearThe1337** [comment]
The [pull request](https://github.com/SimpleMachines/SMF2.1/pull/2867) has been merged, I personally have not tested it as I don't know how too. (Don't normally sell anything on paypal, nor do subscriptions)
Is anyone able to confirm or deny that this fixes the issue, fix should work based on the forum post.

**Comment by live627** [comment]
13426d0e5278930a28fb0f7abb45cfd8020b1bb8
