### ISSUE TITLE
help popup cut off on mobile

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2797]
![](https://imagizer.imageshack.us/v2/510x908q90/901/3Bmz2Q.jpg)

the same happens for the log in popup as well.

**Comment by XinYenFon** [comment]
Can you open index.css and change

.popup_window > left: 50%; to left: 56%;

**Comment by illori** [comment]
unless there is cache on my phone, that seemed to do nothing to fix the issue.

**Comment by live627** [comment]
Try `margin: 0 auto; left: 0;`

**Comment by illori** [comment]
that seems to fix it mostly on my phone, but on desktop it is not centered any longer.

**Comment by live627** [comment]
Good, since I have no phone to test it on.

**Comment by XinYenFon** [comment]
Maybe this helps; https://github.com/ericmmartin/simplemodal/blob/master/src/jquery.simplemodal.js#L593 I used this to try stuff... It has proper calculation for pop.

**Comment by illori** [comment]
Please reopen. Not fixed. On phone the popup does not come up on the proper
location on the page. It is always on the very top of the page. It should
be shown where you are on the page

**Comment by XinYenFon** [comment]
@illori can you test this;

change .popup_container 's position from absolute to fixed.
then increase popup_windows' the top from 5% to 15%.

**Comment by illori** [comment]
that seems to fix it
