### ISSUE TITLE
membergroup key, no color in online list selected

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2801]
```
$request = $smcFunc['db_query']('', '
        SELECT id_group, group_name, online_color
        FROM {db_prefix}membergroups
        WHERE min_posts = {int:min_posts}
            AND hidden = {int:not_hidden}
            AND id_group != {int:mod_group}
            AND online_color != {string:blank_string}
        ORDER BY group_name',
        array(
            'min_posts' => -1,
            'not_hidden' => 0,
            'mod_group' => 3,
            'blank_string' => '',
        )
    );
```

i think even if you have no color selected and the group is visible it should still show in the group key on the board index. it is a bit confusing that a group will not show up if the color is left blank/empty and it is set as visible.

**Comment by margarett** [comment]
That's also how it works in 2.0. It can be improved, yes.

What would be the default color? Black? Whatever color the theme uses as default?
In 2.0 it uses default color (for the member name)

```
        // Some basic color coding...
        if (!empty($row['online_color']))
            $link = '<a href="' . $scripturl . '?action=profile;u=' . $row['id_member'] . '" style="color: ' . $row['online_color'] . ';">' . $row['real_name'] . '</a>';
        else
            $link = '<a href="' . $scripturl . '?action=profile;u=' . $row['id_member'] . '">' . $row['real_name'] . '</a>'; 
```

**Comment by illori** [comment]
I would say the default color for links should be good enough.

**Comment by margarett** [comment]
Eh, funny enough all it takes is just to remove the WHERE condition from the query. The while loop that follows the query already deals with the absence of online color (even if the query clearly excludes these groups :tongue: )

**Comment by illori** [comment]
dont you also need to remove ?

```
'blank_string' => '',
```

**Comment by margarett** [comment]
Yes. Duh! :hear_no_evil:
