### ISSUE TITLE
Upgrader fails

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#2802]
Install works fine...
Upgrader fails when attempting to upgrade a 2.0 RC3 database
old forum files had been deleted...
Extracted/Loaded all 2.1 files
copied upgrade and settings files from "other" directory
changed values in Settings.php to point to the old database.

ran upgrade.php
Error is as follows:
The upgrader was unable to find some crucial files.
Please make sure you uploaded all of the files included in the package, including the Themes, Sources, and other directories.

Ran install.hp in the SAME location, with the SAME files (except using a clean copy of Settings.php)
installed into a new database just fine.

changed Settings.php to point to the old database...
Re-ran upgrade.php
Same errror

**Comment by margarett** [comment]
was the location changed?

**Comment by Kindred-999** [comment]
nope.   New set of files dropped into the identical directory structure.

**Comment by margarett** [comment]
I've seen this issue occurring more than once with upgrades from 1.1.x (to 2.0) actually. I think that it has to do with the forum default theme which is meanwhile not available. I have a topic somewhere in Dev boards about it. 

edit: Since you manually edited Settings.php, did you fix only the database or did you set correct path for $boarddir, $sourcedir, as well as $boardurl?

**Comment by Kindred-999** [comment]
I only fixed the Settings.php. I did not touch the database...

However, that should not have mattered -- because the directories were the EXACT same as they would have been if I had done an upgrade using the normal replace files method instead of deleting the directories beforehand and then putting the stuff back later

**Comment by margarett** [comment]
Yes, you're right. It should :tongue: And I've seen this before (with 2.0 from 1.1, though)

But what I asked was: in Settings.php, did you also fixed $boarddir, $sourcedir, as well as $boardurl?

**Comment by illori** [comment]
i believe i had seen similar issues when using windows server/paths seemed to be an issue with back slashes vs forward slashes in theme paths for the default theme.

there was a topic in the old beta board about this, we found no real reason for the issue to exist i believe.

**Comment by Kindred-999** [comment]
Oh, sorry Bruno...   Yes. Settings.php was completely correct with all values set.

And Illori, this was a Linux box.

**Comment by Kindred-999** [comment]
Haven't been able to replicate this recently. Closing...
