### ISSUE TITLE
unapproved reply alert

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2806]
it seems that is a reply is made that is awaiting approval it does not show up in the alerts drop down. seems like only new topics awaiting approval shows up.

**Comment by MissAllSunday** [comment]
Isn't this commit fixed this?  https://github.com/live627/SMF2.1/commit/060b4136e4674ef6e4103ce55d98e6e890c1d5a1

**Comment by illori** [comment]
If it should it does not fix it. I can check again later but I don't think
that does it.

**Comment by illori** [comment]
made a reply to a topic that was not approved [reply not approved as well] it shows up in the alerts as
the user started a new unapproved topic in [topic name] in [board name].

i made a reply to a topic that was approved [reply was not approved] got the same message in the alerts that a new topic was made. this is incorrect.

as a result of the incorrect text, the link was to the topic and not the message that requires approval.

**Comment by live627** [comment]
so this is now a language issue?

**Comment by illori** [comment]
In part yes. Also the link has to be changed.
