### ISSUE TITLE
new unapproved topic, new unapproved reply email

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2807]
seems that both a new unapproved topic and new unapproved reply have the same email sent out.

both of them point to a new#new message instead of the exact message that needs approval with a reply.

IMO separate emails should be sent out, this way we make sure the topic is linked directly or the exact message is linked.

**Comment by live627** [comment]
They _are_ separate, although you're right they do both use  new#new.

**Comment by illori** [comment]
the message i received looked like they were identical. even the subject was the same in both messages i got.

**Comment by illori** [comment]
i looked it up, both the email for an unapproved reply and topic had the subject "New Unapproved Post: [post or topic subject]"

**Comment by live627** [comment]
That makes sense to me.

**Comment by illori** [comment]
if a topic needs to be approved, the subject should tell you it is a topic not a post or message.

**Comment by live627** [comment]
Fixed in 34c931188cf692a39b76faa47f824ecca9dcd1a6
