### ISSUE TITLE
quote image showing behind other image

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2808]
```
.quickbuttons li a {
    background: url("../images/quickbuttons.png") no-repeat scroll 0 -1px rgba(0, 0, 0, 0);
    display: block;
    float: left;
    line-height: 1.9em;
    padding: 0 4px 0 5px;
}
```

this causes a quote image to show behind other images

i see this on the reports page for members in the moderation center

![](http://imagizer.imageshack.us/v2/356x55q90/540/wHSZiD.png)

if the background is removed the extra image is removed.

@Antes  can you look into this?

**Comment by XinYenFon** [comment]
I thought I fixed this issue ...

**Comment by XinYenFon** [comment]
and yet I don't see quote icons behind user probably using old build.

**Comment by XinYenFon** [comment]
oh lol stupid me :P fixed it.

**Comment by illori** [comment]
So it was not just me :P FYI my build updates daily so I can't be outdated.

**Comment by XinYenFon** [comment]
Actually Quickbuttons (icons) needs rewrite I'll do it before final (possibly this Sunday). Converting those icons into generic_icons will save/improve a lot.
