### ISSUE TITLE
last active in profile only shows when user is online

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2812]
http://www.simplemachines.org/community/index.php?topic=535264.0

if we want this to only show when the user is online, then we should just remove it completely. it is useless this way.

**Comment by XinYenFon** [comment]
yea it should be is_guest or remove it completely.

**Comment by margarett** [comment]
I have the feeling that this is by design (don't know when it was introduced, though). Maybe the idea is to stop handing over the last online of hidden users?

**Comment by illori** [comment]
Maybe but even then it should show to admin by default. If if is to hide
when online then it should not show when you are online.

**Comment by XinYenFon** [comment]
then system should calculate the last active based on if user came online with non-hidden ways. Otherwise that will increase the questions in community about "is that user ever came online? or when was the last time the user was online etc..."

**Comment by live627** [comment]
#1259 a35b867c58bfc6cd1bc1b8c9fe51cae7e7215628

**Comment by illori** [comment]
i see why that was changed, but i dont think it was done the best way.

**Comment by MissAllSunday** [comment]
Is this solved?

**Comment by illori** [comment]
No the behavior has not been changed.

**Comment by MissAllSunday** [comment]
So.... what needs to be changed?

**Comment by illori** [comment]
Admin should always be able to see the last online time. Otherwise hide
from all.

**Comment by margarett** [comment]
Well, the way I see it, we either:
- remove the info altogether (for non admins - or for no "manage users" permission) if the user chooses to be hidden 
- gather a new field in the database for the "filtered last online" and show that if the user chooses to be hidden. How to filter is yet to be decided :P

**Comment by Oldiesmann** [comment]
This is a tough one. It makes absolutely no sense to only show it while the user is online, but at the same time we don't want to show it to all users if they've chosen to remain hidden.

**Comment by illori** [comment]
So only show to admin and problem solved.

**Comment by margarett** [comment]
Or to membergroups allowed to manage members as I suggested :P
