### ISSUE TITLE
Error "showAlerts sub template - eval"

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#2815]
Last Release download from 04.04.2015

The error came on after click "Alerts => All alerts"

Error Log:
Type of error: Undefined
8: Undefined index: text
/index.php?action=profile;area=showalerts;u=1;start=10
File: root/Themes/default/languages/Alerts.english.php (showAlerts sub template - eval?)
Line: 564 

Type of error: Undefined
8: Undefined index: text
/index.php?action=profile;area=showalerts
File: root/Themes/default/languages/Alerts.english.php (showAlerts sub template - eval?)
Line: 564

**Comment by live627** [comment]
Which alerts are those? They may have gotten corrupted.

**Comment by wintstar** [comment]
![alerts_setting](https://cloud.githubusercontent.com/assets/2753863/7000428/b889d17a-dc22-11e4-9709-49850e0058ca.PNG)

**Comment by illori** [comment]
do you have any deleted topics that show blank in your alerts window?

it may be related to https://github.com/SimpleMachines/SMF2.1/issues/2770#issuecomment-80340413

you should also disable eval, it is on the server settings page.

**Comment by wintstar** [comment]
@illori This #2770 (comment) seems to be the solution. Have the missing string inserted in Alerts.english.php and so far no entry in the error log.
