### ISSUE TITLE
Package Manager

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#2816]
Not to sure if this has been fixed yet but I get an error when trying to install any package now. Uncaught exception or something. I will post it when I try again after I get back from supper. In any event, the package manager is not working at all.

**Comment by smfbigguy** [comment]
I guess I should also say that I just updated from github like 15 minutes ago.

**Comment by wintstar** [comment]
For me, the package manager works. Last Release download from 04.04.2015. I could install my chat-Mod (http://www.smfportal.de/index.php/topic,10989.msg85814.html#msg85814) install without error message.

My testboard => http://smf.wintstar.de/index.php

**Comment by smfbigguy** [comment]
Hmm, I will try again now but it doesn't seem to work for me. It could be my server. I was playing with it not to long ago and may have screwed something up.

**Comment by smfbigguy** [comment]
Oh, wait a minute...it worked for one mod. Lets try another.

**Comment by smfbigguy** [comment]
Nope got one installed and that was it. Here is part of the error:

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct

**Comment by wintstar** [comment]
Have you activated the Emulation Support for 2.1 Beta1?
![emulation](https://cloud.githubusercontent.com/assets/2753863/6998456/adab38f0-dbe3-11e4-979a-63dabb5047aa.png)

**Comment by smfbigguy** [comment]
Yes

**Comment by margarett** [comment]
And what was the mod that threw the error?

**Comment by smfbigguy** [comment]
Faq's mod won't install neither will the downloads mod. scared to try Eh Portal, lol

**Comment by smfbigguy** [comment]
Slide tab mod installed fine.

**Comment by live627** [comment]
> Faq's mod won't install neither will the downloads mod

Both from the mod site?

**Comment by smfbigguy** [comment]
The slide tab mod is from my site. Not yet submitted to the mod site. Faq's mod from Suki Oddly enough Suki helped make my slide tab mod if I recall right and it will install fine but the Faq's mod wont.

**Comment by smfbigguy** [comment]
The error I get quotes this line as what is messing it up:

Subs-Package.php on line 2992

**Comment by smfbigguy** [comment]
Line 2989 to line 2995

```
foreach ($dirs as $dir => $dest)
{
    $iter = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($dir, RecursiveDirectoryIterator::SKIP_DOTS),
        RecursiveIteratorIterator::SELF_FIRST,
        RecursiveIteratorIterator::CATCH_GET_CHILD // Ignore "Permission denied"
    );
```

**Comment by live627** [comment]
Ah, it's related to the package backups.

**Comment by live627** [comment]
Please remove

```
 RecursiveIteratorIterator::SELF_FIRST,
```

and report back.

**Comment by smfbigguy** [comment]
That seems to have worked. I can now install mods.

**Comment by live627** [comment]
One more thing, than  I can hopefully stop using you as a guinea pig for
this issues.

Can you insert this code exactly where you removed thee previous line?

```
RecursiveIteratorIterator::SELF_FIRST,
```

**Comment by smfbigguy** [comment]
I can but thats the same line I took out is it not ??

**Comment by smfbigguy** [comment]
It works.

**Comment by live627** [comment]
almost... `child`  is replaced with  `self`.

**Comment by smfbigguy** [comment]
Well, it works. :)

**Comment by live627** [comment]
Apparently, this fix is already in the codebase https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Package.php#L2993 so whatever shenanigans GitHub id pulling is not cool.

**Comment by smfbigguy** [comment]
I'll try updating again tomorrow with new files from github. That's probably the best thing.

**Comment by smfbigguy** [comment]
I guess we can close this then if a fix is in place already.

**Comment by smfbigguy** [comment]
Still getting this error when installing a mod, refresh the page and it will install but if this was fixed I should not still be getting it:

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct
