### ISSUE TITLE
alerts menu to small

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#2818]
The alerts menu is too narrow for other languages. This leads to shifts in the texts. The same also "My Messages".
![alerts_menu](https://cloud.githubusercontent.com/assets/2753863/7001863/97670bce-dc41-11e4-8b32-d74d00c81bd9.PNG)

**Comment by XinYenFon** [comment]
If we increase the width of the box, it'll not fit to smaller displays.

**Comment by wintstar** [comment]
Could not we make different arrangement of the text in the menu? For example, the texts among themselves.

**Comment by illori** [comment]
@antes cant we add a width etc specially for the mobile browsers?

**Comment by XinYenFon** [comment]
@illori we can but that only fix the issue for desktop. Scaling down the text makes UX worse on mobile. But we can do something better maybe? We replace text with icons. That also increase the UX for mobile, since when both a-links come closer it makes harder to tap on proper link.

@wintstar that won't really look good on short text, you can add display: block element to those a-links, that'll make them list one by one.

**Comment by illori** [comment]
If icons then it might be harder to tell what they are for as well.

**Comment by wintstar** [comment]
On the fast first a image assembly. So I imagine that too for "My Message" Popup.
![alerts_menu_3](https://cloud.githubusercontent.com/assets/2753863/7006653/3145aef8-dc83-11e4-9daf-5ed830a89b10.PNG)

**Comment by XinYenFon** [comment]
![screenshot-localhost 2015-04-06 19-01-56](https://cloud.githubusercontent.com/assets/1669995/7007128/7786aafa-dc8f-11e4-82c6-42be505a2282.png)

**Comment by wintstar** [comment]
+1 Top. And there should be a configuration in admin, how many are to be displayed.

**Comment by XinYenFon** [comment]
Well, @wintstar I can only assist with UI/UX part, for that type of things consult our real developers :D

**Comment by wintstar** [comment]
I hope that it reads a developer and perhaps convert.

**Comment by XinYenFon** [comment]
btw alerts has its own custom mobile friendly scroll bar. Currently I don't remember but I think 15 was the hard-limit.

**Comment by illori** [comment]
it is well over 15 as the limit. we just put a limit on the length of the box that shows the alerts.
