### ISSUE TITLE
Missing Paths in Admin

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#2819]
In the configuration menu is missing the part for paths.

![missing_paths](https://cloud.githubusercontent.com/assets/2753863/7003796/f8a2c72e-dc60-11e4-93f9-382e4b35fffe.png)

**Comment by illori** [comment]
they were removed as most of the time when you need to change them you dont have access to your forum anyway. repair_settings.php should be used to change those paths.

**Comment by wintstar** [comment]
Then the language-string should be changed
$txt['database_paths_settings'] = 'Database and Paths';
to
$txt['database_paths_settings'] = 'Database';
Otherwise you will not find paths
