### ISSUE TITLE
remove HTML from board descriptions

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#2821]
allowing HTML in the board descriptions is actually a potential security issue and it leads to regualr issue reports from admins who screw up their site layout (and is unnecessary for the most part)

It would be my inclination to state that we should allow just basic text... but it has been pointed out that there is some valid use for basic formatting and links. So, I recommend basic BBC (bold, italic,underline, hr and links) and ignore or remove everything else..
(allowing images leads the the highest number of reports, so I'd suggest getting rid of those - or forcing a CSS on images in that section to be minimal if it is deemed necessary to keep images)

**Comment by illori** [comment]
unless there is another function $smcFunc['htmlspecialchars'] will not allow basic html

also seems that bbc is not acepted in the board description, so that would need to be fixed with this.
