### ISSUE TITLE
Create a returned page for unknown actions instead of boardindex

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#2822]
Instead of returning to the boardindex, action=blah (or other unknown/undefined actions) should present a standard or perhaps customizable "page not available" message

**Comment by AerandirA** [comment]
Perhaps this could be added to the ACP in the same way editing useragreement does?

**Comment by MissAllSunday** [comment]
Add a default 404 may be a good idea, offer an UI for it may not. If we were to add an UI we may as well add support for custom pages and that requires some other changes and taking into consideration other aspects such as the main menu and how it will behave, ultimately leading to add some kind of "menu" editor too which is way beyond scope right now.

**Comment by Kindred-999** [comment]
true. the extended function is beyond the scope for 2.1

so maybe, just a default 404 which uses the basic header/footer of the forumand lets the user type a custom message to be displayed as the main content of the page?

**Comment by AerandirA** [comment]
I'm pisspoor at php scripting, but spontanously it feels it wouldn't be such a difference from the user agreement page.  Where is that stored? Database? A new page in ACP where the 404 is written; A database table of its own to put it and it'd be done deal

**Comment by illori** [comment]
the agreement is stored in a text file, so a good bit different then most other things in SMF that are stored in the database.

for a 404 page, i would really hope a new database table would not be needed, but a row in an existing table.

**Comment by AerandirA** [comment]
illori; Pretty much what i meant, but you got the terminology down :P
This could possibly be extended with a drop down menu with the most important types of error pages, where different error types could be adressed within the forum.

**Comment by illori** [comment]
I think that is even more outside the scope of what this should be.

**Comment by Kindred-999** [comment]
That is indeed even further out of scope than my original statement.

A simple error message within the forum layout in place of the current "back to index with no error" is th correct way to get this done for 2.1
