### ISSUE TITLE
remove/disallow HTML in membergroup descriptions

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#2823]
we should be removing/cleaning HTML form the membergroup descriptions.

**Comment by illori** [comment]
if we are doing it for membergroups then we should do it anywhere there is a perm.

the membergroup description only shows when you view the group members or want to join the group... i think less of a chance of issue here then with board descriptions or category descriptions.

**Comment by smfbigguy** [comment]
I would be nice to be able to style these areas though somehow. I'm talking from a users p.o.v. now. Taking this away and not doing it at all will let people create mods for this that are unsafe. Better to do it right I think then to take it right out of everywhere. Keep in mind this is just my opinion.

**Comment by Kindred-999** [comment]
why would you need to style the membergroups description?

Membergroup names themselves should 110% be restricted from EVER using html or ANY styling. Styling should be controlled by CSS for those...   but for the membergroup description, I can not imagine any really useful purpose in being able to style the text.

**Comment by illori** [comment]
the membergroup names already dont allow html in 2.1. you can enter it but it does not get parsed.

**Comment by smfbigguy** [comment]
I don't know why....maybe italics or something strange people will want. You know people, they are the ones that always want everything that is not safe cause it's cool, lol. It was a thought on how others will think that's all.

**Comment by illori** [comment]
many users have broken their forum because they have put html that is too long for the field and it gets cut off. it is easier to stop them from using it and it also makes it so that if others can create groups they cant put in javascript.

also italics and bold are already used and have a purpose, reusing that elsewhere may cause confusion.

**Comment by smfbigguy** [comment]
it was just an idea is all. No harm done. :)

**Comment by jdarwood007** [comment]
1. Allow BBC in descriptions, which should prevent bad html from breaking the site.
2. Remove it and let modifications put it back if people wish to do this.  Leave hooks around to allow this.

**Comment by Kindred-999** [comment]
In general, we should only allow basic BBC though.... If we just allow it all, some not-so-bright-idjit would then use the html BBC to try something.

**Comment by illori** [comment]
well only the admin can use the html bbc anyway, so they should be slightly less of an idiot if they do know it even exists.
