### ISSUE TITLE
Install Language

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#283]
Today i noticed, install.language files has their own encoding

$txt['lang_character_set'] = 'xxx';

Can we make a little trick to get this string from index language file?

note: currently very tired 4.30 am here. I'll update this issue further writing for now (to notice myself later).

**Comment by MissAllSunday** [comment]
Easiest but ugly way to do it would be including Index at the end on load_lang_file() func and of course delete the txt string from Install, seems a little too much.

There is also $txt['lang_rtl'].

Dunno how the language editor works as I never saw its code but it will be much more efficient to do this on the language editor and ship the files already synchronized.

**Comment by XinYenFon** [comment]
AFAIK smf2/1 using index.language to get those encodings but to speed things up they cut the index.language from install part and used two strings to do the job.

There is system that hides those lines from translating and LE filling them based on language settings. Actually its not related to SMF at all more likely for LE.

**Comment by emanuele45** [comment]
mmm...TBH I'm not sure why it loads install and not index...

**Comment by XinYenFon** [comment]
btw we solved this problem inside Language Editor so no need for extra coding.
