### ISSUE TITLE
Use Of Capital And Small Initial Letters

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#2831]
Please look here https://github.com/SimpleMachines/SMF2.1/commit/d030793697f58fac261b9726c5398464b8384abb and https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/languages/Alerts.english.php#L15.

**Comment by live627** [comment]
https://github.com/SimpleMachines/SMF2.1/commit/bd99a46d44dffefcdceed950a2a83e94751fc787
