### ISSUE TITLE
Wrong count of board totals with unapproved topics

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#2840]
1 - created a board and set it to post moderation.
2 - with a test user created a topic.
3 - admin replied to said topic but not approve the topic

Now, on Board Index, that board has totals: "1 posts, 0 topics". And shows it for everyone.
Recount totals does not fix this.

Should these replies count towards totals?

**Comment by illori** [comment]
maybe in part related to https://github.com/SimpleMachines/SMF2.1/issues/1292 ?

**Comment by margarett** [comment]
Just did a quick comparison and 2.0.x works exactly the same way. So it's not a biiiiiiiig problem. It's been like this for years :tongue:
