### ISSUE TITLE
Inconsistent behaviour between quick edit and normal edit.

### ISSUE THREAD

**Issue by FearThe1337** [SimpleMachines/SMF#2845]
Noticed the following 2 issues in the current git version.

Creating a post with a malformed(?) quote tag:

```
[quote=29-04-2015]
- Fixed frontpage link going to wrong location
[/quote]
```

The BB Code displays fine, however if you edit the post, it gets rewritten to

```
[quote]
- Fixed frontpage link going to wrong location
[/quote]
```

(Removes the =TEXT part)
![example_screenshot](https://cloud.githubusercontent.com/assets/1053063/7390940/067025a8-ee7d-11e4-974b-8391c0da3d91.png)

Second issue

When doing a quick edit in a topic with no replies for a while no warnings appear, while a warning for no recent post does appear for editing the non-quick way.
(Also, It mentions reply while editing? seems a different thing)

![edit_warning](https://cloud.githubusercontent.com/assets/1053063/7390935/fe652df4-ee7c-11e4-8aea-9d90673bac59.png)

**Comment by margarett** [comment]
About your first issue, yes, the text in quote seems to be lost at edit, although a "normal" quote (with author, date and lnk) keeps the values. Strange.

As for the second case, well, it's kinda expected. Quick edit loads the direct edit window via AJAX so there is no real place to put that warning :tongue: 
As for the "reply" text, well, it's the same warning that appears at the reply page. A new text string would have to be created for that, yes.

**Comment by live627** [comment]
That seems to be a hidden feature of SCEditor I guess. It's undocumented. I don't know if it's expected or not... we didn't develop it.

Quick edit does not use that editor.

**Comment by FearThe1337** [comment]
@live627 
I have been looking into this, it does seem to be documented however I was not able to get a use able fix (unless we directly edit the js files).

The following [page](http://www.sceditor.com/documentation/plugins/bbcode/) lists options for the BBCode parser. As far as I can see the following options would need to be changed to get the same behaviour as quick edit.

```
fixInvalidNesting
removeEmptyTags
fixInvalidChildren
```

I was however unable to get these options changed, I tried the following methods (some hoping it might just work)

```
// File: jquery.sceditor.smf.js
$.sceditor.BBCodeParser.defaults.fixInvalidNesting = false;
$.sceditor.BBCodeParser.defaults.removeEmptyTags = false;
$.sceditor.BBCodeParser.defaults.fixInvalidChildren = false;

// File: GenericControls.template.php (template_control_richedit section)
Tried adding:
    parserOptions: {
        quoteType: $.sceditor.BBCodeParser.QuoteType.auto,
        fixInvalidChildren: false,
        fixInvalidNesting: false,
        removeEmptyTags: false,
    },
```

As well as adding it outside of parserOptions and renaming parserOptions in to options.
At this point I am not sure if this is a sceditor bug, or if I am just messing up my javascript. I assume it will work if changed in the sceditor defaults.

**Comment by jdarwood007** [comment]
I know this is old... But I figured this out.  To add those options you have to update the editor in the sources
```
	// Set up the SCEditor options
	$sce_options = array(
		'style' => $settings['default_theme_url'] . '/css/jquery.sceditor.default.css',
		'emoticonsCompat' => true,
		'colors' => 'black,maroon,brown,green,navy,grey,red,orange,teal,blue,white,hotpink,yellow,limegreen,purple',
		'format' => 'bbcode',
		'plugins' => 'undo',
		'bbcodeTrim' => true,
		'parserOptions' => array(
			'fixInvalidNesting' => false,
			'removeEmptyTags' => false,
			'fixInvalidChildren' => false,
		),
	);
```

However this doesn't fix it because its a SMF bug actually!  Tracked this in the PR referenced.
