### ISSUE TITLE
Password recovery by email broken when a user has recovery questions.

### ISSUE THREAD

**Issue by FearThe1337** [SimpleMachines/SMF#2848]
Recovery by email seems to redirect to the same page without sending an email and the selection choice text header is broken (Not sure how to call it, it used to say something like choose an recovery option).

![2015-05-02 20_51_03-authentication reminder](https://cloud.githubusercontent.com/assets/1053063/7442321/24ea43d2-f10d-11e4-8bef-893f451d4596.png)

**Comment by illori** [comment]
Notice: Undefined index: authentication_options in D:\wamp\www\github2.1\Themes\default\Reminder.template.php on line 51

related error ^^ which means that $txt['authentication_options'] is not found in the language files

in 2.0 that string is 
$txt['authentication_options'] = 'Please select one of the two options below'; in Profile.english.php

was removed by mistake here https://github.com/SimpleMachines/SMF2.1/commit/726757a5a3e420684aa6c78f2e4a7cf70bf90ebf#diff-b93d5517a0987e3b77b2cfe5a2ca159fL82

**Comment by FearThe1337** [comment]
Still seems to not send the password by email, unless this is somehow due to my configuration.

**Comment by illori** [comment]
I did test that and the email was sent out.

**Comment by live627** [comment]
The package on sm.org has that bug.

**Comment by illori** [comment]
given that they got the error above, they are not using the version from sm.org.

**Comment by FearThe1337** [comment]
Still broken.

Note: as the title said with recovery questions, emails were only not being send out if a recovery question was set.
