### ISSUE TITLE
Error when editing posts with quickedit in combination with mentioning members.

### ISSUE THREAD

**Issue by FearThe1337** [SimpleMachines/SMF#2849]
When a user edits a post using quick edit and mentions a user using @<name> in the post, the poster data is not being set in the call to modifypost.
As a result this data is not available in the background task which is supposed to detect when members are being mentioned in messages.

In addition to yielding an error due to this, the background task will not be deleted automatically, and will keep on producing errors.

[Uploaded here](https://github.com/FearThe1337/Files/blob/master/patch.diff) is a possible patch, I am not sure if its the correct way or not, so I am not submitting a pull request, but a possible patch.

![image](https://cloud.githubusercontent.com/assets/1053063/7445206/1a944224-f1a9-11e4-868f-46fc9215a65b.png)

**Comment by live627** [comment]
Your patch looks good to me. Please send a pull request and I'll check it out.

**Comment by FearThe1337** [comment]
Submitted as pull request [2852](https://github.com/SimpleMachines/SMF2.1/pull/2852). Also added one extra commit to resolve some undefined indexes when a user has no preferences set.

**Comment by live627** [comment]
Thanks.

**Comment by XinYenFon** [comment]
I applied your patch but unfortunately I'm still getting the errors in my log.

**Comment by FearThe1337** [comment]
@Antes: Interesting, I applied the patch to my forums which has 100+ active members daily and have no had any errors from that file since. 
Are you sure the errors you are getting might not be related to the [extra commit](https://github.com/FearThe1337/SMF2.1/commit/a8e099b1e4dbdea8f8d660411ff1da8bbf14e95d) in the pull request?

**Comment by XinYenFon** [comment]
I got whole pr as patch don't think so :/

**Comment by FearThe1337** [comment]
Just spend 20 minutes looking at code differences and it appears I forgot a [comma](https://github.com/FearThe1337/SMF2.1/commit/2e087447409ee8e073159726b2ff3016a2c632c2#diff-9147c6e90133e15f04efe7d3ca5137b8R2524)

I'll commit a fix, sorry about that.

Edit: Updated the commit. It should now show up. If you still get any errors let me know and I'll look into it (if possible with errors).

Edit2: Old tasks with too little information, might still be stuck in the queue. See the database table {prefix}background_tasks

**Comment by XinYenFon** [comment]
There are 3 items in that table, I'll clean them

```
|155|$sourcedir/tasks/CreatePost-Notify.php|CreatePost_Notify_Background|a:4:{s:10:&quot;msgOptions&quot;;a:8:{s:2:&quot;id&quot;;s:3:&quot;116&quot;;s:7:&quot;subject&quot;;s:27:&quot;Re: Build Update 27/06/2014&quot;;s:4:&quot;body&quot;;s:302:&quot;Omg.&amp;nbsp; Spell check is in the wrong order because I could not test it -- SMF will not allow me to enable spell checking on my test server.&lt;br&gt;&lt;br&gt;[member=1]Antes[/member] can you load this file here:&lt;br&gt;https://github.com/AngelinaBelle/SMF2.1/blob/patch-3/Themes/default/GenericControls.template.php&quot;;s:4:&quot;icon&quot;;N;s:11:&quot;modify_time&quot;;i:1403885332;s:11:&quot;modify_name&quot;;s:13:&quot;AngelinaBelle&quot;;s:13:&quot;modify_reason&quot;;s:0:&quot;&quot;;s:17:&quot;mentioned_members&quot;;a:1:{i:1;a:2:{s:2:&quot;id&quot;;s:1:&quot;1&quot;;s:9:&quot;real_name&quot;;s:5:&quot;Antes&quot;;}}}s:12:&quot;topicOptions&quot;;a:6:{s:2:&quot;id&quot;;i:31;s:5:&quot;board&quot;;s:1:&quot;1&quot;;s:9:&quot;lock_mode&quot;;N;s:11:&quot;sticky_mode&quot;;N;s:12:&quot;mark_as_read&quot;;b:1;s:4:&quot;poll&quot;;N;}s:13:&quot;posterOptions&quot;;a:0:{}s:4:&quot;type&quot;;s:4:&quot;edit&quot;;}|1431547757
|166|$sourcedir/tasks/CreatePost-Notify.php|CreatePost_Notify_Background|a:4:{s:10:&quot;msgOptions&quot;;a:5:{s:2:&quot;id&quot;;s:3:&quot;123&quot;;s:7:&quot;subject&quot;;s:27:&quot;Re: Build Update 28/06/2014&quot;;s:4:&quot;body&quot;;s:87:&quot;[member=6]Oldiesmann[/member] -- Don&amp;#39;t know how to test #1963 -- need a fatal error&quot;;s:4:&quot;icon&quot;;N;s:17:&quot;mentioned_members&quot;;a:1:{i:6;a:2:{s:2:&quot;id&quot;;s:1:&quot;6&quot;;s:9:&quot;real_name&quot;;s:10:&quot;Oldiesmann&quot;;}}}s:12:&quot;topicOptions&quot;;a:6:{s:2:&quot;id&quot;;i:33;s:5:&quot;board&quot;;s:1:&quot;1&quot;;s:9:&quot;lock_mode&quot;;N;s:11:&quot;sticky_mode&quot;;N;s:12:&quot;mark_as_read&quot;;b:1;s:4:&quot;poll&quot;;N;}s:13:&quot;posterOptions&quot;;a:0:{}s:4:&quot;type&quot;;s:4:&quot;edit&quot;;}|1431547764
|149|$sourcedir/tasks/CreatePost-Notify.php|CreatePost_Notify_Background|a:4:{s:10:&quot;msgOptions&quot;;a:5:{s:2:&quot;id&quot;;s:3:&quot;111&quot;;s:7:&quot;subject&quot;;s:64:&quot;Re: IIn portrait mode, post edit and subject boxes are not right&quot;;s:4:&quot;body&quot;;s:58:&quot;afaik this fixed as well? [member=2]AngelinaBelle[/member]&quot;;s:4:&quot;icon&quot;;N;s:17:&quot;mentioned_members&quot;;a:1:{i:2;a:2:{s:2:&quot;id&quot;;s:1:&quot;2&quot;;s:9:&quot;real_name&quot;;s:13:&quot;AngelinaBelle&quot;;}}}s:12:&quot;topicOptions&quot;;a:6:{s:2:&quot;id&quot;;i:16;s:5:&quot;board&quot;;s:1:&quot;1&quot;;s:9:&quot;lock_mode&quot;;N;s:11:&quot;sticky_mode&quot;;N;s:12:&quot;mark_as_read&quot;;b:1;s:4:&quot;poll&quot;;N;}s:13:&quot;posterOptions&quot;;a:0:{}s:4:&quot;type&quot;;s:4:&quot;edit&quot;;}|1431547775
```

**Comment by XinYenFon** [comment]
I was thinking, should it be better if we run cleaning step on that table on each upgrade ?

**Comment by FearThe1337** [comment]
Hmm that might however cause lost emails or something, but I would say there is a need for a mechanism to prevent these from just keep trying while they will error out anyway. (Maybe a max of 3 retries?)

**Comment by FearThe1337** [comment]
I don't want to sound rude but just wondering a few things.

First of all, I have 3 commits in this PR, one to add the missing information, which is in my opinion needed and the third to use default preferences (which should be done, why is there a default preference setting in the admin panel otherwise).

The second commit fixes errors for when no preferences are found, which should also be fixed by one of my other PRs (Add missing default preferences) in combination with the third commit.

In the case of the second commit, the added isempty checks should not be need since they should never be empty (Unless someone removes the default preferences from the database).

So I asked in IRC and was told SMF prefers extra checks as a user might mess up their database. Can anyone verify if extra checks are wanted or not? If not I should probably remove the extra checks. 

Also since some PRs have been open for some time, is anything wrong with them, should there be improvements made, or are they just waiting to be validated or merged?

**Comment by live627** [comment]
I don't want to merge anything that's not agreed upon for Beta 2 until it's
out . This is just me personally, the other devs may feel differently.

**Comment by FearThe1337** [comment]
Ok, thanks for letting me know. Was getting kind of insecure if the pr was ok or not.

**Comment by Oldiesmann** [comment]
I'll look over the PRs later today or tomorrow and merge them in if I don't see any issues.

**Comment by FearThe1337** [comment]
sounds good :)
