### ISSUE TITLE
!empty vs. count

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#285]
Original report by iksa: http://www.simplemachines.org/community/index.php?topic=493625.0

> in function SendMailing() in file ManageNews.php there are many comparisons to !empty() that should be comparisons to count(). Just to reproduce one issue this causes, try to deliver an admin newsletter to the group 'Regular Members' (whose identifier is zero). You won't be able to get it delivered unless you also select some other group to deliver it to (which makes a difference in the condition empty($_POST['groups']))

**Comment by colinschoen** [comment]
Should be an easy fix. Ema, I will go ahead and make the fix and make a PR if that is alright.

**Comment by matthew-kerle** [comment]
This should be resolved as per the pull request that contains a fix.
