### ISSUE TITLE
"Native" language names

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#2857]
Should we include this?  http://www.simplemachines.org/community/index.php?topic=536359.msg3811781#msg3811781

Needs to be done differently of course, each language will have to define its own "native" name in a string inside index.language and use that string. Should only use entities or otherwise be "safe" in whatever encoding the currnet user is using.

**Comment by margarett** [comment]
Actually I think this is a great idea.
It will not be used in most forums but it's something that clearly I'd like to have as administrator ;)

**Comment by XinYenFon** [comment]
Yeap :)
