### ISSUE TITLE
forum width

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2858]
since 2.1 is responsive and a fixed width will break it, maybe worth removing the option to set a forum width?

**Comment by MissAllSunday** [comment]
It might still make sense if the setting defines a max-width instead.

**Comment by illori** [comment]
i have no issue with a max width instead of a fixed width

**Comment by XinYenFon** [comment]
I vote for removing completely. If it has such big need we can create a small modification.

**Comment by live627** [comment]
> I vote for removing completely.

+1

**Comment by smfbigguy** [comment]
I think Antes idea is a good one. Make it into a small mod. Some might still want the setting.

**Comment by NanoSector** [comment]
Why is this still open?
ETA: Oops, PR is still pending. Nevermind.

**Comment by wintstar** [comment]
'forum width' as small mod  +

Use of the website with smartphone are increasingly. Therefore, I do not think also that this setting is needed. How often this setting is needed one could, can find in a survey.

**Comment by Rupurudu** [comment]
Also +1
