### ISSUE TITLE
MSN -> Skype

### ISSUE THREAD

**Issue by matthew-kerle** [SimpleMachines/SMF#286]
As per some preliminary team discussion, Microsoft Live Messenger should be replaced with Skype support. Microsoft has stated that they are retiring Live Messenger and trying to redirect MSN LM users to Skype.

Skype's API for reference: https://developer.skype.com/skype-uri/skype-uri-tutorial-webpages

As per their API, it is possible to link the Skype username with one of multiple operations - Shift Focus, Video Call, Audio Call, Chat.

**Comment by Oldiesmann** [comment]
Since MSN is an IM client, and that's what most people on forums would likely be using Skype for (that's all I ever use it for), I think we should just do the chat option.

**Comment by matthew-kerle** [comment]
Pull Request: #349

**Comment by illori** [comment]
since #349 has been merged please close this

**Comment by XinYenFon** [comment]
if @Labradoodle-360 doesn't have any plan for expanding Skype with API.

**Comment by illori** [comment]
personally i think it is best the way it is. when you use an API to check if a user is online with their IM, it increases the time it takes to load a page that has the IM listed.

**Comment by matthew-kerle** [comment]
I agree with Illori on this, which is why I didn't extend it any further.
