### ISSUE TITLE
Weird character handling in title of topics.

### ISSUE THREAD

**Issue by FearThe1337** [SimpleMachines/SMF#2872]
When creating a topic with the following subject: 

```
&#32;
```

The editor automatically converts the subject to 

```
&#38;#32;
```

Not sure if related to #1066. (Was trying to find a way to get that bug, and tried random stuff in the title)

Also noticed that for example:

```
&#160

changes into

&#38;#160
```

**Comment by Oldiesmann** [comment]
Something appears to be getting double-encoded there - 38 is the HTML entity for the & character (though "&amp" is usually used instead)

**Comment by Sesquipedalian** [comment]
Fixed in #4283
