### ISSUE TITLE
Group moderator field acts unexpected

### ISSUE THREAD

**Issue by FearThe1337** [SimpleMachines/SMF#2879]
When having a group with e.g. 4 mods it will show up as:

[textfield for input]
- Moderator 1 [x]
- Moderator 2 [x]
- Moderator 3 [x]
- Moderator 4 [x]

Now when entering something in the text field and pressing the enter key, it will delete all the current moderators. I assume this is not the behavior it should be having.

**Comment by illori** [comment]
confirmed an issue and 2.0 does the same thing.
