### ISSUE TITLE
Wrong text lines in email recovery.

### ISSUE THREAD

**Issue by FearThe1337** [SimpleMachines/SMF#2881]
When filling nothing in at the enter username/email field you get the following message:

```
That username does not exist.
```

When filling in a non-existing username or email you get the following message:

```
There are no usernames associated with that email.
```

Surely, I assume that the first text should be something like: "You did not fill in any username or email, please go back and fill in either your username or email"
And the second one: "There were no accounts found for...." (Not only email, as usernames are valid too!)

**Comment by tallona** [comment]
I would even suggest that one message is used for all failed long attempts regardless of if there is no user with that username/email, if the field is empty or if it's a failed login attempt as you are giving a potential hacker hints as to what is and isn't a valid user account that could be targeted.

**Comment by frandominguezl** [comment]
This is solved @live627 @colinschoen

**Comment by live627** [comment]
closing thus then...
