### ISSUE TITLE
Blank messages.

### ISSUE THREAD

**Issue by FearThe1337** [SimpleMachines/SMF#2886]
I noticed after migrating to SMF2.1 some of my private messages were displayed as empty messages. It turns out that in my database a character, [ was encoded as 

```
&#91;
```

Having this encoded character, causes messages to be displayed empty, without any warnings. A clean SMF install 2.0.4 did NOT encode [ in the database, nor does SMF 2.1 beta.
(So, I assume it might of been  a modification)

However, I assume that either a warning should be displayed instead of the message, or that there should atleast be an error logged in the error log. (Which, currently, does not happen)

**Comment by margarett** [comment]
That is probably caused by utf8mb4 characters, which has support just added in 2.0.10

There is an open issue about that somewhere here ;)

**Comment by illori** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/2162

**Comment by FearThe1337** [comment]
Hmm I did not link that to this bug as in this case we are dealing with a 1 byte character, 0x5B. Is this related to the linked issue even though this is a standard ascii character?

**Comment by Arantor** [comment]
No, it's not related to utf8mb4.

[ is sometimes encoded as an entity for other reasons, mostly when you have [ and ] together to avoid confusing the bbc parser, or inside nobbc tags.

**Comment by illori** [comment]
wow @arantor is alive, nice to see you around ;) .
