### ISSUE TITLE
Install by step 3 stopped

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#2888]
With the latest download package from 2015-05-26  7:48pm.
Stop by http://localhost/smftest/install.php?step=3
Error Message:
Table 'smftest.smf_settings' doesn't exist
PHP-Version: 5.5.11
MySQL(i) 5.6.16
php.ini:
max_execution_time = 120
max_input_time = 120
default_socket_timeout = 120
mysql.connect_timeout = 3

Install with "MySQLi"

**Comment by Oldiesmann** [comment]
This is after you've specified the database name, prefix, etc.? It does try to select data from the settings table at the beginning of step 4 (just to make sure there's not already another copy of SMF installed on that database with the same prefix), but we've specifically told SMF to ignore database errors there.

**Comment by margarett** [comment]
This is now known and can be reproduced by some more people. We are looking into it ;)
