### ISSUE TITLE
install.php ex instead of px

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#2889]
install.php at Line 572
                    ul style="margin: 2.5ex; font-family: monospace;"
It should not be 2.5px?
                    ul style="margin: 2.5px; font-family: monospace;"

**Comment by Oldiesmann** [comment]
"ex" is a valid unit as well. See http://www.w3.org/Style/Examples/007/units.en.html for an explanation.

**Comment by wintstar** [comment]
Many thanks for info.

**Comment by colinschoen** [comment]
Should be closed.
