### ISSUE TITLE
Change software version to Beta 2  #2865

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#2890]
https://github.com/SimpleMachines/SMF2.1/pull/2865

Missing version change in files:
other/install.php
other/upgrade.php
other/Settings.php

**Comment by illori** [comment]
in upgrade.php the SMF_VERSION and SMF_LANG_VERSION need to be changed or you can not run the upgrade.

@MissAllSunday can you fix this?

**Comment by MissAllSunday** [comment]
> @MissAllSunday can you fix this?
> 
> —

Yes I can, so does everyone else though.

**Comment by illori** [comment]
i know others create a PR for this. i just thought this you did the last one related to this that you could fix it. i dont really have time to do it myself.
