### ISSUE TITLE
upgrade.php outdated files

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2891]
if upgrade.php finds outdated files and is run from CLI it seems it does not give any output. the browser version tells you it has found outdated files but not the CLI version.

**Comment by MissAllSunday** [comment]
cmdStep0() which is the CLI checker function performs the same checks the browser version does for outdated files and shows an error if found any: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L3222

**Comment by illori** [comment]
well when i ran the upgrader in CLI and there were outdated files there was no output as to why it was doing nothing.
