### ISSUE TITLE
post in topic awaiting approval

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2893]
seems that when a post is waiting approval, the color of the message on the index changes to #ffeaea which is different from when a topic is waiting approval, #e4a17c. also when a message is waiting approval the text (awaiting approval) does not show up. if the admin/moderator does not know what this pink color means the message may take longer to get approved.

**Comment by XinYenFon** [comment]
Are you serious ?

**Comment by illori** [comment]
why would i make a bug report if i was not serious?

**Comment by margarett** [comment]
Strange...

The text thing should have been fixed with this
https://github.com/SimpleMachines/SMF2.1/pull/2805

**Comment by illori** [comment]
that is for unapproved topics, not unapproved posts apparently.

**Comment by illori** [comment]
a topic that is not approved has [approved] => 0 [unapproved_posts] => 2
a topic that has posts not approved has [approved] => 1 [unapproved_posts] => 1 
your code is looking for approved to be 0 not 1 and not checking for unapproved_posts in $topic

**Comment by margarett** [comment]
Yeah, it has exactly the same behavior as topic approval had. The PR I submitted didn't dealt with Display.template.php, which requires a similar fix...

**Comment by illori** [comment]
i am talking about the message listing, not the display.template.php.

**Comment by illori** [comment]
```
(!empty($topic['unapproved_posts']) ? '&nbsp;<em>(' . $txt['awaiting_approval'] . ')</em>' : '')
```

that seems to add the (Awaiting Approval) to any topic that is either unapproved or a message in it is unapproved.

that leaves us to decide if the color is an issue or not. IMO the colors should be the same.

**Comment by Kindred-999** [comment]
I actually disagree...

if a TOPIC is pending approval, it should be one color.
If a post INSIDE that topic is pending approval, then the TOPIC should not be the same color as when the TOPIC is pending.

Like on versus on2...

**Comment by illori** [comment]
We should then reconsider the color. The change to add awaiting approval
imo is useful.

**Comment by XinYenFon** [comment]
color won't make big difference imo, because its like icons, people can't figure out what is it till use it (especially when approve post - topic colors pretty much close to each other.

**Comment by illori** [comment]
the "pink" color is so lite that it is almost not visible. it should be changed to a color that makes it stand out.
