### ISSUE TITLE
Double quotes in MySQL password in installer

### ISSUE THREAD

**Issue by soderlund** [SimpleMachines/SMF#2896]
You can't use double quotes in the MySQL password in the installer.

Double quotes (`"`) in the MySQL password are escaped (`\"`) and the password is stored in the `db_passwd` variable in `Settings.php`. Double quotes should not be escaped because the string is single-quoted.

This results in being unable to connect to the database because backslashes are inserted into the password. You can manually change the password in `Settings.php`, but you still can't finish the installation because you need to enter the MySQL password to create the admin user.

SMF version 2.0.10

**Comment by illori** [comment]
please do not report bugs on 2.0.\* here. this tracker is for 2.1 only. please test this with 2.1 and see if you can duplicate the issue.

**Comment by soderlund** [comment]
It's present in the 2.1-beta as well. Steps to reproduce:
1. Run `install.php`.
2. In "Step 3: Database Settings", enter `a"a` as password and click "Continue".
3. Check `$db_passwd` in `Settings.php`. The value is `'a\"a'`.

**Comment by Oldiesmann** [comment]
I'll have to look into this and see why that's happening. There's nothing in the install script itself that escapes values, so it must be something with how SMF sanitizes POST data.

**Comment by live627** [comment]
#2897
