### ISSUE TITLE
$txt missing in globals in Sources/SubsReportedContent.php

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#2901]
$txt missing in globals in Sources/SubsReportedContent.php

In two functions

 getReportDetails($report_id) and getReportComments($report_id)

Needed for $txt['guest']

**Comment by MissAllSunday** [comment]
Unless I'm missing something, getReportDetails()  doesn't use $txt vars, it returns the whole $row var so whoever function calling getReportDetails() is the one who needs to check if $row['reporter'] is set and non empty.

**Comment by VBGAMER45** [comment]
Scrolled too far meant the function getReports()
