### ISSUE TITLE
Install Bug "Duplicate entry 'cust_aolins' for key 'col_name'"

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#2903]
New Install from Download 19.0.6.2015 17:45Uhr

PHP-Version: 5.5.11
MySQL(i) 5.6.16
php.ini:
max_execution_time = 120
max_input_time = 120
default_socket_timeout = 120
mysql.connect_timeout = 3

Install with "MySQLi"

Error message:
Some of the queries were not executed properly. This could be caused by an unsupported (development or old) version of your database software.

Technical information about the queries:

```
Line #715: Duplicate entry 'cust_aolins' for key 'col_name'
```

![install_from-19-06_17-30](https://cloud.githubusercontent.com/assets/2753863/8257374/7aab1f42-16ad-11e5-855b-6a8ba0486b70.png)

**Comment by Oldiesmann** [comment]
There are no other SMF installs on that database with the same prefix? That's the only place "cust_aolins" appears in the entire file.

**Comment by wintstar** [comment]
No, Database was empty.

**Comment by margarett** [comment]
Are you sure? Because I can duplicate that error (in more ways than one :tongue: ) but it requires one of 2 things:
a) an existing set of tables in the database
or
b) refresh the page (instead of hitting "Continue") when database population finishes

**Comment by wintstar** [comment]
A wise page appeared briefly at level 3, and the page is updated.
