### ISSUE TITLE
Upgrade.php fails on The PostgreSQL user you have set in Settings.php does not have proper privileges.

### ISSUE THREAD

**Issue by tinoest** [SimpleMachines/SMF#2904]
The PostgreSQL user you have set in Settings.php does not have proper privileges.

Please ask your host to give this user the ALTER, CREATE, and DROP privileges.

Is the error you get when running upgrade.php, I modified the code slightly to the following; 

  // Sorry... we need CREATE, ALTER and DROP
  if (!$create)
    print_error("The " . $databases[$db_type]['name'] . " user you have set in Settings.php does not have proper privileges.\n\nPlease ask your host to give this user the CREATE privileges.", true);
  // Sorry... we need CREATE, ALTER and DROP
  if (!$alter)
    print_error("The " . $databases[$db_type]['name'] . " user you have set in Settings.php does not have proper privileges.\n\nPlease ask your host to give this user the ALTER privileges.", true);
  // Sorry... we need CREATE, ALTER and DROP
  if (!$drop)
    print_error("The " . $databases[$db_type]['name'] . " user you have set in Settings.php does not have proper privileges.\n\nPlease ask your host to give this user the DROP privileges.", true);

So that I could work out what one was failing, It was the Alter command, although checking through it was altering the table. 

Adding this on line 306 in Sources/DbPackages-postgresql.php

  print_r($column_info);
  echo(count($column_info));

Showed : Array
(
    [name] => txt
    [null] => 
    [default] => 
)

So db_change_column was called. I'm not quite sure why it was called and then I got lost in the code about what it was trying to do, commenting this check out and returning true allowed it to upgrade with no issues. 

PHP Version 5.5.26 
PostgreSQL : 9.0.22

**Comment by margarett** [comment]
I have PGSQL in my computer, I can try this tomorrow evening ;)

**Comment by tinoest** [comment]
Further update. I found the issue. 

 php upgrade.php 

```
    SELECT tablename
    FROM pg_tables
    WHERE schemaname = 'public'
    ORDER BY tablename

    CREATE SEQUENCE smf_priv_check_seq
     CREATE TABLE smf_priv_check
    (
    "id_test" int NOT NULL default nextval('smf_priv_check_seq'))
    CREATE  INDEX smf_priv_check_id_test ON smf_priv_check (id_test)

    SELECT column_name, column_default, is_nullable, data_type, character_maximum_length
    FROM information_schema.columns
    WHERE table_name = 'smf_priv_check'
    ORDER BY ordinal_position

    ALTER TABLE smf_priv_check
    ADD COLUMN txt character varying(255)

    SELECT column_name, column_default, is_nullable, data_type, character_maximum_length
    FROM information_schema.columns
    WHERE table_name = 'smf_priv_check'
    ORDER BY ordinal_position

            UPDATE smf_priv_check
            SET txt = ''
            WHERE txt IS NULL

        ALTER TABLE smf_priv_check
        ALTER COLUMN txt SET NOT NULL

    SELECT tablename
    FROM pg_tables
    WHERE schemaname = 'public'
    ORDER BY tablename
    DROP TABLE smf_priv_check
    DROP SEQUENCE IF EXISTS smf_priv_check_seq
```

The PostgreSQL user you have set in Settings.php does not have proper privileges.

Please ask your host to give this user the ALTER, CREATE, and DROP privileges.

I added a echo before the SQL query was run and got the above results. 

It turns out that the function smf_db_change_column doesnt have a return true or false within it. So the upgrade.php doesn't detect that the ALTER commands were successful. Adding a return true; to the end of this function makes it work as expected. 

The MySQL version doesn't exhibit this behaviour as this function is never called from smf_db_add_column

**Comment by live627** [comment]
#2906
