### ISSUE TITLE
Search engine friendly URLs: Worth keeping?

### ISSUE THREAD

**Issue by Hristo-** [SimpleMachines/SMF#2913]
Is this option still worth keeping?

**Comment by live627** [comment]
Can you please explain your reasons for removing it?

**Comment by Hristo-** [comment]
Everytime someone asks for this option the answer I see is that it was intended to ease forum's indexing  by the old time search engines which had some dificulties with the standard format. If it's of no real use nowadays, then isn't it bloat?

Also everyone initially thinks this option works like Pretty URLs and they expect a different effect.

**Comment by XinYenFon** [comment]
I agree its pretty much useless, I never used that feature. But it needs upgrade, removing is not an option here, I know some forums still using it. So its better to leave it there and make something good with SMF 3.0.

**Comment by badmonkey72** [comment]
How would removal affect million+ post forums currently using it?  Wouldn't that potentially break thousands of links, both internal and external?

**Comment by XinYenFon** [comment]
that's exactly what happens :P that's why we shouldn't (still last word comes from dev team) remove that feature instead upgrade it in next version (please understand its not a simple feature and needs some planning and coding).

**Comment by badmonkey72** [comment]
Sure.  My point was to gently say not to remove it just for sake of removal.  It certainly would be nice to retain in future versions so links from years ago aren't broken.  Suffice it to say one of "those" million post sites is mine.  lol.  Whether the feature _should_ be useful at this point gets eclipsed by the fact that, right or wrong, it has been used for many years by my site.  It would be a huge consideration in potential upgrades.  What I'm saying isn't for sake of demands or anything like that.  It's simply to serve as a reminder there are some of us out there with an interest.  :)

**Comment by Hristo-** [comment]
Because no dev has spoken yet whether or not this option has any usefulness in it, lets assume for now that it's completely useless. In that case if not removed IMO it at least should be disabled (like choosing non UTF-8 encoding), so no new forums would use it and thus inducing a future problem.

Now, excuse my ignorance, but isn't it possible this to be solved with a redirect and maybe canonical tag?

**Comment by MissAllSunday** [comment]
The option as it is has become old and obsolete, however, removing it could cause some mayor issues for users, considering this option really and directly affects one of the most important aspects of a forum.

Sure we can remove it and offer a redirect for those that used to use this but that would have a negative impact on users, after all, there is a large portion of users out there that firmly believes having so called "SEO" urls is a "must have" and will be very pissed off to see their precious urls were changed to vanilla SMF ones.

I'm all in favor of removing features when the usage is minimal and/or doesn't really affect overall functionality but I'm afraid removing this one would be too much.
