### ISSUE TITLE
filecache: function clean_cache 

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#2915]
if a other prefix (as example "user") used for filecache, on call this with type='user' the index.php timestamp is changed and all smf cache files are duplicated in the cache.

To fix this change follow to:
    // Invalidate cache, to be sure!
    // ... as long as index.php can be modified, anyway.
    if(empty($type))
        @touch($cachedir . '/' . 'index.php');
    call_integration_hook('integrate_clean_cache');
    clearstatcache();

**Comment by live627** [comment]
#2606
