### ISSUE TITLE
After login return where you have been not redirect to Board Index

### ISSUE THREAD

**Issue by Hristo-** [SimpleMachines/SMF#2918]
This is my 3rd attempt to rise this issue (first time on github). In 2.0.\* when you login you return to the page you have been. In 2.1 you are redirected to Board Index. This clearly is step back. Isn't it possible to be fixed?

**Comment by Hristo-** [comment]
Just now I tested it on the newest package and realized it was fixed in the past months.

**Comment by Hristo-** [comment]
Actually it still does not work on admin section pages, i.e. after login you are thrown on Board Index. That is something I can live with, but still if someone wants to take a look...

**Comment by margarett** [comment]
That is confuse. How can you be in admin pages if you are not logged in?

**Comment by Hristo-** [comment]
Session has expired then you click a link, or if you keep some tabs when you load them... ect.

**Comment by margarett** [comment]
That is essential to prevent session hijacking, methinks...

**Comment by Hristo-** [comment]
Methinks nothing :) I just compared 2.0.\* with 2.1.  As long as it works outside admin area I'm fine with that. If devs think it's not a bug, just close the issue. I remember back in the early alpha days (years) Emanuele said he has no idea why is that happening so maybe it's a complex "bug" (or maybe it was not his job at the time).

**Comment by illori** [comment]
also considering that your admin session [not your log in session] can expire before you are logged out and log back in, i dont really see how this can be done easily.

i dont even see the problem getting sent to board index when you log in.

**Comment by Hristo-** [comment]
Disabling administration security is one of the first thing I do after new install, so I mean the login session.
