### ISSUE TITLE
install.php error on database population

### ISSUE THREAD

**Issue by Rupurudu** [SimpleMachines/SMF#2919]
I always got an error while installing SMF via install.php. I mostly ignore this message since installation completes as usual and the installation works.

The mysql user is root.

> ### Populated Database
> 
> Your settings have now been saved and the database has been populated with all the data required to get your forum up and running. Summary of population:
> 
>    Created 71 tables.
>    Inserted 787 rows.
> 
> Click "Continue" to progress to the admin account creation page.
> #### !! Critical Error!
> 
> The database account you specified does not have permission to ALTER, CREATE, and/or DROP tables in the database; this is necessary for SMF to function properly.

**Comment by live627** [comment]
What's the result of `SHOW PRIVILEGES`?

**Comment by Rupurudu** [comment]
Here is the result.

| Privilege | Context | Comment |
| --- | --- | --- |
| Alter | Tables | To alter the table |
| Alter routine | Functions,Procedures | To alter or drop stored functions/procedures |
| Create | Databases,Tables,Indexes | To create new databases and tables |
| Create routine | Databases | To use CREATE FUNCTION/PROCEDURE |
| Create temporary tables | Databases | To use CREATE TEMPORARY TABLE |
| Create view | Tables | To create new views |
| Create user | Server Admin | To create new users |
| Delete | Tables | To delete existing rows |
| Drop | Databases,Tables | To drop databases, tables, and views |
| Event | Server Admin | To create, alter, drop and execute events |
| Execute | Functions,Procedures | To execute stored routines |
| File | File access on server | To read and write files on the server |
| Grant option | Databases,Tables,Functions,Procedures | To give to other users those privileges you possess |
| Index | Tables | To create or drop indexes |
| Insert | Tables | To insert data into tables |
| Lock tables | Databases | To use LOCK TABLES (together with SELECT privilege) |
| Process | Server Admin | To view the plain text of currently executing queries |
| Proxy | Server Admin | To make proxy user possible |
| References | Databases,Tables | To have references on tables |
| Reload | Server Admin | To reload or refresh tables, logs and privileges |
| Replication client | Server Admin | To ask where the slave or master servers are |
| Replication slave | Server Admin | To read binary log events from the master |
| Select | Tables | To retrieve rows from table |
| Show databases | Server Admin | To see all databases with SHOW DATABASES |
| Show view | Tables | To see views with SHOW CREATE VIEW |
| Shutdown | Server Admin | To shut down the server |
| Super | Server Admin | To use KILL thread, SET GLOBAL, CHANGE MASTER, etc. |
| Trigger | Tables | To use triggers |
| Create tablespace | Server Admin | To create/alter/drop tablespaces |
| Update | Tables | To update existing rows |
| Usage | Server Admin | No privileges - allow connect only |

**Comment by live627** [comment]
Are you using PostgreSQL or MySQL?

**Comment by Rupurudu** [comment]
MySQL 5.6

**Comment by illori** [comment]
i have done several installs of 2.1 in the last month or so, using my localhost root user i have never seen this error message come up. wamp mysql 5.6.17

**Comment by live627** [comment]
Is this still an issue? If so, please run

```
ALTER TABLE {$db_prefix}boards ORDER BY id_board
```

in phpMyAdmin and post the results.

**Comment by Rupurudu** [comment]
```
ALTER TABLE smf_boards ORDER BY id_board
```

Error 1105 - ORDER BY ignored as there is a user-defined clustered index in the table 'smf_boards'

**Comment by Oldiesmann** [comment]
It should be safe to just have SMF ignore that error (at least during the installation/upgrade). I'll commit a fix in a bit.
