### ISSUE TITLE
Category description text is too small.

### ISSUE THREAD

**Issue by Rupurudu** [SimpleMachines/SMF#2920]
Category description text is too small and it's hard to read for my eyes. :disappointed: 

Also, it looks ugly on it's current place, can we move it to a better place, or remove it altogether?

Edit: I think it's font issue, Segoe UI on 10px is hard to read while Verdana on 10px is easy.

**Comment by live627** [comment]
Can you please produce a screenshot?

**Comment by Rupurudu** [comment]
![category description](https://cloud.githubusercontent.com/assets/3107676/8631834/8a811820-278a-11e5-9d8b-42e7ee3bee79.png)

**Comment by illori** [comment]
i think that is really personal preference. if we make that text much larger i think it will be too big and distracting. if you dont like the font size then you can modify it on your own install or look for another theme that has that feature once 2.1 themes start to be made.

at this point i dont see developers removing features that were added to 2.1. you can always leave that field blank.

**Comment by XinYenFon** [comment]
I think 12px font-size & small margin change will be enough.

![screenshot-next mmobrowser com 2015-07-12 18-30-55](https://cloud.githubusercontent.com/assets/1669995/8638448/30104114-28c4-11e5-9cf9-605a36b17bfa.png)

**Comment by Rupurudu** [comment]
@Antes Yeah, this looks much better. Thanks!
