### ISSUE TITLE
GenericMenu.template.php

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#2922]
I think, this is a bug in  line 203 ..

this:
    // Print out all the items in this tab (if any).
    if (!empty($context['tabs']))

must:
    // Print out all the items in this tab (if any).
    if (!empty($tab_context['tabs']))

**Comment by live627** [comment]
Is it? Seems to work fine...

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/GenericMenu.template.php#L51

**Comment by PortaMx** [comment]
No, no .. not if you use the hook include_admin_areas !!!
I tested that more then on day in a debugger and with my changes all works fine ...

**Comment by live627** [comment]
Can you show your code?

**Comment by PortaMx** [comment]
here my code ..

/**
- Add Admin menu context
- Called from hook integrate_admin_areas
  **/
  function PortaMx_AdminMenu(&$menudata)
  {
  global $txt, $context, $modSettings;
  
  if(empty($modSettings['pmxportal_disabled']))
  {
      // insert Portamx menu part after 'config'
      $fnd = array_search('config', array_keys($menudata)) +1;
      $menudata = array_merge(
          array_slice($menudata, 0, $fnd),
          array(
              'portamx' => array(
                  'title' => 'PortaMx',
                  'permission' => array('admin_forum'),
                  'areas' => array(
                      'pmx_center' => array(
                          'label' => $txt['pmx_admincenter'],
                          'bigicon' => $context['pmx_imageurl'] .'adm_center.png',
                          'file' => $context['pmx_templatedir'] .'AdminCenter.php',
                          'function' => 'PortaMx_AdminCenter',
                      ),
                      'pmx_settings' => array(
                          'label' => $txt['pmx_settings'],
                          'bigicon' => $context['pmx_imageurl'] .'adm_settings.png',
                          'file' => $context['pmx_templatedir'] .'AdminSettings.php',
                          'function' => 'PortaMx_AdminSettings',
                          'subsections' => array(
                              'globals' => array($txt['pmx_admSet_globals']),
                              'frontpage' => array($txt['pmx_admSet_front']),
                              'panels' => array($txt['pmx_admSet_panels']),
                              'control' => array($txt['pmx_admSet_control']),
                              'access' => array($txt['pmx_admSet_access']),
                          ),
                      ),
                      'pmx_blocks' => array(
                          'label' => $txt['pmx_blocks'],
                          'bigicon' => $context['pmx_imageurl'] .'adm_blocks.png',
                          'file' => $context['pmx_templatedir'] .'AdminBlocks.php',
                          'function' => 'PortaMx_AdminBlocks',
                          'subsections' => array(
                              'all' => array($txt['pmx_admBlk_panels']['all']),
                              'head' => array($txt['pmx_admBlk_panels']['head']),
                              'top' => array($txt['pmx_admBlk_panels']['top']),
                              'left' => array($txt['pmx_admBlk_panels']['left']),
                              'right' => array($txt['pmx_admBlk_panels']['right']),
                              'bottom' => array($txt['pmx_admBlk_panels']['bottom']),
                              'foot' => array($txt['pmx_admBlk_panels']['foot']),
                              'front' => array($txt['pmx_admBlk_panels']['front']),
                              'pages' => array($txt['pmx_admBlk_panels']['pages']),
                              'bib' => array($txt['pmx_admBlk_panels']['bib']),
                          ),
                      ),
                      'pmx_categories' => array(
                          'label' => $txt['pmx_categories'],
                          'bigicon' => $context['pmx_imageurl'] .'adm_category.png',
                          'file' => $context['pmx_templatedir'] .'AdminCategories.php',
                          'function' => 'PortaMx_AdminCategories',
                      ),
                      'pmx_articles' => array(
                          'label' => $txt['pmx_articles'],
                          'bigicon' => $context['pmx_imageurl'] .'adm_article.png',
                          'file' => $context['pmx_templatedir'] .'AdminArticles.php',
                          'function' => 'PortaMx_AdminArticles',
                      ),
                      'pmx_sefengine' => array(
                          'label' => $txt['pmx_sefengine'],
                          'bigicon' => $context['pmx_imageurl'] .'adm_pmxsef.png',
                          'file' => $context['pmx_templatedir'] .'AdminSettings.php',
                          'function' => 'PortaMx_AdminSettings',
                      ),
                      'pmx_languages' => array(
                          'label' => $txt['pmx_languages'],
                          'bigicon' => $context['pmx_imageurl'] .'adm_language.png',
                          'file' => $context['pmx_templatedir'] .'AdminCenter.php',
                          'function' => 'PortaMx_ShowLanguages',
                          ),
                  ),
              ),
          ),
          array_slice($menudata, $fnd, count($menudata) - $fnd)
      );
  }
  }

**Comment by Bloc67** [comment]
It would seem this issue was corrected as the code now shows $tab_context on line 203(unless that line has moved after this was posted), ....mark as solved maybe?

**Comment by PortaMx** [comment]
well ... long time ago I posted this bug 😁 but ...
if is changed as I say .. yes

**Comment by frandominguezl** [comment]
This can be closed @colinschoen

**Comment by colinschoen** [comment]
Sounds good, closed.
