### ISSUE TITLE
Package Manager issues with empty folders

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#2929]
A MOD (or in the test case a smileys pack --> http://custom.simplemachines.org/mods/index.php?mod=2125) fails to (by returning "Modification Parse Error"):

a) properly handle require-dir if the folder to copy is empty AND the package is zipped. This means that if I unpack the package to a folder inside Packages and try to install it (instead of it being a zip file) it will install properly

b) properly handle create-dir. It seems not to work in any case, as it always returns "Modification Parse Error.

**Comment by Oldiesmann** [comment]
The 2nd issue here was fixed in #3009. Is the first issue still a problem?

**Comment by illori** [comment]
still getting modification parse error when using that smiley package with the latest github source.

**Comment by Oldiesmann** [comment]
Which package are you using specifically? I picked a random smiley package from the mod site and it installed just fine (extracting the folder and its files to the Smileys directory).

**Comment by Oldiesmann** [comment]
Ok. I'm seeing the issue with the Solo Smileys package and will look into it, though I'm not sure why they did it that way instead of just putting all the smileys in that directory first and just extracting it.
