### ISSUE TITLE
Move Topic Issue- 2.1 Beta2

### ISSUE THREAD

**Issue by br360** [SimpleMachines/SMF#2930]
I just upgraded a site to 2.1 Beta2, and am seeing something weird when moving topics. If I move a topic from board A to board b, and uncheck "Post a redirection topic.", it works fine.

However, there is an issue if I move a topic from one board to another and leave a redirect topic notice. If I go back to the moved topic notice and delete it, it actually deletes the topic that was moved to a new board instead. Then when I go back and try to reopen the redirect topic notice, I get the "The topic or board you are looking for appears to be either missing or off limits to you" error.

**Comment by margarett** [comment]
For reference:
http://www.simplemachines.org/community/index.php?topic=538199.0
As stated in that topic, I can't reproduce the problem

**Comment by illori** [comment]
i cant reproduce this issue either.

**Comment by live627** [comment]
closed this per http://www.simplemachines.org/community/index.php?topic=538199.msg3825226#msg3825226
