### ISSUE TITLE
New Install stopped by Step 5

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#2931]
Updates package today 17.07.2015  07:30
PHP-Version: 5.6.8
MySQL:  5.0.11-dev

Parse error: syntax error, unexpected 'if' (T_IF) in C:\xampp\htdocs\smf21\Sources\Load.php on line 3359

change root/Sources/load.php line 3356
    call_integration_hook('integrate_set_avatar_data', array(&$image, &$data))
to
    call_integration_hook('integrate_set_avatar_data', array(&$image, &$data));

![install_step5](https://cloud.githubusercontent.com/assets/2753863/8741505/30d4ad26-2c5a-11e5-82f2-42e28d948e8e.PNG)

**Comment by illori** [comment]
that line was changed on june 8, i did several installs after then and did not run into this issue.

maybe a php 5.6 issue? i am running php 5.5.12
