### ISSUE TITLE
paid subs incorrect text

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2936]
http://www.simplemachines.org/community/index.php?topic=538290.msg3825477#msg3825477

If you delete this subscription all users currently subscribed will lose any access rights granted by the subscription. Unless you are sure you want to do this it is recommended that you simply deactivate a subscription rather than delete it.

i dont believe this behavior has changed from 2.0. the group is not removed from the users that paid for the sub.

**Comment by Oldiesmann** [comment]
Based on the code from https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/ManagePaid.php#L415 and following it appears that the text is correct.

**Comment by frandominguezl** [comment]
How did you test this, @illori ?

**Comment by illori** [comment]
did you read the link i provided? no i did not test it, but i wanted to report it in case something had to be changed or looked into.

**Comment by frandominguezl** [comment]
Maybe this needs to be changed but I have no way to test...

**Comment by jdarwood007** [comment]
@d3vcho ,

Subs like PayPal have a test sub you can use.  You just need to signup for a developer account to get access to it and then enable a hidden modSetting to go into developer mode.

**Comment by sbulen** [comment]
The question is whether to make the code match the text, or the text match the code.  The forum discussion focused on 2.0 code, but there have been changes in 2.1 in this area.  

I believe this Issue applies: Deleting a paid sub doesn't fix membergroups #1166

And this change addressed it:  https://github.com/SimpleMachines/SMF2.1/commit/4560eac832441e0bfcb528bfacc66847c438af17

It appears the code was changed to match the text.   

I think this can be closed.  

(Which is what Oldiesmann said above!)

**Comment by sbulen** [comment]
@illori - I think this can be closed.  See the note above.

**Comment by sbulen** [comment]
Can we close this one out?

**Comment by illori** [comment]
I guess so.
