### ISSUE TITLE
Missing Themes/default/images/icons/calendar_modify.png

### ISSUE THREAD

**Issue by realkinetix** [SimpleMachines/SMF#2937]
The calendar is displaying a broken image to administrators next to events, due to it trying to display the above file, which doesn't exist in the 2.1 beta release package or here on github.

**Comment by XinYenFon** [comment]
I can't reproduce, can you put an image ?

**Comment by realkinetix** [comment]
My calendar, with a single event, looks like this to me:

![smf-calendar-broken-icon](https://cloud.githubusercontent.com/assets/13442583/8814789/787aaf4a-2fc5-11e5-8fd9-1f0fe9351666.PNG)

If I inspect the element, I see this:

![smf-calendar-inspect-element-broken-icon](https://cloud.githubusercontent.com/assets/13442583/8814797/851022c6-2fc5-11e5-8e01-456134b50038.PNG)

That file is referenced in the default template a couple of times:

```
# grep -Ri calendar_modify.png
Themes/default/Calendar.template.php:                                                                           <img src="', $settings['images_url'], '/icons/calendar_modify.png" alt="*" title="', $txt['calendar_edit'], '" class="calendar_icon">
Themes/default/Calendar.template.php:                                                                                           <img src="', $settings['images_url'], '/icons/calendar_modify.png" alt="*" title="', $txt['calendar_edit'], '" class="calendar_icon">
```

**Comment by XinYenFon** [comment]
ah i see :D

**Comment by illori** [comment]
```
                                            <a href="', $event['modify_href'], '">
                                                <span class="generic_icons calendar_modify"></span>
                                            </a>
```

that seems to fix it as well as the same thing on line 404 of the calendar template... 

also calendar_export.png is missing

might be nice to have a tooltip or similar to tell what the icon is for.

**Comment by illori** [comment]
![test](https://github.com/SimpleMachines/SMF2.1/blob/d612948129d540eee6dc83ff52cd7cf511032822/Themes/default/images/icons/calendar_export.png?raw=true) is the image that was used for calendar_export.png

it is in generic_icons.png already.

**Comment by illori** [comment]
also on calendar settings in admin, enable show weeks links [at least on the main calendar] you will then see on your event in the weekly view that the icon plus.png is missing

**Comment by mkress** [comment]
also missing: Themes/Default/images/helptopics.gif

**Comment by illori** [comment]
where is that used? it should be .png

**Comment by mkress** [comment]
Used in admin area Start page text - or is it incuded in translation file (i use german from beta 1)??

**Comment by XinYenFon** [comment]
@mkress bugs are only valid if they are in english language or core system. If its related to German translation files contact with Translators or our Localization team.

**Comment by wintstar** [comment]
@mkress, the language pack german for SMF 2.1\* Beta is outdated and not fully. Not compatible with the current SMF 2.1 Beta \* Package.
