### ISSUE TITLE
SSL setting needs work - SSL for Auth doesn't return to http

### ISSUE THREAD

**Issue by realkinetix** [SimpleMachines/SMF#2939]
On my 2.1 Beta2 install, I have set "Enable SSL for Authentication (Login and Register)".  

After login, the forums stay in SSL mode, it doesn't return back to plain http.

The forums work appropriately the same otherwise in either http or https.

**Comment by bperry921** [comment]
I thought that was what it was suppose to do if SSL is enabled, why would it revert back http: if you login with SSL?

**Comment by realkinetix** [comment]
I would guess that the theory of operation for that setting would be to use SSL to pass the sensitive data (auth info), and then return the user back to http, to cut down on CPU time and speed data transfer along as quick as possible.

Wouldn't that be why there's the other option to force encryption on everything?

**Comment by zilladotexe** [comment]
There are only two modes: SSL and non-SSL. There is currently no option to only force SSL for authentication purposes, because the way SMF is set up, it would require a lot of unnecessary code.

**Comment by live627** [comment]
How many login attempts were there in a row?

**Comment by Rupurudu** [comment]
@realkinetix No. Users can embed images an other content to their posts. With full https these content will not load because of the browsers "http and https can't be mixed" policy.

**Comment by realkinetix** [comment]
@MustafaCan That's not what the feature suggests in the least.  SSL for login doesn't deal with the content of the posts.

**Comment by tinoest** [comment]
With Google's plan to warn when not using SSL all the time, not just on login forms as it does now. 

I'd suggest it's either on or off for the entire forum. Ideally SMF should encourage users to use SSL by default as that's the way the web is going anyway.

**Comment by sbulen** [comment]
Issue confirmed.  The inadvertent force to https:// is easily remedied (in Load.php) but then other things fail - e.g., it doesn't actually direct you to https:// when you login, it complains you hadn't already...   But logs you in insecurely anyway...

So...  force_ssl = 1 doesn't work.  

Direction from the development team needed:  Make it work?  Or get rid of it?

**Comment by frandominguezl** [comment]
@sbulen Can this be closed?

**Comment by sbulen** [comment]
No - I think this is actually a pretty big deal.  In my mind, a true RC need.  

Setting force_ssl to 1 (logon & reg only) doesn't work.  Maybe it did at one point, but it is not even close at the moment.

I bet folks will try to use this setting if for some reason they are spooked by the image proxy (e.g., frequent, extremely large attachments).  

So we should either fix this or remove the option.

**Comment by sbulen** [comment]
It may be important to clarify what 'fixed' looks like...  I think the solution should be that https: is utilized whenever credentials are gathered (logon, registration & admin/moderation password prompt).  It should _automatically_ route you back to http at all other times.  

I have not had luck with this one, feels a bit over my head..

**Comment by albertlast** [comment]
What are the reason not to drop this feature?

**Comment by sbulen** [comment]
That's a very good question.

My initial thought was to avoid "mixed content" issues such as broken links for those who wanted the image proxy off.   I.e., if you had https on but the proxy off, in the past some browsers really didn't like that.   

This setting would be a good compromise.  You'd never have a mixed content page, most were http but https mainly when needed for security.

But I don't think any browsers behave that way any more, I think they're all more tolerant of mixed content.   So I'm not so sure this setting is needed anymore.

**Comment by illori** [comment]
if it is easier to remove this feature then fix it, lets remove it ASAP and move on.

**Comment by albertlast** [comment]
By removing the code i came to some places where i think "well this couldn't work",
since i see no benefit of doing a short time ssl only for "critcal" stuff.
I decided to remove this feature.
