### ISSUE TITLE
Fatal error when opening a board

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#294]
I got a fatal error when opening a board in SMF 2.1, from the GitHub repo.

Fatal error: Call-time pass-by-reference has been removed; If you would like to pass argument by reference, modify the declaration of call_integration_hook(). in /var/www/smf2.1/Sources/MessageIndex.php on line 665

Line is this:

``` php
call_integration_hook('integrate_messageindex_buttons', &$context['normal_buttons']);
```

Removing the & sign worked for me and fixed the error.

Using PHP 5.4.6 with Apache 2.

**Comment by NanoSector** [comment]
Arantor just posted a solution:

``` php
call_integration_hook('integrate_messageindex_buttons', array(&$context['normal_buttons']));
```

http://www.simplemachines.org/community/index.php?topic=497341.msg3489424#msg3489424

**Comment by emanuele45** [comment]
Duplicate of #54

**Comment by emanuele45** [comment]
Yups, sorry: slightly different, you are right.

**Comment by Arantor** [comment]
This looks like it's fixed since it is correctly passing an array containing a reference...
