### ISSUE TITLE
ssl only mode - avatars are loaded from http

### ISSUE THREAD

**Issue by mkress** [SimpleMachines/SMF#2940]
have installed newest 2.1 beta 2 - all fine so far.
I have choosen to run all with ssl only - problem is all custom uploaded avatars are always loaded from http:// so browser says not whole site is secure.
Beitrag editieren

**Comment by illori** [comment]
have you checked the URL for avatars in the admin panel to see if it has https on it or not?

these are avatars uploaded to your forum not ones linked from elsewhere?

**Comment by illori** [comment]
http://www.simplemachines.org/community/index.php?topic=538341

user changed the url for avatars and that fixed it.
