### ISSUE TITLE
enabling notifications in default settings is not saved

### ISSUE THREAD

**Issue by mkress** [SimpleMachines/SMF#2941]
checking the box under /index.php?action=admin;area=featuresettings;sa=alerts; for enable newsletter does not get saved

**Comment by margarett** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/2928

If you are still using the package from simplemachines.org then this issue still occurs. That should be fixed in the current code ;-)

**Comment by margarett** [comment]
I just tested the current code and the problem was fixed in the mentioned PR so this issue can be closed ;)

**Comment by illori** [comment]
but the op is talking about in the admin panel not in the profile where that bug was reported and fixed for. did you test the option in the admin panel?

**Comment by margarett** [comment]
Dang, sorry you are right :(
I confused with the profile setting in the issue I mentioned.

Scratch what I said above, the issue does exist.

**Comment by live627** [comment]
It's the same code path. Kinda confusing.

Here's the resultant query:

```
  UPDATE smf_members
  SET notify_announcements = 1
  WHERE id_member = 0
```

Our options are to either remove that option from the admin panel (so it's only in thee profiler), or convert it to a notification pref.

**Comment by illori** [comment]
i say remove it and let the users decide which option they want.

**Comment by mkress** [comment]
No please do not remove - it is a great feature to set default settings!!!

**Comment by mkress** [comment]
The Problem is ID_member 0 will never exist... A unique ID can never be zero

**Comment by illori** [comment]
it has to be 0 to set it as default for everyone. if you have an id other then 0 it will only set it for that user and not everyone when they register.

**Comment by margarett** [comment]
Yeah... This is odd.

This is not defining a preference for new registrations (like the Theme options), it's just overwriting whatever a user might have set.
It is also not a "general" enable/disable of the function, again it's just an overwrite if the members preference on that.
Anyway that is buggy. WHERE id_member = 0 will always be a false condition because there is no member ID 0 (and there can't be)

With that mind, I'd say we either:
a) remove it (my preference)
b) rephrase that so that it is clear what it does. A JavaScript confirmation would also be a great idea, considering we are replacing user options...

**Comment by illori** [comment]
this whole page replaces what is already existing for users? does it set for new users as well? it is not obvious that is changes them for all current users.

**Comment by live627** [comment]
> This is not defining a preference for new registrations 

And yet, all the other options on the page do.

> b) rephrase that so that it is clear what it does. 

I can see it  now: "THIS IS BROKEN"

**Comment by Kindred-999** [comment]
Wow... that page breaks so many standards...
IMO the admin should not be able to overwrite every user's chosen options - especially for alerts.

I think that this page should set the defaults for NEW users... (and the text/description of the page updated to make this clear)

If this is going to reset every existing user, then it needs to be even more clear (but I am opposed to having it do that, as indicated above)

**Comment by Oldiesmann** [comment]
Maybe we should make it ask them if they want to set it for all new users or all existing users as well. I honestly don't see a problem with allowing the admin to override that option for existing users though - if people abuse it, they'll be the ones dealing with the consequences, not us.

**Comment by illori** [comment]
we should still note it clearly what that page effects. we should also give the admin ability to set the alerts for new users which they cannot right now.

**Comment by Oldiesmann** [comment]
That page does set the defaults for new users (as well as any user who hasn't set any notification options). It just doesn't override previously chosen settings for existing users.
