### ISSUE TITLE
search engine friendly pages - without index.php

### ISSUE THREAD

**Issue by mkress** [SimpleMachines/SMF#2942]
yes you could argue that's a feature,
BUT: handling seo urls with with index.php is 2000-like - not 2015.
.htacces mod_rewrite-handling 

rewriting all to index.php like wordpress would be a great solution:
https://codex.wordpress.org/htaccess
so you could also do a 404 handling with board look and feel out of the box and much better seo uris

**Comment by XinYenFon** [comment]
I agree but I actually like to hear from @MissAllSunday since she was into this SimpleSEF mod bit much.

**Comment by Rupurudu** [comment]
Note: Not every web server supports htaccess. One of my SMF Installations built on IIS Server, which uses web.config file instead.

**Comment by Kindred-999** [comment]
Can we please stop calling it "search engine friendly"?  Because -- quite honestly -- the re-write of URLs to path-like structure has nothing at all to do with SEO and has not for YEARS.
Call it "pretty urls" or "path-like" or even "human readable"  but stop calling it SEF and SEO.

I actually recommend REMOVING the so-called SEF option completely from the core.
If Suki wants to put SimpleSEF style re-writes, then I guess we could argue that it's an enhancement of an existing feature --  but, at this point, I am inclined to suggest
1- remove SEF option
2- let mods be built to handle the rewrites.

**Comment by mkress** [comment]
Okay - so let's call it human friendly pages...

**Comment by MissAllSunday** [comment]
I don't have any plans regarding that feature, I don't know where that came from, I updated the simpleSEF mod for my own usage but that's about it.

Jessica González, missallsunday.com

**Comment by Oldiesmann** [comment]
I think it's fine to leave it as a mod (and removing the existing feature is fine as well - at least as long as we leave the code to redirect from the rewritten URLs to the standard ones).

**Comment by live627** [comment]
Since it's done in the buffer, it'll be dead easy to remove.

**Comment by PortaMx** [comment]
Well, well .. all have a little bit right .. but .. Google loves my SEF url's .. and also my mobile design ;-)

**Comment by live627** [comment]
Google also loves regular URL formats just as much. And besides, there are third party mods that do a better and more of a complete job.

The concept of SEF URLs is a hoax today, leftover from decades ago when they actually provided value beyond purely psychological.

**Comment by socram8888** [comment]
Neither nginx nor Lighttpd support `.htaccess` files. I say -1 on removing those `index.php` files.

**Comment by Oldiesmann** [comment]
Nobody said anything about removing the index.php files. We're talking about search-engine friendly URLs and removing SMF's outdated implementation of it (since it doesn't work on all servers and there are better options from third-party mods if you want that feature).

**Comment by socram8888** [comment]
Ah sorry, misunderstood it. I though you were talking about removing protection `index.php` and relying on `.htaccess` to protect those files.

Still, I am against _removing_ current implementation. Why remove it at all? If you don't want it, just disable it on the control panel.

Removing it could cause a massive amount of links to stop working. This is not like removing obsolete BBcode, which is as simple as replacing them with a newer equivalent on your DB. Other websites may link to your forum, and if you ever relied on it, cause those links to stop working.

If this can be implemented in a mod that does not modify `Sources` folder (updating to newer versions with a modded `Sources` folder is a real mess), using hooks for instance, I won't have any complainment.

**Comment by Rupurudu** [comment]
We really don't need index.php at all. Unless server admin sets default document something other than "index.php" (like default.php, default.asp...) it will work without index.php 

/Sources/QueryString.php
Find: `$scripturl = $boardurl . '/index.php';`
Replace: `$scripturl = $boardurl . '/';`

Example:
Old style urls: `http://localhost/index.php?topic=1.0`
New style urls: `http://localhost/?topic=1.0`

**Comment by Oldiesmann** [comment]
And if we do that, we have to implement a redirect to account for all the boards that have URLs indexed _with_ index.php in the URL, which is more overhead for something that really has no benefit whatsoever.

**Comment by Rupurudu** [comment]
Why? URLs with Index.php still work properly.

**Comment by Oldiesmann** [comment]
Because Google and other search engines will see "/index.php?topic=x.y" and "/?topic=x.y" as two completely separate URLs that display the exact same content.

**Comment by mkress** [comment]
For this canonical attribute is the solution : 
http://kress.it/2009/08/canonical-tag-bzw-canonical-attribut-gegen-duplicate-content/

**Comment by Oldiesmann** [comment]
We actually already have that, but there's no reason to change the URLs to drop index.php from them as Google will still crawl them just fine.

**Comment by Rupurudu** [comment]
@Oldiesmann It's not related to crawling, it just looks shorter and nicer. I already added this to my forum, I don't have any issues.
