### ISSUE TITLE
likes popup wrong icon in corner

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2947]
in the left corner of the like popup it has the question mark icon, it should have something more "like" like.

**Comment by margarett** [comment]
Let's make this a 2-in-1 issue
http://www.simplemachines.org/community/index.php?topic=538421.0

When using a rectangular avatar the image overlaps with the username

**Comment by XinYenFon** [comment]
Fix;

```
ul#likes span.avatar {
    width: 45px;
    height: 45px;
    padding: 2px;
}
ul#likes span.avatar img {
    max-height: 40px;
}
```

Replace with;

```
ul#likes span.avatar {
    max-width: 100px;
    max-height: 100px;
    padding: 0 10px 0 0;
}
ul#likes span.avatar img {
    max-height: 90px;
    max-width: 90px;
}
```
