### ISSUE TITLE
version check missing versions to compare with

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2950]
the background tasks files do not have a current version listed like the Sources etc do.

also some templates are missing the compare to version
ReportToMod.template.php
ReportedContent.template.php

and some Sources files...
ReportToMod.php
Topic.php

**Comment by Oldiesmann** [comment]
Missing files have been added to the detailed versions file, so that part will be fixed when the Fetch Simple Machines Files task is run again. The tasks files are already listed, so I need to figure out why that part isn't working.

**Comment by Oldiesmann** [comment]
Finally got a chance to play with this some more and figured it out. It was a combination of incorrect filename specifications in the detailed version JS file on our end and some missing code in SMF. I'll commit appropriate fixes shortly and upload a fixed file to the site as well.

**Comment by Oldiesmann** [comment]
Updated the file on simplemachines.org as well.
