### ISSUE TITLE
topic.js expandThumb() doesn't respect screen size

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#2962]
Need to get the aspect ratio of the full image and resize it to match the current screen size.

**Comment by XinYenFon** [comment]
sorry for the dumb idea I'm throwing but max-width: 100% isn't enough to fix overflowing ? Instead working with aspect ratio and JS calculations ?

**Comment by MissAllSunday** [comment]
En Tue, 04 Aug 2015 12:00:36 -0500, Mert Alınbay  
notifications@github.com escribió:

> sorry for the dumb idea I'm throwing but max-width: 100% isn't enough to  
> fix overflowing ? Instead working with aspect ratio and JS calculations ?
> 
> —
> Reply to this email directly or view it on GitHub.

yep that would be enough, the Js approach is to make sure the width and  
height is kept constant (in relation to whatever html element is  
containing the image) no matter where the bbc_img img is been displayed.

If you are sure this will work well on all places that could show an  
attached image: display, recent, ssi, pms, etc etc then yeah that would be  
a better approach.

**Comment by XinYenFon** [comment]
if bbc_img class is shown on the places you mentioned yes, adding max-width: 100% to bbc_img (or bbc_img img) is fairly enough to solve the issue.

**Comment by Oldiesmann** [comment]
The bbc_img class is only used for the img bbcode tag to my knowledge. I don't think it applies to attachments at all.

**Comment by XinYenFon** [comment]
would it be wrong to add bbc_img class to images in attachment ?

**Comment by MissAllSunday** [comment]
En Tue, 04 Aug 2015 13:40:18 -0500, Michael Eshom  
notifications@github.com escribió:

> The bbc_img class is only used for the img bbcode tag to my knowledge. I  
> don't think it applies to attachments at all.
> 
> —
> Reply to this email directly or view it on GitHub.

The expanded attachment thumbnail can be handle quite easy by adding a new  
class for it.  We aren't talking about this particular case.

The img_bbc class does get applied to any img posted via BBC img tag, we  
are discussing if max-width will work well on all possible vanilla places  
where a message can be displayed.

**Comment by XinYenFon** [comment]
It needs to be otherwise its a bug :P
