### ISSUE TITLE
WYSIWYG editor issue

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2966]
check in your profile that WYSIWYG is DISABLED.

go in quick reply and type something as simple as "test" then highlight it and click the icon to bold it, it shows you 

```
[b]test[/b]
```

now check the status of the toggel to WYSIWYG, does it have the button activated? does it have a tooltip to view source? it should not, you are not in WYSIWYG mode.

![](http://imagizer.imageshack.us/v2/394x168q90/661/oEZxJV.png)

looks like the same in the full reply page as well.

**Comment by margarett** [comment]
Is this still an issue? I think it works fine or I can't really see the problem :(

The only think which is possibly wrong is the "View Source" text, which is always the same no matter if you're on WYSIWYG mode or not, but the button function is "View Source", so it is "pressed" when on "code mode" and "not pressed" when on "WYSIWYG mode"

Or am I missing the problem completely? :tongue:

**Comment by illori** [comment]
That is the issue.

**Comment by margarett** [comment]
The text? So would something like "Toggle View" (like 2.0 has) work better? (because I don't think it's worth to have a dynamic text, javascript and whatnot...)

**Comment by illori** [comment]
No the button status is reversed.

The text? So would something like "Toggle View" (like 2.0 has) work better?
(because I don't think it's worth to have a dynamic text, javascript and
whatnot...)

**Comment by margarett** [comment]
I'm not sure it is, really. The button meaning is really "view source", so its status is "clicked" when out of WYSIWYG mode.

**Comment by XinYenFon** [comment]
What you say is correct on one point but "View Source" is not false/wrong either. I think "Toggle View" is not really explaining things "toggle to what? which view?" but when activated its clear that you are seeing the "source". This is not related to Editor more like a Language problem to me.

**Comment by frandominguezl** [comment]
Is this still an issue, @illori ? I think the behaviour is correct

**Comment by illori** [comment]
if i dont have the WYSIWYG editor enabled the toggle button says "view source" IMO it should only say that when you want to see the code that is used in the editor not to switch to WYSIWYG view.

the text on the button does not change when you do enable WYSIWYG, so maybe it should just have a toggle text instead of view source if it cant change when you click the button to change the status.

**Comment by XinYenFon** [comment]
@illori on latest build, icons on editor has proper active background. It should be clear enough for users. I'm still on the side that this is not an issue (nor the View Source needs change on toggle).

**Comment by NanoSector** [comment]
Can this be closed?

**Comment by Sesquipedalian** [comment]
Yup.

**Comment by illori** [comment]
sorry re-opening this issue. if you do NOT have the WYSIWYG editor enabled, and can view the code of the bbc the button says view source, this toggles you into the WYSIWYG editor where you dont see the code. the text on the icon does not change at all depending on which mode you are in. can change it to toggle editor or similar? as it is not correct right now.

**Comment by Sesquipedalian** [comment]
You're persistent, @illori, I'll give you that. But still, this the standard behaviour of SCEditor, and I don't see a compelling reason to override it. When the button is in active state, the user is viewing the source code of their message. It is the same behaviour as, say, the bold button. When the cursor is in the middle of some bold text, the bold button is shown in active state, but we don't change the tooltip text of the button to "Unbold" when it is in active state. That would be confusing. Likewise, it would be confusing if the tooltip of the "View Source" button changed to "View WYSIWYG" when the button was in active state, since the point of the active state is to communicate to the user "You are in fact viewing the source right now."

**Comment by illori** [comment]
in SMF 2.0 it says toggle view, i think that is better then what we have now. i think the current option is not correct. this is not a major change but i think it is necessary to be done.

**Comment by Sesquipedalian** [comment]
The majority opinion has disagreed with you. https://is.gd/AtxzEl :)

**Comment by illori** [comment]
That is too bad. We just need to change one text string.

On Mar 1, 2018 12:03 PM, "Jon Stovell" <notifications@github.com> wrote:

The consensus opinion has disagreed with you. https://is.gd/AtxzEl :)

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/SimpleMachines/SMF2.1/issues/2966#issuecomment-369660005>,
or mute the thread

**Comment by Sesquipedalian** [comment]
Actually no, we would need to do a bunch of work to override SCEditor's internals. It's really not worthwhile for such a minor change (even if the majority agreed that there was anything wrong with the default behaviour to begin with).
