### ISSUE TITLE
Problem with permutations

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#2973]
ref http://www.simplemachines.org/community/index.php?topic=538611.0

**Comment by live627** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/2975

**Comment by joshuaadickerson** [comment]
@Sesquipedalian did you do any benchmarks or testing?

**Comment by Sesquipedalian** [comment]
> did you do any benchmarks or testing?

Probably.
