### ISSUE TITLE
error on upgrade

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2977]
-  +++  Upgrading post notification settingsUnknown column 'notify_regularity' in 'field list'

**Comment by illori** [comment]
seems that after the column has been removed it errors out if the upgrade is run after as the column does not exist.

**Comment by illori** [comment]
still getting the same error...

**Comment by Oldiesmann** [comment]
Adding 'db_error_skip' => true to the parameters array there should fix the issue. Alternately you can show the columns in the members table (SHOW COLUMNS LIKE 'notify_%') and then only do the select if those columns still exist.
