### ISSUE TITLE
why ..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#2982]
.. show the bottons (text and image, no link) in the board view
Poll
Moved Topic
Locked Topic
Sticky Topic
for members they have no rights to use this function?

**Comment by XinYenFon** [comment]
its for explaining not to do the job.

**Comment by PortaMx** [comment]
hmm .. very confusing

**Comment by XinYenFon** [comment]
really? I always find it helpful to understand the icons especially on custom themes.

**Comment by Rupurudu** [comment]
It's not confusing to me, but they are unneccesary. These icons should be self-explanatory.

**Comment by XinYenFon** [comment]
Mostly true but custom themes may use icons based on the content that may be confusing for newbie users.
