### ISSUE TITLE
Print page

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#2994]
Shall we remove the printpage action and use the media style in CSS?

**Comment by XinYenFon** [comment]
Seems good to me, but is there any demo ?

**Comment by live627** [comment]
https://github.com/SimpleMachines/SMF2.1/archive/release-2.1.zip

**Comment by XinYenFon** [comment]
meh... I was asking the demo of suggested changes... Not the current printpage stuff.

**Comment by Rupurudu** [comment]
Print page also does several changes to content, like showing urls of text links and images. Can we achieve same thing with CSS?

**Comment by XinYenFon** [comment]
Actually yes, http://davidwalsh.name/optimize-your-links-for-print-using-css-show-url but action is still looks better since we cannot toggle image/non-image mode in Ctrl+P mode.

**Comment by illori** [comment]
in 2.1 apparently more has been added to the print page option. text only and text with images. i dont think we could do both those options with just css.

**Comment by XinYenFon** [comment]
I'm curious actually while you see styled print page with "Print" action, if you go Print mode at your browser (at least on Firefox) it ignores whole CSS/Style, if you print on page (report page) it ignores some style. But I think its better to have Print action, we can use that feature for marketing at some point as well.
