### ISSUE TITLE
Implement OpenSearch?

### ISSUE THREAD

**Issue by BitFros7y** [SimpleMachines/SMF#2998]
How about implemening OpenSearch into SMF? Its not that hard as far as i know. One problem could be Internet Explorer 7 because it does not support POST method, but I dont see how anyone would use it these days...Other than that its just a simple XML file and a json return for suggestions (if im right you dont have to provide suggestions, its optional). I know that most people dont see a point in such feature but a simple example would be a search in chrome. Just input youtube, press tab and you are searching youtube, now imagine that being possible for all your favorite forums running SMF. Firefox is a bit different as it has special input field for search engines and having to much search engines can bloat that tab, but for a big forums or some that you visit often it can be very useful...

**Comment by Kindred-999** [comment]
something for 3.0 maybe -- or a mod for 2.0 and/or 2.1 -- this is too big a feature to be added at this point in time, IMO.   I am also not certain what benefit this provides for a SITE that the existing sitemap type XML mods would not already provide....

**Comment by BitFros7y** [comment]
Actually its not big feature at all. A mod would do the job just like for anything else, but it is a mod, out of box would be way better. Anyway, sitemap has nothing to do with OpenSearch. Consider OpenSearch as standard for pointing browser to your search engine (In SMF case search form using post method if im not wrong). Basically what we would do is add XML file that would point to the link to search whole forum. Just like some themes add fast search to header, about the same principle is used, only instead of form that uses html, we would use xml file intended for OpenSearch (It is implemented in IE,Firefox,Chrome, dont know about opera and safari but im pretty sure it is).

**Comment by Oldiesmann** [comment]
Adding the bare basics (an xml file with the info) should be quite easy to do. Getting it to return suggestions/results is a much bigger task though - possibly something that could be added in a future version or via a mod.

**Comment by BitFros7y** [comment]
Well suggestions are optional, but also if they were not, why just not add a single php file to handle them? That way we would not load anything we dont need... Also OpenSearch does not expect return for results, it just sends you to search page. If your post form is  mysite.com/search.php?THESE_IS_SEARCHED_STRING  then OpenSearch would send request to that url, with the string you just searched and method defined in XML (POST/GET).

**Comment by MissAllSunday** [comment]
Definitely mod material.
