### ISSUE TITLE
"Receive message body in e-mails" option broken

### ISSUE THREAD

**Issue by socram8888** [SimpleMachines/SMF#3003]
`notification_reply_once_body` is not defined on `Themes/default/languages/EmailTemplates.english.php`, so it dies with:

```
The email template "notification_reply_once_body" could not be found.
```

on `cron.php`. Creating a new template should be enough.

Also, `MESSAGE` replacement seems to be raw BBcode which is kinda a bad idea to send to users on an email. It could be interesting adding a "can_email" or equivalent boolean to BBcode array so we could run `parse_bbc` and send resulting blob.

**Comment by MissAllSunday** [comment]
The default English language does have that text strings, you most likely are using another language or outdated English files, I had the same issue with Spanish language been outdated.

**Comment by socram8888** [comment]
No. It does have an string called like that but it doesn't have the template. Note string `notification_reply_once_body` is the body for `notification_reply_once` template.

Template `notification_reply_once_body` needs strings `notification_reply_once_body_subject` and `notification_reply_once_body_body`, which are not available as of now.

Check https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Post.php#L2664-L2665.

**Comment by MissAllSunday** [comment]
It seems its defined as "notification_reply_once_subject" https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/languages/EmailTemplates.english.php#L658

I don't think it needs to be "notification_reply_once_body_subject"  body and subject are two separate strings, the common key in this case is "notification_reply_once"  so the strings should be:

notification_reply_once_body  and notification_reply_once_subject.

**Comment by socram8888** [comment]
`notification_reply_once_subject` and `notification_reply_once_body` are subject and body templates for `notification_reply_once`, which is sent to users when somebody replies on a thread. These are not related to this bug.

`notification_reply_once_body` is another kind of notification, exactly the same as `notification_reply_once`, but it also contains the body of the new post. It is sent if users checks "Receive message body in e-mails" in their notification configuration. This template needs new strings called `notification_reply_once_body_subject` and `notification_reply_once_body_body` (note body appears twice).

**Comment by Oldiesmann** [comment]
We have existing strings for that template - they're just named `template_reply_body_once` instead of `template_reply_once_body`. It needs to be changed in one of the files.

**Comment by socram8888** [comment]
Well IMHO updating Subs-Post.php would be a better approach, given translations are already using `template_reply_body_once`.

**Comment by socram8888** [comment]
Should be fixed. I'm closing this.
