### ISSUE TITLE
a few more issues in upgrade.php

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3011]
+++  Upgrading post notification settingsError: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, boolean given File: D:\wamp\www\github2.1\upgrade.php(2587) : eval()'d code Line: 9Error: mysqli_free_result() expects parameter 1 to be mysqli_result, boolean given File: D:\wamp\www\github2.1\upgrade.php(2587) : eval()'d code Line: 22 done.
-  +++  Replacing [br] with &lt;br&gt; done.
  why starting with *? the similar lines following dont, also it should show the brackets IMO.

**Comment by Oldiesmann** [comment]
I'm not sure why that line would be starting with a \* as the comment for that particular step is exactly the same format as it is for all of the other bbcode tags we're replacing. I'm also not sure what you mean by "it should show the brackets", as it already should show the < and > unless HTML doesn't get parsed in the comments.

**Comment by illori** [comment]
The angel brackets did not show, just the html entities. That is when
running in cli.

**Comment by Oldiesmann** [comment]
Ok. I'm not sure if we can fix that though, as fixing it for cli would cause it to break for the regular method.

**Comment by live627** [comment]
Most people don't use CLI  to upgrade.

**Comment by illori** [comment]
i bet most if not all of the big boards do.

even so that leaves the first error to be fixed.

**Comment by live627** [comment]
OK, I found the offending code in 3073e3a6f291b45a05241faf8313d43135a2ad82
and will send in a patch shortly.

**Comment by margarett** [comment]
@live627 did you forget to PR this here?

**Comment by live627** [comment]
https://github.com/live627/SMF2.1/commit/85effb8f124bb5b39fac87a020a7739a2a7095da

**Comment by live627** [comment]
https://github.com/SimpleMachines/SMF2.1/commit/85effb8f124bb5b39fac87a020a7739a2a7095da
