### ISSUE TITLE
Subresource Integrity

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3021]
Google has recently added support for a feature called [Subresource Integrity](https://googlechrome.github.io/samples/subresource-integrity/index.html).  I believe this is a feature we could implant, even though it only supports Chrome at this time,.

To do this we would need to look at the proper way to set this up such as
- Add a table to track css and js files per theme, filename and their base64 encoded sha256 (I believe this is the correct method)
- Setup a way to generate the css/js code (which we sorta do have/use) to add in the integrity as needed).
- Setup a way to allow them to be regenerated.
- Make sure mods do not modify standard css/js files and use a custom one instead
- Additionally when a modification changes the custom css/js to regenerate the integrity hash for those files.
- SMF Patches/Upgrades need to regenerate the hash as well.

**Comment by Oldiesmann** [comment]
The only issue I see with this is that it makes things more complicated because the hashes would have to be regenerated after the file is modified. Many people wouldn't want to have to go through an extra step just so they can modify their file.

**Comment by jdarwood007** [comment]
Which is why I suggested we educate people on using custom.js/css files instead.  We can set it up so custom.js/css doesn't have a integrity check (as a setting).  We could also make it so editing it via the admin panel would update their hash as well.

Only thing that they don't allow is a developer type mode where a warning would occur rather than not loading, which would work better for people to develop on.  We could technically build that ourselves I guess, but rather not.

This would also mean we should have a way to turn that off, as not loading js/css I believe can prevent things from working right or even getting through the admin center.  Additionally repair settings would need to repair this as well (simple fix once we lay the ground work in the code).

The biggest thing here is if something modifies the code outside of SMF and doesn't fix the integrity hash, that it would prevent the file from loading.  Which is a good thing if a site was hacked and something like malicious javascript was inserted into the js files.

**Comment by albertlast** [comment]
i was looking at some of my fav web side no one is using this featue -> no need -> can we close this?

**Comment by Sesquipedalian** [comment]
This doesn't seem necessary to me when we are trying to get RC1 out the door.
