### ISSUE TITLE
Packages get uploaded with chmod 777

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#3025]
This causes a server error on my system (and likely other systems) which does not allow 777 permissions.  All of my files are 644 and directories are 755. The Package manager should use the MINIMUM chmod permissions, not the maximum.

**Comment by Oldiesmann** [comment]
I see that... I have absolutely no clue why that's done though. We don't overwrite the file at all (if you try to upload it and it already exists, you get an error saying so), and there's no reason we need to make them executable at all since you can't execute an archive - you're just reading and extracting its contents.

**Comment by margarett** [comment]
Back from the dead, there are quite some places where we specifically chmod(0777)
For this particular case I supposed we're talking about PackagesGet.php

```
    // Now move the file.
    move_uploaded_file($_FILES['package']['tmp_name'], $destination);
    @chmod($destination, 0777);
```

IMO this should be handled (and it shouldn't be very difficult to do). In some places we perform successive chmods up to 777, we should stop earlier:

```
    // @todo: chmod (especially with some servers) is usually bad
    if (!is_writable($directory))
    {
        chmod($directory, 0755);
        if (!is_writable($directory))
        {
            chmod($directory, 0775);
            if (!is_writable($directory))
            {
                chmod($directory, 0777);
                if (!is_writable($directory))
                {
                    $context['dir_creation_error'] = 'attachments_no_write';
                    return false;
                }
            }
        }
    }
```

**Comment by Kindred-999** [comment]
Can we please fix this?  It can actually cause a complete site shutdown on some hosts...

**Comment by margarett** [comment]
I'm willing to look into this but in my Windows system I can't replicate. If someone offers me some access to a server which won't accept 777 and FTP access (cPanel would be great - FTP takes ages to transfer) I'll try to check it

**Comment by Kindred-999** [comment]
I can give you access to one of my linux sites...    it doesn't completely shut down on 777. but the cpanel filemanager does highlight the permissions assignment as a security risk -- I usually have to do a recursive chmod to set things right.

**Comment by margarett** [comment]
I'm installing a LAMP virtual appliance, if i can't make this work I'll request your access details ;)

**Comment by MissAllSunday** [comment]
@Kindred-999 can you try the files in this branch https://github.com/MissAllSunday/SMF2.1/tree/stuff

I have no idea how the ftp class works so the change to that class might not do anything as I don't know if the class can write multiple times

**Comment by MissAllSunday** [comment]
OK, been doing some tests on my extremely picky server, even my infamous OharaYouTube package doesn't produce any 500 errors and zip packages are uploaded as 644, files are unzipped as 644 too.

I still haven't tested this with a mod that does file edits though.

**Comment by margarett** [comment]
I set up a LAMP VM before vacations which also triggers errors 500 on 777 (does it out of the box which is great :tongue:) I'll test tonight. If I remember how to run it that is :laughing:

**Comment by Kindred-999** [comment]
I will see if I can get some testing done this weekend on that branch.

**Comment by MissAllSunday** [comment]
Any luck?

**Comment by Kindred-999** [comment]
Sorry....    I did test and can not seem to cause the 500 error now.   So, with Suki's branch I think we can mark this tentatively fixed :) pending wide testing.
