### ISSUE TITLE
package manager broken

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3029]
if you try to install https://github.com/margarett/CustomAction_new mod it fails to parse every action. this seems a recent issue. maybe related to https://github.com/SimpleMachines/SMF2.1/commit/e99334a76e638412013b695b4a60514fd8c13932 ? i can still install the solosmileys pack but mods are failing to install.

**Comment by illori** [comment]
actually related to https://github.com/SimpleMachines/SMF2.1/commit/e1fb2cede2e6e671010abe0bde8b064ccec93956

removing 

```
, RecursiveIteratorIterator::SELF_FIRST
```

seems to make the package manager work again. with that removed the smiley package seems to still install fine. even with the @ removed it seems to work fine for the smiley package.

**Comment by illori** [comment]
nope i was wrong, it does break the smiley package. it has the original issue again. #2929

**Comment by live627** [comment]
god damn, I hate regressions.

**Comment by live627** [comment]
Okay, II think I figured it out. The code to create the dir was simply missing..
