### ISSUE TITLE
[Github] Allow people to assign themselves to the issues.

### ISSUE THREAD

**Issue by Rupurudu** [SimpleMachines/SMF#3031]
On every issue there's a little thing on the right for us to see who is working on this issue. Currently it looks like no one can assign issues.

Allow us to assign ourselves into issues, so we can show we are working on this.

**Comment by XinYenFon** [comment]
You can tag an dev/admin to ask it actually. I don't think many more will benefit from it.

**Comment by live627** [comment]
GitHub only allows contributors to assign issues, and even then, only contributors can bee assigned.

**Comment by XinYenFon** [comment]
cool :feet:
