### ISSUE TITLE
Incorrekct speeling 

### ISSUE THREAD

**Issue by StealthWombat** [SimpleMachines/SMF#3032]
index.template.php 

$txt['forum_in_maintainence']

Should be "maintenance". Yeah. I know. English is weird.

**Comment by illori** [comment]
that means in index.english.php the string has be corrected as well.

**Comment by StealthWombat** [comment]
Yup. Potentially in index.any_language.php, but it's only a quick find/replace on that directory.

I suppose the same string might be lurking in one or two other templates as well.

**Comment by illori** [comment]
they are not, i did a search and it came up in that one only.

**Comment by StealthWombat** [comment]
Well, killed PR last night. Then tried reversing commits so I could apply them all over again. Couldn't figure out WTF GitHub was doing there, so just killed the whole repo. Yay! :dancers: 

Will make new repo today and re-do the PR.

**Comment by XinYenFon** [comment]
that's why you need to use "branches". If you fail to do it properly on one branch, you just kill the branch and create different one.

**Comment by StealthWombat** [comment]
Kill repo good. Me like kill repo. :+1:

**Comment by XinYenFon** [comment]
:feet:

**Comment by StealthWombat** [comment]
Why feet? 

Anyway: https://github.com/SimpleMachines/SMF2.1/pull/3068
