### ISSUE TITLE
Presentation in Sources again

### ISSUE THREAD

**Issue by StealthWombat** [SimpleMachines/SMF#3033]
```
    // Are we showing debugging for templates?  Just make sure not to do it before the doctype...
    if (allowedTo('admin_forum') && isset($_REQUEST['debug']) && !in_array($sub_template_name, array('init', 'main_below')) && ob_get_length() > 0 && !isset($_REQUEST['xml']))
    {
        echo '
<div style="font-size: 8pt; border: 1px dashed red; background: orange; text-align: center; font-weight: bold;">---- ', $sub_template_name, ' ends ----</div>';
    }
```

Ok, so why does this have to be defined by inline CSS? Why not just bung an existing class on the div and be done with it? Some admins may not want the thing having an orange background and a dashed red border. I sure wouldn't. That'd be as ugly as a sack full of arseholes.

It's only a notification of a template name.

**Comment by illori** [comment]
since it is only for debugging, i really dont see the issue here.

**Comment by live627** [comment]
Here it is using warningbox

![fireshot screen capture 054 - my community - index - localhost_smf2_1_index_php_debug](https://cloud.githubusercontent.com/assets/431799/9704040/89c8d172-544c-11e5-8c36-a1759c2408fe.png)

**Comment by illori** [comment]
how do we enable this?

**Comment by live627** [comment]
append `;debug` to any url

**Comment by illori** [comment]
so yet another way to enable a debug mode... i wonder if the normal debug we can enable in settings.php should also have an option to put this on as well. how many people know that you can add that to the url and get additional output? i bet very few.

**Comment by live627** [comment]
Hey, even you did not know that.

**Comment by StealthWombat** [comment]
"since it is only for debugging, i really dont see the issue here."

Just extra crud that isn't needed.

`<div style="font-size: 8pt; border: 1px dashed red; background: orange; text-align: center; font-weight: bold;">---- ', $sub_template_name, ' ends ----</div>`

compared to

`<div class="warningbox">---- ', $sub_template_name, ' ends ----</div>`

Less crud is good, yes? Not hard to change either.

The other point is that if it calls a class that is already styled for the theme in question it will potentially be more legible.
