### ISSUE TITLE
More deprecated CSS - Oh si, we have a plethora - body#help_popup

### ISSUE THREAD

**Issue by StealthWombat** [SimpleMachines/SMF#3042]
This one is a leftover from the old 2.0.x and 1.1.x help pop-ups that were nailed to the top left of the screen. Superseded by the nifty new ones that take over the whole screen. Yay! AFAIK this has no purpose any more. Index.css:

```
/* Help popups require a different styling of the body element. */
/* Deprecated? */
body#help_popup {
    padding: 12px;
    box-sizing: border-box;
}
```

**Comment by XinYenFon** [comment]
function template_popup seems still using this. But I'm not sure we are using that function or not.

**Comment by StealthWombat** [comment]
I don't know about that function in Likes.template stuff since that came in after I was off the team. The one in Help.template is the old help pop-ups, which are gone with the wind. So if it's being used it'd only be in likes.

**Comment by StealthWombat** [comment]
Oh yeah, speaking of likes, there's a lot of superfluous taggy stuffz up top in index.css.

```
ul#likes li {
    clear: both;
}
ul#likes span.avatar {
    width: 45px;
    height: 45px;
    padding: 2px;
}
ul#likes span.avatar img {
    max-height: 40px;
}
ul#likes li span.description {
    font-style: italic;
    opacity: 0.4;
    padding: 0.4em 0.7em;
    font-size: 0.9em;
}
```

You can't get more specific than an id, so I can't see any need to call the ul tag there. I assume that any .avatar inside #likes would be a span, since I can't see there being more than one type of element holding avatars. Same with .description. So this should be just as effective:

```
#likes li {
    clear: both;
}

#likes .avatar {
    width: 45px;
    height: 45px;
    padding: 2px;
}
#likes .avatar img {
    max-height: 40px;
}
#likes .description {
    font-style: italic;
    opacity: 0.4;
    padding: 0.4em 0.7em;
    font-size: 0.9em;
}
```

**Comment by StealthWombat** [comment]
Oh crappery. :P Just took a look at Likes.template.php. Has a bit more stuff that could be tidied up.

It's sharing similar markup to the #top_menu stuff that was mentioned in #3047, so really it'd make sense to sort it out the same way for consistency. May be able to save some CSS here if the same can be used for both places.

I'll set up some extra bods on local and play around with likes a bit. I know the br class="clear" can be
ditched, since all that is doing is allowing the finishing text to clear the floated li content. Use inline-block instead of float and that problem will vanish.

I'll see if I can get a pull request together tonight to sort the whole lot out at once. :)

**Comment by XinYenFon** [comment]
@StealthWombat I'll look into the body#help_pop thing next ( I just have exams till next monday --postponed one due to bad weather ).
