### ISSUE TITLE
Possible leaner markup for board and topic index

### ISSUE THREAD

**Issue by StealthWombat** [SimpleMachines/SMF#3052]
Just thinking a bit more. This is not essential as the markup is fairly lean anyway and the CSS isn't too bad, but it would be possible to simplify the board index and topic index even further.

At the moment it's basically:

```
    <div class="up_contain">
        <div class="board_icon">
            <a class="board_', $board['board_class'], '"></a>
        </div>
        <div class="info">
            Lotsa stuff
        </div>
        <div class="board_stats">
            <p>
                Stats stuff
            </p>
        </div>
        <div class="lastpost">
            <p>
                Last post stuff
            </p>
        </div>
        <div class="children">
            <p>
                <strong>', $txt['sub_boards'], '</strong>: List of child boards, not formatted as list
            </p>
        </div>
    </div>
```

The .board_icon div is of dubious value. If the anchor inside it is set to display: table-cell; it could easily take the place of the div. The anchor would just become another block level element anyway, and the board icon class could be chained with its other classes.

The .info div realistically has to stay the way it is now.

The .stats div is another matter, because the paragraph tag within it is another block level element anyway and is quite capable of doing the same job. The same goes for the .lastpost div.

The child boards could be simplified and given better semantics. This is a situation which really is ideal for a definition list.

So the leanest markup would look like this:

```
    <div class="up_contain">
        <a class="board_icon board_', $board['board_class'], '"></a>
        <div class="info">
            Lotsa stuff
        </div>
        <p class="board_stats">
            Stats stuff
        </p>
        <p class="lastpost">
            Last post stuff
        </pv>
        <dl class="children">
            <dt>', $txt['sub_boards'], '</dt>: ', implode('<dd>', $children, '</dd>'), '
        </dl>
    </div>
```

Offhand I can't think of any real disadvantages for this way of doing it, and I have tried to think of alternative presentations. It drops 3 divs from every board (4 if there are child boards), gives better semantics, and actually allows _more_ styling options for the child boards via CSS.

The comma between child boards would not need to be forced in the template. It could be handled with :after, allowing anyone to change the content of the pseudo if they wanted something different (like / or - or | or whatever). Yes, I have wanted something different sometimes. ;)

ETA: Oh and I'm not sure that "up_contain" is a sensible class name for the board wrapper div. I think something like "board_row" would be far more descriptive for practical purposes.

It would also be useful if the forum categories were given a default css class (forum _category being an obvious option) just for extra styling hooks. At the moment they're pretty near impossible to target without borking something else AFAICT.

**Comment by XinYenFon** [comment]
div's for table-cell display, you can't show element (a) on both table-cell & inline-block, also for responsive side that place needs min-width and paddings.

moved child comma to CSS

up_contain needs new name from day 0 :P but I'm not good with naming so I just picked something makes some sense (upper_container or up_contain at that time).

"forum categories" ? :( kinda confused ?
