### ISSUE TITLE
Where can I send pull requests to SMF tools?

### ISSUE THREAD

**Issue by Rupurudu** [SimpleMachines/SMF#3053]
Like repair_settings.php They are not in the github. :confused:

**Comment by XinYenFon** [comment]
https://github.com/SimpleMachines/tools

**Comment by Rupurudu** [comment]
Thanks!

**Comment by Rupurudu** [comment]
It looks like even @live627 don't have access and no one merges the pulls here. I should re-open this...

**Comment by illori** [comment]
send oldiesmann a pm on sm.org and he can take care of it for you. no idea why devs cant merge/commit in the tools repo.

**Comment by Oldiesmann** [comment]
Not sure why he doesn't have access. I'll look into that though.

**Comment by Oldiesmann** [comment]
Developers (live627, Dragooon and MissAllSunday) have access to that repo now. Not sure why that was never set up before though.

**Comment by Rupurudu** [comment]
@Oldiesmann Can you check the pull requests and merge them into master? (and replace the files at simplemachines.org?)

**Comment by colinschoen** [comment]
This should probably be closed.
