### ISSUE TITLE
Using protocol-relative urls brokes links in the sent mails and http <-> https redirection.

### ISSUE THREAD

**Issue by Rupurudu** [SimpleMachines/SMF#3054]
Many email providiers don't make urls clickable if they are not starting with http or https.

We should always add http: (or https: if we are defaulting to https:) when sending emails if $scripturl starts with //

Or we can sent HTML styled mails...

**Comment by Rupurudu** [comment]
It also brokes http to https redirection. Enable HTTPS for entire forum, then use http link to the forum

URL is malformed like this: http://example.net//example.net/index.php?

**Comment by Rupurudu** [comment]
Ugh... Just forget about it. The entire SSL mode is completely broken. I think I'll find the commit for the current implementation, undo it, then make something from the beginning.

**Comment by MissAllSunday** [comment]
Is this a real issue?  SMF by default does not use protocol-less on $scripturl and $scripturl shouldn't be changed like that.

**Comment by Rupurudu** [comment]
It was an issue on SMF 2.0. I was configured my server to accept both http and https requests. People started complaining that links in the mails are not clickable. Most mail programs only makes http and https links clickable by default.

On SMF 2.1 It also broke https redirection when SSL mode is set to always https.

Another issue I found is SSL for Auth is not working even when $scripturl is starting with http or https. The login page is still sent with http. There is no green padlock sign is visible.

As a result, both SSL security modes are somewhat broken on multiple aspects. I'm still trying to improve it but things will go slow because my lack of knowledge on php.

**Comment by MissAllSunday** [comment]
I mean, if this is an actual issue with SMF itself.  

You shouldn't remove http or https form $scripturl.  protocol-less urls are fine for external links, most notably css and js files but making your entire site protocol-less its a really bad idea. Stick with either http or https and use .htaccess to redirect traffic to one or another.

**Comment by Rupurudu** [comment]
Okay. But this still not explaining why SSL for Auth is not working.
