### ISSUE TITLE
Small Smiley bug ..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3057]
If you use the first smiley  - code :-) and the last smiley - code :-)) in the same context, the last smiley is shows as the first with a ) at right ...

To solve this, change the last smiley code (as example) to ;-') and all works as well ...

**Comment by Oldiesmann** [comment]
Sounds like we need to properly sort the smileys by code when pulling them from the database. The table used to be automatically force-sorted that way (ALTER TABLE ... ORDER BY length(code) DESC), but PostgreSQL doesn't support that at all and I don't think that works with InnoDB tables either. Should be pretty easy to fix though.

**Comment by Oldiesmann** [comment]
I'm not sure why you're running into that issue actually, as the query to pull the smileys is ordering the results as it should:

```
                $result = $smcFunc['db_query']('', '
                    SELECT code, filename, description
                    FROM {db_prefix}smileys
                    ORDER BY LENGTH(code) DESC',
                    array(
                    )
                );
```

Because of this, it should parse :-)) first

**Comment by live627** [comment]
This sounds like the board ordering issue all over again. The fix is to
sort the list in PHp.

**Comment by PortaMx** [comment]
I change the order and all works as well ;-)

**Comment by PortaMx** [comment]
uhm .. more problem .. smiley code >:( and >:D are not detected correct. 
But here do not help sort. I think the routine (sarch/replace) is buggy ...

**Comment by Oldiesmann** [comment]
I'm not sure why you're having problems. Both of those smileys work fine on my test board, as does `SELECT * FROM smf_smileys ORDER BY LENGTH(code) DESC;`

**Comment by PortaMx** [comment]
Look at the images:
1 insert smiley in wysiwyg mode
2 after switch to normal mode
3 switch back to wysiwyg mode ,,,
![image1](https://cloud.githubusercontent.com/assets/2270223/9856291/0ca5f08e-5b14-11e5-91a2-d0d09d57e3aa.png)
![image2](https://cloud.githubusercontent.com/assets/2270223/9856298/1581e32a-5b14-11e5-81f6-05a8791fc87a.png)
![image3](https://cloud.githubusercontent.com/assets/2270223/9856308/1cbf5302-5b14-11e5-8e6c-1b071e7d084d.png)

if you cange the image code from >:( to :>( all works correct.
Same with the smilecode >:D .. change to :>D

**Comment by Oldiesmann** [comment]
Ok, so it's a problem with the editor rather than the ParseSmileys function...

**Comment by PortaMx** [comment]
Yup .. all other works now, only one of the extended smileys need a other code to work ..

```
'fname' => 'laugh.gif',
'code' => ':])'
```

**Comment by margarett** [comment]
Is it worth opening an issue in sceditor about this? It still happens (just tested)

**Comment by XinYenFon** [comment]
yeap.

**Comment by margarett** [comment]
https://github.com/samclarke/SCEditor/issues/492

**Comment by margarett** [comment]
I got a reply. They'll look into the issue but maybe it's not a quick fix

**Comment by MissAllSunday** [comment]
The issue was fixed, will be fixed when the editor gets updated
