### ISSUE TITLE
I wonder me ..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3070]
I have follow in the Spider Logs:

Google (AdSense)    Today at 16:47:14   Viewing the package manager. (i)
The red (i) says, he has taken the login page  ...

What do this say me ?
That Google can login to the admin section or what?

**Comment by VBGAMER45** [comment]
No google can't login. But they are finding the urls probably if you have ads that are shown on all pages. The url is then reported back to google which then tries to crawl/check the page.

**Comment by Rupurudu** [comment]
Create a robots.txt on the site root with this text:

```
User-agent: *
Allow: /
Disallow: /*action
Disallow: /*PHPSESSID
```
