### ISSUE TITLE
The missing action value gives error on checking the site (see image)

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3081]
![form_error](https://cloud.githubusercontent.com/assets/2270223/10076427/c3f6336a-62db-11e5-9edc-aadc21d65bf6.png)

**Comment by MissAllSunday** [comment]
Might be extra super duper handy to provide more info, as bare minimum, the url you were checking.

**Comment by Oldiesmann** [comment]
Looks like a validator somewhere is complaining about the empty action attribute. However, according to the specs, that attribute isn't required in HTML5, so we can just remove it entirely.

**Comment by PortaMx** [comment]
Quote "Looks like a validator somewhere is complaining about the empty action attribute. However, according to the specs, that attribute isn't required in HTML5, so we can just remove it entirely."

The validator is right.
The action attribut is otional, but if is exist it must have a valid and not empty value.
Refer: 
https://html.spec.whatwg.org/multipage/forms.html#attributes-common-to-form-controls
Section 4.10.19.6 Form submission

**Comment by MissAllSunday** [comment]
It doesn't exists anymore...
