### ISSUE TITLE
smf_log_activity uses smallints

### ISSUE THREAD

**Issue by wodim** [SimpleMachines/SMF#3082]
The `smf_log_activity` table uses smallints to store the stats, which could not be enough (max number is 65535).

**Comment by Oldiesmann** [comment]
No, it may not be large enough for some, but how many forums actually reach that level of activity? Even one of the largest SMF forums out there (well over 13 million posts) only averages 2800 new posts per day and has a "most online ever" of 12,744 - well below the max value for that field. The smallint value should be plenty large for most people, and it's easy enough to change that to mediumint if the activity level exceeds the max values for those fields.

**Comment by wodim** [comment]
I can understand. I have reached that limit though. I'll close this then, because your response seems reasonable.
