### ISSUE TITLE
classic permissions view

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3084]
this view was removed. there seems to be some code left behind though.

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/ManagePermissions.php#L1563

not sure if other areas that have $relabelPermissions in this file are related to this and should be removed as well.

**Comment by Oldiesmann** [comment]
That particular code is actually still used - it renames the post, reply and attachment permissions if post moderation is enabled (see line 1640).

**Comment by illori** [comment]
Maybe time to fix the comment?
