### ISSUE TITLE
The Report Tabe are moved out of the browser area

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3088]
On bigger reports like Mebergroups and other, the screen is moved outside the browser area.
To solve this, modify the index.css entry:
/\* a general table class */
table.table_grid {
    border-collapse: collapse;
    margin: 1px 0 5px 0;
    width: 100%;
}

add a:
    table-layout: fixed;

and all works fine ..

**Comment by XinYenFon** [comment]
Can you give me the exact page and resolution of your device?

**Comment by PortaMx** [comment]
Sorry .. solved .. was mine css bug ;-)

**Comment by XinYenFon** [comment]
Ah glad to hear, please close the issue if its fixed.
