### ISSUE TITLE
More css fixxes

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3092]
The top avatar is not shown correct.
change the css code as follow:
# profile_menu_top > img.avatar {

```
max-height: 18px;
max-width: 18px;
margin: 2px 5px 0 0;
float: left;
padding: 0;
```

}

More css fixes:
# mlist span.on, #mlist span.off, #edit_buddies .on, #edit_buddies .off {

```
margin: -5px 0 0 10px;
```

}

must be:
# mlist span.on, #mlist span.off, #edit_buddies .on, #edit_buddies .off {

```
margin: 4px 0 0 10px;
```

}

**Comment by XinYenFon** [comment]
```
#profile_menu_top > img.avatar {
    height: 18px;
    width: 18px;
    margin: 2px 5px 0 0;
    float: left;
    padding: 0;
}
```

is already the code ? and what is the changes are you suggesting? btw I find what I was doing wrong with on/off icons got rid of those extra margins.

**Comment by PortaMx** [comment]
If you have a avatar with 40px X 60px as example, this will show a little bit ugly ..
To hold the width/height proportion you have to use MAX-width / MAX-height ..

**Comment by XinYenFon** [comment]
I tried some similar 75x150 (while max 200x200) I didn't see "ugliness" :P this needs to stay as 18x18 hard-limited unfortunately. Increasing the height will make top-menu get bigger as well, considering we hard limited max-height: 100px it'll make top-menu 100px (max) as well.

**Comment by Kindred-999** [comment]
actually, Feline is correct on the idea of the max versus defined...

if we list max-with and max-height instead of forcing the image to be square, then the system will not distort the image by forcing it...

**Comment by XinYenFon** [comment]
max-height/width what? 18px or more?

**Comment by Oldiesmann** [comment]
Leaving it at 18px is fine. We just want to change it to max-height and max-width so it will show properly if the avatar isn't square.
