### ISSUE TITLE
Search API functionality

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3095]
in loadSearchAPIs() we have this line:
                if (strpos($header, '\* SearchAPI-' . $matches[1] . '.php') !== false)

This is looking for a header in the file matching:
    \* SearchAPI-Name.php

This header is missing in all of our default files.  We forcefully load them though which is why this hasn't been noticed.  Since this doesn't cause any issues it isn't a real big issue.  But for semantics, it seems like we should fix this so custom search APIs work properly.

**Comment by Oldiesmann** [comment]
We really should validate it based on whether the class we're expecting exists, not whether that text is in the file (otherwise we could just make a "SearchAPI-X.php" file with "\* SearchAPI-X.php" in it and SMF would think it's a valid search API...).

**Comment by jdarwood007** [comment]
We look for SearchAPI-*.php files, but when validating them on admin side, this is one of the checks we make.

**Comment by Oldiesmann** [comment]
I know. I think we should replace that check with one to make sure the class we wish to load exists...

**Comment by jdarwood007** [comment]
```
                if (strpos($header, '* SearchAPI-' . $matches[1] . '.php') !== false)
                {
                    loadClassFile($file);

                    $index_name = strtolower($matches[1]);
                    $search_class_name = $index_name . '_search';
                    $searchAPI = new $search_class_name();

                    // No Support?  NEXT!
                    if (!$searchAPI->is_supported)
                        continue;
```

Seems like it shouldn't be too hard as long as we change the code to match the filename instead.  The match is used to find the class.

**Comment by Oldiesmann** [comment]
We already have code in there that matches a "SearchAPI-*.php" file:

```
            if (is_file($sourcedir . '/' . $file) && preg_match('~^SearchAPI-([A-Za-z\d_]+)\.php$~', $file, $matches))
```

So really all we need to do is remove the code to open the file and add a check to see if the class exists after we define $index_name on line 724

**Comment by jdarwood007** [comment]
Doesn't seem to be a problem in the latest git checkout.
