### ISSUE TITLE
styling database error

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3101]
starting around line 35 of errors.template.php it seems to be lacking some html calls

this template seems to be called when there is a major error... it does not have a proper header or calls css so the page is pretty blank.

it seems if you add 

```
echo '
        <!DOCTYPE html>
<html', $context['right_to_left'] ? ' dir="rtl"' : '', '>
<head>';
template_css();
echo '
    <div id="fatal_error">
```

to the file you get a better looking page. i was able to get this template to show up when trying to install a mod by putting install.php from the mod package in the SMF root and calling it in the url. in this case the mod had already been installed and i was testing it... hence i got a database error that the table already exists.

i dont know if this template gets called elsewhere but i found it for this purpose.

**Comment by Oldiesmann** [comment]
That template is used with the fatal_error() and fatal_lang_error() functions to display an error message to the user. Adding the extra HTML there would actually break things as rest of the template stuff has usually been loaded at that point.

**Comment by illori** [comment]
So what can we do for the other uses of this template where we get no
styling?

**Comment by Oldiesmann** [comment]
I don't think there is anything we can do in this situation, as there aren't many times when the template will actually get loaded when there's no header info (and, to my knowledge, there's no way to detect whether the CSS and such has been loaded).

**Comment by illori** [comment]
Then maybe a new template for ssi database errors so they get styling?

**Comment by Arantor** [comment]
You probably shouldn't have a template for SSI database errors because you have no idea what code you're in the middle of - that being the entire point of SSI.

It's also not up to SMF to push mod authors to write nice handling in their mod packages, because it's already possible to gracefully handle such errors and few people ever bother (me included because it's not worth the effort)

**Comment by XinYenFon** [comment]
is this a valid issue ? ^ sums up pretty well.

**Comment by jdarwood007** [comment]
Agreed.  SSI handles errors differently as it is up to the code using SSI to handle the errors.

If any error exists in SMF base that is handling the template wrong, we can fix that.  But not for SSI stuff.
