### ISSUE TITLE
Width on News Items in Admin

### ISSUE THREAD

**Issue by Justyne** [SimpleMachines/SMF#3109]
![smurfbug](https://cloud.githubusercontent.com/assets/8726347/10710643/1cff9898-7a5b-11e5-9347-bcd8ecb7e9ba.png)

Resizing the text box does not have seem to have a cap.

**Comment by Oldiesmann** [comment]
I can only get things to flow off the screen if I increase the width of that text box to the point where the "preview" cell can't get any smaller. I can't get it to flow off the screen with a huge gap between cells like that though.

**Comment by Justyne** [comment]
Was done in chrome. Maybe it's browser specific?

**Comment by XinYenFon** [comment]
I can reproduce this on FF as well.

**Comment by Oldiesmann** [comment]
Odd. I tried it in Firefox and couldn't reproduce it.

**Comment by Oldiesmann** [comment]
What version of Chrome and what OS was this done with? I tried it in both Firefox and Chrome on the latest version of Kubuntu (15.10) and can't get it to shove stuff off the screen with a huge gap between the textbox and the end of the cell like that.

**Comment by Justyne** [comment]
Win 10 and latest chrome v.46 .. I think also on win 7
