### ISSUE TITLE
Undefined variable $rows --> Subs-Admin.php

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#3116]
I got an error in my error log while testing @MissAllSunday's attachments stuff and I think this is a small bug.

This is the error:

> Type of error: Undefined
> Undefined variable: rows
> File: C:/xampp/htdocs/smf21/Sources/Subs-Admin.php
> Line: 506
> 
> Type of error: General
> 2: array_keys() expects parameter 1 to be array, null given
> File: C:/xampp/htdocs/smf21/Sources/Subs-Admin.php
> Line: 506

Line 506 (and before) is:

```
    // Load their alert preferences
    require_once($sourcedir . '/Subs-Notify.php');
    $prefs = getNotifyPrefs(array_keys($rows), 'announcements', true);
```

But that variable $rows seems to really be nonexistent. @live627 I think that this was added by you, maybe you can give it a quick spin? :wink: 
Was it supposed to be $members, as this is really fetched above?

**Comment by Oldiesmann** [comment]
Note: The push directly to SimpleMachines was unintentional. It's apparently a "feature" of SmartGit - you set your branch to track a branch of upstream and anything you push to your repo gets pushed to the tracked branch as well. I've removed the tracked branch option now to prevent this from happening in the future.
