### ISSUE TITLE
Improve Secret answer hashes in profiles

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3117]
This is our current handling of Secret answers

```
        'secret_answer' => array(
            'type' => 'text',
            'label' => $txt['secret_answer'],
            'subtext' => $txt['secret_desc2'],
            'size' => 20,
            'postinput' => '<span class="smalltext" style="margin-left: 4ex;">[<a href="' . $scripturl . '?action=helpadmin;help=secret_why_blank" onclick="return reqOverlayDiv(this.href);">' . $txt['secret_why_blank'] . '</a>]</span>',
            'value' => '',
            'permission' => 'profile_password',
            'input_validate' => function (&$value)
            {
                $value = $value != '' ? md5($value) : '';
                return true;
            },
        ),
```

We should improve this, its better than plaintext, but not by much at this point in today's rainbow tables and cpu/gpu speeds.
1. Should we improve this to handle multiple questions/answers?
2. What should we change the method to?  I'm fine with at least going to a salted sha1, but we could also use the password_hash method.

**Comment by Oldiesmann** [comment]
Not sure about multiple questions/answers, as SMF is currently designed to only handle one question, but we should definitely improve it to something other than md5. Problem is we can't update it on upgrade - we'd have to write compatibility checks.

**Comment by joshuaadickerson** [comment]
Whatever the password is stored as, the answer should be the same and there should be multiple questions/answers. At least two, but to store it, it should be a separate table to make it extensible.

**Comment by Oldiesmann** [comment]
I think at this point the only thing we can do is change the encryption method used for answers.

Expanding the functionality would be great, but as we have no way to force existing users to use it, there's not much point in changing how it works at this point. Maybe something to consider for 3.0.

**Comment by Kindred-999** [comment]
definitely -- adding multiple questions is a 3.0 feature, I believe.

So - let's just focus on the encryption for 2.1
