### ISSUE TITLE
Duplicate Hook names

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3118]
In Profile.php we have this:

```
    // Let them modify profile areas easily.
    call_integration_hook('integrate_profile_areas', array(&$profile_areas));
```

In Subs-Menu.php we have this:

```
    // Allow extend *any* menu with a single hook
    if (!empty($menu_context['current_action']))
        call_integration_hook('integrate_' . $menu_context['current_action'] . '_areas', array(&$menuData));
```

$menu_context['current_action'] is set to profile when you are on the Profile.  This causes the hook to be called twice, which can have unexpected results.  Especially with regards to the permissions array which is altered between these calls to remove the own/any.   I am in suggestion we should change the one in Profile.php to integrate_pre_profile_areas.

**Comment by live627** [comment]
I suggest it be removed;  it is redundant now.
