### ISSUE TITLE
[Smf 2.0] Wysiwg with Safari wrong color tag closing

### ISSUE THREAD

**Issue by petitchevalroux** [SimpleMachines/SMF#3129]
Under Safari Version 9.0.1 (11601.2.7.2)

I am not sure if it's the right place to report 2.0 bugs but I don't find the add button on mantis bug tracker.

When formating multilines post using wysiwig i get the following preview : 

```
line 1
line 2
[/color]line 3
line 4
```

To reproduce 
Paste the following lines : 

```
line 1
line 2
line 3
line 4
```

Select the 4 lines and change font to Courrier
Select line 2 and 3 and set color to red
Send form using the preview

**Comment by petitchevalroux** [comment]
In Subs-Editor.php:

preg_replace is false :
- the . is useless
- the ~ are missing when replacing the closing div tags

``` php
    if ($context['browser']['is_webkit'])
        $text = preg_replace(array('~<div(?:\s(?:[^<>]*?))?' . '>~i', '</div>'), array('<br />', ''), $text);
```

must be :

``` php
    if ($context['browser']['is_webkit'])
        $text = preg_replace(array('~<div(?:\s(?:[^<>]*?))?>~i', '~</div>~'), array('<br />', ''), $text);
```

It doesn't fix the bug but it helps :D

**Comment by petitchevalroux** [comment]
It seems that $curCloseTags is not handled properly (so this bug is not specific to safari) when having multiple style attributes.
Using this html as $text param for html_to_bbc($text) isolate the wrong behaviour :

``` html
<span style="font-family: courier; color: red;">line 3</span>
```

Output html_to_bbc :

```
[font=courier][color=red]line 3[/font][/color]
```

In my specific example replacing : 

``` php
$curCloseTags .= '[/color]';
```

with 

``` php
 $curCloseTags = '[/color]' . $curCloseTags;
```

Fix the bug.

It may be done to all closing tags/attributes as closing tags must be done in reverse order.
Need some advice here ;)

**Comment by XinYenFon** [comment]
This repository is only for SMF 2.1.x, please use our bug report board (in simplemachines.org) to report bugs related to SMF 2.0.x.

Thanks :)

**Comment by pcraum** [comment]
@Antes All bug tracker links on simplemachine.org lead to this github repository. Can you give me the url to submit a new bug in mantis ?

**Comment by petitchevalroux** [comment]
@Antes All bug tracker links on simplemachine.org lead to this github repository. Can you give me the url to submit a new bug in mantis ?

**Comment by petitchevalroux** [comment]
Someone (on the forum) explain me that we can't create a bug on mantis so I create a new bug report on the forum : 

http://www.simplemachines.org/community/index.php?topic=541306.0

I close this issue.
Sorry for the bother ;)
