### ISSUE TITLE
Suki's attachments update -- Server responded with 0 code.

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#3130]
Updated to the build as of 17-Nov...   tried to use the drag and drop upload.
image files loaded...
click "upload all"
every one responded with a red background, an attention icon and the message  
Server responded with 0 code.

This also stopped me from editing the text in the post box any further...

clicked the back button

went to try posting again... and the attachments were pre-loaded into the attempted post.... and they could be added inline this time.

**Comment by MissAllSunday** [comment]
What browser are you using?
is this an admin or a regular account?
Anything in the browser console or the error log?

**Comment by smfbigguy** [comment]
Just tested this in FF...the latest and all went fine for me. Love the feature btw. :)

**Comment by Kindred-999** [comment]
Sorry, Should have included details.

Firefox, logged in as admin
nothing in the error log... I don't think I checked the console

**Comment by MissAllSunday** [comment]
If the server gave a response then I would be inclined to think the server couldn't handle the files at that specific moment, is this a recurrent issue or just something that happened once?

**Comment by Kindred-999** [comment]
I have only seen it that once... but I haven't been banging away at the attachments right now....   I'll try a bunch of attachment uploads next weekend
