### ISSUE TITLE
Birthday alert generates a blank message and errors in log

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#3134]
If a user chooses to receive its birthday notification via alert, the generated alert is empty and it generates errors in the log: one in the popup and other in the alerts list

Undefined index: text
http://localhost/smf21_clean/index.php?action=profile;area=alerts_popup;u=1
File: C:/xampp/htdocs/smf21_clean/Themes/default/Profile.template.php
Line: 116

Undefined index: text
http://localhost/smf21_clean/index.php?action=profile;area=showalerts
File: C:/xampp/htdocs/smf21_clean/Themes/default/Profile.template.php
Line: 583

I tried to debug this for a while but I can't understand how the alert system works under the hood...

**Comment by Oldiesmann** [comment]
Can you provide me with the data for those alerts? The text is set based on the content_type and content_action (see the fetch_alerts function in Sources/Profile-View.php). If it's not set, then that means the language string for that combination of type and action doesn't exist.

**Comment by margarett** [comment]
Ups, I forgot about this, sorry.

There is no data I can give you, really, other than the error log. Because the alert message I get is empty :tongue: 

Just go to your notification preferences and set "When it's my birthday --> Receive alert"
Then go to your forum profile and set your birthday for today.
Finally go to Scheduled tasks and choose "Run Now" for "Send Birthday Emails". You'll get an alert (and an error in your log), when you choose the alerts and "All alerts", you'll get the second error in the log. The birthday message is empty in both cases (of course, it's the undefined index :tongue: )

**Comment by margarett** [comment]
Eh, found something. It seems that there is a typo in Alerts.english.php

```
$txt['alert_birthday_mag'] = '{happy_birthday}';
```

Looking at smf_user_alerts, content_type is "birthday" and content_action is "msg" so that text key should be "alert_birthday_msg". Bingo, that kills the error :)

The problem is that it seems we're receiving the email template in the alert :(

> Dear {REALNAME}, We here at {FORUMNAME} would like to wish you a happy birthday. May this day and the year to follow be full of joy. {REGARDS}

edit: I see it, we are not processing the replacements. Maybe I can still fix this after all :tongue:
