### ISSUE TITLE
$modSettings['attachmentUploadDir'] not handled properly?

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#3140]
It seems that $modSettings['attachmentUploadDir'] isn't handled properly in all situations. When we install SMF, it gets set to the path of the "attachments" directory within the main forum directory. However, in several places throughout SMF, it's expected to be an encoded array, regardless of whether we're using multiple directories. This causes all sorts of problems by default.

Not being familiar with the attachments system, I don't know what the proper way is to fix this - do we just encode it by default or do we need to modify some code to check whether it's a directory before trying to json_decode() it?

**Comment by jdarwood007** [comment]
Should create a sub function to handle loading up the attachment directories and let it handle doing things the correct way.

**Comment by margarett** [comment]
I just performed a clean test install and the attachments path is not just a string:

```
{"1":"C:\\xampp\\htdocs\\smf21_clean\/attachments"}
```

If I go to Attachments Settings and change it (just the name), it changes accordingly.

**Comment by Oldiesmann** [comment]
Fixed with #3161
