### ISSUE TITLE
Change custom attachment dir

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#3143]
while trying to change a custom attachment dir to fix an incorrect path I get the following errors.

Undefined offset: 0
Sources/ManageAttachments.php
Line: 2206

current_base_dir
Sources/ManageAttachments.php
Line: 2166

SMF doesn't recognize the new path and still shows the old wrong path.

**Comment by Oldiesmann** [comment]
This may be related to #3140. I'll take a look at it when I get a chance.

**Comment by margarett** [comment]
Just to add, which should be related, when I try to add a new folder using the full path to it, it isn't added (folder name keeps blank, nothing in the logs). Eg, I add:

```
C:\xampp\htdocs\smf21_clean/attachments3
```

And nothing is added. But if I write just "attachments3", then it works fine. smf_settings gets this:

```
{"1":"C:\\xampp\\htdocs\\smf21_clean\/attachments","2":"attachments3"}
```

**Comment by Oldiesmann** [comment]
That's weird. Does it actually work if that directory is used though?

**Comment by margarett** [comment]
Yup. It does create the folder under SMF's root, adds .htaccess and index.php and it is possible to upload attachments as usual ;-)

**Comment by illori** [comment]
seems related to https://github.com/SimpleMachines/SMF2.1/issues/899

**Comment by Oldiesmann** [comment]
Ok... The undefined offset error is because it's looping through the array of $_POST['base_dir'] which is 0-based but $modSettings['attachmentUploadDir'] has a starting index of 1. The easy way to fix that is to just increment $id by 1.

**Comment by Oldiesmann** [comment]
The current_base_dir issue seems to be that we're not checking whether $_POST['current_base_dir'] is even set before trying to use its value. Still not sure about the paths thing, but I'll look at that once I get the rest of the attachment stuff fixed here.

**Comment by Oldiesmann** [comment]
Tested things on my forum and was able to add/delete attachment directories just fine, even when specifying the full path. Not sure why it's not working for you.

**Comment by margarett** [comment]
Maybe because I'm using Windowzzzz?
