### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#3146]
See screenshot but I was wondering why there is no obviously visible login button on the main menu bar when you are a guest. You have login and signup on the top bar but only signup on the main menu. I had a complaint on my new forum that this was not visible enough.
![2015-11-27_213859login](https://cloud.githubusercontent.com/assets/3620111/11449751/b3d1bddc-954f-11e5-8f78-906b888e9ed9.png)

**Comment by illori** [comment]
it got moved for a reason, i bet because of the popup.

i think it is not in a bad place, just users need to get used to the fact that it got moved.

**Comment by XinYenFon** [comment]
agree with @illori

**Comment by smfbigguy** [comment]
Just thought I would put it out there. :)
