### ISSUE TITLE
ACP Search broken

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3147]
No search box and the css doesn't seem to load correctly.
https://imgur.com/RejUKox

**Comment by jdarwood007** [comment]
Tested with:
Chrome on Mac: Fails
Safari on Mac: Fails
FireFox on Mac: Works

Most likely it is a webkit issue.

**Comment by Oldiesmann** [comment]
Can you double check with the latest files from GitHub? I tested it on my own forum and it works fine. #3126 should have fixed this.

**Comment by Mavn** [comment]
I can confirm, I have this error too with latest files 
![search-panel](https://cloud.githubusercontent.com/assets/2140726/11495237/9950bee0-981a-11e5-808b-e2de463b808b.jpg)
chrome on windows: fails
chrome on android: fails
firefox on windows: works

**Comment by MissAllSunday** [comment]
Yep I've seen this too opera on windows

**Comment by Oldiesmann** [comment]
Hmmm... It seems the older code works fine (the form within the h3, which isn't allowed) but the fixed code doesn't work in Webkit-based browsers.
