### ISSUE TITLE
createAttachment silently fails if id_folder is missing

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3150]
During some testing of working with a mod that uses createAttachment, if I call it without specifying the id_folder, it silently returns as if it succeeded.  Worse yet, it inserts data into the database and because id_file isn't set our code automatically converts it to 0.

We should add a check to createAttachment to either fail or pick the default id_folder.

**Comment by Oldiesmann** [comment]
There's $modSettings['currentAttachDir'] as well. That should be useful for figuring out where it goes (unless there's some logic somewhere to sort that all out).

**Comment by jdarwood007** [comment]
Its $modSettings['currentAttachmentUploadDir']
