### ISSUE TITLE
install/uninstall mods base restriction errors

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3152]
Warning: PharData::__construct(): open_basedir restriction in effect. File(/var/www) is not within the allowed path(s): (/var/www/public_html:/var/www/tmp) in /var/www/public_html/smfsd/Sources/Subs-Package.php on line 3049

Warning: PharData::__construct(): open_basedir restriction in effect. File(/var) is not within the allowed path(s): (/var/www/public_html:/var/www/tmp) in /var/www/public_html/smfsd/Sources/Subs-Package.php on line 3049

Warning: PharData::compress(): open_basedir restriction in effect. File(/var/www) is not within the allowed path(s): (/var/www/public_html:/var/www/tmp) in /var/www/public_html/smfsd/Sources/Subs-Package.php on line 3051

Warning: PharData::compress(): open_basedir restriction in effect. File(/var) is not within the allowed path(s): (/var/www/public_html:/var/www/tmp) in /var/www/public_html/smfsd/Sources/Subs-Package.php on line 3051

**Comment by margarett** [comment]
Which MOD is it?

**Comment by Oldiesmann** [comment]
This isn't making any sense at all...

Lines 3032-3049:

``` php
        $output_file = $packagesdir . '/backups/' . strftime('%Y-%m-%d_') . preg_replace('~[$\\\\/:<>|?*"\']~', '', $id);
        $output_ext = '.tar';

        if (file_exists($output_file . $output_ext))
        {
            $i = 2;
            while (file_exists($output_file . '_' . $i . $output_ext))
                $i++;
            $output_file = $output_file . '_' . $i . $output_ext;
        }
        else
            $output_file .= $output_ext;

        @set_time_limit(300);
        if (function_exists('apache_reset_timeout'))
            @apache_reset_timeout();

        $a = new PharData($output_file);
        $a->buildFromIterator($iterator);
        $a->compress(Phar::GZ);
```

If $packagesdir wasn't set properly you'd run into errors before then when it tries to create the backups directory.

**Comment by jdarwood007** [comment]
I think this may be a PHP bug.  I can reproduce this by a simple test file.  I have open_basedir restrictions setup.

```
<?php
error_reporting(E_ALL);
$a = new PharData(dirname(__FILE__) . '/Packages/backups/test.tar.gz');

var_dump($a);
```

My guess is its trying to work its way from the root down the tree and receiving an error because open_basedir restrictions prevents it from having any access.

**Comment by sbulen** [comment]
I believe PR #3998 addressed this, & this can be closed.   The problem was it was checking if the tar file existed first, but it should have been checking for a tar.gz.

**Comment by sbulen** [comment]
Note that PR #3998 fixed an issue with this logic...  It's possible this is now closed.

**Comment by sbulen** [comment]
I've done more reading on this, & it appears these are usually php config issues.  open_basedir is an environment setting, beyond the control of SMF.  (You can narrow the scope of open_basedir in php, but you can't redefine it or widen it...)

Either open_basedir is too restrictive, or, for some reason, PharData is trying to write directly to a temp folder outside the allowed range.  

It looks like PharData is trying to use the var folder instead of  the tmp folder...  And var is not opened up thru open_basedir.

We see these on the support site, & the standard response on the SMF support site is to open a ticket with your host...

**Comment by sbulen** [comment]
@jdarwood007 - Can this be closed?

**Comment by sbulen** [comment]
Another item that should be closed.
