### ISSUE TITLE
package-info hook doesn't handle reverse properly

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3154]
```
        <hook function='func' hook='hook' file='file' reverse='true' />
```

This inside of a package-info.xml for uninstall shows Add Hook still.

**Comment by MissAllSunday** [comment]
Is that the exact tag you are using?  I use used that and got a false on $action['reverse'] when uninstalling, I changed the single quotes to double quotes and it worked just fine.

I never used single quotes on any of the mods I have so I don't know if single quotes worked on 2.0 and are failing on 2.1 or if they haven't ever worked or if its just my server.

**Comment by jdarwood007** [comment]
Single quotes should work the same, but from the referenced fix, I think that should solve this.
