### ISSUE TITLE
No more reuse of the membergroup ID?

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#3157]
Following this bug report (which, IMO, is not a bug but it can also be considered not a great design decision)
http://www.simplemachines.org/community/index.php?topic=541648.0

Should we use the auto increment property of the field instead if always using the next available ID?

```
        // @todo Check for members with same name too?

        $request = $smcFunc['db_query']('', '
            SELECT MAX(id_group)
            FROM {db_prefix}membergroups',
            array(
            )
        );
        list ($id_group) = $smcFunc['db_fetch_row']($request);
        $smcFunc['db_free_result']($request);
        $id_group++; 
```

**Comment by live627** [comment]
+1, must be changed.

**Comment by Kindred-999** [comment]
out of curiosity -- why must it be changed?

I add a board (ID4) - I delete that board - I add another...
do I _REALLY_ need to skip ID4 now and go to ID5?
I think that it is logical to just use the next number available at the end of the stack -- and not bother checking if that number has been used before...

**Comment by margarett** [comment]
@Kindred-999 
http://www.simplemachines.org/community/index.php?topic=541648.msg3849647#msg3849647

> If you create a board (or a topic, for what matters), then delete it, any associated content should explicitly become noted as not valid. Of course, before you remove the board you must have either deleted or moved the content. But the point is: the board becomes non existent.

It should be changed for consistency, nothing more. If we have a SMALLINT it means that we get to create 32767 membergroups before exhausting the IDs. Crazy crazy.

**Comment by margarett** [comment]
This issue has another occurence
Subs-Themes.php

```
    // Find the newest id_theme.
    $result = $smcFunc['db_query']('', '
        SELECT MAX(id_theme)
        FROM {db_prefix}themes',
        array(
        )
    );
    list ($id_theme) = $smcFunc['db_fetch_row']($result);
    $smcFunc['db_free_result']($result);

    // This will be theme number...
    $id_theme++;
```

Although, in this case, the column id_theme is a tinyint. By not reusing IDs it is possible to blow the maximum value (after one messes with 255 themes :tongue: )

**Comment by Oldiesmann** [comment]
I honestly don't see what the big issue is with reusing existing IDs for some things. It does require an extra query but SELECT MAX() really shouldn't have much of an impact on resources even for large tables.

Also, for themes, you wouldn't necessarily have to mess with 255 themes. If you install two themes then uninstall the first one, the next theme installed would have an ID of 4 even though there's no theme with an ID of 2.

**Comment by margarett** [comment]
It's not an issue, at least I don't see it that way. Whether or not IDs should be reused is a design decision. And again, it's not a total reuse (eg, we're not trying to fill all gaps in the sequence, it's just the _last_ ID which might be reused)
For posts/topics/boards/attachments/etc I believe that they should never be reused. It's content, if you delete it, then it should be invalid.

So, IMO, we should not reuse any IDs but only for consistency. We are reusing these IDs (membergroups and themes) and not any others.

**Comment by Kindred-999** [comment]
I'm not sure the "consistency" argument holds up in these cases.... consistency amongst the same activities -- yes. But boards are different from messages and users,
as I said above, I see it as logical to reuse the number (if that number is the next/lastID in the sequence)

I agree that userIDs and messageIDs should not do that (and they don't)

But I still rather see this as a non-issue
(and still don't quite understand live's comment "must be changed")

**Comment by emanuele45** [comment]
And I'm so happy to see that the Project Manager is finally a
developer as well! YAY!

**Comment by Oldiesmann** [comment]
I don't see why this "must be changed" either. There's nothing wrong with what we're doing now, even if we don't do the same with IDs elsewhere.

**Comment by colinschoen** [comment]
I 100% agree with Live. This should be changed. There is a reason why nearly every database solution has an auto incrementing feature and internal primary keys should use it. The reason why primary keys exist is that they are intended to be unique and non-repeated. Why is this important? Well, if for some reason the member group is deleted, but the relationships are not and then the old primary key should not be pointing to a new member group. This is an inherently bad design decision. Just because it hasn't caused issues yet doesn't mean it should not be changed.

**Comment by margarett** [comment]
Just a note: what @colinschoen mentioned was exactly what originated the bug report linked in the first message.
Granted, the code in SP should make sure that no leftovers were left. But it didn't so the permissions were inherited.

**Comment by colinschoen** [comment]
Sorry @margarett didn't see that link before.

**Comment by margarett** [comment]
OK so I gave this some more minutes. Whether it would be merged or not it's not important but I thought that having the PR available would make it easier to make the decision.

In Membergroups, there isn't a problem in going the auto-increment route. Just kill the SELECT MAX, perform the insert and then get a 

```
$smcFunc['db_insert_id']
```

After to get the inserted ID (which is necessary after the insert)

Themes is not so easy. There is a hook _before_ the insert instruction which already expects the ID to be passed.

```
    // Last minute changes? although, the actual array is a context value you might want to use the new ID.
    call_integration_hook('integrate_theme_install', array(&$context['to_install'], $id_theme));
```

And getting the ID beforehand is possible but not reliable (eg, even if not likely, an ID might be inserted during this code's execution --> highly unlikely but better safe)
So either kill that parameter from the hook or... :question:

**Comment by MissAllSunday** [comment]
For themes, remove the SELECT MAX query and move the hook call just before the return, remove the id_theme from the insert query and do a $smcFunc['db_insert_id'](); call to get the $id_theme var.

**Comment by Oldiesmann** [comment]
I still haven't seen an explanation as to why this is an absolute "must" change...

**Comment by colinschoen** [comment]
You are right nothing is functionally broken, but if we want to adhere to
common design paradigms this is something we should fix.

**Comment by albertlast** [comment]
The select max() from membergroups is problematic,
on the pk field is a sequence/ai and they will not updated.

When you insert data there you could get errors that the id already exists.
Reason; the ai and sequence try to use number which is already use.

You should delete the ai/seq whenn they not use.

**Comment by Sesquipedalian** [comment]
Thinking about URLs and external hyperlinks makes a good case for not reusing board IDs. Consider this scenario:
1. Someone posts a link on their blog pointing to a board's URL, like so: `<a href="http://www.example.com/index.php?board=14.0">Check out these awesome discussions of Harley Davidson engines</a>`
2. The forum's admin deletes board 14.
3. The forum's admin creates a new board, dedicated to discussion of My Little Pony accessories. This new board is assigned the recycled id number 14.
4. Bikers click on the blog link and become angry when they find themselves unexpectedly consorting with Bronies. They proceed to hunt down the innocent blogger and teach him why you shouldn't mess with bikers.

The point is, if a board existed and is then deleted, any links to the deleted board's URL should get a 404 response, not some unexpected other content.

**Comment by live627** [comment]
> if a board existed and is then deleted, any links to the deleted board's URL should get a 404 response

Did you test your theory? They already do that.

**Comment by margarett** [comment]
@Sesquipedalian you are right but that is not the case ;) Last time I looked at the code regarding this issue only membergroups and themes reuse the ID. Boards, topics, posts, etc etc, all use the normal incremental IDs automatically assigned from the database.

**Comment by Sesquipedalian** [comment]
Sorry for the lack of clarity. I was responding to @Kindred-999 about why one would not want to recycle board ids. I wasn't really talking about what SMF actually does, but about why it should do that. Which, on further reflection, was probably an unnecessary contribution to the conversation... :)
