### ISSUE TITLE
Inline image attachments get changed to links

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#3165]
This is probably related to #3102.

On my test board...

Upload image attachment
Click "insert" to insert it in WYSIWYG mode

Result: `[iurl="http://smfgit.oldiesmann.us/index.php?action=dlattach;attach=8;type=preview;file"]busted.png[/iurl]`

If I try it in non-WYSIWYG mode, when I save the post, I get the linked thumbnail (with ;"> in front of it), but when I go to edit the post, I see the same iurl code as above (with the link in quotes) rather than the linked thumbnail.

**Comment by Kindred-999** [comment]
hmmm.... that doesn't happen for me

**Comment by MissAllSunday** [comment]
Yep, I'm aware, it happens because the editor fails to recognize an image as well, an image :P  thats why the attach BBC passes the type, to explicitly tell the editor its an url to an image not a regular url but it still fails for some reason.

**Comment by Oldiesmann** [comment]
I think I see why it's treating it as iurl rather than a regular URL (the HTML for linked inline attachments doesn't have a `target="_blank"`), but I'm not sure why it's not picking up that it's a linked image rather than a regular link. I'll have to look into it more when I have time.

**Comment by margarett** [comment]
Even more strange, it seems to only fail for the first time you add the inline attachment. Add it twice and the second time it gets inserted correctly

**Comment by Kindred-999** [comment]
BTW: Yes. it is also happening for me now -- and seems to be breaking the inline display of existing attachment posts

**Comment by Oldiesmann** [comment]
After playing around with it a bit I've gotten it to behave more "properly"...

Change this:

``` javascript
            // Show a link to the file, check if the name attribute has been set and use that, if not use the attachment ID.
            if ((typeof attrs.type !== "undefined" && !attrs.type.match(/image.*/)) || contentIMG.width == 0){
                return '<a href="' + smf_scripturl +'?action=dlattach;attach='+ content + ';type=preview;file"' + ' data-attachment="'+ content +'">'+ (typeof attrs.name !== "undefined" ? attrs.name : content) +'</a>';
            }

            else{
                return '<img' + attribs + ' src="' + contentUrl +'">';
            }
```

To this

``` javascript
            // Show a link to the file, check if the name attribute has been set and use that, if not use the attachment ID.
            if ((typeof attrs.type !== "undefined" && !attrs.type.match(/image.*/)) || contentIMG.width == 0){
                return '<a href="' + smf_scripturl +'?action=dlattach;attach='+ content + ';type=preview;file" target="_blank"' + ' data-attachment="'+ content +'">'+ (typeof attrs.name !== "undefined" ? attrs.name : content) +'</a>';
            }

            else{
                return '<a href="' + smf_scripturl +'?action=dlattach;attach='+ content + ';type=preview;file" target="_blank"' + ' data-attachment="'+ content +'"><img' + attribs + ' src="' + contentUrl +'"></a>';
            }
```

That will cause it to turn the [attach] into [url=...][img]...[/img][/url] when editing again. Not sure if that's the intended behavior, but it works at least.

**Comment by Oldiesmann** [comment]
Got it working now and will commit changes shortly. The only exception is that in the editor, only a thumbnail is shown (rather than a thumbnail linking to the full size image like it is in the post), but we can fix that later if necessary. Also found a bug with smiley parsing but will open a separate issue for that.
