### ISSUE TITLE
Cancel on quick edit is broken

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#3167]
My codebase is about a week or so old...   I'll update it on Sunday and retest...

but, in case anyone else can check...
Go to quick edit a post (this one happens to have inline and non-inline attachments - I then retested on a text only post)
save works
however, pressing cancel not only does nothing... but it seems to also disable the save and spellcheck buttons as well.

**Comment by margarett** [comment]
Just tested, it works fine here (FF and IE11)

**Comment by XinYenFon** [comment]
Can't reproduce. Try with disabling all addons (like Ghostery - AdBlock).

**Comment by Oldiesmann** [comment]
Can't reproduce it on my forum either.

**Comment by Kindred-999** [comment]
ok...    just updated and confirm that cancel works correctly now...   although the update broken Suki's inline attachments.
