### ISSUE TITLE
Upgrade.php fail due to mysql script.

### ISSUE THREAD

**Issue by FearThe1337** [SimpleMachines/SMF#3169]
Using upgrade.php failed for my forum.
Issue is due to the code in line [392](https://github.com/SimpleMachines/SMF2.1/blob/a6a3b329fbdcd18a73e0693d6c3ceb470c6a5bbe/other/upgrade_2-1_mysql.sql#L392) and  [414](https://github.com/SimpleMachines/SMF2.1/blob/a6a3b329fbdcd18a73e0693d6c3ceb470c6a5bbe/other/upgrade_2-1_mysql.sql#L414) .
{$db_prefix} should of been {db_prefix}, Issue is caused by this [commit](https://github.com/SimpleMachines/SMF2.1/commit/a6a3b329fbdcd18a73e0693d6c3ceb470c6a5bbe)

**Comment by FearThe1337** [comment]
Also adding, after fixing this I later got the error:

Notice: Undefined index: db_list_tables in /forum/upgrade.php on line 3893
Fatal error: Function name must be a string in /forum/upgrade.php on line 3893

// Get a list of table names ahead of time... This makes it easier to set our substep and such
$queryTables = $smcFunc['db_list_tables'](false, $db_prefix);

**Comment by margarett** [comment]
I think that this issue can now be closed ;)
