### ISSUE TITLE
JSON-encoded Windows paths fail to decode

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#3173]
I did a clean install and I got errors related to the attachments path.
So I checked the database and this is what was stored:
{"1":"C:\xampp\htdocs\smf21_clean/attachments"}
In ManageAttachments.php there is this:

```
    $modSettings['attachmentUploadDir'] = json_decode($modSettings['attachmentUploadDir'], true);
    $context['attachmentUploadDir'] = $modSettings['attachmentUploadDir'][$modSettings['currentAttachmentUploadDir']];
```

print_r tells me that the json_decode operation returns nothing, http://json.parser.online.fr/ tells me that there is a "bad escaped character". So I manually set the field as:
{"1":"C:\xampp\htdocs\smf21_clean/attachments"}
And the path becomes correct.

**Comment by Oldiesmann** [comment]
PHP's json_encode function automatically adds slashes unless you tell it not to, so I'm assuming this is a fresh install (since we're sort of manually hacking things there rather than running it through json_encode - something that's pretty easily fixable though).

**Comment by jdarwood007** [comment]
Incase its not clear, the path should be: C:\\xampp\\htdocs\\smf21_clean/attachments

json_(en|de)code expects \ to escape a character.

**Comment by margarett** [comment]
Yes, it's a fresh install. Yes, the paths do need the double backslash
