### ISSUE TITLE
upgrade hangs...

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#3181]
attempting to run upgrade form a previous installation of 2.1 beta2

Hangs on
Executing: "Updating legacy attachments..." (2 of 41)
....
....
Fixing invalid sizes on attachments...done

then nothing....

commenting out this section
---# Fixing attachment directory setting...
---{
---if (is_dir($modSettings['attachmentUploadDir']))
---{
--- $smcFunc['db_query']('', '
---     UPDATE {db_prefix}settings
---     SET value = {string:attach_dir}
---     WHERE variable = {string:uploadDir%29',
---     array%28
---         'attach_dir' => json_encode%28array%281 => $modSettings['attachmentUploadDir'])),
---         'uploadDir' => 'attachmentUploadDir'
---     )
--- );
--- $smcFunc['db_insert']('replace',
---),
---     array('currentAttachmentUploadDir', '1'),
---     array('variable')
--- );
---}
---else
---{
--- // Serialized maybe?
--- $array = @unserialize($modSettings['attachmentUploadDir']);
--- if ($array !== false)
--- {
---     $smcFunc['db_query']('', '
---         UPDATE {db_prefix}settings
---         SET value = {string:attach_dir}
---         WHERE variable = {string:uploadDir%29',
---         array%28
---             'attach_dir' => json_encode%28$array),
---             'uploadDir' => 'attachmentUploadDir'
---         )
## ---     );

---     // Assume currentAttachmentUploadDir is already set
--- }
---}
---}
---#
allows the upgrader to continue

but then it hangs on 
Step 6: Convert serialized strings to JSON
with no message displayed in the output section, at all...

This is my test system with not a whole ton of "stuff" in terms of users, messages or anything else

**Comment by Kindred-999** [comment]
it looks like bypassing that step has totally screwed the attachments....   the system won't even accept a new setting for attachments directory

**Comment by margarett** [comment]
Confirmed here too. Not sure if @Oldiesmann already finished the templates for this attachments part though...
I do get the "Server has not responded for 30 seconds." error message though, so it doesn't just "stop" out of nowhere.

edit: it is dying in "---# Fixing attachment directory setting..."

**Comment by jdarwood007** [comment]
Try changing the else to:

```
elseif (substr($modSettings['attachmentUploadDir'], 0, 2) === 'a:')
```

**Comment by margarett** [comment]
@jdarwood007 I think not. I debugged and it enters the first "if"
if (is_dir($modSettings['attachmentUploadDir']))
The problem is (IMO, can't be sure yet) json_encode and single backslashes in windows paths

edit: funny, I was outputting debug variables to a file and, out of the blue, the step was successful and the upgrade finished. :open_mouth:

**Comment by margarett** [comment]
OK so for whatever reason, this query is just dying:

```
    $smcFunc['db_query']('', '
        UPDATE {db_prefix}settings
        SET value = {string:attach_dir}
        WHERE variable = {string:uploadDir)',
        array(
            'attach_dir' => json_encode(array(1 => $modSettings['attachmentUploadDir'])),
            'uploadDir' => 'attachmentUploadDir'
        )
    );
```

Some debug code before and after, everything before gets executed, nothing after it is executed.

edit: commented that query out, the upgrade runs smoothly (until the empty step 6, that is :tongue: )

**Comment by margarett** [comment]
Got it. Whooooooo! :tada: 
Typo.
variable = {string:uploadDir)', should be
variable = {string:uploadDir}',
(curly bracket instead of bracket).
