### ISSUE TITLE
Remaining issues with upgrade

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#3184]
Following #3155 there are still some issues with the upgrade tool.
I've been trying to track this but it's the first time I'm looking into it really.

1 - no sub-template for "Step 6: Convert serialized strings to JSON"
Cause: typo in upgrade.php

```
    $context['sub_template'] = isset($_GET['xml']) ? 'serialize_json_xml' : 'serialize_json';
```

Should be $upcontext. Fixing this brings the template back but it still does nothing

2 - Step 6 doesn't perform any operation, just stays at:

> Completed 0 out of 13 tables.
> Current Table: "background_tasks"

"Continue" also does nothing.

**Comment by margarett** [comment]
OK, got issue 2. It only happens with "debug mode" and it is caused by:

```
                        if (!$temp && ($is_debug || $command_line))
                            echo "\n - Failed to unserialize the '" . $var . "' setting. Skipping.";
                        elseif ($temp !== false)
                            $new_settings[$var] = json_encode($temp);
```

The echo breaks the JS (syntax error in FF's console).
Removing $is_debug allows the step to reach the end (although I would suggest that the debug info should be kept)

I have no solution for this, though :disappointed: 

edit: this was a rough copy of the "backup" routine which still needs some love. At the end of the step, the following information is shown

> Converting data from serialize to JSON...
> Completed 13 out of 13 tables.
> Completed Table: "background_tasks".
> Backup Complete! Click Continue to Proceed.

Also, the "Continue" button seems to be dead (not dead, but it gets back to the same operation)

**Comment by Oldiesmann** [comment]
I don't know why the continue button isn't working. I basically copied the code from the function to handle backing up your database and modified it accordingly. I'll look into it further in a bit.

I think we can handle the debug thing separately but will look into that as well.

**Comment by margarett** [comment]
I also looked at bit more but it's hard because I have no idea what I'm doing :tongue: 

I think that we need to echo if in CLI mode or fill an array in $upcontext which would be displayed in the template. Or echo it in xml template if it's using Javascript? That is a bit over my head :)

**Comment by Oldiesmann** [comment]
Yeah, I'm not too familiar with how things in the upgrade work either, but should be able to figure it out at some point.

**Comment by margarett** [comment]
> should be able to figure it out at some point.

I soooooo understand you :tongue:

**Comment by margarett** [comment]
Just a note, overall the code was fine, just out of place.
It was missing the $_POST['json_done'] evaluation (which fixes the "dead" Continue button) and the 

```
            // If this is XML to keep it nice for the user do one table at a time anyway!
            if (isset($_GET['xml']))
                return upgradeExit();
```

Was out of place, which was why it didn't show the list of tables in debug mode.

The only issue is that the messages "Failed to unserialize" will never show in browser mode, only CLI

Tested a 2.0.11 to 2.1 with browser, browser + debug, CLI. The part I was struggling with (json) worked in all cases
