### ISSUE TITLE
Known Issue: Remove/Split Selected on Mobile pop

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#3193]
So while I was doing the changes, i find out the remove selected and split selected does not added to mobile pop because JS code at bottom, only adds the buttons once and to the first place (moderationbuttons/moderationbuttons_strip).

Ref: https://github.com/SimpleMachines/SMF2.1/pull/3156

**Comment by Oldiesmann** [comment]
Finally getting a chance to look at this. I think if we add an id to the mobile mod button strip we can copy the existing code for the most part and just set sSelf, sButtonStrip and sButtonStripDisplay differently as needed. I'll play with it in a bit and see what I can come up with.
