### ISSUE TITLE
 Warning: Invalid argument supplied for foreach() in ...\Sources\Load.php on line 1494

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#3194]
Errors shows on Display

**Comment by Oldiesmann** [comment]
This happens when $modSettings['displayFields'] isn't set properly. Go to Admin -> Configuration -> Features and Options -> Profile Fields and click "Save" to update it (you don't have to change anything - just saving it is enough to make SMF update that setting).

**Comment by XinYenFon** [comment]
Didn't change anything.

**Comment by Oldiesmann** [comment]
It should. Try changing which ones are active and saving them again, or editing a non-standard one (eg one that isn't included by default).
