### ISSUE TITLE
Replace XMLDoc usage with JSON

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3217]
Since we now use json intead of serialize in our code, I think the next step is to replace XMLDoc with json usage.  We use XMLDoc for our ajax responses mostly.  Replacing with json will require work, but should make it easier to work with data in javascript as we will be operating with native objects in javascript rather than a following a document tree.  The fact we will be using a javascript object rather than working down a document tree should off some minor speed increases.

If we do this, we shouldn't remove XMLDoc base, but setup a json usage and move everything over to using json.

**Comment by MissAllSunday** [comment]
Although I agree and should be done this is going to take a while and there is a lot of stuff that can get borked by doing this.  I would have agree to this is we were in alpha or beta 1 but at this point in time and the stage the deve cycle is I don't think it would be a good idea to implement this.

Mod authors rarely uses SMF's xml stuff for their mods.
