### ISSUE TITLE
Merging a new poll with a existing thread can corrupt the poll.

### ISSUE THREAD

**Issue by FearThe1337** [SimpleMachines/SMF#3221]
Havent checked for reproduction steps yet, but basically:

Preconditions:
 [x] Had 1 topic with replies with no poll.

Scenario: 
 User wishes to add a poll to the topic.

Steps
1. User created a new poll in a other board.
2. Moved poll to board with the topic.
3. Selected posts (Checkboxes at post listing)
4. Merged them without a redirect

Result:
 When clicking vote, it will state the poll does not exist.
 Furthermore the post shows a weird poll without any contents.

![2015-12-26 14_46_56- survival building competition](https://cloud.githubusercontent.com/assets/1053063/12006648/8c3a2f7e-abdf-11e5-8660-8bb84d5fd7c1.png)

**Comment by margarett** [comment]
I confirm this, looking into it a bit more ;)

edit: awkward... The poll is removed from smf_polls, as well as poll_choices.
Yet, in SplitTopics.php it's clear (debugged it) that the code which deletes exceeding polls isn't executed

```
    // Get rid of the redundant polls.
    if (!empty($deleted_polls))
    {
        $smcFunc['db_query']('', '
            DELETE FROM {db_prefix}polls
```

So I have no idea how the heck the poll gets lost :open_mouth:

**Comment by Oldiesmann** [comment]
I'll take a look at this when I get a chance (I'm off tomorrow and Thursday so probably then).

**Comment by Oldiesmann** [comment]
It appears that the poll data isn't getting set properly, so when it goes to delete the poll(s) we don't want to keep, it ends up deleting the poll that we do want to keep as well. Still looking into it though.

**Comment by Oldiesmann** [comment]
Did some digging and finally got to the bottom of this...

``` php
    // Delete any remaining data regarding these topics, this is done before changing the properties of the merged topic (else we get duplicate keys)...
    if (!isset($_POST['postRedirect']))
    {
        // Remove any remaining info about these topics...
        include_once($sourcedir . '/RemoveTopic.php');
        // We do not need to remove the counts of the deleted topics, as we already removed these.
        removeTopics($deleted_topics, false, true, false);
    }
```

The removeTopics function removes any polls associated with the old topics as well, which is why the newly merged topic no longer has a poll. Simple solution is to just set id_poll to 0 for any topic we're deleting prior to actually doing the deletion.
