### ISSUE TITLE
attachment directory setting, upgrade.php

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3223]
+++  Fixing attachment directory setting...Error: is_dir() expects parameter 1 to be a valid path, array given File: D:\wamp\www\github2.1\upgrade.php(2655) : eval()'d code Line: 1Error: unserialize() expects parameter 1 to be string, array given File: D:\wamp\www\github2.1\upgrade.php(2655) : eval()'d code Line: 22 done.

**Comment by Oldiesmann** [comment]
So something is already decoding that variable before we get to that point... I'll look into it and see what I can do.
