### ISSUE TITLE
The error log should contain more information.

### ISSUE THREAD

**Issue by FearThe1337** [SimpleMachines/SMF#3235]
The last few months my forum has had a lot of entries in the error log. Unfortionally, for a lot of these errors it's extremely hard to figure out what caused it.
For example, I have had a lot of errors/warnings of the following type:

```
2: json_encode(): Invalid UTF-8 sequence in argument
File: Sources/Load.php
Line: 3118
```

When investigating, it ends up in:

``` php
function cache_put_data($key, $value, $ttl = 120)
```

Unfortionally in this case this method alone can be called in 123 different places and any of these places could be the cause.
In addition, it's not extremely helpful that this specific error occurs on a lot of different pages (Viewing threads, uploading attachments, viewing the members list...)

I would like to suggest including a backtrace of functions called in each error so that there is more information then just the line where there was an error.
This backtrace should possibly be limited to e.g. 10 lines to prevent excessive data in errors.

**Comment by margarett** [comment]
You probably want something like this
http://custom.simplemachines.org/mods/index.php?mod=3953
But for 2.1. I would suggest that such info is only necessary to who knows what to do with so it might be better to exist as a MOD.

/2 cents :)

**Comment by Oldiesmann** [comment]
SMF should include the URL where the error occurred as well, which would hopefully help you track down the issue.

**Comment by FearThe1337** [comment]
Hmm though possible as a mod, wouldn't it be better to be a default option? I am tempted to install as little mods as possible so I know for sure errors are from the forums themself and not a mod.
As for the URL @Oldiesmann mentions, it's not helpful in this case since it happens on thousands of different pages and could only occur at specific points (e.g. cache refreshed, or maybe its for that user only),

**Comment by margarett** [comment]
I understand that, but IMO it might be considered bloat because very few people would use it properly. But I respect what you're saying. It's not my call though :tongue: 

If you want to try it, Arantor's MOD works just fine in 2.1 with just minor tweaks ;)
https://github.com/margarett/StackTrace_SMF2.1

**Comment by FearThe1337** [comment]
It's not mine either hence, I went ahead and made an issue instead of a PR.
Though I would assume that e.g. people who help people with issues could use the backtrace/stack trace as well for certain error messages.

**Comment by joshuaadickerson** [comment]
If an error occurs, it's a big deal. The more information a user has, the better. I agree that there should be a stack trace and url. If there is user information, include that as well. Everything about the request should be logged. I doubt anyone would think that's bloat.

**Comment by FearThe1337** [comment]
In relation to @joshuaadickerson 's response, urls are includes by default but not always useful.
E.g. in the case of issue #3247 the url would be as generic as index.php or a viewpost url.

I would also suggest issue #3247 as a good example why it is needed at times.

**Comment by Towelie** [comment]
Doesn't seem ideal to force people to use a mod to get basic information on what causes an error.

**Comment by MissAllSunday** [comment]
> Doesn't seem ideal to force people to use a mod to get basic information on what causes an error.

SMF error log system already provides basic information, whats been discussed here its to expand that information.

**Comment by MissAllSunday** [comment]
I tend to be more inclined to leave as it is, sometimes the user gets freaked out by over-exposition of info.

Not every user is a power-user or is capable of actually understanding whatever the error is saying. It may be counterproductive to have a regular user exposed to too much info.

A mod can address this need if and when needed.
