### ISSUE TITLE
Error log ip length is too short?

### ISSUE THREAD

**Issue by FearThe1337** [SimpleMachines/SMF#3248]
Just noticed that the ip in the log_errors table in mysql is 16 characters ( char(16)).
IPv6 adresses can be e.g. 2001:0db8:0000:0000:0000:ff00:0042:8329
which has 39 characters?

**Comment by albertlast** [comment]
yep looks not good.
A possible solution would be to use the ip datatype(inet) which came in the pr https://github.com/SimpleMachines/SMF2.1/pull/3222

**Comment by albertlast** [comment]
Possible duplicate to https://github.com/SimpleMachines/SMF2.1/issues/3291

**Comment by albertlast** [comment]
Can be closed?

**Comment by frandominguezl** [comment]
This can be closed @Oldiesmann

**Comment by frandominguezl** [comment]
@Colin

**Comment by colinschoen** [comment]
Thanks,

Fixed with #3364 and #3369. Closed.
