### ISSUE TITLE
Kill legacy MySQL code

### ISSUE THREAD

**Issue by Daniel15** [SimpleMachines/SMF#3256]
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Db-mysql.php

This is super legacy code that probably shouldn't exist any more. The old MySQL extension has been deprecated for many many years now... MySQLi was released in 2004 (bundled with PHP 5.0) and PDO was released in 2005 (bundled with PHP 5.1). There's no reason to continue even supporting the old extension. 

The entire database abstraction layer in SMF should probably be replaced with PDO at some point.

**Comment by live627** [comment]
We can do this in a future version. Support for MySQLi is built in.

**Comment by MissAllSunday** [comment]
As already explained on the forum: http://www.simplemachines.org/community/index.php?topic=540808.msg3856839;topicseen#msg3856839

2.1 uses mysqli by default for new installations and the upgrade process set it as default too.

Subs-Db-mysql.php is essentially dead weight and it doesn't do any harm by keeping it unless you are very concern about the 28KB of space it occupies.

PDO is out of the scope for this particular version. 2.1 is set to be as compatible with 2.0 as possible and that means keeping the old DB layer.

**Comment by albertlast** [comment]
PDO got one very big weaknes,
that is the missing of sql featurs.
- like window function
- operator http://stackoverflow.com/questions/21095399/is-there-a-way-to-use-the-new-postgresql-9-3-json-operators-in-phalcon
- cte support

i would recommend to keep on mysqli and pg_*
