### ISSUE TITLE
Immediate registration

### ISSUE THREAD

**Issue by redonesmf** [SimpleMachines/SMF#326]
By default SMF allows "immediate" registration for new members. My suggestion is that this is removed by default instead adding some new checks for newly registered members.

**Comment by matthew-kerle** [comment]
Thanks for pointing this out @redonesmf, I definitely would agree that this should be incorporated. Are you interested in working on the Pull Request for this, if so, that'd be fantastic!

We should probably either set it to Email Activation by default, or put the dropdown for selection as part of the installation script. I wouldn't be opposed to either route, really.

**Comment by redonesmf** [comment]
I don't mind helping, its been quite some time since I last went through any SMF code to be honest.

**Comment by matthew-kerle** [comment]
Well if you'd like to that'd be awesome. If not, I'll do my best to get to it here at some point. If you have any specific questions feel free to shoot me a message somewhere.

**Comment by illori** [comment]
this has been merged [and fixed] please close

**Comment by matthew-kerle** [comment]
This was merged in earlier...closed!
