### ISSUE TITLE
MySQL in ANSI mode and strict mode

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#3260]
to get mysql and postgresql more in sync,
i would recommend to use the ansi mysql mode http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi
with that option on,
mysql and pg statements are more the same.

the backtick ` is in this mode not available there for define the standard "
and you can use || to concat string

and i would like to see to use the strict mode http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-strict to get a better error handling (in 5.7 is STRICT_TRANS_TABLES default on)

motivation problems like that: https://github.com/SimpleMachines/SMF2.1/issues/3261
would be already fixed.

**Comment by sbulen** [comment]
@albertlast -
Wondering if this can be closed, due to this PR: Set Default SQL_MODE #4068

**Comment by albertlast** [comment]
Well we don't use/set strict mode,
i believe this topic is to late for implement.
