### ISSUE TITLE
Installation mods from .tar.gz package works wrong.

### ISSUE THREAD

**Issue by thunderamur** [SimpleMachines/SMF#3265]
I tried to fix the mod and pack it in .tar.gz. After the installation has detected that some files haven't unpacked yet and the forum crashed.
The same fixed mod packed in .zip is working properly.

**Comment by Oldiesmann** [comment]
Are you using 2.1? The files downloaded from GitHub shouldn't be any different regardless of which archive format is used.

**Comment by live627** [comment]
Which mod?

**Comment by thunderamur** [comment]
Yes, I using 2.1 Beta 2.
PortaMX Mod. https://github.com/PortaMx/PortaMx-Virgo-2.0-Beta-2

**Comment by thunderamur** [comment]
I reproduced the problem twice or thrice

**Comment by Oldiesmann** [comment]
I'll update my test board to the latest GitHub code soon and see if I can reproduce it. SMF should handle the package just fine regardless of which archive format is used.

**Comment by live627** [comment]
It was probably double-foldered.
