### ISSUE TITLE
Additional integration hook for timeformat

### ISSUE THREAD

**Issue by margarett** [SimpleMachines/SMF#3279]
According to
http://www.simplemachines.org/community/index.php?topic=542867.0
Is it worth/possible to have a new hook for the timeformat function?

**Comment by MissAllSunday** [comment]
I did look at that request, I just didn't found a good place to add the hook.

Having a hook in a highly used function shouldn't be an issue, if there is no function attached to that particular hook, SMF will return pretty early in the process.

Of course if the attached function does perform some heavy queries and stuff then its going to have an impact but thats out of the scope here and it happens on every hook call too.
