### ISSUE TITLE
IPV6 and Ban Mask future

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#3281]
I want to ask how the future ban mask should look,
this awnser is important for the pr https://github.com/SimpleMachines/SMF2.1/pull/3222

the existing look like this:
127.0.0.1 - 255

a alternativ solution could be:
127.0.0.1 - 127.0.0.255

i like last more, because it's looks for me more cleaner and i see less problems with ipv6,
is important to know that in ipv6 exist a short key :: which is hard to implement in the first version

**Comment by live627** [comment]
The latter solution looks cleaner to me. Probably easier to understand for the average joe...

Would it support wildcards?

I'm not very familiar with the ban system.

**Comment by albertlast** [comment]
Supported wildcard use are:
127.*
and 127.0.\* - 127.0.*

127.\* will be converted internaly to 127.\* - 127.*

and single inline wildcard:
127.0.*.1 or 127.*.*.1
but not 
127.*.1 (is there a need for?)

Logic can be foud in Sources/Subs.php between line 3448 and 3492.
