### ISSUE TITLE
SMF 2.1 minimal requirements reference

### ISSUE THREAD

**Issue by Underdog-01** [SimpleMachines/SMF#3286]
Some changes require an update to the SMF 2.1 minimal requirements reference which should be edited more frequently to refelct these changes.
out of date ref. http://wiki.simplemachines.org/smf/SMF2.1:Features#Minimum_requirements
COALESCE requires MySQL 5.6
Imo a minimal requirements reference should be included on the GitHub repository resource to make things easier. That way the SMF wiki page can be updated for releases posted on the SMF website itself.

This minimal requirements reference can be posted in the GitHub SMF 2,1 wiki which I would post myself except atm I am not entirely sure of the exact minimal requirements due to so many "standard" changes. Though this is my point that something like this needs to be addressed as newer code is implemented that requires more up to date versions of PHP, MySQL, etc.

**Comment by albertlast** [comment]
coalesce exists with mysql 5.0 http://dev.mysql.com/doc/refman/5.0/en/comparison-operators.html
pg min version is in documentation outdated should be 8.3 (full text search)

**Comment by Underdog-01** [comment]
You are correct about the MySQL version as I was looking at an incorrect reference.
Good catch on the PostgreSQL version.

Imo a minimal requirements on this repo in its wiki as I described would be prudent.

**Comment by albertlast** [comment]
Could be closed as far i see?
