### ISSUE TITLE
Signup process broken

### ISSUE THREAD

**Issue by bperry921** [SimpleMachines/SMF#3290]
I have a problem where no one can complete the registration process because it will not recognize a correct set of verication characters from the image, even when i know the characters are correct.

**Comment by Oldiesmann** [comment]
Can you provide a link to your forum?

**Comment by bperry921** [comment]
sure, it's http://www.rjventure.com

**Comment by smfbigguy** [comment]
I tried on your site and mine. My signup works fine. Do you have the answers to the questions wrong maybe. ??   (I'm running beta 3)

**Comment by bperry921** [comment]
AH HA!! went in to double check my answers and discovered that somewhere along the line they have been wiped out, there was like 20-30 questions. Thanks so much...

**Comment by live627** [comment]
20-30 questions? Jesus.

**Comment by bperry921** [comment]
Yep, but only two required to answer, the system picks them randomly so spam robots would have a harder time memorizing every question, yes? I say the more the merrier...
