### ISSUE TITLE
Error when viewed as guest.

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#3294]
Just upgraded from 2.1 beta 2 which was working fine.  to the latest files (beta 3) from the repo. Now when viewing site as guest I get a error on page.   Obviously I was logged in as admin while upgrading, and site worked perfectly while I was logged in, no errors. Now session has expired I can no longer log in.

"Database Error
Please try again. If you come back to this error screen, report the error to an administrator."

And these three errors in the error log every time you view the index page.as guest.

Type of error: Database
Database Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.156.188 BETWEEN bi.ip_low and bi.ip_high OR )' at line 6 
http://cctestsite.info/testsite3/index.php? 
File: /Sources/Security.php
Line: 226 

Type of error: General
 2: inet_pton() [<a href='function.inet-pton'>function.inet-pton</a>]: Unrecognized address  
http://cctestsite.info/testsite3/index.php? 
File: /home2/cameracr/public_html/cctestsite.info/testsite3/Sources/Security.php
Line: 1274 

Type of error: Undefined
 8: Undefined variable: bin 
 http://cctestsite.info/testsite3/index.php?File: /home2/cameracr/public_html/cctestsite.info/testsite3/Sources/Subs.php
Line: 4787

**Comment by lurkalot** [comment]
Ran this upgrade, but the problem's still there. http://cctestsite.info/testsite3/index.php

Database Error 
Please try again. If you come back to this error screen, report the error to an administrator

Still can't login either.

**Comment by lurkalot** [comment]
Sorry.. looks like I missed a source file.  All seems to be working now, thanks.

**Comment by live627** [comment]
ah cool
