### ISSUE TITLE
newest upgrade wipes out anti spam questions

### ISSUE THREAD

**Issue by bperry921** [SimpleMachines/SMF#3295]
Did the latest upgrade, after it finished must go back in and replace anti spam questions and answers from previous version, keeps wiping them out.

**Comment by illori** [comment]
my anti-spam verification questions are still in place. although it seems i only have 1, i dont recall if i had added more then 1.

**Comment by bperry921** [comment]
yea it seems to keep the questions, but on my end it wipes out the answers so when i try to manually put the answers back in and save, it wipes out everything and starts over from scratch...

**Comment by illori** [comment]
Do you have multiple answers?

**Comment by bperry921** [comment]
no, just one per question

**Comment by illori** [comment]
If there is no answer at least in 2.0 it does not save the question... Odd
that you have to re-enter the answer and the question is still present.

**Comment by Kindred-999** [comment]
I just did the update to the newest build on Monday -- and it left the questions and answers alone for me... I had 10 questions, some with multiple answers, some with only one... all remained untouched

**Comment by bperry921** [comment]
yep, you're special... each time I upgrade it has the questions displayed, but if I do nothing and hit save, it wipes out everything including the number of questions required...

**Comment by bperry921** [comment]
it could be that I have had a problem of some type from the very first install of 2.1 which I have yet to nail down, it seems to be some type of database issue but the exact cause evades me...it may also be the culprit behind a curious thing with the board viewers module too, it won't function like its suppose to as well as my chatting third party module, neither one recognizes that there are guests online let alone members, yet the who's online screen says different and functions as always, but in this most recent update I notice some funky stuff going on with ip addresses

**Comment by MissAllSunday** [comment]
It seems this is an issue with partial upgrading from old alpha versions.

If this still happens on a full upgrade (from 2.0.x to Beta3) please do open a new issue.
