### ISSUE TITLE
upgrade.php sql syntax error

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3298]
+++  duplicate to topics_last_message_sticky and topics_board_news done.
 Successful.
- Unsuccessful!  Database error message:
  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(ip_low,ip_high) ON smf1_ban_items' at line 1

**Comment by lurkalot** [comment]
I had the same problem this morning after running upgrade.php again.  Then I noticed a source file had changed within the last four hours or so.  Uploaded the source files again and the site popped up like magic. http://cctestsite.info/testsite3/index.php

**Comment by illori** [comment]
ah, your right it does look fixed now.
