### ISSUE TITLE
Undefined variable: ip_array

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#3301]
Not sure if this is a bug of not, or if it's been reported and fixed, thought I'd mention it anyway.

I went to Admin > Forum > Search Engines.  

Set Search Engine Tracking Level = Standard
Set Apply restrictive permissions from group = Disabled
Set Show spiders in the online list = Show Spider Names

Within a few minutes I got two errors in the log, (now have nineteen errors all the same type).

Guest
Today at 08:41 PM
a1deccd17653562588e401be2c4d795c
Type of error: Undefined
8: Undefined variable: ip_array 
http://cctestsite.info/testsite3/index.php?topic=2.0 
File: /homex/xxxxxx/xxxxxx/cctestsite.info/testsite3/Sources/Subs.php
Line: 3510

Guest
Today at 08:34 PM
1e6daff224f2312def4eeddf6378df85
Type of error: Undefined
8: Undefined variable: ip_array 
http://cctestsite.info/testsite3/index.php? 
File: /homex/xxxxxxx/xxxxxxx/cctestsite.info/testsite3/Sources/Subs.php
Line: 3510 

I also noticed in the users online page a IP address from the guest as 0.0.0.0
![whosol](https://cloud.githubusercontent.com/assets/6047983/13404352/235d9116-df11-11e5-9be7-0a18491ab952.jpg)

**Comment by MissAllSunday** [comment]
ip2range function in Subs.php has had some changes recently, make sure you got the most recent code from this repo.

If you have an old installation then you will need to manually add the follow columns:

ALTER TABLE {$db_prefix}ban_items ADD COLUMN ip_low varbinary(16);
ALTER TABLE {$db_prefix}ban_items ADD COLUMN ip_high varbinary(16);

and delete some these:

ALTER TABLE {$db_prefix}ban_items
DROP ip_low1,
DROP ip_low2,
DROP ip_low3,
DROP ip_low4,
DROP ip_low5,
DROP ip_low6,
DROP ip_low7,
DROP ip_low8;

**Comment by MissAllSunday** [comment]
Oh, nevermind, I can reproduce this on my test board too.

**Comment by albertlast** [comment]
ther should be two error,
- not valid ip address
- undefined var if the ip address are not valid (this i fixed)

btw in line 3510 doesn't exist this return -> the Subs.php is not update to date?

**Comment by MissAllSunday** [comment]
I'm getting the following error:

```
Database Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '208.115.113.92' LIKE bi.hostname) OR '????' BETWEEN bi.ip_low and bi.ip_high)' at line 6


SELECT bi.id_ban, bi.email_address, bi.id_member, bg.cannot_access, bg.cannot_register,
bg.cannot_post, bg.cannot_login, bg.reason, COALESCE(bg.expire_time, 0) AS expire_time
FROM smf_ban_items AS bi
INNER JOIN smf_ban_groups AS bg ON (bg.id_ban_group = bi.id_ban_group AND (bg.expire_time IS NULL OR bg.expire_time > 1456946594))
WHERE
('

```

Its related to constructqueryban()

**Comment by albertlast** [comment]
Can you please change the Security.php like this https://github.com/SimpleMachines/SMF2.1/compare/release-2.1...albertlast:removeconstructBanQueryIP ?
Maybe the error msg would be than much clearer.

**Comment by MissAllSunday** [comment]
Did that and now theres another error:

Wrong value type sent to the database. IPv4 or IPv6 expected.(ip)
Function: is_not_banned index.php?topic=247.msg1390.
File: /public_html/Sources/Security.php
Line: 227

**Comment by MissAllSunday** [comment]
mmm, nope, still having errors:

Database Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '208.115.113.92' LIKE bi.hostname))' at line 6

SELECT bi.id_ban, bi.email_address, bi.id_member, bg.cannot_access, bg.cannot_register,
bg.cannot_post, bg.cannot_login, bg.reason, COALESCE(bg.expire_time, 0) AS expire_time
FROM smf_ban_items AS bi
INNER JOIN smf_ban_groups AS bg ON (bg.id_ban_group = bi.id_ban_group AND (bg.expire_time IS NULL OR bg.expire_time > 1457105132))
WHERE
( ' 

File: /public_html/Sources/Security.php
Line: 227

**Comment by albertlast** [comment]
in mysql version i didn't receive any error,
so it's mostly fishing in the dark...
can you please try this in you mysqli oder mysql version: https://github.com/SimpleMachines/SMF2.1/compare/release-2.1...albertlast:nextTrytoFix
which ever you use.

**Comment by MissAllSunday** [comment]
I'm using 5.5.45-cll-lve

Thing is, we shouldn't be adding fixes for specific DB versions.

**Comment by albertlast** [comment]
this is no fix for specif db version, but i'm to lazy to do this for both file, when i not know if this the right solution.
change hex to unhex in both db version,
i hope this fix the problem...

**Comment by MissAllSunday** [comment]
Yeah it seems that stopped the error. Haven't had any new error  entries since I applied.
