### ISSUE TITLE
Another WYSIWYG editor issue

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#3313]
If the WYSIWYG editor is enabled by default, then when the editor is first loaded, the body of the contenteditable document in the iframe starts off with the following content: `<p><br></p>`

Because of these paragraph tags, if the user just starts typing and presses return once, it _looks_ as though that one keypress has inserted a blank line between the two paragraphs. In reality, only that single line break will be preserved when the user posts, requests a preview, or even just hits the View Source toggle button. This is jarring, since the user thought she had cleanly separated her paragraphs, because that is how they visually appeared, when in fact she had not.

The simplest solution, it seems to me, is to make sure the editor's contenteditable document starts out with a truly empty body element. If the offending `<p>` tags are not present at the start, then this issue never arises.

The problem appears to lie in jquery.sceditor.bbcode.min.js. I _think_ I've managed to fix it in a forthcoming pull request—at least, it seems to be working in my tests. But because that script is minified, it is nearly impossible to evaluate whether these edits could be improved or if they are likely to break something else in non-obvious ways. All of which is to say, if either (a) the non-minified version of the script could be included in the repository during the beta stage, or (b) someone more versed than I in JavaScript and SCEditor's functioning in particular could evaluate my changes, that would probably be a good idea.

**Comment by MissAllSunday** [comment]
Is this something that happens only on SMF?  if not it might be good to send a bug report/pr to the editor author at https://github.com/samclarke/SCEditor  as it will be easier for us to incorporate any new version.  If there is no response then we can look at incorporate this fix ourselves.

**Comment by Sesquipedalian** [comment]
Only on SMF, yes. On further investigation, the problem was simply that our modified version of jquery.sceditor.default.css was missing a rule-set that should have been present. My new commits solve it nicely.
