### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3323]
Forum updated to version 2.0.11 to 2.1 ten days ago. Update went smoothly and without error.
Priority output in the separation of threads when vybiraesh separate the selected messages is broken, a screen attached. See how The order of the violated almost everywhere shoves the last message a message of 6 February. Light wedge has converged on this number ???
![c92edb92e531](https://cloud.githubusercontent.com/assets/17574854/13546426/e096d50c-e2be-11e5-84b3-2acdc7c3e61d.jpg)

**Comment by live627** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/3374
