### ISSUE TITLE
Quote not works properly [closed by PortaMx]

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3327]
There is small Bug in the Post.php on line 816
a space after **link=** is missing.

Corrected line:

>   $form_message = '[quote author=' . $mname . ' link= msg=' . (int) $_REQUEST['quote'] . ' date=' . $mdate . ']' . "\n" . rtrim($form_message) . "\n" . '[/quote]';

**Comment by PortaMx** [comment]
Well .. the quote dount work ,, only in the WYSIWYG Editor the quote shown correct.
The fix what I have posted above is correct, but .. no correct quote if the content converted in the subs.php !!

In the message:
![image1](https://cloud.githubusercontent.com/assets/2270223/13578119/4c370be6-e496-11e5-84b2-bb81134d6974.png)

in the WYSIWYG editor:
![image2](https://cloud.githubusercontent.com/assets/2270223/13578131/5d9c5346-e496-11e5-8c01-4bbd5ae2172a.png)

**Comment by Oldiesmann** [comment]
The way the quote is displayed in the WYSIWYG editor has been messed up for as long as I can remember. I don't know if anyone has ever looked into fixing it though.

**Comment by PortaMx** [comment]
**Forgott the problem in the messages .. was my foult (sorry)**
The data format for the WYSIWYG editor i have changes as I post in the other issue (looks better)
