### ISSUE TITLE
Dateformat in WYSIWYG editor looks ugly

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3330]
The qoute datastring looks bad (in germany)
I don't known if is a server issue .. but if find a fix for that.

In the jquery.sceditor.smf.js find
`if (typeof attrs.date !== "undefined" && attrs.date)
            {
                attr_date = attrs.date;
                sDate = '<date timestamp="' + attr_date + '">' + new Date(attrs.date * 1000) + '</date>';
            }`

and replace with
`if (typeof attrs.date !== "undefined" && attrs.date)
            {
                attr_date = attrs.date;
                tDate = new Date(attrs.date * 1000);
                sDate = '<date timestamp="' + attr_date + '">' + tDate.toUTCString() + '</date>';
            }`

Before change:
![image3](https://cloud.githubusercontent.com/assets/2270223/13582417/84955734-e4ac-11e5-960b-1c0cfee9178e.png)

After change:
![image4](https://cloud.githubusercontent.com/assets/2270223/13582425/946edd4c-e4ac-11e5-97f7-5f7327b0895a.png)

**Comment by Sesquipedalian** [comment]
But isn't that forcing the date to be shown in GMT?

**Comment by PortaMx** [comment]
Well .. I fond a goof solution for this ;-)

`if (typeof attrs.date !== "undefined" && attrs.date)
            {
                attr_date = attrs.date;
                tDate = new Date(attrs.date * 1000);
                sDate = '<date timestamp="' + attr_date + '">' + decodeURIComponent(escape(tDate)) + '</date>';
            }
`

Looks as:
![image5](https://cloud.githubusercontent.com/assets/2270223/13606159/350af756-e54b-11e5-8f1b-c35b44c19480.png)

**Comment by PortaMx** [comment]
Well .. after a long run and thinking, I have completely redesign the sc-editors quote function.
Now it looks mostly identical as quotes in the post.
Also I implement a lot of checks, they remove illegal parts in the quote (like missing link, but date set) because these will also not correct converted in the parse_bbc function.
In the sc-ediors css, I make smaller changes, for a better look.
Also I add the missing qoute.png (he, he ;-) , so this is now look in the WYSIWYG edior (applause !!)

If you have interest to implement this, let my known... I add imes to see, what I have done.

BBC EDITOR
![image6](https://cloud.githubusercontent.com/assets/2270223/13632308/54c021f4-e5e9-11e5-98ae-8fff80edde79.png)

WYSIWYG EDITOR
![image7](https://cloud.githubusercontent.com/assets/2270223/13632317/5ecffdc2-e5e9-11e5-975e-670ca6901b59.png)

POSTED
![image8](https://cloud.githubusercontent.com/assets/2270223/13632331/6591cee2-e5e9-11e5-8cd2-54d7237a9b0e.png)

Thanks for reading .. any comments are wellcome ...

**Comment by Sesquipedalian** [comment]
Looks nice! You should submit these changes in a pull request.

**Comment by XinYenFon** [comment]
@Sesquipedalian she had a PR back in day, problem was PR had more than this so its rejected. You can dig-up her job in closed PRs.

**Comment by Sesquipedalian** [comment]
>she had a PR back in day, problem was PR had more than this so its rejected. You can dig-up her job in closed PRs.

I'd thought we'd merged something that took care of this, but I see I was mistaken. #4129 is based on the relevant change in that PR
