### ISSUE TITLE
Package upload failed.  Works in SMF 2.0.x fails in SMF 2.1

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#3337]
Works in SMF 2.0.x fails in SMF 2.1 tested on latest Beta 3 as well.

Here is the package. A zip file. Trying to install on a windows 2008 server.
http://www.smfseo.net/ezPortal3.1beta5.zip

Other note. Zip was built with the windows compressed zip function in windows 7

Fails back with the following message: And if Do below it works ok...

Package upload failed due to the following error:
"Although the package was downloaded to the server it appears to be empty. Please check the Packages directory, and the "temp" sub-directory are both writable. If you continue to experience this problem you should try extracting the package on your PC and uploading the extracted files into a subdirectory in your Packages directory and try again. For example, if the package was called shout.tar.gz you should:
1) Download the package to your local PC and extract it into files.
2) Using an FTP client create a new directory in your "Packages" folder, in this example you may call it "shout".
3) Upload all the files from the extracted package to this directory.
4) Go back to the package manager browse page and the package will be automatically found by SMF."

**Comment by MissAllSunday** [comment]
Are you using the latest build?  I tested your package on both local and my server and was able to install your mod with no errors.

**Comment by VBGAMER45** [comment]
Yes latest files as of this morning.
When it tries to add package in the error log I get this error for all files 

file_get_contents(phar://C:/inetpub/wwwroot/smfseo/beta3/Packages/ezPortal3.1beta1.2.zip\EzPortal.english-utf8.php): failed to open stream: phar error: Cannot open temporary file for decompressing phar archive 

PHP Version 5.4.45
With Apache 2.2

zip

Zip enabled
Extension Version   $Id: 6c872ebfb022206b0cc2a183c7a388c7b6ad8685 $
Zip version 1.11.0
Libzip version  0.10.1

zlib

ZLib Support    enabled
Stream Wrapper  compress.zlib://
Stream Filter   zlib.inflate, zlib.deflate
Compiled Version    1.2.7
Linked Version  1.2.7

Directive   Local Value Master Value
zlib.output_compression Off Off
zlib.output_compression_level   2   2
zlib.output_handler no value    no value

**Comment by MissAllSunday** [comment]
Seems to be a permissions related issue, make sure the dirs your mod  
modifies are writable.

Does the error log indicates any file or line?

**Comment by VBGAMER45** [comment]
All the files and folders are writable.  The mod will install if I upload it extracted to a folder in the packages area which I can then install it.

Each time attempt to upload the package from my computer I get 572 errors same error message just different file.

 Type of error: General
2: file_get_contents(phar://C:/inetpub/wwwroot/smfseo/beta3/Packages/ezPortal3.1beta1.2.zip\ezportal2rc2.xml): failed to open stream: phar error: Cannot open temporary file for decompressing phar archive "C:/inetpub/wwwroot/smfseo/beta3/Packages/ezPortal3.1beta1.2.zip" file "ezportal2rc2.xml"   http://smfseo.net/beta3/index.php?action=admin;area=packages;get;sa=upload
File: C:/inetpub/wwwroot/smfseo/beta3/Sources/Subs-Package.php
Line: 267

The first time I have noticed a phar:// path before which was in the error log.

**Comment by VBGAMER45** [comment]
Looked a little more looks like it is a php 5.4 issue  with the sys_temp_dir setting to c:\windows which I don't want to make writable. Tried changing in the php.ini didn't work 
https://github.com/cztomczak/phpdesktop/issues/39

**Comment by MissAllSunday** [comment]
Thats weird, I have a test forum on windows with php5.4 or 5.6 I cannot remember and I didn't find any issue.

**Comment by VBGAMER45** [comment]
Yeah seems to occur from 5.4 and less that I heard from.

**Comment by VBGAMER45** [comment]
Also I am running on windows with apache as it's own user account to lockdown for security

**Comment by sbulen** [comment]
These really sound very similar to the issues that led to this PR:  Fix issues with package_flush_cache() that prevented uploading of themes #3770

I'm able to process the .zip file listed above.  The same routines are used for themes & packages.

Hopefully this can be retested & closed out.

**Comment by sbulen** [comment]
I just found 3 of these messages in the error log, so there is, in fact, some error outstanding:
![image](https://cloud.githubusercontent.com/assets/23568484/23824885/1f7af444-0634-11e7-9d91-0bad52c0fd3a.png)

**Comment by sbulen** [comment]
This is similar to, but not the same as PR #3770 .   

Several file & dir variables aren't set early, even during the initial upload.  In PackagesGet.php, PackageUpload, $packagesdir is null on a fresh install...  So it is working on files, for example, named "\1483912527.zip", where it was expecting a full file/path spec.  When it tries to move/rename anything, it gets permission denied errors due to the non-existent path.  

Very different results on a new install vs an upgrade.  I don't think the packages dir is even getting set on an install at the moment, so it fails much earlier in the process.

Peeling the onion...  First step, get it uploaded where it can actually work on it...

**Comment by sbulen** [comment]
I've been doing some testing here, and I'm now of a mind that this can be retested & closed out.  

I've been able to fully install the package above in a vanilla 2.1 environment & an upgraded 2.1 environment.

**Comment by sbulen** [comment]
FYI...  I DID have issues for a while, but those were traced back to an error in my 2.1 install.  I had copied the install* files before installation, but I did not copy the blank settings.php file before installation.  The $packagesdir was therefore not set in settings.php, & this led to all kinds of issues (actually very similar to those reported above).  Oddly enough, a settings.php is created, and it has all values OTHER than $packagesdir.  Pretty much the only thing you can't do is install packages...  

It *may* be worthwhile issuing an updateSettings() in Load.php to set $packagesdir.

**Comment by sbulen** [comment]
@VBGAMER45 - could you retest & let us know how it goes?

If you get similar access issues, please confirm the presence of a valid $packagesdir entry in your settings.php file.

**Comment by colinschoen** [comment]
Bump @VBGAMER45

**Comment by VBGAMER45** [comment]
I no longer use php 5.4 moved on to 5.6

**Comment by sbulen** [comment]
I enabled 5.4 in my test system and was able to upload & successfully install the package specified above.

This can be closed.
