### ISSUE TITLE
Interesting effect *g*

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3339]
Try follow:
1. Create a new topic, attach a Image, insert this in the topic - save.
2. Quote this topic full, type in a little bit, save.

Now go to the quoted topic, click on the quotet image ...
Ha  ... The image in the original topic is zoomed (grin)

I think that is never tested !?

Also I wonder me, why SMF don't use HighSlide for Image zooming .. I do it and that looks very good !

**Comment by XinYenFon** [comment]
I agree. Even we can use small tip/trick written by bloc http://www.simplemachines.org/community/index.php?topic=544339.msg3865320#msg3865320

**Comment by Oldiesmann** [comment]
SMF has had the "click a resized image to view the full size version" thing since 2.0.

**Comment by XinYenFon** [comment]
Something like: https://github.com/lokesh/lightbox2/ maybe?

**Comment by PortaMx** [comment]
HighSlide is very simple to implement, with many options and free for NPO's
http://highslide.com/

**Comment by PortaMx** [comment]
I found a free image viewer, they is free, small, easy to use and works with all browser like Chrome, Opera, FireFox, Edge, IE, on Mobile devices (tested with Nexus 5 and 7), responsive design and is simple to implement. Also the problem as I describe above can supressed ...

If SMF have interest on this, let me known ...
