### ISSUE TITLE
Membergroup icons... Unable to add any

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#3340]
The dropdown in the membergroup edit screen shows the standard icons in the list -- However, I added 15 new images to the default and custom theme's images/membericons directory -- but none of them got added to the dropdown (and the screen only accepts the dropdown now - I can not manualyl type a file name into the box)

(running almost beta 3 from last week or so.)

**Comment by illori** [comment]
maybe in part related to #2766 ? seems inconsistent on where it is calling those images from.

**Comment by margarett** [comment]
It's not inconsistent :tongue: 
@Kindred-999 are the images bigger than the hardcoded limit?
https://github.com/SimpleMachines/SMF2.1/issues/2766#issuecomment-94563284

**Comment by frandominguezl** [comment]
@colinschoen @Oldiesmann Please close this one
