### ISSUE TITLE
[Suggestion] Allow custom jQuery

### ISSUE THREAD

**Issue by iveinsomnia** [SimpleMachines/SMF#335]
Admin:
_Source for the jQuery Library_
- Auto
- Local
- Google CDN
- Custom:
  - Direct link: [input]

input can be local `/js/jQuery` or external `http://code.jquery.com/jquery-git2.js`

**Comment by NanoSector** [comment]
I wonder how you will handle the Auto switch. But this may be an useful feature, even though not many would use it.

**Comment by iveinsomnia** [comment]
![image](https://f.cloud.github.com/assets/3958341/406694/6d5df6f2-aab2-11e2-88f6-2c46dc68b4f6.png)
The "Auto" is already present in the 2.1, admin > features
I only suggest to add a direct link input.

**Comment by colinschoen** [comment]
This is a very useful feature. Good idea.
