### ISSUE TITLE
Admin manage members hook placement

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#3350]
Hello,

Wanted to do it myself but thought to ask some opinions first. In ManageMembers.php, we have this:

```
$subActions = array(
    'all' => array('ViewMemberlist', 'moderate_forum'),
    'approve' => array('AdminApprove', 'moderate_forum'),
    'browse' => array('MembersAwaitingActivation', 'moderate_forum'),
    'search' => array('SearchMembers', 'moderate_forum'),
    'query' => array('ViewMemberlist', 'moderate_forum'),
);

call_integration_hook('integrate_manage_members', array(&$subActions));
```

And then later we have the $context['tabs'] getting defined. So if I add something via hook to $subActions, I can't catch $context['tabs'] to add it there as well. (of course if I want it to be a tab)

Shouldn't the $context['tabs'] go to top, between the $subActions and the hook? (or move the hook down below tabs?)

**Comment by Oldiesmann** [comment]
It might just be better to add a hook for the tabs to each location. That way you can set the tabs from a single function instead of having to do global $context and hope you have all the info you need.

**Comment by asmith20002** [comment]
Sure that's the way. Was just trying to avoid adding another hook (of the same nature) in the same function.

**Comment by asmith20002** [comment]
Similar thing is happening in ManageSettings.php. The hook is placed to the point that it won't work.

The placemenet of the hook is fine and where it should be. (after $subActions and tabs definition)
But there's this function loadGeneralSettingParameters which is overwriting $_REQUEST['sa'] and it's getting called BEFORE the hook. So even if the hook adds something to $subActions, the function loadGeneralSettingParameters will overwrite $_REQUEST['sa'] and paralyzes the hook.

Gotta replace these hooks in similar functions and unite them with one pattern/logic. Still believe that it's better to have one hook dealing with both $subActions and tabs.

**Comment by MissAllSunday** [comment]
Yes, whenever possible, Any relevant $context vars should be defined before a hook to make sure they're available.

I've seen cases like this and have changed a few but theres still a few more left so if you found any please go ahead and make the relevant changes.

**Comment by jdarwood007** [comment]
Why do you need to overwrite $_REQUEST['sa']?  That is what the current subaction is and it makes sure that a default one is selected.  You should have launched your call in the hook for that section (adding in the function/method?) and let loadGeneralSettingParameters() do its thing.

If you are trying to add to $context['tabs'], call the integrate_admin_areas hook and add in your needed areas or information, you will have the $admin_areas fully at your disposal.  This hook is kinda hidden, but its called from the createMenu function.  All menus have callable hooks on them if you specify their id properly.

If I can get [SimpleDesk](https://github.com/SimpleDesk/SimpleDesk) to run entirely on hooks, I don't think our current hooks is too far off from working well.  We may need some more clear documentation, but it works.

I should note its been a while since I had time to work on SimpleDesk, so not sure how well it runs against Beta 3.  It should, but haven't tested it.

**Comment by asmith20002** [comment]
@MissAllSunday

I'll review the codes to find similar issues and make the relevant changes.

@jdarwood007 @MissAllSunday

File: ManageSettings.php
On line 98 there's this hook: integrate_modify_features

But a few lines before it we have loadGeneralSettingParameters() which is overwriting $_REQUEST['sa'] to default if it doesn't find the key.

I think this line in loadGeneralSettingParameters():

`
$_REQUEST['sa'] = isset($_REQUEST['sa']) && isset($subActions[$_REQUEST['sa']]) ? $_REQUEST['sa'] : (!empty($defaultAction) ? $defaultAction : array_pop($temp = array_keys($subActions)));
`

Should be removed and be placed in the same function where $subActions is getting defined. All over SMF you see that code in that fashion. (after $subActions initial definition) why break that pattern and make exception for loadGeneralSettingParameters()? That's getting called only twice.

So I think removing that from loadGeneralSettingParameters() and putting it in SMF classic way is not only convenient but also solves the hook problem all together.

@jdarwood007

Regarding $context['tabs'], createMenu happens BEFORE the settings tab in our case. Example:

File: ManageMembers.php
Function: ViewMembers()
Line: 91

$context['tabs'] is being define and that is out of reach.

If I'm missing something here, please tell me before I start making changes :)

**Comment by jdarwood007** [comment]
In your first example it seems like we just need to move the loadGeneralSettingParameters call to after our hook.  I think we could do similar for the second one and move the hook to before call_helper.

**Comment by asmith20002** [comment]
Yes that was my initial thought. But loadGeneralSettingParameters() is also loading languages and those $txt are being used in the $context tabs. So it won't work if we move it after the tabs.
