### ISSUE TITLE
URL with array parameter in parse BBC bug

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#3366]
Parse bbc breaks when there are array in URL parameters:

example.com/index.php?var[]=value

**Comment by MissAllSunday** [comment]
Its a known issue I believe, can't find the relevant report though.

**Comment by illori** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/1187

**Comment by Sesquipedalian** [comment]
In theory, this could be addressed by adding `'quoted' => 'optional'` to the unparsed_equals version of the url BBC. Then the user could enter `[url="http://example.com/index.php?var[]=value"]evil link[/url]`.

Unfortunately, just adding that didn't work when I tried it. Various bits of the current code assume that no quotes will be present. To make it work will probably require some tinkering with both the BBC's validation function and with some of the code related to autolinking plain text URLs.

**Comment by MissAllSunday** [comment]
This would be addressed by messing around with the url regex, unfortunately, thats regex is already quite complex as it is.   It not only happens with [ ]  it also happens with other chars valid for RFC 3986

**Comment by Sesquipedalian** [comment]
What other characters, @MissAllSunday?

**Comment by MissAllSunday** [comment]
There was an bug report about this on mantis but I can't seem to find it :(

**Comment by MissAllSunday** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/1187

**Comment by Sesquipedalian** [comment]
Hmm... Since SMF 2.1 requires PHP 5.3 or higher, perhaps some judicious use of [`filter_var('http://example.com', FILTER_VALIDATE_URL)`](http://php.net/manual/en/function.filter-var.php) would help us solve the problem and make the code more legible.

**Comment by MissAllSunday** [comment]
That might be worth give it a try,  yes

**Comment by Sesquipedalian** [comment]
I've nearly completed a fix for this now. Just doing a bit more testing.

**Comment by MissAllSunday** [comment]
Awesome, thanks!
