### ISSUE TITLE
you must enter a value between 1 and 525600

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3367]
enter a valid username in the log in popup, enter an incorrect password and check the box to always stay logged in. try to log in. log in will fail. try to log in with the correct password and the always stay logged in box checked. get error message about invalid value.
![](http://i.imgur.com/zs7f9Gw.png)

**Comment by Oldiesmann** [comment]
I'm not sure why there's an upper limit on that field, but this should be pretty easy to fix.
