### ISSUE TITLE
Avatar with a link HTTPS

### ISSUE THREAD

**Issue by FranckAsahi** [SimpleMachines/SMF#3375]
Hello

When an avatar information with a 'https' link, it is not registered.
In the sources, eg "Subs.php" line 3242, the link is compared with "http://" and not "https://". Same for "Profile-Modify.php" line 2391.

This may be a desired behavior ?

I informed the avatar from a site connected with SMF, and the visible link in the pictures is composed of the link to the SMF avatar directory and the avatar link. Example: http://127.0.0.1/forum/smf/avatars/https://avatarlink.png

Have a good day

**Comment by live627** [comment]
>  "Subs.php" line 3242

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs.php#L3242

Something doesn't add up.

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Profile-Modify.php#L2391

You using 2.0.x?

**Comment by FranckAsahi** [comment]
Thank you for your reply.
Yes, I use version 2.0.11
So I should just wait for the release of the 2.1.x
Sorry
