### ISSUE TITLE
issue with minify.js

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#3376]
Something pretty strange is happening, for some reason, minify.js is replacing two string vars with 0 on them: '0' with 'smf_tooltip'

``` js
this.oCookie.set(this.opt.oCookieOptions.sCookieName,this.bCollapsed?'1':'smf_tooltip');if(!bInit&&'oThemeOptions' in this.opt&&this.opt.oThemeOptions.bUseThemeSettings)
smf_setThemeOption(this.opt.oThemeOptions.sOptionName,this.bCollapsed?'1':'smf_tooltip','sThemeId' in this.opt.oThemeOptions?this.opt.oThemeOptions.sThemeId:null,smf_session_id,smf_session_var,'sAdditionalVars' in this.opt.oThemeOptions?this.opt.oThemeOptions.sAdditionalVars:null) 
```

This of course causes smf_setThemeOption to save the wrong values, making impossible to "uncollapse" previously collapsed categories.  Will investigate this further

**Comment by MissAllSunday** [comment]
Added a fix for this, well not really a fix since I have no idea why minify changed those '0' vars, my wild guess is a combination of variable scope plus minify trying to be smart.

Fix was simple, just forcing an integer type on both cases, seems to have fixed the issue.

**Comment by Arantor** [comment]
This is still occurring on current beta 3 - 4f013ad47777c319ca349969ea3fa59ed5c1e658 - and hits both the categories and info_center being uncollapsible.

**Comment by MissAllSunday** [comment]
Yes it's still happening  as the PR with the fix hasn't been merged yet.

Jessica González, missallsunday.com
