### ISSUE TITLE
update the feature liste of 2.1?

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#3378]
I would like to see some more feature or minor improvments in this list: http://wiki.simplemachines.org/smf/SMF2.1:Features#General
- Fulltext Search Index in PostgreSQL
- support for Ignore / insert on duplicate key update syntax in PostgreSQL (require pg 9.5+) -- performance tweek
- support for unlogged table (require pg 9.1+) -- performance tweek
- php 7.0 support (or did this already work in 2.0 ?)
- new syntax for ip range with ipv6 support (for ban trigger and spider ip)
- massiv optimization for PostgreSQL

Maybe not all points are needed,
but some are worthwhile.

**Comment by XinYenFon** [comment]
I this its better this discussed with doc team on forums :)
