### ISSUE TITLE
Violation of SMF Coding Standards

### ISSUE THREAD

**Issue by matthew-kerle** [SimpleMachines/SMF#3379]
The loop in Subs-List.php for generating the column headers for $list_context does not wrap the loop with brackets, as per the SMF coding standards. 

This has caused issues for me when wanting to modify something inside the loop with a modification. It leaves me the choice of doing something nearly impossible in an inline condition, or hacking the loop to have brackets and include my code above the array initializer.

Not following SMF's coding standards SMF itself causes consistency problems for mod authors because they are unable to rely on the guidelines to be consistently applied throughout the codebase, causing issues such as the one I am facing. I'd request the brackets be added to this loop (specifically), and any others missing the brackets to prevent issues such as this and to comply with your own guidelines.

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-List.php#L92

**Comment by live627** [comment]
Are you sure the guidelines say that?

Also, that is one of the few things left unchanged since 2.0.

**Comment by matthew-kerle** [comment]
It definitely was. Are you saying this won't be changed? It'd take 10 seconds to throw a fix out for this and merge it. I would if I had a local SMF 2.1 repo open.

**Comment by jdarwood007** [comment]
Where do we say that?  I would call that valid SMF code.

**Comment by matthew-kerle** [comment]
@jdarwood007 you're right...I just looked. I wonder if this has changed recently. I know the general SMF consensus on brackets is for loops you always put them. Especially for code that can have manual modification changes, it makes modding possibilities larger, since loops are a very common way to hook into something.

But yeah, if this isn't part of the guidelines, I'll definitely close it.
