### ISSUE TITLE
$user_info['id'] === $int;

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#338]
I found out today after about 3 hours of debugging and randomly placing var_dump() functions that $user_info['id'] and $context['user']['id'] are both strings. This is evil, and I'm mad about it. :P 

``` PHP
var_dump(
    array($user_info['id'], $context['user']['id'])
);

/* Output:
 * array(2) {
 *     [0]=> string(1) "1"
 *     [1]=> string(1) "1"
 * }
 */
```

**Comment by matthew-kerle** [comment]
Well you do know that you're always able to submit a Pull Request and fix it yourself :)

**Comment by joshuaadickerson** [comment]
`$id_member = $check && ($user_settings['is_activated'] == 1 || $user_settings['is_activated'] == 11) ? $user_settings['id_member'] : 0;`

to

`$id_member = $check && ($user_settings['is_activated'] == 1 || $user_settings['is_activated'] == 11) ? (int) $user_settings['id_member'] : 0;`

Though, replacing that seems like a waste. It should be a simple if instead.

**Comment by ghost** [comment]
Yeah, that got it, @joshuaadickerson. Thanks. :)

**Comment by ghost** [comment]
![](http://i2.kym-cdn.com/entries/icons/original/000/005/365/awwyea.jpg)
