### ISSUE TITLE
BLOB/TEXT column 'txt' can't have a default value

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#3385]
On windows mysql 5.7.9 php 5.6.16  while trying to perform an upgrade.

Setting mysql mode to MYSQL40 doens't seem to work.  Seems to be caused by this bit:

``` php
foreach ($columns as $column)
                        {
                            $updates_blob .= '
                                CHANGE COLUMN `' . $column['Field'] . '` `' . $column['Field'] . '` ' . strtr($column['Type'], array('text' => 'blob', 'char' => 'binary')) . ($column['Null'] === 'YES' ? ' NULL' : ' NOT NULL') . (strpos($column['Type'], 'char') === false ? '' : ' default \'' . $column['Default'] . '\'') . ',';
                            $updates_text .= '
                                CHANGE COLUMN `' . $column['Field'] . '` `' . $column['Field'] . '` ' . $column['Type'] . ' CHARACTER SET ' . $charsets[$upcontext['charset_detected']] . ($column['Null'] === 'YES' ? '' : ' NOT NULL') . (strpos($column['Type'], 'char') === false ? '' : ' default \'' . $column['Default'] . '\'') . ',';
                        }
```

**Comment by MissAllSunday** [comment]
Executting SET @@global.sql_mode='MYSQL40' did the trick,  I manually changed my .ini file and re-started mysql dunno why it didn't pick it up.

Regardless, I still think this should be somehow patched, been investigating and seems this is pretty old issue and the mysql devs aren't interested on fixing it .___.

**Comment by albertlast** [comment]
You can change the field to null able and than you got as default value null

**Comment by albertlast** [comment]
So what is about this topic?
To set the sql_mode to an older version is from my point of view a bad idea,
instead i like to see that the field get null able.

**Comment by MissAllSunday** [comment]
If this is soemthing that happens on mysql 5.7.9  then it needs to be fixed.

The sql_mode was just something I did to temp fix but this shouldn't happen.

**Comment by albertlast** [comment]
http://dev.mysql.com/doc/refman/5.7/en/blob.html
"BLOB and TEXT columns cannot have DEFAULT values."

It's no Bug on mysql side.

---

Von: Jessica González notifications@github.com
Gesendet: 13.06.2016 2:42 AM
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] BLOB/TEXT column 'txt' can't have a default value (#3385)

If this is soemthing that happens on mysql 5.7.9  then it needs to be fixed.

The sql_mode was just something I did to temp fix but this shouldn't happen.

---

**Comment by MissAllSunday** [comment]
@Oldiesmann do you have any idea about this?

Has been recently reported on the forum: http://www.simplemachines.org/community/index.php?topic=547044.msg3880915#msg3880915

**Comment by MissAllSunday** [comment]
@Oldiesmann do you have any idea about this?

**Comment by albertlast** [comment]
by the working on the db sync pr,
i noticed that text/blob fields doesn't have a default value in the install_2-1_mysql.sql.
So my recommandation is, to drop the code in the upgrade.php how is trying to set this.

**Comment by Oldiesmann** [comment]
I would also recommend dropping the code. It's easier than trying to work around it.

**Comment by frandominguezl** [comment]
Please, close this https://github.com/SimpleMachines/SMF2.1/pull/3893#issuecomment-275935653 @colinschoen @Oldiesmann @live627

**Comment by frandominguezl** [comment]
@illori llori please close this

**Comment by frandominguezl** [comment]
@colinschoen
