### ISSUE TITLE
Upgrading from 2.0.11 -> 2.1b3 No tickboxes for upgrade options

### ISSUE THREAD

**Issue by PhuriousGeorge** [SimpleMachines/SMF#3386]
Using Chrome, Edge or Opera, exactly what the title says. I'm not getting the tickboxes when trying to upgrade from 2.0.11, which might be useful since my database upgrades are also hanging.

I do see the tickboxes while using Firefox.

**Comment by MissAllSunday** [comment]
Seems related to this one https://github.com/SimpleMachines/SMF2.1/issues/3384
