### ISSUE TITLE
Inline JavaScript to addInlineJavaScript

### ISSUE THREAD

**Issue by matthew-kerle** [SimpleMachines/SMF#339]
There are a lot of usages remaining in SMF 2.1 that use $context['html_headers'] .= ''; to hack in JavaScript, which isn't bad, but now there is the addInlineJavaScript function that handles adding JavaScript both to the head and html elements.

It's not going to cause any problems leaving instances that use the old method, but as we're going through the code, it can't hurt to clean it up.

**Comment by emanuele45** [comment]
PRs are always welcome! :stuck_out_tongue:

**Comment by colinschoen** [comment]
Do you have a couple or group of files in mind that have this issue? If so I will clean them out.

**Comment by matthew-kerle** [comment]
Nope! I was just going through and saw instances...really somewhat too general of an issue, but they should probably eventually follow suit.

**Comment by colinschoen** [comment]
Sounds good. I will keep my eyes peeled.

**Comment by PortaMx** [comment]
This seem like it's not consequently implemented .. 
I see inline Javascript in the code .. like the smc_toogle for the header ;-) and other...
Also it was a good option to make a function like "addInlineJavaScript" for CSS .. addInlineCSS.
Currently I use the hook "pre_css_output"
By the way .. why not use "integrate_pre_css_output" ? that would consistent with other hook names ;-)

**Comment by matthew-kerle** [comment]
Well of course...JavaScript in template files aren't going to use this.

**Comment by ghost** [comment]
There are still a few instances of $context['html_headers'] to be looked at.

Sources\Load.php
Line: 1635
Line: 1636
Sources\Subs-Editor.php
Line: 1780
Themes\default\index.template.php
Line: 166

**Comment by matthew-kerle** [comment]
There shouldn't be any instances of $context['html_headers'] in templates no matter what, but that case is probably echo $context['html_headers']; where it's actually outputted.

**Comment by Oldiesmann** [comment]
Of those four, the only one we may need to do something about is the one in Subs-Editor.php:

```
    if (!empty($bbcodes_styles))
        $context['html_headers'] .= '
    <style type="text/css">' . $bbcodes_styles . '
    </style>';
```

The others are fine as they are (the lines in Load.php define it to an empty string if it isn't already set, and the one in index.template.php is where its contents are actually output).

**Comment by matthew-kerle** [comment]
Agreed. That one should probably be converted, as you suspected.

**Comment by Oldiesmann** [comment]
Looking at it again, I'm not sure there's anything we _can_ do about it. There doesn't seem to be any function for handling inline CSS.

**Comment by PortaMx** [comment]
I have created my own InlineCSS function like this ;-)
addInlineCSS('
    #preview_section{margin-top:'. abs($tbpad) .'px;}
    #pmx_toppad{margin-top:'. $tbpad .'px;'. (!empty($context['pmx']['settings']['forumscroll']) ? 'overflow-x:auto;' : '') .'}
    .pmx_maintable{'. (!empty($context['pmx']['settings']['forumscroll']) ? 'table-layout:fixed;' : '') .'}');

The CSS is putting out with the hook integrate_pre_css_output.

The header area looks now VERY clean ;-)

**Comment by matthew-kerle** [comment]
It'd make sense to me to have such a function. It'd allow us more extensibility options for the future. Such as CSS parsing if we ever wanted to go that route.

Although I don't know if now is the time to add it or not. It does have benefits, but we'd also have to convert all of the current instances to use the function.

**Comment by Oldiesmann** [comment]
I'm not sure it's worth the trouble to add it right now either. Maybe for 2.2/3.0?

**Comment by matthew-kerle** [comment]
I think if we ever decide to use some sort of CSS parsing then we'd want to obviously. Don't see much benefit until then.

**Comment by PortaMx** [comment]
I think it's no big problem to add a function I use.
Also all CSS and Javascript is compressed on the fly .. that save a many bytes on each request.
Try a look on our Testsite (feline.networks.com) to see all the css/javascript on the header and footer ;-)

**Comment by Arantor** [comment]
I know I added some CSS with html_headers this week (unaware of this report), but in my defence that was because it was a CSS class that appears on a minority of pages under specific circumstances, and there's no addInlineCSS function ;)

But my change (the anti-spam one) seems to be the only use of html_headers now, so I'm tempted to think this issue can be put to bed now?

**Comment by matthew-kerle** [comment]
As far as I'm concerned, definitely. Eventually it'd be awesome to move to a CSS pre-processing such as Sass and just allow things to be hooked in.

**Comment by Arantor** [comment]
OK, so I'm going to close this because unless we do stuff 'as we see it' for 2.1, it's far too far along to really do this now. For 3.0 however we will certainly be looking at preprocessing options for both CSS and JS and this suddenly takes on a new light.
