### ISSUE TITLE
Better qoute looks for jquery.sceditor.smf.js

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3390]
I modify this file, so the qoute looks better and more like as in posts.

![better_qoute_design](https://cloud.githubusercontent.com/assets/2270223/14432692/8b2d0342-000b-11e6-92ed-55074201ad31.png)

Here the modificated file ...

[better_jquery.sceditor.smf.zip](https://github.com/SimpleMachines/SMF2.1/files/213322/better_jquery.sceditor.smf.zip)

**Comment by MissAllSunday** [comment]
Can you please list all the changes you made?  preferable in a correctly formatted PR, it will be far more easy for us to accept your changes that way.

We also need any code included in SMF to be signed off by the author so we know the author fully agrees with our [Developer's Certificate of Origin](https://github.com/SimpleMachines/SMF2.1/blob/master/DCO.txt)

**Comment by PortaMx** [comment]
I have create **my own Repository** so I can make fixes, changes and updates as I mean and how I think.

Look here: https://github.com/PortaMx/SMF-2.1-PMX

Next days we create a new Forum with this release, so you can look what we have done.
Also you can use our version for a test ;-)

If you will see, what we have changed, use a merge tool (like WinMerge) to see the changes ..

**Comment by MissAllSunday** [comment]
OK, good luck with that.
