### ISSUE TITLE
View vs issue likes

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#3393]
If a user has permission to like something, but not to view, liking things will fail with the generic $txt['likes_error'] message, and it's not obvious that both permissions have to be given.

Also, can guests like things now? If not, the group should be removed from the Configuration > Features > Likes page... (Think this is the right area, am at work)

**Comment by Oldiesmann** [comment]
I'm not familiar with the logic of the likes process so I'm not sure where to look as far as making it say you can't view likes rather than just you can't like the content.

The guest thing is indeed a bug.

**Comment by Oldiesmann** [comment]
Found the issue with guests showing up in that list. The only way to prevent a group from showing up in the inline permissions thing is to set $context['excluded_permissions']. However, that applies to all permissions on the page and is completely independent of the list of illegal guest permissions. I'll submit a fix for that shortly.

**Comment by XinYenFon** [comment]
On latest build, I can't see any issue. Guests can see likes but can't like. This is no longer a valid issue.

**Comment by Arantor** [comment]
There are two issues in my report, guests and likes is only one of them.

**Comment by XinYenFon** [comment]
My bad sorry, i forgot to test the first part actually. I guess you are getting "There was an error with your request. " as well. On php5.x/7.0/7.1

**Comment by frandominguezl** [comment]
I've been thinking about this, and I think it's unnecessary to have these 2 types of Likes permission. The best solution for me is; When we click "Enable likes" everyone can see them, but we'll have to set up the permission for which membergroups are allowed to like topics.
We could also add a checkbox like "Allow Guests to see likes?"

What do you think?

**Comment by Arantor** [comment]
Personally, I'd just have enable likes make them visible to everyone, and I wouldn't even have an option for guests to see them, I'd just have guests seeing them.

I'm a huge fan of not having a million options. More options = less simple.

(And yes, it is unnecessary to have two likes permissions.)

**Comment by frandominguezl** [comment]
So, any thoughts on this? ;) @colinschoen @Oldiesmann

**Comment by Sesquipedalian** [comment]
I agree. If likes are enabled, they should just be visible to everyone. There's no need for a permission to control who can see likes.

**Comment by illori** [comment]
lets stop discussing it and make the change that everyone can view the likes by default if enabled. if someone wants permissions they can request a mod.

**Comment by XinYenFon** [comment]
@Sesquipedalian I disagree, permission should stay in there for anyone to use. One thing can be changed is default "all checked" on who can see.

@illori its not really feature improvement yet its there so why remove ?

tbh this is trivial change and waste of time, best to keep it as is and focus on more important issues and if anyone in community asks to change this you can do it in RC ? or whatever.

**Comment by Arantor** [comment]
Because you actually have weird and inconsistent and appearing-buggy behaviour if you don't follow this.

You have to give someone both view and give likes in order for them to like something. This is not obvious behaviour and hard to debug because the error you get back is way too generic.

Of course, let's shove more options in there, while we're at it can we please rename the software to Complex Machine Forums, because that's what happens when you add more options.

**Comment by sbulen** [comment]
I agree with Arantor.   

The problem is that there is a dependency between 'like' and 'view' that is just not obvious in the UI as it stands.  Ideally, you wouldn't even be able to select 'like' without 'view' being selected.   But the two lists are separate, making logical associations difficult to see.  

Thinking out loud, but here's a proposal:
  - Change the text on the admin panel "Membergroups allowed to like posts" to include a note indicating view is required as well.  Something like "Membergroups allowed to like posts (note: view permissions must be enabled as well)"
  - Upon save, for groups have have like posts selected, set the view permission also
  - Bonus points: a .js that will set the 'view' checkbox when the corresponding 'like' checkbox is selected, so it is even more obvious to the user.  

An alternative proposal:
  -  Redefine 'view' to mean 'view only' and enforce it as such...   'like' will assume like & view...

**Comment by frandominguezl** [comment]
I was trying to look for a solution for this. My choice was to remove all the "likes_view" permissions related stuff and make everyone able to see likes if likes are enabled. I'd include a note (maybe in one of those interrogation mark icons?) to warn that everyone will be able to see likes if likes are enabled.

So far, I didn't manage to make guests able to see likes after removing all the likes_view permissions, but I think this is the best solution.

**Comment by illori** [comment]
i think if a member group is able to like they can view the likes, removing the view permission completely would work out well.

**Comment by frandominguezl** [comment]
I've already tried that, with no luck. Maybe I'm missing something else here, so if anyone wants to give it a go, feel free :)

**Comment by sbulen** [comment]
I like that approach as well.  It would work.  

It sure feels to me that allowing guests to view likes should be an option, not assumed, though...  I guess I agree with Antes' comment on that point.

**Comment by sbulen** [comment]
Speaking of likes.php...  Should the "BookOfUnknown()" be removed?  Not sure how that got in there...

**Comment by Arantor** [comment]
Removing the Easter eggs earns you a special round of unpleasantness. I tried it once upon a time.

**Comment by sbulen** [comment]
PR #4289 submitted.
