### ISSUE TITLE
Navigation links on small devices

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#3395]
What's the reason for navigation links to have 50% (and anchor inside them have 65%) width?

Generally it is 100% on small devices on most responsive sites. The links being half with kinda makes them ugly.

**Comment by XinYenFon** [comment]
Going 100% is not a solution, which looks even worse IMO. We can work on menu in later stages currently its working (with help from SuperFish).

![100perc](https://cloud.githubusercontent.com/assets/1669995/14681672/ccbe5646-072a-11e6-9d6d-0ba7337c3cb3.png)

**Comment by asmith20002** [comment]
I think your provided image looks much better.

However in that size, we gotta have one menu button to tap similar to bootstrap. (and hide that list) The current state is causing unnecessary height on top.

**Comment by XinYenFon** [comment]
I'm seriously busy currently. But I'll improve mobile menu / action handling. Go in to topic you'll see User Action & Moderation Action. I'll use that as base and improve its UX for menu & actions on mobile.

**Comment by asmith20002** [comment]
Could you please link me there? I don't know what topic you're talking about.

**Comment by Oldiesmann** [comment]
He's talking about the user action and moderation buttons/pop up menus within topics in SMF 2.1.

![screenshot_2016-04-21-12-50-17](https://cloud.githubusercontent.com/assets/89023/14717798/1b92b2b2-07c1-11e6-862d-9682d46e3716.png)
![screenshot_2016-04-21-12-50-10](https://cloud.githubusercontent.com/assets/89023/14717794/1627ab20-07c1-11e6-9995-0210fe92e5b5.png)

**Comment by asmith20002** [comment]
Ah now it makes sense. That's nice to have same thing for navigation links as well. :)

**Comment by XinYenFon** [comment]
You mean like this :P

![screenshot-localhost 2016-04-22 21-05-42](https://cloud.githubusercontent.com/assets/1669995/14750544/0fcde740-08ce-11e6-86f2-9bdccbbfc675.png)
