### ISSUE TITLE
Convert to UTF-8 should be before serialise / JSON fix in upgrader

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#3396]
SMF will during the UTF-8 conversion go through and fix all the serialised columns since serialised arrays that contain strings will need to have the string lengths checked.

Conversion to JSON should be done first so the conversion to UTF-8 doesn't have to then go through and fix serialised columns.

**Comment by Oldiesmann** [comment]
JSON conversion is done after UTF-8 conversion because of how json_encode() handles Unicode characters in non-UTF-8 charsets (it converts them to "\u<character_code>"). If we do the JSON conversion first, then we have to go back and change all the \u stuff back to regular characters.

**Comment by Arantor** [comment]
Doesn't json_decode naturally handle the \u cases for you?

**Comment by Oldiesmann** [comment]
Yes it will, but then we go from having UTF-8 conversion fix serialized strings to having to decode things before converting them to UTF-8. It seems easier to fix the serialized strings and then encode them.

**Comment by Arantor** [comment]
Hmmm, maybe it might be better that way rather than deserialise, transcode to UTF-8, json_encode, save to DB. At this point, you'd have things in \u format, sure, but the mass conversion wouldn't touch those characters as they're 7-bit safe, and json_decode would fix that when you got the values back from the DB.

The only change would then be the soft conversion to UTF when re-encoding since json_encode won't touch ISO-anything.

There's arguments both ways, just seemed like some processing could be saved without making more changes to the DB than necessary (rewriting serialised columns once rather than twice)

**Comment by sbulen** [comment]
I'd suggest closing this out.

Good arguments both ways, but the current config has been tested hundreds if not thousands of times.  I'd rather not change what's working at this late stage.

**Comment by Arantor** [comment]
The config was broken at the point I reported this.
