### ISSUE TITLE
SMF API Rest create post bug

### ISSUE THREAD

**Issue by ewiggin** [SimpleMachines/SMF#3397]
On SmfRestClient.php have a big bug on create post:

```
protected function create_post()
    {
        try {
            $this->loadSSI();
        } catch (Exception $e) {
            throw new Exception($e->getMessage());
        }
        global $sourcedir;
        require_once($sourcedir . "/Subs-Post.php");

        $this->msgOptions = unserialize($this->msgOptions);
        $this->topicOptions = unserialize($this->topicOptions);
        $this->posterOptions = unserialize($this->posterOptions);

        if (!isset($topicOptions['board']) || !isset($msgOptions['subject']) || !isset($msgOptions['body'])) {
           $this->data = 'false';
        } else {
            $this->data = createPost($this->msgOptions, $this->topicOptions, $this->posterOptions);
        }
    }
```

You use $topicOptions, $msgOptions without $this reference. Always is "false". 

Please, change this to:

`if (!isset($this->topicOptions['board']) || !isset($this->msgOptions['subject']) || !isset($this->msgOptions['body'])) {
           $this->data = 'false';`

**Comment by MissAllSunday** [comment]
Hello, SmfRestClient.php is not included in SMF 2.1, its an external script created by a third party. Please refer your reports to the API author at: http://www.simplemachines.org/community/index.php?topic=458832.msg3205236#msg3205236
