### ISSUE TITLE
SMF 2.0.11 Sent mail doesn't log

### ISSUE THREAD

**Issue by Zack-Dronaman** [SimpleMachines/SMF#3411]
I've noticed that once I've sent a message, I can't find them inside the Sent Folder. 

This is shown in the attached gif.
![lsjngaiwme](https://cloud.githubusercontent.com/assets/10054219/14837044/b5b88278-0bda-11e6-873a-185f9878fab4.gif)

**Comment by XinYenFon** [comment]
This repository for development of SMF 2.1 please report bugs related to SMF 2.0 here: http://www.simplemachines.org/community/index.php?board=137.0

**Comment by illori** [comment]
this is not a bug, you need to check that box at the bottom of that message that says save a copy in my outbox. in SMF 2.1 this is set by default and you cant disable it all messages are saved by default.
