### ISSUE TITLE
Fatal error from Minify class

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3421]
Just upgraded one of my dev instances.

Fatal error: Class 'MatthiasMullie\Minify\Exceptions\IOException' not found in /smf/Sources/minify/src/Minify.php on line 400

The code it is failing on is this:

```
    protected function openFileForWriting($path)
    {
        if (($handler = @fopen($path, 'w')) === false) {
            throw new IOException('The file "'.$path.'" could not be opened for writing. Check if PHP has enough permissions.');
        }

        return $handler;
    }
```

Seems there is a file that it can't write to and it is just through a fatal error.  This shouldn't happen.  SMF should for one try to make the directory/file writable that it needs.  Secondly, SMF should present with a cleaner nicer message/error page and fall back to not using minify.

**Comment by jdarwood007** [comment]
The file it was failing to write was these and they didn't exist:
/smf/Themes/default/css/minified.css
/smf/Themes/default/scripts/minified.js

**Comment by MissAllSunday** [comment]
That file isn't a part of SMF, not really fond of modifiying libraries as that causes a whole new set of issues if/when we update those libraries.

Best we can do is do the write check outselves before calling minify and just don't do it if it fails.
