### ISSUE TITLE
inet_ntop(): Invalid in_addr value

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3423]
Warning: inet_ntop(): Invalid in_addr value in /smf/Sources/Subs.php on line 4862

This seems to be caused by poster_ip being NULL

@albertlast as you have been working on this, I will see what you suggest is the best fix.  I think just adding a null check would be fine, but I wonder about other invalid formats going in there.  Perhaps we could do a string length check.  Should be 4 for IPv4 and 16 for a IPv6 I believe.

If I enter "12345678" into the poster_ip column as well, it creates the same sort of error.  I know its not valid blob, but it still kicks out an error.  Not sure how to solve that yet.

**Comment by albertlast** [comment]
i notice the first null handling 10min ago.

when you manual insert data is that not problem of smf?!

**Comment by jdarwood007** [comment]
It could be a problem with SMF.  Could be anything.  Just wasn't sure if we could handle it cleanly to prevent errors.

On a related note, upon upgrading I noticed all my poster_ip are NULL.  Did we work out the upgrader fixing the IPs?

**Comment by albertlast** [comment]
The error are prevent by the way that the inserting are checked if ip address valid or not.
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Db-mysqli.php#L256

in the mysql upgrade are some fields (not the same amount as by pg) which are convert,
poster_ip,member_ip and member_ip2
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade_2-1_mysql.sql#L1998
when this field get null value then is mostly there a bug,
which need to fix.

when you able to debug this,
would be this helpfull.
maybe the drop of the help table should comment out for debugging.
https://github.com/SimpleMachines/SMF2.1/blob/f913d951553b72515a49f5e68c10a883982bf30f/other/upgrade.php#L5818

**Comment by albertlast** [comment]
should be fixed now

**Comment by jdarwood007** [comment]
FYI, If you add Fixes #3423 into your commit or PR message, it will automatically close the issue.

https://help.github.com/articles/closing-issues-via-commit-messages/
