### ISSUE TITLE
Input overflow

### ISSUE THREAD

**Issue by sicommnend** [SimpleMachines/SMF#3426]
Don't know if this has been brought up. I couldn't find any mention of it so forth.

In mobile and sometimes even on my desktop I am having the problem of input boxes overflowing their boundaries. This results in either a scroll bar below them or part of the input box hidden.

I was wondering if it was feasible just to put a max-width on all inputs in the CSS to prevent overflow.

Like`input, button, select {
    font-size: 0.9em;
}`

Turns into
`input, button, select {
    font-size: 0.9em;
    max-width: 99%;
}`

**Comment by XinYenFon** [comment]
can you also link page & write phone specs (or just name).

**Comment by sicommnend** [comment]
http://dev.sicomm.us/2.1/index.php?action=search

Desktop
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.86 Safari/537.36

**Comment by sicommnend** [comment]
Give the link some time, I just started uploading the latest source to it a few minutes ago.

**Comment by XinYenFon** [comment]
I can't reproduce this on my localhost (Chrome 50)

**Comment by sicommnend** [comment]
Sorry broke the test site, just restored.
Here is a post with the image attached.

**Comment by sicommnend** [comment]
http://dev.sicomm.us/2.1/index.php?topic=4.0

**Comment by XinYenFon** [comment]
Please attach images here.

**Comment by sicommnend** [comment]
![screenshot from 2016-05-01 20 29 55](https://cloud.githubusercontent.com/assets/1163385/14973287/3337b472-10a3-11e6-97a0-361745aaeb41.png)
Sorry, hardly use this form, didn't know I could upload images directly here.

**Comment by XinYenFon** [comment]
I visited your site with Chrome/50 sorry can't reproduce. I also visited different sites with SMF 2.1 beta3, can't reproduce in any of them.

**Comment by jdarwood007** [comment]
Do you have a zoom or a user.css file?  Try it in incognito mode to make sure an extension isn't causing that as well.

**Comment by sicommnend** [comment]
Same in incognito mode, no user defined style sheets, I figure out what CSS element is causing the issue.
`font: 83.33%/150% "Segoe UI", "Helvetica Neue", "Nimbus Sans L", Arial, "Liberation Sans", sans-serif;`
This is part of index.css. If I disable this CSS the problem goes away.

I also ran a search for other SMF 2.1 test forums on the net and the same happens on other sites. Maybe it isn't so much my browser but my OS. I haven't looked into the fonts in the CSS, but I am guessing here I probably don't have one of them.

Here is a screenshot from another SMF test site.
![screenshot from 2016-05-03 20 45 43](https://cloud.githubusercontent.com/assets/1163385/15004118/4a28b49c-1170-11e6-880b-ecc94da25124.png)

**Comment by sicommnend** [comment]
Figured out what font it is
`"Nimbus Sans L"`
Remove this font and the form displays correctly.

**Comment by XinYenFon** [comment]
Anything left here? It seems very specific issue with user.

**Comment by illori** [comment]
this is not a user specific issue. i think this is an OS specific issue.
i think this the other fonts may not be found/loaded before that one it becomes the default the user sees and it is not the same size as other fonts. maybe another font should be selected that is more similar in size? maybe coreisp can shed some light on this as i think he uses linux.

**Comment by XinYenFon** [comment]
Well you should mention him here first :P @CoreISP
