### ISSUE TITLE
Post count not recounting after upgrade

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#343]
- Even i recount stats forum not recounting posts.

**Comment by XinYenFon** [comment]
I keep using this place as my issue report place :package: 

My error log (on FTP)

[22-Jul-2013 15:25:55 Africa/Abidjan] PHP Notice:  Undefined index:  in _**/public_html/Sources/Subs.php on line 3446
[22-Jul-2013 15:25:55 Africa/Abidjan] PHP Notice:  Undefined index: mime_type in *_*/public_html/Sources/Avatar.php on line 118

My error log (of SMF)

File: ***/public_html/Sources/Subs.php
Line: 1960 
8: Uninitialized string offset: 971
http://www.mmobrowser.com/f15/940

**Comment by jdarwood007** [comment]
I am not able to reproduce this at this time.  Please update your Alpha build and let me know if you can still reproduce this issue.

**Comment by XinYenFon** [comment]
I updated my alpha build after Skype changes done. Still same for me.

that was 2.0.4 > 2.1 Alpha (topic count was fine) > 2.1 Alpha (topic & post count broken). Also I don't see any problem on new install too.

**Comment by jdarwood007** [comment]
Are your boards set to not count posts?

**Comment by XinYenFon** [comment]
No they set to count. I have no problem with user post counts.

**Comment by jdarwood007** [comment]
Do you receive any errors or other useful information?  Have you tried toggling the option?  Are there any mods installed?

Is this a public site or a test site?  If you are not getting information, getting access to that and purposely breaking things would help us see what may be going on.

**Comment by XinYenFon** [comment]
Subs.php

$context['common_stats']['boardindex_total_posts'] = sprintf($txt['boardindex_total_posts'], $context['common_stats']['total_posts'], $context['common_stats']['total_topics'], $context['common_stats']['total_members']);

When i try to output any of this directly I can get correct result.

**Comment by XinYenFon** [comment]
Fixed with #593
