### ISSUE TITLE
IP data loss upon upgrading

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3430]
There is data loss happening during the upgrade process as shown here:

> mysql> SELECT a.id_msg, a.poster_ip AS smf21_ip, b.poster_ip AS smf20_ip FROM smf_messages AS a INNER JOIN backup_smf_messages AS b ON (a.id_msg = b.id_msg);

| id_msg | smf21_ip | smf20_ip |
| --- | --- | --- |
| 1 | NULL | 127.0.0.1 |
| 2 | NULL | 54.54.54.54 |
| 3 | NULL | 45.45.45.45 |
| 4 | NULL | 45.45.54.54 |

> 4 rows in set (0.00 sec)

As well reviewing the MySQLConvertOldIp function.  It doesn't look safe for big boards.  Pulling a SELECT from a table with 4 million rows will take some time, not to mention updating all of those.  This function needs to be updated to be safe for large forums.

As well I notice we are dumping data on a lot of the log columns.  Do we really need to do that or can it be saved?

**Comment by albertlast** [comment]
the select is a distinct on ip field,
so the result of this are less then 4mio rows,
i would think around 400k rows maybe...

the mysqlconvertoldip function based on your idea (or my interpretation of your idea): https://github.com/SimpleMachines/SMF2.1/pull/3373#issuecomment-204755621
from my side i didn't understand why is here dataloss,
only one think i could imagine that the your are affected by problem 2 https://github.com/SimpleMachines/SMF2.1/issues/3427

**Comment by jdarwood007** [comment]
Ok the data loss was because I was on another branch and was pulling updates wrong.

The issue still stands right now with unsafe upgrades on larger data sets.  We need browser timeout safety checks.  SMF upgrader has this built in with the nextStep function.
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade_2-1_mysql.sql#L247

**Comment by albertlast** [comment]
For me it's looks more a theoritcal issue,
so i would need a messages table with a relastic ratio of amount of entry and different ips.

A 4 mio rows tables couldn't hav 4 mio different ips...

**Comment by albertlast** [comment]
so jdarwood provide me with a dump with 4mio messages from 4mio different ip's
what is from my pov is far away from relastic ratio,
but never the less i play a litte bit with the data.

the comand for creation of new col (poster_ip with varbinary(16)) takes 920 sec.
the rename of the old poster_ip to poster_ip_old got time out.

the ip_tables engine = memory was only able to hold 61k rows
this mean i need to change the db engine

i do some test:
innodb(xtradb) 256sec
myisam 170 sec
aria192 sec
 to fill (with insert into smf_ip_table select distinct poster_ip_old, INET6_ATON(poster_ip_old) from smf_messages)

add pk:
myisam 101 sec
innodb 85 sec
aria 44 sec

update: 
myisam 537 sec

**Comment by jdarwood007** [comment]
I'm testing some changes to the upgrade process right now.  I've got it converting the members table at about 61,000 ips a minute.  Thats good.

It does involve creating some temp indexes.  These are needed because any updates or selects where causing temp tables to be built to handle the joins or updates and massively slow.  The index speeds this up like crazy.

**Comment by albertlast** [comment]
you could ramp up the speed,
by execute more ip by one update: http://sqlfiddle.com/#!9/8780c9/1/0

**Comment by albertlast** [comment]
Can be closed?

**Comment by jdarwood007** [comment]
Yes
