### ISSUE TITLE
profile db error

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#3435]
Been getting a lot of these errors:

> Wrong value type sent to the database. IPv4 or IPv6 expected.(ip)
> Function: summary   /index.php?action=profile;u=1
> File: /public_html/Sources/Profile-View.php
> Line: 165

**Comment by MissAllSunday** [comment]
perhaps this is because of recent DB changes?

**Comment by albertlast** [comment]
yes this happen when the member_ip or member_ip2 of this userid in the table smf_members
is null.

this two cols and the poster_ip are target of the data converting on which jdarwood works.

**Comment by MissAllSunday** [comment]
ok thanks.

I'm running the upgrade, currently it has Time Elapsed: 60 mins, 57 seconds.  and counting... my site only has about 4k messages or so.

**Comment by jdarwood007** [comment]
What queries is it running?

We've been doing some adjustments to it to make it more efficient but not to kill servers for large forums. 4k is not a large forum so it shouldn't take too long.

**Comment by MissAllSunday** [comment]
The convert ips on messages one.

My forum was already on 2.1, dunno if that has something to do, will test on a clean forum as well as an old 2.1 installation to see if it behaves the same.

At first I was thinking the step was in a loop since I cut off the process and the forum was fine but then the same error happen again.

**Comment by MissAllSunday** [comment]
Just tested on a clean 2.0 forum and it does complete the process just fine.

An old 2.1 installation does have the same issues as my forum so this is just an issue on old 2.1 installs.

Can you list the DB changes so I can manually apply them on my forum?

**Comment by PortaMx** [comment]
on loadMemberData for 'profile' the both rows  mem.member_ip and mem.member_ip2 are not in the query. Add this and all works correct ...

**Comment by MissAllSunday** [comment]
The problem shouldn't be on the code.... it should be on the DB, there is something on my DB thats missing, I'm trying to figure it out what is it to manually apply those changes.

**Comment by PortaMx** [comment]
With ok data they will give error if you get your profile as example .. i add the missing cols and all works ...

**Comment by MissAllSunday** [comment]
No, you're probably using an old branch or something like that.

My issue is different. it seems it only affects newly registered members but since I haven't had any new recent registrations I can't confirm.

**Comment by PortaMx** [comment]
Well .. I download all 2 or 3 days the development branch and apply changes on my devel part.
So I'm always on top 😋

**Comment by albertlast** [comment]
Can be closed?

**Comment by MissAllSunday** [comment]
Well, I would still like to know which were the edits so I can manually  
apply them I still have some errors on users profiles.

## 

Jessica González, missallsunday.com

**Comment by bobrenja** [comment]
@PortaMx  where correct ??
Admin - members 

![32](https://cloud.githubusercontent.com/assets/20020367/17451333/b1229a76-5b6e-11e6-8c7c-76ff402a19e6.png)

**click username**

> Wrong value type sent to the database. IPv4 or IPv6 expected.(ip)

**click IP address**

> Invalid IP / IP range.
> Example of a valid IP address: 127.0.0.1
> Example of a valid IP range: 127.0.0.*

**Comment by PortaMx** [comment]
I think so ;-)
If you will see a Forum version (based on SMF 2.1) they we develope, look at http://smf21devel.portamx.com/

**Comment by bobrenja** [comment]
What is correct, so as not to appear error?
