### ISSUE TITLE
Guest actions integration hook

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#3441]
On a project, I needed to run a custom action via linux cron jobs. The cron simply call the custom action:

example.com/index.php?action=custom_cron

I know SMF has scheduled tasks. But I needed this one to be completely independent.

But then the forum was set to kick guests, so it prevented the server to call that action. The code preventing would be this: (index.php line 185)

`elseif (empty($modSettings['allow_guestAccess']) && $user_info['is_guest'] && (!isset($_REQUEST['action']) || !in_array($_REQUEST['action'], array('coppa', 'login', 'login2', 'logintfa', 'reminder', 'activate', 'help', 'helpadmin', 'smstats', 'verificationcode', 'signup', 'signup2'))))
        return 'KickGuest';`

So the idea is to define that array earlier so that we could pass it an integration hook.

Do you think it's a very rare situation? Shall I make a pull request for that?

**Comment by MissAllSunday** [comment]
If it is independent from SMF then don't use SMF for it, just call SSI.php on your script to get the functions you want from SMF.

**Comment by asmith20002** [comment]
No it is forum-related. SMF cron job relies on the forum to be viewed by someone. So if the cron is set to be called at 10 am but nobody visits the forum in that hour, the cron won't fire. That's why I put it in Linux cron to make sure it gets called at the specified hour.

**Comment by MissAllSunday** [comment]
In that case you can write a normal cron and call SMF index.php with the GET scheduled var defined, that takes care of the time offset while still using the scheduled task feature.

In addition you can use the integrate_default_action with a simple blank function (unset template layers, return false;) to avoid SMF's loading your entire boardIndex action.

**Comment by asmith20002** [comment]
Thanks for the response. It is actually something I could do.

But it seems that the AutoTask() only picks up the next scheduled. (My functions gotta run every 2 minutes and it will collide with other tasks at some point)

However it COULD work if the scheduled could pick up an specific task like the way it does with 'mailq'. Why it doesn't do that anyway?

**Comment by MissAllSunday** [comment]
I don't know what your custom action action=custom will do but chances are it can be done externally via SSI, in that case you don't need SMF at all, just build a normal cron script and include SSI.php

**Comment by asmith20002** [comment]
Thanks for the help. Another question though, I set a linux cron. It's simply "wget exmaple.com/index.php?action=custom"

For each call it makes, a new row gets added to sessions table. Is that the intended behavior? (I set to run every minute and now I have 2k rows in sessions table)

**Comment by MissAllSunday** [comment]
I'm still don't know what you're trying to achieve, perhaps a detailed explanation of what you want to do might help us help you better.

Or do you mean why SMF adds a new row in the session table?  if so, thats completely normal, SMF treats your cron call as a guest user and saves up some data for it. It creates  anew one every time your cron run probably because SMF identifies each call as a separate request, try set up some headers to help SMF identify your cron request

**Comment by asmith20002** [comment]
Thank you for the help!
