### ISSUE TITLE
Upgrade problem (2.0.11 to 2.1)

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3445]
After a upgrade, all attachments are lost .. the table is exists, all data seems ok, but no file can download .. only a blank screen with "file not found" .. huh?

**Comment by MissAllSunday** [comment]
Can't reproduce this issue, please make sure to always test againts the latest commit in the release-2.1 branch.

**Comment by MissAllSunday** [comment]
Closed, no follow up.
