### ISSUE TITLE
Proxy servers question

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#3449]
My forum is behind a proxy server mainly for ddos protection.

The $_SERVER var contains both HTTP_X_FORWARDED_FOR and HTTP_X_REAL_IP for the user ip. In the admin security settings I've tried both of them for the select box and filled in the proxy IP, yet when I check a user profile I still get the proxy server IP for their ip address. Am I doing something wrong?

**Comment by illori** [comment]
are you using SMF 2.1? if not then you should be posting on sm.org for support.

**Comment by asmith20002** [comment]
Yes or course. I don't think other versions of SMF have this option in settings.

**Comment by illori** [comment]
just double checking some people have posted issues about SMF 2.0 here before.

**Comment by asmith20002** [comment]
The only code I found relating to proxy_ip_servers is this : (QueryString line 252)

> ```
>   if (isset($modSettings['proxy_ip_servers']))
>   {
>       foreach (explode(',', $modSettings['proxy_ip_servers']) as $proxy)
>           if ($proxy == $_SERVER['REMOTE_ADDR'] || matchIPtoCIDR($_SERVER['REMOTE_ADDR'], $proxy))
>               continue;
>   }
> ```

How is it suppose to replace proxy ip with user ip?
