### ISSUE TITLE
Admin user not created during install

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#3450]
As the title says, an admin user is not being created during a fresh install. This issue occurs when using MySQL databases (can't check if PostregreSQL is also affected, sorry). This bug was not present in 2ed094f, but I am not sure when exactly it was introduced.

**Comment by albertlast** [comment]
The problem is this:

> ( ! ) Fatal error: Uncaught Error: Call to undefined function isValidIP() in G:\github\SMF2.1\Sources\Subs-Db-mysqli.php on line 259
> ( ! ) Error: Call to undefined function isValidIP() in G:\github\SMF2.1\Sources\Subs-Db-mysqli.php on line 259
> Call Stack
>   Time    Memory  Function    Location
> 1 0.1144  832264  {main}( )   ...\install.php:0
> 2 15.1973 900600  AdminAccount( ) ...\install.php:131
> 3 15.3078 1234704 smf_db_insert( ???, ???, ???, ???, ???, ???, ??? )  ...\install.php:1486
> 4 15.3079 1237552 smf_db_quote( ???, ???, ??? )   ...\Subs-Db-mysqli.php:786
> 5 15.3079 1237880 preg_replace_callback ( ???, ???, ??? ) ...\Subs-Db-mysqli.php:311
> 6 15.3083 1238696 smf_db_replacement__callback( ??? ) ...\Subs-Db-mysqli.php:311

the question is, where require_once is to place.

**Comment by jdarwood007** [comment]
The upgrader calls loadEssentialData() which includes Subs.php.  The installer does no such thing.  I would say since we only need it for creating the admin account, to add the call in before the Subs-Auth.php call in AdminAccount()

**Comment by albertlast** [comment]
i already done this in the pr https://github.com/SimpleMachines/SMF2.1/pull/3452
