### ISSUE TITLE
template_button_strip inconsistencies [minor]

### ISSUE THREAD

**Issue by Sorck** [SimpleMachines/SMF#3453]
Files (where issue was spotted):
- BoardIndex.php
- Compat.template.php

The button array generated circa line 130 in BoardIndex.php uses a "lang" (bool) and a "text" (string) key - presumably with the intention that the lang key being false would have the "text" key directly displayed, whereas an unset or true value would have $txt[text key] displayed instead.

Compat.template.php defines the template_button_strip function that is used to display the button. However, this uses the  $txt array and pays no attention to the "lang" key whatsoever.

If enforcing the best practice of language strings then the lang key could be removed in BoardIndex.php (and any other locations where the function is called - Recent, Memberlist, Reports, MessageIndex, Display, Xml, Calendar, index). Usually the button array is defined in the source file, not template. Conversely, if allowing direct text strings then it'd be simpler to change the definition in Compat.template.php

**Also,** the test key is used in Calendar.php (202) referring to "can_post" as a string - the template_button_strip function only checks the issetness and emptynes of the test key - it doesn't pass it through allowedTo - template_button_strip should probably do the allowedTo test if the value is a string (or array).

No SMF mods should be using the lang key as false (as per mod guidelines) so it _shouldn't_ break any mods.

**Comment by Sesquipedalian** [comment]
Hm. First of all, I'm not sure that there is any reason to have an alternative version of `template_button_strip()` in Compat.template.php in SMF 2.1. It appears to be there only for the sake of backwards compatibility with really old themes. But in SMF 2.1 we have dropped all support for those old themes, and the upgrade process even removes them. So I think having a version of this function in Compat.template.php is purposeless now. For that matter, the entire template file seems useless, since that function is the only thing it contains.

**Comment by Sesquipedalian** [comment]
Looks like the 'lang' key is pointless. My guess is that it is vestigial from sometime in the pre-2.0 days.

**Comment by Sesquipedalian** [comment]
> Also, the test key is used in Calendar.php (202) referring to "can_post" as a string - the template_button_strip function only checks the issetness and emptynes of the test key - it doesn't pass it through allowedTo - template_button_strip should probably do the allowedTo test if the value is a string (or array).

In order for the test to evaluate to true, $context['can_post'] has to already be true, which implies that the allowedTo() check has already been conducted. But even so, the check for this condition should be conducted in the source, not the template. I'll go through the source files and make everything consistent with the changes in #3557.
