### ISSUE TITLE
Delete the smf 2.1 download on smf page

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#3459]
It's hearts everytime when I read some person take the time
to test the smf 2.1 and then relealize he take smf 2.1 beta2.
He wasted his time to find issues which are already fixed.

Alternative solution would be to ref directly to smf 2.1 url from github.
But every snapshot version is wast of time on user and support side.

**Comment by illori** [comment]
we have no plans to remove SMF 2.1 from the download page. we are trying to get a beta 3 release made but it is taking time. not everyone is ready to handle downloading from github and getting the version here ready to install, so directing them here is not always a good option.

**Comment by albertlast** [comment]
And than?
the beta 3 will old again after somedays or weeks,
and the feedback from user are again for the garbage can.

**Comment by XinYenFon** [comment]
I think best solution for this issue will be creating packs taken daily from here (say GMT+1 1 AM) and edit its footer (all automated not manually). 

SMF 2.1 Beta X | Daily Snap: <date> (data needs to be hardcoded in order to avoid some issues).

Edit: Actually this type of "issues" needs to be at forum. Forgot to mention that.

**Comment by Kindred-999** [comment]
no, Antes... Dailies would just complicate matters. If they are ready to use a daily build, then the users can normally figure out that they should come to GitHub...   but the beta build which we officially release and post to the site is considered "slightly more stable" than a normal daily build...

**Comment by albertlast** [comment]
I added a topic in smf board: http://www.simplemachines.org/community/index.php?topic=546088.0
So please further discussion should be done there.
