### ISSUE TITLE
New topic is not displayed

### ISSUE THREAD

**Issue by garyee** [SimpleMachines/SMF#3461]
Hello,

I've installed a forum (version 2.0.11).
Guests have the right to create new Topics and posts.

I have experienced a strange thing error, which is occurring 2 in 5 times when I'm trying to reproduce it.
Steps to reproduce:
1. have a smf installed with at least one board, give the permission to guests to create new topics and posts.
2. as a guest create a new topic on a board that is empty(!)
3. normally after it is posted the user gets redirected to the topic-overview
   and now if the problem is reproduced the message: "no messages..." will be display, even if the new topic was created (to check that it was created go back to the categroy view, in the "last post" column the new post appears and can be clicked)
   If the new topic is displayed correctly the problem couldn't be reproduced, please continue with the next step
4. log-in as admin, delete the new topic, so that the category is empty and log-out.
   Please repeat from step 2 until you can reproduce the error. Stop after the 10. time :)

I do not know if it is just a problem of my installation or a problem in general, so it would be good if some other people tried to reproduce it.

Mods installed:
- Page Management   1.4  
- Split Forum Mod   1.33
- Advanced Language Menu    3.0.1
- reCAPTCHA for SMF     1.0.0

**Comment by garyee** [comment]
I debuged the query that is getting the topics:

normal:
`SELECT
            t.id_topic, t.....
         FROM smf_topics AS t
            INNER JOIN sm....
         WHERE t.id_board = 2
         ORDER BY is_sticky DESC, id_last_msg DESC
         LIMIT 0, 20`
error
`SELECT
            t.id_topic, t.....
         FROM smf_topics AS t
            INNER JOIN sm....
         WHERE t.id_board = 2
         ORDER BY is_sticky DESC, id_last_msg DESC
         LIMIT 0, 0`

**Comment by MissAllSunday** [comment]
Hello.

This is the repo for SMF 2.1, please go to our support forums to report a bug for 2.0: http://www.simplemachines.org/community/index.php?board=137.0

Do note that SMF doesn't keep track of unread or new topics for guests.

**Comment by garyee** [comment]
Okay.
