### ISSUE TITLE
Bugs in printpage ..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3462]
The printpage have a lot of bugs ..
1. on text without images, images/attaches in the content will be shown.
2. on text with images, attaches they inserted in the content are also shown as attach, even this is disabled in the settings.
3. qoutes don't shown correct, the class for cite is missing.

I have fixed all that, and will commit that tomorrow to my smf repository on the branch portamx ..

**Comment by MissAllSunday** [comment]
Please always test againts the latest commit made to the relelase-2.1 branch  as I cannot reprouce any of what you mention.

**Comment by PortaMx** [comment]
Because it seem like that SMF don't have interest on all things I have reported, they I make better (look and feel), I make my own Forum (based on SMF) and so I can implement what I think and what I mean it is a good option (like ECL and mutch more).
Thank you ...

**Comment by MissAllSunday** [comment]
That's cool,  smf license allows that,  good luck with your endeavors. 

Just a quick tip though,  you don't need to constantly publish your changes on this repo,  if you made your own fork that's cool,  what isn't cool is to show off on this repo,  specially when we'd told you countless of times how to contribute and you still don't get it. 

It seems you love to play the victim card,  I honestly don't have time to play along with you so next time you show off I'm simply going to close it without any further explanation. 

Have a nice day. 

Jessica González, missallsunday.com
