### ISSUE TITLE
many duplicate ID's give error on validate html

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3463]
Because the mobile menu is loaded allways (even it's not a mobil device) on Validation it gives many, many errors on duplicate id's.
Whey not check (with php) if a mobile device detected ?
It's very simple to do that .. I can spend the code for that ;-)

**Comment by Sesquipedalian** [comment]
As a matter of fact, Class-BrowserDetect.php already does check for that (although I think that code needs some updating). However, serving up different HTML to mobile vs. desktop is not the strategy the default theme uses. Instead, the theme uses the responsive design strategy, which serves up the same HTML to all clients, and has the CSS respond differently to different clients.

So the best solution is probably just to append "_mobile" or something like that to the mobile menu and the elements it contains.

**Comment by PortaMx** [comment]
Well .. that is not the best way (idea) .. any mobile Browser have a switch to emulate a Desktop Browser.. but that not work if you not check if a mobile device detected. So your (SMFs) way is bad ...

**Comment by MissAllSunday** [comment]
Thats the whole point of delivering a responsive design... if an user in a phone wants to browse a forum emulating a desktop the responsive design will just react and serve its desktop version. no need to do any checks.

The whole point of having a responsive design is not to care about the users resolution, sure its not always perfect but it avoids having checks for everything and it avoids having two separate sets for templates, one for desktop and one for phones/tablets etc
