### ISSUE TITLE
Mobile/Tablet Friendly UI

### ISSUE THREAD

**Issue by kcmartz** [SimpleMachines/SMF#347]
I like to do some of the administration on my Android tablet (I can hover, with my S Pen), but it won't go to the sub-pages. So I have to enable the side-bar. Could you implement something so it's possible to use touch devices since they are becoming so very common?

**Comment by matthew-kerle** [comment]
It does work...I use my iPhone on the menus all the time. Instead of standard hover, click it once.

**Comment by eurich** [comment]
Just a note: kcmartz is right, I can confirm this "bug". The drop menu is almost unusable on android (tested with a Galaxy S2 mobile phone and a Nexus 7 tablet).

**Comment by emanuele45** [comment]
iPhone != Android :wink: 

The top menu though should be always clickable...is it so? (I mean that in 2.1 the top menu element should bring you to a page, not like in 2.0 that was a dead end, so you should at least be able to navigate without having to enable the side menu, unless Android breaks that click too.)

**Comment by Oldiesmann** [comment]
In 2.1 it seems the top menu is always clickable. I'm also sort of able to get the drop menus to work in 2.1 on my Galaxy S3, but it's not consistent (seems if I press and hold the top item briefly it'll show the menu instead of going to whatever page that item links to).

**Comment by eurich** [comment]
tested again .. touching the buttons lightly seems to work now. Maybe a bug in Chrome which was fixed.

>  (seems if I press and hold the top item briefly it'll show the menu instead of going to whatever page that item links to).

yep, same here.

**Comment by matthew-kerle** [comment]
Oh...what do you know...that just so happens to be the same on the iPhone.

**Comment by Arantor** [comment]
How important is it to do administration from mobile/tablet? This is a nice-to-have, not so much a must-have, IMO. To really make the admin panel mobile/tablet friendly requires more than just tweaking menu behaviours.

**Comment by Xarcell** [comment]
This is a must-have for me. Some of us don't sit at a desk all day and need to admin the forum on the fly.

**Comment by Arantor** [comment]
So in the one hand you want us to close the issue and on another which is basically the same issue but for a different part of the infrastructure (and one LESS important for being responsive/mobile friendly) you want us to do it?

**Comment by Xarcell** [comment]
After some thought, yes. I re-tract my statement in this issue.
