### ISSUE TITLE
Inconsequet handling of images / attaches in the message content

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3470]
Because Image ([img]) are shown allways for any visitor, attaches [attach] images are not shown if this not enabled for Guests.
I think, that attach **images** they inserted in the content must also shown like normal images.
Alternative .. [img] is handled like attaches, also checked the attach permission
Any meanings on this ??

**Comment by MissAllSunday** [comment]
No, we shouldn't start deciding on behalf of forum admins.

**Comment by PortaMx** [comment]
Well .. I speek only on attached **IMAGES** they inserted in the content, because this is in fact identically with normal images on the IMG tag.
And download with a Right-Click I have supressed  😋

**Comment by MissAllSunday** [comment]
Nope!  attached images are still attachments and as such are still subject  
to the see attachment permission.  It will be annoying and confusing for  
users to see that attached images doesn't respect the see attachment  
permission.

Disabling right click options is pretty much useless, if the browser can  
fetch any content then said content can always be downloaded.

## 

Jessica González, missallsunday.com
