### ISSUE TITLE
The Microsoft 10 Edge browser is detected as Chrome ..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3474]
Here the Edge User Agent string:

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586"

**Comment by tinoest** [comment]
From Wikipedia "EdgeHTML is meant to be fully compatible with the WebKit layout engine used by the Google Chrome browser, and others."

What errors are you getting to raise this as a issue?

**Comment by XinYenFon** [comment]
@tinoest take a look at our body id, it specifies for browser. I think what she asks for body id="edge"

**Comment by PortaMx** [comment]
It's correct that Edge use the Chrome Engine, but the result of a page is not the same as in Chrome. So it's helpfull, if the Browser correct  detected. I added that in the Browser detection ...
