### ISSUE TITLE
Not a issue, but a look at very good code from me ..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3476]
This is MY ScEditor quote style .. look also at the time in the editor ..
Both looks **exactly** as in the Preview and also in the post itself.

How do I make that?
Yeah .. it's very simple .. a ajax call the the function **timeformat()** make this easy.
And for the alternated background ,, a little bit css.

Simple .. but not SimpleMachine ;-)

![editor_style_vs_forum_style](https://cloud.githubusercontent.com/assets/2270223/15793506/9fff66ae-29e4-11e6-91a5-91bbc92b62d9.png)

**Comment by MissAllSunday** [comment]
Yeah looks pretty nice and al that, thing is, I really don't understand whats the purpose of this.

If you want to contribute to SMF then please follow our procedures. You can't  expect that we go through your files and get whatever code you apply and bring it to SMF, its not only a waste of time (and man power) but its actually quite againts our workflow.
