### ISSUE TITLE
Footerfix Issue

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#3485]
Having more than two lines in footer, breaks the look. I don't have any solution to this unfortunately.

**Comment by iRickyJ** [comment]
I don't get it, you mean this .. ?
![smf](https://cloud.githubusercontent.com/assets/19952568/16107118/c562da3e-33b7-11e6-86bb-0b9d2ab84c57.JPG)

**Comment by XinYenFon** [comment]
more than two :)

![screenshot-localhost 2016-06-16 11-42-26](https://cloud.githubusercontent.com/assets/1669995/16110643/72dc68fc-33b7-11e6-97d4-a59cf1cd111d.png)

**Comment by iRickyJ** [comment]
Is that a problem ? Theme authors and mod authors will eventually add their stuff there, we are bound to have multiple lines. What we may do that can use some less bright colors , may be #bbb to make it less attention grabbing.

**Comment by XinYenFon** [comment]
Main body and footer mixes, after adding more lines. Try to add extra 3 lines you can see footer overflowing onto the Info Center.

**Comment by jdarwood007** [comment]
The question is, why do we specify a position of absolute on the footer?  Drop that and remove the padding from the footer fix and it works just fine.  The debug code breaks the display a little but meh.

**Comment by Arantor** [comment]
Does that cause it to have the footer pulled up to the bottom of the body content? The whole point of this fix was to keep the footer at the bottom even if the page only had a short amount of content.

**Comment by Sesquipedalian** [comment]
I just played around with this, and one solution would be to set a max-height value on the footer element. Extra lines would still be visible by scrolling down, because they'd overflow the 100% height on the body element, but they won't cause the footer to interfere with the main content.

I tried `max-height: 75px` to match the 75px padding on the bottom of the footer-fix element, and a third line fits comfortably using this setting. The fourth and following lines end up in the overflow past the bottom of the viewport on initial page load.

**Comment by Sesquipedalian** [comment]
#3508

**Comment by XinYenFon** [comment]
I don't think "scrolling" is a good solution.

**Comment by Sesquipedalian** [comment]
Perhaps I didn't explain clearly enough. I don't mean scrolling inside the footer. I just mean that if there's a fourth line of text in the footer, it won't be visible within the viewport until the user scrolls to the bottom of the page as a whole. This is visually indistinguishable from what happens now already with any page with content that is taller than the viewport.

If after you try it you don't like it, that's fine, of course.

**Comment by live627** [comment]
Solved with flexbox.

![fireshot screen capture 017 - an error has occurred - localhost_smf2_1](https://cloud.githubusercontent.com/assets/431799/17612077/6ecaa626-6002-11e6-811a-7e0cff4e7800.png)

![fireshot screen capture 018 - set search parameters - localhost_smf2_1_index_php_action search](https://cloud.githubusercontent.com/assets/431799/17612076/6ec9495c-6002-11e6-98f9-ce28f2146c28.png)

Tested in MS Edge,  IE 11, Firefox, Chrome.

**Comment by Sesquipedalian** [comment]
That would be the easy solution, yes. The problem is, IE9 doesn't support flexbox.

**Comment by jdarwood007** [comment]
For IE9 if we still support it, we fall back to a fixed box and just let it break as it currently does..

**Comment by live627** [comment]
Right. So then it silently falls back to the  behavior from before the original fix.

**Comment by Sesquipedalian** [comment]
> For IE9 if we still support it, we fall back to a fixed box and just let it break as it currently does..

I wish we weren't still supporting IE9, but we are. The point of #3508 is that it fixes the problem quite neatly even for IE9. Now, personally I am a fan of flexbox and I like @live627's solution using it. But from what I can tell, @Antes has made it an unstated rule to avoid using flexbox in order to make sure Curve2 will work as intended even on our minimum supported browser. This, however, is a case where I would advocate bending that rule: we should use flexbox to solve it for modern browsers and fall back to the max-height solution for those that don't.

**Comment by live627** [comment]
All thi s work for what - a visual enhancement that almost nobody will see
(a goddamn footer? End of content or bottom of window in ~5% of loads, if
even that?). I'd say use flexbox (fix it properly) and be done.

This  is not nearly as important as a header, or a progress bar.

**Comment by XinYenFon** [comment]
I never made statement against or in favor of using flexbox :P 

@Sesquipedalian the problem with your fix, when footer gets bigger say 10 lines (it might not be possible but still) your fix not become a solution.

@live627 +1

**Comment by Sesquipedalian** [comment]
> the problem with your fix, when footer gets bigger say 10 lines (it might not be possible but still) your fix not become a solution.

My solution handles that quite well.
![screen shot 2016-08-12 at 4 39 18 am](https://cloud.githubusercontent.com/assets/191731/17620070/e6da611c-6046-11e6-894b-59699f37d678.png)

**Comment by XinYenFon** [comment]
My apologies, probably my localhost corrupted (?), because when i applied your fix it wasn't doing this.

**Comment by Sesquipedalian** [comment]
> My apologies, probably my localhost corrupted (?), because when i applied your fix it wasn't doing this.

No worries. :)

**Comment by jdarwood007** [comment]
If we can we should do our best to keep the theme consistent as possible for our oldest possible browser we support.  However we can degrade a little for those older browsers if it means 90% or 95% (whatever) or more browsers and viewers will be better supported.

I can't remember where I read it, but there was an article on this and it basically says, its ok to degrade ascetics/looks for older browsers if it degrades in a graceful way.  This is such a fix that degrades nicely and affects very few of our users.

**Comment by Arantor** [comment]
Are you supporting browsers whose manufacturer stopped supporting them? IE 9 and 10 EOL'd more than six months ago.

As long as the footer stays at the bottom and doesn't creep up the page on short pages, everything is cool.

**Comment by XinYenFon** [comment]
@Arantor not really, but we have small fallbacks.

**Comment by Sesquipedalian** [comment]
> IE 9 and 10 EOL'd more than six months ago.

Did they? Excellent. I see no reason to maintain support for them either. It'll free us up quite a bit, I think.

**Comment by Arantor** [comment]
https://www.microsoft.com/en-gb/WindowsForBusiness/End-of-IE-support - EOL announcement for IE9 and 10.
