### ISSUE TITLE
"Configure guest and new user options for this theme" also apply changes to random existing users when it shouldn't

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#3487]
So I recently used "Configure guest and new user options for this theme" on my board so that future member accounts have certain options changed by default, such as board notifications. However, after I applied the changes, it also changed notification settings for random users. For example, my account was not hit, but many other members were hit, even though I made sure that I had carefully chosen "Configure guest and new user options for this theme".

Shouldn't it just change options for future accounts and (if applicable) guests, and not existing random user accounts?

NOTE: This is a SMF 2.0.11 issue, not a SMF 2.1 bug, but for some reasons SMF dev page led me here for SMF bugs.

**Comment by illori** [comment]
this is not the location to report bugs with SMF 2.0. bugs with SMF 2.0 should be reported here http://www.simplemachines.org/community/index.php?board=137.0 . please report it there and close this report unless you can duplicate the issue with SMF 2.1.
