### ISSUE TITLE
Bug in the database updater

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3488]
The settings table (displayFields) is filled with **serialized** data, but in the code **json_decode** is used. That gives havy problems ;-)

Also I don't uderstand, wy serialize/unserialize used at many points .. this all can replaced with json_xx

**Comment by MissAllSunday** [comment]
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L4128
