### ISSUE TITLE
2.1 beta 3 syntax error in upgrade.php

### ISSUE THREAD

**Issue by iRickyJ** [SimpleMachines/SMF#3490]
Today I tried to test 2.1 beta 3 on forum upgrade from 2.0.11 , worked fine on local test server with php 5.6 , however ,when I tried same on another test server running php 5.4.45, upgrade.php kept giving me following error:  (with blank page)

`[Tue Jun 14 13:21:33 2016] [warn] [client x.x.x.x] mod_fcgid: stderr: PHP Parse error:  syntax error, unexpected '==' (T_IS_EQUAL), expecting ')' in /home/abc/public_html/upgrade.php on line 5141
`

I don't find anything unusual there at 5141, Is it that I am seeing a nested expression which is not supported in 5.4 but in 5.6 or it could be something else ?
(install.php is fine though)

Update: 
Just to verify if its issue with PHP version, I upgraded to PHP 5.5.36 (as tested in 5.6 already at local server) in this server and now there is no error in upgrade.php and upgrade went smooth.

Any idea..  I thought SMF 2.1.x supports PHP 5.3.8 and above..

**Comment by MissAllSunday** [comment]
Yes, this happens because empty() on php 5.4 or less only supports variables, on this case php5.4 doesn't know how to handle the comparison expression given to it.

**Comment by iRickyJ** [comment]
Alright, didn't know that or never got in that situation. Glad to see you already fixed it. I guess we can mark it closed.
