### ISSUE TITLE
Malformed JSON on admin access

### ISSUE THREAD

**Issue by iRickyJ** [SimpleMachines/SMF#3495]
Hi, 

Seeing following error everytime I access admin area : 

```
TheInsider
Today at 11:20:27 AM
x.x.x.x  
34cbeb7dd67a985317a640673c1467f9
Type of error: Critical
Json decode error: Syntax error, malformed JSON
http://some-domain.com/index.php?action=admin;area=logs;sa=errorlog;desc
File: /home/yuse/public_html/Sources/Admin.php
Line: 42
```

However, on line 42, its trying to assign value to context['admin_preference'] from $options['admin_preference'] which outputs to : 

```
["admin_preferences"]=>
  string(29) "a:1:{s:2:"pv";s:7:"classic";}"
```

This error is not there on fresh install but seeing this on a board converted from 2.0.11 to 2.1b3

**Comment by MissAllSunday** [comment]
The upgrade has a substep to convert all current serialized settings into json format, it looks like the upgrade failed to convert all of them or just this specific one, heres a list of tables and coloums affected by it:  https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L4128

Can you please verify that those columns/values were converted to json?  if they weren't then chances are theres something wrong on the upgrade process.

On the other hand, it is nice to know the json error log thing is working as intended :tongue:

**Comment by XinYenFon** [comment]
If you need I can dump db to you (its something like 2mb)
![screenshot-localhost 2016-06-16 18-05-08](https://cloud.githubusercontent.com/assets/1669995/16121773/35d54fd8-33ed-11e6-8bb5-956ceded4fca.png)

**Comment by PortaMx** [comment]
The bug is also on a fresh install ..

**Comment by albertlast** [comment]
@MissAllSunday i think it would be a better approache when you build a new datatype in the db engine,
like i do with inet.
Than your need only on place where the json_enconding need to be placed.

with "db engine" i mean this file: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Db-mysqli.php#L265

**Comment by PortaMx** [comment]
You known, that the inet-array have a bug ?
Look at the code and find the error 🤓

**Comment by albertlast** [comment]
you know how to read? https://github.com/SimpleMachines/SMF2.1/pull/3483#issuecomment-225664567

**Comment by PortaMx** [comment]
> i think it would be a better approache when you build a new datatype in the db engine

A very good point .. I'v tested that for log_online (data type **json**) .. works great. Thank for this good idea !!

`case 'json':
            return sprintf('\'%1$s\'', json_encode($replacement));
        break;
`

**Comment by MissAllSunday** [comment]
json functions aren't solely used with DB values, they are also used on plain regular vars.

There is no point in adding another function when one function can handle it all.

The error the user is reporting happens when upgrading, there has been some issues with the upgrade process, those issues are likely related to this and thus, it won't be solved by adding a new case type in the DB wrapper.

**Comment by MissAllSunday** [comment]
@iRickyJ can you still reproduce this issue?

**Comment by XinYenFon** [comment]
I can't reproduce this issue anymore.

**Comment by PortaMx** [comment]
this can be closed ..

**Comment by MissAllSunday** [comment]
http://i.imgur.com/zCNryif.jpg

**Comment by XinYenFon** [comment]
Weird,, I had this issue while testing #3530. Error occurs after creating event, and occurs each time you visit the topic contains event.

Load.php - Line: 1503
