### ISSUE TITLE
Upgrade problem (2.0.11 to 2.1 b2)

### ISSUE THREAD

**Issue by bobrenja** [SimpleMachines/SMF#3498]
download http://download.simplemachines.org

upgrade error 

![2016-06-19 1 04 06](https://cloud.githubusercontent.com/assets/20020367/16174556/5958ca0a-35cf-11e6-825f-a8bea22da728.png)

**Comment by XinYenFon** [comment]
You can upload images here and also can you write your server-details (php-mysql versions) for better debug.

**Comment by bobrenja** [comment]
MySQL 5.0.67
Php 5.4.45

**Comment by albertlast** [comment]
Make a new copy of you 2.0.11 in mysql,
use the github version https://github.com/SimpleMachines/SMF2.1/archive/release-2.1.zip
move the upgrage\* files from others to the root  directory and
try again to upgrade.

**Comment by bobrenja** [comment]
Where to take russian for release 2.1?

**Comment by albertlast** [comment]
I don't know where the language file are,
but in the worst case (when you realy need them) take the beta2 language packages.

**Comment by bobrenja** [comment]
Settings.php move the  files from others&

No login input

![2016-06-19 9 18 45](https://cloud.githubusercontent.com/assets/20020367/16175674/e90ec562-35fe-11e6-92eb-787da6c54048.png)

**Comment by albertlast** [comment]
Than try without,
maybe after the upgrade process.

**Comment by bobrenja** [comment]
Settings.php move the  from others?

**Comment by albertlast** [comment]
Nope

**Comment by bobrenja** [comment]
Use the github version https://github.com/SimpleMachines/SMF2.1/archive/release-2.1.zip
Write "Thank you for choosing to upgrade to SMF 2.1 Beta 3...."

**So it should be?**

![2016-06-19 11 21 42](https://cloud.githubusercontent.com/assets/20020367/16176194/603bc34a-3610-11e6-9369-e5cf59ab4090.png)

no files

Themes/default/css/**minified.css**
Themes/default/scripts/**minified.js**
Themes/default/scripts/**minified_deferred.js**

**Comment by iRickyJ** [comment]
You can create them manually and set them to chmod 644

PS: I also had to create them , why not to provide these files by default with package ?

**Comment by albertlast** [comment]
I think this is a real issue @MissAllSunday  that the file handling is wrong

**Comment by bobrenja** [comment]
So, these files should be in the package, or they need to be downloaded separately ??
They need to work offline or not?
If needed, where to download?

**Comment by iRickyJ** [comment]
For now you can simply create blank text files with those name and upload.

**Comment by MissAllSunday** [comment]
What files?  can you be more specific?  are you refering to the minify files only?

I'm not even sure why theres a need to mess up with the minify files on upgrading, thats something @jdarwood007 added.

**Comment by jdarwood007** [comment]
I added it to make sure the upgrade script knew they where in place.  We could either drop that check or add the files as empty to the upgrade/install packages.

**Comment by bobrenja** [comment]
Forum and failed to update.
I wish once again to upgrade, download the latest implementing and again this error.
How to overcome it?
![5958ca0a-35cf-11e6-825f-a8bea22da728](https://cloud.githubusercontent.com/assets/20020367/16914489/d6243dde-4cfa-11e6-8705-a5b81580fd51.png)

**Comment by bobrenja** [comment]
Problem solved.
Deleted files are handed in the themes folder.
