### ISSUE TITLE
The function inet_dtop($bin) don't work allways correct..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3504]
I found a lot of ipv6 adresses the have a  . (dot) or : (doublepoint) as binary.
So the test of '.' or ':' failed.

I change that to:
`function inet_dtop($bin)
{
    if(empty($bin))
        return '';

```
$ip_address = @inet_ntop($bin);
if($ip_address === false)
    return '';

return $ip_address;
```

}`

Now all works correct ..

**Comment by albertlast** [comment]
see pr https://github.com/SimpleMachines/SMF2.1/pull/3405

**Comment by PortaMx** [comment]
Yeah .. I see .. but THAT gives a runtime error on **inet_ntop** if the ip not a correct ip4 or ip6 address.
inet_ntop returns false on bad ip's and also a runtime error .. (tested)

Refer: http://php.net/manual/en/function.inet-ntop.php

**Comment by albertlast** [comment]
I can't follow you.
Can you please post the code from inet_dtop which u use for this test?

**Comment by PortaMx** [comment]
See my first Post .. the code is inside this 😉

**Comment by albertlast** [comment]
I mean after you applied the change from pr #3405

**Comment by PortaMx** [comment]
No .. my code works perfect, so I see no necessary to change a running code ...

**Comment by tinoest** [comment]
But you're code isn't good coding practice, you're silencing a error with the @ sign. It's better to not have the error in the first place. 

You also state there is a error when using the code from pr #3405, is this the case or not, as your last comment contradicts your second comment.

**Comment by PortaMx** [comment]
Without the @ it will gives a runtime error, that fills the error log ,,,
You can simple test that if you have a good debugger (like phped or similar) .. set a breakpoint before, manipulate the binary ip, then step into .. bäng .. runtime error ;-)
The problem is here, that you can't test the binary if is have a correct ip ... and php itself have no function for this .. in the net you find many function for this, but at this point that is overdressed.

**Comment by albertlast** [comment]
Your solution doesn't work with postgresql,
take the solution from pr #3405

**Comment by PortaMx** [comment]
Yeah .. Yesterday I have installed a Postgres DB, so I can also test all with postgres,
I added the postgres check and it works fine ..

**Comment by albertlast** [comment]
You only need to place the pg check,
more change is not needed.

the intention of . and : check was only for pg.

**Comment by MissAllSunday** [comment]
Hey @tinoest  do you have an account over at SMF?  or can I contact you in the mail you provide to sign off your commits?  I would like to discuss something with you, thanks.

**Comment by tinoest** [comment]
@MissAllSunday 

You can contact me on SMF i'm also tinoest on there, or my email I use for my commits, tinoest@gmail.com.

**Comment by MissAllSunday** [comment]
Great! thank you.

**Comment by albertlast** [comment]
This issue is fixed with the pr: https://github.com/SimpleMachines/SMF2.1/pull/3529
