### ISSUE TITLE
Upon visiting attachment settings page, on fresh install, two errors in the error log

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#3505]
Json decode error: Syntax error, malformed JSON
File: C:/xampp/writing/laravel/public/smf2.1_20160702/Sources/Subs.php
Line: 3113

8: Undefined offset: 1
File: C:/xampp/writing/laravel/public/smf2.1_20160702/Sources/Subs.php
Line: 3114

**Comment by Oldiesmann** [comment]
What's the value of $modSettings['attachmentUploadDir']?

**Comment by Arantor** [comment]
Whatever a fresh install puts in it... this was a fresh install, nothing configured and I just went to that page. MySQL install.

**Comment by MissAllSunday** [comment]
This seems to be the cause, on Sources/ManageAttachment::ManageAttachmentSettings()

`
// First time here?
    if (empty($modSettings['attachment_basedirectories']) && $modSettings['currentAttachmentUploadDir'] == 1 && count($modSettings['attachmentUploadDir']) == 1)
        $modSettings['attachmentUploadDir'] = $modSettings['attachmentUploadDir'][1];
`

Don't know exactly why we are doing that but we should probably use another temp var and leave $modSettings['attachmentUploadDir']  unaltered.

**Comment by MissAllSunday** [comment]
This is getting interesting...  removing that code and  it seems prepareDBSettingContext doesn't know how to handle json values.

By default it passes whatever value to $smcFunc['htmlspecialchars'] for sanitization, problem is, in the specific case for attachmentUploadDir  its modSettings entry is an array by the time it gets passed:

``` php
                switch ($config_var[0])
                {
                    case 'select':
                        $value = $modSettings[$config_var[1]];
                        break;
                    case 'boards':
                        $value = explode(',', $modSettings[$config_var[1]]);
                        break;
                    default:
                        $value = $smcFunc['htmlspecialchars']($modSettings[$config_var[1]]);
                }
```

So, either make an ugly hack for attachmentUploadDir or create a new type, "json_string" or something to let SMF to handle it properly.
