### ISSUE TITLE
SSI charset problem

### ISSUE THREAD

**Issue by exotickg1** [SimpleMachines/SMF#3517]
I've include the SSI.php, its ok, but when i trying to use it, i see undefined glyphs, where must be russian chars.
![Bug](https://i.gyazo.com/620a91f8e450daa4ecaa3af2c61a626f.png)
I have only 2 chars at russian - "от", it means "from" (user). And yes, they are displayed. This is strange :open_mouth: 

My database - UTF-8, MariaDB 5.5.47
My forum - UTF-8 charset too, no problem at forum with russian glyphs.
My site where i connect SSI - UTF-8 charset. 

0 problem, when i include RSS2. When i open /forum/ssi_examples.php its too ok. No chars missed.

**UPD: Problem only with:**
- _Topic Names_
- _Board Names_
- _Post Content_
- _News_

Other ssi functions working perfectly.

**Comment by MissAllSunday** [comment]
Theres currently an issue with converting to UTF8 on upgrading, can you please do a full new install and see if this issue also happens over there?  this is just to confirm if this is a result of converting to UTF8 on upgrading.

**Comment by exzoc** [comment]
Ok. I'm upload all files from translation, but except the **Themes\default\languages\index.php**:

There's index.php from my language pack for 2.1 beta 2:

```
<?php
// Version: 2.1 Beta 1; Index
?>
```

And last file from 2.1 release:

```
<?php

// Try to handle it with the upper level index.php. (it should know what to do.)
if (file_exists(dirname(dirname(__FILE__)) . '/index.php'))
    include (dirname(dirname(__FILE__)) . '/index.php');
else
    exit;

?>
```

During installation, everything was fine. At the last step page charset fallen off ([screenshot](https://i.gyazo.com/4d440af18a407029c55a0e2ea168ff38.png))

But still, in the end everything appears normal and I did not notice any bugs.
![screenshot](https://i.gyazo.com/27b24cf3c66008aa7b3bf248bd5e2eaa.png)

**Comment by XinYenFon** [comment]
I'm sorry I was bit away from development.

We are aware of the index.php issue on language packs. More importantly if you still have old non-utf8 smf2.0 db, can you set it up and use UTF8 Convert via Admin Panel then run upgrade.php.
