### ISSUE TITLE
[Minor] Replies language

### ISSUE THREAD

**Issue by idesignSMF** [SimpleMachines/SMF#352]
Notices this today and its also on 2.0  When clicking Unread Posts and Updated Topics (with no replies or new topics)...

It shows: No unread topics found since your last visit. Click here to try all unread topics. for both.

Shouldnt be No unread topics found since your last visit. Click here to try all unread topics. and No unread replies found since your last visit. Click here to try all unread replies.?

See the difference? 'topics' and 'replies'?

**Comment by XinYenFon** [comment]
Please see ¨#235 separation is already discussed :)
