### ISSUE TITLE
Stats - expand a month don't work

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3521]
Stats month expand don't work because the action is missing here:

`// Actions that specifically uses XML output.
    $xmlActions = array(
        'quotefast',
        'jsmodify',
        'xmlhttp',
        'post2',
    );
`

Must be:

`$xmlActions = array(
        'quotefast',
        'jsmodify',
        'xmlhttp',
        'post2',
        'stats'
    );
`

Now it works ..

**Comment by bperry921** [comment]
what file is that code in?

**Comment by PortaMx** [comment]
Load.php  .. ~ line 1963
