### ISSUE TITLE
Add Markdown instead BB Code?

### ISSUE THREAD

**Issue by exotickg1** [SimpleMachines/SMF#3524]
I think many users would like to see a modern markup language Markdown in settings. Can you make it please?
http://daringfireball.net/projects/markdown/
https://en.wikipedia.org/wiki/Markdown

**Comment by MissAllSunday** [comment]
At this point we aren't looking to replace BBC with Markdown.

Just like BBC, there are lots and lots of different "flavors" of Markdown running wild on the interwebz so it will be difficult to define what features we will support and what not.

Besides, BBC can be used for more than format and style while Markdown cannot be used this way, I suppose it can be used the same way BBC tags are used but we will end up having the exact same thing BBC already provides.
