### ISSUE TITLE
The Board indicator is set to "no new topic" if the board entered even if unread topics exists

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3536]
To be cleared .. the Board Indicator (the big image at left) is set to no now topics even if the board entered, without read any topic .. that's bad. (by the way .. in the Message view the indicator is missing)

I think, the "board is read" should by moved to "if the board have no new/unread topics". This will passed in the Display.php or MessageIndex.php (I think).

What SMF mean about this ?

Board view:
![image-1](https://cloud.githubusercontent.com/assets/2270223/17652122/10c437c0-6275-11e6-8d3f-39157337d13e.png)

Topic view:
![image-2](https://cloud.githubusercontent.com/assets/2270223/17652123/26bfc616-6275-11e6-892b-31eff26bac87.png)

**Comment by Oldiesmann** [comment]
It's always been that way. It means that there haven't been any new topics in the board since you last visited it.

**Comment by PortaMx** [comment]
Well .. I change the code and mark the board as read, if no new Topic/Reply exists in the Board.
Works perfect ... 😊
