### ISSUE TITLE
Help link after OpenID input field on Login refers to protected help page if Guest's are not allowed to browse the forum

### ISSUE THREAD

**Issue by DelPoint** [SimpleMachines/SMF#354]
Hello Gents,

Just a quick note about the help link after OpenID's input field. The default theme's Login.php file contains this code in line 53:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/Login.template.php#L53
The problem is with the anchor tag's href attribute, which refers to a protected page, therefore if Guest's are not allowed to browse the forum, clicking on the link will open the login form (without CSS) in a pop-up window informing the visitor he can't access that page.

Cheers.

**Comment by emanuele45** [comment]
Hi DelPont,

the link points to the helpadmin action, that as far as I can see doesn't have any permission check, so it should be accessible to everybody, guests included...

**Comment by DelPoint** [comment]
Hi emanuele45,

Well, I've not tested it with SMF2.1, just compared it to the code of the current release (2.0.4), and seen the code is same. So, in SMF's current release if you disable the browsing for Guests, the link will not open the expected 'helpadmin' page, instead (only!) the form tag and its content from the login page will be opened in a new pop-up window without any CSS (so UA's default styling will be applied).

Try it, you'll see it.

**Comment by illori** [comment]
![image](http://imageshack.us/a/img577/6457/image002js.png)

yep as a guest without access to the forum the popup does not work.

there is no other location that i can see that uses the help popup outside areas that require the user to be logged in.

also do note the error text is not showing up in the popup in this case either

also in Help.php with the new popup is this still needed?

``` php
// Set the page title to something relevant.
    $context['page_title'] = $context['forum_name'] . ' - ' . $txt['help'];
```

**Comment by DelPoint** [comment]
Well, I didn't have enough time to investigate the code more deeply. However I guess, the problem is connected to the 'action=helpadmin' parameter. But really not sure...

**Comment by DelPoint** [comment]
Sorry, clicked on the wrong button.

**Comment by Oldiesmann** [comment]
Looks like this is actually a rather simple fix - we just need to add helpadmin to the array of allowed guest actions in index.php. I'll push a fix through for this shortly.
