### ISSUE TITLE
Creating user via admin panel causing errors.

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#3540]
Way to reproduce: Create a user via admin panel and visit user's profile.

Warning: inet_ntop(): Invalid in_addr value in ...\Sources\Subs.php on line 4985

**Comment by MissAllSunday** [comment]
I'm assuming you are testing this locally right?  in that case your IP would be 127.0.0 which is  a string and that function cannot properly handle them.

@albertlast ?

**Comment by XinYenFon** [comment]
![screenshot-localhost 2016-08-19 17-19-47](https://cloud.githubusercontent.com/assets/1669995/17812778/4086ae74-6631-11e6-8146-22d8b06ed7ec.png)

bottom is the created user.

**Comment by albertlast** [comment]
The screenshot look like that the data are wrong saved in the db,
a) field type could be wrong, should be varbinary
b) problem by converting the string into varbinary inet_ptod

please run "select inet6_ntoa(member_ip) ..." 

Is someone else able to reproduce this error?
