### ISSUE TITLE
small bug in script.js

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3541]
the function **createEventListener(oTarget)** have a bug in this line:

function createEventListener(oTarget)
{
    **if (!('addEventListener' in oTarget))**
    {

if oTaget undefined it gives a error. So this line must be change to;

```
if (oTarged !== 'undefined' && !('addEventListener' in oTarget))
```

Now the error is gone ..

**Comment by Oldiesmann** [comment]
At what point would oTarget be undefined?

**Comment by PortaMx** [comment]
The error comes up on **Signup**  and if you request a new image ..

here the worked code:
`function createEventListener(oTarget)
{
    if (typeof oTarget !== 'undefined' && !('addEventListener' in oTarget))
    {
        if (typeof oTarget.attachEvent !== 'undefined')
        {
            oTarget.addEventListener = function (sEvent, funcHandler, bCapture) {
                oTarget.attachEvent('on' + sEvent, funcHandler);
            }
            oTarget.removeEventListener = function (sEvent, funcHandler, bCapture) {
                oTarget.detachEvent('on' + sEvent, funcHandler);
            }
        }
        else
        {
            oTarget.addEventListener = function (sEvent, funcHandler, bCapture) {
                oTarget['on' + sEvent] = funcHandler;
            }
            oTarget.removeEventListener = function (sEvent, funcHandler, bCapture) {
                oTarget['on' + sEvent] = null;
            }
        }
    }
}
`

**Comment by Oldiesmann** [comment]
We need to trace that issue then and figure out why oTarget is undefined

**Comment by XinYenFon** [comment]
I can't reproduce this issue btw.

**Comment by PortaMx** [comment]
Well .. I use the code above and all works as very well ..
You can see the error if you use Chrome with the development options. Look at the console log ..

**Comment by XinYenFon** [comment]
![capture](https://cloud.githubusercontent.com/assets/1669995/18050833/a1f00122-6df9-11e6-9da3-9365014847f2.PNG)

**Comment by PortaMx** [comment]
Hmm .. Intersting things ..
Well .. it's possible that I have a other situation, because I use SEF on all links.
One point they I have to verify .. Thanks for reply to this ..

**Comment by MissAllSunday** [comment]
Must be some external code, all calls to createEventListener within SMF are done on created/defined elements.

**Comment by jdarwood007** [comment]
This is the default SEF urls, not a 3rd party/mod SEF?  Does disabling SEF make it work?

**Comment by XinYenFon** [comment]
@jdarwood007 nope. I enabled SMF's SEF and tried again both on Chrome & Edge no error on console.

**Comment by PortaMx** [comment]
We use a "real sef" and we found a lot of cryptic urls used for likes etc. after we fixed that all works as very well 😋
