### ISSUE TITLE
On more missing action in the $xmlActions array ..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3542]
the missing action is: (tadaaa)
**signup**

without this, the username check on signup won't work ..

(I dont understand me, that i helps SMF because he is ignoring my work)

**Comment by Sesquipedalian** [comment]
Thanks, PortaMX. #3543 should fix this.

**Comment by Sesquipedalian** [comment]
Oh, I just saw that @MissAllSunday already committed a fix for this.
