### ISSUE TITLE
Event in the calendar week view ..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3552]
These looks a little bit ugly on a mobile device (testet with a Nexus 7 tablet) ..
![bad_week_view](https://cloud.githubusercontent.com/assets/2270223/17984438/706191a6-6b11-11e6-9517-1490011d9fae.png)

with a little bit css hack they will looks better ..
in the calendar.css make this changes:
`#main_grid .calendar_week .event_col:before {
        content: "Events: \a";
        white-space: pre;
    }
    #main_grid .calendar_week .holiday_col:before {
        content: "Holidays: \a";
        white-space: pre;
    }
    #main_grid .calendar_week .birthday_col:before {
        content: "Birthdays: \a";
        white-space: pre;
    }
`

Now the event shown like:
![good_week_view](https://cloud.githubusercontent.com/assets/2270223/17984495/af0ed206-6b11-11e6-982a-ed5b5b84a04b.png)

**Comment by XinYenFon** [comment]
This is actually fixed in #3530

**Comment by XinYenFon** [comment]
@live627 this can be closed not sure why its not closed on merge.

**Comment by live627** [comment]
k
