### ISSUE TITLE
ConvertUTF8 issue on upgrade

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#3554]
I just wanted to open this issue as track and discuss. Well actually @equinoxmatt send me a fix and its working. I noticed some small issues, upgrade.php now seems to trying (?) to do utf8 & json convert at same time and its causing upgrade.php stuck (after completing the process). I rerun the upgrade.php and its completed w/o problem. Function converted all tables but {prefix}_user_likes.

I tested some basics of forum after upgrade everything seems working fine (do mind I used empty DB, we're still not sure about the function working perfectly).

![screenshot-localhost 2016-08-26 03-29-58](https://cloud.githubusercontent.com/assets/1669995/17990385/f128e06a-6b3d-11e6-87fb-bb9a219b0681.png)

**Comment by equinoxmatt** [comment]
Hmm, I didn't get that when I tried it,  I will take another look tomorrow.  I noticed some really odd stuff with the MySQLConvertOldIp() function.  Might be worth another issue,  but some of the subStep code seems to be not behaving correctly. 

Not sure if it is all somehow related?  I will do some more digging over the next few days.

**Comment by XinYenFon** [comment]
I did another test run today, and this is still happening. Way to reproduce; "Install non-utf8 SMF 2.0 then upgrade to 2.1 (latest)".

Do mind upgrade process actually ends but user_likes table stays as is.

**Comment by sbulen** [comment]
I don't think user_likes is in vanilla 2.0.

Was this from a mod, in 2.0?   Or is this a 2.0 table being setup incorrectly?

**Comment by Oldiesmann** [comment]
user_likes is a new table in 2.1.

**Comment by sbulen** [comment]
Is the mentions table OK?   How about the moderator_groups table?  
I'm trying to review this code, they all appear to be created similarly in the upgrade script.

**Comment by equinoxmatt** [comment]
Looking a bit more into this today.  The reason we get the odd progress bar update is the following line:

`$upcontext['table_count'] = 13;`
	`$upcontext['cur_table_num'] = $_GET['substep'];`
`	$upcontext['cur_table_name'] = isset($keys[$_GET['substep']]) ? $keys[$_GET['substep']] : $keys[0];`
`	$upcontext['step_progress'] = (int) (($upcontext['cur_table_num'] / $upcontext['table_count']) * 100);
`

table_count is set to 13,  with 13 harcoded table names.  So in the convertToUTF8,  you had 75 tables.  The calculation is this:

> 75 / 13 * 100 = 576

The whole substep stuff is mind boggling,  so I am not sure how to fix this without doing more digging.  

Can anyone shed any light on why the table names are harcoded?  It is hard to solve without a wider context.

	`// List of tables affected by this function`
	`// name => array('key', col1[,col2|true[,col3]])`
	`// If 3rd item in array is true, it indicates that col1 could be empty...`
`$tables = array(`
		`'background_tasks' => array('id_task', 'task_data'),`
		`'log_actions' => array('id_action', 'extra'),`
		`'log_online' => array('session', 'url'),`
		`'log_packages' => array('id_install', 'db_changes', 'failed_steps', 'credits'),`
		`'log_spider_hits' => array('id_hit', 'url'),`
		`'log_subscribed' => array('id_sublog', 'pending_details'),`
		`'pm_rules' => array('id_rule', 'criteria', 'actions'),`
`		'qanda' => array('id_question', 'answers'),`
	`	'subscriptions' => array('id_subscribe', 'cost'),`
		`'user_alerts' => array('id_alert', 'extra', true),`
		`'user_drafts' => array('id_draft', 'to_list', true),`
		`// These last two are a bit different - we'll handle those separately`
		`'settings' => array(),`
		`'themes' => array()`
	`);`

**Comment by equinoxmatt** [comment]
Just realised,  I may be looking at it the wrong way.  Is this a case of $_GET['substep'] should actually be 0 instead of 75 (from UTF8 conversion step?)

**Comment by sbulen** [comment]
Maybe this adds a little insight...

I have run into this issue on a couple of upgrades from 2.0 to 2.1.  Specifically, the status bars are confusing & some tables are not converted to UTF8.  One time it was just a few tables, one time it was ~20.   

Given it doesn't fail the exact same time, I have suspected one of two things - either a resource issue or it's having a problem with a specific table, which it may not always process in the same sequence.   

In my cases, I installed 2.0 & immediately upgraded that empty site to 2.1.

**Comment by live627** [comment]
Anyone care updating me on this issue? I'm completely out of the loop...

**Comment by sbulen** [comment]
I believe I have identified the precise failure that occurs when user_likes is skipped....   It is a simple subscript issue.   

equinoxmatt is on the right track...

In a 100% vanilla 2.0 to 100% vanilla 2.1 scenario, there are 72 tables.  In alpha order, the 1st one is admin_info_files, and the 72nd one is user_likes.   

The main "for ($substep..." loop in ConvertUtf8() on line ~3602 properly executes 72 times, once for each table.  However...
   1st time thru, $substep = '0', (yep, a weird literal) and it processes admin_info_files
   2nd time thru, $substep = 1, and it processes admin_info_files... AGAIN...
              ...   
   72nd time thru, $substep = 71, and it processes user_drafts

It never gets to user_likes - the LAST table, 72...   

To fix, I think $substep should be initialized to 1, not to '0', and the for statement at line ~3602 should be modified from $substep < $upcontext['table_count'] to $substep **<=** $upcontext['table_count']  so it goes properly from 1 to 72 (assuming table_count is 72).

Make sense?

*Note $substep and similar logic is used in BackupDatabase() and serialize_to_JSON().   I haven't confirmed if they have the same issue or not.  Care must be taken not to break these other functions...*

**Comment by sbulen** [comment]
There are 3 issues described in this thread.   Here are my current observations on each:
1) Confusing status bar originally reported.
       - Open.   (EDIT - this is still current...)
2) User_likes not converted to utf8 originally reported.
       - Open.   Subscript issue.
3) Multiple files not converted to utf8 reported by me above.
       - Resolved.  I haven't seen this in the latest code.

Is this accurate?

**Comment by kipaslampu** [comment]
After succesfully upgrade the arabic word is still writing like Ã¢â‚¬Â.
thank u

**Comment by sbulen** [comment]
@kipaslampu - that is an unrelated issue...    This old issue is closed.  Please open a new one.  Thanks!
