### ISSUE TITLE
convert sendXMLDocument and getXMLDocument

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#3555]
To use $ajax()

**Comment by jdarwood007** [comment]
Could we add a sendJSONDocument and getJSONDocument support while we are at it?  It may be too late in the game to switch stuff from XML, but having the support there lets us move over and mod authors use it as needed.

**Comment by MissAllSunday** [comment]
Sure but it will be kinda redundant to add it.

Istead of only supporting json, a function can accept a datatype and httptype params:

```
function getServerDocument(sUrl, funcCallback, sDatatype, sType)
{
    var oCaller = this;
    var oMyDoc = $.ajax({
        type: sType,
        url: sUrl,
        cache: false,
        dataType: sDatatype,
        success: function(response) {
            if (typeof(funcCallback) != 'undefined')
            {
                funcCallback.call(oCaller, response);
            }
        },
    });

    return oMyDoc;
}
```

Which basically is just a wrapper for jQuery.ajax()  and I see little benefit in just adding a wrapper besides returning the jqXHR object for further manipulation.

It will be way more handy for mod authors to just use their own, I use my own calls to ajax() and made heavy use of its callbacks, something I wouldn't be able to do with this wrapper.

If you mean adding support on the server side then I would agree but then again a simple and generic "response" template with a single echo $context['response'] will do the trick. That or a function in Subs.php with some parameters.

A procedural and more generic version of https://github.com/MissAllSunday/Ohara/blob/master/src/Suki/Ohara.php#L640  should work.

**Comment by jdarwood007** [comment]
Whatever would be better for people.  We still have the XML format being used everywhere.  But providing the support so JSON could be used instead would be great for moving over to using JSON completely in future versions.  I mentioned names like that because its a format mod authors would be used to working with or if we have to do any fixups (such as urls) or similar.
