### ISSUE TITLE
subs.php error

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3575]
i have been informed that php version 5.4.16 has an issue.

Fatal error: Can't use function return value in write context in C:\wamp\www\github2.1\Sources\Subs.php on line 1278

Call Stack:
 0.0270 871424 1. {main}() C:\wamp\www\github2.1\upgrade.php:0
 0.1510 885224 2. loadEssentialData() C:\wamp\www\github2.1\upgrade.php:132

**Comment by Sesquipedalian** [comment]
Silly me. I forgot that PHP <5.5 only supports variables inside `empty()`.

**Comment by sicommnend** [comment]
Just came on to report this, went to install the latest and got the same error.

Haven't tested but how about using.
`if (!parse_url($url, PHP_URL_SCHEME))`

**Comment by Sesquipedalian** [comment]
I've already implemented a fix in commit da643bc, @sicommnend. Just waiting for the PR to be merged. :)

**Comment by sicommnend** [comment]
You can also condense that.
`if (($temp = parse_url($data, PHP_URL_SCHEME) == null || false))`
