### ISSUE TITLE
Installer doesn't work

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#358]
Fatal error, where it's trying to insert a row to {db_prefix}settings and can't because it doesn't exist.

See https://github.com/SimpleMachines/SMF2.1/pull/351 for more information.

(I should add, this was reported to us on wedge.org in the hope that we could answer their question.)

**Comment by Devilwillcry4you** [comment]
Tried installing with the fix above and still getting  the same error.
Table 'skinsn_smf.smf_settings' doesn't exist

**Comment by emanuele45** [comment]
Tested with both MySQL and SQLite.
Always completed the installation process.

Are you sure you removed the relevant code from install.php?

Just to be sure, download [this package](https://github.com/emanuele45/playpen/archive/install_fix.zip).

**Comment by Devilwillcry4you** [comment]
Thanks,  I got it working last night.

**Comment by colinschoen** [comment]
Ema, can this be merged soon as it is inhibiting anyone from installing the 2.1 repo?

**Comment by wsabransky** [comment]
Tested @emanuele45 's fix. No problems. Should be good to merge.

**Comment by Arantor** [comment]
Fix is confirmed as working as expected in all respects.

**Comment by illori** [comment]
@Oldiesmann can you close this it is fixed

**Comment by matthew-kerle** [comment]
As per Illori's request, closed!
