### ISSUE TITLE
Not Support In MariaDB ?

### ISSUE THREAD

**Issue by creativefull** [SimpleMachines/SMF#3583]
```
Critical Error!
The installer was unable to detect any database support in PHP. Please ask your host to ensure that PHP was compiled with the desired database, or that the proper extension is being loaded.
```

why ? i'm using archlinux
php -> 7.0.9
MariaDB -> 10.1.16

so i need mysql to run this application ?

**Comment by tinoest** [comment]
Can you provide the output of your phpinfo please? 

MariaDB is a drop in replacement for MySQL. 

So SMF should work. 

Just tested on a local VM works ok with;

mysql --version
mysql  Ver 15.1 Distrib 10.0.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by albertlast** [comment]
with 10.1.9-MariaDB no problem too.

**Comment by creativefull** [comment]
mysql  Ver 15.1 Distrib 10.1.16-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by albertlast** [comment]
i don't understand what you want tell us with that,
but your php need mysqli support,
because smf 2.1 support mysql and mysqli.
And php 7.x didn't support mysql_\* anymore.

**Comment by creativefull** [comment]
i don't know ,.. when i create a project with mysqli it's alright,

maybe i'm missing a configuration in smf ?

**Comment by tinoest** [comment]
No your not, MySQLi is the latest version of the MySQL libs. PHP7 doesn't support the old MySQL libs so it wouldn't work with them. 

If you want to use the older deprecated libraries then downgrade you php version.

**Comment by albertlast** [comment]
Maybe we should place a auto switch, so that smf 2.1 + php 7 + mysql > mysqli

---

Von: Martyn Brown notifications@github.com
Gesendet: 14.09.2016 7:55 AM
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] Not Support In MariaDB ? (#3583)

No your not, MySQLi is the latest version of the MySQL libs. PHP7 doesn't support the old MySQL libs so it wouldn't work with them.

If you want to use the older deprecated libraries then downgrade you php version.

##

**Comment by tinoest** [comment]
It should be removed from the install options. 

Although I'd hope people could read the docs on PHP's website.

**Comment by albertlast** [comment]
But this info is in configuration and below 7 is okay to use mysql

---

Von: Martyn Brown notifications@github.com
Gesendet: 14.09.2016 8:06 AM
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] Not Support In MariaDB ? (#3583)

It should be removed from the install options.

Although I'd hope people could read the docs on PHP's website.

##

**Comment by tinoest** [comment]
Sorry I meant on PHP7 it should. 

I'd even argue below that it should prioritise mysqli if it's available.

**Comment by creativefull** [comment]
so i must be use mysql ?

**Comment by tinoest** [comment]
No, you're not understanding the basics of PHP, please read the below two links.  

http://php.net/manual/en/mysqli.overview.php

http://markonphp.com/difference-mysql-mysqli/

**Comment by creativefull** [comment]
okay, I meant what should I do then... 
to run smf on php7 and mysqli ?

my phpinfo said that I already have mysqli support
![Mysqli support on phpinfo()](https://cloud.githubusercontent.com/assets/13174684/18509887/632a1500-7aa5-11e6-90ff-3c539bd15c98.png)

**Comment by tinoest** [comment]
You're not grasping the fact that MySQLi is the improved version of the MySQL libraries. It is the only MySQL library (other than PDO) available in PHP 7. 

I've provided links to confirm this, please read them.

**Comment by tinoest** [comment]
Can this be closed please?
