### ISSUE TITLE
Upgrade problem (2.1b2 to 2.1b3)

### ISSUE THREAD

**Issue by bobrenja** [SimpleMachines/SMF#3584]
NO upgrade (((
When the file is run upgrade.php
white page appears.

**Comment by bobrenja** [comment]
Fatal error: Can't use function return value in write context in **/Sources/Subs.php on line 1278

array(
                'tag' => 'flash',
                'type' => 'unparsed_commas_content',
                'test' => '\d+,\d+]',
                'content' => '<embed type="application/x-shockwave-flash" src="$1" width="$2" height="$3" play="true" loop="true" quality="high" AllowScriptAccess="never">',
                'validate' => function (&$tag, &$data, $disabled)
                {
                    if (isset($disabled['url']))
                        $tag['content'] = '$1';
                    if (empty(parse_url($data[0], PHP_URL_SCHEME)))
                        $data[0] = 'http://' . ltrim($data[0], ':/');
                },
                'disabled_content' => '<a href="$1" target="_blank" class="new_win">$1</a>',

```
    **if (empty(parse_url($data[0], PHP_URL_SCHEME)))**
                    $data[0] = 'http://' . ltrim($data[0], ':/');
```

**Comment by XinYenFon** [comment]
We are aware of the issue #3575. But do mind, we are not supporting partial upgrade so you should test the latest build upgrade from SMF 2.0.

**Comment by illori** [comment]
since #3575 is closed this should be closed as well.
