### ISSUE TITLE
'permission' => 'profile_other',

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3590]
this is the permission for hidden/showing the website section in the profile, i think the name should be more specific to what it actually will do. other is too generic.

**Comment by Oldiesmann** [comment]
That's probably leftover from the older versions of SMF when we didn't have all the fancy profile permissions that 2.1 has. Definitely something we can look into at least.

**Comment by Oldiesmann** [comment]
Working on this now. Since that's the only thing that permission is used for, renaming it is definitely an option. I just need to go through the upgrade and install later to make sure it's changed everywhere it's used.
