### ISSUE TITLE
bbc_code tfa too small

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3591]
when you are setting up tfa it uses the bbc_code class, this has a font size of .75em i think this is a bit too small for this area. maybe a different class should be used here instead of the bbc_code class?

![](http://i.imgur.com/UfMpJUQ.png)

**Comment by XinYenFon** [comment]
![screenshot-localhost 2016-09-26 19-18-07](https://cloud.githubusercontent.com/assets/1669995/18842532/fafdf8c0-841d-11e6-9c1c-0ccac3c87dcb.png)

**Comment by illori** [comment]
much better
