### ISSUE TITLE
tfa bypass

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3592]
enable tfa on an account. open a new browser [not the one you used to setup tfa] and log in with tfa with checking the box to stay logged in on the tfa page. logout, right after you logout click the login link, fill in your username and password and log in, you get an error message to wait 2 minutes to log in. click the back button... it takes you back to the forum index and you are logged in. IMO if you have not entered your tfa it should not log you or it should give you a different error message.

if you try another browser and attempt to log in, you should get prompted to enter your tfa but you dont. you get to the error page telling you to wait 2 minutes. when you try to click the back button you dont get redirected to the index page when you click back, you just go in a loop on the error page that you need to wait 2 minutes. even clicking on the home button ends me back on the same error page, so i cant even browse the forum as a guest. the URL gets changed to http://localhost:8080/github2.1/index.php?action=logintfa and even manually removing the action does not get me back to the normal board index.

tried the last part again, removed the action and i got prompted to enter the tfa... maybe this needs to be looked into further.

**Comment by Sesquipedalian** [comment]
This should definitely be fixed before RC1. Since I've been digging around in this part of the code lately, I may as well be the one to take this on.
