### ISSUE TITLE
Mentions not work ?

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3593]
How I get Mentions to work?
It's enabled, but I dont get any information if my name mentioned (like @name).
The @name is converted to [member=#]name[/member] but no Alert come up (this is also enabled)

**Comment by illori** [comment]
worked for me. sometimes there is a slight delay in receiving the notification. a page or 2+ refresh may be required to trigger the notification.

**Comment by PortaMx** [comment]
Thank you .. it was a bug in the cron.php  .. he not found my new cache routines (missing a require source .. meeh) .. but many thanks for your hint, so I found the problem.

**Comment by PortaMx** [comment]
As a tip from me .. if you edit a topic with a mention, this is shown as [member=#]name[/member] in the WYSIWYG editor .. thats ugly.
I add a small code is editor javascrript to change that back to @name and this is converted back to [member=#]name[/member] .... before the post is saved to the database.

Here the code for the jquery.sceditor.js
`
$.sceditor.plugins.bbcode.bbcode.set(
    'member', {
        html: function (element, attrs, content) {
            if (typeof attrs.defaultattr === "undefined" || attrs.defaultattr.length === 0)
                return content;

```
        return '@' + content;
    }
}
```

);
`

**Comment by PortaMx** [comment]
Well .. that looks good but don't work correctly.
Also if you edit a post with mentions, they is newly allerted.
So you must do more on this ;-)

A tip from me ..
In the Subs-Post check the old message body if they have mentions.
Then check the updated body for mentions.
Make a diff of both mentions and see if a new mention added.
If so, create the background task for the new mentioned member.

It's a little bit more complicated but mine code works fantastic and perfect ..

Hope this tips will help you ;-)

**Comment by PortaMx** [comment]
You found the solution? No ? Ok .. here comes :-)
All need changes in the Subs-Post .. **function modifyPost**

first change here:
`// using a custom search index, then lets get the old message so we can update our index as needed
        if (!empty($modSettings['search_custom_index_config']) || !empty($modSettings['enable_mentions']))
        {
            $request = $pmxcFunc['db_query']('', '
                SELECT body
                FROM {db_prefix}messages
                WHERE id_msg = {int:id_msg}',
                array(
                    'id_msg' => $msgOptions['id'],
                )
            );
            list ($msgOptions['old_body']) = $pmxcFunc['db_fetch_row']($request);
            $pmxcFunc['db_free_result']($request);
        }`

Second here:
`
    if (!empty($modSettings['enable_mentions']))
    {
        require_once($sourcedir . '/Mentions.php');

```
    $oldmentions = array();
    if (!empty($msgOptions['old_body']))
    {
        preg_match_all('/\[member\=([0-9]+)\]([^\[]*)\[\/member\]/U', $msgOptions['old_body'], $match);
        if(isset($match[1][0]))
        {
            foreach($match[1] as $i => $memID)
                $oldmentions[$memID] = array('id' => $memID, 'real_name' => $match[2][$i]);
        }
        if (empty($modSettings['search_custom_index_config']))
            unset($msgOptions['old_body']);
    }

    $mentions = Mentions::getMentionedMembers($msgOptions['body']);
    $messages_columns['body'] = $msgOptions['body'] = Mentions::getBody($msgOptions['body'], $mentions);
    $msgOptions['mentioned_members'] = $mentions;

    if (is_array($mentions) && is_array($oldmentions) && count(array_diff_key($mentions, $oldmentions)) > 0 && count($mentions) > count($oldmentions))
    {
        // Queue this for notification
        $msgOptions['mentioned_members'] = array_diff_key($mentions, $oldmentions);

        $pmxcFunc['db_insert']('',
            '{db_prefix}background_tasks',
            array('task_file' => 'string', 'task_class' => 'string', 'task_data' => 'string', 'claimed_time' => 'int'),
            array('$sourcedir/tasks/CreatePost-Notify.php', 'CreatePost_Notify_Background', json_encode(array(
                'msgOptions' => $msgOptions,
                'topicOptions' => $topicOptions,
                'posterOptions' => $posterOptions,
                'type' => 'edit',
            )), 0),
            array('id_task')
        );
    }
}
```

`

That is all ... ;-)

**Comment by MissAllSunday** [comment]
Double alert on editing is a different issue  please open a new issue for it. 

Jessica González, missallsunday.com

**Comment by PortaMx** [comment]
You can use the code above or leave it .. not my choice .. I give only tips for you ;-)

**Comment by MissAllSunday** [comment]
I think I'll pass,  can't really use your code as its always incomplete  
and has unique vars (I'm assuming from your fork), but thank you.

**Comment by PortaMx** [comment]
On more problems with mentions i found ..
If you quote a topic with mentions, the mentions in the quote are newly alerted ..
I think, this is not correct, true ?
Currently I code a fix for this ...

And the current code is not commited to github, but I can you get you the source file if this helps ...

**Comment by PortaMx** [comment]
Here comes the fix for mentions in qoutes ..

in the  function createPost araound line 1680 use this code:
`   if (!empty($modSettings['enable_mentions']))
    {
        // we have mentions in a quote?
        $oldmentions = $mentions = array();
        preg_match_all('/[quote[^]]_](._)[\/quote]/U', $msgOptions['body'], $match);
        if (isset($match[1]))
        {
            foreach($match[1] as $data)
            {
                $temp = Mentions::getMentionedMembers($data);
                if (is_array($temp))
                    $oldmentions = array_replace($oldmentions, $temp);
            }
        }
        $allmentions = Mentions::getMentionedMembers($msgOptions['body']);
        $mentions = array_diff_key($allmentions, $oldmentions);
        $msgOptions['mentioned_members'] = $mentions;

```
    if (!empty($oldmentions) || !empty($allmentions))
        $msgOptions['body'] = Mentions::getBody($msgOptions['body'], $allmentions);
}
```

`

Hope it helps ;-)

**Comment by PortaMx** [comment]
ahh .. i think what you mean .. this var ?   $pmxcFunc['db_insert']
it's the same as $smcFunc  and can simple replace ;-))

**Comment by PortaMx** [comment]
Here I attached the sub.post as zip .. so you can see what I have done with all the mentions ..
mentions in a quote will not alerted, outside will alerted.
if you modify a message, existing mentions will not alerted, only new mentions ..
Hope this helps you a little bit ;-)

[Subs-Post.zip](https://github.com/SimpleMachines/SMF2.1/files/498965/Subs-Post.zip)

**Comment by MissAllSunday** [comment]
Thanks, will take a look at them when I got some time.

**Comment by PortaMx** [comment]
Ok .. I have tested my code long time with all available options .. new topic, reply, qoute, qoute reply .. with and without new mentions .. all works as well ;-)
