### ISSUE TITLE
Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3598]
Is no longer displayed some pictures
Error Log
` admin
 Today at 08:16:11
 Type of error: General
2: Invalid argument supplied for foreach()  https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 3586

 admin
 Today at 08:16:11
 Type of error: General
2: array_reverse() expects parameter 1 to be array, null given  https://"""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 3586

 admin
 Today at 08:16:11
 Type of error: Undefined
8: Undefined index: template_layers https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 3586

 admin
 Today at 08:16:11
 Type of error: General
2: Invalid argument supplied for foreach()  https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 3461

 admin
 Today at 08:16:11
 Type of error: Undefined
8: Undefined index: template_layers https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 3461

 admin
 Today at 08:16:11
 Type of error: Undefined
8: Undefined index: session_id  https://"""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 4318

 admin
 Today at 08:16:11
 Type of error: Undefined
8: Undefined index: session_var https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 4318

 admin
 Today at 08:16:11
 Type of error: Undefined
8: Undefined index: id  https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 4100

 admin
 Today at 08:16:11
 Type of error: Undefined
8: Undefined index: id  https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 4100

 admin
 Today at 08:16:11
 Type of error: Undefined
8: Undefined index: id  https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 4091

 admin
 Today at 08:16:11
 Type of error: Undefined
8: Undefined index: is_guest    https://"""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 4086

 admin
 Today at 08:16:11
 Type of error: Undefined
8: Undefined index: can_mod https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 4067`

File as an attachment
[Subs.zip](https://github.com/SimpleMachines/SMF2.1/files/502193/Subs.zip)

**Comment by Oldiesmann** [comment]
This is for issues relating to 2.1. The errors you've posted here are relating to 2.0 and appear to be template-related issues. Please open a support topic in the 2.0.x Support board at http://www.simplemachines.org/community/index.php?board=147.0 for further assistance with this.

**Comment by Yariksat** [comment]
This error SMF 2.1
Somewhere I pointed out that this is a bug SMF 2.0 ?
