### ISSUE TITLE
Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3602]
I repeat once again.
This error SMF 2.1
Somewhere I pointed out that this is a bug SMF 2.0 ?
Why immediately close topic not having understood
if necessary will be the screenshots
Error Log
` admin
Today at 08:16:11
Type of error: General
2: Invalid argument supplied for foreach() https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 3586

admin
Today at 08:16:11
Type of error: General
2: array_reverse() expects parameter 1 to be array, null given https://"""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 3586

admin
Today at 08:16:11
Type of error: Undefined
8: Undefined index: template_layers https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 3586

admin
Today at 08:16:11
Type of error: General
2: Invalid argument supplied for foreach() https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 3461

admin
Today at 08:16:11
Type of error: Undefined
8: Undefined index: template_layers https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 3461

admin
Today at 08:16:11
Type of error: Undefined
8: Undefined index: session_id https://"""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 4318

admin
Today at 08:16:11
Type of error: Undefined
8: Undefined index: session_var https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 4318

admin
Today at 08:16:11
Type of error: Undefined
8: Undefined index: id https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 4100

admin
Today at 08:16:11
Type of error: Undefined
8: Undefined index: id https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 4100

admin
Today at 08:16:11
Type of error: Undefined
8: Undefined index: id https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 4091

admin
Today at 08:16:11
Type of error: Undefined
8: Undefined index: is_guest https://"""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 4086

admin
Today at 08:16:11
Type of error: Undefined
8: Undefined index: can_mod https://""""/index.php?action=dlattach;topic=105.0;attach=12606;image
File: /home/p2777/public_html/Sources/Subs.php
Line: 4067`

**Comment by MissAllSunday** [comment]
We need more details, does your attachment exists?

Subs::4067 takes me to a different part of the parse_bbc function, please always make sure to test on the most recent branch to date.

Also, please do note that this repo concerns 2.1 and 2.1 only, if you are reporting an error for 2.0 please use the [support forum](http://simplemachines.org/community/index.php) instead.

**Comment by Yariksat** [comment]
This error SMF 2.1
Does not display a thumbnail attachments, if you press the this attachment is opened normally
On one such attachment 11 errors.
If you edit the message to download and upload a new attachment is then displayed normally miniature

**Comment by MissAllSunday** [comment]
Does the thumbnail physically exists on your server? can you please update your forum to the latest current commit on the release-2.1 branch.

**Comment by Yariksat** [comment]
I SMF 2.1 Beta 3
Attachments physically exist on the server and can be downloaded
Or miniatures are stored separately?

**Comment by Yariksat** [comment]
Error fixed the last update
