### ISSUE TITLE
Not sure if this is a known issue?

### ISSUE THREAD

**Issue by bperry921** [SimpleMachines/SMF#3605]
Last several versions I get this error...
![smfhelp006](https://cloud.githubusercontent.com/assets/4441576/19070547/dedf0314-89f9-11e6-9891-9e5be69567cc.png)

**Comment by bperry921** [comment]
Okay, sorta figured something out... had a copy of cron.php located both in the root directory and in Sources, if I delete the one in the root I don't get an error... but is cron still going to function as expected located in Sources directory?

**Comment by MissAllSunday** [comment]
SMF expects cron.php to be located on root, there shouldn't be two cron scritps, just one, the one located on your root dir,

**Comment by bperry921** [comment]
At any rate, its a problem I could use some pointers on tracking down, it should not be getting this error...

**Comment by MissAllSunday** [comment]
Well, we need more info to be able to help you.

Whats your php version?  what SMF 2.1 are you using? who creates the topic? on a hidden board? how do you run your cron tasks?

**Comment by MissAllSunday** [comment]
Closing this one due to lack of details/info.  No other users had reported the same or a similar issue which leads me to believe this is an isolated case.
