### ISSUE TITLE
Large Resolution Issues

### ISSUE THREAD

**Issue by matthew-kerle** [SimpleMachines/SMF#3606]
Some of our responsiveness seems to go away when you're on a really large monitor...things are aligned way to the left when they should be to the right.

**Comment by XinYenFon** [comment]
Do you have info ? (like 24'' or 27'' - 1920x1080 or UHD etc...) or any screenshot ? I never had chance to try SMF 2.1 in big screens.

**Comment by matthew-kerle** [comment]
I'm going to take care of them, specifically with boards on the boardindex and messageindex actions, and also in topics there are some.
