### ISSUE TITLE
Searching for "Recent Posts"

### ISSUE THREAD

**Issue by matthew-kerle** [SimpleMachines/SMF#3608]
I couldn't get a search result for "Recent Post" or "Recent Posts" trying to find the setting in Current Theme for how many posts to show on the boardindex. It generates undefined errors too.
![screen shot 2016-10-04 at 11 43 51](https://cloud.githubusercontent.com/assets/648400/19087744/0e2d1aba-8a28-11e6-9864-841dcbcbbd45.png)

**Comment by frandominguezl** [comment]
- This issue is also present in SMF 2.0.x
