### ISSUE TITLE
Replace apc* cache with acpu*

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3613]
Just my note or anyone is able to do this.  APC was removed in PHP 5.6 and is not maintained or supported anymore.  However APCu is maintained and supported even in PHP 7.1.  APCu is APC without the opcache.  All functions I can find seem to be directly the same.  It should be safe to do a PR and replace all APC cache functions with APCu and update text strings as needed.

Should also migrate the modSetting from apc to apcu if its set.

**Comment by Oldiesmann** [comment]
I added support for apcu not long ago, but haven't removed APC at all. I'll look into that when I get a chance.

**Comment by jdarwood007** [comment]
Well we can leave it if we wish.  I think the better solution is to remove and change the setting to apcu.  apc won't even be working on any install newer than 5.6, which is the main market share for PHP now.

**Comment by live627** [comment]
Related to #3703
