### ISSUE TITLE
Moderation Log IP m���

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3614]
Last update from here
Passed properly without errors
1.Moderation Log IP look like  m���
![41](https://cloud.githubusercontent.com/assets/17574854/19274557/21ee9fae-8fd9-11e6-82fb-be360b55d488.jpg)
 I launch Administration Center ►  Forum Maintenance ►  Database Convert HTML-entities to UTF-8 characters and the I get
![42](https://cloud.githubusercontent.com/assets/17574854/19274709/add34042-8fd9-11e6-90ab-646057389d5f.png)
Type of error: Database
Database Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''ban_groups'' at line 2
2.When downloading a file name in Cyrillic trims in the first word of the title

**Comment by albertlast** [comment]
Did you use the newest github version?
try to run this sql comand:
select *, INET6_ATON(ip) from smf_log_erros
ordber by id desc
limit 100

Put the output somewhere so that we can look into.

**Comment by Yariksat** [comment]
I Do SELECT 100, INET6_ATON(ip) FROM `yariksat_forum_log_errors`
![45](https://cloud.githubusercontent.com/assets/17574854/19282259/37a79f86-8ff6-11e6-94ac-244315367679.jpg)

**Comment by Yariksat** [comment]
![47](https://cloud.githubusercontent.com/assets/17574854/19283077/48f17142-8ff9-11e6-80aa-407b732ead93.jpg)

**Comment by albertlast** [comment]
You dont use my command:
select *, INET6_ATON(ip) from yariksat_forum_log_errors
order by id desc
limit 100

okay you tryiot before but your mysql version is to old fpor this command you need 5.6+
alternative solution give me the output without the function:
select \* from yariksat_forum_log_errors
order by id desc
limit 100

**Comment by Yariksat** [comment]
Sorry not the right screenshot loaded
![48](https://cloud.githubusercontent.com/assets/17574854/19283986/ba47abd8-8ffc-11e6-9f4a-4843630590d5.jpg)

**Comment by albertlast** [comment]
the "order by" was writen wrong by my side

**Comment by Yariksat** [comment]
Again, the error can somehow access provide?
![49](https://cloud.githubusercontent.com/assets/17574854/19284266/e166f6e6-8ffd-11e6-842e-6d9bd4b33eef.png)

**Comment by albertlast** [comment]
use the alternativ sql without the function:
select \* from yariksat_forum_log_errors
order by id desc
limit 100

**Comment by Yariksat** [comment]
![default](https://cloud.githubusercontent.com/assets/17574854/19284500/d08bb522-8ffe-11e6-9773-7d8587dbf402.png)

**Comment by albertlast** [comment]
select \* from yariksat_forum_log_errors
order by id_error desc
limit 100

**Comment by Yariksat** [comment]
The request has passed
What data are needed?
Looks like IP ?

**Comment by albertlast** [comment]
i want see all col

**Comment by Yariksat** [comment]
![53](https://cloud.githubusercontent.com/assets/17574854/19285050/3d593f24-9001-11e6-9fe8-ace353bf92d8.jpg)

**Comment by albertlast** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/1782906/19285114/2de05a12-8ff9-11e6-85fa-925109e6ee2a.png)
looks fine
so this issue should be only a display error maybe @Antes can help

**Comment by Yariksat** [comment]
We are waiting for its in this thread?
New does not necessary to open?
This mapping is only in logfiles moderation and administration.
The remaining logs IP looks fine

**Comment by Yariksat** [comment]
As I understand no solution to this problem at the moment ?

**Comment by albertlast** [comment]
looks like only visual issue and this mean someone of smf team needs to fix this @MissAllSunday

**Comment by Yariksat** [comment]
I currently use on my forum the latest version 2.1. Now the everything is fine except of this error. Well and still downloading in Cyrillic attachments not fixed until the end.

**Comment by Yariksat** [comment]
@MissAllSunday please solve this problem

**Comment by illori** [comment]
the moderation log, is logged in the log_actions table, not log_errors. maybe if the above query was on the correct table it may help determine what is going on. i dont have my 2.1 install easily accessible on the internet so all my ip address in that table register as 7f000001. in my profile though it has my correct ip address, 127.0.0.1.

if i look at the administration log in the admin panel it is also not registering my ip address, maybe related to this as it takes the information from the same table from what i can see.

when my script [shows as a guest doing the upgrade] upgrades the forum, it has the ip address in the database as 3132372e302e302e31 when i do admin tasks in the forum it has 7f000001

**Comment by albertlast** [comment]
@Yariksat use this command to share the information:
select id_action,ip from yariksat_forum_log_actions order by id_action desc limit 100;

**Comment by Yariksat** [comment]
Here the problem and there is most likely
Displaying clearly abnormal
![62](https://cloud.githubusercontent.com/assets/17574854/19415197/19d63c14-9371-11e6-890d-54a39bdb6e4a.jpg)
being written with errors Administration Log & Moderation Log

**Comment by albertlast** [comment]
The pr #3627 should fix this issue.

**Comment by Yariksat** [comment]
Magnificently
I close the ticket

**Comment by illori** [comment]
please dont close issues until they are merged. this makes sure that the PR actually gets merged and it fixes the issue.
