### ISSUE TITLE
Web Links

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3616]
Now some words are parsed as links
![44](https://cloud.githubusercontent.com/assets/17574854/19279068/5d370e8e-8fe8-11e6-9974-7a7660ef05bb.jpg)

**Comment by illori** [comment]
@Sesquipedalian did this get a PR made for it? since yariksat has closed it, that does not mean it was actually merged into 2.1.

**Comment by Sesquipedalian** [comment]
Yes. #3618

**Comment by Sesquipedalian** [comment]
This issue can remain closed.
