### ISSUE TITLE
PHP Parse error:  syntax error, unexpected ','

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3619]
PHP Parse error:  syntax error, unexpected ',' in /home/p2777/public_html/Sources/Calendar.php on line 204
`$context['calendar_buttons']['post_event'] = array('text' => 'calendar_post_event', 'image' => 'calendarpe.png', 'url' => $scripturl . '?action=calendar;sa=post;month=' . $context['current_month'] . ';year=' . $context['current_year'] . ';' . $context['session_var'] . '=' . $context['session_id']),
`
Right
`$context['calendar_buttons']['post_event'] = array('text' => 'calendar_post_event', 'image' => 'calendarpe.png', 'url' => $scripturl . '?action=calendar;sa=post;month=' . $context['current_month'] . ';year=' . $context['current_year'] . ';' . $context['session_var'] . '=' . $context['session_id'],
`

**Comment by wintstar** [comment]
open Sources/Calendar.php line 204
change
`$context['calendar_buttons']['post_event'] = array('text' => 'calendar_post_event', 'image' => 'calendarpe.png', 'url' => $scripturl . '?action=calendar;sa=post;month=' . $context['current_month'] . ';year=' . $context['current_year'] . ';' . $context['session_var'] . '=' . $context['session_id']),`
to
`$context['calendar_buttons']['post_event'] = array('text' => 'calendar_post_event', 'image' => 'calendarpe.png', 'url' => $scripturl . '?action=calendar;sa=post;month=' . $context['current_month'] . ';year=' . $context['current_year'] . ';' . $context['session_var'] . '=' . $context['session_id'],`

**Comment by Yariksat** [comment]
Please add this fix

**Comment by illori** [comment]
@d3vcho did you create a PR for this fix? it seems this got closed without a PR being created or merged that i can see.

**Comment by frandominguezl** [comment]
@illori Yes, this is the merged PR https://github.com/SimpleMachines/SMF2.1/pull/3623
