### ISSUE TITLE
Inserting smileys in a message

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3624]
When you insert attached image to the body of the message is not displayed after the smilies
![56](https://cloud.githubusercontent.com/assets/17574854/19361819/cfe6486e-918c-11e6-8acd-c1b8223a08bc.jpg)
![57](https://cloud.githubusercontent.com/assets/17574854/19361824/d5c7c528-918c-11e6-9d47-ff1e49dc1fc7.jpg)

**Comment by frandominguezl** [comment]
I think it's not supposed to display after the smilies or whatever in the body. When you click that button, you insert the attachment into the body to view it and then at the end of the message there's again the attachment.

I tested it, and this is the result:
![16bd09dd75575d3ce958ae9ba3e2bf41](https://cloud.githubusercontent.com/assets/10365222/19393798/8c2251ae-9236-11e6-96be-e5da71d09f31.png)

For me it's the normal behaviour. Maybe I'm wrong.

**Comment by Yariksat** [comment]
I turned off a mapping of the inserted images from below.
I do a description of something and the I interpose lots of images in the text, after these images there is a text in which there smileys are not displayed. It is is ugly at least.
In the screenshot I seethe same does not display 4 and 5 smiley

**Comment by frandominguezl** [comment]
Oh, I misunderstood you. My bad. No, it's not its normal behaviour and should be fixed.

**Comment by Sesquipedalian** [comment]
Thanks for this report, @Yariksat. I will take a look at this soon (unless someone beats me to it).

**Comment by Yariksat** [comment]
Thank you I will wait for the fix

**Comment by Yariksat** [comment]
Please have a solution to this problem?

**Comment by frandominguezl** [comment]
Please be patient. We're all volunteers here. I'm sure this will get a fix, but don't know when. Just wait, please :)

**Comment by Sesquipedalian** [comment]
Also, remember that this is beta software, @Yariksat. SMF 2.1 is **NOT** ready for use in production. That means you should not use it for a live website. If you want forum software that is stable, supported, and bug-free, you should use SMF 2.0.x, not the 2.1 betas.
