### ISSUE TITLE
How can i upgrade to Beta 3 from Beta 2 - SMF 2.1

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#3625]
Hello Developers! How can I upgrade from beta 2 to beta 3? There is no upgrade directory in the download package. I already use 2.1 Beta 2 and would like to upgrade.

Thanks in advance. Also I would like to make a fork of this repos  :smile:

**Comment by XinYenFon** [comment]
There is not partial upgrade option for beta versions yet. You can diff the upgrade files and apply to your site.

You can use "Fork" button on top of the page.

**Comment by albertlast** [comment]
the hard part is the inser the database changes they need to done manuelly

**Comment by Sesquipedalian** [comment]
Updating the PHP code is a simple matter of using `git pull` (assuming you have a git repository set up already).

Upgrading the database, however, is trickier, as @albertlast noted. Your best bet would be to use `diff`, as @Antes suggested already, to see exactly what has changed in the upgrade files compared to the version you last installed (Beta 2, in this case). Once you have that info, you can manually execute the necessary SQL commands using phpMyAdmin.

If that all sounds like gobbledegook to you, then the simple answer is that automated upgrades between beta versions are not supported, so if you want to try out the latest beta, you should do it as a fresh install.

**Comment by Oldiesmann** [comment]
The upgrade files for the GitHub downloads are in the "other" folder - copy them to the main directory and run upgrade.php like usual

**Comment by Sesquipedalian** [comment]
I thought those were for upgrading from 2.0, not from am earlier version of 2.1. Won't some of the upgrade instructions cause issues if executed against a setup that is already at a version of 2.1, @Oldiesmann?

**Comment by jdarwood007** [comment]
Prior to git, the upgrade scripts are supposed to be built to handle being ran multiple times either by checking if certain modSettings exist or checking if something is already set (such as a column existing).  But during development of a specific version (such as 2.1 Beta 3) it is possible to create broken upgrades.  But because prior to git the development was closed, the devs usually worked with team members that had broken installs (although rarely occurred).

The change to git has changed that though.

**Comment by Oldiesmann** [comment]
It shouldn't cause issues if run against an existing 2.1 install. I've done that many times.

**Comment by Sesquipedalian** [comment]
> It shouldn't cause issues if run against an existing 2.1 install. I've done that many times.

Cool. Thanks, @Oldiesmann.

So, @AlexL777, it sounds like a working process to upgrade from Beta 2 to Beta 3 would go like this:
1. Download the latest set of complete PHP files for SMF 2.1. If you use `git` you can just clone the repository by the usual means. If not, you can simply download the zip archive from https://github.com/SimpleMachines/SMF2.1.
2. On your web server, replace your existing Beta 2 files with the new Beta 3 files.
3. Copy the various `upgrade` files from the `other` folder to the root SMF folder.
4. Go to `http://www.example.com/forum/upgrade.php` to initiate the upgrade process. (Obviously, replace `http//www.example.com/forum` with the correct domain and path for your SMF 2.1 installation.)
5. Follow the prompts.
6. Enjoy a nice beverage of your own choosing.
