### ISSUE TITLE
ShowAttachments.php

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3628]
This chunk of code is now working in the Show Attachments.php
`// Update the download counter (unless it's a thumbnail).
    if ($file['attachment_type'] != 3 && empty($showThumb)){
        $smcFunc['db_query']('attach_download_increase', '
            UPDATE LOW_PRIORITY {db_prefix}attachments
            SET downloads = downloads + 1
            WHERE id_attach = {int:id_attach}',
            array(
                'id_attach' => $attachId,
            )
        );
`
And that same chunk of code is in Display.php on line 1565. Forgot your to remove?
And still there is in both files
// On some of the less-bright hosts, readfile() is disabled.  It's just a faster, more byte safe, version of what's in the if.

**Comment by MissAllSunday** [comment]
Its there for legacy reasons only, it doesn't affect your installation.
