### ISSUE TITLE
You have an error in your SQL syntax

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3631]
Convert HTML-entities to UTF-8 characters
![63](https://cloud.githubusercontent.com/assets/17574854/19419158/31c41ddc-93da-11e6-996b-196cbe968c2b.jpg)

**Comment by albertlast** [comment]
Can you please got in the file ManageMaintenance.php in the line 569 and replace
FROM {db_prefix}{string:cur_table}',
with
FROM {db_prefix}{identifier:cur_table}',

it could happen that the error raised again but in a different line.

**Comment by Yariksat** [comment]
Changed, error remained is the same

**Comment by albertlast** [comment]
same line?

**Comment by Yariksat** [comment]
Yes
Line: 573
 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`ban_groups`' at line 2
SHOW FULL COLUMNS
FROM yariksat_forum_`ban_groups`

**Comment by albertlast** [comment]
When you replace this with:
FROM {db_prefix}{raw:cur_table}',
any change?

**Comment by Yariksat** [comment]
Error has changed
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''ban_groups'' at line 2
/home/p2777/public_html/Sources/ManageMaintenance.php
Line: 585
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''ban_groups'' at line 2
SHOW KEYS
FROM yariksat_forum_'ban_groups'

**Comment by albertlast** [comment]
yeah the same error is in line 581 and 606 replace the code with 
FROM {db_prefix}{raw:cur_table}',

please give me feedback if this fix all issue.

**Comment by Yariksat** [comment]
I had already guessed and the did it
Yes, it solves the problem
