### ISSUE TITLE
Topic to the a vote

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3634]
When entering into such theme in error logs
Undefined index: can_remove_poll
/home/p2777/public_html/Sources/Display.php
Line: 804

**Comment by colinschoen** [comment]
Can you give a more specific description and steps so we can reproduce this.

**Comment by Yariksat** [comment]
The topic in this thread have a poll
Just view this topic in error logs

**Comment by illori** [comment]
if you look in Display.php it has all the other poll related context variables defined elsewhere looks like starting around line 716, but can_remove_poll is not defined anywhere else hence the error.

i am guessing we need to add something like 

```
$context['can_remove_poll'] &= $modSettings['pollMode'] == '1' && $topicinfo['id_poll'] > 0;
```

somewhere in Display.php

this code is from SMF 2.0 and not found in SMF 2.1.

**Comment by frandominguezl** [comment]
@illori can_remove_poll is defined in line 1106, but called twice in lines 804 and 1134, so array should be called before line 804

**Comment by illori** [comment]
1106 not the correct definition for can_remove_poll, it has to be defined in $context. if you look starting on line 787 it defines what is then used on line 804, this is where $context['can_remove_poll'] has be defined
