### ISSUE TITLE
inet_ntop(): Invalid in_addr value

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3635]
Warning
: inet_ntop(): Invalid in_addr value in
D:\wamp\www\github2.1\Sources\Subs.php
on line
5052

this is related to the administration log with mysql.

@albertlast seems related to your change in #3627 this error did not show up before that change.

there is also 

Json decode error: Syntax error, malformed JSON
http://localhost:8080/github2.1/index.php?action=admin;area=logs;sa=adminlog;fbf085e64=ccfbcfb72688ae1abb0b821225ca95de
File: D:/wamp/www/github2.1/Sources/Modlog.php
Line: 402

**Comment by albertlast** [comment]
in my eyes is this a convertion error
that some data are not convertert to varbinary.

Are this entry fresh or old data?

**Comment by Yariksat** [comment]
index.php?action=who
![65](https://cloud.githubusercontent.com/assets/17574854/19451944/92a2447a-94b7-11e6-8304-17a3eb9045ec.png)
2: inet_ntop(): Invalid in_addr value
Sources\Subs.php
on line 5052
$ip_address = inet_ntop($bin);

**Comment by albertlast** [comment]
need more information subs 5052 is the function but i need the location where function is caled,
i need the screen in which you are
maybe would be important to be able to read the text on right side to understand from where the error came.

would recommand to create own issue.

**Comment by illori** [comment]
the data is not new data. this is the admin log in the admin panel. same area as the error log. cleared the admin log... now the error has gone away. 
i ran my upgrade script and the error has returned, so it does occur with new data and not just old. anything else you require?

**Comment by albertlast** [comment]
I believe that this is an error from the upgrade script..
can you please give me the dump of your old and new admin log?

**Comment by illori** [comment]
Seems like only my script for updating that runs in cli seems to generate
the error. It is new data as I cleared the admin logs.

**Comment by Yariksat** [comment]
I had not realized what it was
Clean the cache and is no longer observe of this problem, everything is fine

**Comment by albertlast** [comment]
looks like that everything is fine,
so please close the issue

**Comment by illori** [comment]
everything is not fine. i am still getting this error. try running upgrade.php via CLI and you should see the errors show up in the admin log.

**Comment by albertlast** [comment]
i'm not able to test the upgrade process,
so i see nothing.

**Comment by illori** [comment]
Clearing the cache does not fix my issue. It seems to only happen if an
action that would get logged happens by a guest. Like the upgrade script
being run by cli.

On Oct 20, 2016 7:40 AM, "Yariksat" notifications@github.com wrote:

I had not realized what it was
Clean the cache and is no longer observe of this problem, everything is fine

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/SimpleMachines/SMF2.1/issues/3635#issuecomment-254538946,
or mute the thread

**Comment by albertlast** [comment]
it's would be mutch helpfull when you try to finde the dataset how create the error,
or create a dump and let me looking for that.

When the dataset is found we can look from where this came.

**Comment by illori** [comment]
this is the row that i believe is causing the error.
![](http://i.imgur.com/2NWE5FD.png)

i know what is causing the error, running the upgrade script from CLI that makes it show as a guest entry.

**Comment by albertlast** [comment]
Please add the change from pr https://github.com/SimpleMachines/SMF2.1/pull/3642
and let me know if this fix the problem

**Comment by illori** [comment]
that looks to have fixed it.

**Comment by illori** [comment]
it does require to clear out the log first to get rid of the old errors that will still cause the errors to occur.

**Comment by albertlast** [comment]
sure or delete the entry which is wrong.
