### ISSUE TITLE
Actions with messages

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3637]
I separate the messages in topic.
The topic has been successful is divided, in the logs
![64](https://cloud.githubusercontent.com/assets/17574854/19447466/4cdb5de8-94a6-11e6-9737-ee0dce70087f.png)
Unable to load the 'split' template.
This occurs only when the to separate selected messages.
Messages do not separate and the have to to refresh the page to see a which messages are separated... At this time, and there is an error.
This page contains the following errors:

error on line 71 at column 8: Opening and ending tag mismatch: link line 0 and head
Below is a rendering of the page up to the first error.
img.avatar { max-width: 100px; max-height: 100px; } var smf_theme_url = "https://yarik-sat.ru/Themes/default"; var smf_default_theme_url = "https://yarik-sat.ru/Themes/default"; var smf_images_url = "https://yarik-sat.ru/Themes/default/images"; var smf_smileys_url = "https://yarik-sat.ru/Smileys"; var smf_scripturl = "https://yarik-sat.ru/index.php"; var smf_iso_case_folding = false; var smf_charset = "UTF-8"; var smf_session_id = "48b6d07755ec133676691b6bd4ec1b90"; var smf_session_var = "d7e101d7cb"; var smf_member_id = 1; var ajax_notification_text = 'Загружается...'; var help_popup_heading_text = 'Подсказка'; var new_alert_title = "YARIK-SAT"; var alert_timeout = 10000; var smf_you_sure ='Уверены?'; Разделить тему - Отделить выделенные сообщения.

**Comment by Yariksat** [comment]
Can still certain data are needed?

**Comment by MissAllSunday** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/3658
