### ISSUE TITLE
PHP:  7.1

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3643]
![69](https://cloud.githubusercontent.com/assets/17574854/19616881/6d33926a-9828-11e6-9f03-aa180bd6e40e.jpg)

**Comment by albertlast** [comment]
just for notize: ch_buffer is a function of ACcache

**Comment by Yariksat** [comment]
That's for me ?

**Comment by albertlast** [comment]
mostly for the person how feald responsible for this topic, but you could update the headline

**Comment by Yariksat** [comment]
What was the name more preferable topics?

**Comment by Oldiesmann** [comment]
What's ACCache? I can't find any references to it or ch_buffer. I don't think there's much we can do about this either way.
