### ISSUE TITLE
Fatal error can occur on malformed json data

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3646]
1. reloadSettings() when loading is pulling in attachmentUploadDir modSetting.
2. attachmentUploadDir has corrupted json data.
3. smf_json_decode() will launch a log_error because of a json error.
4. log_error when trying to build the query_string will call for $smcFunc['htmlspecialchars']
5. Because reloadSettings() failed early on, we did not get a chance to setup $smcFunc['htmlspecialchars'].
6. Fatal php error occurs.

I found this and tracked it back while messing around with repair_settings.php for 2.1 and it created a bad data in attachmentUploadDir.

The only work arounds I can see is either in smf_json_decode() we bail out or in log_error we allow a fallback to php's htmlspecialchars.

**Comment by albertlast** [comment]
Did we need the attachmentUploadDir to build up the htmlspecialchars function?
Otherwise we could reorder the loading to start earlier with html... and then with the attachment... thing.

**Comment by jdarwood007** [comment]
Its built that early so we can cache the modSettings and we use some of the modSettings lit looks like to build smcFunc.

**Comment by PortaMx** [comment]
As a notice from me ..
The caching in SMF is soo bad .. so I think this need a rewrite.
And for caching always use json as object and handle errors local in the  cache, so you can simple return null if a error occurs and c!ear the bad cache.
I do it so and that works perfectly​ 😊
