### ISSUE TITLE
view who's online

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3648]
as seen in #3626 maybe we should change the text of this permission? we see who's online in the info center as well as the who's online page. maybe add to the text that it is the "page" so that clarifies what is being granted?

**Comment by frandominguezl** [comment]
It is clarified in the interrogation, but wouldn't hurt to add "page" to that text. That way we ensure users won't be misled.

**Comment by illori** [comment]
exactly. we should not assume that users read the help text for everything. although they should.

**Comment by XinYenFon** [comment]
then remove help texts and introduce smalltexts which explains it. Redundant.
