### ISSUE TITLE
Plural Bug in Index

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#3650]
Last Pull request => https://github.com/SimpleMachines/SMF2.1/pull/3642

For the German translation there is a problem with the plural. 

```
$txt['posts'] = 'Posts'; = $txt['posts'] = 'Beiträge';
$txt['redirects'] = 'Redericts'; = $txt['redirects'] = 'Weiterleitungen';
$txt['board_topics'] = 'Topics'; = $txt['board_topics'] = 'Themen';
```

The simplest solution would be to set the text before the total number.
Now:
![plural_index-before](https://cloud.githubusercontent.com/assets/2753863/19628637/ff6b91ce-9962-11e6-9e49-d0dff8d3a3d9.JPG)

Simple solution:
![plural_index-after](https://cloud.githubusercontent.com/assets/2753863/19628643/0e4bd5f0-9963-11e6-9b45-54680828d7f9.JPG)

**Comment by XinYenFon** [comment]
This singular plural thing discussed internally and publicly in lots of places. I think its okay to be tracked under one issue #2020
