### ISSUE TITLE
Language string $txt['total'] = 'Total';

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#3651]
The language string $txt['total'] = 'Total'; has no more use in 2.1 *. 
The last use was in 2.0.12:
Profile.template.php line 2780
`(', $txt['total'], ': <span id="karmaTotal">', ($context['member']['karma']['good'] - $context['member']['karma']['bad']), '</span>)`

index.english.php => https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/languages/index.english.php#L92

**Comment by XinYenFon** [comment]
I think those are too generic, better to keep them in software. Not saying to keep "compatibility" but its too generic and can be easily used by different modifications which may cause errors to users.

Same applies to #3652

**Comment by wintstar** [comment]
I think this is not a good solution. Language strings, if not available, should be supplied by the modification.

**Comment by colinschoen** [comment]
I tend to agree. We should only be keeping language strings that are used by the core product.

**Comment by wintstar** [comment]
moved to https://github.com/SimpleMachines/SMF2.1/issues/3713

**Comment by wintstar** [comment]
I have already done it for more than 3 weeks. So far I have received no answer. http://www.simplemachines.org/community/index.php?topic=258872.msg3899150#msg3899150
