### ISSUE TITLE
Edits Stuff

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3657]
Made changes as described here - the https://github.com/SimpleMachines/SMF2.1/commit/fb3fc8cd345e171e445cc3dd1378fdf6d9855e3d
After a quick editing after saving the message looks like this
That's if the text is typed in Cyrillic, English keyboard layout if all is normal. Such changes result in Themes / default / scripts / topic.js
![70](https://cloud.githubusercontent.com/assets/17574854/19730381/b7c0307c-9ba2-11e6-9037-c2537e21c90b.png)

**Comment by Yariksat** [comment]
Did not understand, now everything is working, probably there was something to the server
But remaining Undefined index: modify reason
`:                  'modified' => array(
2902:                       'time' => isset($msgOptions['modify_time']) ? timeformat($msgOptions['modify_time']) : '',
2903:                       'timestamp' => isset($msgOptions['modify_time']) ? forum_time(true, $msgOptions['modify_time']) : 0,
2904:                       'name' => isset($msgOptions['modify_time']) ? $msgOptions['modify_name'] : '',
==>2905:                        'reason' => $msgOptions['modify_reason'],
2906:                   )`
When I correct my message

**Comment by Yariksat** [comment]
On mobile devices with fast editing breaks down as text
The error makes it
`var i, x = new Array(),
        oCaller = this,
        formData = {
            subject : document.forms.quickModForm['subject'].value.replace(/&#/g, "&#38;#").php_to8bit(),
            message : document.forms.quickModForm['message'].value.replace(/&#/g, "&#38;#").php_to8bit(),
            topic : parseInt(document.forms.quickModForm.elements['topic'].value),
            msg : parseInt(document.forms.quickModForm.elements['msg'].value),
            modify_reason : document.forms.quickModForm.elements['modify_reason'].value.replace(/&#/g, "&#38;#").php_to8bit()
        };

```
// Send in the XMLhttp request and let's hope for the best.
ajax_indicator(true);

sendXMLDocument.call(this, smf_prepareScriptUrl(this.opt.sScriptUrl) + "action=jsmodify;topic=" + this.opt.iTopicId + ";" + smf_session_var + "=" + smf_session_id + ";xml", formData, this.onModifyDone);

return false;`
```

**Comment by MissAllSunday** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/3682
