### ISSUE TITLE
Proxy IP in tables

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#3659]
Hello,

I've been using 2.1 on a live server behind proxy for a while now. I wanted to ask what is the plan regarding ip columns in tables like messages or log_errors etc etc

Right now instead of the user IP, the server proxy IP is getting stored in those tables. Shall I go ahead and rename the insert ip from ip to ip2?

**Comment by jdarwood007** [comment]
What is set in Server Settings -> Security for the Proxy settings?

**Comment by asmith20002** [comment]
HTTP_X_FORWARDED_FOR and the IP of the proxy server.

Currently the IP of the proxy server is getting stored in member_ip column and member_ip2 is storing the real IP of the user.

But messages and log_errors are using the member_ip column, so they're getting filled with the proxy IP.

**Comment by jdarwood007** [comment]
That is done on purpose.  If you are using this, the ip2 is the ban check ip incase of proxies.  If your using a true reverse proxy on your server, your backend should be configured to replace the frontend/reverse proxy server ip with the clients ip.

**Comment by asmith20002** [comment]
I'm sorry I'm not that familiar with this concept. What is a "true" reverse proxy? I'm hiding behind proxy as a DDOS protection.

If my backend would be configured to replace, so why all the hassle with the proxy settings in admin menu?

**Comment by albertlast** [comment]
can we close this issue?

**Comment by asmith20002** [comment]
If one doesn't configure his server and only use the proxy settings in current code, it will just fill the database with the proxy server ip address. For example all ip addresses in messages table becomes the server ip which makes functions that handle ip obsolete.

**Comment by jdarwood007** [comment]
As I said, that is done that way as a proxy server is still handling your traffic and passing through a IP.  If configuration is not done properly, a proxy server could send false IP information to you.

If you are using a proper reverse proxy configuration, your front end (reverse proxy) and backend (server) would handle this without the application (SMF) even knowing about it.

**Comment by albertlast** [comment]
Then close this issue please @Sesquipedalian @colinschoen
