### ISSUE TITLE
Link in language string $txt['spider_settings_desc'] wrong 

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#3660]
The link in $txt['spider_settings_desc']  linked to admin;area=logs;sa=pruning.  
Lock into ManageSearchEngines.php Line 85
`	$context['settings_message'] = '<span class="smalltext">' . sprintf($txt['spider_settings_desc'], $scripturl . '?action=admin;area=logs;sa=pruning;' . $context['session_var'] . '=' . $context['session_id']) . '</span>';`
Correct would be my opinion action=admin;area=logs;sa=settings

**Comment by XinYenFon** [comment]
`...Note, if you wish to enable automatic pruning of the hit logs you can set this up <a href="%1$s">here</a>';`

I think it redirects to right (and proper place).

**Comment by wintstar** [comment]
This **%1$s** is the $context['settings_message'](ManageSearchEngines.php Line 85)
And the url in $context['settings_message']  is not correct. This link leads to the error log and not to the pruning settings
yourforum/index.php?action=admin;area=logs;sa=pruning

Correct would be my opinion 
yourforum/index.php?action=admin;area=logs;sa=settings
