### ISSUE TITLE
Sources/Stats.php ERROR: column "mem.real_name" must appear in the GROUP BY

### ISSUE THREAD

**Issue by rturja** [SimpleMachines/SMF#3664]
@albertlast 
Postgres requires the columns in GROUP BY clause

Sources/Stats.php line 579
`                        GROUP BY m.id_member,`
->`                        GROUP BY m.id_member,  mem.real_name`

**Comment by albertlast** [comment]
okay I fixed in #3665

**Comment by albertlast** [comment]
please open again,
this issue will be closed when the pr is merged.

**Comment by rturja** [comment]
Live and learn, reopened
