### ISSUE TITLE
Undefined index: can_remove_poll

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#3673]
Last Pull Request 3653

Board Version: SMF 2.1 Beta 3
Aktuelle SMF version: SMF 2.1 Beta 2
GD Version: bundled (2.1.0 compatible)
MySQLi engine: MySQL
MySQLi Version: 5.5.52-log
PHP: 5.5.38
Server Version: Apache/2.2.31 (Unix)

Undefined index: can_remove_poll
Type of error: Undefined
8: Undefined index: can_remove_poll
/Sources/Display.php Zeile: 804

**Comment by XinYenFon** [comment]
Duplicate: #3634
