### ISSUE TITLE
Postgres - Sources/ManageErrors.php ERROR: operator does not exist: integer ~~ unknown

### ISSUE THREAD

**Issue by rturja** [SimpleMachines/SMF#3681]
When clicking magnifying glass next to username

Sources/ManageErrors.php code starting from line 72:

> Database Error: ERROR: operator does not exist: integer ~~ unknown
> LINE 4: WHERE id_member LIKE '0'
> ^
> HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
> 
> 
> SELECT COUNT(*)
> FROM verstas_log_errors
> WHERE id_member LIKE '0'

**Comment by albertlast** [comment]
it's look like that,
that every option of the glasses are equal operation without wildcard search -> questionable why here is like used...
