### ISSUE TITLE
Undefined index: modify_reason

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#3682]
Last Pull Request #3662 => https://github.com/SimpleMachines/SMF2.1/pull/3662

Board Version: SMF 2.1 Beta 3
GD Version: bundled (2.1.0 compatible)
MySQLi engine: MySQL
MySQLi Version: 5.5.52-log
PHP: 5.5.38
Server Version: Apache/2.2.31 (Unix)

Type of error: Undefined
8: Undefined index: modify_reason
/index.php?action=jsmodify;topic=4;d114b6e1ad=efb4bbce2de2c9943433ce6ec37b0491;xml
Datei: /Sources/Post.php
Zeile: 2836

Error appeared after a post has been modified.

**Comment by Oldiesmann** [comment]
Thanks for the report. I'll take a look at it when I get a chance.
