### ISSUE TITLE
Board  Description double

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#3687]
Last Pull Request #3684 

Board Version: SMF 2.1 Beta 3
GD Version: bundled (2.1.0 compatible)
MySQLi engine: MySQL
MySQLi Version: 5.5.52-log
PHP: 5.5.38
Server Version: Apache/2.2.31 (Unix)

is double
`<p class="board_description">', $board['description'] , '</p>';
`
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/BoardIndex.template.php#L104
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/BoardIndex.template.php#L113

open BoardIndex.template
search
```
					<div class="info">
						<a class="subject mobile_subject" href="', $board['href'], '" id="b', $board['id'], '">
							', $board['name'], '
							<p class="board_description mobile_display">', $board['description'] , '</p>
						</a>';

				// Has it outstanding posts for approval?
				if ($board['can_approve_posts'] && ($board['unapproved_posts'] || $board['unapproved_topics']))
					echo '
						<a href="', $scripturl, '?action=moderate;area=postmod;sa=', ($board['unapproved_topics'] > 0 ? 'topics' : 'posts'), ';brd=', $board['id'], ';', $context['session_var'], '=', $context['session_id'], '" title="', sprintf($txt['unapproved_posts'], $board['unapproved_topics'], $board['unapproved_posts']), '" class="moderation_link">(!)</a>';

				echo '
						<p class="board_description">', $board['description'] , '</p>';
```
replace with
```
					<div class="info">
						<a class="subject mobile_subject" href="', $board['href'], '" id="b', $board['id'], '">
							', $board['name'], '
						</a>';

				// Has it outstanding posts for approval?
				if ($board['can_approve_posts'] && ($board['unapproved_posts'] || $board['unapproved_topics']))
					echo '
						<a href="', $scripturl, '?action=moderate;area=postmod;sa=', ($board['unapproved_topics'] > 0 ? 'topics' : 'posts'), ';brd=', $board['id'], ';', $context['session_var'], '=', $context['session_id'], '" title="', sprintf($txt['unapproved_posts'], $board['unapproved_topics'], $board['unapproved_posts']), '" class="moderation_link">(!)</a>';

				echo '
						<p class="board_description">', $board['description'] , '</p>';
```
![description_double](https://cloud.githubusercontent.com/assets/2753863/20407055/0785a032-ad10-11e6-95fa-8285a3c8e07b.JPG)

**Comment by XinYenFon** [comment]
Check your CSS, something wrong about it.

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/css/index.css#L3816-L3818

**Comment by wintstar** [comment]
This I have in my index.css. Look in responsive.css https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/css/responsive.css#L386-L388

my laptop screen is 1280px x 647px

I have for Update all files delete until Settings.php.

**Comment by wintstar** [comment]
Is done. Have again updated and the Firefox cache emptied.
