### ISSUE TITLE
Autolinker tlds passed by reference

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3689]
This introduces a new error

Notice
: Only variables should be passed by reference in
/smf21git/Sources/Subs.php
on line
5710

In my Subs 5709 and 10 lines:
````
	// build_regex() returns an array. We only need the first item.
	$tld_regex = array_shift(build_regex($tlds));
````

**Comment by jdarwood007** [comment]
@Sesquipedalian from PR #3680

**Comment by Sesquipedalian** [comment]
What version of PHP?

**Comment by jdarwood007** [comment]
PHP 7.0.8-0ubuntu0.16.04.3

**Comment by Sesquipedalian** [comment]
Thanks, @jdarwood. I am currently travelling, so at the moment I can't directly test any fixes myself. Instead, could you please test what happens if you  change  [line 5799](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs.php#L5799) in your local copy from 
```
$index_to_regex = function (&$index, $delim) use (&$strlen, &$index_to_regex)
```
to
```
$index_to_regex = function ($index, $delim) use (&$strlen, &$index_to_regex)
```

**Comment by albertlast** [comment]
Got the same issue,
when i apply your changes i got: 
Fatal error: Maximum execution time of 30 seconds exceeded in G:\github\SMF2.1\Sources\Subs.php on line 5819
![grafik](https://cloud.githubusercontent.com/assets/1782906/20512241/773fad16-b07e-11e6-9847-cf644764882a.png)

**Comment by jdarwood007** [comment]
Seems to work if I do this:

````
	// build_regex() returns an array. We only need the first item.
	$temp = build_regex($tlds);
	$tld_regex = array_shift($temp);
````

**Comment by Sesquipedalian** [comment]
Well, it strikes me as odd that using a temporary variable is not necessary in PHP 5 but is in PHP 7. But hey, if it works, it works. I'll submit a PR including this change early next week (I won't return from my travels until then).

**Comment by jdarwood007** [comment]
http://stackoverflow.com/questions/28477341/strict-standards-only-variables-should-be-passed-by-reference
https://bugs.php.net/bug.php?id=48937

Seems to indicate this is how array_shift works and strict mode throws the warning.

**Comment by Sesquipedalian** [comment]
Thanks, @jdarwood007. That explains the issue nicely.
