### ISSUE TITLE
memcached procedural functions

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#3693]
My server doesn't recognize memcached procedural functions, it returns false for var_dump(function_exists('memcached_get'));  

But it does recognize Memcached class:

```php
$s = new Memcached;

$s->addServer('server', port);
$s->add ('key', 'value', 3600);
var_dump($s->getAllKeys ());
```

prints out:

array(2) { [0]=> string(3) "key" [1]=> string(3) "value" }

Memcached values:

Version	3.0.0b1
libmemcached version	1.0.18

PHP Version	7.0.13

By reading https://github.com/php-memcached-dev/php-memcached/issues/225  it seems theres a few issues when using php7 and memcached 3.0.0 is still a beta so this might not be a huge issue.

But it would be nice to add support for Memcached class if it exists and the check for procedural fails in case the procedural functions get deprecated/removed later on.

**Comment by jdarwood007** [comment]
Should just move it all to the class method instead of supporting both.

**Comment by MissAllSunday** [comment]
With our current min versions, is it safe to do so? I don't know much about memcached and its development.

I would also like to have a real check to see if theres any real memcached server running, the current code only checks for the php side of it, some hosts, specially shared host might have the extension enabled but theres no server or access to that memcached server.

**Comment by Oldiesmann** [comment]
I've submitted a PR to change all the functions to OOP instead of procedural. No verification of the servers is needed as SMF will try to connect before trying to do anything and bails if the $memcached variable is false (see the get_memcached_server() function in Sources/Load.php).

**Comment by jdarwood007** [comment]
Cool, I will test it when I can.
