### ISSUE TITLE
Receive Emails and Alerts

### ISSUE THREAD

**Issue by bobrenja** [SimpleMachines/SMF#3695]
I turn on the alarm board. New posts to the email did not come.
There are some board where everything is fine, alert to the email come.
In setting up the profile of all active.
Where is it ??
Update the last set.

**screenshot**

![2016-11-30 0 41 23](https://cloud.githubusercontent.com/assets/20020367/20732121/e1bc5a8c-b695-11e6-8301-22ed401b2de3.png)

> 

**smf_user_alerts_prefs**
id_member = 1
alert_pref = board_notify_1
**......**
alert_pref = board_notify_30
alert_value = 3

**Comment by bobrenja** [comment]
**smf_user_alerts_prefs**

topic_notify_391  NO 	

For example in the table is not the theme ID 391
When I go to the board, it is worth icon I get a notification.

![2016-11-30 1 15 21](https://cloud.githubusercontent.com/assets/20020367/20733128/97a292a4-b69a-11e6-9d88-42cee649e67d.png)

**Comment by Oldiesmann** [comment]
Alerts work best if you set up a cron job for cron.php. Otherwise they're only sent when someone is actually visiting the forum.

**Comment by bobrenja** [comment]
many visits.
If you receive a message in the PM, warning immediately comes to email.

**Comment by bobrenja** [comment]
2.1 b2 good Receive Emails and Alerts
update 21. b3 new - no receive emails

**Comment by colinschoen** [comment]
^ We need details about your email configuration in order to look at this more closely.

**Comment by bobrenja** [comment]
@colinschoen thanks for the answer/

Alerts on email when receiving a personal message to come. Comes with an activation, if the new user registration.

It does not work when you create an alert or answer a new topic: Receive alert and Receive email

Tell me where to look?
