### ISSUE TITLE
php 7.1 - A non-numeric value encountered

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#3700]
I wasn't doing anything special actually, just entering the page is enough to generate the error.

php version: 7.1.0 RC6
apache: 2.4.18
mysql: 5.7.11

![screenshot-localhost-2016-12-03-12-22-02](https://cloud.githubusercontent.com/assets/1669995/20858275/13dacb9a-b94b-11e6-9189-a9c9f4ed35ba.png)

**Comment by albertlast** [comment]
This kind is new to php 7.1 before this version something like that works:
var_dump(10 * "apples"); // int(0)
now this keep working but create warning
// E_WARNING: Warning: A non-numeric string encountered in...
