### ISSUE TITLE
New errorr "The database value you're trying to insert does not exist: topic"

### ISSUE THREAD

**Issue by bobrenja** [SimpleMachines/SMF#3709]
Where it should be assigned this variable ??

$topicOptions['id']

```

$request = $smcFunc['db_query']('', '
SELECT id_member, email_address, lngfile
FROM {db_prefix}topics AS t
INNER JOIN {db_prefix}members AS mem ON (mem.id_member = t.id_member_started)
WHERE id_topic = {int:topic}', 	
array(
'topic' => $topicOptions['id'],
)
);

```
Sources/tasks/ApproveReply-Notify.php

**Comment by bobrenja** [comment]
We need to do a rollback, and forget about the spelling of any errors found.

**Comment by Oldiesmann** [comment]
What exactly is being done to generate that error? The code in question loads up information to notify a user that their reply to a topic has been approved, and $topicOptions['id'] should contain the ID of the topic that the approved reply is in, and $topicOptions itself should be passed to the function when the task is called (see lines 2444-2463 of Sources/Subs-Post.php for an example of how that's done).

That being said, I can't find this task being called anywhere. Even when posts are approved, everything goes through the CreatePost-Notify background task.

**Comment by live627** [comment]
> That being said, I can't find this task being called anywhere. 

Right here https://github.com/SimpleMachines/SMF2.1/blob/7dbd504de5bc2c5a29a15859871b57623766dd82/Sources/Subs-Post.php#L1991

**Comment by Oldiesmann** [comment]
Thanks for finding that @live627. I tried searching with both phpStorm and GitHub and couldn't find it anywhere. Guess I didn't look hard enough.

@bobrenja Are you getting any other errors with this one? $topicOptions['id'] should never not be defined when that function is called.

**Comment by bobrenja** [comment]
No more errors were not.
Now I can not check, since pulled back to a working version.
#3707
