### ISSUE TITLE
Remove Script Type Attribute

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#371]
In the HTML5 specification there is no need to specify type attribute for the script tag for javascript file any more as its treated by default as javascript. I would propose that the type attribute be removed from any javascript file 'includes'.

**Comment by XinYenFon** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/319 anything missing here?

**Comment by matthew-kerle** [comment]
There shouldn't be. I did all of these last I looked.

**Comment by ghost** [comment]
Sorry, I should have been more specific, remove the values from 'admin_info_files' table from the install files and the references within the admin area to these files change accordingly.

Example:
(1, 'current-version.js', '/smf/', 'version=%3$s', '', 'text/javascript'),

**Comment by ghost** [comment]
I'm going to close this off as the 'text/javascript' value is used to set the Content-Type of the file.
