### ISSUE TITLE
Post.english.php - Error in the text

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#3710]
Last pull request #3701 

Post.english.php line 131 and 132 is 2x locked. Is that right? Or it should not be unlocked in line 132
line 131 ...topic was locked, line 132 ...topic was **?un?**locked
```
$txt['error_topic_locked'] = 'Warnung - while you were typing the topic was locked. Please check the "Lock this topic" box under "Attachments and other options" below if you do not wish to undo this action.';
$txt['error_topic_unlocked'] = 'Warnung - while you were typing the topic was locked. Please uncheck the "Lock this topic" box under "Attachments and other options" below if you do not wish to undo this action.';
```

**Comment by Oldiesmann** [comment]
It should indeed be "unlocked" for the second one. Good catch!

**Comment by wintstar** [comment]
I´am work to translate for german => https://github.com/wintstar/Lingua.

**Comment by Oldiesmann** [comment]
We can't accept translations via GitHub like that - we have our own translation system. Please send an email to languages@simplemachines.org saying that you'd like to help with German translation and someone should get back to you about helping :)

**Comment by wintstar** [comment]
I have already done it for more than 3 weeks at email. So far I have received no answer. http://www.simplemachines.org/community/index.php?topic=258872.msg3899150#msg3899150

**Comment by Oldiesmann** [comment]
Not sure why you haven't heard anything. I sent a note to the head of the language team about it so hopefully you'll hear more soon.

**Comment by wintstar** [comment]
Many thanks.
