### ISSUE TITLE
jQuery updates

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#3712]
This is more of a "to do" at this point... Leaving notes here so others can comment and so I don't forget about this...

We currently use jQuery 2.1.4 by default in SMF 2.1. However, several newer versions of jQuery exist.

2.2 (released in January: http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/) - now on 2.2.4
3.0 (released in June: http://blog.jquery.com/2016/06/09/jquery-3-0-final-released/) and quickly replaced with 3.1 (http://blog.jquery.com/2016/07/07/jquery-3-1-0-released-no-more-silent-errors/). Now on 3.1.1

So with that in mind...

**2.2**
 - What advantages, if any, would there be for us to switch to this version? Also are there any disadvantages?
 - Are any code changes necessary to support this or can we just swap out the versions?

**3.x**
 - Any changes needed to support this (for future-proofing reasons mainly - the 2.x line is still supported and actively developed at least for bug-fixing purposes so there's really no need to jump to 3.1 at this point)

**Comment by live627** [comment]
> 3.x
    Any changes needed to support this (for future-proofing reasons mainly - the 2.x line is still supported and actively developed at least for bug-fixing purposes so there's really no need to jump to 3.1 at this point)

yes, this may give you an idea https://github.com/elkarte/Elkarte/pull/2682/commits/17a4a1706996bd97ca6b2296da95df90ab48fdae

**Comment by tinoest** [comment]
https://jquery.com/upgrade-guide/3.0/

Is the upgrade guide, I'll work through this and upgrade it to 3.0 if that's what's decided. I'm for running the latest possible at the time of release considering I don't believe SMF 2.2 or 3.0 is anytime soon.

**Comment by live627** [comment]
Go for it.

**Comment by tinoest** [comment]
In answer to your first question @Oldiesmann 

I've not detected any issues switching to 2.2.4 with the current code base. 

When going to 3.1.1 there are quite a few in files which are from external sources; 

slippry.min.js
jquery.sceditor.smf.js 
jquery.sceditor.bbcode.min.js

for example, does anyone know if SMF made any local modifications to these files or can I just get the latest version from the relevant repo?  

Edit: SMF is already on the latest version of sceditor, I've pulled the latest slippry.min.js and will push that to the pull request I have open for this.

**Comment by Oldiesmann** [comment]
If there aren't any issues with switching to 2.2.4, then we can go that route now and consider bumping it up to 3.1 before we go final, since we'll need more time to test everything and make necessary changes to our code.

**Comment by tinoest** [comment]
Code has already been changed it's in my pull request. #3807 

Didn't see any issues when testing what I could.
