### ISSUE TITLE
No longer used language strings

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#3713]
Here I will list the no longer used language strings, which I have found. The list I will update constantly.

**index.english.php**
```
$txt['error_occured'] = 'An Error Has Occurred';
```

**Post.english.php**
```
$txt['digest_subject_daily'] = 'Daily Digest';
$txt['digest_subject_weekly'] = 'Weekly Digest';
$txt['digest_intro_daily'] = 'Below is a summary of all activity in your subscribed boards and topics at %1$s today. To unsubscribe please visit the link below.';
$txt['digest_intro_weekly'] = 'Below is a summary of all activity in your subscribed boards and topics at %1$s this week. To unsubscribe please visit the link below.';

```

**Comment by d3vcho** [comment]
$txt['profile_of'] is being used in Who.template.php on line 74
$txt['total'] is being used in Profile.template.php on line 2780

**Comment by frandominguezl** [comment]
$txt['profile_of'] is being used in Who.template.php on line 71

I can confirm that the other ones aren't being used

**Comment by wintstar** [comment]
Thanks

**Comment by live627** [comment]
`$txt['error_occured']` is most definitely in use https://github.com/SimpleMachines/SMF2.1/search?utf8=%E2%9C%93&q=error_occured

**Comment by XinYenFon** [comment]
profile_of is used in different places as well as error_occured.

**Comment by wintstar** [comment]
Thanks, I'll check it out until next weekend.

**Comment by XinYenFon** [comment]
Digest related language files are loaded here: https://github.com/SimpleMachines/SMF2.1/blob/21045202b56c0047eba6fdab31609726398a7df5/Sources/ScheduledTasks.php#L622-L624
