### ISSUE TITLE
SMF on Retina Screens

### ISSUE THREAD

**Issue by colinschoen** [SimpleMachines/SMF#3716]
We should work to create 2X images to serve to retina screens. There are several javascript libraries to handle serving the correct higher resolution variant image, if appropriate. 

http://imulus.github.io/retinajs/

**Comment by live627** [comment]
imo, this is scope creep, sorry...

**Comment by colinschoen** [comment]
For down the road :). I just wanted it logged somewhere.

**Comment by live627** [comment]
ah cool

**Comment by illori** [comment]
the images that we use do they have the higher resolution images to be added? i am not sure they actually do.

**Comment by wintstar** [comment]
Do you really need that? Should not be offered better than as modification.

**Comment by live627** [comment]
Solve the problem, not  the symptom. Use SVG,

**Comment by XinYenFon** [comment]
I think for this version, we should be skipping things like this. I agree with @live627 using SVG will kill those problems.

**Comment by live627** [comment]
Seems to me that this thread is for the future... prob 3.0.

**Comment by XinYenFon** [comment]
I think so, its better to full focus on remaining issues and be done with this version.

**Comment by XinYenFon** [comment]
@colinschoen Can you pretty please close this issue ?
