### ISSUE TITLE
Incorrect version returned

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#372]
While I know the 'fetch SM files' task obviously can't return 2.1 versions for everything, I find it slightly worrisome that it returns 1.1.x versions for everything... even after manually re-running the task.

Even more interesting, the 'Current version' for 'SMF Package' is listed as SMF 1.1.17 rather than 1.1.18, and the Language Files say their version as 2.1 not 2.1 Alpha 1 like the other things.

**Comment by illori** [comment]
dup of #334 in part
