### ISSUE TITLE
This table hide_email need ??

### ISSUE THREAD

**Issue by bobrenja** [SimpleMachines/SMF#3720]
This table **hide_email** need ?? In the code, call her not.
When do install forum in file **other/install_2-1_mysql.sql**

CREATE TABLE {$db_prefix}members (
........
696    hide_email TINYINT NOT NULL DEFAULT '0',

**other/upgrade_2-1_mysql.sql** 
---# Dropping the "hide_email" column from the members table
1798	ALTER TABLE {$db_prefix}members
1799	DROP hide_email;
1800	---#

**Comment by Oldiesmann** [comment]
That's a bug. Nice find!
