### ISSUE TITLE
Quick edit post 

### ISSUE THREAD

**Issue by bobrenja** [SimpleMachines/SMF#3723]
**message**
![2016-12-13 16 27 17](https://cloud.githubusercontent.com/assets/20020367/21143935/52b03068-c151-11e6-95f4-b72a1429c241.png)

Quick edit -> save

![2016-12-13 16 27 41](https://cloud.githubusercontent.com/assets/20020367/21143950/63033406-c151-11e6-8f4d-e161f58726f3.png)

![2016-12-13 16 31 37](https://cloud.githubusercontent.com/assets/20020367/21144015/b408ab92-c151-11e6-92cd-7b011e801959.png)

**Comment by bobrenja** [comment]
More - Modify - >save - GOOD!!

**Comment by live627** [comment]
So it sounds like the quick edit form messes up accented characters.

**Comment by bobrenja** [comment]
How to fix?

**Comment by frandominguezl** [comment]
Why did you close this? Is this solved?

**Comment by ThomasFok** [comment]
I have the same problem if I enter Chinese characters. So, I think any non-ASCII character will get messed up.

It is a serious bug.
