### ISSUE TITLE
2 errors in ManageLanguages.php after installing language pack

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#3730]
Received this two errors after installing Spanish_es-utf8 (Beta 2, from Admin Panel) in the latest GitHub build:

Undefined index: images
Invalid argument supplied for foreach()

Both in line 379 of ManageLanguages.php

**Comment by XinYenFon** [comment]
Can you reproduce the issue in English pack ? If no, its not valid. You are using beta2 files with nightly build which means there might be (that might is a big possibility btw) difference.

**Comment by frandominguezl** [comment]
Yes. Tried installing English UTF8 and non UTF8 and got the same two errors each time.

**Comment by illori** [comment]
is it during the install you are getting the errors or when? [look at the timestamps]

**Comment by frandominguezl** [comment]
When you, through Admin Panel, search for a language pack and then click "Install". There I got the errors, and then I'm able to install the package. To be more specific, I got the errors after pressing this Install button (yes I know it's 2.0.12)

https://i.gyazo.com/73a33736425614b59a79cf3790d7d744.png

**Comment by Oldiesmann** [comment]
It looks like $context['files']['images'] is never set before we try to go through it - we only set $context['files']['lang'] and $context['files']['other']
