### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3741]
When you enter to the forum
Mixed Content: The page at 'https://yarik-sat.ru/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://yarik-sat.ru/'. This request has been blocked; the content must be served over HTTPS.
VM221:24 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at Object.error (eval at globalEval (jquery.js:328), <anonymous>:24:18)
    at j (jquery.js:3099)
    at Object.fireWith [as rejectWith] (jquery.js:3211)
    at x (jquery.js:8266)
    at XMLHttpRequest.<anonymous> (jquery.js:8599)
error @ VM221:24
j @ jquery.js:3099
fireWith @ jquery.js:3211
x @ jquery.js:8266
(anonymous) @ jquery.js:8599
![83](https://cloud.githubusercontent.com/assets/17574854/21470759/2b990940-caa8-11e6-8c29-d2e644364111.jpg)

**Comment by albertlast** [comment]
duplicate #3726
