### ISSUE TITLE
Duplicated code - needs to be cleaned up

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#3746]
see https://scrutinizer-ci.com/g/SimpleMachines/SMF2.1/issues/release-2.1/files/other/upgrade.php?orderField=issueCount&order=desc#inspectioncomment-57644308

**Comment by Oldiesmann** [comment]
Need to look at things more closely... Similar code but not duplicate.

**Comment by live627** [comment]
yeah... their dupe code finder throws tons of false positives.
