### ISSUE TITLE
Errors with Calendar

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#3749]
Alright, so I started testing Calendar and I got a couple of errors.

- 1. Every time I enter into "Post Event" (under Calendar Tab), I got this error:
8: Only variables should be passed by reference
Sources/Subs.php
Line 5030

After I press the "Post Button" to post an event, I get this screen error:
- 2. An Error Has Occurred
The database value you're trying to insert does not exist: id_board

And also got this 2 errors in error log:
- 3. The database value you're trying to insert does not exist: id_board
Function: insertEvent
Sources/Subs_Calendar.php
Line 919

- 4. 2: array_combine(): Both parameters should have an equal number of elements
Sources/Subs-Db-mysqli.php
Line 800

Event though, the event topic is created.

Couldn't go any further @Sesquipedalian 

**Version Information:**
Forum version: SMF 2.1 Beta 3 (more detailed)
Current SMF version: SMF 2.1 Beta 2
GD version: bundled (2.1.0 compatible) 
MySQLi engine: MariaDB 
MySQLi version: 10.0.20-MariaDB 
PHP: 7.0.6 (more detailed) 
Server version: Apache

**Comment by Sesquipedalian** [comment]
Thanks for the report(s), @d3vcho.

> Every time I enter into "Post Event" (under Calendar Tab), I got this error:
8: Only variables should be passed by reference
Sources/Subs.php
Line 5030

Derp. Easy fix. :)

**Comment by Sesquipedalian** [comment]
> "The database value you're trying to insert does not exist: id_board" errors...

It sounds like your calendar table is messed up. It is *very* strange that the the id_board column can't be found in your calendar table, since that column already existed in the table before my changes.

1. Did you see any error messages about the calendar when you ran upgrade.php?
2. Does the column exist when you look at the table using PHPMyAdmin (or whatever you use)?

**Comment by frandominguezl** [comment]
1. I didn't use Upgrade.php, it's a fresh 2.1 install.
2. Yes

**Comment by Sesquipedalian** [comment]
Oh, I think I found the problem now. Please test the changes in #3751.
