### ISSUE TITLE
Upgrade.php -  Cannot redeclare clean_cache()

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3755]
On one of my test servers, I get this message running Update.php attempting an upgrade from 2.0 to 2.1:

> Fatal error: Cannot redeclare clean_cache() (previously declared in (path)\upgrade.php:183) in (path)\Sources\Load.php on line 3407

I have two test servers I use, this only happens on one.   Must be something different about the environment.  The environment that fails runs php5.6, the one that works runs php5.5.  Not sure it's strictly a version issue though.  

At the heart of the issue is this:
> if (!function_exists('clean_cache'))
> {
> 	// Empty out the cache folder.
> 	function clean_cache($type = '')
> 

clean_cache() is also declared in Load.php, which is included via a require_once earlier in upgrade.php (line 139).  So it appears to me it will always exist at the time this logic is run(???).  Upgrade.php runs to completion if I just comment this statement out - the clean_cache definition within Upgrade.php.  

The problem is that the !function_exists is failing for some reason in this environment.  I've read elsewhere that sometimes function_exists needs a specific scope/path to avoid problems like this (which to me feels like it is defeating the purpose???).

**Comment by jdarwood007** [comment]
The function exists is failing in the upgrade because it comes before the call to Load.php

@jdarwood007

**Comment by tinoest** [comment]
It seems to be due to the fact its not finding the cache_put_data function, although that is on line 3892 for me not 3407. 

Are you using the latest copy checked out from GitHub? 

Also not that it should matter but are you using MySQL or PostgreSQL?

**Comment by sbulen** [comment]
I grabbed a new version today, same message, but it references Load.php on line 3425.  So I did have a slightly older version.   

I'm attempting a MySQL upgrade.  

I just tried it with the latest code, and now both of my test systems get this error.  I think the reason one worked OK earlier was that it had slightly older 2.1 code.

**Comment by sbulen** [comment]
I can get past this error by either commenting out the clean_cache block (as described earlier) 
OR...
...by commenting out the whole "mimic'ing SSI" section....   Lines ~134-145 in Upgrade.php that starts with this:   

> // Are we going to be mimic'ing SSI at this point?
> if (isset($_GET['ssi']))
> {
> 	require_once($sourcedir . '/Errors.php');

**Comment by NanoSector** [comment]
@sbulen this commit should fix this: https://github.com/Yoshi2889/SMF2.1/commit/d05736aecca0ef6f4d0c6ad5e047714db23176b2
it's included in my upgrade.php cleanup PR.
