### ISSUE TITLE
Unable to upgrade with PostgreSQL

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#3756]
I have a PostgreSQL test board. It has been running a git copy from November up until tonight, when I updated the files to the latest ones from GitHub. I tried to run upgrade.php to add the new columns to the calendar table but it failed with an error prior to getting to that point:

```
 *  +++  Changing ip to bigintError: pg_query(): Query failed: ERROR:  column "ip" cannot be cast automatically to type bigint
HINT:  You might need to specify "USING ip::bigint". File: /.../Sources/Subs-Db-postgresql.php Line: 452Unsuccessful!  Database error message:
ERROR:  column "ip" cannot be cast automatically to type bigint
HINT:  You might need to specify "USING ip::bigint".
```

The column in question is already "inet" so I'm not sure why we're trying to convert it to bigint here.

Additionally, after removing that code to get past that point, I run into another issue with the bans table:

```
 *  +++  add columnsError: pg_query(): Query failed: ERROR:  column "ip_low" of relation "smf_ban_items" already exists File: /.../Sources/Subs-Db-postgresql.php Line: 452Error: pg_query(): Query failed: ERROR:  column "ip_high" of relation "smf_ban_items" already exists File: /.../Sources/Subs-Db-postgresql.php Line: 452 done.
 +++  convert dataError: pg_query(): Query failed: ERROR:  column "ip_low1" does not exist
LINE 2: SET ip_low = (ip_low1||'.'||ip_low2||'.'||ip_low3||'.'||ip_l...
                      ^ File: /.../Sources/Subs-Db-postgresql.php Line: 452Unsuccessful!  Database error message:
ERROR:  column "ip_low1" does not exist
LINE 2: SET ip_low = (ip_low1||'.'||ip_low2||'.'||ip_low3||'.'||ip_l...
```

At that point I just added the columns manually

**Comment by tinoest** [comment]
This was done in this issues #3222 

I can't see how it would fail from 2.0 -> 2.1 or at least it didn't when I just tested it with a recently installed 2.0.x forum then run the upgrade. 

PG Version: 9.1.24 
PHP Version: 5.6.29

**Comment by Oldiesmann** [comment]
I'll have to do some more experimenting to see how well it works from 2.0 to 2.1 and also from Beta 2 to latest GitHub. This was from an older Git build to the latest GitHub build.

**Comment by albertlast** [comment]
In my eyes is that not issue,
because you try something which smf not supported (upgrade beta to beta version).

I run the sql command from upgrade directly vs the database.
