### ISSUE TITLE
Hardcoded javascript in Post template

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3768]
From about line 598
````
	// The functions used to preview a posts without loading a new page.
````

to about line 832
````
	// If the user is replying to a topic show the previous posts.
````

This contains hardcoded javascript, entire functions and a lot of logic.  This isn't efficient at all and should be moved to a static js file.

**Comment by colinschoen** [comment]
It look like some of the javascript functions included in `Post.template.php` are injected with `$context` and `$txt` data which is why it wasn't originally in an external `.js` file.

**Comment by jdarwood007** [comment]
Easily handled though using prototypes and specifying those as options.  That is a chunk of code (about 200 lines) that would do much better in a static file so browsers can actually cache that rather than reload it all the time.

**Comment by colinschoen** [comment]
Agreed. I'll take this.

**Comment by live627** [comment]
Very cool. I'm busy on the next 2.0.x update and have very little time for
2.1 ATM.

**Comment by albertlast** [comment]
So what it the status of this?

**Comment by tarantula901** [comment]
So what it the status of this???

**Comment by replikacep** [comment]
Slm hello seriously now rc version instead of this beta rc version is really touched with beta for 2 years i really appreciate you but i have not seen enough rc version emergence is really important now hopefully soon

**Comment by colinschoen** [comment]
I am shooting to have this out next weekend. Sorry, external work has been a bit busier the past few weeks. 

Status: In Progress

**Comment by replikacep** [comment]
Hello Did you speed up a little Too much time passed I need to finish now

**Comment by Oldiesmann** [comment]
@replikacep Everyone involved with this project is a volunteer. We can't always get to things as fast as people would like. Please be patient.

**Comment by albertlast** [comment]
I would not use the same words as replikacep,
but that this issue target for beta 3 got this issue a high priority.

The best solution in my eyes for this topic would be,
to delete the target version or move the target version to rc.

**Comment by replikacep** [comment]
Hello It has been developing for about 3 years
Still no rc version
I think it's too long. Expected Rc version
:)
I think the dating date in 2020

**Comment by frandominguezl** [comment]
As Oldiesmann said above, we're all volunteers. Please stop posting comments like this.

**Comment by colinschoen** [comment]
I don't think this is necessary to hold up Beta 3. I do plan on implementing this, but a few other SMF things have taken priority. I think we can ship Beta 3 without this.
