### ISSUE TITLE
Maintenace login page not responsive + Login issue

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#3769]
When in Maintenace as guest (or user without privileges to view the forum), the login page is not responsive.
![4ceb25bd4a17350b3d094f2f64d322dc](https://cloud.githubusercontent.com/assets/10365222/21582393/d2894e24-d055-11e6-8324-27269e55dc43.png)

Also, in the same screen (now with computer) when you click on the top "Login" link, you got this:
![](https://i.gyazo.com/34fa6a36ab049413abac715eadcecede.png)

This issues aren't happening in the guest screen when trying to access the forum but the box "Allow users to browse the forum" is unchecked.

**Comment by colinschoen** [comment]
#3771 fixes this.

**Comment by frandominguezl** [comment]
Second issue not fixed yet @colinschoen

**Comment by colinschoen** [comment]
Apologies, missed that. Reopened until second issue is fixed.

**Comment by jdarwood007** [comment]
I get the second issue as well.  Goes away after a page refresh so it is difficult to debug.

**Comment by live627** [comment]
I already debugged it. The 503 response confuses the script.

**Comment by jdarwood007** [comment]
Forgive me as I haven't checked the code, but SMF is sending a 503?

**Comment by frandominguezl** [comment]
Yes. In that page I was receiving also a 503 error, appearing in the browser's console @jdarwood007

**Comment by albertlast** [comment]
This issue should be done?

**Comment by frandominguezl** [comment]
If it's fixed, sure. Haven't had a chance to test it yet.

**Comment by frandominguezl** [comment]
Yup, it's fixed. Thanks.
