### ISSUE TITLE
Drop mysql_* ?

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#3774]
yoshi was so nice and place in his upgrade clean pr a logic which switch
the database driver from mysql to mysqli automaticaly.
i got now the question in my mind,
if we not drop the support for mysql_* stuff?

**Comment by tinoest** [comment]
I see no need for it to remain, other than to cause support issues in the future if the host removes it without notifiying the owner. 

MySQLi is more efficient and has been around for years now. It's also covered by the minimum php version in place for 2.1.

**Comment by colinschoen** [comment]
Agreed

**Comment by albertlast** [comment]
Okay the first idea was to delete the Subs-Db-mysql.php file...
But when i do this,
can can it happen that user overwrite there existing smf 2.0 with smf2.1 files and
the Subs-Db-mysql.php doesn't get touched -> the old Subs-Db-mysql.php from smf2.0 keep in place
and would create mutch problems...
Maybe keep the file only do it empty?

**Comment by live627** [comment]
Or maybe rewrite the mysql files with the mysqli code?

**Comment by albertlast** [comment]
and what do we than with the Subs-Db-mysqli.php file?

**Comment by live627** [comment]
I'm thinking we could use only `mysql` in `$db_type` and drop `mysqli` Less complexity,  extra mysqli files can be deleted.

**Comment by tinoest** [comment]
Replacing the files makes sense, as does dropping the MySQLi names. It doesn't serve much purpose having MySQLi as the vast majority don't know or even care about the difference.

**Comment by NanoSector** [comment]
@live627 This complexity was introduced because some files were not renamed from mysql to mysqli, if these files were renamed in the first place this complexity wouldn't have been added.

**Comment by albertlast** [comment]
smf2 know only db_type and mysqli is no db_type, it's a driver.
to start with files called mysqli was an error.

**Comment by NanoSector** [comment]
However if the files are called MySQL it isn't clear to developers if they're working with MySQL, MySQLi, PDO, a custom driver, or whatnot. This may be relevant.

I also disagree with changing MySQLi back to MySQL for no reason, especially since we really need to get 2.1 out the door so we shouldn't start changing or adding stuff for no reason unless it fixes something.

**Comment by live627** [comment]
We could argue about this all day...

I  think things should be named after the database type, not the driver if only one driver is needed to connect. This arbitrary change for no reason reduces complexity, good enough for me.

**Comment by tinoest** [comment]
@Oldiesmann If you are adding MySQLi to SMF2.0 to enable PHP 7.0 support, what are you doing? As that effects some of the comments made on here.

**Comment by live627** [comment]
@tinoest I'm working on 2.0.14 which will add mysqli, along with many other goodies. It does not change `$db_type`.
