### ISSUE TITLE
Proxy quits if image too large

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#3781]
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/proxy.php#L174

Should a silent passthru be the fallback?

**Comment by Sesquipedalian** [comment]
Question: what exactly is the purpose, or purposes, of the image proxy? I haven't really looked at it, but if I understand correctly, it seems that at least part of the purpose is to smooth things over when using SSL. For that, might it not be easier to just use schemeless URLs? 

(To be clear, I'm fully expect that there's more going on here than just that, but I thought it worth asking.)

**Comment by live627** [comment]
When using  SSL, insecure images give warnings in browsers, no?

**Comment by Sesquipedalian** [comment]
Derp. Had a brain-fart and forgot the scenario where we are using SSL and trying to embed an image that's only available unsecured. Never mind. :)

**Comment by Sesquipedalian** [comment]
Okay, looking at the actual code in question, I agree that a silent passthrough would be the best course for images that are too large to cache, if by "silent passthrough" we mean fetching the image afresh from its origin every time and just spitting that back out without caching it. That'll take some restructuring of the code, though.

**Comment by Sesquipedalian** [comment]
Have you started working on a fix for this, @live627? If not, I could take a swing at it.

EDIT: Never mind. I see now that you have listed yourself in the assignees. :)

**Comment by colinschoen** [comment]
Much improved. Thanks for the fix.
