### ISSUE TITLE
First verification question not shown if visual verification and reCAPTCHA both disabled

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#3782]
If SMF's visual verification and the new reCAPTCHA are both disabled, and the admin has set one or more verification questions for users to answer, the first verification question is not shown. If one is required, none are shown; if three are required, two are shown; etc. This makes in impossible for the verification form to be completed successfully, since SMF still expects an answer back for the missing question.

**Comment by colinschoen** [comment]
Good find, thanks for the fix.
