### ISSUE TITLE
Board display with long description

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#3789]
![board-description](https://cloud.githubusercontent.com/assets/4106630/21622892/ca434d40-d1cd-11e6-99da-f18188140580.jpg)

a long board description breaks the standard layout of the boardindex

**Comment by frandominguezl** [comment]
**Note**: That only happens when you zoom out

**Comment by Kindred-999** [comment]
nope...   this happens at standard 100% view in Firefox for me

**Comment by XinYenFon** [comment]
localhost or link ?

**Comment by Kindred-999** [comment]
sorry
https://test2.turtleshellprod.com/index.php

**Comment by frandominguezl** [comment]
Not in Chrome for me

**Comment by XinYenFon** [comment]
Thats probably because @Kindred-999 using higher resolution such as 1920x1080. I can't reproduce the issue on 1366x768 res. as well.

**Comment by Kindred-999** [comment]
yes....  1920x1080

**Comment by Dzonny** [comment]
Appearing in normal 100% view for me. 1680 X 1050

**Comment by Bopske** [comment]
Correct, I am allways using high res, and am seeing this at every 2.1 test site with long descriptions in the boards...
