### ISSUE TITLE
Should use CSS3 pseudo-element syntax

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#3791]
Since IE9 is the lowest IE that SMF 2.1 will support, we can upgrade our CSS to use the CSS3 double-colon (::) syntax for pseudo-elements. Microsoft themselves [recommend this](https://msdn.microsoft.com/en-us/library/hh781508(v=vs.85).aspx#pseudo-elements) for IE9+.

**Comment by frandominguezl** [comment]
What are the advantages of using double-colon instead of single? According to W3Schools, this was just an attempt of W3C to distinguish between pseudo-elements and pseudo-classes.

**Comment by Sesquipedalian** [comment]
Both syntaxes work in browsers today, but using the CSS3 syntax is standards compliant and therefore more future-proof. Basically, I'm suggesting that since we don't need to support the legacy syntax anymore, there's no reason not to do things the standard and recommended way.

**Comment by XinYenFon** [comment]
This is something I suggest for next version. I know its not big, i still think such small changes shouldn't be blocking the releases*.

* the releases: the stable / gold release.

**Comment by colinschoen** [comment]
Agreed, could we push this to Beta 4 maybe? Or Antes are you saying 3.0?

**Comment by Sesquipedalian** [comment]
Whatever you guys think is best is fine with me. If and when you want it, I've implemented this in PR #3795.
