### ISSUE TITLE
HTML BBC fails

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#3794]
Type of error: General
2: strtr() expects parameter 1 to be string, array given
https://test2.turtleshellprod.com/index.php?action=post2;start=0;board=4
File: /.../Sources/Subs.php
Line: 823

tried the following post
testing
[html]HTML STUFF[/html]
and the entire content is removed...
this happens in both preview and post

**Comment by Sesquipedalian** [comment]
The problem was in the preparser.

**Comment by colinschoen** [comment]
Thanks for the fix, @Sesquipedalian
