### ISSUE TITLE
Send this topic - some kind of confirmation.

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#380]
When you send a private message (PM), a confirmation is shown that the message has been sent. It would be great if a similar confirmation could be introduced for sending a topic to someone. At the moment, you just get taken back to the message index and you have no idea if anything actually happened. This issue affects both SMF2.0 and seemingly also 2.1. 

I don't know how difficult this would be to implement, but it could be worth considering. Thank you for reading!

**Comment by Oldiesmann** [comment]
I agree. We need something to say that it was at least sent successfully.

**Comment by Oldiesmann** [comment]
Feature has been added. Thanks for the suggestion!

**Comment by ChainyEO** [comment]
Just noticed this. Thank you for adding this feature!

Best regards,

Robert (ChainySMF)

On Tue, Jun 25, 2013, at 20:53, Michael Eshom wrote:

  Feature has been added. Thanks for the suggestion!

  —

Reply to this email directly or [1]view it on GitHub.
[RNiw30ukCxSh8dBW9Ii_1RA5-v8QdrQQHOPEN4ad9VFJ_U9TE-rZ6PjMXNmfiqeB.gif]

References
1. https://github.com/SimpleMachines/SMF2.1/issues/380#issuecomment-19998619
