### ISSUE TITLE
Event title Notification  

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#3805]
http://www.simplemachines.org/community/index.php?topic=551078.0

**Comment by kat-kta** [comment]
@live627 Heyo, I'm the kat who started the topic. Just another thing i'd like to bring attention to. While the name of the event in notifications is fixed (yay), everyone who recieves the notification of a new event gets spammed the ever living hell out of them... Just made a test site and account1 made 1 event, however, account2 (who is subscribed to get notifications) got a whooping 10 of em in a minute. Am still running the test site. Cheers
