### ISSUE TITLE
integrate_clean_cache

### ISSUE THREAD

**Issue by interlab** [SimpleMachines/SMF#381]
http://www.simplemachines.org/community/index.php?topic=454883.msg3522050#msg3522050

for example if you use library which uses own folders of a cache which you too would like to clear in case of forum cache flush

Subs.php

Find:

``` php
    // Invalidate cache, to be sure!
    // ... as long as Load.php can be modified, anyway.
    @touch($sourcedir . '/' . 'Load.php');
    clearstatcache();
```

Replace:

``` php
    // Invalidate cache, to be sure!
    // ... as long as Load.php can be modified, anyway.
    @touch($sourcedir . '/' . 'Load.php');

    call_integration_hook('integrate_clean_cache');

    clearstatcache();
```

**Comment by PortaMx** [comment]
This is also interesting if you have memory cache like ACP ..

**Comment by interlab** [comment]
(sorry my english)

if you use libraries which generate temporal files, by means of this lever you will be able to clear them:
Twig, Doctrine ORM, CSSMin, JSMin, JSMinPlus, ...
