### ISSUE TITLE
Title bar size on message index

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#3811]
#3793 causes this to happen on the message index:

![screen shot 2017-01-06 at 11 10 59 pm](https://cloud.githubusercontent.com/assets/191731/21739903/bc37b296-d465-11e6-92bf-d41c47c73f6b.png)

**Comment by Sesquipedalian** [comment]
@live627

**Comment by live627** [comment]
Quick thought: it has a min-height of 4.5em which should probably go

@Antes thoughts?

**Comment by Sesquipedalian** [comment]
Wouldn't that also affect the main table rows?

Also, I just noticed that #3793 also affects the positioning of the quick moderation checkboxes at the end of each row.

**Comment by XinYenFon** [comment]
Just a leftover.
