### ISSUE TITLE
Side menu issue, stops package install

### ISSUE THREAD

**Issue by NekoJonez** [SimpleMachines/SMF#382]
It's an extreme nitpick but when I was installing a package and when I clicked on the double arrows to get the side bar menu out of the way, the page returns to the list of the packages.

**Comment by illori** [comment]
which double arrows? in 2.1 the double arrows do not exist any longer, it is only an option via your profile to change from side menu to top menu.

**Comment by Arantor** [comment]
Not being funny but clicking on any link while in the middle of installing a package is going to cause problems. It just so happens in this case that the button in question is no longer there... not really anything to fix here.
