### ISSUE TITLE
Attachments - dropzone formatting

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3826]
Formatting very strange AFTER you have uploaded the attachments (after pressing the "Upload" button):
 - What's the "[attach name" box doing there?  
 - Buttons not aligned, seem randomly placed.  

See screenshot below.

![dz-formatting](https://cloud.githubusercontent.com/assets/23568484/21831803/5baccf58-d75b-11e6-8b32-e601451544e4.JPG)

**Comment by Kindred-999** [comment]
The "attach" box allows you to specify where you place the attachment in the message (inline)
So, that is correct....

The insert button is aligned (vertically) with the attach text box. The "delete attachment" remains in the location of the original buttons.

I think this is actually all correct, FAD...

**Comment by sbulen** [comment]
Is the attach box supposed to be associated with the Insert button?   That is not clear since they're so far apart...
