### ISSUE TITLE
Attachments - orphaned file issues

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3827]
Several file management issues that I believe are related:

(1) Add a few attachments, & press the "Upload" button.   Navigate away without pressing "Post".  Start a 2nd post.  Start to add an attachment to your new post, & **one of** the prior attachments is already in your list...  I'm not sure what you want it to do here, but likely not that...    (Either all or none & clean up after itself...)

(2)  Set your max attachment directory space to something low like 4000K.   Add a bunch of attachments & exceed this.   Upload what you can, & press Post.   
    2A -  It will not log a critical error or notify the administrators that the directory is full.  
    2B -  It will leave post_tmp* files in your file system.  The only way to remove these files is at the file system level.  They are not visible when using "Browse Files" and they are not cleaned up when you run the Attachment Integrity Check.
    2C -  It displays the wrong errors to the user - it will use the 'internal' errors, not the user friendly translated errors.    E.g., the error will state "ran_out_of_space".   

(3)  After doing several tests like the above, check the # of files in your attachment folder.   There are too many [hash].dat files and post_tmp* files.   They don't show up when you "browse" files under Admin | Attachments | Browse.  And they don't go away after running file maintenance.   To verify, browse your attachments and delete ALL of them.   Run the Attachment Integrity Check.  You should have 0 files in the attachment folder now, but you have more...  

The ONLY way to delete these orphaned files is directly, at the file system level (file manager).  Go ahead & do so...   Interestingly, running another Attachment Integrity Check immediately after this will squawk about files it didn't know about a minute earlier...   

Either "Browse Files" is missing files or the Attachment Integrity Check is missing files...   

It appears the dropzone attachment UI leaves orphans around - it doesn't always clean up after itself.

**Comment by sbulen** [comment]
My theory now on (3) above is that all of the [hash].dat files are valid, but browse & Attach Integrity Check are acting on old info, specifically, your previous visit to Admin | Attachments.

**Comment by sbulen** [comment]
(3) Above is repeatable with the following steps:   Add a bunch of files (I always use images) to a post.   Upload.   Navigate away without pressing the 'Post' button.    If the upload was successful, these files exist on disk in [hash].dat format, but are not visible when you use Browse Files (Admin, Attachments & Avatars).  They do not go away when you do an attachment check.  They are, however, included in the stats under File Maintenance.  

So:
 - Files that error out leave behind the post_tmp* orphans.
 - Files that are uploaded successfully but not posted leave behind the [hash].dat orphans.

**Comment by sbulen** [comment]
This is what I think needs to happen for each of the issues above:
(1) Fix to Attachments.php &/or smf_fileUpload.js to do some housecleaning, so you don't see fragments of prior activity.
(2A) (2B) (2C) Fix to Attachments.php to clean up post_tmp* files that error out and to properly process the errors.  
(3) I believe that the File Maintenance function for attachments needs to be enhanced to clean up files that are in the file system but not in the DB - to be safest, it should be able to clean up post_tmp* files and [hash].dat files that are unused.

**Comment by sbulen** [comment]
Made some corrections & clarifications above.  PR for #2a, 2b, 2c coming.   

1 & 3 still outstanding.

**Comment by sbulen** [comment]
I'm now researching (3), the File Maintenance issues.  It looks like all the logic is there, just with a couple issues.   

The problem with the orphaned attachment records (not used in messages) is that the msg_id = 0, and the logic specifically avoids deleting those.    I'm fairly sure they should be deleted.

Note that for all, member_id =0 as well.  They're not avatars.  They're just abandoned attachment records, usually with corresponding file system records.  

I checked, it did so in 2.0 as well...   So... I looked at my very old site and found about 300 similar attachments.   They really do appear to be bogus, likely caused by abandoned posts.  

_Anybody know if there is a reason not to delete these msg_id=0, member_id=0 attachments?_

**Comment by sbulen** [comment]
Update...   

I'm testing a fix for (3), Attachment Integrity Check to clean up orphans.   I'm testing against a vanilla forum & a converted forum, so it is has taken me a few evenings...   Will likely close (3) out tonight.  

(For the record: the existing Attachment Integrity Check logic does a good job cleaning up file-system-level orphans.   Hard to see/test this, because it will not delete some types of orphans until 5 hours has passed...  My fix for (3) focuses on the post-upload orphans that also have an attachment record.)  

Will start looking into (1) tonight.

**Comment by sbulen** [comment]
I believe the last 2 PRs will close this out.

**Comment by Oldiesmann** [comment]
Both of those have been merged now.
