### ISSUE TITLE
installer crashes after Welcome page

### ISSUE THREAD

**Issue by Jailer1** [SimpleMachines/SMF#3831]
Just downloaded the latest build and like the title says installer crashes after welcome screen. Installed on FreeBSD 10.3 with Nginx, Maridb101 and PHP7. From the Nginx error log:

`2017/01/12 18:42:49 [error] 4107#101830: *14 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/Class-Package.php): failed to open stream: No such file or directory in /usr/local/www/nginx/install.php on line 595

PHP message: PHP Fatal error:  require_once(): Failed opening required '/Class-Package.php' (include_path='.:/usr/local/share/pear') in /usr/local/www/nginx/install.php on line 595" while reading response header from upstream, client: 192.168.0.210, server: 192.168.0.222, request: "POST /install.php?step=0 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "192.168.0.222", referrer: "http://192.168.0.222/install.php"`

**Comment by Oldiesmann** [comment]
Thanks for the report. Sounds like a global variable isn't defined there. I'll look into it

**Comment by XinYenFon** [comment]
Unfortunately I can't reproduce this issue on my localhost and according to the install.php Class-Package.php used in two different spot and only one has $sourcedir which is defined as global in same function.

Can you try the following and open your install.php;

Find
``require_once($sourcedir . '/Class-Package.php');``

Replace with
``require_once('Sources/Class-Package.php');``

**Comment by Jailer1** [comment]
That worked, the install proceeded normally after that change.
