### ISSUE TITLE
Upgrade message - The upgrader could not find the "Install" language file for the forum default language, english-utf8.

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3832]
My DB was already in UTF-8.  Running the upgrader, I received this message:
> The upgrader could not find the "Install" language file for the forum default language, english-utf8.
> Please make certain you uploaded all the files included in the package, even the theme and language files for the default theme.

This may be a common occurrence.  Pressing the "Try English" link worked.  

I suggest we go straight to "English" (or other language) upon finding "English-UTF8" (or other language-UTF8) as the setting.   I.e., if we can strip the '-UTF8' and find a match, go for it...   

Given we're requiring UTF8 going forward, specifying '-UTF8' as part of the language is no longer needed, right?

**Comment by sbulen** [comment]
I don't want to get too philosophical here...   Honest.  ;^)

I imagine it would be OK to just close this out, and anticipate that folks already on UTF8 will see this message.

**Comment by sbulen** [comment]
One minor nit is that the message comes up before all the graphics are displayed.  It's a little ugly.

**Comment by Oldiesmann** [comment]
This should be easy to fix. Will look into it shortly.

**Comment by sbulen** [comment]
Much cleaner experience...
