### ISSUE TITLE
Upgrade Issue - Can't get past Step 4

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3833]
I can't get past Step 4.  It keeps telling me there is no response for 30 seconds, but my system seems to be OK otherwise.  Logs are fairly clean.  

This is my first test run on a complete copy of my prod system - with all the prod data - moving from 2.0 to 2.1.  Running PHP 5.6, & MySql 5.7.  

I suspect it is confused what step it is on.  Note in the URL it says it's on **_step 2_**, but it was actually on **_step 4_**.  

Maybe that's the real issue, it's lost.  See screenshot.  

![cantgetpaststep4](https://cloud.githubusercontent.com/assets/23568484/21918320/fd265a98-d904-11e6-86f3-3ff777e838be.JPG)

**Comment by sbulen** [comment]
Just installed a brand new 2.0 instance & upgraded to 2.1 and this did NOT occur.  It executed properly to completion.

**Comment by sbulen** [comment]
Just repeated the upgrade process for the entire site (yes, in test) and the same thing happened.  I can't get past step 4.   Running the very latest off of github.  

EXACT same location - after saying "Add an order value to each existing cust profile field... done", it clearly pauses for a while & issues the error message above.

**Comment by sbulen** [comment]
However, this time I see this entry in my MySQL log:
2017-01-14T17:33:58.960641Z 52 [Note] Aborted connection 52 to db: 'unconnected' user: <my user> host: <myhost> (Got an error reading communication packets)

Reading up on this...  Lots of sources of this error, among them network hardware errors (not likely, it's localhost...), lack of commits, etc., settings too low in MySql config, or PHP unexpected termination.

**Comment by sbulen** [comment]
I suspect an issue in the Messenger Fields migration.   

If I delete the "Add an order value..." and "Converting member values" sections from upgrade_2-1_mysql.sql (rows 957-1062) it executes successfully to completion.

**Comment by jdarwood007** [comment]
Try in the "Converting member values" to change the $limit to something lower like 200.

**Comment by sbulen** [comment]
Hmmm...   Didn't work.  I have it all the way down to 200.  

I've got ~18000 members.  It just seems to run away with that volume on that command that tries to take the old columnar data & convert it.

**Comment by sbulen** [comment]
Looks to me like its job is to take the old messenger contents from the members table and convert them to references in the themes table.  

It didn't add a single row into the themes table after all that effort.

**Comment by sbulen** [comment]
There are two issues here...
First, it really didn't like the theme_id of -1.   Violates the constraint on the table definition.  
~~~Second, it wasn't passing the actual value back into the Themes table.~~~
Testing...

**Comment by sbulen** [comment]
Just as an FYI, after this fix, user location converted data now shows up on the forum.  Screenshot attached.
![image](https://cloud.githubusercontent.com/assets/23568484/21965732/d76d675c-db1a-11e6-8fc1-df298d142384.png)
