### ISSUE TITLE
"postg_fetch_assoc"

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#3834]
Subs-Db-postgrespl.php, line 37:

```
if (!isset($smcFunc['db_fetch_assoc']) || $smcFunc['db_fetch_assoc'] != 'postg_fetch_assoc')
```

Is "postg_fetch_assoc" really what should be in there? I would think "smf_db_fetch_assoc" would be right, based on what I see just a few lines below that.

**Comment by tinoest** [comment]
I'd agree, looking at the MySQL function its the same as whats in the array.
