### ISSUE TITLE
Upgrader - Issues caused by serialize-to-JSON: Wrong value type sent to the database. Integer expected. (maxindex)

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3840]
~~~After enabling Likes,~~~ if you attempt to navigate around the forum, you get the following message:
Wrong value type sent to the database. Integer expected. (maxindex)

Subsequently disabling it doesn't fix it, you're stuck...

**Comment by sbulen** [comment]
Hmmm...  Just saw it without Likes enabled.   This 2nd time it affected my admin ID, but not my test user ID.   

I didn't see it at all before playing around with Likes though.

**Comment by albertlast** [comment]
Can you please post the error message?
Because when i activate like i got no errors.

**Comment by sbulen** [comment]
![image](https://cloud.githubusercontent.com/assets/23568484/21960653/288479d8-daa7-11e6-86ca-913a83f4263c.png)

This is what's in the error log:
Wrong value type sent to the database. Integer expected. (maxindex) Function: MessageIndex

**Comment by albertlast** [comment]
in the admin area should be more information.
and this part which i like to see.

**Comment by sbulen** [comment]
![image](https://cloud.githubusercontent.com/assets/23568484/21960677/c844b618-daa7-11e6-842c-129b78b2985b.png)

**Comment by sbulen** [comment]
It's only affecting my admin account, not 'user' test accounts.

**Comment by albertlast** [comment]
I see another issue below can you please provide alle error log message which raised up in this call?

**Comment by sbulen** [comment]
More of the same 2 messages, I ran into them a few times.

**Comment by albertlast** [comment]
the other below is division by zero and i would like to see from where this came

**Comment by sbulen** [comment]
It's not displayed.  There is no more info in the log.  

In MessageIndex.php, maxinfo is used and is used in a DB query.   In the debugger, I've confirmed that the value: {"pv":"simple"}  is in maxinfo & is being passed to the query.   No bueno.  

It in turn, is coming from line 68, where it's calculated based on some of admin settings.   What I don't know now is how are these admin settings getting overwritten...   

BTW:  This was a freshly upgraded DB.

**Comment by albertlast** [comment]
you see,
than is not the database message the issue,
the division by zero is your problem.

And i don't understand why you not post all related issue to this call...

**Comment by sbulen** [comment]
Sorry - I shared everything in the log (without showing duplicates).    I learned more while answering your questions.   

I think the log is not good with details when the problem is on the DB side.  It is excellent when there is a php error.  

Looking at it further, the root problem appears to be that $options is not initialized when MessageIndex is invoked.  Thus, when these variables are used in math, you get divide by zero issues.  And you pass bad data to the DB.  

I don't know where or how $options is supposed to be populated, though...

**Comment by sbulen** [comment]
The divide by zero is on line 120 of MessageIndex.php.  Didn't notice I truncated that above.

**Comment by albertlast** [comment]
in the table settings in the database exists the entry "defaultMaxTopics" and which value he got?

**Comment by sbulen** [comment]
I think you mean 'topics per page'?   It, along with several other items in $options, is corrupted.  Screenshot below.   The trick will be to find out how $options is getting messed up for admins.  

![image](https://cloud.githubusercontent.com/assets/23568484/21961118/f671d990-dab5-11e6-955a-1b53f5bdcdd4.png)

**Comment by albertlast** [comment]
no i mean the database table settings here the row with the variable defaultMaxTopics
![grafik](https://cloud.githubusercontent.com/assets/1782906/21961128/b7b4b492-db01-11e6-8e41-a1587a5f87d5.png)

**Comment by sbulen** [comment]
defaultMaxTopics is 50 & defaultMaxMessages is 25.

I changed the title above - I no longer think this is associated with Likes.  That was a red herring...

It appears to me that something is clobbering $Options when administrators move from the administration area (e.g., to enable or disable likes) back to the normal part of the forum.

**Comment by albertlast** [comment]
in my eyes is there no database relation, too.
Because the error happen earlier and the database error ist only error which follow up based on this.

**Comment by sbulen** [comment]
Yes, you are correct.   The DB looks fine.  

This is happening in the app somewhere.  Somehow $Options is uninitialized or overwritten for admins.

**Comment by sbulen** [comment]
I have found the source of the corrupt data.  The topics_per_page and messages_per_page settings are stored in the themes table for each user.  

For my admin user, these are corrupt and instead of including a #, say 0 or 50, they now include strange JSON strings like:  {"sb":"member","pv":"classic"}

I searched the whole database and there are scores of such corrupt entries in the themes table.  

These corrupted entries do NOT exist in the source tables (pre-migration from 2.0).  So my latest theory is that this is an upgrader issue.

**Comment by sbulen** [comment]
Serialize-to-JSON is stepping on contents in the themes table.  

On a hunch, I bypassed the serialize-to-JSON step during the upgrade process, and confirmed that the fields are no longer corrupted.  It appears that **admin_preferences** are transformed & propagated to several other fields, e.g., collapse_headers, topics_per_page and messages_per_page.  See the screenshot above...  These values are then presented to the app in the $options array, and cause issues within the app.  

Since admin_preferences are the issue, this mainly corrupts admin users.

**Comment by sbulen** [comment]
Fix tested & PR submitted.  Narrowed the update query to impact rows with the variable 'admin_preferences' only.
