### ISSUE TITLE
Upgrader - : unserialize(): Error at offset 0 of 15 bytes in ... upgrade.php on line 125

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3841]
I've started seeing this at the top of the Upgrader recently:

Notice
: unserialize(): Error at offset 0 of 15 bytes in (path) \upgrade.php on line 125

**Comment by albertlast** [comment]
In general would be better I think,
if we safe this information as json and not as serialze.

**Comment by sbulen** [comment]
When re-testing the upgrade, I restored the DB but kept the settings.php file around.  (I thought this was safe, it had my environment info...)

The 2.1 upgrade adds a bunch of entries to the settings.php file.   These settings are causing the error.   If I restore the original settings.php file when I restore the DB, I do not get this error.  

These are the lines in Settings.php causing the issue:
> $upgradeData = #remove#;
> $image_proxy_secret = '47baf8c8b7f0fbc7fce8';

So...   Due to the comment #remove# (which also negates the semicolon), this ends up executing as:
> $upgradeData = $image_proxy_secret = '47baf8c8b7f0fbc7fce8';

If you attempt to re-use this Settings.php file, $upgradeData gets this weird value, and causes this error message when it attempts to deserialize this value.  

I was going to close this issue out, since there is no issue when I start with the 2.0 settings.php.  

But then I wondered -  Do we really want to leave these lines in Settings.php?   Including:
> $upgradeData = #remove#;

Or are we supposed to remove it as the comment suggests?

**Comment by sbulen** [comment]
OK, to be safest, I just submitted a PR to set $upgradeData to null upon successful completion of an upgrade.  Tested & it works fine.  (If nothing else, we're setup for 3.0!)
