### ISSUE TITLE
SCEditor incorrectly formats and interprets [url] BBCode

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#3843]
It is easier to give instructions on how to reproduce this one than it is to describe it. Do the following, and you will see the issue:

1. In WYSIWYG mode, insert a link to some URL. Initially, everything appears to the eye to be okay (but it isn't—see below on previewing, etc.).
![screen shot 2017-01-15 at 4 33 17 am](https://cloud.githubusercontent.com/assets/191731/21962155/d11dcd22-dadb-11e6-9d8d-9728533ecb12.png)
2. Toggle from WYSIWYG mode to source mode. Instead of converting the `<a>` element to a `[url]` BBCode, it is converted to a `[member]` BBCode with an undefined parameter.
![screen shot 2017-01-15 at 4 35 57 am](https://cloud.githubusercontent.com/assets/191731/21962162/255c49e0-dadc-11e6-80b7-36dd0180bbd0.png)
3. Toggle back to WYSIWYG. SCEditor tries to render this as a mention.
![screen shot 2017-01-15 at 4 37 42 am](https://cloud.githubusercontent.com/assets/191731/21962169/63311732-dadc-11e6-93e7-421142dfb293.png)
4. Toggle to source mode again. Now the `<a>` get converted to an `[attach]` BBCode!
![screen shot 2017-01-15 at 4 39 09 am](https://cloud.githubusercontent.com/assets/191731/21962176/971d9b7e-dadc-11e6-8ced-9dececaf8a0e.png)

This issue does not only affect toggling between editor modes. It also affects the actual data passed to SMF's preparser (and therefore also the data that will be saved in the database). To see this, just get a post preview at any point in the process outlined above. Try to get a preview after completing step 1 above, and you will see this:
![screen shot 2017-01-15 at 4 47 23 am](https://cloud.githubusercontent.com/assets/191731/21962222/bbdee52a-dadd-11e6-8bce-e38fc4941c90.png)
Try after completing step 3, and you will see this:
![screen shot 2017-01-15 at 4 49 08 am](https://cloud.githubusercontent.com/assets/191731/21962231/fa1297c4-dadd-11e6-81e9-3a145df9c45d.png)

**Comment by Sesquipedalian** [comment]
It looks like this bug was introduced in #3714. Reverting the changes to jquery.sceditor.bbcode.min.js seems to resolve the problems. I guess something in the latest version of that file is incompatible with the customizations we've made in jquery.sceditor.smf.js. @colinschoen

**Comment by XinYenFon** [comment]
Are you sure its related to SCEditor ? My wild guess says, after new version we need some changes in [jquery.sceditor.smf.js](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/scripts/jquery.sceditor.smf.js) as well

**Comment by Sesquipedalian** [comment]
Yes. As I said, 

> Reverting the changes to jquery.sceditor.bbcode.min.js seems to resolve the problems. I guess something in the latest version of that file is incompatible with the customizations we've made in jquery.sceditor.smf.js.

Something about the changes in jquery.sceditor.bbcode.min.js between version 1.4.7 and 1.5.2 are not compatible with what we currently have in jquery.sceditor.smf.js. Either we need to roll jquery.sceditor.bbcode.min.js back to version 1.4.7, or else we need to update jquery.sceditor.smf.js to make it compatible with version 1.5.2 of jquery.sceditor.bbcode.min.js. 

Obviously, the latter idea is the better one. But I'm not likely to have the time and energy to implement it in the next little while. If someone else wants to tackle it soon, that'd be great. Otherwise, we should probably roll back for now and then later update both JavaScripts in one commit.

**Comment by XinYenFon** [comment]
There is an issue which we reported, fixed in 1.5.x release, so turning back is not a real option.

**Comment by Sesquipedalian** [comment]
Okay. Well, hopefully @colinschoen will have a chance to fix it soon. :)
