### ISSUE TITLE
SCEditor incorrectly formats and interprets [list] BBCode

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#3844]
Similarly to #3843, inserting a bullet list into a post in WYSIWYG mode doesn't work properly.

1. Insert a bullet list. Initially, all looks well.
![screen shot 2017-01-15 at 5 04 32 am](https://cloud.githubusercontent.com/assets/191731/21962317/2528b87e-dae0-11e6-9ea4-ebbeb79a663e.png)
2. Either get a preview or just toggle the editor into source mode. You will see that instead of converting your `<ul>` into a simple `[list]` BBCode, it will convert it to `[list type=none]`.
![screen shot 2017-01-15 at 5 08 42 am](https://cloud.githubusercontent.com/assets/191731/21962341/b789ac3c-dae0-11e6-8eec-8df7edb2af9b.png)
![screen shot 2017-01-15 at 5 09 16 am](https://cloud.githubusercontent.com/assets/191731/21962344/c9da2c4a-dae0-11e6-85f1-de69d1c1fbf6.png)

As with #3843, the problem appears to have been introduced in #3714, and disappears if one reverts those changes to jquery.sceditor.bbcode.min.js.

**Comment by ThomasFok** [comment]
I found the cause of the problem.  

Themes/default/scripts/jquery.sceditor.smf.js line 277-282
```javascript
format: function (element, content) {
	if ($(element[0]).css('list-style-type') == 'disc')
		return '[list]' + content + '[/list]';
	else
		return '[list type=' + $(element[0]).css('list-style-type') + ']' + content + '[/list]';
}
```

The css() function should return 'disc' but it returns 'none'.  Since the default value of list-style-type is 'disc', I have no idea why the function return 'none'.

**Comment by Sesquipedalian** [comment]
That's helpful, @ThomasFok. Perhaps it is because index.css defines `list-style-type: none` as the default for lists.

**Comment by Sesquipedalian** [comment]
If so, maybe a fix would be as simple as adding a scoped definition in the CSS to make `list-style-type: disc` the default inside the editor.

**Comment by Oldiesmann** [comment]
Here's a diff of the two versions of jquery.sceditor.bbcode.min.js (un-minified): https://www.diffchecker.com/TCE3rbLL. I'm not sure what changed exactly to make it do that. I compared the two versions of jquery.sceditor.smf.js and nothing really changed there. It does look like we can get around the issue with CSS, but I'm curious as to why that wasn't necessary before.

**Comment by ThomasFok** [comment]
If `list-style` in index.css is changed to `disc`, it works. But I cannot find a proper scoped CSS rule that can fix the problem. `.sceditor-container ul{}` does not work.

**Comment by ThomasFok** [comment]
I found a workaround for the problem. When the `[list]` bbcode is converted to html, a style attribute which stores the list-style-type is added to the ul tag.   So, we may get the list-style-type from there.

I have the code already and it seems to work. I can post the code if nobody can find a better fix.

**Comment by Sesquipedalian** [comment]
Instead of index.css, try adding the rule to jquery.sceditor.css. I think that might work better.

**Comment by Sesquipedalian** [comment]
Sorry, I meant jquery.sceditor.default.css. That's the one that styles inside the editor's iframe.

**Comment by ThomasFok** [comment]
Adding `ul{list-style-type:disc;}` to  jquery.sceditor.default.css  does not work.

Then, I tried adding this to jquery.sceditor.default.css. The list bullets did change to circles. 

```css
ul, ol {
	list-style-type: circle;
}
```

![image](https://cloud.githubusercontent.com/assets/25267431/22303896/3f399ca4-e370-11e6-8ae1-dae3d0e33cea.png)

Switching to source mode, it still showed `type=none`.

![image](https://cloud.githubusercontent.com/assets/25267431/22303937/6b011a10-e370-11e6-9748-b9fb7f35c970.png)

I think the root of the problem is inside jquery.sceditor.bbcode.min.js.

**Comment by sbulen** [comment]
There is some pre-processing of list-style-type in sub.php & subs-editor.php.   Might be worth a look.

**Comment by Sesquipedalian** [comment]
Oh hey, I just solved it. :) #3868

**Comment by Sesquipedalian** [comment]
Turns out it was just a matter of adding a test for when the style attribute was undefined. That way we don't have to worry about inherited values, but only whatever has been explicitly set on the element itself.

**Comment by ThomasFok** [comment]
@Sesquipedalian, it is a good fix!
