### ISSUE TITLE
Upgrade not informative window

### ISSUE THREAD

**Issue by Mavn** [SimpleMachines/SMF#3846]
When I upgrade forum I have window with error, but I haven't any information what I need to do to fix error.
I think need provide more information to help fix problem with upgrade
![2017-01-16_11-15-24](https://cloud.githubusercontent.com/assets/2140726/21975356/45a17c00-dbdd-11e6-805a-f9ef5143f220.png)

**Comment by Dzonny** [comment]
Well, there's a note that you should upload all directories found in package, ay?
Also, upgrade script is being worked on, and you're using some language pack from what I can see from the image?

**Comment by Mavn** [comment]
Yes I uploaded all directories and files... This happen when in Settings.php database type set is mysqli.
But now I see this error is fixed. Thanks
