### ISSUE TITLE
Upgrade: missing image in final step

### ISSUE THREAD

**Issue by Mavn** [SimpleMachines/SMF#3847]
Latest files from git.
In final step of upgrade.php I have missed image
![2017-01-16_12-17-31](https://cloud.githubusercontent.com/assets/2140726/21977141/fe9790f2-dbe5-11e6-9491-b9613f17f7c9.png)

**Comment by sbulen** [comment]
The image is "blank.png".   It appears to be a dummy stub to hang the checkbox button off of.  It's located in the themes/default/images directory.   It would be missing if you didn't copy the entire Themes directory to your install location.

Look here:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L4484

Can you still produce this error?   If so, can you confirm the presence of blank.png in themes/default/images?

**Comment by Oldiesmann** [comment]
The blank.png is there to serve as a placeholder for deleting the upgrade. When you check the box, the URL to that image is changed to the URL for deleting upgrade.php. However, at the end of the steps to delete the files, it's supposed to redirect you to blank.png again.

```js
			<script>
				function doTheDelete(theCheck)
				{
					var theImage = document.getElementById ? document.getElementById("delete_upgrader") : document.all.delete_upgrader;
					theImage.src = "', $upgradeurl, '?delete=1&ts_" + (new Date().getTime());
					theCheck.disabled = true;
				}
			</script>
```

Line 557 of upgrade.php:
```php
		header('Location: http://' . (isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : $_SERVER['SERVER_NAME'] . ':' . $_SERVER['SERVER_PORT']) . dirname($_SERVER['PHP_SELF']) . '/Themes/default/images/blank.png');
```

If you're getting a broken image there then either something failed prior to that header() statement being called, or the URL was guessed incorrectly. If it happens again, right-click on the image and find out what URL it's trying to access, and compare that to the actual URL of the upgrade file.

**Comment by XinYenFon** [comment]
I can't reproduce this issue, is this a valid issue or server config problem ?

**Comment by NanoSector** [comment]
Can't reproduce either.

**Comment by frandominguezl** [comment]
Same here. Maybe this needs to be closed; @colinschoen
