### ISSUE TITLE
Installer & Upgrader - Enhancement suggestion: set DB default collation

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3848]
I think the installer & upgrader should suggest & set the database-level default collation to something practical & meaningful, like UTF8_general_ci.  One of those installer/upgrader little checkmarks, and default it to making the change.  Force the person to uncheck it if they know what they're doing.   Remember - most won't...

I think most folks just let the DB stay at defaults, and with MySQL that is still latin1_swedish_ci.  This definitely led to issues with 2.0 - just look at all the collation issues in the support forum.   Most mod developers don't pay attention to this, so when adding mods, the new tables end up being in different collations & even charsets than the rest of SMF; this happened to my forum.   _This will be much worse in SMF2.1+, where we are pushing them towards UTF8._  

I'm willing to bet that 99% of the forum admins will let all the defaults stand, and we will end up with latin1_swedish_ci mod tables all over the place.  

I think 99% of the time, these DBs are dedicated to SMF.  A good default will solve lots of problems down the road.  

As it stands now, I let the defaults stand for testing purposes, and all my SMF2.1 databases, even the brand new vanilla installs, still have the MySQL latin1_swedish_ci default.   This sets the default charset to latin1 (ISO 8859-1) and the default collation to latin1_swedish_ci.  

The screenshot below shows the default collation setting for my test SMF DBs:
![collations](https://cloud.githubusercontent.com/assets/23568484/22001718/ad238512-dbfb-11e6-984b-756cb92072f4.JPG)

**Comment by sbulen** [comment]
In my vanilla 2.0 upgraded to vanilla 2.1 DB, the backup tables created by the upgrader used the default, and ended up with the wrong charset/collation.  Look at the type, too...
![collations2](https://cloud.githubusercontent.com/assets/23568484/22001939/f8f92270-dbfc-11e6-9e99-f7ab1d9c9d6b.JPG)
:

**Comment by Oldiesmann** [comment]
Definitely something worth looking at. For new installs we can set the default charset and collation for the database if there aren't any other tables in that DB, and we should at the very least be forcing the correct values for the tables we create, as well as any tables created by mods.

**Comment by Oldiesmann** [comment]
Looked into this further, and we're already doing that actually...

Lines 1077-1082 of install.php:
```php
		// If the UTF-8 setting was enabled, add it to the table definitions.
		if (!empty($databases[$db_type]['utf8_support']) && (!empty($databases[$db_type]['utf8_required']) || isset($_POST['utf8'])))
		{
			$replaces['{$engine}'] .= ' DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci';
			$replaces['{$memory}'] .= ' DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci';
		}
```

Also, we're already doing that for tables created by the upgrade (lines 1643-1645 of upgrade.php) and tables created by mods (lines 173-174 of Sources/DbPackages-mysql.php).

If your tables are still being created with latin1_general_ci as the charset/collation then something's wrong. Are you using the files from GitHub?

**Comment by sbulen** [comment]
Yes, using the latest files from github.  This is a longstanding issue, affecting 2.0 as well.  

The SMF tables are all properly built.  The backup tables are not - they are somehow using the DB default.  

In the long run, I am more worried about mods.  Most of my installed mods' tables had the wrong type.  I guess they don't all use the techniques provided.   

But setting the DB-level default will fix that.  _We will see far fewer charset & collation issues in the support forum in the long run.  That's the goal._  

(I'm referring to the DB setting, not the SMF settings or individual table settings, e.g:
> CREATE/ALTER DATABASE mydb
>   DEFAULT CHARACTER SET utf8
>   DEFAULT COLLATE utf8_general_ci;

)

If this is not specified, MySQL still defaults to ISO 8859-1 and latin1_swedish_ci.

**Comment by Oldiesmann** [comment]
We don't support charsets/collations in 2.0 (unless you install with UTF-8 support or convert the database to UTF-8 through the admin center. The reason for this is that when 2.0 was released, MySQL 4.0.x was still fairly common, and MySQL 4.1 was the first version to support charsets/collations. 

When you install 2.1 or upgrade from 2.0 all the tables should have utf8 charset by default, and we already have code to do that for new tables as well. The only way that won't happen is if your server isn't configured properly or $db_character_set isn't defined in Settings.php.

**Comment by sbulen** [comment]
MySQL server level settings still default to ISO 8859-1 and latin1_swedish_ci.   Of course, this can be overridden at the DB level or the table level.   SMF does a good job of overriding at the table level for its base tables.  

If you do not override that at the DB or table level, your tables will use ISO8859-1/latin_swedish_ci - as we have seen, even the SMF backup tables are built incorrectly.  

It is safest/smartest in the long run to set the SMF DB defaults appropriately.   So anyone creating new tables (mainly mods, sometimes SMF) will end up with the right table characteristics even if they do not specify charset/collation.

**Comment by albertlast** [comment]
To be ownest I don't understand the issue.
Because we call "set names utf8" in the upgrade phase: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L465
This inform the database that we use utf8 and the database do the conversion stuff between smf and
the existing collation/charset.

**Comment by sbulen** [comment]
"set names UTF8" is temporary.  And you have to remember to do it each & every single time.  Most mod folks don't.  This will cause problems for SMF users down the road.   Even the SMF team doesn't always remember to do it - _look at the backup tables in the screenshot above_.  

Setting a good default at the DB level makes things much, much safer in the long run, and will reduce support issues.   I've been watching the support forum for the last couple of years, and I have seen many charset/collation issues.  Just do a search on the forum.   

It will get much, much worse once we push folks towards UTF8.   Why will it get worse?  Because every time someone forgets to do a set names, you will get the MySQL defaults.  Even under the upcoming MySQL 8.0, the defaults are ISO8859-1/latin1_swedish_ci.  

I'm suggesting that early in the Install or Upgrade process, if the defaults are still latin1/latin1_swedish_ci, that we suggest setting the DB defaults to UTF8/UTF8_general_ci with a CREATE or ALTER DATABASE command.   

_I'm thinking long-term support, beyond just the install/upgrade._

**Comment by sbulen** [comment]
(FWIW, I think the backup issue is caused by the use of CREATE TABLE xxx LIKE xxx...   Which I think defaults to the DB default charset/collate.  Which, if left alone... )

**Comment by sbulen** [comment]
Let me illustrate with a real-world example.  I just installed a vanilla 2.0.13 SMF, and installed 3 mods.  UTF8 was selected upon install.  

_I don't mean to pick on anybody, I chose 3 mods _at random_..._  

**_Scenario 1:  Without touching anything else, installed 3 mods.  DB default collation was latin1_swedish_ci.   2 of the 3 mods installed their tables with latin1_swedish_ci._**

![scen1-1](https://cloud.githubusercontent.com/assets/23568484/22233476/417ef0f8-e1a5-11e6-94b7-e96c5fc64c1b.JPG)
![scen1-2](https://cloud.githubusercontent.com/assets/23568484/22233473/41799ef0-e1a5-11e6-82ce-e92baec9ddb9.JPG)
![scen1-3](https://cloud.githubusercontent.com/assets/23568484/22233474/417ae2e2-e1a5-11e6-8f66-1ae9271bb04e.JPG)
![scen1-4](https://cloud.githubusercontent.com/assets/23568484/22233475/417ae738-e1a5-11e6-82fb-331c0c17976a.JPG)


**_Scenario 2:  I set the DB-level default collation to utf8_general_ci, and installed the same 3 mods.   This time, all 3 mods installed their tables with utf8_general_ci._**  

![scen2-1](https://cloud.githubusercontent.com/assets/23568484/22233478/4859a10c-e1a5-11e6-946a-673289a2b5d2.JPG)
![scen2-2](https://cloud.githubusercontent.com/assets/23568484/22233479/486afe70-e1a5-11e6-821c-5c22216d2b98.JPG)
![scen2-3](https://cloud.githubusercontent.com/assets/23568484/22233480/4875e16e-e1a5-11e6-82ee-7c861db6ece7.JPG)
![scen2-4](https://cloud.githubusercontent.com/assets/23568484/22233481/48798dd2-e1a5-11e6-80b3-e0646263e407.JPG)

**Comment by Oldiesmann** [comment]
In SMF 2.1, as I explained above, all tables are created with utf8 by default. Even tables created by mods (assuming they use SMF's table creation function, which most do). 2.0 is completely different and we won't be changing how things work in that version.

**Comment by albertlast** [comment]
additionaly the set names is called in the intializing of the database connection (for mysql and pg) and
so the mods doesn't need and shouldn't do the same again.

**Comment by sbulen** [comment]
SMF's number 1 download was in my test above.   SMF has also been shown to create tables incorrectly above.

The very simple solution fixed the problem.   I don't understand the reluctance to set a default value.

 I didn't have 2.1 mods to test with, but I predict similar results in 2.1.  

It's human nature.

**Comment by albertlast** [comment]
btw your "ok" solution is not okay, because the default database engine in smf is now innodb and
on you screenshot we can see that is myisam.

**Comment by sbulen** [comment]
All those tables were created by SMF.  

Collation & charset are correct.

This was a 2.0 example for the reasons described above.   Mysql 5.6, which I think still defaults to myisam.

**Comment by albertlast** [comment]
the smf2.1 setup set default innodb.
when this is a new installation something goes wrong on your side.

**Comment by sbulen** [comment]
The examples above are 2.0 for the reasons described above.  (The lack of 2.1 independently-developed mods to demonstrate with.)   

This discussion focuses on charset/collation.   

Even so...  Which would you prefer - a table in which the engine & charset/collation are all wrong, OR, a table in which the charset/collation are correct & the engine is wrong.   One of these two choices may result in corrupt data.

**Comment by albertlast** [comment]
innodb than, because the amount of currupt data is lowed
reason is that acid valid, myisam not.

**Comment by sbulen** [comment]
OK guys, I think I'll drop the torch for now.   Interesting discussion & thanks for your time.  I learned a lot.

I think the root cause of the disagreement is that we look at this from two radically different perspectives:  
  -  You believe the SMF functions cover all the bases.  And they do.  I agree 110%.  And mod developers should use them.  In fact, I'd say the SMF folks provide **_outstanding_** technical solutions, especially on the DB & security fronts.  
  -  My concern is that there are lots of mod developers who don't & won't.  And we can, in fact, protect our users from potential issues with a simple default.  I don't want to depend on that default.  But I want it there as a safety net.  I believe it will reduce support issues with 2.1.  

But this has probably generated more discussion than it's worth! 

At the very, very, very least...  We should probably figure out why the upgrader sometimes builds backup tables with the wrong characteristics...  My 2.0 DB is running in a vanilla MySQL 5.6 environment.  Although the source tables are already UTF8, the backup tables created during the upgrade to 2.1 are latin1.  Somehow it's using MySQL's defaults.  The backups may not be usable.

**Comment by Oldiesmann** [comment]
The backup thing should be pretty easy to fix. I'll look into that when I get a chance in the next couple of days.

**Comment by sbulen** [comment]
Thanks @Oldiesmann & @albertlast .   

I'm feeling rather chagrined at the moment on the backup note.  

I just did a whole barrage of tests, & the backups that were latin1 SHOULD have been latin1 - as they were latin1 BEFORE the upgrade...  And a backup should properly capture it in its untouched state.  

However...   My 2.0 MyISAM tables remained MyISAM tables after the upgrade (though properly converted from latin1 to UTF8).  If we wish those to be InnoDB after migration, that might require work on the upgrader.  

I'll write that up separately.
