### ISSUE TITLE
Upgrade: forum don't work after upgrade process ended.

### ISSUE THREAD

**Issue by realdigger** [SimpleMachines/SMF#3854]
After upgrade process ended, Settings.php have this line which cause critical error
`$upgradeData = #remove#;`

**Comment by Mavn** [comment]
I have same problem

**Comment by sbulen** [comment]
This is a dupe of this issue:
Upgrader - : unserialize(): Error at offset 0 of 15 bytes in ... upgrade.php on line 125 #3841

I've submitted a fix, but we're discussing whether it needs a better approach over in the PR:
Set $upgradeData to null after successful upgrade #3849

**Comment by Oldiesmann** [comment]
Duplicate of #3841
