### ISSUE TITLE
Users with no avatar - broken links in 2.1

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3858]
Lots of users have "no avatar" chosen for their profiles in my 2.0 forum.  

Upon conversion to 2.1, despite the "no avatar" setting, it is attempting to load an avatar of default.png for these users.  Since I don't have one, I have lots of broken links displayed in user profiles by their posts.  

I can't tell if this is a bug or if it is desired behavior in 2.1-think...  

Does "No avatar" now mean default.png?   Should it?   Are we supposed to create one?

I see there is a default.png in the vanilla avatars folder.  But if we're upgrading, we likely want to keep our existing avatars folder...   I wonder if we simply need to tell folks to copy & merge with their existing folder.

![image](https://cloud.githubusercontent.com/assets/23568484/22135293/2b4daa2a-de82-11e6-98c4-7f6c68c79e3b.png)

**Comment by illori** [comment]
by default you should have the default avatar https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/avatars/default.png
SMF 2.1 has a default avatar, by default for anyone that does not have an avatar selected. if you dont have that file you should upload it.

**Comment by sbulen** [comment]
On launch, we likely need to include a note on that in the install instructions.  Or maybe an accompanying FAQ.  

Most - probably all - folks will see broken links throughout their forums after upgrading.   

I'm trying to think ahead what will make it more successful support-wise upon launch...

**Comment by sbulen** [comment]
Just something to keep in mind upon launch...
