### ISSUE TITLE
Some inconsistencies with URLs

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#3859]
1) Go to your Profile > Forum Profile > Website URL and try to put an URL without http:// or https://, when you try to save changes, it won't allow you.

2) Create a new redirect forum and put an URL without http:// or https://. No error displayed, but the redirection doesn't work.

As same as for custom avatar, a possible solution would be add by default http:// to the URL fields.

**Comment by illori** [comment]
why would you use such a URL when you know the complete URL to enter? i dont think this is a bug it is a user not entering the correct URL in the field.

**Comment by XinYenFon** [comment]
Especially when SMF does not support schemeless url.

**Comment by frandominguezl** [comment]
How'd users know that? If we include http:// in the custom avatar URL, why not in the other URL fields?

**Comment by XinYenFon** [comment]
This issue is not related to SMF but browsers due to input type url.
