### ISSUE TITLE
MySQL errors on Install Step 3 + can't proceed with the install

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#3881]
Fresh GitHub install, got this two errors at the top of Step 3.

Warning
: mysqli_real_connect(): (HY000/2002): No existe el fichero o el directorio in
/opt/lampp/htdocs/beta/Sources/Subs-Db-mysql.php
on line
75

Warning
: mysqli_real_connect(): (HY000/2002): No existe el fichero o el directorio in
/opt/lampp/htdocs/beta/Sources/Subs-Db-mysql.php
on line
75

No existe el fichero o el directorio in = "File or directory doesn't exist in"

And I can't proceed with the install... I'm using XAMPP for Antergos and PHP7, got this error:
Cannot connect to the database server with the supplied data.

If you are not sure about what to type in, please contact your host.

There's no error possibility since the user is root and there is no password set.

**Comment by sbulen** [comment]
This error now: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '} } updateSettings(array('langList' => json_encode($newlangs)))' at line 1

![image](https://cloud.githubusercontent.com/assets/23568484/22392693/0efe20ae-e4b1-11e6-8680-1dc85f9f44f9.png)

**Comment by sbulen** [comment]
I wasn't able to reproduce this just now.   
(Install seems clean, it's upgrader that's acting up...)

My initial thought is to make sure you start with an empty (or no) database, and a completely fresh set of files.    

INCLUDING Setting.php....  Use the "blank" settings.php from the other directory.  I'm pretty sure this is where all the logon info is coming from.  

Hope this helps...

**Comment by Oldiesmann** [comment]
Make sure the mysqli.default_sock setting is correct in php.ini. That seems to be one of the most common issues causing that error

**Comment by frandominguezl** [comment]
@sbulen Everything was brand new. I installed a new OS on my laptop and I had nothing on it, not even XAMPP.

Apparently the error is now gone without touching anything. Weird :smile:

**Comment by sbulen** [comment]
It woke up cranky.   It happens.
