### ISSUE TITLE
upgrade.php forum language mysql error

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3884]
*  +++  Update the forum language listUnsuccessful!  Database error message:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '$langlist = json_decode($modSettings['langList'], true)' at line 1

**Comment by sbulen** [comment]
This was another symptom - please try again with a fresh set of files.

**Comment by illori** [comment]
this is resolved.
