### ISSUE TITLE
Wrong character encoding for cyrillic after quick edit message

### ISSUE THREAD

**Issue by realdigger** [SimpleMachines/SMF#3897]
![screen](https://cloud.githubusercontent.com/assets/1187218/22407529/9ec33ad6-e681-11e6-9a55-c7e19efacbc8.png)

**Comment by frandominguezl** [comment]
This is supposed to be solved with #3888

**Comment by realdigger** [comment]
> This is supposed to be solved with #3888

I dont see any related code edit

**Comment by albertlast** [comment]
he means #3886

**Comment by realdigger** [comment]
This fix works
