### ISSUE TITLE
Upgrader:  New tables hard-coded to MyISAM

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3899]
If I have an SMF instance that is already using MySQL & InnoDB, and run the upgrader, all new tables are created with MyISAM.  This is because the scripts are hard-coded to MyISAM.  So we end up with a mix of engine types.  

Question:  Should we remove the hard-coded ENGINE=MyISAM clauses?
 - If we leave it as-is, the administrator will have to catch it & manually convert to InnoDB.   
 - If we remove the hard-coding, it should default to the server setting, which may or may not be InnoDB.   
 - In an ideal world, this should probably be an SMF setting with a default.  

@albertlast - I'd appreciate your input.

**Comment by albertlast** [comment]
well i see not solution in any way,
normaly when you came from smf 2.0.x your table are myisam,
to keep in flow it would be okay i guess to keep in myisam.
On the other hand tables created by the smf api will be innodb... 
so i had no good idea for this "issue"

**Comment by sbulen** [comment]
I agree.  Thanks for the input.  

Like my previous MyISAM-related question (Upgrader - Tables remain MyISAM after upgrade #3867), at this point, this is likely best left up to the administrators who know enough to pay attention to it...

I don't think there's anything fatally wrong with mixed engines.  (Although inconsistencies bother me...  I'll get over it...)

I'll close this out.
