### ISSUE TITLE
As a Notice ...

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3900]
Today we tested our Forum/Portal release with PHP 7 and also PHP 7.1.
All works as very well .. with PHP 7 no problems, with PHP 7.1 we must change  vartypes a little bit.
Seem like PHP 7.1 is very critical on var types, so you can't use var = ''; if you use this later as a array.
So it's need to init vars correctly ...

**Comment by XinYenFon** [comment]
Can you post an example code (old-new) ? Thanks.

**Comment by PortaMx** [comment]
// if you use (as example)
$myvariable = '';
$data = array(0 =>'more', 1 => 'test');
$myvariable = $data; **// here comes the error !!**

$myvariable = array();
$data = array(0 =>'more', 1 => 'test');
$myvariable = $data; **// this works correct !!**

**Comment by Oldiesmann** [comment]
Why would you initialize something as a string if you intend to assign an array to it later on?

**Comment by PortaMx** [comment]
it was a very old code they have worked without problems before PHP 7.1 ...
