### ISSUE TITLE
Upgrader:  Various issues impacting stability & performance

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3901]
I'm still looking at the upgrader.   I was wondering why sometimes you get the "30 seconds" exception & sometimes you don't.  I looked more closely at the issues, & under the covers, there are a number of things big & small that should be fixed.   The upgrader somehow forces its way through it...  I'm a little surprised it completes successfully.  

Over the next few days I'll be testing & submitting fixes to these issues.

Some examples that I found upon reading the code near 30-sec dropouts:
(1) ~~Syntax error creating the mentions table.~~  Edit - mentions table is OK 
(2) Mentions table is built differently in the upgrader than in the installer.
(3) log_topics.  First the unwatched col is created.  No problem.  But then there is a verb that tries to rename a non-existent column (disregarded) to unwatched.  This will always fail, first, because disregarded doesn't exist, and second, because unwatched does.   
(4) Drops columns before the index it's exclusively used in (one example: member_ip_old).  Since the column is gone, the index is gone & dropping the index is a syntax error.   Reversing the order will be more efficient & will not have syntax issues.  
(5) Speaking of which, it drops the index on the messages table, where it created it on the members table...   

I think the root cause here is that these statements are run indirectly by the upgrader, and the errors are very well hidden & easily missed.  If I can figure out how to make these more visible & debuggable, I'll do so...

**Comment by illori** [comment]
disregard did exist in prior versions of SMF 2.1 so it does not hurt to have that part still there for those that did use that version.

**Comment by sbulen** [comment]
I figured it was an old column.   But this will never remove the disregarded column, even if it still exists, due to the syntax.   It basically says:
  -  create unwatched
  -  rename disregarded to unwatched      <= this will always fail, since unwatched will exist already

We could either try the rename first or explicitly delete it.  But the existing code will not accomplish what is desired.

**Comment by sbulen** [comment]
The upgrader definitely allows for reruns.  upgrade_query(), line 1863+, is written to ignore errors like dropping tables that don't exist, and adding column names that already exist.  

But at some point, it appears the upgrader stopped reporting ALL errors.  And some of these are pretty bad, like the syntax errors.  

It'd be nice if it ignored what we wanted it to ignore, and reported all other errors.  

Some are causing the upgrader to hang a bit - hence the 30 sec timeout warnings.  (A side note: I only get the warnings on my InnoDB install.  Apparently it is more strict than MyISAM.)

**Comment by sbulen** [comment]
Updates...   
  -  As discusssed in the PR Some installer & upgrader tweaks #3905, the mentions table issue is not a syntax error.  So this is a good thing - it's working.  
  -  I have confirmed that php code eval'd by the upgrader properly reports a syntax error when given a syntax error.  (The primary eval() for php defined in our .sql files is on line 1791, in parse_sql(), in upgrade.php.)  This is also a good thing - it's working.
  -  What's not working:  I have confirmed that the upgrader ignores all errors in sql code.  It erroneously reports success and moves to the next step.  (sql defined in our .sql files is executed on line 1819, in parse_sql(), which invokes upgrade_query() in upgrade.php.)

upgrade_query() will process the Lumberjack Song as if it were valid sql.  I think it should report an error, as occurs with invalid php.  

The heart of the issue is in the first 10 lines or so of upgrade_query() in upgrade.php.   When the smcFunc for db_query is invoked, it is invoked with 'db_error_skip' => true.   So no matter what happens, the $result is null.  Not false, null.  So it falls through all of the other logic and just moves on.  

Interestingly, $mysqli_errno is always 0, on line 1882 of upgrade.php, causing it to float past all of those checks.   (This is where it is intended to allow drops on non-existent tables/columns, etc., allowing for reruns.  Instead, it actually ends up allowing ANYTHING...)

I thought the fix would be as easy as changing  'db_error_skip' => false, on line 1871, but the logic in subs_db_mysql.php issues a die() on line 734 in smf_db_error() under these circumstances, causing upgrade.php to hang indefinitely.  

Still researching options to restore error checking on sql in the upgrader.  Input welcome.

**Comment by sbulen** [comment]
Final note on this topic!   Turns out the error processing on SQL is just fine.   
(I now know firsthand that it will NOT let you process The LumberJack Song...)

My biggest concern here is that on my fairly modest mid-sized forum, I got several of the "Error! the server has not responded in 30 seconds...." messages.  

Truth is, many of the very complex update queries come back in about 4-10 seconds.  
And the upgrader is not really comparing them to 30 seconds, it was actually comparing them to 3 seconds and telling you it was 30 seconds...  

So, I'll submit a PR to make it REALLY check for 30 seconds...   

I tested the change out & it feels more honest & less panicky.   All you have to do is leave it alone & let it run.  

In the future, if we get more folks with larger DBs complain about too many messages, we may want to change this to 60 seconds instead of 30.
