### ISSUE TITLE
Scroll don't work on small screens

### ISSUE THREAD

**Issue by realdigger** [SimpleMachines/SMF#3903]
```
@media (max-width: 480px) {
	/* Stay where you are in mobile popup enabled */
	body {
		overflow: hidden;
	}
```
Why scroll disabled here? Forum unusable on small screens.

**Comment by frandominguezl** [comment]
What is the exact size of the screen you're having problems with?

**Comment by realdigger** [comment]
480x800
You can resize desktop browser window to see this issue.

**Comment by colinschoen** [comment]
@d3vcho Are you taking this?

**Comment by frandominguezl** [comment]
@colinschoen Nope. Will leave it to @Antes , better
