### ISSUE TITLE
Alert Notifications don't show up?

### ISSUE THREAD

**Issue by kat-kta** [SimpleMachines/SMF#3911]
Noticed that users of my beta 3 test site didn't get any notifications on their alerts. How are they supposed to be set up? What does the number of the "Timeout for Alert desktop notifications" mean? Is it like minutes or something? How are the alert notifications even supposed to appear? Does the server require any specific additional software to support them? I've searched a bit but didn't find much about this. Just a heads up to the devs over here~ Thx for answers~

**Comment by Oldiesmann** [comment]
Alerts work as part of a system known as background tasks. Each time someone visits your forum, SMF calls a file called "cron.php" (located in your forum directory), which in turn checks the database for any background tasks that need to be run and tries to run them.

The best way to ensure notifications work properly is to set up a cron job to call cron.php (`php /path/to/cron.php`) every so often (how often depends on many things such as how active your forum is - if your forum isn't very active there's no point in calling it very frequently). That way the file will always get called at a certain interval regardless of whether your forum is active. If you're not sure how to set up a cron job, ask your host for help.

Desktop notifications are an entirely different. This is a feature supported by many web browsers (Google Chrome and Mozilla Firefox for sure; not sure what other browsers support it) that shows a notification within the browser for something even if you're not viewing the site that the notification is associated with at the time. The "Timeout for Alert desktop notifications" setting specifies the number of seconds to display the alert before closing it.

The alert notifications will appear at the top left in the box marked "Alerts". The "Desktop Notification" will appear in the bottom right-hand corner of your browser window.

No additional software is needed to support them.

I apologize for the lack of documentation, but SMF 2.1 is still in development and we don't recommend using it on live sites unless you know what you're doing and are willing to live with things that may not work properly yet. Once we get closer to a stable release I'm sure we'll have better documentation available for this feature.

**Comment by kat-kta** [comment]
Thanks for a quick reply~ Yeah I've read a bit about cron but asking my host = askin myself since I got the server in the basement. It's just that when you click on the "Alerts" button the first time, a prompt pops up and requests permission to send notifications, however, they never appear (even after waiting while keeping an eye open for them). I'll check out cron.php to see what's it all about.
Regarding 2.1, gladly I am running it on a test directory and made it clear to the users willing to take a look at it to report bugs so I can forward them to you guys, and documentation is no biggie since I can ask ya for uncertian things here~ Thanks for ya answers!

**Comment by Oldiesmann** [comment]
The thing asking to show notifications is the browser prompt to allow the site to show desktop notifications. It's not related to whether SMF shows alerts in the proper area

**Comment by sicommnend** [comment]
In order for true desktop level notifications when your not on the site you need a service worker and https. The specification is not complete yet and I already had to do a few rewrites on my code for my service worker.

`
if (!defined('SMF'))
	die('Hacking attempt...');

// Browser Service Worker Main
function ServiceWorkerMain() {

	global $smcFunc, $scripturl, $boardurl, $user_info, $user_settings, $context, $modSettings;

	loadTemplate('ServiceWorker');
	// Tell the rewriter please don't try to parse this.
	$context['ob_rewrite_compat'] = true;
	// We set our content type, SMF doesn't support this but this site does.
	$context['content_type'] = 'application/javascript';
	// Service Worker .htaccess has this as sw.js. We also set a cached image to autostart the service worker when stalled.
	if (isset($_REQUEST['js'])) {
		$sw = array(
			'ver' => 'SICommSW-2017-02-07',
			'cache' => array(
				'/img/viral/site_thumb.svg',
				'/Themes/Minimalism_smf20rc4/css/index.css',
				'/Themes/Minimalism_smf20rc4/scripts/index.js',
				'/Themes/Minimalism_smf20rc4/jquery/jquery.js',
				'/Themes/Minimalism_smf20rc4/jquery/jquery.sidr.min.js'
			)
		);
		//event.respondWith(caches.match(event.request).then(function(response) {if (response) {return response;}return fetch(event.request);}));
		//return response || fetch(event.request);
		//var fetchRequest = event.request.clone();return fetch(fetchRequest).then(function(response) {if(!response || response.status !== 200 || response.type !== \'basic\') {return response;}var responseToCache = response.clone();caches.open(\''.$sw['ver'].'\').then(function(cache) {cache.put(event.request, responseToCache);});return response;});
		$context['SWNotify'] = 'var time=new Date().getTime();importScripts(\''.xpath_urls_filter($scripturl.'?action=service-worker').'?notify=\'+time);var int=0;setInterval(function(){time=new Date().getTime();importScripts(\''.xpath_urls_filter($scripturl.'?action=service-worker').'?notify=\'+time)},3600000);var paths = [\''.implode('\',\'', $sw['cache']).'\'];caches.open(\''.$sw['ver'].'\').then(function(cache) {return cache.addAll(paths);});self.addEventListener(\'fetch\', function(event) {});';
	// Notifications - notification request time is sent in notify, no real use for this besides preventing caching.
	} else if (isset($_REQUEST['notify']) && $context['user']['is_logged'] && (!isset($_SESSION['log_notify']) || isset($_SESSION['log_notify']) && (time() - $_SESSION['log_notify']) > 600)) {

		// Notifications on topics
		// Yes we are doing a select within, SMF doesn't like this.
		$modSettings['disableQueryCheck'] = 1;
		// All the topics with notification on... Not correct need to fix.
		$request = $smcFunc['db_query']('', '
			SELECT
				ms.subject, ms.body, ml.id_member, b.thumb_board, mem.avatar, t.id_topic,
				(SELECT id_thumb FROM {db_prefix}attachments WHERE id_thumb != 0 AND {db_prefix}attachments.id_msg = ms.id_msg ORDER BY id_attach LIMIT 1) AS id_thumb
			FROM {db_prefix}log_notify AS ln
				INNER JOIN {db_prefix}topics AS t ON (t.id_topic = ln.id_topic' . ($modSettings['postmod_active'] ? ' AND t.approved = {int:is_approved}' : '') . ')
				INNER JOIN {db_prefix}boards AS b ON (b.id_board = t.id_board AND {query_see_board})
				INNER JOIN {db_prefix}messages AS ms ON (ms.id_msg = t.id_first_msg)
				INNER JOIN {db_prefix}messages AS ml ON (ml.id_msg = t.id_last_msg)
				LEFT JOIN {db_prefix}members AS mem ON (mem.id_member = ml.id_member)
				LEFT JOIN {db_prefix}log_topics AS lt ON (lt.id_topic = t.id_topic AND lt.id_member = {int:current_member})
				LEFT JOIN {db_prefix}log_mark_read AS lmr ON (lmr.id_board = b.id_board AND lmr.id_member = {int:current_member})
			WHERE ln.id_member = {int:current_member} AND lt.id_msg <= ml.id_msg AND lmr.id_msg <= ml.id_msg AND ml.id_member != {int:current_member}
			ORDER BY ml.id_msg DESC
			LIMIT 1',
			array(
				'current_member' => $user_info['id'],
				'is_approved' => 1,
			)
		);
		$data = $smcFunc['db_fetch_assoc']($request);
		if ($data) {
			censorText($data['subject']);
			// Try to get a image, need to check for svg's as the Android notification system doesn't like them.
			if (preg_match('[smg id=([0-9]+)(.*)]', $data['body'], $match))
				$data['thumb'] = $scripturl . '?action=media;sa=media;in='.$match[1].';thumb';
			else if (!empty($data['id_thumb']) && $data['id_thumb'] != 0)
				$data['thumb'] = $scripturl . '?action=dlattach;topic='.$data['id_topic'].';attach='.$data['id_thumb'].';image';
			else if (preg_match('#\[img(.*)\](.*)\[\/img\]#Ui', $data['body'], $match))
				$data['thumb'] = $match[2];
			else if (!empty($data['thumb_board']))
				$data['thumb'] = $boardurl.'/img/b/sm/'.$data['thumb_board'];
			else 
				$data['thumb'] = $boardurl.'/img/viral/site_thumb125.png';

			$context['SWNotify'] = ServiceWorkerNotify(array(
				'title' => 'New Reply',
				'body' => $data['subject'],
				'icon' => xpath_urls_filter($data['thumb']),
				'href' => xpath_urls_filter($scripturl.'?topic='.$data['id_topic'].';topicseen#new'),
				'tag' => 'new_reply_'.$data['id_topic'] // Tag is supposed to prevent duplicates in the notification pane.
			));
		}
		$smcFunc['db_free_result']($request);

		// Others if we didn't get a topic
		if (!isset($context['SWNotify'])) {
			// Personal Messages
			if ($user_info['unread_messages'] > (isset($_SESSION['unread_messages']) ? $_SESSION['unread_messages'] : 0))
				$context['SWNotify'] = ServiceWorkerNotify(array(
					'title' => 'Unread PM',
					'body' => 'You have unread Personal Messages!',
					'icon' => '',
					'href' => xpath_urls_filter($scripturl.'?action=pm'),
					'tag' => 'pm_unread'
				));
			// Aeva Media
			else if ($user_settings['aeva_unseen'] > 0)
				$context['SWNotify'] = ServiceWorkerNotify(array(
					'title' => 'Unseen Media',
					'body' => 'New media items have been uploaded.',
					'icon' => '',
					'href' => xpath_urls_filter($scripturl.'?action=media'),
					'tag' => 'unseen_media'
				));
			// Mentions
			else if ($user_settings['unread_mentions'] > 0)
				$context['SWNotify'] = ServiceWorkerNotify(array(
					'title' => 'Someone has mentioned you',
					'body' => 'You have been mentioned in a post or comment.',
					'icon' => '',
					'href' => xpath_urls_filter($scripturl.'?action=profile;area=mentions'),
					'tag' => 'mentioned'
				));
		}
		// Just my reference, this isn't finished yet, needs more logic and fixes.
		// [notify_announcements] [notify_regularity] [notify_send_body] [notify_types] id_msg_last_visit aeva_unseen email_mentions unread_mentions
	}
	if (isset($context['SWNotify']))
		// Log this so we don't flood them, the tag is supposed to do this but that is if supported.
		$_SESSION['log_notify'] = time();
	else
		$context['SWNotify'] = '';
}

function ServiceWorkerNotify($data) {
	return '(function(){self.registration.showNotification(\''.$data['title'].'\', {body: \'' .$data['body'] . '\',icon: \'' .$data['icon']. '\',tag: \'' . $data['tag'] . '\'});self.addEventListener(\'notificationclick\', function(event) {event.notification.close();return clients.openWindow(\''.$data['href'].'\');});})();';
}
`

I wouldn't expect a full implementation in 2.1 on this as I mentioned the service worker specification isn't completed yet and may change breaking stuff like it has done to me in the past.

**Comment by sicommnend** [comment]
sicommnend commented 34 seconds ago
In order for true desktop level notifications when your not on the site you need a service worker and https. The specification is not complete yet and I already had to do a few rewrites on my code for my service worker.

I wouldn't expect a full implementation in 2.1 on this as I mentioned the service worker specification isn't completed yet and may change breaking stuff like it has done to me in the past.

*edit, code doesn't look good in here, attached file for 2.0.x for a reference. 
[Service-Worker.php.tar.gz](https://github.com/SimpleMachines/SMF2.1/files/770325/Service-Worker.php.tar.gz)

**Comment by colinschoen** [comment]
Question answered. Issued closed.
