### ISSUE TITLE
Use this function to inform the moderators and administrators of an abusive or wrongly posted message.

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3913]
Use this function to inform the moderators and administrators of an abusive or wrongly posted message.
is wrongly really a valid word? seems it is a valid word but i dont think it is commonly used.
https://en.wiktionary.org/wiki/wrongly

maybe change the wording to something like this...

"Use this function to inform the moderators and administrators of an abusive or message posted in error."

**Comment by XinYenFon** [comment]
I think wrongly makes more sense compared the sentence you write.

**Comment by sbulen** [comment]
How's:
"Use this function to inform the moderators of an abusive message or a message posted in error."

Wrongly is a real word ("wrongly accused...") just not often used in this context.

**Comment by Sesquipedalian** [comment]
As suggested [here](https://github.com/SimpleMachines/SMF2.1/pull/3952#discussion_r103585261), I think it would be best to say something like, "Use this function to inform the moderators of a problematic message." That conveys the idea simply and cleanly, and "problematic" covers the ideas of both abuse and error.

**Comment by Sesquipedalian** [comment]
Alternatively, if we still want to highlight the idea of reporting abusive messages, we could try "Use this function to inform the moderators of an abusive or otherwise problematic message."

**Comment by XinYenFon** [comment]
can we go with "or a problematic message." ?

**Comment by Sesquipedalian** [comment]
Probably "an abusive or problematic message" rather than "an abusive or a problematic message."

**Comment by XinYenFon** [comment]
Fine by me.

**Comment by frandominguezl** [comment]
Any more objections? If not, I'll submit the final decision

**Comment by illori** [comment]
Go ahead.
