### ISSUE TITLE
Once board subscriptions are turned off they cannot be turned on anymore

### ISSUE THREAD

**Issue by borisneubert** [SimpleMachines/SMF#3914]
SMF 2.0.13

I go to Profile > Ignore Boards and check some boards that should be ignored.
Press [change profile]
I do not receive e-mail notifications any more for new topics in the ignored boards. That is expected.

I go to Profile > Ignore Boards and uncheck the previously ignored boards.
Press [change profile]
I still do not receive e-mail notifications for new topics in the previously ignored boards. That is wrong.
Neither does Profile > Notifications and E-Mail show these boards in the lower pane although they are not ignored.

**Comment by sbulen** [comment]
A couple of questions...  First off, you mean 2.1, not 2.0.13, correct?

The Notifications under Profile shows only the boards you have specifically asked to watch.  If you want to see an item there, you must specifically add it there.    And the application does let you add it, even when previously ignored.   So I'm not sure I see an issue there.

If I'm off base, could you send a couple of screenshots to show exactly which screens you're talking about?    Thanks.

It *is* confusing that it lets you ignore & watch the same boards at the same time...

**Comment by borisneubert** [comment]
Thank you, sbulen, for picking this up.

We are still on SMF 2.0.13 (2014). Please find attached the requested screenshots.

![smf-ignoreboardsoptions](https://cloud.githubusercontent.com/assets/8795819/23522986/5089a8ba-ff85-11e6-83a6-21d1896a44ba.png)
![smf-currentboardnotifications](https://cloud.githubusercontent.com/assets/8795819/23522992/52af2d5e-ff85-11e6-9758-de433e644968.png)
![smf-notificationsprofile](https://cloud.githubusercontent.com/assets/8795819/23523469/4d86b17e-ff87-11e6-9ffb-4b973f67d3f8.png)

Let's forget about the Current Board Notifications for a moment. Might be that I misunderstand what these are meant to show.

Let's have a look at the Ignore Board Options. None of the boards under "Allgemeine Informationen" has a check mark. Still I do not receive notifications for new posts in some of the sub-boards under "Vereinsinterna - FHEM e.V.". By notifications I mean e-mail messages about newly started topics. I still receive notifications about replies to topics I have started or previously replied to in such a board.

The workflow I described is reproducible (check one board to be ignored, change profile, uncheck the board, change profile -> although the board is not ignored any more, I do not receive notifications for new posts in the board) and I run through it together with an administrator to minimize the chance of PEBKAC.

**Comment by Oldiesmann** [comment]
GitHub is only for 2.1. Please post in the "Bugs and Bug Reports" board on the forum if you believe you've found an issue with 2.0.x.
