### ISSUE TITLE
Double string in personal messages

### ISSUE THREAD

**Issue by realdigger** [SimpleMachines/SMF#3917]
The text «You have forwarded or responded to this message.» is displayed twice

![double](https://cloud.githubusercontent.com/assets/1187218/22629891/02300de2-ec09-11e6-8516-e9cbbc272cee.png)

**Comment by frandominguezl** [comment]
@Oldiesmann Not sure what's this line function inside PersonalMessage.template.php L419
`<br><span class="smalltext">&#171; ', $context['folder'] == 'sent' ? $txt['pm_sent_is_replied_to'] : $txt['pm_is_replied_to'], ' &#187;</span>';`

**Comment by Oldiesmann** [comment]
Looks like line 418 of that file is a duplicate.

```
$txt['pm_is_replied_to'] = 'You have forwarded or responded to this message.';
$txt['pm_sent_is_replied_to'] = 'Recipient have forwarded or responded to this message';
```

**Comment by frandominguezl** [comment]
@Oldiesmann In 2.0, L419 is not there, just L418 so, maybe we should delete L418?

**Comment by Oldiesmann** [comment]
Yes, just delete line 418
