### ISSUE TITLE
Normal member can see hidden ones in the online list

### ISSUE THREAD

**Issue by realdigger** [SimpleMachines/SMF#3919]
![hidden](https://cloud.githubusercontent.com/assets/1187218/22630164/f02671c2-ec0d-11e6-8bbe-25b89beb9ddb.png)

**Comment by Oldiesmann** [comment]
Were you logged in as a regular member at that time? Only admins and users with certain admin permissions should be able to see hidden members in that list

**Comment by realdigger** [comment]
We have some reports about this issue from regular members. I test this from regular member account and guest. Both of them can see my hidden admin account online.
I checked some forum settings and found out that this only happens when using Memcached as caching accelerator.

**Comment by realdigger** [comment]
Same issue with file based caching.

**Comment by illori** [comment]
do they have moderator forum members permission? as this grants the access to view users that hidden.

i tested this on my 2.1 install and cant duplicate the issue if the user viewing the online list does NOT have moderate forum members permission.

**Comment by frandominguezl** [comment]
Can't duplicate the issue

**Comment by sbulen** [comment]
Couple of questions - 
(1) Do all hidden IDs ALWAYS appear when cache is enabled?  
(2) Are you changing settings (e.g., permissions) and retesting?   
(3) Is this a migrated forum, where you just completed a 2.0 => 2.1 upgrade?  

Knowing a little more about the exact steps may help.  This could be that some cache needs invalidation upon permission changes or cache changes, etc.   OR..  It could also be that we shouldn't place hidden members' info in cache.

**Comment by sbulen** [comment]
Confirmed.  Yes, hidden users display when caching is enabled.  I'll take a peek at this...

**Comment by sbulen** [comment]
You know...  I don't think this should be cached at all.  Cache doesn't appear to be unique per user...   So...  Once cache is built, it's used by whoever logs on next...    At first I thought that hashed key on the cache file name might include a user ID, but it doesn't appear to (and its set by the cache api).   

The solution here appears to be to simply not use cache for members online.  

If I'm off base, someone let me know...

**Comment by colinschoen** [comment]
Fixed with #3956.
