### ISSUE TITLE
"View as Desktop" button

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#3929]
Sometimes it could be useful to have a "View as Desktop" button when in a mobile device and would be great to have something like this in our design

**Comment by XinYenFon** [comment]
I don't think Curve2 needs such addition.

**Comment by illori** [comment]
i dont think it is needed either. i think it may be complicated to add as we dont have a mobile site to load vs a desktop site.

**Comment by Oldiesmann** [comment]
In Google Chrome on Android there's a "Request desktop site" option in the menu which does exactly what you want. Not sure about other browsers or mobile OSes

**Comment by colinschoen** [comment]
There is a similar option on Safari too. Agreed not necessary for now. Closed.
