### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by bensene** [SimpleMachines/SMF#3930]
themes\default\languages\Admin.english.php (1 hit)
	Line 430: $txt['attachment_transfer_desc'] = 'Transfer files betwen directories.';

BETWEEN

**Comment by Dzonny** [comment]
Thanks for your report! Typo fixed in #3932

**Comment by frandominguezl** [comment]
@Dzonny I already submitted a fix for this in #3931

**Comment by Dzonny** [comment]
@d3vcho I closed my poll request, hope that that Travis check will be okay this time

**Comment by XinYenFon** [comment]
@Dzonny its a pull request 😆

**Comment by Dzonny** [comment]
Yeah, lol :P

**Comment by albertlast** [comment]
is fixed by one of my pr #3940

**Comment by colinschoen** [comment]
Fixed with #3940
