### ISSUE TITLE
Connection refused in /opt/lampp/htdocs/beta/Sources/Subs-Db-mysql.php

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#3944]
Testing latest build with XAMPP for Linux using PHP 7.0.15, getting this errors since a couple of days back:

Warning: mysqli_real_connect(): (HY000/2002): Connection refused in /opt/lampp/htdocs/beta/Sources/Subs-Db-mysql.php on line 75
Connection Problems

Sorry, SMF was unable to connect to the database. This may be caused by the server being busy. Please try again later.

Coul this be something related to SMF? I'm not experiencing this with 2.0

**Comment by albertlast** [comment]
you are 100% sure that your database conection information are right?

**Comment by live627** [comment]
Maybe it's  wieldness regarding the port. Try to restart  the mysql server.

**Comment by frandominguezl** [comment]
Seems MySQL didn't want to play. It's solved now... Thanks :)
