### ISSUE TITLE
integrate_profile_areas

### ISSUE THREAD

**Issue by Underdog-01** [SimpleMachines/SMF#3945]
Question:

Someone edited Profile.php at some point and changed the integration hook name of "integrate_profile_areas" to "integrate_pre_profile_areas".

Currently I do not see any issue with older mods working with the same hook (with the original function name) but now one must adjust this within a mod's install files.  

Is there a good reason for renaming it or is it a mistake?

Regards.

**Comment by Underdog-01** [comment]
Ok, I see the change here:
https://github.com/SimpleMachines/SMF2.1/commit/085840a66e9dae8be6b19b7ef4ee81c83b7041d6

... but where is the other function call & why wouldn't one rename the other one (assuming it exists) to maintain backward compatibility? 

I do not see the original function in any other profile file therefore at the moment it does not appear as a duplicate.

**Comment by tinoest** [comment]
It is made up in the string you linked to. 

 call_integration_hook('integrate_' . $menu_context['current_action']... 

Where menu_context is equal to profile

**Comment by Underdog-01** [comment]
There is no action of profile_areas

**Comment by jdarwood007** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/3118

Read the related issue
