### ISSUE TITLE
[Tweak] Use of jQuery in Unread Messages

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#3955]
The idea is to display the "Mark Selected Read" button only if one or more checkboxes are checked. This can be easily done with jQuery.

What do you think?

**Comment by replikacep** [comment]
hmm

**Comment by colinschoen** [comment]
Seems useful.

**Comment by albertlast** [comment]
What is the benefit and what is shown when nothing is marked?

**Comment by frandominguezl** [comment]
@albertlast It's just an UI improvement. It makes the design look better.

On the other hand, Gwenwyfar proposed to always display the button, but if no checkbox is marked, then deactive the button. I find that better instead of my original idea.
