### ISSUE TITLE
Attachments - discarded upon preview

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3957]
Attachments discarded upon preview.  To reproduce:
1. Add a new message
2. Type in something
3. Attach some photos
4. Upload attachments
5. Preview 
6. Post

If you click on the 'insert' button after uploading, you will get the message: "No message is associated with this attachment" in the message body after pressing Post.

![image](https://cloud.githubusercontent.com/assets/23568484/23640333/c118d53c-02a1-11e7-9d61-12e7bd797e17.png)

**Comment by sbulen** [comment]
The cause of this was my prior PR:  Clear out attachment info for new posts #3879

I need to be more selective about clearing out the $_SESSION attachment info.  

Will need to look a little deeper...

**Comment by sbulen** [comment]
The intent of the original logic was to restore previously uploaded attachments to $context.   There were issues with this, mainly that it only properly restored one of the attachments and discarded the others (leaving orphans in the file system).   

So...    Resume attachment processing or start afresh whenever the user presses Post & attachments are found partially processed in  $_session?   

I'm now leaning towards fixing the old attachment restore logic.

Input welcome...

**Comment by sbulen** [comment]
To recap, since this info is spread across a couple of issues...

Imagine you author a post, and provide - and upload - multiple attachments.  Now imagine you navigate away before pressing Post (possibly on purpose, possibly on accident, the app doesn't know your motives...).  

What should happen the next time you press Post (or Reply)?   Bear in mind, you *might* be trying to recreate the post you just lost.  OR, you *might* be on a different board/topic entirely, starting a new message.  Again, the app doesn't know your intent.   

At this point in time, your previous message text is lost.  HOWEVER...  Oddly, uploaded attachments are tracked.  

The original logic here tried & failed to restore the attachments to $context, so they would be attached to your current post.  It failed, and only attached the first attachment to your post, and left the rest as orphans in your DB & filesystem.  

I thought it was odd to have one of your old attachments auto-attached to a new, blank, message.  It felt random.  My previous PR cleared those out.  It feels much cleaner to start afresh.  

(It turns out that PR inadvertently affected previews, & needs fixing.  Hence this issue.)

My only reservation with clearing everything out is that it is quite possible the attachments were large, and compiling them and attaching and uploading them could have been a chunk of work.  Re-presenting them would give the author the opportunity to delete them purposefully or re-use them.   

So...

Start afresh?   Or re-present the previously uploaded attachments on a new post?

**Comment by sbulen** [comment]
I'm going with clearing everything out...  It is more like I've seen elsewhere, and it is cleaner overall.  PR forthcoming.

**Comment by PortaMx** [comment]
No Problem with our Forum..
1. create new topic
2. type in title and body
3. add image attach
4. upload attach
5. insert in the body
6. preview message (ok)
7. posts massage (ok)

**Comment by sbulen** [comment]
Thanks @PortaMx !

How recent is your refresh from Github?   This was caused by a change that was implemented on 1/27.  PR to address has been submitted.

**Comment by PortaMx** [comment]
Uhm .. now, I test that with OUR Forum version (see: https://github.com/PortaMx/PortaMx-Forum)
This is BASED on SMF 2.1, but with more options and features and less bug's (i think) ;-)

**Comment by sbulen** [comment]
You have the old code that has several issues that have since been addressed.  

One example:
https://github.com/PortaMx/PortaMx-Forum/blob/master/Sources/Post.php#L194

The code for getRawAttachInfo() in subs-attachments.php only returns info for ONE attachment, not the whole list.  So that line of code, under certain circumstances, drops all your attachments except one...

More info here:   Attachments - orphaned file issues #3827

These issues are behind us now.

**Comment by sbulen** [comment]
You might want to take a peek at these PRs also:
Fix issues with attachment critical error processing #3862
Fixes maxfiles check in dropzone #3855

**Comment by PortaMx** [comment]
I think, I have found a good solution for this probem ..
I add the member ID to the upload attachments, so if the user cancel this message (after upload attach[es])
he will see the attach[es] in the next message he will create. No other Member can see this attaches ..
So the getRawAttachInfo() works perfect for this solution.

This all need smaller corretions on 2 or 3 querys, but it's simple ..

If you have interest on this, let me known ...

**Comment by sbulen** [comment]
@PortaMx - Thanks!   But I went the other direction, as explained above.  I had a fully working "keep it all" solution, but it just felt extremely unusual to have old attachments pop up at a later time.  

BTW: getRawAttachInfo only returns info on 1 attachment due to the LIMIT 1 in the sql.  (https://github.com/PortaMx/PortaMx-Forum/blob/master/Sources/Subs-Attachments.php#L999)  You may need to retest with a few attachments to confirm it works.  You gotta build a loop there.  The other issue with that solution was thumbnails, which are stored as attachments, but you do not want to depict thumbnails as separate attachments...  So rebuilding $context properly takes a little care...  Hope this helps.

**Comment by PortaMx** [comment]
Well ok .. I have also found a good solution .. uploaded attachments, they not asigned to a msg_id, I can see in the attachment maintenance (these shown as NOT ASIGNED) in the attachment list. So I can delete this dead attaches and all is clean..

Ah and yes ... thank for your tip

**Comment by PortaMx** [comment]
Well, well .. just I tested my "find not assigned attaches" routine on our old forum .. uuhhiii .. he found al lot of not assigned attaches ;-)
I checked this manually .. and I see .. it't right ;-)
So I  can say, my code works as very well ...

I think, it's a good point to add this service to the weekly maintenance ...

**Comment by sbulen** [comment]
Excellent!

You may find more if you apply this fix:  Delete orphans caused by uploaded attachments on abandoned posts #3878

E.g., you still have the erroneous += in there that actually causes the attachment integrity checker to bypass checking many (at least half of all) attachments...   (https://github.com/PortaMx/PortaMx-Forum/blob/master/Sources/ManageAttachments.php#L1546)

The query was slightly off, too.  

We really have tightened up attachments here in SMF.   (Come back to the dark side!)

**Comment by PortaMx** [comment]
Hmmm .. I'm not sure if your code works on all situation,
As example .. I start a new post .. upload one ore more attaches .. then simple I click on the Home button.
You are sure, that all msgID = 0 attaches and thumbnails ONLY for the current user are removed in this case ?

**Comment by sbulen** [comment]
(edit...  misread question...)

That code is in the Attachment Integrity Checker, it's not doing the cleanup realtime.  It's looking for attachments & thumbnails that don't have messages.  There are two ways this may be exhibited:  Either the attachment was never connected to a message (attach.id_msg = 0), *OR*, the attachment was connected to a message that was somehow removed (outer join, message.id_msg = null).  

It was a DRAG to test...  I had to repeatedly reload my test environment with all attachments, and rerun the upgrader, & then test with and without the change, in order to audit the differences.  Every time I tweaked it...

In my 2.0 forum upgraded to 2.1, out of 11000 attachments, there were ~300 new, legitimate orphans found and cleaned up by the new logic.

**Comment by PortaMx** [comment]
Well .. I tested you code and I see, that this not works correct ..
I have rewritten the code and my worked perfectly !

Now I a´say you why yous not work..
First point here:
`			$ignore_ids = array(0);
`

You will find msgID with 0, your code can't work because this:
`					AND NOT FIND_IN_SET(a.id_msg, {array_int:ignore_ids})' : ''),
`
ups .. we will find msgID = 0 (or not ?)
So the obove must by
`			$ignore_ids = array();
`

Second the query itself don't work properly ,, 
Here a correct query to find out all not assigned attaches and thumbnail:

`			$result = $pmxcFunc['db_query']('', '
				SELECT a.id_attach, a.id_member, a.id_folder, a.filename, a.file_hash, a.attachment_type, m.id_msg
					FROM {db_prefix}attachments AS a
					LEFT JOIN {db_prefix}messages AS m ON (m.id_msg = a.id_msg)
				WHERE a.id_attach BETWEEN {int:substep} AND {int:substep} + 499
					AND attachment_type IN ({array_int:aTypes}) AND (a.id_msg = {int:no_msg} OR a.id_msg = NULL)'. (!empty($ignore_ids) ? '
					AND NOT FIND_IN_SET(a.id_msg, {array_int:ignore_ids})' : ''),
				array(
					'aTypes' => array(0, 3),
					'no_member' => 0,
					'no_msg' => 0,
					'substep' => $_GET['substep'],
					'ignore_ids' => $ignore_ids,
				)
			);

			while ($row = $pmxcFunc['db_fetch_assoc']($result))
			{
				$to_remove[] = $row['id_attach'];
				$context['repair_errors']['attachment_no_msg']++;

				// If we are repairing remove the file from disk now.
				if ($fix_errors && in_array('attachment_no_msg', $to_fix))
				{
					$filename = getAttachmentFilename($row['filename'], $row['id_attach'], $row['id_folder'], false, $row['file_hash']);
					@unlink($filename);
				}
			}
			if ($pmxcFunc['db_num_rows']($result) != 0)
				$to_fix[] = 'attachment_no_msg';
			$pmxcFunc['db_free_result']($result);
`

That worked perfectly (I have tested all situations) and will remove all not assigned attaches and/or thumbnail

Greetings Feline

**Comment by sbulen** [comment]
3 notes:

You should be looking for m.id_msg null, not a.id_msg null.  The outer join will result in m.id_msg as null if the message is not found.  Your logic will work fine, except for attachments that point to non-existent messages.  Not a huge problem, I think 2.0 has always done the same.  These are rare, but they're out there.  

Your NOT FIND IN SET is comparing attachment ids & message ids.  

Yes, due to the array(0), that query will exclude the attachment with an id_attach of 0.  (There isn't one, they start at 1.)  If somehow an attachment with an id of 0 ever gets created (added by phpMyAdmin?), that (single) attachment will be omitted from the check.  IIRC, it didn't like having a NOT IN (), which is why the prior developer had seeded it with 0.  I just left that alone; it was working.

**Comment by PortaMx** [comment]
Well .. after a little bit fiddeling, I found the perfect solution for lost Posts with attaches and/or thumbnails, see images 

![attachments and avatars](https://cloud.githubusercontent.com/assets/2270223/23985906/c6e25dda-0a21-11e7-8647-642e40f31c3a.png)

![attchments_and_avatars_2](https://cloud.githubusercontent.com/assets/2270223/23985913/cbfb2554-0a21-11e7-9f57-3a374c1a9f12.png)

![attachments_and_avatars_3](https://cloud.githubusercontent.com/assets/2270223/23985920/d074a088-0a21-11e7-807c-6076e4c12e39.png)

From this screens, now you can fix these things ;.-)

**Comment by sbulen** [comment]
Nice!

**Comment by PortaMx** [comment]
Well .. I found a other Bug on "remove thumbnails" because these query iss bad:

`	// Get all the attachment names and id_msg's.
	$request = $smcFunc['db_query']('', '
		SELECT
			a.id_folder, a.filename, a.file_hash, a.attachment_type, a.id_attach, a.id_member' . ($query_type == 'messages' ? ', m.id_msg' : ', a.id_msg') . ',
			thumb.id_folder AS thumb_folder, COALESCE(thumb.id_attach, 0) AS id_thumb, thumb.filename AS thumb_filename, thumb.file_hash AS thumb_file_hash, thumb_parent.id_attach AS id_parent
		FROM {db_prefix}attachments AS a' .($query_type == 'members' ? '
			INNER JOIN {db_prefix}members AS mem ON (mem.id_member = a.id_member)' : ($query_type == 'messages' ? '
			INNER JOIN {db_prefix}messages AS m ON (m.id_msg = a.id_msg)' : '')) . '
			LEFT JOIN {db_prefix}attachments AS thumb ON (thumb.id_attach = a.id_thumb)
			LEFT JOIN {db_prefix}attachments AS thumb_parent ON (thumb.attachment_type = {int:thumb_attachment_type} AND thumb_parent.id_thumb = a.id_attach)
		WHERE ' . $condition,
		$query_parameter
	);
`

The Join on thumb.attachment_type don't work, because these is 3 on remove a thumbnail
Also this can removed because this is also coded in the $query_parameter.
So the correct query must by:

`	// Get all the attachment names and id_msg's.
	$request = $smcFunc['db_query']('', '
		SELECT
			a.id_folder, a.filename, a.file_hash, a.attachment_type, a.id_attach, a.id_member' . ($query_type == 'messages' ? ', m.id_msg' : ', a.id_msg') . ',
			thumb.id_folder AS thumb_folder, COALESCE(thumb.id_attach, 0) AS id_thumb, thumb.filename AS thumb_filename, thumb.file_hash AS thumb_file_hash, thumb_parent.id_attach AS id_parent
		FROM {db_prefix}attachments AS a' .($query_type == 'members' ? '
			INNER JOIN {db_prefix}members AS mem ON (mem.id_member = a.id_member)' : ($query_type == 'messages' ? '
			INNER JOIN {db_prefix}messages AS m ON (m.id_msg = a.id_msg)' : '')) . '
			LEFT JOIN {db_prefix}attachments AS thumb ON (thumb.id_attach = a.id_thumb)
			LEFT JOIN {db_prefix}attachments AS thumb_parent ON (thumb_parent.id_thumb = a.id_attach)
		WHERE ' . $condition,
		$query_parameter
	);
`

Greetings from Germany

**Comment by sbulen** [comment]
@PortaMx - 
Yes, that adds a measure of safety in case thumb_parent.id_thumb somehow gets corrupted or somehow becomes illogical.

This issues has long since closed - did you want to open an issue or PR to suggest the change?

**Comment by PortaMx** [comment]
I say you what I see .. and the query do NEVER get a parent in the current version.
If SMF fix that or not, is not my choice .. I say you simple what bugs I found.
Because SMF don't love my work and drop me back allways if I post bug or features, i do nothing more for SMF. But I'm so lovely to tell SMF havy bugs .. not more .. not less.

**Comment by sbulen** [comment]
Thank you for all of your input, @PortaMx .  It's appreciated.
