### ISSUE TITLE
Guests recieve error on pages using SSI when guest access is disabled

### ISSUE THREAD

**Issue by coldcode69** [SimpleMachines/SMF#3959]
I have a website using SSI, /forum/SSI.php is included in my /index.php with `$ssi_guest_access = false` (default). If someone visits /index.php as a guest they receive the following error:

`
Fatal error: Uncaught Error: Class 'MatthiasMullie\Minify\CSS' not found in /var/www/site/public/forum/Sources/Subs.php:3617 Stack trace: #0 /var/www/site/public/forum/Sources/Subs.php(3529): custMinify(Array, 'css') #1 /var/www/site/public/forum/Themes/default/index.template.php(99): template_css() #2 /var/www/site/public/forum/Sources/Load.php(2355): template_html_above() #3 /var/www/site/public/forum/Sources/Subs.php(3263): loadSubTemplate('html_above', true) #4 /var/www/site/public/forum/Sources/Subs.php(2858): template_header() #5 /var/www/site/public/forum/SSI.php(157): obExit(NULL, true) #6 /var/www/site/public/index.php(14): require_once('/var/www/site/p...') #7 {main} thrown in /var/www/site/public/forum/Sources/Subs.php on line 3617`

However, visitors that are logged into the forum do not receive the error and SSI works as intended. 

If I disable Minify CSS/JS in the forum settings then the error doesn't appear for guests, and they are redirected to the forum login as intended.

If `$ssi_guest_access = true` then the error doesn't appear.

**Comment by Sesquipedalian** [comment]
Hi @coldcode69. Can you provide a copy of the external file you are using, or else a description of exactly what SSI functions you are using and how they are implemented in your external file?
