### ISSUE TITLE
Inconsistency between default values

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#396]
As an example lets take the themes table and the 'return_to_post' variable, there is no default entry in the table, it's done in the code using:

``` PHP
<input type="hidden" name="goback" value="', empty($options['return_to_post']) ? '0' : '1', '" />
```

When a member updates their profile to tick the 'Return to topics after posting by default.' option then an entry is entered into the database with a value of 1.

Compare this to 'posts_apply_ignore_list', there is a default entry in the themes tables with a value of 1 and the id_member value is -1 so it applies to all members that don't have an entry for 'posts_apply_ignore_list' in the themes table.

So for this option the code does:

``` PHP
'is_ignored' => !empty($modSettings['enable_buddylist']) && !empty($options['posts_apply_ignore_list']) && in_array($message['id_member'], $context['user']['ignoreusers']),
```

I would expect there to be some consistency on how default values are stored and processed unless there is a reason for differences in code like this.

**Comment by Arantor** [comment]
There actually is consistency in this.

In both cases, a 0 refers to an unticked box and a 1 to a ticked box. The first case, the option is 'Return to topic after posting' which defaults to off. The second is 'Hide messages posted by ignored members', which defaults to on.

So all is doing exactly what it should be doing - if an option is on, have a 1, if it is off, leave the row missing to save a little space or explicitly have a 0 if necessary but it's usually better to have no row and just test either case with empty(), which is one of the underlying design principles in SMF.
