### ISSUE TITLE
package_path lingers

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3963]
I believe $modSettings['package_path'] was an old smf_settings entry that held the packages path at one point.  I have an old $modSettings['package_path'] entry in my 2.0 forum.  

As near as I can tell, package_path was replaced by $packagesdir (in settings.php) & should no longer be used.  However, it is still referenced in code in Subs-Package.php.   

So...  If my understanding is correct, we should:
  -  Clean up that old logic from subs-package.php
  -  Add an entry in the upgrader to delete the old package_path setting

One example, it tries to set the ftp path using it here:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Package.php#L873

**Comment by sbulen** [comment]
This looks like a very easy change, there is only one question in my mind...

For the most part, this is an easy substitution in the code from $modSettings['package_path']) (which was loaded from the settings table) to $packagesdir (now loaded from settings.php). 

However...  In Subs-Package.php, when a valid FTP path is determined, it then issues an updatesettings to update 'package_path'.  I think this is/was questionable...  Updating the settings might make sense if there were a separate setting for the ftp path somewhere; it just doesn't feel right setting the packages path to it, as this feels like it might be disruptive to packages processing.  

I also simply have issues updating critical settings in the background with the user unaware...

So, my recommendation is to use $packagesdir in its place, however, NOT to issue an updateSettings/updateSettingsFile to overwrite the configured packages directory with the FTP directory as the old logic suggests.  

Feedback welcome...

**Comment by jdarwood007** [comment]
I introduced this setting.  It's purpose was to allow the packages directory to be moved, thus allowing more secure configurations by moving this outside of the web accessible location.  A common host setup is to need 755 or 777 on the packages directory to upload customizations and handle the temp directory during their install/uninstall.

It sounds like the modSetting was a older usage for detecting the correct path to be working in for a package.  I would have to dive deeper into its meaning, but I think removing it wouldn't break anything.

**Comment by sbulen** [comment]
Thanks.

I ran across this while looking into a package install issue.  It was a holdover from an earlier version, and had a strange partial path in it.  Reading the code, it looks like it would cause havoc for ftp users under certain circumstances.

**Comment by jdarwood007** [comment]
Well that is what it looks like its for.  Sometimes FTP users paths can vary from the system root.  Such as in shared hosting environments you may have /home/user/public_html/smf for the path to SMF, while a FTP user just sees /public_html/smf.  I've seen very horrible root and ftp paths depending on the shared hosting environment.

Looking at the code, looks like it tries to detect the correct path, if it can't find it falls back to the modSettings if it exists or a detected path (may be wrong).

**Comment by sbulen** [comment]
That sounds right.  I think it's a good thing.  Just two issues:
  -  package_path has been retired, this old code is literally the only place it's used.  At best, it's uninitialized.  At worst, like on my site, it contains questionable path info.  (I'm probably not alone here...)
  -  I have a really hard time with changing system settings without notifying the admin.  In this case, it appeared to try to change the package_path to the detected ftp path.  

I've read elsewhere here that the FTP config is problematic.  (It wouldn't surprise me if this were a contributor.)   Long term, I would suggest creating a separate FTP path setting.

**Comment by jdarwood007** [comment]
If this is the only place its called, then lets get rid of the call.

**Comment by sbulen** [comment]
@jdarwood007 - Part of the reason I was convinced this was an old legacy setting was the invalid path that was populated in my system: /public_html/smf

But...  This is exactly the value you mentioned above.  So now I'm not sure it's invalid...  

I was looking into two older issues logged here that appeared to be package path issues, & researching code & settings I could find in that area.  This one concerned me due to that confusing path.  

I do think that if the FTP path is separate from the regular packages path, they should probably be separate settings, and visible and maintained as such.  Maybe this is a longer term enhancement request.  

So now I'm on the fence about the PR.  Let me know if you think it has value.  If not, I'll cancel it.

**Comment by jdarwood007** [comment]
$packagesdir is definitely supposed to contain the full path to the Packages folder as seen by the file system/php.  I fully intend personally to use $packagesdir just like I do $sourcedir and move it outside of the public_html web root, preventing anyone from having the ability to put a file there and execute it in the browser because of the permissions being open.  It won't stop a LFI doing this, but does keep the executable stuff outside of the web.

I just looked at your PR, I thought it was the only place but there is more references.  So reading the various bits you changed, I can see what it is supposed to do.  Its supposed to keep that as the path that the FTP user sees.  It tries to auto detect it if it doesn't know or takes user supplied input.  It stores it as a quicker reference for later usage when FTP is needed again.

**Comment by sbulen** [comment]
Yep.  So, in effect, the old package_path is the ftp path.  

I just did a grep, my PR gets rid of all references to package_path (except the udpates to the install scripts to remove it).  

I'm thinking I should leave it be & withdraw the PR.  Package_path does seem to have a purpose, and you have explained the funky path - it's not the dangerous broken stray setting I thought it was.  

Thanks for the input.

**Comment by jdarwood007** [comment]
You could still clarify the comments better if you think it will help yourself or future people to understand the reason behind it.  Now that you understand what its purpose is.
