### ISSUE TITLE
Members recieve notification alerts about ignored users.

### ISSUE THREAD

**Issue by realdigger** [SimpleMachines/SMF#3965]
I recieve notification alert when ignored user quote my post. I think this is wrong behavior.

**Comment by frandominguezl** [comment]
I can confirm the issue. Good catch!

**Comment by realdigger** [comment]
Also, I see alerts about likes from ignored user.

**Comment by colinschoen** [comment]
TODO: Check for other instances of notifications from ignored users.

**Comment by Sesquipedalian** [comment]
Should this be closed now, @colinschoen?

**Comment by colinschoen** [comment]
Yes, thanks
