### ISSUE TITLE
Problem reading arabic text after upgrading.

### ISSUE THREAD

**Issue by kipaslampu** [SimpleMachines/SMF#3972]
Im succesfull upgrade my smf forum to this smf 2.1
My problem is, its cannot read the old forum post and topic in arabic after upgrading.

The font show like  SaÃ¢â‚¬â„¢id
Thanks.

**Comment by sbulen** [comment]
A few questions - 
Was your forum UTF8 before the upgrade?
Which do you use - mysql or postgresql?
What version of SMF were you running before the upgrade?

**Comment by sbulen** [comment]
Possibly related...
On the 2.0 support forum, a similar issue was reported:
http://www.simplemachines.org/community/index.php?topic=552591.msg3918546#msg3918546

**Comment by kipaslampu** [comment]
> A few questions -
Was your forum UTF8 before the upgrade?
Which do you use - mysql or postgresql?
What version of SMF were you running before the upgrade?

My forum is not utf8 before upgrade. After this problem im change it manually through my webmin to utf8 but the problem is still running.
Im using mysql
Before upgrade im using smf 2.0.7

**Comment by sbulen** [comment]
Were you latin1-swedish-ci before the upgrade?

**Comment by sbulen** [comment]
Or Cp1256?

**Comment by kipaslampu** [comment]
> Were you latin1-swedish-ci before the upgrade?

Exactly. Before upgrade the langguage is using latin swedish.

**Comment by sbulen** [comment]
Let me confirm the steps that took place:

You completed the 2.1 upgrade, but it did not properly convert your forum to utf8.

You noticed this, and your Web admin manually converted you after the 2.1 process.

My questions:

This was all in your TEST environment, correct?

We're there any errors during the 2.1 upgrade?

Did the utf8 step appear to execute?    Did it take a lot of time?

Can you explain the process used to convert to utf8 after the 2.1 upgrade?    Did your web admin simply change the tables in phpmyadmin?

**Comment by sbulen** [comment]
kipaslampu - 

Do you have a search index built in 2.0?  If so, is it the 'full text' or the 'custom' index?

I'm still looking into this....

**Comment by kipaslampu** [comment]
> This was all in your TEST environment, correct?
YES
We're there any errors during the 2.1 upgrade?
No errors
Did the utf8 step appear to execute? Did it take a lot of time?
UTF8 not show the progress bar... like bypass
Can you explain the process used to convert to utf8 after the 2.1 upgrade? Did your web admin simply change the tables in phpmyadmin?
YES. Manually change thorugh web admin.

> Do you have a search index built in 2.0? If so, is it the 'full text' or the 'custom' index?
Im forgot it. But mybe it has with full index.

**Comment by sbulen** [comment]
Well, all of that information is very interesting...

If UTF8 was bypassed, that means that for some reason, the upgrader thought you were ALREADY UTF8.  (Which makes this the exact opposite of rjen's issue...)

If you already had UTF8 content (which you did, arabic content) then the phpMyAdmin update to UTF8 by updating the collations is the WORST thing to do.  MySQL is not expecting those characters in a latin1 database; it does strange things with them.  

Thankfully, it is in a test environment!   

So, 4 questions:
  -  In your PROD 2.0 environment, do your table collations state latin1-swedish-ci, or do they state UTF8-general ci?    Do ALL of your tables match?   
  -  In your PROD 2.0 Settings.php file, what is the value for $language?
  -  In your PROD 2.0 Settings.php file, what is the value for $db_character_set?
  -  In your PROD 2.0 settings TABLE, what are the contents of the 'value' field for the row where 'variable' is global_character_set?    Do you have a global_character_set entry?

Screenshots would help (no passwords, please)...

**Comment by kipaslampu** [comment]
![untitled](https://cloud.githubusercontent.com/assets/26354110/24088337/2af4d894-0d64-11e7-907e-b3fa797bca06.jpg)

In your PROD 2.0 Settings.php file, what is the value for $language? = english
In your PROD 2.0 Settings.php file, what is the value for $db_character_set? =utf8
In your PROD 2.0 settings TABLE, what are the contents of the 'value' field for the row where 'variable' is global_character_set? Do you have a global_character_set entry?= trying to find it, but can't not be done.

**Comment by sbulen** [comment]
That global_character_set entry would be in your smf_settings table.  I suspect it is not there in your PROD 2.0 environment.   

So it appears there was a prior, failed attempt at converting to UTF8 on an earlier date.   If it didn't complete, that would explain the lack of the global_character_set (just like issue #3980 ). 

That, I think, is the common thread among the current issues, is a UTF8 conversion that was not completed in SMF2.0.
  -  For this issue, the evidence is above - it's partway to UTF8, prior to the 2.1 upgrade.  This looks like an earlier conversion failed.  
  -  For Rjen's issue ( #3980 ), he had manually performed a UTF8 conversion, but he just didn't know he needed to set the global_character_set entry.  
  -  For the 2.0 issue currently on the support forum, he still cannot get the 2.0 utf8 conversion to complete.  (http://www.simplemachines.org/community/index.php?topic=552591.msg3918546#msg3918546)

**Comment by sbulen** [comment]
I've been testing variations all day...    I have confirmed the following:
  -  Latin1 content in a latin1 table is always successfully converted to UTF8 (as expected)
  -  UTF8 content forced into a latin1 table is always successfully converted to UTF8 (as expected)
  -  UTF8 content already in a UTF8 table, if forced thru a 2nd UTF8 conversion, is garbled (definitely NOT as expected... converting UTF8 to UTF8 should do nothing, right???)

The above statements are all true both with the 2.0 maint function and in the 2.1 upgrade process.  Yes, I've run a BUNCH of conversions & upgrades...

_I can reproduce the EXACT symptoms of all 3 current UTF8 issues by doing the UTF8 conversion on a table 2x._ 

I see TWO root causes here:
  -  UTF8 conversions are failing.  The reason is unknown, but I suspect they are encountering invalid data & terminating.  
  -  UTF8 content in a UTF8 table, when converted to UTF8, becomes garbled.  We encounter this when a UTF8 conversion fails, and is subsequently rerun, either by the user hitting the UTF8 conversion button a 2nd time in the admin screen, or, at 2.1 upgrade time.

The next question is what to do about it...   

I'm kinda thinking aloud here...  Feedback welcome...

**Comment by albertlast** [comment]
On of the bigges issue in smf env is,
that no smf 2.0 database dump is provided where we could test the upgrade procedur -> i'm not able to look into this.

**Comment by sbulen** [comment]
Any db export should work.   I have asked Petter B via PM if he could send me one.

I will also try to reproduce it in test with bad data.

**Comment by sbulen** [comment]
My current thoughts on the gameplan for this set of issues.   

1)  We should prevent data corruption by fixing that UTF8 conversion logic (the same logic is in the 2.1 upgrader, the 2.1 code and the 2.0 code as well).  It should probably not touch existing UTF8 columns AT ALL in any of these places...  Users are clearly seeing the task not completed & hitting it again.  Even if they don't in 2.0, the 2.1 logic ends up doing the actual corruption.  
2)  We need a technique to detect the problem data that is causing the UTF8 process to fail.  I'm not sure if we should auto-correct it, OR, point it out to the user to manually correct.  This will take more thought.   I am leaning more towards letting the user correct it.  

Feedback welcome...

**Comment by sbulen** [comment]
Well...   Whaddya know...  For the record, applying UTF8 encoding to an existing UTF8 string is known to garble text.   This underscores the need to ensure we don't "re-encode" columns.   

This has popped up time to time while reading up on the subject.  

_Some references:_
http://php.net/manual/en/function.utf8-encode.php
> In fact, applying this function to text that is not encoded in ISO-8859-1 will most likely simply garble that text.

http://stackoverflow.com/questions/910793/detect-encoding-and-make-everything-utf-8

> If you apply utf8_encode() to an already UTF8 string it will return a garbled UTF8 output.

**Comment by sbulen** [comment]
@kipaslampu -

2 new requests - 
1) Were you able to find the value in global_character_set in your settings table?   Above, you said you couldn't find it, but in the other thread ( #3980 ), you tried to insert one and received a duplicate error message...  It is unclear to me if you have this setting or not.  
2)  Could you provide screenshots for the collation of ALL your tables?  You only have a partial list above.

Looking more closely at the list above, I see that the _SMF_ tables are UTF8, and the mod tables are still latin1.  In other words, SMF may already be UTF8...   If so, you might be more like the #3980 issue than I thought.   

_(Note: This is what happens if you install mods after a UTF8 conversion without setting the DB default collation.   This is why I suggested setting the DB default collation earlier: #3848 .   This may be another real-world example...)_

**Comment by kipaslampu** [comment]
> Were you able to find the value in global_character_set in your settings table? Above, you said you couldn't find it, but in the other thread, you tried to insert one and received a duplicate error message...
**Yes you are right. Im misslooking at it. There is global_character_set in the database.**
    

> Could you provide screenshots for the collation of ALL your tables? You only have a partial list above.
![1](https://cloud.githubusercontent.com/assets/26354110/24158388/2a179356-0e97-11e7-809f-a1dad6f725c3.png)
![2](https://cloud.githubusercontent.com/assets/26354110/24158389/2a1d3f22-0e97-11e7-9886-9132e1a11b47.png)
![3](https://cloud.githubusercontent.com/assets/26354110/24158390/2a23b2f8-0e97-11e7-8e25-2f58d6e0eea9.png)

**Comment by sbulen** [comment]
What value is in global_character_set in PROD 2.0, before the upgrade?    

Are the tables above your PROD 2.0 tables?   Before the attempted 2.1 conversion in TEST?

I am trying to understand the state of your 2.0 DB prior to the upgrade process.

**Comment by sbulen** [comment]
The changes in PR #3984 will prevent re-encoding of utf8 data to utf8 - the action that caused the corrupted data in the 3 recent issues identified above.  

This same code is in ManageMaintenance.php in 2.0 - if there is another 2.0 push, we should consider this change (I have an updated copy if desired - it helped me test various scenarios of the new logic rapidly).
