### ISSUE TITLE
UTF8 forum in 2.0 gets 'mangled' when upgrading to 2.1

### ISSUE THREAD

**Issue by Bopske** [SimpleMachines/SMF#3980]
I have tested the upgrade to 2.1 once again. 

My 2.0.13 test forum was running full UTF8 without any issues. I have downloaded the 2.1 package from Github yesterday and performed an upgrade today. 

The result is not good. Somehow the UTF8 conversion seems to be started, even though the database is already fully UTF8. The result is that special characters are mangled bij the conversion. Not just on screen, but in the database too.

Before upgrade:
![before1](https://cloud.githubusercontent.com/assets/24902644/24082907/9d1a1afc-0ccd-11e7-8a07-51213dc81315.jpg)
![before2](https://cloud.githubusercontent.com/assets/24902644/24082908/9d1ba764-0ccd-11e7-8256-5d178a6e2a97.jpg)

After upgrade:
![after1](https://cloud.githubusercontent.com/assets/24902644/24082913/adc6bd10-0ccd-11e7-8c33-4df8746aeb04.jpg)
![after2](https://cloud.githubusercontent.com/assets/24902644/24082914/adc8621e-0ccd-11e7-9b18-813a956b5686.jpg)

Then when I check the language in the upgraded forum, it shows as ISO-8859-1, is that not supposed to be  UTF-8

![taal](https://cloud.githubusercontent.com/assets/24902644/24082903/787e9fec-0ccd-11e7-8932-c50734b28d69.jpg)

**Comment by sbulen** [comment]
A few questions:
 - Was this a fresh 2.0 to 2.1 upgrade?   (Some people rerun the upgrader)
 - In 2.0.13, in your Settings.php file, what is the value for $language?
 - In 2.0.13, in your Settings.php file, what is the value for $db_character_set?
 - Were you able to run the 2.1 upgrade successfully at an earlier date?

**Comment by sbulen** [comment]
I don't think the character set displayed is a real problem.  I'm pretty sure that is lifted from the $txt['lang_character_set'] setting in the language file.  

It is my understanding that $txt['lang_character_set'] setting was to be left at iso-8859-1 due to the behavior of the SMF language editor.  

That said, it is very confusing to have that displayed here, though, as it will display ISO-8859-1 even if the charset is UTF8.  Thoughts?   @Antes ?

**Comment by sbulen** [comment]
It is also interesting that new tables are MyISAM.   In a vanilla install, they are InnoDB.  But during an upgrade, it leaves the engine setting to the system default.  Maybe not a problem, just interesting... 

Just recalled, this was discussed here, and should be expected:
Upgrader: New tables hard-coded to MyISAM #3899

**Comment by Bopske** [comment]
Was this a fresh 2.0 to 2.1 upgrade? (Some people rerun the upgrader)
answer: Yes: first and clean install: 
First built the 2.0 database and forum from backup, then went through the process once...

In 2.0.13, in your Settings.php file, what is the value for $language?
answer: $language = 'dutch-utf8';		# The default language file set for the forum.

In 2.0.13, in your Settings.php file, what is the value for $db_character_set?
answer:

########## Database Info ##########
$db_type = 'mysql';
$db_server = 'localhost';
$db_name = 'removed';
$db_user = 'removed';
$db_passwd = 'removed';
$ssi_db_user = '';
$ssi_db_passwd = '';
$db_prefix = 'smf_';
$db_persist = 0;
$db_error_send = 0;
$db_character_set = 'utf8';

Were you able to run the 2.1 upgrade successfully at an earlier date?
Amswer: yes and no
YES, I was able to do an upgrade earlier when the old forum was not utf8, but NO, not successful: the exact same issue resulted then. That was one of the reasons to migrate to utf8 ...

**Comment by Bopske** [comment]
> I don't think the character set displayed is a real problem. I'm pretty sure that is lifted from the $txt['lang_character_set'] setting in the language file.

I do not agree: the data is actually changed in the database, So it it a problem: cannot get that to display correctly to users anymore...

**Comment by sbulen** [comment]
> I do not agree: the data is actually changed in the database, So it it a problem: cannot get that to display correctly to users anymore...

Probably a better way to say that would be that I don't think that character set setting on your language screen is the cause of your data corruption.   

To me, that setting is a confusing setting.  It has to do with operations on the language file itself, and nothing to do with the DB.   I wanted to change it to UTF8 earlier, but that would have disrupted the language editor, so it has been left it as-is.

**Comment by sbulen** [comment]
Thanks for all the other info.

One last question:  How did you perform the UTF8 conversion in 2.0?   Did you use the SMF function to do so?

**Comment by Bopske** [comment]
> One last question: How did you perform the UTF8 conversion in 2.0? Did you use the SMF function to do so?

I did not. Due to an earlier move of the forum the database was already updated to UTF8. Using the forum function caused the database to get corrupted as well, so I had to make the change by hand: 
- updating the language files
- update all users
- adding the characer set setting to settings.php

Do you think there is another location where the characters set is kept in the database?

**Comment by sbulen** [comment]
> Do you think there is another location where the characters set is kept in the database?

I'm just trying to understand the history.  I'm trying to connect the dots.  I'm a relative noob here, just started helping out in January.  

Like you, I had to convert my 2.0 forum to UTF8 by hand as well a couple years ago.  

I ran a 2.0 => 2.1 upgrade using the latest code from github yesterday and the Dutch portion of my forum looks good.   My Russian, Portuguese, German all look good.  My sample sizes are all small though, 6-60 topics each - social only; my site's technical discussions are all in English.   I don't see that een word that gave you trouble.

The BIG difference between us is that the UTF8 processing was completely bypassed on my forum.  It didn't even try.  I don't understand why it touched your tables at all based on the info you provided. 

I'll look deeper.  So maybe there is another setting out there.  

More questions:  
 - Did you run the latest github version?  Or the download from the SMF website?   
 - Could you copy some samples of the specific text that was mangled?

**Comment by albertlast** [comment]
Would be not the easiest way to skip the utf8 part when in the setting utf8 is standing?
It's than a problem of user when he forgot some steps...

**Comment by sbulen** [comment]
It does though...  At least for me.   Gotta go read the code again...

**Comment by albertlast** [comment]
well he did not alright,
he had to change his language manuel from 'dutch-utf8' to 'dutch'.

So here are two kinds of issue one would be to skip the automatic part,
and warn the user that he had to do stuff...

**Comment by sbulen** [comment]
A proper 2.1 conversion would have left him with an 'english' language (no '-utf8'), as we don't have any other languages available yet, and languages do not need to specify '-utf8' anymore.   

So for some reason, at first glance it looks like some portions of the 2.1 upgrade ran when they shouldn't (mangling his text)...  And others did not run when they should (pointing to 'english')...

**Comment by albertlast** [comment]
but we only cut the -utf8 off without setting english? https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L1105

**Comment by sbulen** [comment]
Oops, sorry, you are correct.  It should look as above for english.   So maybe that's OK...

In my mind, two questions remain:
  -  Why did it re-do UTF8?
  -  And, a deeper question, why did that UTF8 conversion (though unnecessary) corrupt data?

**Comment by Bopske** [comment]
> Did you run the latest github version? Or the download from the SMF website?
Could you copy some samples of the specific text that was mangled?

I used the github version (as stated before)

Text examples are:
één  has become Ã©Ã©n
ideeën has become  ideeÃ«n
(not easy to find other charcters, but they will be there)

**Comment by Bopske** [comment]
Did I have to make a manual correction before upgrading? I ended up with English after the upgrade. I manually added dutch later...

> well he did not alright,
he had to change his language manuel from 'dutch-utf8' to 'dutch'.

Please elaborate...

**Comment by sbulen** [comment]
Oh good, thanks, that explains that.

**Comment by sbulen** [comment]
Rjen -  In your *2.0* environment, what is the value of the 'global_character_set' variable in the settings table?

I believe it needs to contain 'UTF-8' for the UTF8 conversion to be bypassed by the SMF 2.1 converter.

**Comment by Bopske** [comment]
In the 2.0 forum: entry is NOT in the table. In 2.1 it says: UTF-8

Seems like a root cause. Now, how does this setting normally get added?

**Comment by sbulen** [comment]
I just confirmed by looking at the code.  'global_character_set' is set by 2.0 when the UTF8 conversion is completed.   I am not aware of a utility to add this setting other than the conversion.  

Since you had to do the UTF8 conversion manually, I think you'll have to add the setting manually.  

I would use phpMyAdmin, pull up the smf_settings table, & click on the Insert tab & do the following:
![image](https://cloud.githubusercontent.com/assets/23568484/24084892/98a9ba40-0caf-11e7-8af1-35f62b39a2c1.png)

This is equivalent to doing the following in the SQL tab:
INSERT INTO \`smf_settings\` (\`variable\`, \`value\`) VALUES (\'global_character_set\', \'UTF-8\');

Choose which technique you are more comfortable with.  If your prefix is different than 'smf_', change the above accordingly.

(If there is a better way here, SMF'ers, please chime in!)

**Comment by Bopske** [comment]
Great. I ll try that and do another test. Need to rebuild the 2.0 first.

**Comment by sbulen** [comment]
I hope this is it...   

If so, it answers my 1st question above.   But not my 2nd question...  Which I suspect is tied to this issue: Problem reading arabic text after upgrading. #3972

**Comment by kipaslampu** [comment]
>  would use phpMyAdmin, pull up the smf_settings table, & click on the Insert tab & do the following:
Tried to do above.. but mysql said:
Duplicate entry 'global_character_set' for key 'PRIMARY'

**Comment by sbulen** [comment]
@kipaslampu - that fix won't work for your issue, unfortunately.  You can't even get to a full UTF8 database...

**Comment by Bopske** [comment]
Just added the global charcter set variable, and the direct result is that option to convert to UTF8 in the admin panel is no longer available (that's good), but now the option ' Convert HTML-entities to UTF-8 characters'  is shown.

Should that be excuted, should I ignore it or is there another 'global variable'  missing?
I cannot do the test upgrade untill tonight, so direction on this might be helpful before then...

mmm, just checked the use of this option: does not seem to be mandatory, nor does it seem to be required for my forum. Let's try the upgrade process first...

**Comment by sbulen** [comment]
It's purpose is to convert these html codes to utf8 characters:
https://dev.w3.org/html5/html-author/charref

E.g., &nbsp

Not required.

**Comment by sbulen** [comment]
@ArjenWelling - What do you recall about the failure in your earlier attempt to convert to UTF8 in SMF 2.0?

Did the first UTF8 conversion result in a mix of UTF8-general-ci and latin1-swedish-ci?   Or were all consistently UTF8-general-ci?

Did you need to convert remaining latin1-swedish-ci tables by hand?   How - by changing the collation in phpMyAdmin?  

Did you find troublesome data in one of your tables?   If so, how did you identify it & fix it?

**Comment by Bopske** [comment]
Setting the global variabele solved my problem. The upgrade now skipped the UTF8 conversion.  The result is finally ok.

As for the questions: I never ran the UTF8 conversion in my forum but I moved the forum a few years ago and I suspect I accidentally restored a UTF8 backup then. Hence my UTF8 tables .

Then trying UTF8 conversion in test forums gave me the exact same problem as in the upgrade. That is the reason I had to convert manually.

**Comment by Bopske** [comment]
The manual conversions I did using Phpmyadmin

**Comment by sbulen** [comment]
I think we can close this?   

I'm tracking down root cause in the other UTF8 issue: #3972 .  No need to keep multiple open.

**Comment by Bopske** [comment]
This can be closed
