### ISSUE TITLE
Current Theme (Curve2)  Only variables should be passed by reference 

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#3983]
Got the error message when i open the current theme in admin area,
maybe i break something by my own...
PHP 7.1.1

Notice: Only variables should be passed by reference in G:\github\SMF2.1\Themes\default\Themes.template.php (set_settings sub template - eval?) on line 585

 ich12
Today at 04:17 pm
::1  
afe3874049903470bf1ca645ff3947dc
Type of error: General
8: Only variables should be passed by reference
http://localhost/SMF2.1/index.php?action=admin;area=theme;sa=list;th=1;ca1be848=afe3874049903470bf1ca645ff3947dc
File: G:/github/SMF2.1/Themes/default/Themes.template.php (set_settings sub template - eval?)
Line: 585

**Comment by frandominguezl** [comment]
Disable template eval and see if the error persists

**Comment by albertlast** [comment]
litte change in the error msg:

ich12
Today at 06:10 pm
::1  
8130c62ed5b314572c6acda34511b4d0
Type of error: General
8: Only variables should be passed by reference
http://localhost/SMF2.1/index.php?action=admin;area=theme;sa=list;th=1;e00078b713=8130c62ed5b314572c6acda34511b4d0
File: G:/github/SMF2.1/Themes/default/Themes.template.php
Line: 585

**Comment by sbulen** [comment]
I recall a recent PR along these lines...   Maybe a clue here? 

Fix "only variables should be passed by reference" error #3926

**Comment by sbulen** [comment]
Looks like the same problem.  I think you just need to split the call into 2 lines, just like in #3926
