### ISSUE TITLE
Recaptcha only uses file_get_contents while may be disallowed

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#3991]
Unless I am reading the code wrong, we only utilize the Post method for recaptcha.

However there are 2 possible issues we don't check for.
1. file_get_contents(): Unable to find the wrapper "https"
2. https:// wrapper is disabled in the server configuration by allow_url_fopen=0

The Curl and fsocket methods can get around these.  But it doesn't look like we have the ability to specify that at all during the setup or recaptcha.

**Comment by Sesquipedalian** [comment]
Subs-Package.php contains a lovely little `fetch_web_data()` function. Perhaps using it instead of `file_get_contents()` could solve the problem?

**Comment by sbulen** [comment]
cURL is not always enabled in php yet.   

We now check for https stream support in the installer & upgrader - but only issue a warning if it's not found.

I.e., I don't think we can assume curl or https.

**Comment by sbulen** [comment]
fetch_web_data looks to use curl if it's available, & falls back on fsockopen...
