### ISSUE TITLE
Upgrader - collation set inconsistently, db may not be fully UTF8

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3992]
In some instances, the 2.1 upgrader will build new tables in latin1_swedish_ci, not UTF8 as expected:
![new-tables-not-utf8](https://cloud.githubusercontent.com/assets/23568484/24388741/9aae62fe-1331-11e7-884e-8a1cd50fbbe9.JPG)

The problem is that the upgrader is inconsistent in how it sets charset & collation.  It uses two techniques.  The first method is substituting 'ENGINE=MYISAM;' with a string containing the collation:
![image](https://cloud.githubusercontent.com/assets/23568484/24388807/021b952e-1332-11e7-8193-eec17a5bbe22.png)

The second method is doing a substitution within parse_sql based on $db_collation:
![image](https://cloud.githubusercontent.com/assets/23568484/24388854/3dd6221e-1332-11e7-97c8-eb311b7cc464.png)

Some tables are setup to use method 1:
![image](https://cloud.githubusercontent.com/assets/23568484/24388937/c4dd4bc0-1332-11e7-838a-7899758f94a0.png)

And some are setup to use method 2:
![image](https://cloud.githubusercontent.com/assets/23568484/24388894/7c716754-1332-11e7-9f3c-b874546b0437.png)

The issue is with method 2...   It appears to me that _the upgrader actually never sets $db_collation_.  It appears blank at execution time.  But this is not normally visible, since the UTF8 conversion step in the 2.1 upgrader steps through the tables and fixes any tables not yet utf8_general_ci.   It appears the UTF8 conversion step covers up this issue...  

HOWEVER...  What happens when the DB has already been converted to UTF8, for example, using the 2.0 maintenance tool?

It appears the 2.1 upgrader skips the UTF8 conversion process, leaving the tables exactly as they were created.  They are created using the DB-level default charset & collation, normally latin1_swedish_ci.  

The simplest fix is to set $db_collation in the upgrader.   (A functioning micro-kludge.)  Or, cut over all new tables to using Method 1 by deleting the {$db_collation]..  

I believe the steps to verify are simple:  Convert your DB to UTF8 using the 2.0 maint menu.  Confirm your DB-level default collation is still latin1-swedish-ci (the MySQL default).  Run the 2.1 upgrader.  Look at the collation for the 5 tables in the first image above after migration.

Input welcome...  Am I missing something????   I'm surprised I never noticed this before...

**Comment by kipaslampu** [comment]
Thanks. Can u put the code by text? i will try it..

**Comment by sbulen** [comment]
@kipaslampu -

There are two PRs that I think relate to your situation.  The changes can be found here:
  -  https://github.com/SimpleMachines/SMF2.1/pull/3993/files    (this one, collation inconsistent)
  -  https://github.com/SimpleMachines/SMF2.1/pull/3984/files    (mangled UTF8 data upon upgrade)
  
I'd like you to run a full 2.0 => 2.1 upgrade after these are both approved, to confirm all is as expected.  That may take a few weeks though, as the team needs time to test.

**Comment by sbulen** [comment]
I just realized why I haven't seen this particular issue consistently before.  I normally set my db-level default collation to utf8_general_ci.  I recently rebuilt my test environment, & did not do so.  

I doubt most folks do this, so the symptoms in this PR are likely more common for folks doing a fresh upgrade from 2.0 => 2.1 in MySQL.  

I had proposed earlier having SMF set the db-level default collation in this thread: (Installer & Upgrader - Enhancement suggestion: set DB default collation #3848 ).   After lengthy discussion, it was decided to leave it alone as the tables are normally built properly.   This issue identifies an exception.

**Comment by sbulen** [comment]
It bugs me that db_collation is always blank in the upgrader, so I researched this...

I believe the reason db_collation is always blank is that the logic to build it attempts to make sure the current version of MySQL is greater than the supported version:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L1627

I think the > should be a <...    

The problem is that this logic is very old, and I think it has pretty much always been this way.  I'm more afraid to fix it than leave it alone...  (All of upgrade_2-0-mysql.sql uses the db_collation method to set collation...)   

I've confirmed the current PR submitted works fine with several tests, so I'll leave it as-is.  

The things that keep me up at night...

**Comment by jdarwood007** [comment]
I hate the eval more.

The check would read as: $databases[$db_type]['utf8_version'] > $databases[$db_type]['utf8_version_check']

so I think it should be flipped as well.  Although the comment mentions MySQL.  Is this PostgreSQL safe?

**Comment by sbulen** [comment]
The Eclipse debugger hates those "inline" evals, too...  It tries to find the file for the source code...  And boffs your debug session when there is no file to find...  

That section is _intended_ to be specific to MySQL.   I'm not sure it actually is, though, so I think it's a good thing that comparison fails every time... 

I think that code is from a bygone era where it was uncertain if MySQL provided collation support, and it would apply it conditionally.  I think if we were to try to clean it up, that whole chunk of code in upgrade.php from ~1627 - 1663 should be collapsed to the equivalent of:

```
If MySQL
    $db_collation = ' DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci'
else
    $db_collation = ''
```

I'm not sure I want to do that, though.   

My concern is that it is working now, and I'm not sure what a non-blank $db_collation would do during processing of upgrade_2-0-mysql.sql, where {$db_collation} is used extensively.  That would, I think, necessitate a bunch more testing...  So in my mind it is much safer to simply get rid of that entire section and go with:  
`    $db_collation = ''`

That'd be my vote.  Just set it to an empty string.

**Comment by sbulen** [comment]
What's even stranger about that logic in upgrade.php from ~1627 - 1663 is that it attempts to set $db_collation to what it finds _in the members table..._    Pre-conversion...

What if members ain't UTF8 yet?   Again, I think that code served a different purpose at a different time.

One more tidbit - {$db_collation} is not used in the upgrade_2-*_postgresql.sql files.   In that fashion, it's pg-safe.
