### ISSUE TITLE
UTF8 conversion - template not displayed

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3996]
The UTF8 conversion always executes 'in the background', meaning, the template does not kick off & tell you what it's doing.   You want the template displayed when the UTF8 update executes.  

This is EASILY fixed by making the UTF8 conversion end-of-step return 'false' like all of the other multi-substep steps.  E.g., compare the utf8 conversion end of step:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L2915

With the backup end of step:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L1210

Or the JSON end of step:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L3190

Or the DB-changes end of step:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L1320

Returning false properly displays the template...  

_**HOWEVER...**_   

Then the continue button doesn't work and you can't move past the UTF8 step.  I have not found a way to enable the template - that doesn't leave you stuck in the UTF8 step.  

There are a few little step & substep management code snippets used in the JSON and backup steps that are not used in the UTF8 step.  Even adding these, I still haven't been able to get it work properly.  Specifically, the continue button remains 'disabled' at the end of the UTF8 step.  It's driving me nuts...   I'm probably missing something simple somewhere...

**Comment by sbulen** [comment]
THIS one...  Is a PITA...  Every time I poke it with a stick, it pokes back...

**Comment by sbulen** [comment]
For some reason the UTF8 template is only being displayed once, at the very end, where other templates are displayed only once, at the very start.  

The little inline javascript in the template is supposed to "watch" and only enable the button when it sees it work on the last item.  But the javascript never "sees" the last table complete for the utf8 step, because the template is painted too late in the process at "step completed"...   

My theory is that the root cause is a problem with step & substep tracking.  The upgrader actually tracks steps & substeps in multiple places.  (That's why the URL is wrong as the upgrader executes...)   

For the UTF8 conversion step, for some reason the step & substep aren't reset.  I believe this is why the template doesn't kick off as expected.  

Fixing the step/substep issue may make the 'restart' links work as well.  They don't work at the moment, because the step & substep used by the restart (in the red restart dialog box) are the wrong ones; they take you back much earlier in the process.

**Comment by sbulen** [comment]
Certain substeps are invoked ~7000 times each during the database conversion.  Which is extremely odd, given I'm testing with a forum with only ~10 posts in it (each a different language that requires utf8).  Only one user.

**Comment by sbulen** [comment]
Got to the root of the skipped templates...   They're not really skipped, the "xml" version is invoked, and it is hidden.  The code intends to invoke the 'non-xml' one FIRST, to paint the screen, then let the xml template & inline .js take over.  The problem is that once the xml flag is set, it is never unset, so it will only invoke the hidden xml templates from there on out where available.  So the whole thing will only work once.  (This is why, once you _think_ you have it fixed, a _different_ template disappears...)

**Comment by sbulen** [comment]
The 3 steps that invoke thousands of substesps & take a very long time (on my near-empty forum) are the 3 DB upgrade steps that invoke MySQLConvertOldIp.  That needs a peek...

**Comment by sbulen** [comment]
I believe I found the issues with MySQLConvertOldIP: 
(1) The big one: the array arIp is never reset, it always has the values found.  Consequently the internal loop never knows it's done.  I don't know how the step ends at all; it appears to move on via the nextSubStep logic somehow.  This explains why my empty forum and my 20Kuser 200Kpost forum both take the exact same ~30 seconds to do the same step.  
(2) Minor, but the trace complained that the 'a' index was not defined.  
(3) Minor, but deleting a column before deleting its single-column index is redundant, as deleting the column also deletes the index.  Swapping the order will divide the work into two smaller steps.  

I can fix these & test. 

The template issues are compounded - I've been able to properly set the sub-template by addressing the xml flag as described above, but for some reason the template still isn't called & rendered.  And each of the steps behaves a bit differently...  One layer of the onion at a time...

**Comment by sbulen** [comment]
OMG...  a freaking typo...  I've been staring at it for two weeks...

**Comment by jdarwood007** [comment]
The next step logic works on the select * from table LIMIT X OFFSET Y.  If COUNT(results) < X then we break out and are done.

**Comment by sbulen** [comment]
Yeah, I get that...   But why isn't the button active?  Why doesn't it display UTF8 as it's going along?

I *just* noticed that a big part of the reason is a typo...   This line determines which subtemplate to call:
`$upcontext['sub_template'] = isset($_GET['xml']) ? 'convert_xml' : 'convert_utf8';`
But the two funcs are:
`function template_convert_utf8()`
and:
`function template_utf8_xml()`

There is no template_convert_xml, it's template_utf8_xml...

It *NEVER* calls the xml template, because it has the name wrong.  It will never enable the 'continue' button without the xml template being painted.

I'm about to make a few more changes & test...  It's another piece of the puzzle.   I'm surprised we don't see any error at all calling an invalid function in the call_user_func().

**Comment by sbulen** [comment]
call_user_func simply returns false if passed an invalid function name.  This is indistinguishable from a function properly returning false.  It should be tested for a valid function first.
