### ISSUE TITLE
Installer - Paths & setting not set

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3999]
Brand new downloads from git.  Just installed.  Copied the Install*.* files and settings.php to the main directory prior to install.  

Issues (/questions) noted:

(1) Several paths do not appear to be set properly in settings.php, they still say (__FILE__).  Most are set properly and specify the full path.  
(2) Repair_settings does not populate/show paths for these, it appears to be unexpected.  Repair_settings does, in fact, repair the paths if you click on the recommended values & press save.  
(3) Repair_settings complains about a setting not set - queryless URLs - should that be set by the installer?

Minor things, but I don't think you should have to go to repair_settings.php to complete a plain vanilla install.  

![install-paths-1](https://cloud.githubusercontent.com/assets/23568484/24686916/937089dc-196b-11e7-939a-01756d487e1f.JPG)
![install-paths-2](https://cloud.githubusercontent.com/assets/23568484/24686917/93720294-196b-11e7-98f9-c1f89527c416.JPG)
![install-paths-3](https://cloud.githubusercontent.com/assets/23568484/24686915/93708af4-196b-11e7-9436-cf8acde61446.JPG)

**Comment by sbulen** [comment]
I am unsure what the real intent & approach is here.  I always thought settings.php had a simple set of fully qualified names.  Just enough to get to the DB.  Everything else was in the settings table.  

I'm not sure I like the "logic" in there, e.g., how the \tasks directory is built.  And everything from the "*** error-catching ***' line on down. 

In that vein, my thoughts are that the solution is to:
1) Set a fully qualified $packagesdir, in a fashion consistent with all other settings
2) Set a fully qualified $tasksdir, in a fashion consistent with all other settings
3) Set Queryless URLs in the installer and the upgrader, default to Off
~~4) REMOVE all logic from the "*** error-catching ***' line on down.   Make sure db_last_error.php, $boarddir, $sourcedir & $cachedir are all properly built/set in the installer.~~

Does this sound right?

**Comment by sbulen** [comment]
Hmmm...  Hadn't noticed it before, but item 4 (the 'make sure the paths are correct' section) above exists in all of my vanilla 2.0 environments, so I guess it's OK to leave it as-is.   

(My forum, which has been patched since 1.1, does not have all of that code.  So a 'patched to' 2.0 has a slightly different settings.php than a 'vanilla' 2.0.)

I think that items 1-3 above should be dealt with, though.

**Comment by sbulen** [comment]
I was hoping someone more familiar with the reasons the installer & settings.php behave the way they do could tackle this one...

**Comment by Oldiesmann** [comment]
The `dirname(__FILE__)` thing is normal. That gets the path to the directory the current file is in. I'm not sure why the Tasks and Packages directory aren't set for you. The queryless URLs thing isn't a big deal as it's assumed to be off if it's not set, but it's something we can look into.

**Comment by sbulen** [comment]
Found the issue with the paths - yes, the installer does not deal with the tasks & packages directories.  It's inconsistent with all other paths.  I'll sub a PR for that.  

I'll leave the setting alone, per the notes above.
