### ISSUE TITLE
Installer vs Upgrader - DB differences

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4000]
I have noticed a few of these by chance, so I performed a more rigorous comparison.  

Install a vanilla 2.0, then upgrade it to 2.1.  Install a vanilla 2.1.  Export the data structures & compare.  

How different should the DBs be?  

Differences I am seeing are:
  -  Different defaults - only a few of these
  -  Indexes missing - only a few of these
  -  Differences in signed vs unsigned - only a few of these
  -  Differences in text types - e.g., text vs mediumtext - several of these
  -  Differences in int types - e.g., int vs mediumint - several of these
  -  Differences in int display lengths - e.g., int(3) vs int(4) - **_LOTS_** of these
  -  Differences in index names - **_LOTS_** of these

Suggested actions:
  -  Different defaults **_- need alignment, case-by-case_**
  -  Indexes missing **_- Add the MISSING one..._**
  -  Differences in signed vs unsigned **_- Change to Unsigned..._**
  -  Differences in text types - e.g., text vs mediumtext **_- Unsure, input welcome_**
  -  Differences in int types - e.g., int vs mediumint **_- Unsure, input welcome_**
  -  Differences in int display lengths - e.g., int(3) vs int(4)  **_-  IGNORE_**
  -  Differences in index names  **_-  IGNORE_**

Most of the default differences are NULL vs ''.  Input welcome.

This is all MySQL - I don't have a pg to do an equivalent comparison.  

Thoughts please.  I think MOST of these can be safely ignored, but not all.  

![differences-1](https://cloud.githubusercontent.com/assets/23568484/24689394/10ba036e-197b-11e7-8c32-6c97ff628246.JPG)
![differences-2](https://cloud.githubusercontent.com/assets/23568484/24689392/10b8640a-197b-11e7-90b5-947e9a238d4e.JPG)
![differences-3](https://cloud.githubusercontent.com/assets/23568484/24689395/10ba356e-197b-11e7-94c0-2eaf066f7e6a.JPG)
![differences-4](https://cloud.githubusercontent.com/assets/23568484/24689391/10b6b20e-197b-11e7-8ac5-86b91bf234b0.JPG)
![differences-5](https://cloud.githubusercontent.com/assets/23568484/24689393/10b983d0-197b-11e7-8112-f7f9fb70ca42.JPG)
![differences-6](https://cloud.githubusercontent.com/assets/23568484/24689396/10cdfdec-197b-11e7-872f-38fb4e03f805.JPG)

(*** Note: I converted everything to InnoDB so these would not show up as differences...***)

**Comment by albertlast** [comment]
Let me comment this pictures per line:
mediumint didn't exists with (x)  -> left side is wrong
text vs mediumtext makes for the database no different -> right is wrong

The index looks good to hav -> left side is right
the index could be valid to -> right side is right (this index is missing on pg too)

varbinary(16) = ip fields need to be null able ->right side is wrong

i don't like unsigned in general because pg doesn't support this  -> we got different min max value between mysql and pg installation, would take the right solution

index of the email field ist right

id_board col exists in many other different index -> left side is right

**Comment by sbulen** [comment]
Thanks @albertlast.

These are just examples...   There are plenty more differences. 

I'm not sure I'm comfortable getting rid of the UNSIGNED clauses.  There are LOTS of them, and they make sense to me.   I'm surprised there Is no support in pg.   Is there a possibility pg will support unsigned in the future?

**Comment by albertlast** [comment]
As fare i can see no other database(oracle, ms sql and pg) support unsigned types
so it's a mysql "curse".

Without to dive to deep in this topic,
but because no other db implent this function I think this function is bad (otherwise the other would support this).

**Comment by Oldiesmann** [comment]
I'll take a look at things when I get a chance, but we should try to make them as consistent as possible regardless of whether the change actually makes a difference.

**Comment by sbulen** [comment]
Some of the changes seem like a good idea - e.g., getting rid of "unsigned" and int display lengths - because @albertlast is correct, they are MySQL quirks not supported elsewhere.  

However...  It is not just a simple case of changing them...  Bear in mind that a lot of this is carryforward from 2.0, and will exist in all upgraded forums (without significant changes to the upgrader).  Changing how new tables are created by the installer under 2.1 to enforce new standards will yield even MORE differences between new & upgraded forums.  

I view this as two options, either (1) live with the basic 2.0 structures, MySQL quirks and all, or (2) make a significant amount of changes in the upgrader.  Given where we are at, my suggestion is to leave the rewrite of the upgrader to 3.0...  

That would mean that, for now, I would suggest focusing on the short list of substantive changes (defaults, indexes, types).

**Comment by illori** [comment]
the index on the email column was added for performance. it was suggested sometime ago in the team dev board. it was added only on the install for some reason. you would need to ask @arantor for more information on why it was not added to the upgrade. i would not suggest you remove that.

**Comment by sbulen** [comment]
@Oldiesmann  -  OK I'll leave this in your hands since you're taking a look at it.

**Comment by sbulen** [comment]
I ended up looking into this...   I'll have a PR submitted for consideration.

**Comment by sbulen** [comment]
PR #4311 submitted.
