### ISSUE TITLE
Postgresql search issue with "

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4005]
When you search for "in berlin" than the double quotes create a sql syntay error

`WHERE to_tsvector('pg_catalog.german',body) @@ to_tsquery('pg_catalog.german','"in berlin"')`

the solution could be to replace " with two single quotes ''

**Comment by jdarwood007** [comment]
Why isn't the database safe escape here handling this properly?

**Comment by albertlast** [comment]
Easy anwser,
we use here the database text search function.
In this are double quotes not allowed.

**Comment by jdarwood007** [comment]
But the query passes through the db_query which should be using a {string} type match and passing that into pg_escape_string to ensure its safe for database queries.  I'm confused and thinking the issue is something else because we should be cleanly handling this somewhere else.

**Comment by albertlast** [comment]
please look first in the documentation of the database before your try to solve this in different direction.
https://www.postgresql.org/docs/current/static/textsearch-controls.html#TEXTSEARCH-PARSING-QUERIES

there you find:

> ... to_tsquery can also accept single-quoted phrases... 

--> no double quote support.

This is a special case for the search stuff,
so we can not fix this issue on generic database layer.
