### ISSUE TITLE
Search Wrong handling of single quote

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4006]
When you try to find text where "you're" is used, you will not find one.
Because the single quote will be transformt into html thing ' -> &#39;
but the text are with '.

Solution would be somehow that single quote will be translated to two single quotes,
than sql search can find this text.

**Comment by BloberSh** [comment]
Has this been fixed with beta 3?

I can't reproduce it. 

I created a post with "You're" in the text and the title.
If i modify both to get the string in both text or title, the search find it.

**Comment by albertlast** [comment]
Looks good.
