### ISSUE TITLE
Set HTTPS Board URL on Install

### ISSUE THREAD

**Issue by colinschoen** [SimpleMachines/SMF#4011]
When installing SMF http:// is set as the protocol even if force SSL is enabled in the installer. We should set the board url to be https:// if that is where the installer is loaded from or force SSL is enabled.

**Comment by albertlast** [comment]
is in my eyes related to https://github.com/SimpleMachines/SMF2.1/issues/3726

**Comment by XinYenFon** [comment]
@albertlast yeap, me too.

**Comment by sbulen** [comment]
A bit of a difference, though: #3726 says that theme_dirs are missed after "the change to SSL".   I understood this to be the upgrader &/or an admin function.  

This Issue specifically refers to the installer.    And more than the theme_dirs.

**Comment by sbulen** [comment]
This is how things look to me...   Please let me know if I'm on track...

 - The installer may set SSL on upon request
 - The upgrader does NOT alter the SSL setting, it leaves everything as-is ~~(however, the upgrader creates image proxy settings & assumes they're new & diabled - this is an issue which I recorded elsewhere #4179 )~~  
  - There is a 2.1 admin function to Force SSL throughout the forum.  

There are several settings that remain http: even after forcing ssl throughout the forum:
 - $boardurl, as reported above (settings.php)
 - avatar_url (settings table)
 - custom_avatar_url (settings table)
 - smileys_url (settings table)
 - theme_url (once per installed theme - in themes table)
 - images_url (once per installed theme - in themes table)

Is there anything else lurking out there?

**Comment by sbulen** [comment]
As an FYI...   

If you invoke the installer via:
  -  `https://yourboard.com/install.php,` then everything works - all 6 URLs named above start https:// 
  -  `http://yourboard.com/install.php`, then all  6 URLS above start http://

AND...  .htaccess redirects apply...  So...  

If, after install, your $boardurl is http://, both of these conditions must be true:
   -  You didn't have your .htaccess redirect setup yet at the time of install, AND...
   -  You invoked the installer as http://

Still thinking what to do about it, though.

**Comment by sbulen** [comment]
I'm still trying to figure out what the appropriate solution is here.  I see 3 related issues:
  -  #4011, this one (https upon install)
  -  #3726 theme settings
  -  #4195 upgrading an https forum

These are all related in the broadest sense, because there are a few interrelated SSL settings, and we need to make sure they are properly in sync - whether during installs, upgrades or admin setting changes.   Here is my understanding as to how the settings interrelate:

![image](https://user-images.githubusercontent.com/23568484/28450487-82547a84-6d9c-11e7-806e-78706d4e574f.png)

The types of questions I have...
 - Is the above accurate?
 - Are there other parameters involved that should be taken into consideration?
 - Should changes to $boardurl change the force_ssl setting & URLs?  (whether tokens or not)
 - Or should changes to force_ssl change $boardurl & the URLs?  (whether tokens or not)
 - Will our usage of $_SERVER["HTTPS"] always work, even for IIS, given the above?   
 - How sophisticated does repair_settings.php need to be, should it enforce these rules?

**Comment by sbulen** [comment]
Added some info to the table above...

**Comment by sbulen** [comment]
This is my proposal for this set of related SSL setting issues.  

The Installer, the Upgrader, and the Admin Control Panel should honor these 3 rules:
(1) If a redirect from http to https exists, force_ssl MUST be 2
(2) If NO certificate exists, force_ssl MUST be 0
(3) If a certificate exists, AND no redirect exists, force_ssl MUST be 1

The user does not update the force_ssl setting at all.  

I don't think we should change anything in repair_settings.   I don't think we should update URLs "behind the scenes" in the Admin control panel.  Just stick to the 3 rules above, and let folks fix URLs themselves explicitly in the ACP or repair_settings.  (As soon as we hard-code URLs, someone will need an exception...)

I've been testing cert & redirect detection logic.  The following work:  
```
//*** Check if current domain has a cert
// Adapted from: https://stackoverflow.com/questions/27689147/how-to-check-if-domain-has-ssl-certificate-or-not
// 
function ssl_cert_found() {

	$url = 'https://' . $_SERVER["SERVER_NAME"];

	$result = false;
	$stream = stream_context_create (array("ssl" => array("capture_peer_cert" => true)));
	$read = @fopen($url, "rb", false, $stream);
	if ($read !== false) {
		$cont = stream_context_get_params($read);
		$result = isset($cont["options"]["ssl"]["peer_certificate"]) ? true : false;
	}
    return $result;
}

//*** Check if $boardurl has a redirect to https:// by querying headers
// 
function https_redirect_active() {

	global $boardurl;

	// Ask for the headers for the current $boardurl, but via http...
	// Need to add the trailing slash, or it puts it there & thinks there's a redirect when there isn't...
	$url = str_ireplace('https://', 'http://', $boardurl) . '/';
	$headers = get_headers($url);
	if ($headers === false)
		return false;

	// Now to see if it came back https...   
	// First check for a redirect status code in first row (301, 302, 307)
	if (strstr($headers[0], '301') === false && strstr($headers[0], '302') === false && strstr($headers[0], '307') === false)
		return false;
	
	// Search for the location entry to confirm https
	$result = false;
	foreach ($headers as $header) {
		if (stristr($header, 'Location: https://') !== false) {
			$result = true;
			break;
		}
	}
	return $result;		
}

```

**Comment by sbulen** [comment]
A less draconian version may be to just honor rules 1 & 2 above...

**Comment by sbulen** [comment]
PR #4225 submitted for this.

**Comment by sbulen** [comment]
New PR submitted, #4245

**Comment by colinschoen** [comment]
Thanks for fixing this!
