### ISSUE TITLE
Throw 404 when unable to load image in proxy

### ISSUE THREAD

**Issue by colinschoen** [SimpleMachines/SMF#4013]
When an image link is broken we should throw a 404 rather than redirecting to the actual nonsecure broken asset URL.

This will be back ported to 2.0.14 and is the last thing we need for that release.

**Comment by colinschoen** [comment]
ETA will have time to work on this starting on Tuesday.

**Comment by qcybb** [comment]
Is this really that serious of a bug?

I know lots of us are desperately waiting for the 2.0.14 release for HTTPS / PHP 7 compatibility.

**Comment by jdarwood007** [comment]
This breaks HTTPS by loading a unsecured resource and exposing the HTTPs urls.  Browsers throw alerts and/or don't load the content when this occurs.

**Comment by XinYenFon** [comment]
@Mayhem30 do mind this place is not for SMF 2.0.x.

**Comment by qcybb** [comment]
@Antes I understand that, but I only replied here because the 2.0.x branch is hidden on GitHub and @colinschoen stated "This will be back ported to 2.0.14 and is the last thing we need for that release".

I hope you guys get this sorted out soon, as this issue has been open for 9 days already.

**Comment by XinYenFon** [comment]
There is no repo for SMF 2.0 in GitHub. Even tho this is a mirror issue for both versions, its better to keep things separated from each other to track easier.

**Comment by Mayhem30** [comment]
Isn't this an easy fix - or am I missing something?

Find in : proxy.php
`	protected function cacheImage($request)
	{
		$dest = $this->getCachedPath($request);

		$curl = new curl_fetch_web_data(array(CURLOPT_BINARYTRANSFER => 1));
		$request = $curl->get_url_data($request);
		$response = $request->result();`

Add After:
`		// return false for 4xx http status codes
		// (http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)
		$http_status = curl_getinfo($curl, CURLINFO_HTTP_CODE);
		if (substr($http_status, 0, 1) == 4)
			return false;`

**Comment by Mayhem30** [comment]
Isn't this a simple fix? or am I missing something?

Find in: proxy.php
```php
	protected function cacheImage($request)
	{
		$dest = $this->getCachedPath($request);

		$curl = new curl_fetch_web_data(array(CURLOPT_BINARYTRANSFER => 1));
		$request = $curl->get_url_data($request);
		$response = $request->result();
```
Add After:
```php
		// return false for 4xx http status codes
		$http_status = curl_getinfo($curl, CURLINFO_HTTP_CODE);
		if (substr($http_status, 0, 1) == 4)
			return false;
```

**Comment by qcybb** [comment]
Isn't this an easy fix or am I missing something?

Find in : proxy.php
```php
	protected function cacheImage($request)
	{
		$dest = $this->getCachedPath($request);

		$curl = new curl_fetch_web_data(array(CURLOPT_BINARYTRANSFER => 1));
		$request = $curl->get_url_data($request);
		$response = $request->result();

		if (empty($response))
			return false;
```

Add After:
```php
		// throw 404 error & return false for 4xx http status codes
		// (http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)
		$http_status = $response['code'];
		if (substr($http_status, 0, 1) == 4)
		{
			header("HTTP/1.x 404 Not Found"); // or throw 404 page?
			return false;
		}
```

**Comment by illori** [comment]
@colinschoen should this be closed or are there other issues?
