### ISSUE TITLE
Upgrader executes the prior version also...

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4014]
I'm not sure if this is a question or an issue....  

When doing a 2.0 => 2.1 upgrade, the upgrader executes both the `upgrade_2-0_*.sql` and the `upgrade_2-1_*.sql`.   `upgrade_2-0_*.sql` brings you current to 2.0.  `upgrade_2-1_*.sql` upgrades you from 2.0 to 2.1.  

Is the `upgrade_2-0_*.sql` really necessary if you are already 2.0?   Why is it executed?  It's not really necessary for a 2.0 to 2.1 upgrade.

I know there are times the upgrader is used for support cases.  Is the logic done this way so your current version is always executed no matter what?   E.g., to enable 2.0 to 2.0 (or 2.1 to 2.1) migrations to address potential DB issues?

**Comment by sbulen** [comment]
If this is intended, I'll just close this one...  I'd like to confirm the behavior is as-intended.

**Comment by Arantor** [comment]
This is mostly so you're upgrading from a 2.0 RC it can catch all the 2.0 schema changes. It used to be the case that you could drop it on a 1.0 installation and it would upgrade from 1.0 to 1.1 to 2.0 to 2.1 without any problems.

I assume this is still the case, but as long as it doesn't break anything, I don't see any reason to change it.

**Comment by sbulen** [comment]
Thanks for the feedback @Arantor .

I thought this might be the case.  I'll close this out.
