### ISSUE TITLE
Inline attachment display in topics

### ISSUE THREAD

**Issue by Bopske** [SimpleMachines/SMF#4023]
I was reviewing the attachement layout in 2.1 and noticed the following: when multiple attachments are used of different types (files and images) the inline layout is not always perfectly aligned.

Ideally all attachments are lined up horizontally and once a new line is needed the attachements are displayed on a new line.

See the examples below: due to the float for the attachments in some configurations (combination of screen width and varying attachments) the float shows multiple attachments vertically in the same horizontal line.

'Broken' layout:
![knipsel](https://cloud.githubusercontent.com/assets/24902644/25382138/a9650c62-29b6-11e7-922e-439394a21dcb.PNG)

Ideal layout:
![knipsel2](https://cloud.githubusercontent.com/assets/24902644/25382144/ad72e432-29b6-11e7-858b-ad88f6361f19.PNG)

**Comment by XinYenFon** [comment]
Can you try the following;

Open Display.template.php
Find;
``<div class="floatleft attached">``

Replace with
``<div class="attached" style="display: inline-block;">``

**Comment by Bopske** [comment]
Better, it would be even nicer if it was vertically aligned though...

![knipsel](https://cloud.githubusercontent.com/assets/24902644/25406285/736d204a-2a06-11e7-9c0e-7ff418f1c74c.JPG)

**Comment by XinYenFon** [comment]
Well simply change inline-block with block. Still not sure what is the best approach.

**Comment by Bopske** [comment]
That will actually align the attachments vertically. That's not what I mean: it should be an inline-block, but in the line aligned to the top...

**Comment by XinYenFon** [comment]
I get your point, I'm writing code here to make sure it works for you.

Change this
``<div class="attached" style="display: inline-block;">``
to
``<div class="attached" style="display: block; width: 100%;">``

**Comment by Bopske** [comment]
That's not it, result is below. Then the inline-block is better...

![knipsel](https://cloud.githubusercontent.com/assets/24902644/25406651/bfd992b4-2a07-11e7-9c4c-c79d609c1f4c.JPG)

**Comment by Bopske** [comment]
I think that was closed by accident.

**Comment by Sesquipedalian** [comment]
What if the containing `<div>` used `display: flex; flex-flow: row wrap`?

**Comment by illori** [comment]
what browsers currently support that?

**Comment by XinYenFon** [comment]
https://caniuse.com/#search=flex - Do mind, footerfix already using flex display.

**Comment by Sesquipedalian** [comment]
Everything except obsolete versions of IE (surprise, surprise).
http://caniuse.com/#search=flex

In the discussion of #3485, it was decided that at least basic use of flex box was permitted to solve the issue, and that we were not going to worry about IE less than 11, since Microsoft itself has declared version less than 11 to be EOL.

**Comment by Sesquipedalian** [comment]
Flex wasn't necessary. Just needed to add `vertical-align: top` to @Antes' `display: inline-block`
