### ISSUE TITLE
spelling/typo

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4027]
minor issue, but i think worth fixing.

 +++  Add the index again to mesages poster ip topic done.
 +++  Add the index again to mesages poster ip msg done.

in the upgrade process.
also why the question mark here?
 +++  Force 2FA per membergroup? done.

**Comment by sbulen** [comment]
I really need a coffee.   Stared at this for 5 full minutes before catching the typo.

I'll add this to one of the upgrader PRs.  

After coffee.
