### ISSUE TITLE
mailqueue problems

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#4032]
On sending email, failed emails are put back in the queue, so on bad email adresses (bad AAA record as example) the queue will never empty.
I tested with php's error_get_last() but it seems that this not work here.

Any comment or code for this problem ?
Note: I mean the code in ScheduledTasks.php

**Comment by tinoest** [comment]
Add a counter for failed email attempts then remove email after x failures. 

Or look at the email response to rcpt to

**Comment by PortaMx** [comment]
Thanks .. if found a good solution for this probem ...

**Comment by tinoest** [comment]
Which was?

**Comment by PortaMx** [comment]
I checked the result code in "server_parse" and all mails with a RC > 500 are not put back in the mail queue ;-) .. simple and effective
