### ISSUE TITLE
create_table unsigned

### ISSUE THREAD

**Issue by interlab** [SimpleMachines/SMF#4057]
smf 2.0.xx

Please fix this: https://www.simplemachines.org/community/index.php?topic=553283.0

**Comment by albertlast** [comment]
You shouldn't use unsigned int datatypes,
this is mysql special stuff with hurt with no benefit.

And the solution posted on board looks very wrong.

**Comment by interlab** [comment]
Size does not matter in this error. **$column_info** variable does not exist.

**Comment by albertlast** [comment]
well your are here in smf 2.1 and there it's fine.
This issue can be closed.
