### ISSUE TITLE
Upgrader - fix needed

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4060]
While reviewing my recently merged upgrader PRs, I noticed that the net code merged was slightly different than code submitted.   (Github bug?)

I believe the issue can cause the upgrader to freeze under some circumstances &/or cause one of the templates to be displayed improperly.

I will test a fix with the intended code in the next day or two.

(My PRs were merged in a different order than submitted, and this resulted in slightly different net code....    Very interesting...)

**Comment by jdarwood007** [comment]
What sha1 hash do you get from the upgrade.php? and other files?

**Comment by sbulen** [comment]
This is the history...  

In the PR for Set collation type consistently #3993, I inadvertently pushed part of the UTF8 fix in the wrong branch there: 
https://github.com/SimpleMachines/SMF2.1/pull/3993/commits/d5fc3b2e91b03fc40af8414fd22b3fde9d9def94
This made the convertutf8 function return false (which is correct, but was unrelated to this PR...).  

I caught my error & immediately reversed it:
https://github.com/SimpleMachines/SMF2.1/pull/3993/commits/f603c64fb093f94287b17b8aec3a7599e52a3922
This made the convertutf8 function return true (i.e., unchanged).  

So in theory, #3993 Should have had NO CHANGE to that line of code.  _(I'm sure there would have been no issue if I squashed my commits at that time...)_

Later, while working on Fix utf8 template #4020, I fixed that line of code (line 2949 here):
https://github.com/SimpleMachines/SMF2.1/pull/4020/commits/6e631169ea94e2f444aa30d23396ae9fa3e5e602
This made the convertutf8 function return false (which is correct, & now in the correct PR...).  

Then the PRs were applied in reverse order...  

After Fix utf8 template #4020 was applied, things were correct (the function returned false).

Later, Set collation type consistently #3993 was applied.  The last commit in that PR changed the function to return true, which is wrong...

Hope this makes sense...

I'll be able to correct this by tomorrow morning.

**Comment by sbulen** [comment]
The two PRs involved were:
    Set collation type consistently #3993
    Fix utf8 template #4020

Initially I thought the template fix was easy, & started work on it in #3993.  Once I realized it was not that easy (and not related to collations...) I backed out a couple of changes.  #3993 as submitted was ONLY the collation change.  (I'm sure if I had done a squash at that time, there would have been no issue...)  

Before these two PRs, the end of ConvertUtf8 returned true.  Part of the template fix requires that it returns false.  #3993 initially had a diff that set it to false, but when I backed out that change as described above, it was left alone at true.   #4020 properly set the return at the end of CovnertUtf8 to false.  

They got applied in reverse order...   
#4020 properly set the return to false.
#3993 somehow set it back to true.  This is the part that confuses me as the _net change_ of #3993 _as submitted_ didn't touch that line.  

It's an easy fix.  I'm testing now just to be safe.

**Comment by sbulen** [comment]
Or maybe my memory is just trashed...   Either way, fix tested & submitted.  

PR #4062
