### ISSUE TITLE
Hardcoded text in cron.php

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#4072]
https://github.com/SimpleMachines/SMF2.1/blob/f7f069101cc9cb06cdc13581777a6c8df1ea1f5d/cron.php#L197
https://github.com/SimpleMachines/SMF2.1/blob/f7f069101cc9cb06cdc13581777a6c8df1ea1f5d/cron.php#L210

**Comment by Oldiesmann** [comment]
Per the comment above the first one, language files aren't even loaded at that point so we can't really translate it. I'm assuming the same is true for the second instance.
