### ISSUE TITLE
Non-default sorting on middle pages

### ISSUE THREAD

**Issue by DuncanFairley** [SimpleMachines/SMF#4075]
Sometimes when sorting the message index by specific columns and you have several pages + aren't on the first or last page, it'll try to `order by` invalid column names.

> http://example.com/index.php?board=14.440;sort=last_post
> Unknown column 'tid_last_msg' in 'order clause'
> File: Sources/MessageIndex.php Line: 305

It applies the `identifier` sanitization method to functions as well:
> http://example.com/index.php?board=14.440;sort=starter
> Unknown column 'COALESCE(memfreal_name, mfposter_name)' in 'order clause'
> File: Sources/MessageIndex.php Line: 305

**Comment by colinschoen** [comment]
Great find!
