### ISSUE TITLE
Attachment Limit: 0

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#4079]
When you set attachment limit (kb) to 0 (unlimited) SMF outputting total as 0 instead "unlimited".

**Comment by illori** [comment]
i dont think 0 should be used as some admin may view that as 0 as in you cant upload right now as the size has to be 0 vs 0 as in unlimited.

**Comment by NanoSector** [comment]
@illori it's common for 0 to mean 'disabled' though.

**Comment by frandominguezl** [comment]
Under each text, is stated that 0 is for no limit
