### ISSUE TITLE
membergroup as board moderator bugs

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#408]
@Oldiesmann 
ideally when you go to edit a board, having the list of groups that can be moderator to select from would be easier then having to remember the group name and exact spelling.

edit a board save the page with or without changes

index.php?action=admin;area=manageboards;sa=board;boardid=1
github2.1/Themes/default/ManageBoards.template.php
 Line: 436 
8: Undefined index: moderator_group_list

if the group is the moderator, nothing is shown on the board index to show that the board has any moderators, the group should be listed and when clicked on show who is in the group.

if a group has their status changed to protected the group is not removed from being a moderator of the board, the text under the area to select the group says "Groups whose members have moderation priveleges on this board. Note that this is limited to groups which are not post-based, not "hidden" and not "protected"." if that is correct then the group should automatically be removed or that text should be changed.

**Comment by Oldiesmann** [comment]
I swear all of this stuff was working when I initially tested it :P

It's supposed to show group(s) in the same place as regular moderators. I'll take a further look at things and see what's going on there. I'll also have to see what's up with the theme error.

I hadn't thought of removing groups if their type is changed to protected. I'll have to see what I can do to warn the admin about the changes as well (or preventing them from making those changes until they remove the group as a moderator, which might be a better option).

**Comment by Oldiesmann** [comment]
Theme error is a typo (it should be "moderator_groups_list" instead of "moderator_group_list"). I'll look into the rest of the stuff mentioned here tomorrow when I'm not so tired and commit fixes appropriately.

Also, I went with the auto-suggest thing for groups here to save space and keep things a bit less cluttered.
