### ISSUE TITLE
Password reminder code "invalid"

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#4080]
I'm trying to reset my password through the "forgot your password" form, and the email gets sent correctly, but after entering the password, I get a "Invalid activation code" error.

I did try it twice (now 4 times) to test email vs username entry, but none of the links sent work.

PS: This is on beta 2, but I didn't see this listed in the issues.

**Comment by albertlast** [comment]
i'm not able to test this, but use beta 3 or the github version.
Between your version and the version now are over 2k commits.

**Comment by Gwenwyfar** [comment]
Yes, sorry for the false report :/ I was now able to get it to work, it was probably just the codes canceling each other, I may have submitted twice the first time and didn't notice I was not testing the latest. I'll set this as closed.
