### ISSUE TITLE
syntax error, unexpected ',' in calendar.php on line 204

### ISSUE THREAD

**Issue by BloberSh** [SimpleMachines/SMF#4081]
Hi guys, 

I don't know this was already reported but i report it. 

When i enable the calendar (newly out beta 3) and i go on the calendar page i got this error.

This code on the error is a bit strange : 

`
// Build the calendar button array.
	$context['calendar_buttons'] = array();

	if ($context['can_post'])
		$context['calendar_buttons']['post_event'] = array('text' => 'calendar_post_event', 'image' => 'calendarpe.png', 'url' => $scripturl . '?action=calendar;sa=post;month=' . $context['current_month'] . ';year=' . $context['current_year'] . ';' . $context['session_var'] . '=' . $context['session_id']),
		);

`

cordialy

**Comment by frandominguezl** [comment]
Mmm it's in the main page of the calendar? I can't reproduce it...

**Comment by BloberSh** [comment]
Yes. 

Maybe more infos could help you : 

Php version : 7.0

Fresh install -> Go to admin -> calendar -> enable it -> Clic on calendar link (menu)

**Comment by albertlast** [comment]
Can you please provide a pictures from the error log?

**Comment by BloberSh** [comment]
![image](https://cloud.githubusercontent.com/assets/6509009/26680172/937f6106-46d8-11e7-8532-e70632823f36.png)

This one?
Edit : i just checked github file and there is no errors. It seems to be in the download package from SM.org

**Comment by albertlast** [comment]
yes the download version on sm.org and github (https://github.com/SimpleMachines/SMF2.1/releases) is different of Calendar.php and this not nice.
i believe someone did something wrong.

**Comment by BloberSh** [comment]
Hope there is only one file in this case :s .

**Comment by albertlast** [comment]
@colinschoen maybe you should look into.

**Comment by BloberSh** [comment]
I just checked on github to compare beta 2 and 3 files.

This calendar.php is the same as beta 2 file.

**Comment by colinschoen** [comment]
@albertlast Thank you. Checking into this now.

**Comment by colinschoen** [comment]
@Alex146 We will be updating the packages on the download server soon to match the tag here on GitHub. There was an issue with the build tool. Either download from the release here or hang tight until we update those. 

I'll provide another update in an hour.

**Comment by colinschoen** [comment]
Fixed. Please redownload the package. https://download.simplemachines.org
