### ISSUE TITLE
Issue with "Quote selected text"

### ISSUE THREAD

**Issue by BloberSh** [SimpleMachines/SMF#4084]
I open this issue because i didn't found any on this.
Php version 7.0
SMF beta 3

When you go to a topic, you select a text on a post, you decide that this text is not what you want, you select an other part of the text on the same post. This time it's the right selection. Then you click on the "Quote selected text" and the problem come up. It will insert into the quick reply the first and the second selected texts and not only the last.

Hope it's understandable

**Comment by colinschoen** [comment]
Good find. In some ways this is actually kind of handy to be able to select multiple nonadjacent portions of text, but the UI doesn't make this intuitive so this probably is a bug. :+1:
