### ISSUE TITLE
Installer - Undefined index & func name must be a string

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4085]
I can't get the installer to complete at the moment.  White screen, & the message below:
```
Notice: Undefined index: htmlspecialchars in yadayada\VAN21\Sources\Errors.php on line 69

Fatal error: Function name must be a string in yadayada\VAN21\Sources\Errors.php on line 69

```
Brand new code sync'd from Github.  Vanilla install.

**Comment by sbulen** [comment]
Is this related to: Could not retrieve the file #4063 ?

My test environment does not yet support ssl...   So is this unique to my test environment?

**Comment by jdarwood007** [comment]
This usually means $smcFunc is not loaded up.  An error is occurring very early on in the process and instead of causing a fatal error, its trying to handle things gracefully.  Its supposed to do a fatal error whitepage if $smcFunc isn't ready yet.

**Comment by sbulen** [comment]
OK, digging deeper...  Thanks.   
Yes it's at the very end of the install, & trying to report an error, but having an issue trying to do so.

**Comment by sbulen** [comment]
Yes, it's related to the fact that my test environment can't run ssl.  The error message it is attempting to report is the same as before: 
'Could not retrieve the file https://www.simplemachines.org/smf/current-version.js?version=2.1+Beta+3.'

My initial thought here is to make it so the installer can report the error & move on.   As near as I can tell, the install was otherwise perfectly successful.

**Comment by jdarwood007** [comment]
Well it will continue to fail then with anyone not having SSL.

We should present a warning to the installer and acp that the news feed and downloading of patches will fail due to ssl not being installed.

**Comment by sbulen** [comment]
I was able to resolve my test environment issue.   Very simple - literally uncommenting 2 config lines.

I guess the question here is whether we should have the suggested check & warning  for the https stream in the installer & upgrader.  

If we think it would be rare enough, we can close this, as we closed the prior item, #4063 .  

My recommendation is to close it, and if we start to see a pattern, address it at that time.  It's just hard for me to guess how many folks will also have this config in their test environments...

**Comment by jdarwood007** [comment]
Problem I see is if there is a pattern, we would most likely not see it until 2.1 is gold and it starts getting mass deployments.  At at time, it is more difficult for users to fix, as it requires them to manually upgrade versus a package manager download and install.  They would have to know their install is broken and not receiving notices about updates.

**Comment by sbulen** [comment]
Yep.  Same symptoms reported here:
https://www.simplemachines.org/community/index.php?topic=554352.0

I'd suggest two changes:
1)  fix the error reporting by enabling htmlspecialchars
2)  check for https support

**Comment by sbulen** [comment]
Yep.  Same symptoms reported here:
https://www.simplemachines.org/community/index.php?topic=554352.0

I'd now suggest two changes:
1)  fix the error reporting by enabling htmlspecialchars
2)  check for https support

**Comment by jdarwood007** [comment]
What 2 config lines did you change to fix this?

**Comment by sbulen** [comment]
When I searched the issue, about half the results told me to uncomment an apache setting, & about half told me to uncomment a php setting.   

Very unscientifically, I uncommented 'em both:

	in httpd.conf:
	    LoadModule ssl_module modules/mod_ssl.so
	in php.ini:
	    extension=php_openssl.dll

And now https shows up in phpinfo() under "Registered PHP Streams".

**Comment by sbulen** [comment]
htmlspecialchars is one of several functions added to smcfunc in Load.php in reloadSettings().  reloadSettings() is not invoked during the install.  That's why an error during install chokes the way it does.  (The error logging invokes htmlspecialchars & it ain't there...) 

So we could either move that set of smcfunc declarations from reloadSettings() to somewhere else (which feels a little risky to me...) or simply clone them in install.php (which is a bit of a kludge, but a tempting kludge...).

I'd move those functions somewhere else, but I'm not sure where the most appropriate place is...  Input welcome.

**Comment by sbulen** [comment]
For the record...  

The apache setting above (LoadModule ssl_module modules/mod_ssl.so) was NOT required to enable https strings in php.  

The php.ini setting, (extension=php_openssl.dll), was the sole setting that must be uncommented to enable the https stream in php in my environment.

**Comment by jdarwood007** [comment]
Thanks, I was meaning to get around to doing that once I could test for it properly.
