### ISSUE TITLE
Software copyright/licensing (PR 395)

### ISSUE THREAD

**Issue by norv** [SimpleMachines/SMF#409]
PR #395  is wrong at several levels:
- I have set the development policy on copyright/licensing on these repositories, to ask contributors to offer their work under the license(s) of the project, and license alone. They hold copyright over their work, and offer to everyone the license(s) of the project(s).
- I have amended the copyright notices in the code, to acknowledge copyright of their copyright holders: authors. Reference: https://github.com/SimpleMachines/SMF2.1/pull/213.
  The software is copyrighted by its authors.
- I have made this correction under BSD 3-clause license for BSD 3-clause licensed code. Which means any licensee has to respect it.
  
  > Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. Reference: http://opensource.org/licenses/BSD-3-Clause
- SM and its BoD is a licensee. It has no right to [remove](https://github.com/SimpleMachines/SMF2.1/pull/239) or [alter](https://github.com/SimpleMachines/SMF2.1/pull/395) the copyright notices in the software.

SM BoD should respect it. SM or SM BoD are not above it. SM does not have rights to disregard it.
The moment we had set this policy in place, we had dropped entirely the former policy, CLAs, and we were to delete former CLAs entirely. I have clarified that. The SM BoD has specifically and publicly admitted that.

**Recent events**
SM BoD has made "an announcement" in the sm.org boards, according to which they claim they had a secret "understanding" with developers and code contributors over granting them "copyright over the collective work". Something not covered in the DCO-or-nothing-else-than-license policy.
An "understanding" so secret that not even developers/contributors knew about it. :P Not even myself, who set the policy in the first place. That is ridiculous.
No.
The DCO sign-off policy did not "hide" any secret understandings. It means exactly what it says:

> By making a contribution to this project, I certify that:
> (a) The contribution was created in whole or in part by me and I
>           have the right to **submit it under the open source license**
>           indicated in the file; or
> (b) The contribution is _based upon previous work_ that, to the best
>           of my knowledge, is **covered under an appropriate open source
>           license and I have the right under that license to submit that
>           work** with modifications, whether created in whole **or in part**
>           by me, **under the same open source license** (unless I am
>           permitted to submit under a different license), as indicated
>           in the file; or
> (c) The contribution was _provided directly to me **by some other
>           person who certified (a), (b) or (c)**_ and I have not modified
>           it.

Reading in English: developers/contributors have submitted original works of authorship under the open license of the project. They might belong to the submitter, but they might also belong to someone else. The only thing the licensor offers under this agreement, is the open license. Authors - first party or second party authors - offer everyone the rights to copy, share, modify and reshare, under the conditions of the license, and license alone.
There is no "copyright over the collective work", there is no secret "understanding" over some hidden "copyright".

I have set in place this policy. I have asked from everyone to make sure the work they add or their modifications to it, is under the open license of the project. No more.
I did not ask from anyone - anything more than to offer the rights stated in the BSD 3-clause license to _everyone_, equally.
I did not ask from anyone, anything more than to make sure that the work added (from 3rd party repositories/projects, for example), is under the suitable license.
I have made sure that the licensing is as correct as possible, and fixed it everytime we were aware of any tweak necessary.

I have set this policy in place intently: so that the project will be free. So that people are free to build it and make of it whatever they want, starting up with the same rights. And let their work make the difference.
Free from any 'corporation' that'd claim to have any advantage - any advantage at all - over their work, under SMF name.

SM 'Corporation' BoD: you should correct your PR, to respect the license that developers/contributors have granted to you.

**Comment by Oldiesmann** [comment]
Whether you like it or not, this change was made after consulting with the Software Freedom Law Center, based on their recommendations. It is not up for discussion at this point.

**Comment by norv** [comment]
> this change was made after consulting with the Software Freedom Law Center, based on their recommendations.

So I'm told. In the name of developers and community contributors of this software. And, in particular in my name, who set the development policy on copyright/licensing in the first place.

Hiding behind SFLC does not cut it. Might seem to work as long as the community is kept unaware and you keep repeating at-nauseam mythical "legal legal reasons", but not with me. I set the DCO-or-nothing requirements on SMF repositories for a reason.

On a side note, you'll excuse me if I find it interesting, that I am even these days explaining it to SM BoD, you and Illori, on the uselessness of double sign-off. Just a small irony.

> Whether you like it or not

I am not indifferent, very true, if that is what you mean. It's never personal, but not indifferent.

I am not indifferent to a corporation whose BoD is capable to state that to them, there are heavier consequences if _their corporation_ dies than if SMF dies.
I am not indifferent to a corporation whose BoD "must kill the project" if they don't get their way. That they kill the project if developers don't accept what they want, over their own work.

No one has the right to ask me to, and this corporation sure as hell not.

So. The corporation refuses to discuss? Not that'd be much more to add to the above indeed.

You - the SM NPO corporation - are saying you had "understandings" with me (and thereby developers/contributors), but you refuse to discuss with the community what rights we have granted you over our work?
You do not answer to this community for your actions?
You think your corporation is not accountable to us?

These are not rhetorical questions.

**Comment by LiroyvH** [comment]
Hi Norv,

We are perfectly in compliance with all and any applicable license(s), agreements, etc. with the selected copyright headers.
We are not hiding behind anyone, we are simply stating facts. Facts you seem to knowingly and/or willingly refuse to understand and/or accept.
Our lawyers know the best. That you do not agree with them is your right, but that doesn't mean they are wrong, no matter how much you personally WANT them to be wrong. Your opinion is not a fact.

I would appreciate it if you keep your dislike for the SM organization and/or SMF project to yourself and stop polluting all PR's that are being made with baseless opinions and attempt to dictate what can and cannot be done.

Thanks in advance and enjoy the rest of your day.
