### ISSUE TITLE
Undefined variable: $dif

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#4091]
In Class-Graphics.php around line 304 ([this snippet](https://gist.github.com/Yoshi2889/ac360ca0a6fd0caef82c2daf3fe57d24)), variable $dif is not defined. I'm not sure what this function is supposed to do.

**Comment by jdarwood007** [comment]
While $dif is undefined, its never evaluated here because $idx is -1 during the first loop.  Its defined after that.

**Comment by NanoSector** [comment]
So should it be set to 0 on first run? I know it doesn't matter but hacks like these don't make the codebase easier to comprehend.

**Comment by jdarwood007** [comment]
I don't think it honestly maters as long as $idx is -1 what it does.  From what I can read in the code, its pulling the RGB out and determine if the previous color is greater, then returns the idx which I assume is used for later on graphic processing.  I think, I haven't seen it in action or messed around with the code to determine that.
