### ISSUE TITLE
critical error

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4098]
why is this error a critical error in the error log? i dont think this requires the admin attention to do something. it does not even tell us what account was being attempted to log into.
Sorry, but you've reached your login attempts threshold. Please wait 30 seconds and try again later.

**Comment by sbulen** [comment]
I'm pretty sure it's this way in 2.0 as well.  I always thought it was to raise awareness for spammers/hackers.  But there are LOTS of these, making the term 'critical' less effective...

**Comment by colinschoen** [comment]
Agreed, I think we can reduce the severity based on how commonly this occurs.

**Comment by colinschoen** [comment]
I'll take this.

**Comment by jdarwood007** [comment]
Perhaps we could separate this into a "login" category.  Dump the failed logins into it as well.  These occur so commonly I think it makes sense to put them into a category that is easier for admins to clean out.

**Comment by Oldiesmann** [comment]
That's a good idea @jdarwood007. It'll make it much easier to filter those out from other issues.

**Comment by colinschoen** [comment]
To be clear we are talking about 

`Administration login attempt!` 

Correct?

**Comment by illori** [comment]
no the error message is "Sorry, but you've reached your login attempts threshold. Please wait 30 seconds and try again later."

**Comment by colinschoen** [comment]
Got it, perhaps we could move Administration log in attempt to login category as well.

**Comment by illori** [comment]
you could also move "Your email address needs to be validated before you can login." type of error into that category as well, this is under general currently.

**Comment by illori** [comment]
Sorry, you are out of login chances. Please come back and try again later.
can that message be moved out of critical as well?
