### ISSUE TITLE
Installer & Upgrader - array_keys() expects parameter 1 to be array error message

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4099]
Whenever there's a bunch of changes, I attempt a fresh install & upgrade.   

Just tried a fresh install, all brand new code from git, and got the following message.  Will dig a little deeper, but just getting this out there for folks to be aware of...

This floods the screen during the database population step as well as the admin account creation step:

Warning
: array_keys() expects parameter 1 to be array, null given in
C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\VAN21\Sources\Subs-Db-mysql.php
on line
175

They also appear in the error log as you navigate around the application.

**Comment by Sesquipedalian** [comment]
Looks like `smf_db_replacement__callback()` is being called while `$user_info` is unset.

**Comment by sbulen** [comment]
This is impacting the upgrader as well.

**Comment by Sesquipedalian** [comment]
I think this is due to changes introduced in #4065. Can you take a look at this, @Underdog-01?

**Comment by Sesquipedalian** [comment]
Actually, this looks pretty simple to solve. Try this: #4100

**Comment by sbulen** [comment]
Confirmed works on installer.  Trying upgrader next, to be safe.

**Comment by sbulen** [comment]
Upgrader is operating properly now as well. 

Navigating around the apps (new install & fresh upgrade) no longer creates errors as well.
