### ISSUE TITLE
Installer - won't run at all

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4103]
It won't even fully paint the initial page right now...  

Is this just me?   I've been trying to work on #4085.  I always start with a fresh git load...   

I'd appreciate it if somebody else gave it a shot.  

![image](https://user-images.githubusercontent.com/23568484/26861334-fb503922-4af7-11e7-8d63-f66e08a34fb9.png)

**Comment by jdarwood007** [comment]
https://github.com/SimpleMachines/SMF2.1/commit/8b10e9e0fb8f8d3a73d19bbaa4ffaa2bc62caf61#diff-84252cd3efeb19d2101b84d40680a3d0L258

That change there broke it.  Specifically removing the global is preventing $txt from working properly.

**Comment by sbulen** [comment]
Yep, that's  part of it...   Now I'm getting other issues:


Notice
: Undefined variable: db_connection in
C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\VAN21\install.php(970) : eval()'d code
on line
1


Warning
: mysqli_get_server_info() expects parameter 1 to be mysqli, null given in
C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\VAN21\install.php(970) : eval()'d code
on line
1

**Comment by sbulen** [comment]
Looks similar, let me see if I can plow through this...

**Comment by sbulen** [comment]
A couple more were removed that were needed.  PR tested & submitted:   PR #4104

**Comment by sbulen** [comment]
Thanks, @jdarwood007
