### ISSUE TITLE
PHP 7 constructors change

### ISSUE THREAD

**Issue by BitFros7y** [SimpleMachines/SMF#4107]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP

You guys should have these in mind for both 2.1 and future updates of 2.0 until 2.1 gets out.

**Comment by albertlast** [comment]
do you mention any specific class?

**Comment by BitFros7y** [comment]
No, no specific class, i just installed 2.0.14 and it had warning about deprecation (it was caused by FTP) so i just wanted to notify you guys since 2.0 and 2.1 share base code

**Comment by colinschoen** [comment]
Thanks for the note. Please log 2.0 issues at simplemachines.org 

http://www.simplemachines.org/community/index.php?board=137.0
