### ISSUE TITLE
mbstring.func_overload depracted for php 7.2

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4125]
So this feature is depracted with php 7.2 https://wiki.php.net/rfc/deprecations_php_7_2
so it's use in safe_unserialize 
https://github.com/SimpleMachines/SMF2.1/blob/536d4fef39f4abd242ce18bffb801d0e666c498b/Sources/Subs.php#L5397
and safe_serialize
https://github.com/SimpleMachines/SMF2.1/blob/536d4fef39f4abd242ce18bffb801d0e666c498b/Sources/Subs.php#L5220
 smf only realy use safe_unserialize
orginal this solution came from piwik: https://github.com/piwik/piwik/commit/ee6efcb8701c3378481c71245651e71389001084

in the most cases it's look like it's used for legacy stuff...
so two options:
- get the thing work
- drop the code

i hope someone is able to solve this.

**Comment by replikacep** [comment]
Do not upgrade the Php version all the time

**Comment by albertlast** [comment]
Thanks for posting nonsense

**Comment by Sesquipedalian** [comment]
It looks like all we are doing is temporarily disabling mbstring.func_overload if it was enabled. If it isn't enabled in the ini file, nothing happens. So I don't think we need to change anything in our code.

**Comment by jdarwood007** [comment]
Usage of serialize should not be found in 2.1.  That should only be there for upgrades and mod compatibility.

**Comment by albertlast** [comment]
@jdarwood007 look at this https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Calendar.php#L671
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Menu.php#L125
here you see an active use of this in non legacy code

**Comment by jdarwood007** [comment]
Both of those are easter eggs and could go or be converted.
