### ISSUE TITLE
smf 2.1 Why is it working in beta 2 but not in beta 3?

### ISSUE THREAD

**Issue by replikacep** [SimpleMachines/SMF#4126]
Problem sitemap or beta 3 demi running in beta 2 sitemap

Normally running beta 2

Kod: [Seç]

XML parsing error: incompatible format imi. expected: </link>.
Konum: http://21.replikacep.com/index.php?action=sitemap;xml
Satır: 46, Sütun: 3:</head>
--^

http://21.replikacep.com/index.php?action=sitemap

http://21.replikacep.com/index.php?action=sitemap;xml

not working   

Axis is running in beta 2

Beta 3 does not work   

Why does not work

smf 2.1 Why is it working in beta 2 but not in beta 3?
If the problem is not mod, is it beta 3?

**Comment by replikacep** [comment]
https://www.simplemachines.org/community/index.php?topic=170813.msg3931142#msg3931142

**Comment by XinYenFon** [comment]
A mod related issues are no concern of SMF. Contact mod author to update the modification.

This issue can be closed any time by managers.

**Comment by replikacep** [comment]
Well working on beta 2

**Comment by Sesquipedalian** [comment]
You should not use beta versions of SMF on a live website. Part of the reason for that is that many existing mods will break as SMF's code changes over time. That is what has happened to the sitemap mod you have been using. You will need to wait until the author of the mod updates it to work with SMF 2.1.
