### ISSUE TITLE
Should fix_serialized_columns() be removed?

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#4127]
The `fix_serialized_columns()` function in Subs-Charset.php "Fixes corrupted serialized strings after a character set conversion" in the `id_action` and `extra` fields of the the log_actions table. But the strings in those fields are JSON encoded now, not serialized. So as far as I can see, the function does nothing now and can be removed.

**Comment by XinYenFon** [comment]
Go for it ?

**Comment by Sesquipedalian** [comment]
Heh. I forgot about this one. Yeah, I think I will.
