### ISSUE TITLE
"New message" doesn't appear in "Message" menu

### ISSUE THREAD

**Issue by BloberSh** [SimpleMachines/SMF#4141]
As a regular member, the "New message" and "Show draft" items don't appear in the "Message" menu. You can only create a new pm or see draft buy using the links in the window from "My Messages" on the top bar.

Permitions are set rights. 
![image](https://user-images.githubusercontent.com/6509009/27327245-444fac8c-55ae-11e7-9ae4-c6d6d282193f.png)
Regular user permitions

Menu as admin : 
![image](https://user-images.githubusercontent.com/6509009/27327354-adf92cda-55ae-11e7-8fb2-063efb9c77d2.png)

Menu as regular member : 
![image](https://user-images.githubusercontent.com/6509009/27327407-cb74ae10-55ae-11e7-9d4c-e9216c5e61bf.png)

The item appears for administrator.

If i change these permissions to false, items appear. It should be the opposite : 
![image](https://user-images.githubusercontent.com/6509009/27327611-62d5413e-55af-11e7-9601-d01e04632811.png)

Can someone confirm this?

**Comment by sbulen** [comment]
Confirmed on my end.   Nice writeup, btw.  Helpful.
