### ISSUE TITLE
PHP 7.1 Search Method [] operator not supported for strings 

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#4145]
Affects SMF 2.1 Beta 3 and SMF 2.0.x
After changing the Search Method to Fulltext the error '[] operator not supported for strings' is thrown whenever the 'Search Methods' menu is selected.

The fix is as follows:
In ./Sources/ManageSearch.php
Find:
Code: [Select]

        $context['fulltext_index'] = '';
        if ($request !== false || $smcFunc['db_num_rows']($request) != 0)

Replace With:
Code: [Select]

        $context['fulltext_index'] = array();
        if ($request !== false || $smcFunc['db_num_rows']($request) != 0)

I've confirmed this issue also affects SMF 2.1 Beta 3 - error log info is as follows:
[21-Jun-2017 02:23:37 UTC] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /home/abcdefg/public_html/forum_21B3/Sources/ManageSearch.php:826
Stack trace:
#0 /home/abcdefg/public_html/forum_21B3/Sources/ManageSearch.php(219): detectFulltextIndex()
#1 /home/abcdefg/public_html/forum_21B3/Sources/Subs.php(4584): EditSearchMethod()
#2 /home/abcdefg/public_html/forum_21B3/Sources/ManageSearch.php(77): call_helper('EditSearchMetho...')
#3 /home/abcdefg/public_html/forum_21B3/Sources/Admin.php(495): ManageSearch()
#4 /home/abcdefg/public_html/forum_21B3/index.php(152): AdminMain()
#5 {main}
  thrown in /home/abcdefg/public_html/forum_21B3/Sources/ManageSearch.php on line 826

https://www.simplemachines.org/community/index.php?topic=554723.

**Comment by frandominguezl** [comment]
The fix proposed works fine. Tested in PHP 7.1.4

**Comment by jdarwood007** [comment]
There is multiple instances of this variable, but most are an array, once instance sets it to a string value.

```
./Sources/ManageSearch.php:263:		$context['fulltext_index'] = 'body';
./Sources/ManageSearch.php:265:	elseif (!empty($_REQUEST['sa']) && $_REQUEST['sa'] == 'removefulltext' && !empty($context['fulltext_index']))
./Sources/ManageSearch.php:273:			DROP INDEX ', $context['fulltext_index']),
./Sources/ManageSearch.php:279:		$context['fulltext_index'] = '';
./Sources/ManageSearch.php:472:	$context['double_index'] = !empty($context['fulltext_index']) && $context['custom_index'];
./Sources/ManageSearch.php:811:			$context['fulltext_index'][] = $row['indexname'];
./Sources/ManageSearch.php:821:		$context['fulltext_index'] = '';
./Sources/ManageSearch.php:826:				$context['fulltext_index'][] = $row['Key_name'];
./Sources/ManageSearch.php:829:			if (is_array($context['fulltext_index']))
./Sources/ManageSearch.php:830:				$context['fulltext_index'] = array_unique($context['fulltext_index']);
./Themes/default/ManageSearch.template.php:143:							<input type="radio" name="search_index" value="fulltext"', !empty($modSettings['search_index']) && $modSettings['search_index'] == 'fulltext' ? ' checked' : '', empty($context['fulltext_index']) ? ' onclick="alert(\'' . $txt['search_method_fulltext_warning'] . '\'); selectRadioByName(this.form.search_index, \'fulltext\');"' : '', ' class="input_radio">
./Themes/default/ManageSearch.template.php:149:	if (empty($context['fulltext_index']) && empty($context['cannot_create_fulltext']))
./Themes/default/ManageSearch.template.php:152:	elseif (empty($context['fulltext_index']) && !empty($context['cannot_create_fulltext']))
```

**Comment by diegolyanky** [comment]
**This fix worked fine.
Tested on PHP 7.1.20 and SMF 2.0.15**
