### ISSUE TITLE
Installer/upgrader:  Should we check for mbstring support?

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4148]
This post on the support site caught my eye:
https://www.simplemachines.org/community/index.php?topic=554740.0

How rare would this be?  I'm leaning towards putting a check for mbstring support in both the installer & upgrader.  Let me know if this makes sense.

**Comment by sbulen** [comment]
I just recalled that a few checks were called for in #1869:  GD2, Imagemagick, hash, json, mbstring.  

Are these potential checks appropriate?

**Comment by Oldiesmann** [comment]
I don't think we need a check for GD at all. That's a default feature of PHP and the only way it won't be there is if you specifically compile PHP without it, which is highly unusual.

ImageMagick isn't a requirement for SMF - we've got checks for the two extensions (imagick and magickwand) where appropriate, but SMF will work fine without it.

I'm not sure about the others.

**Comment by sbulen** [comment]
Looks like hash and json are compiled into php by default since php 5.1 & 5.2.

The only item here that is still not enabled by default is mbstring.

I'll add a check for mbstring, and both of these issues can be closed out.

**Comment by sbulen** [comment]
Addressed by PR #4155
