### ISSUE TITLE
Undefined offset: 2 in QueryString.php line 194

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4149]
Fresh load from github.  I get this navigating around a newly upgraded site.  

Notice
: Undefined offset: 2 in
\Sources\QueryString.php
on line
194

Oddly, I don't get a similar message on a newly INSTALLED site.

**Comment by albertlast** [comment]
In my eyes is there no error in this line,
can you give me the url which you call for get this error?
specialy the stuff after ?topic= i cared most.

**Comment by sbulen** [comment]
I'm testing on a local server.  URL when there is an issue looks like:
http://localhost/van2021/index.php?topic=7.0

**Comment by albertlast** [comment]
php version?
And another test case,
please go in a topic which got more than one page,
go on page one then from ther switch to page two.

The topic should look a litte bit different and i care if the notice raised up again.

**Comment by sbulen** [comment]
Php version 5.6.
I'd have to upgrade a larger test db.  I'll do more testing tomorrow. 
If it were looking for a 3rd value of an exploded 7.0 that would fail, right?   There isnt an index 2...

**Comment by albertlast** [comment]
I didn't Notice this behavior in PHP 7,
So i had to change this code line


________________________________
Von: sbulen <notifications@github.com>
Gesendet: 22.06.2017 6:59 vorm.
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] Undefined offset: 2 in QueryString.php line 194 (#4149)


Php version 5.6.
I'd have to upgrade a larger test db. I'll do more testing tomorrow.
If it were looking for a 3rd value of an exploded 7.0 that would fail, right? There isnt an index 2...

**Comment by sbulen** [comment]
Do you still need me to test further?

**Comment by albertlast** [comment]
Pr is in place feel free to test this with you setup.
