### ISSUE TITLE
Installed forum vs Upgraded forum - slightly different error handling

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4152]
Discovered when testing this PR: #4151  
And logging this issue: Undefined offset: 2 in QueryString.php line 194 #4149 

Basically, this error/warning was reported in an awkward fashion on an upgraded forum (text dumped at top of screen), but was ignored in a newly installed forum.   

These two forums are running in the exact same environment.  Somehow, they are behaving a bit differently - something is being set differently.  

Screenshot of the error as reported in the upgraded environment:
![image](https://user-images.githubusercontent.com/23568484/27510026-c3219df6-58bd-11e7-91bf-97134fe2ebd7.png)

**Comment by sbulen** [comment]
The php error reporting level as reported by error_reporting() is identical in both environments.  

Anything else I should be looking at?

**Comment by jdarwood007** [comment]
What urls are you seeing?

**Comment by sbulen** [comment]
A sample URL: 
`http://localhost/van21/index.php?topic=4.0`

**Comment by sbulen** [comment]
One more clue...   I regularly test with THREE forums:
 - a vanilla 2.1 install - OK
 - a vanilla 2.0 install (now 2.0.14) upgraded to 2.1    *** error is displayed
 - my forum upgraded to 2.1 - OK

This error message only shows up on the vanilla 2.0 install upgraded to 2.1.  It doesn't show up in the other 2 environments.

**Comment by sbulen** [comment]
I just rebuilt my vanilla 2.0 & now I cannot reproduce this.  

I am going to assume that this was an issue with my test environment....
