### ISSUE TITLE
Dont format HTML outside of templates.

### ISSUE THREAD

**Issue by BitFros7y** [SimpleMachines/SMF#4158]
I noticed that for some reasons there is some HTML formatting done inside sources files.
For example, administration/moderation link has prepended <span class="amt">%d</span> after button title. While that makes it easier for some users to make templates, it may limit (well at least annoy) others. I think that number of notifications should be as separate variable in array, and that there should not be any html in those variables at all. Also as far as i remember there is some similar things used in board and messages indexes.

**Comment by Oldiesmann** [comment]
Where specifically is the code you're talking about? It's easier to fix things or at least look into possible issues if we have a general idea of where to look.

**Comment by BitFros7y** [comment]
Well specific place i mentioned above is [these](https://github.com/SimpleMachines/SMF2.1/blob/8a5be3189b8ccbe0f2b9c6a0c7742128069704e9/Sources/Subs.php#L4295)

But what i mean is that files in Subs folder should not have any HTML at all. Everything should be in templates to give designers full power.

**Comment by albertlast** [comment]
i'm voting to close this issue,
reason:
it's a software architect design complain,
for this is the board to discuss not the issue part in github.

**Comment by Oldiesmann** [comment]
Moving that specific HTML code to templates wouldn't make much difference in flexibility because span by itself does absolutely nothing - the "amt" class can be customized by the theme designers however they want.

**Comment by BitFros7y** [comment]
Its not the span element itself that's actual "problem". If we dont want to show it we can just add display: none, but that is actually a workaround. Also if we wanted to show that same notifications number without text elsewhere (in modal or popup perhaps), then we would have to cut it out using PHP inside templates. Its not some issue that doesnt have some easy workaround, but the fact we need a workaround for such thing shows flaws in software design. If you still feel like its not worth doing feel free to close issue.

**Comment by asmith20002** [comment]
I'd like to second this "issue".

The pending number shouldn't be concatenated to the button title, but it should be available as a separate variable.
This allows mods to get this pending number and add their own pending number to it. Then the theme gets the final summed up pending number.
