### ISSUE TITLE
json_(de|en)code in $smcFunc

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#4173]
Was there a reason we didn't do this?

Since the json functions are heavily used in our code, it would make sense we move them into $smcFunc so if in the future, like the serialized issue, we have to fix something we can just override it in $smcFunc and be done?

I forsee basically adding 2 items to $smcFunc
$smcFunc['json_encode'] = 'json_encode';
$smcFunc['json_decode'] = 'smf_json_decode';

The code would look a bit cleaner and again, if we need to clean something up later it would be easier.

We put mostly db stuff and utf-8 handling in $smcFunc right now, but that isn't to say we can't do additional stuff in there like this heavily used functions.

**Comment by Sesquipedalian** [comment]
That suggestion makes sense to me.

**Comment by sbulen** [comment]
FYI - there's a bunch of such functions out there in Load.php.  smcFunc isn't just DB stuff...  

I'm not sure everyone knows they're there.   Even string functions:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Load.php#L130

Things get added to smcFunc in a few different places...   Hard to tell what the whole set is.

**Comment by jdarwood007** [comment]
Most of stuff is added in Load.php and then the database abstraction stuff adds as needed for its different pieces.

I will work on getting things converted over.  Lots of places json is used and I need to make sure that $smcFunc is global before using it in a function.
