### ISSUE TITLE
Beta 3 Installer: Step 2 Writable Check

### ISSUE THREAD

**Issue by nathan93** [SimpleMachines/SMF#4175]
After uploading and unzipping the latest release provided on the downloads page of the SMF website, I am stuck on step two of the installation process, the writables check. When using the FTP connection method, I am given the following error:

`
550 Could not change perms on Settings_bak.php: No such file or directory -> Settings_bak.php 
550 Could not change perms on db_last_error.php: No such file or directory -> db_last_error.php
`

I looked through the files on my webserver and I couldn't find the two files that need to be changed to writable. Is this a known issue or is there a known solution at this time?

**Comment by sbulen** [comment]
Yes, folks have reported this before.  They are usually told to create the two files, empty, & set the permissions.   

Which seems odd to me...   

Could you detail the EXACT steps you followed?   

In addition, I have several other questions:
Had you used this same location/folder before for another version of SMF?
Was the folder completely empty before you uploaded the files?
Which files did you copy from the 'other' folder to the main folder?
Did you copy the 'blank' settings.php also?

**Comment by nathan93** [comment]
My exact steps:
 1. Downloaded the .zip file from the SMF downloads page at simplemachines.org
 2. Uploaded .zip file to my webserver
 3. Extracted file contents
 4. Navigated to the installer page in my browser to find this error on step 2

To address your questions/concerns;
 1. No I have not use the directory for another version of SMF
 2. Yes, the directory was completely empty
 3/4. I do not know what you are referring to? I did not copy any files from anywhere, I simply extracted the zip file on my server into the empty, new directory I intended to use it in

**Comment by sbulen** [comment]
Thanks, that makes sense.  You used the zipped "install" version downloaded from SMF.

**Comment by nathan93** [comment]
Where would I create the blank files to satisfy the installer?

**Comment by sbulen** [comment]
Same folder where your settings.php file is.

**Comment by sbulen** [comment]
I don't understand why this doesn't happen EVERY SINGLE TIME on greenfield Unix installations...  

Those 2 files don't exist, so is_writable() will fail.  

Talking out loud here...

**Comment by sbulen** [comment]
You know, I think it does...   How silly is that...

**Comment by jdarwood007** [comment]
It will depend on the web servers permissions to the folder.  If it can write to the folder, it can create the file itself.
