### ISSUE TITLE
Make SMF compatible with PHP 7

### ISSUE THREAD

**Issue by ConstantinopleGR** [SimpleMachines/SMF#4181]
The issue is at Install.php at line 1560

Change:
class ftp_connection

To:
class __construct

Works perfectly with PHP7
On mysql

Package: smf_2-0-14_install.zip

Tested and no issues so far.

Greetings from Greece. Keep up the good work guys, beautiful SMF

**Comment by frandominguezl** [comment]
What is the issue you're getting? Also, this is not the place to report 2.0.x bugs

**Comment by illori** [comment]
since this is a bug report for SMF 2.0, i am closing it. please report bugs for SMF 2.0 on the forum not here.
