### ISSUE TITLE
comma setting by ::after looks wrong

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4183]
First I notice that this comma looks wrong:
![grafik](https://user-images.githubusercontent.com/1782906/27983434-5021e31a-63bc-11e7-88aa-31e19e423566.png)
I would expect that the comma is after new,
when a new element is there

Than i looked in my bigger test area: 
![grafik](https://user-images.githubusercontent.com/1782906/27983440-77c731a4-63bc-11e7-8c83-19311f5ede3a.png)
More or less the same behavior .

Then when you mark a board as read is look strange:
![grafik](https://user-images.githubusercontent.com/1782906/27983448-a9cae312-63bc-11e7-87b6-2be7e6be2960.png)

All this is done by the
`.children a::after {
    content: ", ";
}
`
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/css/index.css#L2939

Is this behavior realy wanted?

**Comment by XinYenFon** [comment]
I can't reproduce this on my localhost.

Tested with: EDGE/IE/Firefox/Chrome.

**Comment by albertlast** [comment]
when there is no "new" included the issue didn't raised up:
![grafik](https://user-images.githubusercontent.com/1782906/27984229-36a8bbf2-63d0-11e7-9ba2-49c5c863fca5.png)

**Comment by frandominguezl** [comment]
I can confirm the issue. Maybe makes more sense to place "New" before the board's name?
