### ISSUE TITLE
Add Index to sessions table column last_update

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#4187]
Was analyzing a larger SMF forum and noticed they were using the database driven sessions and saw that the query 
"DELETE FROM {db_prefix}sessions
		WHERE last_update < {int:last_update}',"

Would benefit in having an index on the last_update column This forum in question had about 60k entries in the sessions table were recent and this index gave a nice speed bump up.

**Comment by albertlast** [comment]
how larg was this board,
that you got 60k entries in the table?

Reason why i ask is that the max 1440 sec,
this mean you need more than 60k different user in 24 minutes or less.

**Comment by VBGAMER45** [comment]
Stats

Total Members:
    4343
Total Posts:
    446032

274 Guests, 86 Users
Users active in past 120 minutes:
Most Online Ever: 827 (August 22, 2016, 11:20:50 AM)


Yeah it is odd I didn't see any older entries at the time older than one day.

**Comment by albertlast** [comment]
well i notice this query exists two times,
Session.php and ScheduledTask.

In Session.php is 24min and Scheduled is 24h,
what is the reason for the different values?
And for me looks like that the session part is not called.
@Oldiesmann are you able to comment about this?

**Comment by VBGAMER45** [comment]
I see what the user did "Seconds before an unused session timeout "

They set databaseSession_lifetime  to 100000

**Comment by albertlast** [comment]
The Session.php got a check,
That not allow values higher that 24min,
Maybe this doesn't work.


________________________________
Von: VBGAMER45 <notifications@github.com>
Gesendet: 09.07.2017 17:35
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] Add Index to sessions table column last_update (#4187)


I see what the user did "Seconds before an unused session timeout "

They set databaseSession_lifetime to 100000

**Comment by Oldiesmann** [comment]
I'm not sure there's much we can do in this situation - if people want to use stupid values for things like unused session timeout, they deserve any issues it brings up...

**Comment by VBGAMER45** [comment]
Does it cost anything to add the index? Meaning if there  is a busy site and table grows to a couple thousand rows it might help a little bit.

**Comment by albertlast** [comment]
on database side you get nothing for free,
when you add a index you slow down the performance of insert,update and delete statements,
because the index needs to be updated every time.

The session table is highly updated and inserted...

@Oldiesmann here we try to ingor to high values: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Session.php#L220

**Comment by albertlast** [comment]
Is duplicate from #1305
