### ISSUE TITLE
Upgrader - Undefined index: json_decode

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4190]
Ran into this running the upgrader just now

![image](https://user-images.githubusercontent.com/23568484/28004050-c690558c-64f6-11e7-928f-c28d3246c0ac.png)

**Comment by sbulen** [comment]
This occurs after the serialize json step, once you press the continue button.

The only thing not yet done is presenting the page to delete the upgrade files.

**Comment by jdarwood007** [comment]
I think my PR #4192 should resolve this.  Yet another place we are using SMF functions without having properly fully loaded SMF.
