### ISSUE TITLE
Thumbnails are for the wrong picture...

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4194]
Testing using github 2.1b4 as of...  now...

Upload a bunch of pix.  The thumbnails are all for the wrong pics.   Seems to all be off by one.  Haven't researched any deeper at the moment.   

These are true attachments.  (Image proxy is enabled, but shouldn't be in use.)

**Comment by sbulen** [comment]
Brand new, vanilla install...   Although the FIRST one I tried, the thumbnail was from an earlier testing session.  

It corrected itself after a while.  

One example:
![image](https://user-images.githubusercontent.com/23568484/28038362-7b4202b0-6573-11e7-857e-945aa377be64.png)
![image](https://user-images.githubusercontent.com/23568484/28038394-95bfe346-6573-11e7-96f3-8105e508fc5e.png)

**Comment by sbulen** [comment]
I've been able to reproduce this.   More info:
 - Attachments at the file system level are proper (in the example above, the motorcycle pic and thumbnail are not in the attachment directory at all....)
 - Attachment records in the DB are also proper and point to he proper file in the filesystem
 - If you open the post for update and everything looks OK (no motorcycle pic, the proper thumbnail is displayed)...   Until you save it, then the phantom thumbnail comes back...

So...  what's wrong?    one of the thumbnails is displayed with the wrong thumbnail image.   

This appears to be restricted to the **FIRST** few posts & thumbnails used in your DB.  Both instances I've seen this, this was the case.  

It corrects itself over time.

Where does the phantom thumbnail come from?   I'm not sure...   The motorcycle image thumbnail above is one of my photos, but had nothing to do with this post.  At all...

**Comment by sbulen** [comment]
I just reinstalled 2.1 & had a bunch of these issues in a row...   All the images were from different tests, an hour earlier.  

My theory is that this info is getting cached in there somewhere, probably in the \tmp directory, and these are getting confused with different photos, in a different session, hours later.  I further suspect the confusion comes in when the attachment IDs are the same from the prior session...   If so, this is not limited to "new" forums, but will be more prevalent in "new" forums.   

(Caching was off...)

**Comment by sbulen** [comment]
My WAMP server does not exhibit this behavior.   Only my hosted 'nix server...

**Comment by sbulen** [comment]
*** Problem goes away if you clear cached images & files from your browser. ***

The proper thumbnail is then associated with the pic...   So...  The issue is with the BROWSER cache...

**Comment by sbulen** [comment]
So...  I think I can close this...  

It only appears to occur when you nuke & restart a forum - an edge condition - and is easily fixed.

**Comment by Sesquipedalian** [comment]
> The issue is with the BROWSER cache...

That makes a lot more sense.

**Comment by sbulen** [comment]
The images are cached by id_attach+url.  Thus, within a day or so, if you end up reusing an attach I'd, this can happen. 

Sleepy explained to me what an etag was, and suggested we make it smarter.

But I really think this is an edge condition...   it will only happen if you nuke and restart a forum within 24 hours.   Even then,  there is no data corruption.  The cache will fix itself in a day, if you don't clear it first.

**Comment by Sesquipedalian** [comment]
Still, if you want to submit a PR to address this, all you'd need to do would be to append the value of `size` column to the end of the ETag string. Then it could only happen if the two attachments had the same URL, the same id, and were the same size.

(In theory, `file_hash` would be better to use that `size`, but we don't store a hash for avatars.)

**Comment by sbulen** [comment]
Thumbnails, not avatars.

The logic in showattachments.php for building the etags is pretty confusing to me.  It appears to try to append the hash to the etag, at least for thumbs.  But it only seems to honor the attach Id.   Why?  There is truncation going on - not sure if the truncation is to comply with rfc or not.  Also, there is slightly different logic for images vs thumbs - not sure why.    Also caches slightly different etag info in the cache - not sure why.  But there are a few variants in there.

Concerned about upsetting the apple cart - for such an edge condition.

**Comment by Sesquipedalian** [comment]
> Concerned about upsetting the apple cart - for such an edge condition.

Fair enough. :)
