### ISSUE TITLE
Topic display no longer pages correctly (EDIT: has security implications, too)

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#4196]
It looks like #4134 introduced a bug with proper paging in topics. There are multiple ways the bug shows up, but it is really all the same bug. #4151 tried to fix part of the situation, but more problems remain.

Assume in the following examples that topic 53 contains 35 replies, and the messages per page option is set to 15.

## Old, expected behaviour
1. Go to http://www.example.com/forum/index.php?topic=53.10
2. Be served a page containing the original post plus replies 1-14 (total 15). The page index indicates that this is page 1 of 3.
3. Go to http://www.example.com/forum/index.php?topic=53.32
4. Be served a page containing replies 30-35 (total 6). The page index indicates that this is page 3 of 3.
5. Create a new post, which becomes reply 36.
6. After posting, be served a page containing replies 30-36 (total 7). The page index indicates that this is page 3 of 3.
7. Go to http://www.example.com/forum/index.php?topic=53.37
8. Be served a page containing replies 30-36 (total 7). The page index indicates that this is page 3 of 3.
9. Go to http://www.example.com/forum/index.php?topic=53.38
10. Be served a page containing replies 30-36 (total 7). The page index indicates that this is page 3 of 3.

## New, buggy behaviour
1. Go to http://www.example.com/forum/index.php?topic=53.10
2. Be served a page containing replies 10-24 (total 15). The desired post (reply 10) is first. The page index indicates that this is page 1 of 3.
3. Go to http://www.example.com/forum/index.php?topic=53.32
4. Be served a page containing replies 32-35 (total 4).  The page index indicates that this is page 3 of 3.
5. Create a new post, which becomes reply 36.
6. After posting, be served a page containing just  reply 36 (total 1).  The page index indicates that this is page 3 of 3.
7. Go to http://www.example.com/forum/index.php?topic=53.37
8. Be served a page containing no replies. The page index indicates that this is page 3 of 3. SMF's error log contains the error message "Undefined offset: 0" referring to line 920 of Display.php.
9. Go to http://www.example.com/forum/index.php?topic=53.38
10. Be served a page reporting the following error:
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 5
File: /Users/jon/Sites/dev/Sources/Display.php
Line: 868


SELECT id_msg, id_member, approved
FROM dev_messages
WHERE id_topic = 53
ORDER BY id_msg DESC
LIMIT 0, -1
```
SMF's error log indicates that this happened on line 868 of Display.php

## Cause
This bug appears to occur because #4134 moved the call to `constructPageIndex()` lower down in the `Display()` function. Among other things, `constructPageIndex()` normalizes the value of `$_REQUEST['start']` to an even multiple of `$context['messages_per_page']`. Doing this avoids all the buggy behaviour described above.

## Security related implications
Using the new code, when would-be hackers try to access, e.g., `http://www.example.com/forum/index.php?topic=53.0&quot;%20and%20&quot;x&quot;%3D&quot;x`, the following error message is logged, referring to line 868 of Display.php:
```
Wrong value type sent to the database. Integer expected. (start)
Function: Display
```

That means that `$_REQUEST['start']` is not being sanitized the way it should be before being passed to `$smcFunc['db_query']()`. It is good that we have multiple layers of security, which is my forum hasn't been hacked yet, but the fact that this error was generated at all means that at least one of our layers of security has been compromised by this bug. The sanitization provided by `constructPageIndex()` silently gets rid of all that sort of SQL-hacker cruft before it has a chance to get anywhere.

## Recommendation
@albertlast, I think you will need to rethink how you have structured the code in Display.php to support your new seek method.

In the meantime, I think we need to revert the following commits (i.e. #4134 and #4151):
9c19ce5fe7d62270949f5ea102da42cd7459d935
21f395b40ac4b7a8f406e1fdf094411d0eede748
1631908b7c441a86e98f69c70a5491d06849dd7c
e2b10fd24660a764ae3f5566800eb29b49348231
a36277b84303eca1fbed27cd61130e49d402fe75

Once @albertlast comes up with a new version of his seek method, we can reimplement it. :)

**Comment by albertlast** [comment]
this is no security issue, that we test that start is a int is wanted by design and our database layer test this.
And this is no "lucky" incidient.

**Comment by Sesquipedalian** [comment]
The database layer intercepted it, yes. But the bad values should not even have gotten to the database layer. The value should have been sanitized before it was handed to `$smcFunc['db_query']()`. Not sanitizing it puts a hole in our first layer of security.

**Comment by albertlast** [comment]
Crazy shit that the function do security stuff,
this wrong by design, i placed a pr wher i pull out this stuff and
boards looks now better.

Needs to be clean up,
maybe a offical security function for start but nothing silent/hidden like the existing solution.

**Comment by Sesquipedalian** [comment]
> Crazy shit that the function do security stuff,
this wrong by design,

I agree. The reason it took me a while to realize that those error messages were connected to this bug is that I assumed that `$_REQUEST['start']` would have been sanitized earlier in the process. Ideally, that sanitization ought to happen in QueryString.php. If you want to take a shot at doing that in #4198, that'd be great. :)

**Comment by Sesquipedalian** [comment]
I've added some code to QueryString.php in #4199 that sanitizes `$_REQUEST['start']`. After it is merged, @albertlast, I recommend that you add some more code in the same place to sanitize `$_REQUEST['page_id']` however you like. Or if you'd prefer, I can include such code directly in #4199.

**Comment by albertlast** [comment]
about page_id
i already mention in the pr from you,
in my eyes it's better to check this var befor you access this and not early on and
this is already done by https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Display.php#L827
maybe a int check is missing, but like i said the database to this stuff already so for me is no need.

**Comment by jdarwood007** [comment]
The database security handler is the last line of defense of protecting uncleaned or improperly formatted data from making int into any queries.  If we are getting errors because the security system is stopping something, we should be preventing that from occurring in the first place by cleaning that input better.
