### ISSUE TITLE
bbc code bug

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4203]
a post with this message
` [code]'&#39;', '&#96;', '&#123;', '&#125;'[/code] `
get as result `'&#39;', '&#96;', '{', '}'`

In the db look like that
`"[code]&#39;&amp;#39;&#39;, &#39;&amp;#96;&#39;, &#39;&#123;&#39;, &#39;&#125;&#39;[/code]"`

i would guess ther are missing amp;

This bug i copy from elkart.
https://github.com/elkarte/Elkarte/issues/2961

**Comment by Sesquipedalian** [comment]
I'll look into it.

**Comment by Archer70** [comment]
What is the desired behavior here? Currently The display is the same, regardless of whether it is posted in a code block, a quote, or just by itself.

![screenshot from 2017-08-20 19-29-01](https://user-images.githubusercontent.com/2660927/29501527-e83884f4-85dd-11e7-8c82-c48d721ebbd5.png)

I believe at Elkarte they decided that code blocks should post literally what is between them:
`'&#39;', '&#96;', '&#123;', '&#125;'`
while outside code, it should be interpreted:
`''', '"', '{', '}'`

Personally, I think it should not be interpreted. If you post `&#39;` you get `&#39;` back, and not a quote.

**Comment by albertlast** [comment]
the right behavior should be input = output and
this is here not the case.

**Comment by Arantor** [comment]
Question: was this posted from quick reply, full reply, or quick edit? Historically the behaviour has been inconsistent between the three in terms of entity preservation.

**Comment by Archer70** [comment]
I used quick reply.

**Comment by Sesquipedalian** [comment]
#4283 seems to fix this, but it needs testing by others before merging. I strongly encourage testers to try to find ways to break this code. I didn't find any ways to produce unexpected behaviour, but I may not have thought of everything.
