### ISSUE TITLE
Summery/digest of posts notification email

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#4204]
After upgrading from beta 2 to beta 3, I'm receiving daily summery/report of posts. The option in my notification settings is "nothing, just make a note of it". Is that the correct option? Shouldn't it be set to "send me daily email digest" for it to send me daily emails?

It wasn't sending anything when it was on Beta 2.

**Comment by colinschoen** [comment]
Pending replication...

**Comment by asmith20002** [comment]
It's a minor issue. I fixed it by selecting another option in the same select box, then again changed it back to "nothing, just make a note of it".
