### ISSUE TITLE
ssi  subs-db-mysql.php

### ISSUE THREAD

**Issue by replikacep** [SimpleMachines/SMF#4205]
Subs-db-mysql.php file has a utf8 problem on db connection created in ssi.php

Row 384  Subs-db-mysql.php

$connection->set_charset("utf8");

**Comment by albertlast** [comment]
can you provide us with more information?
Like the error message you got.

**Comment by replikacep** [comment]
modes There is a character problem with the db connection in the modifications

**Comment by albertlast** [comment]
This doesn't help.

What is the motivation to do this?
smf 2.1 is by default setted to utf8.

**Comment by replikacep** [comment]
Mode larda character gives a mistake

**Comment by ogulcandegdas** [comment]
load.php `if (!empty($db_character_set))
		$smcFunc['db_query']('', '
			SET NAMES {string:db_character_set}',
			array(
				'db_character_set' => $db_character_set,
			)
		);`

Code is invalid in mods.

**Comment by XinYenFon** [comment]
So it requires mod author's attention ? You should be testing the software in vanilla stage.

**Comment by sbulen** [comment]
A screenshot would help - or at the least the text & details of the error.   

Does this only happen with a certain mod installed?  If so, Antes is correct, you should notify the mod author.  

$db_character_set should be populated.  I don't see what the issue could be, & there isn't enough info to work on here.

**Comment by replikacep** [comment]
antes  ben  sana yazayım sen cevir  kaldırdıgınız kodlar  yüzünden   seo yada party  modu olsun link cevirme yada  başka bir modda  karakter eksikligi oluyor burada ki oynama yüzünden gereksiz  tamamen  sadece  dedigim modlarda degil her modda gecerli bu  ya mod yazarlarına bu  satırı  eklemelerini söyleyin  yada  bu satırı geri ekleyin 
load.php if (!empty($db_character_set)) $smcFunc['db_query']('', ' SET NAMES {string:db_character_set}', array( 'db_character_set' => $db_character_set, ) );

**Comment by XinYenFon** [comment]
This can be closed. Its not related to SMF core but mods. Mod authors should update their modifications based on the new changes.
