### ISSUE TITLE
2: stripos(): Offset not contained in string

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4207]
Pure vanilla install, I've started seeing these errors.  More info:
    `https://yadayada/index.php?action=.xml;type=atom`
    `File: /yadayada/Sources/Subs.php   Line: 2477`

These were reported in my hosted test environment (public). I was away on vacation when these occurred.

**Comment by Sesquipedalian** [comment]
I'll look into it.

**Comment by Sesquipedalian** [comment]
Are you testing with the latest version of release-2.1? Because line 2477 of Subs.php is blank.
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs.php#L2477

**Comment by Sesquipedalian** [comment]
Or a better way of putting the question: what is at line 2477 of Subs.php on the specific install that generated the errors?

**Comment by sbulen** [comment]
This was a fresh install one week ago...   The lines are:
![image](https://user-images.githubusercontent.com/23568484/28344697-2fa4a908-6bda-11e7-9106-2a605e5bba80.png)

**Comment by sbulen** [comment]
Looks like it's 2449 now...

**Comment by Sesquipedalian** [comment]
Thanks. Looks like something in one of the posts in the feed is breaking parse_bbc. Could you post here the raw XML of the feed that is generating the error?

**Comment by sbulen** [comment]
To be honest, I don't know...   This is one of my test environments.  I was away for a few days, & had ~15 of these errors in the error log.  

If I had any posts in there at all, it was a simple one with a photo attachment, as I was testing attachments before I left.   (Unfortunately I just reinstalled it with the latest from Github...)

**Comment by sbulen** [comment]
I was testing the image proxy, if that helps...

**Comment by Sesquipedalian** [comment]
Okay. Well, I think I've got a general idea of what happened anyway. News.php truncates the text of a post body before passing it to parse_bbc(), and that resulted in some malformed BBC in that post. Generally speaking, parse_bbc() is quite good at detecting and fixing broken BBC, but your post appears to have created a situation that tripped it up. If I could have seen it, I'd be in a better position to figure out exactly what caused the problem.

**Comment by sbulen** [comment]
May be related...  I had been testing the image proxy, and it's not working for me in test.  Proxied images show up as broken links.  If I look in the browser console, I see an error 403.  

That test was literally the only post in there, other than the 'welcome' post.

**Comment by sbulen** [comment]
I am going to close this.  I believe it was related to the mod_sec issue with my site reported here: #4212 

If it reoccurs, I will reopen.
