### ISSUE TITLE
Image proxy - error 403

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4212]
I have a new test environment on my host.
I can't get the image proxy to work at all in my new test environment.  
The browser console displays error 403...   
Feels like I'm missing something obvious...
![image](https://user-images.githubusercontent.com/23568484/28402612-9fea5aa4-6cd5-11e7-97ca-f23dcb4abd8f.png)

Permissions? but of what? My tmp directory is set at 755...

**Comment by LiroyvH** [comment]
First step in analysis: check the error log. :) This can be located as an error_log file in the directory of your forum, in the main public root of your domain, or in the generic error_log of your webserver. (Eg: Apache. For example on cPanel servers: /usr/local/apache/logs/error_log)

Check that, and see what's in there for showing the 403 error.
This can indeed be permission based, a configuration error or for example some weird mod_security rules or a problematic entry in your .htaccess.

**Comment by sbulen** [comment]
Thanks for the feedback...

Well my ISP (HostGator) has a much more dumbed down UI than that...   That series of folders doesn't exist in FileManager.

Error log access is all thru cPanel portlets.  Mine are all empty - it says they get flushed every few hours unless you archive them...  So, I am now archiving them.  Will take a look later tonight...

Even after reproducing the error, the logs look empty (2 logs are available, "Errors" and "Raw Access").  

I'll keep digging, and, if necessary, open a ticket with HG.  

This is a *brand new* vanilla account with a vanilla 2.1 install.  My concern is that others will experience the same.

**Comment by sbulen** [comment]
The log was not helpful, it just indicated the 403.  

HG support resolved it immediately.  I asked them what they changed, & the response was "Sure, your mod_sec rule was being blacklisted which can happen with plugins and I white listed the rule and now it works".

So, it was, in fact, a mod_sec issue.
