### ISSUE TITLE
Unknown function: authentication

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#4215]
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Profile.php#L648

This function doesn't seem to be defined anywhere.

**Comment by Oldiesmann** [comment]
I'm thinking this is old code as well. The only authentication-related areas in the profile are account (password, secret question, etc.) and tfasetup (handles enabling/disabling two-factor authentication).

**Comment by jdarwood007** [comment]
It was in 2.0
Zeus:~ jeremy$ grep -Rn "function authentication" sm/smf-svn/branches/
sm/smf-svn/branches/2.0/Sources/Profile-Modify.php:1750:function authentication($memID, $saving = false)

It was used for switching between openid and password authentication.  Seems openid is stripped out of 2.1.  Also seems we just drop the table, columns and settings during the upgrade and don't have a way to handle migrating people back to password auth.

**Comment by Sesquipedalian** [comment]
> Also seems we just drop the table, columns and settings during the upgrade and don't have a way to handle migrating people back to password auth.

That's not so good...

**Comment by NanoSector** [comment]
Seems to be fixed since #4252, closing.
