### ISSUE TITLE
Shift to SimpleXML instead of XmlArray

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#4217]
SimpleXML is compiled with and enabled by default in PHP 5.1 and on. We require 5.4 now so I'd say we're pretty sure everyone has it in their PHP installations. If someone can gather data on this, that'd be great.

Benefits to us are that the code is better maintained and probably a lot more resistant to errors than our custom XmlArray.

**Comment by Oldiesmann** [comment]
Taking a quick look at the constructor for XMLArray, I don't see how SimpleXML would be a replacement:

```php
	/**
	 * Constructor for the xml parser.
	 * Example use:
	 *  $xml = new xmlArray(file('data.xml'));
	 *
	 * @param string $data The xml data or an array of, unless is_clone is true.
	 * @param bool $auto_trim Used to automatically trim textual data.
	 * @param int $level The debug level. Specifies whether notices should be generated for missing elements and attributes.
	 * @param bool $is_clone default false. If is_clone is true, the  xmlArray is cloned from another - used internally only.
	 */
	public function __construct($data, $auto_trim = false, $level = null, $is_clone = false)
```

XMLArray does a lot more than just parsing things - it trims data, strips unwanted tags (<?xml>, CDATA, DOCTYPE), error handling, etc. It might be something we can look into for the next version of SMF (whatever version that might be), but at this point I think it's a little late in the development process to do this.

**Comment by NanoSector** [comment]
I agree it's too late for 2.1 now.

What you described is exactly why we should look for a replacement. For a class named XmlArray you would expect it to just be an array of XML data, e.g. a storage of parsed XML data. A class for that should not trim data, strip tags, do error handling, do logging, or whatever else - it's not the point of that class. SimpleXML is nothing more than an XML parser - it takes XML and lets you manipulate it using methods.

**Comment by BitFros7y** [comment]
Ok i have a bit different question, why change XML with XML? Why not just get rid of XML and use JSON? JSON has become standard and replaced XML everywhere... What i would do is leave it as it is now, and add to road map of future version (2.2 or later) "Migration to JSON"

**Comment by XinYenFon** [comment]
@NegativeIQ that requires some discussion, as you understand its a some change to core methods.

@Yoshi2889 I guess then its safe to close this and move to Forum for later discussion ?

**Comment by NanoSector** [comment]
Why not leave it open and add it to a new milestone?

@NegativeIQ package files contain XML documents, these need to be parsed. I don't think JSON can provide everything that our current XML approach can, not in the same manner anyway.

**Comment by BitFros7y** [comment]
@Yoshi2889 i would disagree on that, i think they are both equally capable. In fact they have been born with idea to be both human and program readable. The difference is that XML is generaly oriented, while JSON is more javascript oriented. But for us, that is actually a good thing since we could use same package to support API in the future (or someone will make mod like they always do).

And about packages containing XML's. Converting from XML files to JSON should be piece of cake with a simple script (if people are lazy to do it manually for 10-20 lines). The only downside would be breaking changes without new major version, but then again im pretty sure 2.1 already breaks to much mods...

EDIT: I would add these to road map as (Migrate to JSON) and leave it for some future version, but like @Antes already said, you folks should discuss these first...

**Comment by XinYenFon** [comment]
@Yoshi2889 because you said its too late for 2.1, and this repository for SMF 2.1 not SMF itself so you actually need to close this and move to other repo (or forum).

**Comment by Arantor** [comment]
Aside from the small detail that it isn't actually directly possible to represent things in JSON that it is in XML. Specifically, think of file edit instructions in mods, this requires having attributes on elements, something that literally does not exist in JSON and needs to be modified to express it in a different way. Which brings a raft of semantic changes with it.

**Comment by NanoSector** [comment]
Not to mention JSON requires proper escaping and formatting of its
contents, something which isn't the end of the world but makes the packages
much harder to read and maintain.

Also Antes, I strongly feel like we should be keeping issues together with the code somehow and that the forum is not the right place to put them. But this isn't the right place to discuss this.
