### ISSUE TITLE
SSL Assumptions

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4218]
I believe I have found two coding issues/assumptions both possibly impacting SSL.  

(1) The assumption that if force_ssl is set, that SSL is enabled/active.  This is not true, as force_ssl set to '0' means it is disabled.  Checking is_set(force_ssl) is insufficient.  Since force_ssl is new to 2.1, this only impacts 2.1 code.

(2) $_SERVER['HTTPS'] is used in several places, and what I've read indicates it is used slightly differently between IIS and *nix.  In *nix, it is either 'on' or it's not set (never 'off').  Some IIS servers have it 'on' or 'off'.  Similar thing, we cannot assume it is 'off' when it is not set; that will work for *nix but not all IIS users.  

The $_SERVER['HTTPS'] assumption possibly impacts 2.0 IIS users.  

I'm going to audit usages of both & provide some examples.

**Comment by Sesquipedalian** [comment]
Maybe we could implement some code early in SMF's process to analyze $_SERVER['HTTPS'] and then set something like $context['HTTPS'] to a simple boolean based on the result. After that, everywhere else that we currently check $_SERVER['HTTPS'] could be changed to check $context['HTTPS']

**Comment by sbulen** [comment]
force_ssl example, in Login2 in LogIniOut.php:
`if (!empty($modSettings['force_ssl']) && empty($maintenance) && (!isset($_SERVER['HTTPS']) || $_SERVER['HTTPS'] != 'on'))`
The problem is that force_ssl being non-empty doesn't really tell you anything...

I'm re-reading the $_SERVER['HTTPS'] code...  It may be OK...  Double-negatives sometimes make my head hurt...

**Comment by Sesquipedalian** [comment]
What's the problem with `!empty($modSettings['force_ssl'])`? That'll only return true if force_ssl is set and it's value is greater than 0.

**Comment by sbulen** [comment]
You are correct.  
I looked closely at the $_SERVER items today and I now think those are all OK.  Confusing, but OK.  
I'll check the force_ssl items tomorrow - wasn't able to look at them today.

**Comment by sbulen** [comment]
Back to $_SERVER, one item that confused me was this line in ManageServer:
`array('secureCookies', $txt['secureCookies'], 'db', 'check', false, 'secureCookies', 'disabled' => !isset($_SERVER['HTTPS']) || !(strtolower($_SERVER['HTTPS']) == 'on' || strtolower($_SERVER['HTTPS']) == '1')),`
I'll make it consistent with the rest.  Specifically, we don't need to check for an upper or lower case '1'...  I'll remove that.  It works today due to the OR, it's just confusing.  

Regarding force_ssl, there are a BUNCH of these checks across SMF, especially throughout the template code... This one is from Load.php:
`$context['login_url'] = (!empty($modSettings['force_ssl']) && $modSettings['force_ssl'] < 2 ? strtr($scripturl, array('http://' => 'https://')) : $scripturl) . '?action=login2';`

These will only swap to https if force_ssl is 1.  Which...  Is probably desired...   force_ssl = 1 is the 'login only' setting.  This makes sense if you're operating under the understanding that if force_ssl =2, everything is already https.  force_ssl = 1 requires a conditional swap in certain places.  These are probably ok.

**Comment by sbulen** [comment]
After all that...  One minor tweak...  #4219 submitted.
