### ISSUE TITLE
Collapse header on index.template

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#422]
The header is sliding quickly up and down on each paage load is a guest browse the forum.
It's a problem, because $options['collapse_header'] is not set (the cookie is not read).
can be done with this small code before:
    if(!isset($options['collapse_header']) && isset($_COOKIE['upshrink']))
        $options['collapse_header'] = $_COOKIE['upshrink'];

also this don't work in the smf_toogle settings:
bUseThemeSettings: smf_member_id == 0 ? false : true,

seems like smf_member_id is not set .. better use:
bUseThemeSettings: ', $context['user']['is_guest'] ?  'false' : 'true', ',

**Comment by Arantor** [comment]
Better question: do we actually need that upshrink in the first place? I've never understood the logic of it and from everything I can tell, it seems to cause more questions than it solves.

@Oldiesmann, @MissAllSunday, @emanuele45 thoughts?

**Comment by MissAllSunday** [comment]
Sorry, theres just been a lot of activity here and is difficult to follow all comments, I'm only half way :P

I find it useful to have it collapsed but I recon I'm in the minority.

Well, we could def use some consistency with settings that are displayed to guest as well, I suppose the member ID was used to save another if conditional, so, either use the member ID and make sure the php vars actually shows 0 for guest instead of false or use is_guest and print the false, just like feline mentions, perhaps we can apply the same logic to categories too.

**Comment by illori** [comment]
also there is a bug in collapsing the header in 2.1, it expands a bit too far. i believe yoshi said we need to add a width to the header to stop that from happening.

**Comment by MissAllSunday** [comment]
If it gets removed that bug will be squashed as well.

**Comment by illori** [comment]
this has also caused a bug in some areas of the admin panel where a session verification error comes up when the header is collapsed i believe it is... would need to ask kindred for the details i think he was the one that reported it.

**Comment by emanuele45** [comment]
Illori wrote:

> this has also caused a bug in some areas of the admin panel where a
> session verification error comes up when the header is collapsed i
> believe it is... would need to ask kindred for the details i think he
> was the one that reported it.

Has been fixed ages ago.

**Comment by illori** [comment]
i did not know, as i did not test it as i dont really ever use that feature.

**Comment by matthew-kerle** [comment]
Obviously I don't have much weight in this matter anymore, but I would personally vote for removing it...

**Comment by Arantor** [comment]
As per above, header now can't be collapsed, meaning this is solved.
