### ISSUE TITLE
Repair settings SSL issue/question

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4220]
If you do NOT have a redirect setup, but otherwise have a fully SSL enabled forum, and invoke repair_settings.php, without specifying https://, _all recommended settings are http://._   

Even if the boardurl (& all other urls) are already https.  repair_settings.php recommends that you change them back...  

It works fine if repair_settings is invoked via https://.  

Should repair_settings make recommendations based on how it is invoked?   Not what is found?

I'm still trying to wrap my head around how these SSL settings should interact with the webserver redirect, which is outside of SMF control.  Related to the discussion over on #4011 .

**Comment by jdarwood007** [comment]
repair_settings.php makes assumptions based on what it can detect at the time.  It can't detect a valid https session if your using http only.  So if you are navigating from a https session, it assumes the settings should be fixed to be https.

**Comment by sbulen** [comment]
I think all these tools - the installer, upgrader & repair_settings - make assumptions based on how they are invoked.  If invoked https, they work relative to https; if invoked http, they work relative to http.  

As long as we all know & understand the ramifications, that's good.  Nothing really necessary here.  

So I'll close.

When interacting with users on the support site, for folks cutting over to SSL, it becomes important to tell them to invoke repair_settings via https://.   (Or to have their redirect setup first.)
