### ISSUE TITLE
Membergroup As Board Moderator - Board Index Display Bug

### ISSUE THREAD

**Issue by SugarD-x** [SimpleMachines/SMF#423]
If you set a membergroup as a Board Moderator on a board listed from the forum's Board Index, it will not display UNLESS a user is ALSO set as a Board Moderator for that board. For example:

Board Index when both types are assigned to moderate the board:

"General Discussion"
"Moderators: User1, Membergroup1"

Board Index when only a membergroup type is assigned to moderate the board:

"General Discussion"

Board Index when only a user type is assigned to moderate the board:

"General Discussion"
"Moderators: User1"

My assumption is that this bug is caused by a check missing on the membergroup Board Moderator type, which the user type already has.

**Comment by illori** [comment]
@Oldiesmann one for you to look into

**Comment by matthew-kerle** [comment]
Very simple fix I'm sure. I'll post the code later today.

My local repository is quite messed up due to switching IDE's or I'd commit it.

**Comment by Oldiesmann** [comment]
I'll look into this real quick while I'm still around

**Comment by SugarD-x** [comment]
Just updated my files. Bug still happens on the Board Index, same as reported.

**Comment by illori** [comment]
i just tested this and the group name along with a link to a page showing the groups members shows on the index just fine.

**Comment by SugarD-x** [comment]
I still can't get it showing. Are you guys sure you have ONLY membergroups
set as Board Moderators? If you have a single user set as one too, it works
fine. If no users are set, nothing shows for me from the Board Index,
although it works fine from within the board itself.

**Comment by illori** [comment]
yes i tested it with only a group as moderator and it worked just fine.

**Comment by emanuele45** [comment]
![Uploading screen_107.png . . .]()

**Comment by illori** [comment]
that did not work emanuele, can you try again?

**Comment by emanuele45** [comment]
I know, I had to leave for lunch. :angel: 

![screen_107](https://f.cloud.github.com/assets/1095308/680729/d93d8174-d999-11e2-8a1d-cbeec93673a2.png)

AHA!
It requires amazon javascripts enabled. :-1:

**Comment by SugarD-x** [comment]
![membergroupmoderatornotworkingsmf21](https://f.cloud.github.com/assets/4693806/680751/89716f88-d99a-11e2-8c1b-46694ba14e19.png)

Still not working for me. I updated after this report was closed too. :(

**Comment by illori** [comment]
is that group a visible group or set to be invisible?

**Comment by SugarD-x** [comment]
It's visible.

**Comment by illori** [comment]
is the group private, protected, requestable or free? it should not be a post based group

**Comment by SugarD-x** [comment]
It's a private membergroup.

**Comment by illori** [comment]
that is the problem, a private group is only shown as secondary and can not show the link. although i talked to @Oldiesmann about this and he said private groups should not be board moderators, so he needs to look into why they can still be set if he does not want them to be group moderators

**Comment by SugarD-x** [comment]
Doesn't that defeat the purpose of SMF's membergroup system then? Non-included membergroups created by users are private/visible by default. It doesn't really make sense to restrict them if you only want them assigned to specific users. I can easily think of scenarios where you may make a custom membergroup with a certain purpose who you also want moderating a board.

**Comment by illori** [comment]
i know i told him users will want to assign private groups [but they cant show up on the index due to that they are private and you cant view who is in them] but he did not want to add it, or clarify it. i guess you can add the private groups, just something should be added to say they will not show on the index if that is what oldies does want.

**Comment by illori** [comment]
actually i am wrong, it is the visibility i was thinking of... this may be a bug with private, i thought he had fixed this but either way he needs to look into this issue.

**Comment by SugarD-x** [comment]
Aren't private groups visible using "./index.php?action=groups" and user profiles still? Private groups usually just mean users can't join them on their own, and they must be assigned by someone with rights to do so. Visible/invisible was what controlled whether people could see them or not. I think he might have confused the two settings. :P

**Comment by SugarD-x** [comment]
Ah, sorry. I replied before I saw your message.

**Comment by emanuele45** [comment]
The screenshot I posted is valid for (i.e. I tested it with): a private/protected/requestable/free/post based, "based-on", visible (or invisible <= and this is a bug because invisible groups should...not be visible of course) group. Tested with admin account, normal user account, guest.

Always visible.

Can you try (yet again if you already did) to re-download the last version of the code either pulling it again from release-2.1 branch or downloading [the package from here](https://github.com/SimpleMachines/SMF2.1/archive/release-2.1.zip)?

If I have time I'll try a new install.

**Comment by illori** [comment]
emanuele is right, i tested with private and the group name shows up, i did not double check that earlier.

have you tried clearing out the group from being board moderator save the page and trying to add the group again?
