### ISSUE TITLE
[security] email @ password reset

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4232]
More or less the the same question like username,
when you use reset password function.
smf tell the user if the email address is used or not:
![grafik](https://user-images.githubusercontent.com/1782906/29183815-4cecf16e-7e04-11e7-8511-bdfb2c162e25.png)

Is this behavior good?
In my eyes this information is not avaible in the member list,
so it shouldn't publish here.

**Comment by frandominguezl** [comment]
What is your suggestion to put there instead of that?

**Comment by albertlast** [comment]
the same message when successfull:
![grafik](https://user-images.githubusercontent.com/1782906/29184576-f7e5ad34-7e06-11e7-916d-f518cbc2aae7.png)

**Comment by frandominguezl** [comment]
So, if the user accidentally mistyped his email, he'll be waiting for a never arriving email?

**Comment by albertlast** [comment]
or try it again after some minutes,
which you need to do any way when the mail gelost of some other mistakes are happening

**Comment by frandominguezl** [comment]
No, I mean, if you think you put the email correct but you didn't, and the system tells you that you have been sent an email, you won't get one.

**Comment by albertlast** [comment]
like i said than you try it again when no mail arived,
you could hit "unlucky" someone other mail address.

**Comment by Gwenwyfar** [comment]
Just change the message to say "an email was sent to input-email@x.com". If the user typed wrong, he'll see it on that page, and it just says the same message even if no accounts are associated with it. 

The message could also say at the end something like "if you didn't receive any email make sure the email is correct or you have an account registered with that email".

**Comment by LiroyvH** [comment]
I'd simply phrase it to something like "An email will have been sent to the provided user/email, should it exist in our database.". Something like that. Simple, straightforward; no info leaked.

**Comment by Gwenwyfar** [comment]
Can't you also use the register page to check for used emails though?

**Comment by LiroyvH** [comment]
Yep that's true, didn't think about that one.
