### ISSUE TITLE
Mobile is corrupted Location

### ISSUE THREAD

**Issue by replikacep** [SimpleMachines/SMF#4233]
https://i.hizliresim.com/MvA3ZQ.png

[url=https://hizliresim.com/MvA3ZQ][img]https://i.hizliresim.com/MvA3ZQ.png[/img][/url]

Mobile is corrupted Location  
admin /Mail queue statistics

**Comment by XinYenFon** [comment]
Good catch.

Edit: I suggest this should be addressed before RC1.

**Comment by replikacep** [comment]
:)

**Comment by replikacep** [comment]
I caught a bit more
https://i.hizliresim.com/ER91Dg.png

https://i.hizliresim.com/MvAMR9.png

**Comment by Gwenwyfar** [comment]
It would help if you post the URL along with the image, not everyone speaks (whatever language that is, sorry, I don't even know that much).

These may all be fixed together by the looks of it though, seems to be the same element type.

**Comment by replikacep** [comment]
admin / News and Newsletters 

admin / Smileys and Message Icons
