### ISSUE TITLE
Old issues

### ISSUE THREAD

**Issue by BitFros7y** [SimpleMachines/SMF#4248]
I notice that there are quite a few very old issues opened here, some dating back to 2013. So my question is why nobody closes damn things?

**Comment by XinYenFon** [comment]
Because they are still valid ? (I think)

**Comment by Gwenwyfar** [comment]
Issues need some organizing, have tags/labels on all issues and go through old issues to see if any can be closed (though it seems most old issues are still valid).

**Comment by BitFros7y** [comment]
Yeah exactly...Close what is possible to close right now, and lets see if anyone is willing to fix what's left.
EDIT: Honestly im surprised that they are still valid...I mean is it possible that in almost 4 years nobody fixed them and yet work on 2.1 is considered to be in finishing stages for RC versions...

**Comment by sbulen** [comment]
Serious issues are identified and addressed today.  The question is what to do about the others.  

As a general rule, you want the original poster to close out issues, to make sure it was properly resolved. 
 It's hard to tell who has moved on, though.  

The RC list needs attention.  Folks seem to work on anything BUT that list.  I'd focus on that first.  

My underlying concern is directing volunteers towards the issues that are truly important & must be addressed.  As a volunteer from outside the team, it is hard to tell if I'm working on items of merit, specifically, fixes that will help push 2.1 towards release.

**Comment by Gwenwyfar** [comment]
Even more reason to have everything properly labeled. Add a few labels for importance level as well and that's one less thing to worry about.

**Comment by Arantor** [comment]
In fact there are issues going back 10 years that are still valid but never tackled for reasons.

**Comment by sbulen** [comment]
This subject of discussion is this log, which goes back 4 years.

If there are issues 10 years old in another log, I'd close them.   Valid or not, they were clearly unimportant.  Items that are so low priority - or nebulous - that they will never be addressed should be closed.  Clearly nobody cared but the author, who likely needs to let it go.

**Comment by Arantor** [comment]
They're only this old because too many people are too interested in new things rather than fixing old things, combined with the fact that there are people who argue that bugs aren't actually bugs because "it's always been this way" as though that legitimises something.

You'll notice I stopped filing those issues around that time, after observing that to follow the much-requested "rename child boards to sub-boards" was a multi page debate. What hope was there to fix actual problems?

Besides it doesn't look good for a project to decide not to fix bugs.

EDIT: to the suggestion that I should let it go, I have closed the issues that I filed. Better?

**Comment by sbulen** [comment]
The discussion had veered to unspecified 10 year old issues not visible to folks here on github.  I responded to that.

For the record, @Arantor, I usually agree with your posts & issues & concerns.

**Comment by Arantor** [comment]
Where do you think I got those issues that I closed from?

**Comment by frandominguezl** [comment]
I think this should be closed.
