### ISSUE TITLE
Collapse/Expand categories

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#426]
What I don't understand ..
Why do the category collapse/expand send a request directly?
Why not collapse the category with the smc_toggle and send a ajax request to the server?
I think that is simple and faster to collase/expand ...

**Comment by emanuele45** [comment]
Probably mainly because nobody wrote it.

If you intend to, remember that on expanding it implies an ajax call to retrieve the category structure because if a category is collapsed nothing from that category is loaded.

**Comment by Arantor** [comment]
It would be faster for the user, sure, but it would necessitate more work from the server on board index.

Would it be nice to AJAXively get the partial board index and inject that when expanding?

**Comment by beratdogan** [comment]
I'm working on it.

**Comment by Arantor** [comment]
Closing this issue and referring to 663 instead.
