### ISSUE TITLE
load.php Typing error $smcFUnc

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4269]
Typing error?
$smcF**U**nc
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Load.php#L289
$integration_settings = $smcFUnc['json_decode'](SMF_INTEGRATION_SETTINGS, true);

Would have to $smcFunc, or not?

**Comment by albertlast** [comment]
Should be fixed now.
