### ISSUE TITLE
Install - Cookie names must not be empty

### ISSUE THREAD

**Issue by BitFros7y** [SimpleMachines/SMF#4273]
Latest commit atm. ( 6ad29c7a6bf0569b7833f6debe96c45454b035f0 )
https://smf.local/install.php?step=5
```
Warning
: Cookie names must not be empty in
C:\xampp\VirtualHosts\SMF2.1\Sources\Subs-Auth.php
on line
837
```
After install finishes i used login link and everything is fine so its just minor installer problem.

**Comment by frandominguezl** [comment]
I can't reproduce the issue. What PHP version are you using?

**Comment by BitFros7y** [comment]
Windows 10 x86, XAMPP stack, versions returned from CMD using  -v / --version
```
Server version: Apache/2.4.27 (Win32)
Apache Lounge VC14 Server built:   Jul  9 2017 11:48:22

PHP 7.1.8 (cli) (built: Aug  1 2017 21:10:46) ( ZTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for Win32 (AMD64)
```
If i remember correctly i was using https during installation.

EDIT: Oh i forgot to add, its a warning not error

**Comment by sbulen** [comment]
I don't see this on 5.6 with http on my wamp...   

EDIT:  correction...   http, not https

**Comment by sbulen** [comment]
Just did back to back 5.6, 7.0 & 7.1 installs, all https, all linux.  

5.6 was OK, 7.x displayed the error above at the top of the screen.  

Only thing I'd add is that in all versions, an invalid password also displayed errors at the top of the screen in a similar fashion.  I'll log that separately, I think that's a different, though possibly related, issue.  (It's possible it's all just error trapping?)

**Comment by sbulen** [comment]
In php7+, setcookie() with an empty cookie name now issues a warning...   It hadn't previously.  That may explain the difference between 5.x & 7.x behavior.   A call to setcookie() is on line 837 of subs-auth.php.

**Comment by sbulen** [comment]
PR #4275 submitted.  Caused by some recent cleanup.
