### ISSUE TITLE
class="preview" (href title attr) why only on topic starter messageindex

### ISSUE THREAD

**Issue by Pipke** [SimpleMachines/SMF#4298]
and not on last post messageindex, this class is missing also on board/unread/updated topics index on my quick look at the files @2.1 beta4, maybe there are more places where this class is missing. Just found it weird so i'm adding my first github comment on this project here.

**Comment by Arantor** [comment]
Because this is used for displaying the preview of the topic which isn't loaded in those places - you need to do more than just put the styling in, you need to apply some heavy duty database query changes. Especially as this is a thing that can be disabled... making all the logic way more complicated (and it's complicated enough as it is in unread/updated)

**Comment by Pipke** [comment]
topic starter: with preview class on hover username(not topic)
`<div class="message_index_title">
								', $topic['new'] && $context['user']['is_logged'] ? '<a href="' . $topic['new_href'] . '" id="newicon' . $topic['first_post']['id'] . '"><span class="new_posts">' . $txt['new'] . '</span></a>' : '', '
								<span class="preview', $topic['is_sticky'] ? ' bold_text' : '', '" title="', $topic[(empty($modSettings['message_index_preview_first']) ? 'last_post' : 'first_post')]['preview'], '">
									<span id="msg_', $topic['first_post']['id'], '">', $topic['first_post']['link'], (!$topic['approved'] ? '&nbsp;<em>(' . $txt['awaiting_approval'] . ')</em>' : ''), '</span>
								</span>
							</div>`

last post: no preview when hovering over username
`<div class="lastpost">
						<p>', sprintf($txt['last_post_topic'], '<a href="' . $topic['last_post']['href'] . '">' . $topic['last_post']['time'] . '</a>', $topic['last_post']['member']['link']), '</p>
					</div>';`

**Comment by Arantor** [comment]
How does that change what I said?

**Comment by XinYenFon** [comment]
I'm think there is a communication issue between. I think its safe to close, unless someone thinks its a good idea to change this behavior on other places.
