### ISSUE TITLE
Themes/default/images/membericons/

### ISSUE THREAD

**Issue by replikacep** [SimpleMachines/SMF#4299]
does not accept images with gif extension icon not set

https://i.hizliresim.com/bLDZRm.png https://preview.ibb.co/bAHJB8/bLDZRm.png

**Comment by replikacep** [comment]
beta 2 does not have this problem  Somewhere is breaking down Somewhere is being repaired ?

**Comment by XinYenFon** [comment]
I can't tag dev team as whole but can some explain is this intentional ? (Gif disabled) or bug ?

**Comment by replikacep** [comment]
antes  gif resimlerini  membericons  klasörüne atmama ragmen   çıkmıyor :)

şu anda  sitemde  bu şekil   ama önceki kayıtlar ekli oldugu için  gif  resim leri aktif şu anda  resim degiştirirsem yeniden gif secemem 

beta 2 de bu  sorun çözülmüştü

**Comment by frandominguezl** [comment]
@replikacep Please, just speak English here

**Comment by replikacep** [comment]
https://i.hizliresim.com/bLDZRm.png
https://preview.ibb.co/bAHJB8/bLDZRm.png
gif does not accept images

**Comment by XinYenFon** [comment]
I'm aware of the "issue", we are just trying to confirm if this is intentional (for some reason) or its just a bug, and before jumping to "BUT part" just because it was working on earlier version doesn't mean it should now. For example SMF 2.0 has sidebar toggle icon which is removed due to security issues.

Please be patience.

**Comment by XinYenFon** [comment]
Any update?

**Comment by replikacep** [comment]
problem solved turn off topic

**Comment by frandominguezl** [comment]
How it was solved? Isn't this an issue anymore?

**Comment by replikacep** [comment]
problem solved by developers

**Comment by frandominguezl** [comment]
Close this issue then

**Comment by illori** [comment]
confirmed fixed.
