### ISSUE TITLE
Empty dl being printed on profile page

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#4312]
![extra-dl](https://user-images.githubusercontent.com/28991853/30595961-1cb8e4dc-9d29-11e7-9d06-b6f6ca6ebb00.png)

It seems line 308 in Profile.template.php is checking for fields that go in that area, but their content being empty is not accounted for. So when there are no fields for standard placement the dl isn't printed, but if there are, and they are empty, it still prints it. It should not print the dl on both cases.

**Comment by illori** [comment]
confirmed
