### ISSUE TITLE
custom profile field, show on registration and require entry

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4315]
if you require a field to be completed on registration it also seems to require it to be filled out on the profile view. i dont think it should as there is no flag that states it has to be filled out in the profile.

**Comment by albertlast** [comment]
you mean this message:
![grafik](https://user-images.githubusercontent.com/1782906/30716302-d3760636-9f19-11e7-957d-3c294052b6d0.png)
In my eyes the existing behavior make sense,
otherwise you fill the field at registration and after login you can empty again the field.

**Comment by illori** [comment]
yes that message, it says no where on the config page for the field that would be required on the profile as well. if it should be then this should be noted on the config page.

**Comment by albertlast** [comment]
@illori is the change of the pr enough?

**Comment by albertlast** [comment]
![grafik](https://user-images.githubusercontent.com/1782906/30775449-04616954-a094-11e7-928e-6affddb0efb6.png)

![grafik](https://user-images.githubusercontent.com/1782906/30775455-14dbedfe-a094-11e7-850b-edc51299aa11.png)

**Comment by illori** [comment]
looks good to me.
