### ISSUE TITLE
Mouse Over of long topic looks wrong

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4321]
From a different issue i notice that the subject got a 80 char limit,
so i try out the limit and notice that the mous over of the time (where subject is than showed) looks wrong
when the subject is long:
![grafik](https://user-images.githubusercontent.com/1782906/30775539-e80009a8-a095-11e7-8c24-4043aba311c7.png)

The d is missing and the box look like cutted on the right edge.
More zoomed pic to make my point clear:
![grafik](https://user-images.githubusercontent.com/1782906/30775557-424de83a-a096-11e7-8d8a-34f646ac590b.png)

Maybe @Gwenwyfar  or @Antes could look into

FF 55 with Windows

**Comment by Gwenwyfar** [comment]
This is the browser's title tooltip, it will look different on every browser, we can't change it. Maybe you should submit this as a browser bug.

**Comment by albertlast** [comment]
Okay than it's a bug of ff.
