### ISSUE TITLE
output $topic['pages'] topic pages is missing class

### ISSUE THREAD

**Issue by Pipke** [SimpleMachines/SMF#4330]
on the MessageIndex.template there is this with class="topic_pages"
`', !empty($topic['pages']) ? '<span id="pages' . $topic['first_post']['id'] . '" class="topic_pages">&nbsp;' . $topic['pages'] . '</span>' : '', '`

as you look at Recent.template in there functions templates this class is missing, so the formatting is different if you compare them.
an example:
`<small id="pages', $topic['first_post']['id'], '">&nbsp;', $topic['pages'], '</small>`

**Comment by XinYenFon** [comment]
I think this is no more than a forgotten code, should be easy to fix with bringing MessageIndex code to Recent (tho still needs to be checked).
