### ISSUE TITLE
The google recapcha is not shown in the users language ..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#4331]
as the title say ...
the problem: the recapcha api is load in the template .. not on the head.
but that is a MUST .. then the api?hl=langcode will work correctly.
So you have to check in the Load.php (where all js is loaded), if the api need for the current request and if so, then load here.
If you do that, then the ?hl=lang works correctly !!
And .. the api langcode, you can put in the index.language.php ..

Also this need a little bit more code, so if this works on ALL situations correct.
As exampe .. 
if a guest do a search like "test", make the recapcha auth and show the first page.
then he make a new search with the same value ("test") no recapcha is shown !!
So bad guest can stress the system if he do this many times !!! (not good)

Also on Preview a Post / PM it's a good option to get the user a "HINT" that he have to complete the reCapcha before he **SEND** the message. At this stage it is no ERROR if the capcha not completed !!

Thanks for reading this ;-)

**Comment by Oldiesmann** [comment]
For the language code, we can just pull in $txt['lang_locale'] and drop the locale part (eg "en" instead of "en_US", etc.).

We'll have to look into the other issues.

**Comment by PortaMx** [comment]
I can tell you that this not works .. without the ?hl=langcode the chapcha use always the browsers default  language. And the ?hl=langcode works only if the api loaded on the head ...

**Comment by replikacep** [comment]
SMF 2.1 sanctions canceled 
 progress is very slow
