### ISSUE TITLE
Element closure indicator

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#4332]
This is a problem that tends to happen with any large html pages or in particular those embedded into php (as this makes text editors lose some html-managing functions):

There is no indication of what is closing where. This creates situations where for instance, we start opening some divs on line 184 of index.template.php, and following those, all the way down to line 370:
```
echo '
			</div>
		</div>
	</div>
</div>';
```

So not only you don't know exactly what is closing, if you go 200 lines up to check , you also need to check on the order, and double-check to be sure which one is from which div (or other equally time-wasting ways to see). And also note: not all of them open close to each other, some of these open on 314, so you'd have to be scrolling searching for all of them.

This is also not very good for mod makers, as it makes it harder to replace something after or before a particular div, if they need to.

My proposal is to fix this problem by making a comment indicator of every div that closes too far from it's parent, for example:

```
	echo '
			</div><!-- #main_content_section -->
		</div><!-- #content_section -->
	</div><!-- #wrapper -->
</div><!-- #footerfix -->';
```
Which is much clearer and makes reading or editing the code much easier.

We can have some rules on this so it is always consistent, for example: 

- The name is always the ID if it has one, or if it doesn't, an identifying class (ex: .inner_wrap )
- Only divs that close after Y lines need to be marked, unless there is an exception that could benefit (most other elements are never very large, or they are self-identifying).

Thoughts? Ideas?

**Comment by XinYenFon** [comment]
How much work do you think it requires ? I think its best to be done at next version.

**Comment by Gwenwyfar** [comment]
Not that much, I already want to go over all template files to fix some broken indents, I can add the tags as I do that.

**Comment by Oldiesmann** [comment]
If it's not too much work, we can do this for 2.1, otherwise 3.0. Some sort of comments (HTML or PHP, whichever works best) would definitely be useful though
