### ISSUE TITLE
Errors when going to profile > look and layout

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#4344]
Reproducible on fresh install but maybe only on fresh install.

http://localhost/smf21/index.php?action=profile;area=theme;u=1

Type of error: Undefined
8: Undefined index: display_quick_mod
8: Undefined index: messages_per_page
8: Undefined index: topics_per_page

Settings.template.php, line 1728 (as per eval)

**Comment by sbulen** [comment]
Confirmed on fresh install & upgrade.

**Comment by sbulen** [comment]
The log is confusing, but I believe the "Line 1728" is actually referring to Profile.template.php.

**Comment by Arantor** [comment]
That makes sense (yay template eval)

**Comment by sbulen** [comment]
Pretty sure it's another deleted global...

**Comment by Gwenwyfar** [comment]
I have a few of these errors in my install as well.

**Comment by sbulen** [comment]
One of the issues we have trying to debug stuff is a lot of eval'd code like templates isn't represented well in the logs.  Debuggers don't tend to like eval'd code either...  

Specific case in point - Settings.english.php is only 9 lines long. 

The actual code is Profile.template.php, Line 1728.  You might get a different line number if you are not 100% vanilla or if you are not 100% with TODAY's github version.  

I've confirmed it's not a deleted global.  (Sorry to malign you, Dr. Delete!  ;^) ) 

There was a change a couple months ago to dynamically lay out the options in that view & remove some hard-coding.  
My current theory is that that change confused a couple of theme/user specific settings with global settings.  Looking into that now.

**Comment by sbulen** [comment]
I have a PR ready that addresses the reported issue.  It simply doesn't handle unset values.

But...

What's bugging me is that the logic to hide the user settings for disabled features isn't working.  All settings are displayed, no matter what.  Looking into that now.

Pulling on threads is a nasty habit...

**Comment by sbulen** [comment]
Turns out hiding disabled settings works fine.  I was confusing some theme options with some posts/topics options...

PR #4348 submitted.
