### ISSUE TITLE
Code related to database backups

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#4350]
https://github.com/SimpleMachines/SMF2.1/blob/4bdd419a1b366e860bc9de74a01b85a533727b0d/Sources/DbExtra-mysql.php#L43

This function is related to database backups. Since 2.1 doesn't includes the option for creating backups, is it really needed there?

**Comment by frandominguezl** [comment]
`$txt['maintain_info'] = 'Optimize tables, make backups, check for errors, and prune boards with these tools.';`

Just a reminder, when fixing this, we should also change the line above, located in Admin.english.php

**Comment by Pipke** [comment]
this is used as an option when you execute the upgrade.php file
Step 2: Upgrade Options
Step 3: Backup

> 

  | Backup tables in your database with the prefix "backup_smf_". (recommended!)
-- | --
  | Put the forum into maintenance mode during upgrade. (Customize)
  | Output extra debugging information
  | Empty error log before upgrading
  | Allow Simple Machines to Collect Basic Stats Monthly.If enabled, this will allow Simple Machines to visit your site once a month to collect basic statistics. This will help us make decisions as to which configurations to optimise the software for. For more information please visit our info page.

**Comment by frandominguezl** [comment]
That's right, the db_backup_table function is used in Upgrade.php

Closing this. Thanks!
