### ISSUE TITLE
PostgreSQL cache title

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#4355]
ManageSettings.language.php should contain $txt['postgres_cache'] = 'PostgreSQL as cache'; or similar.

**Comment by albertlast** [comment]
And where should be this used?

**Comment by Arantor** [comment]
This string gets automatically picked up by the cache configuration page like all the other strings. E.g. $txt['smf_cache'].

**Comment by albertlast** [comment]
and where it is shown?
Otherwise i don't know the context..

**Comment by Arantor** [comment]
In the admin panel where you select which kind of cache you want to use.
