### ISSUE TITLE
New login issues

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4357]
I am having issues with logon/logoff functions on the current github version.  

I get the "You were unable to login.  Please check your cookie settings."  

Sometimes I get:
Fatal error: Uncaught Error: Cannot use object of type stdClass as array in \Sources\Load.php:428 Stack trace: #0 index.php(176): loadUserSettings() #1 index.php(150): smf_main() #2 {main} thrown in \Sources\Load.php on line 428

I was re-testing to make sure the fixes for the prior login issues PR worked ( #4353 ).  To reproduce, login as admin, change cookie settings (either local or global setting), log off & try to log back on.

**Comment by Sesquipedalian** [comment]
Is this still relevant now that #4353 has been reverted?

**Comment by sbulen** [comment]
No, these issues were caused by #4353.

This can be closed.
