### ISSUE TITLE
corrupt cookies doesn't get fixed

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4362]
When a mod change the cookie, an old version get the smf cookie in a different format or a bad guy,
then the cookie doesn't get fixed,
since we fix only cookies when the are not corrupted: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Auth.php#L41

Possible fix is provided in pr https://github.com/SimpleMachines/SMF2.1/pull/4358

**Comment by Sesquipedalian** [comment]
Is this still relevant now that #4353 has been reverted?

**Comment by albertlast** [comment]
Sure

**Comment by sbulen** [comment]
Do we allow mods to redefine the cookie?

**Comment by albertlast** [comment]
You can't prohibt this, because the mod can rewrite the smf code (and it's a stupid idea to do so)
