### ISSUE TITLE
Cookie will be not destroyed when you change from global to local

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4364]
Since https://github.com/SimpleMachines/SMF2.1/pull/4363 you introduce
that the cookie get not deleted when you change from global to local cookie

**Comment by sbulen** [comment]
This will be addressed by #4356

**Comment by albertlast** [comment]
And where ther?

**Comment by sbulen** [comment]
Same as in the other note:

The extra session was created because the cookie state change was not detected. Fixing the preg_match restores the cookie & session cleanup logic that was working in 2.0.
