### ISSUE TITLE
jQuery Core now v3.2.1 

### ISSUE THREAD

**Issue by tinoest** [SimpleMachines/SMF#4371]
If you're preparing for a release I would bump the jQuery to the latest version it is now at v3.2.1 

http://jquery.com/download/

I don't see any backwards incompatible changes.

**Comment by Oldiesmann** [comment]
I tested it briefly on my test board (by setting a custom jQuery URL in the admin center and pointing it to https://code.jquery.com/jquery-3.2.1.min.js) and didn't run into any issues, so this should be fine. Might want to test it a bit more thoroughly to be sure though.

**Comment by MissAllSunday** [comment]
Might be good to also take a look at all the plugins currently in use and do a an update if available.
