### ISSUE TITLE
General Error - Sub.php

### ISSUE THREAD

**Issue by Camo1x** [SimpleMachines/SMF#4372]
[![Screenshot from Gyazo](https://gyazo.com/9f4f0d036b3c9e975f336b06f4564e8c/raw)](https://gyazo.com/9f4f0d036b3c9e975f336b06f4564e8c)

https://github.com/SimpleMachines/SMF2.1/blob/b61572edff4b8ac488c462586908c80fdb3b32fd/Sources/Subs.php#L3490

Have been recently getting this error from this line apparently

**Comment by albertlast** [comment]
I think the var $time_start got something wrong,
but this only setted on two places https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/index.php#L29
and
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/SSI.php#L28
i see not possible that here you got something else als numbers.

I would guess that you got a mod or old files which are not synced/updated,
can you please look in you env where the var got setted?

**Comment by colinschoen** [comment]
Any update @camo1x

**Comment by colinschoen** [comment]
Please reopen if you have time to respond.
