### ISSUE TITLE
XSS Profile Fields

### ISSUE THREAD

**Issue by colinschoen** [SimpleMachines/SMF#4379]
HTML tags are not being sanitized from profile field values creating a stored cross site scripting vulnerability.

<img width="684" alt="screen shot 2017-11-02 at 00 28 08" src="https://user-images.githubusercontent.com/2927722/32314388-edb67484-bf64-11e7-8cf5-391c261e7534.png">
<img width="881" alt="screen shot 2017-11-02 at 00 27 56" src="https://user-images.githubusercontent.com/2927722/32314389-edd8f6a8-bf64-11e7-9417-97bdfec2a65a.png">
<img width="837" alt="screen shot 2017-11-02 at 00 27 40" src="https://user-images.githubusercontent.com/2927722/32314390-edf1586a-bf64-11e7-8abd-668c4d9dcb15.png">

**Comment by Gwenwyfar** [comment]
Could this be more specific to one set of options? I can't replicate in some tests here.

Edit: Got it. Doesn't happen when viewing the profile, but does inside topics.

**Comment by MissAllSunday** [comment]
This depends on how do you guys want to handle all the cases, no html is pretty specific but what about the other cases?

Should we add a list of "allowed tags" somewhere?  I believe I added a whitelist for the category and board descriptions, we can use that one.

**Comment by MissAllSunday** [comment]
That commit deals with the nohtml validation but it depends on the user selecting the nohtml mask option.

We can either force html stripping automatically if the "text" option is selected, regardless of whatever mask the admin selected, or completely disable HTML for all field types. Theres no middle ground or rather, a clean, effective way to sanitize user input and still offer flexibility.

**Comment by colinschoen** [comment]
^ This seems fine considering all of the other validation options are more restrictive than `NOHTML` except potentially regex, but that will be up to the user. Do you want to make a PR?

**Comment by MissAllSunday** [comment]
Yeah will do.

**Comment by Gwenwyfar** [comment]
I just noticed my test alert is still triggering inside PMs

**Comment by illori** [comment]
if you show that field on the memberlist, does the test alert show up there? 
(i have not tested it)

**Comment by Sesquipedalian** [comment]
@Gwenwyfar, is that due to an old field value left over from when you were testing this before, or are you able to enter new values to cause this now?

**Comment by Gwenwyfar** [comment]
Is the check done only upon saving then? I indeed can't re-save the old field. I suppose I was expecting it to work in the same way as the profile view does, it simply displays the code without executing. Wouldn't that be better?

@illori : No, it does the same as the main profile view in the memberlist, simply displays the code as text.

**Comment by Sesquipedalian** [comment]
> Is the check done only upon saving then? I indeed can't re-save the old field. I suppose I was expecting it to work in the same way as the profile view does, it simply displays the code without executing. Wouldn't that be better?

I don't know yet. I haven't had a chance to look at this part of the code yet. I'm trying to gather some initial information to help me focus in on the right parts of the code when I get a chance to look at it. Based on what you've said, it sounds like the following statements describe the situation. 

1. `<script>alert('test');</script>` is an old field value leftover from before #4380 was merged.
2. It is no longer possible to enter `<script>alert('test');</script>` into a profile field.
3. On some pages, including at least one of the PM-related pages, the `alert('test');` script is actually executed, whereas on other pages `<script>alert('test');</script>` is merely displayed as inert text.

Is that all correct? If so, on exactly which PM-related page is the script being executed? The inbox, or somewhere else?

**Comment by Gwenwyfar** [comment]
That's all correct. The script is executed on pages that have a PM from a member that has the code in the profile; essentially the same as the topic view problem.

**Comment by NicolasBonet** [comment]
Please check #4666 as a proposal to fix this issue, it re-allows the use of HTML-like tags for profile fields (so users could use something like `<secret>England</secret>` in a field, which is something I've seen in forums) and it also prevents XSS.

**Comment by Sesquipedalian** [comment]
Having taken a look at this again, I believe it can now be closed. It is no longer possible to embed JavaScript into profile fields. The behaviour @Gwenwyfar saw was only the result of some leftover data in her test install.
