### ISSUE TITLE
Gender Icon profile fields Multilanguage Bug

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4381]
The Gender icon  Status ist not display in other language. As an example in German.

The bug is in INPUT. 
`generic_icons gender_{INPUT}`
Input is the replacement for  None, Male or Female. But when it is translated in the admin center => Custom profile fields,  it results to  keine Angabe, Männlich oder Weiblich. 

![gender_german-1](https://user-images.githubusercontent.com/2753863/32404339-1f48ada6-c14e-11e7-8e88-70061bba5b7a.PNG)

![gender_german-2](https://user-images.githubusercontent.com/2753863/32404345-3146a0b2-c14e-11e7-98d4-f5cca3fc62f1.png)

![gender_german-3](https://user-images.githubusercontent.com/2753863/32404349-37096a3e-c14e-11e7-8f42-6ac1b3c8e99b.png)
![gender_german-4](https://user-images.githubusercontent.com/2753863/32404376-d649050a-c14e-11e7-88c4-bb262c3a823f.png)

![gender_german-5](https://user-images.githubusercontent.com/2753863/32404378-db5281f2-c14e-11e7-89f9-d78070f5d9f6.png)

Possible solution would be to change the value in index. css. But I find it to be a less than optimal solution.

=> http://www.stephan-frank.de/board/index.php/topic,12.msg24.html#msg24

**Comment by albertlast** [comment]
Like already mention from you,
you need two information:
- the orginal db value (male,femal, etc) for technical stuff like css class
- the translatet db value for displaying

So in my eyes the main issue is the missing translation function of customfields like here the gender.

Beside of {INPUT} which return the database value,
which you need in your css class (in english) you need somethinkg like {DISPLAY_INPUT} (maybe another name would be better),
which show the translation of this database value.
input "male" get than "Männlich" this information would be solve the key issue here i believe.

Maybe @Gwenwyfar could at some ideas

**Comment by wintstar** [comment]
Fix https://github.com/SimpleMachines/SMF2.1/pull/4383 works.  Good solution @MissAllSunday .

**Comment by albertlast** [comment]
please close issue only when the pr is merged (mostly they get closed)

**Comment by wintstar** [comment]
Ok, I didn't know.

**Comment by PortaMx** [comment]
I don't understand the complicated way they SMF go for this.
Why not simple put the gender (as smallint) in the members table (default 0)?
So you need not the join over other tables for all basic memberdata.

**Comment by Gwenwyfar** [comment]
If I understand it correctly, this field was changed to be a custom field, and therefore removed from the basic user data table.
