### ISSUE TITLE
total attachment size reset

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#4385]
The total attachment size var in smf_fileUpload.js doesn't get reseted when a file is canceled

Steps to reproduce:

- Set a total attachment size limit, SMF by default uses 192KB.
- Upload a file bigger than that size. for example 256KB
- Cancel the file.
- Upload another file. doesn't matter which size, as an example, 50KB

The old file is still counted towards the total size, the new file will also be added:

256 + 50

The error will display 306KB, doesn't matter if the second file surpasses the limit of not.

I remember I fixed this but looking at the file a few more changes were added so I cannot easily identify where the issue is.

![image](https://user-images.githubusercontent.com/3420756/32418773-9078bbe6-c235-11e7-9c8e-9bddeb53f7d3.png)

![image](https://user-images.githubusercontent.com/3420756/32418786-a79604c8-c235-11e7-9f24-ab0285f52ec5.png)

Edit, added some images to help identify the issue.

**Comment by sbulen** [comment]
Confirmed.    Yes, this had been working, as recently as January.

**Comment by MissAllSunday** [comment]
I'll take a look at this and the other issue. I didn't quite enjoyed working with JS back then but I do now.
