### ISSUE TITLE
total attachments amount

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#4386]
The total amount of attachments an user can upload isn't been applied.

By default SMF limits the number of attachments to 4, currently the user can keep on dragging or selecting files with no limit been applied.

The file extension check also isn't been applied, by default SMF doesn't allow .php files but I could keep added them.

![image](https://user-images.githubusercontent.com/3420756/32418818-043fad96-c236-11e7-9362-80bebaffac07.png)

![image](https://user-images.githubusercontent.com/3420756/32418820-1256b604-c236-11e7-8ee4-efe0f60dd5e3.png)

**Comment by sbulen** [comment]
Confirmed.  Both issues - extensions & counts.

Yes, this had been working earlier.

**Comment by sbulen** [comment]
Problems with those buttons, too...
