### ISSUE TITLE
Search - fulltext not allowed if db not myisam

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4387]
On a newly installed 2.1 forum, pulled up the Search Method form, and received the following prompt:
![image](https://user-images.githubusercontent.com/23568484/32673659-daef9960-c604-11e7-9cc6-e4afd2cda065.png)

Since it was a new install, the tables were innodb, and this failed the old 2.0 edit that required myisam.  

I do think InnoDB supports fulltext these days, mysql 5.6+.  I do not know if it is syntactically identical with myisam.  

So...  I think we need some experimentation to determine whether to remove the myisam restriction, or modify it somehow, to make it smarter based on the version of mysql.

**Comment by albertlast** [comment]
Duplicate to https://github.com/SimpleMachines/SMF2.1/issues/1571
i got no motivation to look into.

**Comment by illori** [comment]
we are recommending users to create a custom index, might it be easier to only leave that option along with no index?

**Comment by Oldiesmann** [comment]
While the custom index is recommended, I don't see why we can't support it on InnoDB as well, as long as it doesn't require any major changes.

Other than that we should probably hide the fulltext option if it's not supported.

**Comment by albertlast** [comment]
Why not raised the min mysql version to 5.6(and the compareable mariadb version) -> problem solve.

**Comment by Oldiesmann** [comment]
It doesn't really offer any benefit, and 5.5 is still widely used. It shouldn't be too hard to make sure we're checking the MySQL/MariaDB version before displaying that message.

**Comment by sbulen** [comment]
Looks like there was work to enhance the checks here a while back.  There is a minor problem with checking the version for innodb.  Wrapping up testing & will submit PR shortly.

**Comment by jdarwood007** [comment]
We should be getting the db type information now.  I remember extending that for the stat collection data.
