### ISSUE TITLE
e-mail sending

### ISSUE THREAD

**Issue by replikacep** [SimpleMachines/SMF#4389]
Happy Birthday e-mail sending
we are receiving spam because of this mail?
sends too many mail
The members are going to e-mail you need to set the setting to close
no option to turn on / off
So the option is not working

https://i.hizliresim.com/mJZ6YY.png

**Comment by illori** [comment]
did you disable the scheduled task?

**Comment by replikacep** [comment]
the problem is  subject can be closed

**Comment by replikacep** [comment]
rc version? very slow going
