### ISSUE TITLE
Installing theme from package doesn't work

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#4395]
When installing a new theme through the package, you are given an error: "_An error occurred while installing the theme_". No errors in the error log; multiple PHP versions were tested (5.4, 5.5, 5.6, 7.0 and 7.1).

Installing from a folder works fine. There are a couple packages in the theme site that can be tested, all of them seem to give this error.

Tests done on a live server, not localhost.

Edit: Could be related to #2995

**Comment by illori** [comment]
i have php 5.5.12 on localhost and cannot duplicate this issue.

**Comment by sbulen** [comment]
I am getting the same error on my hosted solution.

My localhost WAMP server has no such issues.

Note that Themes/temp was successfully created, but empty.

**Comment by sbulen** [comment]
There is a caught-but-not-reported exception here:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Package.php#L315

That, if reported, $e would contain something like:
`UnexpectedValueException: Cannot create phar '/tmp/phpX3O29S', file extension (or combination) not recognised or the directory does not exist in /blah/blah/public_html/VAN21/Sources/Subs-Package.php:249`

It's not liking the temp name, passed from Themes.php in InstallFile()....  I think it wants it to end in .phar?

**Comment by sbulen** [comment]
I believe Oldiesmann's original fix would work (renaming the file).   

It was reverted somehow.   Yet another regression.

**Comment by illori** [comment]
I wonder why it got reverted.

**Comment by sbulen** [comment]
There is a PR out there that specifically removed Oldiesmann's change 2 years ago.    Probably tested on Win.

I can get to this in a few days, lots of RL challenges lately.    If someone else can get to it sooner, feel free!
