### ISSUE TITLE
problem on mobile

### ISSUE THREAD

**Issue by replikacep** [SimpleMachines/SMF#4397]
telephone topics are narrowed by changing
samsung s8+

Editing reason: Last edited: Bugün, 00:32:42 Tekyürek Sebep: Edit duzenleme 

problem editing in issue is mobilde

https://i.hizliresim.com/pGpk7m.png

https://i.hizliresim.com/V31R5n.png

https://resmim.net/f/Sz0PnV.png

solve the problem : Temporary
responsive.css
@media (min-width: 720px) and (max-width: 799px) {
.keyinfo h5 .modified {display:none;}

**Comment by Gwenwyfar** [comment]
There are many smaller issues with the current responsive css. It's not worth tackling them now as the main desktop theme is not 100% yet, and the responsive file is based off it. We can go over fixing all the problems after it is.

**Comment by replikacep** [comment]
No problem  as you wish
