### ISSUE TITLE
preg_replace_callback deprecated on PHP 7.2 !!

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#4400]
The preg_replace_callback is deprecated on php 7.2 (just tested) so these needs a redesign !!
Thanks for reading this ...

Feline

**Comment by tinoest** [comment]
It doesn’t appear to be, can you please link to the location where it states it’s depreciated please

**Comment by sbulen** [comment]
Yeah, I don't see it here:
http://php.net/manual/en/migration72.deprecated.php

**Comment by colinschoen** [comment]
Agreed, this doesn't seem deprecated.

**Comment by PortaMx** [comment]
I'm so sorry .. bad look on the code ..
I mean **create_function**
also **each** is deprecated ... and mutch more.

I'm just testing on php 7.2 

Fel

**Comment by tinoest** [comment]
Each isn’t depreciated, it is in certain situations. Like a while list each

**Comment by jdarwood007** [comment]
create_function was resolved earlier.

Zeus:SMF2.1 jeremy$ grep -Rn "create_function" ./
Zeus:SMF2.1 jeremy$ grep -Rn "each(" ./ | grep -v "foreach" | grep -v "\.each"
.//Sources/Load.php:1852:				list ($k, $v) = each($_GET);

**Comment by PortaMx** [comment]
each is deprecated .. 
i tested that with a simple list($a, $b) = each(array) and get a error ..
Fel
