### ISSUE TITLE
reCAPTCHA support may not work on shared hosts

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#4406]
The reCAPTCHA implementation uses Google's off the shelf library for it - but a lot of shared hosts will have a problem with this. Using file_get_contents, even with a stream wrapper to make it a POST request - will fail on shared hosts that disallow HTTP(S) calls with file_get_contents.

Related errors in error log: Sources/ReCaptcha/RequestMethod/Post.php line 68

2: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0
2: file_get_contents(https://www.google.com/recaptcha/api/siteverify): failed to open stream: no suitable wrapper could be found

**Comment by Arantor** [comment]
FWIW the entire library can be replaced out without too much effort; it's only making a cURL POST call out to Google, and curl_fetch_web_data can handle that.

https://github.com/SockDrawer/StoryBB/pull/318 was our solution; might not want to use the exact same class names etc. but it definitely doesn't need a whole library to do what's already provided for in the core.

**Comment by live627** [comment]
I fixed this in https://github.com/SimpleMachines/SMF2.1/commit/66b62cdb7e5fae5ee1bf7a8f5b1ae0cff25e2ced
