### ISSUE TITLE
SSL certificate detection doesn't work on many shared hosts

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#4407]
Similar to #4406, ssl_cert_found relies on being able to open a stream wrapper (only this time, with a straight stream context creation rather than relying on file_get_contents)

This issues two warnings:

2: fopen(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0

2: fopen(https://example.com/): failed to open stream: no suitable wrapper could be found

What makes this doubly funny is that this is a URL that's already set to https:// in the first place...

**Comment by sbulen** [comment]
Is there an alternate technique that can't be disabled?
Or, at least, is infrequently disabled?

**Comment by tinoest** [comment]
cURL would be the alternative fallback most have that enabled

**Comment by sbulen** [comment]
PR #4429 submitted.
