### ISSUE TITLE
Merge topics can be broken

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#4408]
This is because of invalid markup under some circumstances in the merge topic template.

To reproduce: make sure you have at least one board with no topics in it.

1. Visit a topic
2. Select to merge that topic
3. From the dropdown at the top, select the board that has no topics
4. The page will refresh and the top half will confirm there are no messages - but the bottom half where you specify the topic id directly to merge to will not work because there is no <form> tag for it

**Comment by albertlast** [comment]
Step 4 looks on my side so:
![grafik](https://user-images.githubusercontent.com/1782906/34913953-69d18512-f909-11e7-9424-cd56e36d01d0.png)
Looks good to me?

**Comment by Arantor** [comment]
Now try using that bit at the bottom where you merge by topic id, and check it actually has a form tag to live in.

**Comment by albertlast** [comment]
I was hoping that is more intresting issue,
as that only the form tag is missing when the board is empty :(

**Comment by Arantor** [comment]
Sorry to disappoint, I'll see if I can find more interesting bugs for next time 😉
