### ISSUE TITLE
Cachedir empty

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#4409]
https://github.com/SimpleMachines/SMF2.1/blob/35b3d8ccee6ceb1f4b54054825e4a22b0293e01e/SSI.php#L31

Anyone know why we are unsetting the cachedir from globals?

This breaks integrations where you call Settings.php first and then call SSI.php.  Which in turns causes the caching to break because $cachedir is empty.  This only is noticed if you move the Cache directory from its default location due to Settings.php and SSI.php correcting this if it can.

**Comment by Arantor** [comment]
This is historical. $db_character_set and $cachedir didn't always exist and thus could be tainted by way of register_globals so many moons ago (even in 2.0) they were cleansed as they didn't necessarily exist.

I'd wonder why the integration is done wrong (there is no need to load Settings.php then load SSI, just load SSI)
