### ISSUE TITLE
Increase credits field

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#4414]
If a mod author wants to add a license url the length will quickly be filled.

I added that bit so kinda my responsability now 

Edit, for reference: https://www.simplemachines.org/community/index.php?topic=557815.msg3952907#msg3952907

**Comment by albertlast** [comment]
Which field(table fieldname) you mean?

**Comment by frandominguezl** [comment]
@albertlast https://www.simplemachines.org/community/index.php?topic=557815.0;topicseen

**Comment by albertlast** [comment]
and what would be reasonable size?
on pg side i could choose text which provide unlimited size...

**Comment by MissAllSunday** [comment]
yeah, text, its not used that frecuently and it also gets cached if I recall correctly.

**Comment by albertlast** [comment]
where get what cached?

**Comment by MissAllSunday** [comment]
I don't recall exactly where and I don't have a local test at hand  but the mod author credits gets cached using whatever cache system SMF is currently using, to avoid hitting the db each time someone goes to the action=credits page
