### ISSUE TITLE
Website on registration doesn't work (missing field)

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#4425]
Assuming we fix #4424, the field doesn't work anyway because the website URL part of the field is defined as a 'url' type field and doesn't get output anyway.

![image](https://user-images.githubusercontent.com/1156911/34323292-c845823c-e839-11e7-8fff-a1174cf99377.png)

**Comment by frandominguezl** [comment]
Working on a fix now for #4424 and #4425

**Comment by frandominguezl** [comment]
Alright, #4424 was an easy fix, but trying to fix this one ends up in weird stuff. If you set the field type to 'text', the field is displayed but it won't keep the website data after you register. So, something is wrong with 'url' type.

Plus, if you fail to solve the captcha, when the screen reloads, the website info is lost (while your username and email are still there).

**Comment by frandominguezl** [comment]
This can be closed @colinschoen
