### ISSUE TITLE
Housekeeping interface for Caching

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4438]
Like I mention here: https://github.com/SimpleMachines/SMF2.1/pull/4306
an "interface" where i could add some housekeeping would be nice.

For pg and sqlite i would like do a monthly/weekly(maybe the admin can choose) run where i truncate complete table.

Maybe @jdarwood007 could you add something like that?

**Comment by illori** [comment]
SMF 2.1 no longer supports sqlite.

**Comment by albertlast** [comment]
smf 2.1 support sqlite for caching. https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/CacheAPI-sqlite.php
