### ISSUE TITLE
Session 'failed to decode' messages

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4444]
Not all fields in the session are properly encoded.  This results in occasional 'failed to decode' messages.  

I believe the bug is this:  the $_SESSION['last_ss'] is populated with the contents of the last search.  When UTF8 characters are searched for, they are not properly encoded here.   The session encoding & decoding has a problem with this.  

To reproduce:  Search for any special UTF8 characters...   Try this: 'Река неслася; бедный чёлн'

This occurs in 2.1 & in 2.0 at the moment.  This even occurs if your DB is properly setup as UTF8.  

Note that everything works perfectly.  Your search works!  But this message is logged in the background & your session is destroyed & rebuilt.

**Comment by colinschoen** [comment]
Good find.

**Comment by albertlast** [comment]
I found by this description an issue in the postgresql search stuff,
but i'm not able to create any session issue by using this information.

I tested this in my mysql and pg env.
My testet scenario:
Fulltext on and off
Quick Search box and normal search window
Mysql and PostgreSQL

**Comment by sbulen** [comment]
Note from @Arantor over on SMF:

> Try changing the @ini_set('session.serialize_handler', 'php'); to @ini_set('session.serialize_handler', 'php_serialize');
> 
> Requires PHP 5.5.4

**Comment by albertlast** [comment]
Did it solve this?

**Comment by sbulen** [comment]
@albertlast - Hey, I just woke up & got my coffee!   I haven't tried it yet...   

Also, I've been doing a lot of reading first...    I suspect this will work, as most threads that discuss this setting state it will address "known problems" with session_encode with "special characters".   (Some threads suggest hijacking the session encoding algorithm altogether, as they don't think this is sufficient.  Lots of threads out there with alternative session encoding approaches...)

In hindsight, I believe this is the very reason SMF rarely stuffs content into $_SESSION at all.  So I suspect there may be a better way, one that doesn't require bumping the minimum php version.   

Still thinking...

**Comment by sbulen** [comment]
@albertlast - To reproduce, simply search for a string that has multibyte characters:
![utf8-search-issue-1](https://user-images.githubusercontent.com/23568484/34463787-068678f2-ee1c-11e7-9bde-0ac4ad383eaa.JPG)
You will then see this error in the error log:
![utf8-search-issue-2](https://user-images.githubusercontent.com/23568484/34463788-09f91364-ee1c-11e7-80e1-02b923cc9dcf.JPG)
(Note that the 2nd error listed above is actually a dump of the encoded session.   You will not see this in the error log - this is just how I chose to diagnose the issue, by dumping the session into the error log as it was destroyed.   Note that the multi-byte characters are garbled in the encoded session.)
Note these are 2.0 screenshots, but the same thing happens in 2.1.

**Comment by sbulen** [comment]
Yes, changing the session.serialize_handler to php_serialize definitely works.

Now the question is whether there is a way that doesn't require a bump in the minimum php version...

**Comment by albertlast** [comment]
Use the way how wiki does,
Try to activate when doesn't work use the old methods.
https://github.com/wikimedia/php-session-serializer/blob/master/src/Wikimedia/PhpSessionSerializer.php#L70

________________________________
Von: sbulen <notifications@github.com>
Gesendet: Sonntag, 31. Dezember 2017 21:12
An: SimpleMachines/SMF2.1
Cc: albertlast; Mention
Betreff: Re: [SimpleMachines/SMF2.1] Session 'failed to decode' messages (#4444)


Yes, changing the session.serialize_handler to php_serialize definitely works.

Now the question is whether there is a way that doesn't require a bump in the minimum php version...

**Comment by colinschoen** [comment]
`php_serialize` is available from `5.4` on. This seems like a good solution.

**Comment by albertlast** [comment]
nope from 5.5+ i tested it with gwen today

**Comment by colinschoen** [comment]
I misread 5.5.4 I see. Ok we should try to still get this working for 5.4 then.

**Comment by albertlast** [comment]
From my point of view,
when this is the fix (i don't know but it look that it even the best choice).
That this is a issue on admin side -> when he got the issue,
he had to upgrade his php version.

To make it short in my eyes is the issue fixed.

**Comment by Arantor** [comment]
Your alternative is to make sure that anything pushed into $_SESSION converts all the high byte content to entities.

**Comment by colinschoen** [comment]
I just spoke with @albertlast on IRC. I'll take the issue of getting this to work on `5.4`.

**Comment by Arantor** [comment]
https://gist.github.com/pulse00/4204440 might be of use to you; their approach is to decode the session before saving and re-encode it in their own format - you could do something similar here.

**Comment by colinschoen** [comment]
Thanks!

**Comment by albertlast** [comment]
close this issue since only one very old php is affected by this issue

**Comment by sbulen** [comment]
Even in 5.4, the search appears to work fine.  As near as I can tell there is no end-user impact.  Just an ugly message in the logs.  

I think it would be OK to remove the RC dependency.  Note this issue is outstanding in 2.0 also...  Clearly not urgent.

My overall preference would be to raise the minimum php version.  

Or, as albertlast suggests, closing this issue outright.  I'd be OK with that also.  I'll leave the decision to the dev team.

**Comment by albertlast** [comment]
@colinschoen can we close this?

**Comment by colinschoen** [comment]
Done, thanks.

**Comment by colinschoen** [comment]
Whoops, thought this was a different issue. No, this is still a valid bug. It may not need to block the RC, but ideally should be fixed if we don't up the PHP requirement.

**Comment by albertlast** [comment]
Than remove the rc1 tag please,
this issue too rar in my eyes to be in focus.

**Comment by colinschoen** [comment]
I'll leave that to @Sesquipedalian. I'll try to spend some time on this. :\

**Comment by albertlast** [comment]
in my eyes i would like to see,
that you spend your spare time on important stuff not on very rar issue like this.

**Comment by colinschoen** [comment]
I am leaning towards this not having the RC1 tag, but I will let @Sesquipedalian decide on that. I do think it is worth fixing, however. There are a nontrivial amount of installations that will encounter this bug.

**Comment by albertlast** [comment]
Since the bug exists already in smf2.0.x and i don't see many open issue on this -> the amount is low.
This bug get fixed by use of php5.5, why this issue very very very low.

**Comment by sbulen** [comment]
I suggest using the php_serialize fix specified above.  

The few remaining 5.4 users will continue to live with this bug - as they have for a very long time.  

Php 5.4 has been in serious decline in usage.  In this study it only accounts for about 1% of users today:
https://seld.be/notes/php-versions-stats-2018-1-edition

I don't know where to see our internal stats collection, but I bet 5.4 would appear in decline there as well.

**Comment by Arantor** [comment]
Takeaway quote: "almost 95% were using a PHP version that is still maintained"

5.6 ends support in a few months. 5.5 ended support in mid 2016, 5.4 ended support in summer 2015.

You honestly don't need to cater to the 1%.

**Comment by sbulen** [comment]
Since #4464 implemented the handler already, I really think this should be closed.

**Comment by NanoSector** [comment]
Is this still a valid bug?

**Comment by frandominguezl** [comment]
Better ask @colinschoen
