### ISSUE TITLE
Proxy Enhancement:  Don't serve up bots

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4448]
After enabling the proxy on my 2.0 site, I noticed CPU up 2x & bandwidth up 3x.  I believe the crux of the problem is serving up images for search bots.  

I believe we should NOT serve up images thru the proxy for suspected bots.  

We probably shouldn't be serving up these images (originating from other sites) for search engines anyway.

This impacts 2.0 & 2.1.

**Comment by Sesquipedalian** [comment]
A few well-placed `if (!empty($user_info['possibly_robot']))` statements should do the trick. Care to put together an PR for this, @sbulen?

**Comment by sbulen** [comment]
Will do.  I know SleePy already started this & I'll pick it up from there.

**Comment by sbulen** [comment]
PR #4503 submitted

**Comment by albertlast** [comment]
But this not slow down the page deliver time,
Which then hurt the ranking?

**Comment by sbulen** [comment]
Since this disables the proxy for crawlers - crawlers will actually see a pretty dramatic _improvement_ in response time.  (No waiting for the download/upload.)

I've had these changes on my production site in 2.0.15.  After I enabled the proxy on my site, Google performed a full-site recrawl (probably because they sensed the 301 redirect to https).  During the recrawl, my CPU went thru the roof & the proxy image cache grew substantially - by 1GB per day during peak crawl time.  

This change resulted in significant improvements in CPU and cache.
