### ISSUE TITLE
Gender Field

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4451]
Last Pull request: 
https://github.com/SimpleMachines/SMF2.1/pull/4445

Forum version: SMF 2.1 Beta 4 (more detailed)
Current SMF version: SMF 2.1 Beta 3
GD version: bundled (2.1.0 compatible) 
MySQLi engine: MariaDB 
MySQLi version: 10.1.25-MariaDB 
Alternative PHP Cache: 5.1.2 
PHP: 7.1.11 (more detailed) 
Server version: Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11 
Fix: 
https://github.com/SimpleMachines/SMF2.1/pull/4383

Fix not work with the new pull request today. Not by new install or update. Key is not read from the database. This field is not displayed in the post view.

![gender_2](https://user-images.githubusercontent.com/2753863/34460868-009a76f0-ee1c-11e7-89d2-ba3bfc6a0eb2.png) 

![gender_1](https://user-images.githubusercontent.com/2753863/34460869-02b49254-ee1c-11e7-879d-ecae16c1e48d.png) 

![gender_3](https://user-images.githubusercontent.com/2753863/34460870-04545914-ee1c-11e7-8743-799c0ddd503b.png) 

![gender_4](https://user-images.githubusercontent.com/2753863/34461077-cab536f0-ee21-11e7-8da2-9cea87813d63.png)

**Comment by wintstar** [comment]
It would be much easier to set this as the default field. Why the change from 2.0. *? 
It worked in all languages. 

> Never change a runing system

**Comment by albertlast** [comment]
Soi the pr got merge,
please test this again with the changes(notice that also database changes are in ther)

**Comment by wintstar** [comment]
Database was updated with upgrader. It works with the post view, not work in memberlist and not in profile view. With the default language English set in the profile, it does not work there either. There is always the problem with "KEY".

![gender_7](https://user-images.githubusercontent.com/2753863/34638816-0436458e-f2d4-11e7-8f7f-aa7e89d4d830.png) 

![gender_6](https://user-images.githubusercontent.com/2753863/34638819-0d13aa34-f2d4-11e7-8a0c-663424a17c16.png)

![gender_5](https://user-images.githubusercontent.com/2753863/34638822-14f5352e-f2d4-11e7-8e7b-a44a0eacf320.png)

**Comment by albertlast** [comment]
it doesn't solve the issue,
but @colinschoen i think you forgot to add this change frome the install also in the upgrade:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade_2-1_mysql.sql#L1027
https://github.com/SimpleMachines/SMF2.1/pull/4452/files#diff-d6f74e978f1d734a838e3b2e2336b695R2029

**Comment by wintstar** [comment]
Are there any news about this?  If this could be added to this list RC1 Checklist #4485.

**Comment by Sesquipedalian** [comment]
This bug is assigned to @colinschoen, and he is otherwise occupied at this time. When there is news about this bug, it will appear here automatically.

**Comment by colinschoen** [comment]
Thanks yeah on holiday for the next week. Will be tending to this when I get back along with a lot of other backlogged items.

**Comment by wintstar** [comment]
Thank you for your feedback.

**Comment by wintstar** [comment]
>14 Jan 
 Thanks yeah on holiday for the next week. Will be tending to this when I get back along with a lot of other backlogged items.

Are there any news about this and https://github.com/SimpleMachines/SMF2.1/pull/4452?
