### ISSUE TITLE
Installer step 5 umlauts bug

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4453]
Last Pull request:
#4445

Forum version: SMF 2.1 Beta 4 (more detailed)
Current SMF version: SMF 2.1 Beta 3
GD version: bundled (2.1.0 compatible)
MySQLi engine: MariaDB
MySQLi version: 10.1.25-MariaDB
Alternative PHP Cache: 5.1.2
PHP: 7.1.11 (more detailed)
Server version: Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11
Browser: Chrome Version 63.0.3239.108 (64-Bit)

Step 1 to 4 have the charset utf-8. But step 5 have charset ISO-8859-1.  That makes the bug with the German umlauts.  [The German language files correspond to the file encoding utf-8](http://www.stephan-frank.de/board/index.php/topic,11.0.html).

![umlauts_bug_installer](https://user-images.githubusercontent.com/2753863/34464621-ab0b9d06-ee87-11e7-85ed-32f309a723d8.png)

**Comment by albertlast** [comment]
Since the german translate didn't exists official i had to ask that you try the change directly by your side:
go to SMF2.1\Themes\default\languages\Install.german.php and edit here the
$txt['lang_character_set'] = 'ISO-8859-1';
to 
$txt['lang_character_set'] = 'UTF-8';

**Comment by wintstar** [comment]
It's not the language file. This already contains charset utf-8. If the language file was wrongly encoded, why is the bug only in step 5? And why is the charset in step 5 ISO-8859-1  and in the other steps 1-4 utf-8?

```
// These should be the same as those in index.language.php.
$txt['lang_character_set'] = 'UTF-8';
```
There is this umlauts bug only in the installer at step 5, nowhere else. Download the language pack and check it out. Download link, look at the first post.

**Comment by albertlast** [comment]
Possible issue could be that he take the english language file,
you could check this by editing the english file also and set in the index and install language file to UTF-8

**Comment by wintstar** [comment]
Yes, this fixes the bug. I have changed the character set in the index_english and install_english to utf-8.

**Comment by albertlast** [comment]
I already open a issue with the question why we use iso-8895-1 on the english language file #4454,
lets take this issue with "key" issue that somehow the used language file is changed in the middle of the road.

**Comment by albertlast** [comment]
I provided a pr with the fix,
feel free to test this.
#4457

**Comment by wintstar** [comment]
> I provided a pr with the fix,
> feel free to test this. 

 I have changed the character set in the index_english and install_english to ISO-8895-1. Your fix not work. In the header is the charset ISO-8895-1.

**Comment by albertlast** [comment]
your are 100% sure that you apply this changes to the install.php which is directly in your root and not this one in the "other" dictory?

**Comment by wintstar** [comment]
I made the change as in their fix 

```
	// And now include the actual language file itself.
	require_once(dirname(__FILE__) . '/Themes/default/languages/' . $_SESSION['installer_temp_lang']);

	// Which language we load? And also assume that he like his language.
	preg_match('~^Install\.(.+[^-utf8])\.php$~', $_SESSION['installer_temp_lang'], $matches);
	$user_info['language'] = $matches[1];
}
```

**Comment by albertlast** [comment]
I assume that your want to say with the close that the fix is working,
this is nice.
But please keep the issue open until the pr is merged (it's get closed automaticly)

**Comment by wintstar** [comment]
Sorry was a false click. Is not fix. 
I accidentally closed.

**Comment by albertlast** [comment]
Okay forgot to apply the changes to the global to install file in the other dict...
The pr is updated.

**Comment by wintstar** [comment]
Now the fix https://github.com/SimpleMachines/SMF2.1/pull/4457  works. Bug solved. Thanks.
