### ISSUE TITLE
ISO-8895-1 in install and index.english.php

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4454]
i had to ask if ther any reason why we got in
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/languages/index.english.php#L19
and
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/languages/Install.english.php#L5
ISO-8895-1 instead of UTF-8?

**Comment by sbulen** [comment]
I recall being told that this was necessary for the Language Editor.   I tried changing this once earlier myself.  I cannot find the earlier thread.   

@Oldiesmann ?   Does this sound familiar?

**Comment by sbulen** [comment]
Found the old thread, it was in the discussion for PR #3948 .  I was asked to change it back to ISO-8859-1 by Antes , due to Language Editor behavior.  

@Antes - sound familiar?

**Comment by albertlast** [comment]
because the install.english.php used iso-8895-1 we got in the header of the install the charset iso-8895-1,
which looks very bad in my point of view.

**Comment by wintstar** [comment]
> because the install.english.php used iso-8895-1 we got in the header of the install the charset iso-8895-1,
> which looks very bad in my point of view.

But only in step 5. Look in https://github.com/SimpleMachines/SMF2.1/issues/4453

**Comment by albertlast** [comment]
It's a happy "accident" that we detect yours because this issue exists.
But the complet setup process in english is used iso-8895-1 when you install in english.

So this issue is not related to yours.

**Comment by XinYenFon** [comment]
@sbulen yeap, but if I remember well, when that PR created SMF 2.1 was not UTF8 only, it is now so yes default files needs to be UTF8 as well.
