### ISSUE TITLE
Profile Fields Values not Persisted on Registration w/ Errors

### ISSUE THREAD

**Issue by colinschoen** [SimpleMachines/SMF#4456]
When profile fields that `$_POST` to different name/s than the `registration_fields` key their value is not persisted through registration form submissions with errors. 

An example is the `Website` profile field which when enabled to `Show on Registration` is actually two form inputs: `Website title`, `Website URL`. These inputs $_POST to `website_title` and `website_url` respectively which don't match the key in `registration_fields`. Perhaps we need to store the names of all inputs for each `Profile Field` and check for those [here](https://github.com/SimpleMachines/SMF2.1/blob/ae07c3e0b8b0285414af2364330e6a2253af9b4a/Sources/Register.php#L170)

**Comment by colinschoen** [comment]
@d3vcho Want to take a stab?

**Comment by frandominguezl** [comment]
I think this is going to be a little bit more difficult for me, but I will try anyway 👍
