### ISSUE TITLE
Language selection looks not good?

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4458]
Well im not the best guy about good looking gui...
but when you install a second language and you got the language choose pulldown input.
It's looks for me a little bit out of place/compress:
![grafik](https://user-images.githubusercontent.com/1782906/34466876-908591d4-eee2-11e7-91ab-7b10f3b86b41.png)

Could @Antes or @Gwenwyfar give up a comment if it should be this way?

Default behavior:
![grafik](https://user-images.githubusercontent.com/1782906/34466896-1fa5be02-eee3-11e7-8341-6ceca5108802.png)

**Comment by Gwenwyfar** [comment]
I'll look into it.

**Comment by XinYenFon** [comment]
the language selector is fine, the problem is search button is looking weird, I know why its happening I just need to know if my change effecting anything else.
