### ISSUE TITLE
Weird displaying in Register

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#4462]
After enabling Timezone field to show in register, this is how it displays:

![](https://i.gyazo.com/3bed0acdbce42884e2113be165d229f2.png)

**Comment by colinschoen** [comment]
You are specifically referring to the (Forum default) text correct?

**Comment by frandominguezl** [comment]
Yup I mean, the theming looks wrong there with that scroll bar down there.

**Comment by colinschoen** [comment]
Oh not the text but the size of the select.

**Comment by frandominguezl** [comment]
Yes, that's it. Should be an easy fix, though

**Comment by Gwenwyfar** [comment]
Inputs having fun in being a pain as usual. Options text content can't wrap, and we have one selection that is very long. Need to find a solution around that. I think we can just constrain the select size, since the options size can and will be larger than the select box regardless.

**Comment by XinYenFon** [comment]
I can't reproduce this issue on my laptop & 1080p screen (27'')

**Comment by frandominguezl** [comment]
@Antes Which browser are you using? In case you weren't using FireFox, can you try?

**Comment by XinYenFon** [comment]
I'm using Firefox 58B13 (64bit), tested on MS-Edge, IE11, Chrome 63 as well.

**Comment by frandominguezl** [comment]
It happens for me both in FireFox 57.0.3 (64-bit) and in Chrome 63

**Comment by XinYenFon** [comment]
I don't see anything weird on page-load or any extra ID to interfere with this...  Does the list has anything weirdly long ?

**Comment by frandominguezl** [comment]
It has some longer items, but manually reducing the width of that select box to 50% works good and none of the items gets truncated or something like that.

**Comment by Gwenwyfar** [comment]
UTC +4 text is overly long and is what is causing this in english, since we don't define a size for the select (not sure if we translate the time format strings or not, could be why it doesn't happen for you)
