### ISSUE TITLE
upgrade.php hardcoded text

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4465]
During the upgrade process there is no possibility to translate the text in some steps, because it is hardcoded.

Here are just a few:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L218
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L939

Another problem is that other language files are not loaded in all steps.

**Comment by albertlast** [comment]
I'm not fully understand what you mean with: "other language files are not loaded."

**Comment by wintstar** [comment]
![upgrade-1](https://user-images.githubusercontent.com/2753863/34480160-1a4764c4-efab-11e7-9a03-9358cb0a41a2.PNG)  

![upgrade-2](https://user-images.githubusercontent.com/2753863/34480173-2916505a-efab-11e7-89bf-6a8269c6a442.PNG) 

![upgrade-3](https://user-images.githubusercontent.com/2753863/34480182-336a2dba-efab-11e7-8b1d-abc9b13672ad.PNG)

![upgrade-4](https://user-images.githubusercontent.com/2753863/34480248-8e600938-efab-11e7-83d0-9786b24bf1aa.PNG) 

![upgrade-5](https://user-images.githubusercontent.com/2753863/34480252-97916830-efab-11e7-8db0-f60917b9116b.PNG)

![upgrade-6](https://user-images.githubusercontent.com/2753863/34480295-ce767c14-efab-11e7-92c1-f8cab35afba4.PNG)

**Comment by albertlast** [comment]
Well on my side the upgrader start in german,
what language stand in you settings.php?
look at $language

**Comment by frandominguezl** [comment]
@albertlast Looks like he has the upgrade.php in German, but not every word is translated on it.
For example, see "Fortschritte" and right below the steps in English.

**Comment by albertlast** [comment]
You need to look different on the pic.
You see that the first pic's are in english fully and
the others are partly in german.
The intresting part for me is,
why are the first steps in english (in my test env) the first page is already in german.

**Comment by wintstar** [comment]
> Well on my side the upgrader start in german,
> what language stand in you settings.php?
> look at $language

Yes is english. But if the default language in the admin center is German. Should not standing german in the Settings.php file?
In the Admin Center is German set as default language.

**Comment by albertlast** [comment]
Dunno,
but so long in the settings.php stand english the upgrade is done in english,
why it switch in the middle of the road would be intressting to know.

**Comment by wintstar** [comment]
I don't have an explanation. According to my overview in the upgrade.php file, a language package is not defined. As it was changed yesterday in install. php. Maybe it's xampp? This is the basis of my test environment.

**Comment by albertlast** [comment]
The upgrade use the install language file see: 
https://github.com/SimpleMachines/SMF2.1/blob/db4ee69624e40c1b83c518d2a5b91e0009fa70d9/other/upgrade.php#L235-L237

**Comment by wintstar** [comment]
I know that the install language file is used for the upgrade process. I have completely retranslated the language package for German. But I didn't see that in upgrade.php.

**Comment by albertlast** [comment]
Did you not mention that in settings.php stand english? change it to german and you see the translation.

**Comment by wintstar** [comment]
Yes, I realize that. Should this entry in the setting file not be automatically updated if the German language package is installed and set as default in the Admin Center?

**Comment by wintstar** [comment]
I have now german setting in the Settings.php file. 
`$language = 'german';`

However, some texts are not stored with language strings It is not only these
https://github.com/SimpleMachines/SMF2.1/blob/0c3a4e9a03e040c1f0d0d4855cb9db79004b339d/other/upgrade.php#L86-L92 

- Login
- Upgrade Options
- Backup
- Database Changes
- Convert to UTF-8
- Convert serialized strings to JSON
- Delete Upgrade.php

_For security purposes please login with your admin account to proceed with the upgrade._
https://github.com/SimpleMachines/SMF2.1/blob/0c3a4e9a03e040c1f0d0d4855cb9db79004b339d/other/upgrade.php#L3653

![upgrade-7](https://user-images.githubusercontent.com/2753863/34494552-5f06de78-eff1-11e7-8aa8-35065368418f.PNG)

**Comment by frandominguezl** [comment]
Yup, there are definitely some hardcoded text strings over there. I don't think it's going to be too difficult to convert them to true $txt strings. I'll give it a go as soon as I can :)

**Comment by frandominguezl** [comment]
Now working on this.

**Comment by wintstar** [comment]
Thanks :) 
Will update my German translation and give feedback.
