### ISSUE TITLE
Error with Forcing SSL

### ISSUE THREAD

**Issue by Sefank** [SimpleMachines/SMF#4473]
After I installed SMF (using version 3b2b583), I tried to visit the index page but failed.
![image](https://user-images.githubusercontent.com/12670778/34636635-14675666-f2e1-11e7-9458-48c63a507580.png)
I enabled the HTTPS service but it still said "You can only login via HTTPS".
It's really confusing.
BTW the environment I'm using is as follows.
Virtual Host(Linux), Nginx, MySQL 5.5.35, PHP 7.0
Any things I can help?

**Comment by albertlast** [comment]
Can you go to your smf_settings table,
copy the value of the key tld_regex here in the issue?

Could it be that you server got a own https proxy in front of you webserver?
Because your issue should came from:
https://github.com/SimpleMachines/SMF2.1/blob/89e0b80dd68e5cfdf1e5d1505e77dcad0d45de38/Sources/Load.php#L1840-L1851
And the code check if your force ssl and ask the webserver if the connection is ssl,
your webserver could say "no" when a proxy in front of do the ssl stuff.
And i beliefe your webserver say no...
Please place the code on you webserver(empty php file) and call it by using https:
```
 <?php
 echo $_SERVER['HTTPS'];
```
And tell me the output.

**Comment by sbulen** [comment]
I've seen this before...  I believe this happens when there is no redirect, but force_ssl = 2 and you type in http in your url (or http is in your browser memory, so your browser is specifying http...)

**Comment by albertlast** [comment]
nope you can call his side and see directly the issue.

**Comment by sbulen** [comment]
I've seen it pretty frequently, without the proxy.  And you are correct, the  $server [https] is no.   I believe it can happen whenever force_ssl =2 , but you aren't https (eg., no redirect) when logging on

**Comment by albertlast** [comment]
I'm not fully understand your comment,
but this what i mean: https://stackoverflow.com/questions/1175096/how-to-find-out-if-youre-using-https-without-serverhttps

And this could be a valid solution:
```
$isSecure = false;
if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
    $isSecure = true;
}
elseif (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' || !empty($_SERVER['HTTP_X_FORWARDED_SSL']) && $_SERVER['HTTP_X_FORWARDED_SSL'] == 'on') {
    $isSecure = true;
}
$REQUEST_PROTOCOL = $isSecure ? 'https' : 'http';
```

**Comment by albertlast** [comment]
Please try the fix from the pr #4474 ,
maybe it's solve your issue.

**Comment by Sefank** [comment]
@albertlast 
I can't find the key tld_regex in smf_settings table,
And the output of your code is as follows.

> Notice: Undefined index: HTTPS in /home/bae/app/testt.php on line 2

(testt.php is the php file name.)

**Comment by tinoest** [comment]
Change the isset to !empty for the first of check and try again.

**Comment by albertlast** [comment]
is not needed.
Please try the fix from the pr.

**Comment by Sefank** [comment]
Erh, I tried the fix but during the reinstallation process, I got into trouble when going to Step 3.
The error looks like:

> Fatal error: Uncaught Error: Call to undefined function httpsOn() in /home/bae/app/install.php:935 Stack trace: #0 /home/bae/app/install.php(131): ForumSettings() \#1 {main} thrown in /home/bae/app/install.php on line 935

**Comment by albertlast** [comment]
i was not sure if the function is ther when i write to the subs or not,
your error awnser the question.
this fix the error:
https://github.com/SimpleMachines/SMF2.1/pull/4474/commits/cf189bfc5a0cdecfa06692c25c7e96c60c6ad273

**Comment by Sefank** [comment]
I've tried cf189bf but when Step 3 I submited the database info, the web browser gave me a "Confirm the submission of the form" dialog. No matter I chose "Continue" or “Cancel”, it then gave me a blank page.
The page source may help.
```
<html>
	<head></head>
	<body>
		<div style="position: static; width: 0px; height: 0px; border: none; padding: 0px; margin: 0px;">
			<div id="trans-tooltip">
				<div id="tip-left-top" style="background: url(&quot;chrome-extension://ikkepelhgbcgmhhmcmpfkjmchccjblkd/imgs/map/tip-left-top.png&quot;);"></div>
				<div id="tip-top" style="background: url(&quot;chrome-extension://ikkepelhgbcgmhhmcmpfkjmchccjblkd/imgs/map/tip-top.png&quot;) repeat-x;"></div>
				<div id="tip-right-top" style="background: url(&quot;chrome-extension://ikkepelhgbcgmhhmcmpfkjmchccjblkd/imgs/map/tip-right-top.png&quot;);"></div>
				<div id="tip-right" style="background: url(&quot;chrome-extension://ikkepelhgbcgmhhmcmpfkjmchccjblkd/imgs/map/tip-right.png&quot;) repeat-y;"></div>
				<div id="tip-right-bottom" style="background: url(&quot;chrome-extension://ikkepelhgbcgmhhmcmpfkjmchccjblkd/imgs/map/tip-right-bottom.png&quot;);"></div>
				<div id="tip-bottom" style="background: url(&quot;chrome-extension://ikkepelhgbcgmhhmcmpfkjmchccjblkd/imgs/map/tip-bottom.png&quot;) repeat-x;"></div>
				<div id="tip-left-bottom" style="background: url(&quot;chrome-extension://ikkepelhgbcgmhhmcmpfkjmchccjblkd/imgs/map/tip-left-bottom.png&quot;);"></div>
				<div id="tip-left" style="background: url(&quot;chrome-extension://ikkepelhgbcgmhhmcmpfkjmchccjblkd/imgs/map/tip-left.png&quot;);"></div>
				<div id="trans-content"></div>
			</div>
			<div id="tip-arrow-bottom" style="background: url(&quot;chrome-extension://ikkepelhgbcgmhhmcmpfkjmchccjblkd/imgs/map/tip-arrow-bottom.png&quot;);"></div>
			<div id="tip-arrow-top" style="background: url(&quot;chrome-extension://ikkepelhgbcgmhhmcmpfkjmchccjblkd/imgs/map/tip-arrow-top.png&quot;);"></div>
		</div>
	</body>
</html>
```
PS1: Before I did all these, I have clean the temp and cookies.
PS2: It seems that the souce won't help... :D

**Comment by albertlast** [comment]
I change the last commit,
revert the function and place the logic direclty in the code.
And testet the install in non https env(works now):
https://github.com/SimpleMachines/SMF2.1/pull/4474/commits/e11f96e6220f29b24aef6fbf610f5415683641ee
try this changes.

**Comment by Sefank** [comment]
@albertlast Great it WORKS! Very appreciated!

**Comment by albertlast** [comment]
Don't close the issue,
the issue should get closed when the pr is merged.
