### ISSUE TITLE
HTML in text strings

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#4479]
In some text strings of Install.php (under Install.language.php) there's HTML inside them which can mislead some translator. 

I wanted to make a separate issue and do a different Pull Request for those strings. I might check as well the rest of the language files to see if there's HTML on some strings as well.

**Comment by Gwenwyfar** [comment]
There is html in a lot of the strings. Not sure there's any easy way outside that unless you make changes in every template using them and split all the strings. Would we even want that?

**Comment by frandominguezl** [comment]
Not sure. If I'm gonna make it for the text strings I introduce in #4470 then I don't know why I wouldn't do that for the rest. It could be a lot, yes, but if it's better to use sprintf for those strings, then it's okay for me.

Would like to hear some feedback from the devs.

**Comment by Gwenwyfar** [comment]
I think for example this one: `$txt['force_ssl_info']` is the kind we don't want to see anywhere. Definitely we should get rid of all those.

But then we have a lot of things like `$txt['upgrade_bypass']` and `$txt['ftp_path_info']`, in which I think it is perfectly valid to have `<em>` and `<strong>` inside the strings. How would you do that otherwise without simply replacing it with another kind of markup?

There were a few discussions on this on other issues, not sure if they're still open.

**Comment by frandominguezl** [comment]
In the examples listed in #4470 there are some URLs inside some text strings, I'd be great if we could remove those. And in some cases like the one you mentioned, strong could be removed too. When not the full string is inside strong or em or anyother tag, we don't have any choice.

**Comment by Sesquipedalian** [comment]
I approve of these plans.

**Comment by Gwenwyfar** [comment]
@Sesquipedalian just checking, you read all comments right?

I still don't see what's wrong with highlighting specific words/parts when needed.

**Comment by Sesquipedalian** [comment]
I meant that this sounds the right plan to me:

> In the examples listed in #4470 there are some URLs inside some text strings, I'd be great if we could remove those. And in some cases like the one you mentioned, strong could be removed too. When not the full string is inside strong or em or anyother tag, we don't have any choice.

When there are HTML tags embedded within the string in ways that cannot easily be changed, they'll just need to stay as they are. But when, e.g., the entire string is wrapped in a &lt;strong>&lt;/strong>, the tags should be removed from the string and put into the template files.

As for the embedded URLs, those should be inserted into the string at runtime using sprintf. Although it is unlikely that the URLs in the strings in #4470 are going to change anytime soon, they could, and if they do coders would normally expect to implement those changes in the source files, not the language files.

**Comment by Gwenwyfar** [comment]
Oh okay. That sounds like a plan. Thanks for the clarification :)

**Comment by frandominguezl** [comment]
https://github.com/SimpleMachines/SMF2.1/blob/384945c1aac5b8e99d446f84db5dd5d0961fbd4b/Themes/default/languages/ManageSettings.english.php#L370

What should we do with strings like that? I think there are a few. That one refers to:
https://github.com/SimpleMachines/SMF2.1/blob/384945c1aac5b8e99d446f84db5dd5d0961fbd4b/Themes/default/ManageLanguages.template.php#L59

**Comment by Gwenwyfar** [comment]
I don't see anything wrong with those. The alternative is making them boring plain text. Same for the lists, but maybe we can drop the "normallist" class from them, I'll have to check.

**Comment by MissAllSunday** [comment]
@frandominguez03 Do you still see this as a feasible thing to do? if so, we can tag it for Final.

**Comment by frandominguezl** [comment]
Ah, thanks for answering. I was about to leave my opinion on this one so we close more Language issues but forgot about it. Anyway, last time I checked there weren't too many HTML inside text strings but I'd have to double check how many strings does have HTML in them and if it's possible to remove it.

I will do it tomorrow, so I will mention you here then with my point of view.

**Comment by SychO9** [comment]
Here is a list of strings we could definitely remove the html code from, I am unsure about other special cases.

**Search `^\$txt\['[^']*'\] = '<[^'<]*<\/[^>]*>';` (26 hits in 8 files)**
```php
  ..\Themes\default\languages\ManageMaintenance.english.php (1 hit)
	Line 123: $txt['errortype_critical'] = '<span class="red">Critical</span>';
  ..\Themes\default\languages\ManageSettings.english.php (6 hits)
	Line 118: $txt['detected_no_caching'] = '<strong class="alert">SMF has not been able to detect a compatible accelerator on your server. File based caching can be used instead.</strong>';
	Line 119: $txt['detected_accelerators'] = '<strong class="success">SMF has detected the following accelerators: %1$s</strong>';
	Line 156: $txt['loadavg_disabled_windows'] = '<span class="error">Load balancing support is not available on Windows.</span>';
	Line 157: $txt['loadavg_disabled_osx'] = '<span class="error">Load balancing support is not available on OS:X.</span>';
	Line 158: $txt['loadavg_disabled_conf'] = '<span class="error">Load balancing support is disabled by your host configuration.</span>';
	Line 208: $txt['setup_verification_questions_desc'] = '<span class="smalltext">If you want users to answer verification questions in order to stop spam bots, you should setup a number of questions in the table below. You should choose questions which relate to the subject of your forum. Genuine users will be able to answer these questions, while spam bots will not. Answers are not case sensitive. You may use BBC in the questions for formatting. To remove a question simply delete the contents of that line.</span>';
  ..\Themes\default\languages\Modlog.english.php (2 hits)
	Line 44: $txt['modlog_id'] = '<em>Deleted - ID:%1$d</em>';
	Line 90: $txt['modlog_parameter_guest'] = '<em>Guest</em>';
  ..\Themes\default\languages\Packages.english.php (8 hits)
	Line 127: $txt['package_action_missing'] = '<strong class="error">File not found</strong>';
	Line 128: $txt['package_action_error'] = '<strong class="error">Modification parse error</strong>';
	Line 129: $txt['package_action_failure'] = '<strong class="error">Test failed</strong>';
	Line 130: $txt['package_action_success'] = '<strong>Test successful</strong>';
	Line 131: $txt['package_action_skipping'] = '<strong>Skipping file</strong>';
	Line 260: $txt['package_restore_permissions_action_skipped'] = '<em>Skipped</em>';
	Line 261: $txt['package_restore_permissions_action_success'] = '<span class="success">Success</span>';
	Line 262: $txt['package_restore_permissions_action_failure'] = '<span class="error">Failed</span>';
  ..\Themes\default\languages\PersonalMessage.english.php (3 hits)
	Line 190: $txt['pm_readable_and'] = '<em>and</em>';
	Line 191: $txt['pm_readable_or'] = '<em>or</em>';
	Line 201: $txt['pm_readable_then'] = '<strong>then</strong>';
  ..\Themes\default\languages\Post.english.php (1 hit)
	Line 179: $txt['attached_files_in_session'] = '<em>The above underlined file(s) have been uploaded but will not be attached to this post until it is submitted.</em>';
  ..\Themes\default\languages\Who.english.php (2 hits)
	Line 6: $txt['who_hidden'] = '<em>Nothing, or nothing you can see...</em>';
	Line 10: $txt['who_unknown'] = '<em>Unknown Action</em>';
```

**Comment by MissAllSunday** [comment]
Lets do it then, just be careful when searching for string usage since there are times the exact key isn't used.

**Comment by frandominguezl** [comment]
Thank you! I'll do it when I have a spot (maybe tomorrow). Do you want me to start a new PR or can I add it to #5778?

**Comment by MissAllSunday** [comment]
Awesome, thanks!

Let's do it in another PR to keep things more organized => one issue, one PR.

**Comment by frandominguezl** [comment]
As I suspected, almost every string listed by SychO is called from Source files, and probably later called by foreach loops in the template files. All of them but the ones listed in PersonalMessages.english.php

I will submit a PR for those 3. As for the rest, I believe it's too much effort to manipulate them in the foreach loops.

**Comment by SychO9** [comment]
@MissAllSunday is it okay to wrap the html tags around the text strings in the source files ? for the strings which are dynamically used, this for example
```php
	// Wrapping HTML around text strings
	$txt['package_action_missing'] = '<strong class="error">' . $txt['package_action_missing'] . '</strong>';
	$txt['package_action_error'] = '<strong class="error">' . $txt['package_action_error'] . '</strong>';
	$txt['package_action_failure'] = '<strong class="error">' . $txt['package_action_failure'] . '</strong>';
	$txt['package_action_success'] = '<strong>' . $txt['package_action_success'] . '</strong>';
	$txt['package_action_skipping'] = '<strong>' . $txt['package_action_skipping'] . '</strong>';
```

If so I can push changes directly to @frandominguez03 's branch which is in a Pull Request.

**Comment by frandominguezl** [comment]
I don't remember about those particular ones but it would make sense to do so, but we gotta be careful because `_success` and `_skipping` doest **not** make use of `class="error"`

**Comment by MissAllSunday** [comment]
I prefer HTML to be moved to template files but I reckon that's not always possible.

@SychO9 regarding the example you posted, all of them are used for the "description" key in some $actions array for themes and packages right?

if so, we can add another key, something like 'css_class' => 'error' and use that to let the template know this particular txt string needs some special css class.

But overall, if it is too much trouble to change them or if it requires too much changes on the code itself, them leave them as it is.

**Comment by frandominguezl** [comment]
@MissAllSunday Please take a look at what SychO proposed in my branch: https://github.com/frandominguez03/SMF2.1/pull/1/files

I'm not sure I would like to include HTML directly into the Source files.

**Comment by SychO9** [comment]
> I prefer HTML to be moved to template files but I reckon that's not always possible.

I do too, but some might be tedious to do

> if so, we can add another key, something like 'css_class' => 'error' and use that to let the template know this particular txt string needs some special css class.

good catch, I actually didn't even need to add a new key, I just made use of the 'failed' key to add an `error` class, at least those strings are now clean and the html is in the templates
