### ISSUE TITLE
Version emulation warnings

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#4482]
Doesn't look like this should be intended behavior:

![emulation](https://user-images.githubusercontent.com/28991853/34824977-c83af9f2-f6b7-11e7-8d79-3506530d0b2e.png)

(This was running emulation for 2.0.14, 2.0.15 is not on the list yet)

**Comment by illori** [comment]
that even happens in SMF 2.0 as it shows to the "files" that you are using a different version and a patch is available. i dont know if we can really fix this.

**Comment by Sesquipedalian** [comment]
That's expected behaviour.
