### ISSUE TITLE
Need to implement "Some User search Bugs" fix from 2.0.15 patch

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#4500]
It looks like some of the code from this bug fix has been implemented in 2.1, but not all of it.

@colinschoen, since (IIRC) you came up with that fix in the 2.0.15 patch, it might be best if you take point on this.

**Comment by albertlast** [comment]
Worst issue descption ever,
can you somehow descrip what issue are ther?

To make clear my toughts,
unclean desciption + rate this as rc1 dependend.
Which in my eyes is not important for rc1.

**Comment by illori** [comment]
this is a change that was made in the SMF 2.0.15 patch that HAS to be included in SMF 2.1.

**Comment by Sesquipedalian** [comment]
It's a good enough description to allow @colinschoen to know what he needs to do, and he is the one who ought to do it. The only reason I filed this report was to serve as a reminder to him once he returns from his vacation. You can feel free to ignore this one, @albertlast.

**Comment by albertlast** [comment]
Since you tag this as rc1,
i can't ignore.
Because rc1 tag mean "needs to be fixed asap".
For something which "needs to be fixed asap" it need to be such a kind:
- security issue
- issue affected every user on every visit
- the board can be get destroyed
- kitty die when it keep

The the person how had the spare time had to fix it.

**Comment by colinschoen** [comment]
I’ll take care of this one. No worries.

**Comment by Sesquipedalian** [comment]
@colinschoen has already written the code that we need for this, @albertlast. He just forgot to add it to 2.1 when he added it to 2.0.15, so I made this to remind him. It would have been a waste of your time to develop another fix for this bug when we already have one.
