### ISSUE TITLE
Function create_function() is deprecated in Sources/Load.php on line 220

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#4524]
Hello,

such warning is show when SMF 2.0.15 has been installed on server with PHP 7.2.1. Log files are growing very fast. 

> [31-Jan-2018 13:12:00 Europe/Warsaw] PHP Deprecated:  Function create_function() is deprecated in Sources/Load.php on line 178
> [31-Jan-2018 13:12:00 Europe/Warsaw] PHP Deprecated:  Function create_function() is deprecated in Sources/Load.php on line 183
> [31-Jan-2018 13:12:00 Europe/Warsaw] PHP Deprecated:  Function create_function() is deprecated in Sources/Load.php on line 184
> [31-Jan-2018 13:12:00 Europe/Warsaw] PHP Deprecated:  Function create_function() is deprecated in Sources/Load.php on line 220
> [31-Jan-2018 13:12:00 Europe/Warsaw] PHP Deprecated:  Function create_function() is deprecated in Sources/Load.php on line 223
> [31-Jan-2018 13:12:00 Europe/Warsaw] PHP Deprecated:  Function create_function() is deprecated in Sources/Load.php on line 235
> [31-Jan-2018 13:12:00 Europe/Warsaw] PHP Deprecated:  Function create_function() is deprecated in Sources/Load.php on line 250
> [31-Jan-2018 13:12:00 Europe/Warsaw] PHP Deprecated:  Function create_function() is deprecated in Sources/Load.php on line 252
> [31-Jan-2018 13:12:00 Europe/Warsaw] PHP Deprecated:  Function create_function() is deprecated in Sources/Load.php on line 257
> [31-Jan-2018 13:12:00 Europe/Warsaw] PHP Deprecated:  Function create_function() is deprecated in Sources/Load.php on line 268
> [31-Jan-2018 13:12:00 Europe/Warsaw] PHP Deprecated:  Function create_function() is deprecated in Sources/Load.php on line 270
> [31-Jan-2018 13:12:00 Europe/Warsaw] PHP Deprecated:  Function create_function() is deprecated in Sources/Load.php on line 273

**Comment by frandominguezl** [comment]
Hello, that's because the create_function() got deprecated for PHP 7.2
Easiest solution is to downgrade your PHP version.

Also, this is not the best place to post that since is the repo for 2.1 Development, and that issue is about 2.0.x

**Comment by illori** [comment]
since this is an SMF 2.0 issue i am closing this.
