### ISSUE TITLE
Board themes not working properly

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#4525]
Per report here: https://www.simplemachines.org/community/index.php?topic=558121.0

> SMF offers the option to set a theme by board, and not force it on anyone who has a specific theme selected.
For this to work, the user needs to have the "Forum or Board Default" theme option selected in their profile.
For an admin user, this does not work, and so an admin is unable to see the board specific themes without forcing them for everyone.

**Comment by albertlast** [comment]
Was not able with php 7.2 in mysql/pg env to reproduce the error.
As second theme I used lunarfall

**Comment by Gwenwyfar** [comment]
In my tests I could not make it work for logged in users at all. It does display the right theme for guests however. Tested both php 7.2 and 5.5 with mysql on a live server.

**Comment by Gwenwyfar** [comment]
Just uploaded the PRs from the last ~2 weeks. Apparently something in them has fixed the issue. I'm closing this.

**Comment by Gwenwyfar** [comment]
So apparently, using the "Forum or Board default" selection in profile theme settings saves 1 instead of 0. Modifying the value directly on the DB makes it work properly.

What is weird is that unlike the posted issue, themes don't work even with "Override Member's Theme" checked, on neither of my 2 accounts (and one is a normal user account), so it may be two bugs.
