### ISSUE TITLE
Undefined variable: firstIndex

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4531]
Version Information:
Forum version: SMF 2.1 Beta 4 (more detailed)
Current SMF version: SMF 2.1 Beta 3
GD version: bundled (2.1.0 compatible)
MySQLi engine: MySQL
MySQLi version: 5.6.26
Alternative PHP Cache: 5.1.2
PHP: 7.1.10 (more detailed)
Server version: Apache/2.4.28 (Win32) OpenSSL/1.0.2l PHP/7.1.10

Upgrade with Pull Request #4526 

>  Franky
>  Today at 13:40
>  ::1  f84c511352d0e03394e642e70d194371
>  Type of error: Undefined
> 8: Undefined variable: firstIndex
> http://localhost/smfbeta/index.php?topic=17.0
> File: C:/xampp/htdocs/smfbeta/Sources/Display.php
> Line: 1213

If I reverse this change there is no error message https://github.com/SimpleMachines/SMF2.1/pull/4522/commits/b29f32be604d9f076f8bfd52e51b84da0caf40d5

**Comment by Gwenwyfar** [comment]
It shouldn't have been merged without discussion really... So yeah, someone needs to update the upgrader now.

**Comment by wintstar** [comment]
@Gwenwyfar, this has nothing to do with Release 4526, it is related to Release https://github.com/SimpleMachines/SMF2.1/pull/4522. I just want to inform you that I downloaded the last Pull Request, in this case 4526.

**Comment by wintstar** [comment]
> Update the upgrade for smileys fixes #4531 #4532 

This issue have not todo with broken Smileys. So i think.
