### ISSUE TITLE
Quoting messages with embedded attachments results in buggy, inconsistent output

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#4538]
There seems to be something buggy with the security checks when using the [attach] BBCode. Specifically, if the a post author inserts `[attach name=image.jpg type=image/jpeg]131[/attach]` into her post when attachment 131 is not actually attached to her post, things get a little weird.

The logic in `parseAttachBBC()` doesn't see anything wrong with a post including an attachment from another post, and so it returns some nicely formatted data to insert the image in the final output. But then the call to retrieve the actual image file (via an `?action=dlattach` request) may or may not succeed, depending on the reader's permissions. The admin and moderators will see the image embedded into the post, but other users will see a broken image placeholder. This is because for the other users, the `?action=dlattach` request ends up receiving the `HTTP/1.1 403 Forbidden` header [here](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Load.php#L1030).

Now, it is good that retrieving the image fails, because otherwise we would be allowing anyone to view any attachment regardless of their permissions, so we don't want to get rid of the permission checks involved with that. **But** this also means that if someone tries to quote a message that contains an embedded image, the embedded attachment won't appear (except when serving the page to admins and mods, who will see it).

The easy solution would be to add some checks in `parseAttachBBC()` to make sure the attachment identified in the BBC is actually attached to the message, and return an empty string otherwise. That approach would simply remove the embedded attachment from the quotation. But that behaviour would also be inconsistent with how we handle the [img] BBC, and thus would confuse users ("Why can I quote that image, but not this one? U GUYS SUXXORS!!!1!").

A proper solution will need to (1) maintain a proper permissions check on whether the embedded attachment is viewable by the reader, (2) allow attachments to be embedded into posts besides the one they are actually attached to, and (3) return some more helpful feedback from `parseAttachBBC()` if the image can't be displayed, rather than producing an `<img>` element that doesn't ultimately work. An ideal solution would additionally (4) do something to warn an admin or moderator if the attachment they are viewing is probably not viewable by other readers (i.e. if there is a permissions mismatch between ability to download that attachment and ability to see the post that it is embedded in.)

**Comment by albertlast** [comment]
The last open point on the list (when no other point  get added),
did you look by your self into this @Sesquipedalian ?

**Comment by Sesquipedalian** [comment]
I have been looking into it, but it's a tricky one. It's next on my priority list.

**Comment by Sesquipedalian** [comment]
The cause of the bad behaviour I was seeing has turned out not to be what I thought it was. The real cause was that an attachment had somehow not been deleted when the message it was attached to was deleted. I think this was due to a glitch that has since been solved.

At any rate, I can no longer reproduce this issue. Everything now seems to behave exactly as it should.
