### ISSUE TITLE
Add language fails to connect

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#4541]
Getting this error when trying to add a new language:

> The Simple Machines site is not responding. Please try again later.

Nothing in the error log. It works fine in a 2.0 install so it doesn't look like it's a problem in simplemachines.org

**Comment by albertlast** [comment]
Can you provide the language file?

**Comment by Gwenwyfar** [comment]
I have only English. That's the "Download from simplemachines" field. There's no option to upload a package actually.

?action=admin;area=languages;sa=add;

**Comment by albertlast** [comment]
The url used by smf2.1 is: https://download.simplemachines.org/fetch_language.php?version=2.1+Beta+4
and this is a dead end -> sm.org issue.

Just for technical notice, the url is build here: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/ManageLanguages.php#L149

**Comment by Oldiesmann** [comment]
It doesn't work because 2.1 Beta 4 hasn't been released, so we don't have any language packs for that version.

**Comment by XinYenFon** [comment]
@Gwenwyfar probably forgot to close this 😆

**Comment by Gwenwyfar** [comment]
There seems to be a problem with the link for all versions, Beta 3 doesn't work either. @jdarwood007 said we could leave this open.

**Comment by frandominguezl** [comment]
I believe we can close this now.
