### ISSUE TITLE
Responsive.css should load last

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#4544]
To avoid over-usages of !important and more importantly avoid having issues related custom integrations etc... this file should be loaded last so its content will become the most important without usage of !important.

**Comment by XinYenFon** [comment]
load sequence should be like;

index.css > page specific css (admin/calendar etc) > addon css (jquery.sceditor/slider etc) > variant css > rtl css > responsive.css

**Comment by albertlast** [comment]
Please define the css order complet,
the existing load order is this:
Index, responsive, rtl, index_variant, rtl_variant, jquery.custom-scrollbar than optional stuff like jquery.sceditor
