### ISSUE TITLE
Sending a Message Anyone in the Forum does not work

### ISSUE THREAD

**Issue by Juccapucca** [SimpleMachines/SMF#4549]
Viestin  lähettäminen JollaSuomi Foorumilla ei toimi.

**Comment by frandominguezl** [comment]
Can you please write the issue in English?

**Comment by wintstar** [comment]
It's Finnish.  He says
>Sending a Message Anyone in the Forum does not work.

@Juccapucca Käytä Google-kääntäjää  https://translate.google.de/

**Comment by colinschoen** [comment]
You will need to give us some more specifics...

**Comment by Juccapucca** [comment]
Here is screenshot from error, when posting new thread in JollaSuomi
Foorumi.

Br
Jukka

2018-02-15 23:39 GMT+02:00 Colin Schoen <notifications@github.com>:

**Comment by frandominguezl** [comment]
Sorry, but where's the screenshot?

**Comment by Juccapucca** [comment]
Sorry here attached.

2018-02-16 14:11 GMT+02:00 Fran Domínguez <notifications@github.com>:

**Comment by frandominguezl** [comment]
@Juccapucca I can't see anything... Are you sure that you're attaching anything here? Can you post a link to the picture instead?

**Comment by Juccapucca** [comment]
Open the attachment.

2018-02-16 14:25 GMT+02:00 Fran Domínguez <notifications@github.com>:

**Comment by frandominguezl** [comment]
There's no attachment in here

![](https://i.gyazo.com/ec9676495ae3554fee6c9eb079874954.png)

**Comment by Juccapucca** [comment]
Here is forum_error.png


2018-02-16 14:30 GMT+02:00 Fran Domínguez <notifications@github.com>:

**Comment by frandominguezl** [comment]
@Juccapucca You're replying and attaching via email and that doesn't work. You have to directly attach the image via GitHub. Make a comment and attach the screenshot here: https://github.com/SimpleMachines/SMF2.1/issues/4549

**Comment by albertlast** [comment]
Since two month we miss central information, 
Please close this issue.

**Comment by smfbigguy** [comment]
Pm system has always worked on my site.
