### ISSUE TITLE
Beta 4 new post, replay, preview Fatal error: Can't use function return value in write

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#4556]
Hi,
Updated 2.0.15 to  2.1 beta 4 

new post, replay, preview 
![fatal](https://user-images.githubusercontent.com/5096676/36467673-d4e70318-16f0-11e8-8b46-f798d7082301.png)

Fatal error: Can't use function return value in write context in C:\wamp\www\smf\Sources\Post.php on line 166

**Comment by Sesquipedalian** [comment]
What PHP version are you using?

**Comment by Sesquipedalian** [comment]
Never mind. I just looked at line 166. Clearly you are using PHP 5.4. :)

I will submit a fix for this shortly.

**Comment by gevv** [comment]
thanks @Sesquipedalian   replay, preview   ok.

new post   db error 

![db](https://user-images.githubusercontent.com/5096676/36468690-7c09df5e-16f5-11e8-972b-592cec03f2dd.png)

**Comment by Sesquipedalian** [comment]
'is_solved' does not exist in the standard version of SMF 2.1. You probably have a modification installed that is not currently compatible with 2.1 Beta 4. Try uninstalling and reinstalling the modification. If that does not work, you will need to uninstall it and wait for the creator of the modification to update it.
