### ISSUE TITLE
moved topic error

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4559]
tried to move a topic from one board to another using the quick moderation icons

	Type of error: Database
Database Error: Field 'modified_reason' doesn't have a default value

INSERT INTO smf1_messages(`id_board`, `id_topic`, `id_member`, `subject`, `body`, `poster_name`, `poster_email`, `poster_time`, `poster_ip`, `smileys_enabled`, `modified_name`, `icon`, `approved`)
VALUES
(1, 0, 2, SUBSTRING('MOVED: testing', 1, 255), SUBSTRING('This topic has been moved to [url=http://localhost:8080/github2.1/index.php?board=4.0]test[/url].

[iurl]http://localhost:8080/github2.1/index.php?topic=63.0[/iurl]', 1, 65534), SUBSTRING('test', 1, 255), SUBSTRING('email addresshere', 1, 255), 1519212377, unhex('00000000000000000000000000000001'), 1, '', SUBSTRING('moved', 1, 16), 1) http://localhost:8080/github2.1/index.php?action=movetopic2;current_board=1;topic=63.0
D:/wamp/www/github2.1/Sources/Subs-Post.php (Line 1776) 

a newer install that has not been upgraded to github version over time does not have this issue. it has a default set for this as "as defined" where the older install has no default defined at all "none". mysql version 5.6.17

**Comment by albertlast** [comment]
As you see here:
https://github.com/SimpleMachines/SMF2.1/blob/048a3f7888949252f52987034885741ceaa9bfa9/other/upgrade_2-1_postgresql.sql#L1838
and here:
https://github.com/SimpleMachines/SMF2.1/blob/048a3f7888949252f52987034885741ceaa9bfa9/other/install_2-1_mysql.sql#L789
The setup and upgrade define the column right.

Wrong update file mention:
https://github.com/SimpleMachines/SMF2.1/blob/048a3f7888949252f52987034885741ceaa9bfa9/other/upgrade_2-1_mysql.sql#L1784

**Comment by illori** [comment]
Well I run the upgrade every day and I don't have this on my install.

On Feb 21, 2018 2:50 PM, "albertlast" <notifications@github.com> wrote:

As you see here:
https://github.com/SimpleMachines/SMF2.1/blob/048a3f7888949252f5298703488574
1ceaa9bfa9/other/upgrade_2-1_postgresql.sql#L1838
and here:
https://github.com/SimpleMachines/SMF2.1/blob/048a3f7888949252f5298703488574
1ceaa9bfa9/other/install_2-1_mysql.sql#L789
The setup and upgrade define the column right.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SimpleMachines/SMF2.1/issues/4559#issuecomment-367448807>,
or mute the thread

**Comment by albertlast** [comment]
Did you check your install and upgrade file if the line exists?

**Comment by illori** [comment]
They are pulled from github directly daily. So if github has it I do.

**Comment by albertlast** [comment]
Can you please check you smf 2.0.x base if the reason field/column already exists ther?

**Comment by illori** [comment]
What do you mean? This is a 2.1 install that gets upgraded to latest on
github daily.

On Feb 21, 2018 3:44 PM, "albertlast" <notifications@github.com> wrote:

Can you please check you smf 2.0.x base if the reason field/column already
exists ther?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SimpleMachines/SMF2.1/issues/4559#issuecomment-367465546>,
or mute the thread

**Comment by albertlast** [comment]
the upgrade*.sql doesn't support the upgrade between 2.1 version.
so when you run the upgrade*.sql you need a smf2.0.x base.
And i ask you to look into you 2.0.x base if the field exists ther in the table messages.

**Comment by illori** [comment]
This can be resolved then. I will change it manually. That field did not
exist in smf 2.0.
