### ISSUE TITLE
AIM custom profile field left behind

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4560]
AIM was removed, https://github.com/SimpleMachines/SMF2.1/pull/4442 but it seems to be left behind if you had it already. the icon is gone so the field completely should be removed or disabled so it does not show the broken image. or we need to provide direction for removing the left over field.

**Comment by Sesquipedalian** [comment]
Do you mean that you have a `cust_aolins` field in the `{$db_prefix}custom_fields` table?

**Comment by illori** [comment]
Yep. It is present.

**Comment by Sesquipedalian** [comment]
Okay. That suggests that your database was initially created/upgraded using a version prior to #4442. Performing an upgrade from 2.0.x to 2.1 now won't create the `cust_aolins` field. Just go ahead and delete the AIM field using the admin panel, and chalk this one up to the "We don't support upgrading between betas" policy. :)
