### ISSUE TITLE
Should upgrade SCEditor to version 2

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#4567]
We're still using SCEditor 1.5.2. At the time of writing, SCEditor 2.1.2 is the most recent. There are some good reasons to upgrade, but it will take [a bit of work](https://www.sceditor.com/posts/migrating-to-v2/).

**Comment by albertlast** [comment]
Will you look into or how will do it?

**Comment by Sesquipedalian** [comment]
Yes, I have started working on it. I opened the issue just to remind myself to come back to it if I get interrupted before it is done.

**Comment by replikacep** [comment]
updated I guess Close is it OK
