### ISSUE TITLE
2 page topic

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#4571]
From this post at SMF:
https://www.simplemachines.org/community/index.php?topic=559080.0;topicseen

So there seems to be something else going on with SMF. I have a topic that had just hit the second page. Which means my post made the second page of that topic. When that happened some weird crap started to happen and I did get database errors. Those errors did stop until I started to post in the topic again. So that is what I am doing now. So step by step:

I just now went to the second page of my topic. I posted a reply by using the reply button, not quick reply. After I pressed post, I was not redirected back to the topic I was redirect to the middle of the first page. But, the page indicator shows I am on page 2 when page 1 is in fact showing. When I click on page one I get a error in the admin panel:

> Undefined offset: 0  https://www.whatsurbeef.net/index.php?topic=56.0  					/******/******f/public_html/Sources/Display.php (Line 1001

Now I had to go into the admin panel to get that error message. So when I come back to that topic and try to go to page two I get this:

> Wrong value type sent to the database. Integer expected. (page_id)

I think I may have a few more errors now. Page 1 does not show at all and there is no "All" link on the page.

Here is a database error:

Wrong value type sent to the database. Integer expected. (page_id)
Function: Display https://www.whatsurbeef.net/index.php?topic=56.15                  /*******/******/public_html/Sources/Display.php (Line 919

The page does sort itself out eventually and you can see all pages and all topics but for a bit it goes real weird. I hope this makes sense to people, lol. Or some one can re-create it.

**Comment by equinoxmatt** [comment]
Suspect commit: https://github.com/SimpleMachines/SMF2.1/commit/1178ca3f01b8bd95a3fde25181650a995c59b16e

PR: https://github.com/SimpleMachines/SMF2.1/pull/4226

Not had time to look at what in that commit broke it, but that is the commit where it breaks first.

**Comment by albertlast** [comment]
@Sesquipedalian did use the wrong word, so this issue got not closed automaticaly...
