### ISSUE TITLE
help tip icon alignment edit profile fields

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4577]
the help tip icon is not aligned correctly on the edit profile field page, it is a little high, other pages it seems in line but in firefox on this page it is a slight higher then other pages.

**Comment by albertlast** [comment]
Can you please add a screenshot to this kind of error?

**Comment by illori** [comment]
![](https://i.imgur.com/Sz5uGMX.png)

**Comment by illori** [comment]
i dont know why the text is bolded as it is not on other pages in the admin panel.
