### ISSUE TITLE
Cannot enable/disable image proxy

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4583]
The box is protected & cannot be changed no matter what...  

![image](https://user-images.githubusercontent.com/23568484/36942791-3c23fa58-1f30-11e8-91f3-9e5d80ddc57a.png)

Latest & greatest from Github

**Comment by albertlast** [comment]
is already fixed in the external proxy pr: https://github.com/SimpleMachines/SMF2.1/pull/4565/files#diff-1c4d2816e84d2562fd969408e87e24d0R222

**Comment by albertlast** [comment]
@sbulen the pr got merge,
so this issue should be fixed.

**Comment by sbulen** [comment]
This tests clean now.
