### ISSUE TITLE
Fresh install - numerous issues - connection, mysqli errors, session verification issues (WAMP only, not linux)

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4584]
Fresh install, latest from github.   I am having several issues attempting to test on my WAMP server (php5.6, mysql5.7).   I am, oddly, NOT having these issues on my linux server (php7.1, mysql5.5).  Fresh current install attempts on both, within the last hour.  

(1) Cannot connect to DB towards end of install.  
(2) Numerous mysqli errors.
(3) Cannot enter admin panel - session verification errors trying to access admin panel.  (Login is OK, failure is at the admin panel prompt.)  

To reproduce, properly install 2.1 on a WAMP server, and try to navigate to the admin panel.

Screenshots follow for each of the 3 issues:
![newinstall-connect-problem](https://user-images.githubusercontent.com/23568484/36949502-1cea3396-1f9e-11e8-84be-cf9f0a031604.JPG)
![newinstall-mysqli-issue](https://user-images.githubusercontent.com/23568484/36949503-1cffd75a-1f9e-11e8-85ea-92e75bee0e3b.JPG)
![newinstall-session-verif](https://user-images.githubusercontent.com/23568484/36949504-1d17885a-1f9e-11e8-81a6-7e18635ac49a.JPG)

**Comment by sbulen** [comment]
So...  I tried logging off & back in as instructed.  Could not log off - more of the same session verification failed issues.  So I deleted all my cookies & tried logging on.   I got further this time - but after entering my credentials, got the following blank (-ish) screen.   
![newinstall-admin-login-problem](https://user-images.githubusercontent.com/23568484/36949647-2faa3182-1fa0-11e8-8496-2eecc1b4baca.JPG)

**Comment by albertlast** [comment]
places some changes to make a better error handling: https://github.com/SimpleMachines/SMF2.1/pull/4585
but the root cause keeps unclear.

**Comment by albertlast** [comment]
The laste update of #4585 should solve your issue complet,
maybe i need to tune something around this,
but not today any more.

**Comment by Gwenwyfar** [comment]
Session errors on login/logout confirmed here for php 5.6 and below (doesn't happen in 7+), started with #4529. #4585 has fixed it for me.

**Comment by sbulen** [comment]
Confirmed - #4585 addresses all of these errors.

**Comment by albertlast** [comment]
than close please this issue

**Comment by sbulen** [comment]
Yes - now that it's been merged!
