### ISSUE TITLE
Theme packages compressed as tar.gz install with .tar in the name

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#4586]
![name](https://user-images.githubusercontent.com/28991853/36982110-c65502b0-206d-11e8-9bc0-0f1f3f97f72d.png)

**Comment by NicolasBonet** [comment]
Fixed in #4663, dunno if we should target for other possible file extensions (I believe only zip, tar and tar.gz are allowed) if that's the case the regex involved can be enhanced.

**Comment by NicolasBonet** [comment]
This should be closed since the PR has been merged.
