### ISSUE TITLE
Hardcoded Text in ugrade.php

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4588]
Version Information:
Forum version: SMF 2.1 Beta 4 (more detailed)
Current SMF version: SMF 2.1 Beta 3
GD version: bundled (2.1.0 compatible) 
MySQLi engine: MariaDB 
MySQLi version: 10.1.29-MariaDB 
Alternative PHP Cache: 5.1.2 
PHP: 7.1.11 (more detailed) 
Server version: Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11 

Tested with the last Pull Request #4578  from today

Page Title in the Steps are hardcoded.  
 upgrade.php
- Line 225 
`$upcontext['page_title'] = 'Updating Your SMF Installation!';`
- Line 1024
`	$upcontext['page_title'] = 'Upgrade Options';`
- Line 1269
`	$upcontext['page_title'] = 'Backup Database';`
- Line 1372
`	$upcontext['page_title'] = 'Database Changes';`
- Line 1465
`	$upcontext['page_title'] = 'Upgrade Complete';`
- Line 2560
`		$upcontext['page_title'] = 'Converting to UTF8';`
- Line 3089
`	$upcontext['page_title'] = 'Converting to JSON';`

![upgrade-14](https://user-images.githubusercontent.com/2753863/37090656-7d0cfc4a-2205-11e8-8e4c-9126d46106b0.PNG)

**Comment by Sesquipedalian** [comment]
Apparently these were missed in #4470.

**Comment by Sesquipedalian** [comment]
@d3vcho

**Comment by wintstar** [comment]
German translate for testing

[Install.german.php.zip](https://github.com/SimpleMachines/SMF2.1/files/1790375/Install.german.php.zip)

**Comment by frandominguezl** [comment]
Yup I missed those. Thanks for reporting. I'll submit a pull request as soon as I can.
