### ISSUE TITLE
Gender Icons not display

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4589]
Version Information:
Forum version: SMF 2.1 Beta 4 (more detailed)
Current SMF version: SMF 2.1 Beta 3
GD version: bundled (2.1.0 compatible)
MySQLi engine: MariaDB
MySQLi version: 10.1.29-MariaDB
Alternative PHP Cache: 5.1.2
PHP: 7.1.11 (more detailed)
Server version: Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11

Tested with the last Pull Request #4578 from today

Gender Icons not display in Summary and Memberlist.

![gender_8](https://user-images.githubusercontent.com/2753863/37090882-61561d8c-2206-11e8-8579-3c82ebeea727.png)

**Comment by Sesquipedalian** [comment]
This should be fixed in #4574.

**Comment by wintstar** [comment]
> This should be fixed in #4574.

In Summary works. In Memberlist **not work**.

![gender_9](https://user-images.githubusercontent.com/2753863/37110576-920e28d4-223d-11e8-94f9-40ad9d971d98.png)

**Comment by equinoxmatt** [comment]
@wintstar   changes have been made to the PR to fix memberlist. If you could re-test that would be much appreciated :+1:

**Comment by wintstar** [comment]
@equinoxmatt works. :+1:

But
https://github.com/SimpleMachines/SMF2.1/pull/4574/files#diff-a2aa83d2eff230e8a37219a7407dbf4eR667

https://github.com/SimpleMachines/SMF2.1/pull/4574/files#diff-aadb001b2153c8ec26308ac0f21e4ed2R976

should not be a comma in the end

`'{KEY}' => $currentKey`

thats right?
`'{KEY}' => $currentKey,`

**Comment by wintstar** [comment]
Sorry, I just received an error message.
>  Type of error: Undefined
> 8: Undefined index: cust_gender
>  http://localhost/smfbeta/index.php?action=mlist
>  C:/xampp/htdocs/smfbeta/Sources/Memberlist.php (Line 635)

My databse
![cust-gender_1](https://user-images.githubusercontent.com/2753863/37553575-4ecccf2c-29cb-11e8-98ea-1525a62ab110.PNG)

![cust-gender_2](https://user-images.githubusercontent.com/2753863/37553576-5775d894-29cb-11e8-81a2-474c1a15f766.PNG)

![cust-gender_3](https://user-images.githubusercontent.com/2753863/37553579-5d9273f4-29cb-11e8-8a40-49c86b22e718.PNG)

**Comment by equinoxmatt** [comment]
@wintstar   the comma at the end of the line isn't necessary as its the last element in the array.

EDIT: You are using an ugpraded board correct?

I believe that existing members won't have a cust_gender set for the theme, only new members have it set as part of the sign-up process.

@Sesquipedalian @albertlast  - The quick fix for this error would be to put an isset() round it.  However this issue will exist for all members on an existing board, until they set their gender. Is this acceptable?

If not, more work will be needed to set custom field default values in the smf_themes table for each member, on upgrade.

**Comment by wintstar** [comment]
> EDIT: You are using an ugpraded board correct?

No, based of a new install with Database Upgrades of the last Pull Reqeusts.

There is a displaying error. The columns are not at the same height.
![gender_10](https://user-images.githubusercontent.com/2753863/37554998-f2127758-29e0-11e8-93eb-cea0046529b2.png)

**Comment by wintstar** [comment]
Icons are now displayed everywhere. But there are a lot of errors displayed.

>  Type of error: Undefined
> 8: Undefined index: cust_gender
>  http://...../smfbeta/index.php?action=mlist
>  /.../smfbeta/Sources/Memberlist.php (Line 634)

![memberlist_error_gender](https://user-images.githubusercontent.com/2753863/37930085-f7c755c0-3141-11e8-97d1-0f672b453b3c.PNG)


@Gwenwyfar you could look at the columns in the member list, there is still a shift, see above in the screenshot. Thanks

**Comment by Gwenwyfar** [comment]
That is a table. The most likely problem is you are seeing a table bug. Nothing we can do about that if it's the case, some browsers just have rendering bugs. I'll take a look just in case, but if the table is correct that should simply not happen.

**Comment by equinoxmatt** [comment]
@wintstar  I haven't looked at the error you reported yet,  the PR has been merged, so I will try and recreate it on the main branch.

Hopefully will look at it this week, just a bit snowed under IRL atm.

**Comment by wintstar** [comment]
This #4669 **does not** fix the errors in the memberlist.

**Comment by frandominguezl** [comment]
I don't see anything wrong on memberlist's table.

**Comment by wintstar** [comment]
> wintstar at 17.03.2018 09:57
> Sorry, I just received an error message.
> 
> Type of error: Undefined
> 8: Undefined index: cust_gender
> http://localhost/smfbeta/index.php?action=mlist
> C:/xampp/htdocs/smfbeta/Sources/Memberlist.php (Line 635)

@d3vcho, look here 

![memberlist_error_gender](https://user-images.githubusercontent.com/2753863/37929221-aeb2cfe2-313f-11e8-8910-683a1feca346.PNG)
