### ISSUE TITLE
PHP 5.5 generates a preg_replace error

### ISSUE THREAD

**Issue by mcblaber** [SimpleMachines/SMF#459]
Originally Reported - http://www.simplemachines.org/community/index.php?topic=506431.0;topicseen
Confirmed by me.

Both in SMF2.0.4 and SMF2.1 the forum generates a handful of errors in the forum error log when running PHP5.5. 

All errors revolve around preg_replace.
"8192: preg_replace(): The /e modifier is deprecated, use preg_replace_callback insteadFile: .../Sources/Load.php(183) : runtime-created function
Line: 3"

**Comment by joshuaadickerson** [comment]
Looking at the head, it doesn't look like /e modifier is used anywhere in Load.php. Run the alpha and try again.

If anything, I think Spuds fixed this back in October.

**Comment by mcblaber** [comment]
I believe my SMF 2.1 alpha site is running a version from a few months ago, so that's odd.

**Comment by emanuele45** [comment]
Yep, Spuds fixed most, but not all, there are at least still 6 left. Search for `~e'`.

**Comment by Spuds** [comment]
Yup ... I converted most of them to callbacks but there were a few I did not get to, it was a work in progress plus I wanted to leave some fun for others :P

**Comment by jdarwood007** [comment]
This should be either fixed as a compatibility patch or a release for SMF.  If its a compatibility patch it should be included in the next release patch as a can fail operation.  Needs patched for 1.1 and 2.0.

FYI, This was done for a MySQL issue in a old version of PHP as well.

**Comment by jdarwood007** [comment]
These should be fixed in #548

**Comment by Oldiesmann** [comment]
Can anyone test and confirm that this is fully fixed now? I don't have a server with PHP 5.5 to test this on.

**Comment by jdarwood007** [comment]
Oldiesmann,
I have tested this on 5.5 and wasn't getting it.  If you want, I can share my url to my PHP 5.5 site and get you access to browse it.

**Comment by tinoest** [comment]
I can also confirm that I have found none of these errors on my PHP 5.5 site although I am only running 5.5.0 not the latest.

**Comment by Arantor** [comment]
This seems to be fixed in 2.1, this should probably be left open to remind us to get a 2.0 patch out for it.

**Comment by jdarwood007** [comment]
Unless I missed something, this should be the list for 2.0
https://gist.github.com/jdarwood007/6747894

Expend it if we need to.  Will help with getting a mod package wrote out to fix this.

**Comment by Arantor** [comment]
Thanks SleePy :)

**Comment by emanuele45** [comment]
http://www.simplemachines.org/community/index.php?topic=512125.msg3617729#new

[This commit](https://github.com/jdarwood007/SMF2.1/commit/145a12d594ff1686e7c3c1bc07f8544ae3a014c7) breaks posting (for example) an image only:

```
[img]http://www.katzy.dsl.pipex.com/Smileys/c000.gif[/img]
```

**Comment by multiformeingegno** [comment]
So, wiill this be fixed in 2.0.x too?

**Comment by Arantor** [comment]
There is already a patch for 2.0 however it is not ready yet; we have not yet finished thorough testing on it as there are security concerns attached to this.

**Comment by multiformeingegno** [comment]
Oh, ok. Do you think it will be in 2.0.7?

**Comment by Arantor** [comment]
I think the general feeling is to release it as a separate patch, the problem with it is that it makes a _lot_ of changes, and it will confuse people who want to do a x.y.z to x.y.z+1 patch.

**Comment by multiformeingegno** [comment]
Uhm, was asking cause I have logs packed (to say an euphemism) by these warnings :P

**Comment by Arantor** [comment]
And you'll get it when we're satisfied it doesn't cause a security concern, the method by which we distribute it should not be a concern.

**Comment by multiformeingegno** [comment]
It's not a concern. It's an info. I wanted to know if I need to follow this topic to find the patch when it's out or wait for an official release.

**Comment by Arantor** [comment]
There will be an announcement either way, I'm sure.

**Comment by Arantor** [comment]
This is fixed in 2.1 as far as we know, the patch for 2.0 is in final testing (since it has direct security implications), so I'm closing this issue. This will become the basis of the 2.0.7 patch to be released once we're satisfied it doesn't cause any issues.
