### ISSUE TITLE
profile summary Custom fields template creates empty elements (part 2)

### ISSUE THREAD

**Issue by Pipke** [SimpleMachines/SMF#4590]
see #4523 wich is closed, do not know how to re-open it, or if i can.

@you guys didnt check the whole template function: fix need also on:
https://github.com/SimpleMachines/SMF2.1/blob/8d1092c1fa3a556ce2cdefc8a131d1cb75f270ea/Themes/default/Profile.template.php#L206

**Comment by Sesquipedalian** [comment]
Reopened existing issue.
