### ISSUE TITLE
banned

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#4594]
Members that are banned on the forum receive a message. If you hover your mouse over the red dot on the who's online list you can see what the banned members message is. Please see screenshot. My message shows breaks in between the words. Posted on SMF here:

https://www.simplemachines.org/community/index.php?topic=559233.0

![banned](https://user-images.githubusercontent.com/3620111/37151743-d26de574-22a4-11e8-8cbd-9d557123f183.jpg)

**Comment by illori** [comment]
confirmed this is showing, this has nothing to do with the text we are adding as the ban message as that part is showing up correctly.

this seems to be corrected if the br's are removed from line 389 in security.php

`fatal_error(sprintf($txt['your_ban'], $old_name) . (empty($_SESSION['ban']['cannot_login']['reason']) ? '' : '<br>' . $_SESSION['ban']['cannot_login']['reason']) . '<br>' . (!empty($_SESSION['ban']['expire_time']) ? sprintf($txt['your_ban_expires'], timeformat($_SESSION['ban']['expire_time'], false)) : $txt['your_ban_expires_never']) . '<br>' . $txt['ban_continue_browse'], !empty($modSettings['log_ban_hits']) ? 'ban' : false);`

i dont think this "title" popup supports html correctly

**Comment by illori** [comment]
actually now that is not fixing it, but it must be there as that is about the only spot this is in the source.

maybe we can change it from a title popup to something else that may support having html in it?

**Comment by illori** [comment]
on who.php line 431 if you change this line to remove the title, it shows up correctly
`	$data[$k] .= ' <span class="generic_icons error"> ' . $error_message . '</span>';`

maybe we can use the same tooltip that shows on the message index if you hover over the message title?

**Comment by smfbigguy** [comment]
Can someone please read the email I sent to simplemachines. It is named "password for bigguy" It was sent from wubforum@gmail.com My hard drive crashed and I lost my passwords. I don't remember the email I registered under. I have tried the reset password option a few times.

**Comment by albertlast** [comment]
After short google,
i found a possible solution which add to all title the option to got html tages:
https://stackoverflow.com/questions/13066909/how-to-break-line-in-jqueryui-tooltip/25819731#25819731
@Gwenwyfar what is your opinion?

**Comment by Gwenwyfar** [comment]
I think titles should not be used as large tooltips. If we want a tooltip we should use one, and that can be done with some css or we can use the popups (better display on mobile).

It seems to me that title text shouldn't even be there. It should just display "This user has been banned", and maybe make it a link to more info (popup or link to the ban log).

**Comment by illori** [comment]
this did not exist in SMF 2.0, would it just be easier to remove this feature completely? i dont think anyone would miss it and that would resolve this issue with little effort.

**Comment by smfbigguy** [comment]
Just something simple like banned member is all it needs.

**Comment by Gwenwyfar** [comment]
Seems like a good option to me. Just need to change the string.

**Comment by jdarwood007** [comment]
Since its just a tooltip, we could strip all the html easily out and just let plain text show.

**Comment by illori** [comment]
it is reusing the text from elsewhere i believe, so it might not be as easy to just strip out the html.

if it is complicated, i think removing this would be a better option.

**Comment by Gwenwyfar** [comment]
I see two options to this: Remove it or change the string to a generic one, possibly linking to the banned users area. I don't think anything else is worth the trouble.

I'm in favor of the latter since it seems to be about as much work as removing it, and it's a nice thing to have on the who's online list.

**Comment by albertlast** [comment]
The line where we get the data is:
https://github.com/SimpleMachines/SMF2.1/blob/cebf1c4a3b982225f6fe571a67b688ada4982aab/Sources/Who.php#L309
This get than into this:
https://github.com/SimpleMachines/SMF2.1/blob/cebf1c4a3b982225f6fe571a67b688ada4982aab/Sources/Who.php#L431

Problem is the url json look like this:
```
"{"action":"","board":"","topic":"","USER_AGENT":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.98 Safari\/537.36","error":"Sorry ich2, you are banned from using this forum!<br>This ban is not set to expire."}"
```

Since it stand ther error and not banned,
we don't know that this message is a bann messages.

Easy solution would be to remove the error message in who list.
