### ISSUE TITLE
Upgrade.php missing language selector

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#4598]
A note to reader that issue is already explained in the title ?

**Comment by albertlast** [comment]
it's a theme issue right?

**Comment by frandominguezl** [comment]
Isn't the upgrader supposed to pick up the default language?

https://github.com/SimpleMachines/SMF2.1/blob/1bbcf2bf43d82a61cb1bb94533e8b15a0a5247f4/other/upgrade.php#L478

**Comment by wintstar** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/4457

**Comment by frandominguezl** [comment]
@wintstar That didn't add a dropdown to pick the language, which is what Antes is reporting

**Comment by wintstar** [comment]
Just wanted to point out that there have been recent changes.  In my opinion, no language selection is required in the upgrade process.

**Comment by frandominguezl** [comment]
Sure, that's why I left the reference above. Assuming that they've been using their forum and upgrading after a while, forum owners may already have their language set, so no language selection is needed unlike Install.php, where you may want to follow the installation proccess in a language other than English.

**Comment by wintstar** [comment]
Shouldn't this be regulated by $user_info['language']?

**Comment by frandominguezl** [comment]
@wintstar 

https://github.com/SimpleMachines/SMF2.1/blob/1bbcf2bf43d82a61cb1bb94533e8b15a0a5247f4/other/upgrade.php#L488

**Comment by wintstar** [comment]
That's what I meant.

**Comment by albertlast** [comment]
because the user favor language is choosen by the upgrade process,
i see no need for a drop down selection.

**Comment by XinYenFon** [comment]
This creates inconsistency between Install & Upgrade.
