### ISSUE TITLE
banned moderator

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4600]
just playing around, i banned a moderator and i get the following errors:
Notice
: Undefined index: moderate in
D:\wamp\www\github2.1\Sources\Subs.php
on line
4353

Notice
: Undefined index: sub_buttons in
D:\wamp\www\github2.1\Sources\Subs.php
on line
4353

Notice
: Undefined index: reports in
D:\wamp\www\github2.1\Sources\Subs.php
on line
4353

Notice
: Undefined index: title in
D:\wamp\www\github2.1\Sources\Subs.php
on line
4353

Notice
: Undefined index: title in
D:\wamp\www\github2.1\Sources\Subs.php
on line
4395

Notice: Undefined index: active_button in D:\wamp\www\github2.1\Themes\default\index.template.php on line 489
href=""
Notice: Undefined index: href in D:\wamp\www\github2.1\Themes\default\index.template.php on line 489
"> 
Notice: Undefined index: icon in D:\wamp\www\github2.1\Themes\default\index.template.php on line 490

Notice: Undefined index: href in D:\wamp\www\github2.1\Themes\default\index.template.php on line 503
"> 1

after refreshing the page again, the errors go away

**Comment by albertlast** [comment]
Could it be that you doesn't got the newst smf 2.1 version?
Because the line of code errors make no sense.

**Comment by illori** [comment]
i update my version daily at 12am eastern time automatically. there is 0% chance i have an outdated version unless this was changed in the last 8 hours.

**Comment by albertlast** [comment]
but you see that 4353 got nothing:
https://github.com/SimpleMachines/SMF2.1/blob/1bbcf2bf43d82a61cb1bb94533e8b15a0a5247f4/Sources/Subs.php#L4352-L4354

**Comment by illori** [comment]
seems that i have been getting an ssl/tls error and it has not been upgrading, i am looking into why i am getting this error.

**Comment by illori** [comment]
got that fixed, now the errors are as follows:
Notice
: Undefined index: moderate in
D:\wamp\www\github2.1\Sources\Subs.php
on line
4371


Notice
: Undefined index: sub_buttons in
D:\wamp\www\github2.1\Sources\Subs.php
on line
4371


Notice
: Undefined index: reports in
D:\wamp\www\github2.1\Sources\Subs.php
on line
4371


Notice
: Undefined index: title in
D:\wamp\www\github2.1\Sources\Subs.php
on line
4371


Notice
: Undefined index: title in
D:\wamp\www\github2.1\Sources\Subs.php
on line
4413
 Notice: Undefined index: active_button in D:\wamp\www\github2.1\Themes\default\index.template.php on line 498
href=""
Notice: Undefined index: href in D:\wamp\www\github2.1\Themes\default\index.template.php on line 498
"> 
Notice: Undefined index: icon in D:\wamp\www\github2.1\Themes\default\index.template.php on line 499

Notice: Undefined index: href in D:\wamp\www\github2.1\Themes\default\index.template.php on line 512
"> 1

**Comment by albertlast** [comment]
Please test the pr #4604
