### ISSUE TITLE
set ban to expire after 1 days

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4602]
in the admin page for bans, i modified the ban to expire after 1 day, i clicked on the modify button. i went back to main ban list where it shows the users ban will expire after 1 day(s), i click on modify and it shows that the ban will expire after 0 days. this is a bit confusing as i would expect it would say 1 day as i just set it to 1 day a few minutes ago. 0 days means it should expire today but the ban should expire tomorrow.
if you save/click modify with the number of days now set to 0 it shows on the ban list that the ban has now expired when it should still exist for less then 24 hours. if an admin goes back to modify a 1 day ban and does not see that the ban has gone to 0 days they will now have an expired ban rather then 1 day.

**Comment by MissAllSunday** [comment]
OK, the description its a bit confusing and I can't figure ir out whats the actual expire time.

So, a ban was created, what was its initial expire value? one day?

Then the ban was modified to 0 days, is that correct?

after it was modified, the ban was listed as "Expired / disabled" on the ban list, is that correct?

**Comment by illori** [comment]
set to expire in 1 day
when you go back to view the ban it then says it expires in 0 days

so if the admin has to modify this 1 day ban prior to 24 hours going by the ban now says it is 0 days, so they may save it and it should expire prior to 24 hours.

**Comment by XinYenFon** [comment]
so if its <1 day it should count hours.

**Comment by MissAllSunday** [comment]
Not really, the expiration day is still handled by days, not hours, so anything that fulfills this: $row['expire_time'] - time() < 86400  needs to show "1 day".

Theres already a prior check for cases when $row['expire_time'] > time() so we don't need to take those cases into account.
