### ISSUE TITLE
Broken HTML in search results

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#4606]
Some HTML tags seem to be missing the ending > in the "view results as messages" search results.

![html](https://user-images.githubusercontent.com/28991853/37244928-5b13f186-246f-11e8-9449-73379d09820f.png)

**Comment by albertlast** [comment]
Can you please write the message also here (i don't want write this down by hand from your pic)

**Comment by Gwenwyfar** [comment]
Any bbc tag will do it. Even [img] tags are broken. Just needs to be a post with HTML output in it, it seems.

**Comment by albertlast** [comment]
I was mention ``*a*`` and ``* *``

**Comment by albertlast** [comment]
the message:
```
<b>Bold</b>
<em>Em</em>
<i>i</i>
<u>U</u>
<s>S</s>
<ins>ins</ins>
<del>del</del>
<a href="somelink">Somelink</a>
<img src="/upgrade-ver/Themes/default/images/smflogo.png" alt="Someimage" />
<pre>Pre</pre>
<blockquote>blockquote</blockquote>
<br />
<hr />
```

**Comment by albertlast** [comment]
broken html exists only in mysql,
will check this tomorrow.

**Comment by albertlast** [comment]
While looking at the code i hat to ask if this realy an issue?
Because you search for everything because of ``**``,
everything means you also find/match html tages,
since they get highlighted(with bold etc.) stuff get broken.

In my eyes is this an edge case.

**Comment by gevv** [comment]
hi,

beta 4 search results   only looks  `<br />`

modify post  (without changing anything) 

search results br  codes does not appear

the search  results look normal
