### ISSUE TITLE
quick edit looks like a disable text field

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4607]
when you quick edit a text
![grafik](https://user-images.githubusercontent.com/1782906/37245471-97a966f2-2498-11e8-84ed-685aaa3c63f1.png)
and you got you mouse over the text:
![grafik](https://user-images.githubusercontent.com/1782906/37245478-b6b67f9e-2498-11e8-82a8-36481946b65d.png)
than the text look like it's disable for change,
when the mouse is removed the text got a normal white background

**Comment by frandominguezl** [comment]
I think it doesn't look like disabled, it's just a hover effect on the box. I'd leave it as it is.

**Comment by Sesquipedalian** [comment]
I agree that it looks strange to make the background grey on hover. Removing the following from index.css would solve this:
```
textarea:hover, textarea.editor:hover {
	background: #fbfbfb;
}
```
Care to put together a quick PR for that, @albertlast?

**Comment by albertlast** [comment]
i was thinking @Gwenwyfar would do this.
i see me more in the search issues,
maybe in the ban stuff.

**Comment by Gwenwyfar** [comment]
We need to add a better hover (and focus) effect on all inputs. Also needed for those who navigate using a keyboard. Thanks for bringing this up :)

**Comment by XinYenFon** [comment]
its background already set to native white (#FFF), I don't think this is an issue.

**Comment by frandominguezl** [comment]
Can we close this?

**Comment by Gwenwyfar** [comment]
It wasn't fixed yet.
