### ISSUE TITLE
wrong profile field sig above and below

### ISSUE THREAD

**Issue by Pipke** [SimpleMachines/SMF#4609]
@Sesquipedalian , the last fixes aren't correct coded

https://github.com/SimpleMachines/SMF2.1/blob/1bbcf2bf43d82a61cb1bb94533e8b15a0a5247f4/Themes/default/Profile.template.php#L441

and

https://github.com/SimpleMachines/SMF2.1/blob/1bbcf2bf43d82a61cb1bb94533e8b15a0a5247f4/Themes/default/Profile.template.php#L466

should be:
```
		if (!empty($field['output_html']))
				$fields = '<li>'. $field['output_html']. '</li>';
```
otherwise the check statement below these lines isnt function (or whatever isnt been called in code language, i think you get me)

another question why is this in the css:
https://github.com/SimpleMachines/SMF2.1/blob/1bbcf2bf43d82a61cb1bb94533e8b15a0a5247f4/Themes/default/css/index.css#L2107
this: margin: 10px 0 0 0;
should be:
margin: 0px;

because if you use costum fields with ul elements they dont get outprinted on top example img:
![naamloos](https://user-images.githubusercontent.com/31970508/37247406-a953e5fe-24ba-11e8-94fc-b2b673998afe.png)

**Comment by Sesquipedalian** [comment]
Oops! Copy-paste error, I suppose. :)

Regarding the CSS, I agree.

**Comment by Pipke** [comment]
the css edit change i suggested above must not be done as the other ul styles in the id element need the 10px margin top, i think its better to add another css style wich only effects the first ul in the id element (above name)
```
#basicinfo .custom_fields_above_name ul {
	margin: 0px;
}
```
