### ISSUE TITLE
Image proxy issue: content size not validated

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4611]
We should probably do an edit on content-length before serving up the header.   Some browsers object to a size of -1.  

Apparently not all servers serve up the content size in the header...   Case in point:
https://www.simplemachines.org/community/index.php?topic=559269.0

**Comment by Sesquipedalian** [comment]
This is already fixed in #4593. See [here](https://github.com/SimpleMachines/SMF2.1/pull/4593/files#diff-95dde0693614aded154dc51012aba3b8R211).

**Comment by sbulen** [comment]
This needs to be reopened.  The line of code points to bypasses caching for images that are too large.   

The problem here is the opposite: when the headers don't provide a content-length, curl returns a content-length of -1, which we store when we cache the image.   Some servers cleanse the bogus value, some don't.   When it's not cleansed, some browsers (IE and IOS) fail.

**Comment by sbulen** [comment]
Correction - I just re-read it  - looks good.

**Comment by sbulen** [comment]
Also, to be safe, just retested.  Looks good.
