### ISSUE TITLE
show alerts checkboxes

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4617]
http://localhost:8080/github2.1/index.php?action=profile;area=showalerts;u=1

on the above page it has checkboxes shown so that actions can be taken on all or some alerts. i have quick moderation set as icons, IMO the checkboxes should not show on this page when i have icons set.

**Comment by NicolasBonet** [comment]
Fixed with #4651

**Comment by NicolasBonet** [comment]
This one should be closed since the PR was merged!
