### ISSUE TITLE
cron.php error

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4619]
Type of error: Critical
The database value you're trying to insert does not exist: id_member
Function: logActions http://localhost:8080/github2.1/cron.php
D:/wamp/www/github2.1/Sources/Logging.php (Line 567) 

submitted request to join a membergroup the above error was logged in the error log.

**Comment by albertlast** [comment]
Created a group which is request able,
from a test user i ask for join,
accept request with admin acc

in this process are no error message appears.

**Comment by illori** [comment]
very strange, i dont know why i am getting this error then if you cant duplicate it.

**Comment by frandominguezl** [comment]
I cannot reproduce this error either

**Comment by illori** [comment]
Strange I guess it might have been a one off issue.
