### ISSUE TITLE
join membergroup possible issues.

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4620]
Your request to join test has been rejected - Today at 06:29 am

if we are rejecting a request to join a group without leaving a message, should we really be letting the user know?

even though it does not say who rejected the request it could leave a lot of questions with few answers.

also when a user has been accepted, it does not seem to give an alert related to that but it does for a rejection.

when you do reject with a message it puts that message into the alert
"Your request to join test has been rejected

not going to happen - Today at 06:38 am"

i am not sure this is the best way to handle this, i think a PM might be better then an alert. just like when we get a warning and send a warning it sends to your PM box.

**Comment by NicolasBonet** [comment]
I'd be in favor of implementing an alert when an user is accepted, and I disagree with removing the alert when the user is rejected, it's better to receive that alert rather than not letting him/her know and simply keep the user waiting or checking the group requests to find out they were rejected sometime ago.

**Comment by illori** [comment]
I believe in smf 2.0 they get no message so this is a change, I am not sure
a positive one.

**Comment by NicolasBonet** [comment]
Since alerts are now implemented and notifications via email/PM were probably rejected to not spam the user, I think it would be nice. I do see a problem in alerting when rejecting but not when approving, it should both or none.

**Comment by illori** [comment]
it seems in the alert preferences you cannot uncheck if you want an alert on if your request to join a group has been approved or denied, i think the users should have an option if they want that.

in the html it sets the checkbox as disabled... it is not too hard to undo that, if we dont want the users to have that option we should just not give it, or we should grant them to option to check or uncheck that box easily.

also this section shows even if there is no group that you can join, maybe this section should not show if you dont have any groups that are join able?

**Comment by jdarwood007** [comment]
I'm in favor of not changing this.  The user doesn't need to question if the request has been approved or rejected.

We could though allow them to uncheck the alert.  For whatever reason that is forced on.
