### ISSUE TITLE
group membership

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4621]
if you enter your profile and look though the menu it seems group membership is completely missing, you can access it from the profile drop down in the header but not from within the profile itself.

it takes you to this page http://localhost:8080/github2.1/index.php?action=profile;area=groupmembership;u=1

also why can the admin change to registered members group(which i dont agree with the name here) as primary group? 

also why does the primary group have the default avatar present under it? i think we could remove it completely.

in this case below the primary group is global moderator, and this user cannot set primary group as registered members.

![](https://i.imgur.com/hqw4Txv.png)

**Comment by Gwenwyfar** [comment]
I see "Group membership" under the "Forum profile" tab here (when inside a profile).

The avatar display is odd. I'll look into it.

**Comment by illori** [comment]
Are you looking as admin or as a user? I think what you are seeing is the
page that shows what groups you are in but has not option to join groups.

**Comment by Gwenwyfar** [comment]
I see it both as admin and as a normal user, links to `action=profile;area=groupmembership;u=2`

**Comment by illori** [comment]
Strange I just tried it again and you are right. I reported another related
issue and could not have if this was missed.

**Comment by frandominguezl** [comment]
Is this still an issue?
