### ISSUE TITLE
Beta 4 Sing Up Errors Database connection error or not allowed to access

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#4623]
Hi,

2.0.15 update smf 2.1 beta 4 New member can not register

action=signup2 page error 

**Local  host wamp server error (php 5.4.16);**

_An Error Has Occurred
You are not allowed to access this section_

**Real host (php7):**

_Database Error
Please try again. If you receive the error message again, please forward the error to the administrator._

**Edit:** mod error not a bug

**Comment by albertlast** [comment]
The error sounds more like a settings error on your side,
so the forum works in general only on signup2 the error apears?

**Comment by gevv** [comment]
Forum is working normally, just can not register new member

action=signup   page  working  click "sing up"  button load step 2  action=signup2 page error

**Comment by albertlast** [comment]
please check you php_error_log,
maybe ther are more information.
