### ISSUE TITLE
&quot; in reported PM

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4625]
i issued a warning to a user, i went into the PM received and reported it to admin, the resulting message the admin received had 

`Quote from: &quot;github2.1&quot;`

if i quote the message it has in it 
`[quote author=github2.1]` which has no quotes in it at all

if i reported a normal message sent between users there is no $quot; present

**Comment by frandominguezl** [comment]
I cannot reproduce the issue

![](https://i.gyazo.com/950f912e6fb33c48d4ca669507eec3bb.png)

**Comment by illori** [comment]
did you issue a warning with a message going to the user? then report that message to the admin.

**Comment by frandominguezl** [comment]
Oh, sorry. I misread your first post.
