### ISSUE TITLE
2.0.15 to 2.1 Beta 4 Database Changes Error Server has not responded for 30 seconds

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#4626]
Hi,

large data base changes error 

14% Overall Progress
0.2%Step Progress

Database Changes
Executing database changes
Please be patient - this may take some time on large forums. The time elapsed increments from the server to show progress is being made!
Executing upgrade script 1 of 2.
Executing: "Changing column names." (1 of 41 - of this script)

Error!
Server has not responded for 30 seconds. It may be worth waiting a little longer or otherwise please click here to try this step again

**Comment by smfbigguy** [comment]
If your just looking for help upgrading or installing please post on Simple Machines web site in the appropriate board and I am sure someone will help you soon enough.

**Comment by gevv** [comment]
ok.  thanks
