### ISSUE TITLE
Upgrader Undefined index: updating_smf_installation

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4627]
PHP Notice:  Undefined index: updating_smf_installation in /.../upgrade.php on line 225
https://github.com/SimpleMachines/SMF2.1/blob/754615c07867925a1e3d7eb953109fde05c24386/other/upgrade.php#L225

https://www.simplemachines.org/community/index.php?topic=559327.msg3965459#msg3965459

**Comment by wintstar** [comment]
https://github.com/SimpleMachines/SMF2.1/blob/16c15bdd66f5f1e151be4e56d5dcd1b0e56f5d0a/Themes/default/languages/Install.english.php#L337

I think he doesn't have the current language pack.

https://github.com/SimpleMachines/SMF2.1/pull/4591/files

> Don't trust the language package which is offered on simpelmachines.org for 2.1 Beta3.
> 
> It's not up to date with Github.
