### ISSUE TITLE
Please put "forum width" back as a theme setting

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#4628]
Someone removed the setting for Forum Width from the admin/themes settings and now forces it to be very narrow. 

This is a really bad choice, IMO - especially for those of us who like a full screen width view.

Although it can be changed in CSS, this should be settable without editing core files.
Also, it should be seriously considered and reviewed before removing existing functionality from the UI.

Please put it back as a setting in the admin area.

**Comment by XinYenFon** [comment]
if such setting is added back to core, it also requires another setting for max-width otherwise SMF will stop the admin at 1200px which makes the setting irrelevant.

**Comment by Gwenwyfar** [comment]
No, it will be added as a max-width setting. Fixed width would be a mess, we don't need that.

**Comment by Sesquipedalian** [comment]
> Also, it should be seriously considered and reviewed before removing existing functionality from the UI.

🤨 That change was before my time, but I am quite certain that it was seriously considered and reviewed.

If you don't agree with a decision the developers made, by all means feel free to start a discussion and request changes. But don't presume to lecture the developers on how to do their work if in the process of doing that work they make decisions that you don't like. That is less than endearing.

**Comment by Kindred-999** [comment]
I searched but could not find anything obvious about when the change happened, nor any discussion regarding the change.   So, as far as I can tell, it was not widely discussed or considered beyond some (incorrect) assumption that removing it was needed for responsiveness.  So, please don’t lecture me.

Also, it’s not my job nor in my personality to be endearing. ;P I call ‘em as I see ‘em, and I am blunt.
... but I did say please. ;)

**Comment by Kindred-999** [comment]
Correction, I found the pull request, #4328 back in Sept...
Seems to have only been a brief comment between you and Gwen

**Comment by Sesquipedalian** [comment]
> Correction, I found the pull request, #4328 back in Sept...
Seems to have only been a brief comment between you and Gwen

That's not the PR that removed the admin-configurable width setting. That's the PR in which @Gwenwyfar added a max-width value in the CSS. Those are different things.

> So, as far as I can tell, it was not widely discussed or considered beyond some (incorrect) assumption that removing it was needed for responsiveness.

A lack of awareness on your part is evidence only of a lack of awareness on your part. 😉 
#2858

> Also, it’s not my job nor in my personality to be endearing. ;P I call ‘em as I see ‘em, and I am blunt.
... but I did say please. ;)

I suppose it never has been your strong suit. 😆 

But I suppose I didn't need to be quite so snippy, either.

**Comment by Kindred-999** [comment]
Ah... I didn’t go back that far...

But, I was correct , the decision was made based on a faulty assumption.

**Comment by Sesquipedalian** [comment]
Well, no. It was established quickly in that discussion that changing the behaviour of the setting from imposing a width to imposing a max-width would was all that was necessary to make it work with responsive design. The decision was made to remove the setting entirely because the majority view at that time that such behaviour would be better left to a mod. So, no, not based on a faulty assumption, but on a debatable bit of design philosophy.

For the record, if I had been around in 2015, I would have voted to change it rather than remove it. But since it has been removed, neither do I think it is worthwhile to put it back into the core now. If @Gwenwyfar really wants to do it, I won't object, but otherwise I think it is fine to leave it to a mod.

**Comment by wintstar** [comment]
More and more people are using the mobile Internet. There's no point in reintroducing the "forum width". @Kindred-999 Create a modification or your own theme with the corresponding width. I don't think this is here the place to discuss it. Create a poll of simpelmachines.org who is for the "forum width" and who is not.

**Comment by Gwenwyfar** [comment]
And I guess you missed it, but that issue had been posted in the forum discussion too.

@Sesquipedalian, it doesn't make much difference for me either way. A mod would be fine by me too, but it may still be less effort to just re-add it (and, apparently, less fuss too).

**Comment by tinoest** [comment]
Personally I prefer it without a width set. It displays nicely on all my browsers be it mobile or desktop. 

Each to there own. The alternative is to have it as a setting which the forum owner can enable / disable.

**Comment by Gwenwyfar** [comment]
@tinoest that is not a concern, it will be reintroduced as max-width. Width is out of question.

**Comment by tinoest** [comment]
I’ll reserve judgement until I can view the change. 

Most of my Desktop Displays are 3840 x 2160. 

This original issue states adding a width mind, so max-width won’t fix the issue will it?

**Comment by Gwenwyfar** [comment]
The current 2.1 version is already using a max-width. The only change is allowing admins to modify the value through the interface.

If we're going to be strict to the issue request then we can close and open a new one... Width won't be added back. It would break things in multiple ways and there is no benefit in relation to max-width.

And honestly, there's already too much over-complication over this. It's just a setting to make it easier to change the value, nothing else.

**Comment by wintstar** [comment]
The default theme is just the default. Everyone can create his own themes according to his needs as he wants them to be. And via Settings.template.php you can insert any desired theme function. That is why I personally find the discussion about this unnecessary.

**Comment by Gwenwyfar** [comment]
Indeed.

Let me just get one thing clear: All this is about moving one number already in the css to a setting that can be modified in the admin interface. That's all there is to this. Let's not waste any more time in this discussion than already has been.

**Comment by Kindred-999** [comment]
Right. Gwenwyfar’s statement is exactly correct.

**Comment by XinYenFon** [comment]
Do we still need anything from here ?

**Comment by DiegoAndresCortes** [comment]
Nope, themers can decide what settings to add to their own themes. This just isn't a "core" feature anymore, it requires manual edit and can be addressed in a "[Tip]" topic in the future.

**Comment by XinYenFon** [comment]
Can this be closed ?

**Comment by DiegoAndresCortes** [comment]
Yes, themers can add it back if they want
