### ISSUE TITLE
Smiley Tooltip not work

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4631]
Version Information:
Forum version: SMF 2.1 Beta 4 (more detailed)
Current SMF version: SMF 2.1 Beta 3
GD version: bundled (2.1.0 compatible)
MySQLi engine: MariaDB
MySQLi version: 10.1.29-MariaDB
Alternative PHP Cache: 5.1.2
PHP: 7.1.11 (more detailed)
Server version: Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11

Tested with the last Pull Request from today

Smiley Tooltip not work

![smiley-tooltip](https://user-images.githubusercontent.com/2753863/37543369-9b77299a-2961-11e8-8da9-fc237667b8d1.png)

**Comment by NicolasBonet** [comment]
I've proposed a fix #4664, perhaps there could be a better solution touching SCEditor files, but I don't know the editor that well to do it using the same emoticons object.

**Comment by Sesquipedalian** [comment]
Closed in #4664
