### ISSUE TITLE
Upgrader - Language issues if pre-existing non-English language in effect at time of upgrade

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4636]
If you have a non-English language chosen (e.g., Turkish UTF8), and you do NOT clear out your /themes directory prior to the 2.1 upgrade, two issues happen.
(1) LOTS of undefined index messages
(2) The DB appears to hang at the start of the database updates

See this thread:
https://www.simplemachines.org/community/index.php?topic=559327.0

Screenshot here:
![image](https://user-images.githubusercontent.com/23568484/37556778-e84babfa-29b7-11e8-8fce-f2850743ffec.png)

The basic problem is that you can end up trying to use the 2.0 language files for the 2.1 installation and they don't line up at all.  

Current Github version, as of the time of this post.  This test was on my WAMP server, php5.6, mysql5.7.  

This strikes at the heart of the age-old question whether to purge /themes prior to install.

Question:  How are you supposed to install the 2.1 language prior to installation?

**Comment by sbulen** [comment]
Albertlast submitted a PR #4635  for this.   

I still have a question, and maybe it's a process question - We just did all this work to support other languages during the 2.1 install.   

Exactly how is this supposed to work?   How do you install the 2.1 language file prior to installation?

**Comment by wintstar** [comment]
So far it was sufficient to insert the respective language package into the directory Themes/default/languages before the installation or upgrade. That's how I did it with my German language pack and it worked.

**Comment by sbulen** [comment]
Thanks!   I didn't even know where to find them.  I just found them on the support site...  I'd been looking for them on Github...  

So yes, I guess that if you extract the 2.1 files & extract your desired language, you should be OK.  As long as the language pack is in sync with the 2.1 code.  

But the 2.1b3 packs aren't in sync with 2.1b4, so this is hard to test at the moment.  Hard for users to figure out what to do.   So I guess the approach is:
 - If they want to install 2.1b3 + the 2.1b3 language pack, go for it (though it's way out of date)
 - If they want to install 2.1b4 at the moment, to install in English

And Albertlast's PR does the latter, if I read it correctly.

**Comment by wintstar** [comment]
Yes, i think the language packages on simpelmachines.org for SMF 2.1 Beta* are not up to date  with the Github Pull Requests.. Therefore I completely retranslated the German language package to test SMF 2.1Beta* in German language => http://www.stephan-frank.de/board/index.php/topic,11.0.html.

**Comment by sbulen** [comment]
If that's the case, then, I think this should be closed once albertlast's PR is tested & applied.

**Comment by albertlast** [comment]
The pr got merged
