### ISSUE TITLE
Browse button in package manager

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#4637]
2.1 Beta 4.  
![bbchrome](https://user-images.githubusercontent.com/6047983/37561205-b114d6d2-2a40-11e8-9d24-38e5f95e381d.png)
![bbedge](https://user-images.githubusercontent.com/6047983/37561206-b163005a-2a40-11e8-9281-10f9c28ae1b9.png)
![bbfirefox](https://user-images.githubusercontent.com/6047983/37561207-b178e4ce-2a40-11e8-9455-81a2a2c3b5b9.png)
![bbie11](https://user-images.githubusercontent.com/6047983/37561208-b18ec898-2a40-11e8-8525-6cfe351fc52f.png)

Seems the browse button in Package Manager > Add Packages is out of line in Firefox, Edge, and IE11.  It's aligned properly in Chrome.  Also looks different in all those browsers, not sure if that's intentional.

**Comment by Gwenwyfar** [comment]
Inputs and scrollbars are different across browsers, not much we can do.

The height is an issue on a few elements, not just this one. I was already making a patch for this, but as usual inputs like to do their own thing whenever they feel like it, still haven't gotten something that consistent.

**Comment by lurkalot** [comment]
Removing these lines 74-76 in index.css seems to fix it for me.

input, select, .button {
	height: 25px;
}

![bb2chrome](https://user-images.githubusercontent.com/6047983/37565076-3428590a-2a9a-11e8-8a56-3cee713d924e.png)
![bb2edge](https://user-images.githubusercontent.com/6047983/37565077-3446d39e-2a9a-11e8-9eec-ee01b8d49111.png)
![bb2firefox](https://user-images.githubusercontent.com/6047983/37565078-345e89b2-2a9a-11e8-8938-18d4085416ee.png)
![bb2ie11](https://user-images.githubusercontent.com/6047983/37565079-3475a250-2a9a-11e8-8bf5-0c7f72f0e116.png)

**Comment by XinYenFon** [comment]
I introduced this bug while leveling inputs / buttons at the same level, this should fix it

```
input[type="file"] {
	height: auto;
}
```

**Comment by Gwenwyfar** [comment]
Yeah, that's why I said this is not the only place that has an issue, others aren't as simple.

**Comment by Gwenwyfar** [comment]
This has been fixed in my local repo. Will be in my next PR

**Comment by XinYenFon** [comment]
#4787 fixed this issue.
