### ISSUE TITLE
filesize(): stat failed

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4642]
Version Information:
Forum version: SMF 2.1 Beta 4 (more detailed)
Current SMF version: SMF 2.1 Beta 3
GD version: bundled (2.1.0 compatible) 
MySQLi engine: MariaDB 
MySQLi version: 10.1.29-MariaDB 
Alternative PHP Cache: 5.1.2 
PHP: 7.1.11 (more detailed) 
Server version: Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11 

Tested with the last Pull Request #4641 from today.

This error appears when New Install and upgrading.

If the setting Minimize css and JavaScript files, then I get this error message:
 Type of error: General
2: filesize(): stat failed for C:\xampp\htdocs\smf21/Themes/default/scripts/alerts.js?beta21
 http://localhost/smf21/index.php?action=admin;area=featuresettings;sa=basic
 C:/xampp/htdocs/smf21/Sources/Subs.php (Line 3747)

**Comment by frandominguezl** [comment]
@Sesquipedalian

**Comment by NicolasBonet** [comment]
It's the browser cache which is being used in the filepath, a simple fix would be to remove it:

`str_replace($modSettings['browser_cache'], '', $file['filePath'])`

In the custMinify function.

**Comment by Sesquipedalian** [comment]
This should be solved in #4644. Please test it, @wintstar.

**Comment by wintstar** [comment]
@Sesquipedalian the Fix works on New Install and Upgrade.

**Comment by Sesquipedalian** [comment]
Excellent.
