### ISSUE TITLE
Not to the post but to the quick answer

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4657]
Version Information:
Forum version: SMF 2.1 Beta 4 (more detailed)
Current SMF version: SMF 2.1 Beta 3
GD version: bundled (2.1.0 compatible)
MySQLi engine: MariaDB
MySQLi version: 10.1.29-MariaDB
Alternative PHP Cache: 5.1.2
PHP: 7.1.11 (more detailed)
Server version: Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11

Function "Minimize css and JavaScript files" is active. But even when the function is disabled, this strange behavior occurs.

Tested with the last Pull Request from today

After updating today's pull request I had observed a strange behavior. When I call up the last post in the board overview, I get to this post briefly, but then I am forwarded to the quick reply. Before the update I came directly to the post. Is that the same for you?

> In german
> Nachdem Aktualisieren des heutigen Pull request hatte ich ein merkwürdiges Verhalten beobachtet. Wenn ich den letzten Beitrag in der Forenübersicht aufrufe, komme ich kurz zu diesem Beitrag, werde dann aber zur schnellen Antwort weitergeleitet. Vor der Aktualisierung kam ich direkt zu dem Beitrag. Ist das bei euch auch so?

**Comment by Sesquipedalian** [comment]
When you say "the last Pull Request from today," do you mean #4656?

If so, then no, I do not see the same behaviour in my tests. Could you post screenshots showing how the behaviour has changed for you?

**Comment by wintstar** [comment]
No, this one https://github.com/SimpleMachines/SMF2.1/pull/4651

You can't show it with a screenshot. 

If Iclick  a post i come briefly to the post. A process is still running in the background and then it is forwarded to the quick reply.

![quick-replay](https://user-images.githubusercontent.com/2753863/37854354-db7c0680-2eea-11e8-8b31-b4882f6cfee8.png)

**Comment by Sesquipedalian** [comment]
Thanks for clarifying.

Still, I do not see this behaviour in my tests. Please post screenshots showing what is happening on your forum (or provide a link that I can follow to see the behaviour myself).

**Comment by wintstar** [comment]
This is the link I click on:
http://localhost/smfbeta/index.php/topic,4.msg96/topicseen.html#msg96

I do not have a current test board online at the moment. Only on my local server.

**Comment by wintstar** [comment]
I could put the board online tomorrow and I would give you access data.

**Comment by illori** [comment]
can you disable search friendly URLs and try again?

**Comment by wintstar** [comment]
As a guest with disabled friendly urls everything is fine. Come directly to the post and stay there too. Logged in as user with disabled friendly urls the problem exists.

http://localhost/smfbeta/index.php?topic=4.msg96;topicseen#msg96

**Comment by wintstar** [comment]
No matter which link I click for topics and posts, I finally get to Quick Reply. Everything was still in order here #4644 .

**Comment by wintstar** [comment]
If I remove this from Display.template.php I stay with the post and will not be redirected:

https://github.com/SimpleMachines/SMF2.1/blob/c3ff7fb7a800ce3ae53988469451f6e915f0fc5f/Themes/default/Display.template.php#L292-L293

**Comment by Sesquipedalian** [comment]
Does #4659 solve this, @wintstar?

**Comment by wintstar** [comment]
I'm out of the house. I'm testing it tonight.

**Comment by wintstar** [comment]
> Does #4659 solve this, @wintstar?

No not works.
If this function im profile "Show WYSIWYG editor on post page not acivate." is not activated, one comes briefly to the post and is then forwarded to the quick reply. You can see for yourself. I sent you a PM with the access data. Fix is installed in Testforum.

**Comment by Sesquipedalian** [comment]
Thank you for that, @wintstar. I've gone to your test forum and tried to reproduce the error using the login information you gave to me. I still do not see anything unexpected happening.

For example, when I click on this link:
![screen shot 2018-03-24 at 11 14 15 pm](https://user-images.githubusercontent.com/191731/37871967-8ccf57e2-2fb9-11e8-9a10-103def539e76.png)

I am taken to this:
![screen shot 2018-03-24 at 11 14 27 pm](https://user-images.githubusercontent.com/191731/37871970-9d76c404-2fb9-11e8-820d-4a3881b72889.png)

Nothing else happens after that. The window does not scroll down to the quick reply form or change in any other way.

**Comment by wintstar** [comment]
Did you deactivate the "Show WYSIWYG editor on post page by default." function in your profile?

Look at the Screenshort

![profile_editor_source](https://user-images.githubusercontent.com/2753863/37872890-f4dea1ce-3010-11e8-97cd-007d4dc0e307.PNG)

Please check again in the test forum. Thanks

**Comment by Sesquipedalian** [comment]
I have tried it with that setting enabled and with it disabled. I still do not see any strange behaviour. 

Does this happen to you with all web browsers?

**Comment by wintstar** [comment]
In Edge, Firefox ist not the problem, but with Chrome Version 65.0.3325.181 (Official Build) (64-Bit).

Cookies and browser cache I have already deleted several times

**Comment by Sesquipedalian** [comment]
I just tried again using the same version of Chrome on your test site. I still could not reproduce the issue.

If you have any Chrome extensions installed, try disabling them to see if one of them is causing the issue.

**Comment by wintstar** [comment]
Ok. 
I will update to the new pull request. Maybe that fixes that problem. Please don't close the issue yet. I will report here after the update if it is fixed.

**Comment by wintstar** [comment]
I updated today to Pull Request "remove_whitespace". The fault is Chrome. As soon as I activate any extension, no matter which, the error comes. Before Pull Request #4644 everything was fine in Chrome. The error did not appear in Chrome until it was updated to Pull Request #4651. In between Chrome was not updated. I don't understand this.

You can close the issue if you want.

**Comment by wintstar** [comment]
I got the bug after the pull requests #4641, #4644 and #4651.

The only change to the editor was this one here:
GenericControls.template.php
`sceditor.instance(textarea).createPermanentDropDown();', empty($editor_context['rich_active']) ? '' : '`
to
`sceditor.instance(textarea).createPermanentDropDown();', !empty($editor_context['rich_active']) ? '' : '`

I don't know if it is actually the cause, but it is the period in which the bug occurred.

https://github.com/SimpleMachines/SMF2.1/issues/4657
