### ISSUE TITLE
request to Unapproved Topics and Messages button counter 

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#4662]
Hi, add a counter to the moderation button
![untitled 1](https://user-images.githubusercontent.com/5096676/37863843-38c9669e-2f76-11e8-9afa-271ac8a94ad6.png)

**examples**

![untitled 2](https://user-images.githubusercontent.com/5096676/37863897-5068f7dc-2f77-11e8-90b1-9ed221b4c1ee.png)

Unapproved Topics and Messages

**Comment by albertlast** [comment]
It's already ther:
![grafik](https://user-images.githubusercontent.com/1782906/37866736-ebc124e0-2f8e-11e8-8412-51807773cbb4.png)
And please use english version of smf when you post something.

**Comment by gevv** [comment]
ok. thanks

**Comment by gevv** [comment]
@albertlast  Does the counter work for  Unapproved Topics and Messages?

Unapproved Topics and Messages I do not see the number I use english version

(_Reported Messages, Reported Members  counter work no problem_)

**Comment by albertlast** [comment]
Dunno but the counter is their and split the numbers to the different points


________________________________
Von: gevv <notifications@github.com>
Gesendet: Samstag, 24. März 2018 20:11
An: SimpleMachines/SMF2.1
Cc: albertlast; Mention
Betreff: Re: [SimpleMachines/SMF2.1] request to moderation button counter (#4662)


@albertlast<https://github.com/albertlast> Does the counter work for Unapproved Topics and Messages?

I do not see the number I use english version

**Comment by gevv** [comment]
no counter or not working  on unapproved topics and messages

**Comment by illori** [comment]
there is no counter for how many if any posts/topics are awaiting approval.
