### ISSUE TITLE
Cannot call session save handler in a recursive manner

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4668]
Version Information:
Forum version: SMF 2.1 Beta 4 (more detailed)
Current SMF version: SMF 2.1 Beta 3
GD version: bundled (2.1.0 compatible) 
MySQLi engine: MySQL 
MySQLi version: 5.6.37-log 
PHP: 7.1.13 (more detailed) 
Server version: Apache/2.4.29 (Unix) 
Browser: Chrome Version 65.0.3325.181 (Offizieller Build) (64-Bit)
Last Pull Request from today #4667

> Type of error: General
> 2: Unknown: Cannot call session save handler in a recursive manner
>  xxx//xxxxxx/smfbeta/index.php?action=admin;area=repairboards

If I click "Find and repair any errors" in Admin Center /  Forum Maintenance come to  get to a white page with the Error:
**Warning: Unknown: Cannot call session save handler in a recursive manner in Unknown on line 0**

![find_and_repair](https://user-images.githubusercontent.com/2753863/37896142-70082104-30e3-11e8-9999-5e282be695ab.PNG)

![find_and_repair_withe-page](https://user-images.githubusercontent.com/2753863/37896171-7ecf7c00-30e3-11e8-94a8-7976d7c29a5f.PNG)

**Comment by albertlast** [comment]
Could you try if #4671 fix your issue?

**Comment by wintstar** [comment]
Fix works.
