### ISSUE TITLE
Undefined errors each time you access to an user's profile

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#4669]
You get various undefined errors each time you access to any user's profile. Here's an example;

![](https://i.gyazo.com/e9dd9691d26808cf419e5642c6b1edad.png)

**Comment by equinoxmatt** [comment]
This is my PR that was merged this morning #4574 . Will try and make a fix tonight.

This is also linked to: #4589

**Comment by frandominguezl** [comment]
I just got the fix @equinoxmatt do you mind if I submit a PR?

**Comment by equinoxmatt** [comment]
Go for it :) I am struggling for time atm.

This is my fault for only testing on new forum with only one custom field (gender!). Mea Culpa!
