### ISSUE TITLE
Custom profile fields in multiple languages (Enhancement)

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4674]
Gender icon now works. Thanks to you developers. but custom profile fields cannot be created for multiple languages.

The following scenario:
The Forum has installed the German, English and French language pack. Now we create gender icons in German. Now the German member can enter and view the gender icons in his German language.The English and French member see the gender icons only in German. I used gender icons as an example here. I also see this problem with other profile fields. 

![muliple_languages_profile_feld](https://user-images.githubusercontent.com/2753863/37950600-75ca7e28-3199-11e8-92eb-d7b7aa58eba5.PNG)

**Comment by frandominguezl** [comment]
This is the perfect idea for a mod. I don't think this is necessary as a core feature.

**Comment by equinoxmatt** [comment]
Hmm, it is a fair point I guess.  Not sure if it is the point of a mod though?

I think this is a problem with 'default' fields like gender, being a 'custom field'.  It isn't custom (created by the user), it's already created thus should be translatable?

Anything in the core should be able to be translated, a mod shouldn't have to fix this.   

Just my thoughts.

**Comment by wintstar** [comment]
@equinoxmatt, I agree with that. Creating a mod for it is not a good idea

**Comment by MissAllSunday** [comment]
To be able to offer translations for dynamic fields we need to either instruct the user on how to do it or offer a way to add those translations during field creation.

One way I see to solve this would be to offer the chance to use "tokens" on both the name and the description, if a token is used then it will be replaced with whatever string the user put on whatever language the user is using.  This isn't perfect as the admin still needs to manually add the translation to each language they are using and those extra vars will be lost if they ever update their language files.

**Comment by wintstar** [comment]
This is also the solution for other forum software. And if modifications are made, the admin must also make sure that language variables are not lost during an update. These additional language variables can be inserted into Modifications.english.php. And this is not overwritten during an update.

**Comment by Sesquipedalian** [comment]
I agree that this would be nice. But it would also be an entirely new feature. We are trying to finish up RC1 right now, so we don't want to add new features at this point.
