### ISSUE TITLE
Spellcheck

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#4676]
I have just installed pspell on my server. All went well with that. SMF saw it and told me spell check was working. I enabled it and went to make a test post. Spelled a word wrong and hit the button. Nothing else happens. No errors, no popups, nothing.

My SMF install was just updated the other day
I tried the default theme and a custom theme
I cleared cache and restarted server
Nothing worked.

https://www.simplemachines.org/community/index.php?topic=559604.0

**Comment by albertlast** [comment]
Maybe a stupid question,
but how we know that you pspell is working?

**Comment by smfbigguy** [comment]
In the admin panel of SMF it say it is. That's all I know. How can I test it. Is there a way. ?? Is there something on the server in WHM I can do to test it.

**Comment by smfbigguy** [comment]
Here is a post on SMF:

https://www.simplemachines.org/community/index.php?topic=559604.0
