### ISSUE TITLE
Toggle Source disables editor's input on link & mail

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#4678]
Actually, its not really disabling but more like falling back to old-school browser pop-input.

And here goes nothing 😆

**Comment by colinschoen** [comment]
I don't think this is worth fixing. If these were substantial text inputs that would be painful to lose I could see fixing this, but it is just one URL or one email. Plus I can't come up with a workflow that involves viewing the source in the midst of inserting an email or URL.
