### ISSUE TITLE
2.0.15 to 2.1 b4 All user Birth date 1004-01-01

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#4681]
Hi,

upgrade 2.0.15 to 2.1 b4 All user profile  birth date 1004-01-01

![brit](https://user-images.githubusercontent.com/5096676/38167317-fb80859e-353b-11e8-9585-c93bb02a7bb5.png)

**Comment by Sesquipedalian** [comment]
It sounds like the upgrader isn't preserving birthdates properly. @sbulen, would you be able to take a look at this?

**Comment by sbulen** [comment]
I believe this is restricted to uninitialized (not user-specified) birthdates.  User-specified birthdates are fine.  

I'll look a little deeper.  IIRC, the old 2.0.x uninitialized value (0001-01-01) was causing issues & this was set to 1004-01-01 on purpose.

**Comment by Sesquipedalian** [comment]
> IIRC, the old 2.0.x uninitialized value (0001-01-01) was causing issues & this was set to 1004-01-01 on purpose.

Yes, that is correct.

> I believe this is restricted to uninitialized (not user-specified) birthdates. User-specified birthdates are fine.

I understood @gevv to be saying that *all* birthdates were being changed to 1004-01-01. If this is just a matter of *uninitialized* birthdates being turned into 1004-01-01, then the upgrader is doing what it is supposed to do. If that's the case, then perhaps the fix is simply to change the display on the profile page (and wherever else) to show a blank if the birthdate is 1004-01-01.

**Comment by sbulen** [comment]
Few folks specify them, they are almost all uninitialized in my DBs.  The few that did specify them are properly kept in 2.1.  

I was just reading the old PR to confirm:
https://github.com/SimpleMachines/SMF2.1/pull/4139

& Issue:
https://github.com/SimpleMachines/SMF2.1/issues/4136

I don't see it displayed anywhere...  The 'age' appears to handle an uninitialized value OK.  

What screen looks awkward?   

EDIT:  The only place I've found it is on the modify forum profile page (screenshot first post).   I'd be tempted to leave this as-is.

**Comment by gevv** [comment]
> I believe this is restricted to uninitialized (not user-specified) birthdates. User-specified birthdates are fine.


yes likely

must be empty  birthdates

**Comment by albertlast** [comment]
because of stupid reason,
smf didn't allow null values and for second stupid reason,
mysql can't handle years below 1k.
This is the "best" solution we got than.
