### ISSUE TITLE
top default avatar does not appear in topic

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#4684]
hi,

top default avatar does not appear in topic

broken link: www.xxxxxx.com/index.php/topic,xxxxx.msgxxxx/avatars/default.png

home page and other normaly

![zopic-ava](https://user-images.githubusercontent.com/5096676/38171064-711520e0-359a-11e8-912b-f3b76b3b4921.png)
![topic-ava](https://user-images.githubusercontent.com/5096676/38171065-715a8112-359a-11e8-92fa-296524900f21.png)

------------
_no problem after upload new avatar_

**Comment by albertlast** [comment]
~Nope i don't get this error~,
maybe more details are needed.

The error appears only when you enable search friendly url.

In my eyes is the result of the js correct but we need a rewrite rule how define the right path for this.

**Comment by gevv** [comment]
change  avatar settings  url  change  public_html/attachments  to public_html/avatars

problem solved

**Comment by albertlast** [comment]
doesn't solve the issue on my side
