### ISSUE TITLE
Wrong change with gender icons css

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4689]
Due to the changes with Pull Request #4672 the gender icons are no longer displayed.

This change ist wrong
https://github.com/SimpleMachines/SMF2.1/pull/4672/files#diff-c5ef6bd5b5f64bcfc3d4647ac7c33792R1712

https://github.com/SimpleMachines/SMF2.1/pull/4672/files#diff-c5ef6bd5b5f64bcfc3d4647ac7c33792L1729

![gender_css](https://user-images.githubusercontent.com/2753863/38228607-9b51b330-3704-11e8-9858-2e7585eae4f3.JPG)

![gender_css1](https://user-images.githubusercontent.com/2753863/38228724-467f0424-3705-11e8-857c-7f173cd27072.JPG)

**Comment by illori** [comment]
confirmed.

**Comment by wintstar** [comment]
If no gender is selected (None) will still display an icon. Antes has already commented:
https://github.com/SimpleMachines/SMF2.1/pull/4672#issuecomment-376437736

My solution would be:
default/css/index.css
find
```
.generic_icons.gender_None {
	background: none;
}
```
replace with
```
.generic_icons.gender_0 {
	display: none;
}
```

![gender_none](https://user-images.githubusercontent.com/2753863/38262955-ef9c2514-376e-11e8-932a-ce1216ae43db.PNG)

**Comment by Sesquipedalian** [comment]
I see the opposite.
![screen shot 2018-04-03 at 9 57 18 pm](https://user-images.githubusercontent.com/191731/38287849-42f749b2-378a-11e8-9a44-77022bfb4200.png)
![screen shot 2018-04-03 at 9 58 18 pm](https://user-images.githubusercontent.com/191731/38287850-431978de-378a-11e8-96e0-6977cbc9202d.png)

@wintstar: Do you see any difference when using English vs. German? I am trying to figure out why my test forum uses `gender_Male` while yours uses `gender_1`.

**Comment by albertlast** [comment]
@Sesquipedalian  you miss the database changes
i guess this one: https://github.com/SimpleMachines/SMF2.1/pull/4383/files#diff-d6f74e978f1d734a838e3b2e2336b695

**Comment by wintstar** [comment]
@Sesquipedalian 
my Database changes https://github.com/SimpleMachines/SMF2.1/issues/4589#issuecomment-373905175

> Do you see any difference when using English vs. German? I am trying to figure out why my test forum uses gender_Male while yours uses gender_1.

Once the user-defined profile fields are defined in one language, they cannot be used in another language. You have closed this issues https://github.com/SimpleMachines/SMF2.1/issues/4674   from me. Please reopen it so that it can be solved at a later time. Mark it with a milestone RC2 or similar. But please don't leave closed, I think it's very important to solve this.

**Comment by illori** [comment]
i made the change in that commit listed above and now i got gender_2 and it is missing the image due to the css.

this is caused by the fact that we dont support an upgrade from an existing beta install to another beta install, so this change was not applied to the existing install.

**Comment by wintstar** [comment]
@illori Is your forum on the current Pull Request?

There was a change in the icons and CSS values

Icon =  https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/images/icons/generic_icons_sprite.png

The css values must now contain "background position:"

**Comment by illori** [comment]
It gets updated daily.

**Comment by wintstar** [comment]
![gender-female](https://user-images.githubusercontent.com/2753863/38383293-7246610c-390c-11e8-92fd-12af3fbc38de.png)

**Comment by illori** [comment]
That is what I am seeing.

**Comment by wintstar** [comment]
@Sesquipedalian 
https://github.com/SimpleMachines/SMF2.1/pull/4383#issue-150730962

https://github.com/SimpleMachines/SMF2.1/pull/4383/files#diff-c5ef6bd5b5f64bcfc3d4647ac7c33792L1703
