### ISSUE TITLE
warning level box/color bar does not fit

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4694]
in your profile if you go to view warnings and you have a warning level in effect, the color bar seems to be a few px lower then the outline of the box. maybe just remove the color and leave the percentage? when we issue a warning it no longer has the color, so maybe it is not so necessary here.

**Comment by wintstar** [comment]
Please look here, Gwenwyfar has already planned some improvements in the themes

https://github.com/SimpleMachines/SMF2.1/pull/4629
