### ISSUE TITLE
admin panel -> warnings view warnings not populating

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4695]
on the warnings page in the admin panel, if you click on select permissions for each group it lists the groups but it seems if you grant permission to view the warnings in the permissions area it is not showing up here.

for my global moderator i have checked view warning status for own and any yet on this page no group is checked off.

also by default since it seems that if you can issue warnings as well as moderate forum members it shows the warnings by default, maybe this should be removed from here and left as permissions section only?

**Comment by jdarwood007** [comment]
This is because its using 2 different permissions.  "view_warning" for the warnings page, and view_warning_own/view_warning_any for the permissions page.

The warnings page doesn't make it clear to me which permission it is supposed to be.  I'm guessing own, but it could be any as well.
