### ISSUE TITLE
show drafts link

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4700]
when you want to "load" drafts from the post view, you need to click on the text or the image on the right side, is it possible to just click anywhere in the bar to enable the same function?

**Comment by frandominguezl** [comment]
Can you specify about the area you want to be enabled?

**Comment by illori** [comment]
So that the complete line can be clicked on to expand the drafts.

**Comment by frandominguezl** [comment]
I just saw it, I had to enable "Enable the selection of drafts from the posting screen". I don't really think it's necessary to make the whole bar clickable, it's enough having the image and the text clickable.

**Comment by frandominguezl** [comment]
Can we close this?

**Comment by illori** [comment]
i would like input from the devs. i think this is worth being considered. for those on mobile it might make it easier for them to get the drafts to show.

**Comment by DiegoAndresCortes** [comment]
I don't think this is an issue, and this behavior is consistent in different sections
