### ISSUE TITLE
iurl

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#4703]
iurl is still present in the editor. Please see this post at SMF

https://www.simplemachines.org/community/index.php?topic=542792.msg3968271#msg3968271

**Comment by smfbigguy** [comment]
OK, hold on a sec...If you have the editor on and you click the link icon and you fill in both fields it actually opens the link in a new tab so it works as intended that way. If you highlight a word in your text and click on the link icon and just fill in the url then it becomes an iurl. So I sorta gotta ask...is this the way it should work. I'm not sure. I figure it should turn it to a url either way is what my thought was.

**Comment by smfbigguy** [comment]
Asked this on SMF, no need to reply in this post. Reply here:

https://www.simplemachines.org/community/index.php?topic=542792.msg3969137#msg3969137

**Comment by smfbigguy** [comment]
I think maybe this should be closed if no one has any input.( not being rude ) As I said above I'm not so sure this is an issue. The link button in the wysiwyg editor works two ways. So I will let you guys decide but the more I think about it the more I think it is not an issue.

**Comment by Sesquipedalian** [comment]
No, I agree that it should be as consistent as possible in all cases. I just haven't had time to get to this one yet.

**Comment by smfbigguy** [comment]
No problems at all. I know your all busy. :)
