### ISSUE TITLE
Mobile theme issues

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#4713]
Since there's a fair amount of small issues, let's keep them all in one place.

Have in mind that a large revision will be done in responsive.css before 2.1 final version, regardless of reported issues, so time spent testing the desktop view is preferable right now.

Related issues:
#4691 #4673

**Comment by sbulen** [comment]
See also #4793 
Sorry, missed this thread!

Note that User Actions misalignment creates some deadspace:
![useraction1](https://user-images.githubusercontent.com/23568484/41812359-4ec0c9ae-76d6-11e8-97fb-a92d9688f638.jpg)

**Comment by sbulen** [comment]
Another deadspace issue on mobile - Premature Wrappage!   

![prematurewrappage](https://user-images.githubusercontent.com/23568484/41812639-a3b940f8-76db-11e8-8c96-73bdf5c45b11.jpg)

**Comment by sbulen** [comment]
Last one for today...  Topic title wrap is ugly...  Not sure if it is the font, the spacing, or both...  
![funkyfont](https://user-images.githubusercontent.com/23568484/41815790-dabbfa48-7729-11e8-9d0d-44f315ca2a21.jpg)

**Comment by XinYenFon** [comment]
Lets start;
#4691
* Not an issue, you shouldn't be seeing the topic icons on mobile.
* Not an issue, buttons are controlled by specific template and we can't divide them.
* Not an issue, user names gets extra eye-candy (or attention).

#4673
* Known issue, this is happening because of tables are lacking class so we can't really hide/show things properly (CC: fixing #4675 will fix this issue)

https://github.com/SimpleMachines/SMF2.1/issues/4713#issuecomment-399700731
* I have fix for this, I just forgot to send it.

https://github.com/SimpleMachines/SMF2.1/issues/4713#issuecomment-399727536
* This is related to new word wrapper thing I have no idea so passing it to @Gwenwyfar

**Comment by gevv** [comment]
Hi, desktop and mobile no new message link

![pm](https://user-images.githubusercontent.com/5096676/43782498-366adb0a-9a68-11e8-8681-363659271b7a.png)

**Comment by XinYenFon** [comment]
That's not related to responsive issues. Open separate issue.

**Comment by XinYenFon** [comment]
To me, each issue (big or small) needs to be tracked by its individual issue, I think best to close this.

**Comment by SychO9** [comment]
Is there a reason there are so many unneeded **!important** rules in the responsive file ? just making sure before I remove them

**Comment by gevv** [comment]
and ""Mark ALL messages as read, All Unread Topics"" buttons do not appear

must be ""User actions"" buttons

https://user-images.githubusercontent.com/5096676/38322835-3b7da0a4-3844-11e8-8188-02dbc7690960.png

**Comment by gevv** [comment]
""Mark ALL messages as read, All Unread Topics"" buttons do not appear mobile

must be ""User actions"" buttons

https://user-images.githubusercontent.com/5096676/38322835-3b7da0a4-3844-11e8-8188-02dbc7690960.png

**Comment by Gwenwyfar** [comment]
> Is there a reason there are so many unneeded **!important** rules in the responsive file ? just making sure before I remove them

Besides one at the body and maybe similar exceptions, there shouldn't be. 

> To me, each issue (big or small) needs to be tracked by its individual issue, I think best to close this.

We will do that once the file is revised. There are too many issues right now.

**Comment by gevv** [comment]
"Quote selected text" not work. button does not appear mobile (android chrome, firefox)
