### ISSUE TITLE
User search problem

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#4717]
Hi,

Search for member "X" on forum page  not be found  "X" member 

Admin page  search for "X" member there is no problem

**Comment by albertlast** [comment]
i would guess that the admin page found someone with x is the real issue,
because the search allow by default, only search string witch meat the min word length,
which is for x not enough

**Comment by gevv** [comment]
I meant to say as an example  (X)

missing description sorry 

I use word length normaly

example search "gevv"

?action=mlist;sa=search     not be found 

?action=admin;area=viewmembers;sa=search   found a member "gevv"

**Comment by albertlast** [comment]
than we need more information, because the normale search for members works fine for me.

**Comment by gevv** [comment]
new noticed member not activated

thanks
