### ISSUE TITLE
Creating Report, missing language strings or incorrect database entries

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4718]
Version Information:
Forum version: SMF 2.1 Beta 4 (more detailed)
Current SMF version: SMF 2.1 Beta 3
GD version: bundled (2.1.0 compatible) 
MySQLi engine: MariaDB 
MySQLi version: 10.1.29-MariaDB 
Alternative PHP Cache: 5.1.2 
PHP: 7.1.11 (more detailed) 
Server version: Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11 
Browser: Chrome Version 65.0.3325.181

## **Board is new installed**
Pull Request from today # 4714, no additional language package is installed. Standard language is english. Has been detected when creating a report about Group Permissions.

Creating Report missing language strings or incorrect database entries
- profile_blurb_own
- profile_displayed_name_own
- profile_forum_own
- profile_password_own
- profile_signature_own
- profile_website_own

![groupperms-report](https://user-images.githubusercontent.com/2753863/38866364-f6d83ce6-4240-11e8-9dd6-d4bb27769b0b.PNG)

**Comment by albertlast** [comment]
For it look it that it wanted in this way how it is:
https://github.com/SimpleMachines/SMF2.1/blob/dd179b23c765f51a490c9464e4db0cd06aa86137/Sources/Reports.php#L721

**Comment by wintstar** [comment]
I know, but why can only see the language strings and not the text. See the screenshot above.

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/languages/Reports.english.php#L96-L132

... can not found the language string
$txt['group_perms_name_profile_blurb_own';
$txt['group_perms_name_profile_displayed_name_ownn';
$txt['group_perms_name_profile_forum_ownn';
$txt['group_perms_name_profile_password_ownn';
$txt['group_perms_name_profile_signature_ownn';
$txt['group_perms_name_profile_website_ownn';

**Comment by albertlast** [comment]
Because they are own permission and
own permission text you find here: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/languages/ManagePermissions.english.php

**Comment by wintstar** [comment]
@albertlast, maybe I didn't translate it right. The language strings are not missing in ManagePermissions.english.php but in Reports.english.php, I think. Or there are obsolete database entries. Go to the Administrator Center to Maintenance then Reports and create a report for group permissions. Then you see as above in the screenshot that there what is not in order. It's all about the generated report. Are missing text. Instead of text, only the language strings are displayed.


> german translate
> @albertlast, vielleicht habe ich es nicht richtig übersetzt. Die Sprachstrings fehlen nicht in ManagePermissions.english.php sondern in Reports.english.php, denke ich. Oder es sind veraltete Datenbankeinträge. Gehe in das Administrator-Center zu Maintenance dann Reports und erstelle einen Bericht für Gruppen Berechtigungen. Dann siehst du wie oben im Screenshot das da was nicht in Ordnung ist. Es geht nur um den generierten Bericht. Es fehlen Texte. Statt Text werden nur die Sprachstrings angezeigt.

**Comment by albertlast** [comment]
I provide a pr,
please give me feedback about this.
