### ISSUE TITLE
Long code database error

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#4723]
Hi,

code added to new topic  preview  no problem 

topic posting  database error  (beta4)

**New topic error**

> Incorrect string value: '\xC4\xB1 oku...' for column 'body' at row 1
> Dosya: /xxxxx/Sources/Subs-Post.php
> Line: 1735 

Same code add comment database error

**comment error**

> Data too long for column 'body' at row 1
> Dosya: /xxxxxx/Sources/Subs-Post.php
> Line: 1735 

_Same code  test smf 2.0.15 new topic, comment no problem_
**Code:**

[code.txt](https://github.com/SimpleMachines/SMF2.1/files/1942723/code.txt)

**Comment by frandominguezl** [comment]
Go to: Maintenance > Forum Maintenance > Database and run the task called "Convert to MEDIUMTEXT". Then go to Forum > Post and Topics > Post Settings and change the "Maximum allowed post size" to whatever number you want.

**Comment by gevv** [comment]
thanks, problem solved.
