### ISSUE TITLE
A mistake appears in the quick modification

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#4729]
Hi,

On my forum SMF 2.0 I use Darkec theme from SMFTricks, this theme is based on SMF 2.1. Look at this mistake:

Darkec theme:

https://youtu.be/Ohz_i4m--uo

SMF 2.1:

https://youtu.be/EZqClPRyvqA

This mistake occurs in the quick modification of the message if the post is long. The same mistake is on SMF 2.1. 

If there is less text in the editor then the quick edition of the message is in correctly place.

Darkec theme:

https://youtu.be/0iQlBpVM9DA

SMF 2.1:

https://youtu.be/eD02dYLkzAo

How to fix it?

**Comment by smfbigguy** [comment]
You should be asking this on Simple Machines. I don't think this is the place for it.

**Comment by illori** [comment]
you mean if the post is long the whole post does not appear unless you scroll down? if so that is the expected behavior and not a bug.

**Comment by jsqx** [comment]
@smfbigguy 

I understand, but it looks like an mistake in this function.

@illori 

I mean it, that if there is much text in the post and if I click on the quick modification, the page will automatically scroll down. And I have to scroll the page up so that I can see the editor of writing the message. It should not be like that. After clicking on editing the post, I should immediately see the editor without automatically scroll down. Therefore, I think this is a mistake in 2.0 and in 2.1. I informed the author of the theme about this mistake. I am waiting for information.

If there is less text in the editor then the quick edition of the message is in correctly place.

Just look at this videos:

Long text:

https://youtu.be/Ohz_i4m--uo

The same is on 2.1

https://youtu.be/EZqClPRyvqA

Less text:

Darkec theme: (correct)

https://youtu.be/0iQlBpVM9DA

SMF 2.1: (correct)

https://youtu.be/eD02dYLkzAo

**Comment by illori** [comment]
This issue tracker is for SMF 2.1 only. Any issues with a theme or SMF 2.0
should not be reported here. We can look into the issue with the quick edit
though.

**Comment by jsqx** [comment]
I understand it, but this mistake also appears in 2.1. The Darkec theme (SMF 2.0) is based on the functions of SMF 2.1 - I informed you that this mistake appears in 2.0 and in 2.1. And how to fix it for 2.0?

I will create a new topic on the SMF forum.

**Comment by albertlast** [comment]
Would be the pr #4731 a possible good solution?

**Comment by jsqx** [comment]
Thank you for fixing this mistake, but there is still something you need to fix in 2.1.

Look at this:

Opera 52.0.2871.99 (latest) / Google Chrome 66.0.3359.139 (latest)

When I first click in the quick editing, the edit window will stay in place, the page will not scroll down. If I click a second time in quick editing, the page will automatically scroll down. It should not be like that.

And if I refresh the page in the ctrl+F5 browser or with the refresh icon, this page will automatically scroll down to the quick reply editor. I think it should not be like that.

Look at this video:

Opera:

https://youtu.be/S7SIIxJFHjE

Chrome:

https://youtu.be/ouDg1SKAEGs

****

IE 11.0.9600.18537

In this browser, the quick edit editor works properly for the first and second turn on and so on.

But if I refresh the page in the ctrl+F5 browser or with the refresh icon, this page will automatically scroll down to the quick reply editor. I think it should not be like that.

Look at this video:

https://youtu.be/rrbw7E78l7I

****

Mozilla Firefox 59.0.2 (latest)

In this browser, the quick edit editor works properly for the first and second turn on and so on.

But if I refresh the page in the ctrl+F5 browser or with the refresh icon, this page will automatically scroll down to the quick reply editor. I think it should not be like that.

Look at this video:

https://youtu.be/NwVXqSoER40

Can you fix it all?

**Comment by illori** [comment]
since this issue is now closed, it would be easier for you to open a new issue.
