### ISSUE TITLE
Moderation center menu permissions

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#473]
in the moderation center there are almost no permissions as to who can see what in the menu and the referred to pages, beyond if they are a board moderator.

it could be useful to be able to restrict what moderators can see depending on their permissions.

if a moderator can not issue warnings why should they be able to view the warnings that others have issued?

i think the main point is to limit the warnings currently it only allows board moderators... what if a user is allowed to warn users but is not a board moderator? then they are not even allowed to view the warnings in the moderation center.

**Comment by Oldiesmann** [comment]
Not sure about the warning log to be honest with you - it may be useful for some moderators to have this info even if they can't issue warnings.

For the other warning thing, we need to test this and make sure. It does appear to be the way you say, but I haven't tested it yet to verify.

After a quick glance I don't see anything else that would either allow people to see stuff they shouldn't be able to or not being able to see stuff they should be able to.

If there are any other things that need to be tweaked, we should definitely fix that. Much of what's shown is dependent on the mod cache.

**Comment by illori** [comment]
then there should be a separate permission to view the warning log for those that cant issue warnings, but i think it is not necessary.

the main issue just seems to be with the warnings visible to those that cant issue warnings from what i can tell.

**Comment by Arantor** [comment]
Seems to me this ties in with the other issue around users being able to see their own warnings. Perhaps this needs to be a single own/any permission (view own warnings, view any warnings)?

**Comment by MissAllSunday** [comment]
Is there actually anything to do here?

**Comment by illori** [comment]
set permissions in the moderation center for who can view the warnings issued
