### ISSUE TITLE
A mistake appears in the quick modification part 2

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#4732]
Thank you for fixing this mistake https://github.com/SimpleMachines/SMF2.1/issues/4729 but there is still something you need to fix in 2.1.

Look at this:

Opera 52.0.2871.99 (latest) / Google Chrome 66.0.3359.139 (latest)

When I first click in the quick editing, the edit window will stay in place, the page will not scroll down. If I click a second time in quick editing, the page will automatically scroll down. It should not be like that.

And if I refresh the page in the ctrl+F5 browser or with the refresh icon, this page will automatically scroll down to the quick reply editor. I think it should not be like that.

Look at this video:

Opera:

https://youtu.be/S7SIIxJFHjE

Chrome:

https://youtu.be/ouDg1SKAEGs

****

IE 11.0.9600.18537

In this browser, the quick edit editor works properly for the first and second turn on and so on.

But if I refresh the page in the ctrl+F5 browser or with the refresh icon, this page will automatically scroll down to the quick reply editor. I think it should not be like that.

Look at this video:

https://youtu.be/rrbw7E78l7I

****

Mozilla Firefox 59.0.2 (latest)

In this browser, the quick edit editor works properly for the first and second turn on and so on.

But if I refresh the page in the ctrl+F5 browser or with the refresh icon, this page will automatically scroll down to the quick reply editor. I think it should not be like that.

Look at this video:

https://youtu.be/NwVXqSoER40

Can you fix it all?

**Comment by albertlast** [comment]
Please try the new way from the pr if this fix this issue complete.

**Comment by jsqx** [comment]
Now the quick edition editor works correctly. Thank you.

And I have a question about refreshing, when I double-click on the refresh icon (only Mozilla Firefox) or (ctrl+F5 all browsers) the page will automatically scroll down. Why is this happening? Can you change it? This does not occur in SMF 2.0

Should I show it on video?

**Comment by albertlast** [comment]
I don't understand what you mean with scroll down,
when i press ctrl + f5 the page refresh more not.

**Comment by jsqx** [comment]
Look at this video. Refreshing in SMF 2.1

https://youtu.be/2ZvPMrLWt0o

Refreshing via Ctrl+F5 the page will automatically scroll down. I think it should not be like that. After refreshing, the page should stay in place.

Look at this video. Refreshing in SMF 2.0 (correctly)

https://youtu.be/cEPcMfxgNx4

**Comment by albertlast** [comment]
i don't got the issue on smf2.1

**Comment by jsqx** [comment]
I do not understand what you mean.

**Comment by albertlast** [comment]
the issue didn't happen in my test env.

**Comment by jsqx** [comment]
I will check it on another computer, I will answer tomorrow.

**Comment by wintstar** [comment]
I already reported that https://github.com/SimpleMachines/SMF2.1/issues/4657 .

I don't think it's fixed.  Is it correct that on the board overview page ( /index.php) topic.js is not loaded?

I added the fix to my page, cleared the cache several times, but still when I click a post in the board overview page under Recent Posts, it always scrolls to the quick reply when I call the page to the post.

**Comment by albertlast** [comment]
On your testside i clicked on a recent post,
this forwards me to the post and move the screen to the point of where the message is.
After this nothing happen,
did i something wrong @wintstar ?

**Comment by wintstar** [comment]
The problem is only in ChromeBrowser Version 66.0.3359.117 (Offizieller Build) (64-Bit). I have not enabled an extension in Desktop Chrome Browser.
With Edge, Firefox and mobile Chrome Browser (Smartphone) is not a problem.

**Comment by albertlast** [comment]
Okay I startet my chrome and visit *your-domain*/smfbeta/index.php/topic,4.msg94/topicseen.html#msg94
and it keep sticking on the msg94 and doesn't move downwards

**Comment by wintstar** [comment]
I have cleared my browser cache again, now it seems to work. I have noticed several times that Chrome stores it in cache for a very long time. Although you have cleared the cache several times, it takes a very long time before changes become visible.
