### ISSUE TITLE
GDPR support natively?

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4751]
Since i got no response in the internal forum,
i ask here.
Would be a good idea to implement gdpr tools direclty into smf2.1?

**Comment by wintstar** [comment]
gdpr Tools, what this?

**Comment by albertlast** [comment]
gdpr is in german dsgvo and
tools means functions which support the process which you got around this topic

**Comment by jdarwood007** [comment]
You just submitted that post this morning?

**Comment by albertlast** [comment]
enough time to say yes or no from someone of the smf team.

**Comment by jdarwood007** [comment]
For volunteers to respond within hours of your post on a weekend?  Highly unlikely.
