### ISSUE TITLE
quickedit reply got empty class on chrome

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4755]
While debugging other stuff i notice when i use chrome and write something in editbox
an empty class appear.
The start
![grafik](https://user-images.githubusercontent.com/1782906/39766895-b46760e8-52e5-11e8-8fa4-842d01747dea.png)
looks fine

when i write something:
![grafik](https://user-images.githubusercontent.com/1782906/39766968-e20e58a8-52e5-11e8-82b9-f9070b4667d3.png)
empty class appear (that is the issue)
right would be class=""
see https://stackoverflow.com/questions/30748847/is-an-empty-class-attribute-valid-html

when i remove the text:
![grafik](https://user-images.githubusercontent.com/1782906/39767028-044f1088-52e6-11e8-9bea-f8c1318a5f4e.png)
class get as entry placeholder

@Sesquipedalian catch please

**Comment by Sesquipedalian** [comment]
Don't worry about it. Chrome just likes to render empty attributes that way when presenting them in the development inspector. It's doesn't mean anything about the source HTML itself. :)

**Comment by albertlast** [comment]
@Sesquipedalian could you than look pleae into: https://github.com/SimpleMachines/SMF2.1/issues/4749
