### ISSUE TITLE
Error at create  Error log

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4761]
Forum version: SMF 2.1 Beta 4 (more detailed)
Current SMF version: SMF 2.1 Beta 3
GD version: bundled (2.1.0 compatible)
MySQLi engine: MariaDB
MySQLi version: 10.1.29-MariaDB
Alternative PHP Cache: 5.1.2
PHP: 7.1.11 (more detailed)
Server version: Apache/2.4.33 (Win32) OpenSSL/1.0.2o PHP/7.1.11
Browser: Firefox Quantum 60.0 (64-bit)
Last Pull Request of Today #  4752 

I installed a buggy mod to test the changed error log. There are deliberately missing language strings. No errors are logged, but the following error message is displayed:
> Warning: mysqli_stmt_bind_param() expects parameter 1 to be mysqli_stmt, boolean given in C:\xampp\htdocs\smfbeta\Sources\Subs-Db-mysql.php on line 991
> 
> Warning: mysqli_stmt_execute() expects parameter 1 to be mysqli_stmt, boolean given in C:\xampp\htdocs\smfbeta\Sources\Subs-Db-mysql.php on line 992

Nothing has been stored in the database ( smf_log_errors) either.

**Comment by albertlast** [comment]
did you apply the database changes(add the backtrace column)?

**Comment by wintstar** [comment]
The column is not inserted in the database during the upgrade process. But I'm testing that again. I give you feedback.

**Comment by albertlast** [comment]
Sure it is: https://github.com/SimpleMachines/SMF2.1/blob/ec5bbc5f018ea76adbbad44e980802edc66d786a/other/upgrade_2-1_mysql.sql#L2647

**Comment by wintstar** [comment]
I know this,. This column is not added to the database during the upgrade process. I have performed the upgrade process 3 times. This column is available for a new installation.

**Comment by wintstar** [comment]
The new error logging has become very good. :+1:

**Comment by smfbigguy** [comment]
Is it possible to run this fix in phpmyadmin. I updated my site today and then this fix came in, lol. If not don't worry. I will be upgrading I think in the next week or 3 anyways, lol.

**Comment by albertlast** [comment]
sure you can, take the upgrade command from mysql:
https://github.com/SimpleMachines/SMF2.1/blob/175e499e01e0adf1f24ec061a2aa5425ad8d0310/other/upgrade_2-1_mysql.sql#L2646-L2647
replace {$db_prefix} with you prefix (default is smf_) and run this on phpmyadmin.

**Comment by smfbigguy** [comment]
Thank you sir. I will give this a shot later today.

**Comment by smfbigguy** [comment]
That shows errors in phpmyadmin. I think I will wait to add that. Thanks though for taking the time to post it.
