### ISSUE TITLE
Code tags

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#4763]
I hate to do this. It should be a simple fix though.....I think. Code tags do not copy and paste right. This could be a wysiwyg editor problem really. If copy and pasting code into the editor and then using code tags, it treats it like a paragragh not a code block. No formating at all.

**Comment by smfbigguy** [comment]
Like the tags work right them selves but the code put in between the tags does not.

**Comment by smfbigguy** [comment]
Screenshot:

![firefox_screenshot_2018-05-15t00-19-18 575z](https://user-images.githubusercontent.com/3620111/40029745-2939ac1e-57b4-11e8-8f78-73e77129f73c.png)

**Comment by Sesquipedalian** [comment]
Do you mean that it loses the line breaks?

**Comment by smfbigguy** [comment]
The screenshot is how it looks when I do it. When a member on my site does it it works great for them. Nothing wrong at all. I wonder now if it is me or if there is a problem.

**Comment by smfbigguy** [comment]
I guess the other member that was doing it was NOT using the editor to post his. That's why they turned out good. code tags and php tags work with no editor. When using editor they show like the screenshot. Most anything copied to the editor has no line breaks or formatting.

**Comment by Sesquipedalian** [comment]
I'm having trouble reproducing this. What browser are you using, and what is the source of the text that you are copying? I'm guessing that some combination of source formatting and browser is producing this.

**Comment by Sesquipedalian** [comment]
Oh, I've figured out how to reproduce it now. I needed to first paste the text *not* into a code block. That apparently strips out all of the line breaks for some reason. Using the toolbar button to wrap it into a code block after pasting produced the result in your screenshot.

The fact that pasting multiple paragraphs into the editor in its normal mode strips out all the line breaks is obviously a bug of some sort. I'll have to see if I can figure out what's going on with that.

**Comment by smfbigguy** [comment]
I'm glad you found it. :)

**Comment by Sesquipedalian** [comment]
The problem has turned out to be with the AutoYouTube plugin. I'm implementing fixes now.

**Comment by Sesquipedalian** [comment]
Please test if #4763 solves the issue for you, @smfbigguy.

**Comment by smfbigguy** [comment]
Ok, I'm runnin around in cirlcles here tryin to figure out where this is supposed to be put, lol. Anyway, I cleared all my cache before and nothing really worked other than php tags. Now, after waiting for hours before testing again. All I have to do is paste a bit of code into the editor and it adds the tage without me even pushing the bbc button. So it does work.

**Comment by smfbigguy** [comment]
Didn't mean to close that sorry I coughed and hit the wrong button.

**Comment by gevv** [comment]
Hi,

is this normal? please see the picture
![untitled](https://user-images.githubusercontent.com/5096676/41200595-31fbad46-6cb0-11e8-9a48-8a42c6bb2f17.gif)

**Comment by smfbigguy** [comment]
No, that doesn't look right at all. I have never noticed it on my site but no, that's not right.

**Comment by Archer70** [comment]
@Sesquipedalian's last commits fixed the issues for me! :+1:

**Comment by vort7u** [comment]
Hi @Sesquipedalian only a question...
Is normal that code layout doesn't have a limit and with long code we have a very long page?
![test code](https://user-images.githubusercontent.com/1554203/50654405-0b8b6180-0f8d-11e9-8834-28a7458ff113.png)

**Comment by SychO9** [comment]
It isn't, can you please create a separate issue about it ?
