### ISSUE TITLE
A non-numeric value encountered $_REQUEST['start'] PHP 7.1.17

### ISSUE THREAD

**Issue by Pipke** [SimpleMachines/SMF#4764]
Got a [report](https://www.simplemachines.org/community/index.php?topic=522114.msg3972665#msg3972665) from a user on one of my mods concerning this error, wich happens when the url is changed by **guess who i dont know** but it happend to start=%1, yeah right when you change the url yourself (maybe hacking attempt, or by spammers/bots?) instead of clicking valid forum link(s).

> Apache Version | Apache/2.4.33 (Win32) OpenSSL/1.0.2o PHP/7.1.17

SMF 2.0.*
2: A non-numeric value encounteredApply Filter: Only show the errors from this file File: E:/XAMPP/htdocs/smf/Sources/Recent.php
Line: 229

SMF 2.1 beta*
2: A non-numeric value encountered
 http://localhost/beta/index.php?action=recent;start=%1
 E:/XAMPP/htdocs/beta/Sources/Recent.php (Line 242)

This will occur on all pages wich use the $_REQUEST['start'] method (like member list, error log etc), i only posted the above ones.
fix:
```
	// Make sure start are numbers.
	if (isset($_REQUEST['start']))
	{
		// Make sure its a string and not something else like an array
		$_REQUEST['start'] = (string) $_REQUEST['start'];

		// If there's a slash in it, we've got a start value! (old, compatible links.)
		if (strpos($_REQUEST['start'], '/') !== false)
			list ($_REQUEST['start'], $_REQUEST['start']) = explode('/', $_REQUEST['start']);
	
		// Now make absolutely sure it's a number.
		$_REQUEST['start'] = isset($_REQUEST['start']) ? (int) $_REQUEST['start'] : 0;
	}
	// Well, start is going to be a number no matter what.
	else
		$_REQUEST['start'] = 0;
```

**Comment by albertlast** [comment]
I don't understand why this is a issue.
Someone provide something wrong and so an error appears,
why is this behavior an issue?

**Comment by Pipke** [comment]
Well why there is QueryString.php then?

> * This file does a lot of important stuff.  Mainly, this means it handles
> * the query string, **request variables**, and session management.

https://github.com/SimpleMachines/SMF2.1/blob/175e499e01e0adf1f24ec061a2aa5425ad8d0310/Sources/QueryString.php#L156

https://github.com/SimpleMachines/SMF2.1/blob/175e499e01e0adf1f24ec061a2aa5425ad8d0310/Sources/QueryString.php#L199

**Comment by albertlast** [comment]
Well i don't understand where you would like to place your fix,
but i place a check in the recent code part.
