### ISSUE TITLE
Text smileys broken on upgrade

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4767]
In my 2.0 forum, we use the 'classic' smiley set.  After upgrade, we are still on the 'classic' set - which is .gif based.  

Using a text smiley - e.g., "8)" for "cool" - is broken after upgrade, because SMF 2.1 assumes your default smileys are always .pngs.   It can't find "cool.png" in the classic folder, and displays a broken link.  

In short, all text-based smileys are broken after the upgrade if your forum default points to a .gif based set.

**Comment by wintstar** [comment]
Smileys in 2.1 changed from .gif to .png. Please look #4526 and #4532.

**Comment by albertlast** [comment]
In my eyes the text smilies are not broken.
The cool.png exists: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Smileys/default/cool.png

**Comment by sbulen** [comment]
As explained above, if you point to a .gif based smiley set in 2.0, and upgrade to 2.1, text based smilies become broken links.

That is because your forum's default still points to the old set, all gifs, but 2.1 has now hard-coded a .png extension.

I suspect this is going to happen to lots of users.

The question is what should we do about it - if anything.

Should we change the default to one of the new .png-based sets on upgrade?   Or should the upgrade instructions point out that the default must be changed?

What about users that like their current gif-based smiley set?   Due to the hard-coded .png extension, those won't work as defaults going forward.

**Comment by sbulen** [comment]
Looking into this further...   The current state of 2.1 doesn't allow support of .gif-based smileys **_AT ALL_** anymore.  (I understand that it had to go one way or the other, given that the extension is specified as part of the filename in the smf_smileys table...)   

_Further, all the smileys were .gif-based in 2.0.   So...  NONE will work upon upgrade or even after the upgrade..._   

So...   To fix:
1)  We need to change the default to one of our new .png-based default sets upon upgrade. 
2)  We need to document the lack of support for .gif-based smileys going forward upon launch.  

EDIT:   The existing upgrade logic tries to preserve the old smiley sets, and concatenates the two new sets to the end of the list of the old ones.  This will create an unusable mix of .gif-based & .png-based sets.  So the fix will need to be to have the upgrader set the values for smiley_sets_known, smiley_sets_names and smiley_sets_default with the same values that the installer does.  Just set them to the new sets, don't try to keep the old ones around.

**Comment by Sesquipedalian** [comment]
We should simply make the file extension variable rather than hard coded.

**Comment by sbulen** [comment]
That would be the ideal solution.  Do we really want to tackle that now?  

I suspect it's a little messy.  I suspect one of the settings will need to become a JSON structure.  And we'd need to move the old values into the new structure & assume .gif.  Installer & upgrader work.  Displaying 'em...   ACP changes also.

For smileys?   Not sure it's worth it.  My suggestion is to set the default & work with .pngs going forward.  

(My conservative don't-make-unnecessary-changes streak is showing...)

EDIT:  The 'default' folder is going to have both .gifs and .pngs...   .gifs from 2.0 & .pngs from 2.1...  What value do we set there?

**Comment by sbulen** [comment]
Downside to losing .gif support:  No animated .gif smileys...

**Comment by wintstar** [comment]
Are  .gif not vulnerable to malicious code?

**Comment by sbulen** [comment]
Short answer: no.  

Longer answer:  Years ago on horribly configured systems this was a problem.  .pngs are in the same boat, actually.  I don't think a .png is any more secure than a .gif.   (You can find posts of malicious payloads in .pngs if you search.)  Once the malicious code was up there, you'd use a separate vulnerability to get it to execute.  Those have since been closed up.  It is much harder to get a picture to execute these days...  

.pngs are preferred mainly due to better color depth.  They look nicer.  But the downside is that they don't animate.  

And the bigger downside is that pretty much all of our existing 2.0 users are using .gifs that won't work in 2.1.

**Comment by sbulen** [comment]
@Sesquipedalian - How's this for a compromise - a short term & a longer term approach.  

Short term - the upgrader defaults to one of the new .png smiley sets as I propose above.  This is quick & easy, and addresses the immediate problem that smilies are basically broken upon upgrading at the moment.  

Long term - we enhance the smiley system to honor multiple extensions.  IMO, this need not be an RC dependency, but that's a dev team call.

**Comment by Sesquipedalian** [comment]
> The current state of 2.1 doesn't allow support of .gif-based smileys **_AT ALL_** anymore.

I've taken a look at the code in `parse_smilies()`, and I am not sure how you came to that conclusion. PNG files are only hard coded for the default set, and only if the option for custom smiley sets is disabled. If you are using a custom set, the file name and extension will be whatever is set in the table. You could use a mixture of PNG, GIF, JPG, and SVG if you liked. To verify, I just tested with both `.gif` and `.png` extensions set in my smileys table (and the corresponding files in my smileys directory), and both worked just fine.

I suspect that whatever is going on with your install has to do with a messed up table and/or missing files, but without further information I can't be sure.

**Comment by sbulen** [comment]
This is what I'm seeing....   

I am using the latest code from github.  As described above, I had 'classic' selected as the default in my forum.  I performed a 2.0 to 2.1 upgrade.  I left the 'classic' smiley set as the default.  

Smileys now look like this:
![image](https://user-images.githubusercontent.com/23568484/40327233-07fd8a46-5cf7-11e8-8207-a728598a1339.png)

The editor looks like this:
![image](https://user-images.githubusercontent.com/23568484/40327274-1ed57eb8-5cf7-11e8-874f-4981c28d0a2d.png)

These symptoms go away if I select a .png based smiley set.  And they return whenever I re-select a .gif based smiley set as the default.  

EDIT:  Custom smiley sets are enabled.

**Comment by Sesquipedalian** [comment]
The fact that you are seeing the original text next to the broken image icon suggests that something really odd is going on. It looks like the alt text that is added to each smiley image is being rendered as regular text, which makes me suspect that the generated HTML is broken. 

Please do the following:

1. Use your browser's developer tools to inspect the HTML of the broken images and paste it here.
2. Paste the contents of your smileys table here.

**Comment by Sesquipedalian** [comment]
Please also post:

3. The value of the `smileys_url` variable from your settings table.
4. The value of `smiley_set` column for an affected member (e.g. your own) from the members table.

**Comment by sbulen** [comment]
1)  image html:
![image](https://user-images.githubusercontent.com/23568484/40336045-f2f7b87c-5d1b-11e8-97a6-52fb1fbd1038.png)
2)  smileys table
![image](https://user-images.githubusercontent.com/23568484/40336084-2036e538-5d1c-11e8-888e-d2fa945fe6b3.png)

3)  smileys_url from settings:
![image](https://user-images.githubusercontent.com/23568484/40336108-3fc7eb9a-5d1c-11e8-83f3-d93d73ac41fd.png)

4)  smiley_set from member:
is blank...   

This is the data from the pix depicted above.  In all instances the forum's default smiley set is used (classic).   But there is no 'cool.png' in my forum's default (classic) smiley set - it's a bunch of .gifs:
![image](https://user-images.githubusercontent.com/23568484/40336183-de1d2be8-5d1c-11e8-9b20-9de444a0371a.png)
  

Note that the smiley set in the 'default' folder will work, because in 2.0 it had .gifs, the 2.1 installation added .pngs, so now it has both, e.g.:
![image](https://user-images.githubusercontent.com/23568484/40336155-b03f5e6c-5d1c-11e8-8137-275ee9484148.png)

**Comment by sbulen** [comment]
Some more notes on changing the _personal_ smiley set (not the forum default) under Look & Feel:

Using the forum default (which is classic, .gif only):
![image](https://user-images.githubusercontent.com/23568484/40343027-bbf4bf56-5d42-11e8-89d3-2ddd1a79024f.png)

Default (which will work, because as shown above, it has both .pngs and .gifs).  The Fugue .pngs were added to the default folder:
![image](https://user-images.githubusercontent.com/23568484/40343056-e0ab5b48-5d42-11e8-90d9-e8d7e273684d.png)

Classic fails, it's .gif only:
![image](https://user-images.githubusercontent.com/23568484/40343070-efe8d68a-5d42-11e8-8f9a-07a3b8c0197d.png)

Aaron works, which is confusing...  It only works because the settings are confused (see below) and it is actually pointing to Alienine, one of the new ones with .pngs:
![image](https://user-images.githubusercontent.com/23568484/40343085-03be67e2-5d43-11e8-977b-636e1493b2d6.png)

So this issue is not limited to the 'default' smileys.  The 'personal' smileys are affected as well.  

=====

ONE OTHER ISSUE...   There is in fact a different upgrader issue.  The logic for adding Alienine & Fugue to smf_settings is failing.  I believe Fugue is failing because it's the default, and there is already a default.  Alienine is failing because of syntax.   Note the directories are all there in the filesystem, but the names are confused because the smf_settings values are confused:
![image](https://user-images.githubusercontent.com/23568484/40343223-af9eed16-5d43-11e8-86e1-2d06d7130e4a.png)

The logic for updating these values in the upgrader needs to be fixed also.

**Comment by Sesquipedalian** [comment]
Please test #4772

**Comment by Sesquipedalian** [comment]
> ONE OTHER ISSUE...   There is in fact a different upgrader issue.  The logic for adding Alienine & Fugue to smf_settings is failing.  I believe Fugue is failing because it's the default, and there is already a default.  Alienine is failing because of syntax.   Note the directories are all there in the filesystem, but the names are confused because the smf_settings values are confused:
> ![image](https://user-images.githubusercontent.com/23568484/40343223-af9eed16-5d43-11e8-86e1-2d06d7130e4a.png)
>
>The logic for updating these values in the upgrader needs to be fixed also.  

Please create a new issue for that. 🙂

**Comment by Gwenwyfar** [comment]
I will need to test the PR later and read the whole discussion, but are we re-allowing .gifs also? It really should not be hardcoded to png, at all. The upgrade should simply look for smf-default smileys and change those. Preferably removing the standard .gifs.

**Comment by sbulen** [comment]
Today, the only smilies that work are .pngs.  Sesquipedalian's PR aims to restore functionality for other file types.

There are other issues with the upgrade logic itself, now tracked in a separate issue, #4773.
