### ISSUE TITLE
MOD Uninstalls do not appear to be working - dangling hooks

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4780]
If you install a mod & uninstall it, you get a lot of "The callable xxxxx could not be called." messages afterwards while navigating around the forum.   Feels like the code is gone but the hooks are there.

**Comment by MissAllSunday** [comment]
How does that mod is been uninstalled?  in its package-info.xml file which action gets called first?  hooks uninstall or removing files/dirs?

**Comment by sbulen** [comment]
It forced me to install & uninstall in 2.1b3 emulation mode.  

Looking at package-info.xml, I think the 2.1 beta 3 uninstall step skips it's hooks step?

I'll report to the mod author...

**Comment by sbulen** [comment]
FYI, mod author confirmed it was an issue with the mod & fixed it.
