### ISSUE TITLE
Sending email notifications is unreliable

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#4783]
For example, if a user is set up to receive email notifications immediately (but only for the first unread message), they may or may not actually be sent an immediate notification. Moreover, they may be sent a daily or weekly digest email even though that is not the setting they have selected.

I haven't yet been able to discover a pattern for how and why this happens, but it happens frequently.

This should be fixed before RC1.

**Comment by albertlast** [comment]
Nope nope,
you don't know the reason and
don't know how to reproduce and
the function is not critical -> not rc1 issues.

**Comment by Sesquipedalian** [comment]
This is key functionality. We can't call this a release candidate when this functionality is so broken. The fact that I have not yet had time to figure out what the cause is does not make any difference in that regard.

**Comment by albertlast** [comment]
A key function is image caching and this is in smf 2.0.x  broken more than a year and this in a stable release. 

Such bugs you call in software development "know issue".

End of day stop trying to find excuses,
just release the rc1.

**Comment by MissAllSunday** [comment]
Does this has to do with the scheduled tasks?  if so thats where the issue is, SMF depends on someone/thing hitting the server to trigger any task.

**Comment by Sesquipedalian** [comment]
@MissAllSunday the issue seems chiefly to be that the user's notification preferences are not being followed.

**Comment by MissAllSunday** [comment]
Ohh I see. Carry on then 😅

**Comment by smfbigguy** [comment]
It happens on my site. Sporadic notifications. Not sure why it happens cause there is no error to go with it. I was mentioned in this so that's why I replied. It is a bit annoying not knowing when you will get a notification.

**Comment by albertlast** [comment]
In the most background task is a return value a static true,
without evaluation if the task realy successfull.
https://github.com/SimpleMachines/SMF2.1/blob/ecae71521a41cf1c11fc16f8d1dc40e30bc4203b/Sources/tasks/Register-Notify.php#L135

https://github.com/SimpleMachines/SMF2.1/blob/ecae71521a41cf1c11fc16f8d1dc40e30bc4203b/Sources/tasks/MsgReport-Notify.php#L186

**Comment by MissAllSunday** [comment]
And I just realized my mail client borked my comment....

**Comment by Sesquipedalian** [comment]
FYI, in a fit of procrastination from the work I should be doing, I found some flawed logic in the functions for creating post notifications and for sending daily digest emails that is probably at least part of the cause of this. At the very least, I think it is the reason why digest emails were being sent to people who didn't ask for them. I'm not sure yet if this same flaw is also why immediate notifications were not being sent, or if there is another related flaw that I have not found yet which is causing that misbehaviour.

**Comment by betonkamil** [comment]
Come on  no longer rc 1  he's been too late

**Comment by betonkamil** [comment]
_Mod (Colin): Removed._
🙄😏😑☺🤗😚😊😁🤣
