### ISSUE TITLE
Regex masks in custom fields aren't delimited

### ISSUE THREAD

**Issue by bit2shift** [SimpleMachines/SMF#4784]
When registering or editing a regex-masked custom field, the following error is logged:
`preg_match(): No ending delimiter '^' found`

It originates from [Register.php](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Register.php#L470) and [Profile-Modify.php](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Profile-Modify.php#L1231)

Technically, I could simply surround the regex with `~`, but it'd be better if it was done in code.
```
preg_match('~' . substr($row['mask'], 5) . '~', $value)
```

**Comment by MissAllSunday** [comment]
The help section when adding/editing a profile field does indicate you need to use a valid delimeter. It might be counter-intuitive to add a pattern without delimeters.

**Comment by bit2shift** [comment]
It does on 2.1, but not on 2.0.
There's not even a mention of their requirement in the help popup in 2.1.

PS: It's not counterintuitive to have a regex without delimiters. In such cases, the flags are either passed as inline modifiers [`(?imsxXU)`] or [as arguments to the engine during initialisation](https://github.com/bit2shift/r3dVoxel/blob/master/inc/r3dVoxel/ILogger.hpp#L37) (the `R"(...)"` is a raw string, not a delimiter).

**Comment by Archer70** [comment]
Gonna have to go with @MissAllSunday on this one. The help text does show delimiters in the examples, and IMO, it's more "obvious" to have them required. I would expect to have to enter delimiters in any regex field.

**Comment by bit2shift** [comment]
@Archer70, you can't really vouch against this issue since your view of regular expressions is biased towards delimited patterns.
The same can be said for any SMF contributor who only works with languages that use PCRE (JS, Perl, PHP, Ruby, etc.).

You're also forgetting that there are people using SMF who neither work with PHP nor use delimited patterns, eg. folks working with C (POSIX library), C++ (Boost.Regex, Boost.Xpressive or C++11), C#, D, Go, Java, Python, Rust, etc.

So you either have two options:
1) Add the delimiters in code (`preg_match('~' . substr($row['mask'], 5) . '~', $value)`)
2) Fix the bloody help section by making the delimiter requirement absurdly verbose
---
<details>
<summary>Can you imagine how many people are/were misguided by this sloppy help section in 2.0?</summary>
<img alt="sloppy" src="https://user-images.githubusercontent.com/6282023/42198505-37072dce-7e80-11e8-8d47-11ea2649009b.png">
</details>

**Comment by Archer70** [comment]
k :smile:

**Comment by bit2shift** [comment]
<details>
<summary>thank_you.gif</summary>
<img alt="thank you" src="https://bit2shift.github.io/images/thank_you.gif">
</details>
