### ISSUE TITLE
Upgrader generating http urls while in https mode

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#4790]
Some content is being blocked by the browser in the upgrader because of http urls. Seems to be only the css and js urls.

**Comment by sbulen** [comment]
Could you give an example?   I don't think I've seen this.   Here's a screenshot during an upgrade I did this morning...  .css is fine, .js works (or the Continue button wouldn't work) and there are no errors in the browser...
![image](https://user-images.githubusercontent.com/23568484/41811788-4652203e-76cb-11e8-8ca6-67e7b11cc1d4.png)

**Comment by sbulen** [comment]
Also, I double-checked all URLs after the upgrade & they are all properly https://.

**Comment by Gwenwyfar** [comment]
Doesn't seem php version related, happens on 5.4, 5.5 and 7.0 all the same:

![http](https://user-images.githubusercontent.com/28991853/41813306-d30c33fa-7709-11e8-9298-1747eaf4f462.png)

**Comment by sbulen** [comment]
The only way I can reproduce the above is to try to upgrade an http:// site.   I believe those URLs are built up from Settings.php.  

What I tested:
 - No redirect, http:// forum, launched upgrade.php via https    <= Reproduced the above
 - No redirect, https:// forum, launched upgrade.php via http    <= Worked fine - everything was https://

Are you sure the forum was https:// to begin with?

The upgrader does not change the scheme, it will leave an http:// site as http:// and an https:// site as https://.    

EDIT:  Note that if you have a https redirect, everything will be https.  These variations can only exist on a site with no redirect.

**Comment by sbulen** [comment]
A correction to my note above - those paths come from 'default_theme_url':
https://github.com/SimpleMachines/SMF2.1/blob/503c62028fe991803593f00af2dbd291246edb71/other/upgrade.php#L3498

My suspicion is that the themes weren't fully pointing to https:// prior to the upgrade.

**Comment by Gwenwyfar** [comment]
What do you mean with "being https to begin with"? I have been using it as https with https urls since I installed it. Now that you mention though, the plain URL (domain.com/smf) is no longer redirecting me to https as it was doing before. Maybe a server-side issue?

I haven't actually run the upgrade yet as I'm testing it page by page, you think that might solve the issue?

**Comment by sbulen** [comment]
By "being https to begin with" I am referring to whether all the main URLs (especially $boardurl & the theme-related URLs) as seen in repair_settings.php are https.   

You can have a forum with all settings as http, but if you launch it via https (which you can do if you have an SSL certificate) it will kinda sorta look like your forum is https.   But you can fall out of https back to http.   Which sounds like what is happening.  

Hope this makes sense.  

You can confirm by running repair_settings.php - use the 2.0 version prior to attempting an upgrade.

**Comment by sbulen** [comment]
Just confirming - is this the problem you are seeing?
![image](https://user-images.githubusercontent.com/23568484/41820972-d158b044-778e-11e8-9fbc-e3e5a1c14334.png)

**Comment by sbulen** [comment]
This is my theory (not yet confirmed by Gwen...).   To reproduce:
 - The forum is http - $boardurl & all major urls (e.g., themes) are http
 - There is an SSL cert on the domain
 - The upgrader was invoked via https, e.g., `https://myforum.com/upgrade.php`

If you follow the above steps you get the screenshot in the prior message & the formatting/theme is broken.  

The real question is what to do about it - if anything.  I see 3 options:
 1. Do nothing.  If we see this, tell folks to invoke the upgrader via http
 2. Ignore the https - redirect to http & continue; the forum will remain http and the upgrader will behave properly
 3. Assume they want to convert to https & change all URLs/settings accordingly

My preference is 1.  The downside of 1 is we may see a lot of these issues when we go to GA.  If folks are concerned about this & agree, 2 may be preferable.  I don't like 3 - I don't like making assumptions.

**Comment by sbulen** [comment]
Hmmm...   Option 4...  I suspect using relative paths for all such resources will solve the issue (as the scheme is not specified).   I'll experiment with that & report back.

**Comment by sbulen** [comment]
Option 4, relative paths, works great, BUT...  The upgrader attempts to honor all settings, including the theme_dir & theme_url settings.  Using relative paths assumes the location is under the forum root.  Two completely different sets of assumptions.  I think we need the upgrader to continue to honor the theme_url setting, thus, relative paths won't work.  

I'm back to 1 or 2, above.  Input welcome.

**Comment by Gwenwyfar** [comment]
Yes, the screenshot is the same problem I see. And yep, repair_settings shows most URLs as http. So everything you said on how to reproduce it matches.

My first question is though, isn't everywhere else already doing option 3? So why not do the same here?

Relative paths sounds like a better idea though, if it can be done.

**Comment by albertlast** [comment]
Option 5. check if the upgrader is called under https and if the forum run under https,
when this is not the same stop the upgrade.

**Comment by sbulen** [comment]
Yep.  Its option 5.

**Comment by sbulen** [comment]
Went with option 6.  If the upgrader is called under https, then tweak the theme setting for https.  
Similar idea, friendlier to the user.  

Submitted PR #4807
