### ISSUE TITLE
User Actions on mobile - a nit

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4793]
User Actions for guests may be empty under some circumstances - I wonder if it should be there at all if it is empty.  See photo 2.  

(EDITS a portion of this issue was moved to #4713 ....   This report/fix should focus on the empty User Action message box...)

![useraction2](https://user-images.githubusercontent.com/23568484/41812054-41c33562-76d0-11e8-9a8f-c1e4cfda6510.jpg)

**Comment by Gwenwyfar** [comment]
Can you refer n1 onto #4713? n2 could be minor too, but will need to confirm it first.

**Comment by sbulen** [comment]
OK - I'll narrow this one down to n2.
