### ISSUE TITLE
Language strings review

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#4798]
So here is the discussion for the language strings review. What criteria should we follow to achieve this?

Looking at the first file of the language folder (Admin.language.php), in the first strings we can find things like:

`$txt['admin_boards'] = 'Boards and Categories';`
`$txt['admin_members'] = 'Manage Members';`
`$txt['admin_censored_words'] = 'Censored Words';`
`$txt['admin_reserved_names'] = 'Reserved Names';`
`$txt['admin_modifications'] = 'Modification Settings';`
`$txt['admin_server_settings'] = 'Server Settings';`
`$txt['admin_maintain'] = 'Enable Maintenance Mode';`
`$txt['admin_title'] = 'Forum Title';`

And a little bit further;
`$txt['cookie_name'] = 'Cookie name';`

What to do with them? Everything to lowercase?
What about "Boards and Categories"? This one is about two names and I believe that should remain uppercase, in this particular case.

Thoughts are welcomed :)

**Comment by Gwenwyfar** [comment]
What I have personally done when translating is that I left the menu names in uppercase (except for the "and" and similar words), and then also left feature/menu names in uppercase when they are mentioned in the help texts and tooltips. ex: A tooltip speaking of the Private Messages feature is uppercase. 

Pretty much everything else went to lowercase, including dashed words (still one single word, only the first letter is uppercased).

**Comment by wintstar** [comment]
I think that should be left to the translator himself. There is different spelling in each country. At least it should be possible to translate it without great effort, depending on the country, as is customary in the national language.

**Comment by Gwenwyfar** [comment]
This is about the default English files. Other languages are decided by their respective translators :)

**Comment by wintstar** [comment]
> This is about the default English files. Other languages are decided by their respective translators :)

Yeah, I know it's about the english language files. These are, after all, the prerequisite for translation.

Have you read this

> At least it should be possible to translate it without great effort, depending on the country, as is customary in the national language.

**Comment by Gwenwyfar** [comment]
I'm sorry but that doesn't make much sense. We are discussing changes to the English strings, not translation.

**Comment by wintstar** [comment]
I'll try to explain it differently. With some language strings it is not easy to translate because it is not always possible to translate from English text 1 to 1. With some language strings it is not always understandable what is meant by the text. Therefore I think it should be easy to translate the English texts. 
So think of the translators who will translate it  :blush:

**Comment by illori** [comment]
some of what you list seem to be the header text for pages in the admin panel. i think it is fine to keep them as is and not change them at all. now if they are not in the header location then maybe we could consider changing it.

**Comment by frandominguezl** [comment]
Yes @illori that's because I picked Admin.language.php, I'm sure if I choose any other file I'd have to change a lot of strings but yes, I'll always look for the best solution having aesthetics in mind.

@wintstar What I plan to do here is just to convert some initial letters from some words from uppercase to lowercase, basically because they don't need to be uppercase. The translation will remain the same, probably.

**Comment by illori** [comment]
you might get more input posting this on the forums instead of github as not all translators or team members are on github.

**Comment by Gwenwyfar** [comment]
Another consistency review should be done on email vs e-mail. No idea which we should use, but either way, we should be using only one, not both. You can get them with a mass replace followed by a revision.

**Comment by wintstar** [comment]
@d3vcho  yes the translation does not need to be changed.

**Comment by frandominguezl** [comment]
@wintstar This is not about translations, this is about the original text strings that the English version will use.
Each translator can translate the strings as they want. I personally, in the Spanish translation I tried to avoid using capital letters when not needed; this is the purpose of this issue/discussion and the already opened PR I created.

Is it clear now? :)

**Comment by frandominguezl** [comment]
PR got merged, so I'm closing this.
