### ISSUE TITLE
alerts errors

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4801]
i used my test account to send a PM to another user, the other user is admin. the following errors have been generated after viewing the alerts drop down.
Guest 							 							Today at 09:32 am 							 							 							61ef6fa4e149345bcbb60a0ab3f79671 						 						 							 							Type of error: Undefined  							 							8: Undefined index: is_admin 							 							http://localhost:8080/github2.1/index.php?action=profile;area=alerts_popup;u=1  							 													 D:/wamp/www/github2.1/Sources/Security.php (Line 909)

Guest 							 							Today at 09:32 am 							 							 							61ef6fa4e149345bcbb60a0ab3f79671 						 						 							 							Type of error: Undefined  							 							8: Undefined index: permissions 							 							http://localhost:8080/github2.1/index.php?action=profile;area=alerts_popup;u=1  							 													 D:/wamp/www/github2.1/Sources/Security.php (Line 918)-

Guest 							 							Today at 09:32 am 							 							 							61ef6fa4e149345bcbb60a0ab3f79671 						 						 							 							Type of error: General  							 							2: array_intersect(): Argument #2 is not an array 							 							http://localhost:8080/github2.1/index.php?action=profile;area=alerts_popup;u=1  							 													 D:/wamp/www/github2.1/Sources/Security.php (Line 918)

Guest 							 							Today at 09:32 am 							 							 							61ef6fa4e149345bcbb60a0ab3f79671 						 						 							 							Type of error: Undefined  							 							8: Undefined index: buddies 							 							http://localhost:8080/github2.1/index.php?action=profile;area=alerts_popup;u=1  							 													 D:/wamp/www/github2.1/Sources/Load.php (Line 1413)

Guest 							 							Today at 09:35 am 							 							 							61ef6fa4e149345bcbb60a0ab3f79671 						 						 							 							Type of error: Undefined  							 							8: Undefined index: is_guest 							 							http://localhost:8080/github2.1/index.php?action=profile;area=alerts_popup;u=1  							 													 D:/wamp/www/github2.1/Sources/Load.php (Line 1432)

these were duplicated to add up to 30 errors total in the error log.

clicked on the alerts drop down again and 30 more errors were generated, all as the guest user

i can post the backtrace if requested.

**Comment by MissAllSunday** [comment]
Yep, the backtrace will be handy, I'm guessing this has to do with the alert system trying to make use of stuff that hasn't been set yet

**Comment by illori** [comment]
Type of error: General
    Error message: 2: array_intersect(): Argument #2 is not an array
    File: D:/wamp/www/github2.1/Sources/Security.php
    Line: 918
    URL of page causing the error: http://localhost:8080/github2.1/index.php?action=profile;area=alerts_popup;u=1

Backtrace information


    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$line in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326
    #0: smf_error_handler()
    Called from on line 0
    #1: array_intersect()
    Called from D:\wamp\www\github2.1\Sources\Security.php on line 918
    #2: allowedTo()
    Called from D:\wamp\www\github2.1\Sources\Load.php on line 1432
    #3: loadMemberContext()
    Called from D:\wamp\www\github2.1\Sources\Profile-View.php on line 266
    #4: fetch_alerts()
    Called from D:\wamp\www\github2.1\Sources\Profile.php on line 843

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$line in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326
    #5: alerts_popup()
    Called from on line 0
    #6: call_user_func()
    Called from D:\wamp\www\github2.1\Sources\Profile.php on line 734

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$line in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326
    #7: ModifyProfile()
    Called from on line 0
    #8: call_user_func()
    Called from D:\wamp\www\github2.1\index.php on line 150

**Comment by illori** [comment]
Type of error: Undefined_vars
    Error message: 8: Undefined index: permissions
    File: D:/wamp/www/github2.1/Sources/Security.php
    Line: 918
    URL of page causing the error: http://localhost:8080/github2.1/index.php?action=profile;area=alerts_popup;u=1

Backtrace information

    #0: smf_error_handler()
    Called from D:\wamp\www\github2.1\Sources\Security.php on line 918
    #1: allowedTo()
    Called from D:\wamp\www\github2.1\Sources\Load.php on line 1432
    #2: loadMemberContext()
    Called from D:\wamp\www\github2.1\Sources\Profile-View.php on line 266
    #3: fetch_alerts()
    Called from D:\wamp\www\github2.1\Sources\Profile.php on line 843

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$line in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326
    #4: alerts_popup()
    Called from on line 0
    #5: call_user_func()
    Called from D:\wamp\www\github2.1\Sources\Profile.php on line 734

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$line in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326
    #6: ModifyProfile()
    Called from on line 0
    #7: call_user_func()
    Called from D:\wamp\www\github2.1\index.php on line 150

**Comment by illori** [comment]
Type of error: Undefined_vars
    Error message: 8: Undefined index: is_admin
    File: D:/wamp/www/github2.1/Sources/Security.php
    Line: 909
    URL of page causing the error: http://localhost:8080/github2.1/index.php?action=profile;area=alerts_popup;u=1

Backtrace information

    #0: smf_error_handler()
    Called from D:\wamp\www\github2.1\Sources\Security.php on line 909
    #1: allowedTo()
    Called from D:\wamp\www\github2.1\Sources\Load.php on line 1432
    #2: loadMemberContext()
    Called from D:\wamp\www\github2.1\Sources\Profile-View.php on line 266
    #3: fetch_alerts()
    Called from D:\wamp\www\github2.1\Sources\Profile.php on line 843

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$line in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326
    #4: alerts_popup()
    Called from on line 0
    #5: call_user_func()
    Called from D:\wamp\www\github2.1\Sources\Profile.php on line 734

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$line in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326
    #6: ModifyProfile()
    Called from on line 0
    #7: call_user_func()
    Called from D:\wamp\www\github2.1\index.php on line 150

**Comment by illori** [comment]
Type of error: Undefined_vars
    Error message: 8: Undefined index: is_guest
    File: D:/wamp/www/github2.1/Sources/Load.php
    Line: 1432
    URL of page causing the error: http://localhost:8080/github2.1/index.php?action=profile;area=alerts_popup;u=1

Backtrace information

    #0: smf_error_handler()
    Called from D:\wamp\www\github2.1\Sources\Load.php on line 1432
    #1: loadMemberContext()
    Called from D:\wamp\www\github2.1\Sources\Profile-View.php on line 266
    #2: fetch_alerts()
    Called from D:\wamp\www\github2.1\Sources\Profile.php on line 843

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$line in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326
    #3: alerts_popup()
    Called from on line 0
    #4: call_user_func()
    Called from D:\wamp\www\github2.1\Sources\Profile.php on line 734

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$line in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326

    Notice: Undefined property: stdClass::$file in D:\wamp\www\github2.1\Themes\default\Errors.template.php on line 326
    #5: ModifyProfile()
    Called from on line 0
    #6: call_user_func()
    Called from D:\wamp\www\github2.1\index.php on line 150

**Comment by MissAllSunday** [comment]
I cannot replicate the issue using php 7.1

On what page are you in when you're trying to view the drop down?

Is it actually the alert dropdown? it was my understanding that pms were shown on their own dropdown.

**Comment by frandominguezl** [comment]
Just wanted to say that I can replicate the error using PHP 7.1, it happens when you click on the "My Messages" dropdown.

**Comment by MissAllSunday** [comment]
Yeah but whats the page you are in when you click on it? this error really depends on where you are and what you were doing when you clicked that dropdown.

Did you did a refresh on a page? did you log out and then log in?

**Comment by frandominguezl** [comment]
I logged out from the admin account to send the PM to the admin one, then logged back in and opened the dropdown from the board index. It also happened if I open it from the error log and then refresh the page. Those are the only situations I tried.

**Comment by illori** [comment]
I have php 5.something I did not log out, I believe I got the error on the
error log page and index page.

**Comment by MissAllSunday** [comment]
Yeah but again, where were you?  on what page? did you refresh the page or not?  on which dropdown?  I need more details

**Comment by illori** [comment]
Alerts drop-down. I know I was on the admin error log page at least one
time the error happened. I am not sure if I refreshed the page or not since
I got the error the previous time.

**Comment by illori** [comment]
i changed to the index, clicked on the alerts text to open the drop down, hovered on the admin button and went to the error log, it increased by 30 errors. when in the error log, clicked on alerts, refreshed the page and the error log increased by 30 errors. i did NOT refresh the page the second time i clicked on alerts.

**Comment by sbulen** [comment]
My confusion here is that PM alerts are on the messages dropdown,  not the alerts dropdown...  In user prefs, the option to receive alerts for PMs is greyed out/protected, with help text explaining this.

So...   Why are you going to the alerts dropdown for PMs?   Are you able to configure alerts for PMs somehow?

**Comment by illori** [comment]
there is no new alert showing. just posting the steps that were completed and what has happened.

**Comment by sbulen** [comment]
Ah, ok.

I haven't been able to reproduce this.  I have tried to reproduce it in my linux environments so far.   Looks like you're using a wamp env.  I'll try there next...

**Comment by sbulen** [comment]
Are you working in a vanilla 2.1 install?   Or an upgraded 2.0 environment?

**Comment by illori** [comment]
it has always been a 2.1 install, upgraded daily for years to github version.

**Comment by sbulen** [comment]
Do you do a new install?  Or just overwrite the code?

If you just overwrite the code without doing an install, you may have a difference between the db and the code.    You should try to reproduce after doing an install.

(A column was added to the error log table to support the backtrace... )

**Comment by illori** [comment]
Override. If I have time I will try a new install.

**Comment by sbulen** [comment]
There were changes to notifications default values as well.    I believe these db changes are why you have these errors.   Your code and db are out of sync.

**Comment by illori** [comment]
i run upgrade.php when i override the code, where are the changes and i can compare to my database?

**Comment by sbulen** [comment]
Examples that may affect behavior include:
https://github.com/SimpleMachines/SMF2.1/commit/d9203d47b4183a605fcf0e9e60e6f9517ea3a235#diff-d6f74e978f1d734a838e3b2e2336b695
https://github.com/SimpleMachines/SMF2.1/commit/7f15e55440092d6fd9d64593059fcdb7564c3e12#diff-d6f74e978f1d734a838e3b2e2336b695
https://github.com/SimpleMachines/SMF2.1/commit/a52e629ed84087cb438043ac7cfbd4a3bd7bed64#diff-6489f80a747780508f46c1c916963fb9

Doing an upgrade may address the concern.  Sorry my interpretation of install/overwrite may have sent us down a wrong path.  

However...  I have always doubted that beta-to-beta upgrades are 100% effective...  Too many possibilities of layered updates/corrections (such as the above) not ending up correctly.  

So, I would still like to know if an install exhibits the same behavior.   (Or a 2.0 => 2.1 upgrade.)  

I cannot replicate on either.

**Comment by sbulen** [comment]
@d3vcho - can you replicate on a fresh install?   Or are you doing beta-to-beta upgrades also?

**Comment by frandominguezl** [comment]
I do the same as Illori but I don't run upgrade.php. I'll try to make a fresh install later today.

**Comment by frandominguezl** [comment]
Alright so for anyone looking at this, I've been able to reproduce this. It's weird. Steps to reproduce **(on a new install)**:

- Log out from your admin account and create a new account
- Send a message to the admin account from the new one
- Log in back in the admin account and click on the "Alerts" dropdown

As soon as you navigate elsewhere, a few errors will appear in the log. Some notes;

- If you read the message, the errors will still appear
- If you mark the alert notification as read, the errors will stop appearing
- If you create a third account and check the behaviour of the alerts, errors will still appear even if you don't send any message to the admin account*

_* I would like to test if this still happen on a fresh install even without sending a message_

**Comment by Archer70** [comment]
Aha! So it looks to me like the issue is not related to personal messages, but the alert you get when a new member registers. 

![Popup](https://image.ibb.co/jqzbSJ/Screenshot_from_2018_07_04_14_30_14.png)

I get seven new errors whenever I view the alerts box after someone registers, regardless of whether or not they send a PM.

Will continue investigation and hopefully get this one closed.

**Comment by sbulen** [comment]
Verified - good diagnostics, @d3vcho !   

What I had been doing differently is registering the new users via the admin register function.  As Archer says, it fails when someone uses the 'signup' function.  

The error count increases any time you go near that alert link.

**Comment by illori** [comment]
that could be it, i got several user just signed up alerts present in the drop down.
