### ISSUE TITLE
"Duplicate column ip_low5" on upgrade

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#481]
Leaving this as a note so I don't forget it...

2.1 adds some new columns to the ban table to handle ipv6

If your db already has these columns, the upgrade will fail:

```
 *  +++  Adding new columns to ban items...Duplicate column name 'ip_low5'
```

However, this only shows if you're using command line - not if  you run it from your browser.

We need to figure out a solution for that.

**Comment by jdarwood007** [comment]
Well the odd thing is I thought SMF silently ignored those errors during the upgrade.  Its how that process is supposed to work..

**Comment by Oldiesmann** [comment]
It's supposed to, but for some reason it's not. I wonder if the error numbers changed in 5.5?

If I delete the new columns in the bans table, it gets slightly further before it croaks:

```
 *  +++  Adding new columns to log_packages ..Duplicate column name 'credits'
```

**Comment by Oldiesmann** [comment]
After further investigation, I figured out what's going on here...

Line 2553 of upgrade.php:

```
$result = $smcFunc['db_query']('', $string, 'security_override');
```

Last few lines of smf_db_query:

```
if (empty($db_unbuffered))
    $ret = @mysql_query($db_string, $connection);
else
    $ret = @mysql_unbuffered_query($db_string, $connection);

if ($ret === false && empty($db_values['db_error_skip']))
    $ret = smf_db_error($db_string, $connection);
```

When we get through all the checking in smf_db_error, because nothing's defined, it just die()'s with the error message.

Looks like our best option here would be to either stop using $smcFunc['db_query'] in the upgrade, or move the error-handling stuff from upgrade.php to the db files.

**Comment by Oldiesmann** [comment]
Alternately, we could also just add an optional parameter to smf_db_query telling it to just return false when there's an error. That would trigger the error-handling functionality in upgrade.php and should fix this issue.

**Comment by emanuele45** [comment]
It may be related:
http://www.simplemachines.org/community/index.php?topic=497135.0

**Comment by Oldiesmann** [comment]
Yep, that's the same issue. Seems the fix suggested in that topic would be the best fix.
