### ISSUE TITLE
Warning : mysqli_stmt_bind_param() expects parameter 1 to be mysqli_stmt, boolean given in 

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#4810]
Warning: mysqli_stmt_bind_param() expects parameter 1 to be mysqli_stmt, boolean given in ...\Subs-Db-mysql.php on line 994.
Warning: mysqli_stmt_execute() expects parameter 1 to be mysqli_stmt, boolean given in ...\Subs-Db-mysql.php on line 995.

Way to reproduce;
1) Enable Paid subscriptions
2) Create a dummy one
3) Leave mail accounts empty and visit paid subs page on user profile

**Comment by frandominguezl** [comment]
Which version of PHP are you using? I can't reproduce the error following those steps.

**Comment by XinYenFon** [comment]
PHP Version(s): 5.6.35 / 7.0.29 / 7.1.16 / 7.2.4
MySQL: 5.7.21

**Comment by frandominguezl** [comment]
What do you mean in point 3? Like, the PayPal emails and the email for correspondence?

**Comment by XinYenFon** [comment]
second part of that page yes.

**Comment by frandominguezl** [comment]
All I get following those steps is: "
An Error Has Occurred
Sorry, the admin has not yet finished setting up paid subscriptions. Please check back later."

This is my current setup;
MySQLi version: 10.1.33-MariaDB
PHP: 7.2.6
Server version: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6

**Comment by XinYenFon** [comment]
Its mistake from my side I forgot to run upgrade.php
