### ISSUE TITLE
Package manager button order.

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#4815]
2.1 beta 4 noticed the button order in 2.1 package manager is the opposite way around compared to SMF 2.0    Now I realise this isn't a major issue, but for consistency, and not to confuse long time users, would it not be an idea to have these the same as SMF 2.0, not sure I like delete as the fist option.  A couple of screenshots attached.

![2pm](https://user-images.githubusercontent.com/6047983/42294576-f26c440a-7fd9-11e8-90b8-4672cc4a0b4b.png)
![21pm](https://user-images.githubusercontent.com/6047983/42294583-fb92af92-7fd9-11e8-854e-86c3dc6c4efe.png)

**Comment by Gwenwyfar** [comment]
I think they are actually only inverted because of a float.

**Comment by illori** [comment]
a lot of the button orders were changed in SMF 2.1, i am not sure this is actually a bug or they wanted it this way.

**Comment by lurkalot** [comment]
Can't see why they would want it in this order, delete shouldn't be the first option in the row, it's tempting fate, as you need to uninstall first.  Also it's been the other way around for years which has worked fine.

**Comment by wintstar** [comment]
The order of the buttons makes logical for me in 2.1*.

1. Delete
2. List files
3. Deinstall / Install

This is the order in which you proceed or not. I wouldn't change the current order.

**Comment by lurkalot** [comment]
Well you could proceed in that order but you'll be left with a real mess to deal with.

**Comment by wintstar** [comment]
If you don't know that an installed package needs to be uninstalled first, this is not the problem of the others who know that.

**Comment by Arantor** [comment]
There is a fair amount of the forms in 2.1 that put the “most significant/relevant” action on the right, but it’s not consistent everywhere.

**Comment by wintstar** [comment]
Wouldn't it be better to show the Delete Button only if the package is not installed or uninstalled?

**Comment by illori** [comment]
what if you manually uninstalled the package as it would not uninstall any other way, then you cannot delete the package using the "normal method" ?

**Comment by Gwenwyfar** [comment]
The order wasn't changed, so this is technically a minor "bug" because of floats... Feel free to submit a fix. Considering there are floats elsewhere also, it's not unlikely that other cases where order got inversed are the same.

**Comment by XinYenFon** [comment]
@illori examples are welcomed :)
@Arantor do you mean on admin sections some buttons are on left ?

**Comment by Arantor** [comment]
No, I mean that the buttons are on the right, but the focus of them is inconsistent.

Quick reply, the order of buttons is: Save Draft | Preview | Post
- the most important button is on the right hand side

Thread buttons: Reply | Add Poll | Mark unread | Print | No alerts or emails
- the most important button is on the left, and is even recoloured

Modify board: Delete board | Modify
- the most likely button to be pressed (and the safest one) is on the right hand side

Smiley Sets: New Smiley Set | Delete Selected
- kind of a push, but not sure the delete button is the one most likely to be pressed

Attachment Directories: Add Path | Save
- could easily go either way as to which one is the more likely to be pressed

The trend seems to be 'most significant button to the right', for which the package manager as outlined would follow consistently.

**Comment by XinYenFon** [comment]
I can't comment on "order" thing I'm okay with decided order, but Reply button on topics has different color.

**Comment by XinYenFon** [comment]
We can solve this with two different way;

1) bringing back to old button container and floating based on it
2) Changing code to respect the old order
*) or ofc leave it as is.

**Comment by Gwenwyfar** [comment]
I don't think the button container should have been removed. The problem with the order is one reason. It is also useful for positioning/margins and to make it easier to identify/style it.
