### ISSUE TITLE
Poster's Avatar Overflow

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#4818]
Not sure if this has been addressed before, 
If an admin chooses to set the max avatar upload size to (for example) 180px
the avatar overflows in the topics&posts 
![overflow](https://user-images.githubusercontent.com/20267363/42345329-419dd122-809f-11e8-9140-0b90b96ca891.png)

So I think a **max-width:100%;** should be added, or such

**Comment by Gwenwyfar** [comment]
Probably better to make the poster info area's width auto-adjustable as in 2.0

Edit: And I may only be thinking of it as auto-adjustable because I had to fix it there... heh

**Comment by Arantor** [comment]
The problem is that the poster info area is floated left - and the main post area has a margin-left on it to accommodate it. (160px and 175px respectively)

Changing that gets... complicated unless willing to entertain things with flexbox at this stage.

**Comment by SychO9** [comment]
And the profile as well, I don't know about auto adjusting, but either an **overflow hidden** property or **max width 100%** would do just fine.

![overflow2](https://user-images.githubusercontent.com/20267363/42377749-efd41564-8124-11e8-8a6d-74b882c41054.png)

**Comment by Gwenwyfar** [comment]
The margin-left isn't really necessary, the main problem is that the poster area can become erratic with all sorts of sizes if a .poster width isn't defined. Maybe setting a size limit based on the avatar width instead, among the inline css definitions.

(And this is one more thing that would have been easily solved with sass, but oh well, too late for that at this point).

**Comment by Arantor** [comment]
Except it is defined, it’s 160px. And you’d still need to set that left margin anyway to give some space between the poster and the post, which needs to factor in whatever width you have set up for the poster...

**Comment by Gwenwyfar** [comment]
Exactly my point, and we can't remove it (which would be one solution to this if it didn't look terrible).

And that's not the only way to solve spacing with floats ;)

**Comment by Arantor** [comment]
It can be fixed other ways, sure, but not without some fairly significant reworking in other ways (not just to fix the RTL case but also the mentality that this was done deliberately to make it easy to switch the poster to the other side)

**Comment by Gwenwyfar** [comment]
I find editing a single selector to change sides and margin an easier solution than having to edit two different ones. 

And it could be personal preference but having to calculate two different sizes in different places also isn't an optimal solution to spacing.

**Comment by DiegoAndresCortes** [comment]
Flexbox is the best aproach for this imo
We have done it in some of our themes when we wanted to match the height of the poster with the postarea

**Comment by SychO9** [comment]
#4953 #4947
