### ISSUE TITLE
Post header & post icons controlled by Source

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#4824]
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Post.php#L1325-L1382

Self explains.

**Comment by jdarwood007** [comment]
With CSS you can still effectively target these correctly though.  Is this necessary to push back into a template?

**Comment by XinYenFon** [comment]
You can't change the icons say if they are font-icons or sprite icons. Also why mix source & template in source side (vice-versa) ?

**Comment by jdarwood007** [comment]
Well we would have to expand beyond this as getMessageIcons in Subs-Editor is what sets up everything to use the png files not a sprite.

This would only work well for built in icons.  Otherwise it would get complicated to support this for the edit/add/manage message icons and supporting message icons for just selected boards.

**Comment by Gwenwyfar** [comment]
This is the same case as smileys, we can't really change them and let people modify them at the same time without replacing it with a system that auto-builds sprites or something of the sort.

**Comment by XinYenFon** [comment]
This is not a user-side request, its more dev request. Because with these limitations you can't create a theme without creating a mod to support it. You can alter the JS files to allow the change (or adapt the system you are using) but since the output is locked in source you need to release a mod to change that place which also breaks other themes which is not using the theme's system.

**Comment by Gwenwyfar** [comment]
If it's only about moving it to templates then sure, it shouldn't be there to begin with.

**Comment by XinYenFon** [comment]
Exactly my point 😆

**Comment by Sesquipedalian** [comment]
No mod is needed. The theme can freely ignore anything in `$context['posting_fields']` and build its own posting fields instead, just the way themes in 2.0 did. If you don't like the standard content of `$context['posting_fields']['icon']`, feel free to build your own select menu in the theme file.

But I suppose we could change the content of `$context['posting_fields'][<whatever>]` from 'dt' and 'dd' elements to a list of properties and leave it to the theme to format that data.

**Comment by Sesquipedalian** [comment]
Alternatively, just add something like this in your theme file right before the loop that goes through `$context['posting_fields']`:

```
$context['posting_fields']['icon']['dd'] = '<select tabindex="2" name="icon" id="icon" onchange="showimage()">
							<option value="xx" selected="">Standard</option>
							<option value="thumbup">Thumb Up</option>
							<option value="thumbdown">Thumb Down</option>
							<option value="exclamation">Exclamation point</option>
							<option value="question">Question mark</option>
							<option value="lamp">Lamp</option>
							<option value="smiley">Smiley</option>
							<option value="angry">Angry</option>
							<option value="cheesy">Cheesy</option>
							<option value="grin">Grin</option>
							<option value="sad">Sad</option>
							<option value="wink">Wink</option>
							<option value="poll">Poll</option>
						</select>
						<img id="icons" src="' . $context['icon_url'] . '">';
```

Using that approach, you can change the content of any posting field to whatever you want right in your theme file.
