### ISSUE TITLE
Full topic notifications contain BBC, HTML code

### ISSUE THREAD

**Issue by mtomas7** [SimpleMachines/SMF#4826]
Hi all,

I'm not sure if this is related to v2.1 (I'm using Beta 4 RC1 branch install), but when user chooses to receive full message body of the message in notification, if text was formatted all that code is included in a message which doesn't look good at may confuse users and perhaps trigger spam filters. Example:

https://pastebin.com/E0j9NqP0

Is it possible that code could be removed from the notification message?

Thank you!

Reference: https://www.simplemachines.org/community/index.php?P=32d1cc244e18fe39b4a82e122fd7329e;topic=561075.msg3979087#msg3979087

**Comment by illori** [comment]
there is no beta 4 RC1 version. i assume you mean the version available on github which is beta 4.

i have disabled the admin setting dont allow post text in notifications, i enabled receive message body in e-mails in my profile, i was able to duplicate the issue and the bbc is showing in the email received.

**Comment by mtomas7** [comment]
Thank you, guys!

**Comment by mtomas7** [comment]
Hello, after testing it looks that HTML tags are still sent, like `<br>`, could anyone else test it?

**Comment by jdarwood007** [comment]
Is the `<br>` present in the normal message?  The code itself is supposed to translate <br> to "\n" which is a new line character.  My tests I didn't see it, but perhaps I don't have enough info.  If you got a example text straight from the database (smf_messages table) I can take a look and see what is going on.

**Comment by illori** [comment]
i made a post that has `<br>` in it and `&lt;br&gt;` showed up in the email received

**Comment by jdarwood007** [comment]
Can I get what the smf_messages has?

My smf_messages test data:
```
keep<br>testing<br>returns
```

I captured the smf_background_tasks as well as:
```
{"msgOptions":{"id":80,"subject":"return","body":"testing<br>not<br>working<br>","icon":"xx","smileys_enabled":true,"attachments":[],"approved":1,"send_notifications":true},"topicOptions":{"id":65,"board":3,"poll":null,"lock_mode":null,"sticky_mode":null,"mark_as_read":true,"is_approved":true,"redirect_expires":null,"redirect_topic":null},"posterOptions":{"id":21,"name":"test","email":"test@svn.test","update_post_count":true,"ip":"127.0.0.1"},"type":"topic"}
```

The email I get looks correct:

```
The text of the topic is shown below:
keep
testing
returns

Unsubscribe to new topics from this board by using this link:
```

**Comment by illori** [comment]
is your forum a new install from github or existing? mine has been upgraded so if yours has not then that would be why.

**Comment by jdarwood007** [comment]
My test one is upgraded.  I didn't see why a new forum would be needed to test out this issue.

**Comment by illori** [comment]
mine is upgraded as well, so something is different about my forum vs yours. can anyone else duplicate this issue?

**Comment by mtomas7** [comment]
I upgraded a couple of days ago to the github version and here are some examples with symbols that are still showing up on the emails:

`<br> Children&#39;s Dreamcoat&quot; at 3pm &amp;  tomorrow.&nbsp; &nbsp; :read:&nbsp;`

:read: is smiley.

Thank you!

**Comment by illori** [comment]
Please open a new issue as this one is closed.
