### ISSUE TITLE
Fatal Error in SSI examples

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#4827]
Following functions returning fatal error in ssi

* ssi_todaysBirthdays
* ssi_todaysHolidays
* ssi_todaysEvents

**Comment by MissAllSunday** [comment]
How are you using them? do you have the calendar enable?  whats the exact fatal error?  what php version are you using?

**Comment by XinYenFon** [comment]
navigate to ssi_examples.php and open those functions

**Comment by Sorck** [comment]
I cannot reproduce this using fresh install of commit a3d3e2ad2322c64337f4245106906a3a16b72df4

Today's birthdays and events are showing as expected when navigating to ./ssi_examples.php

**Comment by MissAllSunday** [comment]
Yep, cannot replicate, hence why I asked for more details.

**Comment by illori** [comment]
i cant duplicate the issue with the above mentioned items in ssi_examples.php, but i do see the below errors,
todays events
Notice: Undefined index: include_holidays in D:\wamp\www\github2.1\Sources\Subs-Calendar.php on line 752

 Notice: Undefined index: include_events in D:\wamp\www\github2.1\Sources\Subs-Calendar.php on line 754

Notice: Undefined index: include_holidays in D:\wamp\www\github2.1\Sources\Subs-Calendar.php on line 788

Notice: Undefined index: include_events in D:\wamp\www\github2.1\Sources\Subs-Calendar.php on line 813

todays holidays 

Notice: Undefined index: include_birthdays in D:\wamp\www\github2.1\Sources\Subs-Calendar.php on line 753

Notice: Undefined index: include_events in D:\wamp\www\github2.1\Sources\Subs-Calendar.php on line 754

Notice: Undefined index: include_birthdays in D:\wamp\www\github2.1\Sources\Subs-Calendar.php on line 798

Notice: Undefined index: include_events in D:\wamp\www\github2.1\Sources\Subs-Calendar.php on line 813

similar errors with todays events function as well if you want line numbers let me know.
