### ISSUE TITLE
Unable to add "answers" to the antispam questions

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#4831]
I can enter the first answer. I then click on [ Add another answer ] and have no response...  no additional textbox is added.

**Comment by Sorck** [comment]
I cannot reproduce this using commit a3d3e2ad2322c64337f4245106906a3a16b72df4 in Firefox 61, IE 11, or Opera 54 on Windows 10.

Are there any errors in the JavaScript console when trying to add an extra question and answer?

**Comment by illori** [comment]
i see the same thing, the console says "ReferenceError: addAnswer is not defined"
