### ISSUE TITLE
move topic, Redirect to the moved topic

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#484]
if you have the show post preview on message index feature enabled [current theme] [posts and topics max length of last/first post preview]

move a message to another board and make sure the box is checked to redirect to the moved topic

go back to the message index, hover over the moved message subject you will see the text of a moved topic, ideally it should show the text of the message that was moved as there is no real moved topic like 2.0 creates by default.

**Comment by emanuele45** [comment]
To me the current behaviour is the correct one: what is in the board is the moved notice (even though it becomes sort of invisible due to the automatic redirect), not the topic that has been moved.

**Comment by illori** [comment]
it just seems a bit inconsistent to me, but if it is a hassle to fix then best to leave as is.

**Comment by emanuele45** [comment]
Also I consider it useful because it tells the board where the topic has been moved that otherwise I'd have to click on the redirect to discover.

**Comment by illori** [comment]
that depends on the number of characters that shows, if there are too few it will never get to that point in the message

**Comment by Oldiesmann** [comment]
I really don't think it's worth the trouble to display a preview of the moved post instead of a preview of a message saying it was moved.

There's also not much we can do about useful information not being shown because the admin chose too small of a value for the length of the preview.

**Comment by illori** [comment]
then lets close this.
