### ISSUE TITLE
Remove MOVED: redirection topics scheduled task

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#485]
the scheduled task Remove MOVED: redirection topics is not enabled by default.

would moved topic notices that are scheduled to be removed be removed if this tasks is not enabled?

same for Remove temporary attachment files

**Comment by Oldiesmann** [comment]
Fixed in PR #498 :)

**Comment by illori** [comment]
those already running 2.1 need a fix for this in the upgrade.php script IMO otherwise their scheduled tasks will still be disabled

**Comment by emanuele45** [comment]
Let's add it here too:
1) if they are running 2.1 in the current state they should know what they are running,
2) if they don't know, it's not my fault.

**Comment by illori** [comment]
this also effects those running 2.0 and lower as it is not in the upgrade.php script
