### ISSUE TITLE
Language editor can't handle values with ) correctly with array values

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#4855]
If using the inbuilt language editor to edit an array, like the months array in index.english.php, the values currently must not have ) in them, as these are used for string matching.

Arbitrary example:
```
$txt['months'] = array(1 => 'January(Jan) Jan', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
```

Renders in the editor for `months-+- 1` as `January(JanJan`

Also, it can't handle string indexes which will make life interesting supporting the proposed fixes for #2020.

**Comment by Sesquipedalian** [comment]
Once I get this taken care of, @Arantor, will that open the way for you to submit a PR to implement the system you described in [this comment](https://github.com/SimpleMachines/SMF2.1/issues/2020#issuecomment-406408773)?

**Comment by Arantor** [comment]
```
function numeric_context(string $string, $number, bool $commaise = true): string
{
    global $txt;
    if (!isset($txt[$string]))
        return '';

    if (!is_array($txt[$string]))
        return sprintf($txt[$string], $commaise ? comma_format($number) : $number);

    if (isset($txt[$string][$number]))
        return sprintf($txt[$string][$number], $commaise ? comma_format($number) : $number);

    $numstring = (string) $number;
    for ($i = strlen($numstring); $i > 0; $i--)
    {
        $trunc = 'x' . substr($numstring, -$i);
        if (isset($txt[$string][$trunc]))
            return sprintf($txt[$string][$trunc], $commaise ? comma_format($number) : $number);
    }

    return sprintf($txt[$string]['x'], $commaise ? comma_format($number) : $number);
}
```

$string is the identifier in $txt ('ordinals' in my example), $number is the number you're looking for, $commaise is whether to comma-format the number (typically yes)

You might need to tweak the above code, this came from my PHP 7 codebase complete with type hints, but I don't think 2.1 is 7.0+ only... not that I've really paid any attention. Might also deserve a better name but I couldn't think of anything at the time.
