### ISSUE TITLE
Language editor truncates weirdly on Help

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#4856]
Trying to use the inbuilt language editor on the Help language strings results in truncation of the editable string. Not sure why yet.

![image](https://user-images.githubusercontent.com/1156911/42970669-dabdb9dc-8ba1-11e8-95d5-68717bf57d3c.png)

**Comment by dragomano** [comment]
There is a some relation with using `&quot;` and line breaks. If you remove the hyphenation, the text is displayed completely.
![temp](https://user-images.githubusercontent.com/229402/43683444-46ef934a-98a5-11e8-82e0-2732490e4011.png)

P. S. By the way, maybe it makes sense to replace all "strlen" and "substr" with "$smcFunc['strlen']" and "$smcFunc['substr']" in **cleanLangString** function? (ManageLanguages.php)
