### ISSUE TITLE
br bbc

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4860]
[br bbc](https://wiki.simplemachines.org/smf/Br)

looks like in SMF 2.1 beta 4 the br bbc is no longer working
if i make a post that contains
`test[br]test` it shows in the post the exact same way, if i test in SMF 2.0 there is a line break between each of the words test.

**Comment by illori** [comment]
seems that the br bbc is not showing in the list of bbc tags you can enable, was it removed?

**Comment by jdarwood007** [comment]
Looks like it was removed and the upgrader is supposed to replace it.

**Comment by illori** [comment]
replace it with what?

**Comment by jdarwood007** [comment]
<br>.  During the upgrade process.

**Comment by illori** [comment]
i get that but it seems my forum is missing this so i want to check why. can you link to where it was added/changed?

**Comment by jdarwood007** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/2885
https://github.com/SimpleMachines/SMF2.1/pull/2991
https://github.com/SimpleMachines/SMF2.1/pull/2949

**Comment by illori** [comment]
so [br] among some others are completely removed and no longer function if used. we should document this on the wiki somewhere so we know when people ask why x bbc does not work any longer.

in attempts to duplicate another issue, i was using the [br] bbc and it was not parsed that seems because the bbc was completely removed.

i guess this can be closed.

**Comment by sbulen** [comment]
Looks like #2991 tried to replace this.  If it's not working, this looks like a valid bug to me.

**Comment by sbulen** [comment]
Sorry, read this wrong...
  If only new posts are affected this isn't an upgrade issue.

**Comment by LexArma** [comment]
I Seriously hope that removing and replacing tags was planned properly, and in that plan the need to do HUGE amounts of changes in the databases of big boards with millions of posts was taken in to account., and me trying to upgrade won't end up with my server dying on me.
