### ISSUE TITLE
changing alerts status

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4861]
i had a board i set to receive emails and alerts, i finished my testing and set it back to no alerts or emails
i checked the topics in the board and they are still set to receive emails and alerts even though i set the per board setting back to no emails and alerts. but i did not receive the email until i set the setting in a new board/topic.

**Comment by frandominguezl** [comment]
Can't reproduce the error.

**Comment by illori** [comment]
So after you set the board to alert you, then turn it off and check a topic
in the board, is that topic set for alerts?

**Comment by illori** [comment]
I tried it again and could not duplicate it, if you can't I will close it.
