### ISSUE TITLE
Installer issue - blank screen

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4866]
Just tried a simple 2.1 install & got this:
![image](https://user-images.githubusercontent.com/23568484/43054477-a16f0644-8de6-11e8-8ec4-52f674dd0386.png)

WAMP.  current version as of now.

**Comment by sbulen** [comment]
Same thing on a unix install.

**Comment by sbulen** [comment]
Upgrader seems fine on WAMP.

**Comment by sbulen** [comment]
Only clue found so far is this in the browser debugger window:
![image](https://user-images.githubusercontent.com/23568484/43055188-0cc8d03e-8dea-11e8-8b0c-c18b797fd64b.png)

**Comment by jdarwood007** [comment]
Your not getting text strings it seems.

**Comment by sbulen** [comment]
Last time this happened it was due to some cleanup.  I guess some of the tools out there (phpstorm?) erroneously report globals as unused when they're actually used.  

I don't think I'll be able to get to this any time soon.    Maybe in a couple days.

**Comment by sbulen** [comment]
@MissAllSunday - could you look into this?  My current theory is that this is due to the PR #4864 cleanup in the installer.  

Reference these old threads:
https://github.com/SimpleMachines/SMF2.1/issues/4103    (exact same symptoms)
https://github.com/SimpleMachines/SMF2.1/issues/4281
https://github.com/SimpleMachines/SMF2.1/pull/4275


(EDIT:  This is the fix that was needed last time: #4104 )

**Comment by MissAllSunday** [comment]
yeah will take a look, I found it weird that unused global vars end up being used 👅

**Comment by sbulen** [comment]
Yep...  

Normally, you declare a global in order to USE a global that already exists.  But declaring something global also MAKES it global.  If you don't declare $txt global in load_lang_file(), none of your $txt strings would be visible outside of load_lang_file() - _which is where they are loaded..._  Hard to see this, because none of the $txt strings are actually _used_ in load_lang_file().  That's what confuses some of the tools like phpstorm.  

It's like trying to follow a Shane Carruth movie.

**Comment by sbulen** [comment]
I ended up addressing this...  Any questions let me know,
