### ISSUE TITLE
Cannot properly edit ban trigger

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#4867]
Applies on 22bf54f, probably earlier too.

1. Create a ban with a trigger (doesn't matter what)
2. From the ban list, go to modify the ban you just made
3. Select modify on any of the existing ban triggers
4. Edit the value
5. Save
6. Note that the value has not updated

Type of error: General 
2: Invalid argument supplied for foreach()
 http://localhost/SMF2.1/index.php?action=admin;area=ban;sa=edittrigger
 D:/xampp_php7/htdocs/SMF2.1/Sources/ManageBans.php (Line 930)

Backtrace:
#0: smf_error_handler()
Called from unknown on line -1
#1: saveTriggers()
Called from unknown on line -1
#2: BanEditTrigger()
Called from unknown on line -1
#3: call_helper()
Called from unknown on line -1
#4: Ban()
Called from unknown on line -1
#5: AdminMain()
Called from unknown on line -1

**Comment by albertlast** [comment]
Here a proper backtrace (after I fixed the backtrace):

    #0: smf_error_handler()
    Called from F:\github\SMF2.1\Sources\ManageBans.php on line 930
    #1: saveTriggers()
    Called from F:\github\SMF2.1\Sources\ManageBans.php on line 1619
    #2: BanEditTrigger()
    Called from F:\github\SMF2.1\Sources\Subs.php on line 4853
    #3: call_helper()
    Called from F:\github\SMF2.1\Sources\ManageBans.php on line 86
    #4: Ban()
    Called from F:\github\SMF2.1\Sources\Admin.php on line 496
    #5: AdminMain()
    Called from F:\github\SMF2.1\index.php on line 150

**Comment by sbulen** [comment]
This one also needs the "has fix" label, PR identified above.

**Comment by Hatshepsut71** [comment]
I'm using SMF 2.1 RC3+ (commit d248131) with PHP 8.0.
When I'm trying to edit an existing ban trigger, I get 'HTTP Error 500' message on the white screen, and I cannot edit the trigger at all.

Forum details:

Forum version: SMF 2.1 RC3 (more detailed)
Current SMF version: SMF 2.1 RC3
GD version: bundled (2.1.0 compatible)
MySQL engine: MariaDB
MySQL version: 10.3.27-MariaDB-log
SMF file based caching: 2.1 RC3
SQLite3 database based caching: 3.7.17
PHP: 8.0.0 (more detailed)
Server version: Apache

**Comment by albertlast** [comment]
did you try the fix?

**Comment by Hatshepsut71** [comment]
Yes, the error is the same. 
But if I change PHP to 7.4, the error is gone.

**Comment by Hatshepsut71** [comment]
Maybe, it's needed to open new issue, especially for PHP 8.0 ?

**Comment by albertlast** [comment]
yea,
also check if this error happen with nightly version.

if you able to copy you board.
