### ISSUE TITLE
Please put "Use quick reply on topic display:" back as a profile setting

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#4870]
Hi,

a useful feature, please put "Use quick reply on topic display:" back as a profile setting

thanks.

![untitled 2](https://user-images.githubusercontent.com/5096676/43200506-70418896-901e-11e8-8d97-2df11167499b.png)

Please merge https://github.com/SimpleMachines/SMF2.1/issues/4871

**Comment by illori** [comment]
we have no plans to add this back, quick reply will stay enabled. if you want it added back then you will need to have a mod created to put it back.

**Comment by gevv** [comment]
@illori  How do I quick reply box  hide  the manual editing? php files 

_ because of this problem_ https://github.com/SimpleMachines/SMF2.1/issues/4749

**Comment by illori** [comment]
I don't know.
