### ISSUE TITLE
Use full editor toolbar in Quick Reply setting problem

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#4871]
Hi, 

"Use full editor toolbar in Quick Reply" setting Only the smile sets are invisible 

![notm2](https://user-images.githubusercontent.com/5096676/43202981-a496f87c-9025-11e8-8d7f-66630a891e4d.png)

![notm](https://user-images.githubusercontent.com/5096676/43203196-3607ef50-9026-11e8-8f80-a0d54ad04225.png)

--------------------------------------------------------------
![marked](https://user-images.githubusercontent.com/5096676/43202988-a8455234-9025-11e8-800d-709f002a061e.png)

![marked2](https://user-images.githubusercontent.com/5096676/43202999-ad1a1ec0-9025-11e8-9757-4c4502352bee.png)

**Comment by smfbigguy** [comment]
From what I have been told this is default for SMF 2.1

**Comment by Gwenwyfar** [comment]
Could just rewrite the language string to be more clear.

**Comment by smfbigguy** [comment]
Use smiley toolbar in quick reply  ??

**Comment by illori** [comment]
actually if that is the only change, i would be tempted to just remove the option completely. but changing the text would be easier.

**Comment by XinYenFon** [comment]
I think removing this extra not so needed setting would be best.

**Comment by Gwenwyfar** [comment]
I only wonder how does this affect the server in the number of requests, when you have a large amount of smileys in a larger forum. Other than that I don't see any use for the setting either.

**Comment by live627** [comment]
I removed the setting awhile back but put it back after someone complained. Maybe I broke it in my haste to restore it.

**Comment by Gwenwyfar** [comment]
I'm reopening this as there's still the language issue.

**Comment by woodholly** [comment]
So smiles disabled by default ?
Wasted 2 hours to find this issue and 3 hours to find where this idiotic "Use full editor toolbar in Quick Reply" located.
PS: /index.php?action=admin;area=theme;sa=reset; - down there.
