### ISSUE TITLE
Php 7 +

### ISSUE THREAD

**Issue by u3games** [SimpleMachines/SMF#4881]
No work smf forum wtih php 7.2 or higher....

**Comment by Gwenwyfar** [comment]
What version of SMF are you using?

**Comment by Arantor** [comment]
SMF 2.1 should work correctly on PHP 7.2...

**Comment by frandominguezl** [comment]
It does

**Comment by u3games** [comment]
Mm... ok, i use 2.0.15 of https://download.simplemachines.org

Close pls ^^

**Comment by frandominguezl** [comment]
You can close the issue as you're the creator. And for your information, SMF 2.0.15 is not meant to work with PHP 7.2, try with PHP 7.0

**Comment by u3games** [comment]
Thx for help ^^
