### ISSUE TITLE
can not select profile picture

### ISSUE THREAD

**Issue by replikacep** [SimpleMachines/SMF#4883]
can not select profile picture this is important

https://i.hizliresim.com/3zzJP9.png

**Comment by frandominguezl** [comment]
The url is not working

**Comment by replikacep** [comment]
bidaha try

**Comment by Arantor** [comment]
The URL just goes to a 403 error.

**Comment by replikacep** [comment]
http://sahibindenal.org/index.php
admin : admin
pasword: demo

you can take care of it

**Comment by frandominguezl** [comment]
Is it a fresh install or an updated one?

**Comment by replikacep** [comment]
new installation

**Comment by Arantor** [comment]
I successfully uploaded a new avatar to your test installation.

If this isn't working, we're going to need *way* more details than this.

**Comment by replikacep** [comment]
again I reinstalled  I've reloaded it again

the same result

**Comment by frandominguezl** [comment]
I've just tried again and it's working now.

**Comment by illori** [comment]
@replikacep you need to provide step by step directions to duplicate your issue. without those this bug report is not useful.

**Comment by replikacep** [comment]
must be : https://i.hizliresim.com/EDD4Av.png  
false : https://i.hizliresim.com/6NNLp3.png

this code is breaking the business : height: 2em;
simple thing
I do not speak english: :) I'll tell you exactly Unfortunately I do not know

**Comment by illori** [comment]
That site is not allowing anyone to view it. Please upload the images some
where else. Also are you using SMF 2.1?

**Comment by replikacep** [comment]
must be : https://preview.ibb.co/kvnRET/sshot_1.png
false :  https://preview.ibb.co/cU7CM8/sshot_5.png
I am using yes 2.1 : www.replikacep.com  1.5 years
this code is breaking the business : height: 2em;
 simple thing

**Comment by Arantor** [comment]
I still don't really understand what the problem is even with your screenshot because it's so small, it's unintelligible. Not to mention that you don't show the steps being taken along the way to get to where you're going.

Note that you can always upload images to GitHub where we will actually be able to see them.

**Comment by smfbigguy** [comment]
It looks like that when he chooses a avatar from the gallery within SMF it will not show. He has the browser console open and it is showing the css for the avatars. There is a line that reads 2em, which I would think HE thinks is the height of the avatars according to the css. Which is why they will not show for him.

**Comment by replikacep** [comment]
index.css  line : 46  	height: 2em;  : delete this

find
input, button, select {
	padding: 0 0.4em;
	height: 2em;
	line-height: 2em;
}
CHANGE
input, button, select {
	padding: 0 0.4em;
	line-height: 2em;
}

**Comment by Arantor** [comment]
That's not actually the problem he has - it's not the height of the avatar that's the problem, it's the height of the selectors themselves.

There's recent style changes forcing the heights of select tags to be no more than 2em, which is fine normally but doesn't work in this one specific case where it needs to not be doing this. (And contrary to the above suggestion, should be implemented globally.)

I think it just needs #avatar_server_stored select { height: auto; } to be defined.

**Comment by replikacep** [comment]
height: auto; 👍  sensible

**Comment by smfbigguy** [comment]
Well, he seems happy anyway, lol. I wasn't real sure what he was saying and had to zoom in on the pic but at least this is out in the open.

**Comment by Gwenwyfar** [comment]
It seems to me the only problem here is a css issue with the selectors. Thus he "can't select the avatar" because they are unusable.

`select[size]` should work to get those cases.
