### ISSUE TITLE
$context['login_cookie_times'] is not defined for all path

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4886]
Look like that exists some path where login page is called,
where the $context['login_cookie_times'] is not defined.
![grafik](https://user-images.githubusercontent.com/1782906/43561554-cf537ea8-9617-11e8-9b4b-477b496cbe2b.png)

Related smf post: https://www.simplemachines.org/community/index.php?topic=561477.0
related pr: #4863
commited by @jdarwood007 

https://github.com/SimpleMachines/SMF2.1/blob/8902c394cf9228726a66db41053fed3131a262ff/Themes/default/Login.template.php#L259

Requirements

    Calendar must be enabled
    Guests shouldn't have permissions to see Calendar

Steps to reproduce

- Bein logged, on board index, right-click the "Logout" button and select "Open in a new tab".
- On board index now click "Upcoming Calendar". You will be redirected to the login page (which needs a bit of tweak since the time to stay logged in is not working). You may now login again and check the error log. The errors are:

**Comment by frandominguezl** [comment]
I didn't know you already tracked this. I made an [issue](https://github.com/SimpleMachines/SMF2.1/issues/4888) about it as well, now closed.

**Comment by sbulen** [comment]
I get this pretty consistently after a session timeout.  It corresponds to the login form not having the time dropdown properly populated.  So another way to reproduce is to set the timeout to an hour and resume activity after an hour has passed:

![image](https://user-images.githubusercontent.com/23568484/44699260-422dfa00-aa38-11e8-8fc0-1c3ef911c98a.png)

**Comment by albertlast** [comment]
@frandominguez03 like i mention in the irc, you didn't fix the issue, you only hide error message.

The issue keep open.

**Comment by frandominguezl** [comment]
@albertlast If I haven't submitted a pull request yet its because I'm not sure how to fix it.

**Comment by SychO9** [comment]
Well, Adding the array in the kickGuest() Function located in Subs-Auth.php would fix the problem

> // Login Cookie times. Format: time => txt
>	$context['login_cookie_times'] = array(
>		60 => 'one_hour',
>		1440 => 'one_day',
>		10080 => 'one_week',
>		43200 => 'one_month',
>		3153600 => 'always_logged_in',
>	);

**Comment by SychO9** [comment]
And same for maintenance mode, $context['login_cookie_times'] is undefined

**Comment by jdarwood007** [comment]
I will look into it.  Seems I may need to call this sooner.  So many adhoc places we call the login form.

**Comment by albertlast** [comment]
Look like that still exists path where the var is not setted:
![grafik](https://user-images.githubusercontent.com/1782906/46303971-a6029000-c5ad-11e8-870e-2992c5ef488a.png)
@jdarwood007 https://www.simplemachines.org/community/index.php?topic=562437.msg3990544#msg3990544
