### ISSUE TITLE
Upgrader will not run to completion on mid-to-large forums

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4896]
It seems to freeze whenever it gets to the substep progress bar:
![upgr-freeze-1](https://user-images.githubusercontent.com/23568484/43811339-e1d630cc-9a70-11e8-97a4-ca9300ad9cd0.JPG)

I got past the above by truncating the log in question, but then this happened:
![upgr-freeze-2](https://user-images.githubusercontent.com/23568484/43811341-e431cc78-9a70-11e8-8d33-8df910cf9473.JPG)

I cannot get the upgrader to run to completion on a large forum.

**Comment by sbulen** [comment]
Two minor issues:
 - substep_text doesn't exist here:  
https://github.com/SimpleMachines/SMF2.1/blob/6c1eb12b25427f005270f9ba3382f950650c4710/other/upgrade.php#L4277

 - This action steps on the whole bar's content (substep_bar_div) & wipes out some attributes, e.g., width, causing other failures:
https://github.com/SimpleMachines/SMF2.1/blob/6c1eb12b25427f005270f9ba3382f950650c4710/other/upgrade.php#L4278

Since the substep name is listed in the debug info, I suggest using a $txt for 'Substep Progress' and making the substep bar text consistent with the step & overall progress bars.  That way it can be translated as well.  That line that steps on substep_bar_div can then be removed entirely.

**Comment by wintstar** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/4889

**Comment by sbulen** [comment]
I'll take a stab at this tonight.
The worst problem is displaying the substep name is really ugly.  
But I'll at the very least get it working & functional.  Folks can enhance the aesthetics later...
