### ISSUE TITLE
error: rmdir Smileys/default no such file or directory found

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4898]
+++  Deleting the old default smiley directoryError: rmdir(D:\wamp\www\github2.1\Smileys/default): No such file or directory File: D:\wamp\www\github2.1\upgrade.php(1919) : eval()'d code Line: 3 done.

i checked and no such folder is in the smiley's directory, so it cant delete it.

@sbulen can you check this?

**Comment by illori** [comment]
also we should have some type of alert to those running the upgrade.php script that the smileys will be deleted. maybe a better idea to move them somewhere else rather then delete so that if the admin was silly and did not backup they dont loose their smileys.

**Comment by sbulen** [comment]
... Or just not attempt the delete.  I'll remove that step.  Probably safest overall.
