### ISSUE TITLE
max number of days to keep a draft

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#490]
the default max number of days to keep a draft is 0, which means to keep them forever. if the admin is not told of this it could increase the size of their database by a lot.

i think this should have some default value like 5 days or so.

**Comment by XinYenFon** [comment]
else users concern about their drafts are deleted unnoticed (because the same applies).

**Comment by illori** [comment]
then a note should be added somewhere so users can see it that the drafts will be deleted after x number of days.

**Comment by XinYenFon** [comment]
agree its better to put notice on post or somewhere proper (and can be seen) after first auto-save or manual save.
