### ISSUE TITLE
Full topic notifications contain BBC, HTML code (take #2)

### ISSUE THREAD

**Issue by mtomas7** [SimpleMachines/SMF#4912]
In reference to closed issue: https://github.com/SimpleMachines/SMF2.1/issues/4826

I upgraded a couple of days ago to the github version and here are some examples with symbols that are still showing up on the emails:

`<br> Children&#39;s Dreamcoat&quot; at 3pm &amp; tomorrow.&nbsp; &nbsp; :read:&nbsp;`

:read: is smiley.

Thank you!

**Comment by jdarwood007** [comment]
@mtomas7 Can you provide the database value of the post in the messages table?  I just want to be sure to get exactly what your receiving for a test.

**Comment by mtomas7** [comment]
Several examples:
`:bravo:&nbsp; Yay! You&#39;re getting the new forum messages!`

`[quote]<br>[center][table][tr][td][table][tr][td][table][tr][td][table][tr][td][table][tr][td][color=#222222][size=2][font=arial, sans-serif][font=arial, sans-serif][font=arial, sans-serif][font=arial, sans-serif][color=#000000][font=arial, sans-serif][color=#333333][size=3][font=Times New Roman, Times, serif][color=#0000ff][size=5][font=Arial, Verdana, Helvetica, sans-serif][b]CASTING 20 YOUNG PERFORMERS[/b][/font][/size][/color]<br><br>We are auditioning young performers to perform in the Children&#39;s Choir in our fall main stage production of Andrew Lloyd Weber&#39;s &quot;Joseph and the Amazing Technicolor Dreamcoat&quot; directed by BST Artistic Director, Jeffrey Cass. There is no fee to participate and all participants will receive a t-shirt to remember this experience.<br><br>We are looking to cast 20 young performers ages 8-18 who are vocally strong, able to harmonize, and learn quickly. &quot;Joseph and the Amazing Technicolor Dreamcoat&quot; will perform 12 performances 11/23/18-12/9/18 - Fridays at 8pm, Saturdays at 3pm &amp; 8pm and Sundays at 3pm. <br><br>Your young performer MUST be able to :<br>[/font][/size][/color][/font][/color][/font][/font][/font][/font][/size][/color]<br>[list]<br>[li][color=#222222][size=2][font=arial, sans-serif][font=arial, sans-serif][font=arial, sans-serif][font=arial, sans-serif][color=#000000][font=arial, sans-serif][color=#333333][size=3][font=Times New Roman, Times, serif][color=#333333][size=3]Perform at 6 of the performances (this is 1/2 of the performances)[/size][/color][/font][/size][/color][/font][/color][/font][/font][/font][/font][/size][/color][/li]<br>[li][color=#222222][size=2][font=arial, sans-serif][font=arial, sans-serif][font=arial, sans-serif][font=arial, sans-serif][color=#000000][font=arial, sans-serif][color=#333333][size=3][font=Times New Roman, Times, serif]Attend all rehearsals on Sundays most likely from 2-4 pmOctober/November.[/font][/size][/color][/font][/color][/font][/font][/font][/font][/size][/color][/li]<br>[li][color=#222222][size=2][font=arial, sans-serif][font=arial, sans-serif][font=arial, sans-serif][font=arial, sans-serif][color=#000000][font=arial, sans-serif][color=#333333][size=3][font=Times New Roman, Times, serif]Must attend one day of tech week 11/19, 11/20, or 11/21 - there are just 3 days of tech (this is Thanksgiving Day Week)[/font][/size][/color][/font][/color][/font][/font][/font][/font][/size][/color][/li]<br>[/list]<br>[color=#222222][size=2][font=arial, sans-serif][font=arial, sans-serif][font=arial, sans-serif][font=arial, sans-serif][color=#000000][font=arial, sans-serif][color=#333333][size=3][font=Times New Roman, Times, serif]Auditions will take place at the BrightSide Theatre Rehearsal Studio, [iurl=&quot;https://maps.google.com/?q=4953+Fairview+Ave&amp;entry=gmail&amp;source=g&quot;][color=#1155cc]4953 Fairview Ave[/color][/iurl] in Downers Grove. You must attend either Saturday, August 25 from 10-12 OR Sunday, August 26 from 2-4. Each young performer will need to sing 32 memorized measures of a song of your choice. An accompanist will be provided, so please bring sheet music or you may sing a capella. There will not be a dance audition.<br><br>[url=&quot;http://r20.rs6.net/tn..jsp?f=001ItvBJxIiQ6GMR8_Ulp5yxuCN0xMoAFye7xaEDQohIQbkAGAW2Cz5b6_A2m_mnnMm81gEyTQur9ZjujC9hud7jKgphmPm6GMjxsw8nXn4q5WGNo5l8R-cRNBFuYNyjdtVjwKE441siT0pfmoej_3BG02l1u4siM4MoCi6Tp81QoRkDFyJhCbjcQ==&amp;c=O3T04B_mmRYyTVGzUgAf0ZlR3HGsbdBjaD1cKcOtQEekgE2l4-ilow==&amp;ch=uWOs8dbHIe-75xcmh_3rS-pU2REE5YNOzk6RWj7k5Rve9A7PeT1MMw==&quot;][color=blue][u]CLICK HERE[/u][/color][/url] to book your young performers audition. **If you are a past performer and have already been assigned an audition time, you do NOT need to do anything further.<br><br><br>Thank you we look forward to seeing you and your young performer. If you have any questions please call us at 630-447-8497[/font][/size][/color][/font][/color][/font][/font][/font][/font][/size][/color][/td]<br>[/tr]<br>[/table]<br>[/td]<br>[/tr]<br>[/table]<br>[/td]<br>[/tr]<br>[/table]<br>[/td]<br>[/tr]<br>[/table]<br>[/td]<br>[/tr]<br>[/table]<br>[/center]<br>[/quote]`

**Comment by jdarwood007** [comment]
@mtomas7 Try the referenced PR.  You only need to test the CreatePost-Notify.php changes.

**Comment by mtomas7** [comment]
@jdarwood007 Thank you for your work! I will only test the line:

`'MESSAGE' => trim(un_htmlspecialchars(strip_tags(strtr(parse_bbc(un_preparsecode($msgOptions['body']), false), array('<br>' => "\n", '</div>' => "\n", '</li>' => "\n", '&#91;' => '[', '&#93;' => ']', '&#39;' => '\''))))),`

As other code is for the [other ticket](https://github.com/SimpleMachines/SMF2.1/issues/4869), that is also very important to me, but currently I cannot risk people not getting all notifications, as community is about to vote to accept SMF as new forum software.

**Comment by mtomas7** [comment]
From several Notifications I received, it looks that this patch successfully solved the problem.
