### ISSUE TITLE
Undefined index: calendar_start_day

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#4913]
![image](https://user-images.githubusercontent.com/1280380/44105470-261f276c-9ff2-11e8-8de5-cc672f6ef96b.png)

This goes away after setting a start day in the Look & Layout options.

**Comment by frandominguezl** [comment]
What are the steps to reproduce?

**Comment by NanoSector** [comment]
Go anywhere in the profile settings, it'll throw this error. It's because of the way it tries to build the settings page.

Might be for new members when they're created before the calendar is enabled, I'm debugging this now.
