### ISSUE TITLE
Smiley problem - cry confused

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4918]
After upgrading to 2.1, the "cry" icons have been confused somehow.  

This is a post of all 16 smileys in 2.0:
![smileys-in-post-20](https://user-images.githubusercontent.com/23568484/44131676-82ed473c-a009-11e8-833f-98fbb3dff5ec.JPG)

And this is the same post after upgrading to 2.1:
![smileys-in-post-21](https://user-images.githubusercontent.com/23568484/44131684-8a2c88b4-a009-11e8-9ac3-ef2593658fc7.JPG)

Note that upon inspection, the cry smiley looks funky in 2.1 - look at the spaces:
![image](https://user-images.githubusercontent.com/23568484/44132001-5b1d991c-a00b-11e8-8ffd-b3ba4ecc9ba9.png)

**Comment by sbulen** [comment]
For that matter, I'm really confused why the times are different post upgrade...

**Comment by illori** [comment]
is the time zone set correctly in the users profile?

**Comment by sbulen** [comment]
This particular test was simple:  install 2.0.15, post all 16 smilies, upgrade to 2.1.

Everything was defaulted.

This timezone issue sounds familiar, I'll do some more searching...

I don't think the smiley issue is an upgrade issue.  If you modify the record (no updates, just modify & save) the smiley reappears.

**Comment by sbulen** [comment]
2.1 & 2.0 seem to default to random _- different -_ timezones.  Probably not worth worrying about.  

Still trying to figure out the cry smiley issue...

**Comment by sbulen** [comment]
Two learnings on the Cry smiley not working:
1)  When stored in 2.0, Cry looks like this:  `:&#039;(`
Left untouched after the upgrade to 2.1, it is not parsed properly.  If you open & save the message in 2.1 (without touching anything), it works.  Cry gets modified to look like this in the DB  `:&#39;(`

I believe only Cry is affected because it's the only one that uses a hex special character.  

2)  The Angel smiley doesn't work at all in either 2.0 or 2.1.

**Comment by sbulen** [comment]
3rd learning:
 3.  Most "hidden" smileys don't work unless there is trailing whitespace (space or crlf), in 2.0 or 2.1.  
![image](https://user-images.githubusercontent.com/23568484/44279535-9cdc8000-a206-11e8-8347-565281561a71.png)

**Comment by sbulen** [comment]
Part of Angel's problem is that different characters are used in different parts of the code.   O:-)  vs 0:)
