### ISSUE TITLE
Package Manager Hook install can cause error log entries

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#4926]
When installing a mod using <hooks> you may receive multiple error log entries.

```
Hook call: function "shd_parse_wikilinks" in file /sdsmf21/Sources/sd_source/Subs-SimpleDesk.php could not be called.
The callable shd_parse_wikilinks could not be called.
Hook call: function "shd_bbc_codes" in file /sdsmf21/Sources/sd_source/Subs-SimpleDesk.php could not be called.
The callable shd_bbc_codes could not be called.
```

In Packages.php we have the code that handles hooks:
```
			elseif ($action['type'] == 'hook' && isset($action['hook'], $action['function']))
			{
				if ($action['reverse'])
					remove_integration_function($action['hook'], $action['function'], true, $action['include_file'], $action['object']);
				else
					add_integration_function($action['hook'], $action['function'], true, $action['include_file'], $action['object'], true);
			}
```

The add_integration_function updates the $modSettings[$hook] with the new information.  Which can cause SMF later on to use this thinking the hook is loaded up.

Seems like it should be simple to add another parameter and have the function ignore updating the $modSettings when coming from a package manager operation.

Actually no, that won't fix it up as then later on we have this:
```
		// Assuming we're not uninstalling, add the entry.
		if (!$context['uninstalling'])
		{
			// Reload the settings table for mods that have altered them upon installation
			reloadSettings();
```

The reloadSettings() call causes $modSettings to be repopulated as well.  But wait there is more!

add_integration_function has another surprise for us.

```
		updateSettings(array($hook => implode(',', $permanent_functions)));
```

UpdateSettings does this:
```
		$modSettings[$variable] = $value;
```

Seems no mater what there isn't an easy way to escape this.

Thoughts?

This isn't a 2.1 show stopper, but a real annoyance as more people use <hooks>

**Comment by MissAllSunday** [comment]
Perhaps it would ve a good idea to not use updateSettings when adding/deleting hooks, maybe even stop using the settings table altogether and add a specific table for hooks.

**Comment by jdarwood007** [comment]
I think we should use a different table for hooks, but didn't think we would have time for 2.1 when I thought about it.

I think it could be implanted with little chance of causing any breakage.  The upgrader would have to find all integrate_* and convert them.

**Comment by live627** [comment]
Is there an inverse for `$context['uninstalling']`? Perhaps `call_integration_hook()` can check for both aforementioned variables and skip the callbacks.
