### ISSUE TITLE
install with db non-standard port

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4929]
similar fix to https://github.com/SimpleMachines/SMF2.1/commit/4abb70448660a498ff5b666f04c31f2e318a5efe needs to be added so the installer will connect to a non-default port. currently it returns error it cannot connect.

if i add the port after localhost it works fine.

**Comment by sbulen** [comment]
Also reported here:
https://www.simplemachines.org/community/index.php?topic=561973.0

**Comment by dnessett** [comment]
I tried localhost:<non-standard-port>. That seemed to work, since the instance of postgres using the non-standard-port dropped some lines into the pg_log entry, which were warnings. For the record, they were:

2018-09-01 08:30:55 PDT WARNING:  nonstandard use of escape in a string literal at character 222
2018-09-01 08:30:55 PDT HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.

However, the install still threw a critical error and couldn't get past the database connect. Anyway to get detailed information from the install script, other than using a debugger?

**Comment by dnessett** [comment]
Errata: The first sentence should read: I tried localhost:non-standard_port

**Comment by dnessett** [comment]
OK, belay that stuff about the warnings. It appears to come from pgAdmin  (I am running an old version). So, it looks like the installer isn't connecting to postgres. In case 'localhost' was being treated specially, I tried 127.0.0.1:non-standard-port and *IP address of my machine*:non-standard-port. They both failed quickly, whereas the localhost:non-standard-port took some time to fail.

**Comment by albertlast** [comment]
Please have in mind that pg 9.1 not supported any more. 
The issue with the port is known, 
Could be fixed in the next days.

**Comment by dnessett** [comment]
The version of postgresql I am using on the non standard port is 9.6

**Comment by albertlast** [comment]
@dnessett please test the pr #4987

**Comment by dnessett** [comment]
The install completes but the forum is broken. When I access index.php in the install directory, I get the following message:

ERROR: relation "smf_settings" does not exist LINE 3: FROM smf_settings ^

I then looked at the logs for both 9.1 (running on the default port) and 9.6 (running on port 5433). Both logs showed activity, so I suspect somewhere the default port is being used even though a non-standard-port is specified. Here are the pertinent entries from both postresql servers:

9.1 (default port):

2018-09-01 22:09:13 PDT ERROR:  column "pid" does not exist at character 12
2018-09-01 22:09:13 PDT STATEMENT:  SELECT
	    pid,
	    datname,
	    usename,
	    application_name,
	    client_addr,
	    to_char(backend_start, 'YYYY-MM-DD HH24:MI:SS TZ') AS backend_start,
	    state,
	    CASE WHEN waiting THEN 'yes' ELSE 'no' END AS waiting,
	    query,
	    to_char(state_change, 'YYYY-MM-DD HH24:MI:SS TZ') AS state_change,
	    to_char(query_start, 'YYYY-MM-DD HH24:MI:SS TZ') AS query_start
	FROM
	    pg_stat_activity
	WHERE
	    datname = (SELECT datname FROM pg_database WHERE oid = 470839)ORDER BY pid
2018-09-01 22:09:14 PDT ERROR:  column "state" does not exist at character 180
2018-09-01 22:09:14 PDT STATEMENT:  SELECT
	   (SELECT count(*) FROM pg_stat_activity WHERE datname = (SELECT datname FROM pg_database WHERE oid = 470839)) AS "Total",
	   (SELECT count(*) FROM pg_stat_activity WHERE state = 'active' AND datname = (SELECT datname FROM pg_database WHERE oid = 470839))  AS "Active",
	   (SELECT count(*) FROM pg_stat_activity WHERE state = 'idle' AND datname = (SELECT datname FROM pg_database WHERE oid = 470839))  AS "Idle"
2018-09-01 22:09:18 PDT ERROR:  column "pid" does not exist at character 12
2018-09-01 22:09:18 PDT STATEMENT:  SELECT
	    pid,
	    datname,
	    usename,
	    application_name,
	    client_addr,
	    to_char(backend_start, 'YYYY-MM-DD HH24:MI:SS TZ') AS backend_start,
	    state,
	    CASE WHEN waiting THEN 'yes' ELSE 'no' END AS waiting,
	    query,
	    to_char(state_change, 'YYYY-MM-DD HH24:MI:SS TZ') AS state_change,
	    to_char(query_start, 'YYYY-MM-DD HH24:MI:SS TZ') AS query_start
	FROM
	    pg_stat_activity
	WHERE
	    datname = (SELECT datname FROM pg_database WHERE oid = 470839)ORDER BY pid
2018-09-01 22:09:23 PDT ERROR:  column "pid" does not exist at character 12
2018-09-01 22:09:23 PDT STATEMENT:  SELECT
	    pid,
	    datname,
	    usename,
	    application_name,
	    client_addr,
	    to_char(backend_start, 'YYYY-MM-DD HH24:MI:SS TZ') AS backend_start,
	    state,
	    CASE WHEN waiting THEN 'yes' ELSE 'no' END AS waiting,
	    query,
	    to_char(state_change, 'YYYY-MM-DD HH24:MI:SS TZ') AS state_change,
	    to_char(query_start, 'YYYY-MM-DD HH24:MI:SS TZ') AS query_start
	FROM
	    pg_stat_activity
	WHERE
	    datname = (SELECT datname FROM pg_database WHERE oid = 470839)ORDER BY pid

9.6 (port 5433)

2018-09-01 22:08:21 PDT ERROR:  relation "smf_settings" does not exist at character 36
2018-09-01 22:08:21 PDT STATEMENT:
				SELECT variable, value
				FROM smf_settings
2018-09-01 22:11:01 PDT ERROR:  relation "smf_settings" does not exist at character 36
2018-09-01 22:11:01 PDT STATEMENT:
				SELECT variable, value
				FROM smf_settings

The 9.1 server has all tables in the smf database populated, whereas the 9.6 server has no tables in the smf database populated - that is, the database is empty (I created a smf database on both servers for the purposes of testing).

**Comment by albertlast** [comment]
With the new pr,
the pg 9.6 issue should be gone.

That pg9.1 throw error is expected since the min version is pg9.4

**Comment by dnessett** [comment]
Install worked. Bug fixed. Thanks.
