### ISSUE TITLE
default view of calendar

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4930]
current default is list view, i think this should be changed to month view. right now you go to the calendar after enabling it and think it may be broken due to showing nothing at all. the admin may not notice that list is highlighted and changing to month may make stuff show up. [this is given that there are no holidays in the given month like August]

**Comment by XinYenFon** [comment]
This is not an issue just an "old times stuff", team should inform community better. Having list as default is better compared to month.

**Comment by illori** [comment]
i dont agree with you on that, i think it should be changed. lets see what others think.

**Comment by Gwenwyfar** [comment]
I agree that calendar view is better as a default.

**Comment by Sesquipedalian** [comment]
If the list view showed a "There are no upcoming events" message, that would make it clear that nothing is broken. Beyond that, this is an aesthetic disagreement, not a practical one.
