### ISSUE TITLE
per user change default of calendar view

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4932]
i think it might not hurt to let the user select their own default for the calendar view, currently it looks like only the admin can set the default and have it set for everyone. some may like a week or list view instead of monthly and they can only switch for the current view of the calendar, when they move back to another page and back to the calendar the view does not stay.

**Comment by XinYenFon** [comment]
*Too much settings, more complex code.* In a nutshell its good but does it worth the effort ?

**Comment by illori** [comment]
not sure how much effort it would take, if only a few lines of code then i think so.

**Comment by XinYenFon** [comment]
Its not limited to this issue actually, this will lead to that (I'm not exaggerating), others may ask for other viable settings to be able controlled by user level (again I'm not saying they are or you are wrong). At that point we have massive user-based settings which confuses and overwhelms most of the users.

I have to note; even I'm using default settings on user level, I hardly think this much customization is required by more simpler users.
