### ISSUE TITLE
date for calendar in list view does not follow user selected date format

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4933]
i went in my profile and changed the date format, so the year would be last, this is reflected when showing the current time at the top of the forum. when in list view in the calendar it shows 2018-8-19 where it should show August, 19, 2018 or 8-19-2018. 

when you switch to the month view it has a drop down to select month and year, maybe worth using the same in the list view?

**Comment by Sesquipedalian** [comment]
To do this, I'd need to add the big, fat moment.js library. But I suppose users will complain if we don't...
