### ISSUE TITLE
weekly calendar view drop downs for month/year

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4937]
this view should have a drop down to change the week that is viewed not just month/year. you can change to the next month but not the next week using the drop down. the drop down that we have in the list view currently should be present here so we can easily change which week is in view.

when we change the month currently it only shows the first week of that month which may include the last week of the prior month not the complete first week of the given month.

**Comment by illori** [comment]
this is not using full screen so the mini 3 month calendar is not in view to use to modify the view of the calendar.

**Comment by Sesquipedalian** [comment]
The chevron characters in the "Week View" header bar let you navigate between weeks. But still, I see your point. To fix this and make things generally more consistent, we should datepicker inputs on both the monthly and weekly views instead of select menus.
