### ISSUE TITLE
memberslist [non-admin panel] post count not centered

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4938]
seems the posts column has colspan of 2 which makes the post count number not be aligned with the word posts, it is off to the left. if the colspan is modified to 1, then it is centered.

@Gwenwyfar can you look into this?

this is using the default columns present in the members list.

**Comment by XinYenFon** [comment]
That's because, that section has bar (statsbar), if you are testing on 0 post forum it looks weird.

**Comment by illori** [comment]
yes i am currently testing on a 0 post count forum user, maybe that is why.

**Comment by XinYenFon** [comment]
The statsbar is not showing because its 0% in 0% total (yea I know it worded bit weird but). At best we can show empty statsbar.

**Comment by illori** [comment]
how about putting the number in the middle of the bar? then only 1 column would be needed as well.

i would not mind getting rid of the status bar completely as well.

**Comment by XinYenFon** [comment]
that looks like a very good solution tbh.

**Comment by Gwenwyfar** [comment]
We could just make it a single column (which it should be anyway). Then if someone wants to hide statsbar it is also much simpler.
