### ISSUE TITLE
Allow AJAX Desktop Notifications for Alerts on wrong page

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4939]
Allow AJAX Desktop Notifications for Alerts is on the main features and options page, i think this should be moved into the notifications page as it relates to notifications.

**Comment by MissAllSunday** [comment]
Can't really be moved since that page is also used to manage the per-user notification settings and it contains a reference to the same modSettings value.

Besides, the token verification on saveDBSettings() will always fail because it wasn't really set.
