### ISSUE TITLE
admin panel alert preferences

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4940]
If i enable email alerts for all members/buddies

this setting is for all members anyway right? as it is in the admin panel, it is a bit confusing to set it for "buddies" as the admin does not know if any of the users on the forum have buddies. i think for the admin this should only be able to be enabled for all members or not at all.

also the popup here for receiving new personal message replies is incorrect, for this the admin cannot set this for all users, the popup has the user visible help text.

**Comment by Sesquipedalian** [comment]
Are you talking about the Configuration > Features and Options > Notifications subarea? If so, that panel is for setting the default options for members. The settings there apply only if the user hasn't customized them.

So it makes perfect sense for the admin to be able to set the default value for getting emailed notifications about personal messages to "Buddies." In some communities it would make sense to expect that the average user would only want to receive email notifications about PMs from buddies, so it makes sense to have the ability to set that as the default option.

The text in the help popups likewise makes sense here. Regardless whether a user is setting his own options or the admin is setting the default options, it is accurate in both cases for the help text to say "Notifications of new personal messages do not appear in the Alerts pane, but appear in the 'My Messages' list instead."
