### ISSUE TITLE
disable tfa

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4941]
seems that when you want to disable tfa, it just does it when you click on the link. i think it should require you to enter your password at least or something so you dont disable it by mistake.

**Comment by Sorck** [comment]
Are you referring to when the admin disables 2fa site wide?

Does it even need to be possible to turn it off site wide? Having options for enabled and forced makes sense.

**Comment by illori** [comment]
No in the users profile.

**Comment by Sorck** [comment]
I will get a fix out tomorrow to add a confirmation dialogue with password protection.

**Comment by illori** [comment]
@Sorck have you had time to work on this fix?

**Comment by Sorck** [comment]
@illori Yeah, I've got it working locally with a new page with a password and session token required in a POST request.

At the moment I'm cleaning up the logic a little in the 2FA system to allow mods to interface more easily by having tabs in the 2FA section, similar to many area in profile, moderate, and admin sections.

**Comment by illori** [comment]
any further updates on this?

**Comment by live627** [comment]
Yes. Here's what I've got:

![screenshot_2018-10-20 profile - disable two-factor authentication 2](https://user-images.githubusercontent.com/431799/47252993-40fac700-d402-11e8-9f62-db583a803e00.png)

**Comment by illori** [comment]
that looks good.

**Comment by illori** [comment]
we need a setting for admin to disable the TFA as well...

of course needing them to enter their password like other options in editing another users profile require.
