### ISSUE TITLE
new moderators note/delete note message

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4942]
> You successfully created a new comment. 

i think this string must be a reuse from somewhere else. i am not even sure we need the note. 

maybe something like "You successfully added a new note."

when you delete a note it says "The message was successfully deleted. " i would suggest a similar change here as well.

**Comment by frandominguezl** [comment]
`$txt['report_action_message_saved'] = 'You successfully created a new comment.';
$txt['report_action_message_edited'] = 'You successfully edited the comment.';
$txt['report_action_message_deleted'] = 'The message was successfully deleted.';
$txt['report_action_message_edit_issue'] = 'The message you\'re trying to edit isn\'t available any more. Please check if it wasn\'t deleted already.';
$txt['report_action_message_edit_cannot'] = 'I\'m sorry, you aren\'t allowed to edit this comment.';
$txt['report_action_message_delete_cannot'] = 'I\'m sorry, you aren\'t allowed to delete this comment.';
$txt['report_action_message_delete_issue'] = 'The message you\'re trying to delete isn\'t available any more. Please check if it wasn\'t deleted already.';`

To something like;
`$txt['report_action_message_saved'] = 'You successfully created a new note.';
$txt['report_action_message_edited'] = 'You successfully edited the note.';
$txt['report_action_message_deleted'] = 'The note was successfully deleted.';
$txt['report_action_message_edit_issue'] = 'The note you\'re trying to edit isn\'t available any more. Please check if it wasn\'t deleted already.';
$txt['report_action_message_edit_cannot'] = 'I\'m sorry, you aren\'t allowed to edit this note.';
$txt['report_action_message_delete_cannot'] = 'I\'m sorry, you aren\'t allowed to delete this note.';
$txt['report_action_message_delete_issue'] = 'The note you\'re trying to delete isn\'t available any more. Please check if it wasn\'t deleted already.';`

Is that good?

**Comment by illori** [comment]
personally i would replace I'm with I am and aren't with are not etc, otherwise it looks fine.
