### ISSUE TITLE
allow non-admin to hide their online status help text

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4944]
> With this setting enabled all members will be able to hide their online status from other users (except administrators). If disabled, only users who can moderate the forum can hide their presence. Note that disabling this setting will not change any existing member's status - it just stops them from hiding themselves in the future.

which users that can moderate the forum can hide their presence? for some admin they may see that as those that can do moderation actions on users posts in the forum, but i dont think that what is meant here.

**Comment by frandominguezl** [comment]
So does that part need just to be removed?

**Comment by illori** [comment]
I think so. Maybe a double check in the code to make sure the help text is
correct.

**Comment by frandominguezl** [comment]
I made some checks and there's no way users that can moderate the forum can also hide their presence, so I believe it's good to remove that sentence.
