### ISSUE TITLE
message icon selector

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#4946]
i dont know if would possibly clean up code or not.

when you create a post it has a drop down with the names of each message icon, you select it then a preview shows up on the right side

when you  want to change the message icon from the normal topic view you can click on the icon and a popup with the icons show up to pick from. i think it would be nice if we had this same selector on the new topic page instead of seeing the names of each icon.

**Comment by Sesquipedalian** [comment]
> ... from the normal topic view ...

Exactly what view are you talking about here?

**Comment by illori** [comment]
from the topic view, you can click on the message icon and change it, this view is not the same as when you are creating a topic. i think this view from the message/topic view should be the same as when creating the message and selecting the message icon.

**Comment by illori** [comment]
![image](https://user-images.githubusercontent.com/4436860/45300676-033e8080-b4dd-11e8-98ec-b3f333dd86d7.png)


make this drop down for selecting message icon to look like this one...
![image](https://user-images.githubusercontent.com/4436860/45300720-210be580-b4dd-11e8-9cf5-fd214ec52bab.png)


this might also reduce some code that creates this drop down in 2 different ways depending on view.

**Comment by XinYenFon** [comment]
This is something for next version, unnecessary delay for this version. Also both are controlled by JS not jQuery.
