### ISSUE TITLE
[Database Error] Paid Subscriptions

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#4952]
I'm getting this in my error log

```
Field 'pending_details' doesn't have a default value
File: /home/vol7_2/0fees.us/0fe_15107040/dzignmz.22web.org/htdocs/SMF2.1-release-2.1/Sources/ManagePaid.php
Line: 1138
```

**How to Reproduce**
-> Enable Paid Subscriptions (test mode)
-> Add a Subscription
-> Add a user (yourself) in the subscription with "Finished" Status

**Comment by MissAllSunday** [comment]
What DBMS are you using and whats its version?

**Comment by SychO9** [comment]
Forum version: SMF 2.1 Beta 4 (more detailed)
Current SMF version: SMF 2.1 Beta 3
GD version: bundled (2.1.0 compatible) 
MySQLi engine: Percona 
MySQLi version: 5.6.41-84.1 
PHP: 7.0.19 (more detailed) 
Server version: Apache

**Comment by MissAllSunday** [comment]
So, pending_details is marked as not null so it should be filled when a new entry to log_subscribed gets inserted, that or adding a default value but that might upset mysql strict mode and the mysql guys [aren't going to do it](https://bugs.mysql.com/bug.php?id=21532).
