### ISSUE TITLE
Old Themes language strings

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4954]
install.english.php
```
$txt['default_core_theme_name'] = 'Core Theme';
$txt['default_classic_theme_name'] = 'Classic YaBB SE Theme';
$txt['default_babylon_theme_name'] = 'Babylon Theme';
```
Can't they be removed?
Yabbse and Babylon is no longer available in 2.0. And Core didn't exist in 2.1* anymore.

**Comment by frandominguezl** [comment]
Yes, they can probably be removed. I'd have to double check.
