### ISSUE TITLE
Hook placement

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#4960]
If a function has a single hook, it should be placed as late as possible (after setting vars, performing validations, etc) so $context and other global vars can be manipulated by those using the hook.

**Comment by albertlast** [comment]
since the function should be easy to read,
the code sometimes never reached the bottom of the function -> you will no general rule,
the meet both requirements

**Comment by MissAllSunday** [comment]
Of course, the "general" in this case means "when appropiate".

And no, I'm not talking about the end of a function, I'm talking about the very moment before performing some kind of logic, for exmaple, inserting a DB record, a hook should be placed right before actually eprforming the action but after all other validations and preparations have been done.

There would be cases where two hooks are needed, one right at the start of a function and other at the end, in this case there is no action to perform, for example in a controller function.

**Comment by albertlast** [comment]
So which function needs to be fixed in your eyes?
I mean your proposal should be common sense,
like don't kill other people.

Without "target" we will never be able to close this issue.

**Comment by MissAllSunday** [comment]
There was a report on the support forum I just forgot to link to it. I already know which function needs to be changed and I'll do the change myself.
