### ISSUE TITLE
regex field on registration

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#4963]
![image](https://user-images.githubusercontent.com/3420756/44630135-ab214f00-a91e-11e8-9ab5-cd65701c3419.png)

![image](https://user-images.githubusercontent.com/3420756/44630156-e91e7300-a91e-11e8-81ec-c86409835acd.png)

I noticed there is a regex field on the registration form, it appears on the regular registation form as well as when an admin registers a new member.

If you don't put a valid regex token the registration fails:

![image](https://user-images.githubusercontent.com/3420756/44630199-60ec9d80-a91f-11e8-9b6c-b28e05cbc818.png)

**Comment by SychO9** [comment]
I have the lastest github version installed, but I don't see that field, unless I'm missing something
maybe custom modification made in your forum ?

**Comment by MissAllSunday** [comment]
Indeed, I forgot I added a custom profile field named regex
