### ISSUE TITLE
Code Select content php 

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#4965]
It doesn't work when the content of the code block is php (contains child elements rather than just text)
the problem is here (line: 1421 script.js)
> oCurSelection.setBaseAndExtent(oCodeArea, 0, oLastChild, 'innerText' in oLastChild ? oLastChild.innerText.length : oLastChild.textContent.length);

Changing it to this seems to fix the issue
> oCurSelection.setBaseAndExtent(oCodeArea, 0, oCodeArea, oCodeArea.childNodes.length);

this is also a 2.0 issue btw

**Comment by jdarwood007** [comment]
Could you give me more information to reproduce this?

Safari: Version 11.1.2 (13605.3.8)

This is the post text I tested with:
```
[code]
foreach ($context['shd_credits'] as $section)
{
echo '
<div class="roundframe noup">
', $section['pretext'], '
<hr>';

foreach ($section['groups'] as $group)
{
echo '
<div class="padding">';

// Pretty icons! :D
if (isset($group['icon']))
echo '
<img src="', $settings['default_images_url'], '/simpledesk/credits/', $group['icon'], '" alt="" class="floatleft">
<div class="shd_credits_names">';

[/code]
```

Safari seems to be able select all just fine.

However i can get Safari to not want to select both without and with your changes.  If you do a quick edit on that code block and then save, Safari fails to let you select the code block.

**Comment by SychO9** [comment]
you forgot to add '< ? php' ad the start and '? >' at the end, you'll see what I mean then

**Comment by jdarwood007** [comment]
Still works fine for me unless I do the quick edit bug I'm seeing.

**Comment by SychO9** [comment]
idk it doesn't work for me, this topic for example
https://www.simplemachines.org/community/index.php?topic=561898.0

**Comment by jdarwood007** [comment]
Well that site doesn't run 2.1.  But it also works for me there.

What version of Safari and OS X do you have?

**Comment by SychO9** [comment]
Chrome 65 Windows 10 ( although the comment says Safari it actually affects chrome mozilla safari edge )

here try this https://www.browserling.com choose w7 chrome 65 and try 
https://www.simplemachines.org/community/index.php?topic=561898.0

didn't work for me there either, so I'm pretty sure It's not an issue on my end

oh and I know it's smf 2.0, but the script is the same, and the issue is the same in 2.1 so I don't think it matters
