### ISSUE TITLE
not sending e-mail  for subscribed topics

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#4966]
Hi,

not sending e-mail and alert for  subscribed topics  after recent smf 2.1 updates

edit: no problem sending test email (admin page send test) 
no problem sending  personal message  e-mail , alert

**Comment by Sesquipedalian** [comment]
Is this the same issue as reported [here](https://www.simplemachines.org/community/index.php?topic=561369.0)?

**Comment by gevv** [comment]
No. 

Problem;  the subscribed topic and there is does not sending an email and alert

user alert and email not coming

sample;

I subscribe to a topic
a member commented to the topic
I did not receive an email and alert

**Comment by gevv** [comment]
@jdarwood007  I renew files problem not solved. strange problem..

Alert settings are configured correctly, configured user alert settings correctly

Some members do not have problems

Some members are having problems

**Comment by gevv** [comment]
@Sesquipedalian @jdarwood007    the problem continues alerts and emails are not coming

Could this editing be the problem? https://github.com/SimpleMachines/SMF2.1/commit/89d81d1b77d62c876ac5eee7b95343bbe4e5e484
