### ISSUE TITLE
Admin settings panel for hooked mods cannot be accessed

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#4970]
When a mod uses hooks to add its settings into a separate tab in the Modification Settings area of the admin centre, navigating to that tab always shows the contents of the Miscellaneous tab instead.

The cause is that #4964 moved the `call_integration_hook('integrate_modify_modifications', array(&$subActions));` line to a position below the `loadGeneralSettingParameters($subActions, 'general');` line in `ModifyModSettings()` in ManageSettings.php. Because the hook hasn't been called to add the new sub-action to the `$subActions` array yet, `loadGeneralSettingParameters()` rewrites `$_REQUEST['sa']` to the default action.

This probably also affects `ModifyFeatureSettings()` and perhaps other functions as well.

**Comment by jdarwood007** [comment]
@MissAllSunday Can you look into this?

**Comment by MissAllSunday** [comment]
Sure, will do over the weekend.

**Comment by Sesquipedalian** [comment]
I already submitted the fix. Just waiting for approval on #4971.

**Comment by jdarwood007** [comment]
Yea I saw that after I commented.  But hopefully @MissAllSunday can verify your fixes don't break the fixes just done.  Code looks fine to me and I approve.  Haven't had time to test them though.
