### ISSUE TITLE
Possible bug with permissions in Who.php

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#4972]
So I noticed this yesterday and decided to install a fresh one in a different folder to test it and result is the same.
1- I registered another account to be a regular user and went into action=who
2- With admin account accessed the admin center and went to Permissions page

![indice](https://user-images.githubusercontent.com/3318127/44730498-b901dc00-aaa6-11e8-8c89-0a39ebdc91cd.png)

So the regular user can see what the admin account is doing. It's not showing the actual text of the action, but just because it's supposed to show $txt['who_hidden']
It happens in multiple areas but I'm not sure I've visited all of them.

**Comment by DiegoAndresCortes** [comment]
BTW the title is referring to the permissions to see these actions, not to the actual permissions area, that's just one area I tested to get the picture.

**Comment by albertlast** [comment]
In my eyes it is more a posible privacy issue,
instead of a permission issue.

**Comment by DiegoAndresCortes** [comment]
Of course, by permissions I just meant the lack of permissions from the regular user to see these actions.

**Comment by Sorck** [comment]
IIRC SMF 2.X says something like "Nothing, or nothing you can see" if the user does not have permission to view a specific action. Direct the admin to ?action=admin;area=manageboards and you can see the case I have described even in SMF 2.1.

In Who.php we have ```determineActions()``` that works out what to show. Admin pages use different logic to everything else - the 'area' is treated as the action for the purposes of calculating if you can see it. Basically we just need to add permissions for every admin 'area' in the ```$allowedActions``` array.

However, it's possible the sub-actions aren't being properly permission checked. That's something to look into further.
