### ISSUE TITLE
Display edit Smileys

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#4984]
#### Description
Why this bracket at the beginning and end? It doesn't look nice.

### Steps to reproduce
Admin Center edit Smileys

### Environment (complete as necessary)
- Version/Git revision:  Beta4, last Pull Request 4716 from 01.09.2018
- Database Type: MariaDB
- Database Version: 10.1.29
- PHP Version: 	7.1.11

### Additional information/references

![smilley-2 1](https://user-images.githubusercontent.com/2753863/44943581-ea411b80-adc8-11e8-83d5-6b97a3b088ff.PNG)

(Git Template => I miss the question about the PHP version. It must be important too.)

**Comment by frandominguezl** [comment]
@SychO9 Perhaps you want to include this in your current pull request?
