### ISSUE TITLE
2FA Secrets not created using cryptographic random numbers

### ISSUE THREAD

**Issue by Sorck** [SimpleMachines/SMF#4999]
#### Description
TOTP class uses [mt_rand() which is not a cryptographically secure number generator](http://www.php.net/manual/en/function.mt-rand.php) and thus not suitable for our cryptographic purposes in generating 2FA secrets for the TOTP algorithm. 

[TOTP specs state](https://tools.ietf.org/html/rfc6238#page-4):
> keys SHOULD be chosen at random or using a cryptographically strong pseudorandom generator properly seeded with a random value
So whilst not required, it is adviseable to go cryptographically secure.

Furthermore, the 2FA backup code is not generated using cryptographically secure random numbers.

This applies to the latest version on Github.

Exposing the centralised crypto random generator used by the password salt generator would be good as we could have easy access to secure random number generators for TOTP, 2FA backup codes, and could be useful for random tokens in the authentication system. We could use [random_bytes()](http://www.php.net/manual/en/function.random-bytes.php) and its userland substitute for PHP 5.X.

**Comment by albertlast** [comment]
This is the mention userland implementation: https://github.com/paragonie/random_compat

**Comment by MissAllSunday** [comment]
Yeah, I'm planning on including that lib for users still on 5.x and do make more use of it, specially if we do implement the per machine token auth thing.

**Comment by albertlast** [comment]
mt_rand is used on ~100 placed

**Comment by Sorck** [comment]
We don't need to replace every instance of mt_rand, only those used for crypto. Basically anything in Security.php. Profile, Admin, Register, and LogInOut may also need it.

**Comment by albertlast** [comment]
Since you asked for this,
please test the pr: https://github.com/SimpleMachines/SMF2.1/pull/5077
