### ISSUE TITLE
2FA secret leaked to third party and possibly stored in browsing history

### ISSUE THREAD

**Issue by Sorck** [SimpleMachines/SMF#5000]
#### Description
When the QR code with the authenticator setup secret is generated, it is a link to a third party (Google) QR code generating service. This means the user secret is being leaked during 2FA setup via browsing history and sent to a third party. 

https://github.com/SimpleMachines/SMF2.1/blob/74e690529fe0e9ed4f7ba9c077ce10be2677b7d8/Sources/Class-TOTP.php#L348-L352

Partial improvement could be gained from a self hosted QR code generation script with a link, even better would be a base 64 encoded image included in the page source. If the server doesn't have GD then we can just let the user manually type in their authenticator secret into their apps.

**Comment by albertlast** [comment]
Alternative generate the qr code locally by using js exp: https://davidshimjs.github.io/qrcodejs/

**Comment by live627** [comment]
We may have our work cut out for us. From upstream:

https://github.com/enygma/gauth/blob/master/src/GAuth/Auth.php#L299

It uses [this library](https://github.com/Bacon/BaconQrCode) which will require some minor work to get working properly.

**Comment by live627** [comment]
The problem with using JS for this is that the code is still transmitted to the browser. I'm not up to speed on cyber security at all, so perhaps I'm missing something.

**Comment by albertlast** [comment]
When you transmit the image,
you sense the code to the browser too.

**Comment by live627** [comment]
but that's not plain text...

**Comment by albertlast** [comment]
But as qr code which is easy to read for programm.

**Comment by albertlast** [comment]
Same as by the other pr please test the pr: #5078
