### ISSUE TITLE
Global Moderator Right to create Category Issue

### ISSUE THREAD

**Issue by nwabritish** [SimpleMachines/SMF#5002]
#### Description
 When Global Moderators are given Right to Create Categories. After creation of any category(by Global Moderator) it only appears in Admin's Panel. Global Moderator will only see such category or add board ONLY after admin might have added one board in that category.

### Steps to reproduce
1)Assigned Global Moderators right to create Categories and board.
2) they can create Categories but once they click "Add category" it won't appear in Manage Boards and Categories in Global Moderator's panel.
3) They can see the categories created by Admin, they can add board but the categories they created aren't appearing on their Manage Boards and Categories unless Admin add one Board to that category, then they can add more boards.

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1 Beta 3
- Database Type:MySQL
- Database Version:5.7.22
- PHP Version:7.1.20
![cate](https://user-images.githubusercontent.com/43107401/45262478-181e0400-b44a-11e8-91fd-8c4805343d49.PNG)
![manage boards and categories](https://user-images.githubusercontent.com/43107401/45262480-22400280-b44a-11e8-92b7-45dcc5677c69.png)

### Additional information/references

**Comment by SychO9** [comment]
I've Tested this on The lates github version,

Also When creating a board as the GM I get this error:
The board you specified doesn't exist

**Comment by nwabritish** [comment]
Yea that is correct but the version here and the one on SMF

**Comment by illori** [comment]
you need to test on the latest on github as it has more fixes then what is on sm.org. if you cant duplicate on the github version then we need to close the bug.

**Comment by nwabritish** [comment]
I have tested it on Github version and its still the same. There is an issue with Global Moderation right creating Category. DO NO Close as this is a bug. I have provided the steps to reproduce the issue. Test and verify it.

**Comment by SychO9** [comment]
the problem here is with query_see_board, Subs.php 6489, it checks if the user can see the board but it never checks the 0 group "Regular Members" because it's not in the $user_info['groups'] array, but it has to be checked, additionally if a category has no boards the condition is never met, so does not show up, unless the user is an admin since the condition would just be 1=1

**Comment by Sesquipedalian** [comment]
Thanks, @SychO9. That's very helpful information!

**Comment by nwabritish** [comment]
Thank you @SychO9 hope this issue will be fix ASAP.
