### ISSUE TITLE
Comment needed in minified files about not editing them

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#5004]
I'm noticing we might begin to have a lot of problems with support with people editing the minified files (in particular the css files). Any thoughts on what we could do to reduce the confusion? I'm thinking if we move them to another folder it may discourage people from editing it, and having only the real files in view is a bonus that is useful to everyone.

Could also make the minified script add a comment in the beginning about this.

**Comment by SychO9** [comment]
I think a comment on the script would be good, something that clearly states that **editing the file is not to be done.**
I'm not sure about the location change, they can easily find it from the browser if they really want to edit it since in the first place they wouldn't know to edit the minified file unless they use the DevTools which reveals the location, but it might very well discourage others.

**Comment by Gwenwyfar** [comment]
Yeah, that's sure to help.

Most people don't even seem to know about the dev tools. My guess would be they see two files named index.css, and randomly edit one of them. For sure some find it in the dev tools, but the less fuss we get over this the better. It could just be a folder inside js/css folders, and since it's possible to have multiple minified files now, it would be useful for organization too.

**Comment by SychO9** [comment]
true that, and I think doing both should should be good enough

**Comment by Sesquipedalian** [comment]
If I think back to when I first started with SMF, I'm pretty sure that if I had seen one file named index.css and another named minified_71d5135887a2d6a9ef67130a5cdb4581.css in the theme folder, I'd have been inclined to leave the second one alone—especially if I opened it up and saw a comment at the top of the file explaining that it was automatically compiled from the other CSS files and that I should edit those instead.

**Comment by illori** [comment]
adding the comment might help. might not hurt to also create a wiki page about this.

maybe link such wiki page from the comment in the header of the minimized file?

how about adding the link to the normal css file as well?

**Comment by Gwenwyfar** [comment]
@Sesquipedalian: You're right, I forgot their naming got changed. We're still getting people editing the index.min.css from older versions. That adds more weight to the second purpose of it though:

The folder would have a double purpose here, one being simply to keep it organized, and the files out of sight (if you're editing anything in there, you don't care about the minified files, and in the case where there are multiple, they are just clutter).

If we add a wiki page it could be about the entire minification process and documentation for it.

**Comment by StealthWombat** [comment]
Hey, my account still works.

Anyway, thought for the day: if you are going to chuck the minified files in their own folder (which is not a bad idea) you could also throw a brief readme in the folder with them. Anyone silly enough to edit the minified files is probably silly enough to ignore a comment in the file, and comments are really bloat in those files anyway.

OTOH, if you have hey_you_read_this_kthnx.txt sitting at the top of the folder it is barely possible that they might read that (you can be sure they won't read smf.org docs) in which case they might be able to stay out of trouble.

**Comment by illori** [comment]
i doubt they will read anything, but we try in case they do see something they want to read.

**Comment by Gwenwyfar** [comment]
It wouldn't be useful to add much info there or a large comment (and like you said, those files should remain small). It should just be a short message that says "don't edit this, changes won't take effect. edit the main files" with a link to the wiki page.

It would be seen as soon as they open the file, and the only really readable part of it at first glance. If they still miss it, we're dealing with one of those "will ignore everything" people and there's nothing we can do about that. This is to pass the info to those who will read but are just lost, not to prevent stupid.
