### ISSUE TITLE
parse_bbc Undefined index: browser

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#5016]
#### Description
When parse_bbc is called by cronjob the $context['browser']['is_ie'] is not setted.
https://www.simplemachines.org/community/index.php?topic=562323.0

i guess
### Steps to reproduce
1.  marke a post to notify
2. create a post with bbc code

### Environment (complete as necessary)
- Version/Git revision:newest
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references
stacktrace
![grafik](https://user-images.githubusercontent.com/1782906/45897339-20c1f300-bdd7-11e8-8962-2b22311fdf5b.png)

https://github.com/SimpleMachines/SMF2.1/blob/8aafc85d03b52eb6780a5ff9ac61d4f7aad9d987/Sources/Subs.php#L1742

Possible introduce by @MissAllSunday 
with pr https://github.com/SimpleMachines/SMF2.1/commit/5fdfd87109545cefd5fff2960aded63bbebe23f0

**Comment by MissAllSunday** [comment]
Yay for adding legacy BBC.....  still cannot understand why people want those tags so badly..........

At this point, the is_ie thing should be completely erased, unless of course people starts to complaining about not supporting IE 6 in order to view their precious move and blink BB codes.............

**Comment by albertlast** [comment]
ther are many placed where this check is placed,
would you create pr with the removing of this?

**Comment by MissAllSunday** [comment]
Or set every browser context related vars to null or false or any other falsy value when running in cli mode.

**Comment by albertlast** [comment]
Feel free to choose your way how to solve this.

**Comment by Sesquipedalian** [comment]
The easiest fix would be to use `!empty($context['browser']['is_ie'])`.
