### ISSUE TITLE
Subs-Db-mysql uses addslashes instead of mysqli_escape_string

### ISSUE THREAD

**Issue by tinoest** [SimpleMachines/SMF#5019]
#### Description

It's better security practise to use the built in mysqli_escape_string rather than addslashes

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Db-mysql.php#L48

### Additional information/references

http://shiflett.org/blog/2006/addslashes-versus-mysql-real-escape-string

**Comment by gevv** [comment]
hi, error encountered when looking for members in the admin area

Warning: mysqli_stmt_bind_param() expects parameter 1 to be mysqli_stmt, boolean given in /xxxx/Subs-Db-mysql.php on line 995 Warning: mysqli_stmt_execute() expects parameter 1 to be mysqli_stmt, boolean given in /xxxx/Subs-Db-mysql.php on line 996
