### ISSUE TITLE
Upgrade to 2.1 - Unnecessary UTF8 step

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5027]
#### Description
I just upgraded a test forum to 2.1.  It was already utf8, but the utf8 migration steps were repeated.  

I think when you choose the option to move to a new settings file, it may miss some of the old settings?

### Steps to reproduce
1. Have a 2.0 forum that's aready utf8
2. Upgrade it to 2.1; choose the 'migrate to new settings' option

### Environment (complete as necessary)
- Version/Git revision: Latest as of today
- Database Type: mysql
- Database Version: 5.7
- PHP Version:5.6

### Additional information/references

**Comment by jdarwood007** [comment]
There is no detection in the upgrade script to determine if you should skip the UTF8 conversion or not.  The logic goes right into running the conversion process which detects what needs converted there.

There is an exception for postgresql and it is skipped.

**Comment by sbulen** [comment]
Actually, it does check, that's an OR in there:  
https://github.com/SimpleMachines/SMF2.1/blob/3bec079583489cbaa8cdabb5d9e58270804bff0b/other/upgrade.php#L2606

This is new behavior.  It normally bypasses the step on DBs that are already UTF8.  

I think the setting $db_character_set from Settings.php was lost.  I'm a little nervous about losing that, since $db_character_set is used in the SET NAMES.  That could conceivably result in data corruption.  

It's used throughout upgrade.php.

**Comment by jdarwood007** [comment]
Oh your right.  It isn't kept because it wasn't in the template.

So we can either not suggest a migration if this variable is set, or we can add it into the template and deprecate changing it.

**Comment by sbulen** [comment]
I suspect many folks have likely gone thru the utf8 conversion in 2.0.  I don't think it makes sense to not suggest an upgrade...

Sounds like the template route.

(I always felt the setting was kinda silly...  MySQL should know its charset,  right?  Why does it corrupt itself if you don't tell it what it should already know?)

**Comment by albertlast** [comment]
Would be nice if we provide some kind of hint of template side,
for pg would be the important note that the database had to be already in utf8 otherwise smf 2.1 get some issue.

**Comment by sbulen** [comment]
The setting shouldn't be needed at all, since the upgrade brings you to utf8.   Another option is to remove it altogether.  Its referenced a lot throughout the code, though.

**Comment by albertlast** [comment]
From my side is not clear (since the check is ther) what is the issue and what is the wanted result/behavior.

**Comment by sbulen** [comment]
The initial report is that an unnecessary utf8 conversion is taking place.   Ie., even if you are already utf8, the conversion takes place again.

So...   The issue is that the step should be skipped, but it isn't. 

This is because $db_character_set is getting lost/ignored if you choose to convert to a new settings.php file.

My broader concern is that the loss of $db_character_set may be hurting us in other ways.  For example,  it is used in the SET NAMES command.   What might happen if you do db updates without a proper SET NAMES?  Potentially data corruption...

**Comment by jdarwood007** [comment]
So do we add it into Settings.php (and then the template) or handle this a different way?

**Comment by sbulen** [comment]
Near term, as long as we preserve it in Settings.php, we're safe.

Long term (post 2.1), it needs a rethink.  It shouldn't really be necessary, IMO.  Better saved for a distant future overhaul.  A lot of code is in there to support different encoding & charsets that should be evaluated & removed now that we're committed to utf8.

**Comment by jdarwood007** [comment]
This should address it.  Added a legacy settings section to the Settings file and defaulted it to utf8.

This should also be useful in the future to allow this to continue to be used for legacy reasons.
