### ISSUE TITLE
sceditor.undo.js

### ISSUE THREAD

**Issue by pouvik** [SimpleMachines/SMF#5035]
took a download today of recent file getting error message when visiting posts, The file "sceditor.undo.js" could not be located on the current or the default theme and therefore it wasn't included in the minified file.

No changes made to coding and its using most up todate version took it about 15 mins ago

**Comment by wintstar** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/5026

This would still need to be removed.

https://github.com/SimpleMachines/SMF2.1/blob/c00aa28a5625072af72b3e03eb32dd6098e7fac7/Sources/Subs-Editor.php#L1558

**Comment by albertlast** [comment]
Added a pr to fix this by adding the file back again.

**Comment by wintstar** [comment]
> Added a pr to fix this by adding the file back again.

Why add back again? The plugin has been removed, see here #5026

**Comment by albertlast** [comment]
In my eyes it's only important to disable the plugin,
For the time it's broken.
When it got fixed,
Than we enable the plugin again.

**Comment by wintstar** [comment]
Ok. The Pull request from jdarwood007 on SCEditor "Going back in the browser causes the loss of content" works in my test board.
