### ISSUE TITLE
The file "sceditor.undo.js" could not be located...

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5038]
#### Description
New install of 2.1, as of today.  After posting, I am seeing these errors in the error log:

```
Type of error: General 
The file "sceditor.undo.js" could not be located on the current or the default theme and therefore it wasn't included in the minified file.
https://localhost/van21/index.php?action=post;msg=2;topic=2.0
```

### Steps to reproduce
1. Install 2.1
2. Post

### Environment (complete as necessary)
- Version/Git revision:  10/9/18
- Database Type: MySQL
- Database Version: 5.7
- PHP Version: 5.6

### Additional information/references

**Comment by wintstar** [comment]
Same, look here https://github.com/SimpleMachines/SMF2.1/issues/5035

**Comment by sbulen** [comment]
Don't know how I missed that, I'll close this one.
