### ISSUE TITLE
Upgrader - Messages say individual steps are complete, when they're not...

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5040]
#### Description
I just started the database updates step, but it says it's done.  That message is supposed to be displayed upon completion, not during the step:
![image](https://user-images.githubusercontent.com/23568484/46712725-3de42780-cc07-11e8-857d-a8f93d1c2c72.png)

### Steps to reproduce
1. Run a 2.0 to 2.1 update

### Environment (complete as necessary)
- Version/Git revision:  10/9/18
- Database Type: MySQL
- Database Version: 5.7
- PHP Version: 5.6

### Additional information/references
Message can be safely ignored.
I did select the option for a new settings.php file, but I don't think it would make a difference here.

**Comment by sbulen** [comment]
It also says the UTF8 Conversion is completed, while it is still in progress:
![image](https://user-images.githubusercontent.com/23568484/46712847-e1cdd300-cc07-11e8-838d-aa1ebac054d4.png)

**Comment by sbulen** [comment]
It also says the JSON step is complete, while it is still in progress...  I think I see a pattern here...
![image](https://user-images.githubusercontent.com/23568484/46712868-0cb82700-cc08-11e8-9ccf-cb53a9e93772.png)

**Comment by sbulen** [comment]
All the above happens both on WAMP and on Linux hosted.

**Comment by jdarwood007** [comment]
This is most likely related to #5036 as it is just not hiding that box properly after completing the tasks

**Comment by sbulen** [comment]
To be clear: it is not hiding that message BEFORE completing the task.  It should "appear" when the task is complete.
