### ISSUE TITLE
Undefined index: can_remove

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#5044]
#### Description
Type of error: Undefined 
8: Undefined index: can_remove
 .../index.php?action=admin;area=languages;sa=editlang;lid=german;entries
 .../htdocs/smfbeta/Themes/default/ManageLanguages.template.php (Line 276)

### Steps to reproduce
1.  Change language string with language editor 
2. 

### Environment (complete as necessary)
- Version/Git revision: Pull Request 5037
- Database Type: MariaDB
- Database Version: 10.1.34-MariaDB 
- PHP Version: 7.1.20

### Additional information/references
Testing the new language editor

**Comment by Sesquipedalian** [comment]
Are you sure that you testing with the latest code? [Line 276 of ManageLanguages.template.php](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/ManageLanguages.template.php#L276) is just an `else`, so that error message does not make sense.

**Comment by wintstar** [comment]
Yes. Pull request 5037.

**Comment by wintstar** [comment]
Although I emptied the cache and browser cache several times, I got the error message. After today's check there was no more error message. Chrome seems to be very persistent, despite clearing the cache and it takes a long time until the changes are visible.
