### ISSUE TITLE
Installer Issue - 'Line 1552: Unknown column 'grp' in 'field list'

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5045]
#### Description
Error appears during install.  

### Steps to reproduce
1. Do a fresh install of 2.1

### Environment (complete as necessary)
- Version/Git revision:  Today - 10/11/18
- Database Type:  MySQL
- Database Version: 5.7
- PHP Version: 5.6

### Additional information/references
Have seen this on both WAMP & on Linux.  
![21-install](https://user-images.githubusercontent.com/23568484/46846217-ab24c380-cd93-11e8-9291-a9ca628f9b8c.JPG)

**Comment by sbulen** [comment]
Probably related (I suspect user group issues), but two more sets of symptoms:

(1) Guests get a very strange presentation, can't read posts, but can search 'em!: (Linux & WAMP)
![21-install-2](https://user-images.githubusercontent.com/23568484/46846512-c7753000-cd94-11e8-9883-2781a5c5c048.JPG)

(2) Errors in log, Linux only (not seen on WAMP):
![21-install-3](https://user-images.githubusercontent.com/23568484/46846534-d360f200-cd94-11e8-80a0-3ebc3c42c634.JPG)

**Comment by sbulen** [comment]
Just did a quick 2.0 to 2.1 WAMP upgrade & did not have these issues.  I am pretty sure they are limited to the installer.

**Comment by albertlast** [comment]
The issue is related to my last pr,
I will look into this.

**Comment by sbulen** [comment]
Thanks,

**Comment by albertlast** [comment]
should be fixed with the pr.
