### ISSUE TITLE
Translation typo in "showing credits" action on the Who's Online page in Czech translation

### ISSUE THREAD

**Issue by TLama** [SimpleMachines/SMF#5053]
There's a typo in the action name for showing credits on the **Who's Online** page in Czech translation. It says:

> Zobrazuje stánku s kredity.

whilst it should be:

> Zobrazuje st**r**ánku s kredity.

Could we fix this?

**Comment by frandominguezl** [comment]
Not a software issue but a translation issue. Please post it in https://simplemachines.org

**Comment by TLama** [comment]
> Not a software issue but a translation issue. Please post it in https://simplemachines.org

Sorry, I felt a bit strange posting this (thought it's fine according to [this issue](https://github.com/SimpleMachines/SMF2.1/issues/2020)). Is there a specific board for it? I cannot find any...

P.S. feel free to delete this issue later on.

**Comment by frandominguezl** [comment]
Post it right here and I'll have a look at it tomorrow: https://www.simplemachines.org/community/index.php?board=12.0
