### ISSUE TITLE
non-numerical keys for select options

### ISSUE THREAD

**Issue by Underdog-01** [SimpleMachines/SMF#5060]
#### Description
Restricting modification developers & future SMF updates to non-numerical key entries for select options is not the proper way to implement a fix for timezone aesthetics.
This also causes backward compatibility problems for mod developers.

### Steps to reproduce
1. Use numerical keys in select options.
2. Causes all options with numerical keys to be disabled and saves them as a 0 value.

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: MySQL / MariaDB
- Database Version: MySQL 8.0.12 / MariaDB 10.3.10
- PHP Versions: PHP 5.6 - PHP 7.2.10

### Additional information/references
PR that was applied that caused the issue(s):
https://github.com/SimpleMachines/SMF2.1/commit/afaf09bf6d38a6159fdb34eaae4397b747fc97c1#diff-22dc696c41300fca70fca6941cea4df1

**Comment by Sesquipedalian** [comment]
Given that the value of any valid time zone selection option needs to be an Olsen database time zone (e.g. "America/New_York"), how would you imagine numerical keys being used in this context?

As for backwards compatibility with mods, to my knowledge there are no mods listed on our site that tried to alter the time zone selection menu, so I don't believe there is anything to maintain backwards compatibility for.

If you have a concrete example of something that this change breaks in a way that cannot be easily fixed, please share it.

**Comment by Underdog-01** [comment]
It's the edits to the profile & register templates that are the issue.
Mods that add profile and/or registration options more than likely have nothing to do with timezones.

The codes you edited in those templates concern any select options added & are not restricted to timezones.  I noticed this with my Arcade mod which adds profile options.. the drop-downs were all disabled because of the referenced edit to the profile template. Hitting save on the same page sets those drop-downs to a "0" value.

I do have a possible solution for you (off the cuff).
ie.
`<option', str_replace(timezone_identifiers_list(), '', $name) != $name && is_numeric($value) ? ' value="" disabled' : ' value="' . $value . '"', $value === $field['value'] ? ' selected' : '', '>', $name, '</option>`

**Comment by Underdog-01** [comment]
You can see one example of the issue by testing the Arcade mod from my website.
Don't bother with my GitHub version nor the one from the SMF site.
Public : Arcade version 2.56.10
.. go to user profile / arcade settings & look at the drop-downs

I don't want to spam but for the purpose of this report the site is web-develop.ca
Either download & test it or register then test it.
Although you may understand what I mean now without having to do that.

**Comment by Sesquipedalian** [comment]
Yes, I see what you mean now. I'll comment further on your pull request.

**Comment by Underdog-01** [comment]
The current edits in my PR  (as of now) should have the behavior of maintaining backward compatibility and allow the timezone select menu to behave as intended.
When you get some free time to test it let me know if your findings are the same.
