### ISSUE TITLE
Should the cache work under SSI?

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#5061]
#### Description
Because right now it doesn't work.

### Steps to reproduce
1. Enable file cache
2. cache get/put do nothing

### Environment (complete as necessary)
- Version/Git revision:last Thursday
- Database Type:blah
- Database Version:blah
- PHP Version:7.2

### Additional information/references
Missing global declaration

This implies that I have a fix and will send it in upon confirmation.

**Comment by albertlast** [comment]
What are the pro and con?

**Comment by jdarwood007** [comment]
It should work under SSI.  Will look into it.
