### ISSUE TITLE
Something about legacy BBC (yes again)

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#5063]
Hum, so this keeps cropping up like those weeds in the yard.

What is the desired effect of their usage? Because, according to my unit tests, most still do work.

![untitled2](https://user-images.githubusercontent.com/431799/47050600-d4f43680-d155-11e8-9850-b5c2b91d90c1.png)

Reproduction message text 
```
[br][tt]blah[/tt]
[flash]blah[/flash]
[bdo=rtl]blah[/bdo]
[black]blah[/black]
[white]blah[/white]
[red]blah[/red]
[green]blah[/green]
[blue]blah[/blue]
[acronym]blah[/acronym]
[ftp]blah[/ftp]
[glow]blah[/glow]
[move]blah[/move]
[shadow]blah[/shadow]
```

preparsecode() also still messes with the raw color tags.

**Comment by jdarwood007** [comment]
Legacy bbc is supposed to disable the specific bbc code by telling the bbc handler to just do nothing but output the text.

i.e.
```
[red]test text[/red]
```
Becomes this on output:
```
test text
```

The bbc itself is not displayed.  Preventing it from ruining the flow of text, but also preventing it from doing the functionality it did.

This way if a mod author wants to implant it again, they can and just remove it from the legacy bbc array.  They can do so by simply calling the bbc hook, then unsetting the legacy they want to implant from the array.

**Comment by live627** [comment]
@Sesquipedalian this should be marked for RC2 as it's not a showstopper.


Should the legacy codes list be defined in parse_bbc? Currently it's in reloadSettings()... I don't see why? Something that I'm not getting?

**Comment by jdarwood007** [comment]
Don't think it maters where it is defined as long as its done once and before any work in parse_bbc is done.

**Comment by MissAllSunday** [comment]
It was placed on reloadSettings() for the same reason all the other new $context vars were placed on it, to keep a single place where this kind of vars are defined and let a single hook to handle them all.

**Comment by live627** [comment]
#5226 addresses this
