### ISSUE TITLE
Printing randomness makes the page go berserk

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#5064]
![screenshot_2018-10-16 login](https://user-images.githubusercontent.com/431799/47052632-06710000-d15e-11e8-9a35-dcb07ed1d688.png)

### Steps to reproduce
1. print something in a source file
2. view in firefox
3. this will come up when someone gets an error in debug mode since they get spit out at the top

**Comment by jdarwood007** [comment]
Is this something we can logically fix?

@Gwenwyfar or @Antes have feedback on that?  Assuming this is printing text before the < HTML> declaration.

**Comment by XinYenFon** [comment]
Try changing `.popup_container` height to max-height
