### ISSUE TITLE
database error stating outdated version

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#507]
i have not tested it but i assume same as 2.0 when there is a database error it will tell you that an update may be required to the database if the versions dont match. when a patch is made the version number is not updated in the database, either remove the version in the database error message or make it not show unless the version does not match a set value when there were database changes last

**Comment by Kindred-999** [comment]
this error message is one of the most confusing things that we get queries on in Support. I agree that the error message needs ot be changed.   Either emove the database verison check and error message or check it properly against that last actual database change version.

**Comment by Oldiesmann** [comment]
I think it would probably be best to just drop the database version entirely. I don't remember all the details, but I think there's only been one instance when we've changed the database after a major version has gone final.

**Comment by Kindred-999** [comment]
sounds like a plan then.   Go ahead and make that commit?

**Comment by Oldiesmann** [comment]
Looking into this, I think it's best to just remove the part of the code that generates the "you might need to update your database" error, as the upgrader is fairly dependent upon that setting in ways that we can't easily work around at the moment. Removing the setting wouldn't effect upgrades from older versions, but it would cause problems later on down the road when upgrading between 2.1 releases, etc. I'll go ahead and commit the change to remove the error messages until we can figure out a way around the other problem (possibly storing a version number in Settings.php as well?)

**Comment by Arantor** [comment]
The version test is no longer carried out on errors, and as outlined before we can't really remove it from the upgrader at this point without major overhauls, and to be honest I think we're going in a different direction going forwards so that the in-place upgrade we use now won't be used in future. Closing for now - we can always reopen it if we need to change things in the upgrader between now and then.
