### ISSUE TITLE
responsive.css should be loaded from current theme only

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5079]
If someone tries to make a theme but they have no intention of making it responsive, they wouldn't be able to stop the file from loading, if they remove it from their theme, it loads from the default.

force_current should be set to true.
>	loadCSSFile('responsive.css', array('force_current' => false, 'validate' => true, 'minimize' => true, 'order_pos' => 9000), 'smf_responsive');

@Gwenwyfar what do you think ?

**Comment by albertlast** [comment]
sure they are able,
by placing an empty responsive.css in ther theme dir.

**Comment by SychO9** [comment]
ain't that just a workaround :/

**Comment by albertlast** [comment]
The common logic is,
that when you want a different behaviour,
You create a file with the new behaviour.

In this scheme it's feel right to place a empty file to disable unwanted default behaviour.

Result: The solution from me is not a workaround.

**Comment by XinYenFon** [comment]
Working as intended. Its not really a core file to a theme, since responsive.css's main duty to make sure generic containers are responsive and rest of the inner elements flow freely.

**Comment by SychO9** [comment]
So it sounds better to have themers upload an empty css file to remove the behavior, than remove the file itself if they're not gonna use it ? why though ?

**Comment by XinYenFon** [comment]
and there is this interesting question, why you don't want to make your theme responsive ? Also loading CSS files are actually controlled by Source so even if you don't want to load responsive.css in someway, I think you need to control it via Load.php or some other place.

**Comment by SychO9** [comment]
I understand what you mean, I'm sure that not many would want to remove the responsiveness, but some might change a lot in their theme from the default, to the point where they have to make a lot of changes to responsive.css to keep it responsive otherwise, it'd be just broken in smaller screens, in which case they might just decide to remove responsiveness rather than have it broken.

I think the right way to go about it, is not assuming "who'd want to remove it", it's "what if some would rather remove it"

>Also loading CSS files are actually controlled by Source so even if you don't want to load responsive.css in someway, I think you need to control it via Load.php or some other place.

Unless you change 'force_current' to true, in which case you just have to delete the file from the package :|

**Comment by Sesquipedalian** [comment]
I think the best solution here would be to require the theme author to explicitly set a "not_responsive" variable in their theme's Settings.template.php if they don't want to use a responsive.css at all. Without that setting, we do what we are doing now.

**Comment by XinYenFon** [comment]
Themes should not be encouraged to be non-responsive. If someone really wants to do it, they should make it from the hardway.

**Comment by Sesquipedalian** [comment]
It is still pushing theme authors to do it, since they would need to take proactive steps to make it not responsive. It's just that we will make them define a setting rather than making them upload an empty CSS file, which is cleaner and less hack-ish. The code change would look like this:

```
loadCSSFile('responsive.css', array('force_current' => empty($settings['not_responsive']), 'validate' => true, 'minimize' => true, 'order_pos' => 9000), 'smf_responsive');
```

**Comment by SychO9** [comment]
It looks like there's a similar setting called $settings['disable_files'] which can be controlled from index.template.php 's template_init()
```
// Allow css/js files to be disabled for this specific theme.
	// Add the identifier as an array key. IE array('smf_script'); Some external files might not add identifiers, on those cases SMF uses its filename as reference.
	if (!isset($settings['disable_files']))
		$settings['disable_files'] = array();
```

this however doesn't affect files such as index.css or responsive.css ..etc which are loaded in Load.php
perhaps we could just use that as such

```
loadCSSFile('responsive.css', array('force_current' => in_array('responsive.css', $settings['disable_files']), 'validate' => true, 'minimize' => true, 'order_pos' => 9000), 'smf_responsive');
```

**Comment by Sesquipedalian** [comment]
Actually, I think adding responsive.css to `$settings['disable_files']` should work. `loadTheme()` calls `loadCSSFile()` to load responsive.css just like any other. Unless I am missing something, that should mean that `template_css()` will handle it just like any other CSS file—including skipping it if it is included in `$settings['disable_files']`.

**Comment by Sesquipedalian** [comment]
Confirmed. Changing [this line in index.template.php](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/index.template.php#L76) to `$settings['disable_files'] = array('smf_responsive');` caused responsive.css not to be loaded.
