### ISSUE TITLE
Possible issue in file cache backend

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#5083]
#### Description
There's always been some concern about the reliability of the file cache backend. I think we have a case where it actively has been shown to break.

If the cached content contains a null byte, the addcslashes call to write the data will truncate the string.

### Steps to reproduce
1. Have content that contains a null byte
2. Push it to the cache with cache_put_data
3. Observe result file cache is malformed

### Environment (complete as necessary)
- Version/Git revision: master
- Database Type: n/a
- Database Version: n/a
- PHP Version: n/a

### Additional information/references

See https://www.simplemachines.org/community/index.php?topic=560471.0 for more including a dump of a modSettings cache entry at 20489 bytes, so not a file write boundary issue (like we saw back in the day). I don't know for sure if this is the problem but it's a reasonable bet right now.

**Comment by Sesquipedalian** [comment]
Interesting. I find myself wondering if there are any cases where we would ever want to write a null byte into the cache. If not, perhaps an easy solution would be a simple `str_replace("\0", '', $str)` when reading and/or writing cache files.

**Comment by Sesquipedalian** [comment]
...Or maybe just convert any null characters to`&#x0;`  entities on write, and convert them back on read.

**Comment by jdarwood007** [comment]
After we convert it to a string, we could convert it to a hex.
bin2hex and hex2bin could possibly do this.

Adds some overhead though.

**Comment by Sesquipedalian** [comment]
Hex wouldn't be an efficient solution. https://stackoverflow.com/a/2612978

**Comment by jdarwood007** [comment]
Well your right.  We could try to add into it to use pack/unpack with compressions, but I think at that point we are wasting more cycles than we are saving.

**Comment by Sesquipedalian** [comment]
`str_replace("\0", '&#x0;', $str)` (and vice versa on read) is about as efficient as we could get, I think.

**Comment by Arantor** [comment]
Or even use the correct escaping as I suggested in topic 😉

**Comment by Sesquipedalian** [comment]
*Looks at topic again. Notices post on second page*

Oh, yes. That would work better. 👍
