### ISSUE TITLE
4-byte Unicode characters for user names

### ISSUE THREAD

**Issue by Underdog-01** [SimpleMachines/SMF#5088]
#### Description
Entering 4-byte Unicode characters for a user name during registration or manually adding a user causes a database error 

### Steps to reproduce
1. Navigate to the register page as a new user
2. Enter a user name that contains 4-byte characters from ie. HTML decimal entities
3. example: 🅻🅴🅼🅾🅽
4. db error: 
Incorrect string value: '\xF0\x9F\x85\xBB\xF0\x9F...' for column 'member_name' at row 1
File: C:\wamp64\www\smf21site4\Sources\Subs-Members.php
Line: 709

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: MySQL / MariaDB
- Database Version: MySQL 8.0.12 / MariaDB 10.3.10
- PHP Versions: PHP 5.6 - PHP 7.2.11

### Additional information/references
I have a fix for this which restricts the name entry to 3-bytes that I can enter as a PR but I would like to know the intended behavior prior to doing that.
If 4-byte Unicode characters are intended then this will require a utf8mb4 charset for MySQL or MariaDB.

**Comment by albertlast** [comment]
two points,
general behavior of smf and than the specific issue.

in general smf support mb4,
but it depends on the database.
In postgres mb4 is enabled by default ond mysql mb4 is disabled by default.
Both can be overwrited by the settings value: 
https://github.com/SimpleMachines/SMF2.1/blob/ea606b8e7ac4d461a749b1d8d922c4a06159eeb5/other/Settings.php#L118-L123

In you case it look like we got here a bug because the mb4 convertion function is not called or do the wrong thing.

**Comment by Underdog-01** [comment]
Ok thanks for the feedback.

Although those type of characters may be ok for the "display name" perhaps it would be prudent to not allow them for the actual user/logon name.
Do you agree that restricting those characters would be better for the user name input?

**Comment by albertlast** [comment]
When smf run on disabled mb4,
Then chars from this area get converted into html entities -> the user is able to use them.

**Comment by Underdog-01** [comment]
So if $smcFunc['db_mb4'] is false then the db is not set to 4-byte charset and colllation ?
If it is 3-byte then such characters should be converted to html decimal entities and if it is 4-byte then let it remain as it was entered?
Do I have that correct?

**Comment by albertlast** [comment]
When it false,
 than the db didn't support mb4 and
Strings will get converted in a mb3 format.

When it's true,
So the database support it,
No converting is needed.

**Comment by Underdog-01** [comment]
I'm about to create a PR for this.
At the moment I have 2 methods to detect a mb4 string so if you don't like the method I use then respond in the PR.

ref. PR
https://github.com/SimpleMachines/SMF2.1/pull/5093

**Comment by albertlast** [comment]
@live627 a pr exists for this issue

**Comment by live627** [comment]
Right. I missed this because #5093 didn't reference this issue.
