### ISSUE TITLE
Attach name in function not spelled correctly

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5089]
Attach name in function not spelled correctly

Sources\Attachments.php(134): $this->createAtttach();
Sources\Attachments.php(316): protected function createAtttach()

Also do you care about typos in comments?

**Comment by Sesquipedalian** [comment]
> Also do you care about typos in comments?

They drive me nuts, personally, but not enough to comb through 27439 lines of comments hunting them all down.
