### ISSUE TITLE
Alter table generates wrong SQL for type boolean

### ISSUE THREAD

**Issue by tinoest** [SimpleMachines/SMF#5096]
#### Description
See steps to reproduce..

### Steps to reproduce
1.  Create a database table with int as default with db_create_table 
2. Then try to change it to type boolean using db_change_column. It will add the size attribute incorrectly 

### Environment (complete as necessary)
- Version/Git revision: Any
- Database Type: MariaDB
- Database Version: 10
- PHP Version: 7.0

### Additional information/references

Created SQL is 

ALTER TABLE mytable CHANGE COLUMN `column_int` `column_int` boolean(1) NOT NULL default '1' 

Should be 

ALTER TABLE mytable CHANGE COLUMN `column_int` `column_int` boolean NOT NULL default '1'

**Comment by albertlast** [comment]
mysql didn't got boolean right?
Right would be than:
ALTER TABLE mytable CHANGE COLUMN ``column_int`` ``column_int`` tinyint NOT NULL default '1'

**Comment by tinoest** [comment]
> mysql didn't got boolean right?
> Right would be than:
> ALTER TABLE mytable CHANGE COLUMN `column_int` `column_int` tinyint NOT NULL default '1'

Which will mean it doesn't work correctly in pgsql. type boolean is correct for both.

**Comment by albertlast** [comment]
Test please the pr

**Comment by albertlast** [comment]
Please had in mind,
because of the lazy implementation of #5916 mod author etc. can't check if a table got already a boolean field or not.
So please don't forget this.
