### ISSUE TITLE
Info center date

### ISSUE THREAD

**Issue by Underdog-01** [SimpleMachines/SMF#5107]
#### Description
The info center date display for latest & multiple posts shows PHP time() in seconds. 

### Steps to reproduce
1. Install a test installation of the current SMF 2.1 build
2. Change:  Theme Settings -> Number of recent posts to display on board index to 1 or more
2. Look at the info center at latest topic/post.
3. Look at the info center at recent posts
4. Both 2 & 3 display PHP time() instead of the proper date

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: MySQL / MariaDB
- Database Version: MySQL 8.0.12 / MariaDB 10.3.10
- PHP Versions: PHP 5.6 - PHP 7.2.11

### Additional information/references
This PR caused the issue:
https://github.com/SimpleMachines/SMF2.1/pull/5052/files
 $row_board['poster_time'] needs to be converted to the forum date format.

**Comment by smfbigguy** [comment]
I don't see the problem. All my time is displaying fine.
![firefox_screenshot_2018-11-01t01-16-09 071z](https://user-images.githubusercontent.com/3620111/47827138-68cb2280-dd52-11e8-8ebf-02df080b050a.png)

**Comment by Underdog-01** [comment]
Look at your image beside where it says the topic title in Forum Stats
 Latest post: "Re. Update Complete".
The number: 1541034926 is supposed to be in date format.

**Comment by smfbigguy** [comment]
Lol. I am sorry. One of my members was playing around with his username and I mistook that for his username. Disregard my post. Sorry all. You can use the screenshot though for illustration, lol.

**Comment by Underdog-01** [comment]
It actually helps to show the issue.
