### ISSUE TITLE
Updater fails with bayblon theme present on php7.2

### ISSUE THREAD

**Issue by acid** [SimpleMachines/SMF#5110]
#### Description
Hello. I did an upgrade from 2.0.3 to 2.1-beta3 pretty impressive software, congrats! :)

While running the upgrader I encountered the following error message:
```
2018/11/02 01:32:38 [error] 16773#16773: *260 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mysql_result() in /var/www/eeb/html/smf/upgrade.php(1755) : eval()'d code:13
Stack trace:
#0 /var/www/eeb/html/smf/upgrade.php(1755): eval()
#1 /var/www/eeb/html/smf/upgrade.php(1276): parse_sql('/var/www/eeb/ht...')
#2 /var/www/eeb/html/smf/upgrade.php(278): DatabaseChanges()
#3 {main}
  thrown in /var/www/eeb/html/smf/upgrade.php(1755) : eval()'d code on line 13" while reading response header from upstream, client: 79.209.64.85, server: extendedemotional.de, request: "GET /upgrade.php?step=3&amp;substep=0&amp;data=eyJjdXJzdGVwIjozLCJsYW5nIjoiZ2VybWFuIiwicmlkIjozOTEyLCJwYXNzIjo5NDc2LCJkZWJ1ZyI6MCwianMiOjF9&xml&filecount=2&substep=252&_=1541118757961 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "extendedemotional.de", referrer: "http://extendedemotional.de/upgrade.php?step=0&substep=0&data=eyJjdXJzdGVwIjowLCJsYW5nIjoiZ2VybWFuIiwicmlkIjozOTEyLCJwYXNzIjowLCJkZWJ1ZyI6MCwianMiOjB9"
```

I grep'ed the source and found that this line is causing that bug https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade_2-0_mysql.sql#L2773

I worked around the bug by removing the theme folder.  I'm sure you people know which of your own api-methods you want to use in the future to fix this thing.

### Steps to reproduce
1.  Have 2.0.3 with babylon theme present (it was actually upgraded from 1.x years ago. Maybe that's why the folder was present?)
2. run upgrader

### Environment (complete as necessary)
- Version/Git revision: 2.0.3
- Database Type: mysql
- Database Version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1
- PHP Version: 7.2

**Comment by albertlast** [comment]
Please use gh version,
Beta 3 is to old.
