### ISSUE TITLE
Requiring TFA kills the profile popups

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#5112]
The popups for alerts and messages quit. The profile popup goes crazy.

![screenshot_2018-11-03 scheduled tasks](https://user-images.githubusercontent.com/431799/47957221-19ae0900-df6f-11e8-8acb-c96712e9ff62.png)

### Steps to reproduce
1. Require TFA on either all accounts or for specific groups
2. Try to open any of the three popups on top

### Additional information/references

Perhaps skip the tfa check for any xml requests. Maybe even for feeds, too. And SSI. Definitely SSI.

Relevant code
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Load.php#L547

**Comment by albertlast** [comment]
When the user setup his tfa information,
Than the popup works correctly?
Because for me it's look fine,
Please had in mind the admin define tfa as required,
So the user is enforced to do so.

**Comment by live627** [comment]
yes, it's  only when tfa isnt set up. Forgot to mention that before.
