### ISSUE TITLE
"Undefined index: You can only login via HTTPS"

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#5115]
#### Description
Found this in the error log of a forum I recently upgraded from 2.0 to 2.1. Although I did have the forum set to use HTTPS, I didn't enforce it until the 2.1 upgrade.

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision: One revision behind current
- Database Type: MariaDB
- Database Version: 10.0.36
- PHP Version: 5.6.38

### Additional information/references
This appears to occur if someone tries to login over HTTP and you have error logging enabled. Here's the complete backtrace:

#0: smf_error_handler()
Called from /.../Sources/Errors.php on line 219
#1: fatal_lang_error()
Called from /.../Sources/Load.php on line 1886
#2: loadTheme()
Called from /.../index.php on line 189
#3: smf_main()
Called from /.../index.php on line 150

**Comment by illori** [comment]
maybe related to https://github.com/SimpleMachines/SMF2.1/issues/5070 ?

**Comment by Oldiesmann** [comment]
Probably.

**Comment by live627** [comment]
Could be
```
./Load.php:1873:			fatal_lang_error($txt['login_ssl_required']);
```

I intend to fix that for RC2.

Also nice to see you pop in 😃

**Comment by live627** [comment]
Fixed in https://github.com/SimpleMachines/SMF2.1/pull/5422
