### ISSUE TITLE
Old avatars partially broken in 2.1

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#5116]
#### Description
The code to show avatars that were uploaded to the attachments directory doesn't work properly when using the old "dlattach" URLs.

### Steps to reproduce
1. Install SMF 2.0 and upload an avatar with the default settings (so it uses the attachment directory)
2. Upgrade to 2.1, then try to edit the "forum profile" section of the profile of the person who uploaded the avatar in step 1.

### Result:
1. Avatar won't show up
2. Two errors in the error log

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: Mariadb
- Database Version: 10.0.35
- PHP Version: 7.1

### Additional information/references
Errors with backtrace:

```
Error message: 8: Undefined index: extension
File: /.../Sources/ShowAttachments.php
Line: 152
URL of page causing the error: .../index.php?action=dlattach;attach=35;type=avatar
#0: smf_error_handler()
Called from /.../Sources/ShowAttachments.php on line 152
#1: showAttachment()
Called from /.../index.php on line 150
```
```
Error message: md5_file(/.../attachments/35_048ee2ceb5718ba7ffd553d9ac5b199f5bd97cb): failed to open stream: No such file or directory
File: /.../Sources/ShowAttachments.php
Line: 153
#0: smf_error_handler()
Called from unknown on line -1
#1: md5_file()
Called from /.../Sources/ShowAttachments.php on line 153
#2: showAttachment()
Called from /.../community/index.php on line 150
```
The information in the database regarding the avatar file is correct, but it seems this part of the code hasn't been updated to show it properly.

**Comment by Oldiesmann** [comment]
Further investigation into this, with help from albertlast...

If you add a check on line 152 of ShowAttachment.php to set $filePath['extension'] to an empty string if it's not set, the two errors go away.

However, there is a discrepancy in how the avatars are loaded. On the profile summary, it tries to load it from the custom avatars directory. When you go to edit your profile, it loads it via action=dlattach.

**Comment by albertlast** [comment]
This is the mention code from oldy, between 151 and 152:
`` $filePath['extension'] = empty($filePath['extension']) ? '' : $filePath['extension'];``

**Comment by MissAllSunday** [comment]
This is prob my fault so I'll take a look at it.

Edit, didn't saw the PR for this, my bad.

Edit 2, it only handles the error message 👅

**Comment by albertlast** [comment]
@MissAllSunday the issue #5123 got open for the other part of this issue here.
