### ISSUE TITLE
Calendar "Short Day Titles" Help Popup Typographical Error

### ISSUE THREAD

**Issue by SugarD-x** [SimpleMachines/SMF#5118]
#### Description
When editing the calendar settings, opening the help popup for the "Short Day Titles" section results in the information displaying a typographical error for the word "Disabled". It is currently spelled as "Disbaled".

### Steps to reproduce
1. Enable the calendar.
2. Open the calendar settings.
3. Click the help icon beside the setting for "Short Day Titles".
4. Read the displayed help popup.

### Environment (complete as necessary)
- Version/Git revision: Latest Github repository.
- Database Type: MySQL
- Database Version: 8.0.12 - MySQL Community Server - GPL
- PHP Version: 7.2.8

### Additional information/references
This appears to only be present within "\Themes\default\languages\Help.english.php" on line 199.

**Comment by live627** [comment]
o god I pushed my fix for this directly upstream. I'm sorry.

**Comment by Sesquipedalian** [comment]
> o god I pushed my fix for this directly upstream. I'm sorry.

![Well, shame on you](https://media.giphy.com/media/NGV4vAghFiUOA/giphy.gif)
