### ISSUE TITLE
Uploaded/URL avatars not shown when editing profile

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#5119]
#### Description
When you go to edit your forum profile, if you have chosen an avatar type other than gravatar, your avatar isn't shown. This is because the `<img>` to show the avatars is inside the "avatar_gravatar" div, which is hidden when you haven't selected Gravatar.

### Steps to reproduce
1. Go to your profile and either upload an avatar via URL or upload one.
2. After you save the profile, the avatar you chose isn't displayed except in the user menu at the top left.

### Environment (complete as necessary)
- Version/Git revision: Latest
- Database Type: MariaDB
- Database Version: 10.0.36
- PHP Version: 7.1.23

### Additional information/references
The reason for this is that the `<img>` to display your avatar is inside the "avatar_gravatar" div, which is hidden when you have chosen an option other than Gravatar. If you select the "Choose an avatar from the gallery" option after uploading an avatar or specifying one via URL, it will also show up to the right of the select box.

Relevant code from Profile.template.php:
```php
	// if the user is able to use Gravatar avatars show then the image preview
	if (!empty($context['member']['avatar']['allow_gravatar']))
	{
		echo '
								<div id="avatar_gravatar">
									<img src="' . $context['member']['avatar']['href'] . '" alt="">';```

**Comment by live627** [comment]
That code is confusing. 😞
