### ISSUE TITLE
Upgrade "Undefined index: theme_url"

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#5126]
#### Description
When you run a clean install of smf 2.0 and
apple the upgrade stuff of 2.1 you get the errors:
![grafik](https://user-images.githubusercontent.com/1782906/48248301-0b407100-e3f7-11e8-8292-ee5f7bf2934c.png)

### Steps to reproduce
1. A clean 2.0 setup
2.  try to upgrade to 2.1

### Environment (complete as necessary)
- Version/Git revision: 450da88
- Database Type: pg
- Database Version: 10
- PHP Version: 5.6

### Additional information/references
the root cause is the reloadSettings
fixed by the pr https://github.com/SimpleMachines/SMF2.1/pull/5124

Additionaly even you fiy this topic the next issue would be,
that on errors now the default error log function is called (see the last stacktrace on the pic),
which would lead in another issue that the error log table didn't exists in the format which needs to be to log the errors.

**Comment by Gwenwyfar** [comment]
I just ran upgrade on 2.1 to 2.1 and had the same error as well.
