### ISSUE TITLE
Modify a post lost the height width settings of img tag

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#5131]
#### Description
When you insert a image in a post in this way:
```
[img width=20 height=80]https://static.simplemachinesweb.com/site/images/frontpage_logo.png[/img]
```
And works everything fine,
but when you modify the numbers get 0.

Looks like that this bug only happen when ff is used.
### Steps to reproduce
1.  Create a post with a images which got height and or width save
2.  Modify the post and notice that the numbers get zero

### Environment (complete as necessary)
- Version/Git revision: newset
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references
Quicked works fine,
only modify create this issue.

First reported on sm.org https://www.simplemachines.org/community/index.php?topic=563197.0

**Comment by SychO9** [comment]
I can't reproduce this with the latest version :/

**Comment by albertlast** [comment]
I keep been able to reproduce this.

**Comment by awxcerztu** [comment]
It happens only with Firefox browser, but not with Chrome or Microsoft Edge.

**Comment by SychO9** [comment]
Ah, that is correct I can reproduce it in FF
