### ISSUE TITLE
Slogan text size and alignment.

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5133]
Dunno if this is intended behaviour, but I noticed when you add your own text for a slogan it seems to be the same size as the default logo text (forum name).  The slogan also sits higher in the container than the logo (forum name).  I'm guessing this will also increase the height of the container unnecessarily.

When you remove the slogan text and let it display the default SMF image it appears to sit at the same height as the forum name. 

![21slogan1](https://user-images.githubusercontent.com/6047983/48301392-533dc180-e4e5-11e8-9f16-f06fea98e562.png)
![21slogan2](https://user-images.githubusercontent.com/6047983/48301393-53d65800-e4e5-11e8-88d0-cff6f2ed46f0.png)

**Comment by SychO9** [comment]
I'm thinking of removing the floating from the forumtitle and the slogan, and set the header display to flex and then have the slogan to align self : flex end
Just because I hate resorting to absolute display

**Comment by Gwenwyfar** [comment]
@SychO9 can you do this one then?

**Comment by SychO9** [comment]
Alrighty then
