### ISSUE TITLE
Undefined offset for unapproved atachments

### ISSUE THREAD

**Issue by Underdog-01** [SimpleMachines/SMF#5134]
#### Description
When a membergroup is set to admin approval and a member in that group posts attachments but does not insert them into the post (just attaches image files & does not include bbcode), "Undefined offset" errors occur in the log when viewing the thread/post. 

### Steps to reproduce
1. Set new user membergroup to admin approval for posts
2. Create new user
3. Set that user to warning level of 35%
3. Log in with that new user and post a thread that includes image attachments (jpg was tested)
4. Include them in the post but do not insert them as bbcode

### Environment
- Version/Git revision: Current
- Database Type: MySQL / MariaDB
- Database Version: MySQL 8.0.12 / MariaDB 10.3.10
- PHP Versions: PHP 5.6 - PHP 7.2.11

### Additional information/references

Two errors produced:

Undefined offset: 304
../Sources/Subs-Attachments.php (Line 1001)

Undefined offset: 306
../Sources/Subs-Attachments.php (Line 982)

**Comment by albertlast** [comment]
Coul you add the backtrace?

**Comment by Underdog-01** [comment]
Barebone SMF 2.1 install

When attempting to do as you requested, I noticed another issue.

Assuming the board being used allows permissions for that new user membergroup to read/write posts:
Also user warning levels and restrictions are as default upon installation.

If you take that new user & issue a warning level of 35%, they should be able to post whereas it should be pending moderation.

Actual behavior:
They can not post... even when I change that user back to 0% warning... they can not post.
The behavior is wack.

**Comment by Underdog-01** [comment]
In case you're wondering... 
The initial report was from my own live forum that has been upgraded to the current build. With that scenario the new member with 35% warning can post pending moderation but with the issues reported here. 

The second behavior was from a fresh local install of the latest build. With that scenario the new user with warning level of 35% can not post even when changed back to 0%.

**Comment by Sesquipedalian** [comment]
Please open a separate bug report for each issue.

**Comment by sbulen** [comment]
I cannot replicate the "undefined offset" errors.

It might help to see screenshots showing exactly how the usergroup & permissions were setup.

**Comment by Sesquipedalian** [comment]
I've moved this to the Final milestone for now, pending further information. @Underdog-01, does this error still occur for you? If so, can you give us more information on how to replicate it?

**Comment by MissAllSunday** [comment]
@Underdog-01 Does this issue still happens to you with the current build?

**Comment by Sesquipedalian** [comment]
Closed because we do not have enough information to allow us to reproduce the issue
