### ISSUE TITLE
Menu item for disabling 2fa doesn't always show up

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#5140]
#### Description
If "$_REQUEST['area']" is set for the profile, the menu option to disable two-factor authentication won't show up at all, regardless of permissions.

### Steps to reproduce
1. Enable two-factor authentication in the admin center (doesn't necessarily have to be enabled for any user)
2. Go to someone's profile then go to an area (summary, track user, etc. - doesn't matter)
3. If you hover over the "Forum profile" menu, there is no "Disable two-factor authentication" option

### Environment (complete as necessary)
- Version/Git revision: latest
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

Line 265 of Sources/Profile.php...
```php
					'hidden' => isset($_REQUEST['area']) && $_REQUEST['area'] != 'tfadisable',
```

**Comment by live627** [comment]
It's only supposed to show when tfadisable is being displayed.

**Comment by Oldiesmann** [comment]
It also shows up if no "area" is set in the profile. Why have it if it's only going to show up on one page?

On a related note, the link in the Account Settings area to disable it is missing the querystring - it just goes to the forum index.

**Comment by live627** [comment]
The menu item is there because otherwise the entire menu gets confused and
thinks the very first item should be active; in this case, summary.

I suppose I should change that *for RC2) since eit's unexpected behavior.
