### ISSUE TITLE
"Last Edit" layout can cause problems with images

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#5149]
#### Description
This is partly dependent on settings, but if you make the resolution low enough so that the "Last edit" part gets shoved down to its own line, this cuts off how much of a large image is shown.

![image](https://user-images.githubusercontent.com/89023/48666852-b5736500-ea97-11e8-803e-f07c3980d18f.png)

### Steps to reproduce
1. Make a post with a large image in it
2. Edit the post so that the "Last edit" info shows up
3. Adjust the resolution such that the "Last edit" line shows up on its own line rather than next to the date/time

### Environment (complete as necessary)
- Version/Git revision: Latest
- Database Type: MariaDb
- Database Version: Latest 10.2.x
- PHP Version: Latest 7.1.x

### Additional information/references
Screenshot taken in Chrome on Windows. Note that I have increased the default font sizes of this forum a bit due to the audience (seniors), but I would assume this can be reproduced on a default install as well. The "max size for posted images and attachments" setting is 800 on this particular forum.

**Comment by XinYenFon** [comment]
Link if possible.

**Comment by Oldiesmann** [comment]
https://www.seniorsandfriends.org/index.php?msg=144083

**Comment by XinYenFon** [comment]
Display.template change;
```
									<a href="', $message['href'], '" rel="nofollow" title="', !empty($message['counter']) ? sprintf($txt['reply_number'], $message['counter'], ' - ') : '', $message['subject'], '" class="smalltext">', $message['time'], '</a>
									<span class="page_number floatright">
										', !empty($message['counter']) ? ' #' . $message['counter'] : '', ' ', '
									</span>';

	// Show "<< Last Edit: Time by Person >>" if this post was edited. But we need the div even if it wasn't modified!
	// Because we insert into it through AJAX and we don't want to stop themers moving it around if they so wish so they can put it where they want it.
	echo '
									<span class="smalltext modified floatright', !empty($modSettings['show_modify']) && !empty($message['modified']['name']) ? ' mvisible' : '','" id="modified_', $message['id'], '">';

	if (!empty($modSettings['show_modify']) && !empty($message['modified']['name']))
		echo
										$message['modified']['last_edit_text'];

	echo '
									</span>
								</h5>
```
to this
```
									<a href="', $message['href'], '" rel="nofollow" title="', !empty($message['counter']) ? sprintf($txt['reply_number'], $message['counter'], ' - ') : '', $message['subject'], '" class="smalltext">', $message['time'], '</a>';

	// Show "<< Last Edit: Time by Person >>" if this post was edited. But we need the div even if it wasn't modified!
	// Because we insert into it through AJAX and we don't want to stop themers moving it around if they so wish so they can put it where they want it.
	echo '
									<span class="smalltext modified floatright', !empty($modSettings['show_modify']) && !empty($message['modified']['name']) ? ' mvisible' : '','" id="modified_', $message['id'], '">';

	if (!empty($modSettings['show_modify']) && !empty($message['modified']['name']))
		echo
										$message['modified']['last_edit_text'];

	echo '
									</span>
									<span class="page_number floatright">
										', !empty($message['counter']) ? ' #' . $message['counter'] : '', ' ', '
									</span>
								</h5>
```

**Spoiler alert, I wrote this at 5:17 AM, expect weirdness**

**Comment by SychO9** [comment]
Even better
```
.keyinfo h5::after {
	content: "";
	clear: right;
	display: block;
}
```
![no_clear_right](https://user-images.githubusercontent.com/20267363/48738873-94a33f00-ec52-11e8-8e9e-558d3ae82837.png)

Becomes:
![clear_right](https://user-images.githubusercontent.com/20267363/48738879-9a992000-ec52-11e8-8ba0-db4e0df89ec4.png)

**Comment by XinYenFon** [comment]
Not really because code is inconsistent, the code needs to be on end outputted before the "edit reason". Also unnecessary addition to CSS, while you can solve it with code change.

oh edit; code snip I posted above actually has extra float in it.

**Comment by XinYenFon** [comment]
Ignore the comment above partially... Code change still required but yea CSS also needed unless you can make them floatright with textalign or something.

**Comment by Gwenwyfar** [comment]
@SychO: Can you submit it in a PR?

**Comment by SychO9** [comment]
It's not really required @Antes 
this is **before** the code change **with** css
![before_code](https://user-images.githubusercontent.com/20267363/48763848-7408d280-ecae-11e8-87b6-741ced137a03.png)
this is **after** the code change **with** css
![after_code](https://user-images.githubusercontent.com/20267363/48763869-83881b80-ecae-11e8-9dd4-dcfabe9bc149.png)
this is **after** code change **without** css
![after_code_without_css](https://user-images.githubusercontent.com/20267363/48763885-8daa1a00-ecae-11e8-90ff-ad58a9c1f9a1.png)

Css change is all that's needed, but you're right the floating is the issue, text alignment would be better but applying it here would be trickier
