### ISSUE TITLE
Deny Board Access (broken)

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#5150]
#### Description
Seems that a recent comit broke the "deny board access" functionality.
https://www.simplemachines.org/community/index.php?topic=563357

### Steps to reproduce
1.  turn on "Enable the option to deny board access based on membergroup"
2.  all the boards and categories disappear.

**Comment by albertlast** [comment]
what should be the right behavior?

**Comment by SychO9** [comment]
I'm pretty sure both this issue and this one #5002 are caused because the query_see_board **6489** in Subs.php needs to be fixed

**Comment by albertlast** [comment]
Well i asked @SychO9 how it should work,
a board could got three state,
not allowed
allowed
deny

The behavior of not allowed and allowed are clear,
not able to see or is able to see.
Deny affected only boards where you allowed to see that they get not allowed.
