### ISSUE TITLE
Subs-Attachements Undefined Offset

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5162]
#### Description
```
Type of error: Undefined 
8: Undefined offset: 17
http://localhost/SMF21/index.php?/topic,20.msg54.html
C:/Apache24/htdocs/SMF21/Sources/Subs-Attachments.php (Line 972)
```
https://github.com/SimpleMachines/SMF2.1/blob/54e2dbcce94b0832b9cae7a9aa1494b19bea9279/Sources/Subs-Attachments.php#L972

### Steps to reproduce
1. On post creation page upload two attachements (images)
2. Insert one of the two
3. Change the ID of the inserted attachement to the ID of the other one (you have to change the ID to an existent ID of another attachement)
4. Post
5. Check your error log

It won't work right off the bat, you basically have to show the message "**Not a valid attachment ID.**" in the post for the error to be logged.

![attach_offset](https://user-images.githubusercontent.com/20267363/48858449-b23fe800-edbb-11e8-82fb-af3c42bec20d.png)

### Environment (complete as necessary)
- Version/Git revision: latest
- Database Type: MySQL
- Database Version: 5.7
- PHP Version: 7.1

**Comment by albertlast** [comment]
I'm not able to reproduce this error.

**Comment by SychO9** [comment]
It might have been fixed when the attachement bbcode was changed, i'll have to check again and report back.

**Comment by SychO9** [comment]
Yup this is no longer an issue, so I'm closing it.

**Comment by SychO9** [comment]
I'm re-opening this

**How to Reproduce**
1. Post an attachement
2. Use its thumbnail's ID instead of its ID
