### ISSUE TITLE
why don't they have smf

### ISSUE THREAD

**Issue by replikacep** [SimpleMachines/SMF#5163]
![sshot-1](https://user-images.githubusercontent.com/25404392/48908644-f85c8080-ee7b-11e8-92e1-3910b59cd20c.png)

Advanced picture display 

Share topics to see links

![resim1](https://user-images.githubusercontent.com/25404392/48909312-f85d8000-ee7d-11e8-8783-40300b051ace.png)

I need to get a sample I need a little XenForo review

**Comment by SychO9** [comment]
SMF 2.1 does not have such features

**Comment by replikacep** [comment]
Share topics to see links  this should be the property

Social networks need to be added to see links
Share Share Logic

**Comment by SychO9** [comment]
Considering that's not something many people want, someone can make that into a mod, but it's not needed by default

**Comment by replikacep** [comment]
do it then as module

**Comment by replikacep** [comment]
https://www.forumandroid.com/konu/port-gm8_sprout-teamwin-recovery-project-3-2-3-0-for-gm-8.12949/   enter address  Click Picture

**Comment by SychO9** [comment]
I said someone could, I'm afraid I didn't say I would
Can this be closed ?
