### ISSUE TITLE
Inconsistency with inline image attachments

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#5165]
#### Description
There's some inconsistency with image attachments and how they're displayed inline. I tested this with an image that's 4032x1960 (which I can attach here if needed). When inserting the image I leave the height and width at "auto"

If I check the box to resize images when displayed under posts, it shows it as a thumbnail, which can be clicked to view the fullsize image in a new window.

If I uncheck that box and don't set a max height, the larger image appears in the post and don't check the box, the fullsize image is displayed, but is distorted and upside down. If I click on it, it shows smaller than actual size, still upside down, but not distorted.

If I do set a max height, it displays the image with the appropriate height and width, but there is no way to view the original sized image. Nothing happens when I click on the image.

### Steps to reproduce
1. Upload a large image and insert it inline using the "auto" option for height and width
2. Play with image options in the "Attachments and Avatars" section of the admin center.

### Environment (complete as necessary)
- Version/Git revision: Latest as of today (11/22/18)
- Database Type: MariaDB
- Database Version: 10.2.x (latest)
- PHP Version: 7.1.x (latest)

### Additional information/references
In previous versions of SMF, when a larger image was displayed smaller than actual size, you could click on it to view the full size.

Images are as follows - reference image and showing the distortion/incorrect orientation when no max width or height are set. EDIT: It appears something weird is going on either with Chrome or whatever is being used to resize the image as the image shows upside down here too until you click on it.
![20181119_014816](https://user-images.githubusercontent.com/89023/48928810-a8e47780-eeb0-11e8-8c86-223f0becab46.jpg)
![screenshot_20181122_234402](https://user-images.githubusercontent.com/89023/48928812-b39f0c80-eeb0-11e8-9846-8401f771cf18.png)

**Comment by Gwenwyfar** [comment]
It showing upside-down may have to do with the image information. Some applications will use it to rotate the image.
