### ISSUE TITLE
Primary key check can bring false positives

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#5168]
https://github.com/SimpleMachines/SMF2.1/blob/b641970a1945f084792ebd9d43c4403a3b12b241/Sources/Subs-Db-mysql.php#L779-L782

The above check will trigger a database error if `$keys` contains a value not found in `$columns`.

**Comment by albertlast** [comment]
Yes this is wanted behaviour see comment and related pr.
You can close this issue.
The error message tell you what you need to do: "Change the method of db insert to insert or add the pk field to the columns array"

realted pr https://github.com/SimpleMachines/SMF2.1/pull/5031

**Comment by Sesquipedalian** [comment]
Agreed. If this happens, the coder needs to fix the query that triggered the error.
