### ISSUE TITLE
Image proxy - appears to drop redirected images

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5169]
#### Description
I just picked 21 random http: images from my forum.  With the proxy off, all 21 show.  In 2.0, with the proxy ON, 19 show & 2 are dropped.  But in 2.1, with the proxy ON, 14 show & 7 are dropped...  I see at least 4 different symptoms on the 7 items dropped.  ("dropped" means not displayed at all.)  I've confirmed this on WAMP & on Linux.  

At first glance, the biggest issue appears to be that 2.0 deals with 301/302 redirects but 2.1 doesn't.  And folks are converting their forums to https, so old posts that point to an http pic are facing a redirect.  For some reason 2.1 isn't honoring those.  

I'll log bugs in Github for the 4 different symptoms.

Note the simpsons one below fails in 2.0 as well, but the other 3 are proxied properly in 2.0.  (The difference is that curl works for the other 3 but internally curl fails for the simpsons one with a 403.)  

### Steps to reproduce
Test pics:
http://www.joness.com/gr300/pics/IMG2010/IMG2010-DROP-SHADOW-SILVER.jpg
http://smileys.sur-la-toile.com/repository/Respect/applaudir-41.gif
http://www.americanmusical.com/ProductImages/Large/p38119.jpg
http://www.avatarist.com/avatars/Cartoons/The-Simpsons/Homer-Mr-Sparkle.gif

### Environment (complete as necessary)
- Version/Git revision:  Today's
- Database Type: MySQL
- Database Version: 5.7
- PHP Version: 5.6

### Additional information/references

**Comment by MissAllSunday** [comment]
Didn't got closed with the merge, closing manually.
