### ISSUE TITLE
name of default theme in 2.1

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#517]
currently the default theme of 2.0 and 2.1 has the same name... curve in the admin panel

this will cause many headaches for the support people, as they will not know if someone has tried to use the old 2.0 default theme in 2.1 or if they are using the 2.1 default theme.

the default theme name needs to be changed [it appears in the drop down and elsewhere in the themes and layout area]

it requires a db update to whatever the name should be, IMO something different then curve to stop confusion.

**Comment by Oldiesmann** [comment]
I thought it was called "Curve 2" at some point, but I agree that we need to change it to avoid confusion. Any suggestions on the new name?

**Comment by illori** [comment]
i am not great at coming up with names... if we want to stick with something "curve" like why not something like ... "curvature"

**Comment by matthew-kerle** [comment]
The theme name is "Curve II", and I personally like it. That's honestly what it is...an updated version of SMF Curve, nothing more. I think since we're about to beta, we should stick with the naming structure and not add another thing to change.

**Comment by illori** [comment]
and that will be very confusing to people posting and telling what theme they are using, they will leave off the II and support staff will think they are trying to use the 2.0 default theme on 2.1.

**Comment by matthew-kerle** [comment]
However, you know that if they're using the default theme on SMF 2.1, it's indeed Curve II rather than "SMF Curve" or "Curve I". And likewise, if they say they're using SMF 2.0, you know they're using SMF Curve and not SMF Curve II.

I do see the potential for confusion, but in almost every case you'll ask for version number, or the actual file, and that'll eliminate any confusion.

**Comment by illori** [comment]
either way the theme has to be renamed, currently it is named curve in the database.

**Comment by ghost** [comment]
im with Lab on this, I dont think name is as important as you think, no matter what name is chosen people wont like it so I think Curve2 or Curve II is best for it, as for the name change in db to change it to Curve2 or CurveII thats easy.

**Comment by illori** [comment]
the name "Curve2" instead of "Curve II" would be fine with me, as people will be less likely to leave out the 2 as it is more part of the name, without the space.

**Comment by ghost** [comment]
if oldies agrees we can just call it Curve2 ... getting marketing ideas n ow

**Comment by Oldiesmann** [comment]
I don't care what we call it. Whatever makes it easier for you guys

**Comment by illori** [comment]
if we are to stick to curve, then curve2 is fine, but i think curvature would work as well. sounds like more people here think curve2 would be best.
