### ISSUE TITLE
Alerts are broke

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#5176]
I think this says it all really:

https://www.simplemachines.org/community/index.php?topic=563540.0

1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type: mariadb
- Database Version: 
- PHP Version: 7.1 (7.0 at the time of upgrade)

### Additional information/references

**Comment by gevv** [comment]
try it, it could work; https://www.simplemachines.org/community/index.php?topic=563540.0

**Comment by gevv** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/5020

**Comment by smfbigguy** [comment]
All that was checked already. Still broke. I unchecked one option and that was to log profile edits.

**Comment by smfbigguy** [comment]
Changed those setting again and still no love. I think they are broke. :(

**Comment by albertlast** [comment]
possible introduce by the pr: #4834 by @jdarwood007

**Comment by gevv** [comment]
@smfbigguy    is the problem solved?

Rc1  topic subscription       alert and e-mail not working

Admin page test mail work no problem

**Comment by smfbigguy** [comment]
Alerts work and so does test email. There is an open issue though with alerts. Please see that issue.

https://github.com/SimpleMachines/SMF2.1/issues/5518

**Comment by gevv** [comment]
Ok. thanks
