### ISSUE TITLE
Malformed JSON for $modSettings['displayFields'] when using Postgres cache

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#5178]
#### Description
Set up a local SMF install with PostgreSQL as the database. I set the cache option to use PostgreSQL as well since that's available. When viewing the topic I posted, I get the following error:
```
Json decode error: Syntax error, malformed JSON
http://localhost/smf/index.php?topic=2.msg3
/srv/http/smf/Sources/Load.php (Line 1566)
```

### Steps to reproduce
1. Set up SMF with PostgreSQL cache
2. View a post made by a registered user

### Environment (complete as necessary)
- Version/Git revision: Latest
- Database Type: PostgreSQL
- Database Version: 11.1
- PHP Version: 7.2.12

### Additional information/references
Backtrace:
```
#0: smf_json_decode()
Called from /srv/http/smf/Sources/Load.php on line 1568
#1: loadMemberContext()
Called from /srv/http/smf/Sources/Display.php on line 1564
#2: prepareDisplayContext()
Called from /srv/http/smf/Themes/default/Display.template.php on line 254
#3: template_main()
Called from /srv/http/smf/Sources/Load.php on line 2460
#4: loadSubTemplate()
Called from /srv/http/smf/Sources/Subs.php on line 3164
#5: obExit()
Called from /srv/http/smf/index.php on line 153
```

This is the actual JSON for $modSettings['displayFields']:
```
[{"col_name":"cust_icq","title":"ICQ","type":"text","order":"1","bbc":"0","placement":"1","enclose":"<a class=\\"icq\\" href=\\"\\/\\/www.icq.com\\/people\\/{INPUT}\\" target=\\"_blank\\" title=\\"ICQ - {INPUT}\\"><img src=\\"{DEFAULT_IMAGES_URL}\\/icq.png\\" alt=\\"ICQ - {INPUT}\\"><\\/a>","mlist":"0"},{"col_name":"cust_skype","title":"Skype","type":"text","order":"2","bbc":"0","placement":"1","enclose":"<a href=\\"skype:{INPUT}?call\\"><img src=\\"{DEFAULT_IMAGES_URL}\\/skype.png\\" alt=\\"{INPUT}\\" title=\\"{INPUT}\\" \\/><\\/a> ","mlist":"0"},{"col_name":"cust_yahoo","title":"Yahoo! Messenger","type":"text","order":"3","bbc":"0","placement":"1","enclose":"<a class=\\"yim\\" href=\\"\\/\\/edit.yahoo.com\\/config\\/send_webmesg?.target={INPUT}\\" target=\\"_blank\\" title=\\"Yahoo! Messenger - {INPUT}\\"><img src=\\"{IMAGES_URL}\\/yahoo.png\\" alt=\\"Yahoo! Messenger - {INPUT}\\"><\\/a>","mlist":"0"},{"col_name":"cust_loca","title":"Location","type":"text","order":"4","bbc":"0","placement":"0","enclose":"","mlist":"0"},{"col_name":"cust_gender","title":"Gender","type":"radio","order":"5","bbc":"0","placement":"1","enclose":"<span class=\\" generic_icons gender_{KEY}\\" title=\\"{INPUT}\\"><\\/span>","mlist":"0",,"options":["None","Male","Female"]}]
```

**Comment by albertlast** [comment]
The amount of ``\\`` looks wrong,
Should be ``\``

**Comment by albertlast** [comment]
Well two problem first i'm not able to create this issue,
second your line of code are off again.
Could it be that you use a mod?

**Comment by Oldiesmann** [comment]
The line number for Load.php in the backtrace is off because of code I added to dump the contents of $modSettings['displayFields'].

The extra slashes are there at install so I guess that's what needs to be fixed.

**Comment by albertlast** [comment]
possible introduce the issue by the pr  #3954 https://github.com/SimpleMachines/SMF2.1/commit/750af0e8f59383c6ecb3bc39280e19d6c28bcfc3
from @sbulen 
the pg setup is broken since then,
mysql setup needs to be checked.

**Comment by albertlast** [comment]
@live627 for this a pr exists

**Comment by live627** [comment]
okie dokie 😃 

IMO that PR probably should only fix pg code. @Sesquipedalian may feel different about that.

**Comment by albertlast** [comment]
Like in many other places is the pg code is right version and mysql the issue source.

But I see not the label for a sign if the pr right or not,
Only the existence is with this shown.
