### ISSUE TITLE
Image proxy - drops images, fsocket partial downloads

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5182]
#### Description
Two more images getting dropped by the Image Proxy.  What appears to be happening here is that the fsockets attempt is retrieving the text headers only.  In one of these, an http 206 is used, which tells you to do a 2nd request to get the rest of the data (the image).  

Note that curl works properly for both of the images below.  But since the fsockets call was successful, curl is not called.  Since only the text headers were returned, the proxy thinks there is text only and aborts caching the image.   

Potential solutions:  
 - When only text is retrieved, attempt a 2nd fsockopen call 
 - When text is retrieved, fall back to curl
 - When text is retrieved, ball back to using a redirect

### Steps to reproduce
Paste the following in to a message.  With the image proxy off, the images are displayed.  With the image proxy on, they are not:
```
Photo: 1037
[img]http://store.caig.com/core/media/media.nl?id=1966&c=ACCT113328&h=17b55c298ab2fe47a0c8[/img]
Photo: 1046
[img]http://images.samash.com/sa/ZMS/ZMS50GXXX-P.fpx?cell=540,400&qlt=90&cvt=jpg[/img]
```

### Environment (complete as necessary)
- Version/Git revision: Todays
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 5.6

### Additional information/references
Last 2, I promise...   

I wrote a utility to extract http image URLs from 600 unique hosts from my forum posts.  I then compared non-proxied posts to proxied posts, and audited which images were dropped.   I did this because I had seen many images dropped, & knew there to be several different sources of the errors. 

_The GOAL should be that ZERO images get dropped when you enable the image proxy..._  

I have thousands more, but I'm getting tired of comparing images...

**Comment by albertlast** [comment]
I think you goal is wrong,
reason why you drop many security checks.

**Comment by sbulen** [comment]
That's why it's important to align on the goal.   

Folks actually use forums to share information.  That's the whole purpose.  Forums don't exist to provide fun coding opportunities for programmers.  Dropping users' forum content renders the proxy feature useless, IMO.  

If our design approach allows images to be dropped, I will never use that feature, and will actively discourage usage.  At the very, very least, forum users should be aware that X% of their linked images in posts will simply disappear with no warning or placeholder whatsoever.

Some crude stats from when I started logging these issues:
- Only 67% of proxied images served by the proxy were OK... 
- 22% of proxied images were dropped due to redirects (Issue #5169 , PR #5173 merged)
- 6% of proxied images were dropped due to encoding issues (Issue #5170 , PR #5174 )
- 4% of proxied images were dropped due to fsock/curl restrictions (Issue #5172 , PR #5175 )
- 1% of proxied images were dropped due to two-stage downloads (This issue, #5182, PR #5184 ) & special characters (#5181 , PR #5183 )

Alternative approaches are welcome!  If there is a better way to do it, then submit better PRs.  My PRs fall back on redirects, which will result in mixed use pages.  (If redirects are that bad, we shouldn't be doing them at all, but we have always done redirects for large images.)

But we cannot just rampantly drop images with no warning or placeholder.  

One possible idea:  A strict-SSL mode.  Offer an option where redirects won't be supported at all.  This may be helpful if someone absolutely requires padlocks.   

Or...  How is it your browser always gets the images?  Is there an alternative approach, e.g., streams?  Or...  At the very least, display a "sorry cannot serve this image" placeholder...  Or...  log errors when caching fails?  That'd be helpful...   Or....  Some combination of the above...

**Comment by albertlast** [comment]
not all images a shared by the image proxy,
only non https images are cached,
so the number is lower of image which got lost.

alternative  solution would to use a own image proxy,
mods already avaible for 2.1
maybe i should add the mod when i mention it...
https://custom.simplemachines.org/mods/index.php?mod=4175

**Comment by sbulen** [comment]
We shouldn't be discarding ANY user content.

**Comment by tinoest** [comment]
Photo: 1046
[img]http://images.samash.com/sa/ZMS/ZMS50GXXX-P.fpx?cell=540,400&qlt=90&cvt=jpg[/img]

This one returns the wrong headers and states;

Request URL: http://images.samash.com/sa/ZMS/ZMS50GXXX-P.fpx?cell=540,400&qlt=90&cvt=jpg
Request Method: GET
Status Code: 304 Not modified
Remote Address: 65.74.179.165:80
Referrer Policy: no-referrer-when-downgrade
Content-Length: 0
Content-Security-Policy: default-src https: data: unsafe-inline unsafe-eval
Content-type: text/html
Date: Sun, 02 Dec 2018 12:33:37 GMT
Expires: Mon, 03 Dec 2018 11:08:03 GMT
Last-modified: Mon, 15 Jul 2013 18:20:34 GMT
Public: GET
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

I can't see how the proxy can deal with that other than just returning the url for the image.

**Comment by sbulen** [comment]
That's what the PR does.

**Comment by albertlast** [comment]
which create a mixed content error -> security issue.
you should add ad least a option if the proxy image should be work unsafe or not.

**Comment by sbulen** [comment]
As pointed out earlier, the proxy has always used that technique.  (For large files.)

The "strict ssl" option is a good idea.  I suggested it above.

**Comment by albertlast** [comment]
which is not good by default,
but to open this gate make the thing not better.
