### ISSUE TITLE
Undefined variable `$dif`

### ISSUE THREAD

**Issue by KarelWintersky** [SimpleMachines/SMF#5190]
#### Description
Undefined variable `$dif`

### Steps to reproduce
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Class-Graphics.php#L304

```
if (($idx == -1) || ($d < $dif))
			{
				$idx = $i;
				$dif = $d;
			}
```
`$dif` is undefined anywhere in scope.

### Environment (complete as necessary)
- Version/Git revision: all

### Additional information/references

**Comment by Oldiesmann** [comment]
This is old code that was written by someone else not involved with SMF (see the information in the file header comments). It's only used if you don't have the appropriate GIF functions via GD. I don't know that there's much SM can do about this.

**Comment by KarelWintersky** [comment]
make GD **required** PHP extension and remove old code from repo forever.

**Comment by jdarwood007** [comment]
Could try to define $dif = null; before the for loop and see if that resolves it.  It should be how PHP would handle this before.

**Comment by MissAllSunday** [comment]
Indeed this is only an issue on host with weird configurations, ie, when they explicitly need a var to be set, not a bad policy or bad configuration, in fact I favor var declaration for everything

**Comment by KarelWintersky** [comment]
vars must be defined always. Silent definition is bad practice
