### ISSUE TITLE
Enableling "Automatically link posted URLs" causes malformed img tags in posts

### ISSUE THREAD

**Issue by Rsmith19r** [SimpleMachines/SMF#5192]
#### Description
--Description Here--
If Automatically link posted URLs is enabled, posts with html tags in the body are malformed when output. <a href= is inserted into the src= attribute.

The problem is in the parse_bbc function somewhere. If the call to that function in Display.php is commented out, the links are correct. Disabling Automatically link posted URLs also eliminated the problem.  
### Steps to reproduce
1. enable Automatically link posted URLs
2. View a message with embedded html 

### Environment (complete as necessary)
- Version/Git revision: 2.1 Beta 4
- Database Type: MySQL
- Database Version: 5.6
- PHP Version: 5.6

### Additional information/references

**Comment by Rsmith19r** [comment]
<img src="<a href="http://www.address.com/forum/Smileys/default/tongue.gif" class="bbc_link" target="_blank" rel="noopener">

**Comment by Rsmith19r** [comment]
`<img src="<a href="http://www.address.com/forum/Smileys/default/tongue.gif" class="bbc_link" target="_blank" rel="noopener">`

**Comment by tinoest** [comment]
It’s an issue with the preg_match for urls, had a similar issue with it recently. I’m not sure if you are meant to send html to the parse_bbc function.
