### ISSUE TITLE
XML preview eats ampersands and cuts the rest of the message

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#5195]
#### Description
--Description Here--

### Steps to reproduce
1. Create a new topic
2. write a message & text to observe snipped out
3. hit preview and  observe the both the ampersand and all text following it is gone

### Environment (complete as necessary)
Firefox

### Additional information/references
I'm guessing that it isn't encoded.

**Comment by MissAllSunday** [comment]
looking at how preview is handled, do we really need to mix preview and posting? ie using post() to handle previews?

we're not really handling other stuff besides subject and body and while xml has a stubborn and steady fanbase I would much prefer using json for this kind of stuff.

The way I see it, previewing is just giving some text some format, thats it, it doesn't involve permissions or other types of logic, just send some text and return it formatted it.

So perhaps a generic preview action, something that can be used for something more than just posts, send some params in a nice json encoded string and return an even nicer json response.

**Comment by Sesquipedalian** [comment]
That sounds like a good idea for 3.0, @MissAllSunday, but not 2.1.

**Comment by MissAllSunday** [comment]
Nah, this is just to de-cluttering Post() and Post2(). 

I would rather fix this properly than trying apply some encoding func somewhere in the js and hope it doesn't break anything else.
