### ISSUE TITLE
Preview  "+" and  "&" problem

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#5199]
#### Description
Preview  + not see 

If there is a "&" character, the preview is cutting there, and the message doesn't seem to continue.

https://postimg.cc/4HmSqFvp

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by frandominguezl** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/5195
