### ISSUE TITLE
seo should be smf

### ISSUE THREAD

**Issue by betonkamil** [SimpleMachines/SMF#5206]
seo neden smf de seo dedikleri tüm forumlarda gelmiyor bağlantı yapısı değişmeli
seo why do not come in all the forums why they say smf de seo
link structure should change
mod makers don't want seo to come  Everything is not money
connection structure must be serf url

**Comment by betonkamil** [comment]
XenForo vBulletin These designs are using seo

**Comment by albertlast** [comment]
Could you please name the feature which you mean?
SEO is a big collection of stuff and
some already exists in 2.1.

**Comment by betonkamil** [comment]
link structure exampl
serlf url structure 
h1 h2 tags
Sitemaps
ping throwing

**Comment by betonkamil** [comment]
XenForo Forum System Seo Settings How To ...

The biggest feature of XenForo is Seo. In addition, the XenForo system hosts Google's recommended connection structure. And there is a simple system to provide ease of merging.

XenForo Seo How General Settings Should Be?

Forum is the site where your system is installed. After this tracking is complete, click Admin Control Panel> Options> Forum General Settings> Site title and site setup from the current field.

Search Engine Optimization How To ...

Admin Control Panel> Options> Search Engine Optimization (SEO)

Easy URL: Take a check.

Apply Thread to Connect: Take a mark.

XenForo Catagori and Forum Link Structure How does it work?

Creating forums and categories in general. I like it, instead of ...

**Comment by betonkamil** [comment]
With this going, there will be no smf user

**Comment by LexArma** [comment]
"Built-in" SEO for forums is, really - no matter how you put it - irrelevant. There are virtually no achievable results to be had, and what little there is, SMF mostly does already.

**Comment by betonkamil** [comment]
does not come to your business  
to whom you will sell seo pro yu

**Comment by LexArma** [comment]
Just to make it clear, we do not sell anything to anyone. SMF is free, so are many fine mods. 
Some people do also make mods that they sell for money, and that is their business, and perfectly fine as well - but that is not us.
