### ISSUE TITLE
Editor adds quotes to bbc link

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5209]
Editor adds " either end of url " when adding a bbc link
`[url="https://www.tinyportal.net"]TinyPortal Support[/url]`

**Comment by Sesquipedalian** [comment]
This is expected behaviour in 2.1.

**Comment by lurkalot** [comment]
While I can do nothing but except this response.  I'm still thinking this will cause problems, especially when linking from one site to another such as in this example where someone posted a link from 2.1. https://www.simplemachines.org/community/index.php?topic=567688.msg4019234#msg4019234

**Comment by SychO9** [comment]
They posted bbcode from an SMF2.1 installation to a SMF2.0 installation, it's only natural that if you post bbcode from a software to a different one that it wouldn't work.
