### ISSUE TITLE
Token verification failed in smiley

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#521]
`There is one smiley in this smiley set not yet imported. Click here to import it now.`

`Token verification failed. Please go back and try again.`

**Comment by Oldiesmann** [comment]
The problem is that we're trying to validate the same token twice:

Lines 198-202 of ManageSmileys.php:

```
// They must've been submitted a form.
if (isset($_POST['smiley_save']))
{
    checkSession();
    validateToken('admin-mss', 'request');
```

Then we try to validate it again a little further down if we're importing something (lines 281-285):

```
// Importing any smileys from an existing set?
if ($context['sub_action'] == 'import')
{
    checkSession('get');
    validateToken('admin-mss', 'request');
```

**Comment by emanuele45** [comment]
Unlikely (but I have not checked yet).

The first you posted is on $_POST, while what I observed is from a $_GET (the "click here" is just a link that forwards to somewhere else).

**Comment by Oldiesmann** [comment]
I see that now. I wasn't paying attention :P

The problem would then be that the token data is never sent to the server when you go to that URL:

```
            $context['current_set']['import_url'] = $scripturl . '?action=admin;area=smileys;sa=import;set=' . $context['current_set']['id'] . ';' . $context['session_var'] . '=' . $context['session_id'];
```

The only options here are to either remove the token check, or put it in the URL.

**Comment by jdarwood007** [comment]
Tokens are ok in urls.  Their purpose is a one time use key that is valid only for that form or script.  A page refresh will generate a new token.  Tokens help stop CSRF attacks by making them much more difficult for an attacker to craft a URL to send you.

**Comment by colinschoen** [comment]
Good idea.
