### ISSUE TITLE
Installer - not working at all - knocked back to Welcome

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5210]
#### Description
Cannot install at the moment.  Keep getting knocked back to welcome.  

### Steps to reproduce
1. Attempt an install

### Environment (complete as necessary)
- Version/Git revision:  Current as of now
- Database Type:  MySQL
- Database Version:  5.7
- PHP Version:  5.6

### Additional information/references
Very similar to #4483

**Comment by Sesquipedalian** [comment]
Uh-oh. We'll need to fix that ASAP. You've had a lot of experience dealing with the installer in the past, @sbulen. Would you be willing to take this one?

**Comment by sbulen** [comment]
Yep.
