### ISSUE TITLE
Weekly digest is pushed daily

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#5212]
Uhh, not sure what to type here...

**Comment by Sesquipedalian** [comment]
Just to be sure, did you close this because the behaviour no longer occurs, @live627?

**Comment by live627** [comment]
It needs a complete rewrite because it's so very buggy. I have ahd this enabled on bigguy's site (wub) for a few months now and could not discern a clear pattern.

**Comment by Sesquipedalian** [comment]
🙁
