### ISSUE TITLE
User stats doesn't take timezone into account in PostgreSQL

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#5217]
#### Description
In PostgreSQL, the user stats page doesn't take the timezone into account. On my test board, I've made 3 posts - two between midnight and 1am my time and one between 10pm and 11pm my time. When I go to my user stats page, it shows one post made between 3 and 4am and 2 posts made between 5 and 6am. My timezone is Eastern (UTC-5). This appears to only happen with PostgreSQL as a MySQL test board doesn't have this problem (though the two are running on different machines - the Postgres test board is on my laptop while the other one is on my server)

### Steps to reproduce
1. Set the timezone in your profile to something other than UTC
2. Make some posts
3. Go to your profile then Profile Info -> User Stats

### Environment (complete as necessary)
- Version/Git revision: latest
- Database Type: PostgreSQL
- Database Version: 11.1
- PHP Version: 7.3.0

Screenshots:

![image](https://user-images.githubusercontent.com/89023/50265156-46699300-03ec-11e9-9f6d-4227a67170e7.png)
![image](https://user-images.githubusercontent.com/89023/50265220-90eb0f80-03ec-11e9-904f-3b5face6ae3f.png)

**Comment by Sesquipedalian** [comment]
Fixed in #5216
