### ISSUE TITLE
8: Undefined index on profile theme options

### ISSUE THREAD

**Issue by shnazzle** [SimpleMachines/SMF#5220]
#### Description
Clicking the "change" link on the forum profile Look and Layout page, by Current Theme, triggers a number of Undefined Index errors

Type of error: Undefined
8: Undefined index: display_quick_mod
8: Undefined index: messages_per_page
8: Undefined index: topics_per_page

On URL:
http://localhost/roc_2/index.php?action=profile;area=theme;u=1

File: C:/wamp64/www/roc_2/Themes/default/languages/Settings.english.php (edit_options sub template - eval?)
Line: 1719

### Steps to reproduce
1.  Log in
2.  From profile dropdown open Look and Layout
3.  On Current Theme click "change" 

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1 Beta 3
- Database Type: MySQL InnoDB
- Database Version: 5.7.14
- PHP Version: 5.6.25 and 7.0.10

### Additional information/references
This is a complete vanilla install with no configuration changes and 2 users.
Not using latest git pull, but using latest available download off website as I can't find a previous issue linking to this anyway

**Comment by SychO9** [comment]
So you're using beta 3 ?
Can't reproduce this on the latest git revision. It was probably fixed.

**Comment by shnazzle** [comment]
Fair enough. Yes I'm using beta 3,just downloaded yesterday from the smf site. I couldn't find an existing open or closed issue for it so thought I'd raise it

**Comment by albertlast** [comment]
Beta 3 is to old, please use the github or nightly version.
And don't try to upgrade from beta 3 to github/nightly version.

**Comment by shnazzle** [comment]
Ah OK. Sorry, this can be closed then if the build I have is quite old. I'll try a clone of the latest

**Comment by shnazzle** [comment]
Just to confirm, this issue is indeed resolved now. I can't reproduce it on the latest release-2.1 build
