### ISSUE TITLE
Icons are gone

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#5224]
#### Description
with the last pr i got this:
![grafik](https://user-images.githubusercontent.com/1782906/50340703-613b2500-051c-11e9-95d9-cf882da11ccc.png)

 i didn't apply the db changes from https://github.com/SimpleMachines/SMF2.1/pull/5221
because mostly gender stuff was changed here

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references
The issue got introduce by https://github.com/SimpleMachines/SMF2.1/pull/5221 from @Gwenwyfar 

From my pov the change is to big to merge this in this time slot -> revert the change and apply is after rc1.

**Comment by SychO9** [comment]
The image wasn't renamed
`generic_icons_sprite.png` --> `main_icons_sprite.png`

**Comment by Gwenwyfar** [comment]
Oh my bad. I missed that. Thanks, SychO. Will get a fix up shortly.
