### ISSUE TITLE
Navigation won't open on Chrome/FF [RC1]

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#5228]
This started with RC1 after the renames.
https://mobasuite.com/forum/index.php

**Comment by Gwenwyfar** [comment]
Is that using the very latest build? I'm not having issues in my test site.

**Comment by SychO9** [comment]
what navigation ?

**Comment by Gwenwyfar** [comment]
I assume he means the menu. 

I see you have some custom code as well to remove the footer and header, is there anything else you have changed?

**Comment by ghost** [comment]
The profile menu won't open nor any other of the two options.

For CSS changes, it's just #header, #footer set to display: none;

I fixed the icon issue, it was an error on my part.

**Comment by Gwenwyfar** [comment]
Any changes/mods elsewhere?

**Comment by ghost** [comment]
default theme is straight from latest .zip (RC1)

The 3 navigation items work on first login, but as soon as you change topic it stops working.

All else is working.

**Comment by Gwenwyfar** [comment]
I can't replicate this.

**Comment by ghost** [comment]
Erased all files and did a clean upgrade, same thing.

But w/e its not gamebreaking.

**Comment by Gwenwyfar** [comment]
I'm still not even sure what is the problem and what causes/triggers it, if you could provide more details that would help.

**Comment by ghost** [comment]
CSS ID "top_section"

From what i noticed from previously is that there might have been a "dropdown.css" which Isnt there in RC1.

And I am using Firefox 64

No problems on Edge

It's not a caching issue either as I've cleared it.

**Comment by SychO9** [comment]
there was no *dropdown.css*

the only difference between when it works the first time and when it doesn't is `type="text/javascript"` is added to all script elements the second time, by default there are none.

Also you have some paths that still need to be changed to **https**

**Comment by ghost** [comment]
It was CloudFlare RocketLoader which was causing the issue.

Last questions, where in DB are custom avatars stored ?

**Comment by SychO9** [comment]
Then this can be closed.
Files are not stored in the DB they are stored in the forum directory in **custom_avatar** folder.
