### ISSUE TITLE
quick reply  add image problem

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#5230]
"add" button does not appear

![untitled 1](https://user-images.githubusercontent.com/5096676/50376633-42ba5400-0618-11e9-9d32-bc3bb654fd49.png)

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by frandominguezl** [comment]
It does appear for me.

**Comment by SychO9** [comment]
> It does appear for me.

I don't remember who, but someone on IRC said it was probably a language problem

**Comment by frandominguezl** [comment]
Then the op should leave more details about the issue

**Comment by Oldiesmann** [comment]
> > It does appear for me.
> 
> I don't remember who, but someone on IRC said it was probably a language problem

That was me...

**Comment by MissAllSunday** [comment]
This is indeed a language/language file issue.
