### ISSUE TITLE
rtl.css image file no longer exists

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5232]
rtl.css image file no longer exists

/* Themes */
.is_directory {
	padding-right: 18px;
	background: url(../images/admin/boards.png) no-repeat 100% 0;
}

**Comment by SychO9** [comment]
gotta revise rtl.css :/

**Comment by Gwenwyfar** [comment]
Yeah, that'd be good. The problem is I have no idea how it _should_ look as I'm not familiar with any ltr languages. Might need to grab someone to check it for us. But I imagine we might be able to flip the icons side with it being on a pseudo element now, too.

**Comment by SychO9** [comment]
no worries, I am familiar with an **rtl** language

**Comment by Gwenwyfar** [comment]
Whoops xD

Perfect then :)
