### ISSUE TITLE
downloadAvatar in sources/subs-graphics.php undefined  $path

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5233]
downloadAvatar in sources/subs-graphics.php undefined  $path

```
		// Remove the .tmp extension from the attachment.
		if (rename($destName . '.tmp', empty($avatar_hash) ? $destName : $path . '/' . $attachID . '_' . $avatar_hash . '.dat'))
		{
			$destName = empty($avatar_hash) ? $destName : $path . '/' . $attachID . '_' . $avatar_hash . '.dat';
			list ($width, $height) = getimagesize($destName);
```

In previous versions of SMF had this code in in it.
		// Walk the right path.
		if (!empty($modSettings['currentAttachmentUploadDir']))
		{
			if (!is_array($modSettings['attachmentUploadDir']))
				$modSettings['attachmentUploadDir'] = unserialize($modSettings['attachmentUploadDir']);
			$path = $modSettings['attachmentUploadDir'][$modSettings['currentAttachmentUploadDir']];
		}
		else
			$path = $modSettings['attachmentUploadDir'];

**Comment by Sesquipedalian** [comment]
Apparently there were conflicting edits made to the code between Dec 25, 2013, and Jan 17, 2014, that were not resolved quite correctly.
