### ISSUE TITLE
sources/Subs-Db-mysq.php $last_id

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5234]
Looks like last_id should be $old_id in the code below since $last_id is not defined any where

`			$old_id = $smcFunc['db_insert_id']();

			$smcFunc['db_query']('', '
				' . $queryTitle . ' INTO ' . $table . '(`' . implode('`, `', $indexed_columns) . '`)
				VALUES
					' . $insertRows[$i],
				array(
					'security_override' => true,
					'db_error_skip' => $table === $db_prefix . 'log_errors',
				),
				$connection
			);
			$new_id = $smcFunc['db_insert_id']();

			// the inserted value was new
			if ($last_id != $new_id)
			{
				$ai = $new_id;
			}
			// the inserted value already exists we need to find the pk
			else
			{`

**Comment by albertlast** [comment]
The error was fixed by the pr https://github.com/SimpleMachines/SMF2.1/pull/5167
and got reintroduce by https://github.com/SimpleMachines/SMF2.1/pull/5125 from @Gwenwyfar .

**Comment by Gwenwyfar** [comment]
Must have been one of the file conflicts.
