### ISSUE TITLE
function getAttachsByMsg($msgID = 0) Missing global $user_info

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5235]
function getAttachsByMsg($msgID = 0) Missing global $user_info  in Sources/Sub-Attachments.php
`if (!$row['approved'] && $modSettings['postmod_active'] && !allowedTo('approve_posts') && (!isset($all_posters[$row['id_msg']]) || $all_posters[$row['id_msg']] != `$user_info['id']))``

**Comment by albertlast** [comment]
It would be a improvment,
when you post code snipets from the project that you use perma links from github,
the result look better:
https://github.com/SimpleMachines/SMF2.1/blob/cc6b057dda6ec6cdadfb610ef385113c6e7e82ba/Sources/Subs-Attachments.php#L1117
