### ISSUE TITLE
unneeded code in install.php

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5239]
mysql_group_by_fix not used anywhere

	// Check if we need some stupid MySQL fix.
	$server_version = $smcFunc['db_server_info']();
	if (($db_type == 'mysql' || $db_type == 'mysqli') && in_array(substr($server_version, 0, 6), array('5.0.50', '5.0.51')))
		updateSettings(array('db_mysql_group_by_fix' => '1'));

**Comment by Sesquipedalian** [comment]
These unnecessary lines appear in both install.php and upgrade.php
