### ISSUE TITLE
oSettings.tooltipContent just in the open and one typo smf_jquery_plugins.js

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5248]
oSettings.tooltipContent is just in the js file in a random spot it looks like.
Also position comment under it is mis spelled.

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/scripts/smf_jquery_plugins.js#L154

					oSettings.tooltipContent

					// show then position or it may postion off screen

**Comment by albertlast** [comment]
Thanks for adding the link to loc,
but you safe your work when you use perma link:

![grafik](https://user-images.githubusercontent.com/1782906/50385172-fbdc6500-06d0-11e9-93e9-3cefd74130e5.png)

**Comment by VBGAMER45** [comment]
Thanks for tip
