### ISSUE TITLE
Call to undefined function random_int() in upgrade.php on line 564

### ISSUE THREAD

**Issue by pouvik** [SimpleMachines/SMF#5251]
#### Description
Upgrade.php fails when running due to no fallback code for non php 7 sites to quote oldiesmann
"random_int doesn't exist prior to PHP 7, but the way the code is written there's supposed to be a compatibility function in Sources/Subs-Compat.php"

### Steps to reproduce
1.  Run upgrade.php

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by albertlast** [comment]
Error got introduce by @MissAllSunday and pr #5138

**Comment by albertlast** [comment]
Please test the upgrade with the changes from the pr #5252
