### ISSUE TITLE
Private Message sent via Warning system has no recipient when replying

### ISSUE THREAD

**Issue by shnazzle** [SimpleMachines/SMF#5267]
#### Description
A user that receives a warning can reply to the warning Private Message.
However, no recipient is auto-populated.

If a Warning PM purposely has no recipient, it shouldn't be made possible to reply. Otherwise, SMF should populate an admin/moderator user or group (of choice?) as recipient.

### Steps to reproduce
1. Create warning for user
2. Log in as user and view PM warning
3. "Reply with quote"
4. Type reply and send -> Results in "no recipient" error

### Environment (complete as necessary)
- Version/Git revision: 2.1 beta 3 - git clone from 21/12/2018
- Database Type: MySQL
- Database Version: 5.7.14
- PHP Version: 7.0.10

### Additional information/references

**Comment by Oldiesmann** [comment]
It should probably be sent from whoever issued the warning

**Comment by Arantor** [comment]
This has always been the case, though. Warnings were always sent (intentionally) anonymously, by sending a PM without a sender. Maybe simpler to remove the reply option there.

**Comment by frandominguezl** [comment]
I do think that's the easiest solution too.

**Comment by LexArma** [comment]
It shouldn't really reveal who sent the warning, yet I think we should allow replying to it. 

The way it is now is a good compromise, in most cases users should be able to name an admin or moderator they want to approach on the issue.

**Comment by shnazzle** [comment]
Agreed it should not reveal the actual sender. Maybe the very easiest thing would be to prepopulate with the webmaster email address. This is a stored (global?) value anyway.

**Comment by Arantor** [comment]
Repopulating with webmaster email doesn't work - because this is a PM, not an email, so you can't reply to it in that sense.

Replying to this is actually not a simple task because there's no recipient, so you need to have some other way to work out if the message can be replied to, and funnel it somewhere else, and make sure the relevant moderators can see it and action it. Lot of work, that.

Or, just hide the reply button and leave it be able to be reported (which does offer the option of choice of admin).

**Comment by shnazzle** [comment]
I think the most intuitive way would be for there to be a check to see if the sender is the forum. If so, disable the reply. Then in the message itself, admins can choose to put a message in to tell the person to message the admin or a moderator group of choice.

**Comment by Arantor** [comment]
I think that was what I suggested ;)

**Comment by shnazzle** [comment]
We agree then haha
Now someone kindly go forth and implement. Don't make me get my code on

**Comment by Arantor** [comment]
More likely to get fixed if everyone contributes a little bit :)

**Comment by shnazzle** [comment]
Just forked to fix and noticed that the behaviour is actually different between the Warning notifications and "normal" PMs. With a normal PM, the "Reply" button is shown. With notifications this button isn't shown (seems someone has thought of this before), but the "Reply with quote" button is shown. So I guess just a case of disabling that as well

**Comment by LexArma** [comment]
What about if the reporting is disabled. I think the quote button was there originally to allow for easy forwarding. Now if we remove it, and reporting is disabled, it will be a bit more difficult.

**Comment by shnazzle** [comment]
Is reporting disabled based on that change? It only disables the showing of the reply button. Reporting should still be possible

**Comment by LexArma** [comment]
No, that does not change reporting - but reporting of PMs is a forum wide setting. Not every install will allow it.

**Comment by shnazzle** [comment]
In any case, the fix I proposed (https://github.com/SimpleMachines/SMF2.1/commit/1714d7980eb6d812dbf7147493dd4e5539dcce9f ) should be OK. If reporting is turned off forum-wide, it's up to the admin to take the queue from the sample template to tell users to message the admin if they need to. The only thing I would say about the fix is that I'd prefer not to use a magic number like 0,inztead of ['member'] ['is_admin'] which doesn't seem to exist there

**Comment by Arantor** [comment]
Actually that fix makes more sense because there can be other cases where a PM can be in the system without a valid recipient like that, not just warnings.

**Comment by LexArma** [comment]
Well yeah, it works, and the addition to the warning template is good too. Not a big problem to lose the quote button.

**Comment by sbulen** [comment]
@shnazzle - were you going to submit this PR?  Just checking!

**Comment by frandominguezl** [comment]
@sbulen https://github.com/SimpleMachines/SMF2.1/issues/5267

**Comment by sbulen** [comment]
@frandominguez03 #5267 is this issue, not a PR.  

The PR mentioned above is still in shnazzle's private repo, and has not been submitted.  

There are several similar items out there - where folks have applied "Has fix" labels, but there is no PR yet submitted that I can find.

**Comment by illori** [comment]
then we should remove the has fix label from this PR?

**Comment by shnazzle** [comment]
Hmm... I.must have done something wrong then as I put in a request yonks ago for my code to be merged in.

I put it in here. As per post above https://github.com/SimpleMachines/SMF2.1/commit/1714d7980eb6d812dbf7147493dd4e5539dcce9f

**Comment by illori** [comment]
a warning should be discussed IMO with the moderators before going to the admin. i would suggest that change be made to the language string.

**Comment by LexArma** [comment]
I'm not so sure about that. I'd say a user that wants to argue a moderator action would more often be directed to contact the admin. Also what if the forum has no moderators, a forum always has an admin? I'd say either stick with admin, or replace it with something more neutral like forum staff.

**Comment by sbulen** [comment]
PR #5297
