### ISSUE TITLE
warning not showing up on message

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#527]
if a user has a warning issued, text letting moderators know should show up below the send message text. currently this is not showing up.

for my admin user var_dump($message['member']['can_see_warning']); is showing boolean false in display.template.php

that is with Users who can see warning status set to show to moderators

tested with global moderator account same results

changed to show warning status to all users no change in result.

**Comment by illori** [comment]
the warning level also does not show up in the mini-profile in the pm view

**Comment by illori** [comment]
in display.php we have

``` php
$memberContext[$message['id_member']]['can_see_warning'] = !isset($context['disabled_fields']['warning_status']) && $memberContext[$message['id_member']]['warning_status'] && ($context['user']['can_mod'] || (!$user_info['is_guest'] && !empty($modSettings['warning_show']) && ($modSettings['warning_show'] > 1 || $message['id_member'] == $user_info['id'])));
```

if in display.template.php we do a var_dump on $memberContext[$message['id_member']]['warning_status'] it gives us null

if we change that line to 

``` php
$memberContext[$message['id_member']]['can_see_warning'] = !isset($context['disabled_fields']['warning_status'])  && ($context['user']['can_mod'] || (!$user_info['is_guest'] && !empty($modSettings['warning_show']) && ($modSettings['warning_show'] > 1 || $message['id_member'] == $user_info['id'])));
```

we get the warning to show although there are errors showing in the log as a result [and as such it does not really show]

``` php
$txt['warn_' . $message['member']['warning_status']],
```

var_dump($message['member']['warning_status']); is giving us string '' (length=0) so we have an Undefined index: warn_ as a result

we also have 

``` php
$txt['user_warn_' . $message['member']['warning_status']], 
```

 and an Undefined index: user_warn_

i think it may be more helpful to show a warning bar in place of the text, or show the percentage of the warning 

similar to the code posted here http://www.simplemachines.org/community/index.php?topic=507536.msg3575179#msg3575179

**Comment by Oldiesmann** [comment]
This isn't really a bug as much as a feature.

The warning_status is set in loadMemberContext function in Load.php.

`'warning_status' => !empty($modSettings['warning_mute']) && $modSettings['warning_mute'] <= $profile['warning'] ? 'mute' : (!empty($modSettings['warning_moderate']) && $modSettings['warning_moderate'] <= $profile['warning'] ? 'moderate' : (!empty($modSettings['warning_watch']) && $modSettings['warning_watch'] <= $profile['warning'] ? 'watch' : ('')))`

If the warning level is less than the "Warning level for user watch" value set in the admin center, the warning_status is set to an empty string, and therefore there's nothing to display.

Maybe we should add an "Always display warning status" option that simply says "Warned" if their warning level is less than "watch"?

**Comment by illori** [comment]
would it be possible to allow a warning level of lets say 0 be default instead of 0 be disabled?

otherwise your idea would work.. but the same thing does not seem to happen with 2.0 last i checked.

**Comment by Oldiesmann** [comment]
If we go with an option to show something if the warning level is less than the "watch" level, we wouldn't show anything if the warning level was 0, as it makes no sense to show that they've been warned if they haven't been.

**Comment by illori** [comment]
then go with your idea. also what do you think about adding something similar to the percentage bar instead of the text?

or even just listing the percentage next to the text?

**Comment by Arantor** [comment]
So right now, everything seems to work as it is supposed to at least by 'intention' - the thing shows up if it's supposed to (I have a user with no warnings and no strings, and no errors, and a user with a 20% warning which shows up as it should)

So the question is: do we actually need to show warnings below 'watched'? My feeling is no, because if you cared enough for that, you could just change the watched threshold to 1% and job done, they're always 'warned' as it were until that totally goes.

I just don't feel we need to change this but I'm willing to be convinced.

**Comment by illori** [comment]
i think a min warning level for watched should be even 1%... i really dont see a use for the warning system to have watch at 10 for default, if that were changed i think this would be less of an issue overall.

also i would add that the help text next to warning level for user watch should be broken up and applied to each point and not just one massive help text.

**Comment by Arantor** [comment]
That would confuse admins, actually, seeing how you're not 'supposed' to be able to issue warnings in increments of anything smaller than 5%... But I'm just not quite seeing why this is an issue.

The help text, sure, we can look at that.

**Comment by illori** [comment]
so then set watched at 5% instead of 10% ? even though it does tell you what type of warning will be issued with the percentage it is not that obvious that a warning so low will really do nothing.

**Comment by Oldiesmann** [comment]
There are really two ways we can handle this:
1. As Arantor stated above, tell people to decrease the warning level for watched if it matters that much.
2. Add a setting to allow admins to determine whether or not to always show the warning status.

Decreasing the default "watch" level is pointless.

**Comment by illori** [comment]
then how about making the text with the result a bit larger?

**Comment by Arantor** [comment]
I take it you mean the '(icon) Watched' or '(icon) Muted' type text? I dunno, I'm not sure it needs to be any bigger, and I've never been convinced it needs to be shown any more than it currently is.

Note that the warning status can be shown to 'no-one', 'moderators', 'moderators and warned users', 'everyone' (though I forget if that's really everyone or just everyone currently signed in) already, and was an option even in 2.0, so I'm still not sure what actually needs changing from our perspective.

**Comment by illori** [comment]
no i mean on the page you issue the warning, there is text as to the warning type issued.

**Comment by Arantor** [comment]
Anything else that needs doing?

**Comment by illori** [comment]
Pretty sure no. Go close it.
