### ISSUE TITLE
upgrade.php hardcoded error text

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#5273]
#### Description
Error text message are hardcoded and cannot be translated

Example
https://github.com/SimpleMachines/SMF2.1/blob/cc6b057dda6ec6cdadfb610ef385113c6e7e82ba/other/upgrade.php#L636 

### Environment (complete as necessary)
- Version/Git revision: Pull Request 5620
- Database Type: MySQL
- Database Version: 5.6.42-log 
- PHP Version: 7.1.22

It would be advantageous if the texts could be translated.

**Comment by jdarwood007** [comment]
Some strings such as these are not easily possible for us to remove the hard coded text, due to this being so early in the startup process and needing to ensure if it looks like not all parts of the code base are there, to bail out.
