### ISSUE TITLE
Member search does not work properly - date mismatch?

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#5274]
#### Description
When using admin search, searching by registration date may not work correctly. Last active also appears to have the same problem - they don't work for me.

### Steps to reproduce
1. Install RC1 from beta board.
2. Register admin account during registration - the date registered as far as the platform is reporting is today, 25th December.
3. Go to admin > members > search for members
4. Try to search for any members registered on that date, 25/12/2018

![image](https://user-images.githubusercontent.com/1156911/50427281-8e306480-089b-11e9-819d-b98af60766ad.png)

5. No results are found - presumably because it's trying to match on yyyy-mm-dd format but the HTML5 datepicker doesn't automatically submit it in that format...

### Environment (complete as necessary)
- Version/Git revision: RC1 build
- Database Type: MySQL
- Database Version: 10.1.22-MariaDB
- PHP Version: 7.0.18

### Additional information/references

Interestingly, if I edit the date on the user, moving it forward to 26/12/2018 and then back to 25/12/2018, search subsequently works correctly. Something about the initial creation may not work properly - if I either register or create a member from the admin panel today, this doesn't find them.

**Comment by sbulen** [comment]
The other humorous thing here is that the entry prompt (dd/mm/yyyy) is different from the tip just to the right (YYYY-MM-DD)...

**Comment by sbulen** [comment]
The core issue is a timezone mismatch.  All date comparison logic was comparing your entry (your timezone) to DB entries (GMT), which won't work...

**Comment by Arantor** [comment]
I’m in GMT (or was when I filed the issue...)

**Comment by sbulen** [comment]
There was also a basic > vs >= issue.

**Comment by sbulen** [comment]
The timezone issue I found would happen if either your user's time offset (based on your timezone) was non-zero OR the server time offset was non-zero.   If either of those were true, the date logic was off by that many hours.   

My suspicion is that when you modified the date, the time was truncated, thus putting the date back in the middle of the selection criteria.  (I've confirmed that the datetime looks good when adding users.)

I'd appreciate it if you could test, thanx!
