### ISSUE TITLE
Initial values for custom profile fields ordering

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#5278]
#### Description
When first presented with the custom profile fields on a fresh install, the ordering looks like this:

![image](https://user-images.githubusercontent.com/1156911/50427376-5676ec00-089e-11e9-9a05-31494bfacb27.png)

Out of the box, you can switch location and gender around without any problems, but in order to move location before Skype (assuming you ever cared to), you need to hit up twice (once to move it to 3 rather than 4, and then once again to move it to 2)

Doing so also causes there to be a gap before Gender, when the order numbers will be 1, 2, 3, 5.

**Comment by albertlast** [comment]
based on the issue i rewrite this part completly,
only the update stuff is missing.

**Comment by Arantor** [comment]
Or, y’know, fixing the default values on install would have done it too...

**Comment by albertlast** [comment]
Well since custom field are target to be added and deleted by admin over time,
which would create a gap between two fields or more,
the system needs to allow this.

So you easy approache is not well thought out.

**Comment by Arantor** [comment]
Given that deletion as of RC1 also moves all the others down, I'd say the easy approach was already taken care of... (just retested, I had ids 1, 2, 3, 5, deleted id 3 from the admin panel and now I have ids 1, 2 and 4)

**Comment by sbulen** [comment]
Needs "has fix" label - PR ID'd above.

**Comment by MissAllSunday** [comment]
Closed via #5286
