### ISSUE TITLE
Cannot add multiple answers to a question in the Q&A feature

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#5279]
#### Description
I can't add a second answer to a question in the Q&A feature.

### Steps to reproduce
1. Go to the Anti-Spam page
2. Select add new question
3. Type something in for the new question
4. Type something in for the first answer
5. Press 'Add new answer'
6. No new box appears

![image](https://user-images.githubusercontent.com/1156911/50427396-051b2c80-089f-11e9-9008-a368f0192da4.png)

### Environment (complete as necessary)
- Browser: Chrome 71.0.3578.98, Firefox 64.0

### Additional information/references
No errors in the console in either browser.

**Comment by Sesquipedalian** [comment]
I cannot reproduce this. The new answer field appears as expected when I click the "Add Another Answer" link.

**Comment by frandominguezl** [comment]
I could reproduce the issue. Will try again today and give more details if I can.

**Comment by Arantor** [comment]
@Sesquipedalian what browser are you using?

**Comment by SychO9** [comment]
if you already have a QA, the link will work, if you dynamically add a new question the link won't work, that's because the **click** event only applies on the existing elements when the document is loaded.

Gotta use the jQuery **on()** function.
