### ISSUE TITLE
Editing email templates doesn't work properly

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#5280]
#### Description
Even with the improved language string editor, email templates aren't properly editable and may damage editing of other email notifications.

This is the view I see when editing language strings -> Email Templates

![image](https://user-images.githubusercontent.com/1156911/50427443-5ed02680-08a0-11e9-9c6e-e37883ac8ee9.png)

Notice how {%$txtBirthdayEmails['happy_birthday_subject']%} and similar aren't split out as they should be but end up inside the editable area for msg_mention_body.

**Comment by sbulen** [comment]
This needs the "has fix" label added, PR ID'd above
