### ISSUE TITLE
Theme settings link

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#5281]
#### Description
This one's more of an enhancement than a bug.

![image](https://user-images.githubusercontent.com/1156911/50427459-cbe3bc00-08a0-11e9-846f-43fa7234bbbc.png)

There is absolutely no visual cue that the title - "SMF Default Theme - Curve2" is a link to the settings. It would be great if an actual link could be added somewhere to show people where to click. More important for other themes, though.

**Comment by Sesquipedalian** [comment]
Yeah, that's always annoyed me. A simple EDIT button would be nice and obvious.
