### ISSUE TITLE
Flash is disabled on the toolbar with no way to fix

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#5283]
#### Description
The WYSIWYG toolbar has a Flash button on it on a fresh install - but it is greyed out, even though the Flash bbcode is enabled.

![image](https://user-images.githubusercontent.com/1156911/50427553-241bbd80-08a3-11e9-9e6e-4e24ab284902.png)

The original 'enable Flash' option appears to have been removed though the Flash bbcode is still present.

![image](https://user-images.githubusercontent.com/1156911/50427555-2bdb6200-08a3-11e9-8d03-dee5ac9244cc.png)

This feels unfinished - if supporting backwards compatibility is a thing, leave the bbcode in but disable it in the editor so it still works if editing legacy posts, while hiding it in the toolbar for new users.

Flash support is going to disappear in browsers from next summer onwards (even if official EOL is 2020), might as well properly disable it in new installs, and leave just enough in upgrades to work if not nicely.

**Comment by Sesquipedalian** [comment]
#5226 removes the button from the toolbar and renders the flash BBCode as a simple hyperlink (that is, when it is enabled at all).

**Comment by Arantor** [comment]
That seems like it would do it!
