### ISSUE TITLE
Legacy bbcodes - inconsistent handling

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#5284]
#### Description
I get that notionally, old bbcodes should be hidden, e.g. glow, shadow. And the rendered version, fine, it doesn't break, it just doesn't do anything.

However, they're still listed in the admin panel in the bbcode section, which looks like they should be supported. If they're not meant to be really supported, would it be possible to remove them from the admin panel?

There's a similar situation with the color bbcodes - black, blue, green, red, white - these aren't real bbcode in the conventional sense because they're all converted during preparse to be color bbcodes, so it seems like these should be removed and let the preparser (plus any during-upgrade conversion) deal with it.

**Comment by Sesquipedalian** [comment]
Please see #5226 🙂

**Comment by Arantor** [comment]
I think that would cover it. Shame that br is legacy, there’s plenty of uses I’ve had for that for aligning content in bbc tables.
