### ISSUE TITLE
Upgrade: Fatal error: Call to undefined function random_int()

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5291]
Just tried upgrading to latest nightly build, last_commit_416b859
https://github.com/SimpleMachines/SMF2.1/compare/416b859...release-2.1

Now when I run upgrade.php I get this error,

Fatal error: Call to undefined function random_int() in /home/cxxxxx/public_html/cxxxxxxxx.info/tesxxxxx/upgrade.php on line 564

Previous nightly build upgrades have gone fine and without hitch until now.

**Comment by wintstar** [comment]
He who seeks finds:
https://github.com/SimpleMachines/SMF2.1/pull/5252

**Comment by lurkalot** [comment]
Thanks.  Just reporting as I find. 

So I guess you're saying it's been fixed, but that pull request hasn't been merged yet?

**Comment by wintstar** [comment]
No, it did not. But the fix works.

**Comment by lurkalot** [comment]
>           No, it did not. But the fix works.

It does indeed, just tried it.  Thanks.

**Comment by wintstar** [comment]
@Gwenwyfar can closed. Is the same of https://github.com/SimpleMachines/SMF2.1/pull/5252

**Comment by Sesquipedalian** [comment]
Thanks for the report, @lurkalot. We don't mind duplicate reports, but we wouldn't want to miss anything.
