### ISSUE TITLE
Mysql Syntax error

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#5295]
`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INSERT INTO smf_calendar_holidays (title, event_date) VALUES ('New Year''s', '1' at line 6`

That's the message I get when upgrade from previous dev-build.

**Comment by VBGAMER45** [comment]
Looks issue with ' in new years

**Comment by ghost** [comment]
Seems like this one : https://github.com/SimpleMachines/SMF2.1/commit/1f3e76f67fa0db18ffe91a1f671f396287fd209f

**Comment by albertlast** [comment]
In the template of creating issue we ask many things,
it would helpfull when you insert them.

Because i'm not able to reproduce this issue.

**Comment by ghost** [comment]
It could only be those two files, things upgraded fine previously.

**Comment by albertlast** [comment]
let me ask directly:
What is you php and mysql/mariadb version?

**Comment by ghost** [comment]
10.1.30-MariaDB-1~xenial

**Comment by albertlast** [comment]
plase do a  ``select version();``

**Comment by ghost** [comment]
(edited)

**Comment by albertlast** [comment]
Please try this changes: https://github.com/SimpleMachines/SMF2.1/pull/5296

**Comment by ghost** [comment]
Yup, le works.

**Comment by albertlast** [comment]
as typical,
mysql doesn't show the place where the error happen,
it stop random somewhere else.

**Comment by ghost** [comment]
Yes, I guess Issue closed.

**Comment by albertlast** [comment]
No,
please not close,
the issue get closed by the pr when merged.

**Comment by ghost** [comment]
okay
