### ISSUE TITLE
Php 5.4 - Issue with cert detection?

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5304]
#### Description
I am having a problem with cert detection in php 5.4.   I can't tell if this is an environment config issue or a real issue with the code.  This can cause issues with attempting to enable SSL.  

### Steps to reproduce
1.  In a PHP 5.4 environment that has a valid cert, do a fresh install & try to enable SSL
OR...
2. In a PHP 5.4 environment that has a valid cert, in the ACP, Disable SSL then attempt to re-enable it

### Environment (complete as necessary)
- Version/Git revision:  Todays
- Database Type: MySQL
- Database Version:  5.6
- PHP Version:  5.4

### Additional information/references
This always returns false for me in 5.4:
https://github.com/SimpleMachines/SMF2.1/blob/98d5cfd420ee2db29b1fd793751cc06e5ba4eb05/Sources/Subs.php#L6327

**Comment by albertlast** [comment]
I spend some time on this now,
first for me is a big issue to get a php 5.4 env running (we should drop php 5.4 ...)

My test code:
```
<?php

/**
 * Check if the passed url has an SSL certificate.
 *
 * Returns true if a cert was found & false if not.
 *
 * @param string $url to check, in $boardurl format (no trailing slash).
 */
function ssl_cert_found($url)
{
	// First, strip the subfolder from the passed url, if any
    $parsedurl = parse_url($url);
    var_dump($parsedurl);
	$url = 'ssl://' . $parsedurl['host'] . ':443';
	// Next, check the ssl stream context for certificate info
	$result = false;
    $context = stream_context_create(array("ssl" => array("capture_peer_cert" => true, "verify_peer" => true, "allow_self_signed" => true)));
    var_dump($context);
	$stream = stream_socket_client($url, $errno, $errstr, 30, STREAM_CLIENT_CONNECT, $context);
	if ($stream !== false)
	{
        $params = stream_context_get_params($stream);
        var_dump($params);
		$result = isset($params["options"]["ssl"]["peer_certificate"]) ? true : false;
	}
	return $result;
}

echo 'huhu';
$test = ssl_cert_found("https://www.heise.de");
if (!empty($test))
    echo 'good';
else
    echo 'bad';
```
Becaus of the removing of @ in front of ``stream_socket_client``
i got a warning:
```
huhuarray(2) { ["scheme"]=> string(5) "https" ["host"]=> string(12) "www.heise.de" } resource(2) of type (stream-context)
Warning: stream_socket_client(): unable to connect to ssl://www.heise.de:443 (Unable to find the socket transport "ssl" - did you forget to enable it when you configured PHP?) in D:\xampp\htdocs\test1.php on line 20
bad
```

First conclusion:
php 5.4 needs the exentsion openssl enabled in php.ini 

after enabling this i got the next error:

```
huhuarray(2) { ["scheme"]=> string(5) "https" ["host"]=> string(12) "www.heise.de" } resource(2) of type (stream-context)
Warning: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in D:\xampp\htdocs\test1.php on line 20

Warning: stream_socket_client(): Failed to enable crypto in D:\xampp\htdocs\test1.php on line 20

Warning: stream_socket_client(): unable to connect to ssl://www.heise.de:443 (Unknown error) in D:\xampp\htdocs\test1.php on line 20
bad
```

Second conclusion:
It's very likly that sutch old openssl version or env is not able to handle modern encryption (ssl3 is dead)

Possible option beside of drop php 5.4 support would be to skip the check if the php version is to old.
And php 5.5 should be also affected by this issue.

**Comment by Sesquipedalian** [comment]
Since you have that PHP 5.4 instance up and running at the moment, @albertlast, could you test again after changing this line:
```
$context = stream_context_create(array("ssl" => array("capture_peer_cert" => true, "verify_peer" => true, "allow_self_signed" => true)));
```
... to this:
```
$context = stream_context_create(array("ssl" => array("capture_peer_cert" => true)));
```

According to [this page](http://php.net/manual/en/openssl.configuration.php), the "cafile" and "capath" context options that "verify_peer" depends on weren't added until PHP 5.6. Since "allow_self_signed" in turn depends on "verify_peer", if we remove those two options from our code, we might be able to bypass this problem.

Of course, it'll mean that we aren't verifying the certificate at all, but I'd argue that it isn't part of the task of this function to do that anyway.

**Comment by albertlast** [comment]
Well the problem keep,
only when you enable openssl (which is by default  disabled)
then the code works.

**Comment by Sesquipedalian** [comment]
Great. Thanks. I'll add a comment to your PR with a recommendation based on this info.

**Comment by Sesquipedalian** [comment]
Since this affects the installer, I'm tagging it for RC1.
