### ISSUE TITLE
Quoting a post adds it on end of message

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5306]
Quoted posts insert in the wrong place.

Click reply. Type your message,  Now assuming you want to add a quoted post above your text.
Nudge the text down a bit.  and then click above it where you want the quoted post to appear.

Scroll the page down to the post you want to quote, and click quote.  The quoted post seems to get tacked onto the end of your message instead of above it where you clicked.  Pretty sure it shouldn't work like that.

2.1 RC1
https://github.com/SimpleMachines/SMF2.1/compare/98d5cfd...release-2.1

**Comment by MissAllSunday** [comment]
- Which browser? include its version too.
- Normal or WYSIWYG editor?
- Normal quote or "selected" quotes?
