### ISSUE TITLE
Moderation icons

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#5308]
Look at the edit icon, it is not centered. And the quote icon should be in this place, or should also it be centered.

https://i.imgur.com/tbF59wP.png

SMF 2.1 RC1

**Comment by Arantor** [comment]
The icons are the same size, quote just has more space in it...

**Comment by jsqx** [comment]
The edit icon is unevenly is placed.

**Comment by jsqx** [comment]
The edit icon is unevenly embedded.

**Comment by Arantor** [comment]
They’re embedded exactly the same. The quote icon just has more empty space in it.

**Comment by jsqx** [comment]
I think that these icons should in this way be placed. The space at the top and bottom is the same. Now these icons are evenly set.

https://i.imgur.com/gqzq7UC.png

**Comment by Gwenwyfar** [comment]
They are inline, so they default to baseline align in the icon boundary block itself. That makes them go more to the bottom. Center align should fix this. It actually also has it's quirks among browsers and may not be completely centered in some cases, but then that's no longer our problem.

**Comment by jsqx** [comment]
On all top browsers the edit icon is below. In Opera, Chrome, Fiefox.
