### ISSUE TITLE
spam control

### ISSUE THREAD

**Issue by jon80** [SimpleMachines/SMF#5310]
I would like to develop a new **text mining**-based system to control spam, the innovation is that I need to gather data from different community based systems not merely a single system.  The purposes could include anti-fraud and compliance checks [audit] as guided [online](https://idpc.org.mt/en/Pages/Home.aspx).  It will require translation from codex-based languages and natural languages to common languages for the purpose of simplification as well.

I am hoping to seek technical and business support for this huge project, that I will ask the university to sponsor eventually.

**Comment by LexArma** [comment]
Sounds like something you might want to post to the forum for discussion, instead of Github amongst development issues.

**Comment by Gwenwyfar** [comment]
Indeed, please do move this to the forums.
