### ISSUE TITLE
Should 'Likes' received by users be countable?

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#5314]
#### Description
The exsting table and programm logic allow to count the person how liked something,
but the existing system didn't allow to count the amount of receiving likes.

related issue: https://github.com/SimpleMachines/SMF2.1/issues/5161

Problem is that we got also a stats site where print the received likes,
but like i said the numbers are technical wrong atm.

I could image based on ~ two or three addiontal functions with integration hooks in subs.php,
we could fix the problem, but want we to do this?

**Comment by Arantor** [comment]
No, they shouldn’t, at least not in the core. If a mod wants to add that, sure, but not in core. It was by design that this wasn’t facilitated.

**Comment by Gwenwyfar** [comment]
Agreed. And it's not a very useful stat to have even if it were not easily misused.

**Comment by albertlast** [comment]
For me this are all social arguments,
which in my eyes not very good reasons.

Why is count by the core bad and by a mod good?
This is inconsistency for me.

**Comment by Gwenwyfar** [comment]
It's not working properly, we have no good reason to keep it, plus negative aspects to keeping it. Those are, together, a very good reason.

Core means it will always be enabled and people are very unlikely to disable it even if they do not need it/if it is causing havoc. On the other hand, by a mod only those who really need it will get it. That is, if anyone even thinks it's worthy to make a mod of.

If there was no difference to having things as core vs mods, we could as well dump all mods into core...

**Comment by albertlast** [comment]
I mention in the start of the issue,
that no central function exists to count the receiving like.

Based on this you can't buid a mod how add this core function,
so that other like system work correctly.

And likes are by default disabled,
core function -> can be disabled.

**Comment by Gwenwyfar** [comment]
No one is going to disable likes because they don't like the stats. You'd have to manually edit it out.

**Comment by albertlast** [comment]
This issue didn't had the topic if the likes are shown in the stats or not,
i talk about the core function is missing to count the likes.

**Comment by Gwenwyfar** [comment]
And you were also talking about the stats, which is what I'm commenting on...

**Comment by Arantor** [comment]
Mods can totally implement a function to do it even if it will be bad. Some people think it is a good idea but that doesn’t make them right, and a mod gives them the option to do it even if I think it’s wrong.

The proposal you have just means karma should have been left in, as it amounts to the same thing, reputational gaming and clique building.

**Comment by albertlast** [comment]
@Sesquipedalian can i close this?

**Comment by Sesquipedalian** [comment]
Sure.
