### ISSUE TITLE
Error: The email template "notification_edit" could not be found

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#5320]
#### Description
From 
https://www.simplemachines.org/community/index.php?topic=564275.msg4001736#msg4001736

> I've looked into this, and it is a legitimate bug. It was hard to track down, but apparently it was introduced long ago in this commit. If you look there, you'll see on line 2081 that a notification is being created with its "type" set to "edit" even though there is otherwise no such thing as an "edit" notification in SMF.

### Steps to reproduce
> The reason it has taken so long for this bug to manifest is probably that a very specific set of circumstances are required before it will trigger any errors. Specifically, a post containing a mention needs to be modified in a topic that being watched by some other user who has selected the option to be notified by email immediately whenever there is new activity in their watched topics. If that particular scenario occurs, SMF ends up trying to send an email notification using non-existent "notification_edit" email templates.

### Environment (complete as necessary)
- Version/Git revision: 5aa9050
- Database Type: N/A
- Database Version: N/A
- PHP Version: all

### Additional information/references
> Unfortunately, merely changing that "type" value from "edit" to something that actually exists, such as "reply", isn't a good solution. That would avoid generating error messages in the log, but it would cause false "new reply" email notifications to be sent out to users watching the topic when what really happened was that an existing post containing a mention was modified. That would be wrong, and avoiding it is probably the reason why a different notification type was introduced here in the first place. The best solution is to follow through on that idea and implement proper handling of the "edit" notification type.

**Comment by smfbigguy** [comment]
Testing this.

**Comment by smfbigguy** [comment]
I have no errors at all. This worked great for me and taking care of the error. Thanks. :)
