### ISSUE TITLE
Custom smiley will be not converted

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#5322]
#### Description
The upgrader didn't convert the existing custom smiley to the new format.
For the complet story see https://www.simplemachines.org/community/index.php?topic=564355.msg4001786#msg4001786

I'm not sure if this part is a task of the upgrader.

**Comment by Sesquipedalian** [comment]
Yes, this should be handled by the upgrader. Custom smiley sets follow a known and predictable set of rules, so we should be able to process them correctly.

**Comment by sbulen** [comment]
My initial thought is that the update is too restrictive on these lines:
https://github.com/SimpleMachines/SMF2.1/blob/4a751c639634055c63dc8440b4963331577024b1/other/upgrade_2-1_mysql.sql#L2549

Custom smileys won't meet that condition.

I'll experiment to confirm.  Everything else should be good.

**Comment by Sesquipedalian** [comment]
Lovely. Thanks, @sbulen.
