### ISSUE TITLE
Wrong alerts count 

### ISSUE THREAD

**Issue by mastum** [SimpleMachines/SMF#5323]
#### Description
The count does not restart from 1 once the notifications are read but continues...

### Steps to reproduce
1. Mark read alerts
2. The next alert will have the number 2 and not 1
3. Mark read alerts
4. The next alert will have the number 3 and not 1
5. And so on ...

### Environment (complete as necessary)
- Version/Git revision: RC1 / 4a751c639634055c63dc8440b4963331577024b1
- Database Type: All
- Database Version: All
- PHP Version: All
![1](https://user-images.githubusercontent.com/1554203/50729228-a1162500-1136-11e9-9186-83e43c4a80ad.png)
![2](https://user-images.githubusercontent.com/1554203/50729272-61037200-1137-11e9-9acc-f4e6811b78f2.png)

### Additional information/references

**Comment by Sesquipedalian** [comment]
Sounds like the Mark Read link isn't resetting the counter correctly. I'll check that and if necessary add a fix to #5202. I'll probably also move #5202 up to RC1 inclusion if that turns out to be the case.

**Comment by vort7u** [comment]
> I'll probably also move #5202 up to RC1 inclusion if that turns out to be the case.

It would be great, so we can test it well 😃
