### ISSUE TITLE
PHP Info screen HTTP 500 on php 5.4

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5325]
#### Description
The PHP Info screen under Admin | Maintenance | PHP Info serves up a blank screen under PHP 5.4.
Sometimes displays an HTTP 500.  

### Steps to reproduce
1. Pull it up!

### Environment (complete as necessary)
- Version/Git revision:  Today's
- Database Type:  MySQL
- Database Version:  5.7
- PHP Version:  5.4

### Additional information/references

**Comment by Oldiesmann** [comment]
Check your server error log. There should be more info there about the specific error.

**Comment by sbulen** [comment]
I haven't been able to find an error for this thus far...

**Comment by Oldiesmann** [comment]
For an "Internal Server Error" there should be something in the server error log about it. I don't have access to anything with a PHP version that old to test it myself.

**Comment by sbulen** [comment]
Found it...  Felt like a cache delay or something, it didn't show up for a while.   Error is:
`PHP Fatal error:  Out of memory (allocated 4980736) (tried to allocate 149799 bytes) in /blah/blahblah/public_html/VAN21/Sources/ManageServer.php on line 1489`

**Comment by Oldiesmann** [comment]
That's weird... 4980736 is just under 5MB. It shouldn't be running out of memory so soon, especially since PHP's default memory_limit is 128MB.

**Comment by LexArma** [comment]
Perhaps one more place we shouldn't trust people to have sensible limits, and should try to to up the limit first? Though, for that page it seems a little odd if it would really be needed.

**Comment by sbulen** [comment]
My phpinfo says my memory_limit is 256MB.  (When run standalone...)

I've tried a few things, including upping the limit, but oddly, it failed elsewhere on a memory limit before painting the page.   This is a symptom of something else, I think.

One clue...  I suspect that the buffer isn't getting cleared - the ob_end_clean doesn't work without the proper flags set in ob_start...  So that's sitting around when we think it isn't...

Again, this is 5.4 only, on my hosted test site.  Changing it to 5.6 it works fine.

**Comment by albertlast** [comment]
An oom mean that php is not able overall to extend the used ram.
Ther is no help with change some config file entries in php.ini.

**Comment by LexArma** [comment]
I do believe that can't be judged only on the error message, even PHP's own documentation say that hitting memory_limit can end in either "Allowed memory size " or "Out of memory" errors.

**Comment by sbulen** [comment]
Has anybody else tried this in a 5.4 environment?

**Comment by albertlast** [comment]
yes works fine with 5.4.45

**Comment by sbulen** [comment]
On my (hosted) 5.4 environment in question, output_buffering says 'no value' on phpinfo.  On my 5.6 hosted environment that works it also says 'no value'.  On my WAMP environments it is set to 4096.  

I've tried a few variants of 
	`ini_set('output_buffering','0'); `
& 'On' & '4096', etc, but none seem to make a difference in my 5.4 hosted environment.  

However, what *works* on my 5.4 environment is:
	`ob_start(null, 270000);`

Which tells php to use a buffer "chunk_size" of 270K.  Any value above 270000 works.  Smaller values cause the phpinfo() output to actually get painted raw on the screen _- even in my 5.6 environment..._  

The manual for this "chunk_size" field says that:
> If the optional parameter chunk_size is passed, the buffer will be flushed after any output call which causes the buffer's length to equal or exceed chunk_size. The default value 0 means that the output function will only be called when the output buffer is closed.

I think I am seeing that described default behavior in 5.6, but not in 5.4.  In 5.4, I am finding I must specify a big enough chunk_size for it to eat the output of phpinfo in one chunk.

**Comment by albertlast** [comment]
I see here not an issue on smf side.

**Comment by sbulen** [comment]
It may be if we have a lot of linux/5.4 users who see the same symptoms on their hosts.   

It's not a critical function, that's for sure.

**Comment by Sesquipedalian** [comment]
I'm inclined to agree with @albertlast. If this proves to be a frequently reported issue after release, we can reopen it then.
