### ISSUE TITLE
Upload new smiley does not work

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#5328]
#### Description
Adding a new smiley still uses the default of "use existing file" instead of the files you selected to upload.

### Steps to reproduce
1. Add a new smiley through upload
2. The new smiley will be one of the selected existing files.

### Environment (complete as necessary)
- PHP Version: 5.6

**Comment by sbulen** [comment]
Confirmed, as in this:
![image](https://user-images.githubusercontent.com/23568484/50741428-d6ac2400-11b1-11e9-83b6-ba5e5b7cc7e7.png)

Gives you this:
![image](https://user-images.githubusercontent.com/23568484/50741444-fe02f100-11b1-11e9-88d9-1c331735eca7.png)

Which is not the blank.png selected.

**Comment by sbulen** [comment]
I'm looking into this...

**Comment by Gwenwyfar** [comment]
Thanks. I'll test it later.
