### ISSUE TITLE
Cannot upload smileys with different extensions

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#5331]
Even if you have sets with different extensions, you cannot upload files matching that extension.

Error message:
"All smileys must have the same filename."

"Filename" must be a comparison of the full filename. I tried gifs and pngs with the same name excluding the extension.

In addition to this, maybe this should not even be an error at all, because I don't see why we want to block whatever extension you want to use on any set.

**Comment by sbulen** [comment]
Multiple extensions per set are not supported by the current design.  Changing this would require a fundamentally different design, including database changes in this area.  My personal thought is that this would be beyond the scope of 2.1.  

"All smileys" erroneous message confirmed, i.e., this:
![image](https://user-images.githubusercontent.com/23568484/50741326-a0ba7000-11b0-11e9-9b02-cd04991c71e0.png)

Gives you this:
![image](https://user-images.githubusercontent.com/23568484/50741341-ccd5f100-11b0-11e9-9740-760a6b704ecd.png)

Note it also logs an error.  Not sure it needs to do that...

**Comment by sbulen** [comment]
I'm looking into the erroneous message here.

**Comment by Gwenwyfar** [comment]
Then I think this should be changed. What if I want to add an animated gif and the rest of the smileys are anything else? What if I have random images that are not png and want to put them in? We're not only going to force users to convert all their smileys each time they want to add one, but we're locking them to either having one thing or another.

It will also break any smiley sets coming from 2.0 that have any of the above, with no way to fix it without losing something.

I saw the changes being made, but I never thought this is what the extension changes were.

**Comment by sbulen** [comment]
2.0 will be all .gifs.

**Comment by Gwenwyfar** [comment]
Only for the default smileys. I don't think this is a small issue, animated gifs are going to be very common. And if you're using a png set the alternative will be to convert them all to gif. Not to mention the extra work converting and making sure the forum accepts your image.

**Comment by sbulen** [comment]
Fair point on the possibility of a non-gif custom smiley in 2.0.  That would pose an issue, I think.

**Comment by sbulen** [comment]
LONG day at work, sorry for the delay...
Just tested, and yes, in 2.0, various non-.gif formats are allowed.   And bad things happen upon upgrade.  

I have a "hybrid" fix in mind that I'll propose in another issue...

I'll start another issue mainly because this one will get auto-closed when the erroneous message fix goes in...   Also the proposal will need its own discussion & vetting.

**Comment by Gwenwyfar** [comment]
Don't worry about it. Thanks for looking into this :)
