### ISSUE TITLE
admin username change password incorrect problem

### ISSUE THREAD

**Issue by Bocekbasi** [SimpleMachines/SMF#5339]
smf In version 2.1 beta 3, admin changes the user name and exits the site and the password is incorrect.

Şifre yanlış hatası var sürekli olarak doğru şifre girildiği halde.

**Comment by vort7u** [comment]
I can not reproduce the problem with RC1
1. After changing the username I received an email with the new password: login done without problems
2. Also the password reset procedure works correctly after changing the username

Obviously the email address must be valid...

**Comment by snrj** [comment]
testing 
smf 2.1 Rc1 problem
smf 2.1 beta 3 problem
https://screenshotscdn.firefoxusercontent.com/images/30f6249f-eba7-4969-8116-ba4c93b166a5.png

username change 
login problem

**Comment by snrj** [comment]
localhost testing mail problem :D
smf 2.1 Rc1 problem
smf 2.1 beta 3 problem
https://screenshotscdn.firefoxusercontent.com/images/30f6249f-eba7-4969-8116-ba4c93b166a5.png

admin change your own name
Do you need mail

**Comment by vort7u** [comment]
Sorry but if your local WAMP or LAMP server can't send email is not a SMF bug...

**Comment by sbulen** [comment]
I have not been able to reproduce this as well.  

Please confirm this issue is current (RC2 or current github version).

**Comment by MissAllSunday** [comment]
@Bocekbasi are you able to still reproduce this issue using the current build?

**Comment by MissAllSunday** [comment]
I'm going to close this one. Feel free to re-open or create a new one if the issue still happens on the current build
