### ISSUE TITLE
[Discussion/To Do] Clean up ugly/long inline conditionals

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#534]
There's no denying the usefulness of inline conditionals. However, I think we're taking the idea a bit too far in some cases - to the point that it's getting confusing, ugly and difficult to read.

Take for example $context['member']['warning_status'], set by loadMemberContext in Load.php

`'warning_status' => !empty($modSettings['warning_mute']) && $modSettings['warning_mute'] <= $profile['warning'] ? 'mute' : (!empty($modSettings['warning_moderate']) && $modSettings['warning_moderate'] <= $profile['warning'] ? 'moderate' : (!empty($modSettings['warning_watch']) && $modSettings['warning_watch'] <= $profile['warning'] ? 'watch' : (''))),`

I realize it's more convenient to set all the array values in one big block of code, but if it makes things more confusing, I'd rather set them in normal, easier-to-read blocks and/or find better ways to do them.

For warning status, something like this should work...

``` php
$memberContext[$user]['warning_status'] = '';
$warning_levels = array('mute', 'moderate', 'watch');
foreach ($warning_levels as $level)
{
    if (!empty($modSettings['warning_' . $level]) && $modSettings['warning_' . $level] <= $profile['warning'])
    {
        $memberContext[$user]['warning_status'] = $level;
        break;
    }
}
```

Longer and not as convenient as setting it with the other array items, but much easier to read, and also much easier to extend via modifications.

**Comment by ghost** [comment]
The code should be readable and as clean as possible, there is no point having tons of code inline, if someone new comes along and has to spend ages to figure out what the line does.

It's not all about as few lines of code you can write it in as possible it's more about sensible coding practises, reuse of code and clean readable code, it's a balancing act.

**Comment by jdarwood007** [comment]
This is a "as we find them" need really.  That right there is a good example of one to cleanup.  You can drop setting that array though and just put it directory into the foreach.

``` php
$memberContext[$user]['warning_status'] = '';
foreach (array('mute', 'moderate', 'watch') as $level)
{
    if (!empty($modSettings['warning_' . $level]) && $modSettings['warning_' . $level] <= $profile['warning'])
    {
        $memberContext[$user]['warning_status'] = $level;
        break;
    }
}
```

Unless there is a need to call back to that variable, it seems to be a waste to create it.

**Comment by live627** [comment]
@jdarwood007 that is not hookable.

EDIT: Fixed typo.

**Comment by jdarwood007** [comment]
I'm sorry, I don't understand what you mean by bookable?

**Comment by live627** [comment]
Edited to fix typo.

**Comment by jdarwood007** [comment]
Neither was the code in Oldiesmann's example, unless you add them or saying we need to add a hook for more warning levels.

**Comment by Arantor** [comment]
Personally I think the entire warning system needs an overhaul anyway ;)

**Comment by Oldiesmann** [comment]
There are no hooks for the warning system at the moment, so I'm not sure why the code change would matter in that area.

**Comment by jdarwood007** [comment]
Can this be something we look into with SMF 2.2 or 3.0?  Does it need to be cleaned up before the release of 2.1

**Comment by Arantor** [comment]
I'd argue we shouldn't be doing this for 2.1 at this stage. It will be occurring as part of 3.0 for sure. But this one isn't my call, I feel.

**Comment by Oldiesmann** [comment]
I was thinking this was a more "fix them as we find them" thing, rather than a "hunt down all the inline conditionals and change them". At the very least we could re-do this one for 2.1

**Comment by matthew-kerle** [comment]
Very nice. Makes things easier to modify if you have to. A lot more clean. :thumbsup:

**Comment by siddhartha-gupta** [comment]
How about refining this one either in 2.1 or > 2.1.

Load.php, should be in other files too where we are selecting/deciding members avatar images

```
'avatar' => array(
    'name' => $profile['avatar'],
    'image' => $profile['avatar'] == '' ? ($profile['id_attach'] > 0 ? '<img class="avatar" src="' . (empty($profile['attachment_type']) ? $scripturl . '?action=dlattach;attach=' . $profile['id_attach'] . ';type=avatar' : $modSettings['custom_avatar_url'] . '/' . $profile['filename']) . '" alt="" />' : '') : (stristr($profile['avatar'], 'http://') ? '<img class="avatar" src="' . $profile['avatar'] . '"' . $avatar_width . $avatar_height . ' alt="" />' : '<img class="avatar" src="' . $modSettings['avatar_url'] . '/' . htmlspecialchars($profile['avatar']) . '" alt="" />'),
    'href' => $profile['avatar'] == '' ? ($profile['id_attach'] > 0 ? (empty($profile['attachment_type']) ? $scripturl . '?action=dlattach;attach=' . $profile['id_attach'] . ';type=avatar' : $modSettings['custom_avatar_url'] . '/' . $profile['filename']) : '') : (stristr($profile['avatar'], 'http://') ? $profile['avatar'] : $modSettings['avatar_url'] . '/' . $profile['avatar']),
    'url' => $profile['avatar'] == '' ? '' : (stristr($profile['avatar'], 'http://') ? $profile['avatar'] : $modSettings['avatar_url'] . '/' . $profile['avatar'])
),
```

**Comment by Arantor** [comment]
That's a slightly odd case where it's part of a much larger array doing something - you can't exactly fix that inline, only modifying the array after the fact. That's not necessarily a bad thing, mind.

**Comment by equinoxmatt** [comment]
Can this be closed?  As someone else said,  this is purely a nice to have,  not an actual issue.  People should be cleaning up the code in whatever area they touch as they go along.
