### ISSUE TITLE
Adding more than one space adds semicolon ; to end of link.

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5348]
Adding more than one space adds semicolon to end of link, and breaks the link.  

Example,
Lets add a link, https://cctestsite.info/testsite3/ a space and some more text. The link works fine.

Lets add a link, https://cctestsite.info/testsite3/   a double space and some more text. Now you can see it's added ; to the end of the url, and broken the link.

RC1 a few days old, so this might have been fixed. https://github.com/SimpleMachines/SMF2.1/compare/98d5cfd...release-2.1

**Comment by albertlast** [comment]
From my side I didn't understand how to reproduce the Error.

**Comment by lurkalot** [comment]
OK, looks like the GH editor stripped my double space out above.  So for example, say you were going to drop a link in amongst some text.  Type some text, copy a link and paste it straight in. Hit space a couple of times and then some more text. Hit Post.

![2 1-scaeol](https://user-images.githubusercontent.com/6047983/51301439-1e8b4080-1a27-11e9-9643-9ea033258cff.png)

**Comment by albertlast** [comment]
Please test the related pr

**Comment by lurkalot** [comment]
Tested, that fix.  It seems to get rid of that semicolon ; with two spaces, but hit spacebar three times and post and it comes back and breaks link again.

**Comment by albertlast** [comment]
in my test case three spaces didn't produce the error
![grafik](https://user-images.githubusercontent.com/1782906/51343469-cbe96d00-1a96-11e9-8471-b0dcd9ebeb9d.png)

**Comment by lurkalot** [comment]
Tried it again. Seemed to work doing it the same way around as you, but start at top with one space adding another working down seems to bring the semicolons back. 
 
![2 1editsc1](https://user-images.githubusercontent.com/6047983/51347672-a78e9000-1a98-11e9-8837-2b31f2d1da11.png)

![2 1editsc2](https://user-images.githubusercontent.com/6047983/51347673-a78e9000-1a98-11e9-8a67-ca941be8d77d.png)

**Comment by albertlast** [comment]
Nope 
![grafik](https://user-images.githubusercontent.com/1782906/51348126-2cca7280-1aa2-11e9-9cec-2e7c49c73a0a.png)

**Comment by lurkalot** [comment]
Strange.  Try editing the post and changing the spacing, and saving between changes. That's what I did.

Meanwhile, thanks for taking a look, I'll see what happens when I bring my test site up to date with the repo, after these last commits are merged.

**Comment by albertlast** [comment]
i changed the pr,
with this the quick edit works fine

On normal edit,
the spaces get lost on displaying side,
when you got three spaces, it show only two...

**Comment by lurkalot** [comment]
>           i changed the pr,
> with this the quick edit works fine
> On normal edit,
> the spaces get lost on displaying side,
> when you got three spaces, it show only two...

Think I saw that as well, thought it was me, then clicked next to the text and added the extra space, that's when the semicolon's appeared.

**Comment by lurkalot** [comment]
Thanks for sorting this. Looks like it's ok, testing, https://github.com/SimpleMachines/SMF2.1/compare/29024fd...release-2.1

Will play some more and see if it breaks.
