### ISSUE TITLE
Attachments Preview image not showing when Modifying post

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5352]
As the title says, the preview image doesn't show when you modify post attachments.  Just a image placeholder showing.  Attachments show fine in the posts, and preview image is there when you upload, the problem appears to be only when you modify the post.

Running https://github.com/SimpleMachines/SMF2.1/compare/29024fd...release-2.1

Click modify on a post with attachment(s) > Click, Attachments and other options. See Screenshot below,

![modpwatt](https://user-images.githubusercontent.com/6047983/51426282-33f79a80-1be0-11e9-8bc8-184b259b42d1.png)

**Comment by frandominguezl** [comment]
I can't replicate the issue

**Comment by lurkalot** [comment]
>           I can't replicate the issue

That's strange then.  I was posting on someone else's site when I noticed this, so tried it on my own test site and get the same results.

**Comment by TPMick** [comment]
OK, sorry to say it's my fault somewhat.  I didn't realise I still had my IE11 tab open to, it seems the problem only occurs with IE11.  It works ok in Edge, Chrome and Firefox.   

Still think it's a bug though, because in IE11 the preview images and attachment work fine when uploading and viewing the post, just when you modify that the problem arises.

**Comment by lurkalot** [comment]
> OK, sorry to say it's my fault somewhat.  I didn't realise I still had my IE11 tab open to, it seems the problem only occurs with IE11.  It works ok in Edge, Chrome and Firefox. Still think it's a bug though, because in IE11 the preview images and attachment work fine when uploading and viewing the post, just when you modify that the problem arises.

Sorry, yes that was me posting under the wrong account.  (Embarrassed Smiley)

**Comment by vort7u** [comment]
I confirm, it only happens with Internet Explorer 11.
Tried with Chrome, Edge, Firefox, Opera and it works properly.

**Comment by albertlast** [comment]
Is ie11 supported by 2.1?

**Comment by lurkalot** [comment]
Dunno, it seems to work pretty well on it, although you have to install and or upgrade using a different browser. Other than that it works ok.

IE11 will be around until 2025 so I guess it should.

**Comment by albertlast** [comment]
My personal opinion is,
That the ie11 got to many limitation because of his age,
So we shouldn't support actively,
When it works than nice when not is that no issue.

**Comment by lurkalot** [comment]
>           My personal opinion is,
> That the ie11 got to many limitation because of his age,
> So we shouldn't support actively,
> When it works than nice when not is that no issue.

I tend to agree.  Thing is everything seems to work nicely in IE11 except for this issue, and the fact that you can't install or perform a upgrade using IE11 only because the username and password boxes get merged and unusable.  Once installed using a different browser 2.1 seems perfectly usable in IE11.

And the fact that IE11 is part of Windows 10, and supported until that goes end of life in 2025,

**Comment by Sesquipedalian** [comment]
> the fact that you can't install or perform a upgrade using IE11 only because the username and password boxes get merged and unusable.

I was not aware of this. Please open a new issue for this so we can remember to fix it.

**Comment by lurkalot** [comment]
Thanks. Have done as you requested, https://github.com/SimpleMachines/SMF2.1/issues/5353

**Comment by frandominguezl** [comment]
Is this still an issue @lurkalot?

**Comment by MissAllSunday** [comment]
@lurkalot can you please verify if this is still an issue?

Regardless, moved to Final.

**Comment by lurkalot** [comment]
> Is this still an issue @lurkalot?

As far as I'm aware it is still an issue.  I haven't updated my test install for a few weeks so it's a little behind, but still does it.  I will update asap.

**Comment by lurkalot** [comment]
Just to confirm. This issue appears to be still happening for me also after upgrading to RC4

**Comment by DiegoAndresCortes** [comment]
Have you tried it on multiple forums?
I've only tried with a couple of local installations but I still see the previews when editing the post

**Comment by lurkalot** [comment]
> Have you tried it on multiple forums?
> I've only tried with a couple of local installations but I still see the previews when editing the post

Sure it was, though not tried this on a local test bed.  I will later though.  You are checking this in IE11 ?

**Comment by DiegoAndresCortes** [comment]
I just realized it's only IE11 lol
I don't have it to test it. When I try to download and install IE11 on the computer it asks me to restart the computer and then it deletes itself for Edge regardless.

**Comment by Sesquipedalian** [comment]
I don't see any need to code a workaround for a bug in that decrepit dinosaur of a browser that even Microsoft is now actively trying to wipe from the face of the earth.
