### ISSUE TITLE
Can't upgrade or install using IE11

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5353]
When trying to install or upgrade 2.1 using IE11, the username and password boxes are merged together in such a way you can't add the details to them.  This only seems to happen in IE11

Two screenshots below, performing an upgrade, one in IE11, the other in Edge which is for comparison only, it's fine in Edge, Firefox, and Chrome.

![2 1upgradeie11](https://user-images.githubusercontent.com/6047983/51444078-aa80bf00-1cea-11e9-8bea-5f5c00bb6cc8.png)

![2 1upgradeother](https://user-images.githubusercontent.com/6047983/51444080-b4a2bd80-1cea-11e9-8aa5-fd4a9b78368c.png)

**Comment by Sesquipedalian** [comment]
Apparently install.css includes some `-ms-grid` stuff that is making a mess. We should kill it with fire.
