### ISSUE TITLE
Who's Online almost always reports the member activity as "Viewing their own profile"

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#5356]
#### Description
See https://www.simplemachines.org/community/index.php?topic=564454.0.

### Environment (complete as necessary)
- Version/Git revision: 31ffeb3

### Additional information/references
Looking at the log_online table, the problem appears to be that AJAX calls to fetch alerts are being logged. This action should be excluded from logging.

**Comment by smfbigguy** [comment]
I just tried this and it still shows as they are viewing their profile. I will give it a bit and see if it changes. I have cleared all my cache.

**Comment by smfbigguy** [comment]
No, this does not work. Still shows users viewing their profile.

**Comment by smfbigguy** [comment]
I noticed this line in the index.php file:
unset($no_stat_actions);

Just below where this new edit goes.

But nothing for:
$no_stat_areas

So I added this:
unset($no_stat_areas);

I have no idea if that is right but it made sense to me to add it and I have no idea if it works, lol. Just thought I would try it I guess.

**Comment by smfbigguy** [comment]
Well, my above post does nothing, lol. I really didn't expect it to but I thought I would try.

**Comment by live627** [comment]
Try to replace
```
	if (empty($_REQUEST['action']) || !in_array($_REQUEST['action'], $no_stat_actions) || !isset($no_stat_areas[$_REQUEST['action']]) || !isset($_REQUEST['area']) || $no_stat_areas[$_REQUEST['action']] != $_REQUEST['area'])
```

with

```
	if (isset($_REQUEST['action']) && in_array($_REQUEST['action'], $no_stat_actions) || isset($no_stat_areas[$_REQUEST['action']]) && isset($_REQUEST['area']) && $no_stat_areas[$_REQUEST['action']] = $_REQUEST['area'])
````

I haven't tested this because... reasons...

**Comment by smfbigguy** [comment]
Took out my change and put yours in. Now I just gotta wait for members to show up.

**Comment by smfbigguy** [comment]
Type of error: Undefined_vars
    Error message: 8: Undefined index: action
    File: /home/******/public_html/index.php
    Line: 209
    URL of page causing the error: https://www.whatsurbeef.net/index.php?https://www.whatsurbeef.net/

**Comment by smfbigguy** [comment]
Took your change out and mine.

**Comment by Sesquipedalian** [comment]
It would be a lot easier to follow your feedback regarding the changes in my PR if you made the comments in the discussion for the PR rather than the discussion of the bug. 😉
