### ISSUE TITLE
Register for calendar event

### ISSUE THREAD

**Issue by kruimeltje93** [SimpleMachines/SMF#5365]
is it an option to implement registration for events?
Like FB with "interested" and / or "going". So you can easily see who will be present at the event.

Something like this mod: http://custom.simplemachines.org/mods/index.php?mod=3238

Would be a nice feature to consider at a later stage :)

**Comment by Sesquipedalian** [comment]
That is best left to mods like the one you linked to. But thanks for taking the time to file the request! 🙂
