### ISSUE TITLE
Should remove Afrinic.net whois link

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5366]
Used in Sources\Profile-View.php(2186): 'url' => 'https://www.afrinic.net/cgi-bin/whois?searchtext=' . $context['ip'],

The new url is https://www.afrinic.net/whois?searchtext=

**Comment by lesmonds** [comment]
> The new url is https://www.afrinic.net/whois?searchtext=

Doesnt work, if you add this to Profile-View.php 
`'url' => 'hhttps://www.afrinic.net/whois?searchtext=' . $context['ip'],`
Send you to a blank page

**Comment by VBGAMER45** [comment]
you have hhttps in your edit

**Comment by lesmonds** [comment]
I knew that, was testing to see if you noticed ;)

I added an African IP but no results are shows, although not a blank page.
`https://www.afrinic.net/whois?searchtext=41.66.128.0`

**Comment by Oldiesmann** [comment]
It looks like they don't allow direct querying of the database via a URL anymore, or if they do I haven't figured out what the proper URL is.

**Comment by lesmonds** [comment]
I agree I have been try to find the URL, will post here if I do.

**Comment by frandominguezl** [comment]
I wasn't able to find any URL despite my efforts. Any suggestions on this one?

**Comment by jdarwood007** [comment]
Real URL is here: https://www.afrinic.net/whois-web/public/
Looks like it wants a post versus get.  We could convert that hyperlink into a psuedo form and submit it.  Unless they are blocking that as well.

Anyone try contacting them for more information?
