### ISSUE TITLE
Errors in log after install

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5367]
Just installed latest nightly build https://github.com/SimpleMachines/SMF2.1/compare/a31952a...release-2.1

Version Information:
Forum version: SMF 2.1 RC1 (more detailed)
Current SMF version: SMF 2.1 Beta 3
GD version: bundled (2.1.0 compatible) 
MySQLi engine: MariaDB 
MySQLi version: 10.1.37-MariaDB 
PHP: 7.1.26 (more detailed) 
Server version: Apache/2.4.37 (Win32) OpenSSL/1.0.2p PHP/7.1.26

Noticed as soon as it was installed and I logged in there was five errors in the log straight away.  Might just be my local setup, but I'll post them here just in case.

Guest
Type of error: Undefined  							 							
Undefined index: latestRealName 							 							http://localhost/2.1RC1/index.php?http://localhost/2.1RC1/  							 													 C:/xampp/htdocs/2.1RC1/Sources/Subs.php (Line 3537) 

Guest				 						 							 							Type of error: Undefined  							 							
Undefined index: latestMember 							 							http://localhost/2.1RC1/index.php?http://localhost/2.1RC1/  							 													 C:/xampp/htdocs/2.1RC1/Sources/Subs.php (Line 3537)  

Guest				 						 							 							Type of error: Undefined  							 						
 Undefined index: latestMember 							 							http://localhost/2.1RC1/index.php?http://localhost/2.1RC1/  							 													 C:/xampp/htdocs/2.1RC1/Sources/Subs.php (Line 3536)  

Guest					 						 							 							Type of error: Undefined  							 							 Undefined index: latestRealName 							 							http://localhost/2.1RC1/index.php?http://localhost/2.1RC1/  							 													 C:/xampp/htdocs/2.1RC1/Sources/Subs.php (Line 3535) 

Guest
Type of error: Undefined
Undefined index: latestMember 							 							http://localhost/2.1RC1/index.php?http://localhost/2.1RC1/  							 													 C:/xampp/htdocs/2.1RC1/Sources/Subs.php (Line 3534)

**Comment by sbulen** [comment]
Did you have issues creating the admin account during the install?

I cannot duplicate these errors on a successful install in WAMP or LINUX.   

However...   These are the error messages you get if you skip the step of the install where the admin account is created.   That's where latestMember & latestRealName are created & initially populated (with the admin account info).  If you then navigate to the main board, these errors get logged.

**Comment by sbulen** [comment]
So, to duplicate...    
 - Install thru step 4 (where you create the admin account), but do not proceed with creating the admin account
 - On another tab/browser, navigate to the forum (this is where the errors are logged)
 - Complete your install 

That set of errors will be there.   

Not sure if we really want to do something about this?  If anything, we could possibly have the installer create the two fields as empty.

**Comment by lurkalot** [comment]
Thanks. No it installed fine. I was testing in a fresh install of XAMPP which could have glitched  in some way, but didn't notice anything strange.  All seems fine except for this.

I guess if no one else can confirm it can be put down to operator error.  ;)

**Comment by Sesquipedalian** [comment]
Closing for now. Can be reopened if it surfaces again.
