### ISSUE TITLE
Large smileys list overflows the entire textarea

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#5370]
If your smileys list is too big, it will overflow and cover the entire textarea when making a new post.

**Comment by Sesquipedalian** [comment]
We should probably set an upper limit on how many smileys can appear in the main list before forcing the rest into the "More..." dropdown.

**Comment by SychO9** [comment]
this doesn't have a fix

**Comment by live627** [comment]
Soon, though.

(It was quite annoying to track down and fix.)
