### ISSUE TITLE
When editing a board, all html tags are stripped

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#5372]
Unless this is not what I think it is, it is not being respected, similar to the float issue:

https://github.com/SimpleMachines/SMF2.1/blob/4fa7e97e66008a73a81dff5b5c238510f9b241b6/Sources/Load.php#L353-L357

**Comment by MissAllSunday** [comment]
The list of allowed tags in the description is defined further down that same function: https://github.com/SimpleMachines/SMF2.1/blob/4fa7e97e66008a73a81dff5b5c238510f9b241b6/Sources/Load.php#L373

And it depends on some obscure function to reverse html back to bbc or something like that, if that function was removed or edited then the description thing surely got affected.

**Comment by Gwenwyfar** [comment]
Is `description_allowed_tags` not for bbc only? That has a problem as well, tracked in #5271

**Comment by MissAllSunday** [comment]
mmm, can't replicate the issue, if I edit a board, all content of the Description field still appear. What I did found was that valid HTML, IE the tags listed in $context['description_allowed_tags'] doesn't get parsed back to their BBC equivalents.

**Comment by Gwenwyfar** [comment]
Testing again, it might be because I tested in an upgraded forum. In the converted forum the descriptions are using divs, and they still function, but upon editing they disappear. 

On a new install, it is just displayed as-is, and editing it again doesn't remove it, probably gets treated as text. On both cases it is not letting you use any html.

Maybe editing the entry in the database would mimic the upgrade issue.
