### ISSUE TITLE
Installer & Upgrader - formatting

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5375]
#### Description
I think recent changes have messed up alignment in both the installer & upgrader.

### Steps to reproduce
1. Install
2. Upgrade

### Environment (complete as necessary)
- Version/Git revision:  Now
- Database Type:  MySQL
- Database Version:  5.7
- PHP Version:  7.1

### Additional information/references
![image](https://user-images.githubusercontent.com/23568484/51888185-1eeeda00-234b-11e9-975a-e5daa6f1080d.png)
![image](https://user-images.githubusercontent.com/23568484/51888212-3af27b80-234b-11e9-8aea-34c266613a56.png)

![image](https://user-images.githubusercontent.com/23568484/51888286-78ef9f80-234b-11e9-95e9-bfbad8aad19a.png)

**Comment by Sesquipedalian** [comment]
That'll have been caused by #5364. I guess more CSS tweaking is necessary.

**Comment by Gwenwyfar** [comment]
That's exactly the kind of problem using grid was avoiding, which we can't really fix for every different language either, with only float, as it will have an unknown size every time.

It's at least better than it being unusable... thanks again for an unnecessary headache, IE.

**Comment by live627** [comment]
See this grid here. It works everywhere.

https://github.com/SimpleMachines/SMF2.1/pull/3046/files#diff-c5ef6bd5b5f64bcfc3d4647ac7c33792R3374
