### ISSUE TITLE
Errors while upgrading PostgreSQL

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#5377]
#### Description
A couple of minor issues occur when trying to upgrade on PostgreSQL from a recent Git build to the most recent one.

First, you get an error when attempting to upgrade the bans table to support IPv6 because there is no longer an "ip_low1" column. The only easy way to get around this is to either ignore errors from this or check whether an upgrade is needed.

Second, if the index already exists, you also get an error.

### Steps to reproduce
1. Attempt to upgrade a forum running 2.1 on PostgreSQL.

### Environment (complete as necessary)
- Version/Git revision: Latest
- Database Type: Postgres
- Database Version: 10.6 (server) / 11.1 (local test site)
- PHP Version: 7.3

The first one should be relatively simple to fix but I haven't had time to look into it yet. Basically we just need to see if there's an "ip_low1" column in the bans table before we run the query to update that table.

The second issue can be fixed by adding ` IF NOT EXISTS` to the `CREATE INDEX` statement.

**Comment by Sesquipedalian** [comment]
Can I get you to put together a quick PR for this, @albertlast?

**Comment by albertlast** [comment]
your are funny guys...
i create long time ago a process to allow upgrade of beta to beta,
was decline because of beta to beta is not supported

on the other hand this kind of issue which is a beta to beta issue you place as high priority issue....

>The second issue can be fixed by adding IF NOT EXISTS to the CREATE INDEX statement.

pg 9.5+ support this type of commands --> can we not use.

to remind you: https://www.simplemachines.org/community/index.php?topic=548174.0

**Comment by Sesquipedalian** [comment]
Beta to beta isn't supported, no. But this issue will affect anyone who runs the upgrader twice even on supported versions. For example, if someone is already on RC1 and then runs the RC1 version of the upgrader again, these errors will arise. 

This situation is similar to the one with `serialize_to_json()`, where we don't want to run the process twice and so we use `$modSettings['json_done']` to check whether we should do anything. That check isn't there to support beta to beta upgrades, but rather to make sure that running the upgrader a second time won't break things that were previously correct.

**Comment by albertlast** [comment]
and why you don't solve this in a general fashion like i show you in the topic?

**Comment by albertlast** [comment]
@Sesquipedalian add a methode/way where i can skip major steps:
/********
--- do something
/********

in the upgrade process.

And i would fix this issue here.

This "kind" of function i need in upgrade
```
/*******
--- new hot stuff
/******
---#
---{
if (something === 'inet')
$upcontext['skipStep'] = true; <- something like that i need
---}
---#

---# changes which will be not executed when check is true
asdasd
---#

/****
--- next mayor thing
/****
```

**Comment by sbulen** [comment]
Rerunning the upgrader should execute properly to completion, and should do no harm.   Over the years, when forums have gotten screwed up, running the upgrader was often a suggested remedy, to ensure that db changes had at least been executed to get the forum to a known state.  

It's true that beta-to-beta upgrades are imperfect, but we need to look beyond that.    We should be able to rerun the upgrader for support purposes.
