### ISSUE TITLE
Not able to delete some profile fields

### ISSUE THREAD

**Issue by kruimeltje93** [SimpleMachines/SMF#5379]
#### Description
--Description Here--
On my test account I had no problems adding and deleting the skype-field.
A member joined and tried to delete his Skype, but after "change profile" and going back to profile overview you still see the skype-icon. Once back on the forum profile the skype name is back.
Tried several times to delete it, turned the profile field on and off, but it is impossible (by some accounts) to delete the skype-name once filled in.

### Steps to reproduce
1. Add skypename in forum profile and confirm/change profile
2. Delete the name (empty textbox) and confirm/change profile -> view profile overview: skype not deleted. -> back to forum profile: Skype name is not deleted.

### Environment (complete as necessary)
- Version/Git revision: RC1
- Database Type: MariaDB
- Database Version: 10.1.37-MariaDB
- PHP Version: 5.6.39

**Comment by Sesquipedalian** [comment]
Does this affect any other profile fields, or just the Skype one?

**Comment by kruimeltje93** [comment]
not checked yet, will do it tonight if I have the time :)

**Comment by kruimeltje93** [comment]
Alright, I have checked some fields:

Personal text - works fine
Location - not able to delete
skype - not able to delete
custom field for Kik - not able to delete
custom field for gender (explain if filled in 'other') - not able to delete.

Looks like all text fields (except personal text) have the same problem.

**Comment by Sesquipedalian** [comment]
Thanks. That's helpful info. 🙂

**Comment by Sesquipedalian** [comment]
Please navigate to My Community ►  Administration Center ►  Features and Options ►  Profile Fields, scroll down to the Custom Profile Fields section, and click on the Modify link for one of the affected fields. In the Advanced Settings section of the page that loads, what value is selected for the Privacy setting?

**Comment by kruimeltje93** [comment]
Members can see this field, Owner can edit it.

**Comment by Sesquipedalian** [comment]
Thanks for that info.

**Comment by kruimeltje93** [comment]
I changed the profile section (section where user can edit the field) to 'account settings' in place of 'forum profile' and now it works fine.
So I think it is related with the forum profile.

**Comment by Sesquipedalian** [comment]
Note to self: more info on this issue can be found in #5483.
