### ISSUE TITLE
$other_passwords - support other forum password types

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5385]
For final I would suggest looking at some other forum systems for other types of passwords to support. This would make it easier when doing convertors and not cause core SMF files to be modified.

For instance for phpBB 3.1 and 3.2.x
https://www.phpbb.com/community/viewtopic.php?f=556&t=2410311
https://www.phpbb.com/community/viewtopic.php?f=556&t=2410311#p15031216

I would also take a look xenforo seems using bycpt since xenforo 1.2
https://xenforo.com/community/threads/xenforo-1-2-password-encryption.133272/
Another reference https://github.com/vanilla/vanilla/issues/2545

Not these changes apply to Sources/LogInOut.php in function Login2()

**Comment by albertlast** [comment]
Be more specific,
what option/algo/stuff you need.

btw 2.1 use byrcpt.

**Comment by Sesquipedalian** [comment]
That's what this is for:
https://github.com/SimpleMachines/SMF2.1/blob/293d58ccf8da73980a4afe97a1e5a0d9182441a0/Sources/LogInOut.php#L357-L358
