### ISSUE TITLE
Possible SMF 2.1 upgrade json issue with displayFields

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5388]
Link https://www.simplemachines.org/community/index.php?topic=564909.msg4005682#msg4005682

I did notice some html in json maybe that is corrupteing it
<a href="{INPUT}"><img src="https://www.mustangv8.com/fr/Themes/red-clique/images/pony.png" /></a>

**Comment by Sesquipedalian** [comment]
I manually converted the corrupted serialized string back to an array and then serialized it again. The problem appears to be with the accented characters in some of the strings. My guess is that something went wrong involving the conversion to UTF-8 and corrupted the string. I have not had time to discover anything further yet.

**Comment by Sesquipedalian** [comment]
This is just speculation at this point, but an easy fix might be to perform the serialize_to_json step before the UTF-8 conversion step. JSON doesn't care about the byte length of values like serialization does, so the potential byte length changes involved in changing character encodings won't break JSON the way it does with the serialized strings.

**Comment by albertlast** [comment]
When i remember correctly,
than is displayfields only a "collection" of already existing information from other tables:
https://github.com/SimpleMachines/SMF2.1/blob/d497f77e934424d80a906363e10aa23924e4cfe8/Sources/ManageSettings.php#L2142-L2175

So would it be not easier for displayfields instead of convert the serial to json,
to generate the information new by trigger this line somehow from the upgrade?

**Comment by Arantor** [comment]
> This is just speculation at this point, but an easy fix might be to perform the serialize_to_json step before the UTF-8 conversion step. JSON doesn't care about the byte length of values like serialization does, so the potential byte length changes involved in changing character encodings won't break JSON the way it does with the serialized strings.

https://github.com/SimpleMachines/SMF2.1/issues/3396

**Comment by Sesquipedalian** [comment]
Thanks, @Arantor. After reading that, I checked the manual, tested, and discovered that Oldiesmann's concern in that discussion was a moot point. It seems that by default `json_encode()` converts Unicode characters to "\u<character_code>" notation regardless of the character encodings in use at the time. So at this point I don't see any reason not to convert to JSON before converting to UTF-8.
