### ISSUE TITLE
Alerts for mentions & likes

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5392]
https://www.simplemachines.org/community/index.php?topic=564936.msg4005872#msg4005872

Tested mention & likes Alerts myself and couldn't get them to work, latest git version

**Comment by Arantor** [comment]
Cron fails with this warning:

```SMF file version (SMF_VERSION) does not match SMF database version (2.1 RC1).<br>Run the SMF upgrader to fix this.<br><a href="https://wiki.simplemachines.org/smf/Upgrading">More information</a>.```

So notifications cannot be sent and no background tasks will work.

**Comment by Sesquipedalian** [comment]
Yikes. That's no good. 

I suppose RC2 is going to need to be released ASAP, and our RC2 milestone will need to be renamed to RC3.

**Comment by vort7u** [comment]
Unfortunately I noticed that not even the daily emails arrive, this commit should be inserted in the RC1 😕
