### ISSUE TITLE
 doesn't have a default value on upgrade

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5400]
doesn't have a default value seeing this error occur on a few sites. Think it may cause a lot support issues for people who are using upgrading forums that had mods installed.
https://www.simplemachines.org/community/index.php?topic=564951.0

Looks like mainly from old modes that didn't have a default value set and did not allow null.
I think they are popping up now because this added line
mysqli_query($connection, 'SET SESSION sql_mode = \'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION\'');

Not sure what would be the best way to fix this. If scanning all custom columns added on smf tables and making sure they allow null or have a default value set.

**Comment by VBGAMER45** [comment]
To add maybe also fix handling bad birthdates during upgrade process such as Incorrectdate value: '1948-00-00' for column 'birthdate' at row 68

**Comment by albertlast** [comment]
please don't put two issues in one issue.
for the first issue a possible pr exists: #5401

**Comment by VBGAMER45** [comment]
Looks good!
