### ISSUE TITLE
Alerts should show as read when read.

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5412]
For example you have 42 alerts showing at top of screen. Surely clicking on that alert and viewing whatever it alerted you to, it should mark itself as read, instead of still saying you have 42 alerts it should say you have 41 alerts.  

You have to go to all alerts and mark them read manually.  This isn't right is it?

**Comment by Gwenwyfar** [comment]
It's sending the poll notifications twice as well because of that. And perhaps a separate issue, maybe they shouldn't be sent if you are viewing old ones after opening the site.
