### ISSUE TITLE
Wrong error message shown on upgrader

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#5414]
When some paths are incorrect in the settings (seems to be the avatars folder in particular), the upgrader is displaying an error about file permissions instead.

Related to: https://www.simplemachines.org/community/index.php?topic=564981.0

**Comment by frandominguezl** [comment]
I tried to manually change the avatars path in the settings table but instead of getting any errors, my upgrade process just hang. I tried but so far couldn't reproduce.

**Comment by BrickOzp** [comment]
I also tried to do an upgrade with a modified avatars path with the RC4 Beta and did not run into any errors.
After the upgrade the admin->Forum->Avatars Settings complain about "The Avatars directory is not valid"
