### ISSUE TITLE
Permissions error, html bbc

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5417]
#### Description
From #5351 
```
Subquery returns more than 1 row
File: C:\Apache24\htdocs\Upgrader\Sources\ManagePermissions.php
Line: 2369
```

### Steps to reproduce
1. Create two membergroups with independant permissions
2. Give each group permission to admin forum **or** mange groups **or** manage perms
3. Go to manage permissions page

### Environment (complete as necessary)
- Version/Git revision: 2e48b89

**Comment by live627** [comment]
A simple untested blurb:

Replace

```
		WHERE id_group NOT IN (1, COALESCE((
			SELECT DISTINCT id_group
			FROM {db_prefix}permissions
			WHERE permission IN ({array_string:permissions})
				AND add_deny = {int:add}
		), 1))',
```

with

```
		WHERE id_group NOT IN (1, (
			SELECT DISTINCT id_group
			FROM {db_prefix}permissions
			WHERE permission IN ({array_string:permissions})
				AND add_deny = {int:add}
		))',
```

**Comment by albertlast** [comment]
Should work better

```
		SELECT id_group
		FROM {db_prefix}membergroups
		WHERE id_group NOT IN (
			SELECT DISTINCT id_group
			FROM {db_prefix}permissions
			WHERE permission IN ({array_string:permissions})
				AND add_deny = {int:add}
		) AND
		id_group <> 1
```

**Comment by wintstar** [comment]
> 		WHERE id_group NOT IN (1, (
> 			SELECT DISTINCT id_group
> 			FROM {db_prefix}permissions
> 			WHERE permission IN ({array_string:permissions})
> 				AND add_deny = {int:add}
> 		))',

The live627 solution works in my test board. I created a hook with 2 bbcodes. With live627 all 2 bbcodes are displayed, with albertlast only one bbcode for selecting the group permissions.

**Comment by SychO9** [comment]
> The live627 solution works in my test board. I created a hook with 2 bbcodes. With live627 all 2 bbcodes are displayed, with albertlast only one bbcode for selecting the group permissions.

Please open a separate issue as you're clearly talking about something unrelated to this issue at hand.

albertlast's suggested query fixed the issue, however I didn't test if the wanted behavior still works as I don't really have an idea on how to test that.

**Comment by wintstar** [comment]
> Please open a separate issue as you're clearly talking about something unrelated to this issue at hand.
> 
> albertlast's suggested query fixed the issue, however I didn't test if the wanted behavior still works as I don't really have an idea on how to test that.

I have tested this with the function you do not know.  You have to create a hook as described by Sesquipedalian.

> Sesquipedalian
> * To impose permissions restrictions for a given BBC, the BBC tag simply needs to be appended to the $context['restricted_bbc'] array via the integrate_pre_load hook.

**Comment by SychO9** [comment]
hmmmm, I see...

**Comment by wintstar** [comment]
@SychO9 , bbcode youtube is with the hook, html is default.

![bbcode_perm](https://user-images.githubusercontent.com/2753863/52628384-d93c2080-2eb7-11e9-8719-4d6e0a75c46d.jpg)

![bbcode_perm1](https://user-images.githubusercontent.com/2753863/52628401-e0632e80-2eb7-11e9-9a4b-3dca8981e146.jpg)

**Comment by albertlast** [comment]
The base problem is that subquery return more than one line,
becuase of the missing limit (when wanted).

Because of this,
the fix of live didn't fix the root cause.

**Comment by live627** [comment]
> The base problem is that subquery return more than one line

That's actually desired.

**Comment by wintstar** [comment]
> > The base problem is that subquery return more than one line
> 
> That's actually desired.

That's right live627. With alberlast of his solution, only the permission for html is displayed.
