### ISSUE TITLE
Language strings for permissions missing

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#5418]
#### Description
Language strings for permissions missing in for Groups Permission Reports
Only the Language strings are displayed but no text:
- mention
- likes_like

Reports.english.php
`$txt['group_perms_*']`

### Steps to reproduce
1. Create a report for Group Permissions

### Environment (complete as necessary)
- Version/Git revision: RC1
- Database Type: MariaDB 
- Database Version: 10.1.29-MariaDB 
- PHP Version: 7.1.11

**Comment by SychO9** [comment]
there's also **report_user** missing a language string

**Comment by wintstar** [comment]
![report_string_missing](https://user-images.githubusercontent.com/2753863/52625852-359c4180-2eb2-11e9-98c8-462ad648ae0c.jpg)
