### ISSUE TITLE
Incorrect text in error message recaptcha?

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#5419]
#### Description
I'm not sure, but I think the language string is not correct here. 

### Environment (complete as necessary)
- Version/Git revision: * RC1
- Database Type: * MariaDB
- Database Version: * 10.1.29-MariaDB
- PHP Version: * 7.1.11

### Additional information/references

https://github.com/SimpleMachines/SMF2.1/blob/7bd43ba47756955e6bd7d6767d345c4168501dff/Sources/Subs-Editor.php#L2092-L2102

At recaptcha you can not enter any text, letters anymore. Would not another text be better understood?
`$txt['error_wrong_verification_code'] = 'The letters you typed don\'t match the letters that were shown in the picture.';`

**Comment by live627** [comment]
Also reported in #5158
