### ISSUE TITLE
2.0 Attachments update cannot handle fileexts > 8 chars

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5425]
#### Description
2.0 Attachments update cannot handle fileexts > 8 chars.  This will result in a message along the lines of:
```
Executing database changes
Please be patient - this may take some time on large forums. The time elapsed increments from the server to show progress is being made!
Executing upgrade script 1 of 2.
Executing: "Updating attachment data..." (12 of 41 - of this script)
Error!
Data too long for column 'fileext' at row 288

```

### Steps to reproduce
1. File extension longer than 8 chars
2. Update the 2.0 update script

### Additional information/references
From this issue:
https://www.simplemachines.org/community/index.php?topic=565060.0

I'm pretty sure the code in question is here:
https://github.com/SimpleMachines/SMF2.1/blob/42da6b7c819b77852c37c30ba3823cf0cfe8e628/other/upgrade_2-0_mysql.sql#L1214

**Comment by albertlast** [comment]
the problem for me here is,
that i can't imagine how the finished solution look like.

Want we extend the col length?
Want we stop the upgrade when something is found?
Do we something else?

**Comment by sbulen** [comment]
My initial thought is that if it is > 8 chars, leave fileext blank.  
It is certainly not a standard extension.  
And we do not exclude it from the filename.   The full filename, extension included, is in the filename column.  
Subsequent logic tries to set it properly if it is png or jpg, etc.  

8 does seem a little arbitrary...   I have a lot of weird custom extensions used in my forum, lots of custom filetypes.  Fortunately, nothing longer than 8 characters.  E.g., we have "sample.touchosc", where ".touchosc" is a frequently used extension.  

EDIT:  Truncation might provide a little more utility in the long run, e.g., for queries against the raw table.

**Comment by albertlast** [comment]
In this special case the easiest way would be,
To check if fileext is empty,
When not do no update.


________________________________
Von: sbulen <notifications@github.com>
Gesendet: Donnerstag, 14. Februar 2019 06:00
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] 2.0 Attachments update cannot handle fileexts > 8 chars (#5425)


My initial thought is that if it is > 8 chars, leave fileext blank.
It is certainly not a standard extension.
And we do not exclude it from the filename. The full filename, extension included, is in the filename column.
Subsequent logic tries to set it properly if it is png or jpg, etc.

8 does seem a little arbitrary... I have a lot of weird custom extensions used in my forum, lots of custom filetypes. Fortunately, nothing longer than 8 characters. E.g., we have "sample.touchosc", where ".touchosc" is a frequently used extension.

**Comment by sbulen** [comment]
I think this can only happen in a 1.x upgrade.  Can't get more than 8 bytes in the 8 byte field in 2.0.

**Comment by sbulen** [comment]
Poster notes he is upgrading from 2.0.15.

createAttachment() in Subs-Post.php in 2.0.15 will set fileext to '' if the extension length is > 8:
![longextension](https://user-images.githubusercontent.com/23568484/52797608-0d841e00-302b-11e9-84cd-6d008dcac050.JPG)

createAttachment in Subs-Attachments.php in 2.1 does the same thing, sets it to '', so that is the logical thing to do.  
https://github.com/SimpleMachines/SMF2.1/blob/42da6b7c819b77852c37c30ba3823cf0cfe8e628/Sources/Subs-Attachments.php#L696
