### ISSUE TITLE
Issues with conversion to JSON

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5433]
#### Description
We have already had reports of two users whose upgrades have frozen during the Convert to JSON step.  

Not sure what's gong on here yet, but seems to be a pattern.

### Steps to reproduce
1. Can't yet...   It's out there in the wild...   

### Additional information/references
Thread 1:
https://www.simplemachines.org/community/index.php?topic=565072.0

Thread 2:
https://www.simplemachines.org/community/index.php?topic=564909.msg4005686#msg4005686

**Comment by sbulen** [comment]
I don't have the spider tracking on in my site, so to attempt to reproduce, I used some of the data provided in the forum from above:
![image](https://user-images.githubusercontent.com/23568484/52822958-20691380-3068-11e9-9c91-7b719e9482fd.png)

~~During the 2.0.15 => 2.1 upgrade, 2 of 3 rows were not converted to JSON.  My initial suspicion is that there is an issue with our unserialize logic, because online testers properly detect serialized content here:~~


~~The rows not converted cause malformed JSON errors in the app:~~


EDIT:  Red herring....  All rows above convert fine...

**Comment by jdarwood007** [comment]
Are you able to get the data shown there so we can analyze it?

**Comment by sbulen** [comment]
It's all from the thread shown above - here's a link to the specific post:
https://www.simplemachines.org/community/index.php?topic=565072.msg4007008#msg4007008

**Comment by sbulen** [comment]
I have asked that user via PM to see if he can provide the full file somehow...

**Comment by sbulen** [comment]
The user sent me his spider_hits file, 455K entries, and...

It runs just fine through the upgrader for me (WAMP environment).   It executes to completion in only a minute or two.  

Observation 1:  There are, in fact, a great # of url entries in the spider_hits table that do not get translated to JSON.  These all appear to be because the USER_AGENT field is very long, and gets truncated, as this was restricted to varchar(255) bytes in 2.0.    ~85K out of the 455K spider_hits entries are broken.  

These entries are corrupt & irrecoverable, in 2.0 & 2.1.  Viewing them in the UI generates malformed JSON errors, but otherwise do not seem to hurt anything.  

We may need to think of something better to do with these?  Warn users to prune the spider hits log?  Drop them in the upgrader?  Ignore them?  They are currently left in the serialized format in the spider_hits table.

Examples:
```
a:4:{s:5:"topic";i:1455;s:4:"wap2";s:0:"";s:5:"board";i:16;s:10:"USER_AGENT";s:169:"SAMSUNG-SGH-E250/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 UP.Browser/6.2.3.3.c.1.101 (GUI) MMP/2.0 (compatible; Googlebot-Mobile/2.1; +http://www.google.com/bot.html)";
a:4:{s:5:"topic";i:1341;s:4:"wap2";s:0:"";s:5:"board";i:11;s:10:"USER_AGENT";s:194:"Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4 (compatible; Googlebot/2.1; +http://w
a:4:{s:5:"topic";i:4563;s:4:"wap2";s:0:"";s:5:"board";i:11;s:10:"USER_AGENT";s:194:"Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4 (compatible; Googlebot/2.1; +http://w

```

Observation 2:  Upon completion of the JSON update, I was prompted to logon again...   I've seen this once before, thought it was a fluke.  I'll log a separate issue for this.

**Comment by jdarwood007** [comment]
Those are not valid serialized data either.  That is main problem with that.  Unless your text got trimmed as well.

**Comment by sbulen** [comment]
That is what is in the url field for these - they got truncated after 255 chars in 2.0.   

Sample screenshot before JSON conversion:
![image](https://user-images.githubusercontent.com/23568484/52889809-8c19b200-3136-11e9-820c-ebef51cf8153.png)

Sample screenshot after JSON conversion - the truncated ones were left untouched:
![image](https://user-images.githubusercontent.com/23568484/52890073-a011e380-3137-11e9-9de3-9f5b92a99661.png)

**Comment by sbulen** [comment]
If you provide me a location, I can send you the file.   

Note I captured some data in my 2.0.15 environment & it is identical in format to the "before" shot above.

**Comment by live627** [comment]
Now I know why I have garbage in my log. 

![screenshot_2019-02-15 spider log](https://user-images.githubusercontent.com/431799/52890710-7c549a80-3143-11e9-921f-842bd794fd7e.png)

**Comment by jdarwood007** [comment]
Is this only affecting the log_spiders?

We could either dump the extra data, or do a manual conversion with best guess matching.

**Comment by live627** [comment]
I'm looking at the code right now and I have this huge urge to rewrite it. IT'S SO MESSY OMG! Must... resist...

**Comment by sbulen** [comment]
I see 2 aspects of this issue...

1) The truncated 2.0 log_spiders data.  I honestly don't know why someone would want a ton of this data around other than to use it for some deep bot analytics.  But...  it's already broken in 2.0, so that's a bust.  My recommended solution for this is to truncate the table upon upgrade.  

2) I believe the long duration is a problem.  There is no substep progress within each table in the JSON conversion.  So...  I do think this is going longer than it should, and getting timed out by some hosts.  This is my theory for why it appeared to freeze for the user in the original post.  Thus disrupting the upgrade.  

Truncating the table fixes both problems...  

We should also consider jacking up the timeout...  Some steps try to do this, but the JSON step doesn't.  So it's probably operating under a 30-second max, which may explain why folks are freezing during the JSON step.  

There may be other substeps in the JSON conversion that may run long like this...   

So...   My suggestions are to truncate this particular table & to introduce timeout logic during the JSON step.
