### ISSUE TITLE
Can't renable Hook from  Forum Maintenance  -> Integration Hooks

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5444]
#### Description
Can't reenable Hook from  Forum Maintenance  -> Integration Hooks after you disable it. Clicking the icon does not nothing and stays disabled.
Also any reason why we only allow deleting hooks that do not exist and not the ones that are disabled as well.

### Steps to reproduce
1. Install mod that has hooks then try to disable then enable a hook

### Environment (complete as necessary)
- Version/Git revision:
- Database Type: MySQL
- Database Version: 
- PHP Version: 7.1.x

### Additional information/references

**Comment by MissAllSunday** [comment]
That section never really worked like it should, will take a look at it.

**Comment by Pipke** [comment]
also a note, when you want to remove a hook thats not a function anymore, you have to click 2 times the red X to remove it. (first click x, then the page (?action=admin;area=maintain;sa=hooks;do=remove;hook={blabla};) reloads, then you have to click the x agian, then its gone)

**Comment by sbulen** [comment]
This came up in the forum recently:
https://www.simplemachines.org/community/index.php?topic=575496.0

**Comment by SychO9** [comment]
also, hooks that are not permanent should be handled in a special way here.

**Comment by DiegoAndresCortes** [comment]
I think an icon would be fine to show that they are not permanent, the same way it shows an icon if there's an instance created
