### ISSUE TITLE
Language Strings missing in upgrade process

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#5450]
#### Description
Language strings missing in upgrade process, look screenshot.

### Steps to reproduce
1.  upgrade databse

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1 RC1 / Request 5432
- Database Type:  MariaDB 
- Database Version: 10.1.29-MariaDB
- PHP Version:  7.1.11 

![upgrade_language_strings](https://user-images.githubusercontent.com/2753863/53017199-b679b100-344f-11e9-89c6-6b11aae9be28.jpg)

**Comment by frandominguezl** [comment]
Has to do with this https://github.com/SimpleMachines/SMF2.1/commit/1148c2cc2a6a915f64fd30e19e6d3e6e25877f19#diff-cccb32785017365b9e98cf35be9ed3df, apparently

**Comment by wintstar** [comment]
Thanks for Info  :blush:

**Comment by wintstar** [comment]
Yes it has already been fixed already. But currently it is still without language strings.

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade.php#L92-L98

**Comment by frandominguezl** [comment]
I meant it worked before that commit. Those lines were similar to the ones in install.php, so I don't know why were they changed.

**Comment by wintstar** [comment]
This has already been fixed
https://github.com/SimpleMachines/SMF2.1/pull/5294

December 2018 / January 2019, the language strings ($txt) were removed.

Here were the $ txt strings no longer available
https://github.com/SimpleMachines/SMF2.1/commit/6fc48e176aab41fea4f6480cffa3750a75a36458#diff-cccb32785017365b9e98cf35be9ed3df

**Here are the $ txt removed**
https://github.com/SimpleMachines/SMF2.1/commit/326a4a41524a07bc57185edce97a790ce1f5f278#diff-cccb32785017365b9e98cf35be9ed3df

**Comment by Sesquipedalian** [comment]
This happened because @Gwenwyfar force-pushed some changes in #5129 in an attempt to resolve conflicts. The force-push overwrote previously merged changes, causing this problem. Unfortunately, I didn't notice what had happened before merging the PR. I will restore the proper behaviour shortly.

**Comment by Gwenwyfar** [comment]
I guess this confirms what we discussed before about conflicts, then :(

**Comment by Sesquipedalian** [comment]
Yup. No worries, though; it's fixed now.
