### ISSUE TITLE
Smileys are displayed displaced in RSS Feed

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#5452]
#### Description
If you look at an RSS feed with a post where smileys are posted, they are not displayed correctly.

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1 RC1 / Request 5432
- Database Type:  MariaDB 
- Database Version: 10.1.29-MariaDB
- PHP Version:  7.1.11 
- Browser: Firefox 65.0.1 (64-Bit)

![rssfeed_image](https://user-images.githubusercontent.com/2753863/53018929-e0cd6d80-3453-11e9-8555-f640d1d5391e.jpg)

![rssfeed_post](https://user-images.githubusercontent.com/2753863/53018941-e9be3f00-3453-11e9-93c3-ed1a0619845a.jpg)

**Comment by Sesquipedalian** [comment]
Have you tested that in multiple RSS readers? If this happens in every RSS reader, then maybe we are doing something wrong. Otherwise, I’d say this looks like a bug in your RSS reader, not in SMF.

**Comment by wintstar** [comment]
Opera is display correct, Firefox not. Yes it is a bug with the original Firefox feed reader.
