### ISSUE TITLE
$user_info not correctly filled when using SSI.php

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5455]
**$user_info** always shows as **guest** data from in **SSI.php** even when you're logged in the forum. Though it's all good in the forum
I tried to look for the code affecting this, I noticed that **$id_member** equals **0** after this block of code when using it from SSI.php, and equals **1** when using it in the forum.

https://github.com/SimpleMachines/SMF2.1/blob/6698fc4c179a461ccd0d0479ea22407ac918d2ae/Sources/Load.php#L445-L473

**Comment by Sesquipedalian** [comment]
When I go to the "Welcome, Login & Logout" section of ssi_examples.php while logged in, I see this:
![screen shot 2019-02-20 at 12 18 34 am](https://user-images.githubusercontent.com/191731/53073381-1d758500-34a5-11e9-9399-d3f4ddea6020.png)
Based on that, it looks like `$context['user']`, and therefore `$user_info`, are in fact populated with the correct data for my user when loaded via SSI.

So, if you are seeing different behaviour in your tests, I'm going to need more information about how to reproduce it.

**Comment by SychO9** [comment]
take the **ssi_examples** file out of the forum directory, correct the path to **SSI**, now try and access it,
is the user's data still correctly filled ?

**Comment by Oldiesmann** [comment]
It works properly on my test board as well (both using ssi_examples.php and SSI.php?ssi_function=welcome)

**Comment by SychO9** [comment]
Okay so I tried to reproduce this in a new install, here's how I did that:
1. move **ssi_examples.php** out of the forum dir (correct the path to SSI.php)
2. Turn **Enable local storage of cookies** ON
3. access **ssi_examples.php**, you'll see that you're logged in
4. access the forum, you're logged out
5. login, then go back to ssi_examples
6. go back to the forum, you're logged out

it's.. weird

**Comment by illori** [comment]
do you have subdomain independent cookies enabled?

**Comment by SychO9** [comment]
no, and you can't enable it when **local storage of cookies** is enabled

**Comment by Sesquipedalian** [comment]
This sounds to me like expected behaviour. By definition, local cookies only work within a specific directory. So, if ssi_examples.php is moved outside of the forum's main directory, then a local cookie will not be used when accessing ssi_examples.php. If the admin wants SMF cookies to work outside the forum directory, she should turn off local cookies.
