### ISSUE TITLE
file permissions page

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#546]
the file permissions page under the package manager looks like it would be really useful.

what if you accidentally give a file the execute permission? there is no way to remove it but to insert the chmod in the field below the table.

the table does not seem to give anyway to remove the read/write/execute after it is already given.

i tried to use the "predefined permission profile" option, using any of the 3 profiles nothing seemed to change.

i did enter the ftp details so it should be able to do the changes.

the only change that worked was putting the chmod value in the box and clicking the dot to apply the file permission and custom dot in the top table.

this test was done with 2.0, i dont believe this has changed with 2.1 though.

does this mean that if the no change dot is selected that the profiles dont get applied?

**Comment by Oldiesmann** [comment]
On my server, in both 2.0 and 2.1, selecting "Read" next to a file removed the execute flags.

For agreement.txt, if I choose "Execute" it gets changed to 0755. If I then choose "Read", it gets changed back to 0644.

The profiles should be applied regardless of which radio button is selected. On my server, with the attachments directory at 0644, if I choose "Standard - key files writable" from the profiles list, it changes the directory to 0755 instead.

**Comment by illori** [comment]
it just seems to not make sense to me to check another button to remove the option that a separate option applied.

i had it working before... when it asked for ftp

now in a new tab i try to use the default profile options and they do nothing at all

the chmod options at the top of the page work just fine it shows they have changed.
