### ISSUE TITLE
Members receiving Likes when turned off

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5465]
RC1

With all alert settings unchecked, regular members still receive likes form admin, and other members.

**Comment by SychO9** [comment]
I can't reproduce this, @lurkalot are you editing the notification settings from the admin panel or are you editing your own notification settings ?
Also did you test with a more recent version ?

**Comment by lurkalot** [comment]
It might well be sorted now, I'll have to check and see if it's still happening for me..

**Comment by SychO9** [comment]
bump !

@lurkalot can you please check again ?

**Comment by lurkalot** [comment]
Sorry missed this and your previous comment.   I have now unchecked everything in my alert settings over at Bigguy's site which is where it was happening.  Just need to wait now and see what happens.

**Comment by lurkalot** [comment]
As far as I can see it's working as expected now.  So looks like it's fixed.

**Comment by SychO9** [comment]
Okay, Thank you I've never been able to reproduce it either, so feel free to close this.
