### ISSUE TITLE
Attachment: Error on Screenshot upload

### ISSUE THREAD

**Issue by grimes2** [SimpleMachines/SMF#5466]
Upload of a normal screenshot fails security checks. The screenshot was made with the tool Greenshot.
Version: 2.1 RC1

Error:
> Greenshot_2019-02-25_17-21-44.png There was a problem during the uploading of Greenshot_2019-02-25_17-21-44.png.
Your attachment has failed security checks and cannot be uploaded. Please consult the forum administrator. 0.2 MB

![greenshot_2019-02-25_17-21-44](https://user-images.githubusercontent.com/15456836/53427319-070d8300-39e9-11e9-90f2-878d7305ef1a.png)

**Comment by frandominguezl** [comment]
Did you download Greenshot from their official website?

**Comment by grimes2** [comment]
Was not sure, so I reinstalled Greenshot from Github. Uploaded screenshot from that version fails also.

**Comment by albertlast** [comment]
Since ther only some static checks,
which could create false positive (us a av software when you like to do a real check),
can sutch behavior happen.

**Comment by grimes2** [comment]
Screenshot was too large.
The size of a uploaded picture is limited to 500x500
This is too small!
How can I change this limit or is it hardcoded in the security checks?

**Comment by grimes2** [comment]
I suggest a limit of 2000x2000 for the security checks, or does this cause problems.

**Comment by Gwenwyfar** [comment]
> Screenshot was too large.
> The size of a uploaded picture is limited to 500x500
> This is too small!
> How can I change this limit or is it hardcoded in the security checks?

Isn't that from the attachments width/height limit settings?

**Comment by grimes2** [comment]
Do you mean "Max display width of posted or attached images". Yes this is at 500x500, but changing the values (width/height) has no effect on the upload problem.

**Comment by Arantor** [comment]
Turn off the security checks, use the admin search for “security”.

Meanwhile, the size limit will not give you that error, but it might resize your image down if not changed. (Note, display size in posts is different to max attachment size, the latter is the only thing that needs changing here.)

**Comment by MissAllSunday** [comment]
@grimes2 is this still an issue?

**Comment by grimes2** [comment]
Yes, but at the moment the security checks are turned off.

**Comment by MissAllSunday** [comment]
Which 2.1 version are you using? can you try it again using the latest GitHub build?

Just want to make sure the issue still exists so we can track it properly.

**Comment by grimes2** [comment]
2.1 RC2. Can't use latest build.

**Comment by MissAllSunday** [comment]
Thing is, we need to confirm against the current build.

Does anyone else can confirm the issue still exists on the current build?

**Comment by SychO9** [comment]
Upon testing, I got 3 images rejected and 7 accepted. I am not sure if there is a bug here as there is a notice that says "**The extensive security checks can result in a large number of rejected attachments.**"

**Comment by grimes2** [comment]
Did you test pictures larger 500x500 pixel?

**Comment by SychO9** [comment]
> Did you test pictures larger 500x500 pixel?

hmm, it seems large images always fail the security checks

**Comment by sbulen** [comment]
It's a game of statistics...  The security checks look for suspicious string matches.  The bigger the pic, the more likely it is you will find some random pixels that match a suspicious string.  

With "extensive security checks" ON, you will definitely get a lot of hits on large photos.  You should only really use this setting if you're on a very old environment you think may be susceptible to some ancient hacks...

If you are getting a lot of hits with "extensive security checks" OFF, we may need to look more closely at a sample pic.  There are only a couple checks performed, for strings that look like flash sequences & php programs.  

I just tried a few & the edits appear to be working properly.

The strings searched for can be seen in the code here:
https://github.com/SimpleMachines/SMF2.1/blob/d6cb538fb43857e3208ed3688832f5bf274232ba/Sources/Subs-Graphics.php#L211

More background here:
https://github.com/SimpleMachines/SMF2.1/pull/3961

**Comment by sbulen** [comment]
What are your php.ini values for post_max_size and upload_max_filesize?

We have seen php.ini values that are too small cause spurious errors, e.g., here:
https://github.com/SimpleMachines/SMF2.1/issues/5757

**Comment by sbulen** [comment]
With "extensive security checks" OFF, I've been able to load many very large files (4000x6000px, 2-3MB) just fine, no false positives at all:
![image](https://user-images.githubusercontent.com/23568484/63558132-7d0a2700-c500-11e9-909c-807f491ee3ab.png)

**Comment by sbulen** [comment]
A bit of a photographer, I kept trying bigger & bigger files.  I didn't get my first false positive until I attempted an upload of a 50MB 7630x4912 photo in RAW (uncompressed) format:
![image](https://user-images.githubusercontent.com/23568484/63558371-93fd4900-c501-11e9-94c6-14d17d0f0607.png)

**Comment by grimes2** [comment]
> It's a game of statistics..

I doubt that. It passes upload always for images <500x500px and it fails always for images >500x500px. (security checks ON)

Max. Größe pro Dateianhang 2000KB
Max display width of posted or attached images 500px

**Comment by sbulen** [comment]
Please, as noted above, turn the "extensive security checks" OFF.  

If you still have issues:
What are your php.ini values for post_max_size and upload_max_filesize?

If you still have issues:
Maybe you could attach the pic here so I can take a look at it & see why it's failing?

**Comment by SychO9** [comment]
In which case I believe there is nothing to fix here, all is good for me when checks are turned off

**Comment by MissAllSunday** [comment]
I'll go ahead and close this, feel free to re-open in case the issue can be duplicated with the "extensive security checks" off and current build
