### ISSUE TITLE
Split Topic - Select posts to split. | show post in the wrong order

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#5470]
#### Description
I got a test topic which got multi pages and
it start with:
![grafik](https://user-images.githubusercontent.com/1782906/53542875-bf8a1280-3b20-11e9-8a62-d97408e5563b.png)

When i go into selective split i start with this(the view is fine):
![grafik](https://user-images.githubusercontent.com/1782906/53542944-0bd55280-3b21-11e9-936d-5c4a3f81e784.png)

When i move now the the post with 8 (the second post):
![grafik](https://user-images.githubusercontent.com/1782906/53542973-27d8f400-3b21-11e9-8083-dcba64d3a2d9.png)
you notice that the message with 1q move one down and "noch mal" get on the first place,
this "noch mal" is the first post on the next page of the topic.

And so it keep doing,
when i move the next post 9 to the right,
the next post get on the top:
![grafik](https://user-images.githubusercontent.com/1782906/53543085-9fa71e80-3b21-11e9-813b-4e5907f72eba.png)

The problem is not that it is shown,
the order is in my eyes wrong.

### Steps to reproduce
1.  selected post split
2.  move the second post (you could the first one too, but this case is not supported)

**Comment by Gwenwyfar** [comment]
This was also reported here before, along other bugs, we should make sure there aren't other remaining ones as well: https://github.com/SimpleMachines/SMF2.1/issues/2643#issuecomment-305076620
