### ISSUE TITLE
Avatar image alt contains member login

### ISSUE THREAD

**Issue by realdigger** [SimpleMachines/SMF#5475]
Avatar image looks like 
`<img class="avatar" src="https://..." alt="avatar_**login**"> `

Avatar image alt contains member login. Wouldn't it have been better to insert displayed username here?
`<img class="avatar" src="https://..." alt="avatar_**displayed_name**"> `

**Comment by SychO9** [comment]
huh interesting, I never noticed, the alt value contains the user's username which anyone can see even if they don't have permission to.

**Comment by Sesquipedalian** [comment]
Displayed names can contain spaces, etc. This could be charged to the member's ID number instead.

**Comment by Gwenwyfar** [comment]
I thought we had already changed the avatar alt to not show anything. Screenreaders can already see the name of the user, they do not need to see it twice in the form of "avatar of user".

**Comment by Sesquipedalian** [comment]
Can you double check that, @Gwenwyfar? If so, we can close this.

**Comment by realdigger** [comment]
It's not changed
https://github.com/SimpleMachines/SMF2.1/blob/dcbf1a60b14e6bfa697aefa88090c307a37fcd85/Sources/Load.php#L1573

**Comment by Gwenwyfar** [comment]
I guess it was discussed but we forgot to make the changes.

This other one also needs an empty alt, instead of none:

https://github.com/SimpleMachines/SMF2.1/blob/7d6b4d0c5d94c0e1147e711515826dde8f977940/Sources/Load.php#L3639

**Comment by Gwenwyfar** [comment]
> Displayed names can contain spaces, etc. This could be charged to the member's ID number instead.

And just to comment on this: Alts can (and should) have spaces. They are just a description of the image. So if we were to keep it, a proper one would be "Avatar of username" or "username's avatar" instead of "avatar_username"

**Comment by Sesquipedalian** [comment]
Derp. I must have been thinking about class names, not alt text.
