### ISSUE TITLE
New message anchor doesn't show sometimes

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#5477]
From https://www.simplemachines.org/community/index.php?topic=565241.0

This has been aggravating to try and track down. And I'm not so sure that I came up with the right solution.

I've figured out how to reliably reproduce this. A great boon to this is to disable/comment out the query that writes to log_topic in Display.php.

-  User A posts a reply to a topic.
- User B then views that topic . The new anchor is not found (verify in dev console). Refresh the page to see it appear.
Things seem to be cached in the session, to clear that, go view another topic. Populate.php is very handy.

My solution is at https://www.simplemachines.org/community/index.php?topic=565241.msg4009132#msg4009132

Affected code: "seek method" whatever the hell. https://github.com/SimpleMachines/SMF2.1/commit/1178ca3f01b8bd95a3fde25181650a995c59b16e from #4226

**Comment by shnazzle** [comment]
A bit confused about where this defect is but I can verify that there is an issue with posting with the **Show most recent posts at the top in topic view.** option ticked, and also Return to thread by default.
When you reply, it returns to an arbitrary position in the thread. When you turn **Show most recent...** off, it no longer does this.
