### ISSUE TITLE
Disable moderation security

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5481]
RC1
The setting "Disable moderation security" In the tooltip which accompanies this setting it says,

> This disables the additional password check for the moderation page. **This is not recommended!**

Thing is, this appears to be disabled by default. 

Admin > Maintenance > Server Settings > Security >> Disable moderation security

**Comment by live627** [comment]
If ti's dibbled by default, should the help text then say _enable_?

**Comment by frandominguezl** [comment]
Please, add "Has Fix" label over here.

**Comment by MissAllSunday** [comment]
Done.
