### ISSUE TITLE
2.1 RC1 - Can't blank out a custom profile field's value

### ISSUE THREAD

**Issue by MarkRH** [SimpleMachines/SMF#5483]
#### Description
Also have a thread here: https://www.simplemachines.org/community/index.php?topic=565437.msg4009382#msg4009382

### Steps to reproduce
1.  Create a custom profile field
2.  Edit your profile and place a value into that field
3.  Go back into your Forum Profile and you can not blank out the field. You can only change it to another non-blank value.  Only way seems to be to edit the database directly.

### Environment (complete as necessary)
- Version/Git revision: 2.1 RC 1
- Database Type: MySQL (Aria tables)
- Database Version: 10.1.38-MariaDB on webhost, 10.1.35-MariaDB on local PC
- PHP Version: 7.2.15 on webhost and local PC

**Comment by albertlast** [comment]
Create a text field,
setted Show on Registration: yes

filled with asdf, saved -> get showed
removed asdf, saved -> got empty

did i miss something?

**Comment by SychO9** [comment]
The only case where you can't have a blank value is when you set it to **Show on Registration: _Yes, and require entry_** which makes sense and means there's no issue here

unless you don't have it set to that

**Comment by MarkRH** [comment]
Here's how the field is defined in the Admin section:
![image](https://user-images.githubusercontent.com/8035962/53838533-f1eda280-3f5a-11e9-8d56-ea8776eee5b9.png)

If I do check that it is required, when I try to blank it out I get a prompt that it can't be empty.

I have PrettyURLs, SimpleColorizer, and Simple Audio Video Embeder mods installed (latest versions). Hmmm

**Comment by MarkRH** [comment]
Hmmm.. same thing with the ICQ Number filed. I can't blank that one out.  I can blank out the Personal Text field though.  I need to log what it's trying to do somewhere.

**Comment by smfbigguy** [comment]
Can you not just delete it. I deleted the icq field and it is gone now. Excuse me for interrupting if this is not what you are talking about.

**Comment by MarkRH** [comment]
No @smfbigguy I am not talking about deleting a field such that no-one no longer has it.  I simple mean to return the field to a blank or no value.

Anyway, I created a new forum from scratch and in this forum, I can blank out custom field values but I still can't blank out the ICQ value.  Seeing what's different now.

**Comment by kruimeltje93** [comment]
See also: https://github.com/SimpleMachines/SMF2.1/issues/5379

**Comment by MarkRH** [comment]
Yeah looking at that other bug report, if I move the custom field to Account Settings where users can edit it, then I can blank the field out.  Something is broken somewhere with the Forum Profile save procedure.

The ICQ field, I can blank out if I move it to the Look and Layout section but the custom field wouldn't blank out if I moved it there.  Weird stuff.

**Comment by Sesquipedalian** [comment]
I'm going to close this issue as a duplicate, but put a note in #5379 that this one contains more info.
