### ISSUE TITLE
Selecting variant of forum default theme

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5484]
#### Description
If you have a theme which has **variants**, and the theme is set as forum default, users can't change the variant from the default theme's selection box
![vrt](https://user-images.githubusercontent.com/20267363/53879949-05a71080-4010-11e9-833f-059886796716.png)

Possibly related PR #4527

**Comment by Oldiesmann** [comment]
I would think that's intended behavior (although maybe a bit confusing here).

Forum/Board Default = always use whichever theme the admin has selected as the default for the forum or board. This could change, and there's no guarantee that the default theme chosen for a board even has variants (though I realize very few people probably use this feature).

variants = always use this theme regardless of what the forum/board default is (though the admin can still force a board to always use a theme even if the user has chosen a different one).

If we change this we just need to make sure we handle it properly so we don't end up with unexpected results (such as trying to use a variant for a theme that doesn't have any)
