### ISSUE TITLE
Theme selection permission

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5485]
If you have a bunch of themes installed and **Allow members to select their own themes.** = Off
users can still enter the Pick Theme page through the url (same in 2.0)
http://example.com/index.php?action=theme;sa=pick;u={user_id}
But the main issue is they can even switch themes using the following url (clicking on use theme) (unlike 2.0)
http://example.com/index.php?action=theme;sa=pick;u={user_id};th={theme_id};{session}

Or if only one of the themes is disabled for users

**Comment by live627** [comment]
I'm going out on a   limb here to say that #4527 is relevant here too
