### ISSUE TITLE
Breaking topics with posts order option

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5486]
#### Description
When you have a topic with for example 3 pages, leave the page open and edit
**Show most recent posts at the top in topic view** from **Look & Layout**, go to the topic(which you left open) click on a page item
```
Type of error: Critical 
Wrong value type sent to the database. Integer expected. (page_id)
Function: Display
 http://localhost/SMF21/index.php?topic=1.0
 C:/Apache24/htdocs/SMF21/Sources/Display.php (Line 935)
```

### Steps to reproduce
1. Open a topic with at least 3 pages
2. edit **Show most recent posts at the top in topic view** in a new tab
3. go back to the topic tab and change the page
Might wanna try a few times to reproduce this

**Comment by live627** [comment]
I'm now really wondering if that obscure "seek" code is really worth. I think this is the fourth bug it generated so far.

**Comment by live627** [comment]
#4226

**Comment by albertlast** [comment]
Smf got over 2k issue,
is that worth?
