### ISSUE TITLE
Ripe Database

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#549]
RIPE have updated there site and the ip search now no longer works.  Be good for this to be fixed before beta.

**Comment by illori** [comment]
url has changed to https://apps.db.ripe.net/search/query.html?searchtext=IP ADDRESS HERE

**Comment by ghost** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/550

Sorted :)

**Comment by illori** [comment]
the pr was merged, so this can be closed?
