### ISSUE TITLE
Strange behavior of img/float tag parameters in post modify function

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5494]
https://www.simplemachines.org/community/index.php?topic=565710.msg4010294#msg4010294

Seems like any custom bbc parameters are lost during modification, and the float **left** parameter is always changed to **right**

tested on Firefox & Chrome

**Comment by Sesquipedalian** [comment]
I'm not surprised to see SCEditor dropping non-standard parameters added to standard BBC. If the user wants to add extra parameters in parse_bbc(), he also needs to add them to the relevant JavaScript file.

However, the behaviour with the float BBC is unexpected. I'll have to look into that.
