### ISSUE TITLE
ACP - error trying to bring up BBC menu

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5496]
#### Description
Trying to pull up Admin | Configuration | Features and Options | Bulletin Board Code, I get this:
`Fatal error: Can't use function return value in write context in /blah/blah/public_html/VAN21/Sources/ManagePermissions.php on line 631
`
No errors logged, just  a blank screen with the above message.

### Steps to reproduce
1. Just navigate there...

### Environment (complete as necessary)
- Version/Git revision:  As of now...
- Database Type: MySQL
- Database Version: 5.7
- PHP Version:  5.4

### Additional information/references
I've seen this on 5.4, but not on 5.6 or 7.1.

**Comment by sbulen** [comment]
@Sesquipedalian - I believe empty() has some restrictions in 5.4...

**Comment by Sesquipedalian** [comment]
Derp. Fixed now.
