### ISSUE TITLE
Can't install language pack through the admin panel

### ISSUE THREAD

**Issue by Dzonny** [SimpleMachines/SMF#5498]
As reported here:
https://www.simplemachines.org/community/index.php?topic=563258.msg4010388#msg4010388

When you try to install new language through the admin panel, error appear:
"The Simple Machines site is not responding. Please try again later."

**Comment by albertlast** [comment]
Its not so helpfull when you use a url to a private part of sm.org on a public github repo.

**Comment by smfbigguy** [comment]
I get the same as Dzonny. No errors or anything come with it but it just won't install any language. Well, just the warning appears as above.

**Comment by VBGAMER45** [comment]
I am not sure if that can be fixed till final. It checks using SMF version for language packages on the SMF site

$url = 'https://download.simplemachines.org/fetch_language.php?version=' . urlencode(SMF_VERSION);

**Comment by Sesquipedalian** [comment]
Apparently https://download.simplemachines.org/fetch_language.php doesn't currently expect to receive strings like "RC1" in the version parameter.

**Comment by jdarwood007** [comment]
I did some adjustments to the site code.  Seems to have resolved this.  Will do some more verifications later but I think its fixed.

**Comment by gnysek** [comment]
I can confirm it worked on my local installation, which previously was giving this issue.

**Comment by SychO9** [comment]
It's working now

**Comment by smfbigguy** [comment]
Works for me.

**Comment by jdarwood007** [comment]
FYI,
There was some slight adjustments made after this closed to the handling here.  If it broke again, let me know.  I tested with the latest versions and they work fine.  Old versions do not work on on purpose to pull language packs down.
