### ISSUE TITLE
PHP 7.3 Support

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#5504]
#### Description
Currently when enabling PHP 7.3 with SMF 2.1 the database looses connection.

### Steps to reproduce
1. Enable PHP 7.3
2. Try to connect to forum

### Additional information/references
Works OK with PHP 7.2

Using SMF from : https://github.com/SimpleMachines/SMF2.1/commit/c569dfe00decd9662e7ba49d28d088fa3eceb30a

**Comment by Oldiesmann** [comment]
This must be a problem with your setup. My test board runs fine on 7.3. What specific error are you getting?

**Comment by ghost** [comment]
Unable to test this atm as I'm temporarily locked out of my account.

Error I was getting is Unable to connect to database, when visiting the forum URL

**Comment by Oldiesmann** [comment]
This should help diagnose the issue...

Sources/Subs-Db-mysql.php

Find
```php
	// Something's wrong, show an error if its fatal (which we assume it is)
	if ($success === false)
	{
```

Add after that
```php
		die(mysqli_error($db_connnection));
```

That will spit out the actual error message from the database server.

**Comment by ghost** [comment]
Yes, no longer getting crashes.
