### ISSUE TITLE
Subs-Editor.php not defined $smiley_codes

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5505]
In function function html_to_bbc($text) Looks like this code changed since RC1
Looks like wrong variable name

`	// Do the smileys ultra first!
	preg_match_all('~<img\b[^>]+alt="([^"]+)"[^>]+class="smiley"[^>]*>(?:\s)?~i', $text, $matches);
	if (!empty($matches[0]))
	{
		// Get all our actual smiley codes
		$request = $smcFunc['db_query']('', '
			SELECT code
			FROM {db_prefix}smileys
			WHERE code IN ({array_string:smiley_codes})
			ORDER BY LENGTH(code) DESC',
			array(
				'smiley_codes' => $smiley_codes,
			)
		);
		$smiley_codes = $smcFunc['db_fetch_all']($request);`

### Environment (complete as necessary)
- Version/Git revision: smf_2-1-rc2_test1
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by Sesquipedalian** [comment]
Derp. Not sure what I was thinking when I did that.
