### ISSUE TITLE
 build_query_board comment

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5506]
More of a comment.
Subs.php function build_query_board($userid)

`	$query_part = array();
	$groups = array();
	$is_admin = false;
	$mod_cache;
	$ignoreboards;`

The last two variables is that short hand for notation that I am not familiar with to setup the variables?

**Comment by Sesquipedalian** [comment]
I don't think so. That just looks like stray code to me. In fact, it looks like there is a fair bit of useless code in that function...

**Comment by Oldiesmann** [comment]
I could have sworn we actually used $mod_cache['mq'] at some point... I wonder what happened with that.

**Comment by Sesquipedalian** [comment]
It was used in the query prior to #4727.

**Comment by Oldiesmann** [comment]
Ah. Shows how much I pay attention to code changes these days :stuck_out_tongue:
