### ISSUE TITLE
Custom Profile Fields - Duplicate on source

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#551]
Added two custom profile fields today (as you can see below), both are working normal (no duplicated steam icons on profile in display), but when i went to the source i saw steam duplicated several times.

![custom](https://f.cloud.github.com/assets/1669995/891007/43429d54-fa45-11e2-8d1b-e9ca18d2c74a.png)

**Comment by Oldiesmann** [comment]
What code are you using for your profile fields? I've never seen it duplicate the code like that.

**Comment by XinYenFon** [comment]
Field type : Text - Placement : With Icons (Show on topic view: On)

```
<a href="http://steamcommunity.com/id/{INPUT}/" target="_blank"><img src="{DEFAULT_IMAGES_URL}/steam.png" alt="Steam" />
```

``````
<a href="http://raptr.com/{INPUT}" target="_blank"><img src="{DEFAULT_IMAGES_URL}/raptr.png" alt="Raptr" /></a>```
``````

**Comment by Oldiesmann** [comment]
In your code you posted here, you're missing a `</a>` after the img for the Steam field. I'll test this out on one of my boards tomorrow and see if I can reproduce it.

**Comment by XinYenFon** [comment]
I should sleep more thanks sorry :(
