### ISSUE TITLE
manage_boards groups

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5516]
If you have a group with manage_boards permission, they ~~can't access the administration center and manage the boards &~~ can't see all boards(they're supposed to be able to see all boards)

Latest git version

**Comment by SychO9** [comment]
nevermind, something wrong with my setup

**Comment by SychO9** [comment]
yeah no there's definitely something wrong here, if manage_boards groups are supposed to see all boards,
they can't

**Comment by Sesquipedalian** [comment]
Bleh. When I added the `allowedTo('manage_boards')` check to `build_query_board()` in #5472, I failed to notice that `build_query_board()` is executed before the user's permissions array is populated.
