### ISSUE TITLE
Profile Area Track User Subitem

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5517]
#### Description
getting tons of 
```
Type of error: Undefined 
8: Undefined index: label
 http://localhost/Upgrader/index.php?action=profile;u=1
/Themes/default/GenericMenu.template.php (Line 112)
```

### Steps to reproduce
1. Create a membergroup with permission to **Manage and assign membergroups**
2. Must not have permission to **Moderate forum members**
3. Visit a user's profile
![trackuser](https://user-images.githubusercontent.com/20267363/54273822-f03d6380-4586-11e9-8c98-2a6963ed7133.png)

### Additional information/references
Latest Git Revision

**Comment by Sesquipedalian** [comment]
Hm. I can't reproduce this using the information provided.

**Comment by Sesquipedalian** [comment]
Can you please provide the backtrace for the error?

**Comment by SychO9** [comment]
Try with a regular member account that has vanilla permissions, visit a profile.

**Backtrace information**
```
#0: smf_error_handler()
Called from SMF21\Themes\default\GenericMenu.template.php on line 112

#1: template_generic_menu()
Called from SMF21\Themes\default\GenericMenu.template.php on line 35

#2: template_generic_menu_dropdown_above()
Called from SMF21\Sources\Load.php on line 2467

#3: loadSubTemplate()
Called from SMF21\Sources\Subs.php on line 3688

#4: template_header()
Called from SMF21\Sources\Subs.php on line 3274

#5: obExit()
Called from SMF21\index.php on line 154
```

**Comment by SychO9** [comment]
Okay forget what I said,

**Here's how you can really reproduce this**
1. Create a membergroup that is either ***private*** or ***protected***
2. Make a regular member the moderator of said group
3. Connect to that regular member's account
4. Visit anyone's profile

Edit: **There must be no requestable groups available**

it seems the issue is right here, **approve_group_requests** is true but **$modSettings['show_group_membership']** is false
https://github.com/SimpleMachines/SMF2.1/blob/1280283d1e389fd1532f8cfa37d6e532d8777ed3/Sources/Profile.php#L210-L216
