### ISSUE TITLE
Small alerts count glitch(s)

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5518]
#### Description
When you receive an alert without refreshing the page and you mark it read, the count will after a while go back to the amount it was before

### Steps to reproduce
1. Produce an alert
2. don't refresh the page on the alert-receiving end user, just wait for it to dynamically show
3. Mark Read
4. Wait

Also Notice that if you open the alert box before receiving the alert, only the count will go up, the actual alert won't show until you refresh the page.

**Comment by gevv** [comment]
topic subccription alerts e mails not working  (I think some member groups are problematic)

+viewing alerts  page  (only admin)

error record ;

Type of error: Undefined
8: Undefined offset: 128 ........../index.php?action=profile;area=showalerts
/........../Sources/Profile-View.php (Line 392) 

+incorrect listing  

sample  ;

viewing alerts  page  
10 alerts listing  delete all
page refreshes

only 2 alerts visible  
next page   8 alerts visible   
refresh page manually  and next page   10 alerts visible

**Comment by SychO9** [comment]
I think it's better to create a new issue for that, as it's unrelated to the glitch reported
