### ISSUE TITLE
Unneeded hash_passwrd fields in Login.template.php

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5519]
This is from RC1 but I believe still in RC2 I do not see any other references to it.

Themes\default\Login.template.php(80): <input type="hidden" name="hash_passwrd" value="">
Themes\default\Login.template.php(276): <input type="hidden" name="hash_passwrd" value="">
Themes\default\Login.template.php(329): <input type="hidden" name="hash_passwrd" value="">

**Comment by sbulen** [comment]
@live627 - were you going to submit this PR as well?  Just checking!

**Comment by live627** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/5552

**Comment by sbulen** [comment]
Thanks, it's good to have a firm association between issue & PR.

**Comment by live627** [comment]
it's in the commit message
