### ISSUE TITLE
topic subccription alerts and mails not working ++

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#5521]
#### Description smf 2.1 rc1
topic subccription alerts e mails not working 

------------------------------
+viewing alerts page (only admin)

error record ;

Type of error: Undefined
8: Undefined offset: 128 ........../index.php?action=profile;area=showalerts
/........../Sources/Profile-View.php (Line 392)

-----------------------------
+incorrect alert list page

sample ;

viewing alerts page (40 pages old alerts)
10 alerts listing, delete all.
automatic page refresh.

only 2 alerts visible
next page 8 alerts visible
refresh page manually and next page 10 alerts visible

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by gevv** [comment]
"topic subccription alerts e mails not working". Is there a solution?

should I open the topic in the forum? SMF 2.1.x Support

**Comment by SychO9** [comment]
did you install this mod ?
https://custom.simplemachines.org/mods/index.php?mod=4208

**Comment by gevv** [comment]
i didn't know.  thanks @SychO9

**Comment by SychO9** [comment]
sure, so this can be closed then ?

**Comment by gevv** [comment]
alerts and mail working ok.

note: @SychO9 many new error records

Guests
Type of error: Cron
8: Undefined index: id http://.............../cron.php
/............../Sources/Profile-Modify.php (Line 2368)

Members
Type of error: Undefined
8: Undefined offset: 44 http://..................../index.php?action=profile;area=alerts_popup;u=XXXX
/......................../Sources/Profile-View.php (Line 392)

**Comment by SychO9** [comment]
clear your log, those were probably logged before you installed the mod, and if they still show up even after installing the mod, then we'll need more details
