### ISSUE TITLE
spider log incorrect text

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#5524]
#### Description
Note that logging of every spider action only occurs if tracking is set to either "high" or "very high". Detail of every spiders action is only logged if tracking is set to "very high". 

high or very high no longer exist

### Steps to reproduce
1. admin -> forum  -> search engines -> spider log

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references
current levels are
```Sets the logging level.
Standard - Logs minimal spider activity.
Moderate - Provides more accurate statistics.
Aggressive - Same as "Moderate", but logs data about each page visited.```

**Comment by live627** [comment]
More info related to this issue:

```
grep -nHIirF -- Note that logging of every spider (in directory: D:\repos\SMF2.1\)
./Themes/default/languages/Search.english.php:111:$txt['spider_mode_note'] = 'Note that logging of every spider action only occurs if tracking is set to either "moderate" or "aggressive". Detail of every spider\'s action is only logged if tracking is set to "aggressive".';
./Themes/default/languages/Search.english.php:148:$txt['spider_logs_info'] = 'Note that logging of every spider action only occurs if tracking is set to either &quot;high&quot; or &quot;very high&quot;. Detail of every spiders action is only logged if tracking is set to &quot;very high&quot;.';
Search completed with 2 matches.
````

This issue has existed even in 2.0.

**Comment by illori** [comment]
no this does not exist in 2.0, the text was not updated in 2.1 from the 2.0 text.

**Comment by sbulen** [comment]
@live627 - were you going to submit that PR?

**Comment by live627** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/5554
