### ISSUE TITLE
draft  published smiley problem

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#5526]
#### Description smf2.1 rc1
Hello,

draft  published smiley not appear

https://streamable.com/twsnk

http://sendvid.com/08nafdd2

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by Oldiesmann** [comment]
That is a weird issue indeed. What's even stranger is if you go back and edit the post after it's made, the smileys still don't get parsed even though they show up properly in the editor.

**Comment by albertlast** [comment]
What you described @Oldiesmann make sense and is correct behavior.
But that they get converted in this style make no sense.
