### ISSUE TITLE
Undefined function (Subs.php)

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#5530]
#### Description
Getting this in error log :

[20-Mar-2019 17:50:54 Europe/Stockholm] PHP Fatal error:  Uncaught Error: Call to undefined function allowedTo() in /home/lolupdat/public_html/forum/Sources/Subs.php:6581

### Steps to reproduce
1. Latest SMF (RC1)
2. check error_log

### Environment (complete as necessary)
- Version/Git revision: https://github.com/SimpleMachines/SMF2.1/commit/1c530f0b0badea95818990ec2665d2c4bdb3ba4a
- Database Type: mysql
- Database Version:
- PHP Version: 7.1

### Additional information/references

**Comment by albertlast** [comment]
pr https://github.com/SimpleMachines/SMF2.1/pull/5527 should fix this

**Comment by ghost** [comment]
It seems to do, not getting an error_log atm.

**Comment by ghost** [comment]
This brings another issue 

https://github.com/SimpleMachines/SMF2.1/blob/ca4be53bb922b777a0eac6c004c37c353247f823/Sources/Load.php

8: Undefined index: board_manager_groups /Sources/Load.php (Line 955)
8: Undefined index: board_manager_groups /Sources/Load.php (Line 776)
