### ISSUE TITLE
alerts errors

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#5540]
#### Description

sometimes error appears when all alerts are deleted

![IMG-20190326-WA0000](https://user-images.githubusercontent.com/5096676/54990722-12da6e00-4fc4-11e9-8007-3b3505a47d31.jpg)

Type of error: Undefined
8: Undefined offset: 191 /index.php?action=profile;area=alerts_popup;u=15946
/home/....../public_html/Sources/Profile-View.php (Line 392) 

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version: 5.6.32 

### Additional information/references

**Comment by live627** [comment]
@albertlast you know that debug code shouldn't be in production code, right?

**Comment by albertlast** [comment]
and this is no debug code.

**Comment by sbulen** [comment]
Is this still occurring?

I haven't been able to reproduce.

**Comment by SychO9** [comment]
I wasn't able to reproduce either, up until now that is, I'm not exactly sure how but somehow you can end up with topic related alerts that have invalid board ids
