### ISSUE TITLE
board manager

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#5541]
#### Description
Just installed SMF from GH this morning and this is the error I had. It has not happened since install but I figured I would post about it.

https://www.simplemachines.org/community/index.php?topic=566507.0

### Steps to reproduce
1. Install SMF
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version: 7.1

### Additional information/references

**Comment by Sesquipedalian** [comment]
Please test #5542 to see if it fixes the issue, @smfbigguy.

**Comment by smfbigguy** [comment]
No errors at all. Seems fine. :)

**Comment by Sesquipedalian** [comment]
Great.
