### ISSUE TITLE
undefined offset Alerts

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#5549]
There is an error about alerts. If you could take a look at this post on my site:

https://www.smfhelper.com/index.php?topic=217.msg1821#msg1821

### Steps to reproduce
1.  Delete some saved alerts/notifications
2. It may only happen for each member once but am not sure. I had errors when I went to delete mine right after upgrade but not now when I do it. (If that makes sense.)

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by sbulen** [comment]
Is this a dupe of #5540?

Can't tell with no error message or screenshot.

**Comment by SychO9** [comment]
they both say line 392 so I suppose they must be the same

**PS:** line 392 is probably not the line in question anymore

**Comment by sbulen** [comment]
Yep, line # will be different.

We should close this as a dupe.
