### ISSUE TITLE
Guests and security

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#5560]
I am getting a lot of errors from guests. I don't know what they are doing but I have a few screenshots to show you. 
![Screenshot_2019-03-31 Error Log - Page 2](https://user-images.githubusercontent.com/3620111/55288579-9959cb80-5387-11e9-9f99-0bbaa2f82f09.png)
![Screenshot_2019-03-31 Backtrace](https://user-images.githubusercontent.com/3620111/55288580-9c54bc00-5387-11e9-871b-b856940743c5.png)

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by albertlast** [comment]
is this rc2 or github version?

**Comment by smfbigguy** [comment]
RC2 but I got it from GH

**Comment by albertlast** [comment]
you mean the zip version?
Did you run the uprader afterwards?

**Comment by smfbigguy** [comment]
Yes and yes I did.

**Comment by albertlast** [comment]
well you got not the rc2 release version,
you got the github version -> always mention you github version when you use it.
The bug was introduce by me with the pr: https://github.com/SimpleMachines/SMF2.1/pull/5493

**Comment by smfbigguy** [comment]
I will try to remember that next time, thank you. I always get mine from GH.
