### ISSUE TITLE
Disable user statistic

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#5572]
#### Description
In the german sm.org board someone raised the question how this function can be disabled,
reason for this need is gdpr.

specialy the daily post time is critical in ther eyes.

So should we provide some way to disable this function?

**Comment by wintstar** [comment]
No! That's what a modification's supposed to do. The user statistics do not conflict with the gdpr. 

> specialy the daily post time is critical in ther eyes.

In my eyes, it would be better if he put his forum offline.


https://www.simplemachines.org/community/index.php?topic=566792.msg4014455#msg4014455

**Comment by Sesquipedalian** [comment]
Closing for now. I'm not an expert on the legal requirements of the GDPR, though, so if @CoreISP or someone else knowledgable thinks it should be reopened, that'll be fine with me.
