### ISSUE TITLE
Warning about blocked resource in console

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#5573]
#### Description
**Errors in console:**
The resource from "http://***/index.php" was blocked due to MIME type ("text/html") mismatch (X-Content-Type-Options: nosniff).
Loading failed for the <script> with source "http://***/index.php".

### Steps to reproduce
1.  Go into any topic or open add/edit topic area (where SCEditor is using)
2.  Open console

![console](https://user-images.githubusercontent.com/229402/55549388-28037b00-56ef-11e9-9d9c-19d05abe7544.png)
![source](https://user-images.githubusercontent.com/229402/55549391-2c2f9880-56ef-11e9-9d29-5c55e580f454.png)

**Comment by Sesquipedalian** [comment]
I can't reproduce this.

**Comment by dragomano** [comment]
This error appears with other languages, try to change English to any other.

**Comment by dragomano** [comment]
Subs-Editor.php:

> 
		if (!empty($txt['lang_locale']) && $txt['lang_locale'] != 'en_US')
			loadJavaScriptFile($scripturl . '?action=loadeditorlocale', array('external' => true), 'sceditor_language');

I think, these lines can be removed.

**Comment by Oldiesmann** [comment]
It would be interesting to see exactly what's being sent from that URL. It's supposed to output javascript, not HTML.

Removing those lines will prevent the proper language strings from being loaded for the editor when you're not using English.

**Comment by SychO9** [comment]
> Removing those lines will prevent the proper language strings from being loaded for the editor when you're not using English.

It doesn't seem to be the case though, it looks like that javascript code was added inline in the generic controls template, which renders this action useless

**Comment by NTsvetkov** [comment]
Hi,
Same problem here.
I made some debug echoes and I found that http://aquariumbg.com/forum/index.php?action=loadeditorlocale should be loaded as JS, but somehow loader trims request parameters and only index.php is shown in the html code

_// Removing the lines above not removes the included index.php and does not solves the problem. :-(_
**Edit: Seems this solution is working**

![image](https://user-images.githubusercontent.com/9739074/67625000-07dd0a00-f841-11e9-9c34-bb97c390a5dd.png)

![image](https://user-images.githubusercontent.com/9739074/67625045-9baed600-f841-11e9-8ce8-dbae36171dc9.png)

**Comment by NTsvetkov** [comment]
Hi,
Same problem here.
I made some debug echoes and I found that http://aquariumbg.com/forum/index.php?action=loadeditorlocale should be loaded as JS, but somehow loader trims request parameters and only index.php is shown in the html code

// Removing the lines above not removes the included index.php and not solves the problem. :-(
Edit: Seems this solution is working

![image](https://user-images.githubusercontent.com/9739074/67625000-07dd0a00-f841-11e9-9c34-bb97c390a5dd.png)

![image](https://user-images.githubusercontent.com/9739074/67625045-9baed600-f841-11e9-8ce8-dbae36171dc9.png)
