### ISSUE TITLE
Unresponsive tables

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5594]
a reminder to look at a few more unresponsive tables in the admin section
* hooks
* langs
https://www.simplemachines.org/community/index.php?topic=567096.msg4015563;topicseen#new

**Comment by frandominguezl** [comment]
@sbulen Please, "Has Fix" label on this one O:)

**Comment by sbulen** [comment]
Is this still outstanding?  "Has fix" labels came & went...  Subsequent PRs affecting this have come & gone as well...

**Comment by DiegoAndresCortes** [comment]
I could only find the hooks table as a legitimate issue and since you don't want to play around too much with that info on a phone I decided to hide some elements.
But other than that I couldn't find any other essential sections that are not responsive.
E.g. The languages page is fine for me.

**Comment by BrickOzp** [comment]
This could be closed now
