### ISSUE TITLE
"Native Name of Language" is always English

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#5597]
#### Description
When you download a language pack by the download manager of smf,
the "Native Name of Language:" is always English.

**Comment by Sesquipedalian** [comment]
That's not what I see. Which language pack were you using?

<img width="601" alt="Screen Shot 2019-04-13 at 7 14 45 PM" src="https://user-images.githubusercontent.com/191731/56087046-6fd97f00-5e20-11e9-9bc4-6116c7ee0d7e.png">
