### ISSUE TITLE
Can't install from current HEAD using postgres

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#5608]
#### Description
This is probably a followup to #5584. Using the current git checkout, I can't connect to my (Postgres) DB at all during install. (Haven't tested MySQL because I don't have it installed.)

### Steps to reproduce
1.  Try to install using postgresql: port 5432, valid credentials with a trivial password like
```
$db_passwd = 'VejmZ8zs';
```
2. Installer fails with
```
Critical Error!
Cannot connect to the database server with the supplied data.

If you are not sure about what to type in, please contact your host.
```

The DB is running (other services are using it), so I don't think there's an issue there. I've tried several passwords, with and without special characters, including those that caused the problems in #5584.

I don't understand enough PHP to debug this further.

### Environment (complete as necessary)
- Version/Git revision: c84bf54d547e3e2bc008bacac00048c8370725a5
- Database Type: Postgres
- Database Version: 9.4.21
- PHP Version: 5.6.40

**Comment by albertlast** [comment]
can you check the port in you settings.php?

**Comment by m4z** [comment]
Good catch! Whether or not I input a port, the config contains the default MySQL port:
```
$db_port = 3306;
```

**Comment by m4z** [comment]
When manually editing the port in the `Settings.php` file before submitting the DB form, installation is possible (using a password _without_ `'` and `\`; I can test with those tomorrow or so).

**Comment by m4z** [comment]
Sorry for the noise, I forgot to mention this: the progess bar on the top of the page is now broken, too; it always displays step 1.

**Comment by albertlast** [comment]
i did already a check for ``'`` and ``\``,
the result you see in this comment:  https://github.com/SimpleMachines/SMF2.1/pull/5585#issuecomment-485227019
