### ISSUE TITLE
Feature Request: Logout button in the mini profile drop down menu

### ISSUE THREAD

**Issue by MechDR** [SimpleMachines/SMF#5616]
This is probably a bit too late at this point, but, could it be possible to also add a Logout button in the mini profiled drop down menu?

![SHOT7036](https://user-images.githubusercontent.com/45944962/56697367-a8b20780-66ee-11e9-9525-e3d1d28da58c.png)

Just seems kind of logical, at least to me. I've seen it in some forum platforms (can't remember which though) and I think it's pretty handy to also have a Logout button there as well :).

**Comment by SychO9** [comment]
take a look at
https://github.com/SimpleMachines/SMF2.1/issues/4876

**Comment by MechDR** [comment]
Thanks ;).

**Comment by gevv** [comment]
+my drafts

**Comment by MechDR** [comment]
Should I close this, or... ???

**Comment by SychO9** [comment]
yup, since there's already an issue about it.
