### ISSUE TITLE
Fatal error: Can't use function return value in write context

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5618]
#### Description
Error "Fatal error: Can't use function return value in write context in /blah/blah/public_html/van21/Sources/Subs-Post.php on line 458"

### Steps to reproduce
1. Pure vanilla install
2. Register new member from the Admin menu
3. I made this new member a moderator; did not require email activation

### Environment (complete as necessary)
- Version/Git revision:  Today's
- Database Type: Mysql
- Database Version: 5.7
- PHP Version: 5.4
- Linux

### Additional information/references
 - Works fine if I change to php 5.6
 - 5.4 errors are annoying

**Comment by sbulen** [comment]
Note:  This also occurs if just simply hitting the Reply button...

**Comment by MissAllSunday** [comment]
Yeah, that can only be done in PHP 5.5 or greater.
