### ISSUE TITLE
Possible typo (and more) in english $helptxt['dont_show_attach_under_post']

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#5621]
#### Description
[(Original thread here.)](https://www.simplemachines.org/community/index.php?topic=567411.0)

##### 1/3
Wrong(?):
> $helptxt['dont_show_attach_under_post'] = 'If enabled, the attachments embedded ~~on~~ the post won\'t appear under the post but are still subject to be deleted.';

Suggested fix:
> $helptxt['dont_show_attach_under_post'] = 'If enabled, the attachments embedded _**in**_ the post won\'t appear under the post but are still subject to be deleted.';

###### 2/3
I'm not sure about the meaning of everything after the "but"; I guess the point is that all other "normal"-attachment-related settings still apply to them?  (Because that's what `Admin.english.php:$txt['dont_show_attach_under_post_sub']` says.)
Also, why even have the help text when it is basically a shortened repetiton of `Admin.english.php:$txt['dont_show_attach_under_post_sub']`? Shouldn't the extra help text be _more_ verbose by default?

##### 3/3
[Irisado pointed out](https://www.simplemachines.org/community/index.php?topic=567411.msg4017470#msg4017470) that there needs to be a comma before the "but" (my grammar skills aren't enough the comment on that; in German the comma is optional).

### Steps to reproduce
1. Read Help.english-utf8.php

### Environment (complete as necessary)
- Version/Git revision: Revision: #95312(?); are the language files in a Git repo somewhere?

**Comment by m4z** [comment]
> ### Environment (complete as necessary)
> * Version/Git revision: Revision: #95312(?); are the language files in a Git repo somewhere?

[I'm officially an idiot (the english files live in this very repo).](https://github.com/SimpleMachines/SMF2.1/tree/release-2.1/Themes/default/languages)

**Comment by m4z** [comment]
I'm willing to write up a PR for this, I'm just not sure how to move forward.

**Comment by jdarwood007** [comment]
I wrote a quick tutorial for SimpleDesk, but the same logic applies for SMF: https://www.simpledesk.net/community/index.php?topic=2184.0

**Comment by m4z** [comment]
Thanks for that pointer, the guide looks really useful.
However, I realize now my own phrasing wasn't optimal: My point wasn't about how to _technically_ submit a PR in general, I know my way around CLI Git just fine. I was trying to say that I need input regarding my issues above first, because I don't know how to fix the issue, how to create the "content" of my PR.

So, are 1 and 3 valid issues and are the proposed fixes OK; are my assumptions in 2 generally correct?

**Comment by m4z** [comment]
I will roll items 1 and 3 into a new PR sometime next week.
For item 2, can somebody please comment, or suggest a fix, or at least a route to move this forward?

**Comment by m4z** [comment]
* #5778 only has a fix for point 1 above.
* Point 2 still stands (although I now understand the part about deletion being about the Admin attachment cleanup tasks; I believe the help text could explain that though, which would also address my length difference concerns above).
* Point 3, if valid, still stands.

**Comment by frandominguezl** [comment]
I believe that it's pretty clear now. The next commit will fix point 3, but I believe all sub texts and helptexts are pretty clear for that setting already.

**Comment by m4z** [comment]
Yeah, I will hold on to point 2 for another day and just re-check the situation in rc3. Thanks!
