### ISSUE TITLE
$helptxt['themes']: Unclear reference

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#5622]
#### Description
>$helptxt['themes'] = 'Here you can select whether the default theme can be chosen, what theme guests will use,
>	as well as other settings. Click on a theme to the right to change the settings for it.';

This is the help text of the Admin section "top header"; there are 4 menu items below, each of which could be selected when reading this help text, and in none of them do I find something about changing theme settings to the right side of the page. Or is it (clumsily) referring to the right-most menu item, "Modify Themes"?

### Steps to reproduce
1. Read Help.english-utf8.php

### Environment (complete as necessary)
- Version/Git revision: Revision: #95312

**Comment by frandominguezl** [comment]
I don't see what's the issue with this.

**Comment by m4z** [comment]
Thanks for addressing this, I've been a bit swamped lately.

As I attempted to explain in my OP (which apparently I didn't do well), the help text references something that I can't find; I assume it's a leftover from the 2.0.x admin menu structure but don't have a 2.0 install to verify this (and don't care enough about 2.0 to install one).

The help text appears in the Admin menu section > Configuration > Themes and Layout, when you
- (under "Manage and Install") click on the question mark to the top left of either one of the _two_ top boxes labelled "Themes and Layout settings", or
- (under "Theme Settings", "Member Options", or "Modify Themes") click on the question mark to the top left of the single box labelled "Themes and Layout settings".

In none of these four cases is there something "to the right" that changes something about theme settings, as the text incorrectly claims:
- "Manage and Install": to the right are Save and Upload buttons, plus "choose..." text links to change the default forum theme and to reset all users (this _might_ be what's referenced, but I'm not sure; I'm not clicking on a "theme" to the right, and to me, this isn't strictly changing the "settings for a theme")
- "Theme Settings": to the right are only buttons to disable and remove themes, and to reset base URLs/directories (again, no theme to the right to click on)
- "Member Options": nothing to click on to the right at all; maybe one or both of the left-aligned text links for each theme ("Configure guest and new user options for this theme" and/or "Change current options for all members using this theme") are referenced; this is (or these are) the most plausible to be referenced by the text, but again, it's (they're) not to the right.
- "Modify Themes": even less text to the right.

If this is still unclear, I could provide screenshots of the default theme. 😛

(#5778 doesn't change `$helptxt['themes']`, so why does it claim to fix this issue?)

**Comment by frandominguezl** [comment]
Alright I understood you know. This behavior is the same as in 2.0.x and I don't think it's worth keeping. If we are going to keep it, then we should move this helptext to Manage and Install > Settings because that's what the text is meant to point out.
I will open another discussion for it as it's kinda related to frontend rather than language.

Thanks for pointing out!

**Comment by m4z** [comment]
Thank _you_ for working on it. Feel free to reference your issue and close this one then!

**Comment by m4z** [comment]
Closing in favor of your wonderful #5785.
