### ISSUE TITLE
Phrasing of $helptxt['securityDisable_why'] and $helptxt['securityDisable_moderate_why']

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#5623]
#### Description
> `$helptxt['securityDisable_why'] = 'This is your current password. (the same one you use to login.)<br><br>[...]`
> `$helptxt['securityDisable_moderate_why'] = 'This is your current password. (the same one you use to login).<br><br>[...]`

No, this is an empty password box, I haven't input anything yet. The text should probably read something like "(Please) (Re-)Enter your current password here. (***T***he same[...])".

### Steps to reproduce
1. Read [Help.english-utf8.php](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/languages/Help.english.php#L360-L362)

### Environment (complete as necessary)
- Version/Git revision: Revision: #95312/HEAD

**Comment by frandominguezl** [comment]
This is closed, but still referred in #5661 
I see no issue with this. The helptext is not meant to tell what's inside the box, but what you should fill the box with, in this case, your current password. I don't see the need of changing this.

**Comment by m4z** [comment]
Yes, I closed this issue. IIRC, I interpreted [this message by Sesquipedalian](https://github.com/SimpleMachines/SMF2.1/issues/5634#issuecomment-490558277) to mean "create The One Collection Issue™️ [and close the referenced issues since they're then tracked centrally]".

And you're describing the exact issue in your own words: the help text isn't helping, it's imprecisely and incorrectly describing something that isn't there (unless your password is the empty string), when instead it should read something like "Insert your current password here" or "If you're wondering what to input here, enter your current password because we need it to verify it's actually you deliberately changing this important setting" (and use correct capitalization at the beginning of the next sentence). This kind of help text is totally different from the others. Yes, most admins will probably understand what's happening _despite_ this text, but I'm nitpicky like that. This text stands out both in style and quality (and not in a good way) because it's so inconsistent compared to the other texts.

**Comment by frandominguezl** [comment]
Alright, I understand you point. I do not doubt about your english skills but I do doubt about mines, so I asked a native english speaker, a team member which had no context about this. He said that both, the current string and your suggested one are good. Given the context of the helptext, it's obvious what's meant.
Anyway, if you still want, I can make the change but I don't think it's truly necessary.

**Comment by m4z** [comment]
IMAO this is one of the worst-quality strings in all of SMF (that I've seen so far), so if you have the time, please change it. 😇
Even changes as simple as `s/This is/Enter your/` && `s/the same/The same/` && `s/)\./.)/`  would make a world of a difference to my sore eyes.
