### ISSUE TITLE
Should make the backtrace information more obvious in the error log

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#5629]
It is so helpful for support purposes to have the backtrace information from an error, but right now it can be difficult for users to discover how to get it. Instead of an icon, we should move the link to the backtrace information to its own line in the error report and give it a label like "More information..." or something of that sort.

**Comment by albertlast** [comment]
since i like more a clean ui,
i like the existing way...

could you provide some kind of mock up?

**Comment by SychO9** [comment]
This is the idea @albertlast (I think)

![bi](https://user-images.githubusercontent.com/20267363/56829184-5b0adb80-6863-11e9-914e-0c0ea8c343e7.png)

**Comment by albertlast** [comment]
Static text with a url keep me not liking it.

**Comment by SychO9** [comment]
There isn't much to not like though, and it's especially helpful for the Support Team

**Comment by albertlast** [comment]
For this exists wiki or "how to post error" topic,
this is not part of the ui topic of smf error log.

**Comment by SychO9** [comment]
You expect people to find a wiki topic when they can't find the right icon ? :P

**Comment by albertlast** [comment]
I expect that sm.org provide a form where the important question placed holded and
ref to source how to get this information.
Ypou can place a big bling text and people will it not finde.

**Comment by Sesquipedalian** [comment]
> There isn't much to not like though, and it's especially helpful for the Support Team

Exactly. I'm not even on the support team, and even I have already had to explain how to get the backtrace information more times than I would like.

**Comment by frandominguezl** [comment]
@SychO9 This looks neat. Perhaps might want to make a PR?

> This is the idea @albertlast (I think)
> 
> ![bi](https://user-images.githubusercontent.com/20267363/56829184-5b0adb80-6863-11e9-914e-0c0ea8c343e7.png)

**Comment by SychO9** [comment]
I will soon enough

**Comment by albertlast** [comment]
Since I see many times backtrack in sm.org I still see no need.

**Comment by frandominguezl** [comment]
I respect your thoughts albertlast but let's make it easier for end users.
