### ISSUE TITLE
Misnomer $modSettings['who_enabled'] and incorrect $helptxt['who_enabled']

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#5632]
#### Description
> `$helptxt['who_enabled'] = 'This setting allows you to turn on or off the ability for users to see who is browsing the forum and what they are doing.';`

This seems to be incorrect. The option only controls the latter option.

If it is disabled, the Info Center on the front page will still show "Users Online"
* how many guests and members are online, and
* the names of online registered users.

However, the former isn't a link anymore, so you can't find out what individual users are doing.

I proprose to either
* also hide the info center section "Users Online" if this setting is disabled, or
* find a more proper name and description for it

### Steps to reproduce
1. Read Help.*.php

### Environment (complete as necessary)
- Version/Git revision: HEAD

**Comment by illori** [comment]
this is related to the page that shows what the users are doing online.

https://www.simplemachines.org/community/index.php?action=who as was mentioned in the PR. i dont think this has anything that needs to be fixed.

**Comment by SychO9** [comment]
And since it only disables the who online page, the string should probably be changed to say

```
$helptxt['who_enabled'] = 'This setting allows you to turn on or off the ability for users to see what those online are doing.';
```

**Comment by m4z** [comment]
The (current) description is misleading. I disabled this feature in an attempt to disable the "Users Online" part of the Info Center and expecting from the description it does exactly that.

Regarding a solution, I'd still prefer to have one that includes the possibility to disable the Info Center. :wink: (But I've no problem at all with moving that part to another issue and fixing only the language issue here.)

**Comment by illori** [comment]
maybe adding a link to the page that is being enabled/disabled. otherwise i dont see how we can actually fix this unless the page has its name changed which may confused more then fix.

**Comment by illori** [comment]
we had an option to disable the info center in SMF 2.0, it seems to have been removed in SMF 2.1. since it has been removed i dont see that we would add it back.

**Comment by m4z** [comment]
:crying_cat_face:

**Comment by m4z** [comment]
BTW `ManagePermissions`:`permissionhelp_who_view` is more specific and also describes the issue I was complaining about; maybe the text fix could put the two more in sync:
`$txt['permissionhelp_who_view'] = 'Who\'s online shows all members that are currently online and what they are doing at that moment. This permission will only work if you also have enabled it in \'Features and Options\'. You can access the \'Who\'s Online\' screen by clicking the link in the \'Users Online\' section of the board index. Even if this is denied, members will still be able to see who\'s online, just not where they are.';`
