### ISSUE TITLE
$helptxt['avatar_action_too_large']: confusing reference

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#5634]
#### Description
The "external avatar" section contains the option to decide what to do with large images, and seemingly out of the blue, the help text begins with:
> `$helptxt['avatar_action_too_large'] = 'This setting therefore lets you reject images [...]`

I think the "therefore" is a reference to the "external avatar" section help text:
> `$helptxt['avatar_external'] = 'With this enabled, your members can type in a URL to their own avatar. The downside of this is that, in some cases, they may use avatars that are overly large or portray images you don\'t want on your forum.';`

But without any context (if the user hasn't read that, or doesn't draw the connection), it's just confusing. I therefore propose to drop "therefore". 😉 

### Steps to reproduce
1. Read Help.*.php 

### Environment (complete as necessary)
- Version/Git revision: HEAD

**Comment by gevv** [comment]
@Gwenwyfar   Is it possible to merge?  as "Language issues"

sample; https://github.com/SimpleMachines/SMF2.1/issues/4713

**Comment by Gwenwyfar** [comment]
@m4z, indeed it would be better to keep many of those problems in a single issue, it's easier to fix them all at once (since it's all just grammar fixes, so there's not much to it) and link to only one PR.

**Comment by Sesquipedalian** [comment]
> @m4z, indeed it would be better to keep many of those problems in a single issue, it's easier to fix them all at once (since it's all just grammar fixes, so there's not much to it) and link to only one PR.

That would be preferred, yes. Could you please compile all these individual reports into a single issue and then close the individual ones, @m4z? That will make it easier to manage them all.

**Comment by m4z** [comment]
Yeah I closed (some of?) the language PRs already, but forgot the language Issues. Closed some more now. All those that are still open are waiting for a comment or nudge in the right direction.

Sadly I'm behind my schedule, but I'm tracking my TODO list in a private Trac, so I will get to it, probably in a week or two.

**Comment by Sesquipedalian** [comment]
Thanks, @m4z. 

Rather than maintaining your own list in a separate bugtracker, I think you might find it easier to just use Markdown syntax to create a checklist in your unified issue here on GitHub. Then you wouldn't need to manually synchronize information across disconnected systems, and it would be easier for the rest of us to interact with the list. 😊
