### ISSUE TITLE
$txt['quote'] in translation

### ISSUE THREAD

**Issue by ChainyEO** [SimpleMachines/SMF#565]
This is something that affects translations into many languages.

$txt[['quote']  - in index.english-utf8.php - This is used to place the word "Quote" both on the button in the top right hand side of a post, and also to place the word "Quote" above a quotation in a post.

This is OK in English, but in many other languages it causes bit of a problem as the verb form "to quote"  is different to the noun form "a quote". In the case of German, they have made do with the noun form in both cases (Zitat), but this looks strange next to the other buttons, which all use the verb form. In the case of the Russian translation, they have used the noun form, but that means it says "to quote" above each quotation, which is far from ideal ! I translate the Esperanto version and it has the same problem...

Would it be possible to create an extra string to help solve this? Thank you!

Here's a picture of the problem:

![quote1](https://f.cloud.github.com/assets/3731638/940571/f8b35e7c-012e-11e3-9f62-aaabf90dcc39.png)

**Comment by XinYenFon** [comment]
I agree that could be better to split $txt['quote'] and $txt['quote_action']

**Comment by ChainyEO** [comment]
Yes, that would be perfect. Would it be difficult to do that? Sorry, I don't know much about the technical side.

**Comment by Oldiesmann** [comment]
It won't be too difficult to do at all. According to my editor (phpDesigner), $txt['quote'] is only used in 8 places (excluding where it's defined). I'll take a look at this tomorrow and see what I can do. It looks like most of the uses are the verb form anyway.
