### ISSUE TITLE
Default font size too small in mobile

### ISSUE THREAD

**Issue by avalyn2** [SimpleMachines/SMF#5650]
Attach samples from elpais.es, smf mobile and finally smf 2.1. As you can see the default font size in mobile is too small. Can this be increased in the next release?

![Screenshot_20190505-125548](https://user-images.githubusercontent.com/32930476/57192877-a5f8b300-6f35-11e9-835e-a58afafd7bca.jpg)
![Screenshot_20190505-125702](https://user-images.githubusercontent.com/32930476/57192878-a5f8b300-6f35-11e9-9ee6-91c4fd794695.jpg)
![Screenshot_20190505-125535](https://user-images.githubusercontent.com/32930476/57192879-a6914980-6f35-11e9-9b09-7d0c3f63dd59.jpg)

**Comment by Sesquipedalian** [comment]
I would prefer a larger size, too. A larger size is easier to read in general, of course, but moreover iOS will automatically zoom in on input fields and textareas when the font size is less than 16px, which can get very annoying to users trying to interact with the forum.

However, I can imagine that an increased font size might break some elements of the layout on small screens, so changing this would need thorough testing on all UI pages.

Do @Gwenwyfar, @SychO9, and/or @Antes have any thoughts to share on this matter?

**Comment by SychO9** [comment]
Depends, do we want to increase the font size everywhere and only on small screens (that as you said will need thorough testing to make sure all is good) or do we want to increase the font size in the post area only, that wouldn't cause any trouble.

As for the iOS zooming issue, we can obviously just target the fields as well, but I'm afraid that it'll start looking inconsistent, so we might want to increase the font size on the whole page.

**Comment by Sesquipedalian** [comment]
I think it would be best to increase the base font size of the whole page, if we can do so without breaking anything. We should probably also explicitly set the font size of the inputs and textareas to 16px, just to be sure.

**Comment by Gwenwyfar** [comment]
I was actually considering increasing the size by 1px for everything. The standard we use has gotten old due to higher resolution monitors. The physical size of the fonts is smaller than it used to be in a large portion of monitors. And sadly, using values in cm or mm is still not really widely supported (which would essentially make the sizes consistent anywhere). This would make it something close to 13px, since we're using % to define the base font.

For mobile, I'm not sure 1px larger is going to be enough, so we can always increase another px or two just for it. I'll have to do some testing to see how big 16px is.

**Comment by StealthWombat** [comment]
My 2c on this (since I know you're all dying to hear it :P ):

Back when I did the alpha code I set font-size to 83.33% simply because it was supposedly one of the exact font sizes (10pt) that Windows had designed their desktop fonts for, and it was minutely bigger than the font size set for the old Curve (which was the equivalent of 12.48px, but in Verdana *yuk* rather than Segoe UI *nicer*).

With the benefit of hindsight 10pt is a bit too small, and for Elkarte we settled on 14px (declared as 87.5% from memory). This is a nice size for the average desktop monitor. Mine is 1920x1200 and 95 dpi, and 14px/87.5% text is perfect on it. OTOH, 16px/12pt is like being hit in the face with a brick.

What I have done with my latest messing around mutant for 2.0.x is to set 14px for low dpi large screens, and 16px for small and/or high density screens. This should, hopefully, keep just about everyone happy.

```
body {
	margin: 0;
	padding: 15px 0;
/* Backdrop gradient. */
	background-image: linear-gradient(#375976 0, #e9eef2 500px);
/* Typography update. */
	color: #444;
	font: 1.4rem/2rem "Segoe UI", Roboto, -apple-system, BlinkMacSystemFont, Arial, sans-serif;
}
/* Set Retina font-size to browser default. */
@media screen and (min-resolution: 160dpi) {
	body {
	font-size: 1.6rem;
	line-height: 2.2rem;
	}
}
```
```
/* Textareas need their own declaration for font. */
textarea {
	box-sizing: border-box;
	max-width: 100%;
	min-width: 100%;
	margin: 0;
	padding: 6px;
	font: 1.4rem/2rem "Segoe UI", Roboto, -apple-system, BlinkMacSystemFont, Arial, sans-serif;
	border: 1px solid #7f9db9;
}
/* Set Retina font-size to browser default. */
@media screen and (min-resolution: 160dpi) {
	textarea {
	font-size: 1.6rem;
	line-height: 2.2rem;
	}
}
```
And lower down the file:
```
/* 640px at standard browser settings. */
@media screen and (max-width: 40em) {
	body, textarea {
	font-size: 1.6rem;
	line-height: 2.2rem;
	}
```
...along with the rest of the responsive stuffz.

And yes, Ant sets break points in em. Break points in em are yummy. You do wotcha like.

**Comment by StealthWombat** [comment]
Just thought of an easier way of doing this. It saves separate declarations for textareas and line-height.

I'm using the old 62.5% trick on my current playground. IOW, font-size is set to 62.5% (exactly 10px) on the html tag, which makes all font sizes and line heights multiples of 10 in exact pixels. This makes it easy to get things nicely aligned on average desktop monitors. To shunt things up to a 16px body text size, all that's needed is this:
```
html {
	background-color: #e9eef2;
/* Reset to 10px base for easy font sizing. */
	font-size: 62.5%;
}
/* Set Retina font-size to browser default. */
@media screen and (min-resolution: 160dpi) {
	html {
	font-size: 71.43%;
	}
}
```
Doing it that way means all your relative font sizes and line heights are still in proportion to each other. They won't be in exact CSS pixels, but on a high density screen there will be 3 or more physical pixels per CSS pixel anyway, so things should still be aligned better than anyone can notice.

**Comment by StealthWombat** [comment]
> 
> 
> I think it would be best to increase the base font size of the whole page, if we can do so without breaking anything. We should probably also explicitly set the font size of the inputs and textareas to 16px, just to be sure.

Found an interesting idea about the auto-zoom on iOS.
[https://thingsthemselves.com/no-input-zoom-in-safari-on-iphone-the-pixel-perfect-way/](url)

---------------------------------------------

Edit: On second thought that really is a bit over the top. Here's a more sensible idea:

That media query I suggested earlier (min-resolution: 160dpi) apparently won't work on Safari/iOS anyway. No idea why, but Safari is the only one that won't support it. Even IE supports it.

However, what iOS does support is another one that nobody else supports (d'oh). This will target iOS, but nothing else on the planet:

```
@supports (-webkit-overflow-scrolling: touch)
```

If base body text size is being boosted on mobile anyway (114.3% on the html tag, or similar) then inputs should not be much smaller than this even without any tweaks. At a guess 1, or not more than 2, px less than body text. Giving them a bit of a boost in iOS still shouldn't break anything. The existing line-height should be quite adequate to handle it with the text still sitting nicely inside the inputs.

2.1 CSS is currently worked out on the assumption that base html font-size will be the standard 16px/100% so best to keep that to minimise work. If standard body text on desktop is going to be declared as 14px/87.5% then the media query for everyone except iOS would be:

```
@media screen and (min-resolution: 160dpi) {
	html {
	font-size: 114.3%;
	}
}
```

Which will give you a theoretical 16.02px font size for body text on high density gizmos (and nobody will notice the .02). To deal with iOS, this should work:

```
@supports (-webkit-overflow-scrolling: touch) {
	html {
	font-size: 114.3%;
	}
	input, button, select, textarea {
	font-size: 1rem;
	}
}
```

Apparently if font-size is set to more than 16px then OS will not auto zoom, so a theoretical 16.02px should keep it happy.

**Comment by gevv** [comment]
hi,
@Gwenwyfar 
issues can you merge with https://github.com/SimpleMachines/SMF2.1/issues/4713

**Comment by Gwenwyfar** [comment]
I'm no longer part of the team/following up on what goes on here, so that's for @SychO9 and @Sesquipedalian to decide. 

The idea for #4713 was to condense everything until a general revision was made, and make individual issues afterwards, given the large amount of issues at the time.

**Comment by sbulen** [comment]
@MissAllSunday I would close this out.  Many changes have been made, and it is much improved.

We need a specific issue raised to continue.

Thus, at the very least, the RC4 label should be removed.

**Comment by MissAllSunday** [comment]
Yes, a new and specific issue must be created for any still remaining issues.
