### ISSUE TITLE
Unable to verify referring URL. Please go back and try again.

### ISSUE THREAD

**Issue by avalyn2** [SimpleMachines/SMF#5651]
getting several errors like this in the log:

` Type of error: User 
Unable to verify referring URL. Please go back and try again.
http://myforum.com/index.php?action=login2`

**Comment by Sesquipedalian** [comment]
Appears to have been caused by misconfigured cookie settings and to have been fixed by changing them: https://www.simplemachines.org/community/index.php?topic=567608.0
