### ISSUE TITLE
strlen() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#5653]
Logging::truncateArray()  should be able to handle multidimensional arrays or skip them gracefully

`Type of error: General
Error message: 2: strlen() expects parameter 1 to be string, array given
File: /var/www/html/Sources/Logging.php
Line: 33`

**Comment by albertlast** [comment]
Would you want to skip this or
using implode to convert the array to a string?

**Comment by Sesquipedalian** [comment]
I'd use json_encode to handle them.

**Comment by MissAllSunday** [comment]
Whatever works for you but I'll go a step further and move that function to Subs.php where it can be used by others.
