### ISSUE TITLE
Some members can not login after migration to 2.1.x RC2

### ISSUE THREAD

**Issue by avalyn2** [SimpleMachines/SMF#5655]
#### Description

After migration some members are reporting they can not login to my forum. The temporary workaround is to give them the full path to login `path_to_forum/index.php?action=login`

### Steps to reproduce

Members reported the following:

> Having troubles signing up. It says I am "not allowed access to this section". Anyone else having this issue?

> I noticed the change yesterday in the late evening and couldn’t login.
Every time a small window appears with ‚error‘. The same happened today.

### Environment (complete as necessary)
- Version/Git revision:
- Database Type: MySQL
- Database Version: Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407
- PHP Version: 7.0.33

### Additional information/references

Maybe the above is related to the errors I am getting:

```
Type of error: User 
Unable to verify referring URL. Please go back and try again.
path_to_forum/index.php?action=login2
```

**Comment by Sesquipedalian** [comment]
Is this still happening, @avalyn2, or did the changes you made in [this discussion](https://www.simplemachines.org/community/index.php?topic=567608.0) resolve the problem for you?

**Comment by avalyn2** [comment]
hello, that solved the problem. thank you.
