### ISSUE TITLE
cron.php errors

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#5663]
#### Description
The database value you're trying to insert does not exist: group_list
Function: boardsAllowedTo
 https://mobasuite.com/forum/cron.php
 /home/lolupdat/public_html/forum/Sources/Security.php (Line 1108)

2: array_diff(): Expected parameter 1 to be an array, null given
 https://mobasuite.com/forum/cron.php
 /home/lolupdat/public_html/forum/Sources/Security.php (Line 1092)

8: Undefined index: is_admin
 https://mobasuite.com/forum/cron.php
 /home/lolupdat/public_html/forum/Sources/Security.php (Line 1077)

### Steps to reproduce
1.  fresh install of rc2
2. 

### Environment (complete as necessary)
- Version/Git revision: RC2
- Database Type: mysql
- Database Version:
- PHP Version:7.3

### Additional information/references

These are the 3 errors I currently get with cron

**Comment by Sesquipedalian** [comment]
This sounds like the same issue that #5659 is meant to fix.

**Comment by ghost** [comment]
After applying that fix this is what I now get :
Type of error: Critical
Invalid value inserted or no type specified.
Function: alert_count http://mobasuite.com/forum/cron.php
/home/lolupdat/public_html/forum/Sources/Profile-Modify.php (Line 2391)
	

Type of error: Cron
Undefined index: english http://mobasuite.com/forum/cron.php
/home/lolupdat/public_html/forum/Sources/tasks/CreatePost-Notify.php (Line 307)

**Comment by JuanCarlosGO** [comment]
I had the same problem and after the change I have this:

Type of error: Critical 
The database value you're trying to insert does not exist: group_list
Function: boardsAllowedTo
 https://www.cuatrocuatro.com/foro/cron.php
 /homepages/8/d361504127/htdocs/cuatro/foro/Sources/Security.php (Line 1108)

Type of error: Cron 
2: array_diff(): Argument #1 is not an array
 https://www.cuatrocuatro.com/foro/cron.php
 /homepages/8/d361504127/htdocs/cuatro/foro/Sources/Security.php (Line 1092)

**Comment by ghost** [comment]
solved after calendar fixes update
