### ISSUE TITLE
2: Unknown: Failed to write session data using user defined save handler. (session.save_path: )

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5664]
#### Description
Anybody else getting these?

Getting a few variants of this message when simply navigating around the forum:
2: Unknown: Failed to write session data using user defined save handler. (session.save_path: )

### Steps to reproduce
1. Enable persistent db connections
2. Just navigated around

### Environment (complete as necessary)
- Version/Git revision:  Current GH as of now
- Database Type:  MySql
- Database Version:  5.7
- PHP Version:  7.1.3
- WAMP server

### Additional information/references
![image](https://user-images.githubusercontent.com/23568484/57503139-c8772d00-72a3-11e9-9579-1b1f3f373029.png)

**Comment by albertlast** [comment]
please add a backtrace

**Comment by sbulen** [comment]
I can no longer reproduce this at will.  May reopen if it recurs.

**Comment by albertlast** [comment]
Would be nice to had the backtrace any way.
