### ISSUE TITLE
css generic control on menues

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5665]
#### Description
parts like these should not be targeting a specific menu, instead we can generically target menues without having to edit the CSS for any additional menues, I've already done this in my test environment, it cleans up a lot of the code while still achieving its purpose.
```
#main_menu .popup_heading, #genericmenu .popup_heading {...}
#main_menu .popup_window, #genericmenu .popup_window {...}
#main_menu .popup_container, #genericmenu > .popup_container {...}
@media (max-width: 480px) 
#main_menu .popup_container, #genericmenu .popup_container {...}
@media (max-width: 480px)
.popup_window, #main_menu .popup_window, #genericmenu .popup_window {...}
@media (max-width: 480px)
#main_menu .popup_heading, #genericmenu .popup_heading {...}
```

but gotta wait for other theme related PRs to be merged before doing this. it gets messy when there are too many PRs editing the same file

**Comment by DiegoAndresCortes** [comment]
Dunno if it has been addressed but #main_menu .popup_container, #genericmenu > .popup_container
Needs a higher z-index than the sc editor. 
e.g. z-index: 4;
