### ISSUE TITLE
Should use hash_hmac to generate image proxy hashes

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#5666]
Right now, the hash used by the image proxy is generated using `md5($url . $image_proxy_secret)`. First, the fact that we are using md5 is a problem in itself, of course. But more fundamentally, this way of generating the hash for a given URL is inappropriate for this situation and makes it relatively easy to discover the value of `$image_proxy_secret`.

In general, `$hash = hash($algo, $message . $salt);` is appropriate when the value of `$message` is secret and the `$salt` and `$hash` are not. This is the approach we use for user passwords, for example, so that even if the database is compromised and the salt and hashes are learned by an attacker, the password itself (i.e. the secret message part) remains computationally unfeasible to calculate.

The situation with the image proxy is different, in that the value of the salt is the secret this time, whereas the message and hash are publicly visible. It would be better to use `$hash = hash_hmac($algo, $message, $salt);` in this case. This function does a better job protecting the salt value than the normal hash function.

Real cryptography nerds can go look up more research on this if they like. 😉

**Comment by albertlast** [comment]
did you not want to mention which algo should be used?

**Comment by Sesquipedalian** [comment]
Oh, probably sha256.
