### ISSUE TITLE
Error when on custom language edit page

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5668]
#### Description
If you hit edit on some languages, you get the following errors

```
Type of error: General 
Invalid argument supplied for foreach()
../index.php?action=admin;area=languages;sa=editlang;lid=arabic
../Themes/default/ManageLanguages.template.php (Line 212)
```
```
Type of error: Undefined 
Undefined index: name
../index.php?action=admin;area=languages;sa=editlang;lid=arabic
../Themes/default/ManageLanguages.template.php (Line 210)
```
```
Type of error: General 
usort() expects parameter 1 to be array, null given
../index.php?action=admin;area=languages;sa=editlang;lid=arabic
../Sources/ManageLanguages.php (Line 907)
```

also, weird thing, the footer's copyright year changes to 2011 on the edit page of that language(arabic)

### Environment (complete as necessary)
- Version/Git revision: https://github.com/SimpleMachines/SMF2.1/commit/229f76c70f63431558196fb3fb479789cea92ed5
- PHP Version: 7.1

**Comment by frandominguezl** [comment]
I couldn't replicate the error with Arabic language. Any other languages to test?

**Comment by SychO9** [comment]
I just tried again, I can still reproduce this with Arabic and French

**Comment by frandominguezl** [comment]
The copyright issue is because it's not updated in index.arabic.php L506. As for the other errors, I'm still unable to reproduce them. If someone else has time, please do try to reproduce the error.
