### ISSUE TITLE
Stats should use https

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#5670]
#### Description
Stats code uses port 80:
```
		$fp = @fsockopen('www.simplemachines.org', 80, $errno, $errstr);
```

We should change this to support both port 80 and 443, defaulting to 443.  We should also have this start sending a user agent (PHP/SMF)

### Additional information/references
Mostly adding this as a note to myself to look into fixing this.  This should be fixed before final but is not any RC deal breaker.

**Comment by frandominguezl** [comment]
@MissAllSunday If #5706 fixes this please add a "Has Fix" label to this issue.

**Comment by MissAllSunday** [comment]
No it doesn't
