### ISSUE TITLE
value error in writing database by cron

### ISSUE THREAD

**Issue by mhubaut** [SimpleMachines/SMF#5672]
#### Description
--error value in sql writing by cron

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:2.1 RC2
- Database Type:mariadb
[Backtrace.pdf](https://github.com/SimpleMachines/SMF2.1/files/3187170/Backtrace.pdf)

- Database Version:
- PHP Version:7.0

### Additional information/references
Incorrect string value: '\xE0\xAE\x9A\xE0\xAE\xBF...' for column 'value' at row 1 http://local.attac.org/tarn/forum/cron.php
/srv/www/attac.org/local/tarn/www/forum/Sources/Subs.php (Ligne 537)

**Comment by frandominguezl** [comment]
Any steps on how to reproduce this?

**Comment by Sesquipedalian** [comment]
Hm. I wonder how on earth `set_tld_regex()` could possibly have ended up passing a string like *that* to `updateSettings()`...

**Comment by Oldiesmann** [comment]
Looks like it's not treating the string as UTF-8, thereby causing it to get scrambled. The "9A" character in particular is likely what's causing the problem, as that's a Unicode control character rather than an actual symbol.

**Comment by Sesquipedalian** [comment]
That sounds reasonable. It was probably an incomplete download via fetch_web_data() then.
