### ISSUE TITLE
css notation for colors is inconsistent 

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#5674]
#### Description
in CSS files, some colors notated as hex -  # aaa 
and some notated as rgba - rgba(0, 0, 0, 0.1)

Usage should be consistent

### Steps to reproduce
1. view index.css

**Comment by SychO9** [comment]
if the color isn't solid (ie transparent) it's better to use rgba because IE doesn't like the hex notation

**Comment by Kindred-999** [comment]
fair....   it just makes things a little harder when making a child-of theme with color switches.

**Comment by SychO9** [comment]
yup I hear you, unfortunately IE doesn't give us a choice, we could change everything to rgba() but I personally would rather we use hex where we can.
