### ISSUE TITLE
Cron error (again)

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#5682]
### Steps to reproduce
1. Latest SMF2.1
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version: 7.3

### Additional information/references

Database error, given array of integer values is empty. (members)
Function: updateMemberData

/Sources/Subs.php (Line 422)

**Comment by Sesquipedalian** [comment]
For more info, see https://www.simplemachines.org/community/index.php?topic=567922.0

**Comment by ghost** [comment]
Any idea when this pr will be pushed into mainstream ?

**Comment by SychO9** [comment]
when it is finished and ready to go

**Comment by ghost** [comment]
vcool
