### ISSUE TITLE
Unapproved admin posts

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5690]
#### Description
Posts from an admin are unapproved

### Steps to reproduce
1. Use the quick reply textarea
2. Hit the "Preview" button, notice how the "Approve this post" checkbox is unavailable
3. Submit
4. Notice that the post is unapproved because the checkbox wasn't there.

### Environment (complete as necessary)
- Version/Git revision: https://github.com/SimpleMachines/SMF2.1/commit/9b265a38e63e161192f574406adfcbdfd7b307e4

### Additional information/references
https://www.simplemachines.org/community/index.php?topic=567724.msg4020460;topicseen#new

**Comment by Sesquipedalian** [comment]
Thank you for tracking down the way to reproduce this! Now that we know, it should be easy to find and fix the cause.

**Comment by albertlast** [comment]
So what is the main issue here?
That the button/checkbox is missing or that the post get not approved?

**Comment by Oldiesmann** [comment]
The main issue is that the post doesn't get approved, but the checkbox issue is the reason for that...
