### ISSUE TITLE
unapproved members count

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5697]
#### Description
The count does not go down when deleting the registrant's account from the admin area

### Steps to reproduce
1. Set registration to admin approval
2. register a new account
3. set registration to immediate
4. delete the account from the admin -> members area
5. see how the count is still there in the admin menu button

### Environment (complete as necessary)
- Version/Git revision: https://github.com/SimpleMachines/SMF2.1/commit/e0848c82fbbc912b51789a2fefded6b6830f086f (was: https://github.com/SimpleMachines/SMF2.1/commit/3428c48f144566b25b3ac0f97aa6cb505ebba264)

### Additional information/references
https://www.simplemachines.org/community/index.php?topic=565217

**Comment by nickwhetstone** [comment]
Is anyone able to reproduce this off of e0848c82fbbc912b51789a2fefded6b6830f086f? I am unable to do so.

**Comment by SychO9** [comment]
I am still able to reproduce it.

**Comment by frandominguezl** [comment]
Please, add "Has Fix" label over here
