### ISSUE TITLE
Language dropdown should never says "English" for non-English languages

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#5699]
If a language pack does not yet have a proper translation in the `$txt['native_name']` variable, the language selection menu will say "English" for that language instead of whatever it should say.

The long term fix is, of course, for all the language packs to be updated properly. But in the real world, we need to add a hack to fall back to the language file name if the value of `$txt['native_name']` is `English` when the language is not actually English.

**Comment by albertlast** [comment]
I saw the related topic,
but error of this is human issue and
humand issue need to solved by human and not from software...

See many possibly pains without many gains...

so i would say we don't need this.

**Comment by Sesquipedalian** [comment]
It was trivial to solve, actually. If the file name is `index.finnish.php` but it contains `$txt['native_name'] = 'English';`, that's obviously wrong and we can discard the `English` in that specific case. We can't predict what the value of `$txt['native_name']` *should* be, but it is easy enough to know when it should *not* be `English`.

**Comment by albertlast** [comment]
Like  the check for version number,
How scrued the rc2 release?

________________________________
Von: Jon Stovell <notifications@github.com>
Gesendet: Montag, 3. Juni 2019 05:39
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] Language dropdown should never says "English" for non-English languages (#5699)


It was trivial to solve, actually. If the file name is index.finnish.php but it contains $txt['native_name'] = 'English';, that's obviously wrong and we can discard the English in that specific case. We can't predict what the value of $txt['native_name'] should be, but it is easy enough to know when it should not be English.
