### ISSUE TITLE
alert_count Invalid value inserted or no type specified

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5703]
#### Description
Getting this in the error log
```
Type of error: Critical 
Invalid value inserted or no type specified.
Function: alert_count
http://.../cron.php
.../Sources/Profile-Modify.php (Line 2412)
```

https://github.com/SimpleMachines/SMF2.1/blob/3428c48f144566b25b3ac0f97aa6cb505ebba264/Sources/Profile-Modify.php#L2403-L2412

### Steps to reproduce
The errors gets logged often from the cron jo, but you can manually trigger it aswell:
1. Using two accounts, lock a topic that the other account is following
2. you should see the error logged, but you might have to retry a few times

### Environment (complete as necessary)
- Version/Git revision: 3428c48f1

### Backtrace Information
```
#0: smf_db_error_backtrace()
Called from ...\Sources\Subs-Db-mysql.php on line 190
#1: smf_db_replacement__callback()
Called from unknown on line -1
#2: preg_replace_callback()
Called from ...\Sources\Subs-Db-mysql.php on line 404
#3: smf_db_query()
Called from ...\Sources\Profile-Modify.php on line 2412
#4: alert_count()
Called from ...\Sources\Subs.php on line 394
#5: updateMemberData()
Called from ...\Sources\tasks\CreatePost-Notify.php on line 357
#6: execute()
Called from ...\cron.php on line 216
#7: perform_task()
Called from ...\cron.php on line 110
```

**Comment by shnazzle** [comment]
This particular defect is causing thousands of errors a day. Happy to look at it, if someone has already established the offending area, I'll have a look. If not, I'll have a look from scratch :)

**Comment by Sesquipedalian** [comment]
By all means feel free, @shnazzle. That would be most helpful.

**Comment by SychO9** [comment]
From what I can see, if **build_query_board** is not executed here, than it will need to take the values from $user_info array, but the array is not populated with that info in cron jobs, which is what causes the error, we can fix this by loading the user settings in cron.php (that's just one way though)

https://github.com/SimpleMachines/SMF2.1/blob/fd4c4fea7ba1b6f10e46f8471ab62836af9b7e35/Sources/Profile-Modify.php#L2372-L2379

**Comment by shnazzle** [comment]
I admit to not fully understanding this but why are we checking the logged alerts for whether they should be visible? Should it not be that we don't enter it into _user_alerts unless it should be visible?
Why apply a board access filter after we've requested an alert?

i.e. an alert shouldn't be logged for the user, for a msg,board or topic, unless they have access to it and they have requested an alert?
Or is that what it already does?

**Comment by SychO9** [comment]
The msg/topic can in the future be moved to a board not visible to the user

The board's access can in the future be changed.

That's why those checks are in place

**Comment by shnazzle** [comment]
aha.

Makes sense. But then again, my preference would be to unset the alert when the board access is changed, or the user access is changed etc.

Logic being: access-changing events are a lot less common than cron alert checks every 5 mins. So it should severely reduce the overall load of the forum

**Comment by albertlast** [comment]
Since we changed the logic of access-right checks for boards from 2.0 to 2.1,
the logic and check is very fast,
this goes so far that a user with limited access can be faster than someone with many rights.

Also the access are intregated by the data collection,
so the check didn't add to the time.

**Comment by albertlast** [comment]
i'm not able to reproduce the error to be honest.
@Sesquipedalian but by looking at the code i ask my self if this check ``(!empty($possible_msgs) || !empty($possible_topics))`` realy provide a good way or maybe the root cause of this complete issue?

So my first guess would be to delete this part of the if part,
but you introduce this with some reason: https://github.com/SimpleMachines/SMF2.1/pull/5687

**Comment by shnazzle** [comment]
I've circumvented the error by implementing a "1=1" on the check. Logic being that if they don't have access to that board anymore, it will just fail to open the topic/thread.

I couldn't find a clean way to incorporate the necessary global data

**Comment by albertlast** [comment]
Like i said,
when you change
```
if ((!isset($user_info['id']) || $user_info['id'] != $memID) && (!empty($possible_msgs) || !empty($possible_topics)))
```
to
```
if ((!isset($user_info['id']) || $user_info['id'] != $memID))
```
Should work fine

**Comment by SychO9** [comment]
that's not the problem @albertlast, the problem is when the condition isn't meat and it goes to the else block, the user settings aren't loaded in cron jobs so the {query_see_message_board} for example doesn't get replaced with the actual data.

This can be fixed by adding loadUserSettings(); to **cron.php**, but I'm just not certain that's the best solution.

**Comment by albertlast** [comment]
Like i said,
in my eyes is the problem that he goes in the else part.
The initial idea of this if case is (i know it becaue i wrote this) to handle the case when the user data are not loaded,
so it make no sense to call loadUserSetting here.

**Comment by SychO9** [comment]
Aha I see now, I tested what you wrote but it didn't fix the issue either, that's because **$user_info['id']** is set but not **query_see_\***

This on the other hand fixes the issue

```php
if ((!isset($user_info['query_see_topic_board']) || $user_info['id'] != $memID))
```

Which should probably also be changed in the `fetch_alerts()` function as well

**Comment by albertlast** [comment]
Your fix looks very good,
is this still working when we add `` && (!empty($possible_msgs) || !empty($possible_topics)) ``?

**Comment by SychO9** [comment]
Yes this works
```php
if ((!isset($user_info['query_see_topic_board']) || $user_info['id'] != $memID) && (!empty($possible_msgs) || !empty($possible_topics)))
```

**Comment by albertlast** [comment]
want you do the pr for this?

**Comment by SychO9** [comment]
done
