### ISSUE TITLE
online icon @ action=who

### ISSUE THREAD

**Issue by Pipke** [SimpleMachines/SMF#5719]
Just wondering why are there online icon(s) at the action=who page, all users/guest are online at that page aren't they....
![why_online_icon_at_who_online](https://user-images.githubusercontent.com/31970508/59877962-7697eb80-93a7-11e9-816d-2fa1f51ff57a.png)

**Comment by frandominguezl** [comment]
It's weird. When you click the button, you get directed to sending a PM to said user. I don't believe this is the expected behaviour. Maybe we should switch the icon to the "New Message" one?

**Comment by SychO9** [comment]
> Maybe we should switch the icon to the "New Message" one?

Yea I think we should do that
