### ISSUE TITLE
obtaining themes in admin panel

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#5723]
#### Description
If you run into any questions with themes, each modification published on simplemachines.org has a dedicated topic about it where support and comments should be directed to. 

it should be

If you run into any questions with themes, each **theme** published on simplemachines.org has a dedicated topic about it where support and comments should be directed to.

**Comment by albertlast** [comment]
How is smf 2.1 by this affected?

**Comment by illori** [comment]
this is a string in SMF 2.1 that is incorrect. did you even look before you posted your question?

**Comment by albertlast** [comment]
you didn't mention the place,
so why is the discription not self explaining?

**Comment by illori** [comment]
the place is in the title of the bug.
