### ISSUE TITLE
Link to delete Package on uninstall package

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5731]
As a mod developer one thing that annoys me is when I uninstall a package. Normally I want to delete the package. This usually involves going back to package manager file listing and finding the mod to delete.  It would be cool to add a link to delete the package on the same page that says the package has been uninstalled.

**Comment by albertlast** [comment]
Could you add a image how you think this should look like?

**Comment by VBGAMER45** [comment]
Sure something really basic like this screenshot


![deletepackage](https://user-images.githubusercontent.com/978002/60909644-62c40480-a244-11e9-9382-76492ad08d97.png)

**Comment by MissAllSunday** [comment]
Closed via #5733
