### ISSUE TITLE
getBoardindex do call parse_bbc which takes 94% of the run time

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#5734]
#### Description
notice in my test board,
that the generation goes up from ~ 0.060 ms to ~0.340 ms.
By cecking the trace i notice that the parse_bbc and calls below create 94% of the call time:

![grafik](https://user-images.githubusercontent.com/1782906/61103166-38a35a00-a471-11e9-94eb-a1a65c0c3512.png)

trace file: https://mega.nz/#!W8piDSKa!6qkqASjhWj80unkS8uAY_XvFW5iwHYRhJZtdjjScyik

issue is introduce by pr: #5704 from @MissAllSunday 
because of this line: 
https://github.com/SimpleMachines/SMF2.1/blob/e941ff2b0b31fe44a8aeb9ca435ff6231d5eaa26/Sources/Subs-BoardIndex.php#L263
### Steps to reproduce
1.  time notice on the start page

### Environment (complete as necessary)
- Version/Git revision: e941ff2b0
- Database Type:
- Database Version:
- PHP Version: 7.2

### Additional information/references

**Comment by MissAllSunday** [comment]
Yeah, this is a side effect of moving the parsing to display.

Since the board and category descriptions won'y be updated that often, we can save the parsed description on cache

**Comment by albertlast** [comment]
Well from performance point of view,
the feature double(with improved build_regex) the time of the smf start page,
so it should double the user exprience otherwise is questionable to take so mutch time for not worth function.

A middle way in my eyes could be the right way:
to safe the information twice in the database,
in one column the orginal version(this is would be the string which we use now) and display/optimize column where the parsed version is filled in.

So when you editing/changing you work with the original column and
when you display this information you use the display column

**Comment by MissAllSunday** [comment]
Yeah, that's pretty much what the cache does already only without the burden on adding a new column on the db.

This really belongs to a cache entry, specially since using a proper cache system will be far better than a DB entry.

If you are worried about users not using any cache, then there isn't much we can do, perhaps instructing users to use it whenever possible.

**Comment by albertlast** [comment]
from performance view, is the cache slower than database in this case.
because you need to run a select anyway, so a column more or less doesn't hurt,
but to do 193 cache calls add to the time.

**Comment by MissAllSunday** [comment]
Thing is, if we see everything from a performance view then we will never finish doing performance optimizations.

We have a cache feature, this case can benefit from using said feature, lets use it. Even if there are better ways to do it.

We also need to start thinking about SMF's code being scalable and uniform. Whats better, to add a new column to fix this specific case or normalize all our bottlenecks into using our cache system and focus on making the cache feature get faster and better?

**Comment by albertlast** [comment]
did you read what you write?
you write:
stop performance optimization
add third party stuff which we doesn't had under controll
and do performance optimization

Every smf got a database,
not every smf got a cache and
we got many different caches so what would be easier to optimiz and better for more setups?

Write good code is my eyes the better solution and
for this case here you need the data in different format.

**Comment by MissAllSunday** [comment]
Lets agree to disagree then, I prefer a long term fix rather than an easy, short term one.

And no, I never said "stop performance optimization add third party stuff". I said over thinking about performance doesn't help.

> add third party stuff which we doesn't had under controll

Sure, we know better about caching than, for example, the Memcached guys...  and yeah, PHP/MySQL combo surely is far more better at cache and performance than specialized tools we already offer support by default 🙄 

> we got many different caches so what would be easier to optimiz and better for more setups?

We indeed support multiple cache systems, however, we support them via an easy to expand and maintain cache api.

**Comment by albertlast** [comment]
to throw data into a cache is the short easy solution,
to make a clean database design which scale well with different amount of data is the right one, yes.

every cache call take some time,
when you do it 193 times is that slower than doing no call.

**Comment by live627** [comment]
-  The cache subsystem is the perfect candidate for this.
- Those who have it disabled won't see the problem. (small boards et al)
- Ditto for database caches.
- Most admins won't have near 200 boards.
- Big boards where this may come into play will already have apc/memcache


Also, a separate db column will not be i18n friendly.

**Comment by albertlast** [comment]
I see you read the really the code...
Because  for every board parse BBC is called twice,
One for the name
One for the description 

And the same for the category.

To get over  200 calls you only need around 90 boards and this not uncommon.

The cache system is not faster as the existing solution.

**Comment by MissAllSunday** [comment]
> The cache system is not faster as the existing solution.

Can you please attach your benchmarks?

**Comment by albertlast** [comment]
Since is your idea to fix this issue by cache,
present us the solution + benchmark.

From my pov i already miss a hint from the initial pr (#5704),
"the pr could slow down smf by the factor 5".
