### ISSUE TITLE
Upgrader - challenges with 1.1 to 2.1 upgrade

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5741]
#### Description
Having problems with dates when upgrading from 1.1 to 2.1:  
![image](https://user-images.githubusercontent.com/23568484/61583093-1d2af580-aae8-11e9-80a3-286b311f9d72.png)

### Steps to reproduce
1. Install a 100% vanilla 1.1.21
2. Upgrade to 2.1

### Environment (complete as necessary)
- Version/Git revision:  GH as of today
- Database Type:  MySQL
- Database Version:  5.7
- PHP Version: 7.1

**Comment by sbulen** [comment]
I believe this is due to applying strict mode to this old 1.x syntax:
```
UPDATE {$db_prefix}calendar
SET endDate = startDate
WHERE endDate = '0001-01-01'
	OR endDate = '0000-00-00';

UPDATE {$db_prefix}calendar_holidays
SET eventDate = '0001-01-01'
WHERE eventDate = '0000-00-00';
```
In these cases, it's not trying to STORE the invalid values, it's attempting to REPAIR the invalid values.

**Comment by albertlast** [comment]
The fix would be to place simliar logic from 2.1 here:
https://github.com/SimpleMachines/SMF2.1/blob/e0848c82fbbc912b51789a2fefded6b6830f086f/other/upgrade_2-1_mysql.sql#L3-L27

But the result would be,
that 1.1 upgrade create a database version which is not any more 1.1...
Maybe to remove this logic from 1.1 upgrade would be the most valid way to fix it.

**Comment by sbulen** [comment]
I think we need to... Those old upgrader scripts need to be able to execute under more recent versions of mysql.

An alternative may be to associate each step with it's own sql_mode.

**Comment by albertlast** [comment]
This change will be changed in a later time of the upgrade again,
so it make no sense to keep this.

**Comment by sbulen** [comment]
For the record, 1.1 has a few issues, but 1.0 has MANY issues...  

It should be able to run thru...

**Comment by sbulen** [comment]
The dates aren't the only issue with 1.1 - the 'previous fix detected' kind of logic has at least one issue as well:
![1-0-upgrade-9](https://user-images.githubusercontent.com/23568484/61921788-29adb480-af13-11e9-8cf5-d5ce5c3bc7ba.JPG)

**Comment by sbulen** [comment]
Found another issue if you leave the "classic" theme laying around:
![image](https://user-images.githubusercontent.com/23568484/62014954-2822fd00-b15c-11e9-8094-47b3336ae4d9.png)
