### ISSUE TITLE
Language install error HTTP 500 on edit language

### ISSUE THREAD

**Issue by dhmyrdal** [SimpleMachines/SMF#5748]
#### Description
Edit or set language to Norwegian give HTTP error.
"This page isn’t working <site> is currently unable to handle this request. HTTP ERROR 500"
Similar to issue #5668, but seems not to be covered by that one.

### Steps to reproduce
1.  Install on top of site with UTF8 language files.
2.  Download new language packs.
3. Set default language to Norwegian or enter edit language menu:  URL: ...forum/index.php?action=admin;area=languages;sa=edit;dcbe096=a54ac7c21bd7881119b9e0dbd00102ae

### Environment (complete as necessary)
- Version/Git revision: 2.1 RC2
- Database Type: mysql 
- Database Version:  5.7.
- PHP Version:  5.5.36

### Additional information/references
https://www.simplemachines.org/community/index.php?topic=567729.msg4019307#msg4019307

**Comment by albertlast** [comment]
Please notice that mysql min version 5.0.22 or 5.1.10 is,
your 5.0.11 is below this version number.

**Comment by dhmyrdal** [comment]
I have contacted my ISP to see if they can upgrade the database. However - there are several other people that have had similar issues and reported in the thread, so I am not convinced that will fix it. Will report back when I know.

**Comment by albertlast** [comment]
this issue will be not fixed by the database upgrade,
but we set the mysql not random,
so something will not work when mysql is below 5.0.22.

This issue is related with the to low mysql version: https://github.com/SimpleMachines/SMF2.1/issues/4441

**Comment by dhmyrdal** [comment]
Thanks for the info on issue #4441. Uniweb (our server host) responded that they did not see a reason to upgrade the servers as no major bugs or security issues were known for version 5.0.11...
Update: Turns out that I had the wrong version number. 5.0.11 was for mysqlnd. MySQL actually is 5.7.x

**Comment by dhmyrdal** [comment]
Additional info:  
1) There is a report in the thread that the same happen with Hungarian language. 
2) I have tried to remove all language files (including the ones that had -UTF8 tags in the file names) under the default template folder and copy manyally in all fresh versions from the distribution. => No change.
3) I have noticed what seems to be inconsistent: When adding a new language, the list says "SMF 2.1 RC2 norwegian", version "2.1 RC2", then UFT-8: "No"... Why "No"?    At the same time, the smf.settings table field "global_character_set" contains "UTF-8" and field "previousCharacterSet" contains "latin1"...  field "langlist" seems to correctly contain "{"english":"English","norwegian":"Norwegian"}"

**Comment by frandominguezl** [comment]
I installed the language pack and got some errors that didn't allow me to navigate the forum. They were because of syntax errors in the languages files. I'll update them tomorrow.

**Comment by MissAllSunday** [comment]
@frandominguez03 does #5778 fixes this issue?

**Comment by frandominguezl** [comment]
We discussed it:

![image](https://user-images.githubusercontent.com/10365222/65066142-199ada00-d984-11e9-9636-3a6e13169a88.png)

I believe it does, but it's up to you

**Comment by MissAllSunday** [comment]
Oh yes, I forgot about that. Sure if you removed the check for utf8 and directly assign the yes string var then that's enough for this.

**Comment by MissAllSunday** [comment]
#5778 has been merged, will close this too.
