### ISSUE TITLE
Can't enable Two-Factor authentication

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5749]
Anyone able to enable it in their account ? It doesn't seem to be working for me using **Google Authenticator**. It shows a success box after enabling it, but it isn't actually enabled.

**Comment by vort7u** [comment]
Yes, I'm using it with RC2 without problems.

**Comment by SychO9** [comment]
did you try enabling it with the latest revision from GitHub though ?

**Comment by illori** [comment]
i just tested it and it did not enable, nor was i able to scan the QR code.

**Comment by jackschappell** [comment]
I just tried it again too. I can't get Google Authenticator to scan the QR code at all. It might also be a good idea to add a unique key for users that have phones that can't read QR codes easily. Most apps these days offer both options together.

**Comment by illori** [comment]
We have the unique key already. When I used it, I got the app setup but smf
did not see it.

**Comment by SychO9** [comment]
Thanks for confirming, I think the issue is related to the the following PR #5580

**Comment by SugarD-x** [comment]
Sorry, used the wrong account on here, but yes, I have the same issue as illori.

**Comment by SychO9** [comment]
hmm,

The process stops at the redirection in line 755 so the **tfasetup()** function doesn't even get executed, I'm unfamiliar with the logic here so I have no idea how to fix this.

https://github.com/SimpleMachines/SMF2.1/blob/e0848c82fbbc912b51789a2fefded6b6830f086f/Sources/Profile.php#L753-L765

**Comment by Oldiesmann** [comment]
I've never had problems with 2FA. Works on a couple of test boards of mine and a couple of live forums as well, both RC2 and the latest GitHub version. I use Authy as the authentication app for all but one of those (for the other one I use Bitwarden as I'd like to keep my 2FA and passwords in a single spot)

**Comment by SychO9** [comment]
unless you already had it enabled when you updated to the latest github version, enabling it doesn't not currently work
