### ISSUE TITLE
Upgrader - challenges with 1.0 to 2.1 upgrade

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5750]
#### Description
Many issues with attempting to upgrade from 1.0.x.   The upgrader tries to do it, so it ought to work.  

Causes of various issues:
 - Compliance to STRICT mysql, so the old syntax doesn't work
 - 'Previous execution' logic not working
 - The 1.0 script also updates from YABB, and references YABB tables & fields
 - The 1.0 script must also, of course, repair any issues found with 1.0; there is at least one instance where the 1.0.x installer creates different field names than the app

I attempted a YABBSE install to test as well, but no luck, it just stared at me...  

### Steps to reproduce
1. Install any vanilla 1.0 version.  (I've been using 1.0.23.)
2. Upgrade to 2.1

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: MySQL
- Database Version: 5.7
- PHP Version: 5.6

### Additional information/references
![1-0-upgrade-5](https://user-images.githubusercontent.com/23568484/61921880-84471080-af13-11e9-9aa1-4b94c8713895.JPG)
![1-0-upgrade-4](https://user-images.githubusercontent.com/23568484/61921881-84471080-af13-11e9-919b-882942194d72.JPG)
![1-0-upgrade-3](https://user-images.githubusercontent.com/23568484/61921882-84471080-af13-11e9-8696-c06ce0a5e75d.JPG)
![1-0-upgrade-2](https://user-images.githubusercontent.com/23568484/61921884-84471080-af13-11e9-8daa-432493f820f6.JPG)
![1-0-upgrade-1](https://user-images.githubusercontent.com/23568484/61921885-84471080-af13-11e9-8267-a65df258f067.JPG)
![1-0-upgrade-8](https://user-images.githubusercontent.com/23568484/61921886-84471080-af13-11e9-87b9-ab7688ccbc9f.JPG)
![1-0-upgrade-7](https://user-images.githubusercontent.com/23568484/61921887-84dfa700-af13-11e9-907e-ff215952ada6.JPG)
![1-0-upgrade-6](https://user-images.githubusercontent.com/23568484/61921888-84dfa700-af13-11e9-89df-04e9531d882d.JPG)

**Comment by sbulen** [comment]
Note: the UTF8 conversion has issues with 1.0 as well.  This is specific to 1.0.   1.1 & 2.0 upgrades test OK.   On the left is a "Kermit test" of a 1.0.23 upgrade (bad), on the right is a 1.1.21 upgrade (good):
![image](https://user-images.githubusercontent.com/23568484/61963876-7c25ba00-af81-11e9-9f39-3101639099d1.png)

![image](https://user-images.githubusercontent.com/23568484/61964171-1ede3880-af82-11e9-8b90-fe241202e618.png)

**Comment by sbulen** [comment]
I believe the challenge with the 1.0 items is that they were never converted to html entities...   

For some reason, the Maintenance function isn't working to fix these...  The message bodies appear to be untouched.

**Comment by sbulen** [comment]
OK...  I no longer think the utf8 issue noted above has anything to do with the upgrader.  

First, the data is clearly double-encoded - _even in 1.0.23, before the upgrade_.   After the upgrade, it is untouched (still double-encoded), and in the DB, represents the exact same content as before 1.0.23.  The ugrader leaves it alone, as expected.  

I suspect this is more of a problem with running 1.0.23 on a recent apache install that wants to speak in utf8.  

As such, it is not a problem really with the upgrader; it's the data.  

I think we've seen this before in the support forum.  It'd be nice to have a "find & fix double-encoded utf8 data" utility hanging around!

**Comment by Arantor** [comment]
Also if you were testing the YABB SE part, you need to drop down to PHP 4.x since it predates $_GET and $_POST existing and the legacy method was long since removed.

**Comment by sbulen** [comment]
Thanks @Arantor ...

I actually tried to install YABBSE but couldn't get it up & running.  That explains why!  

I don't have access to a php4 environment.  My WAMP only goes back to 5.6, &  my host only goes back to 5.4.

**Comment by Arantor** [comment]
Grab VirtualBox, install an old version of Ubuntu on it, then you can have whatever version of PHP you need... I recently did this for 1.0 and 1.1 so I could check out some themes I had in my archive and take screenshots for references. (Though I went with PHP 5.2 on Ubuntu 12.04, didn't feel the need to go back to really old versions, though isos should be available if you wanted to do so)

**Comment by sbulen** [comment]
Getting php4 up & running is a windmill I don't want to tilt.  

However, with a little effort, Yabbse installs cleanly, with a good file system, db, and settings.php file...
