### ISSUE TITLE
Upgrader - challenges with 1.0 to 2.1 security

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5751]
#### Description
If you upgrade from 1.0 to 2.1, your password is somehow mucked up...  You're locked out.  I've tried this a couple times, it always happens

### Steps to reproduce
1. Install 1.0.23, get it up & running fine
2. Upgrade to 2.1

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: MySQL
- Database Version: 5.7
- PHP Version: 5.6

### Additional information/references
![image](https://user-images.githubusercontent.com/23568484/61925192-0a695400-af20-11e9-83fb-ac95d173d037.png)

**Comment by illori** [comment]
i dont have 1.0.* available, can you check the password hashing that is used compared to other versions? i dont know when we started to use sha1 and how that would be converted to work with the new hash in 2.1.

**Comment by sbulen** [comment]
I'm not as familiar with that code...  

At first glance I think it's using md5_hmac & that there is no salt in 1.0. 

2.1 has logic to attempt to support the prior versions for this very reason.  I suspect it just needs to consider md5_hmac as well.

**Comment by sbulen** [comment]
And... md5_hmac is already in the list, intended for legacy 1.0.x support.  I don't know what the fix is here.

**Comment by sbulen** [comment]
OK - figured out the cause here.  The enable_password_conversion flag isn't set.  Once set, everything works perfectly.  

Of course, how do you set it if you can't login?
