### ISSUE TITLE
jQuery is outdated again

### ISSUE THREAD

**Issue by SugarD-x** [SimpleMachines/SMF#5760]
#### Description
jQuery has made several updates since the last public release candidate of SMF 2.1. Google Chrome is also reporting a potential vulnerability in the current version used by SMF 2.1 RC2 during page audits.

### Steps to reproduce
1. Not applicable.

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1 RC2
- Database Type: MySQL
- Database Version: 8.0.12 - MySQL Community Server - GPL
- PHP Version: 7.2.8

### Additional information/references
SMF 2.1 RC2 appears to be using jQuery 3.2.1, however jQuery 3.4.1 is the latest as of this bug report posting. (Bug report numbers 3712 and 4371 also reference previous updates done to the jQuery system as part of SMF 2.1's development).

**Comment by frandominguezl** [comment]
It was updated in #5648 
It wasn't updated in install.php though, so I'm doing it now.

**Comment by SugarD-x** [comment]
Thanks!
