### ISSUE TITLE
Topic listing issues

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#5764]
#### Description
```
Error
Type of error: Critical
Error message:
Wrong value type sent to the database. Integer expected. (page_id)
Function: Display
File: .../Sources/Display.php
Line: 934
URL of page causing the error: http://.../index.php?topic=187.0
Backtrace information
#0: smf_db_error_backtrace()
Called from ...\Sources\Subs-Db-mysql.php on line 204
#1: smf_db_replacement__callback()
Called from unknown on line -1
#2: preg_replace_callback()
Called from ...\Sources\Subs-Db-mysql.php on line 404
#3: smf_db_query()
Called from ...\Sources\Display.php on line 934
#4: Display()
Called from ...\index.php on line 151
```

### Steps to reproduce
0. Turn [**Show most recent posts at the top in topic view**] ON
1. Make a topic with 2 pages
2. Mark the topic unread
3. View the 1st page
4. Go back to the board
5. Click the "New" button
6. Now click on a different page
7. Click on a different page again

```
Wrong value type sent to the database. Integer expected. (page_id)
```

### Environment (complete as necessary)
- Version/Git revision: https://github.com/SimpleMachines/SMF2.1/commit/22482b33dd5704417a989e41311c397d45ee8936
- Database Type: MySQL
- Database Version: 5.7
- PHP Version: 7.3

### Additional information/references
Similar to this issue: #5486
Related PR: #5488

**Comment by SychO9** [comment]
in fact it seems like when the option is turned ON, the order of the posts in topics is very messy, posts from the first page show up on the second and ...etc

**Comment by albertlast** [comment]
Something i guess is missing,
i'm not able to reproduce the error.

**Comment by frandominguezl** [comment]
@albertlast When he says "click on a different page" (points 6 and 7), he means a different page of the same topic. For example if you are in page 2, go to 1 and then back to 2. You'll get the error.

I could replicate the issue.

**Comment by albertlast** [comment]
please try the related pr,
you should got at least a topic wth ~ 3 or 4 pages to test all possibilties.
