### ISSUE TITLE
Undefined variable: _REQUEST

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#5768]
#### Description

Notice
: Undefined variable: _REQUEST in
D:\wamp\www\github2.1\Sources\Display.php
on line
241

Notice
: Undefined variable: _REQUEST in
D:\wamp\www\github2.1\Sources\Display.php
on line
244

Notice
: Undefined variable: _REQUEST in
D:\wamp\www\github2.1\Sources\Display.php
on line
277

Notice
: Undefined variable: _REQUEST in
D:\wamp\www\github2.1\Sources\Display.php
on line
307

### Steps to reproduce
1. open topic message at top of page

### Environment (complete as necessary)
- Version/Git revision: update from 12am eastern time 8/18
- Database Type:
- Database Version:
- PHP Version: 7.1.16

### Additional information/references

**Comment by NanoSector** [comment]
Looks like it expects `$_REQUEST['start']` but that's probably not being set in the URL when that specific link is being clicked.

**Comment by sbulen** [comment]
Illori - are you still seeing these issues?  Can you provide more info on exactly which link is causing the issue?

I cannot replicate this under php7.1 or 5.4.  

The 'start' is part of the URL: ?topic=id_topic._start_ and can be a # or sometimes text, e.g., 'new'.  It's cleaned up in QueryString before use here.

**Comment by illori** [comment]
I found the topic that gave this message before and now it is not. Maybe it
was a one off issue.

**Comment by MissAllSunday** [comment]
@illori were you able to reproduce this issue again after the changes you did?
