### ISSUE TITLE
Undefined variable: GLOBALS

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#5769]
#### Description
Type of error: Cron
8: Undefined variable: GLOBALS http://localhost:8080/github2.1/cron.php
D:/wamp/www/github2.1/cron.php (Line 242) 

### Steps to reproduce
    #0: smf_error_handler_cron()
    Called from D:\wamp\www\github2.1\cron.php on line 242
    #1: cleanRequest_cron()
    Called from D:\wamp\www\github2.1\cron.php on line 104

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version: 7.1.16

### Additional information/references

**Comment by sbulen** [comment]
I cannot reproduce this in php7.1 or php5.4.  

This is old php4 stuff that is simply getting unset/cleaned up.  On the one hand, this is probably unnecessary in the world of php5-7...   OTOH, when you 'unset' a variable that doesn't exist, there is not supposed to be a warning at all.  

The mystery here is why you're getting that error...

**Comment by illori** [comment]
I have not actually used my install in a long time even though I keep it up
to date with github. Maybe just a glitch?

**Comment by sbulen** [comment]
Pretty interesting glitch!  It would sure be interesting to know what happened.  

Some error reporting is different in 7.1.  E.g., evals (used heavily by SMF) behave differently.  So there may be something here.

I'd suggest keeping this (and #5768 ) open for a while to see if anyone else can reproduce.

**Comment by illori** [comment]
i can refresh the home page and watch the error count go up due to this... any idea what could be done to troubleshoot this further?

**Comment by illori** [comment]
corrected my email settings and this error has gone away. does that make sense?

as far as i am aware there was nothing in the email queue.

**Comment by SychO9** [comment]
that's weird, what exactly did you change in your email settings ?

**Comment by illori** [comment]
In php.ini my email address and path to sendmail.

**Comment by MissAllSunday** [comment]
@illori were you able to reproduce this issue again after the changes you did?

**Comment by illori** [comment]
So far no. You can close. I will open a new one if the issue returns.
