### ISSUE TITLE
Tweaking some hooks?

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#5780]
#### Description

1.  integrate_post2_start (Post.php)
     We should include _&$post_errors_ as we don't have any other hook where we could append information to $post_errors **before** these errors are read.

2.  integrate_message_index (MessageIndex.php)
    We don't have a way to add more _where_ statements to $sort_table so if we include new data, pagination won't be loading the correct information and can't behave as expected compared with the old query of 2.0.x

3. loadBoard (Load.php)
   Seems like it's missing a hook? However, with a simple query you can define new $board_info elements depending on where you need this information so I'm not sure about this one.

**Comment by albertlast** [comment]
Two the second point it's okay that is not changeable by hook.
When you change here,
You code must be able to run on big size forum,
And need to support mysql 5.0 till $today and postgres.
When you skilled enough use code replace.

**Comment by DiegoAndresCortes** [comment]
4. integrate_remove_message (RemoveTopic.php)
   This hook is only invoked when the recycle board is disabled, is this correct? If a post goes to recycle bin then there's no hook to handle information

**Comment by MissAllSunday** [comment]
I agree with the change on the second point. Adding the ability to modify the where statement doesn't mean SMF will have problems running on large boards. The ability is there for mod authors to use, we can't guarantee how that option will be used.

**Comment by DiegoAndresCortes** [comment]
Just for keeping track #5870
