### ISSUE TITLE
Helptext of Configuration > Themes and Layout

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#5785]
Ref. #5622
Navigate to Configuration > Themes and Layout. You will find the following:

![image](https://user-images.githubusercontent.com/10365222/63860248-14f88c80-c9a9-11e9-965e-13e16509e0a5.png)

Both helptexts are the same and first of all they don't even belong there. The helptext is meant to be under Themes and Layout > Manage and Install > Settings but I would like to gather opinions about to place the helptext there or just removing the helptext.

Also, what's "Theme Settings" expected to hold? It doesn't look too good.
![image](https://user-images.githubusercontent.com/10365222/63860392-5426dd80-c9a9-11e9-82b7-266db501aec0.png)

**Comment by DiegoAndresCortes** [comment]
On 2.0.x it has this description
" From here, you can view the list of themes you currently have installed, change their paths and settings, and uninstall them. "
