### ISSUE TITLE
errors in querystring.php

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#5787]
#### Description
--Description Here--

### Steps to reproduce
open forum, get errors:

Notice: Undefined variable: _GET in D:\wamp\www\github2.1\Sources\QueryString.php on line 51
--

1 | 0.0156 | 469832 | {main}(  ) | ...\index.php:0
2 | 0.3432 | 3234376 | cleanRequest(  ) | ...\index.php:69

Warning: array_keys() expects parameter 1 to be array, null given in D:\wamp\www\github2.1\Sources\QueryString.php on line 51
--

1 | 0.0156 | 469832 | {main}(  ) | ...\index.php:0
2 | 0.3432 | 3234376 | cleanRequest(  ) | ...\index.php:69
3 | 0.3432 | 3242264 | array_keys (  ) | ...\QueryString.php:51

Notice: Undefined variable: _GET in D:\wamp\www\github2.1\Sources\QueryString.php on line 151
--

1 | 0.0156 | 469832 | {main}(  ) | ...\index.php:0
2 | 0.3432 | 3234376 | cleanRequest(  ) | ...\index.php:69

Fatal error: Uncaught Error: Unsupported operand types in D:\wamp\www\github2.1\Sources\QueryString.php on line 154
--

1 | 0.0156 | 469832 | {main}(  ) | ...\index.php:0
2 | 0.3432 | 3234376 | cleanRequest(  ) | ...\index.php:69

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version: 7.1.16

### Additional information/references

seems odd since this fine has not been modified for months. i cant access the forum at all due to these errors.

**Comment by frandominguezl** [comment]
Open forums, get errors... I honestly can't reproduce the error. Perhaps you should perform a new 2.1 installation.

**Comment by smfbigguy** [comment]
No errors like this on my site at all.

**Comment by illori** [comment]
It started a few days ago. I will try to see what else is going on this
weekend.

**Comment by MissAllSunday** [comment]
How are you running PHP? FPM, mod_php?

**Comment by illori** [comment]
What ever is default in wamp.

**Comment by MissAllSunday** [comment]
Can you be more specific? I don't use wamp myself

**Comment by jdarwood007** [comment]
Can you get us a php info?
That phpinfo should tell you the path to the php.ini.  Can we get that as well?

I suspect something has disabled the _GET and other vars.

**Comment by illori** [comment]
[phpinfo().zip](https://github.com/SimpleMachines/SMF2.1/files/3560979/phpinfo.zip)
let me know if this helps. php.ini included.

**Comment by illori** [comment]
restarted wamp server, errors went away. closing issue.

maybe my wamp install is going wonky

**Comment by jdarwood007** [comment]
I can't see anything wrong with your configs.  I wonder if you are triggering this bug: https://bugs.php.net/bug.php?id=73554

**Comment by illori** [comment]
Sounds like it. I could switch to 7.2.4 if SMF 2.0 supported it.
