### ISSUE TITLE
Previewing a Poll thread results in error message

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#5792]
#### Description
[Original report here](https://www.simplemachines.org/community/index.php?topic=569500.0)

### Steps to reproduce
1. In a board, click "new poll"
2. add some stuff to the input fields (subject, question, two or more options, message text) so you have a valid poll and don't get any other errors when previewing
3. click "preview"
4. Admire the error message above the input area:

> The message has the following error or errors that must be corrected before continuing:
> You must have at least two choices!
> 

### Environment (complete as necessary)
- Version/Git revision: 2.1rc2
- Database Type: postgres (but probably any)
- Database Version: 9.4.21 (debian)
- PHP Version: 5.6.40 (debian)

**Comment by SychO9** [comment]
Looking at the code, poll options were never handled:
https://github.com/SimpleMachines/SMF2.1/blob/f9bd04630420e687b6158cea2bfe00d6f257d479/Themes/default/scripts/script.js#L1834-L1844
