### ISSUE TITLE
Progress markup doesn't... progress

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#5795]
#### Description
I briefly mentioned this back in #5608, and it still applies to the recent Github version: When installing, the steps to the top right of the webpage don't change along with the URL; even though I'm at `/install.php?step=[1-5]`, the markup is always stuck at step 1.

### Steps to reproduce
1. click through the web installer
2. notice step 1 is permanently highlighted

### Environment (complete as necessary)
- Version/Git revision: recent Github ("release-2.1" branch) HEAD (6ba1e53c0b65edb202fa17b9dc0088f610fdbfd8, 2019-09-01)
- Database Type: postgres
- Database Version: 9.4.22
- PHP Version: 5.6.40-0+deb8u4

**Comment by sbulen** [comment]
Confirmed - this is true for both MySQL & PG...  A minor graphics issue, it doesn't affect the installation.
