### ISSUE TITLE
preview didn't support mb4 chars

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#5804]
#### Description
When the preview of replay used,
the mb4 char get filtert out,
when preview of quickreplay is used everything works fine

### Steps to reproduce
1. 🤔
2. 

### Environment (complete as necessary)
- Version/Git revision: head
- Database Type: pg
- Database Version: 11
- PHP Version: 7.3

### Additional information/references
https://www.simplemachines.org/community/index.php?topic=569620
did not testet if the issue exists with mysql.

**Comment by frandominguezl** [comment]
Issue confirmed with MySQL as well.
