### ISSUE TITLE
Incorrect DB comparison / value of $smcFunc['db_title']

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#5817]
#### Description
A couple of places in the smileys code check against $smcFunc['db_title'] to see if it contains 'MySQL' so they can use a more specialised comparison.

Unfortunately, Subs-Db-Mysql.php lists itself as MySQLi so that comparison never plays out.

See https://github.com/SimpleMachines/SMF2.1/blob/527a3ea50166b39deb9e03303fead37cd3c9135f/Sources/ManageSmileys.php#L629 for example.

Either the entire edge case should be removed (since it currently does nothing special) or $smcFunc['db_title'] should probably return 'MySQL' instead.

**Comment by sbulen** [comment]
We should also consider mariadb & percona.

**Comment by albertlast** [comment]
Nope

**Comment by sbulen** [comment]
I meant to test & confirm that they didn't return something that would break it as well.  

But Arantor is correct, it's hard coded to a strange value at the moment:
https://github.com/SimpleMachines/SMF2.1/blob/c6b7a9f657c914ddd4786915d67f0cdf3f7482d1/Sources/Subs-Db-mysql.php#L55

**Comment by albertlast** [comment]
It's not strange,
it's the driver which is used.
Image smf would use pdo,
than would be the name pdo_mysql.

**Comment by Arantor** [comment]
I’m not disputing the value, nor is it strange, but it’s currently the basis of a comparison that is wrong.
