### ISSUE TITLE
Child boards with new posts: presentation and PHP

### ISSUE THREAD

**Issue by StealthWombat** [SimpleMachines/SMF#5818]
Ok, two separate things here. First one is the current presentation for the child board new post indicators. They're a bit washed out and bleh, IMO. Would be hard to read for some people too, if they were new to SMF. The current ones are shown in the top row of the first attached image.

My suggestion is shown in the second row of the first image. I think this is far more legible, and a much better aesthetic match for the board icons at the left side, and better for positioning. It can also be done with a bit less code.

```
/* The "new" button */
.new_posts {
	display: inline-block;
	position: relative;
	top: -2px;
	padding: 0 4px;
	background: linear-gradient(#f97b00,#884d00);
	color: #fff;
	font: 9px/15px verdana, sans-serif;
	font-weight: 700;
	border-radius: 2px;
	opacity: 0.8;
}
.new_posts:hover, .new_posts:focus {
	text-decoration: none;
	opacity: 1;
}
``` 
Note that I removed the transition, as I think in this instance it is not worth the bytes. I also added a minor tweak to BoardIndex.template.php and MessageIndex.template.php. Since you are always going to want a slight gap between the "New" thingy and the board name, I think this is a situation where it makes sense to add a non-breaking space to the HTML. Keeps the CSS simpler, works for any language, and even the most persnickety themer is unlikely to mind.

```
			if (!$child['is_redirect'])
				$child['link'] = '' . ($child['new'] ? '<a href="' . $scripturl . '?action=unread;board=' . $child['id'] . '" title="' . $txt['new_posts'] . ' (' . $txt['board_topics'] . ': ' . comma_format($child['topics']) . ', ' . $txt['posts'] . ': ' . comma_format($child['posts']) . ')" class="new_posts">' . $txt['new'] . '</a>&nbsp;' : '') . '<a href="' . $child['href'] . '" ' . ($child['new'] ? 'class="board_new_posts" ' : '') . 'title="' . ($child['new'] ? $txt['new_posts'] : $txt['old_posts']) . ' (' . $txt['board_topics'] . ': ' . comma_format($child['topics']) . ', ' . $txt['posts'] . ': ' . comma_format($child['posts']) . ')">' . $child['name'] . '</a>';

```
![2_1_child_boards_new](https://user-images.githubusercontent.com/4676512/66091687-277b6c80-e5cc-11e9-93e6-4c77d6aa6546.jpg)

-----------------------------------------------------------------------
So that's one thing. The other thing is the content of the title attributes.

When the child board has new posts the "New" thingy links to ?action=unread;board=** while the board name obviously just links to ?board=** yet they both have the same title content, which implies they both do the same thing. I think this is a GUI fail, and it would be better if the child board link always had the total post and topics, and left the "New" count to the "New" thingy title. That way they're not claiming to do the same thing and trying to trick newbies. It'd also save you a ternary in the template, which is not such a bad thing either,
  
![2_1_child_boards_PHP](https://user-images.githubusercontent.com/4676512/66091693-29453000-e5cc-11e9-901f-2628f7415f79.jpg)

**Comment by DiegoAndresCortes** [comment]
I don't mind the second thing as the new button would be the interesting part for a newbie, they wouldn't really pay much attention if the board title says the same or similar.
Does anyone else have an opinion on that, I find it weird having just the post and topic count in the title because normally if there are no new posts it says that instead of "new posts".
I tried moving it around but didn't like anything in particular besides the current state.
