### ISSUE TITLE
Undefined index: can manage boards

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5822]
#### Description
When attempting to reproduce #5821 , whenever an email was sent I received :  8: Undefined index: can_manage_boards.  This was produced later, at mailing time, by the cron.  

### Steps to reproduce
1. User notifications were setup by user to receive emails immediately.  
2. Admin replied to a topic the user was watching.  
3. Wait for the email to go...

### Environment (complete as necessary)
- Version/Git revision: Current as of today
- Database Type: MySQL
- Database Version: 5.7
- PHP Version: 5.6

### Additional information/references
![image](https://user-images.githubusercontent.com/23568484/66286347-ea420380-e885-11e9-9266-f312647ebbb4.png)

**Comment by live627** [comment]
So here's what's happening:

https://github.com/SimpleMachines/SMF2.1/blob/5194bb8a4c5faec8273614382b9a6c3ffbe097f1/Sources/tasks/CreatePost-Notify.php#L225-L227

`$user_info`  is never set in `cron.php`, so the above code will never evaluate.

https://github.com/SimpleMachines/SMF2.1/blob/5194bb8a4c5faec8273614382b9a6c3ffbe097f1/Sources/tasks/CreatePost-Notify.php#L229-L236

This confuses  `build_query_board()` into thinking that SMF is running normally, hence it expects a fully populated `$user_info`.

https://github.com/SimpleMachines/SMF2.1/blob/5194bb8a4c5faec8273614382b9a6c3ffbe097f1/Sources/tasks/CreatePost-Notify.php#L266-L273

Therefore this `isset()` block will never execute. And I'm not sure why the assignment to `null` didn't work -  perhaps the garbage collector didn't kick in, or maybe there is some undefined behavior here.

Note: no  testing was done to make this post.
