### ISSUE TITLE
admin/viewmembers next/prev missing

### ISSUE THREAD

**Issue by bobo3k** [SimpleMachines/SMF#5831]
#### Description
When in admin/members/view all members
Only the first 30 members are shown (as set in settings) but no next/prev buttons are available

### Steps to reproduce
0. you need more than 30 members :)
1. login as admin
2. click on members/views all members
3. no next/prev button(s)

**Comment by sbulen** [comment]
I can't reproduce this.  I tested on WAMP, PHP 5.6 & 7.2, today's GitHub version.

On the first page, only the next button is displayed, that's the right arrow here:
![image](https://user-images.githubusercontent.com/23568484/67149873-80eac900-f265-11e9-823f-b39a563ba1e3.png)

**Comment by vort7u** [comment]
I can't reproduce it also on RC2.

**Comment by bobo3k** [comment]
well, in that case it might be my fault... I'm creating a small script based on smf_api2.0 since there is no 2.1, and I think I removed a stats line on member creation that *might* be used a count to get the next/preb pages....
Feel free to mark is as closed since I'm the only one with the issue and I used a "dodgey" API to create my members ;)
sorry for the "issue" ...

**Comment by sbulen** [comment]
OK - thanks for checking!

**Comment by bobo3k** [comment]
I confirm, it was due to my "bridge"... I didn't add the settings "stats" data in the DB after registration.
The cache has somehow been emptied and this morning everything went fine... 
I added the stats update in the member's registration process & now it's all fine :)
Thanks again for the checkup - and sorry for the wrong alert ;)
