### ISSUE TITLE
Calendar events should use forum TZ

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#5833]
#### Description
[Original thread here](https://www.simplemachines.org/community/index.php?topic=570135.0)
When creating calendar events, the timezone dropdown seems to always default to UTC. A better default would be server TZ + forum offset (or at least the server TZ).

### Steps to reproduce
1. Set forum to any server TZ and forum offset
2.  Begin creating a calendar event and notice "Time zone" is set to UTC

### Environment (complete as necessary)
- Version/Git revision: 50dc25705dfdf56bada445704f6295163fa670e8 from 2019-10-10
- Database Type: postgres (the original reporter probably has MySQL)
- Database Version: pg9.4
- PHP Version: 5.6.40ish

**Comment by illori** [comment]
i have an old but updated version of 2.1 [updated daily from github]. server time zone is set to america/new york. when i go to create a calender event the time zone is showing correctly. database is mariaDB

i tested again, set the overall time offset to 1 hours, went back to create an event and it was the correct time zone and +1 hour in the displayed time.

**Comment by m4z** [comment]
Interesting. I tested with three (postgres) forums on two servers:
* forum 1 (server 1, real server TZ is UTC): SMF (GH version from 2019-10-10) has sTZ UTC + forum offset 2. Calendar defaulted
* forum 2 (server 1, real server TZ is UTC): SMF (nightly from ~2019-10-10) has the install default(?) TZ of Atlantic/Azores, plus and offset of 0.25 or so
* forum 3 (server 2, real server TZ is UTC): SMF (nightly from ~12 hours ago) has the Pacific/Funafuti TZ and no offset

In all three cases, calendar events default to UTC.

**Comment by illori** [comment]
but when you look at the time is it also in UTC? mine showed the eastern time zone but the actual time was off set by the time specified.

**Comment by m4z** [comment]
Do you mean the forum time or the event time? Interestingly, the event times aren't displayed consistently:
* forum 1: UTC +2 => So.20.10.2019, 22:22 – 23:22 (20:22 – 21:22 UTC)
* forum 2: Azores +1 => Oct 20, 2019, 9:25 PM – 10:25 PM (8:25 PM – 9:25 PM UTC)
* forum 2: Azores +0.25 => Oct 20, 2019, 8:42 PM – 9:42 PM (8:27 PM – 9:27 PM UTC)
* forum 3: Funafuti +0 => Oct 21, 2019, 8:29 AM – 9:29 AM UTC

The first of the has the correct time. The second/third too, if my geography isn't off (I played with the offset in that forum). The third is... strange, Funafuti is near Australia.

**Comment by illori** [comment]
when you open the screen to make the event, it shows the correct time zone and then the time shown is offset by the amount set in the admin panel. given i have not tested it much myself. i have *not* actually created the event, is that when you are running into the issue?

**Comment by sbulen** [comment]
The timezone in the dropdown is defaulting to your USER selection under Profile | Look and Layout.  

Since all the servers I've ever worked on have stored datetime in UTC, I have always had my 'server' setting at UTC, 0 offset, and it works fine (where the server is stored is irrelevant...).  If you want to SEE local time, you have to set that in your profile.  The calendar defaults to your user setting, which is good.

Given this, I'm wondering if we should close this??? I think it's working OK.  Calendar events are consistently stored in UTC, and displayed properly per user settings.  

(I am going to log a separate one, though.  Testing this just now, for me the user-selected timezone in Look & Layout is saved properly, but not displayed properly when you go back in to change it...)

**Comment by m4z** [comment]
Sigh, this just got more complicated.
* (as stated above,) my server is set to UTC, my SMF setting for server time is set to UTC, with a forum offset of 2.
* when my user uses the default personal TZ of "-----", which is either UTC or "(forum default)" which probably is UTC+2 in my case, the overall forum time is correct but the default calender TZ is wrong (UTC)
* when my user account uses the "correct" personal TZ of CEST, the overall forum time is off by +2 hours, and calendar events default to my personal setting of CEST (but the beginning and end times default to 2 hours ago (== UTC?)), and when I create an event, the time event time displayed is totally incorrect: the event was created for 06:35-07:35 CEST, and the time displayed is "Mo.21.10.2019, 8:35 – 9:35 (6:35 – 7:35 CEST)"
  * the first time range actually corresponds to my correct CEST current time (I'm really not sure at this point what it's supposed to represent, the personal TZ + the forum offset? makes no sense), the latter in parentheses should maybe be UTC

(The weird TZ string [for the calendar event] might be another bug, because it is similar what I configured for my time string (`%a., %d.%m.%Y, %H:%M`), but not completely. And the overall forum time is displayed correctly according to my string.)

**Comment by m4z** [comment]
> (I am going to log a separate one, though. Testing this just now, for me the user-selected timezone in Look & Layout is saved properly, but not displayed properly when you go back in to change it...)

For me it is displayed correctly. 😕 🤣

**Comment by sbulen** [comment]
The reason the users time is off by two hours is because you put 2 in the offset.  That's all that does, is add that value to the time.  If you don't want to add anything to the time, leave the offset at 0.

Why did you put 2 in the offset?

**Comment by m4z** [comment]
Because my server uses UTC, but the server and users are located in CET/CEST. So to get the default forum time correct, I have to add the offset of 2 (CEST) or 1 (CET).

**Comment by sbulen** [comment]
The offset is a strange thing - it does exactly what says.  It adds that to the time.  The reason everybody is off by 2 is because you told it to add 2 to everything.

**Comment by m4z** [comment]
So I'm just doing it wrong/misunderstanding that feature, and there is no possibility to provide a reasonable default for my users when server TZ and user TZ are different?

**Comment by sbulen** [comment]
What I would do is make the tz visible upon registration - under profile fields.  Also, there is in fact a general setting to specify "show timezones from these countries first".   Put user configs in the hands of the user & point them in the right direction...

**Comment by sbulen** [comment]
m4z - OK to close this?

**Comment by m4z** [comment]
Sorry, busy AF...

A quick test says "maybe"; I removed the offset, have server TZ on UTC, user setting on CEST. When I create events now, the TZ is fine, but the default event start and end times are always 2 hours in the past (I guess the current _UTC_ time is filled in, not the current time according to the user TZ), so I have to adjust _them_ manually.
So yeah, I guess the problem is replaced by another one. 😜

**Comment by sbulen** [comment]
What is YOUR tz in your profile?

For times to show as the same, the two users should be on the same tz.

**Comment by m4z** [comment]
Sorry, confusing phrasing... when talking about "the user TZ", I was always talking about my own (admin) user account (as opposed to the global, ACP settings). [So, my user setting is CEST, no other user(s) involved.]

**Comment by sbulen** [comment]
Gotcha.  THAT, I verified.   The 'default' start time for new events is the current system time, in UTC - and it shows that alongside your timezone...  

I would suggest closing this one & opening a new one, so the comment history focuses on the new issue.  Make sense?

**Comment by sbulen** [comment]
Closing this one out as discussed above.

Logged #5842
