### ISSUE TITLE
Typo fix 2 lines

### ISSUE THREAD

**Issue by Pipke** [SimpleMachines/SMF#5835]
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/languages/Profile.english.php#L337-L338

Why is there the character ' after the s from users?

**Comment by sbulen** [comment]
It's plural possessive, & "users" ends in s.   

LGTM.  Might he a problem only if you find it referring to a single avatar or signature in usage.

**Comment by Pipke** [comment]
User's guide: A guide belonging to one user.

Users' guide: A guide belonging to all the users.

Thought first it was wrong, i get it now, english is not my native language, you can close this.

Tip: SMF could also use **Do not display user avatars** instead of **Don't show users' avatars**.

**Comment by sbulen** [comment]
Thanks for participating!  I'll close this out.
