### ISSUE TITLE
Database Error: Data too long for column 'avatar'

### ISSUE THREAD

**Issue by Pipke** [SimpleMachines/SMF#5838]
#### Description
errors from log:
Error
Type of error: Database
Error message:
Database Error: Data too long for column 'avatar' at row 1
File: E:/XAMPP/htdocs/rc2/Sources/Subs.php
Line: 426
URL of page causing the error: http://localhost/rc2/index.php?action=profile;area=forumprofile;u=1
Backtrace information
#0: smf_db_error()
Called from E:\XAMPP\htdocs\rc2\Sources\Subs-Db-mysql.php on line 489
#1: smf_db_query()
Called from E:\XAMPP\htdocs\rc2\Sources\Subs.php on line 426
#2: updateMemberData()
Called from E:\XAMPP\htdocs\rc2\Sources\Profile.php on line 701
#3: ModifyProfile()
Called from E:\XAMPP\htdocs\rc2\index.php on line 155

### Steps to reproduce
1. Forum Profile
2. Personalized picture / Specify avatar by URL
3. Google image, right click image get url ie: https://www.google.com/imgres?imgurl=http%3A%2F%2Fwww.google.com%2Flogos%2Fdoodles%2F2015%2Fgoogles-new-logo-5078286822539264.3-hp2x.gif&imgrefurl=http%3A%2F%2Fwww.google.com%2Fdoodles%2Fgoogles-new-logo&docid=hWfwYn6E9UL_wM&tbnid=wNsZSiIPru5UcM%3A&vet=10ahUKEwj62uXBvbDlAhWQfZoKHcR7DLcQMwhRKAEwAQ..i&w=881&h=400&bih=767&biw=1600&q=google%20image&ved=0ahUKEwj62uXBvbDlAhWQfZoKHcR7DLcQMwhRKAEwAQ&iact=mrc&uact=8
4. Paste the url in input field, hit enter.

### Environment (complete as necessary)
- Version/Git revision: 2.1 RC2
- Database Type: MariaDB
- Database Version: 10.1.38-MariaDB - mariadb.org binary distribution
- PHP Version: Apache/2.4.38 (Win32) OpenSSL/1.1.1a PHP/7.3.2

### Additional information/references
user must get a nice error: `fatal_lang_error('your image url is way to long, please try another one or similar text', false);` message instead of this

googled the error, it is has reported earlier for smf 2.0 here: https://www.simplemachines.org/community/index.php?topic=568670.0 seems to be unnoticed

**Comment by albertlast** [comment]
Well i see no error here,
since it's got defined length,
personaly i would define this unlimted...
But it work how it's designed.

**Comment by sbulen** [comment]
Verified.  The problem is simply that the error is not properly trapped & displayed.  We just need to do that...

E.g. this is what the user sees:
![image](https://user-images.githubusercontent.com/23568484/67361006-4fe7ee00-f51c-11e9-83d6-dd755d343143.png)
