### ISSUE TITLE
BBC and smileys are not honored in subject lines, in previews or posts.

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5839]
#### Description
BBC and smileys are not honored in subject lines, in previews or posts.

### Steps to reproduce
![image](https://user-images.githubusercontent.com/23568484/67359228-9424bf80-f517-11e9-9ad6-38deb387cb23.png)

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: pg & mysql

### Additional information/references

**Comment by VBGAMER45** [comment]
I think that is by the design at least for the subject lines

**Comment by DiegoAndresCortes** [comment]
Yeah I don't think subject is supposed to parse that stuff.
At least on 2.0 it doesn't do that if I'm not mistaken

**Comment by sbulen** [comment]
Correct, same behavior in 2.0.x.  

Still seems like an odd gap to me, though.

**Comment by VBGAMER45** [comment]
It can get out of hand though with all the BBC code options. I could see maybe limited support for bold,italic, underlines.  Smileys would be tough since there could be custom smileys of any size.

**Comment by sbulen** [comment]
Good points...

**Comment by sbulen** [comment]
OK, @VBGAMER45 , upon further thought, you are correct.  I'll close this out...
