### ISSUE TITLE
avatar not able to be clicked

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#584]
when you view a message from a user with an avatar, if you want to click on their avatar you are unable due to the superfish menu that always overlaps the avatar.

IMO the avatar should be moved out of the h4 block that makes the superfish menu show. there may be cases people want to link to someone's avatar or whatever and can not in 2.1

if the avatar is moved out of the h4 [the persons name is the h4] it should still have a link back to the users profile.

this applies to messages in a board as well as PMs

**Comment by Oldiesmann** [comment]
If people want to link someone's avatar to something, it's easy enough for them to edit the templates to do that. I like the current functionality.

**Comment by illori** [comment]
but the users of the forum can not, we need to think about all the users and not just ourselves. there are times people try to examine a users avatar and the way it is with the dumb drop down you cant right click it or anything as the drop down is always in the way.

**Comment by Kindred-999** [comment]
Although I understand both sides (and I am on record as saying that I despise the hover pop-ups that we are using in 2.1), I think, in this case, Illori is correct - although for the wrong reason.
Images shoudl not, in general, be in heading tags. I can see not good reason to include the user's avatar within the H4 tag. Providing a link back to the profile would be a theme thing and could be included int he default them (or not). (I'd like to se eit, but I don't view that as important as moving the image out of the heading tag.

**Comment by Arantor** [comment]
How did it get into the h4 in the first place? It certainly wasn't in there in 2.0 (mostly because there was other stuff there as well)

**Comment by illori** [comment]
it has been like this since the new theme was made.
