### ISSUE TITLE
 Youtube bb and center alignment 

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5843]
#### Description
Center alignment doesn't work when there is a YouTube bbc used

### Steps to reproduce
1. Add a youtube video using the bbc
2. Select the string & center it - it remains left justified

### Additional information/references
![image](https://user-images.githubusercontent.com/23568484/67528750-1247aa00-f66f-11e9-8919-52bda616e204.png)

**Comment by MissAllSunday** [comment]
Fir this I would suggest making it centered by default, that's how I got it on my own mod and no one has ever complained about it.
