### ISSUE TITLE
Spellcheck not showing

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#5847]
#### Description
My version of SMF is not that old, it was installed Oct 16th from GH. For some reason Spellcheck only shows up on quick reply. Please see this topic on SM's for a better description:

https://www.simplemachines.org/community/index.php?topic=570230.0

And this post for screenshots:

https://www.simplemachines.org/community/index.php?topic=570230.msg4035696#msg4035696

### Steps to reproduce
1.  Enable spellcheck
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by smfbigguy** [comment]
This is still an issue. Spellcheck shows on quick reply only

**Comment by dragomano** [comment]
Do we need this feature at all? It seems all modern browsers have built-in spell checking, for most languages.

**Comment by smfbigguy** [comment]
I always found it handy, but that's just my opinion.
