### ISSUE TITLE
Server timezone setup language very confusing

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5850]
#### Description

The timezone labels & online help are very confusing; I don't think they are even close.  

_Current labels & help:_
"Server timezone" help says "The server time zone tells PHP where your server is located. You should ensure that this is set correctly, preferably to the country/city in which the server is located. You can find out more information on the PHP Site."

And..

"Overall time offset" help says "Not all forum administrators want their forum to use the same time zone as the server upon which it is hosted. Use this setting to specify the time difference (in hours) between the server time and the time to be used for the forum. Negative and decimal values are permitted."
With a sub-label of: "(added to the member specific option)"

_I suggest something along the lines of:_
"Forum default timezone" help should be "This is the default timezone used for the display of times throughout the forum."

"Overall time offset" help should be "Some old systems do not store times in UTC.  Use this setting to specify the time difference (in hours) between the server time and the forum default timezone. Negative and decimal values are permitted."
& get rid of the sub-label...

![image](https://user-images.githubusercontent.com/23568484/67829857-dd37bf00-fa95-11e9-85a6-f5e4070e106b.png)

### Additional information/references
https://www.simplemachines.org/community/index.php?topic=570135.0

**Comment by m4z** [comment]
Also, the "server timezone" could be described in terms of what the server is configured to use, and not its location: especially using UTC is a common IT practice all around the world.

**Comment by sbulen** [comment]
m4z - above, I intend to get rid of the "server timezone" label altogether & change it to "forum default timezone".  

You are correct, basically everything is really in UTC under the covers.  The way things work in 2.1, I believe the only usage for the "server offset" would be for that odd egg server out there that isn't on UTC.
