### ISSUE TITLE
Incorrect permissions on Package Manager dirs result in "empty" page

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#5856]
#### Description
When the permissions on `Packages/temp/` (and/or files/dirs below) are incorrect, the package manager behaves strangely when trying to uninstall a mod (I originally mentioned this [here](https://www.simplemachines.org/community/index.php?topic=569588.msg4030864#msg4030864)): In the uninstall screen, a(n error?) message flashes for a split second, and then I only see the dialog for providing my FTP data to fix the file( permission)s.

### Steps to reproduce
I removed a smiley set from the Smileys section in the Admin menu ([original post](https://www.simplemachines.org/community/index.php?topic=569588.msg4030802#msg4030802)); SMF reminded me that the files weren't deleted, only the set in the forum, hence (because I had forgotten it was installed via a package; it was late) I happily removed my Smileys/fugue-icons/ dir. Then I remembered, and tried to uninstall the package, but of course it failed because the dir was missing. I mkdir'ed an empty dir back and now the uninstaller (probably) complained about my missing uninstall files (`uninstall.php` and `smf21_uninstall.php`, as defined by the mod). In the uninstall screen, a message that I couldn't read flashed for a split second, and then I only saw the dialog for providing my FTP data (for an FTP server that I don't run) to fix the file( permission)s.

### Environment (complete as necessary)
- Version/Git revision: GH version of ~2019-10-10
- Database Type: Postgres but probably any
- Database Version: 9.6ish
- PHP Version: 5.6ish

**Comment by BrickOzp** [comment]
I have tried to reproduce this on latest.

1. Install https://custom.simplemachines.org/mods/index.php?mod=2866
2. Delete both Dizzy smiley sets via the smiley editor
3. Remove smiley sets folders via ftp. /Smileys/dizzy*
4. Uninstall package.
5. An error is shown that files are missing, but package can be uninstalled correctly.

I think this is no longer a problem

**Comment by MissAllSunday** [comment]
@m4z  Can you please verify that this issue is no longer a problem?

Regardless, moved to Final

**Comment by Sesquipedalian** [comment]
Closed since it seems that this issue cannot be reproduced and we have had no further word to say otherwise.

@m4z, if this issue is still occurring for you, please let us know so that we can take another look at it.
