### ISSUE TITLE
Youtube Videos not working

### ISSUE THREAD

**Issue by ivanabobs** [SimpleMachines/SMF#5859]
youtube videos not working when embeding in new response and also in old post is anyone else experiencing this problem? a fix? . Thanks.

**Comment by smfbigguy** [comment]
My youtube works great.

**Comment by MissAllSunday** [comment]
Is this for SMF 2.1? Can you provide steps to reproduce this issue. perhaps some screenshots as well.

**Comment by ivanabobs** [comment]
Hello i'm sending you a video better i have no idea how to solve it .
Thanks,
Sent using EngageBay <https://eblink1.com/website>

**Comment by MissAllSunday** [comment]
We can’t see email attachments, please pose directly on GitHub if you want to attach a video, also, is this for SMF 2.1?

**Comment by ivanabobs** [comment]
sorry you can see it here: https://youtu.be/W-6hQ49gsZM i think it's 2.09

**Comment by m4z** [comment]
What is your "frame security" setting? (Admin → Maintenance → Server Settings → Security → "Frame Security Options")
I guess this might effectively interfere with the HTML code that is produced by the `[youtube]` BBCode (similar to #5848).

**Comment by MissAllSunday** [comment]
It looks like you're using SMF 2.0.x, this issue tracker is for SMF 2.1 alone. Please use the SMF's support board for assistance : https://www.simplemachines.org/community/index.php?board=59.0

Find the mod's support topic and post there.
