### ISSUE TITLE
Calendar dropdowns - both date & time dropdown update the date field

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5862]
#### Description
Calendar dropdowns - both date & time dropdown update the date field...

### Steps to reproduce
![image](https://user-images.githubusercontent.com/23568484/68443633-61bac980-0189-11ea-93fd-a8573b4861e1.png)

### Environment (complete as necessary)
- Version/Git revision:  Current
- Database Type:  MySQL
- Database Version:  5.7
- PHP Version:  7.1

**Comment by Sesquipedalian** [comment]
Someone must have messed with the ids or classes on the input fields. The time picker script uses those to determine which fields to attach the time picker to.

**Comment by sbulen** [comment]
@Sesquipedalian - did #6040 address this?

**Comment by Sesquipedalian** [comment]
Yes, it did.
