### ISSUE TITLE
cron.php doesn't initialize smileys and attempts to use SERVER_PROTOCOL

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#5868]
#### Description
So I'm trying to use my crontab to run cron.php and ran into some issues:
```
Type of error: Cron
8: Undefined index: smiley_set
http://(redacted).de/cron.php
(redacted)/Sources/Subs.php (Line 3011( & 3024 & 3035 & 3037))
```
```
The database value you're trying to insert does not exist: smiley_set<newline>Function: parsesmileys
(redacted)/Sources/Subs.php (line 3263)
```
```
8: Undefined index: SERVER_PROTOCOL
(redacted)/Sources/Subs.php (line 7076)
```

Original threads (linking to Arantor's summaries near the ends of both threads):
* https://www.simplemachines.org/community/index.php?topic=569827.msg4036609#msg4036609 (problems caused by the normal javascript-based scheduled tasks)
* https://www.simplemachines.org/community/index.php?topic=570396.msg4036612#msg4036612 (crontab problems)

### Steps to reproduce
1. run 2.1 between rc2 and the GH version of 2019-10-10
2. patch [this](https://github.com/SimpleMachines/SMF2.1/pull/5222/commits/6e288d5f78e954aacbceb629ce3346d8a1b26cd9) postgres-related bug
3. enjoy the spam 😉 

### Environment (complete as necessary)
- Version/Git revision: GH version of 2019-10-10
- Database Type: Postgres
- Database Version: 9.6ish
- PHP Version: 5.6ish

**Comment by live627** [comment]
@m4z in ./sources/tasks/CreatePost-Notify.php , find

				'time_format' => empty($data['time_format']) ? $modSettings['time_format'] : $data['time_format'],


with

				'time_format' => empty($data['time_format']) ? $modSettings['time_format'] : $data['time_format'],
				'smiley_set' => $modSettings['smiley_sets_default'],

This is a temporary untested fix.

This will enable smileys in alerts I think, but only the forum default set.

**Comment by m4z** [comment]
This seems to work, thanks! (I even received a notification from 3 months ago that was apparently stuck  somewhere.)
