### ISSUE TITLE
Logout should have a prompt screen

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#5869]
#### Description
This came up while looking into the integration issue between MediaWiki and SMF.  PHP 7.2 has also introduced a session_start issue which has made it impossible for us in the integration to step into SMF session and modify session data or obtain the session info to allow redirects or logouts. Redirects issue will be resolved in a pr that allows us to as safely as possible issue a redirect from outside SMF.  I've got an idea in mind that will fix this.

We should allow at the logout screen to prompt to logout.
- This should trigger only when action=logout is called with no session validation.
- If the session validation is invalid, the standard invalid session alert should trigger.
- The page should simply ask for confirmation to log out.  Clicking confirm should just be the logout action with the session validation.
- Setup this way should prevent backwards compatibility breakage.

### Additional information/references
https://github.com/SimpleMachines/smf-mw-auth/issues/11#issuecomment-552227164
https://github.com/elkarte/Elkarte/issues/3368

**Comment by SpacePhoenix** [comment]
This might be the session_start() issue: https://stackoverflow.com/questions/48245296/php-custom-session-handler-problems-php-7-1/48245947#48245947
