### ISSUE TITLE
Search.php: 8: Undefined variable: approve_query

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#5877]
#### Description
Originally reported [here](https://www.simplemachines.org/community/index.php?topic=570651.0): Since ~2019-10-10, the GH version produces the following errors when using the search function:

```
Code: [Select]
Type of error: Undefined
8: Undefined variable: approve_query
 http://localhost:8080/smf/index.php?action=search2
 C:/wamp64/www/smf/Sources/Search.php (Line 1715)

Type of error: Undefined
8: Undefined variable: approve_query
 http://localhost:8080/smf/index.php?action=search2
 C:/wamp64/www/smf/Sources/Search.php (Line 1828)
```
These lines were last changes 6 months ago ([L1715](https://github.com/SimpleMachines/SMF2.1/blame/0009c2d072ef77f8f8f869def5986d7a9449e2b1/Sources/Search.php#L1715), [L1828](https://github.com/SimpleMachines/SMF2.1/blame/0009c2d072ef77f8f8f869def5986d7a9449e2b1/Sources/Search.php#L1828)), but I didn't see this before 2019-10-10 in my installs (but I didn't explicitly test the search function and my users don't seem to use it much). Also just confirmed this in a freshly updated nightly build from 15 minutes ago.

### Steps to reproduce
1. Install from/update to a recent version 
2. Search something (posting from entire forum or current board, or a member) in the top-right search bar
3. if the search has no result, only the first error occurs; if it has one, both appear

### Environment (complete as necessary)
- Version/Git revision: HEAD
- Database Type: any? (confirmed on psql, assume sm.org reporter uses mysql)
- Database Version: any?
- PHP Version: any?

**Comment by m4z** [comment]
(btw: I also suspect this is triggered somehow by mod pkg install/uninstalls and once directly after the update, but not sure.)

**Comment by sbulen** [comment]
I cannot reproduce this with vanilla current code.  More information would be helpful.

**Comment by live627** [comment]
@sbulen might need to disable post moderation

**Comment by m4z** [comment]
This still happens with the version from this weekend, but now in [L1807](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Search.php#L1807) and [L1920](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Search.php#L1920).

**Comment by sbulen** [comment]
m4z - did you test live's PR?  Connected to this issue?
#5931

**Comment by m4z** [comment]
No, sorry. Didn't have time until my update this weekend. Just wanted to confirm it still happens.

**Comment by sbulen** [comment]
Don't worry - I was able to confirm the issue, test the PR & it is merged now.  

THANX!
