### ISSUE TITLE
PM notification email: recipient redundancy

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#5878]
#### Description
[Originally reported here](https://www.simplemachines.org/community/index.php?topic=567982.0): In notification emails with two or more senders the username is included (because TOLIST already contains all user names) even though the user was already addressed as "you":

```
You and {TOLIST} have just been sent a personal message by {SENDER} on {FORUMNAME}
```

### Steps to reproduce
1. Look at `Themes/default/languages/EmailTemplates.english.php`:`$txt['new_pm_tolist_body']`

### Environment (complete as necessary)
- Version/Git revision: HEAD
- Database Type: postgres but probably any
- Database Version: 9.6 but probably any
- PHP Version: 5.6 but probably any

### Additional information/references
This might be a good first issue; I assume there's some kind of PHP filter function to remove the addressee's username.

**Comment by illori** [comment]
is this sending the username or the display name? it should send the display name for security as the username does not need to be the same.

**Comment by m4z** [comment]
I don't know which is used. I kept the original phrasing and didn't think about it. (And even if I had, I wouldn't know. 😇 )

**Comment by live627** [comment]
@illori it is the display name
