### ISSUE TITLE
disable superfish menu per theme

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#588]
currently the call for smf_jquery_plugins.js is in load.php. it says 

``` php
loadJavascriptFile('smf_jquery_plugins.js', array('default_theme' => true));
```

according to what i see, there is then no way to disable the superfish menu that is used in the default theme in 2.1 unless you edit theme.js. i dont think we should require theme authors to edit theme.js to remove the call to superfish

**Comment by Oldiesmann** [comment]
Unless we move the call to superfish to a template file (which makes no sense), there is no other way to do it. I think it's fine the way it is.

**Comment by illori** [comment]
so there would be no way to have a per theme option to enable/disable superfish like we have other options?

**Comment by emanuele45** [comment]
theme.js is there exactly to be edited in a theme-specific way.

**Comment by illori** [comment]
right but some theme authors may not be familiar with js, so it may be harder for them to figure out how to disable the superfish menu if they dont what it.

**Comment by emanuele45** [comment]
A themer not familiar with js nowadays?
It means he is just changing colors, so he doesn't even know what superfish is anyway.

Of course my 2 (euro) cents.

**Comment by illori** [comment]
oh i bet once 2.1 is released and people start working on themes the question will come up.

**Comment by Oldiesmann** [comment]
If it does then we can explain how to disable it. I don't think moving it from a JS file to a template file makes any sense.

**Comment by Kindred-999** [comment]
Although I would like to see a "switch" that can be set in the theme settings/configuration, I understand the argument from the developers and don't fele that it is worth arguing about, since it CAN be overridden in the theme.js. This may be a case of "document it in the themer instructions and forget it"

**Comment by illori** [comment]
since the drop down menu for the mini profile has been removed this request is not so useful to be considered
