### ISSUE TITLE
Long quote posts  Expand /  Shrink (Feature Request)

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#5881]
Hi,

Can "Expand /  Shrink" feature be added to long quote posts?  as in the code box

**Comment by MissAllSunday** [comment]
Expand/Shrink how exactly? do you have some live example or perhaps a video where this feature can be seen?

**Comment by gevv** [comment]
![Untitled](https://user-images.githubusercontent.com/5096676/71099968-d63b4c00-21bc-11ea-8e56-ccfb1cbaef74.gif)
