### ISSUE TITLE
Tons of errors with PHP 7.4

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#5888]
#### Description
Getting spammed daily with errors regarding deprecated functions.

### Steps to reproduce
1. Use PHP 7.4
2. Use SMF

### Environment (complete as necessary)
- Version/Git revision: 0009c2d
- Database Type: mysql
- Database Version: 5.7.28
- PHP Version: 7.4

### Additional information/references

**Comment by sbulen** [comment]
https://www.php.net/manual/en/migration74.deprecated.php

**Comment by ghost** [comment]
This Line needs to be reformated :

$context['show_approval'] = isset($_REQUEST['approve']) ? ($_REQUEST['approve'] ? 2 : 1) : allowedTo('approve_posts') ? 2 : 0

Sources/Post.php

Line 449

**Comment by jdarwood007** [comment]
Try it like:
$context['show_approval'] = isset($_REQUEST['approve']) ? ($_REQUEST['approve'] ? 2 : 1) : (allowedTo('approve_posts') ? 2 : 0);

**Comment by ghost** [comment]
Done, and worked.


Multiple instances of this :

8192: Array and string offset access syntax with curly braces is deprecated
 https://mobasuite.com/forum/index.php?action=deletemsg;topic=967.0;msg=6726;e8c0d00c=066efa3ed1108164103e76cdbf3503aa
 /home/lolupdat/public_html/forum/Sources/Subs-Package.php (Line 2997)

In that file, doing the replacement atm.

**Comment by ghost** [comment]
edited and (that) corrected the error-prompts.

**Comment by ghost** [comment]
Here are the two edited files.

[Desktop.zip](https://github.com/SimpleMachines/SMF2.1/files/3964127/Desktop.zip)

**Comment by ghost** [comment]
Another modified file
[Subs-Graphics.zip](https://github.com/SimpleMachines/SMF2.1/files/3964142/Subs-Graphics.zip)

**Comment by ghost** [comment]
[Register.zip](https://github.com/SimpleMachines/SMF2.1/files/3964208/Register.zip)

And this

**Comment by ghost** [comment]
Some more
[Desktop.zip](https://github.com/SimpleMachines/SMF2.1/files/3964249/Desktop.zip)

**Comment by albertlast** [comment]
Maybe the test matrix should be expand about php 7.4 too,
but this change should be an own pr.

**Comment by ghost** [comment]
Closed, since it has a PR

**Comment by frandominguezl** [comment]
Leave it open. It will automatically close when the PR gets merged.
