### ISSUE TITLE
jquery.sceditor.css called for each theme

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#589]
currently jquery.sceditor.css is called from each theme, it should only be called from the default theme.

**Comment by emanuele45** [comment]
Nope, it is like that on purpose because if a themer wants to change the aspect of the editor can directly edit the file and not add yet another css (because index.css is loaded before this one if I remember correctly).

**Comment by illori** [comment]
well currently without that file being copied over when you copy a new theme in the admin panel, none of the icons for bbc show up. so then it needs to be set for fall back to the default folder if it is not found in a custom theme.

**Comment by emanuele45** [comment]
Reopening because that doesn't fix the issue. ;)

**Comment by Oldiesmann** [comment]
What exactly is the problem then? I was going by what @illori said above.

**Comment by Oldiesmann** [comment]
After looking at loadCSSFile more closely, I can see why my fix doesn't work, but at the same time, falling back on the default theme is NOT the default behavior unless you pass the "validate" parameter and set it to true.

I also found a bug with loadCSSFile which I'll fix in a second.
