### ISSUE TITLE
pg - spider stats error - cannot cast type bigint to abstime

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5898]
#### Description
Get an error pulling up spider stats

### Steps to reproduce
1. Enable spider stats (tracking level standard), & pull up the page

### Additional information/references
![image](https://user-images.githubusercontent.com/23568484/70866953-9eb27280-1f24-11ea-8615-635c3ecbe8f8.png)

**Comment by sbulen** [comment]
Error occurs on the Spiders tab also:
![image](https://user-images.githubusercontent.com/23568484/70867012-59db0b80-1f25-11ea-9016-c5da7e6f563c.png)

**Comment by jdarwood007** [comment]
@albertlast, Any thoughts?

**Comment by sbulen** [comment]
I have a draft PR out there.  Input welcome.
