### ISSUE TITLE
Settings table only allows settings 30 characters long

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#5906]
#### Description
```
CREATE TABLE {$db_prefix}settings (
	variable VARCHAR(255) DEFAULT '',
	value TEXT NOT NULL,
	PRIMARY KEY (variable(30))
) ENGINE={$engine};
```

While variable is 255 characters, the primary key is set to 30 characters.  This prevents using variables longer than 30 characters as you can run into duplicates due to the truncation.

Simple solution is to bump the key up.  But this could have a potential impact on performance.

Thoughts?

**Comment by albertlast** [comment]
How mutch slower get a query?
To make my point clear,
i find this massiv dump to truncate pk.

**Comment by Sesquipedalian** [comment]
In PostgreSQL, it doesn’t make any difference.

According to what I found on StackOverflow, for MySQL a longer varchar limit will increase the size of any temporary and memory tables generated in the course of working with the column’s data. So increasing the length of a varchar column in, say, the members table could affect performance, because that table is often used in complex queries that might require temporary tables. But the settings table is never used in complex queries like that—we just run a simple SELECT to read the data into our PHP variables, and occasionally an UPDATE when a value changes—so a longer varchar limit shouldn’t affect performance in this case. (Of course, I could be wrong.)

**Comment by albertlast** [comment]
the size topic get real when you got "many" rows in a table,
but the settings table will not reach this size, even in big setups.

Ps. would be nice when you mention sf topic that you link them.

**Comment by sbulen** [comment]
I don't see an issue here.  As much as possible, we should treat the schema as frozen.  

No bug reported anywhere that I've seen. 

You could pick ANY varchar - and there are many - and argue for a larger size.

**Comment by jdarwood007** [comment]
Ok, then we should address this before final.  Its a issue in 2.0 as well but not fixable for it.

**Comment by sbulen** [comment]
My recommendation is to leave it as-is - even for final.

**Comment by albertlast** [comment]
the issue is,
that this is a suprising function can work good or not.

**Comment by Sesquipedalian** [comment]
Actually, ignore what I wrote earlier. @jdarwood007 was talking about raising the length limit of the primary key to something higher than 30. I misread it as asking about raising the length limit of the column data itself. That is a different matter, so what I wrote is irrelevant. 

At the moment I have no idea what the effects of increasing the key length would be.

**Comment by sbulen** [comment]
I guess my point is...

Why?

I've never heard or read anything suggesting a problem.  And I think the bar should be pretty high for a schema change.

**Comment by albertlast** [comment]
Because it's make no sense,
short the complet field length to 30 or keep the full length in the index.
The issue is, when you got two entries which got the same first 30 chars,
than you get a unique constraint violation,
even the chars 31 is different of both entries.
The 30 chars can get very fast the same,
when  you use prefix.

So the existing solution make no sense.

**Comment by jdarwood007** [comment]
The issue arose while working on a mod and I had two settings with 30+ names but the first 30 where the same.  It created a conflict in the system and settings didn't save right.

Once I realized this, I just started abbreviating the settings to keep them under 30 characters.

This most likely has existed for a long time but hasn't been noticed for a variety of reasons I'm sure.

**Comment by sbulen** [comment]
I poked around a bit....  
In SMF 1.0.x & 1.1.x, variable was tinytext (which has a 255 max) & the pk was variable(30).  
In SMF 2.0.x, all tinytexts were converted to VARCHAR(255), and the pk here remained variable(30). 

_There is an identical issue with the themes table._  

So, oddly, both tables appear to have had a similar config all along...

I admit it is odd.  In my production forum, I have several settings > 30 chars (4 from LikePosts).  And the fact there hasn't been a conflict appears to have been pure luck.  

In the big picture, it's a pretty tiny table.  I doubt there will be a measurable performance impact.  

I am just very conservative when it comes to making such changes; I thought we were trying to keep the schema frozen.  I can't _think_ of any downside.  It's the unanticipated stuff that keeps me paranoid!  😨

**Comment by jdarwood007** [comment]
It will only conflict if the first 30 characters match another setting's first 30 characters.  Low chance of collision.

We are trying to keep the schema frozen, its RC time.  If our Lead Dev approves, we can make a PR happen to fix this, otherwise its onto the next release to fix it.  We can fix the themes table if needed, but it does do more complex joins though as it contains member options.

**Comment by Oldiesmann** [comment]
My two cents on this is that it's probably not worth fixing. Most people aren't likely to use settings with names longer than 30 characters to begin with.

**Comment by live627** [comment]
> It will only conflict if the first 30 characters match another setting's first 30 characters. Low chance of collision.

Outside of our arbitrary tests, have any such collisions ever happened? I never seen any reported...

> At the moment I have no idea what the effects of increasing the key length would be.

Increased index filesize, which then translates to slower queries _if_ any complex joins or filtering is used. We do none of that on smf_settings.

**Comment by MissAllSunday** [comment]
I would be inclined to leave it as it is, while its true the settings table doesn't get involve on complex queries where the index size could be a factor, theres also two points against doing such change:

- keep the schema frozen
- low collision chance 

Indeed its weird that both themes and settings table has this specific table configuration but we also need to consider that we are dealing with a 10+ years old schema and while we can fix these issues (also the late scope comes into play) we would do better if we leave the schema as it is right now, work with it and take a note of this for future versions.
