### ISSUE TITLE
"Trying to access array offset on value of type null" when viewing error log

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#5907]
#### Description
Possibly related to #5888. When trying to view all errors in the error log, you generate another error. However, this only happens if there are other errors in the log (in my case three administration login attempt messages because I didn't remember which password I used on this forum :stuck_out_tongue: )

```
Type of error: General 
8: Trying to access array offset on value of type null
http://localhost/smf/index.php?action=admin;area=logs;sa=errorlog;desc
/srv/http/smf/Sources/ManageErrors.php (Line 168)
```

Line 168:
```php
		if ($search_message == $filter['value']['sql'])
```

### Steps to reproduce
1. Do something to generate an error, such as attempting to login with an incorrect password.
2. View all errors in the error log.
3. If affected, you will see a new "general" error with the above message.

### Environment (complete as necessary)
- Version/Git revision: 2.1, recent Git release (don't remember exactly which one)
- Database Type: PostgreSQL
- Database Version: 12.1
- PHP Version: 7.4.1

I haven't tested this on other versions of PHP or on MySQL yet so I'm not sure specifically what's causing this.

**Comment by jdarwood007** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/5892

**Comment by Oldiesmann** [comment]
Looks like I need to update my local test copy then. Thanks!
