### ISSUE TITLE
Error about search

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#5908]
#### Description
Message : Undefined variable: approve_query
/Sources/Search.php (Line 1828)

Not sure if that is new or not.

### Steps to reproduce
1. https://github.com/SimpleMachines/SMF2.1/commit/967b680eeb977a703cb58973790781169328a802 + https://github.com/SimpleMachines/SMF2.1/pull/5891.patch

### Environment (complete as necessary)
- Database Type: mysqli
- Database Version:5.7.28
- PHP Version: 7.4

**Comment by Oldiesmann** [comment]
#5877

**Comment by sbulen** [comment]
Yes, this is a dupe of #5877.  I'll close this out.
