### ISSUE TITLE
Proxy cache cleanup

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5914]
#### Description
The 2.0 proxy cache cleanup has a couple issues.  The 2.1 version is functionally similar.   

It needs to:
 - skip directories
 - skip files like index.php

### Additional information/references
See 2.0 issue here: https://www.simplemachines.org/community/index.php?topic=571162.0

**Comment by albertlast** [comment]
can you please produce this errors with 2.1?
