### ISSUE TITLE
2.0.16 Changes Needs Merged

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#5923]
Just a note, prior to RC3, we need to merge the changes from 2.0.16 into here.

I was going to start working on it, but if anyone has already started, please speak up.

**Comment by sbulen** [comment]
Which ones?

**Comment by MissAllSunday** [comment]
Theres a few RC3 tagged issues, all related to the GPR whatever stuff:

https://github.com/SimpleMachines/SMF2.1/labels/GDPR

Dunno if those needs to be resumed and worked on or just go straight and use 2.0.17's code.

**Comment by sbulen** [comment]
I think it's the other way around.  Once these are completed,  a couple functions need to be back ported to 2.0.  (# 76)

The main question is the sequence.

**Comment by MissAllSunday** [comment]
Oh, if thats the case then those PRs will need to get extra attention since they are now becoming blockers for RC3 release.

**Comment by Sesquipedalian** [comment]
There are some things that need to be ported forward, and some that need to be ported back. This is my top priority right now, so I've assigned it to myself.

**Comment by albertlast** [comment]
what is on the list?

**Comment by live627** [comment]
@Sesquipedalian what's the status of this?
