### ISSUE TITLE
Settings.php blanked out after running upgrade.php

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#5934]
#### Description

after running upgrade.php both Settings.php and Settings_bak.php are blanked out

### Steps to reproduce
1. upgraded to latest code in this repo
2. ran upgrade.php via CLI
3. Settings.php was blanked out as well as Settings_bak.php

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

i dont want went wrong here but the files are empty except for 
?>

**Comment by Sesquipedalian** [comment]
Please test #5953.
