### ISSUE TITLE
WSOD upon install

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5936]
#### Description
WSOD on install after entering DB parameters

### Environment (complete as necessary)
- Version/Git revision: Current GitHub
- Database Type: MySQL
- Database Version: 5.7
- PHP Version: 5.6

### Additional information/references

**Comment by m4z** [comment]
Special characters in password? :zipper_mouth_face:

Edit: suspecting #5930

**Comment by MissAllSunday** [comment]
Nope, a function was re-declared, will push a patch shortly.
