### ISSUE TITLE
Installer - infinite loop, can't get past db settings

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5938]
#### Description
Keep going back to the welcome screen

### Steps to reproduce
1. Install

### Environment (complete as necessary)
- Version/Git revision: Current as of this moment...
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 7.3

### Additional information/references
Getting further than I was earlier!
I've seen this before...  Can't recall where...

**Comment by sbulen** [comment]
Thinking aloud here...  I believe the problem is that the installer redirect is still in the settings file.  

The upgrader used to have it's own custom version of updateSettingsFile, that cleared out the installer redirect.  (Funky approach...  My assumption was always that this was an esoteric security fix...🙄)  

Now that we are using the standard updateSettingsFile, the redirect still exists and is not getting cleaned out, so you keep getting pushed back a step.  

Just a theory at this point...  Still testing...

See:
#5815 
#5210
#4483

**Comment by sbulen** [comment]
OK...  Removing the redirect from the template Settings.php file works.

_Now, the real question - why was it there in the first place?_  I am hesitant to just yank it outta there without understanding where it came from...

**Comment by sbulen** [comment]
OK, it gets much further along, but then we start getting undefined variable $boarddir issues.

Still looking...

**Comment by sbulen** [comment]
OK, so once past the $boarddir issues, then it almost completes, but the settings file is incomplete.

So there are at least 3 separate issues:
 - The redirect logic in settings.php is no longer removed, causing an infinite loop.  (Note if you just remove the redirect, then, the redirect is gone...  I.e., the install is less user-friendly - the only way to start the installer is to type in the full path to install.php.  Typing in the full path works, though.)  
 - $boarddir is not set
 - settings.php file is incomplete

**Comment by mobasuite** [comment]
Same issue

**Comment by live627** [comment]
An idea is that you could skip the redirect if `SMF_INSTALLING` is defined.

**Comment by sbulen** [comment]
@Sesquipedalian - were you going to look at some of these or would you like me to?

**Comment by jdarwood007** [comment]
Somebody should.  These regressions are considered blockers for RC3.

**Comment by sbulen** [comment]
I'm tied up today & most of tomorrow.  I spent what time I could today looking at the new updateSettingsFile code.  If things are still outstanding on Sunday I'll dive in.  

Note that once you get past the infinite loop here, your DB is built with all the defaults from the default settings file - e.g., with a DB name of "smf" - not what you had entered.

**Comment by sbulen** [comment]
What I thought was going to happen with RC3 was that the remaining GDPR stuff (exports) was going to be implemented (the PRs are already in the works here - #5081 & #4892), then ported back for 2.0.18.  I think wrapping those is the biggest chunk of work for RC3.

**Comment by Sesquipedalian** [comment]
I'm working on it right now, folks. Had a busy couple of days, so just getting caught up. :)

**Comment by Sesquipedalian** [comment]
Please test #5953.
