### ISSUE TITLE
updateSettingsFile() had a a bruh moment

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#5939]
My code

		$this->configVars = array(
			array('mtitle', 'maintenance_subject', 'file', 'text', 36),
			array('enableCompressedOutput', 'enableCompressedOutput', 'db', 'check', null, 'enableCompressedOutput'),
		);
		$_POST = array(
			'mtitle' => 'value',
			'enableCompressedOutput' => '1'
		);
		$token_check = createToken('admin-ssc');
		$_POST[$token_check['admin-ssc_token_var']] = $token_check['admin-ssc_token'];
		$token_check = createToken('admin-dbsc');
		$_POST[$token_check['admin-dbsc_token_var']] = $token_check['admin-dbsc_token'];
		saveSettings($this->configVars);

Settings.php before

```
<?php
$db_type = 'mysql';
$db_name = 'smf21';
$db_user = 'root';
$db_passwd = '';
$db_server = 'localhost';
$db_prefix = 'smf_';
$db_show_debug=true;
$cookiename = 'SMFCookie574';
$db_port = '3307';
$boardurl = 'http://localhost/SMF2.1';
$boarddir = 'C:\\wamp64\\www\\SMF2.1';
$sourcedir = 'C:\\wamp64\\www\\SMF2.1/Sources';
$cachedir = 'C:\\wamp64\\www\\SMF2.1/cache';
$packagesdir = 'C:\\wamp64\\www\\SMF2.1/Packages';
$tasksdir = 'C:\\wamp64\\www\\SMF2.1/Sources/tasks';
$mbname = 'My Community';
$language = 'english';
$image_proxy_secret = '49933237e8ae60456661';
$image_proxy_enabled = 0;
$db_character_set = 'utf8';
$webmaster_email = 'live627@gmail.com';
$cache_enable = 0;
$cache_accelerator = 'smf';
$cache_memcached = '';
$upgradeData = '';
$image_proxy_maxsize = 5190;
$maintenance = 0;
$mtitle = '';
$mmessage = 'Don\'t worry, we will be back shortly with an updated forum.  It will only be a minute ;).';
$db_error_send = 1;
?>
```

Settings.php after

```
<?php

/**
 * The settings file contains all of the basic settings that need to be present when a database/cache is not available.
 *
 * Simple Machines Forum (SMF)
 *
 * @package SMF
 * @author Simple Machines https://www.simplemachines.org
 * @copyright 2020 Simple Machines and individual contributors
 * @license https://www.simplemachines.org/about/smf/license.php BSD
 *
 * @version 2.1 RC1
 */

########## Database Info ##########
/**
 * The database type
 * Default options: mysql, postgresql
 *
 * @var string
 */
$db_type = 'mysql';
/**
 * Database username
 *
 * @var string
 */
$db_user = 'root';
/**
 * Path to the Sources directory.
 *
 * @var string
 */
$sourcedir = 'C:\\wamp64\\www\\SMF2.1/Sources';
/**
 * Path to the tasks directory.
 *
 * @var string
 */
$tasksdir = 'C:\\wamp64\\www\\SMF2.1/Sources/tasks';
/**
 * Email address to send emails from. (like noreply@yourdomain.com.)
 *
 * @var string
 */
$webmaster_email = 'live627@gmail.com';
820592552b4a7b10cc4cb101ee21cd78

?>
```

Also, if `$cache_memcached = '';` is removed, the function complains about it missing on line 918. I only know this because I had to add it in. To test this further, I removed `$upgradeData = '';` since fresh installs won't have it IIIRC. Same result.

Related to #5934

**Comment by sbulen** [comment]
There have been a bunch of recent changes in this area...

**Comment by live627** [comment]
I updated my codebase this afternoon and thsi was the result - a failed test.

**Comment by sbulen** [comment]
Yep, this is current.

**Comment by mobasuite** [comment]
This is preventing upgrade from proceeding.

**Comment by live627** [comment]
If anyone was wondering, I'm not going to fix this, that's why I opened this issue.

**Comment by jdarwood007** [comment]
This seems related to this in Subs-Admin.php:
```
			case 'string':
				$regex = '
						# If the string starts with a single or double quotation mark
						(?(?=["\'])
							# match the opening quotation mark
							(["\'])
							# then any number of other characters or escaped quotation marks
							(?:[^\\1]|(?<=\\\)\\1)*
							# then the closing quotation mark
							\\1
						)';
				$flags .= 'x';
				break;
```

More specifically the look behind is causing it.
Also removing the x flag fixes it as well.

**Comment by jdarwood007** [comment]
https://regex101.com/r/vHu4yk/1

Seems the regex is greedy sometimes.  If I add \r\n to the ending match it seems to be fine.
```
			case 'string':
				$regex = '
						# If the string starts with a single or double quotation mark
						(?(?=["\'])
							# match the opening quotation mark
							(["\'])
							# then any number of other characters or escaped quotation marks
							([^\1\r\n])*
							# then the closing quotation mark
							\1
						)';
				$flags .= 'x';
				break;
```

**Comment by Sesquipedalian** [comment]
> Seems the regex is greedy sometimes.

That's part of the issue here, yes.

> If I add \r\n to the ending match it seems to be fine.

Actually, that only appeared to work because changing the double slashes to single slashes broke the regex entirely.

Anyway, I have a fix coming soon for this. 🙂

**Comment by Sesquipedalian** [comment]
Please test #5953.
