### ISSUE TITLE
attachmentEncryptFilenames

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#594]
attachmentEncryptFilenames should be removed, there is no need to even allow attachments to be stored as their file name and it causes issues with files that share the same name.

there are some forums out there that somehow have not had this disabled and run into issues.

there is code for this in the upgrade/install sql's and one line in subs.php

**Comment by Arantor** [comment]
Yes there is: legacy handling. This was already hashed out in 2009 when this was changed in the aftermath of the krisbarteo incident.

Unless something's drastically changed, the upgrade SQL should just be ensuring that the relevant columns exist and then forcing the option to be enabled. It was deemed (and rightly so) too expensive to go through and force each existing attachment to be adhering to the new structure, doubly so in a x.y.z to x.y.z+1 patch (as 1.1.9 and 2.0 RC1-1 were, yup this was so important the team actually pushed out a patch to an RC)

I'd argue that, to be honest, this behaviour shouldn't actually change.

**Comment by illori** [comment]
then we need better checking that on upgrade this setting is set correctly in the database.

**Comment by jdarwood007** [comment]
Honestly thought Arantor,
It is the 2.1 upgrade.  This would be the proper time to change this over to make sure everything is using the new hashing method.  And honestly shouldn't be that intensive on the server.  We are simply talking a rename of the file in the existing directory

**Comment by Arantor** [comment]
When did the upgrader start backfilling file_hash entries for files that never had it? If the file is stored without encryption, the file_hash wouldn't have been populated either... at least in the legacy stuff. But in the last 4 years it has become less of a problem, admittedly.
