### ISSUE TITLE
Upgrade broken in new SMF

### ISSUE THREAD

**Issue by mobasuite** [SimpleMachines/SMF#5943]
#### Description
Get main branch set-up
Then apply : https://github.com/SimpleMachines/SMF2.1/pull/5940

Produces two errors :

1. Undefined index: utf8 in /home/lolupdat/public_html/forum/Sources/Subs-Admin.php on line 794

2. Also apparently the UpdateSettingsFile() is messing up the settings.php

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type: mysql
- Database Version:
- PHP Version: 7.4

### Additional information/references

**Comment by live627** [comment]
#5939

**Comment by Sesquipedalian** [comment]
Please test #5953.

**Comment by mobasuite** [comment]
@Sesquipedalian 

Settings is still getting truncated.
