### ISSUE TITLE
using html as a membergroup name

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#595]
the ability to use html in the membergroup name field should be disabled. many people try this and end up with a partial entry which breaks the membergroup page in admin as the html is not complete in the name of one or more groups. this requires the user to edit the name of the group in the database.

some people try to change the name into an image using html and depending on the length of the url to the image it may be longer then the field can accept, then it get truncated and breaks the whole page. many admin over the years have had this issue. if we are to keep allowing html then letting the admin know the name field is too long to save would help.

**Comment by emanuele45** [comment]
3c78bc910de75aa1e7da3723ee08749cdb4337ac

**Comment by illori** [comment]
that is good to know. i guess then i can close this. we should make sure admin know that will apply in 2.1 though.

**Comment by emanuele45** [comment]
Not that it will change anything for those that already broke their forum, the commit just removes the option to use html in that field (and I removed it from few others as well I think).

**Comment by illori** [comment]
yea that is good enough, future proof it so that others can not break it. now we just need this for 2.0 :P
