### ISSUE TITLE
upgrade.php error windows chmod

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#5952]
#### Description
 +++  Converting legacy attachments.Error: chmod(): No such file or directory File: C:\wamp64\www\github2.1\upgrade.php(2028) 

### Steps to reproduce
1. just upgraded to latest on windows got above error in upgrade log

### Environment (complete as necessary)
- Version/Git revision:
- Database Type: mariaDB
- Database Version: 10.4.10
- PHP Version: 7.1.33

### Additional information/references

**Comment by live627** [comment]
I believe what happened to trigger that issue was that one of the attachment directories was missing, but was still in the $modSettings whatever. The script that @illori uses deletes all extraneous attachment directories.

**Comment by sbulen** [comment]
The upgrader is not yet working at this time.

I think the chmod issue is related to the existing issues.  There are fixes for chmod in a current PR (8f089ac9c967d54c93df87c40ee54e35e9802804).

**Comment by live627** [comment]
`chmod()` is built into PHP.

**Comment by illori** [comment]
My script does not delete attachment directories.

**Comment by illori** [comment]
the root issue seems to be related to https://github.com/SimpleMachines/SMF2.1/issues/899 where i still cannot change the paths in the admin panel for attachments.

the repair_settings.php script did not rename the paths hence getting the issue here. i guess this can be closed and a new issue for the rename of the paths has to be opened.

**Comment by sbulen** [comment]
> the root issue seems to be related to #899 where i still cannot change the paths in the admin panel for attachments.
> 
> the repair_settings.php script did not rename the paths hence getting the issue here. i guess this can be closed and a new issue for the rename of the paths has to be opened.

That would probably be the right thing to do...
