### ISSUE TITLE
Birthday task didn't find people how birthday is on 29.02 in a non leap year

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#5955]
#### Description
This query:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/tasks/Birthday-Notify.php#L36-L48
didn't show up people how birhtday is on 29.02. when the actualy year is not a leap year.

So question is,
do we fix it?
When yes,
do they had birthday on 28.02 or 1.3?

**Comment by jdarwood007** [comment]
Which day leap year people celebrate their birthday is mostly a personal preference.
Honestly I don't see a need to fix it.  This isn't something legally binding.  It seems even legally standing laws go either direction.

**Comment by albertlast** [comment]
@Sesquipedalian yes or no?

**Comment by Sesquipedalian** [comment]
I don't think this matters very much, but if you want to do something about it, I won't object. It looks like more places around the world use March 1, so I suppose you should use that date if you want to address this.
