### ISSUE TITLE
Couldn't fetch mysqli_result in

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#5965]
#### Description

Warning
: mysqli_fetch_assoc(): Couldn't fetch mysqli_result in
C:\wamp64\www\github2.1\Sources\Subs-Membergroups.php
on line
675

### Steps to reproduce
1. latest as of 12am eastern, getting this error on the board index and no where else i have seen
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type: mariadb
- Database Version: 10.4.10
- PHP Version: 7.1.33

### Additional information/references

    #0: smf_error_handler()
    Called from unknown on line -1
    #1: mysqli_fetch_assoc()
    Called from C:\wamp64\www\github2.1\Sources\Subs-Membergroups.php on line 675
    #2: cache_getMembergroupList()
    Called from C:\wamp64\www\github2.1\Sources\Load.php on line 3488
    #3: cache_quick_get()
    Called from C:\wamp64\www\github2.1\Sources\BoardIndex.php on line 126
    #4: BoardIndex()
    Called from C:\wamp64\www\github2.1\index.php on line 168

**Comment by albertlast** [comment]
Did you try to run this query directly vs your db?
```
SELECT id_group, group_name, online_color
FROM {db_prefix}membergroups
WHERE min_posts = -1
    AND hidden = 0
    AND id_group != 3
ORDER BY group_name
```

**Comment by live627** [comment]
- can you take a peek at smf_membergroups in phpMyAdmin?
- is this a new install or upgraded?
- is Settings.php empty? I guess not since you can presumably access things...

**Comment by illori** [comment]
what am i looking for in smf_membergroups?

it is not a new install.

Settings.php was empty but restored from backup.

**Comment by illori** [comment]
-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Server version: 10.4.10-MariaDB
-- PHP Version: 7.1.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `github2.1`
--

-- --------------------------------------------------------

--
-- Table structure for table `smf1_membergroups`
--

DROP TABLE IF EXISTS `smf1_membergroups`;
CREATE TABLE IF NOT EXISTS `smf1_membergroups` (
  `id_group` smallint(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_name` varchar(80) NOT NULL DEFAULT '',
  `description` mediumtext NOT NULL,
  `online_color` varchar(20) NOT NULL DEFAULT '',
  `min_posts` mediumint(9) NOT NULL DEFAULT -1,
  `max_messages` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
  `icons` varchar(255) NOT NULL DEFAULT '',
  `group_type` tinyint(3) NOT NULL DEFAULT 0,
  `hidden` tinyint(3) NOT NULL DEFAULT 0,
  `id_parent` smallint(5) NOT NULL DEFAULT -2,
  `tfa_required` tinyint(3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_group`),
  KEY `min_posts` (`min_posts`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `smf1_membergroups`
--

INSERT INTO `smf1_membergroups` (`id_group`, `group_name`, `description`, `online_color`, `min_posts`, `max_messages`, `icons`, `group_type`, `hidden`, `id_parent`, `tfa_required`) VALUES
(1, 'Administrator', '', '#FF0000', -1, 0, '5#iconadmin.png', 0, 0, -2, 0),
(2, 'Global Moderator', '', '#0000FF', -1, 0, '5#icongmod.png', 0, 0, -2, 0),
(3, 'Moderator', '', '', -1, 0, '5#iconmod.png', 0, 0, -2, 0),
(4, 'Newbie', '', '', 0, 0, '1#icon.png', 0, 0, -2, 0),
(5, 'Jr. Member', '', '', 50, 0, '2#icon.png', 0, 0, -2, 0),
(6, 'Full Member', '', '', 100, 0, '3#icon.png', 0, 0, -2, 0),
(7, 'Sr. Member', '', '', 250, 0, '4#icon.png', 0, 0, -2, 0),
(8, 'Hero Member', '', '', 500, 0, '5#icon.png', 0, 0, -2, 0),
(9, 'test', '', '', -1, 0, '1#icon.png', 2, 0, 0, 0),
(10, 'not test', '', '', -1, 0, '1#icon.png', 0, 0, 0, 0);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

i did have some html in the description of the admin and global mod group, removed that and the error still exists.

**Comment by live627** [comment]
> what am i looking for in smf_membergroups?

Just that it looks normal, which it is, judging from that dump.

**Comment by illori** [comment]
Then I wonder why this issue is happening.

**Comment by live627** [comment]
found it, will post a fix in a few

**Comment by live627** [comment]
done

#5970
