### ISSUE TITLE
repair_settings.php - multiple issues

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5968]
#### Description
I think repair_settings needs a little tlc to be brought current from some recent changes.  
Note:  repair_settings works on 2.0 as well as 2.1 as well as 1.x...

### Issues
1. Error thrown across top of screen:
`Warning: Use of undefined constant MYSQL_TITLE - assumed 'MYSQL_TITLE' (this will throw an Error in a future version of PHP) in D:\EasyPHP\van21\Sources\Subs-Db-mysql.php on line 55`
2. Logo broken:
![image](https://user-images.githubusercontent.com/23568484/72871293-426b0d00-3c9f-11ea-94dc-c436908cd047.png)
From the console log:
![image](https://user-images.githubusercontent.com/23568484/72871273-35e6b480-3c9f-11ea-95be-f5cc82b99a41.png)
3.  smf_scripturl not defined - from the console log:
![image](https://user-images.githubusercontent.com/23568484/72871316-5878cd80-3c9f-11ea-989d-36d2a0aba7f3.png)

### Environment (complete as necessary)
- Version/Git revision:  Today's
- Database Type:  Mysql
- Database Version:  5.7
- PHP Version:  7.3

### Additional information/references
repair_settings.php was obtained directly from the github tools repo

**Comment by albertlast** [comment]
repair_settings is not part of this project,
so why open here?

**Comment by sbulen** [comment]
Awareness.  It is a critical part of the SMF environment, that has been impacted by changes made here.

**Comment by sbulen** [comment]
PR submitted to address, so I'll close this out:
https://github.com/SimpleMachines/tools/pull/40
