### ISSUE TITLE
Installation step 3 brings back to Step 0

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#5975]
#### Description
After filling in the details of installer's Step 3, I automatically get back to Step 0 with no errors showing on screen.

### Steps to reproduce
1. Start installer and complete details until step 3

### Environment (complete as necessary)
- Version/Git revision: Latest: https://github.com/SimpleMachines/SMF2.1/commit/8987084e15104ef3cd67fbb06b3614cd2722f3b5
- Database Type: MySQL MariaDB
- Database Version: 10.3.16-MariaDB
- PHP Version: 7.2.20

**Comment by sbulen** [comment]
I think this is a dupe of #5938

**Comment by frandominguezl** [comment]
Definitely it is. Closing this one.
