### ISSUE TITLE
multiple attachment folders and new base directory path

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#598]
if you have in the past had more then one attachment directory and then enabled the option create new directories within a base directory in the attachment directories page you can still select any of the additional attachment folders as the current in the table at bottom of the page, this should be disabled as you are using the base directory path at the top of the page.

it would seem to me that those additional attachment directories that you can select as current in the bottom table dont actually become current.

**Comment by illori** [comment]
also related to this if you are using the option create new directories within a base directory and select a new current directory from the bottom table it will uncheck the checkbox for create new directories within a base directory if any directory is selected as current in the bottom table even if the directory is already marked as a base directory.

also after that checkbox is unchecked you can still view the base directory section on the attachment directories page even if there are no directories in those base directories. IMO if the base directories do not have directories made in them the base directory paths section should be hidden once the create new directories within a base directory checkbox has been unchecked

**Comment by MissAllSunday** [comment]
Are you still able to reproduce this issue?

**Comment by illori** [comment]
yes nothing here has changed.

**Comment by jdarwood007** [comment]
@illori I can't reproduce this.  When I pick to use the automatic method, the old multiple directories are retained.   However i can't choose them.  I can only add new base directory paths.

**Comment by illori** [comment]
reading this i am not 100% sure what the issue was. i am going to close it and if it is an issue someday it will get a new issue opened.
