### ISSUE TITLE
Font size selector doesn't work in Safari

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#5980]
#### Description
I don't have an Apple device to test this with, but I've had two users lately report that the font size option in the editor results in a blank screen on Safari (one on Mac, one on an iPad - switching to Chrome fixed the issue for the Mac user).

### Steps to reproduce
1. Start a new post/PM using the Safari browser
2. Tap/click on the font size button

### Environment (complete as necessary)
- Version/Git revision: 2.1 RC 2
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references
I'm not sure if this is a problem with SMF or with SCEditor itself. I don't have access to an Apple device to test this with so further testing is needed as well. Forum is 2.1 RC2 with TinyPortal and a few other mods (but nothing that deals with the editor).

**Comment by DiegoAndresCortes** [comment]
I'm trying to reproduce this issue on iOS but I'm just unable to login into my test environment.
Tested on iPhone and iPad, could be another safari related issue. 
Tried both the popup and the login action but it doesn't actually work despite refreshing the page.

Would be nice if someone can test both of these problems on the desktop version of Safari. (and mobile too just to verify).

BTW my issue was using the latest build.

**Comment by DiegoAndresCortes** [comment]
I was able to login using a live (online) version.
Tested the Font size selector and it's working fine for me on iPhone.
@Oldiesmann

**Comment by Oldiesmann** [comment]
This was reported on a forum for senior citizens so I'm guessing this was on the desktop. I'll see if I can dig for further info

**Comment by MissAllSunday** [comment]
<img width="1476" alt="Captura de Pantalla 2020-07-20 a la(s) 11 41 41" src="https://user-images.githubusercontent.com/3420756/87963506-6bb5fb80-ca7e-11ea-983f-0470369c92c6.png">


I was able to use the font size selector just fine in Safari for desktop
<img width="871" alt="Captura de Pantalla 2020-07-20 a la(s) 11 42 36" src="https://user-images.githubusercontent.com/3420756/87963610-9902a980-ca7e-11ea-85f6-2a5765dc5e84.png">

**Comment by MissAllSunday** [comment]
I'm going to close this one, if anyone else was able to reproduce this or a similar behavior  please create a new issue.
