### ISSUE TITLE
dropzone.min.js ignores attachment settings (hardcoded 256MB limit)

### ISSUE THREAD

**Issue by kungfooman** [SimpleMachines/SMF#5989]
I fixed all forum attachment and php.ini settings to allow files up to 2GB, but the forum still told me that my 0.7GB file was too large.

I traced it all down to: Themes/default/scripts/dropzone.min.js

I beautified the code, it contains this crucial line, which hardcodes the limit to 256MB:

```JS
maxFilesize: 256,
```

I fixed it manually to `2000` (2gb) and now large files finally work

**Comment by MissAllSunday** [comment]
mmm, weird, dropzone should overwrite its own default settings with whatever we sent when we initialize it. Will have to check it. Thanks for the report.

**Comment by MissAllSunday** [comment]
I cannot reproduce this issue with the current build:

I set up my PHP upload_max_filesize to 80M, set my SMF settings to the same and was able to upload two large files without issue.

![Screenshot from 2020-02-16 18-43-37](https://user-images.githubusercontent.com/3420756/74616324-c53f8600-50ec-11ea-8547-32671b1f4811.png)
![Screenshot from 2020-02-16 18-45-32](https://user-images.githubusercontent.com/3420756/74616326-c7a1e000-50ec-11ea-8d62-b9d16596f3fe.png)

**Comment by kungfooman** [comment]
Thank you for testing!

80MB is too small, it starts to fail at >256MB for individual files (e.g. a large .mp4 video)

**Comment by sbulen** [comment]
This sounds a little similar to #4766...

**Comment by Sesquipedalian** [comment]
It does sound somewhat similar, but #4766 had to do with a timeout limit rather than an amount of data, and the symptom was that the upload simply halted with no error message or indication except that the progress bar stopped moving. The symptoms here are a bit different, and @kungfooman’s workaround points to a different cause.
