### ISSUE TITLE
Undefined index: O in Subs.php

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#5990]
#### Description
Undefined index.  

### Steps to reproduce
1. Navigate past a post with a smiley in it

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: MySQL
- Database Version: 5.7
- PHP Version: 7.3

### Additional information/references
![image](https://user-images.githubusercontent.com/23568484/73690975-51ca5d00-4686-11ea-8748-878e1413a45e.png)

**Comment by sbulen** [comment]
Note:  Reported in the forum as well.  Note the line# is a little different, but this user has some mods installed.  The trace is the same:
https://www.simplemachines.org/community/index.php?topic=571716.0

**Comment by sbulen** [comment]
The regex that is built, for some reason, is broken now.  Not sure why...  

It thinks the character "O" is a smiley...   But then it can't look it up...  This is an example of a post that generates an error:
![image](https://user-images.githubusercontent.com/23568484/73799514-09389f80-476b-11ea-94f8-e52875d2a3b2.png)

Kind of a big deal, actually, it's dropping Os...   There may be different symptoms for different folks, depending on the layout of the smiley sets.

**Comment by sbulen** [comment]
Emphasizing that this is different for different folks...  In my various test environments, the smileys are in different orders, and as a result, the regex is not built the same...  Different forums are breaking on different things...

As an example, this is the regex built for my environment that is breaking on posts that have Os:
`(?<=[>:\?\.\s\x{A0}[\]()*\\;]|(?<![a-zA-Z0-9])\(|^)((?>&gt;\:(?>\(|D)|\?\?\?|\^\-\^|8\)|\>\:(?>\(|D)|\:(?>&\#39;\(|'\(|\:\)|\(|\)|\-(?>\*|X|\[|\\)|D|P|o)|;(?>\)|D)|O))(?=[^[:alpha:]0-9]|$)`

**Comment by Sesquipedalian** [comment]
What happens if you revert the changes introduced in #5735?

**Comment by Sesquipedalian** [comment]
FYI, I haven't been able to reproduce this yet myself.

**Comment by sbulen** [comment]
I've only seen it on older migrated forums.  Initial theory is that smileys were escaped differently...???  Something is really confusing build_regex.

Pretty sure that caching change isn't related.  Issues happen 1st time thru.

**Comment by sbulen** [comment]
Two ways to reproduce the problem with the lethal O characters:
1)  Install any 1.x version then upgrade to 2.1.  
2)  Take any 2.1 installed version & delete the 3 "new" smileys - Laugh, Police & Angel.

Both processes above should leave you with only the original 19 smileys.  You will then get tne undefined index error if you put a standalone O in a post (leading & trailing space).  

I think something has changed in the last year or so that alters the behavior of build_regex.  Depending on what is passed to it, the built regex is somehow mangled.

This is a pure vanilla 2.1 environment, which supports 22 smileys.  Note that one smiley, afro, isn't working.  (I'm a little thankful of that...)  No undefined index error.
![image](https://user-images.githubusercontent.com/23568484/73867894-4f8a0f00-47fc-11ea-8ec5-773f4cc1122f.png)
This is the same post in a 1.x environment upgraded to 2.1, which supports 19 smileys.  The final 3 aren't working, as expected (laugh, police, angel).  Note that afro isn't working here as well.  Note that standalone character 'O's are eaten & result in the undefined index error. 
![image](https://user-images.githubusercontent.com/23568484/73867900-5add3a80-47fc-11ea-9c30-638a71d47c17.png)
2.1 can be made to behave the same way if you delete the laugh, police & angel smileys, leaving only the original 19.

**Comment by Sesquipedalian** [comment]
That's helpful info, @sbulen. Thanks. I'm looking into this now.

**Comment by sbulen** [comment]
A quick glance at the code, & wondering if 0 is returning an empty...  So it is never detected as being under the O...

**Comment by Sesquipedalian** [comment]
> A quick glance at the code, & wondering if 0 is returning an empty... So it is never detected as being under the O...

Yup. I reached the same conclusion, but it looks like you beat me to it. 🙂
