### ISSUE TITLE
implode(): Passing glue string after array is deprecated - PHP 7.4.2

### ISSUE THREAD

**Issue by SugarD-x** [SimpleMachines/SMF#6000]
#### Description
The following error appears in the error log when using SMF 2.1 RC2 with PHP 7.4.2 while browsing the forum:
```
Type of error: General
8192: implode(): Passing glue string after array is deprecated. Swap the parameters /index.php?board=1.0
/Sources/minify/src/CSS.php (Line 522)
```

### Steps to reproduce
1. Install SMF 2.1 RC2 and run it with PHP 7.4.2.
2. Browse the forum.
3. Check the error log.

### Environment (complete as necessary)
- Version/Git revision: 2.1 RC2
- Database Type: MySQL
- Database Version: 8.0.19
- PHP Version: 7.4.2

**Comment by SugarD-x** [comment]
This may be related to bug #5891 regarding PHP 7.4 deprecations.

**Comment by albertlast** [comment]
It's already fixed: https://github.com/SimpleMachines/SMF2.1/commit/c9ce5107c731c2b8d253ffd24b5bba1e89e7fa73

**Comment by SugarD-x** [comment]
Awesome, thank you! I wasn't able to find it in a search, so I wasn't sure. Much appreciated!
