### ISSUE TITLE
Upgrader - CLI - custom_avatar & $upgradeData

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6001]
#### Description
Two issues _specific to upgrading via the CLI_:
 - If the prior version didn't have a custom_avatar directory, it is somehow not created upon upgrade
 - $upgradeData is left in Settings.php when done

### Steps to reproduce
1. Do an upgrade via CLI on a pure vanilla 2.0 or 1.x implementation with no custom avs directory setup

### Environment (complete as necessary)
- Version/Git revision: Today
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 7.3

### Additional information/references
Errors from trying to upload an avatar:
![image](https://user-images.githubusercontent.com/23568484/73817245-50d91e80-479f-11ea-9d73-92a717bdbe40.png)

The problem is the folder & url weren't setup by the upgrader:
![image](https://user-images.githubusercontent.com/23568484/73817281-63ebee80-479f-11ea-81f5-e7c2c0e2fa6e.png)

$upgradeData is still in Settings.php:
![image](https://user-images.githubusercontent.com/23568484/73817310-7108dd80-479f-11ea-9ff0-1a9505eaad27.png)

**Comment by sbulen** [comment]
I'm not quite sure how deep to go here.  I have been focusing on reporting errors from 2.0=>2.1 upgrades thus far via CLI.  1.x=>2.1 produces many, many more errors & gaps in functionality.  

Browser upgrades are far more robust than CLI at the moment...  Especially the further back you go.

**Comment by jdarwood007** [comment]
Focus mostly on 2.0 to 2.1.  Unless you can prove that the 1.1 to 2.0 worked and the 1.1 to 2.1 does not.
