### ISSUE TITLE
Moderation - Call to undefined function when deleting a post 

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6017]
#### Description
Fatal error: Uncaught Error: Call to undefined function recountOpenReports() in D:\EasyPHP\van21\Sources\RemoveTopic.php:1023 Stack trace: #0 D:\EasyPHP\van21\Sources\RemoveTopic.php(140): removeMessage(3) #1 D:\EasyPHP\van21\index.php(168): DeleteMessage() #2 {main} thrown in D:\EasyPHP\van21\Sources\RemoveTopic.php on line 1023

### Steps to reproduce
1. As a user, report a post
2. As moderator, when looking at the report, choose the action to delete the post

### Environment (complete as necessary)
- Version/Git revision:  Now
- Database Type: MySQL
- Database Version: 5.7
- PHP Version: 7.3

### Additional information/references

**Comment by halldorr** [comment]
Just noting that I also get an error in the error log following these steps but I get a different error.

Type of error: Critical
Error message: The selected search API the forum is using is out of date - falling back to standard search. Please check file SearchAPI-Standard.php.
URL of page causing the error: http://site.com/smf/index.php?action=deletemsg;topic=1.0;msg=1;modcenter;fbc5952696=e0f52b7b62b41dfe7b73eabcede3cd32

Backtrace information
    #0: findSearchAPI()
    Called from RemoveTopic.php on line 360
    #1: removeTopics()
    Called from RemoveTopic.php on line 714
    #2: removeMessage()
    Called from RemoveTopic.php on line 140
    #3: DeleteMessage()
    Called from index.php on line 151
