### ISSUE TITLE
word censor

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#602]
you can allow users to turn off the word censor in admin -> current theme

you can also set a permission to disable word censor for each group.

why do we have 2 places to set this and which will override the other?

this should be in one place or the other not both places.

**Comment by illori** [comment]
upon further testing the permission does not seem to work at all anyway.

it was added with https://github.com/SimpleMachines/SMF2.1/commit/6261424eb0b7c27652e8cf7ebf0d1cfc2e2efe83 and there is nothing more then a permission added and nothing that hooks into it.

https://github.com/SimpleMachines/SMF2.1/commit/f8cff26430e427f6bd562fb98cc8587279549820 seems to try to add the hooks so the permission would work, but it does not. i can check the permission to disable word censor and allow users to turn off word censoring on current theme and the user can still see the option in their profile -> look and layout

**Comment by emanuele45** [comment]
You are reading it the other way around. :P 
It was added in the second commit you referenced, that is 2 years old and is one of the first imports from SVN (a bunch of cherry-picks), see:

```
! Moved word censor option to a permission (Profile-Modify.php, Subs.php, ManagePermissions.php, Profile template, Settings template, ManagePermissions langauge) [Feature 4738]
```

And something was added back (probably removed by a git hiccup) by the first one you are referencing.

Hide it from the profile may be tricky, at least it should not be saved.
Try changing this code:

```
            // Only let admins and owners change the censor.
            elseif ($opt == 'allow_no_censored' && !$user_info['is_admin'] && !$context['user']['is_owner'])
                    continue;
```

to

```
            // Only let admins and owners change the censor.
            elseif ($opt == 'allow_no_censored' && !$context['allow_no_censored'])
                    continue;
```

**Comment by illori** [comment]
well it still exists under current theme, so it should be removed from there is a permission should exist for it. but why do we need a permission for this? just to annoy admin that they need to go and set the permission for each group when they upgrade?

**Comment by emanuele45** [comment]
http://dev.simplemachines.org/mantis/view.php?id=4738

**Comment by illori** [comment]
then it was not done completely and IMO it should not be a permission, it will just be more confusing for admin then it already is.

**Comment by emanuele45** [comment]
Well, then we are 1 pro, 1 against and a half implemented feature.
It should be fine. :tongue:

**Comment by Oldiesmann** [comment]
I honestly think we should kill the permission and move the "allow users to disable the word censor" setting to a global option. It makes no sense to have it as a theme setting (if you want to allow them to disable it, you likely want that functionality regardless of the theme being used), and I can't think of a reason why it needs to be a permission either.

**Comment by illori** [comment]
sounds good to me.
