### ISSUE TITLE
Installer warning - Cookie names must not be empty

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6022]
#### Description
Warning
: Cookie names must not be empty in
D:\EasyPHP\van21\Sources\Subs-Auth.php
on line
862

![image](https://user-images.githubusercontent.com/23568484/74678213-3758af00-516f-11ea-8234-e29939f5e1e3.png)

~~The DB files are not created or populated.  You cannot load the forum, you get:~~
(EDIT: the files are in fact created...)

### Steps to reproduce
1. Install vanilla 2.1 

### Environment (complete as necessary)
- Version/Git revision:  Now
- Database Type:  Mysql
- Database Version:  5.7
- PHP Version:  7.3

**Comment by Sesquipedalian** [comment]
> The DB files are not created or populated

Just to make sure I understand clearly, you mean by this that the database tables are not created during the install, right? 

Assuming so:

1. Can you confirm for me that they are in fact missing in the database? 

2. Did the database population step run during the installation process? 

3. Were any errors reported during the database population step?

**Comment by sbulen** [comment]
Correct,  they are missing.
It looked like it ran (you dont get a lot of details, like with the upgrader)...
The only message was the one reported above.

**Comment by MissAllSunday** [comment]
I can reproduce the issue but on my case the tables are created normally it just the cookie that doesn't get created.

**Comment by sbulen** [comment]
I provided a dbname, didn't use its default.  

One thing that we sometimes saw testing the new approach was that the db was actually created, but with the wrong name.  Working now, can't confirm if that's what is happening here.

**Comment by sbulen** [comment]
Just re-tested - DB is fine this time.  It's just the warning.  

(In hindsight, the 2nd error above was clearly due to a typo...  Sorry about the confusion...)

**Comment by sbulen** [comment]
FYI - This issue is still open - I got this attempting an install today:
![image](https://user-images.githubusercontent.com/23568484/77586280-25230c80-6ea3-11ea-98c0-c6d23b554494.png)
