### ISSUE TITLE
BBC nit - list & li

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6023]
#### Description
The list & li BBC codes are enabled separately, but neither work properly unless both are enabled.  Behavior is inconsistent.  

### Steps to reproduce
**_SCENARIO 1:_** Both enabled; both buttons visible in editor; both work:
![image](https://user-images.githubusercontent.com/23568484/74680843-ba313800-5176-11ea-93eb-44c1623b0272.png)
![image](https://user-images.githubusercontent.com/23568484/74680854-bef5ec00-5176-11ea-9132-aa6377af91c6.png)

**_SCENARIO 2:_** li enabled, list disabled; neither button visible in editor; all lists (numbered or not) appear as bullets:
![image](https://user-images.githubusercontent.com/23568484/74680875-cb7a4480-5176-11ea-8c1d-c1b3881eb61c.png)

**_SCENARIO 3:_** list enabled, li disabled; both buttons visible in editor; neither work:
![image](https://user-images.githubusercontent.com/23568484/74680901-db922400-5176-11ea-98ed-174d7505fc52.png)

### Environment (complete as necessary)
- Version/Git revision: Now
- Database Type: MySQL
- Database Version: 5.7
- PHP Version: 7.3

### Additional information/references
Issue exists for both 2.1 & 2.0.  Initially reported here:
https://www.simplemachines.org/community/index.php?topic=547426.0

**Comment by sbulen** [comment]
My suggestion is to keep it simple. One setting affects both buttons/features.  I'm not sure it makes sense to enable/disable li separately from list...

**Comment by Sesquipedalian** [comment]
Yeah, that should be controlled with a single setting. We should probably do the same for the table-related ones, too.
