### ISSUE TITLE
Mail - salutation sometimes in wrong language

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6028]
#### Description
From this reported issue:
https://www.simplemachines.org/community/index.php?topic=571923.0

### Steps to reproduce
1. Set up 3 different users, in different languages
2. All 3 should be setup to receive mail notifications (straight away); have them all follow the same topic
3. Take turns posting posting from the different languages
4. This is an intermittent problem - it works fine, most of the time, but sometimes the salutation is in the wrong language

### Environment (complete as necessary)
- Version/Git revision:  Today
- Database Type:  Mysql
- Database Version:  5.7
- PHP Version:  7.3

### Additional information/references
Notice the "regards" instead of "saludos":
![image](https://user-images.githubusercontent.com/23568484/75122157-93c83c80-564f-11ea-96d9-5c98543f179b.png)

**Comment by live627** [comment]
This is addressed in #6024 specifically https://github.com/SimpleMachines/SMF2.1/pull/6024/commits/3f5380fb6d2ab29a9ca648f44605addf673028bc

but then there is some code overlap between that pr and #6025
