### ISSUE TITLE
Checking if guest in advanced options of package manager

### ISSUE THREAD

**Issue by Acans** [SimpleMachines/SMF#603]
http://www.simplemachines.org/community/index.php?topic=510848.0

"It's for the collapsible panel in the emulate area of the package manager which is also apparently referred to by 'advanced options'.

It's just silly that it even checks if it's a guest because if it's in the admin panel, doing a package manager thing, it ain't gonna be no guest. No security risk, no real issue, just struck me as funny that it should be doing this." - Arantor

**Comment by illori** [comment]
strange this did not get closed when the PR was merged

**Comment by XinYenFon** [comment]
I'm not sure GitHub supports Fix for #issue-number - I'm even not sure its supporting titles for that feature needs to write required word to comment section.

**Comment by emanuele45** [comment]
Found this:
https://help.github.com/articles/closing-issues-via-commit-messages

Oh well...
/me clicks "Close & Comment"

**Comment by Acans** [comment]
Perhaps it didn't close because it was a Sunday.
- Snow is lazy on Sunday's too

**Comment by emanuele45** [comment]
lol

Possible! :P

**Comment by Acans** [comment]
emanuele, I found out why!

https://github.com/blog/1386-closing-issues-via-commit-messages

Has to be merged into master to close the message, since we do to release it doesn't work.

**Comment by illori** [comment]
well it always has worked before with the release branch.

**Comment by Oldiesmann** [comment]
Per the link @Acans referenced, it only works if you include "close", "closes", "closed", "fixed" or "fixes". "Fix for" doesn't trigger it.

**Comment by emanuele45** [comment]
The default branch here is not master, but release-2.1, and it was not closed automatically because the list of keywords that trigger the auto-close are:

```
close
closes
closed
fix
fixes
fixed
resolve
resolves
resolved
```

as written in the github article I linked above. ;)
