### ISSUE TITLE
Database Error: Data too long for column 'log_type' 

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#6031]
#### Description
If language strings are created for WaitTime_broken for modifications, the length for column log_type in table *_log_floodcontrol is too small. This should be increased from 8 to 16.
### Steps to reproduce
1.
look here https://www.simplemachines.org/community/index.php?topic=203471.msg4047900#msg4047900

2. 
```
 Type of error: Database
Database Error: Data too long for column 'log_type' at row 1


			REPLACE INTO smf_log_floodcontrol(`ip`, `log_time`, `log_type`)
			VALUES
				(unhex('00000000000000000000000000000001'), 1582827357, 'downloads')
 http://localhost/xxx/xxx/index.php?action=downloads;sa=comment&amp;id=1
 /var/www/html/xxx/xxx/Sources/Security.php (Line 1203)
```

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1 RC2
- Database Type:  MYSQL
- Database Version: 5.7.28-log
- PHP Version: 7.3.14

**Comment by albertlast** [comment]
Why 16?

**Comment by wintstar** [comment]
Just a suggestion. Can also be less.

**Comment by albertlast** [comment]
i would suggest to raise this to 30.
