### ISSUE TITLE
Login Problem at simplemachines.org

### ISSUE THREAD

**Issue by KitchM** [SimpleMachines/SMF#6038]
Evidently, because of my own loss of personal records somewhere, I cannot log in to the web site any longer, and that includes the community forum.  I don't have the correct password.  It also appears that my old email address is getting the reset message.  Sadly, my old mail servers are shut down, so I don't get mail there.  Please advise as to the correct method for changing my email address.

Thank you for your help.

**Comment by shnazzle** [comment]
Hey. Methinks you've come to the wrong place for product support. This is for actual defects and new features. 
You want the support forum:
https://www.simplemachines.org/community/index.php

**Comment by KitchM** [comment]
Thanks, good buddy, but I couldn't find a contact email address anywhere.

**Comment by Pipke** [comment]
> Thanks, good buddy, but I couldn't find a contact email address anywhere.

https://www.simplemachines.org/about/contact.php

**Comment by KitchM** [comment]
You're the man!  Many thanks.

**Comment by smfbigguy** [comment]
Please close this.
