### ISSUE TITLE
Alerts notification top menu not getting marked read, after read

### ISSUE THREAD

**Issue by Pipke** [SimpleMachines/SMF#6039]
Alerts notification (top menu) not getting marked read when you have been on the notification. Example when the alerted post is approved without click from top to the post, also if some one else have approved it or when you have seen the alert post where you have been mentioned etc. Infact it should been auto mark read then , just like the new posts icon, or do i think wrong here in your eyes.

**Comment by SychO9** [comment]
What version are you using, if from github what exact commit ?

**Comment by MissAllSunday** [comment]
Hi @Pipke Can you please tell us some more details about this issue? Theres a nice template for reporting bugs at https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/.github/ISSUE_TEMPLATE/standard_bug.md  which really help us narrowing down envs to tests this for confirmation.

**Comment by SychO9** [comment]
Don't think this is valid anymore, sesquiledalian added code that marks all related alerts to the topic you view as read.

**Comment by Pipke** [comment]
> Don't think this is valid anymore, sesquiledalian added code that marks all related alerts to the topic you view as read.

true, new option is added.(havent test if it works, guess the devs did;) )
![image](https://user-images.githubusercontent.com/31970508/88107911-3c9ba900-cba8-11ea-901b-02421e7c8a9b.png)
