### ISSUE TITLE
Funky active branch

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6045]
#### Description
Is this here for a reason or should it get cleaned up?  Not sure, just checking...

![image](https://user-images.githubusercontent.com/23568484/77116691-c87ca900-69ed-11ea-9bf2-086540c47cad.png)

**Comment by jdarwood007** [comment]
Looks like from a revert that occurred.  Just deleted it.

**Comment by sbulen** [comment]
Perfect.  Closing...
