### ISSUE TITLE
reCaptcha stopped working

### ISSUE THREAD

**Issue by mastum** [SimpleMachines/SMF#6056]
#### Description
No errors in logs, keys are valid, no changes have been made to code or settings. It just fails with "invalid captcha value" when clicking submit now, even with a green checkbox.

More info: https://www.simplemachines.org/community/index.php?topic=572333.0

### Steps to reproduce
1. Activate reCaptcha v2 antispam
2. Try to register a new user

### Environment (complete as necessary)
- Version/Git revision: 6103f5842c8ae3dc23455be910255ae8b479c504
- Database Type: MariaDB
- Database Version: 10.1.44
- PHP Version: 7.3.6

**Comment by dhmyrdal** [comment]
This happened suddenly with no change on our servers, about March 17h might be some change on Google's side?  Google admin console indicate that a "normal" 50% of attempts are rejected.

Long term SMF could support reCaptcha v.3 ?
