### ISSUE TITLE
MySQL 8.0 The storage engine for the table doesn't support descending indexes

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#6066]
#### Description
Saw this on SMF site this user ran into an issue upgrading their forum
https://www.simplemachines.org/community/index.php?topic=572637.0

Seems like it is an issue with MySQL 8.0.  table needs to be Innodb
https://www.percona.com/blog/2016/10/20/mysql-8-0-descending-indexes-can-speedup-your-queries/

### Environment (complete as necessary)
- Version/Git revision: Latest
- Database Type: MySQL
- Database Version: 8.0.18
- PHP Version: 7.3

### Additional information/references

**Comment by albertlast** [comment]
the problem is,
that mysql 8.0 is the first mysql version how support desc index,
all mysql before ignore this
Second problem is that we still keeping myisam for the upgrade stuff instead of using innodb.

**Comment by sbulen** [comment]
THAT's funny.  Yes, it just simply ignored it, no error or warning or anything.  The index is actually created, but the DESC clause has been ignored all this time...

I guess MYSQL 8 makes that a hard error now.  How thoughtful.  

Given that most of us have never actually seen that work DESC, I'm not sure it's really needed.  _My suggestion for now is to simply drop the DESC._  

I pleaded the case to have the upgrader convert to InnoDB a while back & lost.  You frequently get a mix of engines today.  Today, I am truly concerned with how complex the upgrader is already...

Any problem with just removing the DESC clause?

**Comment by albertlast** [comment]
that is mysql.

I got no problem so long you don'T try to hurt postgres here.

**Comment by jdarwood007** [comment]
We should not convert MyISAM to InnoDB. That should be left up to the admin.  New installs can default to InnoDB.  The admin may have reasons for running a different engine.  We shouldn't make assumptions during upgrades.

**Comment by albertlast** [comment]
I don't beliefe that the common admin had a reason for this,
it's only there because he had install smf for some time ago and since them he upgrade.

**Comment by sbulen** [comment]
> We should not convert MyISAM to InnoDB. That should be left up to the admin. New installs can default to InnoDB. The admin may have reasons for running a different engine. We shouldn't make assumptions during upgrades.

Correct, I am not for adding more complex steps to the upgrader...
