### ISSUE TITLE
Error log display

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6071]
#### Description
Something happened to the display of the error log, I hadn't seen this before.  The individual entries exceed the boundaries of the page.

### Steps to reproduce
1. Look at errors...

### Environment (complete as necessary)
- Version/Git revision:  Today
- Database Type:  MySQL
- Database Version:  5.7
- PHP Version: 7.3

### Additional information/references
![image](https://user-images.githubusercontent.com/23568484/79172547-e7cae400-7da9-11ea-9ca5-49497aeb7ec3.png)

**Comment by Oldiesmann** [comment]
It's because of the long filename

**Comment by SychO9** [comment]
hmm, weird I remember someone added a CSS rule to address that.

**Comment by XinYenFon** [comment]
I do recall we fixed this as well

**Comment by sbulen** [comment]
Screenshot from last week...
