### ISSUE TITLE
Privacy policy support

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#6075]
We need to port the privacy policy system forward from 2.0.16+, including the system that records the user's acceptance of the registration agreement and privacy policy and prompts for re-acceptance when they change. The code from 2.0.x will need some changes in order to work in 2.1.

**Comment by MisterVector** [comment]
I'm going to see if I can take a stab at this. I'd really love to help this project reach RC3!

**Comment by Sesquipedalian** [comment]
That'd be lovely, @MisterVector. Thanks for pitching in! 😊

A couple of notes:

1. Please make sure that your implementation works as closely as possible to the implementation in 2.0.16+. Ideally, you will start with the 2.0 code and adjust it just as necessary to make it work in 2.1.

2. A key requirement is that upgrading from 2.0.16+ to 2.1 must preserve not only the privacy policy itself (in multiple languages where applicable) but also the records of when the privacy policy and registration agreement were last updated (again, for each language as applicable) and the records of when each user last accepted the registration agreement and privacy policy.

**Comment by MisterVector** [comment]
I actually don't have really any knowledge of the SMF codebase. Currently I'm doing a diff of 2.0.15 to 2.0.17, grabbing all relevant changes from there, and replicating that into my SMF 2.1 fork. Then I'll see if there are any changes to be made to that code for it to work with SMF 2.1. I suppose I also need to add migration logic for the upgrade process too?

**Comment by Sesquipedalian** [comment]
> I actually don't have really any knowledge of the SMF codebase. Currently I'm doing a diff of 2.0.15 to 2.0.17, grabbing all relevant changes from there, and replicating that into my SMF 2.1 fork. Then I'll see if there are any changes to be made to that code for it to work with SMF 2.1.

Yeah, unfortunately we are not (yet) able to make the SMF 2.0.x codebase publicly available due to arcane legal complications, so I can't give you direct access to see the code changes that were involved. However, to make things easier for you, I've attached a diff that *should* show all the changes relevant to the privacy policy system.

[SMF_2-0_privacy_policy.diff.txt](https://github.com/SimpleMachines/SMF2.1/files/4548045/SMF_2-0_privacy_policy.diff.txt)

As you look at that, you'll notice references to a `force_gdpr` setting that controls various behaviours when enabled. In SMF 2.1 we are not using that setting; our goal instead is to code all behaviour to comply with the GDPR at all times. So whenever you see references to that setting in the diff, please implement the behaviour in 2.1 as if that setting were always `true`.

Also note that:
1. SMF 2.1 has done away with the "Core Features" page, so any logic that was contained in that page needs to be either moved elsewhere or dropped (but see the previous paragraph).
2. A lot of old cruft has been cleaned out of the 2.1 theme files compared to the 2.0 theme files. So when you see things like `<span class="topslice"><span></span></span>` in that diff file, you won't want to blindly copy that over into the 2.1 theme files. Instead, do your best to follow the conventions in the 2.1 theme. 🙂 

>  I suppose I also need to add migration logic for the upgrade process too?

If you need to make any changes to the database, whether to its structure or to the information stored in it, then yes. However, if you stick as closely as possible to the 2.0.x implementation, you probably won't need to do that.

**Comment by MisterVector** [comment]
Alright, then I shouldn't need to update the upgrade script at all. I want to keep this as simple as I can. And thanks for the diff, it's really helpful but I already have kdiff3 open to do the necessary comparisons.

**Comment by MisterVector** [comment]
I'd like to keep things as simple as I can make them. Thanks for the tips!

**Comment by MisterVector** [comment]
In process of testing my changes. Unfortunately, I tried to use the latest XAMPP which has MariaDB support, but during the install there was an error. Turns out the messages table could not be created. So I went back to a version of XAMPP that used MySQL. If it is your desire to support MariaDB I can create a separate issue in regards to my experience trying to use MariaDB.

Edit: The context here is an SMF 2.0.17 installation that has the error. Not sure if the latest SMF 2.1 development state has the error.

**Comment by MisterVector** [comment]
@Sesquipedalian so when I see code like this:

```
<div class="righttext">', empty($context['force_gdpr']) ? '
						<label for="minor_edit"><input type="checkbox" value="" id="minor_edit" name="minor_edit" tabindex="' . $context['tabindex']++ . '" class="input_check" /> ' . $txt['admin_agreement_minor_edit'] . '</label>' : '', '
```

In 2.0.16, the label and input fields would only show up if the force_gdpr setting was false, but in this case should I assume it's true and always show the label and input?

**Comment by Sesquipedalian** [comment]
Hi @MisterVector. I just saw your comments above. 

Regarding the installation problem with 2.0.17 and MariaDB, thanks for that report. We’ll log that in our 2.0 bug tracker.

Regarding your question, we can discuss that in the PR you’ve since submitted. :)
