### ISSUE TITLE
issue warning because of message

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#608]
a lot of people will think this feature has been removed in 2.1 as it is in the drop down from the users name, it makes no sense. why would i want to go in that drop down to issue a warning for a post that was made? i would not, i want the option in my face so i can easily see it.

**Comment by Arantor** [comment]
If it's going to be in a dropdown, it should be in the one in the post (the More... dropdown)

**Comment by illori** [comment]
that is a better location, but i think the location it is in, in 2.0 would be fine as well.

**Comment by Arantor** [comment]
The aesthetic view of 2.1 is all about 'minimalism to the user'. Moving the button to the other menu certainly fits that.

**Comment by illori** [comment]
it might be but how many people will actually like that style? i guess we will find out once 2.1 goes beta and people try to use it and start complaining.

**Comment by Arantor** [comment]
I don't have a problem with that. Constructive feedback does help it improve.

**Comment by illori** [comment]
yep and i hope all of our developers will agree and make changes if they are required.
