### ISSUE TITLE
Upgrade database from 2.0 fail in smf_settings

### ISSUE THREAD

**Issue by gayratv** [SimpleMachines/SMF#6085]
#### Description
--during php upgrade.php error was on smf_settings upgrade--

Error was on this record:

variable = attachmentUploadDir
value:
a:5:{i:1;s:58:"/var/www/admin/data/www/forum.woodtools.ru/frm/attachments";i:2;s:59:"/var/www/admin/data/www/forum.woodtools.ru/frm/attachments1";i:3;s:59:"/var/www/admin/data/www/forum.woodtools.ru/frm/attachments2";i:4;s:59:"/var/www/admin/data/www/forum.woodtools.ru/frm/attachments3";i:5;s:55:"/var/www/admin/data/www/forum.woodtools.ru/files/Attach";}

Error : can't convert to JSON

I'm fix it to left only one directory

### Steps to reproduce
1. I'm have about 300 000 attachments in 4 folders
2. run php upgrade.php

### Environment (complete as necessary)
- Version/Git revision: latest from git
- Database Type: MySQL
- Database Version: 8
- PHP Version: 7.3

### Additional information/references

**Comment by sbulen** [comment]
As noted here, you weren't running the upgrader, you attempted to run the installer.   

 Once you tried the upgrader, it worked,  correct?

I think this should be closed.


https://www.simplemachines.org/community/index.php?topic=572888.msg4053258#msg4053258

**Comment by gayratv** [comment]
No, I'm wrote that I'm start process from blank - import database and so on.
I'm run php upgrade.php

**Comment by sbulen** [comment]
I cannot replicate this.   Multiple attachment directories, 2.0=>2.1, mysql8, php7.3.

Before (serialized string):
`a:4:{i:1;s:32:"D:\EasyPHP\80van2021/attachments";i:2;s:33:"D:\EasyPHP\80van2021/attachments2";i:3;s:33:"D:\EasyPHP\80van2021/attachments3";i:4;s:33:"D:\EasyPHP\80van2021/attachments4";}
`

After (json):
`{"1":"D:\\EasyPHP\\80van2021\/attachments","2":"D:\\EasyPHP\\80van2021\/attachments2","3":"D:\\EasyPHP\\80van2021\/attachments3","4":"D:\\EasyPHP\\80van2021\/attachments4"}
`

Your input string is valid, so it wasn't a problem with your setting.

**Comment by pouvik** [comment]
I have managed to update a similar size attachment files with no issues, could it have been a broken table in the OP's db?

**Comment by gayratv** [comment]
May be problem in collation ?
Collation for smf_settings was cp1251_general_ci
I'm attach backup for smf_settings table.
May be it help to reproduce error.

[smf_settings.txt](https://github.com/SimpleMachines/SMF2.1/files/4665071/smf_settings.txt)

**Comment by MissAllSunday** [comment]
There is indeed an issue with your serialized data (Error at offset 9 of 366 bytes) but upgrade.php does check against !== false and according to the PHP manual unserialize() should return false for conditions such as malformed data.

Might be good to add an extra check to ensure we are really working with valid data before trying to json_encode on it

**Comment by sbulen** [comment]
After numerous efforts to reproduce, I can't.  

Try with the latest versions.  If still an open issue, please provide more info.
