### ISSUE TITLE
Database error: ERROR:  operator does not exist: inet ~~ unknown

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#6087]
#### Description
Using a revision from 6 months ago.
Had a couple of errors caused by a single (guest) user. Clicked on the IP filter icon in the ACP Error Log screen, then clicked the "<s>Remove selected</s>Remove all filtered results" button. Result:
```
Type of error: Database error
Database error: ERROR:  operator does not exist: inet ~~ unknown
LINE 3:    WHERE ip LIKE '1.2.3.4'
                    ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
https://forum.[...].de/index.php?action=admin;area=logs;sa=errorlog;desc;start=15;filter=ip;value=1.2.3.4
/home/[...]/public_html/Sources/ManageErrors.php (line 358)
```

### Environment (complete as necessary)
- Version/Git revision: Github version from around 2019-10-11, maybe af31e402a6d5172304dae403b8268ebd8ccff75d
- Database Type: postgres
- Database Version: 9.4.26-0+deb8u1
- PHP Version: 5.6.40+dfsg-0+deb8u10

**Comment by smfbigguy** [comment]
You should probably update what you are running and see if the error is still there. There have been a lot of changes in 6 months.

**Comment by albertlast** [comment]
Please test #6088

**Comment by m4z** [comment]
Edit: Correction, I didn't click "Remove selected" but "Remove all filtered results".

**Comment by m4z** [comment]
> You should probably update what you are running and see if the error is still there. There have been a lot of changes in 6 months.

Yeah, thanks, I know…
