### ISSUE TITLE
implode(): Invalid arguments passed

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#6090]
#### Description
Viewing the RSS feed for a board causes an "implode(): Invalid arguments passed" error

### Steps to reproduce
1. View the RSS feed for a board
2. Check the error log

### Environment (complete as necessary)
- Version/Git revision: Latest as of this report
- Database Type: MariaDB
- Database Version: 10.2.31
- PHP Version: 7.4.5

### Additional information/references

```
2: implode(): Invalid arguments passed
File: /.../smfgit/Sources/News.php
Line: 229
URL of page causing the error: https://smfgit.oldiesmann.us/index.php?action=.xml;type=rss2;board=1
```

**Comment by Sesquipedalian** [comment]
Fix is forthcoming shortly.
