### ISSUE TITLE
Wrong value type sent to the database

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#6091]
#### Description
![1](https://user-images.githubusercontent.com/229402/80488613-0ddeaf80-8978-11ea-82d3-30d4a83ec9d5.png)
![2](https://user-images.githubusercontent.com/229402/80488622-11723680-8978-11ea-9f7f-e89e4aabaf7c.png)

### Steps to reproduce
1.  ~Go to Profile -> Actions -> Download profile data -> Run export~
2. ~Get an error in the Error log, without IP (`Database Error: 'smf_home.pm.msgtime' isn't in GROUP BY`)~ ~ ← *Separate issue*
3. Go to Profile -> Profile info -> Track User -> Activity and get an error:
`Wrong value type sent to the database. IPv4 or IPv6 expected.(ip_list) `

### Environment (complete as necessary)
- Version/Git revision: 6cda6d8e1c3b65ce80ab75de519e327b283196b2
- Database Type: MariaDB
- Database Version: 10.4.12
- PHP Version: 7.2.29

### Possible solution, in Profile-View.php, line 2056, make a little check:
~`		if (!empty($row['ip']))
			$ips[] = $row['ip'];`

**Comment by Sesquipedalian** [comment]
Label removed because this has nothing to do with exports.

**Comment by Sesquipedalian** [comment]
This appears to be two distinct issues:
1. The error that occurred during the export.
2. The error that occurred when trying to track activity.

~@dragomano, please open a separate bug report for the second issue. Meanwhile, I will edit the description above to refer only to the first issue.~ See below.

**Comment by Sesquipedalian** [comment]
On second thought, I've edited this issue to refer to the error that arose when you went to Track Activity. Please disregard my previous request, @dragomano, and instead create a separate issue for the error you encountered during export.
