### ISSUE TITLE
Abracadabra in the filename with export results

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#6092]
#### Description
There is a problem when the filename with export results contains non-English characters.

### Steps to reproduce
0. Create a non-English forum name
1.  Go to Profile -> Download profile data -> Run export, wait for a some time
2.  See the result with strange characters

### Environment (complete as necessary)
- Version/Git revision: 6cda6d8e1c3b65ce80ab75de519e327b283196b2
- Database Type: MariaDB
- Database Version: 10.4.12
- PHP Version: 7.2.29

### Additional information/references
![3](https://user-images.githubusercontent.com/229402/80488740-45e5f280-8978-11ea-872c-dcc8ec799ecc.png)

**Comment by Sesquipedalian** [comment]
Thanks for the report. Shouldn't be too hard to fix.
