### ISSUE TITLE
please fix indonesian language package

### ISSUE THREAD

**Issue by Saepulawr** [SimpleMachines/SMF#6109]
I found bugs in the file ModerationCenter.indonesian.php: 31
so it can't open the moderation page.

just change it
$ txt ['mc_seen'] =% 1 $ s last seen% 2 $ s;
Becomes
$ txt ['mc_seen'] = '% 1 $ s last seen% 2 $ s';

thank you

**Comment by m4z** [comment]
I'll look into it.

**Comment by m4z** [comment]
We're currently in the process of switching to another translation tool. I've fixed the string in the old tool; the new tool apparently wasn't affected.

I'm not sure if the language files are still updated from the old tool. If so, the fix should be released with the next daily update. Do you know how to update your languages files?

Alternatively, you can edit the file in your installation via FTP or SSH.

**Comment by Saepulawr** [comment]
yes i know how to update language files.
thank you for replying :)
