### ISSUE TITLE
Memcache errors

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6110]
#### Description
#5969 I didn't notice that it introduced an error.
We should not call ->connect() during the loadCacheAPIs() call.  We should only call the isSupported(true) as we are checking that its supported and we are in test mode.  Test mode indicates we are not going to make any connections.  Outside of test mode we are attempting to use the caching engine and then may need to do more sanity checks.  On connect we finally attempt to connect to the caching engine.

@live627 Your thoughts here?

### Additional information/references
2: Memcache::connect(): Can't connect to :11211, php_network_getaddresses: getaddrinfo failed: Name or service not known (0)
8: Memcache::connect(): Server  (tcp 11211, udp 0) failed with: php_network_getaddresses: getaddrinfo failed: Name or service not known (0)

/Sources/CacheAPI-memcache.php (Line 76)

**Comment by live627** [comment]
Both memcache APIs recquire at least one server connected to give a version number.

**Comment by jdarwood007** [comment]
But if we don't have memcache setup, when we do this, we error out.

Maybe we can have version checks disable error handling, attempt a connect, then if it fails we simply provide a N/A or similar.

**Comment by Underdog-01** [comment]
The error occurs when not using memcache.
I just set up a secondary test forum using Apcu and these errors popped up.
How about just using error suppression on lines 76 & 78 of the mentioned file?
Unless someone knows a better way to see if there is a connection.

Oops.. my apologies Ms. González .. I just saw your PR.
Perhaps suppression is discouraged but it would be less editing & changes.
