### ISSUE TITLE
Static string "webmaster" should be language string

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#6122]
#### Description
If a user has not set an email address for himself and tries to request his password, we currently use a static string "webmaster" as link text to the email address of the forum admin.
```
$ grep -RC2 "to_ask_password" .
./Themes/default/languages/Profile.english.php-$txt['no_reminder_email'] = 'Unable to send reminder email.';
./Themes/default/languages/Profile.english.php-$txt['send_email'] = 'Send an email to';
./Themes/default/languages/Profile.english.php:$txt['to_ask_password'] = 'to ask for your authentication details';
./Themes/default/languages/Profile.english.php-
./Themes/default/languages/Profile.english.php-$txt['user_email'] = 'Username/Email';
--
./Sources/Reminder.php-	$row['email_address'] = trim($row['email_address']);
./Sources/Reminder.php-	if ($row['email_address'] == '')
./Sources/Reminder.php:		fatal_error($txt['no_reminder_email'] . '<br>' . $txt['send_email'] . ' <a href="mailto:' . $webmaster_email . '">webmaster</a> ' . $txt['to_ask_password'] . '.');
./Sources/Reminder.php-
./Sources/Reminder.php-[…]
```
For the sentence (basically constructed by `$txt['send_email'] . ' webmaster ' . $txt['to_ask_password']`) to make sense in German, the word would at least have to be capitalized (and should probably have a comma before the space following it). I assume problems in other languages are even worse. :wink:

**Comment by MissAllSunday** [comment]
Is it enough to just move it to a txt string or does it require a more robust txt where all those strings are included for translators to have more freedom when translating it?

**Comment by m4z** [comment]
I don't care either way. While we're at it, we could just go ahead and use `sprintf`. But I don't think keeping it separate for now would be a problem, given it's such a specific placeholder (but I basically know nothing about "non-western" languages, for lack of a better term on my part).

Plus, I believe there are already a couple more strings that are concatenated this way.
