### ISSUE TITLE
Unused variable $txt['attach_dir_files_missing']?

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#6132]
#### Description
I can't find it being used or constructed anywhere.

**Comment by SychO9** [comment]
It's used, language strings aren't always used in a straightforward way, this one for example is used like so:

in ManageAttachments.php the following function returns the status which can be `files_missing` which is later used in the same file to determin the language string

https://github.com/SimpleMachines/SMF2.1/blob/fa91d997ecb26b1c38c24394e67283945bcc0b2e/Sources/ManageAttachments.php#L2574-L2595

https://github.com/SimpleMachines/SMF2.1/blob/fa91d997ecb26b1c38c24394e67283945bcc0b2e/Sources/ManageAttachments.php#L2471-L2497

**Comment by m4z** [comment]
Thanks for checking and explaining!
