### ISSUE TITLE
Alert no longer marked read after clicking/viewing it

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#6136]
#### Description
Alerts used to get marked read when viewing them, the logic used to be that they take you to `?action=profile;area=showalerts;alert={id}` where it gets marked read and then it redirects to its targeted link, and if no link redirects to the alerts list.

Either way that ensured that the alert got marked read when clicked instead of having to manually do that every time. 

That doesn't work anymore, not sure what changed but they now no longer take to the alert route to mark it read, alert links take directly to the targeted link.

(The previous way of redirecting could have been made better, I should have just included `alert={id}`to the url and then intercepted that and marked the alert read on forum load instead of redirecting but I didn't think of it at the time)

At the moment only some message related alerts get marked read when viewing them.

### Steps to reproduce
1. Produce a non topic/message related alert.
2. View alert.
3. You have to manually mark it read.

**Comment by SychO9** [comment]
Also if by any chance this was intentional, then I don't think this block of code is of any use anymore

https://github.com/SimpleMachines/SMF2.1/blob/dcbbf523fa90d0b90f3ddd5a2e464f23f3111e4e/Sources/Profile-View.php#L658-L681

**Comment by BrickOzp** [comment]
This was changed in, but it does not say much about the background of the change.

commit c1c1cd0d43a706c5603175d70e7d801602d3aad3
Author: Jon Stovell <jonstovell@gmail.com>
Date:   Mon Oct 28 20:17:14 2019 -0600

    Improves efficiency looking up the correct URL an alert should link to
    
    Signed-off-by: Jon Stovell <jonstovell@gmail.com>

**Comment by Sesquipedalian** [comment]
I'll look into this.

**Comment by Sesquipedalian** [comment]
Apparently I got a bit trigger-happy changing the target URLs in the UI in c1c1cd0. Oops! 😅
Please test #6824 to confirm that it solves the issue.
