### ISSUE TITLE
Notification polling stopped working

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#6137]
#### Description
I noticed for a while now that notification polling no longer works, it used to update in real time since there is the javascript code for that, but it doesn't work anymore now. At least not from what I can see.

I tested multiple times to make sure as well.

### Steps to reproduce
1. Have two accounts open at the same time
2. Produce alert from account A (make sure the alert is targeted towards account B)
3. Open account B tab
4. Watch the alert counter for a long time
5. Doesn't update
6. Refresh page
7. It updates

**Comment by sbulen** [comment]
I think this is part of issue #6102

**Comment by SychO9** [comment]
I don't think so, in my tests when I was watching for http requests in the console, the usual notification polling requests never even happened. So this might be an issue with the javascript code.

**Comment by SychO9** [comment]
Ah never mind, it's intended behavior.

When the browser blocks notifications on the site, notification polling is auto disabled on client side.
