### ISSUE TITLE
Post calendar even page produces errors

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#6139]
#### Description
```
Type of error: General
2: timezone_transitions_get() expects parameter 1 to be DateTimeZone, bool given
 http://.../index.php?action=calendar;sa=post
 .../Sources/Calendar.php (Line 445)
```
```
Type of error: General
2: timezone_open(): Unknown or bad timezone (0)
 http://.../index.php?action=calendar;sa=post
 .../Sources/Calendar.php (Line 445)
```

### Steps to reproduce
1. Go to Calendar > Post Event
2. Errors are thrown

**Comment by Oldiesmann** [comment]
What's your timezone set to? That code is only called if the event timezone isn't in the list generated by smf_list_timezones.

**Comment by Oldiesmann** [comment]
Not sure why this is happening... That code is only called if `$context['event']['tz']` isn't in the list of timezones generated by `smf_list_timezones()`. The event timezone is set from the `getUserTimezone()` function in Subs-Calendar.php, which, if nothing else, will default to whatever is returned by PHP's `date_default_timezone_get()` function.

What do you have selected for the default forum timezone (Admin -> Features and Options -> General) and your own timezone (under "Look and Layout Settings" in your profile)?

Also, what's shown for "Default timezone" in phpinfo?

**Comment by SychO9** [comment]
Can't reproduce this anymore for w/e reason, must have been something to do with my server configuration.

**Comment by SychO9** [comment]
> Not sure why this is happening... That code is only called if `$context['event']['tz']` isn't in the list of timezones generated by `smf_list_timezones()`. The event timezone is set from the `getUserTimezone()` function in Subs-Calendar.php, which, if nothing else, will default to whatever is returned by PHP's `date_default_timezone_get()` function.
> 
> What do you have selected for the default forum timezone (Admin -> Features and Options -> General) and your own timezone (under "Look and Layout Settings" in your profile)?
> 
> Also, what's shown for "Default timezone" in phpinfo?

Sorry didn't see your reply, I don't think that information matters now, I can no longer reproduce this, I'll still do some research and look into it in case it's a specific scenario that triggers this.

**Comment by SychO9** [comment]
Alright ! I was able to reproduce it, here are more details,

**User TimeZone:** Atlantic/Azores (idk how my user account got that timezone)

What happens is
1. that timezone doesn't belong to the `$context['all_timezones']` array so the condition on line 437 is met.
2. the `$context['all_timezones']` array has an element with a key of 0 (I believe that's the one causing the problem)

```
array (size=97)
  'UTC' => string 'UTC - Coordinated Universal Time' (length=32)
  0 => string '-----' (length=5)
  'Pacific/Midway' => string '[UTC-11:00] - SST - Midway, Pago Pago' (length=37)
  'Pacific/Niue' => string '[UTC-11:00] - Niue' (length=18)
  'Pacific/Rarotonga' => string '[UTC-10:00] - Rarotonga, Tahiti' (length=31)
  'Pacific/Honolulu' => string '[UTC-10:00] - HST - Honolulu' (length=28)
  'Pacific/Marquesas' => string '[UTC-09:30] - Marquesas Islands' (length=31)
  'America/Adak' => string '[UTC-09:00] - HDT - Aleutian Islands' (length=36)
  'Pacific/Gambier' => string '[UTC-09:00] - Gambier Islands' (length=29)
  'America/Anchorage' => string '[UTC-08:00] - AKDT - Alaska' (length=27)
  'Pacific/Pitcairn' => string '[UTC-08:00] - Pitcairn Islands' (length=30)
  'America/Los_Angeles' => string '[UTC-07:00] - PDT - Pacific Time (USA, Canada)' (length=46)
  ...
```

**Comment by Oldiesmann** [comment]
That should be easy to fix then
