### ISSUE TITLE
COPPA info link doesn't work

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#6147]
#### Description
To test the coppa language strings changed by #6121, I enabled coppa below a certain age, created an account below that age, and received the following mail:
```
Thank you for registering at My Community. Your username is […]. If you forget your password, you can change it at https://[…]/index.php?action=reminder

Before you can log in, the admin requires consent from your parent/guardian for you to join the community. You can obtain more information at the link below:

https://[…]/index.php?action=coppa;u=4

Regards,
The My Community Team.
```

When I click the info link at the bottom, I just get:
```
An error has occurred
You are not allowed to access this section
BACK
```
Even when accessing that link _as an admin_ with _any_ user ID, I receive the same error.

### Steps to reproduce
1. Enable coppa with age X
2. During registration of a new user, select "i agree to the terms and am less than X years old"
3. Receive "we need consent" mail after registration
4. Click info link in mail
5. See error (even as admin, with any user ID in the URL)

### Environment (complete as necessary)
- Version/Git revision: applies to HEAD

**Comment by Oldiesmann** [comment]
That's because it's looking for "member" and not "u".

Lines 725-727 of Register.php:
```php
	// No User ID??
	if (!isset($_GET['member']))
		fatal_lang_error('no_access', false);
```

It can be fixed either by changing the language string or by modifying the CoppaForm() function in Register.php (replace both instances of $_GET['member'] in that function with $_GET['u'])
