### ISSUE TITLE
Add support for Discord (Profile option)

### ISSUE THREAD

**Issue by mobasuite** [SimpleMachines/SMF#6157]
Maybe drop ICQ

**Comment by smfbigguy** [comment]
This should be posted on the forum and discussed.

**Comment by DiegoAndresCortes** [comment]
Thought ICQ was dropped?
I agree Discord should be an option instead of icq, but if icq was indeed dropped then I don't see it as relevant, could be added as a mod or profile field.

**Comment by mobasuite** [comment]
ICQ is still there.

**Comment by SychO9** [comment]
please use the custom profile fields feature to add any additional profile fields you want, you can also disable ICQ from there.
