### ISSUE TITLE
Error thrown when viewing a poll

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#6158]
#### Description
```
Type of error: General
8: Trying to access array offset on value of type null
 http://.../index.php?topic=1.0
 .../Sources/Display.php (Line 762)
```

### Steps to reproduce
1. Visit a topic that has a poll 

### Environment (complete as necessary)
- Version/Git revision: https://github.com/SimpleMachines/SMF2.1/commit/cad4ed3997fca35e94838e27f86609326cc716a1
- PHP Version: 7.4

**Comment by dragomano** [comment]
It seems, should be `$pollinfo['poster_name']` instead of `$row['poster_name']`

**Comment by SychO9** [comment]
yup, I haven't tested, but that seems at a first glance to be the case.
