### ISSUE TITLE
Browsing files in theme

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#6168]
#### Description
Language files that named like ".{lang_name}.php" (.english.php, etc) are not visible via "Browsing files in theme"

### Steps to reproduce
0. Install any mod with language files in separate dir (e.g. Optimus)
1. Go to Themes and layout / Modify Themes / Browse the templates and files in this theme / languages / Mod lang dir
2.  We'll see only index.php

**Comment by SychO9** [comment]
I haven't looked at the code, but I would assume it ignores any `.extension` files, because those are special type of files, so it probably treated the language files you're referring to the same way.

**Comment by illori** [comment]
we have a built in language file editor, why should we edit or view the language files from the theme editor?

**Comment by dragomano** [comment]
These files are not displayed in the language editor too. In any case, I use a text editor to edit them. This question is more theoretical.

**Comment by SychO9** [comment]
> These files are not displayed in the language editor too.

I don't see that as an issue tbh, the files have no name anyway. It's an edge case, we shouldn't always try to make up solutions for every case scenario (at least not at this point in time), rather, mod authors should avoid such edge cases.
