### ISSUE TITLE
http://localhost:8080/clean2/index.php?action=helpadmin;help=themes select default theme

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#617]
"Here you can select whether the default theme can be chosen, what theme guests will use, as well as other options. Click on a theme to the right to change the settings for it."

as of 2.0+ there is no option to outright allow/deny the users to select the default theme as there was in 1.1.*

but you can select which themes users can select from the check list when you click "show the list of themes"

**Comment by Oldiesmann** [comment]
So we need to change that to "Here you can select which theme guests will use, whether or not users can choose their own theme and, if so, which themes they can choose".

**Comment by illori** [comment]
sounds good to me

**Comment by ChainyEO** [comment]
Was the comment of Oldiesmann meant in jest? That sentence is quite a riddle.

**Comment by illori** [comment]
i dont think so, it actually explains how it works in 2.0+.

do you have a better option?

**Comment by ChainyEO** [comment]
I don't understand what you mean by this:

"as of 2.0+ there is no option to outright allow/deny the users to select the default theme as there was in 1."
- there's an option "Allow users to choose their own theme". If you tick this, then you are indeed allowing users to choose a theme that will become the default for them every time they log in.

I'm not sure I see much wrong with the original form of this string.

**Comment by illori** [comment]
in 1.1.\* there is a clear option in the admin panel that allows users to select the default theme or not, in 2.0 it does not exist any longer.

so the text is referring to the 1.1.\* version of the layout and not 2.0+.

**Comment by ChainyEO** [comment]
Sorry, I don't know what you mean. Are you referring to this:

"Here you can select whether the default theme can be chosen..."
- that means: "Here you can select whether users are able to choose their own theme or not (ie. select a theme that will become their default).

**Comment by ChainyEO** [comment]
"in 1.1.\* there is a clear option in the admin panel that allows users to select the default theme or not,"

I've never used 1.1, but I really don't get what you're saying by that. What does that actually mean?

**Comment by illori** [comment]
in 1.1.\* there are 2 options, Allow members to select their own themes. and Allow members to select the "Default" theme.

the help text is from 1.1.\* without changes in 2.0 you can via the checkboxes allow/deny any or all themes [but one] so the text does not IMO cover the changes in 2.0.

**Comment by ChainyEO** [comment]
If you don't allow users to select their own theme, then they HAVE to use the default, so there is no choice in the matter. That's what I don't get about what you're saying.

**Comment by illori** [comment]
the text is talking about the default theme not the forums default theme. in 1.1.\* the core theme or the curve theme in 2.0.*

yes if you dont allow users to change the theme they would end up with the forums default theme not the "default" theme.

in 2.0 you can allow or not allow a user to select the default theme by checking off curve in the list, but there is no option as in 1.1.\* that would disallow users from selecting the default theme [curve for 2.0]

**Comment by Oldiesmann** [comment]
In 1.1 you did not have the ability to specify whether or not a user could choose a theme that you had installed. If it was installed and users were allowed to select their own theme, they could choose it. The only exception was that you could check a box to not allow them to use the "default" theme.

In 2.0, you can choose which themes the user can choose. I reworded the sentence to make this clearer.

**Comment by ChainyEO** [comment]
Ok, I think that when I was translating the above, I just tried to make sense of it within the context of version 2.0+. 

The rewording done by Oldiesmann seems to be good now, though.
