### ISSUE TITLE
Upgrade Script Error

### ISSUE THREAD

**Issue by Butterflysaway** [SimpleMachines/SMF#6176]
![Error](https://user-images.githubusercontent.com/68415596/87755393-e9ef7500-c7d4-11ea-95cc-39ebb24abe5a.png)
#### Description
I have a very large smf 1.1.21 forum of over 1.5 million users.  I know I should've upgraded awhile ago due to security risks etc.  However, I have been very lazy.  I kinda got some energy lately to redo my old theme into the new SMF 2.1 latest (github) version and finally push the newest SMF running on the newest PHP 7.2.

### Steps to reproduce
1. Have a large forum > 1.5 million users
2. Upgrade from 1.1.21 to 2.1 (github version)

### Environment (complete as necessary)
- Version/Git revision: Latest SMF on github
- Database Type: MySQL
- Database Version: mysql  Ver 15.1 Distrib 10.2.19-MariaDB,
- PHP Version: 7.2

### Additional information/references
2020/07/17 02:06:50 [error] 9726#9726: *1574950 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16777224 bytes) in /var/www/**REMOVED**/**REMOVED**/public_html/upgrade.php(2134) : eval()'d code on line 33" while reading response header from upstream, client: **REMOVED**, server: **REMOVED**, request: "GET /newtest998/upgrade.php?step=3&amp;substep=0&amp;data=eyJjdXJzdGVwIjozLCJsYW5nIjoiZW5nbGlzaCIsInJpZCI6MTEyNiwicGFzcyI6Njg5MCwiZGVidWciOnRydWUsImpzIjoxfQ==&xml&filecount=3&substep=91&_=1594963621919&strict_step=51 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "**REMOVED**", referrer: "https://**REMOVED**/newtest998/upgrade.php?step=1&substep=0&data=eyJjdXJzdGVwIjoxLCJsYW5nIjoiZW5nbGlzaCIsInJpZCI6MTEyNiwicGFzcyI6Njg5MCwiZGVidWciOjAsImpzIjoxfQ=="

P.S. Sorry if this is a "noob" bug report.  I am new to github.

Fix #6177

**Comment by Butterflysaway** [comment]
I was able to manually fix the problem by modifying upgrade_2-1_mysql.sql

line 869
$limit = 100000; **to** $limit = 50000;

**Comment by Sesquipedalian** [comment]
I believe this has been fixed. If not, please reopen.
