### ISSUE TITLE
$context['login_cookie_times'] not defined when resetting forgotten password

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#6179]
#### Description
Saw this in the error log of one of the forums I run. Not sure if it's been fixed yet or not.

### Environment (complete as necessary)
- Version/Git revision: RC2, not sure which revision
- Database Type: MariaDB
- Database Version: 10.2.31
- PHP Version: 7.3.20

```
Type of error: General
Error message: 2: Invalid argument supplied for foreach()
File: /.../Themes/default/Login.template.php
Line: 58
URL of page causing the error: .../index.php?action=reminder;sa=setpassword2
Backtrace information
#0: smf_error_handler()
Called from /.../Themes/default/Login.template.php on line 58
#1: template_login()
Called from /.../Sources/Load.php on line 2479
#2: loadSubTemplate()
Called from /.../Sources/Subs.php on line 3279
#3: obExit()
Called from /.../index.php on line 154
```

I also have an "Undefined index: login_cookie_times" error on the same line.

**Comment by MissAllSunday** [comment]
Looks like it was already reported: https://github.com/SimpleMachines/SMF2.1/issues/4886 

It seems we still need to move the declaration earlier in the process and since the context var is basically constants theres no real harm in doing so.
