### ISSUE TITLE
Avatar/Attachment Upgrade failure - only some convert correctly

### ISSUE THREAD

**Issue by Butterflysaway** [SimpleMachines/SMF#6180]
#### Description
While upgrading from 1.1.21 the users avatars were only partially updated from attachments to the new custom_avatar folder.  No errors or warnings were produced via php.

My board has around 50,000 avatars, around 30890 avatars moved to the custom_avatar folder.  The rest stayed in the attachments folder and did not set attachment_type = 1 to the other 20,000+.  Hence now 20,000+ users that had avatars no longer do.

### Steps to reproduce
1. Have large board with lots of users and attachments/avatars.
2. Upgrade from 1.1.21 to 2.1 (github version)

### Environment (complete as necessary)
Version/Git revision: Latest SMF on github
Database Type: MySQL
Database Version: mysql Ver 15.1 Distrib 10.2.19-MariaDB,
PHP Version: 7.2

### Additional information/references

I will update this bug report soon when I figure out what's causing it.

**Comment by Butterflysaway** [comment]
Alright, this is a very complex bug that I believe you guys can fix.  I'm too lazy to.  I just made a script to manually convert the avatars.

I think it has something to do with the step count in your upgrade script, for example

you are querying the database for any attachments where attachment_type != 1 and you are setting some of the rows that convert to avatars to attachment_type = 1 and skipping some rows the next load since it's going based on the first query count but its skipping rows.  Perhaps that makes sense.  Good Luck.

**Comment by Butterflysaway** [comment]
also this bug affects even attachment, not just avatars.  It seems a good bit of the regular post attachments failed to convert to .dat at the end.

**Comment by Butterflysaway** [comment]
I have updated my other PR to include this bug fix aswell.  I double checked that it's working perfectly now by re-upgrading my large forum.  


(I decided to not be lazy because I really love your forum system and wish it could be finished soon for release)
![Untitled22](https://user-images.githubusercontent.com/68415596/87909071-86b04d80-ca35-11ea-9ae9-a4203713af59.png)

Fix: #6177

**Comment by DiegoAndresCortes** [comment]
Was this fixed by #6811 ?
@BrickOzp ?

**Comment by sbulen** [comment]
I do believe this has been addressed, across a couple PRs.  First, BrickOzp's, and also the other fixes after the smorg migration.  

The reported issues became more apparent with much larger DBs.  @Butterflysaway was correct.
