### ISSUE TITLE
gravatar not taking email address

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#6182]
#### Description
use my gravatar option does not select gravatar
### Steps to reproduce
enable gravatars for forum users is enabled, even tried to disable allowing storing an extra email address for gravatars
2. go in profile and selected option to use my gravatar, only the default avatar is showing.

### Environment (complete as necessary)
- Version/Git revision: HEAD is now at 8104e4328 Merge pull request #6178 from SychO9/fix_disabled_files
- Database Type: mariadb
- Database Version:
- PHP Version: 7.1.33

### Additional information/references

this is a fresh install from github, cache was not enabled.

also checked "Force Gravatars to be used instead of normal avatars?" and that did not force a gravatar to show.

**Comment by frandominguezl** [comment]
I couldn't replicate the issue. Fresh install as well.

![image](https://user-images.githubusercontent.com/10365222/88463105-92c26200-ceb0-11ea-8394-2d70bf0319e3.png)

**Comment by illori** [comment]
even if you dont fill in an email address and disable that feature i cannot get it to populate the avatar. 

![image](https://i.imgur.com/fWcPEh6.png)

**Comment by Butterflysaway** [comment]
Doesn't work for me either.

**Comment by frandominguezl** [comment]
> even if you dont fill in an email address and disable that feature i cannot get it to populate the avatar.
> 
> ![image](https://camo.githubusercontent.com/714c77931c40ddb6cffa9ddf05ad0f8854978987/68747470733a2f2f692e696d6775722e636f6d2f665763504568362e706e67)

That screen appares when you have "Allow storing an extra email address for Gravatars?" setting disabled. Can you verify it's enabled?

Admin > Forum > Attachment & Avatar > Avatar Settings > Allow storing an extra email address for Gravatars?

**Comment by illori** [comment]
I tried both and neither worked.

**Comment by BrickOzp** [comment]
Did you create a gravatar account with the same email address?

**Comment by illori** [comment]
Nope and it is not required.

**Comment by BrickOzp** [comment]
If you don't have registered a gravatar account and selected an avatar you get the default image. And that is the one you have on your attached image.

**Comment by illori** [comment]
Have you even tested this out? It seems very broken. The field does not
store the email address.

**Comment by BrickOzp** [comment]
Yes, I have tested it. I have registered a gravatar account and uploaded an avatar, just to test this.
It shows both for default email, and for special gravatar email.

**Comment by BrickOzp** [comment]
Did you enter the same email address for special gravatar email as you have for your smf account? In that case it does not store the email.

**Comment by illori** [comment]
I can't get an email address to be saved in the field. Also if you force
gravatar the gravatar does not show. Only the default avatar shows.

**Comment by BrickOzp** [comment]
If you don't have registered a gravatar account and uploaded an avatar, it will only show the default avatar.

**Comment by illori** [comment]
It used to show a random gravatar even if you don't have an account just
like it does here on GitHub.

**Comment by BrickOzp** [comment]
That can be customized in the admin settings.
Default image to show when an email address has no matching Gravatar

**Comment by illori** [comment]
I know that but I can't get it to work.

**Comment by BrickOzp** [comment]
I also found that if you enabled both "Force Gravatars to be used instead of normal avatars?" and "Allow storing an extra email address for Gravatars?" it will not save the email from extra email address for gravatar.
Could that be the problem you have experienced?

**Comment by illori** [comment]
That is part of it.

**Comment by BrickOzp** [comment]
I will look into that problem.
What is the url of the gravatar image showing in your forum.
Like http://www.gravatar.com/avatar/4ca8674ef9ba34380c194c9d17456b32?rating=PG&default=identicon&s=65

**Comment by illori** [comment]
Seems the default a simple, cartoon-style silhouetted outline of a person
does not work.

**Comment by illori** [comment]
It had none due to the default not working. Now I have the monster one
working. Which is fine for now, but we should fix the default option.

**Comment by BrickOzp** [comment]
From gravatar docs.
mp: (mystery-person) a simple, cartoon-style silhouetted outline of a person (does not vary by email hash)

So this option will not change depending on email address. All users without gravatar will have the same image
