### ISSUE TITLE
Unknown column b.id_board in where clause

### ISSUE THREAD

**Issue by Filiaes** [SimpleMachines/SMF#6186]
#### Description
I had to Update my smf to the nightly build due to the ReCaptcha issue described [here.](https://www.simplemachines.org/community/index.php?topic=572333.0)

I receive database errors since the update:

```
Art des Fehlers: Datenbank
Datenbankfehler: Unknown column 'b.id_board' in 'where clause'


			SELECT num_posts
			FROM foobar_boards
			WHERE id_board = 11
				AND 
			EXISTS (
				SELECT bpv.id_board
				FROM foobar_board_permissions_view AS bpv
				WHERE bpv.id_group IN (-1)
					AND bpv.deny = 0
					AND bpv.id_board = b.id_board
			)
			LIMIT 1
 https://foobar-users.de/index.php?action=.xml;type=atom;board=11
.../Sources/News.php (Zeile 197)
```

Backtrace:

```
Backtrace information
#0: smf_db_error()
Called from .../Sources/Subs-Db-mysql.php on line 489
#1: smf_db_query()
Called from .../Sources/News.php on line 197
#2: ShowXmlFeed()
Called from .../index.php on line 173
```

### Environment (complete as necessary)
- Version/Git revision: last_commit_8104e43
- Database Type: MySQL
- Database Version: 10.3.23-MariaDB-1:10.3.23+maria~stretch
- PHP Version: 7.1.33

### Additional information/references

Maybe it has something to do with the upgrade process, I had some issues like described in my post here:
https://www.simplemachines.org/community/index.php?action=post;quote=4063764;topic=558451.40;last_msg=4063765

**Comment by albertlast** [comment]
"As b" is missing in sql Statement from news line 197

**Comment by Filiaes** [comment]
Hi Albert,

thanks for the hint ... so it should be like this ?

```
array(
				'current_board' => $board As b,
			)
```

**Comment by albertlast** [comment]
Here https://github.com/SimpleMachines/SMF2.1/blob/8104e4328223106289fcb7719f85cb5ce88b1b1a/Sources/News.php#L192

**Comment by Filiaes** [comment]
Hi, I have still some error messages but for the type rss2 instead of atom now:

```
Art des Fehlers: Datenbank
Datenbankfehler: Unknown column 'b.id_board' in 'where clause'


			SELECT num_posts
			FROM foobar_boards
			WHERE id_board = 15
				AND 
			EXISTS (
				SELECT bpv.id_board
				FROM foobar_board_permissions_view AS bpv
				WHERE bpv.id_group IN (-1)
					AND bpv.deny = 0
					AND bpv.id_board = b.id_board
			)
			LIMIT 1
 https://foobar-users.de/index.php?action=.xml;type=rss2;board=15
 .../Sources/News.php (Zeile 197)
```
Backtrace:
```
#0: smf_db_error()
Called from .../Sources/Subs-Db-mysql.php on line 489
#1: smf_db_query()
Called from .../Sources/News.php on line 197
#2: ShowXmlFeed()
Called from .../index.php on line 173
```

**Comment by albertlast** [comment]
Make no sense,
since thie line of code of the error message is the same,
look like the changes of the fix got lost.

**Comment by Filiaes** [comment]
Sorry ... my fault. I overwritten it during some testing
