### ISSUE TITLE
Non-existing ID causes JS Type Error of getElementByID in admin.js

### ISSUE THREAD

**Issue by DelPoint** [SimpleMachines/SMF#619]
There is a JS code that could re-color some elements in #update_section container on the Administration Center page - this section appears when SMF announces updates, and shows a warning for admins about the new version.

There is an error in that JS code, because the markup sent by SMF update server changed.

Check the following code/file:
/Themes/default/scripts/admin.js has this line of code around line 101:
document.getElementById('update_table').style.backgroundColor = '#aa2222';

The problem is: there are no more any element with ID 'update_table' in the HTML document. 

This JS code was copied over from SMF1.x 'Admin.template.php' in which there was a table with the ID in question. SMF2.x uses Admin.template.php only for creating the outermost container #update_section in the markup - everything else downloaded from the SMF server - which doesn't send HTML element with that ID anymore.

That causes element is null error with the above code in "admin.js".

Cheers,

DelD.

**Comment by Oldiesmann** [comment]
Thanks for the info! I'll take a look at it and see if it can be removed :smile:
