### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Butterflysaway** [SimpleMachines/SMF#6192]
#### Description
Session invalid on login after failed login

### Steps to reproduce
1. Enter wrong username and password. Press Login
2. Try entering correct username and password on the screen telling you incorrect password.

### Environment (complete as necessary)
- Version/Git revision: Latest 2.1 github version
- Database Type: mysql
- Database Version:mysql latest
- PHP Version:7.2

**Comment by Butterflysaway** [comment]
turns out my browser had PHPSESSID set for session on .website.com and subdomain.website.com

Deleting the subdomain.website.com PHPSESSID session fixed the problem but unclear how this even got put there unless it was by the upgrade script as my website uses global sessions/cookies.  Either way I think you should add a check to not read the PHPSESSID if its not from the correct path e.g. subdomain.website.com should be ignored even if .website.com doesn't exist if globalCookies is set to true.

**Comment by Sesquipedalian** [comment]
Was the domain of the forum's URL `website.com` or `subdomain.website.com`?

**Comment by sbulen** [comment]
I cannot reproduce.

Since we haven't heard back on this one, I suggest closing.
