### ISSUE TITLE
Database error during run of cron.php

### ISSUE THREAD

**Issue by Butterflysaway** [SimpleMachines/SMF#6198]
#### Description
![dberror](https://user-images.githubusercontent.com/68415596/88469921-7c260600-cec4-11ea-8c66-14aae396a910.png)

### Steps to reproduce
1. Open website on browser and wait for cron.php to be called by the javascript.

### Environment (complete as necessary)
- Version/Git revision: 2.1 Latest
- Database Type: mysql
- Database Version: Ver 15.1 Distrib 10.2.19-MariaDB, for Linux (x86_64) using readline 5.1
- PHP Version: PHP 7.4.8

### Additional information/references
My forum was converted from 1.1.21 to 2.1 latest (github version).

I'm unsure if the upgrade script didn't rename a column correctly or what.  Either way I know it's a bug that needs fixed since my 1.1.21 forum worked fine now has an error every 5 minutes or so from cron.php.

Can someone let me know if this is a common bug that hasn't been fixed?

**Comment by Butterflysaway** [comment]
P.S. ignore my theme, It's not quite done yet. And yes, the error triggers on the default theme too.

**Comment by Butterflysaway** [comment]
This is linked to the export system it looks like.  I had requested a xml file of the profile data to see how it worked and I suppose it keeps failing on the cron.  I will just remove the export feature for now as I plan to push this to my live website soon once my theme is done for 2.1.  Perhaps just add a option to turn off profile exporting since its buggy.  Also Memcache is bugged if we don't use it.  I'll manually remove both of these until they are not causing errors.

**Comment by albertlast** [comment]
error got added by sequi and his pr https://github.com/SimpleMachines/SMF2.1/commit/ee9506238f8bba715f2feb7ee3a6a966ec7cacf4
did run some test with sych0 result was,
that for pg is this always in error and
on mysql/mardiab it's depends on the version

**Comment by frandominguezl** [comment]
This needs a "Has Fix" label.

@live627 @sbulen @MissAllSunday
