### ISSUE TITLE
Notification Memory Exhaustion Bug

### ISSUE THREAD

**Issue by Butterflysaway** [SimpleMachines/SMF#6200]
#### Description
My forum has 1.7 million members currently.  I know I can fix this error by increasing the maximum php memory size but I'd rather not have to do that if I can help it.

### Steps to reproduce
1. Go to your profile
2. Click Forum Profile -> Notifications -> Notifications Preferences

### Environment (complete as necessary)
- Version/Git revision: 2.1 Latest Github version
- Database Type: mysql
- Database Version: mysql  Ver 15.1 Distrib 10.2.19-MariaDB, for Linux (x86_64) using readline 5.1
- PHP Version: 7.4

### Additional information/references
![image](https://user-images.githubusercontent.com/68415596/88795757-88cd8700-d16e-11ea-9b6b-4994dd541bd0.png)

**Comment by albertlast** [comment]
It would be helpfull when you provide error message as text not as picture and
addditionaly the backtracking is always nice.

**Comment by Butterflysaway** [comment]
Error doesn't show backtracking information.

The file is Sources/Subs-Members.php line 1120 if that makes it easier.

**Comment by live627** [comment]
@Butterflysaway try this fix please https://github.com/live627/SMF2.1/commit/8366f3d539b592ee70dadbf3f6fde289062eed38

Luckily I don't need a backtrace.

**Comment by Butterflysaway** [comment]
@live627 Seems to have fixed the error, but not sure if notifications are working or not.  Last time I tried receiving notifications for topics after watching them nothing ever sent via email nor alert notification when I posted on the topic with another account.  I was debating just removing notifications entirely since it doesn't seem to work very good.

**Comment by SychO9** [comment]
@Butterflysaway what do you have the option `How frequently to tell me:` set to ?

**Comment by albertlast** [comment]
Why we don't push down the memid or membergroup to the allowed function?

**Comment by Butterflysaway** [comment]
@SychO9 that seems to be the issue.  Notifications are working pretty well right now.

Thanks.

**Comment by SychO9** [comment]
What does that mean ? you didn't say what it is (or was) set to

**Comment by Butterflysaway** [comment]
It was set to Never.  I figured notification settings got reset when I upgraded from 1.1.21.

**Comment by SychO9** [comment]
Alright, thank you.

I believe the default value should be changed to `Straight Away` instead of `Never`, I'll make an issue and PR for that.

**Comment by Butterflysaway** [comment]
@SychO9 how about if somebody follows a topic with it disabled it re-enables it automatically?

**Comment by SychO9** [comment]
I don't think so, even `msg_auto_notify` which refers to `Follow topics I create and reply to` is off by default.
