### ISSUE TITLE
 Default notification frequency preference should not be Never

### ISSUE THREAD

**Issue by SychO9** [SimpleMachines/SMF#6203]
I believe the default value should be changed to `Straight Away` instead of `Never`, it's not very clear when installing the software that notifications will only work when you change it to something other than `Never`, I've had the same problem myself when installing a new forum, and I'm very familiar with SMF. 

So for other normal/new users, it'll give them the impression that the notifications system does not work or is bad, like here: https://github.com/SimpleMachines/SMF2.1/issues/6200#issuecomment-666218372, mainly because when it's set to `Never` it doesn't matter if you turn on alerts in the topic.

**Comment by SychO9** [comment]
maybe we should also have `msg_auto_notify` which refers to `Follow topics I create and reply to` ON by default as well ?

**Comment by Butterflysaway** [comment]
I agree that this needs changed definitely.  Most people will assume clicking follow on the topic itself will handle all notifications for that specific topic.  Tbh the option **Never** should be entirely removed from **How frequently to tell me:**.  If someone doesn't want to be notified from a topic they have plenty of ways to remove the following from topics.  Only thing that option does is make the forum appear to be buggy.  For example, how can somebody even follow a topic if that option is enabled, the button should be removed from the topic entirely if thats set to **Never**.

**Comment by SychO9** [comment]
There's no reason to completely remove the `Never` option, it has its uses. For instance if you have been in a forum for many many years, then chances are you have manually followed a big amount of topics, and being able to use the `Never` option to shut them all off without having to go through all of them is nice.

Changing the default value should be enough to make the system work nicely :)
