### ISSUE TITLE
Registration issue

### ISSUE THREAD

**Issue by Butterflysaway** [SimpleMachines/SMF#6207]
#### Description
While testing the entire forum for bugs before I push to my live site I noticed when I registered on the forum it registered 2 new members with the same name, password, different verification codes, password salts and id's, also sent out 2 emails to the same email address for both accounts.

![register_bug](https://user-images.githubusercontent.com/68415596/89088673-a3b71b80-d367-11ea-880d-46c89d72150f.png)

### Steps to reproduce
I'm still not sure how to reproduce this bug as I tried again and it only registered once, but I know for sure this has to be a bug somewhere for some reason.

### Environment (complete as necessary)
- Version/Git revision:2.1 Latest github version
- Database Type: mysql
- Database Version: mysql  Ver 15.1 Distrib 10.2.19-MariaDB, for Linux (x86_64) using readline 5.1
- PHP Version: php 7.4

### Additional information/references
No error messages or warnings were given.

**Comment by Butterflysaway** [comment]
Can someone tell me if this has happened to them before?

**Comment by Butterflysaway** [comment]
Turns out I must have accidentally pressed register 2 times.  I am able to reproduce it only if I press sign up 2x very fast on chrome.  I think if I enable reCaptcha that should fix the problem since each submit token has to be verified by google.

**Comment by albertlast** [comment]
on db side this issue could be catched by creating an unique index over the member_name or email_address.

**Comment by Butterflysaway** [comment]
Yeah I can also confirm this is a bug spanning all the way back to 1.1.21 as it happens on that version as well.

Turns out my database had around 700 duplicate registrations from 1.1.21

**Comment by albertlast** [comment]
What is for you a duplicate?
the same name? the same mail? or something else?

**Comment by Butterflysaway** [comment]
same name and email.  smf by default does not allow you to register another account with the same name nor email address, but this bug allows it to happen.

**Comment by Butterflysaway** [comment]
@albertlast could this be fixed by using **replace** instead of **insert** for the user registration query?

**Comment by albertlast** [comment]
Yes and no,
yes it would solve this issue,
no it would allow to overtake an existing account.

so in general NO would be right answer.

What is in your point of view the issue with unique index here?

**Comment by Butterflysaway** [comment]
I have no issue with making them unique indexes, but before that could even be released for everybody you'd have to remove already duplicated entries of email addresses and usernames or MySQL would throw an error while trying to alter the table right?

**Comment by albertlast** [comment]
yes this is problem by the solution and to integrate this in the upgrade process.
in the install process is this no issue.

**Comment by albertlast** [comment]
btw how long takes it for php to generate your index and maybe on of your big topics?
in compare between live version with 2.0.x? and you test area with 2.1

**Comment by Butterflysaway** [comment]
Never had 2.0.x only 1.1.21.  I can tell though that 1.1.21 is significantly faster in some pages than 2.1 (registration, topics, profile editing, selecting themes for all members, etc).  I'll get some numbers for you in a minute.

**Comment by albertlast** [comment]
for this kind of question is always nice to had
``
$db_show_debug = true;
``
in your settings, since you get timing of your db queries.

**Comment by Butterflysaway** [comment]
Profile Page 1.1.21 - Page created in 0.051 seconds with 16 queries.
Profile Page 2.1 - Page created in 0.037 seconds with 16 queries.

Board Index 1.1.21 - Page created in 0.049 seconds with 16 queries.
Board Index 2.1 - Page created in 0.037 seconds with 14 queries.

Topic with 100 messages showing all 1.1.21 - Page created in 0.059 seconds with 21 queries.
Same Topic with 100 messages showing all 2.1 - Page created in 0.120 seconds with 23 queries.

Setting all members themes 1.1.21 - Around 11 seconds.
Setting all members themes 2.1 - Around 25 seconds.

**Comment by albertlast** [comment]
I guess the numbers are make by calling the index page with your admin account,
a normal user should got different  page creation time on the index page,
since smf needs to do more security checks.

**Comment by Butterflysaway** [comment]
Seems like it.  On a normal user it is Page created in 0.042 seconds with 15 queries. for Board Index on smf 2.1

**Comment by Butterflysaway** [comment]
Overall 2.1 works exceptionally well from all my tests.  I will be glad to finally not have to rely on php 5.6 anymore.
