### ISSUE TITLE
Various inconsistencies related to passwords

### ISSUE THREAD

**Issue by Butterflysaway** [SimpleMachines/SMF#6219]
#### Description
A few inconsistencies that relate to just password resetting, validation handling & hashing that I've found while looking through the files.

Bugfix 1: Fixes a problem which prevented the user from changing e-mail address on the activate action if they entered a non-valid e-mail on sign up and your board requires activation.
Bugfix 2: Added proper titles to some of the message pages the user sees when requesting a new verification code.
Bugfix 3: No longer gives 404 html header when user requests a new verification code.
Bugfix 4: Added un_htmlspecialchars to missing password post from verifyPassword calls where needed.
Bugfix 5: Removed strip_slashes on password which will prevent any user from having a backslash in their password from saving their profile. Also removed the extra un_htmlspecialchars which was already handled when setting $password.
Bugfix 6: Removed unneeded un_htmlspecialchars from upgrade hash password which will prevent an error if your password contains html special chars by random chance.

### Environment (complete as necessary)
- Version/Git revision: 2.1 Latest
- Database Type: Mysql
- Database Version: Mariadb
- PHP Version: 7.4 Latest

### Additional information/references

**Comment by jdarwood007** [comment]
@Butterflysaway Thanks for all the recent help.  If you are going to submit a PR, you don't need to open a separate issue on it.  The PR can describe the issue and contain the fix all in one.

**Comment by live627** [comment]
some projects actually require every PR to have its own issue

**Comment by Butterflysaway** [comment]
@jdarwood007 Np.  Sounds good.  Just trying to fix all the problems I find before using this on my live site.  Hopefully it helps others that are using SMF as well.  I've used it on my site for 10+ years.

Can someone answer a question about modifications I have

I've been wanting to update the modifications I used on SMF 1.1.21 which are no longer supported for SMF 2.1.  Is it possible to just send an email to admins or w/e with the modification fixed and you can update it on the SMF website or how does that work?

Mods in particular:
Member Color Link - https://custom.simplemachines.org/mods/index.php?mod=111
Simple Portal - https://custom.simplemachines.org/mods/index.php?mod=1104

What I would like to do is just modify the existing packages and make them compatible.  I don't want any credits/etc.  Just would like it to be available to everyone once I do so since they are great mods that should be continued on 2.1.

**Comment by frandominguezl** [comment]
You can get in touch with the Customization Team over https://simplemachines.org (contact SychO or Gary), and they'll guide you on how you can do that.
