### ISSUE TITLE
New install: Undefined errors - lastRealName, latestMember

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6225]
#### Description
Immediately upon fresh install, there are at least 5 undefined errors.

### Steps to reproduce
1. Install 2.1

### Environment (complete as necessary)
- Version/Git revision:  Current
- Database Type:  MySQL
- Database Version:  5.7
- PHP Version:  5.4 & 7.3

### Additional information/references
![image](https://user-images.githubusercontent.com/23568484/90347498-b70feb00-dfe5-11ea-9bcb-9faae4c93040.png)

**Comment by sbulen** [comment]
I am going to cancel this, as I cannot consistently reproduce it.  

(I actually suspect my new mouse... It has a special tiny button on the side that emulates hitting the browser BACK key...)

**Comment by live627** [comment]
lol bad rodent!

**Comment by sbulen** [comment]
Yep...  

(Nothing to do with the operator...)
