### ISSUE TITLE
Visibility to Policy Acceptance

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6229]
#### Description
User acceptance of the privacy policy is being logged, but is not visible anywhere - as far as I can tell...

If you can see them somewhere, I'll close this!

The records themselves are buried in log_actions...

I suspect we should make policy acceptance visible, read-only, under Profile | Track User.  

![image](https://user-images.githubusercontent.com/23568484/90588090-ad29eb80-e18f-11ea-8e30-0951aca9f13c.png)

**Comment by live627** [comment]
You need to enable the user log.

**Comment by sbulen** [comment]
Which setting is that?

**Comment by live627** [comment]
under the log settings

or search the admin pages for profile edits log

**Comment by sbulen** [comment]
No, nothing under the profile edits log either.  That would have been an acceptable place for it, I think...

![image](https://user-images.githubusercontent.com/23568484/90681589-806de680-e218-11ea-88dd-0d5866dc7312.png)


The 2.0 log entries are there:
![image](https://user-images.githubusercontent.com/23568484/90681692-a3989600-e218-11ea-91c1-2d27aaada76b.png)

**Comment by sbulen** [comment]
But...  Looking at the above...  The problem is that the id_member field isn't being populated...  

If you do populate it, the entries show up:
![image](https://user-images.githubusercontent.com/23568484/90682040-3802f880-e219-11ea-8220-fbd561c3a0a7.png)


**_What to do about THAT?   It's actually a 2.0 bug, the field hasn't been getting populated in 2.0..._**

**Comment by sbulen** [comment]
I will close this out.  

The missing entries are bugs...  In 2.1, it will be dealt with as part of #6100 

A separate issue was logged for the 2.0 bug in the internal 2.0 log.
