### ISSUE TITLE
Policy Acceptance - add language selection

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6230]
#### Description
When registering, you view the registration (& policy soon...) agreement prior to registration.  The agreements are presented in the forum default language.  

It's odd, because it's only AFTER you've signed up that you can see what you agreed to in your own language...

I may be missing something???

I propose we add a language selection dropdown when viewing the agreement page prior to registration.

Note there is no language selection visible here...  What if I don't speak English:
![image](https://user-images.githubusercontent.com/23568484/90588581-d434ed00-e190-11ea-8866-f856e9cbfe5a.png)

**Comment by live627** [comment]
does the existing language select box not cut it?

**Comment by sbulen** [comment]
> does the existing language select box not cut it?

There is none...  Screenshot???  

It doesn't appear to fall back to the browser default either.

**Comment by live627** [comment]
![Screenshot_2020-08-19 Registration Agreement](https://user-images.githubusercontent.com/431799/90669990-61b32400-e207-11ea-81ec-8fcdcc30a66a.png)
add a language pack to make it show

**Comment by sbulen** [comment]
I am brain damaged.  Too much huffing CA wildfire smoke...

I've been looking right thru it...

**Comment by live627** [comment]
lmao

I'm in Arizona. They happen here too.
