### ISSUE TITLE
Registration - should we rename 2.0 agreements that have -utf8 in the name?

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6238]
#### Description
If your 2.0 site is multi-language, and has -utf8 languages installed, it will have several .txt files that have -utf8 in the filenames.  In 2.1, everything is -utf8, so we no longer include -utf8 in the language names.  The Upgrader has gone out of its way to find all settings, etc., and rename them, to remove the -utf8.  

Should we rename these .txt files as well?  Or should we rely on the admins just recognizing this & renaming the files themselves?  

I wasn't quite sure if this was overkill or not, hence I'm asking the question...  If you weren't aware of this, it will look like you LOST all your old agreements on the 2.1 install, because they won't be found...

These 2.0 agreements won't be found in 2.1 after the upgrade unless renamed:
![image](https://user-images.githubusercontent.com/23568484/91100477-23a86c80-e61a-11ea-87e5-88c8183a3c22.png)

**Comment by frandominguezl** [comment]
If they won't be found, then I believe we should rename them. I don't think we should let any of this kind of tasks on admins.

**Comment by sbulen** [comment]
Thanks for the feedback.  Done.
