### ISSUE TITLE
Session bug

### ISSUE THREAD

**Issue by Butterflysaway** [SimpleMachines/SMF#6239]
#### Description
Error
Type of error: General
Error message:
2: Unknown: Failed to write session data using user defined save handler. (session.save_path: /var/lib/php/session)
File: Unknown
URL of page causing the error: https://website.com/index.php?action=dlattach;attach=18981;type=avatar
Backtrace information
#0: smf_error_handler()
Called from unknown on line -1

### Steps to reproduce
Don't know how to reproduce.

### Environment (complete as necessary)
- Version/Git revision: 2.1 Latest
- Database Type: Mariadb
- Database Version: Mariadb latest.
- PHP Version: 7.4

### Additional information/references

If anyone knows what caused this error to occur lemme know.  It has only happened one time in 5 days on my production website.

**Comment by Butterflysaway** [comment]
Update: same error has happened around 10 times in around 11 days.

**Comment by frandominguezl** [comment]
It's still the same URL?

**Comment by Butterflysaway** [comment]
Different url's its probably worth noting i'm using php-fpm and nginx.  The path for sessions is writable and seems to work fine.  Perhaps this is just a php-fpm/nginx bug?

**Comment by jdarwood007** [comment]
Your using file based sessions.  Is your IO overloading or storage layer having problems that may be preventing read/writes?

**Comment by vort7u** [comment]
Type of error: General
Error message: 2: Unknown: Failed to write session data using user defined save handler. (session.save_path: /var/cpanel/php/sessions/ea-php73)
File: Unknown
URL of page causing the error: https://www.site.info/index.php?action=keepalive;time=1598784440850

Backtrace:
#0: smf_error_handler()
Called from unknown on line -1
https://www.site/index.php?action=admin;area=logs;sa=errorlog;file=c2Nvbm9zY2l1dG8=;line=-1

SMF 2.1 RC2 with **cache disabled**
PHP Version 7.3.20
MariaDB 10.3

> Update: same error has happened around 10 times in around 11 days.

Me too.

**Comment by frandominguezl** [comment]
Can you guys check (you or with the help of your host) if those files/folders have proper permissions?

**Comment by sbulen** [comment]
Is your session.save_path set?
If not, php uses your temp dir.  How is that defined?
In the past, I've seen this with file-based sessions, and explicitly setting session / temp folders addressed.  
Otherwise you're at the mercy of whatever is going on at the OS level, which may be dynamic...

/tmp : Temporary files
The /tmp directory must be made available for programs that require temporary files.

Programs must not assume that any files or directories in /tmp are preserved between invocations of the program.

**Comment by vort7u** [comment]
> Can you guys check (you or with the help of your host) if those files/folders have proper permissions?

Yes



> Is your session.save_path set?

Yes

![php](https://user-images.githubusercontent.com/1554203/92131676-8e218f80-ee06-11ea-8ba4-f44ee98a35bf.jpg)

![2](https://user-images.githubusercontent.com/1554203/92131695-91b51680-ee06-11ea-9d4f-fdfe5aa8716a.jpg)

**Comment by sbulen** [comment]
If these are file-based sessions, how/why is the custom handler being invoked?

The custom handler is specifically for db sessions...

**Comment by Butterflysaway** [comment]
Yes, permissions are set properly for the folder. Pretty sure there is no IO issues as the only errors I get from anything running on my server are those few random session errors every day.

**Comment by sbulen** [comment]
A couple more questions - 
Do you see any records in your sessions table?  (You shouldn't, but...)
Do you have a value in your settings table for 'databaseSession_enable'?

EDIT:  One more...   Do you use SSI?

**Comment by vort7u** [comment]
> Do you see any records in your sessions table? (You shouldn't, but...)

Ehmm ... yes smf_sessions table with 216 records 🙄

> Do you have a value in your settings table for 'databaseSession_enable'?

Yes
![session](https://user-images.githubusercontent.com/1554203/92515731-58b8df80-f214-11ea-919f-b6a169fd6c44.jpg)

> EDIT: One more... Do you use SSI?

No

Thanks

**Comment by sbulen** [comment]
> > Do you see any records in your sessions table? (You shouldn't, but...)
> 
> Ehmm ... yes smf_sessions table with 216 records 🙄

OK, but you have database sessions enabled, not file-based sessions.  So you _should_ see them. 


@Butterflysaway - Same two questions for you:  Do you have sessions in your sessions table?  What is the value of databaseSession_enable?

I thought we were working on specifically a file-based sessions issue...  Still trying to understand the problem...

**Comment by Butterflysaway** [comment]
Yup, I have 12,000 sessions in the sessions table.  Also the setting for databaseSession_enable is 1.

**Comment by sbulen** [comment]
OK - thanks for confirming.  You both have DB sessions enabled, so it makes sense that the custom session handlers are in effect and they are being written to the DB.  Something earlier threw us & made us think we were looking at file-based sessions...  But we're not...

Some things are making a bit more sense now.  We were looking in the wrong place ealier...

**Comment by live627** [comment]
I'm guessing the  data is overflowing the column.

I have a query to try... it may or may not provide a clue.

`SELECT MAX(LENGTH(data)) FROM smf_sessions`

**Comment by Butterflysaway** [comment]
1838 is the max length in my sessions table anyway.

![image](https://user-images.githubusercontent.com/68415596/92555544-eb1dab00-f235-11ea-8de5-44dc40c0ca14.png)

**Comment by sbulen** [comment]
Hmmm...  

What about the max length of the session_id field?

**Comment by vort7u** [comment]
> I have a query to try... it may or may not provide a clue.

![Annotazione 2020-09-09 084104](https://user-images.githubusercontent.com/1554203/92563720-4a9caa80-f278-11ea-9767-21b9f930e9fc.jpg)

**Comment by Butterflysaway** [comment]
Max length is 28 for session id's.  Is it possible to have a much longer one?

**Comment by live627** [comment]
it deepness on the hash  algo as seen in https://stackoverflow.com/a/17032075/4710434

**Comment by live627** [comment]
Are the errors logged by users/members or guests? Or maybe bots?

The function to write session data ignores any errors when inserting a new row. Perhaps there is a hidden error...

Find in Session.php

	// If that didn't work, try inserting a new one.
	if ($smcFunc['db_affected_rows']() == 0)
		$smcFunc['db_insert']('ignore',
			'{db_prefix}sessions',
			array('session_id' => 'string', 'data' => 'string', 'last_update' => 'int'),
			array($session_id, $data, time()),
			array('session_id')
		);

replace with

	// If that didn't work, try inserting a new one.
	if ($smcFunc['db_affected_rows']() == 0)
		$smcFunc['db_insert']('ignore',
			'{db_prefix}sessions',
			array('session_id' => 'string', 'data' => 'string', 'last_update' => 'int'),
			array($session_id, $data, time()),
			array('session_id')
		);

**Comment by frandominguezl** [comment]
Those two chunk of code are the same @live627

**Comment by Butterflysaway** [comment]
Just to clarify, the error could be caused by a mysql query?  I haven't really dug into how sessions work on php and smf2.1.  Why would php report the php save path if it's a mysql error? "Failed to write session data using user defined save handler. (session.save_path: /var/lib/php/session)".  If that's the case the error message should be changed by php as it's misleading.

**Comment by sbulen** [comment]
> Just to clarify, the error could be caused by a mysql query? I haven't really dug into how sessions work on php and smf2.1. Why would php report the php save path if it's a mysql error? "Failed to write session data using user defined save handler. (session.save_path: /var/lib/php/session)". If that's the case the error message should be changed by php as it's misleading.

The initial error includes the actual php error text.  Php (not SMF) puts the session.save_path path in there to help your diagnoses.  In this case, it is a red herring.

But it is common to write sessions to a DB, and you can do so by writing your own session handlers.  Our session handlers are in Session.php, and we're looking at sessionWrite().  At the moment, we're looking at things that can result in a return value of _false_.  That appears to narrow it to either a failed DB update, or a failed preg_match.

**Comment by sbulen** [comment]
@live627  - it attempts an update, and if that fails, it does an insert.  It will only return false if both fail.  

I do think #6254 may be related, based on your comment:
> Thee output of the errors found during each step is saved in the session. You apparently have so many errors that it couldn't store the session.

I believe this is what it would look like if it couldn't store the session.

**Comment by Butterflysaway** [comment]
Would you like me to just record in a file when it fails to save so we could see what's causing it?

**Comment by sbulen** [comment]
> Would you like me to just record in a file when it fails to save so we could see what's causing it?

Yep.  If you could!  We'd need to look at the content, and the ID.  You'd need to look at both possible sources of a false - the preg_match and the DB update.  You'd need to set a trap at both places...

**Comment by sbulen** [comment]
If it's the DB update that is failing, that may be in a mysql log also, depending on your configuration...

**Comment by Butterflysaway** [comment]
I'll let you know when it gets triggered again.  I have it fully setup to log now.

**Comment by sbulen** [comment]
While you're at it...  Try repair_boards, see if that triggers it...  (#6254)

**Comment by Butterflysaway** [comment]
![sdskdn](https://user-images.githubusercontent.com/68415596/92811985-f46d5b80-f38c-11ea-91c2-a5cef60d1bf3.png)

-----------------------------
inside my custom log file:


Session ID: 28h39oqc6ja9n2nt9c9dko44a3

a:2:{s:13:"session_value";s:32:"0d7aac56f7f7c98ca9806321401948bc";s:11:"session_var";s:9:"fbffb536e";}

**Comment by Butterflysaway** [comment]
function saveSession($session_id, $data)
{
	$echodata = "\nSession: " . $session_id . "\n" . $data;
	file_put_contents ("/var/www/sessionserrors.txt", $echodata, FILE_APPEND);
}
function sessionWrite($session_id, $data)
{
	global $smcFunc, $db_connection, $db_server, $db_name, $db_user, $db_passwd;
	global $db_prefix, $db_persist, $db_port, $db_mb4;

	if (preg_match('~^[A-Za-z0-9,-]{16,64}$~', $session_id) == 0)
	{
		saveSession($session_id, $data);
		return false;
	}

	// php < 7.0 need this
	if (empty($db_connection))
	{
		$db_options = array();

		// Add in the port if needed
		if (!empty($db_port))
			$db_options['port'] = $db_port;

		if (!empty($db_mb4))
			$db_options['db_mb4'] = $db_mb4;

		$options = array_merge($db_options, array('persist' => $db_persist, 'dont_select_db' => SMF == 'SSI'));

		$db_connection = smf_db_initiate($db_server, $db_name, $db_user, $db_passwd, $db_prefix, $options);
	}

	// First try to update an existing row...
	$smcFunc['db_query']('', '
		UPDATE {db_prefix}sessions
		SET data = {string:data}, last_update = {int:last_update}
		WHERE session_id = {string:session_id}',
		array(
			'last_update' => time(),
			'data' => $data,
			'session_id' => $session_id,
		)
	);

	// If that didn't work, try inserting a new one.
	if ($smcFunc['db_affected_rows']() == 0)
		$smcFunc['db_insert']('ignore',
			'{db_prefix}sessions',
			array('session_id' => 'string', 'data' => 'string', 'last_update' => 'int'),
			array($session_id, $data, time()),
			array('session_id')
		);

	if($smcFunc['db_affected_rows']() == 0)
	{
		saveSession($session_id, $data);
	}

	return ($smcFunc['db_affected_rows']() == 0 ? false : true);
}

**Comment by Butterflysaway** [comment]
`function saveSession($session_id, $data)
{
	$echodata = "\nSession ID: " . $session_id . "\n" . $data;
	file_put_contents ("/var/www/sessionserrors.txt", $echodata, FILE_APPEND);
}
function sessionWrite($session_id, $data)
{
	global $smcFunc, $db_connection, $db_server, $db_name, $db_user, $db_passwd;
	global $db_prefix, $db_persist, $db_port, $db_mb4;

	if (preg_match('~^[A-Za-z0-9,-]{16,64}$~', $session_id) == 0)
	{
		saveSession($session_id, $data);
		return false;
	}

	// php < 7.0 need this
	if (empty($db_connection))
	{
		$db_options = array();

		// Add in the port if needed
		if (!empty($db_port))
			$db_options['port'] = $db_port;

		if (!empty($db_mb4))
			$db_options['db_mb4'] = $db_mb4;

		$options = array_merge($db_options, array('persist' => $db_persist, 'dont_select_db' => SMF == 'SSI'));

		$db_connection = smf_db_initiate($db_server, $db_name, $db_user, $db_passwd, $db_prefix, $options);
	}

	// First try to update an existing row...
	$smcFunc['db_query']('', '
		UPDATE {db_prefix}sessions
		SET data = {string:data}, last_update = {int:last_update}
		WHERE session_id = {string:session_id}',
		array(
			'last_update' => time(),
			'data' => $data,
			'session_id' => $session_id,
		)
	);

	// If that didn't work, try inserting a new one.
	if ($smcFunc['db_affected_rows']() == 0)
		$smcFunc['db_insert']('ignore',
			'{db_prefix}sessions',
			array('session_id' => 'string', 'data' => 'string', 'last_update' => 'int'),
			array($session_id, $data, time()),
			array('session_id')
		);

	if($smcFunc['db_affected_rows']() == 0)
	{
		saveSession($session_id, $data);
	}

	return ($smcFunc['db_affected_rows']() == 0 ? false : true);
}`

**Comment by sbulen** [comment]
Hmmm...  Oddly the data look OK to me, unless I'm missing something...  The session ID matches the regex.  The session id & data look valid, & I can insert & update with those values...

So...   Next thought is that the db update is failing on some OTHER reason.  Two more data requests:
 - Is the empty($db_connection) logic kicking in?  It might help to touch something in the log there...
 - It would help to see the error info, if any, returned from `$smcFunc['db_error']($db_connection);` after the update & the insert attempts...  

Unless someone else sees something wrong that that data...  I don't...

**Comment by Butterflysaway** [comment]
I will add some additional logs for any mysql errors that occur including if the db connection is empty.

**Comment by Butterflysaway** [comment]
I'd like to add that I am completely baffled as to why this is happening.  It finally got triggered again today and there was no mysql error, and the db_connection was not empty.  If anyone else has any ideas would like to hear.  Error happens 1-2 times per day with very low load on the server.  Shouldn't be anything to do with the server itself.

**Comment by Butterflysaway** [comment]
I think this is the problem

$smcFunc['db_insert']('ignore',
			'{db_prefix}sessions',
			array('session_id' => 'string', 'data' => 'string', 'last_update' => 'int'),
			array($session_id, $data, time()),
			array('session_id')
		);

Perhaps something in the insert function is preventing it from inserting without throwing an error?

**Comment by Butterflysaway** [comment]
I'll replace this with a manual db_query statement and see if that fixes it.

**Comment by sbulen** [comment]
Sometimes the smcFunc itself has an issue, and it cannot report an error because it is too early in the process.  Language not loaded, or theme, or $context, etc.  So, reporting the error fails.  But...  How to trap for that & capture what's going on...   Hmmm...

**Comment by Butterflysaway** [comment]
just replaced it with this:

	$smcFunc['db_query']('', 'INSERT IGNORE INTO {db_prefix}sessions (`session_id`,`data`,`last_update`) VALUES ({string:session_id}, {string:data}, {int:last_update})',
	array(
			'last_update' => time(),
			'data' => $data,
			'session_id' => $session_id,
		));

If the same error happens, then it's a problem with smf_db_query, if not then it's a problem with smf_db_insert

**Comment by live627** [comment]
Can you remove `IGNORE`? that keyword tells mysql to swallow any errors in
that specific query.

**Comment by Butterflysaway** [comment]
Will try that now.  Error still occurs with the manual insert query instead of using smf insert.

**Comment by Butterflysaway** [comment]
Looks like it was a deadlock error that would occur randomly, and INSERT IGNORE caused smf to not retry the query.  Is there any reason you guys put ignore in the query?  So far running it with just INSERT INTO for 3 days has caused no errors.

**Comment by sbulen** [comment]
Pretty interesting.  Clearly both the update & the insert are both failing for some mysterious reason.  I am still holding out for an issue with the data itself - e.g., one of the fields is somehow too long...  To make things worse, the error is not getting logged...  This can sometimes happen on an attempt to log an error out of the "normal" context (the app itself).  

To answer your question...  The session may or may not exist.  So, this logic first attempts an UPDATE.  If the update fails, it attempts an INSERT.  The smcFunc INSERT is actually very cool & flexible.  It can be told what to do upon conflicts - either IGNORE a conflict (so the record is not updated at all), or, REPLACE the record if there is a conflict.  It is done this way because pg in the past didn't have an equivalent to MySQL's "INSERT … ON DUPLICATE KEY UPDATE", and SMF needs to support both engines, mysql & pg.  (Plus, the smcFunc engine supports lists, so, IIRC record by record this logic kicks in...)

If it is only working with the IGNORE not there, given the UPDATE has previously failed, that means the record is not being updated at all.  No session is being saved/used.

We still need to trap that error.  

Do you have access to the MYSQL logs so we can look at the query itself?  Usually, this can be enabled...  If so, let's turn IGNORE back on & look at the corresponding query & response from the mysql side.

**Comment by Butterflysaway** [comment]
I believe its working without ignore because it's retrying the query automatically when a deadlock is being detected.

**Comment by Butterflysaway** [comment]
I'm not sure I'll be able to turn on the mysql logs.  My database has a high load frequently which might affect performance.  I'll attempt it though and revert it back to the original smf session file if it doesn't affect the performance too much.

**Comment by sbulen** [comment]
I have done a lot of experimentation here, and it appears to me that the error reporting is working just fine.  I deliberately introduced various errors, e.g., data too long, sql syntax, and sessionWrite properly logged issues in log_errors.  So I don't think we're looking at a hidden error.  

OTOH, I have reproduced the error message, indirectly, enough to confirm that error in the log is EXACTLY what is presented if sessionWrite returns false...  

So I don't think it's a true deadlock, or we'd have a SQL error in the log_errors.  However, you may be right in that there are multiple updates occurring nearly simultaneously.  Sessions are written A LOT...

Since there are NO OTHER ERRORS in the logs (correct?), maybe, just maybe, the code is doing what it's told to...

And it appears to be returning false at the end, when the # of rows updated is 0...

My latest theory - today it attempts an update, then, if that fails, it attempts an insert ignore.  What if there are two threads executing, such that for one thread, the session does NOT exist for the first sql call (the update), but does exist for the second (the INSERT IGNORE)?  No error is reported, because there is in fact no sql error.  But zero records are updated, so sessionWrite returns false.

It has been bugging me that we do two operations - an update + an insert ignore, because we could really do one operation - an insert replace...  

That would be my next suggested test.  Replace both of the sql calls with one:
```
	$smcFunc['db_insert']('replace',
		'{db_prefix}sessions',
		array('session_id' => 'string', 'data' => 'string', 'last_update' => 'int'),
		array($session_id, $data, time()),
		array('session_id')
	);

	return ($smcFunc['db_affected_rows']() == 0 ? false : true);
```

**Comment by Butterflysaway** [comment]
Replace is probably the way to go here.  I've done that and will report back if any further errors occur. - I can add that INSERT without ignore never threw any further errors either.  It's up to the devs if they want to use replace instead of update then insert if it doesn't exist.  Replace is working great so far with no problems.

**Comment by sbulen** [comment]
> I can add that INSERT without ignore never threw any further errors either. It's up to the devs if they want to use replace instead of update then insert if it doesn't exist. Replace is working great so far with no problems.

Well look here, a blank is treated as a replace:
https://github.com/SimpleMachines/SMF2.1/blob/b9674508df9874c6d356e1b99fc95b553c2e1e6d/Sources/Subs-Db-mysql.php#L729

**Comment by albertlast** [comment]
which db engine is used on session tabel?

**Comment by sbulen** [comment]
None...   I don't see the db specified in a session.  

Gotta pic of what you're looking for?

**Comment by sbulen** [comment]
My tables are all innodb / mysql.

**Comment by albertlast** [comment]
Different engine got different behavior about table/row locks.

**Comment by Butterflysaway** [comment]
I can say now with 100% certainty that the problem is resolved by using replace.  No errors have occurred in about a week on my forum.  Before there would be 1-2 times per day.

**Comment by albertlast** [comment]
Did you try to turn back to check if the problem appears again?

**Comment by sbulen** [comment]
The insert has been off & on a couple times in this thread.  I think this is explained at this point.  

@Butterflysaway  - go ahead & submit a PR if you like!  If not, I can.

**Comment by sbulen** [comment]
Heh...  I just got this for the first time in my 2.1 test DB...  I'll submit a PR...
