### ISSUE TITLE
What is your target browser support?

### ISSUE THREAD

**Issue by KolyaKorruptis** [SimpleMachines/SMF#6245]
I'm a frontend dev and would like to contribute to the JS side of things. 
For that I would like to know what browser support you're aiming at? 
That could be specific browser vendors and versions, or better yet something like: _"all evergreen browsers at their current versions -2"._
If you plan to support old browsers like IE, do you plan to have a build chain with Babel to transpile down the JS? 

And before I forget: What tests do you run and how?

**Comment by m4z** [comment]
https://wiki.simplemachines.org/smf/SMF2.0:Requirements_and_recommendations:
> * Microsoft Internet Explorer 6.0 or higher (7.0 or higher recommended).
> * Opera 7.0 or higher (9.5 or higher recommended).
> * Netscape 6.0 or higher.
> * Mozilla Suite 1.0.2 or higher.
> * Konqueror or Galeon.
> * Apple Safari 1.0 or higher (3.0 or higher recommended).
> * Mozilla Firefox 3.0 or higher (3.5 or higher recommended).

(2.1 will most likely receive a bit of cleanup, but we generally support everything back to the invention of the abacus.)

**Comment by KolyaKorruptis** [comment]
That doesn't seem to gel with your use of jQuery 3.5.1 in the release-2.1 branch, because jQuery 3 doesn't go back that far.  https://jquery.com/upgrade-guide/3.0/#browser-support. 

Also that jQuery update isn't in the development branch. So release-2.1 is actually further along the way than development.
Do you ever merge release-2.1 into development?

**Comment by Oldiesmann** [comment]
The development branch got left behind at some point, though I don't remember when or why. At this point all development is done in the release-2.1 branch.

**Comment by MissAllSunday** [comment]
Hi, as far as browser support goes, we currently use jQuery to determinate that.

We aren't currently planning to use any compiler such as Babel to offer support for older browsers.

The development branch is no longer used for our release cycle, we instead use the release-2.1 branch, this of course doesn't mean we won't used in the future.

**Comment by KolyaKorruptis** [comment]
Okay, may I ask why you are introducing jQuery to SMF now, when it has largely become obsolete?
Don't get me wrong, jQuery was great from 2008-2018 to smooth out browser support for JS and I've used it a lot. It's how I learned JS. And yeah, I loaded it into SMF too.
But if jQuery 3 represents your bottom browser support line, you could start writing modern JS today, without jQuery. 
Eg for selecting DOM nodes you could use document.querySelector with [even better browser support](https://caniuse.com/#search=document.queryselector) than jQuery 3 provides. 
Maybe it's a matter of familiarity, which I totally get. But still worth considering to future proof your code and drop 87 KB from your page load.

**Comment by MissAllSunday** [comment]
The election of using jQuery was made some time ago. We aren't currently changing our UI this late in the dev process.

**Comment by KolyaKorruptis** [comment]
Sure, I get that. Was just wondering. 

Maybe you can answer me another question, to help me set up my development environment (or point me in the right direction): 
I have Ubuntu on WSL2 with a lamp stack and SMF files in place. I would like to work on a running SMF install so I can easily test JS changes. But I noticed in the RC2 on download.simplemachines.org the installation files are in the root, but in the release-2.1 branch here, they're in a directory named "other". I could move them to root of course, but then would have to ignore that change going forward. How do you deal with that in your environment?

**Comment by SychO9** [comment]
when you run `install.php`, the installation files are auto deleted anyway, so you don't have to worry about ignoring them after that.

**Comment by KolyaKorruptis** [comment]
Gotcha, thanks!
