### ISSUE TITLE
select timezone from install

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#625]
it should be possible to select the timezone of the forum when running the installer.

we have the registration option now, why not the time zone which for many may be more important.

**Comment by Arantor** [comment]
Let's get proper timezone support in the rest of it first.

**Comment by illori** [comment]
cant hurt, you up for it in 2.1?

**Comment by Arantor** [comment]
I honestly think a full timezone workover in 2.1 is a bit much. It's a schema change and even the hacky way I did it in Wedge was a big enough job. If 2.1 were earlier in its process I'd be all for it.

**Comment by illori** [comment]
well in the mean time cant hurt to add the options to the installer

**Comment by Arantor** [comment]
It's probably not for the best, actually, because I suspect it will confuse people who will end up trying to select the wrong timezone and all kinds of fun happening with it.

Technically the installer does declare a timezone in its innards but it's not a proper timezone ;)

**Comment by jdarwood007** [comment]
At what point do we say too many options during install is enough?  I don't know, it seems like just adding way to many options gets pointless and ends up like one of those damn installers that take you through 5 pages of options just to install the thing.

**Comment by Arantor** [comment]
That's a valid question too.

**Comment by illori** [comment]
is there anything that could be removed?

**Comment by Arantor** [comment]
Well, we could remove the 'registration mode' option that was added in 2.1... we could also remove the 'enable SM stats collection' feature while we're at it (it's not like most people have that enabled)

Pretty much everything else is actually needed at this point in time.

**Comment by illori** [comment]
the registration mode part was added to help prevent spammers hitting a forum before it is setup [if that could even occur] but with the code you committed for your mod i dont think it is really needed any longer

**Comment by Arantor** [comment]
If that was the case, we could just start with registration disabled and go from there ;)

**Comment by jdarwood007** [comment]
I'm just saying we need to be careful here, adding too many options will make the installer seem less friendly.  SMF stats is fine (and should be default in releases really).  Registration mode seemed like a reasonable option to allow the longer setups to occur

**Comment by Arantor** [comment]
Given how poor the stats have turned out to be, would it not be better to actually remove it? It will also mean less effort for sm.org servers.

**Comment by illori** [comment]
right now i am not even sure the script for collecting the stats works correctly. last coreisp said something had to be run to update them and he had no idea what it was.

**Comment by jdarwood007** [comment]
There are a couple bugs but I attribute most of them to our site stack at the time.

The stats are supposed to collect basic information such as versions and database support, which give us insight into what we need to support although with our current release cycle speed it is fairly evident what we need to support.

**Comment by Arantor** [comment]
In which case is it worth removing the stats collection for now and then readding it in future if we get the site stack sorted out?

**Comment by Arantor** [comment]
Opened the stats collection question elsewhere.

Meantime, I do not think it is a good idea to add this option to the installer at this time.
