### ISSUE TITLE
Upgrade 2.0.5 to 2.1 Alpha 1

### ISSUE THREAD

**Issue by BurkeKnight** [SimpleMachines/SMF#626]
Error!
Unknown column 'id_theme' in 'where clause'

Get this error while doing the database.
Hangs and will not let continue.

**Comment by illori** [comment]
i think oldies fixed this, if so can we close this?

**Comment by BurkeKnight** [comment]
I don't see why not. He did say it was fixed.

**Comment by Oldiesmann** [comment]
Didn't see this issue before, but yes, this is fixed now.
