### ISSUE TITLE
Missing $auth_secret prevents logins

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6261]
#### Description
As expected if $auth_secret is missing, we attempt to populate Settings.php with it.  But if we can't write this Settings.php we silently fail.  This will cause unexpected silent login errors since $auth_secret keeps changing, the cookie will never be valid.

We should either:
1. When $db_show_debug = $true;, show a warning if we are missing $auth_secret and can't write to Settings.php
2. Show a warning on login if $auth_secret is missing

### Steps to reproduce
1. remove $auth_secret from Settings.php
2. Set Settings.php to read only
3. Attempt to login

### Environment (complete as necessary)
- Version/Git revision: latest
- Database Type: mysql
- Database Version:
- PHP Version: 7.4

### Additional information/references

**Comment by live627** [comment]
I have no mouth and I must scream

**Comment by jdarwood007** [comment]
I couldn't sleep last night, so I thought about this more and wrote a PR that fixes this up in the best way I think possible.  Which is to weaken security a bit but alert the admins to this issue with error logs and notifications.  If we shouldn't weaken security, I can have it do the original thoughts.
