### ISSUE TITLE
Feature Request: Hide poster IP addresses by default 

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#6265]
#### Description
When you're an admin, by default you see (in both 2.1 and 2.0, AFAIK) the poster IP addresses next to the messages posted in all your threads (on the bottom right in 2.0, bottom left in 2.1). When people share screenshots, they tend to forget to censor them, like [this guy](https://www.simplemachines.org/community/index.php?topic=574841.0) did repeatedly. Should we hide them by default, f.e. behind a "Show IP" javascript snippet?

### Steps to reproduce
1. Be an admin
2. Notice the IP address next to any post
3. Take a screenshot, share it, but forget to censor the IP(s) :hand_over_mouth:
4. TODO
5. $$$

### Environment (complete as necessary)
- Version/Git revision: any 2.1 rc2 version, probably
- Database Type: any
- Database Version: any
- PHP Version: any

**Comment by MissAllSunday** [comment]
Sounds good, click over hover to help with mobile users.
