### ISSUE TITLE
"Show most recent posts at the top" causes weird issues

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#6270]
#### Description
Kind of hard to describe this but the "Show most recent posts at the top" setting (under "Look and Layout" in the profile) causes weird issues. This was reported by a member of my seniors forum and I was able to reproduce it by testing a few things...

On my test board (running latest git build as of this posting):
Replying to a topic results in only the first post in the topic being shown (though the post number is correct)
The link to the latest post in the topic is incorrect on the board index (for instance, in one topic it shows .../index.php?topic=3.msg23#new but the highest post ID is 22)

Also, on the seniors forum, I've found that some posts get cut off. For instance, in one topic, the most recent post was made earlier today but when I go directly to that topic (eg .../index.php?topic=x.0) it doesn't show anything newer than July 20th.

### Steps to reproduce
1. Go to Profile -> Look and Layout and check the box marked "Show most recent posts at the top in topic view"
2. Post and browse the forum like usual

### Environment (complete as necessary)
- Version/Git revision: Seniors forum is from early September (shortly after #6244 was merged), test board is latest revision
- Database Type: MariaDB
- Database Version: 10.3.22
- PHP Version: 7.3.22 on seniors, 7.4.10 on test board

### Additional information/references
Seniors forum: https://www.seniorsandfriends.org
Test board: https://smfgit.oldiesmann.us
Seniors board is running solely on nginx while the test board is Apache with nginx reverse proxy
Caching is at level 1 using APCu, but disabling caching doesn't make a difference in the outcome

**Comment by dragomano** [comment]
Display.php, try to comment out these lines: from 867 to 895.

**Comment by SychO9** [comment]
Same as #5764 ?

**Comment by Oldiesmann** [comment]
> Same as #5764 ?

@albertlast seems to think so. I haven't encountered any database errors though.

**Comment by SychO9** [comment]
the database error is just one symptom, a lot of weird things happen with this one setting, all due to the same problem. Hence why I think this is most likely a duplicate issue

**Comment by Butterflysaway** [comment]
Why not just remove the option permanently?  I've removed it from mine.  Could do a PR if you want.

**Comment by sbulen** [comment]
I think it's a very handy option - especially for mobile browsing.  It makes it much easier to see the latest & greatest.  

I use it, & the question comes up on my forum from time to time, so I know my users use it also.

**Comment by SychO9** [comment]
yea, I've seen from other communities where I was around that it is a very used option, so I think trying to fix it would be better than directly removing it.

**Comment by MissAllSunday** [comment]
Indeed it looks like a duplicate, as such will close this one. Please lets continue on the original issue: #5764
