### ISSUE TITLE
Upgrader (nit) - On long steps, titles are redisplayed sometimes

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6282]
#### Description
This happens to me, for example, when running the 2.0 to 2.1 upgrader.  
Everything seems to work perfectly, but the display hiccups.  I have run many upgrades, I've never seen this behavior before...
Note that "Renaming table columns" is repeated below...

![21rc3-upgrader_wrinkle](https://user-images.githubusercontent.com/23568484/94757478-2d2aa000-034f-11eb-846a-5359c1ef21a0.png)

### Steps to reproduce
1. Upgrade from 2.0 to 2.1...  Look at the renaming table columns step...

### Environment (complete as necessary)
- Version/Git revision: current
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 7.4

### Additional information/references

**Comment by jdarwood007** [comment]
Are you saying you see this constantly?

I've seen it happen. We print the dots to indicate the loops as it keeps stepping through it.  It seems sometimes it finishes that loop but doesn't quite tell the parent its done, so it reprints the text and restarts the loop.
One of those difficult bugs to track down exactly why it occurs and reproduce it.

**Comment by sbulen** [comment]
I've never seen this one before...  (And I've really run the upgrader hundreds of times...)  I've seen it pretty often on the renaming columns step at the start of the 2.0 upgrade file recently.  It does appear to restart.

**Comment by sbulen** [comment]
Very minor.  Will close.
