### ISSUE TITLE
MariaDB GROUP BY issue

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6309]
#### Description
This occurs during exports

Forum post:
https://www.simplemachines.org/community/index.php?topic=575293.0

> I cannot export my profile data, maybe it's another error due to the conversion from MyBB  ;D

```
Type of error: Database
Error message:
Errore del Database: 'user_smf.pm2.from_name' isn't in GROUP BY
File: /home/public_html/Sources/News.php
Line: 2593
URL of page causing the error: https://site.com/cron.php
Backtrace information
#0: smf_db_error()
Called from /home/public_html/Sources/Subs-Db-mysql.php on line 489
#1: smf_db_query()
Called from /home/public_html/Sources/News.php on line 2593
#2: getXmlPMs()
Called from /home/public_html/Sources/tasks/ExportProfileData.php on line 236
#3: exportXml()
Called from /home/public_html/Sources/tasks/ExportProfileData.php on line 459
#4: exportHtml()
Called from /home/public_html/Sources/tasks/ExportProfileData.php on line 117
#5: execute()
Called from /home/public_html/cron.php on line 233
#6: perform_task()
Called from /home/public_html/cron.php on line 127
```

### Environment (complete as necessary)
- Database Type: MariaDB

### Additional information/references
https://jira.mariadb.org/browse/MDEV-11588

https://github.com/SimpleMachines/SMF2.1/issues/6094

**Comment by albertlast** [comment]
This is not only a lazy ness factor,
in pg is this a performance advantage when you got a functional dependency,
since less operation are needed.

In pg the dependency get detected and related columns get ignored, with newer version.
Dunno how mysql handle this.

**Comment by sbulen** [comment]
Mysql honors it (and Percona, etc.).  The exception is specifically MariaDB.  And this has been an open MariaDB issue for a while...
