### ISSUE TITLE
2.1 RC3 Upgrader fails on invalid birthdays

### ISSUE THREAD

**Issue by LexArma** [SimpleMachines/SMF#6316]
#### Description
My site is originally from Xsorbit (ie SMF 1.something), and has been gradually updated all the way up to 2.0.17
Today, whilst testing upgrade to RC3 I ran in to problems with select members. 

The upgrader fails if there are birthdays ending in -00-00. 
I'm not sure how, or from what time in the past 15 years - but I had a handful of members with birthdays like that. 
Easy to fix manually by going in the DB and just changing it to -01-01, 
but could we do something to fix this in the upgrader in case others run in to this?

### Steps to reproduce
1. Have 2.0 with a member whose birthday is for example 1984-00-00
2. Run 2.1 RC3 upgrade
3. See results

### Additional information/references
I still have a clone of the original DB, so if further details are wanted I can actually redo the upgrade and gather information.

**Comment by live627** [comment]
This is the code in question

https://github.com/SimpleMachines/SMF2.1/blob/f7293b0277df74fe0262b87fb781cb048e9392b8/other/upgrade_2-1_mysql.sql#L24-L26

How shall partially filled birthdates be dealt with?

**Comment by sbulen** [comment]
Zeroes are not tolerated at all under our strict settings.

**Comment by sbulen** [comment]
I'm looking into this.  

Something very strange is happening.  It doesn't even get to the DB step at all...  I think that code would fix it if it got that far, but it doesn't.
