### ISSUE TITLE
Undefined index latestMember|latestRealName

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#6317]
#### Description
It seems latestMember and latestRealName keys on $modSettings doesn't get set on install, the values does exists on the DB:

![Screenshot from 2020-10-24 11-53-21](https://user-images.githubusercontent.com/3420756/97087424-c3b94c80-15ef-11eb-9b49-1ddf8366029b.png)

I recall this was reported before and I haven't really dig too much into it

### Steps to reproduce
1. Perform a clean install

### Environment (complete as necessary)
- Version/Git revision: at 52cc4a3283318a450937239f54911d7298517e33
- Database Type: MySQL
- Database Version: 8.0.21
- PHP Version: 7.4.3

### Additional information/references

```
#0: smf_error_handler()
Called from /SMF2.1/Sources/Subs.php on line 3764
#1: setupThemeContext()
Called from /SMF2.1/Sources/Subs.php on line 3879
#2: template_header()
Called from /SMF2.1/Sources/Subs.php on line 3499
#3: obExit()
Called from /SMF2.1/index.php on line 176
```
This is immediately after complete the installation, a refresh or any other action populates the keys accordingly.

**Comment by sbulen** [comment]
This has been reported before - but to the best of my knowledge it only happens when that last step is skipped or has some other issue & it doesn't complete properly.  

Do you see it every time?

**Comment by MissAllSunday** [comment]
Yep, everytime I perform a clean install but perhaps it is my setup/env  if anyone else hasn't been able to reproduce this then we can toss it aside.

**Comment by live627** [comment]
just a random guess but those vars could be populated on the very last step
in the  installer which sounds like it is being skipped on your side
