### ISSUE TITLE
Error deleting upgrade

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6320]
#### Description

This has been mentioned on the board several times, e.g.:
https://www.simplemachines.org/community/index.php?topic=575295.0
https://www.simplemachines.org/community/index.php?topic=575322.msg4071730#msg4071730
https://www.simplemachines.org/community/index.php?topic=575379.msg4072110#msg4072110

I cannot reproduce it, and I can't find anything in that code that has changed...  Very odd that it keeps showing up.

Logging it here, because it seems to be real...  If anybody has seen this, please share...

**Comment by MissAllSunday** [comment]
Got a feeling this is hosting specific,  could be something from poorly configured envs, permissions, overly paranoid security patches to time and memory limits.  We do a lot of unlink() calls.

Can't do much on our side if the hosting doesn't like unlink(), best we can do is check if it exists and is writable before calling unlink() on it

**Comment by sbulen** [comment]
I do suspect permissions...  

One thing we could (and probably should) do is hit those files with a quickFileWritable() before attempting the delete.
