### ISSUE TITLE
Dropzone displaying error page html, not error

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6328]
#### Description
I think Dropzone may have an issue when a server-side error is encountered.  Instead of displaying the error, it displays the html of the error page served up by the server...

Note, I cannot reproduce this.  Sharing in case it looks familiar to someone?

Multiple threads from the support board:
https://www.simplemachines.org/community/index.php?topic=575402.0
https://www.simplemachines.org/community/index.php?topic=575434.0

This exact dropzone issue has been reported before - apparently if there is a server-side error reported this can happen.  This thread shows how to trap the error instead of serving up the html:
https://stackoverflow.com/questions/39761736/dropzone-image-upload-error-display-how-to-remove-error

**_What you see instead (with console window open):_**
![smfhelper-issue2](https://user-images.githubusercontent.com/23568484/97907971-e5ef5080-1cfa-11eb-9b0c-57e8d8a44bd8.png)

**_This is the error in the console:_**
![smfhelper-issue3](https://user-images.githubusercontent.com/23568484/97911087-92333600-1cff-11eb-8a01-c3e22ca92561.png)

**_If you click on the link in the console error, this is what you see:_**
![smfhelper-issue](https://user-images.githubusercontent.com/23568484/97907722-8d1fb800-1cfa-11eb-8a13-91409db06147.png)

**Comment by sbulen** [comment]
I have confirmed here that part of the problem is that current_board is undefined...

So, this new logic kicks in:
https://github.com/SimpleMachines/SMF2.1/pull/6301/files

As a result, the URL built to upload the attachment has no board on it, which, I think, is why there is a permissions error on the upload.  

The js currently thinks it is being passed an error message to display.  But since the problem is bigger & deeper, our fatal error form is presented.  An entire page of html, which then gets embedded into the .js error message box where normally a message gets displayed...

**Comment by sbulen** [comment]
I can reproduce this using the current GitHub code.  Just add a regular user & have them try to upload a file.

I cannot reproduce this with RC3.  This appears to be due a post-RC3 change.

**Comment by sbulen** [comment]
Reverting this PR fixes it:
https://github.com/SimpleMachines/SMF2.1/pull/6301/files

@jdarwood007 - could you take a peek?

**Comment by smfbigguy** [comment]
Taking that code out worked perfect for me.
