### ISSUE TITLE
Gender being inactive in Profile Fields doesn't carry through to Stats page

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#633]
If you disable the Gender option in the list of fields that can be disabled when Advanced Profile Fields is on, sure, no-one can select it.

However, even when it's disabled, it's still listed (and collected) in the stats page. The only problem with removing it from there is that currently the top area in the stats page is nicely balanced with 7 rows of information in two columns and this would make it 7/6.

**Comment by live627** [comment]
>  The only problem with removing it from there is that currently the top area in the stats page is nicely balanced with 7 rows of information in two columns and this would make it 7/6.

Someone likes symmetry. :P

**Comment by Arantor** [comment]
It would be so wrong to make it unbalanced!
