### ISSUE TITLE
RC3 Show most recent posts at the top in topic view Problem

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#6333]
Hi,

please watch the video

https://streamable.com/mxi0k8

I tried on real and localhost there is a problem

Logout is required or a long wait is required to see messages

#### Description
--Description Here--

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by SychO9** [comment]
Duplicate of #5764

**Comment by gevv** [comment]
@SychO9  is there any code for solution?
