### ISSUE TITLE
Inconsistent additional settings below "My Messages"

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#6335]
#### Description
Most user settings are located in the various sub-sections of the "Forum Profile". Even the settings below the top-level "Alerts" are just a shortcut for Forum Profile 🡒 Notifications 🡒 Notification Preferences.
The only exception to this seems to be the settings below the top-level "My Messages", which are not reachable from the user profile, hence quite hidden.

My users keep getting confused by this ("I can't find these settings" / "The settings you talk about don't exist!!1eleven"), and I can relate (apart from the multiple exclamation marks; a sure sign of a diseased mind). 😉 

Is there a reason for this inconsistency? Could it be changed to be more consistent?

### Environment (complete as necessary)
- Version/Git revision: 2.1 RC2 (but probably also RC3)
- Database Type: any
- Database Version: any
- PHP Version: any

**Comment by MissAllSunday** [comment]
I'm sure there was a reason but due to developer turnover it has most likely be forgotten or not documented at all.  My bet would be that both alerts and messages were separated from the profile menu, hence both alerts and pm have their own settings page and links to them.

**Comment by MissAllSunday** [comment]
At this point we're not making changes to the UI
