### ISSUE TITLE
Incompatibility between Timezone.{language}.php and CrowdIn

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#6342]
As reported by m4z in [this topic](https://www.simplemachines.org/community/index.php?topic=573012.0), our Timezones language file is causing difficulties with CrowdIn. 

The trouble boils down to the fact that this special language file isn't just a normal translation file. It also functions like a configuration file that fine-tunes SMF's handling of time zones in order to meet the requirements for any given locale. It does this by allowing the localizer to decide which string variables will be defined in their version of the file. Giving a language file any influence on the program logic is, admittedly, unorthodox, but it actually works quite well to create a system that is at once user-friendly, accurate, and adaptable to varying locale requirements. (FYI, achieving all three of those at once is no simple feat when it comes to time zones.)

But however smoothly this all works within SMF itself, it doesn't play nicely with CrowdIn. This is because CrowdIn (quite reasonably) expects all the same string variables to be defined in each translation of the file. So for full compatibility with CrowdIn, we need to define all the possible strings in the file. Doing that, however, will leave the file unable to serve its secondary role as an ersatz config file. That in turn means that we'll need to define that configurtion information elsewhere.

The cleanest way to do this is to add a Subs-Timezones.php file whose only job is to determine that configuration Information. We will also need to add a whole lot more strings to the existing language file so that all possibilities are covered.

The good news is that I've almost finished coding this, so I'll submit a PR soon.

**Comment by jdarwood007** [comment]
Won't you still run into issues with translation since the language may define more strings than what is provided in the english file?

**Comment by Sesquipedalian** [comment]
> Won't you still run into issues with translation since the language may define more strings than what is provided in the english file?

Timezones.{language}.php now defines all the possible strings. I managed to keep the possibility for some customization for an individual locale, because many of the strings in that file are now `sprintf`-ed with the data. This allows a more limited degree of customization than before, but it should be good enough.
