### ISSUE TITLE
Undefined_vars with unsubscribe links 

### ISSUE THREAD

**Issue by mastum** [SimpleMachines/SMF#6346]
#### Description
Undefined_vars error when a user try to unsubscribe from email notifications.

![](https://i.postimg.cc/fR2RYp9M/smf-1.jpg)

![](https://i.postimg.cc/dQ896J38/smf.jpg)

### Steps to reproduce
1. Activate “Require new members to accept the privacy policy”
2. Send a newsletter to users
3. Click on link 
`To unsubscribe from forum newsletters, announcements and important notifications, follow this link:<br />https://mysite.com/SMF_test/index.php?action=notifyannouncements;u=2;token=ZB9GobxTf_r4Bw`
4. Try to unsubscribe and check error log.

PS. Yes there is a `<br /> ` before link.

### Environment (complete as necessary)
- Version/Git revision: SMF RC3
- Database Type: MariaDB
- PHP Version: 7.3.21

### Additional information/references

**Comment by Oldiesmann** [comment]
The `<br />` is because someone forgot you can't use HTML in plaintext emails 😛 

I'm not sure why you're getting those undefined errors as both of those language strings are defined in index.english.php, which should always be loaded.
