### ISSUE TITLE
Topic display is messed up if viewed in reverse order

### ISSUE THREAD

**Issue by BrickOzp** [SimpleMachines/SMF#6349]
#### Description
When setting "Show most recent posts at the top in topic view" is enabled the messages in a topic is sometimes not displayed.

### Steps to reproduce
1. Create one or more topics. One with at least three pages.
2. Enable setting Show most recent posts at the top in topic view
3. Display a topic with one page
4. Refresh page

5. All messages but the first is displayed

6. Display a topic with multiple pages
7. Jump between pages

8. Page is sometimes not updated, sometimes some messages are not displayed.

### Environment (complete as necessary)
- Version/Git revision: RC3 or latest git f837b0e4462
- Database Type: MySQL
- Database Version:
- PHP Version: 5.6

**Comment by SychO9** [comment]
Duplicate of #5764

**Comment by BrickOzp** [comment]
Issue already exists
