### ISSUE TITLE
moderation center with missing titles with sidebar menu

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#635]
i believe due to https://github.com/SimpleMachines/SMF2.1/commit/651820084e4b8aaaf4064c5a6d0f7d0185b9349f when using the sidebar menu in the moderation center many areas are missing headers

**Comment by Arantor** [comment]
It's passed on! This sidebar is no more! It has ceased to be! It's expired and gone to meet its maker! It's a stiff! Bereft of life, it rests in peace! 

It's kicked the bucket, it's shuffled off this mortal coil, run down the curtain and joined the bleedin' choir invisibile!! THIS IS AN EX-SIDEBAR!

(sorry, needed an easter egg somewhere)
