### ISSUE TITLE
Forum time is wrong unless default time zone is set to UTC

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#6366]
#### Description
If the admin sets the forum's default time zone to anything other than UTC (or to somewhere that uses GMT, such as Africa/Abidjan), then the timestamps calculated by `forum_time()` will be incorrect for logged in users. Specifically, the calculated time will be off by an amount equal to UTC offset of that default time zone.

Guests do not appear to be affected by this bug.

### Steps to reproduce
1. In Administration Center ►  Features and Options ►  General, set the forum's default timezone to, e.g., "America/Denver".
2. In Profile of <user> ►  Look and Layout, set your own time zone to the same value (e.g. "Mountain Time," which corresponds to "America/Denver")
3. Look at the time shown in the forum header and notice how wrong it is. For example, "Nov 21, 2020, 6:36 AM" when it should say "Nov 21, 2020, 1:36 PM"

### Environment (complete as necessary)
- Version/Git revision: 5d327fb
- Database Type: N/A
- Database Version: N/A
- PHP Version: Any

### Additional information/references
This bug appears to have been introduced in #5646.

**Comment by sbulen** [comment]
Hmmm....  Let me look into this.  

I had this all working perfectly 18 months ago when the PR was submitted...

**Comment by sbulen** [comment]
Yikes, confirmed...

**Comment by Sesquipedalian** [comment]
Fix added to #6344

Edit: Sorry, @sbulen. I didn't see your comment until after I'd committed my fix. Didn't mean to step on your toes. :)
