### ISSUE TITLE
Domain as category name causes trouble

### ISSUE THREAD

**Issue by NFGman** [SimpleMachines/SMF#6407]
#### Description
If your category name is a domain (URL.COM) then excess code appears in the page output.  Changing this to, for example, 'url' fixes it.  Instead of simply 'url.com' the category title shown to the user becomes:

`url.com" id="c3">url.com`

The correct title is always shown in the admin pages.

### Steps to reproduce
1.  Create or edit a category name to be a domain name:  url.com

### Environment (complete as necessary)
- Version/Git revision:  2.1 RC3
- Database Type: MySQL
- Database Version:  8.0.22
- PHP Version: 7.4

### Additional information/references
https://www.simplemachines.org/community/index.php?topic=576000.0

**Comment by NFGman** [comment]
Note that this also affects board names, as well as category names.  The URL becomes clickable but leads to the URL itself, not the board.  So if your board is url.com, that board can no longer be visited because the title and link text takes you to another site.

**Comment by jdarwood007** [comment]
I can't reproduce this and tested with both Firefox and Chrome latest.

This seems like a browser extension autolinking URLs?

**Comment by NFGman** [comment]
I just ran some tests.  I disabled all my extensions, and nothing changed.  I use Vivaldi, so I checked with Chrome (which is  base install, I never use it) and the garbage text in the category names is not showing, so that's something I'll look into.

The auto-linking of the URL in the board name is still happening, so the title of the board cannot be clicked on if it is only the URL (since it takes you to that URL, not the board).  The chatty icon can be clicked as normal.

**Comment by NFGman** [comment]
The page content differs for logged in or out users.   This is not a browser issue, or an extension problem.  A basic installation of Chrome breaks in the same way.

Logged in:

```
<h3 class="catbg">
<span id="category_3_upshrink" class="toggle_up floatright" data-collapsed="0" title="Hide Category" style="display: none;"></span>
<a href="https://mydomain/forum2/index.php?action=unread;c=3" title="Click to see the new posts in <a href="//URL.com" class="bbc_link" target="_blank" rel="noopener">URL.com</a>" id="c3"><a href="//URL.com" class="bbc_link" target="_blank" rel="noopener">URL.com</a></a>
</h3>
```

Logged out:

```
<h3 class="catbg">
<span id="c3"><a href="//URL.com" class="bbc_link" target="_blank" rel="noopener">URL.com</a></span>
</h3>
```

The bad code (again, creating a URL link where none was desired) in the board name happens in both browsers, regardless of logged in status:


```
<a class="subject mobile_subject" href="https://mydoman/forum2/index.php?board=8.0" id="b8">
<a href="//URL.com" class="bbc_link" target="_blank" rel="noopener">URL.com</a> &nbsp;General
</a>
```

**Comment by MissAllSunday** [comment]
Can you please update your forum to the latest build and see if the error still appears?

**Comment by NFGman** [comment]
The latest build (5 days old) seems to have solved the problem.  =)
