### ISSUE TITLE
wamp server install error

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#6410]
Hello,,

https://download.simplemachines.org/index.php?thanks;filename=smf_2-1-rc3_install.zip
https://0exclusive.de/smf/smf2.1_nightly_install.zip

php 7.2.18
wamp 3.1.9  64b

Notice: Undefined index: database_error in C:\wamp64\www\smf\Sources\Subs-Db-mysql.php on line 702
--

1 | 0.0001 | 406048 | {main}(  ) | ...\install.php:0
2 | 4.1153 | 477352 | DatabasePopulation(  ) | ...\install.php:145
3 | 4.6468 | 784856 | smf_db_insert(  ) | ...\install.php:1413
4 | 4.6469 | 786760 | smf_db_query(  ) | ...\Subs-Db-mysql.php:803
5 | 4.6471 | 786760 | smf_db_error(  ) | ...\Subs-Db-mysql.php:489

Fatal error: Uncaught Error: Call to undefined function allowedTo() in C:\wamp64\www\smf\Sources\Subs-Db-mysql.php on line 703
--

1 | 0.0001 | 406048 | {main}(  ) | ...\install.php:0
2 | 4.1153 | 477352 | DatabasePopulation(  ) | ...\install.php:145
3 | 4.6468 | 784856 | smf_db_insert(  ) | ...\install.php:1413
4 | 4.6469 | 786760 | smf_db_query(  ) | ...\Subs-Db-mysql.php:803
5 | 4.6471 | 786760 | smf_db_error(  ) | ...\Subs-Db-mysql.php:489

--------------------------------------------------------------------------------------------------------------------------

**Nightly version errors**

Notice: Undefined index: database_error in C:\wamp64\www\smf\Sources\Subs-Db-mysql.php on line 704
--

1 | 0.0001 | 406192 | {main}(  ) | ...\install.php:0
2 | 4.1004 | 476712 | DatabasePopulation(  ) | ...\install.php:145
3 | 4.5663 | 784640 | smf_db_insert(  ) | ...\install.php:1409
4 | 4.5664 | 786544 | smf_db_query(  ) | ...\Subs-Db-mysql.php:805
5 | 4.5666 | 786544 | smf_db_error(  ) | ...\Subs-Db-mysql.php:491

Fatal error: Uncaught Error: Call to undefined function allowedTo() in C:\wamp64\www\smf\Sources\Subs-Db-mysql.php on line 705
--

1 | 0.0001 | 406192 | {main}(  ) | ...\install.php:0
2 | 4.1004 | 476712 | DatabasePopulation(  ) | ...\install.php:145
3 | 4.5663 | 784640 | smf_db_insert(  ) | ...\install.php:1409
4 | 4.5664 | 786544 | smf_db_query(  ) | ...\Subs-Db-mysql.php:805
5 | 4.5666 | 786544 | smf_db_error(  ) | ...\Subs-Db-mysql.php:491

**Comment by MissAllSunday** [comment]
Can you update your forum to the latest build and make sure all the files are correctly set?

**Comment by gevv** [comment]
Nightly version gives the errors above

Direct github download gives the following errors;



( ! ) Notice: Undefined index: database_error in C:\wamp64\www\smf\Sources\Subs-Db-mysql.php on line 704
--


1 | 0.0001 | 406192 | {main}(  ) | ...\install.php:0
2 | 4.1111 | 476712 | DatabasePopulation(  ) | ...\install.php:145
3 | 4.5533 | 784640 | smf_db_insert(  ) | ...\install.php:1409
4 | 4.5534 | 786544 | smf_db_query(  ) | ...\Subs-Db-mysql.php:805
5 | 4.5536 | 786544 | smf_db_error(  ) | ...\Subs-Db-mysql.php:491


Fatal error: Uncaught Error: Call to undefined function allowedTo() in C:\wamp64\www\smf\Sources\Subs-Db-mysql.php on line 705
--



1 | 0.0001 | 406192 | {main}(  ) | ...\install.php:0
2 | 4.1111 | 476712 | DatabasePopulation(  ) | ...\install.php:145
3 | 4.5533 | 784640 | smf_db_insert(  ) | ...\install.php:1409
4 | 4.5534 | 786544 | smf_db_query(  ) | ...\Subs-Db-mysql.php:805
5 | 4.5536 | 786544 | smf_db_error(  ) | ...\Subs-Db-mysql.php:491

**Comment by gevv** [comment]
change database name problem solved
