### ISSUE TITLE
From forum:  unidentified index, page_ascending

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6412]
#### Description
Type of error: Undefined
8: Undefined index: page_ascending
 https://URL/forum2/index.php?topic=5463.0
 /var/www/web/forum/Sources/Display.php (Line 867)

User says he started seeing this shortly after upgrade to RC3.
https://www.simplemachines.org/community/index.php?topic=575999.0

### Additional information/references
albertlast notes it is related to this PR:
https://github.com/SimpleMachines/SMF2.1/pull/6272

**Comment by sbulen** [comment]
@albertlast - Thoughts?

**Comment by albertlast** [comment]
I don't understand you.
The problem got already fixed with mention pr.

**Comment by sbulen** [comment]
I misread your note in the forum.  Closing.
