### ISSUE TITLE
Upgrader - json conversion completion not always recorded

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6415]
#### Description
This user is attempting an RC1 to RC3 conversion.  Failing at the json conversion step for an unknown reason.
https://www.simplemachines.org/community/index.php?topic=576054.msg4075924#msg4075924

Why is it even attempting the json conversion again?

There is a flag in the settings table for 'json_done', and it looks like it was not set in this instance.  I don't think this has changed since RC1...

I have several converted 2.1 test environments, so I reviewed them all, and I found that json_done was not set all of them.

I am still attempting to identify why this happens occasionally...  But it's a thing...

### Environment (complete as necessary)
- Version/Git revision:  Current
- Database Type:  mysql
- Database Version:  5.7
- PHP Version:  7.4

**Comment by MissAllSunday** [comment]
Not really fond of spending time debugging RC to RC issues :/  2.0 to 2.1 issues sure but RC to RC are, at best, very low priority.

**Comment by Sesquipedalian** [comment]
Have you found any situations where 'json_done' is not set during an upgrade from 2.0.x to 2.1, @sbulen? If not, can we close this?

**Comment by sbulen** [comment]
Yes.  I just looked at my last **9** upgrade tests, including three 2.0 =>2.1 upgrades, and the flag wasn't set on any of them.

It's definitely a thing... 

What makes it worse is it is used as a a generic "one time only" flag for other 2.1 conversion steps, in particular around attachment processing.

I'll look deeper into this; haven't had a chance lately.

**Comment by sbulen** [comment]
My initial guess is it's failing on all browser/xml upgrades.  CLI appears to be fine.  I suspect the XML completion logic is exiting before the flag is set.

**Comment by Sesquipedalian** [comment]
Yikes.
