### ISSUE TITLE
Missing language strings for notifications

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6421]
#### Description
Note the language strings for notifytopic_subscribed, notifytopic_unsubscribed, notifyboard_subscribed, notifyboard_unsubscribed do not exist.  

Reported in the support forum:
https://www.simplemachines.org/community/index.php?topic=576115.0

Where used:
https://github.com/SimpleMachines/SMF2.1/blob/14534158667dfea36ce9917c49a2e54ac0087de9/Sources/Notify.php#L318
https://github.com/SimpleMachines/SMF2.1/blob/14534158667dfea36ce9917c49a2e54ac0087de9/Sources/Notify.php#L148

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: any
- Database Version: any
- PHP Version: any

**Comment by sbulen** [comment]
I *believe* this can be resolved by adding an underscore "_" in these two locations, changing "notifyboard" to "notify_board" and "notifytopic" to "notify_topic".  Since I cannot reproduce, I can't confirm.

**Comment by Oldiesmann** [comment]
Adding the missing _ as @sbulen suggested will resolve the problem.

**Comment by sbulen** [comment]
Forum user reported it worked as well.
