### ISSUE TITLE
Language String to Mark Read Logs

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#6423]
SMF RC3 Current build

Language String to Mark Read Logs

I find that a little confusing. Im Sprach String ManageSettings.english.php

https://github.com/SimpleMachines/SMF2.1/blob/a138346cab790479b6fa6c84263bf3f07949ef73/Themes/default/languages/ManageSettings.english.php#L40

it says Mark Read Logs. In the language string ManageScheduledTasks.english.php

https://github.com/SimpleMachines/SMF2.1/blob/a116f624883c268e1742be0fb859d677a3e3bebe/Themes/default/languages/ManageScheduledTasks.english.php#L64

it says Mark Read Logs. 

I think that in ManageSettings.english.php it would be better to name it as "Marks boards read" as well.

ManageSettings.english.php
`$txt['markread_title'] = 'Mark Read Logs';`

change to

`$txt['markread_title'] = 'Marks boards read Logs';`

Mark Read is not meaningful and might be incomprehensible to some translators to translate.

In my opinion it would also be better to mark the setting in the text:
`$txt['scheduled_task_desc_prune_log_topics'] = 'Marks boards read for users inactive longer than the number of days defined in the &quot;<em>Marks boards read Logs</em>&quot; settings in the admin panel.';`

**Comment by albertlast** [comment]
i don't like html code in text string.

**Comment by wintstar** [comment]
The marking does not have to be, but the text I think should be changed.
