### ISSUE TITLE
Database nit - smf_user_alerts_prefs different when installed vs upgraded

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6425]
#### Description
The field alert_value is tinyint(4) when installed, but tinyint(3) when upgraded.

### Additional information/references
Caught in the wild here:
https://www.simplemachines.org/community/index.php?topic=576115.msg4076590#msg4076590

**Comment by albertlast** [comment]
and doesn't care because (x) value get ignored :P.

**Comment by sbulen** [comment]
Correct...  And looking back, when we brought the installer & upgrader DBs in sync, we agreed not to change all of these....
