### ISSUE TITLE
Custom Profile Fields can not be translated

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#6435]
I had already reported this once https://github.com/SimpleMachines/SMF2.1/issues/4381.

I also remember that it was discussed. In a multilingual forum it should be possible that the input of user-defined fields can also be translated.

There are already language strings, but they do not work
https://github.com/SimpleMachines/SMF2.1/blob/35a6bd91253ca655f2c3bad62033a9998329f2db/Themes/default/languages/index.english.php#L222-L225
https://github.com/SimpleMachines/SMF2.1/blob/35a6bd91253ca655f2c3bad62033a9998329f2db/Themes/default/languages/index.english.php#L231-L232

![custom_profile_fields](https://user-images.githubusercontent.com/2753863/103447525-adcda500-4c8c-11eb-94ef-cb76e961cc4d.png)

User profile settings
![image](https://user-images.githubusercontent.com/2753863/103447660-52041b80-4c8e-11eb-8849-af9671067742.png)

Statistics
![custom_profile_fields_3](https://user-images.githubusercontent.com/2753863/103447685-cb9c0980-4c8e-11eb-90be-d90a7b0f02e7.png)

There should be a possibility to have a separate field for each installed language pack.

![custom_profile_fields_2](https://user-images.githubusercontent.com/2753863/103447607-be324f80-4c8d-11eb-8644-7e11122c5791.png)

**Comment by albertlast** [comment]
and where should be this saved?

**Comment by wintstar** [comment]
It does not have to be stored in the database.  You could create it as a language string, maybe in Modifications.english.php. This function already exists in this function is  available in "Edit Languages => Add another Item".

**Comment by MissAllSunday** [comment]
I don't really understand the issue here. Custom values are, well, custom. You can edit them and add whatever you want, including changing their name and description.  We can't really "force" names and descriptions to be set on languague files since that would severely limit the functionality and will force the user to edit their language files in order to add custom fields.

As a Spanish user I rather prefer to deal with translation in a single place, edit the custom field and do the translation there rather than having to create the custom field and then having to add yet another language string. Not to mention having their names and descriptions on a language file means those can be ereased/replaced by modifications or custom code and will therefore be prone to errors.


The only feasible way to provide an already translated name and description would be to select your languague on install and that will only work for the default custom values, all other user generated values will have to be raw translated on creation since SMF has no idea what kind of custom profile field you will create.

**Comment by wintstar** [comment]
If you look back at the last issue, gender, for example, worked with a fixed language pack. Now it no longer works. Look at my screenshots.
Now when I look at the main forum simplemaschines.org, this forum is for different languages of the members. That means with a custom profile field the French can only guess, as well as the Italian, Russian etc. what is asked for in the custom profile field. Because the custom profile field is only available in Dutch.
This is not optional. If you offer several language packages, the displayed texts should be translatable into several languages, especially in the member profile.
When administrators install mods in their forums, they must also change the language packs. Since the mods are not available for all language packs. 
If I change the language pack in the Admin Center in the function "Edit Languages => Add another Item", is it not a problem?  Why not use this function for the user-defined profile fields as well, what's wrong with that?

**Comment by sbulen** [comment]
> When administrators install mods in their forums, they must also change the language packs. Since the mods are not available for all language packs.
> If I change the language pack in the Admin Center in the function "Edit Languages => Add another Item", is it not a problem? Why not use this function for the user-defined profile fields as well, what's wrong with that?

It would be great if the profile fields were all easily predicted & translatable...  

The question is, who provides the translations for the user-created fields?  When?

The thing about a mod is it is centrally located, and acquires users & fans, and language packs can be added to the SMF customization site.  Also, even mods have _a fixed #_ of labels needed to be translated.  Just like SMF itself.

Custom profile fields are added by _tens of thousands of_ individual forum owners, completely independent of the SMF team...  How is SMF to know what labels/translations are needed?  Who does the translations?

**Comment by MissAllSunday** [comment]
A set of tokens {gender_name} {gender_desc} that are parsed into defined txt vars  for default custom fields can be added, because they are shipped by default and we know them.

But thats only feasible for default custom fields, we cannot realistically add support for any multi-language custom field any user might want to add, even if we add empty pre-defined txt $txt['custm_0_name], $txt['custm_0_desc], $txt['custm_1_name], $txt['custm_1_desc] there will only be a finite number of custom fields which means it will severily limit the functionality.

**Comment by MissAllSunday** [comment]
I think I have an idea to make it work without adding complexity but it will require admins to know what they are doing (IE, define their own language $txt)

**Comment by sbulen** [comment]
Nothing is impossible...

I was thinking that if we had to do it, it would be more along the lines of a profile field request system, where frequently requested fields could be added to the translation queue.  It becomes an ever-increasing list of available fields to add.

But...  

Whatever the solution...  We're really talking about SMF 2.3 or so...   Certainly not a priority before final.  We shouldn't be entertaining enhancements of this scope before final.

**Comment by wintstar** [comment]
> A set of tokens {gender_name} {gender_desc} that are parsed into defined txt vars for default custom fields can be added, because they are shipped by default and we know them.
> 
> But thats only feasible for default custom fields, we cannot realistically add support for any multi-language custom field any user might want to add, even if we add empty pre-defined txt $txt['custm_0_name], $txt['custm_0_desc], $txt['custm_1_name], $txt['custm_1_desc] there will only be a finite number of custom fields which means it will severily limit the functionality.

Every administrator should know what he is doing. And if someone runs a forum, he should also be able to do more than just install a forum. 

My idea is based on when creating a custom field, the possibility to create a language file / or strings with php and enter them into a language file. When deleting the field, this can also be removed from the language file.

**Comment by MissAllSunday** [comment]
@wintstar Can you test it out #6498 to see if you can find any issues with the implementation?

**Comment by wintstar** [comment]
@MissAllSunday, I am already in the process.
https://sf-atelier.stephan-frank.de/smfrc/index.php/topic,4.msg158.html#msg158

**Comment by wintstar** [comment]
Works, but in Stats and Memberlist gender not work. And the change for yahoo in Database is missing.

![image](https://user-images.githubusercontent.com/2753863/108625260-3a554200-744a-11eb-9170-7069dd63e75a.png)

![image](https://user-images.githubusercontent.com/2753863/108625274-480ac780-744a-11eb-98fe-d8a965f5d4c8.png)

I have tested gender with the settings "With symbol" and "Standard (with text)".

**Comment by wintstar** [comment]
Solution Example Summary
Themes/default/Profile.template.php

If I use this code 
https://github.com/SimpleMachines/SMF2.1/blob/9236c6402cd83ce9c0b441ba7202d42d9f1f3af9/Themes/default/Profile.template.php#L344

change to, the text is displayed.
`<dt>', $txt['' . $field['name'] .''], ':</dt>`

![image](https://user-images.githubusercontent.com/2753863/108623196-f6f4d680-743d-11eb-89ca-9ebde1409c89.png)


The string for gender $field['output_html'] seems to be empty.

I have checked this in the template

```
			foreach ($fields as $field)
			{
				echo '
				<dt>', $txt['' . $field['name'] .''], ':</dt>
				<dd>', $field['output_html'], '</dd>';

				var_dump($field['output_html']);
			}
```

**Comment by MissAllSunday** [comment]
Will take a look at the stats and memberlist page. We no longer offer support for yahoo messenger since the service itself isn't available anymore.

**Comment by wintstar** [comment]
> Will take a look at the stats and memberlist page.

I will do

> We no longer offer support for yahoo messenger since the service itself isn't available anymore.

Right. I had forgotten that this no longer exists


Very good idea the function  tokenTxtReplace :+1:

**Comment by wintstar** [comment]
Member list also works. I had overlooked a place to insert something.

I was able to solve the error in the forum statistics like this

https://github.com/SimpleMachines/SMF2.1/blob/660ed67b50dbdfcaee9962447ce585df115604b2/Themes/default/Stats.template.php#L75

change to
`echo tokenTxtReplace($g), ': ', $n, '<br>';`
