### ISSUE TITLE
Remove UI option for 'disable admin security'

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#644]
Just before we get into this, let me cover what admin security is.

Admin security is the system by which SMF prompts an admin to log in every hour. It is on by default but can be turned off in Admin > Config > Security and Moderation.

Now, I don't want to remove it; it's useful on localhost setups, but honestly I'm not sure it needs to be an option in the main admin panel. I've never been keen on options that by which a user can choose to make their setup less secure with only a couple of clicks.

So I'm suggesting we remove the tickbox in the admin panel - and anyone who _does_ need to implement it can do so directly from phpMyAdmin or similar. That way it's not something people can do by accident, they will have to make a conscious choice to do so.

**Comment by beratdogan** [comment]
I agree with you, the tickbox should be removed. And that option can be enable/disable via editing Settings.php file, I think. Like:

``` php
$disable_admin_security = true|false; // 
```

With this way, only self-conscious users can disable admin security.

**Comment by Arantor** [comment]
It can't currently be done from Settings.php though I'm not averse to doing it from there. I would personally prefer not to add yet another global variable, especially one that will be false for virtually every install.

**Comment by illori** [comment]
i can see the pros of removing this, but i have had to use this on a production site due to needing to run the attachments maintenance task and it ran several hours and the log in would stop it. it was easy to disable the admin security and let it run.

also semi related to this, why in 2.1 and not in 2.0 do we have moderation center security? i really dont see the need to put in your password to view basically a bunch of logs

**Comment by Arantor** [comment]
I haven't looked at exactly what that setting covers but there are things like editing others' profiles that could be affected by it.

And yes, I can see your argument, however those are still fringe cases, yes?

**Comment by illori** [comment]
yes they would not be everyday use cases, but they would happen and not always would the person that can "fix" the issue always need to get access to the database which if this setting was removed they would need file and/or database access so they could change the setting to let a task like that keep running.

**Comment by Arantor** [comment]
Maybe that means we need to fix that task to be able to run in the background...

**Comment by illori** [comment]
and then how would you see the results where it asks if you need to delete extras that are found?

**Comment by Arantor** [comment]
Can't argue that one.

**Comment by illori** [comment]
do you think we really need the option for the moderation center? i think having the option in the first place is a bit useless.

**Comment by Arantor** [comment]
Until I review exactly what the option covers, I'd definitely leave it in place.

**Comment by illori** [comment]
it is the same as the feature for the admin panel but requires a password for the moderation center. and you need to log back in every hour etc

**Comment by Arantor** [comment]
Hmm, I thought - perhaps naively - that things like editing profiles was covered by it, but it isn't. In fact, it is indeed the only thing covered, and given what that offers (moderation log, reported posts, unapproved posts), it's not particularly significant.

Either it needs to be expanded and cover more things (like profiles), or removed, but that's just IMO.

**Comment by illori** [comment]
i would say remove it, it IMO is more of an annoyance then helpful.

**Comment by Oldiesmann** [comment]
It does appear that the "disable admin security" option affects other things as well.

On my test board:
Go to the admin center, then choose the "admin end session" option from the menu
Go to a user's profile and try to edit it
As soon as you click "change profile", you're asked for your password

Go back to admin center
Disable admin security
Go back to user's profile
You can now edit it without having to enter a password.

**Comment by Arantor** [comment]
There are _two_ things up for debate here.

1) the UI option for admin security - and if you don't have admin security enabled, you don't need the admin end session stuff for the obvious reason that you're always permanently in an admin session, and that also means the profile edits etc. - I never suggested removing admin security, merely the UI option for it, meaning users would have to do a DB edit instead to enable/disable it rather than accidentally enabling it.

2) there is a separate option for moderator security which solely covers the moderation centre, which seems rather pointless as it currently stands. That's the part we moved into talking about removing entirely (or expanding)

**Comment by Oldiesmann** [comment]
1. The "admin end session" option doesn't appear if you've disabled admin security. Either way, I definitely agree we should remove the UI option for it, as we don't want to make it easy to enable that (even though that checkbox has been there since 2.0).
2. I'm not sure why you'd want to enable this setting to begin with, but I'm fine with removing it.

**Comment by Arantor** [comment]
1. Of course it doesn't! Why would it? If you disable admin security, you never get the whole elevated permission thing in the first place, so ending admin session does precisely squat. Oh, and the checkbox was there in 1.1.x as well, only even MORE prominently so (it's in Features and Options > Basic Features) There is the valid argument Illori raised, though, that there are times you do need to enable it to get through the maintenance things on a larger install, and that made me pause to consider that perhaps we shouldn't remove it at the present time. (To fix this, I'd suggest we reconsider how the maintenance things can be run, firstly I'd be inclined to provide some of the heavier-weight maintenance scripts additionally as CLI scripts, and secondly I'd be inclined to provide some kind of background processing that allows for them not to require admin intervention. In the case of the example Illori provided this is not something that can be trivially done without a much larger change to the maintenance area, but we'll deal with it in 3.0. I have some ideas that will work just great for this.)
2. Moderation security (like admin security) is enabled by default, and carries all the other stuff with it, meaning moderators can also end session and whatnot, after re-logging in to get to the moderation panel, and relogging in every hour, just for that. Now, I'm not averse to ripping it out, but I feel like we should at least try to find a use for it before we do that :P

**Comment by illori** [comment]
and what use would we be able to find for the moderation security feature? another way to annoy the moderators and keep them from using the tools they have available due to needing to type in their password each time they need to access it

**Comment by Arantor** [comment]
Well, how often do people go into the moderation area? I've done it a total of once since I became dev team on sm.org and that was to check one thing in the log to answer a random question that came up.

That said, anyone thoroughly doing heavy-weight moderating will be in and out of the panel and continue to do so for the hour they have before the next login, so that's less of an issue.

As I said I could see the use of it being extended to certain types of profile editing but that raises a bunch of other issues too (so maybe not, then!)

I wonder if anyone else has any ideas on the subject but the more we look at this I'm inclined to think we can't do anything with it and it should go - but I don't want to throw it out just yet in case we _can_ do something with it.

**Comment by illori** [comment]
depends on the size of the forum, if you do a lot of moderating you may spend hours doing stuff and every hour needing to log back in can be annoying and cause the person to stop moderating.

i know compared to how 2.0 works if this was enabled on a forum i moderate i would be much less likely to go in the moderation center at all just because the password only lets you stay logged in for 1 hour.

**Comment by Arantor** [comment]
Yup, there is a very real usability vs security issue here. However, here's the thing: the re-entry of passwords is primarily about limiting the damage a user can do if they manage to steal a session.

Let's say, then, that the session of a moderator - but not their password - is compromised. For the life of that session, then, what could the attacker do? Well, they can still approve posts from the post listing, they can delete posts, move topics, merge, split etc. As far as I know they're prevented from doing approving member group changes and accessing the log. I think even warning users is doable without this security.

By that logic, all of the moderation actions should come under the same security but as you rightly point out it is a usability issue.

**Comment by illori** [comment]
i really dont see that much "security" required for the whole moderation center, most of the time general moderators are not moderators of groups and such, and other tasks moderators can do are without the moderation center as you said.

if it is an issue we can always put the password on certain sections like changing member groups or view members in a group [which i think includes showing all the email addresses even if the user has not opted to allow people to view their email addresses]

**Comment by Arantor** [comment]
That's the thing, there isn't a lot of security for the mod centre, but the mod _security_ could conceivably applied to mod actions that are active, like deleting, like approving, like merging and splitting. They're all moderator actions, after all and they are more active than anything in the centre.

On the other hand, there are already precedents for admin security elsewhere (such as editing profile details) so having that extra security outside the obvious area is not unknown. Perhaps we should apply it to moderation actions outside the mod centre.

**Comment by illori** [comment]
i think that would be worse and push people away from using smf due to that. i know i would stop doing things i have had to type in my password everytime i wanted to move a thread or edit a post etc.

**Comment by Arantor** [comment]
There was more discussion on the forum about this, and the general consensus was that it wasn't as bad as 'every time', and we could make moderation security one day rather than one hour and see how that works out in practice.

**Comment by NanoSector** [comment]
Any progress on this? Should just be a one-liner (assuming SMF uses empty() on the $modSettings variable already), I can do this one if wanted.

**Comment by illori** [comment]
i dont think there is really a clear answer on this, unless i missed it. some are considering extending the requirement for the moderation center password to elsewhere.

**Comment by Arantor** [comment]
You would not use variable checking here. validateSession does it all itself.

**Comment by Xarcell** [comment]
This may be a stupid question, but instead of setting both the admin and moderators to re-login every hour regardless of activity, why not set it based on in-activity? Say for example, if the admin or moderator goes inactive for 15 minutes, re-login required.

**Comment by Arantor** [comment]
Not really recommended, because it would be possible to use that towards escalating an account or system takeover. The whole point of admin security is that the admin has to reauthenticate on a regular basis to mitigate account being taken over. If the account doesn't require reauthentication, because it's active, you can keep getting the admin to appear to be active as far as admin sessions goes to the point where compromising admin security doesn't actually require a password compromise. It only requires a session compromise which is an order of magnitude simpler to pull off on a purely technical level (though probably easier to simply get the password by way of social engineering if you really wanted to...)

**Comment by Xarcell** [comment]
Ok I see. Never thought of it that way.

**Comment by XinYenFon** [comment]
I vote to close this issue and leave the setting as is.

**Comment by Sesquipedalian** [comment]
> I vote to close this issue and leave the setting as is.

Agreed.
