### ISSUE TITLE
New DB parameter types: literal and empty

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#645]
This is something I've done before but I want to know what the thoughts are on it. We already have the ability to inject properly escaped strings in the query layer, however currently we have situations like this query:

```
$request = $smcFunc['db_query']('', '
    SELECT id_comment
    FROM {db_prefix}log_comments
    WHERE comment_type = {string:ver_test}',
    array(
        'ver_test' => 'ver_test',
    )
);
```

We're adding a whole parameter just for the sake of including what is otherwise a literal.

I'd suggest adding the literal operator as such that would allow us to improve readability in queries without affecting security.

```
$request = $smcFunc['db_query']('', '
    SELECT id_comment
    FROM {db_prefix}log_comments
    WHERE comment_type = {literal:ver_test}',
    array()
);
```

We still end up getting ver_test escaped as a string, for whichever backend we're dealing with, but without having to go through anything extra with it.

While we're on the subject, we could also add an {empty} option, for when we need to add an empty string without having to manually declare an empty string as a parameter.

Random example (before)

```
$request = $smcFunc['db_query']('order_by_board_order', '
    SELECT b.id_board, b.name AS board_name, c.name AS cat_name
    FROM {db_prefix}boards AS b
        LEFT JOIN {db_prefix}categories AS c ON (c.id_cat = b.id_cat)
    WHERE redirect = {string:empty_string}',
    array(
        'empty_string' => '',
    )
);
```

Random example after:

```
$request = $smcFunc['db_query']('order_by_board_order', '
    SELECT b.id_board, b.name AS board_name, c.name AS cat_name
    FROM {db_prefix}boards AS b
        LEFT JOIN {db_prefix}categories AS c ON (c.id_cat = b.id_cat)
    WHERE redirect = {empty}',
    array()
);
```

It just seems more readable to me; performance is not significantly affected either way. Also note that if implemented, we wouldn't go on a witch-hunt to fix these, but fix them as we find them.

**Comment by siddhartha-gupta** [comment]
Hi Arantor,
- 'literal' option sounds great as it surely going to reduce the extra vars of array.
- About 'empty' I'd say lets keep 'literal' in place of empty only, as you might want to name it empty, but one can name it as 'blank/empty_string/blank_sting'. Point is that naming it to a specific word can create confusion. So if someone wants to use a blank sting, lets have 'literal' as blank string i.e ''.

**Comment by MissAllSunday** [comment]
I like both options, perhaps it would be helpful to add an empty array too?  {empty_array} I gotta say the specific cases where this would be used are limited but it never hurts to have it covered, like the "raw" case.

**Comment by Arantor** [comment]
I would really not want to use literal to handle empty strings. An empty string is an empty string, regardless of anything else, and frankly it should be treated as such: with a single covering entry. Besides, the equivalent correct code, {literal:} just looks completely wrong in any case, because it looks flat out mismatched.

As far as empty-array goes, it wouldn't actually work. You can't have SELECT ... WHERE var IN () at least in MySQL, and that's where arrays are injected into queries.

**Comment by Oldiesmann** [comment]
I like both ideas, and agree with you about empty arrays. I can't think of when we'd need to pass an empty array to a query.

**Comment by MissAllSunday** [comment]
oh yeah, now I see empty array won't do much.
