### ISSUE TITLE
Users with Update Boards & Categories permissions can't see boards & categories

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6450]
#### Description
Reported on the forum & confirmed.  

Very odd, I do not see this on my wamp, but I do see it on my hosted linux environment.  

On both wamp & linux, if I view the permissions of the user in question, the restricted boards are listed as not accessible to this user.

### Steps to reproduce
1. On a linux environment....
2. Give 'Global Moderators' the ability to update boards & categories under Admin | Forum | Manage Boards & Categories | Settings
3. Create a category only visible to Global Moderators
4. Create a board under that category only visible to Global Moderators
5. Create a user & assign to Global Moderators as his primary group
6. Logon as that user & the boards are missing...

### Environment (complete as necessary)
- Version/Git revision:  RC3
- Database Type: Mysql
- Database Version: 5.6
- PHP Version: Both 5.4 & 7.3

### Additional information/references
Reported on the support forum here:
https://www.simplemachines.org/community/index.php?topic=576328.0

**Comment by jdarwood007** [comment]
Steps 3-5 mention Global Admin.  Is it supposed to be Global Mod?

I would assume that those with the ability to update boards/cats could only update those they can see.

**Comment by sbulen** [comment]
Yes, I'll correct the above, thanks.  

These boards are configured to be visible to Global Moderators, but aren't.  Unix only, which is odd...

**Comment by sbulen** [comment]
Screenshots:

Global Moderators have permission to Manage Boards & Categories:
![image](https://user-images.githubusercontent.com/23568484/104269645-a60bbe80-544b-11eb-9653-75e37666eca1.png)

Global Moderators have access to the board:
![image](https://user-images.githubusercontent.com/23568484/104269819-0569ce80-544c-11eb-89ba-0bb8770dc722.png)

User is a Global Moderator:
![image](https://user-images.githubusercontent.com/23568484/104269867-1fa3ac80-544c-11eb-96fd-8ccb56cfb412.png)

But cannot see the board at all (unix only, fine on windows):
![image](https://user-images.githubusercontent.com/23568484/104269936-4235c580-544c-11eb-9697-0d212891a23e.png)
![image](https://user-images.githubusercontent.com/23568484/104270029-67c2cf00-544c-11eb-9406-7304b23d0682.png)

Both unix & windows have this message on the user profile permissions tab:
![image](https://user-images.githubusercontent.com/23568484/104270202-cab46600-544c-11eb-832e-397318709b7a.png)

**Comment by sbulen** [comment]
ACK!!!  This is a dupe of #6302
