### ISSUE TITLE
Moderator Notes Time Stamp

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#647]
Reference: http://www.simplemachines.org/community/index.php?topic=511645.0

Previously discussed on #505

**Comment by Arantor** [comment]
Hmm, #505 already even mentions the time stamp stuff...

**Comment by MissAllSunday** [comment]
Yes, I just wanted to have it separate, it is difficult to decide on what I should be focusing on, but since this will be a part of something bigger feel free to close it.
