### ISSUE TITLE
unreadreplies page mobile problem

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#6483]
topic title  narrow on unreadreplies page

responsive.css solution;
```
   /* Unread */
   #unread .board_icon, #unread .lastpost {
      display: none;
   }
   
  #unreadreplies .board_icon, #unreadreplies .lastpost {
      display: none;
   }
```

#### Description
--Description Here--

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by BrickOzp** [comment]
I don't think we should remove .lastpost, as it contains information about the latest post, and that is the purpose of the unread topics page.
Maybe the board icon can be skipped.

Edit: On the other hand, this information is not shown on Unread Posts page. Maybe it should be consistent
