### ISSUE TITLE
Warning: sprintf(): Too few arguments Guests change languages

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#6487]
![Untitled 1](https://user-images.githubusercontent.com/5096676/106396680-9fed7a00-641a-11eb-8b59-55867797dcba.png)
Hi,

The following error appears when guests change languages

Warning: sprintf(): Too few arguments in /Themes/default/index.template.php on line 247

No problem when logged in

php 5.6  nightly github smf2.1 rc3

#### Description
--Description Here--

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by frandominguezl** [comment]
Hello!

Well this is a language specific issue. In index.french.php, you have the following code:

```
// argument(s): $txt['guest_title'], login URL, login JavaScript snippet
$txt['welcome_guest'] = 'Bienvenue, <strong>%1$s</strong>. Merci de <a href="%3$s" onclick="%4$s">vous connecter</a>.';

// argument(s): forum name, login URL, login JavaScript snippet, signup URL
$txt['welcome_guest_register'] = 'Bienvenue sur <strong>%2$s</strong>. Veuillez vous <a href="%3$s" onclick="%4$s">connecter</a> ou vous <a href="%5$s">enregistrer</a>.';
```

Could you please change those lines to:

```
// argument(s): $txt['guest_title'], login URL, login JavaScript snippet
$txt['welcome_guest'] = 'Bienvenue, <strong>%1$s</strong>. Merci de <a href="%2$s" onclick="%3$s">vous connecter</a>.';

// argument(s): forum name, login URL, login JavaScript snippet, signup URL
$txt['welcome_guest_register'] = 'Bienvenue sur <strong>%1$s</strong>. Veuillez vous <a href="%2$s" onclick="%3$s">connecter</a> ou vous <a href="%4$s">enregistrer</a>.';
```

That should solve the issue. Please confirm me so.

I'll make sure that all the languages correct this specific issue.

**Comment by gevv** [comment]
Hello  @frandominguez03 

same error appears in other languages
