### ISSUE TITLE
'HTTP Error 500' when trying to edit ban triggers (PHP 8.0)

### ISSUE THREAD

**Issue by Hatshepsut71** [SimpleMachines/SMF#6488]
Hello,
I'm using SMF 2.1 RC3+ (commit c5fd8ce) with PHP 8.0.
When I'm trying to edit an existing ban trigger, I get 'HTTP Error 500' message on the white screen, and I cannot edit the trigger at all.

Forum details:

Forum version: SMF 2.1 RC3 (more detailed)
Current SMF version: SMF 2.1 RC3
GD version: bundled (2.1.0 compatible)
MySQL engine: MariaDB
MySQL version: 10.3.27-MariaDB-log
SMF file based caching: 2.1 RC3
SQLite3 database based caching: 3.7.17
PHP: 8.0.0 (more detailed)
Server version: Apache

Steps to reproduce
1.  Install last Github build c5fd8ce
2.  Set forum to run on PHP 8.0
3.  Try to edit an existing ban trigger

### Environment (complete as necessary)
- Version/Git revision: c5fd8ce
- Database Type: MariaDB
- Database Version: 10.3.27
- PHP Version: 8.0

### Additional information/references

The error exist and in previous build d248131
The error is gone if I switch forum to PHP 7.4 (I have no tested with any lower PHP versions)

**Comment by dragomano** [comment]
Subs-List.php, line `$list_context['total_num_items'] = call_user_func_array($call, empty($listOptions['get_count']['params']) ? array() : $listOptions['get_count']['params']);` replace with `$list_context['total_num_items'] = call_user_func_array($call, empty($listOptions['get_count']['params']) ? array() : array_values($listOptions['get_count']['params']));` Does it fix your issue?

**Comment by Hatshepsut71** [comment]
Yes, that change fix the issue! Thanks :)
