### ISSUE TITLE
 Redirect  board count ?

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#6490]
Hi,

Post count and topic count appear

Clicking on the  redirect  board link increases the number of post

smf 2.1 rc php 5.6

![Untitled 2](https://user-images.githubusercontent.com/5096676/106637481-cc78d180-6593-11eb-95fd-d25cf833fc9d.png)

#### Description
--Description Here--

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by jdarwood007** [comment]
Thats how it is supposed to work.  However the template is supposed to change it to be more friendly

template_main
```
			// Show some basic information about the number of posts, etc.
			echo '
					<div class="board_stats" title="', $board['type'], '">
						', function_exists('template_bi_' . $board['type'] . '_stats') ? call_user_func('template_bi_' . $board['type'] . '_stats', $board) : template_bi_board_stats($board), '
					</div>';
```

Which is then handled by the helper templates:
```
/**
 * Outputs the board stats for a standard board.
 *
 * @param array $board Current board information.
 */
function template_bi_board_stats($board)
{
	global $txt;

	echo '
		<p>
			', $txt['posts'], ': ', comma_format($board['posts']), '<br>', $txt['board_topics'], ': ', comma_format($board['topics']), '
		</p>';
}

/**
 * Outputs the board stats for a redirect.
 *
 * @param array $board Current board information.
 */
function template_bi_redirect_stats($board)
{
	global $txt;

	echo '
		<p>
			', $txt['redirects'], ': ', comma_format($board['posts']), '
		</p>';
}
```

**Comment by gevv** [comment]
Hi,

SMF 2.0.XX

![Untitled 1](https://user-images.githubusercontent.com/5096676/106767864-60a66f80-664c-11eb-8977-054a3b0bd9db.png)


SMF 2.1 RC3

![Veb-95fd-d25cf833fc9d](https://user-images.githubusercontent.com/5096676/106767883-656b2380-664c-11eb-87e0-571d7dfe9799.png)

**Comment by MissAllSunday** [comment]
Is this indeed a redirect board?

I created a redirect board and its type is indeed marked as "redirect" which triggers the correct template call: template_bi_redirect_stats

![Screenshot from 2021-02-03 09-15-16](https://user-images.githubusercontent.com/3420756/106767352-62e2dc80-6600-11eb-9e14-8565aeca6254.png)


Make sure you are using the latest github build.

Also, if you are using another theme other than the default one and it has its own boardIndex and MessageIndex files you need to make sure all the logic from the default theme files are ported to your theme's files.

**Comment by gevv** [comment]
sorry there was a mod conflict ..  uninstall the fa board icons mod the problem was solved 

thanks.
