### ISSUE TITLE
Add Member to Admin Group

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#6491]
#### Description
If you want to add a member to the admin group, this error message appears after logging in.

Token verification failed. Please go back and try again.

### Steps to reproduce
1.  Go to Admin Center =>    Manage Membergroups => Edit membergroups
 

### Environment (complete as necessary)
Version/Git revision: Last Commit RC3
Database Type: MySQL
Database Version: 5.7.33
PHP Version: 7.4.14!

### Additional information/references
https://github.com/SimpleMachines/SMF2.1/blob/a7c4e1bb7f6cb245b623cc67821e8691eaf873e1/Sources/Groups.php#L285-L293

I have changed the above code to 

```
        // Demand an admin password before adding new admins -- every time, no matter what.
        if ($context['group']['id'] == 1)
            validateSession('admin', true);

        checkSession();
        validateToken('mod-mgm');
```

Then it works. The error message no longer appears and the selected member is added to the admin group.

**Comment by live627** [comment]
Do you have admin security on?

**Comment by wintstar** [comment]
> Do you have admin security on?

Yes

BrickOzp has described it correctly  https://github.com/SimpleMachines/SMF2.1/pull/6508

> The problem is that verifyToken unsets the token after it is checked. And since it is not transferred to the password form it gets lost.
> verifySession will halt the execution when the password is required and the token will only be verified after the admin pass is correct.
