### ISSUE TITLE
by new install: Undefined index: requirePolicyAgreement

### ISSUE THREAD

**Issue by Pipke** [SimpleMachines/SMF#6499]
#### Description

Type of error
--
Undefined_vars
Error message
8: Undefined index: requirePolicyAgreement
File
C:/xampp/htdocs/smf3/Sources/Subs.php
Line
3923
URL of page causing the error
http://192.168.178.19/smf3/index.php?

### Steps to reproduce
1. install the newest version 
2. see admin log it should be there now

### Environment (complete as necessary)
- Version/Git revision: RC3  release-2.1 (#6496)
- Database Type: MariaDB
- Database Version: 10.4.14
- PHP Version:  Apache/2.4.46 (Win64) OpenSSL/1.1.1g PHP/7.2.34

### Additional information/references

3923: | if ($modSettings['requirePolicyAgreement'])

**Comment by Pipke** [comment]
possible fix:

if (isset($modSettings['requirePolicyAgreement']))

**Comment by DiegoAndresCortes** [comment]
I think #6449 will fix it?

**Comment by live627** [comment]
So will https://github.com/SimpleMachines/SMF2.1/pull/6492
