### ISSUE TITLE
?action=helpadmin;help=xmlnews_enable

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#651]
> Allows people to link to Recent news and similar data. It is also recommended that you limit the size of recent posts/news because, when rss data is displayed in some clients, like Trillian, it is expected to be truncated.

IMO we should remove the part about Trillian, it is not really needed.

**Comment by Arantor** [comment]
I think having an example of such a client that truncates is valid.

**Comment by illori** [comment]
i am not sure that trillian still truncates or has an RSS client, i dont see RSS as an option by default.

**Comment by illori** [comment]
according to the wikipedia article on trillian, RSS support is via a plugin, so it may not actually have support any longer. i cant find any recent posts on their forum newer then 2010 about RSS.

http://en.wikipedia.org/wiki/Trillian_(software)#Plugins

**Comment by Arantor** [comment]
OK, so Trillian is not the right example. We need to either find another example or consider whether we continue to need the feature anyway ;)

**Comment by illori** [comment]
i guess if i had time i could see if my rss reader truncates the feed, remind me if i dont reply back.

**Comment by Arantor** [comment]
How about we remove the 'like Trillian' bit for now? There are other reasons we need to consider keeping this handy (performance being the biggest)

**Comment by illori** [comment]
that is all i was asking for ;) from the start
