### ISSUE TITLE
Double string?

### ISSUE THREAD

**Issue by Dzonny** [SimpleMachines/SMF#6510]
Sorry if this is double-posted, but just noticed a double string while checking everything during Crowdin transfer.

https://github.com/SimpleMachines/SMF2.1/blob/6a158f4d4c6d3fb00d165d0537837ef698303b3a/Themes/default/languages/Install.english.php#L209

**Comment by live627** [comment]
oh and they differ too
https://github.com/SimpleMachines/SMF2.1/blob/b895dd79477e70a2281cc19d0252c310dd131b7d/Themes/default/languages/Install.english.php#L163
which one do we keep

**Comment by Dzonny** [comment]
I'd keep first one, but it's just a matter of preference.

**Comment by Oldiesmann** [comment]
I'd keep the one on line 209. That's the one that ultimately ends up getting used anyway.
