### ISSUE TITLE
Error! Incorrect date value: '0000-00-00' for column 'eventDate' at row 1

### ISSUE THREAD

**Issue by HakanKutluturk** [SimpleMachines/SMF#6518]
hello, when doing smf 2.1 rc3 update I get this error, 'Error!
Incorrect date value: '0000-00-00' for column 'eventDate' at row 1 '. What should I do?

**Comment by bhsmither** [comment]
When I get this error, I find that my database is in "strict" mode. When "strict", having zero dates is not permitted.

If the SMF programmers anticipate storing '0000-00-00' in a date/time column, SMF must assure that the database will allow this.

This could be accomplished by executing this statement for every instance of establishing a new connection to the database:
`SET SESSION sql_mode = ''`

**Comment by sbulen** [comment]
The upgrader already does this.

What version were you upgrading from?
