### ISSUE TITLE
Error hard coded Text

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#6521]
#### Description
SMF RC3 Current build

Found hard coded Error text. This can not translated

https://github.com/SimpleMachines/SMF2.1/blob/660ed67b50dbdfcaee9962447ce585df115604b2/Sources/Subs-Boards.php#L875
trigger_error('createBoard(): **One or more of the required options is not set**', E_USER_ERROR);

https://github.com/SimpleMachines/SMF2.1/blob/660ed67b50dbdfcaee9962447ce585df115604b2/Sources/Subs-Boards.php#L878
trigger_error('createBoard(): **Target board is not set**', E_USER_ERROR);

**Comment by wintstar** [comment]
The next found

https://github.com/SimpleMachines/SMF2.1/blob/660ed67b50dbdfcaee9962447ce585df115604b2/Sources/Subs-Boards.php#L528

trigger_error('modifyBoard(): **The move_to value** \'' . $boardOptions['move_to'] . '\' **is incorrect'**, E_USER_ERROR);

**Comment by wintstar** [comment]
The next found

https://github.com/SimpleMachines/SMF2.1/blob/660ed67b50dbdfcaee9962447ce585df115604b2/Sources/Subs-Categories.php#L146

trigger_error('createCategory(): **A category name is required**', E_USER_ERROR);

**Comment by wintstar** [comment]
https://github.com/SimpleMachines/SMF2.1/blob/660ed67b50dbdfcaee9962447ce585df115604b2/Sources/Subs-Categories.php#L233

trigger_error('deleteCategories(): **You cannot move the boards to a category that\'s being deleted**', E_USER_ERROR);

**Comment by wintstar** [comment]
There are more files in the Sources directory.

**Comment by Oldiesmann** [comment]
Working on it now. I'm not sure if we can or should do anything about the "Hacking attempt..." ones though
