### ISSUE TITLE
White page when adding new board

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#6529]
Hello,

White page when adding new board.  

page refreshes token error appears.

but the board has been added, no problem  (rc3 nightly  php 7.4

/index.php?action=admin;area=manageboards;sa=board2
/Sources/Subs-Boards.php (Satır 878)

8: Trying to access array offset on value of type null

=```
=>878: | $context['description_allowed_tags']);
-- | --
```

General

8: Trying to access array offset on value of type null
File
Sources/Subs-Boards.php
Line 878
The address of the page that caused the error
/index.php?action=admin;area=manageboards;sa=board2

    #0: smf_error_handler()
    Called from /Sources/Subs-Boards.php on line 878
    #1: modifyBoard()
    Called from /Sources/ManageBoards.php on line 746
    #2: EditBoard2()
    Called from /Sources/Subs.php on line 5349
    #3: call_helper()
    Called from /Sources/ManageBoards.php on line 71
    #4: ManageBoards()
    Called from /Sources/Admin.php on line 500
    #5: AdminMain()
    Called from //index.php on line 178





#### Description
--Description Here--

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:


### Additional information/references

**Comment by sbulen** [comment]
I'm not seeing this, on either windows or unix.  

More info needed:
 - Any special combo of parameters?  Or allowing everything to default?
 - Current GitHub or the RC3 downloaded from the simplemachines website?
 - Windows or unix?

And you didn't provide any of the basic info:

> 
> #### Description
> --Description Here--
> 
> ### Steps to reproduce
> 1. 
> 2. 
> 
> ### Environment (complete as necessary)
> - Version/Git revision:
> - Database Type:
> - Database Version:
> - PHP Version:
>

**Comment by MissAllSunday** [comment]
@gevv Are you able to replicate this issue on a clean SMF install with no modifications?

**Comment by Sesquipedalian** [comment]
Closing due to lack of response.

@gevv, if you are still encountering this issue, please reopen this issue report and provide more information.
