### ISSUE TITLE
Bug in "DbExtra-postgresql.php"

### ISSUE THREAD

**Issue by juedan** [SimpleMachines/SMF#6542]
#### Description
In the module **DbExtra-postgresql.php** in line 271 there is a big bug:
```
if (preg_match('~\(([^\)]+?)\)~i', $row['inddef'], $matches) == 0)
	continue;
$index_create .= $crlf . 'ALTER TABLE ' . $tableName . ' ADD PRIMARY KEY ("' . $matches[1] . '");';

```
If $matches[1] contains more than one key then the result produces an syntax error when the generated SQL query is executed.
Example:
`$matches[1]` contains "id_group, id_profile, permission"
Result:
`ALTER TABLE smf_board_permissions ADD PRIMARY KEY ("id_group, id_profile, permission");;`

**Solution:**
```
if (preg_match('~\(([^\)]+?)\)~i', $row['inddef'], $matches) == 0)
	continue;
$s = str_replace(' ', '', $matches[1]);
$s = str_replace(',', '","', $s);
$index_create .= $crlf . 'ALTER TABLE ' . $tableName . ' ADD PRIMARY KEY ("' . $s . '");';
```

Example:
`$matches[1]` contains "id_group, id_profile, permission"
Result:
`ALTER TABLE smf_board_permissions ADD PRIMARY KEY ("id_group","id_profile","permission");;`
And this SQL query works without any problems.

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1RC3
- Database Type: PostgreSQL
- Database Version: 12.2
- PHP Version: 7.4

### Additional information/references

**Comment by albertlast** [comment]
Please test the pr #6543

**Comment by juedan** [comment]
Thanks for the hint. you are right: those queries are better and all those queries in #6543 work perfect standalone. But I get an error: `Undefined type used in the database query. (boolean:pk)`

**Comment by albertlast** [comment]
should be fixed now by the last update

**Comment by juedan** [comment]
Now it works perfect. Thanks!

**Comment by albertlast** [comment]
please reopen the issue,
the issue get closed automaticaly when the pr get merged.
