### ISSUE TITLE
script.js should get minified

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#6547]
#### Description
While checking some network traffic stuff,
i notice that we transfer the complet scripts.js file without minified it.
When i send this throw a minifier the file get from ~60kb to 40kb,
so should this be done somewhere, maybe in build tools?

The values are without gzip.

In best case we also generate some map files for minified version so that development is possible on this files,
when wanted.
https://stackoverflow.com/questions/21719562/how-to-use-javascript-source-maps-map-files

**Comment by Oldiesmann** [comment]
Doesn't it get minified with the rest of the JS stuff when you enable that option in the admin center?

**Comment by jdarwood007** [comment]
Only if you have minified enabled in the settings and your themes scripts/css folder is writable by the process running php.

**Comment by sbulen** [comment]
I have confirmed script.js is getting successfully minimized in 2.1.  Not sure there's an error here.
