### ISSUE TITLE
Do a file integraty check?

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#6561]
#### Description
Some time in sm i read something like,
"some files are old" "my setup/upgres goes wrong"
in some cases the issue is,
that not all file of install/upgrade packages find ther way in folder.

idea would be to add somekind of integraty json to the packages,
so that installer and upgrade could check if the files are orginal and
when not provide a warning (which the admin can ignore).

is this something which would be usefull?

possible code to generate this kind of json could be this:
```
$hash_method = 'sha256';
$files = glob('./Sources/*.php');
$hashes = array();
foreach ($files as $key => $value) {
    $hashes[$value] = hash_file($hash_method,$value, false);
}
$manifest = ['hash_method' => $hash_method, 'files' => $hashes];
echo json_encode($manifest);
```

the install/upgrade file would try to finde the json file (if not find -> no check maybe a warning that no file was found?),
and provide a warning for missing/mismatch files.

We could also provide the json file directly from sm.org instead of placing this into the packages.

**Comment by jdarwood007** [comment]
This won't work because of modifications that modify files.   Until we have enough mods going hooks only, this won't work and will provide too many false errors.

**Comment by albertlast** [comment]
from what i understand,
in case of a install and upgrade the files should be original so here would be able to check if this is true or not.
in a case of patch process we still could check the hashes of backup + patch without modes,
so also here the hash check could be help full.
And also in repair board php this information could be used,
to check which files got changed and to "highlight" possible issues sources.

**Comment by sbulen** [comment]
https://github.com/SimpleMachines/SMF2.1/pull/5960

**Comment by albertlast** [comment]
question is still if we want to add a check for the install and upgrade packages.

**Comment by Sesquipedalian** [comment]
I don't think such a check would be viable at this point.
