### ISSUE TITLE
GitHub Actions on forks

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6570]
#### Description
Is there a way to disable GitHub actions on forks?  

The weekly scheduled GitHub action for CrowdIn ran on my fork.  It failed, since it doesn't have the credentials for CrowdIn.  But I suspect this will happen for all forks at some point...

I did some searches, & GitHub's response is to disable unwanted actions on the forks.  There has got to be a better way than that.

Even the PHP workflows are running - for every single PR (submitted by me or not) - on my local fork.  

I.e., these aren't all my PRs, but this is my fork of SMF:
![image](https://user-images.githubusercontent.com/23568484/111077900-241e2d00-84b0-11eb-9578-c39f4d855d7f.png)

**Comment by jdarwood007** [comment]
We could limit the branches the actions run on.  Then only the main branches (master, development, release-2.1)  would take action.  If you wanted to get around it, you would just not sync those branches to your github.

**Comment by sbulen** [comment]
I'm not worried about *my* GitHub.  I'm more worried about the other 200+ active forks out there.

Just feels like a big, wasteful, dangerous gap in thinking in the GitHub action rollout...

No forks have the proper credentials for CrowdIn...  We are safe...  -ish...  It just feels insane that they are all *trying* to do the updates...

**Comment by sbulen** [comment]
From CrowdIn support:
> Hi @sbulen, you can add to your workflow check like this if: env.CROWDIN_PERSONAL_TOKEN != null after -name of step, and if not exist secret it will be skipped.

https://github.com/crowdin/github-action/issues/62

**Comment by sbulen** [comment]
Yes, this works great, thank you!

I would suggest putting that on any examples...

**Comment by sbulen** [comment]
Closed prematurely...  That comment was meant for the CrowdIn issue for the CrowdIn folks...

**Comment by jdarwood007** [comment]
Ok, well the PHP and other checks don't seem to be harmful to run on other forks.  I think its fine to close this up?

**Comment by sbulen** [comment]
The one thought I had about the PMP wf is to withhold execution on the release-2.1 branch.  All other branches are in-progress or just-submitted PRs - the ones we want tested.  Execution on the release-2.1 branch is either during or post merge, & as such, is unnecessary.  

If you look at my screenshot above, all the release-2.1 ones are post-merge, & executing on my local repo when I sync it up.  Too late to be helpful, & wasteful.  

Make sense?

(I have heard that the GH action servers have been getting backed up recently... I'm not sure they thought thru forks... And none of their examples account for this...)

**Comment by m4z** [comment]
We could use the `if` to [run the actions only on our repo](https://github.community/t/stop-github-actions-running-on-a-fork/17965/2).

**Comment by sbulen** [comment]
I'm not sure there's a lot of warmth for the remaining bits of this, so closing it out!
