### ISSUE TITLE
Menu shines through login box

### ISSUE THREAD

**Issue by BrickOzp** [SimpleMachines/SMF#6573]
#### Description
The main menu shines through the dimming and the login box.

### Steps to reproduce
1. Logout
2. Click Login
3. Notice the main menu shines through the dimming, and the login box.
![menu shines through](https://user-images.githubusercontent.com/2890167/111143620-4c785b00-8586-11eb-82fb-3af94a4971f4.png)

### Environment (complete as necessary)
- Version/Git revision: 89c3980d3
- Database Type: MySql
- Database Version:
- PHP Version: 5.6

### Additional information/references
Related to https://github.com/SimpleMachines/SMF2.1/pull/6502/commits/e81ea07a862ec3e7f445db537e901b630c8f0e1a and 
https://github.com/SimpleMachines/SMF2.1/commit/52334481ed17645f07e72d875e928ab1f3d8d61a

Reverting those fixes the problem.

**Comment by BrickOzp** [comment]
@DiegoAndresCortes and input?

**Comment by BrickOzp** [comment]
This will also  introduce problems when interacting with the login box. E.g. the box will close if clicking in the password field.

**Comment by DiegoAndresCortes** [comment]
A better fix for this would be reverting it and also removing z-index from this in jquery.sceditor.css
`.sceditor-container,
.sceditor-container div,
div.sceditor-dropdown,
div.sceditor-dropdown div {
	padding: 0;
	margin: 0;
	z-index: 5;
}`

Do you think this would be a better change, couldn't see anything being broken by this on my initial test.
Could also just lower the z-index to **4** in that portion of code, that seems to be the proper value.
Seems like all we needed to do was care for the previous value already set on .popup_container which is **5**
