### ISSUE TITLE
Ajax login will fail for banned users on non-english

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6587]
#### Description
In index.template.php we have this:
```
				<li>', sprintf($txt[$context['can_register'] ? 'welcome_guest_register' : 'welcome_guest'], $context['forum_name_html_safe'], $scripturl . '?action=login', 'return reqOverlayDiv(this.href, ' . JavaScriptEscape($txt['login']) . ');', $scripturl . '?action=signup'), '</li>
```

The second parameter of reqOverlayDiv is $txt['login']
This is set in the index.language.php
```
$txt['login'] = 'Login';
```

In script.js we define the parameters:
```
// Open a overlay div
function reqOverlayDiv(desktopURL, sHeader, sIcon)
```

And finally when we receive an error 500, we throw an error that they are banned if it's from the login page.
```
		statusCode: {
			500: function() {
				if (sHeader == 'Login')
					oPopup_body.html(banned_text);
				else
					oPopup_body.html('500 Internal Server Error');
			}
		}
```

But we are depending on sHeader which is a text string.  So in non english forums, this will never trigger the banned message, but only the internal error message.

### Steps to reproduce
1. Change $txt['login'] to anything else.
2. Ban the member
3. Try to login

### Environment (complete as necessary)
- Version/Git revision: latest at time of report
- Database Type: n/a
- Database Version: n/a
- PHP Version: n/a

### Additional information/references

Tagging this for final, it doesn't need to resolve for RC4 but could.

**Comment by live627** [comment]
imo this should be handled by the server and should throw a 403, not a 500.

**Comment by jdarwood007** [comment]
Agreed on that as well.
