### ISSUE TITLE
$txt['smf_stats_14'] duplicates $txt['most_online']

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#6599]
#### Description
Originally reported here: https://translate.simplemachines.org/translate/simple-machines-21-beta/33/en-es?filter=basic&value=0#5646

### Steps to reproduce
1. https://github.com/SimpleMachines/SMF2.1/blob/a7c4e1bb7f6cb245b623cc67821e8691eaf873e1/Themes/default/languages/Stats.english.php#L21
2. https://github.com/SimpleMachines/SMF2.1/blob/a7c4e1bb7f6cb245b623cc67821e8691eaf873e1/Themes/default/languages/Stats.english.php#L6

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by Oldiesmann** [comment]
That's the only place $txt['stats_14'] appears so it can be safely removed.
