### ISSUE TITLE
Rephrase "board directory"; rename "$boarddir"

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#6615]
"`$boarddir`" seems to be a historic misnomer for the forum's main (install) directory. Since we also have the concept of boards and sub-boards (essentially "(sub)sections" of the forum), and most translators don't know about code internals, this makes it awkward to translate strings that mention the "board directory":
https://github.com/SimpleMachines/SMF2.1/blob/8e38073dcc4586b49e0f218c57bf1855761c97d7/Themes/default/languages/Install.english.php#L327

So I not only suggest the following change:
```
-It looks as if your board directory settings <em>might</em> be incorrect. Your board directory
+It looks as if your forum directory settings <em>might</em> be incorrect. Your forum directory
```

...but also to refactor "`$boarddir`" into something like "`$installdir`".

**Comment by DiegoAndresCortes** [comment]
I think it's too late to change this? Mods are using this too.

**Comment by Sesquipedalian** [comment]
We can use "forum" instead of "board" it in the strings, but the variable names can't change.
