### ISSUE TITLE
Improve quoting?

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#6617]
(This is more of a request for comments or a feature request than a bug report. Please bear with me.)

---

Context: [Different languages use different quoting.](https://en.wikipedia.org/wiki/Quotation_mark#Summary_table)

---

The English "translation" currently (somewhat inconsistently) uses `"` (`&quot;`), and sometimes `'` (`\'`) or `"` (`\"`), examples:
https://github.com/SimpleMachines/SMF2.1/blob/41509ff31acb755844239e9aeecbac727a022229/Themes/default/languages/Admin.english.php#L224
https://github.com/SimpleMachines/SMF2.1/blob/a7c4e1bb7f6cb245b623cc67821e8691eaf873e1/Themes/default/languages/ManagePermissions.english.php#L78
https://github.com/SimpleMachines/SMF2.1/blob/41509ff31acb755844239e9aeecbac727a022229/Themes/default/languages/Admin.english.php#L656

This (latter string with `&quot;`) renders as:
> Results for search: &quot;xxx&quot;

Question 1: Should English consistently use `&quot;`?

---

We _could_ use the "66-99" style (`&ldquo;` and `&rdquo;`) for english, which would be a bit cleaner entity-wise:
```
$txt['admin_search_results_desc'] = 'Results for search: &ldquo;%1$s&rdquo;';
```

This renders as:
> Results for search: &ldquo;xxx&rdquo;

The rendering is only marginally different with the sans-serif fonts used by GitHub and SMF 2.1, but more visible in serif fonts:
![2021-03-27_smf-quoting](https://user-images.githubusercontent.com/387675/112731790-a5f26980-8f38-11eb-80a1-104f22a59934.png)

All things considered, I'm not sure this almost invisible change is worth the effort (but also see Question 3 below).

Question 2: Should English consistently use `&ldquo;` and `&rdquo;`?

---

If I put on my translator hat, [German should use `&bdquo;` and `&ldquo;`](https://en.wikipedia.org/wiki/Quotation_mark#German), which is visibly different even with sans-serif fonts:
```
$txt['admin_search_results_desc'] = 'Results for search: &bdquo;%1$s&ldquo;';
```
This renders as:
> Results for search: &bdquo;xxx&ldquo;

---

Question 3: Since most languages seem to use different opening and closing quotes (see first link above), would it be feasible to define the opening and closing quote characters in a language string (maybe call them `$txt['lq']` and `$txt['rq']`<sup>1</sup>) and then use that everywhere, or use some kind of `quote` "macro"? Or is it up to the translators to manually and redundantly replace them everywhere?

[1]:  Which may be confusing to RTL language users, but at least is consistent with the HTML entity naming.

**Comment by BrickOzp** [comment]
Since all languages are utf-8 now. Are there any point in using html entities instead of the real characters in the strings?

**Comment by m4z** [comment]
Not really, I just didn't think the extra mile. 😉

**Comment by m4z** [comment]
PS: [Typing the (German) quotes actually isn't trivial, especially on Windows.](https://german.meta.stackexchange.com/questions/509/how-to-type-the-actual-german-quotation-marks) For some reason I don't care about, the alt-codes don't correlate with the unicode table:
* https://unicode-table.com/en/201C/
* https://unicode-table.com/en/201E/

**Comment by sbulen** [comment]
I would exercise caution...  And only make a change if you can document the before & after & confirm no adverse impact.

I started aligning escaping in one of the language files once, but stopped, because there really are variants for a variety of reasons, including php vs javascript vs html/emails vs some pass thru our BBC/entity routines & some don't, etc...  Only by testing can you confirm you aren't breaking something...  

I ended up making few (zero?) changes because it turned out the ones I thought were suspicious were that way for a reason.  

That doesn't mean they're all perfect; it just means _TEST..._

**Comment by albertlast** [comment]
> 
> 
> Since all languages are utf-8 now. Are there any point in using html entities instead of the real characters in the strings?

when you use mysql as database,
then some utf chracters(4bytes) get transform into html entities on db side.

**Comment by BrickOzp** [comment]
@albertlast Are there any use case where language strings are stored in the database? And if so, does it matter if they are html entitites to begin with?

**Comment by albertlast** [comment]
OopS i didn't  notice that we talk about language files, here is no connection to db stuff. So ignore my comment

**Comment by Sesquipedalian** [comment]
~The best solution is probably to use `<q></q>` elements in all languages. Then the browser will automatically show the correct punctuation marks for the language.~

~Of course, making that change might be more work than it is worth...~

On second thought, never mind. Using `<q></q>` that way wouldn't be semantically correct.

**Comment by DiegoAndresCortes** [comment]
> I would exercise caution... And only make a change if you can document the before & after & confirm no adverse impact.
> 
> I started aligning escaping in one of the language files once, but stopped, because there really are variants for a variety of reasons, including php vs javascript vs html/emails vs some pass thru our BBC/entity routines & some don't, etc... Only by testing can you confirm you aren't breaking something...
> 
> I ended up making few (zero?) changes because it turned out the ones I thought were suspicious were that way for a reason.
> 
> That doesn't mean they're all perfect; it just means _TEST..._

I think based on this comment, this could be tagged 'for the future', we don't want to break anything at this point...

**Comment by sbulen** [comment]
I would actually suggest closing this.  It was just for discussion, and there is no specific issue mentioned.  It's not actionable in its current state.

A well-doc'd, well-tested PR is always welcome.

**Comment by m4z** [comment]
I agree with closing this.

For the German translations, I chose the unicode route and I'm still working on easier test environment creation to actually test it.

Not sure if it makes sense for myself to research the finer points of the English rules and write a PR for that. Maybe someday.
