### ISSUE TITLE
"attachment directory" vs. "attachments directory"

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#6624]
Crowdin counts:
* 20x [singular](https://crowdin.com/translate/simple-machines-21-beta/all/en-de?filter=basic&value=0#q=%22attachment%20directory%22) (10 duplicate)
* 12x [plural](https://crowdin.com/translate/simple-machines-21-beta/all/en-de?filter=basic&value=0#q=%22attachments%20directory%22) (6 duplicate)

Because of #6623, I'd lean towards using plural everywhere.

Edit: 50% of each are duplicates.

**Comment by jdarwood007** [comment]
As we have built in support for multiple attachment directories, plural is the correct way with our current language strings.

**Comment by Sesquipedalian** [comment]
Using plural everywhere would be more technically correct, but "attachments directories" feels unnatural in English (as evidenced even in @jdarwood007's comment above).

I would say that translators can and should feel free to normalize these strings to the plural form in their translations, but for English itself I wouldn't call this an issue.
