### ISSUE TITLE
Date picker does not work for non english languages

### ISSUE THREAD

**Issue by BrickOzp** [SimpleMachines/SMF#6631]
#### Description
When selecting dates with the date picker, and the forum uses a non english language, the selected date is not used.

### Steps to reproduce
1. Install and use a languages that is not english
2. Use a time format with strings for months. e.g DD Month YYYY, (If using all digits time format there is no issue)
3. Open the calendar and select a date.
4. The date is reset to the current date.
5. Create a new event
6. Invalid date

### Environment (complete as necessary)
- Version/Git revision: 11d666fe8
- Database Type: mysql
- Database Version:
- PHP Version: 5.6

### Additional information/references

**Comment by BrickOzp** [comment]
The date picker returns the date in localized format.
On the server side we use date_parse to parse the date, but it does only understand english months.

I see two possible solutions:
1. Pass the date in iso format as well in a hidden field.
2. str_replace months into english before passing it to parse_date.

What do you think?

**Comment by Sesquipedalian** [comment]
In theory I like the first option better, but it may require editing jquery.timepicker.min.js and/or jquery.datepair.min.js. So the second option may be simpler in the end.
