### ISSUE TITLE
[Feature Request] Show username only when display name differs

### ISSUE THREAD

**Issue by toby63** [SimpleMachines/SMF#6633]
Recently there was a discussion in a roleplay forum about doubled usernames, when the display name and the username is shown (see screenshot below).
The admins explained that this is useful to allow for clear identification when the users change their display names.
Thus the idea came up, that the username could only be shown when the display name differs from it.

Screenshot of the situation in the forum:
![Screenshot](https://user-images.githubusercontent.com/61703250/112867522-51c3c280-90bb-11eb-933a-50aa1d074502.png)

Forum: https://www.tanelorn.net
Forum Version: 2.0.15 (but I guess it is this way in other versions too)

**Comment by m4z** [comment]
This looks like a custom theme, so I think only the theme creator can handle that.
(~~Also, that forum uses 2.0.15, not 2.1.~~ Nevermind, you mentioned that.)

**Comment by toby63** [comment]
> This looks like a custom theme, so I think only the theme creator can handle that.

I think my request has not much to do with the theme.
It's the functionality of the username tag.

**Comment by DiegoAndresCortes** [comment]
While a theme could include it, SMF doesn't do it by default, only the admins see the username in their profiles.
Because of that, this is not happening. Should be addressed in your custom theme with caution as the username is sensitive information.
