### ISSUE TITLE
BBC titles in $txt['admin_news_desc']

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#6645]
https://github.com/SimpleMachines/SMF2.1/blob/6ecd719bede90acb68017c0dc6e302963a433432/Themes/default/languages/Admin.english.php#L54

The humour is pretty much impossible to translate, so i suggest to keep it simple instead:
```
-title="Are you bold?"
+title="bold"                       (or boldface)
-title="I tall icks!!"
+title="italics"
-title="Brackets are great, no?"    (*)
+title="underscore"                 (or underline)
```

(*): I don't even understand this one; did the author run out of ideas even in English?

**Comment by Oldiesmann** [comment]
The "brackets" thing is an inside joke. SMF owes much of its existence to a guy named "[Unknown]", aka "Unknown W. Brackets". I believe he was the one who created this easter egg.

**Comment by m4z** [comment]
Ok, is it worth keeping it this way, or could we do something like:
```
-BBC tags, such as
+Because (brackets are great|everyone loves brackets), BBC tags, such as
```
...plus my suggestions from above?

**Comment by DiegoAndresCortes** [comment]
Was this ever an issue on SMF 2.x for translations?

**Comment by BitFros7y** [comment]
Why not keep it in English like that, and give translators simplified version to translate?

**Comment by sbulen** [comment]
> Why not keep it in English like that, and give translators simplified version to translate?

The English version *is* what is provided to the translators to translate.  There isn't a separate English translation.

**Comment by sbulen** [comment]
I like m4z's simplifications, including the one that keeps the brackets inside reference.

(I once submitted a PR to remove a fairly odd easter egg, and was scolded & received an ominous warning....)

**Comment by wintstar** [comment]
@m4z, you should not use only google translator. Use deepl.com. And think now and then around the corner. And very important! Take a look at the function for the language string in the source code. Then you understand it better to translate.

**Comment by Sesquipedalian** [comment]
> I like m4z's simplifications, including the one that keeps the brackets inside reference.

Agreed.
