### ISSUE TITLE
Inconsistent use of "display name" vs. "displayed name"

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#6646]
There seems to be a somewhat equal amount of both, in both variable names and strings:
* [display](https://github.com/search?q=%22display+name%22+repo%3ASimpleMachines%2FSMF2.1+path%3AThemes%2Fdefault%2Flanguages&type=Code&ref=advsearch&l=&l=)
* [displayed](https://github.com/search?q=%22displayed+name%22+repo%3ASimpleMachines%2FSMF2.1+path%3AThemes%2Fdefault%2Flanguages&type=Code)

**Comment by DiegoAndresCortes** [comment]
I think only _$txt['display_name']_ could be merged into one and added to index.english.php and that's if it's used in multiple places, if it's only in 2 pages max I don't know if it's a necessary change.

But other than that I don't think the strings are that similar.

Edit: Regarding the use of displayed in some of the permissions could be needed to provide context for translations? E.g. Displayed as in changing the currently **displayed name** vs changing **display name**
That's just my opinion but I'm not against changing it.

**Comment by DiegoAndresCortes** [comment]
This could be just changing the strings from displayed to display?
There's a lot of places where variables are consistently using displayed, so not sure if it's something that should be changed at this point.

**Comment by m4z** [comment]
Sorry for the late reply, I was busy with moving house for a looong time.


> I think only _$txt['display_name']_ could be merged into one and added to index.english.php and that's if it's used in multiple places, if it's only in 2 pages max I don't know if it's a necessary change.

Actually I didn't even think about merging variables; I was just looking at this with my translator hat on: it seems weird that two spellings are used when (I think) they're referring to the same thing.


> This could be just changing the strings from displayed to display? There's a lot of places where variables are consistently using displayed, so not sure if it's something that should be changed at this point.

I'm not sure what/who you're asking. If you're asking if we should change every "displayed" to "display" then yes, that was basically what I was going for.

**Comment by sbulen** [comment]
I don't see a problem with this.  Sometimes the field is referenced, sometimes a description of it...  

I don't think any action is necessary here...  Unless it's causing mass confusion among translators?

(Yes, we English-ish speaking Americans can be a little casual with our word choice...)

**Comment by DiegoAndresCortes** [comment]
I forgot to update on this...
I discussed this issue with Irisado on Discord and we agreed on it not being an issue. It surely is an inconsistency, but not an issue really.
We decided that this could be something to fix for 3.0 or other future version.

**Comment by sbulen** [comment]
OK, I'll close this out.

**Comment by m4z** [comment]
My only concern (about the English part) is that others will wonder (like myself) if the displayed name is always the display name, or if combinations of settings exist where something different happens. (Everything else are follow-up German translation problems and considerations.)
