### ISSUE TITLE
Typo in Install.english.php

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#6652]
Testing the RC4 upgrade, I found a minor typo in Install.english.php:

`$txt['upgrade_done'] = 'Upgrade complete. Now you are ready to use <a href="$1%s/index.php">your installation of SMF</a>. Hope you like it!';`

Should be `%1$s` not `$1%s`.

**Comment by m4z** [comment]
Nice, we all overlooked that in #6627.

**Comment by Oldiesmann** [comment]
I only noticed it when I clicked the "Your Installation" link at the end of the upgrade and got a 404 page instead of my forum
