### ISSUE TITLE
gitattribute

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#666]
#641 forces ttf files to be text...I don't think they are.

**Comment by Arantor** [comment]
That would certainly explain why we've been seeing issues lately with people trying to commit and referencing the ttf files. (Personally, I already set my local config to autocrlf = false so that wasn't an issue anyway for me)

**Comment by jdarwood007** [comment]
Problem was is we are getting windows line endings and linux line endings.  SMF has always enforced linux line endings in its code.

ttf files I assume should be binary then?

**Comment by Arantor** [comment]
Yup, they're binary files.

**Comment by jdarwood007** [comment]
Can you modify the repo here directly to do that?  I wanted to make a commit but when I try to it is pulling in the Subs-Charset.php file as having changes, checking that file out again or doing a reset --hard is not fixing it, so yea..

**Comment by jdarwood007** [comment]
I pushed a fix for this on accident in #668 If we merge that this will resolve as well.

**Comment by illori** [comment]
668 was merged, so we can close this?

**Comment by Arantor** [comment]
Yup.
