### ISSUE TITLE
Admin Template - code is not well written, is somewhat offset

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#6660]
#### Description
--Description Here--
Admin Template
The code is not well written, is somewhat offset
```
 $context['config_vars'] = array_filter($context['config_vars'], function ($v) use ($context) 
 	{
```

https://github.com/SimpleMachines/SMF2.1/blob/40e0e3910096b4d72fa7923a0187e5855f6d6a05/Themes/default/Admin.template.php#L759-L778

**Comment by sbulen** [comment]
Is there a bug here?

**Comment by wintstar** [comment]
Is not a bug, but not nice to look at this shifted source code. Not fine to see.

**Comment by jdarwood007** [comment]
Sounds like @wintstar is saying it is an indentation issue.

**Comment by sbulen** [comment]
Understood.  But this isn't a control structure,  it's an inline function,  a bit of a grey area in our coding standards.  There are plenty of similar examples throughout the code.  I'd rather not go around changing them.

**Comment by jdarwood007** [comment]
Thats fine.  I marked it housekeeping because its one of those cleanups we can do, but isn't necessary to make any release.  Maybe it will get fixed during some other code cleanup in being done in that area.

**Comment by jdarwood007** [comment]
Although this isn't template logic really, it should be in the source files instead.  But I wouldn't hold it up either for a release due to the low chances many templates will modify these files.

**Comment by wintstar** [comment]
> Sounds like @wintstar is saying it is an indentation issue.

Yes.
