### ISSUE TITLE
Error when upgrading from 2.0.15 to 2.1 RC4

### ISSUE THREAD

**Issue by BrickOzp** [SimpleMachines/SMF#6663]
#### Description
PHP error when upgrading from 2.0.15 to 2.1 RC4

### Steps to reproduce
1. Have a 2.0.15 forum
2. Copy 2.1 RC4 files to server
3. Enter site (index.php)
4. Notice: Undefined index: htmlspecialchars in /Sources/ScheduledTasks.php on line 1022 Fatal error: Function name must be a string in /Sources/ScheduledTasks.php on line 1022

### Environment (complete as necessary)
- Version/Git revision: Beta test 2.1 RC4
- Database Type: mysql
- Database Version:
- PHP Version: 5.6

### Additional information/references

**Comment by BrickOzp** [comment]
The error originates from Load.php row 72. $modSettings['attachmentUploadDir'] contains a string with the path to the attachments folder. During json decoding an error occurs (because it is not json), and the error should be logged. loadLanguage('Errors') is called. $settings['default_theme_dir'] is empty so loadEssentialThemeData is called.
htmlspecialchars has not yet been created so the error occurs.

**Comment by BrickOzp** [comment]
If I assign $attachmentUploadDir to the attachments path without json_decoding, the upgrader starts.

**Comment by sbulen** [comment]
Did you run the upgrader?

This is a common error reported if you skip one of the steps when upgrading from GH - either forget to run the upgrader, or don't copy the upgrade*.* files from /other, etc.  (Running 2.1 code on a 2.0 DB.)

I cannot reproduce.

**Comment by BrickOzp** [comment]
No, this was before running the upgrader. Just after copy of rc4 files.

**Comment by sbulen** [comment]
This would be expected then - the DB is still in 2.0 format.

The 2.0 DB and the 2.1 code are incompatible.  You need to run the upgrader to bring them in sync.

That would explain your avatars/smiley issue as well.

**Comment by sbulen** [comment]
The "fix" is to run the upgrader.  FYI, it not only changes DB structures, there are many **_data_** fixes/changes/restructures in there as well.  

You can scan all the changes from 2.0 to 2.1 here:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade_2-1_mysql.sql

**Comment by BrickOzp** [comment]
Just to clarify; I didn't expect the forum to work. Just to be redirected to the upgrader, as will be done right after this code.
This error will also occur in 2.1 if the attachmentUploadDir is corrupted (not valid json).
To not log this error will solve it.
Changing smf_json_decode($modSettings['attachmentUploadDir'], true);
to smf_json_decode($modSettings['attachmentUploadDir'], true, false);
