### ISSUE TITLE
Erroneous 'No alerts or emails' messages after upgrade

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6665]
#### Description
Reported by @BrickOzp 

After an upgrade, the lists of notifications erroneously indicate 'No alerts or emails'.

Issue exists for both watched topics & boards.  

**_One example:_**
![image](https://user-images.githubusercontent.com/23568484/113760602-41b76e80-96cb-11eb-9c0d-362458b80cae.png)

**_But if you open the topic it correctly states to 'RECEIVE ALERTS':_**
![image](https://user-images.githubusercontent.com/23568484/113760717-6a3f6880-96cb-11eb-9f15-e629409d3123.png)

### Steps to reproduce
1. Have some watched topics/boards in 2.0
2. Upgrade to 2.1

### Environment (complete as necessary)
- Version/Git revision: current GH
- Database Type: Mysql
- Database Version: 5.7
- PHP Version: 7.4

### Additional information/references

**Comment by sbulen** [comment]
Plus, the red is ugly.

**Comment by BrickOzp** [comment]
topic_notify_<topic_id> is missing from user_alerts_prefs table

**Comment by BrickOzp** [comment]
In the Display.php there is a fallback to user default topic_notify setting and then to system default topic_notify setting.
In Profile-Modify.php there is only fallback to the user default topic_notify setting. That is why they differ.
