### ISSUE TITLE
Youtube short codes support on editor

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#6672]
Currently we support youtube short codes:

[youtube]dQw4w9WgXcQ[/youtube]

But when clicking on the editor's youtube icon, it asks for full URL and rejects short codes (nothing happens). For shortcodes you gotta manually type [youtube][/youtube] in order for it to work.

**Comment by asmith20002** [comment]
I have fixed this. Wanted to submit a pull request but the target file is minimized (one line) and the change won't be easily visible. Should I submit it anyway?

file: /Themes/default/scripts/jquery.sceditor.bbcode.min.js

find string: 
`var t=(n=Re(a,"#link")[0].value).match(/(?:v=|v\/|embed\/|youtu.be\/)(.{11})/)`

replace with:
`var t=(n=Re(a,"#link")[0].value).match(/(?:v=|v\/|embed\/|youtu.be\/)?([a-zA-Z0-9_-]{11})/)`

**Comment by BrickOzp** [comment]
Nice! The right way would be to send a PR to the SCEditor https://github.com/samclarke/SCEditor
Then it will be included in the next release after it has been merged and will be imported to SMF.
Otherwise this needs to be patched after every update of the SCEditor in SMF.

**Comment by asmith20002** [comment]
Alright. [Done](https://github.com/samclarke/SCEditor/pull/837).
