### ISSUE TITLE
s/Url/URL/g

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#6673]
The only occurrences I could find (but I searched via Crowdin and Github, so there might be more):
https://github.com/SimpleMachines/SMF2.1/blob/6ecd719bede90acb68017c0dc6e302963a433432/Themes/default/languages/Help.english.php#L579-L588

**Comment by sbulen** [comment]
What's the issue?

**Comment by live627** [comment]
see the title—`Url` vs `URL`

**Comment by m4z** [comment]
AFAIK, "Url" isn't an English word, and at least [wiktionary](https://en.wiktionary.org/wiki/Url) agrees:
> Did you mean [URL](https://en.wiktionary.org/wiki/URL)?
