### ISSUE TITLE
Phrasing (and name) of $helptxt['whytwoip']

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#6682]
https://github.com/SimpleMachines/SMF2.1/blob/6ecd719bede90acb68017c0dc6e302963a433432/Themes/default/languages/Help.english.php#L526

Can "more than one" address(es) be found, or exactly "two"? If the former, don't use "both". If the latter, rephrase.

(Without looking at the code, I assume DNS is used to lookup the (single) name from the IP, and then the (possibly multiple) IP(s) from the name, but I don't know if additional addresses from the latter are added to or dropped from the result.)

**Comment by DiegoAndresCortes** [comment]
I think it's fine because it only compares two at a time, so "both" would be correct, right?

**Comment by Sesquipedalian** [comment]
"In this case SMF logs the two most recent addresses..."
