### ISSUE TITLE
Old imageshack links cause total thread break

### ISSUE THREAD

**Issue by NFGman** [SimpleMachines/SMF#6684]
#### Description
In some old threads, c.2008, some links to imageshack images exist in posts, and those links no longer resolve.  SMF is trying to do something with those links and failing, resulting in an out of memory error (at 256 or even 512MB allowed).  Because the thread display died before the offending post could be shown, I manually edited the SQL and removed the [url=] links and the problem went away.  But during my experimenting with exactly what caused the breaks, I also experienced some timeout errors (more than 30s) when I included the links but not the last 1/3 or so of the post content.  So for sure these [URL] links are causing several kinds of havoc.

Update: Simply pasting the imageshack links into a post doesn't seem to break anything.  So it's a problem, I guess, in combination with something else in the post.  Here's the entire post as it was, copied from the database:

https://pastebin.com/cC6A55Bd

This post reliably kills threads.  The post is not shown, nor is anything past that - including quick reply, footer, etc.  If user-facing PHP errors are allowed, an out of memory error is shown.

### Steps to reproduce
1. Paste the content of the pastebin link into the body of  a post in smf_messages.
2. That's it.

### Environment (complete as necessary)
- Version/Git revision: 2.1 RF3, dated Dec 11 2020, (so a dev version from here)
- Database Type: mySQL
- Database Version: 5.0.12
- PHP Version: 7.4

### Additional information/references
By removing the [url=] and [/url] the problem goes away.

**Comment by live627** [comment]
Might be related to the image proxy

**Comment by NFGman** [comment]
I should have included the actual error text, which points to the specific problem.  My apologies.

`PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 69061872 bytes) in /var/www/forum/Sources/Subs.php on line 2996`

**Comment by BrickOzp** [comment]
I have copied your post to my test forum, but I have no problem viewing it

**Comment by BrickOzp** [comment]
Wierd. No after some time I see the problem

**Comment by BrickOzp** [comment]
The problem has nothing to do with the images.
It is the trailing = in http://www.google.co.uk/search?hl=en&q=BA6596F&btnG=Google+Search&meta= that causes a clash with the solution for https://github.com/SimpleMachines/SMF2.1/issues/6336
