### ISSUE TITLE
Error when editing a post in an announced topic

### ISSUE THREAD

**Issue by BrickOzp** [SimpleMachines/SMF#6705]
#### Description
When editing a post, in a topic that has been announced, the error "Array" is displayed and an item is added to the error log.

### Steps to reproduce
1. Announce a topic
2. Edit a post in the topic
3. "The message has the following error or errors that must be corrected before continuing:
    Array" is visible above the editor.
    8: Array to string conversion in Themes/default/Post.template.php on line 107

### Environment (complete as necessary)
- Version/Git revision: 3a6b2257d
- Database Type: MySql
- Database Version:
- PHP Version: 5.6

### Additional information/references

**Comment by BrickOzp** [comment]
Post.template.php implode $context['post_error']) to show all errors.
Most errors creates an item like:  ["no_message"]=> string(32) "The message body was left empty."
But for announced topics a sub array is added: ["messages"]=> array(1) { [0]=> string(55) "Please note that this topic has already been announced." }

Questions: "Please note that this topic has already been announced" does not sound like an error that can be corrected. Should it be in the same array?
Why is this added like a sub array?
From commit msg in 2933d1ff8c919133e093bea046b15e61f1b72b63 it sounds like this warning should only be shown if editing the first post. It is shown when editing all posts of the topic.

**Comment by Oldiesmann** [comment]
It's not really an error that can be corrected - it's simply meant to be a warning since some people may have already seen the original message text.

It should indeed only be shown when the first post is being edited. Not sure why it's added as a sub-array - that's clearly a bug in my opinion.
