### ISSUE TITLE
Multiple bugs in translation files (probably all translations affected)

### ISSUE THREAD

**Issue by woodholly** [SimpleMachines/SMF#6709]
#### Description
Invalid double backslash in russian translation files:
`
Themes/default/languages/index.russian.php:$txt['regards_team'] = "С уважением,\nАдминистрация форума %1\\$s";
Themes/default/languages/index.russian.php:$txt['movetopic_default'] = "Тема перенесена в %1\\$s.\n\n%2\\$s";
Themes/default/languages/Profile.russian.php:$txt['profile_warning_notify_template_outline'] = "{MEMBER},\n\nВы получили предупреждение за %1\\$s. Пожалуйста, соблюдайте правила форума, иначе мы предпримем другие меры.\n\nЕсли вы хотите обсудить это, свяжитесь с администратором.\n\n{REGARDS}";
Themes/default/languages/Profile.russian.php:$txt['profile_warning_notify_template_outline_post'] = "{MEMBER},\n\nВы получили предупреждение за %1\\$s в сообщении:\n{MESSAGE}.\n\nПожалуйста, соблюдайте правила форума, иначе мы предпримем другие меры.\n\nЕсли вы хотите обсудить это, свяжитесь с администратором.\n\n{REGARDS}";
Themes/default/languages/Admin.russian.php:$txt['security_wrong'] = "Попытка войти под администратором!\nReferrer: %1\\$s\nUser-agent: %2\\$s\nIP: %3\\$s";
`

All \\$s should be replaced with \$s

### Environment (complete as necessary)
- Version/Git revision: 2.1 RC3

**Comment by BrickOzp** [comment]
Duplicate of https://github.com/SimpleMachines/SMF2.1/pull/6607
Already fixed but downloaded translations will not be affected until RC4 is released

**Comment by woodholly** [comment]
Good!
