### ISSUE TITLE
Interesting bug with [code] copy/paste using WYSIWYG editor

### ISSUE THREAD

**Issue by woodholly** [SimpleMachines/SMF#6714]
#### Description
Interesting because [quote] not affected ....
I also added smiles bug as a bonus ;)

Video gif:
![bugs](https://user-images.githubusercontent.com/65503093/115967757-01664600-a53d-11eb-976b-89485d6e8e9b.gif)

### Environment (complete as necessary)
- Version/Git revision: RC3

**Comment by woodholly** [comment]
This is sceditor bug, will be fixed by sceditor.

**Comment by jdarwood007** [comment]
Reopening then.  Will keep an eye on SCeditor for a release and once we have updated the plugin, this can close.

**Comment by Sesquipedalian** [comment]
Fixed by #6877
