### ISSUE TITLE
Bugged mouse selection does not reset on click

### ISSUE THREAD

**Issue by woodholly** [SimpleMachines/SMF#6716]
#### Description
Usually if you select anything in the internet with your mouse pointer, you can click inside selected area and this resets the selection. But not inside SMF 2.1 posts ... Why? Selection can only be reset by clicking outside selected area.
Selection here is not html select but, clipboard select.

### Steps to reproduce
1. open any smf post
2. keydown left mouse button and move it to select some text
3. click inside selected text to reset selection
4. no you can't ...

### Environment (complete as necessary)
- Version/Git revision: RC3

**Comment by jdarwood007** [comment]
This is most likely due to the quote selected text feature.
