### ISSUE TITLE
🚨 Potential Server-Side Request Forgery (SSRF) (CWE-918)

### ISSUE THREAD

**Issue by huntr-helper** [SimpleMachines/SMF#6734]
👋 Hello, @MissAllSunday, @Sesquipedalian, @Oldiesmann - a potential critical severity Server-Side Request Forgery (SSRF) (CWE-918) vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-SimpleMachines/SMF2.1** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by sbulen** [comment]
Thank you for the report.  Note that we have a separate link for reporting security issues (which is available when you click on the New Issue button above):
https://www.simplemachines.org/about/smf/security.php

The issue you reported above was addressed in a prior release, quite some time ago.  You need to note this was closed out in your internal tracker.

If you still believe this is an open issue, please feel free to report the issue following the proper link, and please provide details on how to replicate.

SMF Dev team
