### ISSUE TITLE
🚨 Potential OS Command Injection (CWE-78)

### ISSUE THREAD

**Issue by huntr-helper** [SimpleMachines/SMF#6735]
👋 Hello, @MissAllSunday, @Sesquipedalian, @Oldiesmann - a potential high severity OS Command Injection (CWE-78) vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/2-other-SimpleMachines/SMF2.1** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by live627** [comment]
That site  claims that    I'm not a maintainer of this repo even though I am.  @JamieSlome can you look into this please?

**Comment by JamieSlome** [comment]
Hey 👋 @live627 - apologies for the confusion. I will get this sorted for you now, so you can view the advisory page against your repository.

Let me know if you have any more questions, and happy to help! 🍰

**Comment by JamieSlome** [comment]
Hey 👋 @live627 - apologies for the confusion. I will get this sorted for you now, so you can view the advisory page against your repository.

Let me know if you have any more questions, and happy to help! 🍰

**Comment by sbulen** [comment]
Thank you for the report.  Note that we have a separate link for reporting security issues (which is available when you click on the New Issue button above):
https://www.simplemachines.org/about/smf/security.php

The issue you reported above was addressed in a prior release, quite some time ago.  You need to note this was closed out in your internal tracker.

If you still believe this is an open issue, please feel free to report the issue following the proper link, and please provide details on how to replicate.

SMF Dev team
