### ISSUE TITLE
Can't clear old privacy policy changes from administration log

### ISSUE THREAD

**Issue by SugarD-x** [SimpleMachines/SMF#6741]
#### Description
After editing the privacy policy, you aren't able to clear the logged changes from the administration log.

### Steps to reproduce
1. Modify the privacy policy.
2. Attempt to clear privacy policy changes from the administration log, even weeks later.

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1 RC3
- Database Type: MySQL
- Database Version: MySQL Community Server 8.0.24
- PHP Version: 7.4.18

### Additional information/references
After clearing the administration log, I was able to remove all entries _except_ the privacy policy ones. The entries are **more than two weeks old**, and the option to select them to manually remove them is also grayed out. (This behavior seems to only be typical for logs that are not old enough to delete yet for security purposes).

I have not tried to reproduce this yet, so this could be a one-off bug, but I couldn't find anyone else experiencing this, and the privacy policy is still such a new feature that I'd imagine no one else has noticed it yet if it is reproduceable.

**Comment by albertlast** [comment]
My opinion is,
That the changelog needs so long hold,
Until the last one is accepting the new one or 5 years.

**Comment by Sesquipedalian** [comment]
This is intended behaviour. Changes to the registration agreement and privacy policy are logged permanently for the sake of your own legal protection under the rules of the GDPR and similar laws. We should actually be logging the full text of each version, too, which it looks like we aren't. That'd need to be filed as a different issue, though.
