### ISSUE TITLE
Board titles not quoted

### ISSUE THREAD

**Issue by woodholly** [SimpleMachines/SMF#6742]
#### Description
Board titles not quoted inside "new post" form if board number omited, leading to invalid board titles and probably XSS by board creator.

### Steps to reproduce
Create board with double-quotes:
```
My best "Really interesting" board!
```
then open /index.php?action=post
and check board title inside select-box

### Environment (complete as necessary)
- Version/Git revision: RC3

**Comment by BrickOzp** [comment]
This seems to already be fixed on the latest sw. If you refer to the "Post in" select box.

**Comment by woodholly** [comment]
@BrickOzp good!
