### ISSUE TITLE
Size is not a valid attribute for HTML input type number

### ISSUE THREAD

**Issue by WhistlingDonkey** [SimpleMachines/SMF#6745]
#### Description
In Admin.template.php (currently line 980) size is used as an attribute for HTML input type number which is an invalid attribute for this input type, as below:

<input type="', $type, '"', $javascript, $disabled, ' name="', $config_var['name'], '" id="', $config_var['name'], '" value="', $config_var['value'], '"', ($config_var['size'] ? ' size="' . $config_var['size'] . '"' : ''), '', $min . $max . $step, '>';

To set the size of the number input type in the same manner as other input types it will need to be done with inline CSS as suggested below:

<input type="', $type, '"', $javascript, $disabled, ' name="', $config_var['name'], '" id="', $config_var['name'], '" value="', $config_var['value'], '"', ($config_var['size'] ? ' style="width:' . $config_var['size'] . 'rem;"' : ''), '', $min . $max . $step, '>';

Which is the best relative width to use (rem shown) probably needs to be discussed. em, ch and rem would be the logical choices and out of those ch or rem the preferred.

### Environment (complete as necessary)
- Version/Git revision: Github latest

### Additional information/references
See Relative lengths at https://www.w3schools.com/CSSref/css_units.asp for info on em, ch and rem.

**Comment by BrickOzp** [comment]
I think this is already handled.

I found this in index.css

input[type="number"][size="6"] {
    width: calc(6ch + 15px + 0.8em);
}

**Comment by WhistlingDonkey** [comment]
I see how it works now, and why I wasn't getting the expected behaviour (a 10ch wide number box) before trying the inline style method. 

At some stage, depending on what happens with the HTTP response headers we'll need to add a larger number for the number type input to index.css; 6ch isn't wide enough to display a year as seconds which requires 8 digits (a year as seconds is required by HSTS). 10 gives an adequate space.

input[type="number"][size="10"] {
width: calc(10ch + 15px + 0.8em);
}

While the current method works it does limit the width of a number input box to a few small sizes. The more dynamic approach can perhaps be revisited in the future.

I think we can close this issue unless anyone else has something to add. Adding the new rule to index.css to get a wider than 6ch number box can be done as part of the HTTP response headers.
