### ISSUE TITLE
Invalid timezone code, timezone always UTC

### ISSUE THREAD

**Issue by woodholly** [SimpleMachines/SMF#6747]
#### Description
This line inside Sources/Subs-Members.php:
```php
'timezone' => empty($regOptions['timezone']) || !in_array($regOptions['timezone'], smf_list_timezones()) ? 'UTC' : $regOptions['timezone'],
```
is invalid, because smf_list_timezones() returns associative array( 'timezone' => 'timezone description' ), and in_array test always returns false so timezone is always 'UTC'.

This test should use array_key_exists:
```php
'timezone' => empty($regOptions['timezone']) || !array_key_exists($regOptions['timezone'], smf_list_timezones()) ? 'UTC' : $regOptions['timezone'],
```

### Environment (complete as necessary)
- Version/Git revision: latest

**Comment by BrickOzp** [comment]
Nice catch

Found out how it will affect in reality

1. Remove timezone from registration fields
2. Register new user
3. Users time zone is set to UTC even if the forum default time zone is not UTC

**Comment by woodholly** [comment]
@BrickOzp you are right, default timezone is also forgotten here, so here we have 2 bugs in the same line :) 'UTC' should be replaced with forum-default-timezone.
This affects all alternative-registration-mods, like social registration (that is how I have found it).

**Comment by BrickOzp** [comment]
No $regOptions['timezone'] is the forum default timezone

**Comment by woodholly** [comment]
Are you sure ?
$regOptions['timezone'] is timezone provided by user of registerMember function.
Real forum default timezone is in $modSettings['default_timezone']
Well you can keep 'UTC' as a fallback in this function, but this forces addon-writers to set default timezone from outside.

**Comment by BrickOzp** [comment]
Yes.
The selected timezone is in $regOptions['extra_register_vars']['timezone'] and is later written to $regOptions['timezone']

**Comment by woodholly** [comment]
@BrickOzp I don't think so, try to admin-register new user and timezone will be UTC whatever default timezone is set.

**Comment by woodholly** [comment]
That happens because developers forgot to provide default timezone in parameters to registerMember function ...
And this happens in all alternative-registration-mods.

**Comment by woodholly** [comment]
$regOptions['timezone'] is not default timezone, but user-defined timezone. So I insist, 'UTC' in that line should be replaced with forum-default timezone.

**Comment by BrickOzp** [comment]
$regOptions['timezone'] is assigned in Register.php line 439
'timezone' => !empty($modSettings['default_timezone']) ? $modSettings['default_timezone'] : '',

A bit further down from your initial code in Subs-Members.php this is done
// Integrate optional member settings to be set.
	if (!empty($regOptions['extra_register_vars']))
		foreach ($regOptions['extra_register_vars'] as $var => $value)
			$regOptions['register_vars'][$var] = $value;

That will overwrite the default timezone value with the one the user selected on the registration page, but only if the timezone is set to be shown at registration.

I have tried to register both with and without the timezone shown at registration and with your initial change I got the correct timezone set for the new user.

Could you point to a use case where it will not work?

**Comment by woodholly** [comment]
I understand what you talking about, but you don't understand me :)
Try to **admin-register** (index.php?action=admin;area=regcenter) new user and timezone will be UTC whatever default timezone is set. Fix does not help with that.

**Comment by BrickOzp** [comment]
Yes, you are right. Will look into it.

**Comment by BrickOzp** [comment]
Ok, a fix for that is pushed to the PR

**Comment by woodholly** [comment]
Looks good, wrong by desing tho,  because it forces addon-writers to set default timezone from outside.

My note about admin-register code was just an example of how easy to fail with that design.
Look for example at this social registration mod: https://github.com/oneall/social-login-simple-machines-forum/blob/smf/2.1%2B/upload/package-files/Sources/OneallSocialLogin.sdk.php
It has this bug, because they have no idea about timezone parameter and that it should be set to default timezone.

What do you think about it ?

**Comment by BrickOzp** [comment]
Yes, I get your point. The new commit would resolve this.
This is probably some carry over from 2.0 where timezone was not shown at registration.

**Comment by woodholly** [comment]
That just disables timezone option at all, and some mods can use it...

This ugly onliner should fix all cases:
```php
'timezone' => !empty($regOptions['timezone']) && array_key_exists($regOptions['timezone'], smf_list_timezones()) ? $regOptions['timezone'] : (!empty($modSettings['default_timezone']) && array_key_exists($modSettings['default_timezone'], smf_list_timezones()) ? $modSettings['default_timezone'] : 'UTC'),
```

**Comment by BrickOzp** [comment]
The correct way would be to do $regOptions['extra_register_vars']['timezone'] = 'timezone name'
For backwards compatibility your code is good though.

**Comment by BrickOzp** [comment]
I have given this some thought and I think we should not add the special handling of timezone.
If a mod want to set the timezone or any other Standard Profile Fields they should use the ['extra_register_vars'].

I don't think there exists a lot of mods using the registerMember function. And if they do, they will probably need to do other changes as well to support the 2.1

But would like other devs opinion about this.

**Comment by Oldiesmann** [comment]
> Yes, I get your point. The new commit would resolve this.
> This is probably some carry over from 2.0 where timezone was not shown at registration.

2.0 doesn't use timezones at all - only time offsets

As far as the timezone goes, I don't see any reason why we shouldn't support allowing users to set that at registration time. It's pretty common these days with other software as I recall (it's been a while since I registered for a forum though). The only mods that would really be touching the registration stuff would be things adding support for login via other websites (Facebook, Google, etc.).

**Comment by BrickOzp** [comment]
> 2.0 doesn't use timezones at all - only time offsets

Oh, so then we don't have anything to be backwards compatible with either.

The timezone option is shown at registration time, if the administrator has it configured to be shown.

The only remaining question was how a mod should pass the timezone setting when register a new user.

And another thing I been thinking about. We do not validate the timezone passed in $regOptions['extra_register_vars']['timezone']. Should we?

**Comment by woodholly** [comment]
@BrickOzp IMHO it is better to validate everything provided by mods :)
