### ISSUE TITLE
undefined index in loadMemberContext() in 'minimal' set

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#6749]
Using the 'minimal' set for `loadMemberData()`, is it allowed to call `loadMemberContext()` after? The code inside `loadMemberContext()` indicates it can be used:

Line 1667:
```
// If the set isn't minimal then load the monstrous array.
if ($context['loadMemberContext_set'] != 'minimal')
```

Also line 1739:

```
// If the set isn't minimal then load their avatar as well.
if ($context['loadMemberContext_set'] != 'minimal')
```

However, there will be undefined indexes if this function is called after the minimal set:

Line 1631:
```
// Censor everything.
censorText($profile['signature']);
censorText($profile['personal_text']);

// Set things up to be used before hand.
$profile['signature'] = str_replace(array("\n", "\r"), array('&lt;br&gt;', ''), $profile['signature']);
$profile['signature'] = parse_bbc($profile['signature'], true, 'sig' . $profile['id_member']);
$profile['is_online'] = (!empty($profile['show_online']) || allowedTo('moderate_forum')) &amp;&amp; $profile['is_online'] &gt; 0;

```

There are no `signature` or `personal_text` or `is_online` in data.  This is what minimal set is loading:

```
			$select_columns = '
			mem.id_member, mem.member_name, mem.real_name, mem.email_address, mem.date_registered,
			mem.posts, mem.last_login, mem.member_ip, mem.member_ip2, mem.lngfile, mem.id_group';
			$select_tables = '';
```

**Comment by asmith20002** [comment]
I think the Question tag has made this issue to be ignored. It is actually a bug. Codes needs to refactor. I can do this but I was waiting for some opinions.

**Comment by MissAllSunday** [comment]
Yes it is indeed a bug, if you can submit a PR @asmith20002 that would be great.
