### ISSUE TITLE
'Top Topic Starters' list in Forum stats displays 9 users only

### ISSUE THREAD

**Issue by Hatshepsut71** [SimpleMachines/SMF#6756]
#### Description
I use SMF 2.1 RC3+ (commit 08c9720), but problem persist since I've installed RC3.
'Top Topic Starters' list in Forum stats displays 9 users only, but that list needs to be with 10 users, as any other lists in Forum stats.

### Steps to reproduce
1. Install SMF 2.1 RC3 or some newer Github build
2. If your forum has more than 10 topic starters, see appropriate list in Forum stats

### Environment (complete as necessary)
- Version/Git revision: 08c9720
- Database Type: MariaDB
- Database Version: 10.3.29
- PHP Version: 8.0.3

### Additional information/references

**Comment by BrickOzp** [comment]
Could you test if the PR solves the problem https://github.com/SimpleMachines/SMF2.1/pull/6757?

I don't have 10 users in my test forum.

**Comment by Hatshepsut71** [comment]
Thanks, with this fix problem is solved, now 'Top Topic Starters' list displays 10 users.
