### ISSUE TITLE
Hook integrate_credits does not support multiple mods copyrights

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#6758]
#### Description
Hook integrate_credits does not support multiple mods copyrights.

### Environment (complete as necessary)
- Version/Git revision: Github Pull Request #6551
- Database Type: MySQL
- Database Version: 8.0.25-0ubuntu0.20.04.1
- PHP Version: 7.4.18

### Additional information/references
https://www.simplemachines.org/community/index.php?topic=577829.msg4089251#msg4089251

**Comment by Sesquipedalian** [comment]
The `integrate_credits` hook does support multiple mods. The symptoms described in the linked post are due to an error by the mod author, not a bug in SMF.
