### ISSUE TITLE
Replacing serialize with json_* functions

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#676]
Several places we use serialize, we should really use json functions instead, e.g. embedding search parameters into a link.

**Comment by jdarwood007** [comment]
To be clear, for 2.1 we need to aim to do this on all user input such as for search.  A complete overhaul to json everywhere isn't needed at this point and could take too long.

**Comment by Arantor** [comment]
Yup, I'm good with that, I just wasn't being specific.

Do you reckon we should backport to 2.0?

**Comment by jdarwood007** [comment]
Unless it poses a significant security issue I don't think it is worth it.

**Comment by emanuele45** [comment]
Just for the record: that means also bump the minimum php version to 5.2 (current is 5.1 if I'm not wrong), unless obviously use some compat thing (if it is worth).

**Comment by Arantor** [comment]
I was going to add that in anyway just in case ;)

**Comment by jdarwood007** [comment]
Well that is true  CentOS 5.9 has only PHP 5.1(.4) in it, Ubuntu 12.04 has PHP 5.3, Debian 5.0 (Obsolete now) had 5.2 it appears.  Trying to find a version matrix (I wish there was one), but with CentOS 5.9 only having 5.1, we can assume most hosters will be using CentOS/RedHat and may still be on 5.9 as there isn't a safe upgrade to 6.0+ versions.  Alternate repos resolve this but its hard to say whether hosts would use it or not.

My assumption is if we did this we would be hitting the combat mode a lot, however in the next year or two we should see 5.3 being mainstream.

**Comment by butch2k** [comment]
You can use distrowatch to get an idea of the PHP versions used in the various distros.

I experienced quite a few problems working with json on the older 5.2 versions, i remember issues with the decimal separators not being properly handled on french locale for instance. Since u do not have json last error function until 5.3 it's a real pain to debug json issues on the 5.2 AFAIR. Everything would probably work just out fine on the latest 5.2 revisions though.

**Comment by Arantor** [comment]
There is a very large problem with this: json_encode and json_decode do not behave properly with non-UTF-8 content. Which means we either need to be UTF-8 only or we need a complete replacement that's character-set safe in the meantime :(

**Comment by Kindred-999** [comment]
note, additional information provided...
http://www.simplemachines.org/community/index.php?topic=531549.0

**Comment by Oldiesmann** [comment]
Closing this since this has been taken care of now.
