### ISSUE TITLE
Invalid encoding of RSS feed name for non-latin utf-8 characters

### ISSUE THREAD

**Issue by woodholly** [SimpleMachines/SMF#6760]
#### Description
Example of invalid feed name:
```
Ð_Ð¾Ñ_Ñ_Ð¼_-recent-rss.xml
```

### Steps to reproduce
1. make forum title in non-latin utf-8 characters, for example: ФОРУМ (FORUM in russian)
2. click RSS link: /index.php?action=.xml;type=rss
3. check xml filename, it contains invalid utf-8 characters: Ð_Ð¾Ñ_Ñ_Ð¼_-recent-rss.xml

### Environment (complete as necessary)
- Version/Git revision: RC3

**Comment by Sesquipedalian** [comment]
Please test the changes in #6761 to see if they solve the problem.

**Comment by woodholly** [comment]
@Sesquipedalian tested, yes this patch fixes the issue!
