### ISSUE TITLE
Installer - cookie setting defaults confused 

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6762]
#### Description
The default cookie setting logic attempts to set the local & global cookie settings and the global cookie domain based on the board url.

It is confusing multi-level tlds with subdomains, e.g., when it sees xxxxx.com.au, it will set global cookies to true and the domain to com.au.

### Additional information/references
This has come up a few times recently in the support forums:
https://www.simplemachines.org/community/index.php?topic=577727.msg4088673#msg4088673

This needs to be looked at:
https://github.com/SimpleMachines/SMF2.1/blob/ab409dffe23b960cfec2744f09c98734af6284fb/other/install.php#L1294

**Comment by MisterVector** [comment]
This is a very interesting issue. The only way I can think of to address this is to store a list of all known multi-level TLDs and searching against that. Otherwise I'm not sure how you can determine from a domain string what the TLD is.

**Comment by BrickOzp** [comment]
There seems to be a list here https://www.publicsuffix.org/

Library that claim to parse all ccSDs 
https://github.com/layershifter/TLDExtract PHP <= 7.3 (deprecated)
https://github.com/jeremykendall/php-domain-parser PHP >= 7.4
https://github.com/utopia-php/domains PHP >= 7.4
