### ISSUE TITLE
JPEG thumbnail orientation incorrect for images that are rotated by Imagick 

### ISSUE THREAD

**Issue by GL700Wing** [SimpleMachines/SMF#6770]
The changes introduced with https://github.com/SimpleMachines/SMF2.1/pull/6608 have introduced a problem with thumbnails created by Imagick for images that are rotated - the testing I've done indicates that the EXIF orientation values are only needed for GD.

Reported here with suggested fix: https://www.simplemachines.org/community/index.php?topic=577205.msg4089588;topicseen#msg4089588

Also, [GD rotates images **anticlockwise/counterclockwise**](https://www.php.net/manual/en/function.imagerotate.php) while [Imagick rotates images **clockwise**](https://www.php.net/manual/en/imagick.rotateimage.php) so the rotation values for EXIF orientations 6 and 8 in Subs-Graphics.php were only correct for GD.

![Imagick-1](https://user-images.githubusercontent.com/67716760/120885283-76906500-c62b-11eb-9467-d4c46f53beb3.jpg)

**Comment by BrickOzp** [comment]
Could you attach the images you used for the test?
I have tested with the image from https://github.com/SimpleMachines/SMF2.1/issues/5165 and it requires the rotation code for Imagick for the thumbnail to be rotated correctly.

Another thing could be the Imagick version. Maybe they have fixed this in a later version. I am using version 3.4.3. What is your version? You can find it in the php-info section of the admin portal.

**Comment by BrickOzp** [comment]
After doing some research it could possibly be your browser that is rotating the images.

Could you try this change in Subs-Graphics.php around line 466
			if ($rotate != 0)
			{
				$imagick->rotateImage('#00000000', $rotate);
				$imagick->setImageOrientation(Imagick::ORIENTATION_TOPLEFT);
			}

**Comment by GL700Wing** [comment]
Here's a link to the images I use for EXIF testing: https://github.com/recurser/exif-orientation-examples.

I'm using Imagick 3.4.4 

I've done a test with PNG and JPEG thumbnails with the original code and the suggested update - see https://not-at-home.today/forum_21/index.php?topic=13.0

I've also done a test with PNG and JPEG thumbnails using the code edit I suggested: https://not-at-home.today/forum_21/index.php?topic=5.0

The images always display correctly in the browser (Firefox, Chrome and Edge) when opened by clicking on the thumbnail and in the original orientation when downloaded via the image link - it's the thumbnails that are not displayed correctly below the message.

**Comment by BrickOzp** [comment]
Could you try the patch in https://github.com/SimpleMachines/SMF2.1/pull/6775

I could't get imageflip() to work for GD so inverted thumbnails are not correct, but rotation should be right.
For Imagick imverted thumbnails should be correct

**Comment by GL700Wing** [comment]
Results of my testing of your latest code change here:  https://not-at-home.today/forum_21/index.php?topic=14.0
OK for Imagick/PNG thumbnails but still issues for Imagick/JPEG thumbnails.

I've attached a version of Subs-Graphics.php that is working correctly for Imagick and GD thumbnails (both PNG and JPEG) - you can see the results here: https://not-at-home.today/forum_21/index.php?topic=15.0

[Subs-Graphics.txt](https://github.com/SimpleMachines/SMF2.1/files/6616320/Subs-Graphics.txt)

PS:  I used 'flopImage' instead of 'flipImage' for Imagick.

**Comment by BrickOzp** [comment]
Now I think it should work for all cases

**Comment by GL700Wing** [comment]
You code now works for all cases.

Some things to consider:
1.  I don't think the 'resizeImageFile' function needs to work out the orientation because the only thing it does with that information/variable is to pass the value to the 'resizeImage' function - consider putting orientation code in the 'resizeImage' function.
2.  The code for rotating/flipping images does not need to be executed for images that are already correctly oriented (ie, orientation value = 1).
3.  The code for rotating/flipping images can be further streamlined.

[resizeImage.txt](https://github.com/SimpleMachines/SMF2.1/files/6620737/resizeImage.txt)
