### ISSUE TITLE
Setting user's post count to a negative value causes an error when saving

### ISSUE THREAD

**Issue by MisterVector** [SimpleMachines/SMF#6771]
When modifying a user's post count in their profile and setting it to a negative value, an error will be given when attempting to save the profile. SMF will attempt to insert the negative value into the database despite the column being unsigned.

![image](https://user-images.githubusercontent.com/437096/120915939-7c9e3a00-c65b-11eb-9289-25fa6d926034.png)

To reproduce, go to user's profile and modify "Account Settings" and set the post count to a negative value and then attempt to save.

**Comment by Sesquipedalian** [comment]
Can you tell us what outcome you had expected? From my perspective, generating an error seems like the right response, since a negative post count makes no sense. Were you just looking for a more pleasant and descriptive error message, or...?

**Comment by MisterVector** [comment]
Yes the fact there was an error should be fine. However, I figured that it wasn't consistent with other errors encountered, such as this:

![image](https://user-images.githubusercontent.com/437096/120937620-60ce7e80-c6c3-11eb-857c-fa09878f0e15.png)

**Comment by Sesquipedalian** [comment]
Understood. So basically, we should return a nicer error message. I agree. Thanks.

**Comment by Oldiesmann** [comment]
If that uses the standard "number" HTML input type, we can set a min value of 0 as well. Won't completely prevent the issue (could possibly still happen if you're on an ancient browser), but it'll all but eliminate it at least.

**Comment by MisterVector** [comment]
FYI the error also happens if you set the posts count greater than 16777215 (MEDIUMINT max value unsigned).
