### ISSUE TITLE
default_time_format not honoring seconds

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6791]
#### Description
I see "Invalid Date" errors entering events into the calendar on my migrated test 2.1 forum.  

Then I noticed the times looked funky:
![invalid-date-migrated-forum](https://user-images.githubusercontent.com/23568484/122509316-6d52b100-cfb8-11eb-86b7-5ca68fcf3bb0.png)

It appears the :%S to include seconds in the time is not working.  This is the default time format:
![image](https://user-images.githubusercontent.com/23568484/122509798-4052ce00-cfb9-11eb-8f75-4306346e7712.png)

Note the DB allows seconds, so I think the :%S should be valid:
![image](https://user-images.githubusercontent.com/23568484/122509588-e6520880-cfb8-11eb-95ea-4d4fbb76084c.png)

### Steps to reproduce
1. Add :%S to the default time format
2. Add an event in the calendar

OR....

1. Add an event in the calendar on a migrated forum that had :%S specified (the old default)

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 7.4

### Additional information/references
This is the **_2.0 default time format_** upon install - unless overridden, it specifies seconds:
![image](https://user-images.githubusercontent.com/23568484/122509472-b1de4c80-cfb8-11eb-813b-17ecd50f29a8.png)

This is the **_2.1 default time format_** upon install:
![image](https://user-images.githubusercontent.com/23568484/122509496-bdca0e80-cfb8-11eb-91a5-1dfc9640e416.png)

Not a big priority - workaround is easy, to remove the :%S.

**Comment by BrickOzp** [comment]
This fix will remove the trailing colon
https://github.com/SimpleMachines/SMF2.1/pull/6637

**Comment by Oldiesmann** [comment]
Shouldn't we keep the default time format the same in 2.1 as well? There's no real reason to change it.

**Comment by sbulen** [comment]
> Shouldn't we keep the default time format the same in 2.1 as well? There's no real reason to change it.

That was changed 7+ years ago (#1158).  At this point, we should leave it be.
