### ISSUE TITLE
https link in copyright

### ISSUE THREAD

**Issue by Dzonny** [SimpleMachines/SMF#6795]
We should have https link in copyright here?
https://github.com/SimpleMachines/SMF2.1/blob/2f165a0913145292f3352b14d3f158a921f7d3cb/Themes/default/languages/index.english.php#L508

Ref: https://www.simplemachines.org/community/index.php?topic=577992.0

**Comment by BrickOzp** [comment]
Fixed in https://github.com/SimpleMachines/SMF2.1/pull/6794
