### ISSUE TITLE
Out of range value for column 'id_profile' at row 1

### ISSUE THREAD

**Issue by woodholly** [SimpleMachines/SMF#6798]
#### Description
SQL database error at new board creation with non-standard access settings (not sure which one):
```sql
UPDATE smf_boards
			SET
				id_cat = 13,
				id_parent = 0,
				child_level = 0,
				board_order = 59,
				count_posts = 1,
				id_theme = 0,
				override_theme = 0,
				member_groups = '2,9',
				deny_member_groups = '',
				name = 'zzzzzzzzzzzzzzz',
				description = 'zzzzzzzzzzzzzzzzzzzzzzz',
				id_profile = -1,
				redirect = ''
			WHERE id_board = 129
```

### Steps to reproduce
Choose profile = -1 (first option) on board settings.

### Environment (complete as necessary)
- Version/Git revision: RC3
- Database Type: Mysql

**Comment by sbulen** [comment]
Yep.  To reproduce:
 - Add a new board
 - Select [inherit from parent] as the permission profile
 - You will fail on this error whether or not a parent board actually exists
