### ISSUE TITLE
Invalid HTML generated

### ISSUE THREAD

**Issue by woodholly** [SimpleMachines/SMF#6799]
#### Description
Small html bug here, this code generated inside Sources/Display.php works but not valid HTML:
```html
<li class="quick_edit" id=" modify_button_223051"onclick="oQuickModify.modifyMsg('223051', '')">
```
Look closely, space before "onclick" absent, and there is space after id=" ...

### Steps to reproduce
Always, for signed users.

### Environment (complete as necessary)
- Version/Git revision: RC3

**Comment by MissAllSunday** [comment]
It seems there was a recent fix for this, can you please use the current build from github rather than the RC3 release and see if the issue still persists?

**Comment by woodholly** [comment]
@MissAllSunday is there any bash/shell script to install SMF quickly and test it ?
Like this:
test_smf.sh --add-test-topics --add-test-users smf2.1RC3.zip
Script unpacks, sets default settings, setups sqlite database, starts web-server at 127.0.0.1:8080

**Comment by MissAllSunday** [comment]
Not really no, updates from RC to RC aren't supported and building a script to make all the DB changes so far would actually take more time than just starting out a new test site.

Remember, we don't recommend running RCs on production, for this very same reason.

**Comment by MissAllSunday** [comment]
You can also apply the commit directly to your files:

https://github.com/SimpleMachines/SMF2.1/commit/7c26a090b15a1fc88bed0ab3e8c7476ff30314d1

as a way to quick test if that commit fixes your issue.

**Comment by woodholly** [comment]
> Not really no, updates from RC to RC aren't supported and building a script to make all the DB changes so far would actually take more time than just starting out a new test site.

No, that's not what I mean. I want quick and easy way to install clean brand new smf forum of any version to quickly test commits ...

> 
> Remember, we don't recommend running RCs on production, for this very same reason.

I already did that ... wait a minute .. can I at least upgrade from RC3 to RC4 not by "upgrade package", but by reinstalling all files and mods?

**Comment by Oldiesmann** [comment]
You can upgrade from the git build easily. Just download, overwrite your files, move the "upgrade" files from the "other" directory to the main directory and run upgrade.php like usual.

**Comment by woodholly** [comment]
> You can also apply the commit directly to your files:
> 
> [7c26a09](https://github.com/SimpleMachines/SMF2.1/commit/7c26a090b15a1fc88bed0ab3e8c7476ff30314d1)
> 
> as a way to quick test if that commit fixes your issue.

I can't test it because it requires previous patches... but that patch probably solves the issue.

> You can upgrade from the git build easily. Just download, overwrite your files, move the "upgrade" files from the "other" directory to the main directory and run upgrade.php like usual.

Good!
