### ISSUE TITLE
Tiny annoying problem with attachment after upgrade :)

### ISSUE THREAD

**Issue by woodholly** [SimpleMachines/SMF#6810]
#### Description
After upgrade of a large forum from SMF 2.0 to SMF 2.1 everything works smoothly, except that I see insignificant but annoying  errors inside error log:
`
md5_file(/var/www/html/attachments/23742_12127006f5580f2a4ba08404a1470d8a393f96dd.dat): failed to open stream: No such file or directory
`
This attachment is an image and it is successfully shown inside the topic.
There is file without ".dat" extension present: /var/www/html/attachments/23742_12127006f5580f2a4ba08404a1470d8a393f96dd

How this happened ? Why this file wasn't renamed to .dat extension by upgrade script ?

PS: most of the other attachments are correct and with .dat extension, only some (very small amount) of attachments annoy me with this error in error log

**Comment by BrickOzp** [comment]
I think this could be the same problem as in https://github.com/SimpleMachines/SMF2.1/issues/6181

A bit more severe than just nu setting the mime type

**Comment by woodholly** [comment]
How can be this fixed after upgrade, should I just rename them to .dat ?

**Comment by Sesquipedalian** [comment]
> How can be this fixed after upgrade, should I just rename them to .dat ?

That's more of a support request than a bug report. Please create a support request topic in the [SMF 2.1 Support](https://www.simplemachines.org/community/index.php?board=254.0) board for that. Feel free to include a link back to this issue as part of explaining the problem you are trying to solve.

**Comment by BrickOzp** [comment]
The issue was not bad, Sesquipedalian was just referring to your last comment.

I have been able to reproduce this problem. Though I did not having any problem with showing the files. Maybe this could be attachments uploaded from older SMF versions. I did only try 2.0.18
