### ISSUE TITLE
Users randomly switch login to other users.

### ISSUE THREAD

**Issue by mobasuite** [SimpleMachines/SMF#6816]
#### Description
Users are switched to other peoples login username by random after clicking a certain category/topic.

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision: 3f83b01
- Database Type: mysql
- Database Version:
- PHP Version: 8

### Additional information/references

**Comment by jdarwood007** [comment]
Can you describe the scenarios you are seeing this in?
What is your setup like?
Can you reproduce this on other setups?

**Comment by mobasuite** [comment]
my forum is closed for guests, but users are able to "sneak peek" on other peoples login, not intentionally just by "random", at least it says they are logged in as another user when they are logged in as themselves.

Here is my phpmyadmin info :

Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.3.29-MariaDB-0ubuntu0.20.04.1 - Ubuntu 20.04
Protocol version: 10
User: -----
Server charset: UTF-8 Unicode (utf8mb4)

**Comment by jdarwood007** [comment]
How are you handling sessions?  php default (file based), php extension or database driven?
Are you using SSL on  your site itself?
Do your urls contain a session ID?

**Comment by mobasuite** [comment]
it was database driven, turned it off now, as well as enabled secure cookies & local storage of cookies.

SSL is available for the site and is used in the default installation directory of the forum.

Session ID, how would one see that ?

**Comment by mobasuite** [comment]
this happens less often now, but now the problem of a secondary login screen for accessing the board.
