### ISSUE TITLE
"Go Down" button not visible on mobile for topics

### ISSUE THREAD

**Issue by HogCode** [SimpleMachines/SMF#6817]
#### Description
The mobile presentation of a topic does not display the "GO DOWN" button even though it does display the "GO UP" button. This issue only goes into effect when the browser window is less than 720px wide.

This issue only shows up on the Topic page, **not** the Board page which has the same Go Down / Go Up buttons

### Steps to reproduce
1. Install a fresh copy of SMF 2.1 RC3
2. Navigate to the default "Welcome to SMF!" topic.
3. Reduce the width of your screen to under 720px or view on a mobile device. 

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1 RC3

**Comment by DiegoAndresCortes** [comment]
Seems like this could've been a mistake?
