### ISSUE TITLE
Main menu is visible through maximized Editor

### ISSUE THREAD

**Issue by Hatshepsut71** [SimpleMachines/SMF#6820]
Hello,
I'm using SMF 2.1 RC4 (last Github build 0f375f1)
When I maximize Editor to reply on some topic, main forum menu is visible in Editor window:

![2021-07-09](https://user-images.githubusercontent.com/68983397/125097008-5a765c80-e0de-11eb-9618-c043c3250da3.png)

### Steps to reproduce
1. Install last Github build 0f375f1
2. Open Editor and then maximize it

### Environment (complete as necessary)
- Version/Git revision: 0f375f1
- Database Type: MariaDB
- Database Version: 10.3.30
- PHP Version: 8.0.7

### Additional information/references

**Comment by smfbigguy** [comment]
Seems the z-index in the css needs to be changed somewhere maybe. (Just a guess though)

**Comment by Sesquipedalian** [comment]
I wish this report had come in a day or two earlier, so that we could have included the fix in RC4. At any rate, please test #6822 and let us know whether that resolves the issue for you.

**Comment by Hatshepsut71** [comment]
Yes, with this fix problem is solved. Now main menu items are not visible in maximized Editor :)
