### ISSUE TITLE
Users Logins randomly switch to other users

### ISSUE THREAD

**Issue by mobasuite** [SimpleMachines/SMF#6821]
#### Description
Once logged in the profile field for "logged in user" switches to other users login by random.

### Steps to reproduce
1.  Login
2.  Click around on boards and topics
3. Users become logged in as another user.

### Environment (complete as necessary)
- Version/Git revision: RC4 (1ab0407)
- Database Type: MySQL
- Database Version: libmysql - 5.6.43
- PHP Version: 7.3.28

**Comment by mobasuite** [comment]
might have been just a configuration error on my part in Settings.php, changing localhost to actual IP and port to actual port seemed to have solved it. (although not 100% sure yet)

**Comment by Sesquipedalian** [comment]
I cannot reproduce this issue using the information provided.

**Comment by mobasuite** [comment]
I've reinstalled once, and upgraded twice, the database is brand new.

Is there a way to move database ?

**Comment by mobasuite** [comment]
It only happened after this new installation, although seems less frequent now than before.

**Comment by Sesquipedalian** [comment]
This now sounds more like a support request than a bug report. Please create a support request at https://www.simplemachines.org/community/index.php?board=254.0
