### ISSUE TITLE
Undefined $domain

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#6825]
https://github.com/SimpleMachines/SMF2.1/blob/61ba790d56415fc9aa4821be31717989e98c8995/Sources/Security.php#L1470

Is this variable $domain right? Or is right $subdomain.

**Comment by Sesquipedalian** [comment]
I suspect that it should be `$base_domain`, but @jdarwood007 would be the best person to answer that question.

**Comment by jdarwood007** [comment]
Yea it should be $base_domain.  That line of code would pop a subdomain like www or sub off www.domain.tld or sub.domain.tld respectively
