### ISSUE TITLE
Subscriptions-PayPal has mutiple exit statements

### ISSUE THREAD

**Issue by HoverClub** [SimpleMachines/SMF#683]
Subscriptions-PayPal has multiple places where is exits() directly without any error logging or other debug information.  

The log_error function is loaded and available however, it's not normally good practice to call external functions from inside a class so has anyone got any other practical solution - fixing PayPal issues is very difficult the way things are?

**Comment by Arantor** [comment]
If there are functions available, they should be called. I've never heard of this 'not good practice' thing that you're referring to. Mind you, a class of procedural and OOP isn't particularly good practice in general ;)

The main reason for exit() is straightforward; it's not like the subs routines ever output anything back to the IPN sender in the first place, so exit is the quickest way out of that.

If you want to change it for debugging, go nuts and change it. The main issue is understood already (just not yet solved) - in that it doesn't support half the things PayPal will notify for. But I don't really want to add a ton of debugging stuff to the core, just while we're debugging.

**Comment by HoverClub** [comment]
Encapsulation is the word - however, as you say, it's an uncomfortable mix at the moment,,,,,   

No problem - it's just something to consider in future.

**Comment by Arantor** [comment]
In the future I still wouldn't change it. There is no reason for leaving debug stuff in a production build.
