### ISSUE TITLE
New replies warning can no longer be disabled

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6851]
#### Description
Reported in the forum:
https://www.simplemachines.org/community/index.php?topic=578187.0
https://www.simplemachines.org/community/index.php?topic=577845.0
https://www.simplemachines.org/community/index.php?topic=537677.0

Yes, in high volume forums this would be extremely annoying.

There was a setting in 2.0 that was removed in 2.1 for some reason.  (Possibly in error? The setting is still referenced in the code...)

Should be logged.  I would not flag it for Final.

**Comment by sbulen** [comment]
Looks like this was always controversial.  There is no reason documented for the change.
https://github.com/SimpleMachines/SMF2.1/pull/1082

**Comment by Sesquipedalian** [comment]
Yeah, I think we should probably revert #1082.

**Comment by Sesquipedalian** [comment]
> I would not flag it for Final.

I disagree. The fix is fast and easy, and the issue is very frustrating for those whom it affects. All we are doing is bringing back a user setting that existed in 2.0.

**Comment by sbulen** [comment]
I sure wish the reason for the change was documented.

Chesterton's fence...  (https://fs.blog/2020/03/chestertons-fence/)

One of the reasons I'm so conservative when it comes to such changes....

**Comment by Sesquipedalian** [comment]
My guess is that it was removed in pursuit of greater simplicity in a Simple Machines Forum. I get the reasoning there, but this has turned out to be a case where "everything should made be as simple as possible, but no simpler."
