### ISSUE TITLE
"New" link can sometimes use incorrect text colour

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#6853]
Under certain (rare?) circumstances, the "New" link next to a topic title could end up using the incorrect text colour. Specifically, if the URL in the href attribute of the link is one that has been visited before in the browser, the CSS for `a:visited` has a higher precedence than the CSS for `.new_posts`, and so the text colour for visited links, `#346`, overrides the `#fff` defined for the "New" link.

![Screen Shot 2021-07-18 at 7 15 14 PM](https://user-images.githubusercontent.com/191731/126089485-675424a2-f3cb-4ba4-8a82-07e3bb59aff2.png)

**Comment by albertlast** [comment]
Since i tumble across this topic in this pr too: https://github.com/SimpleMachines/SMF2.1/pull/6842
why we use #new instead of real msg id in # ?

**Comment by Sesquipedalian** [comment]
It is possible that the value of "new" will change between the the time when the message index is displayed and the time when the topic is displayed. Targeting `#new` lets us determine the correct post to target using the most recent information when preparing the topic for display.

**Comment by albertlast** [comment]
I understand but is see some disadvantage by this,
let's say you open the message index see some post with new,
klick on this with the command to open in a new tab,
look into this, close this tabn and than you remember you want to check this again, when you now click on new again you land somewhere else and not any more where you land before.

so for my is the dynamical not always the right way to approache the user "needs" special he didn't refreshed the message index but land on different places in a post depends on behavior which happen somewhere else.

**Comment by Sesquipedalian** [comment]
If you think the behaviour should change, that's probably something that should be discussed separately. Such changes would be out of scope for this issue.
