### ISSUE TITLE
$context['javascript_vars'] and the value of 0

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#6859]
I was working on a personal project and used an integration hook to insert a custom value to $context['javascript_vars']:

```
$context['javascript_vars']['custom_count'] = 0;
```

That will be printed inside script tag as this:

```
var custom_count;
```

So it gets set as null instead of 0.

This is how it works:
for boolean values, we can set strings:

```
$context['javascript_vars']['custom_count'] = 'true';
```

For strings we'll use JavaScriptEscape():
```
$context['javascript_vars']['custom_count'] = JavaScriptEscape('Custom value');
```

I don't think there's a way for the actual zero value.

Subs.php, line 4311:
```
		foreach ($context['javascript_vars'] as $key => $value)
		{
			if (empty($value))
			{
				echo '
		var ', $key, ';';
			}
			else
			{
				echo '
		var ', $key, ' = ', $value, ';';
			}
		}
```

Following the boolean style and setting '0' also won't work because '0' is also empty()

The solution could be:
```
if (empty($value) && !is_numeric($value))
```

**Comment by Sesquipedalian** [comment]
That sounds like a good solution to me.
