### ISSUE TITLE
SSI:  Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6863]
#### Description
Error is present simply loading ssi_examples.php.

Nothing urgent, but should be cleaned up:
![image](https://user-images.githubusercontent.com/23568484/126575861-be49b839-0921-4aba-95cb-3ca88e29df18.png)

### Steps to reproduce
1. Load ssi_examples.php with your console browser open

### Environment (complete as necessary)
- Version/Git revision: Current
- PHP Version: 7.4
- Browser: Firefox

**Comment by Sesquipedalian** [comment]
Looks like we need to add jQuery to ssi_examples.php.
