### ISSUE TITLE
UTF-8 characters not showing as UTF-8 characters

### ISSUE THREAD

**Issue by WhistlingDonkey** [SimpleMachines/SMF#6875]
#### Description
When a UTF-8 character is put into a signature, topic subject or post using &#xxxx; notation it doesn't show as the UTF-8 character once the signature, topic subject or post is saved but retains it's &#xxxx; notation. It does show correctly in signature preview.

### Steps to reproduce
1. Put a UTF-8 character into a signature, topic subject or post using &#xxxx; notation.
2. Save the signature, topic or post.

### Environment (complete as necessary)
- Version/Git revision: Github latest
- Database Type: MariaDB
- Database Version: 15.1
- PHP Version: 7.3

**Comment by Sesquipedalian** [comment]
That actually sounds like a bug in the signature preview. We always try to preserve strings as entered, which means `&#12345;` is indeed supposed to be stored as `&amp;#12345;` in order to preserve the literal string. The signature preview is making a mistake by not encoding the `&` to `&amp;`.

**Comment by sbulen** [comment]
> That actually sounds like a bug in the signature preview. We always try to preserve strings as entered, which means `&#12345;` is indeed supposed to be stored as `&amp;#12345;` in order to preserve the literal string. The signature preview is making a mistake by not encoding the `&` to `&amp;`.

Correct.  What is entered should be displayed.  If you want to see a UTF8 character, you should enter a UTF8 character.

We have been stamping out all the weird edge cases where some characters are displayed inappropriately as encoding.  But I think there are still outliers, e.g., I sometimes see still-encoded characters in browser tabs.  This might be the last one, though:
![image](https://user-images.githubusercontent.com/23568484/126838345-ab1bec26-6865-4e55-b021-8f8fa62104fc.png)

**Comment by sbulen** [comment]
So I think there are two issues here:

- Signature not properly encoded
- Browser tabs not properly un-encoded

**Comment by WhistlingDonkey** [comment]
Ok, I had it backwards and SMF doesn't encode HTML entities (nor u+xxxx or u/xxxx and others) to UTF-8 for you when saving and the signature preview has the bug. What threw me was the function Convert HTML-entities to UTF-8 characters in Forum Maintenance -> Database did not convert any of the HTML entities in the database to UTF-8 when I ran it.

I can see a few edge cases where preserving the literal string (for example with HTML entities) would be a pain where someone uses things like maths / scientific symbols a lot and they might have to copy and paste UTF-8 symbols endlessly into SMF but other that that it's probably not a big deal.

**Comment by sbulen** [comment]
Since mysql's implementation of utf8 only honors 3 bytes, it cannot store all unicode characters.  Any 4-byte utf8 chars (emojis, some languages) must remain html encoded.  Until we support utf8mb4, anyway.

But smf deals with all that...  Give it any valid utf8.  It will encode just what it needs to, & store all the rest.  The function to convert entities will convert all but the 4-byte ones, which must remain encoded.
