### ISSUE TITLE
Should externally loaded scripts and css be receiving an SMF generated query string (seed)

### ISSUE THREAD

**Issue by WhistlingDonkey** [SimpleMachines/SMF#6876]
#### Description
Should externally loaded scripts and css be receiving an SMF generated query string (seed)?

I believe the purpose of the query string is for caching purposes (cache busting) but in my testing so far it's not made any positive difference to that, as the string doesn't change after editing any given file that receives a query string, even after forcing a reload it doesn't change (this applied as well to non externally loaded theme scripts and css). 

What it does negatively do though is prevent some content from being used from the browser cache when the user already has the file in the cache. For example, giving the jQuery library a query string as we do now defeats the purpose of caching it as jquery-3.5.1.min.js?smf21rc4_xxxxxx is different to just jquery-3.5.1.min.js that a user may already have in their cache which could have been used.

I propose we should definitely remove the query string from the jQuery library load, and at least offer a setting to turn off the query string for external files (or even all files) unless explicitly set in the load function.

**Comment by Sesquipedalian** [comment]
I agree that we should not be appending the seed to the jQuery library.

**Comment by Sesquipedalian** [comment]
Please test #6880 to confirm that it solves the issue for you, @WhistlingDonkey.

**Comment by WhistlingDonkey** [comment]
That was quick, I didn't get to finish my (inferior) fix @Sesquipedalian.

#6880 is working fine, and ties in very nicely to my SubResourse Integrity security feature that I've just finished.

**Comment by Sesquipedalian** [comment]
Oops, sorry. Didn't mean to step on your toes. Thanks for both the report and for being willing to work on a fix. 🙂

**Comment by WhistlingDonkey** [comment]
Not a problem, your fix was far better and more elegant than mine was working out to be. I just didn't expect someone else to fix it so quickly after reporting it, things have really ramped up on github lately!
