### ISSUE TITLE
Member Approval inconsistent behaviour

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#688]
As per http://www.simplemachines.org/community/index.php?topic=424036.msg3056979#msg3056979

paleolith described it better than I could, but to sum it up

Approve a member through their profile, it will not offer to send notification of approval.
Approve a member through the admin section, it will make it clear that it's an option.

The profile area should offer the same options as the manage members page does, i.e. approve/approve+email/approve+require activation

**Comment by Oldiesmann** [comment]
I definitely agree.

**Comment by Arantor** [comment]
We should also ensure the appropriate calls to the logAction(s) function is handled if it isn't already, I know this was occasionally an issue in 2.0.

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
