### ISSUE TITLE
Emulate Version missing newer SMF 2.0.x and has SMF 2.1 RC4 Listed twice

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#6883]
Emulate Version missing newer SMF 2.0.x and has SMF 2.1 RC4 Listed twice
Not sure what is the best way to handle new additions to SMF 2.0.x going forward.
But it stop at 2.0.14 right now

Screenshot
![emulateversion](https://user-images.githubusercontent.com/978002/126926049-ccdfcc24-6dd6-49f7-ad1e-2303d867d320.png)

**Comment by jdarwood007** [comment]
The file is served from the site, i've updated it.  Not sure why we are getting the double 2.1 RC4.  Perhaps its because its finding the current SMF version and its not matching.  Need to look into it more.

**Comment by BrickOzp** [comment]
Seems we always add the current version to the list, even if it was already provided by the server
