### ISSUE TITLE
Search never returns more than one page of results

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6884]
#### Description
Search never returns more than one page of results.

The problem is that the total search results used for the paging logic comes from this query:
https://github.com/SimpleMachines/SMF2.1/blob/1d163c4b492f22bc3d92e46c06d5f778a89cd728/Sources/Search.php#L1922
...which I am pretty sure can never exceed max-results-per-page.  So, the paging logic determines you only have one page & will not offer navigation links to other pages.

Looking into alternatives...  

### Steps to reproduce
1. Perform a search with more than results than your max results per page setting under Search | Settings...

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: na
- Database Version: na
- PHP Version: na

**Comment by DiegoAndresCortes** [comment]
is it related to #5978 ?

**Comment by sbulen** [comment]
No, different symptoms.  This one is clearly pagination.  The others are incomplete (zero or 1 instead of 5...).

I was looking into #5978 when I found this...
