### ISSUE TITLE
URL tags change from url to iurl

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#6886]
#### Description
--bbc url tags change from url to iurl when using preview in quick reply, or clicking to modify a post.

### Steps to reproduce
1. post a text url using quick reply, then preview before posting.
2.  Post a text link in either a new topic, or by clicking the reply button.  Then click to modify that post.

### Environment
- SMF 2.1 RC4
- PHP Version: 7.4.21

**Comment by smfbigguy** [comment]
I don't think it should default to iurl to begin with. It should always be url.

**Comment by lurkalot** [comment]
> I don't think it should default to iurl to begin with. It should always be url.

It doesn't default to using iurl, for me,  it only seems to change to iurl when using preview before posting using the quick reply, or if you modify a post.   If you start a new topic, or use the reply button then it's fine and stays as url

**Comment by smfbigguy** [comment]
I use the sceditor all the time so to post a link to a site I press the link button and fill in the two fields. "link" and "Description". Then I post the link. After the post has been posted and I click on the link it does not open in a new tab it opens in the same window. Leading me away from the post and thread I was on.

**Comment by smfbigguy** [comment]
Correction. If I use that button all it does is post the description beside an unclickable link. Once I change the tags from iurl to url it works as intended.

**Comment by lurkalot** [comment]
> Correction. If I use that button all it does is post the description beside an unclickable link. Once I change the tags from iurl to url it works as intended.

And what happens when you modify that post?

**Comment by smfbigguy** [comment]
Once I change the tags from iurl to url it works as intended.

**Comment by smfbigguy** [comment]
What I am saying is they might be coded as iurl and that is why this is happening. I can't see how they would change from url to iurl by pressing post. It could happen I guess, I don't know. :)

**Comment by live627** [comment]
This is a side effect of the increased security in SCEditor v3.0.0. Our tags rely on target=blank, which gets scrubbed with DOMPurify.
