### ISSUE TITLE
BBCodes in search results are not processed properly

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6887]
#### Description

If you request "Show results as messages", and the message contains a quote, that quote is displayed as bbc, and is not formatted.

**_2.1 Search Result Example:_**
![image](https://user-images.githubusercontent.com/23568484/127094495-8dab15dc-2122-4b39-9aee-3e2245654337.png)

**_This is what it looks like in 2.0:_**
![image](https://user-images.githubusercontent.com/23568484/127094592-8a4db605-bb9f-4acf-83ce-9f6a28c29888.png)

**Comment by Sesquipedalian** [comment]
This seems to affect quite a few BBCodes, not just quote.
