### ISSUE TITLE
$params['defer'] and $params['attributes'] not defined

### ISSUE THREAD

**Issue by WhistlingDonkey** [SimpleMachines/SMF#6894]
#### Description
$params['defer'] is not defined in the loadJavaScriptFile function and $params['attributes'] not defined in both the loadJavaScriptFile and loadCSSFile functions, even though the code to use them is functional and defer is actually specified as a parameter for several files

### Environment (complete as necessary)
- Version/Git revision: Github latest

### Additional information/references
I'm using this issue to learn git, before anyone beats me to the punch in getting the fix up.

**Comment by sbulen** [comment]
In case you hadn't seen this:
https://www.simplemachines.org/community/index.php?topic=570117.msg4034855#msg4034855

**Comment by WhistlingDonkey** [comment]
No, I haven't seen it.
Error: The topic or board you are looking for appears to be either missing or off limits to you.

Since I doubt you posted a dud link I'm guessing I don't have enough privileges for the board that topic is in?

**Comment by Sesquipedalian** [comment]
Strictly speaking this isn't a bug—the `!empty()` checks in `template_css()` and `template_javascript()` handle unset variables—but proactively declaring them would be good practice, so go for it. 🙂

**Comment by WhistlingDonkey** [comment]
Another reason I chose this one for learning with, if it didn't matter then it wouldn't be a big deal to throw the work away.

@Sesquipedalian, if $params['attributes'] currently defaults to false now if it hasn't been set when the functions are called and it works fine is there a reason why you indicate it should default to array() instead as in your PR comments? 

I still can't access the topic referenced by @sbulen, even when logged in at SMF forums. Is it something I should know to be able to contribute?

**Comment by sbulen** [comment]
Sorry wrong link...  I think this is correct:
https://www.simplemachines.org/community/index.php?topic=576283.0

**Comment by Sesquipedalian** [comment]
> @Sesquipedalian, if $params['attributes'] currently defaults to false now if it hasn't been set when the functions are called and it works fine is there a reason why you indicate it should default to array() instead as in your PR comments?

Because it doesn't default to `false` now. 

If `$params['attributes']` is not set at all, PHP implicitly considers it to have the value `null`. Otherwise, the expected value for `$params['attributes']` is an array of zero or more key-value pairs indicating extra HTML attributes to set on the `<link>` element. In general, whenever you set a variable to an explicit default value, you should always set it to the expected type of value. In this case, that means setting it to an empty array, not a boolean.

**Comment by WhistlingDonkey** [comment]
@sbulen, thanks. Yes I have seen, read it many times over. Excellent work.

@Sesquipedalian, I am very embarrassed, I should have known that from programming in other languages. I though PHP worked a bit differently in regards to false as I've never seen anyone deliberately set anything to null in PHP before like I have with say c# and no error was thrown. I know I look like a foolish noob right now, and you'd be right to think that but I do have better stuff coming, I promise.

**Comment by Sesquipedalian** [comment]
No worries, @WhistlingDonkey. It's all good. Thanks for taking time to contribute to SMF! 🙂
