### ISSUE TITLE
Missing link for images in attach bbc tag

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#6898]
#### Description
Attach any image and paste it into a post with [attach] tag

### Environment (complete as necessary)
- Version/Git revision: 0f375f1

### Additional information/references
Subs.php, RC4, line 1443:
`$returnContext .= '<img src="' . $currentAttachment['href'] . '"' . $alt . $title . ' class="bbc_img"></a>';`

Subs.php, RC3, line 1479:
`$returnContext .= '<a href="' . $currentAttachment['href'] . ';image" id="link_' . $currentAttachment['id'] . '" onclick="' . $currentAttachment['thumbnail']['javascript'] . '"><img src="' . $currentAttachment['thumbnail']['href'] . '"' . $alt . $title . ' id="thumb_' . $currentAttachment['id'] . '" class="atc_img"></a>';`

**Comment by BrickOzp** [comment]
What is the problem you see? Attached images now behaves as img tag.

**Comment by dragomano** [comment]
I see closing `</a>` without opening `<a>`
