### ISSUE TITLE
New Post in Board jump get empty list

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#6899]
#### Description
When click here:
![grafik](https://user-images.githubusercontent.com/1782906/127809255-67d697e0-ab63-4d2d-be52-8f0f1652d07e.png)
i get empty list:
![grafik](https://user-images.githubusercontent.com/1782906/127809322-77354451-7a65-4c4b-82a4-492ecb17039c.png)
when i got directly i see this new:
![grafik](https://user-images.githubusercontent.com/1782906/127809393-0feba9e2-b19b-4afb-a692-34d67943a123.png)

Is this a wanted behavior?

**Comment by DiegoAndresCortes** [comment]
I get the same behavior in SMF 2.0

**Comment by DiegoAndresCortes** [comment]
If I click on the "Try All unread Topics" link which turns into _unread;all;board=77.0_ it works with the expected behavior (I think)

**Comment by sbulen** [comment]
I am not seeing that, I get brought to new posts for that sub-board.

@albertlast - looks like you are using the Populate tool?  There is an important query at the end that is not pg-friendly and it fails.  Maybe the board isn't fully populated?  See here:
https://github.com/SimpleMachines/tools/issues/48

If you make a pg-version of that query & execute it, does the board then behave properly?

*** Note, I do see these exact symptoms if executed WHILE Populate.php is executing.  I do not see the issue when Populate.php completes properly.  I suspect this is related to the issue referenced above.

**Comment by sbulen** [comment]
Example:
![image](https://user-images.githubusercontent.com/23568484/127908362-dda0e582-3fde-4da1-a869-0f956a4da936.png)
Gave me this:
![image](https://user-images.githubusercontent.com/23568484/127908393-7088bcdf-84a9-49a1-91e0-00fe664bde2c.png)


But a few minutes later, gave me this:
![image](https://user-images.githubusercontent.com/23568484/127908440-4ac46c66-e818-438e-81d8-8a947fe0df84.png)


So I suspect Populate.php is not working & that 2.1 is fine here.

**Comment by albertlast** [comment]
> If you make a pg-version of that query & execute it, does the board then behave properly?

no change of behavior.

**Comment by sbulen** [comment]
Do you see this behavior on a board not populated with Populate.php?

**Comment by albertlast** [comment]
didn't got one

**Comment by sbulen** [comment]
_Before testing any further on that particular test env, I would mark all messages as read & ensure all the NEW flags go away.  You need to make sure you're looking at real behavior & not fallout from Populate.php._

Did you use the browser BACK key, or navigate back to the board index?  Big difference...
