### ISSUE TITLE
Adds DNS prefetch to SMF

### ISSUE THREAD

**Issue by WhistlingDonkey** [SimpleMachines/SMF#6912]
DNS-prefetch and DNS-preconnect can help with page load times by having the browser attempt to pre resolve domain names and pre connect to a domain for a resource before the resource is requested in the DOM build.  dns-prefetch and dns-preconnect can be specified as a link rel's in the document head or as a HTTP header. The PR attached to this issue enables dns-prefetch to be set via the link rel method in SMF. Preconnect is not implemented in this PR.

In it's default out-of-the-box form, SMF would only have one resource that could potentially benefit from dns-prefetch, being the jQuery library but if a user has content or assets that they pull in from elsewhere, for example if they have a gallery and pull it's contents in from say flickr or similar or they pull in fonts from Google (instead of having them locally) it could certainly help.

https://developer.mozilla.org/en-US/docs/Web/Performance/dns-prefetch

**Comment by albertlast** [comment]
the problem is the different kind of external sources,
like jquery which (when active external source active) called every page, so easy to add
other kind like gallery content is only needed when the user is context where this is needed for example when he look into a topic,
but elsewhere like board index this prefetch/preconnect is not needed to a gallery cdn.

**Comment by WhistlingDonkey** [comment]
You are correct in regards to something like a gallery but we'd have to have some sort of check of what prefetch or preconnect link gets sent for which topic, which would likely become a nightmare very quickly. It's also one of the reasons why I haven't done preconnect yet, a DNS lookup with dns-prefetch for something that's not required on a particular page isn't a massive deal, a useless connection with preconnect is a different matter.

Gallery was a poor choice for an example.  I was thinking along the lines of resources that get pulled in on every page, like jQuery, webfonts (if the user is using them), images that appear on every page.

**Comment by albertlast** [comment]
Ende of the day is that maybe an admin choice,
To decide which url needs to pre dns and connect -> would allow to do both,
He needs to know if this right or not

**Comment by WhistlingDonkey** [comment]
I can't figure out how to actually link the PR to this issue (instructions on github don't work) so I'm using these mentions
#6906

**Comment by WhistlingDonkey** [comment]
Update. completely updated by last commit. Now includes preconnect.

**Comment by WhistlingDonkey** [comment]
Closing this issue. I'm not happy with the Pull request and have come up with a better way.
