### ISSUE TITLE
It needs to be easier to fix missing smf_smiley_files data

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6918]
#### Description
From the forum:
https://www.simplemachines.org/community/index.php?topic=578392.0

Here's the background as I understand it...  The smiley url/directory settings were incorrect before running the upgrader.  So, the upgrader could not find any smileys to add, leaving smf_smiley_files empty after the upgrader ran.  

Here's the problem:  There is now no filename information anywhere at all.  _And as near as I can tell, no way to correct this in the UI._  The UI assumes you have smf_smiley_files populated for at least one set.

The initial smileys are there in smf_smileys.  Thus, you cannot manually add them, they get reported as duplicates...  Even though smf_smiley_files is empty.

I could not find any way in the UI to populate smf_smiley_files.  

Maybe I'm missing something???

The only way I could find to fix this was to import smf_smiley_files data from a working forum.  Once smf_smiley_files was properly populated for one set, adding any other existing smiley sets worked fine.  But that first set requires a DB import.

### Steps to reproduce
1. Put invalid values in for the smiley url and directory in a 2.0 DB.
2. Run the upgrader.
3. smf_smiley_files is now empty.
4. Attempt to correct...

### Environment (complete as necessary)
- Version/Git revision: Current 
- Database Type: na
- Database Version: na
- PHP Version: na

**Comment by Sesquipedalian** [comment]
It looks like I caused this in 0cbb279f1f when I used `JOIN` instead of `LEFT JOIN` in a few queries.
