### ISSUE TITLE
Mismatched HTTP header options for reverse proxy servers (e.g. Cloudfare)

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#6922]
The individual options for the `proxy_ip_header` setting do not coincide with the headers supported by the `autodetect` option.

The individual options are:
https://github.com/SimpleMachines/SMF2.1/blob/5356c2da692de9289ff052898743ab9d61a8cd20/Sources/ManageServer.php#L651-L659

But when `autodetect` is selected, the headers we try to detect are:
https://github.com/SimpleMachines/SMF2.1/blob/5356c2da692de9289ff052898743ab9d61a8cd20/Sources/QueryString.php#L276

This raises two questions:
1. Is there a reason why `HTTP_X_REAL_IP` isn't included in the autodetect list?
2. Shouldn't `CF-Connecting-IP` be `HTTP_CF_CONNECTING_IP`?

@jdarwood007

**Comment by jdarwood007** [comment]
I'm not sure why, git blame doesn't have me on here.  But CF-Connecting-IP would be from a ClareFlare system while the others are standard headers used by other proxies.

**Comment by Sesquipedalian** [comment]
> I'm not sure why, git blame doesn't have me on here.

It's just that the lines in question were most recently modified by a whitespace and formatting cleanup.

>But CF-Connecting-IP would be from a ClareFlare system while the others are standard headers used by other proxies.

Yes, but PHP will store the value of the raw `CF-Connecting-IP` header in `$_SERVER['HTTP_CF_CONNECTING_IP']`. 

Perhaps what we should do in ManagerServer.php is this:
```
 	array( 
 		'disabled' => $txt['setting_proxy_ip_header_disabled'], 
 		'autodetect' => $txt['setting_proxy_ip_header_autodetect'], 
 		'HTTP_X_FORWARDED_FOR' => 'X-Forwarded-For', 
 		'HTTP_CLIENT_IP' => 'Client-IP', 
 		'HTTP_X_REAL_IP' => 'X-Real-IP', 
 		'HTTP_CF_CONNECTING_IP' => 'CF-Connecting-IP' 
 	) 
```
