### ISSUE TITLE
Autodetecting reverse proxies doesn't respect $modSettings['proxy_ip_servers']

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#6923]
5b828d1 replaced this:
https://github.com/SimpleMachines/SMF2.1/blob/8487407d28e4f71c605827b87601a20b5066f0b6/Sources/QueryString.php#L250-L251
... with this:
https://github.com/SimpleMachines/SMF2.1/blob/5b828d187e58699dc3b5ad6177fe31ae0bae6e9c/Sources/QueryString.php#L250-L255

This appears to be broken logic, because the `continue` statement only continues the inner `foreach (explode(',', $modSettings['proxy_ip_servers']) as $proxy)` loop, rather than the outer `foreach ($reverseIPheaders as $proxyIPheader)` loop.

Assuming I understand the intended logic here, the simple fix would be to change line 254 from `continue;` to `continue 2;` so that the outer loop is affected.

This bug might explain the comment made [here](https://github.com/SimpleMachines/SMF2.1/pull/5732#issuecomment-893541702), but @mastum will need to provide more details in a separate issue report before that can be determined for certain.

@jdarwood007

**Comment by jdarwood007** [comment]
There would need to be a bit more logic here. Continue 2 won't fix this.

The updated logic just allows us parse reverse proxy servers better by using cidr logic.  Which for giants like CloudFlare and others, is going to be needed to get the proper list of IPs to trust from CloudFlare.  Such as from this list: https://www.cloudflare.com/ips/

So the correct thing to do is when we find the REMOTE_ADDR is inside a valid CIDR, that we can trust the header sent by that client to contain the clients real ip.  If it does not match the REMOTE_ADDR inside any CIDR, then it can not be trusted.

I think adding a $valid_sender = false; and then if we match, we set to $true and continue.  Then we check later if $valid_sender isn't true to continue again.

Something like this I think
```
		if (!empty($modSettings['proxy_ip_servers']))
		{
			$valid_sender = false;

			foreach (explode(',', $modSettings['proxy_ip_servers']) as $proxy)
				if ($proxy == $_SERVER['REMOTE_ADDR'] || matchIPtoCIDR($_SERVER['REMOTE_ADDR'], $proxy))
				{
					$valid_sender = true;
					continue;
				}

			if (!$valid_sender)
				continue;
		}
```

**Comment by Sesquipedalian** [comment]
The inner continue could probably be a break, since we don't need to perform any further tests once we've validated the sender, but otherwise this looks good to me.
