### ISSUE TITLE
SMF file caching is messed up

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#693]
At some point previously in the dev cycle, the move was made to pull the cache parameters to Settings.php, which makes sense - means they can be used even to cache the $modSettings values.

Only it doesn't look like it was done completely... I see plenty of uses of $modSettings['cache_enable'] that need looking at.

**Comment by emanuele45** [comment]
Just in case you missed it:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/ManageServer.php#L407
;)

**Comment by Arantor** [comment]
Um, so the two are kept in sync. I still don't get why $cache_enable wasn't used everywhere.

**Comment by emanuele45** [comment]
No idea, maybe it was faster like that...

**Comment by Arantor** [comment]
I can't imagine a situation where it would be faster.

**Comment by emanuele45** [comment]
I meant faster to do. :innocent:

**Comment by Arantor** [comment]
That's the point, I can't see how it could be faster. OK, so you have to bring a variable into scope, sure, but the cost of calls to that variable once in scope should be cheaper than looking up an entry in the hashtable for $modSettings.

**Comment by emanuele45** [comment]
Probably another misunderstanding: it was a faster change to apply. Nothing to do with execution time, just with practical implementation of the new behaviour. ;)

And, backward compat with mods (since at the time it was one of the most important points): both in terms of expected variables in scope and expected characters in a certain position.

**Comment by Arantor** [comment]
Ahhhhh, I see now.

**Comment by deliciousbamboo** [comment]
So is this a bug or not or other? Does this thing work or is it "messed up" as the title states?

**Comment by Arantor** [comment]
Well, it would appear that it is not a bug but a word in progress that was left as it was by people who worked on the repository before I did, which at a glance did appear to be messed up - but after the conversation it wasn't. Misunderstandings do happen when dealing with 100k+ lines of code.

**Comment by deliciousbamboo** [comment]
was wanting to take a look if it was a problem, want to figure out if I can help here or no

**Comment by Arantor** [comment]
Quite frankly given your attitude, I'm not sure we'd actually _want_ your help.

**Comment by deliciousbamboo** [comment]
I see .. I though tis was an OS project that wanted people to join, even if they had a different view, guess not, thanks for being clear.

**Comment by Arantor** [comment]
Oh, people helping is fine. People jumping in, commenting on issues they even admit they don't understand (cf $smcFunc['htmlspecialchars']) and generally being unpleasant is not fine.

To contribute does imply working as a team and all you're doing is spreading bile.

**Comment by deliciousbamboo** [comment]
your being most unpleasant, why you on team?

**Comment by Arantor** [comment]
Ask the rest of the team, they'd tell you I wasn't particularly unpleasant. On the other hand, coming here and spreading bile straight off the bat - over a misunderstanding - and you wonder why I'm getting defensive.

How would you feel if the situation was reversed and I came to your project and acted how you have?

I think this discussion is futile, please stop this.

**Comment by deliciousbamboo** [comment]
> I think this discussion is futile, please stop this.

insult again and then say stop,  so you can have final word ... so far "team" call me troll, puppet and bile .. team did the wrong thing.

**Comment by Arantor** [comment]
What were we supposed to do? We admit we made a mistake, and we rectified it. Everything else has been about responding to your less than pleasant commentary.

**Comment by NanoSector** [comment]
If this is a work in progress, any idea where the person/people was/were working before they dropped it?

**Comment by Arantor** [comment]
Basically if you read everything up to before deliciousbamboo's comment, it's totally clear where things got to: not breaking backwards compatibility.

**Comment by AngelinaBelle** [comment]
Is this messed up or is it working as designed? 
Does this need something fixed, should it be closed?

**Comment by Oldiesmann** [comment]
It's not technically "broken" as this doesn't break anything, but it's something we should fix, if for nothing more than consistency. If we've got a variable in Settings.php that specifies whether caching is enabled, we should use it instead of relying on $modSettings['cache_enable'] everywhere (though I don't know if we can or even should get ride of $modSettings['cache_enable'] altogether - that's something that needs a bit more research).

**Comment by illori** [comment]
you mean something like this?

```
/**
 * The level at which you would like to cache. Between 0 (off) through 3 (cache a lot).
 * @var int
 */
$cache_enable = 1;
```

which is in Settings.php

**Comment by Arantor** [comment]
For bonus points, you need to have it in Settings.php because $modSettings is cached.
