### ISSUE TITLE
8: Undefined index: jquery_source - Load.php line 2476

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#6938]
#### Description
From the forum, & confirmed:
https://www.simplemachines.org/community/index.php?topic=578482.0
![image](https://user-images.githubusercontent.com/23568484/129451903-4421daf5-2e88-499d-9026-e99b7ef1da4d.png)

Two other notes:
1) I suggest the default be 'Local'.  SMF should be self-contained as much as possible.  Plus, we need to account for the fact that some folks install on internal networks, closed off from internet access. 
2) If you go pull up the settings, the form is a little wonky.  Normally the 'custom URL' field is only enabled when 'custom' is selected, but with no values initialized, it shows 'Google CDN' and the field is enabled.
![image](https://user-images.githubusercontent.com/23568484/129453035-c22cd941-be66-469a-bd0a-3092bf3d9b8d.png)

### Steps to reproduce
1. Install current GH

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: na
- Database Version: na
- PHP Version: na

**Comment by Sesquipedalian** [comment]
Needs an `isset($modSettings['jquery_source']` at the start of the condition test.

**Comment by sbulen** [comment]
Yes, we need to set a proper default somewhere - I think it should be 'Local'.  I modified the above to include a couple additional observations.

**Comment by WhistlingDonkey** [comment]
Correct, I missed the isset as I already had the jquery_source set. I have a fix.

Also related, jquery_custom is not disabled when jquery_source is not set. I have fix for that too.

**Comment by sbulen** [comment]
I have sub'd a PR.  Feel free to use  it or not!  Note it addresses all 3 issues noted above.

**Comment by WhistlingDonkey** [comment]
hmm, can't edit previous post. Sesquipedalian and I had a conversation about local and cdn as the default. It was changed to local as default when I did the change but it was decided that a cdn was the best case for most scenarios, but in the light of what you say, perhaps local is the better default.

**Comment by WhistlingDonkey** [comment]
Apologies sbulen, I did not see that you had submitted a pr already.
