### ISSUE TITLE
Email activation then admin approval

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#694]
The ability to set things up so that even in admin approval, users have to validate their email first even before being pushed to admin approval.

This would be an additional option in the list of registration modes.

**Comment by DannyCork** [comment]
>????

**Comment by jasonclemons** [comment]
I would honestly rather see it the other way around.
1. User registers, registration gets sent to admin for approval
2. Admin approves/denies registration request
3. If approved, user is sent an email informing them of activation, and to verify email address
4. Account is fully activated after email verification

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
