### ISSUE TITLE
Memory limit breaks upgrader

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6941]
#### Description
When the upgrade reaches this step: Upgrading post notification settings
It can fail and stop the upgrade.

The forum has a large number of members and the individual php process limit is set to 128M of memory.

The upgrade was ran via command line: php upgrade.php

### Steps to reproduce
1. Have a high number of members (500k+)
2. Have PHP set to 128M
3. Run upgrade.php via command line: php upgrade.php
4. Upgrade bails out at step: Upgrading post notification settings

### Environment (complete as necessary)
- Version/Git revision: latest
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 7.4

### Additional information/references
Bumping the memory limit to 512 fixes this.

**Comment by BrickOzp** [comment]
The limit for the sub steps is set to 100 000.
Lowering it to 25 000 will probably solve this.
