### ISSUE TITLE
Attachments failed eval

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6942]
#### Description
During a CLI upgrade.  The upgrader crashed.  Restarting the upgrade resulted in this:

```
 *  +++  Adding more space to the mime_type column. done.
 +++  Converting legacy attachments.Error: Trying to access array offset on value of type bool File: /upgrade.php(2148) : eval()'d code Line: 65Error: Trying to access array offset on value of type bool File: /upgrade.php(2148) : eval()'d code Line: 65
```

As a temp patch, the following code was used in upgrade.php
```
				try
				{
					if(@eval('global $db_prefix, $modSettings, $smcFunc, $txt, $upcontext, $db_name; ' . $current_data))
						throw new ErrorException('eval error');
				}
				catch (Throwable $e) {
					$upcontext['error_message'] = 'Error in upgrade script ' . basename($filename) . ' on line ' . $line_number . '!' . $endl;
					if ($command_line)
						echo $upcontext['error_message'];
				}
				catch (ErrorException $e) {
					$upcontext['error_message'] = 'Error in upgrade script ' . basename($filename) . ' on line ' . $line_number . '!' . $endl;
					if ($command_line)
						echo $upcontext['error_message'];
				}
```

This let it continue.  But the original issue still exists.  There is nothing on that step that would eval on line 65 that results in a bool.

More research and testing will be needed.

This bug report essentially is two issues.

First is, we should have that try/catch, but disable it by default.  Its way late in 2.1's process to introduce that with little testing.  But by having it in there but disabled, we can have support enable it for upgrade issues if needed.

The second issue is why the attachments are failing or erroring out.

### Environment (complete as necessary)
- Version/Git revision: latet git
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 7.4

### Additional information/references

**Comment by BrickOzp** [comment]
I think line 65 of "Converting legacy attachments" corresponds to line 450 of upgrade_2-1_mysql.sql

$currentFolder = !empty($modSettings['currentAttachmentUploadDir']) ? $modSettings['attachmentUploadDir'][$row['id_folder']] : $modSettings['attachmentUploadDir'];

Either $modSettings or $row is null/false.

According to https://stackoverflow.com/questions/59674903/trying-to-access-array-offset-on-value-of-type-bool-in-php-7-4 this warning was introduced in php 7.4

if the query returns no rows mysqli_fetch_assoc will return null, but then it should not enter the while loop.
From what I can see $modSettings is always created as an array.

**Comment by sbulen** [comment]
Can this be reproduced at will?  Do we know what the problem is?

I cannot reproduce - and I have run LOTS of upgrades...  It would help to know what the issue is here.  Seems to me to be an odd edge case...

**Comment by sbulen** [comment]
Question: Did you have multiple attachment directories?

I have some ideas & am about to attempt to reproduce.

BrickOzp is correct on the line #.

**Comment by jdarwood007** [comment]
Yes.

**Comment by sbulen** [comment]
Pretty sure I understand the issue.  

If execution got past the "Fixing attachment directory setting..." step, then attachmentUploadDir is already converted to json:
https://github.com/SimpleMachines/SMF2.1/blob/9cf0a6e4a734fdb81eaffb7d722e37d157ef7278/other/upgrade_2-1_mysql.sql#L595

So...  If the upgrader failed after this and was subsequently restarted, then the unserialize would return **_false_** here:
https://github.com/SimpleMachines/SMF2.1/blob/9cf0a6e4a734fdb81eaffb7d722e37d157ef7278/other/upgrade_2-1_mysql.sql#L424

So, when referenced here as an array:
https://github.com/SimpleMachines/SMF2.1/blob/9cf0a6e4a734fdb81eaffb7d722e37d157ef7278/other/upgrade_2-1_mysql.sql#L450
...you get that "Trying to access array offset on value of type bool" error.

Two fixes needed:
 - Leave the serialize_to_json conversion to the serialize_to_json step.  No need to do it twice.
 - Stop using json_done as a "have I done this step before" flag for steps that come much earlier than serialize_to_json... 

As an aside, it is also converted to json in the serialize_to_json step:
https://github.com/SimpleMachines/SMF2.1/blob/9cf0a6e4a734fdb81eaffb7d722e37d157ef7278/other/upgrade.php#L3454

I always wondered why the conversion to json always fails during that step for attachmentUploadDir - yet it is properly formed json.  This is from a CLI execution:
![image](https://user-images.githubusercontent.com/23568484/147866654-afe91b05-73c6-46dc-8a5f-8c17a4853a86.png)

Getting rid of the earlier json_encode will fix this as well.

I don't think a try/catch is going to add anything?  Note our existing error handler is what produced the string: "Error: Trying to access array offset on value of type bool File: /upgrade.php(2148) : eval()'d code Line: 65".  We already have the error message & the line of code.

**Comment by sbulen** [comment]
I was able to reproduce this  PR sub'd.
