### ISSUE TITLE
MySQLConvertOldIp fails with invalid IPs

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6945]
#### Description
If a IP contains any of these.  The conversion process gets stuck in a loop

172.16.60.132,
 10.0.32.24
192.168.0.33, 1

The second one has a space at the start

**Comment by jdarwood007** [comment]
FYI.  During my upgrade process I just used a TRIM to fix the spaces.  But the other two I corrected manually.

**Comment by jdarwood007** [comment]
The trim issue causes the most failures.

That should be fixed with:
```
			$arIp[$i] = trim($arIp[$i]);

			if (!filter_var($arIp[$i], FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 | FILTER_FLAG_IPV6))
				continue;

			$updates['ip' . $i] = $arIp[$i];
			$cases[$arIp[$i]] = 'WHEN ' . $oldCol . ' = {string:ip' . $i . '} THEN {inet:ip' . $i . '}';
```

To:

```
			if (!filter_var($arIp[$i], FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 | FILTER_FLAG_IPV6))
				continue;

			$updates['ip' . $i . '_org'] = $arIp[$i];
			$updates['ip' . $i . '_clean'] = trim($arIp[$i]);
			$cases[$arIp[$i]] = 'WHEN ' . $oldCol . ' = {string:ip' . $i . '_org} THEN {inet:ip' . $i . '_clean}';
```

I haven't fixed the invalid IPs yet.  That should be a regex match on the filter_var if it fails and if that fails, force it to continue.

**Comment by sbulen** [comment]
I am not seeing what you are seeing at all...  It is like your filter_var() is failing entirely.  

E.g., this little program:
```
<?php
$input = array(
    '1.1.1.1',
    '1.1.1.1 ',
    ' 1.1.1.1',
    '1.1.1.1,',
    ',1.1.1.1',
    '1.1.1.1,1',
    '1.1.1.1, 1',
    '1:1:1:1:1:1:1:1',
    '1:1:1:1:1:1:1:1 ',
    ' 1:1:1:1:1:1:1:1',
    '1:1:1:1:1:1:1:1,',
    ',1:1:1:1:1:1:1:1',
    '1:1:1:1:1:1:1:1,1',
    '1:1:1:1:1:1:1:1, 1',
);

foreach($input as $ip)
{
    $result = filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 | FILTER_FLAG_IPV6);
    echo '"' . $ip . '": ';
    echo $result ? 'true' : 'false';
    echo '<br>';
}
?>
```

Returns this:
```
"1.1.1.1": true
"1.1.1.1 ": false
" 1.1.1.1": false
"1.1.1.1,": false
",1.1.1.1": false
"1.1.1.1,1": false
"1.1.1.1, 1": false
"1:1:1:1:1:1:1:1": true
"1:1:1:1:1:1:1:1 ": false
" 1:1:1:1:1:1:1:1": false
"1:1:1:1:1:1:1:1,": false
",1:1:1:1:1:1:1:1": false
"1:1:1:1:1:1:1:1,1": false
"1:1:1:1:1:1:1:1, 1": false
```

All leading/trailing spaces, commas, numbers, etc., all return false.  

**_No trim, etc., should be necessary._**

This feels to me like a php config error?

**Comment by jdarwood007** [comment]
I realized that it should be because sooner or later you get an entire batch of bad addresses and the while loop gets stuck.  So we need to clean up the data if we can or if we can't, we need to skip past it better.

I would have to look into that again

**Comment by sbulen** [comment]
This sounds like a very familiar discussion - didn't a fix for the 'what if they're all bad' IPs go in?

Hmmm...

**Comment by sbulen** [comment]
I think we need to set the funky IPs to '', so they are skipped on subsequent queries.  We can't just continue.  the query already skips ''.

**Comment by jdarwood007** [comment]
That may be best.  We are trying our best to fix them.  Although since they are IPv4, we can do our best to try and "handle them better by doing a dumb regex match for the 4 sets of numbers.

The suggested idea to split _org and _clean will help here, because if we can clean up and get a valid IP, we need to match against the dirty IP (the original) and pass the cleaned version into inet.

**Comment by sbulen** [comment]
@jdarwood007 - FYI - I've been looking into this.  I expect to submit a PR soon.
