### ISSUE TITLE
Serialize to json slow

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6947]
#### Description
Serialize to json is very slow.  On average is 50 every second it converts.  On large forums.  This is horribly slow.

This may not be a bug, but something we want to analyze for performance

```
								$temp = @safe_unserialize($row[$col]);

								// Maybe we can fix the data?
								if ($temp === false)
									$temp = @safe_unserialize(fix_serialized_data($row[$col]));

								// Maybe the data is already JSON?
								if ($temp === false)
									$temp = smf_json_decode($row[$col], true, false);
```

We should run this code block through 1,000 iterations, divide by time and get the average time taken.  Then see if we can optimize it.

Could we combine fix_serialized_data and safe_unserialize together to reduce the times we unserialize data?

Do we want to skip smf_json_decode and use native json_decode?  We use smf_json_decode to future proof ourselves to handling any data issues.  We could forgo that for the upgrader and deal with it differently if needed.

**Comment by albertlast** [comment]
https://github.com/SimpleMachines/SMF2.1/blob/1533251e538b5c3fca01064d59802bfac1d49c24/other/upgrade.php#L3614-L3622

**Comment by jdarwood007** [comment]
https://gist.github.com/jdarwood007/9ec1c704f8eb61b76999a3365603c344

@albertlast You where interested in this as well.

Testing for valid string - Time taken:0.40983104705811
Testing for invalid string - Time taken:1.0849678516388
Testing for JSON string - Time taken:0.063544988632202
Testing for valid string with NEW - Time taken:0.4165620803833
Testing for invalid string with NEW - Time taken:0.4167811870575
Testing for JSON string  with NEW - Time taken:0.055032968521118

I'm not seeing it in a test here.  So I can't explain our slow 50 rows a second processing time on this.

But with a change to the fix_serialized_data, I capture the result of serialize attempt.  If it came out as a non false, we simply return that.   If not, we work with it, try again and then return that result.  Rather than try it 4 times to decode through testing.
