### ISSUE TITLE
Undefined index: approved

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6948]
#### Description
When changing the topic icon via ajax action the response from the server is:

```
<br>
<strong>Notice</strong>: Undefined index: approved in <strong>/Sources/Subs-Post.php</strong> on line <strong>2348</strong><br><?xml version="1.0" encoding="UTF-8"?>
<smf>
	<message id="msg_4094047">
		<modified><![CDATA[&#171; <em><span class="lastedit">Last Edit</span>: <strong>Today</strong> at 11:50:56 by SleePy</em>&#187;]]></modified>
	</message>
</smf>
```

I can't reproduce on a test forum though.

Changing this
```
	if ($msgOptions['send_notifications'] && $msgOptions['approved'] && (!empty($msgOptions['quoted_members']) || !empty($msgOptions['mentioned_members'])))
```

to this

```
	if ($msgOptions['send_notifications'] && !empty($msgOptions['approved']) && (!empty($msgOptions['quoted_members']) || !empty($msgOptions['mentioned_members'])))
```

**Comment by BrickOzp** [comment]
I guess you click on the topic icon in a topic, a list with all available icons are shown.

When I do this on my test forum I get a 500 error with this error message: "The database value you're trying to insert does not exist: var_body".

**Comment by BrickOzp** [comment]
When the other problem was fixed, I could reproduce this.
However I only get the error in the error log, and not in the response.
