### ISSUE TITLE
Slow stats query

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6954]
#### Description
```
            SELECT COUNT(*) AS total_members, gender
            FROM (
               SELECT mem.id_member, COALESCE(t.value, 'None') AS gender
               FROM smf_members AS mem
               LEFT JOIN smf_themes AS t ON (
                  mem.id_member = t.id_member AND
                  t.variable = 'cust_gender' AND
                  t.id_theme = 1
                  )
               WHERE is_activated = 1
            ) AS a
            GROUP BY gender
         ORDER BY null
   in /Sources/Stats.php line 192, which took 10.86450696 seconds at 0.08292794 into request.
```

id | select_type | table | partitions | type | possible_keys | key | key_len | ref | rows | filtered | Extra
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | SIMPLE | mem |   | ref | is_activated | is_activated | 1 | const | 278193 | 100.00 | Using index; Using temporary
1 | SIMPLE | t |   | eq_ref | PRIMARY,ID_MEMBER | PRIMARY | 96 | const,forum.mem.id_member,const | 1 | 100.00 | Using where

**Comment by albertlast** [comment]
when the "LEFT" is removed the pk index of themes table is used in pg,
maybe should every user had somekind of gender information in themes table?
