### ISSUE TITLE
Gender stats labels

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6955]
#### Description
This is happening on sm website

Gender stats:None: 430266
Male: 11011
Female: 1418
{gender_2}: 5
{gender_1}: 23

**Comment by wintstar** [comment]
Look here https://github.com/SimpleMachines/SMF2.1/issues/6435#issuecomment-782948795

**Comment by jdarwood007** [comment]
I think that will get us started.  But the second problem exists with the old legacy names and the new custom profile field names.   They either need merged in the upgrade process, or we fix the code to handle both.

**Comment by Sesquipedalian** [comment]
This is a bug in the upgrader.

This line sets the options for the gender field to translatable tokens:
https://github.com/SimpleMachines/SMF2.1/blob/3b5644a7aad411d6101f0c78b2d9ffd7f4fad5cd/other/upgrade_2-1_mysql.sql#L1371

But this block of code sets the migrated values to literal English strings:
https://github.com/SimpleMachines/SMF2.1/blob/3b5644a7aad411d6101f0c78b2d9ffd7f4fad5cd/other/upgrade_2-1_mysql.sql#L1439-L1453

The fix will be to change the second block to use the translatable tokens.

**Comment by wintstar** [comment]
Also check the change in Themes/default/Stats.template.php. During my test of the new funtion tokenTxtReplace($string) this was necessary.

https://github.com/SimpleMachines/SMF2.1/issues/6435#issuecomment-782948795

**Comment by Sesquipedalian** [comment]
@jdarwood007: To fix this on simplemachines.org, run the following SQL queries:
```
UPDATE {db_prefix}themes
SET value = '{gender_0}'
WHERE variable = 'cust_gender'
AND value = 'None';
UPDATE {db_prefix}themes
SET value = '{gender_1}'
WHERE variable = 'cust_gender'
AND value = 'Male';
UPDATE {db_prefix}themes
SET value = '{gender_2}'
WHERE variable = 'cust_gender'
AND value = 'Female';
```

**Comment by jdarwood007** [comment]
Appears since I modified the custom profile field, it reset everyone to the default.  So no fixing that unless I want to pull from backups.  Which honestly for this, doesn't seem worth it.
