### ISSUE TITLE
Notification settings reset after upgrade

### ISSUE THREAD

**Issue by LiroyvH** [SimpleMachines/SMF#6956]
Not sure if intentional, but have noticed that upon upgrading from 2.0 to 2.1 (smorg), all the notification settings have been reset. For example, receiving an email for new Personal Messages seems to be disabled now; even if it was *enabled* in 2.0.
It also seems to disable notifications for paid subscriptions by default, which it probably should enable by default.

**Comment by BrickOzp** [comment]
Confirmed that "email for new Personal Messages" setting is not migrated

**Comment by BrickOzp** [comment]
In 2.0 the pm_notify setting is stored in the members table in the alert_pm_new column. 0 = never, 1 = always, 2 = Only for buddies

In 2.1 the settings are stored in the user_alerts_prefs table.
"When I receive a new personal message" - pm_new - 0 = off, 2 = on
"If enabled, e-mail alerts for" - pm_notify - 1 = All members, 2 = Buddies only

**Comment by m4z** [comment]
Was this closed by accident? The PM issue is only one part of the problem, right?

For reference: https://www.simplemachines.org/community/index.php?topic=584199.0

**Comment by sbulen** [comment]
I suggest writing up a new issue if some symptoms still remain.

**Comment by sbulen** [comment]
See also #7652
