### ISSUE TITLE
Quote selected text inserts a second quote with gibberish

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#6960]
I tried out this on SM Site and when clicking on the _quote selected text_ it inserts the correct quote plus an extra quote with some random text.

Sometimes it inserts the rubbish quote **before** the good one, and sometimes **after**.

e.g.
`[quote author=Gary link=msg=4094098 date=1629206116]announced[/quote]
[quote author=Gary link=msg=4094098 date=1629206116]Well, you say that but way back in the day SM.org ran 2.0 when it was still in alpha and before 2.0 itself was even announced, mindsets have changed over the years. [/quote]
`

**Comment by BrickOzp** [comment]
I did see this once on smf.org, but tried maybe 50 times after that and it worked.
How often do you see this problem?

**Comment by DiegoAndresCortes** [comment]
It happens consistently for me, using firefox btw.

**Comment by Sesquipedalian** [comment]
Is this only happening on simplemachines.org, or does it happen elsewhere too?

**Comment by DiegoAndresCortes** [comment]
Happens on my test site too, I found out how to reproduce it too.
This behavior only happens when you double click to select the text, if you manually select it, works as expected.

Additionally, it won't show the option to quote text if you manually select, but your cursor is not a text pointer yet.

**Comment by BrickOzp** [comment]
Figured out how to reproduce.

Select some part of the message.
Do a new selection in the same message. 
Click the "quote selected text"-button.
You get both the texts you selected as quotes.

You can actually do as many as you like.
