### ISSUE TITLE
Preview won't load when inserting attachment in the post

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#6961]
Ref: https://www.simplemachines.org/community/index.php?topic=578516.msg4094198#msg4094198

When I upload an attachment and then insert in the post, preview won't load.

**Comment by WhistlingDonkey** [comment]
It's working fine for me on my test forum (github latest). Could the problem be what they've implemented on simplemachines.org? I haven't tested there myself but I don't ever recall having this issue on my test forum..

**Comment by BrickOzp** [comment]
It works on my test forum as well.
On smf.org it will give a 500 error if there is an attachment in the message.

**Comment by WhistlingDonkey** [comment]
Can replicate the issue. I had noticed before that cron was giving a 500 internal server error on smf.org. When you mentioned the 500 error on message preview I renamed cron.php and tested. Result: No more image in the preview. This is an issue on the smf.org server.

**Comment by WhistlingDonkey** [comment]
Scratch that, I don't know what just happened but now it works without cron. :(

**Comment by jdarwood007** [comment]
Can you guys try again?  @WhistlingDonkey I don't know your SM profile link.  Can you send it?
I will check the error logs and see if anything is captured for your profile.

**Comment by DiegoAndresCortes** [comment]
I just tried on mobile and ran into that the issue

**Comment by BrickOzp** [comment]
Still gives 500 from desktop as well

**Comment by jdarwood007** [comment]
I'm not getting anything in the logs for any of you generating any errors.

**Comment by WhistlingDonkey** [comment]
Looking at the headers there doesn't seem to be anything out of the ordinary different between my test server and simplemachines.org. I did notice two other things testing sm.org today:

1. The delete attachment button doesn't seem to work (so there is probably an attachment without a post on simplemachines.org now).
2. If inserting an existing attachment the preview states "You cannot see attachments on this board.".
3. cron is working now and not returning a 500 error.

@jdarwood007, did you get my PM over at simplemachines? I had let you know my SM profile there as I was logged in there at the time. If you didn't, SM profile is Chief of Nothing.
