### ISSUE TITLE
Bug?  $txt['custom_avatar_dir_wrong']

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#6972]
https://github.com/SimpleMachines/SMF2.1/blob/f2b2a910a700455b6813495f5648cb712b413dca/Themes/default/languages/Admin.english.php#L474

Is this a bug. In the language string is **custom_avatar_dir**  defined. Wouldn't the text then have to contain custom_avatar_dir.

`$txt['custom_avatar_dir_wrong'] = 'The custom avatars directory is not valid. This will prevent avatars from working properly.';`

**Comment by BrickOzp** [comment]
What do you mean by "In the language string is custom_avatar_dir defined"?

**Comment by wintstar** [comment]
`'custom_'

This custom in the $txt string. 
If there is custom in the $txt string, it should also be custom in the text. So instead of avatar dir, custom avatar dir. Or Not?

**Comment by DiegoAndresCortes** [comment]
Any other strings similar to this? Could be that it was added in case the custom dir needed a different description but seems it's not the case.

**Comment by wintstar** [comment]
There are 2 avatar directories => avatars + custom_avatar. Which one is meant by this text string? avatars or custom_avatar. After text string $txt['custom_avatar_dir_wrong'] it should be **custom_avatar**_dir_wrong. The text only says **Avatars directory**.
Now the question is? directorie avatars or directorie custom_avatar?

**Comment by BrickOzp** [comment]
I would say that it should be "The Upload directory..." och "The Avatar upload directory..."
![custom_avatar](https://user-images.githubusercontent.com/2890167/130203933-d1a84ab5-3027-4c9f-9d65-fc2ceabbc431.png)

**Comment by wintstar** [comment]
Then the texts should state this more clearly what is directory avatars and what is directory custom_avatars. Also with the error language strings.  As it is now, it is not obvious what the 2 avatar directories are for. This should be described in the description of the avatar management in the Admin Center.

**Comment by BrickOzp** [comment]
Is this unclear in the Avatar settings page, you think or is it while doing the translations?

**Comment by wintstar** [comment]
I think this is better

**Admin.english.php line 467**
`$txt['avatar_server_stored'] = 'Server-stored avatars';`
change to
`$txt['avatar_server_stored'] = 'Avatars gallery';`

**Admin.english.php line 474**
`$txt['custom_avatar_dir_wrong'] = 'The Avatars directory is not valid. This will prevent avatars from working properly.';`
change to
`$txt['custom_avatar_dir_wrong'] = 'The Custom avatars directory is not valid. This will prevent avatars from working properly.';`

**Help.english.php line 512**
`$helptxt['avatar_upload'] = 'This setting is much like &quot;external avatars&quot;, except that you have better control over the avatars, a better time resizing them, and your members do not have to have somewhere to put avatars.<br><br>However, the downside is that it can take a lot of space on your server.';`
change to
`$helptxt['avatar_upload'] = 'This setting is much like &quot;external avatars&quot;, except that you have better control over the avatars, a better time resizing them, and your members do not have to have somewhere to put avatars.<br>By default, the uploaded avatars are stored in the &quot;custom_avatar&quot; directory.<br><br>However, the downside is that it can take a lot of space on your server.';`

**Comment by BrickOzp** [comment]
The "Custom avatars" is not used anywhere in the ui, only in string names, so I do not feel it is a good idea to call it that.
But I like the "Avatars gallery"

**Comment by sbulen** [comment]
@wintstar is correct the custom avatar upload directory is not the avatar directory.
