### ISSUE TITLE
Edit membergroup javascript error

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6973]
#### Description
Edit a membergroup.  Javascript console has error.

```
    at eval (eval at window.onload (script.js?smf21rc4_1629247795:1421), <anonymous>:1:19)
    at window.onload (script.js?smf21rc4_1629247795:1421)
smc_AutoSuggest.init @ suggest.js?smf21rc4_1629247795:56
eval @ VM1369:1
window.onload @ script.js?smf21rc4_1629247795:1421
load (async)
addLoadEvent @ script.js?smf21rc4_1629247795:1415
(anonymous) @ theme.js?smf21rc4_1629247795:51
```

Marking this for 2.1.1.  Its not critical to be fixed for final.

**Comment by Oldiesmann** [comment]
Autosuggest for group moderators works fine for me in Chrome. No errors in the console at all.

**Comment by sbulen** [comment]
I haven't been able to reproduce this.  Suggest seems to work OK.

You do get an error if you add a negative value for max PMs...  (_Database Error: Out of range value for column 'max_messages' at row 1_)

@jdarwood007 - can you reproduce?  I wonder if this was fixed when you sync'd up the themes?

**Comment by jdarwood007** [comment]
Can't reproduce anymore now either.  Closing.
