### ISSUE TITLE
Moderation button shows for guests in mobile mode

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6975]
#### Description
While on mobile, the moderation menu shows even for those without moderation permissions.

<img width="374" alt="Screen Shot 2021-08-18 at 4 56 34 PM" src="https://user-images.githubusercontent.com/732116/129986796-69721b95-db84-4632-9743-d352ae6d7f7f.png">

**Comment by DiegoAndresCortes** [comment]
I don't see this in my local forum

**Comment by DiegoAndresCortes** [comment]
Can you check $context['mod_buttons'] content so we know what is triggering it?

**Comment by jdarwood007** [comment]
Ok this is a result of a mod.  So lets discuss the problem and determine if this is a SMF issue or a mod issue.

The mod uses the hook
```
	call_integration_hook('integrate_mod_buttons', array(&$context['mod_buttons']));
```

And adds in a mod.  Example output
```
array (size=1)
  'solve' => 
    array (size=5)
      'test' => string 'can_solve' (length=9)
      'text' => string 'solve_topic' (length=11)
      'image' => string 'solve.gif' (length=9)
      'lang' => boolean true
      'url' => string 'XXXXX' (length=300)
```

So the array is populated and it processes through normally.
Then we go into the template and it runs through template_button_strip for the mod_buttons.
That function runs the "test" against $context[$test].  Which is false in this case so no moderation buttons.

Should the mod do the can_check sooner or should we handle a empty output better?

**Comment by Sesquipedalian** [comment]
> Should the mod do the can_check sooner or should we handle a empty output better?

Both.

As it says in [index.template.php](https://github.com/SimpleMachines/SMF2.1/blob/a9b8608b91f8b5a5f9cdfe2cf1fdd510731ebc64/Themes/default/index.template.php#L579):
> // As of 2.1, the 'test' for each button happens while the array is being generated. The extra 'test' check here is deprecated but kept for backward compatibility (update your mods, folks!)

But if we are going to continue to offer backward compatibility for the deprecated 'test' check, then we need to find a way to avoid problems like this:
https://github.com/SimpleMachines/SMF2.1/blob/a9b8608b91f8b5a5f9cdfe2cf1fdd510731ebc64/Themes/default/Display.template.php#L313-L326

That chunk of code creates the container div before the tests are checked in `template_button_strip()`, potentially resulting in an empty container showing up (as described in your report above).

**Comment by jdarwood007** [comment]
Ok.  We can also do a 3rd fix in the Dislay.php itself by running through the array quickly and doing the tests and if any fail, delete them from the array.

I did update the mod to do the test earlier in the code.
