### ISSUE TITLE
Possible broken install if not using UTF8?

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#698]
The MySQL I'm using has the charset set to UTF8, when I install SMF without using UTF8 obviously everything is broken: messages, and other strings are truncated at the first accented char.

**As far as I udnerstood**, in the past, SMF tried to fix communications between SMF and the MySQL server using SET NAMES in the case SMF was installed as UTF8 and the server charset was instead not UTF8, but the current situation would require the opposite (I think).

That said, I suppose this is not really a big issue for 2.1 since default is UTF8 and so very few people will change it (hopefully), so let's say it's just a tracking issue that may probably be closed immediately.

**Comment by Arantor** [comment]
So we need a SET NAMES for whatever the charset is going to be?

**Comment by emanuele45** [comment]
A bit overkill, isn't it?

On the other hand it would just mean set $db_character_set in Settings.php... but obviously that should be set "properly" for any collation (or maybe just few). A bit of a mess I suppose.

...or get rid of the setting during install.

**Comment by Arantor** [comment]
I give you Load.php as per trunk

```
// Most database systems have not set UTF-8 as their default input charset.
if (!empty($db_character_set))
    $smcFunc['db_query']('set_character_set', '
        SET NAMES ' . $db_character_set,
        array(
        )
    );
```

So we're already actually doing that if we know the $db_character_set is set. And shouldn't it be set anyway? I'm not entirely sure of the changes to the installer over the years but I always thought it was set regardless.

**Comment by emanuele45** [comment]
I know it, I was reading it while filing the bug report. :P  

And I can paste something from install.php:

```
        // UTF-8 requires a setting to override the language charset.
        if ((!empty($databases[$db_type]['utf8_support']) && !empty($databases[$db_type]['utf8_required'])) || (empty($databases[$db_type]['utf8_required']) && !empty($databases[$db_type]['utf8_support']) && isset($_POST['utf8'])))
        {
            if (!empty($databases[$db_type]['utf8_version_check']) && version_compare($databases[$db_type]['utf8_version'], preg_replace('~\-.+?$~', '', eval($databases[$db_type]['utf8_version_check'])), '>'))
            {
                $incontext['error'] = sprintf($txt['error_utf8_version'], $databases[$db_type]['utf8_version']);
                return false;
            }
            else
                // Set the character set here.
                updateSettingsFile(array('db_character_set' => 'utf8'));
        }
```

;)

**Comment by Arantor** [comment]
Oh, wait, I know why we're not setting the character set... it's because the character set is fluid depending on situation... i.e. depending on the language file, in theory >_<

**Comment by emanuele45** [comment]
And not only that, probably, because in order for it to work on my setup, I had to use `latin1` as charset of the db, so...it's even another bits of information that we currently don't have and we should "find" somehow...

**Comment by Arantor** [comment]
Hmm, I was thinking about this.

Is there any reason why we can't make SMF 2.1 only install UTF-8? Obviously we have to keep the legacy stuff for legacy upgrades, but for new installs (which is what this affects), just have it not just be default but mandatory?

**Comment by illori** [comment]
then should a new install come with utf-8 language files?

**Comment by Arantor** [comment]
That's where it gets complicated. Technically it already does, because the basic English ISO and English UTF-8 should be identical.

**Comment by illori** [comment]
i would think so too. so then we would need to make sure no ISO language packs for other languages are available as well?

**Comment by Arantor** [comment]
No, those are still needed for the reasons outlined above: upgraded installs still need ISO packs because we're not going to do the conversion on upgrade.

**Comment by Xarcell** [comment]
How bad would it be to install utf-8 by default, and force all upgrades to utf-8? Please don't set me on fire.

Feb:2012 - http://4.bp.blogspot.com/-O4jXmTm7WWI/Tyw1As8jt7I/AAAAAAAAI9E/nxxi1T21IH4/s1600/unicode.png
Also useful: http://w3techs.com/technologies/overview/character_encoding/all

**Comment by Arantor** [comment]
It would be a major headache to force all upgrades to UTF-8. It would basically require a rewrite of the upgrader, and I don't want to do that twice (since for 3.0 it's going to be rewritten anyway but what ends up in 3.0 will necessarily be a totally different structure)

There are compatibility issues with breaking that kind of thing (e.g. external scripts) where they could be expected to work properly otherwise.

**Comment by Arantor** [comment]
I just remembered why we can't make UTF-8 enforced in 2.1... SQLite 2.8 does not support it at all. Though we could possibly enforce it for all the others. Hmm.
