### ISSUE TITLE
Wrong conversion of text into links

### ISSUE THREAD

**Issue by woodholly** [SimpleMachines/SMF#6982]
#### Description
Text-to-link convertor converts some text into mess

### Steps to reproduce
1. Create post with this content:
```
Test_1_test.zip
Test_2_test_0.zip
```
2. Check out constructed post html and you will see invalid link created.
3. Conversion is made by code in Sources/Subs.php near "no_autolink_area". I think this can be fixed by adding exceptions to zip/rar/7z domains

### Environment (complete as necessary)
- Version/Git revision: RC3

**Comment by BrickOzp** [comment]
They do not get autolinked on my test forum with latest github version.

**Comment by woodholly** [comment]
Probably fixed, good!
