### ISSUE TITLE
Double spaces prevent autohyperlinks

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#6984]
#### Description
```
https://google.com/foo  and
https://google.com/foo and
```

First one is not hyperlinked.  Second one is.

**Comment by Sesquipedalian** [comment]
Looks like that annoying bug with `&nbsp;` interfering with the auto-linker is back.

**Comment by jdarwood007** [comment]
Thinking out loud.  Can we create a capture group like ``[&nbsp;|\s]`` and have it match the "space"?
