### ISSUE TITLE
warning user by moderator is prompted for password

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#6987]
#### Description
warning user by moderator is prompted for password

### Steps to reproduce
1. enter users profile go to page to issue warning
2. enter text for warning submit page, prompted to enter password. currently password for moderation center is disabled.

### Environment (complete as necessary)
- Version/Git revision: tested on sm.org version
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by BrickOzp** [comment]
And by "currently password for moderation center is disabled" you mean that "Disable moderation security" is enabled?

**Comment by illori** [comment]
Yes.

**Comment by illori** [comment]
i dont agree with this being a 2.1.1 milestone for this issue. this extra step could let a spammer or bad person end up making many more posts in the time it takes to enter the password. this should be fixed before 2.1 final.

**Comment by LexArma** [comment]
I'd agree with Illori. This is currently well and truly an annoyance and a hindrance to moderation on simplemachines.org, I would actually go as far as to suggest that simple warnings should not have moderation security regardless of the "disable moderation security" setting.

**Comment by Sesquipedalian** [comment]
There you go. 😉

**Comment by illori** [comment]
Thank you
