### ISSUE TITLE
Responsive Designe amount of different breakpoints to high

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#7003]
#### Description
Based on this search:
![grafik](https://user-images.githubusercontent.com/1782906/130347891-00dc54bf-b6e6-48c5-af70-52996453fc07.png)
we got many different ranges where responsive kick in,
in general should be one or two breakpoints enough.

responsive css by his own know this:
max-width: 
320
480
720

ranges of min - max of:
480 - 560
720 - 799
721 - 855
856  - 1024

min-width
481

Proposel two ranges:
min-width 640px (~40 rem)
min-width 1024

This two breakpoints would result in three display sizes, small, medium and large.

This numbers based on the breakpoint of tailwind: https://tailwindcss.com/docs/responsive-design

**Comment by DiegoAndresCortes** [comment]
Too late to change all of these imo, if it's not broken I say skip it

**Comment by Sesquipedalian** [comment]
This is a matter of design philosophy, not a bug.
