### ISSUE TITLE
Calendar needs to handle distant future dates more gracefully...

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7020]
#### Description
If you enter a future date, e.g., in 2099, the Calendar reports an error.

**_PHP 7.4 issues 6 errors, 3 pairs of this:_**
![image](https://user-images.githubusercontent.com/23568484/130856184-1c5fc115-b148-466e-bd8d-dde66185474b.png)

**_PHP 8.0 gives a white screen with this error:_**
![image](https://user-images.githubusercontent.com/23568484/130855933-7b1256b4-f19b-4965-955b-e6e563ec294b.png)

**_Note a different but similar error was reported in the forum:_**
```
ManageCalendar.php (Line 300)
mktime(): Epoch doesn't fit in a PHP integer 

```

### Steps to reproduce
1. Enter a date a century out from today

### Environment (complete as necessary)
- Version/Git revision:  Current
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 7.4 & 8.0

### Additional information/references
From the forum:
https://www.simplemachines.org/community/index.php?topic=578657.0

**Comment by jdarwood007** [comment]
This is the [Y2K38 Problem](https://en.wikipedia.org/wiki/Year_2038_problem)

Only way to resolve it right now is to move to a bigint instead of int for the timestamp.  Its possible moving to a true date field may work as well.

**Comment by albertlast** [comment]
Can't replicate on pg, so it's a mysql issue?

**Comment by sbulen** [comment]
Two issues listed above.  I had thought they were related, but they are not.

The "int expected, float given" error is a 32-bit vs a 64-bit PHP issue, not a pg vs mysql issue.  It will only happen on some builds.

The "Epoch doesn't fit in a PHP integer" issue appears to be an OS build issue.  I have found a couple articles that say this has to do with using an old version of the libseccomp2 module:
https://community.linkace.org/t/epoch-doesnt-fit-in-a-php-integer-error-on-arm-v7/69
https://github.com/Kovah/LinkAce/issues/255

The fix for the first is simple.  I'm testing.

The fix for the second is to patch the OS...  I believe if you see this you need to make sure that at least libseccomp2.4.4 is installed.
