### ISSUE TITLE
unapproved topic, OPs replies are not approved

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#7021]
#### Description
unapproved topic, OPs replies are not approved

### Steps to reproduce
1. i have seen this on SM.org, i did not test it myself
2. users topic was unapproved, user posted in the topic again and their posts were not approved. user was not on post moderation.

### Environment (complete as necessary)
- Version/Git revision: whatever sm.org is running
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

related to #379

**Comment by Sesquipedalian** [comment]
This is by design. From #2841:

> * If the topic is unapproved the message automatically becomes unapproved too fixes [Wrong count of board totals with unapproved topics #2840](https://github.com/SimpleMachines/SMF2.1/issues/2840)
>   Instead of messing around with already convulsed queries, let use try a different approach, each message under an unapproved topics becomes unapproved automatically, yes I realize people will ask why their messages were set as unapproved (I am THE ADMINZZZZ) and stuff but hey, better complain about that than complaining their forum is slow or acting bizarrely.

**Comment by Sesquipedalian** [comment]
... Although I suppose we did eventually have to add checks for topic approval status to the relevant queries anyway, so this is no longer strictly necessary for the original reasons.

However, I would be worried about introducing unintended side effects, particularly regarding notifications, if we suddenly changed this behaviour now. Extensive testing would be required, and I don't think it is worthwhile. After all, if the topic is unapproved, then everyone who can see *any* of the replies (i.e. moderators and the original poster) can in fact see *every* reply.
