### ISSUE TITLE
Cannot upload mods in Package Manager (403 Error)

### ISSUE THREAD

**Issue by Hatshepsut71** [SimpleMachines/SMF#7022]
#### Description
After installing latest Github build 697d1f3 on my test forum, no one mod package cannot be uploaded in Package Manager.
I get 'Error 403' on the white screen. Reinstalling RC4 resolve this problem.

### Steps to reproduce
1. Install latest build 697d1f3
2. Open Package Manager and try to upload some mod package

### Environment (complete as necessary)
- Version/Git revision: 697d1f3
- Database Type: MariaDB
- Database Version: 10.3.31
- PHP Version: 8.0.9

### Additional information/references

**Comment by DiegoAndresCortes** [comment]
Might be related to #6996
