### ISSUE TITLE
setlocale breaks some functions

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7027]
So I am using ucfirst() to capitalize some words.  It is failing for some international users. 

The problem relates to this key note on the https://php.net/ucfirst page
```
Note that 'alphabetic' is determined by the current locale. For instance, in the default "C" locale characters such as umlaut-a (ä) will not be converted.
```

Thus using setlocale is causing ucfirst to not work as expected, since it is no longer working with the english alphabet.

I asked in Libera.chat#php and got some info.  I'm attaching that to this report.

I think we need to remove the usage of setlocale in our timeformat function, since it has unexpected consequences.  We need to figure out a different solution to time handling.

Right now this is only affecting sm website because of some code we use on it directly not related to SMF.  But since the code calls in SSI.php and starts up a user session, this setlocale is used.

I hate to do this, but I'm marking it for 2.1.0.  I think this is a big enough change regarding it, that we want to get it right for final, not a patch.

Tagging both @Sesquipedalian  and @live627 since your name is on the blame lines.

```
19:00:09 < SleePy> What would cause ucfirst to fail to upper case a english word?  I've got a ucfirst that is failing, resulting in a require_once that fails.  Its a english word ('index') being passed into ucfirst.  But the result is still index.  I don't get it
19:00:39 <@__adrian> https://3v4l.org/gYElF
19:00:47 < SleePy> Its only happening for users on my site from places like turkey.  So i'm wondering if something is mucking around with php?
19:01:01 < SleePy> Yea.  I know.. It should work
19:01:02 <@__adrian> unlikely
19:01:23 <@__adrian> where's this word coming from?
19:01:34 < SleePy> -error_log:6089:[Sat Aug 28 07:17:09.471987 2021] [php7:error] [pid 26220] [client XXXX:0] PHP Fatal error:  require_once(): Failed opening required '/index.english.php' (include_path='.:/usr/local/lib/php') in /Subs-Language.php on line 67
19:02:05 < SleePy> require_once($languages . '/' . ucfirst($section) . '.' . $lang . '.php');
19:02:14 < SleePy> Thats the line of code.  I'm very confused as to what..
19:02:41 <@__adrian> yes, but where does the value come from
19:02:46 <@__adrian> e.g., is it input?
19:02:52 < SleePy> Entirely from internals.  
19:03:10 <@__adrian> bin2hex() it
19:03:11 < SleePy> No user input.  The app is calling that file
19:03:36 < SleePy> Will try that
19:04:11 <@__adrian> "only happens for specific users" makes me question that there's no input involved
19:04:39 <@__adrian> how do you know they're from turkey? is there anything special that happens for users from turkey?
19:04:56 < SleePy> The guy who said it says others from turkey are all getting it.
19:04:59 <@__adrian> e.g., do you screw with locale settings?
19:05:50 < SleePy> Umm.. I'm trying to think..  maybe.  But I have to recall what PHP function does that
19:05:57 <@__adrian> setlocale
19:05:57 < SleePy> Big site, lots of code
19:06:04 <@__adrian> just grep "locale"
19:06:20 <@__adrian> well, bin2hex first
19:06:26 < SleePy> Yes, we do a setlocale in the site code
19:06:40 < SleePy> Can that break ucfirst?
19:06:58 <@__adrian> https://www.php.net/ucfirst  second sentence
19:07:04 < SleePy> If its expecting to upper case non english characters but Turkish characters instead?
19:07:17 <@__adrian> it's not "breaking" it, but it's making it work correctly in a different way
19:07:47 < SleePy> Uggh.. So to "fix" it, I need to either revert the setlocale.  Or come up with my own ucfirst
19:07:49 <@__adrian> this is a guess
19:07:55 <@__adrian> you should confirm
19:08:07 <@__adrian> no - i'd say you should simply not be setting the locale
19:08:16 < SleePy> Will do..  Added some code to log the error.  Just need a user to trigger it
19:08:37 shailangsa has joined (~shailangs@host86-186-127-196.range86-186.btcentralplus.com)
19:08:48 < SleePy> I have to dig into why, but it looks to be time related reasons.  Any reason we shouldn't?
19:08:51 <@__adrian> you can trigger it. just send a request with a suitable Accept-language header (or however you're deciding on the locale)
19:09:08 <@__adrian> (or just set it explicitly)
19:09:44 <@__adrian> "SleePy> Any reason we shouldn't?"  well for one it might be breaking your strategy for requiring files
19:09:51 < SleePy> Well it looks like its entirly for handling time formats.
19:10:00 <@__adrian> https://php.net/intl
19:10:30 < SleePy> https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs.php#L857
19:10:40 < SleePy> Thats the code (which is public), which does our setlocale
19:11:02 <@__adrian> re: require startegy: i'd also recommend explicit mappings instead of trying to determine it dynamically
19:11:20 < SleePy> Ok, well I will have to look into this.
19:12:09 < SleePy> Yea.   Its just setup so I can call loadLanguage('index') and that function handles figuring out what language the user has and loads the correct sections language strings up for translation on pages
19:12:25 <@__adrian> re: setting locale: this generally shouldn't be a runtime thing. set the locale to what YOU want, not to what each request wants. handle l10n in different way that don't completely change the server env (e.g., intl)
19:12:42 <@__adrian> *i18n/l10n
19:13:17 <@__adrian> s/don't/doesn't/
19:14:20 < SleePy> Ok.  Well thats a bug that we will have to correct.
19:14:50 < SleePy> Thanks for the help with that.
```

**Comment by live627** [comment]
LC_TIME  does not affect this. SMF 2.0 uses it in tiimeformat().

https://github.com/SimpleMachines/SMF2.1/blob/0767de6458100362da1e4e16e80fd2d74397b655/Sources/Load.php#L3048-L3050

This is not in 2.0.


Relevant issue:
- https://github.com/SimpleMachines/SMF2.1/pull/3948

**Comment by jdarwood007** [comment]
Odd.  This was never an issue in 2.0 and setlocale seems to be the cause because its what can change this.

https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs.php#L856-858

**Comment by jdarwood007** [comment]
FYI, For now, I've worked around this by using mb_* based functions to create a mb_ucfirst

```
function mb_ucfirst(string $string, $encoding = 'UTF-8'): string
{
	return mb_strtoupper($string[0], $encoding) . mb_substr($string, 1, mb_strlen($string, $encoding) - 1, $encoding);
}
```

**Comment by Sesquipedalian** [comment]
> Odd. This was never an issue in 2.0 and setlocale seems to be the cause because its what can change this.
> 
> https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs.php#L856-858

I'm pretty sure that @live627 is correct. The PR he linked to (#3948) added a `setlocale()` call in `loadLanguage()` that affects string processing in general. The `setlocale()` call in `timeformat()` only affects time formats.

I think the problem is that the `setlocale()` call in `loadLanguage()` affects far too broad a set of behaviours. The specific issue that #3948 was meant to solve was "If the filename of attachment starts with a non-ASCII character (like Chinese), the filename is missing after posting" (#3887). I think we'd do better if we only switched locales just at the point where we need to process the attachment's file name and then switched back again as soon as possible.

**Comment by sbulen** [comment]
I would not feel comfortable with limiting setlocale to attachment processing only.  I think you'd need to consider/test utf8 character usage in all places pathinfo() & basename() are used.

Note that this isn't even an SMF issue.  We should be very wary of such a potentially dangerous change - especially without a reported SMF problem.

Sounds like using mb_ucfirst is the proper solution.

**Comment by sbulen** [comment]
If you do not issue a setlocale, it will use the php default, which is what?

We should consider that random...  SMF should take control of the locale, which affects a lot of PHP processing, or expect random behavior.

Note most language translations in SMF do not specify the locale, so it falls back to en_US.  I do recall reading somewhere that for full utf8 support, that's all that is necessary.  We could consider hardcoding to en_US, so behaviors would be consistent no matter what language is selected.  SMF takes control of other locale-related functions, e.g., time & currency, so that would not be affected.  

But not specifying locale would be a step backwards in terms of utf8 support.  We need to embrace mb.

**Comment by Sesquipedalian** [comment]
After spending a bit of time poking around, I now agree with @sbulen. This code should be left as it stands.

FYI, `$smcFunc['ucfirst']()` already does what you are looking for, @jdarwood007. Since you are calling SSI.php in your external code, that should be available to you already.
