### ISSUE TITLE
atwho mention system

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#7030]
Did some search on this but couldn't find a topic. Apologies if this is a duplicate.

atwho mention system is no longer maintained. Should we continue using it?

https://github.com/ichord/At.js

> This project was no longer maintained. You could use zurb tribute instead.

**Comment by Sesquipedalian** [comment]
To my knowledge, we are currently experiencing no issues with it. If something comes up in the future, it should be relatively painless to switch to another library, but I don't see a need to do that just before reaching the 2.1.0 milestone.
