### ISSUE TITLE
parse_bbc() should handle `<br/>`, `<hr/>`, etc.

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#7043]
In SMF 2.1, parse_bbc() generates HTML5 `<br>` elements rather than HTML4 `<br/>` elements, which is good. But parse_bbc() also only seems to *recognize* the `<br>` version as an HTML element, and not the `<br/>` version. This means that `<br/>` elements are erroneously encoded to `&lt;br/&gt;` in the function's output.

**Comment by jdarwood007** [comment]
I'm seeing these a lot in sm website searches.  Lots of <br /> not being converted.  Seems like it should be simple addition to one of the strtr.

**Comment by Sesquipedalian** [comment]
Hm. Upon further testing, it seems that my diagnosis was incorrect. Whatever the reason is that literal `<br />` strings are showing up in signatures on simpleamachines.org, it isn't because of parse_bbc().
