### ISSUE TITLE
BBC parsed results show in search

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7044]
#### Description
I think this is related to the fix from #6887

Because we use results after we parse bbc, we sometimes get bbc parsed text strings in search results.
<img width="1198" alt="Screen Shot 2021-09-06 at 8 15 06 AM" src="https://user-images.githubusercontent.com/732116/132237765-2cae6d9d-6be7-462e-bc44-a0acd6418ca1.png">
<img width="1183" alt="Screen Shot 2021-09-06 at 8 15 15 AM" src="https://user-images.githubusercontent.com/732116/132237766-4e410900-0481-42be-b94c-623a9f470e89.png">

I don't know if we can fix this or have to accept this as a side effect from the fix.

### Steps to reproduce
1. Make a post with this content
```
words and words and words and more words... Then Code..

[code]Use my code
[/code]
```
2. Search for "code"

### Environment (complete as necessary)
- Version/Git revision: Latest Git
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references
@sbulen @live627 @Sesquipedalian 
Since you worked with the original PR.  Mentioning you guys on this.

**Comment by BrickOzp** [comment]
This happens on 2.0 as well

However, if you search in the topic the results are not stripped of tags and truncated, and looks really bad with this input. And that seems to be related to #6887

**Comment by jdarwood007** [comment]
Correct.  The issue has been a battle between how to make this look right in search results with the highlighter.  I tracked it, but I don't know if we can fix it for 2.1 or any version because its a issue that will have a side effect one way or another.  Whether its before or after we parse bbc.

**Comment by live627** [comment]
Could a possible solution be in using a new [mark] bbc?

**Comment by Sesquipedalian** [comment]
This is a legitimate bug, but it is not one we can fix unless we implement significant changes to the search system more broadly.
