### ISSUE TITLE
identifier syntax is not backwards compatible.

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7049]
#### Description

SMF 2.0
```
:~# php /smf20/testdb.php
SELECT * FROM `database`table
```

SMF 2.1 
```
~# php /smf21git/testdb.php
SELECT * FROM `database`.``table
```

test.php
```
<?php
$my_prefix = 'database.';
require_once('SSI.php');
echo $smcFunc['db_quote']('SELECT * FROM {identifier:my_prefix}table', array('my_prefix' => $my_prefix));
```

### Additional information/references
Relevant PR from the change: https://github.com/SimpleMachines/SMF2.1/pull/4076

**Comment by jdarwood007** [comment]
I noted in discussion with @Sesquipedalian I suspect the author of the related PR assumed identifier was used for table.column syntax while I (and maybe others) assumed its usage as database.table syntax.

Regardless, it is a BC change.  Not sure the best method here but I think the 2.0 syntax while wrong, was closer to right.

**Comment by Sesquipedalian** [comment]
The lone occurrence in SMF 2.1:
https://github.com/SimpleMachines/SMF2.1/blob/6776b7627d308dd668f2f51037f990f50213df3a/Sources/ManageMaintenance.php#L619-L627

In that case, the assumption seems to be that `{identifier:key}` will contain a complete identifier, not a substring to be concatenated with anything else.

Meanwhile, there are no occurrences in SMF 2.0 at all.

**Comment by jdarwood007** [comment]
Maybe we would wrap another strtr around the call to replace `.`` with just `. and then `` with just one `.  Thoughts?

```
		case 'identifier':
			// Backticks inside identifiers are supported as of MySQL 4.1. We don't need them for SMF.
			return strtr('`' . strtr($replacement, array('`' => '', '.' => '`.`')) . '`', array('`.``' => '`.', '``' => '`'));
			break;
```

Not ideal, but cleans it up and shouldn't break the one use case in 2.1.

**Comment by Sesquipedalian** [comment]
It might simpler and more reliable to just use `explode()` and `implode()`.

**Comment by albertlast** [comment]
Why not throw an error and request a change from mod author?

**Comment by Sesquipedalian** [comment]
> Why not throw an error and request a change from mod author?

Because there's no need. 

In SMF 2.0.x, `{identifier:foo}` only worked for substitutions where the value contains either no period characters, or only a single period at the end of the string, such as `'foo' => 'bar'` or `'foo' => 'bar.'`.

As of a551a45 in SMF 2.1, `{identifier:foo}` works for `'foo' => 'bar'` and  `'foo' => 'b.bar'`, but not for `'foo' => 'bar.'`.

With the changes in #7051, `{identifier:foo}` will work for `'foo' => 'bar'`,  `'foo' => 'bar.'`, `'foo' => 'b.bar'`, and  `'foo' => 'b.bar.'`
