### ISSUE TITLE
Database version not detected correctly in the upgrade.php script (when run through CLI)

### ISSUE THREAD

**Issue by websmurf** [SimpleMachines/SMF#7060]
#### Description
I'm in the process of testing an upgrade for my SMF 2.0.18 site and ran in to this error when running the upgrade.php script through cli (`php upgrade.php`)

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function smf_db_query(), 1 passed in /var/www/forum/upgrade.php on line 2594 and at least 2 expected in /var/www/forum/Sources/Subs-Db-mysql.php:361
```

### Steps to reproduce
1. Load in a 2.0.18 database
2. Run the cli upgrade script: `php upgrade.php`

### Environment (complete as necessary)
- Version/Git revision: 2.1 RC4
- Database Type: Mysql 
- Database Version: 8.0.23
- PHP Version: 8.0.5

### Additional information/references

It appears the `$database_version` detection is missing an `eval` call.
At this point the version_check code is being injected into version_compare as is:

In upgrade.php
```php
        if (empty($database_version))
	{
		$database_version = $databases[$db_type]['version_check'];
		$where_field_support = $db_type == 'mysql' && version_compare('5.0', $database_version, '<=');
	}
```

If I change this to:
```php
        if (empty($database_version))
	{
		$database_version = eval($databases[$db_type]['version_check']);
		$where_field_support = $db_type == 'mysql' && version_compare('5.0', $database_version, '<=');
	}
```

The upgrade continues as expected.

**Comment by websmurf** [comment]
There are a few additional errors in the upgrade process, will have a look into that as well:

```
 +++  Update the information already in log_actionsError: unserialize(): Error at offset 48 of 87 bytes File: /var/www/forum/upgrade.php(2149) : eval()'d code Line: 20Error: unserialize(): Error at offset 48 of 87 bytes File: /var/www/forum/upgrade.php(2149) : eval()'d code Line: 20Error: unserialize(): Error at offset 57 of 91 bytes File: /var/www/forum/upgrade.php(2149) : eval()'d code Line: 20Error: unserialize(): Error at offset 49 of 83 bytes File: /var/www/forum/upgrade.php(2149) : eval()'d code Line: 20Error: unserialize(): Error at offset 61 of 95 bytes File: /var/www/forum/upgrade.php(2149) : eval()'d code Line: 20Error: unserialize(): Error at offset 48 of 82 bytes File: /var/www/forum/upgrade.php(2149) : eval()'d code Line: 20Error: unserialize(): Error at offset 51 of 85 bytes File: /var/www/forum/upgrade.php(2149) : eval()'d code Line: 20.. done.

....
 +++  Fixing attachment directory setting...Error: unserialize(): Error at offset 0 of 43 bytes File: /var/www/forum/upgrade.php(2149) : eval()'d code Line: 22 done.
```

**Comment by live627** [comment]
that could be trying to `unserialize()` JSON-encoded data

**Comment by sbulen** [comment]
Can you share the serialized strings in question?  We haven't seen un-serialize fail before - unless the strings are truly broken.  

Are you certain the serialized strings from your 2.0 db are valid?

**Comment by sbulen** [comment]
I can reproduce this issue using php8 and current github code, upgrading 2.0.18 to 2.1.  

I have also confirmed that #7077 addresses this issue.  

I suspect the unserialize errors are valid, and point to some data issues in your serialized strings.

**Comment by websmurf** [comment]
> Can you share the serialized strings in question? We haven't seen un-serialize fail before - unless the strings are truly broken.
> 
> Are you certain the serialized strings from your 2.0 db are valid?

Will have a look at this. There are 65k users; so it's more than likely that there are some issues in the strings in the database :-)
