### ISSUE TITLE
Upgrade stalls on backup

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#7066]
I just downloaded the .zip file from GH not more than 5 minutes ago to do an upgrade on my site. The upgrader will not run, it just sits there. I am literally trying to upgrade right now.

### Steps to reproduce
1. Download from GH
2. Make a zip file
3. upload to cpanel
4. extract
5. run upgrade.php
6. nothing happens. 

### Environment (complete as necessary)
- Version/Git revision: Just now
- Database Type: MariaDB
- Database Version: 10.2.36
- PHP Version: 7.4

### Additional information/references

**Comment by sbulen** [comment]
Did you copy the 8 upgrade*.* files from /other down to root (between steps 4 & 5)?

What version are you upgrading from?

**Comment by sbulen** [comment]
Confirmed.  For me it freezes here:
![image](https://user-images.githubusercontent.com/23568484/132959640-30335336-3f64-4e1e-9af4-b2dc1aa03c78.png)

**Comment by smfbigguy** [comment]
Yes all files where copied over. I go to upgrade.php and it just sits there doing nothing. I'm not sure what version I was at before this. I didn't look before I overwrote all the files with the upgrade files. This may be the same problem illori is having ?

**Comment by illori** [comment]
this is a different issue then what i reported.

**Comment by sbulen** [comment]
Yes, this is different from Illori's...

**Comment by sbulen** [comment]
> 
> 
> I didn't look before I overwrote all the files with the upgrade files.

Was this a 2.1 => 2.1 upgrade?

**Comment by sbulen** [comment]
I am seeing this in the console:
![image](https://user-images.githubusercontent.com/23568484/133023750-a714b342-0787-410a-861e-2452c9f92455.png)

@jdarwood007 - could you take a peek?

**Comment by smfbigguy** [comment]
> 
> 
> > I didn't look before I overwrote all the files with the upgrade files.
> 
> Was this a 2.1 => 2.1 upgrade?

Yes it is

**Comment by sbulen** [comment]
#7077 closed this issue out.

Please try again, it should work now!

**Comment by smfbigguy** [comment]
I will when I get home from work, thank you.

**Comment by smfbigguy** [comment]
Works great
