### ISSUE TITLE
Upgrader: Hangs on first step via browser

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7075]
#### Description
Note this is different from #7073 - which is via CLI.  It is failing much earlier when run via browser.

Note this is also different from #7066 - it fails on backup.  This is running without the backup selected.

Bottom line is, today, the upgrader cannot run no matter which set of options is selected.

Lots of different recent changes appear to have had adverse effects...  

![image](https://user-images.githubusercontent.com/23568484/133018022-616c7a85-1f8e-4fdb-b43d-872a47d96e3e.png)

### Steps to reproduce
1. Upgrade from 2.0 to 2.1
2. No backups requested
3. Via browser, not CLI

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type:  Mysql
- Database Version:  5.7
- PHP Version:  7.4

**Comment by WhistlingDonkey** [comment]
I had this same issue upgrading 2.1RC3 to 2.1RC4 in the browser back when RC3 went to RC4  - it just wouldn't work no matter which options were selected when upgrading in the browser (it did work in the CLI back then though) so we need to look that far back at least.

**Comment by sbulen** [comment]
No, this is new.  I ran a full set of tests just a few weeks ago.  

I am finding this in the console, which I think is preventing the next step from being requested:
![image](https://user-images.githubusercontent.com/23568484/133023555-cb5cb788-4cd4-4049-a274-dd90e60c6263.png)

@jdarwood007 - could you take a peek?

**Comment by sbulen** [comment]
I don't think it is the same thing.  We had seen similar issues earlier (e.g., see #6801 ).  But prior to RC4 they were all resolved.

I now think the current issue is caused by a js/ajax error, which might actually be related to #7066 :
![image](https://user-images.githubusercontent.com/23568484/133024255-f601b087-ecc1-4cae-8a50-a41d18ebf91d.png)

**Comment by WhistlingDonkey** [comment]
You are quite likely correct, it just looks exactly the same, crashed in exactly the same spot as what happened when I upgraded RC3 to RC4 on the day that RC3 went to 4. Unfortunately I forgot to look for errors in the console before I went and ran it in the CLI instead :(

**Comment by lurkalot** [comment]
Glad you found this issue, I managed to kill two local test sites while testing the upgrader yesterday. Exact same problem, and with or without options selected.

**Comment by vort7u** [comment]
It's the same problem that I had too and at this point I don't think it's due to this:
https://github.com/SimpleMachines/SMF2.1/issues/6823

**Comment by smfbigguy** [comment]
Same problem for me.
