### ISSUE TITLE
Installer: same MySQL version detection as Upgrader

### ISSUE THREAD

**Issue by WhistlingDonkey** [SimpleMachines/SMF#7078]
#### Description
The installer uses the same `mysqli_get_server_info()` MySQL version detection as the upgrader which causes issues in detecting the proper version number for MariaDB, so just adding this issue so we can fix the installer at the same time as the upgrader.

### Environment (complete as necessary)
- Version/Git revision: Github latest

### Additional information/references
Refer #7070 for previous discussion on mysqli_get_server_info() and MariaDB.

**Comment by illori** [comment]
duplicate of #7070
