### ISSUE TITLE
Case sensitive LIKE is not handled as such (PGSQL, SQLite)

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#708]
In a lot of places we still use LIKE in queries when we really mean a case-insensitive match as MySQL does. While this is most important in auth cases where we use the lower case of the user name, there are others e.g. in the ban system amongst others.

Originally documented in http://dev.simplemachines.org/mantis/view.php?id=5002 but still an issue so moving it over here for referencing future commits.

**Comment by butch2k** [comment]
MySQL does case-insensitive search only when the collation is case insensitive, if the default collation is case sensitive then MySQL does case sensitive matching. If i'm correctly reading the source, SMF always assume case insensitive search in the case of MySQL which might prove wrong.

**Comment by Arantor** [comment]
@butch2k: You're not reading it wrong. However the collations used by SMF most of the time should be case insensitive.

**Comment by Oldiesmann** [comment]
This is still an issue with searching, at least in Postgres (haven't tried SQLite).

With the welcome topic there, if you search for "welcome", it doesn't find anything. However, if you search for "Welcome", it finds that topic/post.

This is with a large-sized custom search index created.

**Comment by Arantor** [comment]
That sounds like a problem with the index (or it's not using the index for some reason)

**Comment by Oldiesmann** [comment]
Fixed that issue in #785.

**Comment by Oldiesmann** [comment]
I believe the remaining issues with this were resolved with #785, so I'm going to close this now. If I run across any further issues relating to this, I'll fix them as I find them.
