### ISSUE TITLE
Upgrader: Tries to delete custom_avatar directory

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7082]
#### Description
I've never seen this one before...
`+++  Converting legacy attachments.Error: rmdir(yada/yada/custom_avatar): Directory not empty File: yada/yada\upgrade.php(2155) : eval()'d code Line: 31. done.
`

This particular run was via CLI, so I could see the error.  

### Steps to reproduce
1. Upgrade a 2.0 forum that already has a folder for custom_avatar

### Environment (complete as necessary)
- Version/Git revision:  Current
- Database Type:  mysql
- Database Version:  5.7
- PHP Version:  8.0

### Additional information/references
This is being run in a test wamp environment.  Initial suspicion is directory separators are confused, so it thinks that the folder names are different when they're not...

**Comment by mobasuite** [comment]
no problems on my end

**Comment by Sesquipedalian** [comment]
What happens if you change the following?

Find:
https://github.com/SimpleMachines/SMF2.1/blob/bcf8c77b3274ad48b37571b388e16ba5198ec484/other/upgrade_2-1_mysql.sql#L393

Replace:
```
if (real_path($custom_av_dir) != realpath($GLOBALS['boarddir'] .'/custom_avatar'))
```

**Comment by sbulen** [comment]
@Sesquipedalian - yep that worked.  PR submitted.
