### ISSUE TITLE
Better handling of IRIs is needed in various places

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#7084]
Various parts of SMF's code need to do a better job handling IRIs.
- Although the autolinker now correctly converts IRIs to pure ASCII URLs in `href` attributes, that doesn't currently happen in BBCodes.
- IRIs entered in the user profile field `website_url` need to be normalized, in order to avoid problems further down the line.
- IRIs entered as the targets of redirection boards need to be normalized for similar reasons.
- If `$boardurl` is an IRI, it needs to be normalized, too. Otherwise, it is possible for the admin to enter an IRI that is perfectly correct to the human eye but could nevertheless immediately render the forum unreachable.
- IRIs in `globalCookiesDomain` and `cors_domains` need to be normalized. **Failing to do so has potential security implications.**
- Likewise, incoming checks for cookies and cross-origin requests need to be make IRI-aware. **Failing to do so has potential security implications.**

**Comment by sbulen** [comment]
Have you seen specific bugs you can share?  I'd hate to go rewriting a bunch of stuff unless it's truly necessary.

Maybe we need an internal discussion on this.

**Comment by Sesquipedalian** [comment]
Sure. #7079 was one example that was easy to reproduce. #7025 was another, and my first bullet point above is basically the same bug but for BBC instead of the auto-linker. Here's another easy one that I've found since opening this issue:

1. Make sure you have SSL and the image proxy turned on.
2. Make a post including the following string: `[img]http://кто.рф/images/search.gif[/img]`
3. Notice how it the image doesn't appear. This is because the image proxy doesn't handle the IRI correctly.

Others require more work to reproduce—or rather, they require more work to demonstrate their negative consequences. For example, it takes more effort to prove how mishandling IRIs in `$modSettings['globalCookiesDomain']` will break cookies, because you need to register an IDN to install your test forum on first (otherwise you can't generate testable cookies), but if you look at the relevant code with IRIs in mind, it become clear pretty quickly that, yeah, that's going to produce problems.

I'm still in the midst of the audit I am now undertaking, and I'm finding and fixing them as I go. When it's done, you'll see it all. 

The good news is that this doesn't amount to a rewrite. It mostly just consists of inserting calls to `normalize_iri()`, `iri_to_url()`, or `url_to_iri()` to make sure the value is what the existing code already expects it to be.

**Comment by jdarwood007** [comment]
Do you really need to register a IDN?  Can't you just use a sub domain?

**Comment by Sesquipedalian** [comment]
> Do you really need to register a IDN?  Can't you just use a sub domain?

Oh yeah, that'd work, too. 🙂
