### ISSUE TITLE
Too low mysql version

### ISSUE THREAD

**Issue by mobasuite** [SimpleMachines/SMF#7086]
#### Description
--Description Here--

### Steps to reproduce
1.  Try to upgrade forum
2. receive message : Your MySQL version does not meet the minimum requirements of SMF.

Please ask your host to upgrade.

### Environment (complete as necessary)
- Version/Git revision: https://github.com/SimpleMachines/SMF2.1/commit/7143a85777f9926cf2008018d9ce5f596e9e5ef1
- Database Type: mysql
- Database Version: Database client version: libmysql - 5.6.43
- PHP Version: 7.3.28

### Additional information/references

**Comment by jdarwood007** [comment]
#7077 should resolve this and has been merged

**Comment by mobasuite** [comment]
thanks, worked
