### ISSUE TITLE
Invisible Joinable group becomes primary

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7089]
#### Description
If you have a group that is request-able to join and the group is set to invisible.  Upon approving the join, the group becomes primary.
 
### Steps to reproduce
1.  Make a test group, setting the group type to Requestable and Visibility to Invisible
2. Make a test user
3. Request under test user to join the test group
4. As admin approve this via the moderation center groups
5. User will have the test group become their primary group.

### Environment (complete as necessary)
- Version/Git revision: latest git
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references
Tested on 2.0 and it works as expected with the same steps.

**Comment by WhistlingDonkey** [comment]
Well that was a bit of a pain to track down. 

So what is happening is that adding members to groups through the moderation center (the user requested to join) is done as a background task and GroupAct-Notify is setting the group type to 'auto' (line 65) `addMembersToGroup($row['id_member'], $row['id_group'], 'auto', true);` and no check is done there on whether the group should be auto or only_additional. When `addMembersToGroup()` is run there doesn't appear to be any check whether the group should actually be only_additional or not so if a member is only part of a post based group the invisible group gets set as the primary.
