### ISSUE TITLE
No line breaks possible in board descriptions

### ISSUE THREAD

**Issue by LexArma** [SimpleMachines/SMF#7096]
Fairly minor issue, but concerns many forums - Even simplemachines.org has line breaks in board descriptions.
With board descriptions no longer accepting HTML, we have lost the ability to have line breaks in descriptions. 
Currently allowed BBC: abbr, anchor, b, center, color, font, hr, i, img, iurl, left, li, list, ltr, pre, right, s, sub, sup, table, td, tr, u, url
Could we add br?

**Comment by Sesquipedalian** [comment]
Sure. Should be trivial to fix.
