### ISSUE TITLE
Very long page loading-time (Integration hooks)

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#7097]
#### Description
`Fatal error: Maximum execution time of 60 seconds exceeded in ***\Sources\ManageMaintenance.php on line 2084`

### Steps to reproduce
1. Install several mods that use many hooks (~200+)
2. Go to Maintenance => Forum Maintenance => Integration hooks page in Admin

### Environment (complete as necessary)
- Version/Git revision: 2.1 RC4
- Database Type: MariaDB
- Database Version:  10.5.10
- PHP Version: 7.4.23

### Additional information
Of course, this can be fixed, e. g. through `ini_set('max_execution_time', 120)` in the `get_integration_hooks_data` function, but maybe it is better to optimize the function that retrieves information about all the hooks?

**Comment by albertlast** [comment]
From my point of view, is this not repeatable, to many unknown factors. Based on this issues information.

**Comment by DiegoAndresCortes** [comment]
> 
> 
> From my point of view, is this not repeatable, to many unknown factors. Based on this issues information.

Not so sure about that, a simple mod could easily be using 10+ hooks

**Comment by live627** [comment]
@dragomano you on Windows?

**Comment by dragomano** [comment]
Yep

**Comment by live627** [comment]
[ManageMaintenance.zip](https://github.com/SimpleMachines/SMF2.1/files/7273160/ManageMaintenance.zip)


Does the above stop the timeout?

**Comment by dragomano** [comment]
Yes, but some installed mods' hooks are displaying "Not Exists" status now.

**Comment by live627** [comment]
Which mods do you have installed? I think               I figured out what
went wrong, now I need more integrations to verify my fix.

**Comment by dragomano** [comment]
Try out the [Light Portal](https://custom.simplemachines.org/index.php?mod=4244) to test.

**Comment by live627** [comment]
Thanks. Was it `Bugo\LightPortal\Integration::whoisOnline`?
[ManageMaintenance.zip](https://github.com/SimpleMachines/SMF2.1/files/7278143/ManageMaintenance.zip)

That one should fix that.

**Comment by dragomano** [comment]
Pages are loading faster now :)
But integrate_whos_online hooks are no longer displayed

Before changes:
![2021-10-04 19_21_28-Toster - Unreal Commander v3 57x64 − Bugo](https://user-images.githubusercontent.com/229402/135869585-2e385746-7188-4ebb-b6ea-ab0d1f043445.png)

After changes:
![2021-10-04 19_22_55-Integration Hooks — Firefox Developer Edition](https://user-images.githubusercontent.com/229402/135869618-6a4e3603-6093-4bc0-a713-e15260de091a.png)

Error log:
```
Sources/ManageMaintenance.php (Line 1871)
Undefined variable $hook
```

**Comment by dragomano** [comment]
Now it works:
```php
	$filtered_hooks = array_filter(
		$hooks,
		function ($hook) use ($current_filter)
		{
			return $current_filter == '' || $current_filter == $hook;
		},
		ARRAY_FILTER_USE_KEY
	);
```
Also, you can add hook sorting for select box:
`ksort($hooks);`

[ManageMaintenance.zip](https://github.com/SimpleMachines/SMF2.1/files/7278956/ManageMaintenance.zip)
