### ISSUE TITLE
Improve path handling for FTP instances (installer, upgrader, webinstall)

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#710]
Originally referenced - a little indirectly - in Mantis 5024, the current detection code for paths is limited and often wrong in all cases we do FTP.

We can improve upon this; I know I did in Wedge, by actually trying to find the directory and on the hosts I tested that code on, it was able to find the right path more than not, which is an improvement on what we have now.

But it requires more than just a little tweak; all the FTP classes we use need improvements to support the testing required. I'm really not sure about backporting this below 2.1 either, there's a lot to do there.

**Comment by jdarwood007** [comment]
If it isn't too much, I would like to see rather than improving FTP support (not that we can't), we add support for SFTP and WebDav.  These will bring in the newer technologies being used and gaining ground, while FTP is still common among hosts, not having those options is very limited.

**Comment by Arantor** [comment]
I'm not keen on WebDev so much but SFTP is worth adding at some stage - the problem is we really need to have a pure PHP solution to make it work without adding exotic dependencies. Now, that's entirely possible to do, phpseclib will do the job admirably, it's just rather chunky, hundreds of KB to handle the various things that are needed which pretty much rules out being in webinstall.

But quite honestly, the major headache is the fact that we're doing all this with file edits. If we didn't have to account for file edits so much, we wouldn't have half as many problems as we do (since permissions could just be left with whatever the system umask is and handled as regular uploads)

**Comment by deliciousbamboo** [comment]
Excellent .. just take it from Wedge if you already did the work.

**Comment by live627** [comment]
Wedge has a closed license.

Off topic: Another sockpuppet?

**Comment by Arantor** [comment]
Oh, no, deliciousbamboo is a troll who doesn't like us.

Oh, and while Wedge is under a closed licence, I submitted a CLA to Nao that allows me to use my own code in other projects.

Difference is there are things that need to be considered that Wedge wasn't interested in doing that SMF still needs to consider.

**Comment by deliciousbamboo** [comment]
> Wedge has a closed license.

Was not aware, the OP said they had done the work in said project.  If they did the code and did not sign over IP then they are the owner then should not they be able to share it with other programs?

> Oh, no, deliciousbamboo is a troll who doesn't like us.

yes that is correct

> Off topic: Another sockpuppet?

yet another insult from this place, whats up with that, why so protective of comments?

**Comment by Arantor** [comment]
I did the code, I signed a licence, I can include such code if I see fit. The requirements in Wedge are different.

You don't like us because of an image that was suggested to be included (but hasn't been) from a totally different project of two white circles overlapping on a grey background, really just because we hadn't thoroughly checked out the licensing details at this point in time?

As far as insulting goes, firstly, it's not very nice to dive into a project and start spreading bile all because of a misunderstanding. Secondly, there are people who do not like our project who have already been observed joining up specifically to make bad comments and some of them seemed like yours. I apologise for the misunderstanding on that score.

**Comment by deliciousbamboo** [comment]
Thats fine and understood.

**Comment by NanoSector** [comment]
While reading through the ftp code a while back I noticed some code that handled finding the right path, is this the code that you wanted to include?

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
