### ISSUE TITLE
Better input sanitization needed in posts and profile fields, etc.

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#7101]
This issue is closely related to #7085, but extends it more generally.

SMF currently does not filter out invisible formatting characters, private use characters, or non-character byte sequences in user input. We do filter out ASCII control characters in various places, but that's not sufficient in a Unicode environment.

Filtering out ASCII control characters, private use characters, and non-characters is easy, but invisible formatting characters are a much trickier problem. On the one hand, if we don't filter out these invisible characters, it becomes trivial to insert them into strings in order to circumvent input filters. But on the other hand, if we simply ban all formatting characters in the name of security, we'll break support for emoji and for many non-European languages. Dealing with this problem requires a more nuanced approach than a simple ban, because formatting characters are legitimately necessary in some contexts, but have no business appearing in other contexts.

**Comment by chopinesque** [comment]
Since you are quite serious about sanitization, I would suggest trimming leading, trailing and multiple spaces too (at least in subject field); or providing an option for that.
