### ISSUE TITLE
PHP 8.1 MySQLi error mode

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#7107]
I noticed after looking at the new release for PHPBB they added mysqli_report(MYSQLI_REPORT_OFF);  to handle mysqli errors being outputted to the screen which is the default for PHP 8.1 now...  https://wiki.php.net/rfc/mysqli_default_errmode.

Looks like you can do set before the connection is set.

**Comment by Sesquipedalian** [comment]
We should address this in SMF 2.0 as well.
