### ISSUE TITLE
undefined function matchPackageVersion()

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#7112]
#### Description
When testing with my mod Themes Demo this error message came up. 

> Fatal error: Uncaught Error: Call to undefined function matchPackageVersion() in /var/www/html/smf21rc/Sources/Subs-Themes.php:275

### Steps to reproduce
1. I checked if a theme with a low version is to be installed (theme-info/install/@for).

### Environment (complete as necessary)
- Version/Git revision:  https://github.com/SimpleMachines/SMF2.1/pull/6998/commits/c7ada60da0a0792a8cfa4b58465d807fb4180a40
- Database Type: MySQL
- Database Version: 5.7.35
- PHP Version: 7.4.24

### Additional information/references
https://www.simplemachines.org/community/index.php?topic=579234.0

In Subs-Themes.php line 273  this should be missing:
`require_once($sourcedir . '/Subs-Package.php');`

Change this
```
	// The theme isn't compatible with the current SMF version.
	if (!$install_versions || !matchPackageVersion($the_version, $install_versions))
	{
		remove_dir($path);
		fatal_lang_error('package_get_error_theme_not_compatible', false, SMF_FULL_VERSION);
	}
```
to
```
	// The theme isn't compatible with the current SMF version.
	require_once($sourcedir . '/Subs-Package.php');
	if (!$install_versions || !matchPackageVersion($the_version, $install_versions))
	{
		remove_dir($path);
		fatal_lang_error('package_get_error_theme_not_compatible', false, SMF_FULL_VERSION);
	}

```
This fixes the error in my test forum.

**Comment by BrickOzp** [comment]
I can't reproduce this problem.
I downloaded the SF-Themes-Demo.zip from https://custom.simplemachines.org/index.php?mod=4253
I have installed it and didn't see the problem.
Should I do something else?

The only error I see is
Undefined index: thdo_page_title in Subs-Themesdemo.php (Line 121)
But that is in the mod

**Comment by wintstar** [comment]
I have completely rebuilt the mod SF-Themes-Demo and added new features. I also use core functions for the mod. When checking the function get_theme_info($path) https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Themes.php#L228  got this error.

**Comment by BrickOzp** [comment]
Could you share the mod where this happens?

**Comment by wintstar** [comment]
I wanted to use this function to read the theme_info.xml file and store the data in a table created for the mod in the database.In the current mod version this function is not yet included. But I have created my own function to read out the data. I am currently finishing a new version of the mod.
