### ISSUE TITLE
Answer message disappears, post failed

### ISSUE THREAD

**Issue by woodholly** [SimpleMachines/SMF#7121]
#### Description
Forum users complain that:
1) Sometimes when they write answer to the topic, and there is (probably) new message has been posted to the topic, page reloads and written text disappears.
2) Sometimes after writing new message and clicking Post, message disappears without a trace and without errors/warnings.

### Steps to reproduce
This is hard to reproduce bug. Have you guys know why this happens ?
Probably related to new message notifications...

### Environment (complete as necessary)
- Version/Git revision: RC3 (large forum and I can't check RC4 yet)
- Database Type: Mariadb
- Database Version: 10.3.31
- PHP Version: 7.3.29
Drafts feature disabled.

**Comment by Sesquipedalian** [comment]
We'll need information about how to reproduce this before any further steps can be taken.

**Comment by woodholly** [comment]
Not happened since that time. I think this issue can be closed.
