### ISSUE TITLE
SAVE in admin > Server Settings causes error

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#7127]
#### Description
.../index.php?action=admin;area=serversettings;sa=general;save
.../Sources/ManageServer.php (Line 203)

Type of error: General
Error message
8: Uninitialized string offset: 3
```
201: | foreach ($config_vars as $config_var)
-- | --
202: | {
==>203: | if ($config_var[3] == 'text' && !empty($_POST[$config_var[0]]))
204: | $_POST[$config_var[0]] = $smcFunc['normalize']($_POST[$config_var[0]]);
205: | }
```

### Steps to reproduce
1. go to admin > Server Settings
2. Click Save

### Environment (complete as necessary)
SMF 2.1 RC4 updated from GitHub at 1555EDT on 18-OCT

**Comment by sbulen** [comment]
I think this was caused by #7102
