### ISSUE TITLE
Slow query on Calendar

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7140]
#### Description
Just going to drop the query/explain here
```
SELECT id_member, real_name, YEAR(birthdate) AS birth_year, birthdate
FROM smf_members
WHERE MONTH(birthdate) != 0
   AND DAYOFMONTH(birthdate) != 0
   AND YEAR(birthdate) <= 2021
   AND (
      DATE_FORMAT(birthdate, '2021-%m-%d') BETWEEN '2021-12-01' AND '2021-12-31'
   )
   AND is_activated = 1
in /Sources/Subs-Calendar.php line 58, which took 1.30696106 seconds at 4.21728086 into request.
id	select_type	table	partitions	type	possible_keys	key	key_len	ref	rows	filtered	Extra
1	SIMPLE	smf_members		ref	is_activated	is_activated	1	const	286475	100.00	Using where
```

### Steps to reproduce
1. httpx://www.simplemachines.org/community/index.php?action=calendar;viewlist;year=2021;month=11;day=01

### Environment (complete as necessary)
- Version/Git revision:  b11f632ddb0912d18c3d456f68e8d653b45090fb

### Additional information/references
https://stackoverflow.com/questions/40252101/index-on-date-field-and-month-year-functions
Suggests instead of using YEAR, we can use the range, which will hit a index (if we have one)

If we supported the min of MySQL 5.7, we could use virtual columns
https://stackoverflow.com/questions/50939499/how-to-optimize-mysql-group-by-with-date-format
Our min seems to be set to 5.6.

Marking this as 2.1.0 for now, because we can't be fixing indexes after 2.1.0 easily..

**Comment by albertlast** [comment]
this is a mysql issue,
for pg setup a faster version of the query is used:
```sql
 SELECT id_member, real_name, YEAR(birthdate) AS birth_year, birthdate
 FROM smf_members
 WHERE YEAR(birthdate) != '1004'
    AND MONTH(birthdate) != 0
    AND DAYOFMONTH(birthdate) != 0
    AND (
       indexable_month_day(birthdate) BETWEEN indexable_month_day('2021-11-01'::date) AND indexable_month_day('2021-11-08'::date)
    )
    AND is_activated = 1
```
this used the index: smf_members_person_birthday_idx
``in ...\Sources\Subs-Calendar.php line 85, which took 0.00068402 seconds at 0.01782894 into request.``

**Comment by jdarwood007** [comment]
I hate having PG only queries.  It makes development so much more complicated and more work to maintain the code base.  I would love if we had a cross platform solution.

That said, if its what we have to do to fix postgres, then I guess.   Does it also perform poorly?

**Comment by sbulen** [comment]
We should not use pg only queries, other than as constructed via the smcFunc abstraction layer.

**Comment by albertlast** [comment]
Well this decision was maded by the project,
by defining mysql 5.6 which got released in 2013,
(this optimization are from a time where mysql 5.0 got supported from 2005),
so you got mysql ancient release and hope that it same capable as newer release of other product.

This decision implies also the recommendation from the project it self,
for small/non-professional setup to use mysql and for big/professional setup to use pg.

I follow you decision and was searching for performance issue,
try to find general solution but when i was not able,
i choose pg specific solution since performance issue only happen in big setups.

Instead of talking how to cripple pg,
you should come up first with a solution for mysql and
than we could look into for pg.

**Comment by sbulen** [comment]
I think the birthday query needs work, and the birthday edit & storage as well.  

First off, it needs some range controls.  You can pull up the calendar and ask for all birthdays from Oct 2020-Oct2021 - and get ***all*** birthdays in your forum...  Triggering a WSOD, and likely a nasty query.  We need to limit this.

January 1 is fun to look at...  Since we're in strict mode, mm & dd are plugged with 1 on unspecified birthdays.  So...  Just looking at 1/1 can also WSOD/nasty query a large forum.  

The 1/1 birthday mailer is going to be fun...

We need to rethink allowed dates given the strict mode restrictions.  In 2.0 & 2.1, we currently allow users to specify yyyy **_and/or_** mmdd.  If only yyyy is specified, they get a 1/1 birthday.  Which is indistinguishable from a real 1/1 birthday.  

Note also that a completely unspecified birthday has 1/1 as well.  Which is indistinguishable from a real 1/1 birthday with no year specified.

**Comment by albertlast** [comment]
Alternative solution,
you introduce a new column "next birthday",
which safe the information when a person got his next day.
Based on this you could easy work with a classic index access.

**Comment by sbulen** [comment]
We may need to do away with strict mode.

The problem is that 0 _meant_ something: "I'd rather not say".  That info is lost upon upgrade.

Or, only have one unspecified value.  No more specifying yyyy without mmdd, or mmdd without yyyy.  That could work.

**Comment by Sesquipedalian** [comment]
I would very much prefer not to make changes to the database structure at this point. Adding indices would be acceptable, but adding new columns should not happen unless there's no other option.

> We may need to do away with strict mode.
> 
> The problem is that 0 _meant_ something: "I'd rather not say".  That info is lost upon upgrade.
> 
> Or, only have one unspecified value.  No more specifying yyyy without mmdd, or mmdd without yyyy.  That could work.  

I agree that it would be better to simplify this by not having unspecified values. But what would we do with existing partial values during upgrade? Delete the partial data so that it is reset to the default value? Fill in the missing component(s) with arbitrary values?

**Comment by albertlast** [comment]
I guess that db structur change not wanted, lead us in the situation where we are now.

**Comment by sbulen** [comment]
Thinking aloud here...   

In 2.0, I see **_a lot_** of no year specified, e.g., 0004-11-07.   

I have seen unspecified mmdd before, e.g., 1961-00-00, helping folks with upgrader issues.  But I *think* those are very rare (none on my forum).  I'm not sure you can do this with recent versions of SMF 2.0.x.  But they're out there.  Given they're rare, maybe the only ones we need to punt on.

E.g., we can migrate the no-years properly, e.g., 0004-11-07 becomes 1004-11-07.  

Unspecified remains unspecified, e.g., 0001-01-01 becomes 1004-01-01.  

But zeroes anywhere else become 1004-01-01.  And we exclude 1004-01-01 from birthday mailers, calendar views, etc.

**Comment by jdarwood007** [comment]
Why not null?

**Comment by sbulen** [comment]
It's NOT NULL...

**Comment by live627** [comment]
I think  I might have a temporary solution.

```diff
@@ -39,18 +39,13 @@ function getBirthdayRange($low_date, $high_date)
 		$result = $smcFunc['db_query']('birthday_array', '
 			SELECT id_member, real_name, YEAR(birthdate) AS birth_year, birthdate
 			FROM {db_prefix}members
-			WHERE MONTH(birthdate) != {int:no_month}
-				AND DAYOFMONTH(birthdate) != {int:no_day}
-				AND YEAR(birthdate) <= {int:max_year}
+			WHERE birthdate != \'1004-01-01\'
 				AND (
 					DATE_FORMAT(birthdate, {string:year_low}) BETWEEN {date:low_date} AND {date:high_date}' . ($year_low == $year_high ? '' : '
 					OR DATE_FORMAT(birthdate, {string:year_high}) BETWEEN {date:low_date} AND {date:high_date}') . '
 				)
-				AND is_activated = {int:is_activated}',
+				AND is_activated = 1',
 			array(
-				'is_activated' => 1,
-				'no_month' => 0,
-				'no_day' => 0,
 				'year_low' => $year_low . '-%m-%d',
 				'year_high' => $year_high . '-%m-%d',
 				'low_date' => $low_date,
```
| id  | select_type | table | type | possible_keys | key | key_len | ref | rows | Extra |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1   | SIMPLE | smf_members | range | idx_birthdate | idx_birthdate | 3   |     | 365 | Using index condition |
```json
{
  "query_block": {
    "select_id": 1,
    "r_loops": 1,
    "r_total_time_ms": 0.1823,
    "table": {
      "table_name": "smf_members",
      "access_type": "range",
      "possible_keys": ["idx_birthdate"],
      "key": "idx_birthdate",
      "key_length": "3",
      "used_key_parts": ["birthdate"],
      "r_loops": 1,
      "rows": 365,
      "r_rows": 30,
      "r_total_time_ms": 0.1648,
      "filtered": 100,
      "r_filtered": 100,
      "index_condition": "smf_members.is_activated = 1 and smf_members.birthdate &lt;&gt; '1004-01-01' and date_format(smf_members.birthdate,'2021-%m-%d') between '2021-12-01' and '2021-12-31'"
    }
  }
}
```
@jdarwood007 thoughts?

**Comment by albertlast** [comment]
on pg query version when the mention change is applied
changed  from ~ 0.060 to ~0.050 ms

**Comment by sbulen** [comment]
Note this comment recently left on an earlier related issue:
https://github.com/SimpleMachines/SMF2.1/issues/5911#issuecomment-1001154604

Quote:
This is also an issue in the Calendar if you have birthdays set to display. Interestingly, there was a year check there in 2.0, but removed in 2.1. I fixed it on my forum by copying it from the 2.0 code and changing year_one to '1004'. I don't have the code checked out so I can't submit a pull request, but here's the modified query.

The quick fix in Subs-Calendar.php, getBirthdayRange():

$result = $smcFunc['db_query']('birthday_array', '
			SELECT id_member, real_name, YEAR(birthdate) AS birth_year, birthdate
			FROM {db_prefix}members
			WHERE YEAR(birthdate) != {string:year_one}
			    AND MONTH(birthdate) != {int:no_month}
				AND DAYOFMONTH(birthdate) != {int:no_day}
				AND YEAR(birthdate) <= {int:max_year}
				AND (
					DATE_FORMAT(birthdate, {string:year_low}) BETWEEN {date:low_date} AND {date:high_date}' . ($year_low == $year_high ? '' : '
					OR DATE_FORMAT(birthdate, {string:year_high}) BETWEEN {date:low_date} AND {date:high_date}') . '
				)
				AND is_activated = {int:is_activated}',
			array(
				'is_activated' => 1,
				'no_month' => 0,
				'no_day' => 0,
                'year_one' => '1004',
                'year_low' => $year_low . '-%m-%d',
				'year_high' => $year_high . '-%m-%d',
				'low_date' => $low_date,
				'high_date' => $high_date,
				'max_year' => $year_high,
			)
		);

_Originally posted by @sportfogadas in https://github.com/SimpleMachines/SMF2.1/issues/5911#issuecomment-1001154604_

**Comment by sbulen** [comment]
From:
https://www.simplemachines.org/community/index.php?topic=579789.0;topicseen

Quote:
I'm using SMF 2.1 RC4+ (commit ed0f841)
Today I have noticed that Calendar displays list of all users with Upcoming Birthday on 1 January 2022.
The list is displayed in Board index at "Upcoming Birthdays" section, and within Calendar (either on 'List' or 'Month' view)
**_But almost all users have no birthday added in their profiles_**.

https://bg-nacionalisti.org/BNF/index.php?action=calendar

The setting in Admin panel is Upcoming Bithdays to be displayed in advance of 31 days.

**Comment by jdarwood007** [comment]
> ```diff
> ```diff
> @@ -39,18 +39,13 @@ function getBirthdayRange($low_date, $high_date)
>  		$result = $smcFunc['db_query']('birthday_array', '
>  			SELECT id_member, real_name, YEAR(birthdate) AS birth_year, birthdate
>  			FROM {db_prefix}members
> -			WHERE MONTH(birthdate) != {int:no_month}
> -				AND DAYOFMONTH(birthdate) != {int:no_day}
> -				AND YEAR(birthdate) <= {int:max_year}
> +			WHERE birthdate != \'1004-01-01\'
>  				AND (
>  					DATE_FORMAT(birthdate, {string:year_low}) BETWEEN {date:low_date} AND {date:high_date}' . ($year_low == $year_high ? '' : '
>  					OR DATE_FORMAT(birthdate, {string:year_high}) BETWEEN {date:low_date} AND {date:high_date}') . '
>  				)
> -				AND is_activated = {int:is_activated}',
> +				AND is_activated = 1',
>  			array(
> -				'is_activated' => 1,
> -				'no_month' => 0,
> -				'no_day' => 0,
>  				'year_low' => $year_low . '-%m-%d',
>  				'year_high' => $year_high . '-%m-%d',
>  				'low_date' => $low_date,
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

I'm testing this live and it resolves white page issues from trying to load way too many members with default birthdates.
Can we get that sent in as a PR?

**Comment by live627** [comment]
- https://github.com/SimpleMachines/SMF2.1/pull/7201

**Comment by sbulen** [comment]
What is remaining on this @jdarwood007 ?  It seems like the @live627 PR was the 90% fix?

Do you think we need a range check on the list view?
![image](https://user-images.githubusercontent.com/23568484/148655419-d84317e0-fccd-4f33-aca0-f00b4a2752c7.png)

**Comment by jdarwood007** [comment]
Yes.  I was testing the line above, but the PR just cleans it up properly.
