### ISSUE TITLE
Calendar view start & end dates, display truncated for long month names

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7141]
#### Description
https://github.com/SimpleMachines/SMF2.1/pull/6636

I can still reproduce this on sm website: https://www.simplemachines.org/community/index.php?action=calendar;viewlist;year=2021;month=11;day=01

if I get rid of the `width: 100px`, the calculated width is 116px.  Can we just unset it and let the browser handle it?  There is a max-width that seems to be doing the work and it looks fine.

related topic: https://www.simplemachines.org/community/index.php?topic=579254.msg1;topicseen#new

**Comment by Sesquipedalian** [comment]
Yeah, it should be fine. It looks like jquery-ui.datepicker.min.js sets the `size` attribute on the input fields as part of setting up the date picker, which works well enough.

**Comment by DiegoAndresCortes** [comment]
We should remove the `width: 100px` for 2.1 regardless of other later changes on this imo
