### ISSUE TITLE
Token error on Recount all forum totals and statistics

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7150]
#### Description
--Description Here--

### Steps to reproduce
1. Go to Forum Maintenance
2. Click "Recount all forum totals and statistics"
3. When timeout protection occurs after the countdown a token error is generated.

### Environment (complete as necessary)
- Version/Git revision: 5d414f4c4a1863335d77c7b2ed503c511354388c
- Database Type:
- Database Version:
- PHP Version: 8.0

### Additional information/references
A very old issue based on this is #2876

**Comment by Sesquipedalian** [comment]
At what step in the overall recount process did you see this occur? You can check that by looking at the `step` parameter in the URL.

**Comment by jdarwood007** [comment]
/index.php?action=admin;area=maintain;sa=routine;activity=recount;step=0;start=50000;

Its a test forum and was Populated with the populate tool.

**Comment by jdarwood007** [comment]
So debugging this.  The session token is not being updated.  Via some careful testing, even though we are updating the $_SESSION, it i not being written and reverts on the next page load.  I'm on PHP 8.0 and using database driven sessions.
If I disable database driven sessions it works.

I ran out of time to test anymore.  But I'm on three trails

1. Database driven sessions are not being written fast enough or in time before the request is handled.
2. The replace function isn't working well and isn't updating the value stored in the database.
3. I'm on MariaDB.  So its possible it doesn't do the replace into properly either.

**Comment by jdarwood007** [comment]
I was able to figure it out.  The way we saved the token into the continue_post_data caused issues.  But the not_done_token setting seems to work fine.  I cleaned up the logic to generate the token earlier in the process to reduce code complexity/copies.
