### ISSUE TITLE
Board Report terminology

### ISSUE THREAD

**Issue by LexArma** [SimpleMachines/SMF#7153]
Regular Members are called Full Members on the Boards access report. 
(Reports showing the current settings and access levels for each of boards on your forum.)
This applies to 2.0 and 2.1 both - and is confusing as heck, since we include a default post count group called Full Member as well.

Reported for 2.0 separately https://github.com/SimpleMachines/SMF2.0/issues/244

**Comment by DiegoAndresCortes** [comment]
Should they be called "Regular Members"? Or what's the other term used?

**Comment by LexArma** [comment]
Permissions uses "Regular members" for ungrouped users, and Full Member is one of the default post count groups. 
So "Regular members" would be correct IMO. 

This is the Boards report with the wrong name:
<img width="880" alt="BoardsReport" src="https://user-images.githubusercontent.com/39050447/150406242-6d311ddd-a845-4677-8e54-26cd69157885.PNG">

Here you can see the groups with access, and can see Full Members is not checked.
<img width="606" alt="AllowedGroups" src="https://user-images.githubusercontent.com/39050447/150406493-b4c18d5b-1c18-4452-becc-03b980b1aa7c.PNG">

This is the Board Permissions report which uses the same (correct) terms as all other areas.
<img width="885" alt="BoardPermissionsReport" src="https://user-images.githubusercontent.com/39050447/150406248-02d6bba2-9316-42bd-820e-6c03b04a1c72.PNG">

**Comment by DiegoAndresCortes** [comment]
Question: If you check Full Member too, does it duplicate?
I don't think this is language related, at least not completely

**Comment by DiegoAndresCortes** [comment]
Since you mention it's the same on 2.0 I guess there's no reliable way to know why it's like this, but surely looks to be the wrong term.
