### ISSUE TITLE
Setting your email to an invalid one locks you out of the forum

### ISSUE THREAD

**Issue by MisterVector** [SimpleMachines/SMF#7158]
Recently I went to change my email address on my account at simplemachines.org. However, I accidentally set it to an invalid email. The forum attempted to send me a link to re-activate my account. Obviously I never got the email. Whenever I try to sign in to the forum I get this:

![image](https://user-images.githubusercontent.com/437096/142687933-e0141351-a0f8-4abe-a063-552754299cab.png)

There should be some behavior changes that allows you to sign in with the option to change your email, if you had set it to something invalid. I'm not sure what would be the best option going forward as I haven't thought too much about it but I wanted to alert you guys to this issue anyways.

**Comment by LexArma** [comment]
I agree this can be a bit of a problem. Perhaps, save the old email address until the new one has been confirmed, and allow to reverse the change until the new address has been confirmed. Just an option that came to mind.

**Comment by Sesquipedalian** [comment]
Er, did you click the "Did you miss your activation email?" link, @MisterVector?

If you do, it takes you to `index.php?action=activate`, which shows a form that will allow you to enter a new email address if you need to do so.
