### ISSUE TITLE
Smiley (Default) is set to :cry

### ISSUE THREAD

**Issue by mobasuite** [SimpleMachines/SMF#7160]
#### Description
as topic, not complicated

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by sbulen** [comment]
Cannot reproduce at all, either on installation or upgrade.  

Please provide more info.

**Comment by mobasuite** [comment]
See the first smiley, it's the same as (cr
![Screenshot 2021-11-22 064341](https://user-images.githubusercontent.com/59516556/142807022-618a4b97-bb2c-459a-9e9a-2f80204d652f.png)
y)

**Comment by mobasuite** [comment]
This is on a freshly upgraded database.

**Comment by BrickOzp** [comment]
Upgraded from what?

**Comment by mobasuite** [comment]
An SMF database installation also RC4

**Comment by live627** [comment]
Check the smiley order in  the admin panel.

**Comment by mobasuite** [comment]
The first smiley has an incorrect image

**Comment by mobasuite** [comment]
fixed
