### ISSUE TITLE
Language string "attachment_thumb_memory_note" missing

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#7163]
Language string "attachment_thumb_memory_note" missing.

https://github.com/SimpleMachines/SMF2.1/blob/cd5705c0c78a85ee22bfebfbfb51585deda1c29e/Sources/ManageAttachments.php#L171

**Comment by wintstar** [comment]
Added on 27 March 2012. Again, I think the language string was missing.

> ! Memory check option added to ACP attachment settings, attempts to f…
> …ix white screen from occurring with boarder case images.

https://github.com/SimpleMachines/SMF2.1/commit/b062f89c2232c6f8d66436b954ee969a7a1d8e6e

**Comment by DiegoAndresCortes** [comment]
What's the language string we would want to add for the note, or should we remove the warning?
e.g If disabled, memory is limited to 128M

https://github.com/SimpleMachines/SMF2.1/blob/54b854bba9abddf1f351ab48eed0edc347027366/Sources/Subs-Graphics.php#L288-L293
