### ISSUE TITLE
 PHP 8.1: strftime() is deprecated 

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#7167]
> The strftime() and gmstrftime() functions exhibit similar issues as strptime(), in that the formats they support, as well as their behavior, is platform-dependent. Unlike strptime(), these functions are available on Windows, though with a different feature set than on Linux. Musl-based distributions like Alpine do not support timezone-related format specifiers correctly. These functions are also locale-based, and as such may exhibit thread-safety issues.
> Once again date() or DateTime::format() provide portable alternatives, and IntlDateFormatter::format() provides a more sophisticated, localization-aware alternative.

Ref: https://wiki.php.net/rfc/deprecations_php_8_1#strftime_and_gmstrftime

> The strftime() and gmstrftime() functions have been deprecated in favor of
> date()/DateTime::format() (for locale-independent formatting) or
> IntlDateFormatter::format() (for locale-dependent formatting).

Ref: https://github.com/php/php-src/blob/1cf4fb739f7a4fa8404a4c0958f13d04eae519d4/UPGRADING#L379-L381

Other references:

 * https://www.php.net/manual/en/function.strftime.php (for the old format string characters)
 * https://www.php.net/manual/en/datetime.format.php (for the new format string characters)
 * https://www.php.net/manual/en/datetime.construct.php (see Example 2 for a Unix timestamp code sample)

Verification of the principle: https://3v4l.org/MCURg

---

Instances of strftime() in the code: https://github.com/SimpleMachines/SMF2.1/search?q=strftime

**Comment by Sesquipedalian** [comment]
Ugh. 

Well, we can replace all calls to strftime() with calls to timeformat() and then rewrite timeformat() to use the non-deprecated alternatives.
