### ISSUE TITLE
User alerts could cause performance issues

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7169]
#### Description
```
/**
 * Fetch the alerts a member currently has.
 *
 * @param int $memID The ID of the member.
 * @param mixed $to_fetch Alerts to fetch: true/false for all/unread, or a list of one or more IDs.
 * @param array $limit Maximum number of alerts to fetch (0 for no limit).
 * @param array $offset Number of alerts to skip for pagination. Ignored if $to_fetch is a list of IDs.
 * @param bool $with_avatar Whether to load the avatar of the alert sender.
 * @param bool $show_links Whether to show links in the constituent parts of the alert meessage.
 * @return array An array of information about the fetched alerts.
 */
function fetch_alerts($memID, $to_fetch = false, $limit = 0, $offset = 0, $with_avatar = false, $show_links = false)
```

The $limit allows 0 for all.  The code goes on to do do just that.  If you do 0, you get all of them.  If you somehow have a ton of alerts (such as in a very active forum and alerts tagged on many boards/topics, you could possibly get a bunch of alerts tagged.  

Now combine this with the alerts_popup area/code:
```
	$counter = isset($_REQUEST['counter']) ? max(0, (int) $_REQUEST['counter']) : 0;

	$context['unread_alerts'] = array();
	if ($counter < $cur_profile['alerts'])
	{
		// Now fetch me my unread alerts, pronto!
		require_once($sourcedir . '/Profile-View.php');
		$context['unread_alerts'] = fetch_alerts($memID, false, !empty($counter) ? $cur_profile['alerts'] - $counter : 0, 0, !isset($_REQUEST['counter']));
```

Essentially it is told to load every alert the member has.  Even if that member has lets say 100,000+ alerts.

### Steps to reproduce
1. Generate 100,000+ alerts for a  single member.  You can enable admins to get notifications for new members and then have Populate.php generate a ton of new members.
2.  Hit the url a many times: action=profile;area=alerts_popup;ajax
3. Server will have performance issues.

### Environment (complete as necessary)
- Version/Git revision: latest
- Database Type: mysql
- Database Version: mariadb 10.0
- PHP Version: 8.0

### Additional information/references
This should be fixed before final.

I would like to propose the following changes
In fetch_alerts:
```
	$limit = min((int) $limit > 0 ? (int) $limit : 1000, 1000);
```
This will ensure we can't use more than 1000 ever in any call to fetching alerts.  Pagination will occur if you go to the full alerts page.

In alerts_popup
```
		$limit = min(!empty($counter) ? $cur_profile['alerts'] - $counter : 25, 25);
		$context['unread_alerts'] = fetch_alerts($memID, false, $limit, 0, !isset($_REQUEST['counter']));
```
This ensures the popup is limited to 25 items.  25 is more than enough for a alerts popup that doesn't have pagination.

Any feedback on this?

**Comment by frandominguezl** [comment]
I would even lower a little bit more the popup items. We can maybe indicate somehow that they might be more alerts, and a link to  the all alerts page.

**Comment by vort7u** [comment]
I'm not sure but I think it's related to the many errors I have with some users, they probably have a lot of notifications.

`Database error: Out of range value for column 'alerts' at row 1`

**Comment by albertlast** [comment]
What is the idea of define a hard max limit?
Should be this not a task from forum admin to do so?

**Comment by jdarwood007** [comment]
If it should be a defined option, then we can do that.  I would foresee it not being changed much though.  But the hard limit of 1000 seems sensible to prevent calls to too many items at once.

**Comment by Sesquipedalian** [comment]
Rather than a limit of 25 for the pop-up, I suggest 10 and then some special handling to show "9+" in the UI if we find 10. 

In addition to the performance improvement, this will also make theming easier because the counter span in the UI will never be more than two characters wide.

**Comment by jdarwood007** [comment]
The counter will still show the number of unread alerts.  The popup window should only show unread alerts (if it doesn't already) in my opinion.

**Comment by Sesquipedalian** [comment]
Fair enough. I misunderstood.
