### ISSUE TITLE
mysqli_affected_rows() expects parameter 1 to be mysqli, boolean given

### ISSUE THREAD

**Issue by BrickOzp** [SimpleMachines/SMF#7176]
#### Description
Error found in error log

mysqli_affected_rows() expects parameter 1 to be mysqli, boolean given

#0: smf_error_handler()
Called from unknown on line -1
#1: mysqli_affected_rows()
Called from /Sources/Subs-Db-mysql.php on line 513
#2: smf_db_affected_rows()
Called from /Sources/Session.php on line 242
#3: sessionGC()
Called from unknown on line -1
#4: session_start()
Called from /Sources/Session.php on line 81
#5: loadSession()
Called from /index.php on line 184

### Steps to reproduce
1. Don't know
2. 

### Environment (complete as necessary)
- Version/Git revision: 12bf435a8
- Database Type: MySql
- Database Version:
- PHP Version: 7.1

### Additional information/references

**Comment by BrickOzp** [comment]
In Session.php

$session_update = $smcFunc['db_query']('', '
--
235: | DELETE FROM {db_prefix}sessions
236: | WHERE last_update < {int:last_update}',
237: | array(
238: | 'last_update' => time() - $max_lifetime,
239: | )
240: | );
241: |  
==>242: | return ($smcFunc\['db_affected_rows']( $session_update ) == 0 ? false : true);


smf_db_affected_rows() -> mysqli_affected_rows() expects a connection, but here we pass it a query result.

**Comment by sbulen** [comment]
This usually means there was a connection error.  So connect returns false instead of a resource, and when you try to use that result in a query, this message pops up.

You need to figure out why you couldn't connect...
