### ISSUE TITLE
PHP 8.1 - Postgres issue - Automatic fetching of PostgreSQL connection is deprecated

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7190]
#### Description
I've started testing under php 8.1.  No major mysql issues, but there are some pg issues.  

First one is this: 
![image](https://user-images.githubusercontent.com/23568484/146597392-adb48f94-731a-45e0-a576-8296ab91a0da.png)

### Steps to reproduce
1. Run pg under php 8.1

### Environment (complete as necessary)
- Version/Git revision: current
- Database Type: postgres
- Database Version: 14.1
- PHP Version: 8.1.0

### Additional information/references
See additional discussion under: #7177 

See article: https://php.watch/versions/8.1/PgSQL-resource

**Comment by albertlast** [comment]
are more function effected or only pg_escape_string?

**Comment by sbulen** [comment]
I have not tested extensively.  This is the only issue I've seen thus far, but it affects a lot of things, e.g., you cannot complete an install.   (Actually, you can, but you get thousands of errors on screen...)

If you have a working pg 2.1 forum, and upgrade php to 8.1, many functions work fine, e.g., you can post and even run ACP and scheduled tasks, etc.  But you get a lot of errors in the logs due to this, and this issue appears to prevent updates to settings.  

So we will know more once we are past this issue...
