### ISSUE TITLE
Phrasing of $txt['admin_basic_settings']

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#7191]
Via [Crowdin](https://crowdin.com/translate/simple-machines-21-beta/all/en-deinf?filter=basic&value=0#20):
https://github.com/SimpleMachines/SMF2.1/blob/cd5705c0c78a85ee22bfebfbfb51585deda1c29e/Themes/default/languages/Admin.english.php#L25

The user writes: "The word 'very' in the source string is not needed because there is not much difference between careful and very careful"

I tend to agree.

**Comment by LexArma** [comment]
While it's true that the "very" in there is probably superfluous, I do think it is there intentionally to highlight and emphasize the need to be careful. Sometimes too much is not enough, as a quick glance on our support boards may show. :P

**Comment by Sesquipedalian** [comment]
Warning says:
"Be careful with these settings..."
Sesquipedalian thinks:
"Make sure there are no typos before saving."

Warning says:
"Be very careful with these settings..."
Sesquipedalian thinks:
"Don't mess with these settings without understanding exactly what they do. Also, don't make any typos."

The latter is what we want.
