### ISSUE TITLE
vsprintf error on noexistant profile

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7199]
#### Description
I attempted to view a profile of a non-existent user.

( ! ) Fatal error: Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, int given in /Sources/Errors.php on line 231
( ! ) TypeError: vsprintf(): Argument #2 ($values) must be of type array, int given in /Sources/Errors.php on line 231
--
1 | 0.0000 | 372800 | {main}( ) | .../index.php:0
2 | 0.0033 | 597560 | ModifyProfile( $post_errors = ??? ) | .../index.php:195
3 | 0.0039 | 640328 | fatal_lang_error( $error = 'not_a_user', $log = FALSE, $sprintf = 404, $status = ??? ) | .../Profile.php:54
4 | 0.0040 | 642224 | vsprintf( $format = 'The user whose profile you are trying to view does not exist.', $values = 404 )

**Comment by sbulen** [comment]
I really don't think this is a 2.1.0 requirement.  Could we remove or change the milestone?

**Comment by Sesquipedalian** [comment]
This was fixed by #7329.
