### ISSUE TITLE
PHP 8, undefined function shell_exec & hostname lookups

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7203]
#### Description
It has been reported in the forum lately that folks trying php 8 are receiving "Call to undefined function shell_exec()".

When doing hostname lookups, SMF first attempts shell_exec, and if that fails, it goes on to try other things.  It ignores the errors with an "@shell_exec()".  

This appears to be another facet of the new php 8.x behavior for the error suppressor, "@".  

We need to either rethink that logic, or, treat the shell_exec fail differently in the error routine.  

This logic is the same in 2.1 & 2.0.

### Additional information/references
https://www.simplemachines.org/community/index.php?topic=580071.0

**Comment by sbulen** [comment]
The workaround is to disable hostname lookups, but you really shouldn't have to do so...

**Comment by jdarwood007** [comment]
We can wrap it in a function_exists and a try/catch.  Should let it gracefully handle it.
PHP has moved how the @ operator works.  I think you can get around it by doing error_reporting(0), but I can't recall.

https://www.php.net/releases/8.0/en.php
>The @ operator no longer silences fatal errors.

**Comment by sbulen** [comment]
Yeah, we had to make some other changes a while back: https://github.com/SimpleMachines/SMF2.1/pull/7161/files

But that was for the upgrader only.

It may be sufficient to the main error handler as well:
https://github.com/SimpleMachines/SMF2.1/blob/4502804a886115d25e393b64d05f7b2e3f90c3dd/Sources/Errors.php#L251

**Comment by tinoest** [comment]
error_reporting set to 0 just silences the error, the script still halts there. 

If you want to continue on then it need's to be in a try/catch, other option is function_exists check first. 

e.g.
`try {
echo @shell_exec('uname -a');
} catch (Error $e) {
null;
}`

**Comment by sbulen** [comment]
Actually the script continues - prior to php8.  And if you have an error handler, you can control your response.

A lot of that changes with PHP8.  Prior to PHP8, the error handler was passed an error_reporting level of 0 for suppressed errors.  That is no longer the case for php8+.

I think we need to duplicate the fixes we made to the upgrader error handler to the main smf error handler (links above).

More here:
https://php.watch/versions/8.0/fatal-error-suppression

**Comment by tinoest** [comment]
The link you provided states **All of these errors, if raised, halts the rest of the application from being run. The difference in PHP 8.0 is that the error message is not silenced, which would have otherwise resulted in a silent error.**

I tried it on my test install here and it halts the application at that point. So either I am doing something wrong (entirely possible) or something else is going on.

Adding a try/catch block around it allow's it to continue. function_exists is probably the better option mind.

**Comment by sbulen** [comment]
And, as noted above, you can alter the behavior in the error handler.  And they show you how.

**Comment by tinoest** [comment]
> And, as noted above, you can alter the behavior in the error handler. And they show you how.

Then they say 

> To reiterate, both of these approaches will stop the execution of the application; only the error will be hidden.

I tried setting the error_reporting(0) and it didn't work. SMF halted at that point.

If you do get it working just setting the error_reporting, please let me know how as it would be helpful to understand.

**Comment by sbulen** [comment]
I believe they are making a distinction with some errors that are going to stop no matter what - e.g., E_PARSE, E_COMPILE, etc.  They are careful to add the words "might" and "all" here & there, e.g., "might not suppress all the errors"...  

I.e., some do, some don't...  As always, testing would be needed.

But, for example, the @ operator is in use and execution continues with the change to the error handler noted above.  That's working today under php8 (PR #7161 ).

I do agree function_exists would work also - here.  But the error handler would help us address other places, e.g., @ is commonly used with file opens, deletes, etc.

**Comment by tinoest** [comment]
I think we’re talking at cross purposes, I was focusing on the shell_exec error. Only way I can get it to continue as it used to is a try/catch.

Same actually applies for some of those other calls you just mentioned.

They’re tightening up the error handling, which as I maintain PHP applications first written for PHP 4.0 is causing no end of issues, with the jump to PHP 8. If there was a simple fix I’d love to know it 😅

**Comment by jdarwood007** [comment]
I think the error handler fix is appropriate for 2.0, but for 2.1 we should do it properly with a funcion_exists and try/catch.

Just a quick search, there is 350 occurrences of `@[A-z]+\(`
But we only need to worry about @ usage on functions that would generate fatal errors.
So we just need to figure out which functions can generate fatal errors.  The documentation on those pages should help.

Just poking around I have seen a few that mention fatal errors.  Oddly enough, apache_reset_timeout doesn't exist in php documentation anymore.  https://github.com/php/doc-en/commit/89cb55b8608cbe21a6c65c5b06da42fa4f820a94

**Comment by sbulen** [comment]
I suggest the other way around - do the error handler and see how far that gets us.  I expect exceptions to be extremely rare after that - and those extremely rare exceptions must be treated as bugs at that point.  

We have plenty of "@" references in the code, almost all file operations, ob_ calls, ini_ calls and more.  We really do not want to rewrite all of those prior to 2.1 launch.  **_That is an unnecessary and large change in scope..._**

I think the documentation is still inconsistent and inspecific, unfortunately.  I would only rewrite where we see confirmed issues.

**Comment by live627** [comment]
https://www.php.net/manual/en/language.operators.errorcontrol.php

>  Prior to PHP 8.0.0, it was possible for the @ operator to disable critical errors that will terminate script execution. For example, prepending @ to a call of a function which did not exist, by being unavailable or mistyped, would cause the script to terminate with no indication as to why.
