### ISSUE TITLE
Birthdays out of order on calendar

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#7205]
the last date comes first in an otherwise orderly list
![Screenshot 2021-12-28 at 22-46-54 Calendar](https://user-images.githubusercontent.com/431799/147632752-fec8a99a-6328-4a40-8846-899eaca7bdd8.png)

**Comment by jdarwood007** [comment]
This is because the dates are being sent in like this in the array:
```
["2021-01-01"]=>....
["2021-12-29"]=>....
["2021-12-30"]=>....
["2021-12-31"]=>....
["2022-01-02"]=>....
```

I think changing this block of code in Subs-Calendar should do it:
```
		if ($year_low != $year_high)
			$age_year = substr($row['birthdate'], 5) < substr($high_date, 5) ? $year_high : $year_low;
		else
			$age_year = $year_low;
```

to
```
		if ($year_low != $year_high)
			$age_year = substr($row['birthdate'], 5) <= substr($high_date, 5) ? $year_high : $year_low;
		else
			$age_year = $year_low;
```

Thoughts?

**Comment by BrickOzp** [comment]
This happens when there are birthdays on the last day of the range, and like @jdarwood007 has found, those birthdays are listed on the wrong year. The proposed solution works fine.
