### ISSUE TITLE
PHP 8.1 Compatibility 

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7209]
Tracking this as a general task list.  Please comment if we need to add/remove issues.  Marking this as needs to meet 2.1.0.

Pull Requests:
- [x] #7213
- [x] #7192
- [x] #7196
- [x] #7210 
- [x] #7204  
- [x] #7221
- [x] ~#7230~ #7329
- [x] #7231
- [x] #7232

Issues:
- [x] #7212
- [x] #7207
- [x] #7206
- [x] #7195 
- [x] #7190 
- [x] #7187
- [x] #7167 
- [x] #7107 
- [x] #7203 

Anyone with a PHP 8.1 test env, please test as many areas as you can and report issues.

**Comment by sbulen** [comment]
I do not think 8.1 support is a hard requirement for 2.1.0 go-live...  That was never discussed.  

We cannot keep slipping scope.

In all seriousness, 8.2 is slated for a few months away.  Will we add 8.2 to scope of 2.1.0???

**Comment by jdarwood007** [comment]
That is true.  @Sesquipedalian, do you feel we need PHP 8.1 support for 2.1.0 or push it off for 2.1.1?

PHP 8.2 support will also have to come.  I'm not aware of what it deprecated or broke.

**Comment by live627** [comment]
> PHP 8.2 support will also have to come. I'm not aware of what it deprecated or broke.

They just released 8.1 a month ago! 8.2 won't be for another year yet.

**Comment by sbulen** [comment]
> They just released 8.1 a month ago! 8.2 won't be for another year yet.

If we do not change our behavior, we will be having this discussion in 12 months for 2.1.0.

**Comment by live627** [comment]
+5 magic

**Comment by albertlast** [comment]
8.1 look like big hole of work,
so when you plane somekind of release i would say without 8.1 support.

so when a admin want to run 8.1 he had to disable notice about deprecation.

**Comment by jdarwood007** [comment]
I agree.  Lets push this into 2.1.1.  @Sesquipedalian can move it back if he feels it needs to ship into 2.1.0.

We have added a few more PRs/issues already today for 8.1.  So this is a useful thread as is to show how much work we need to do in order to get 8.1 compatible.

**Comment by Sesquipedalian** [comment]
I agree entirely.

**Comment by SugarD-x** [comment]
Did this make it into 2.1.1? I see no mention of it in the announcement, and it shows two tasks still pending here, but it's marked for 2.1.1. If not, it might need the milestone updated.

**Comment by Sesquipedalian** [comment]
Looks like everything on this list is done.

**Comment by jdarwood007** [comment]
Awesome.  Do we have confirmation that PHP 8.1 is functioning with SMF 2.1 now?  I haven't moved up to 8.1  yet on my dev server to confirm.

**Comment by Sesquipedalian** [comment]
Well, I can't reproduce any of the issues on this list. However, I don't currently have a PostgreSQL instance set up for testing, so I am simply trusting that @albertlast has taken care of those issues.
