### ISSUE TITLE
Default avatar

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#721]
As we discussed in #558 having a default avatar would be good.

We don't actually have any icons to use right now - the only ones in the Oxygen set are (clearly) male, nothing neutral there. There's also not a straight female avatar to use, should we want to do that.

I'm not averse to using something else as an avatar but please for the love of $deity let us not use the 'online' icons in Oxygen. They never look like people to me, but I don't really want to say what they do look like ;)

@Labradoodle-360 You mentioned getting a graphic artist, how did that work out?

**Comment by MissAllSunday** [comment]
This is the one I use: https://github.com/MissAllSunday/Breeze/blob/develop/Themes/default/images/breeze/default_user.png I suppose its genderless enough, I don't remember were I found it but I'm sure it is under a permissive license.

**Comment by Arantor** [comment]
It's genderless enough and it wouldn't be hard to make our own like that (even my limited art skills can do that), do others like it?

**Comment by deliciousbamboo** [comment]
>  I don't remember were I found it but I'm sure it is under a permissive license.

Not remembering where is no excuse for IP theft .. but then looking at some of your other questionable commits that may just be normal.  GitbHub does not care if its open source or not, so why should you.

**Comment by MissAllSunday** [comment]
Looks like someone got angry over this... not a big deal I'll just remove it and move on, don't even care if you're the image owner or just a troll.

**Comment by deliciousbamboo** [comment]
>  don't even care if you're the image owner

It was already obvious that you don't care about IP, well at least others, does not take a troll to see that, just one to do it.

**Comment by MissAllSunday** [comment]
...and now is gone.... I'll create a new image and release it as public domain.

**Comment by MissAllSunday** [comment]
There you go.... I license this image with the WTFPL license: http://www.wtfpl.net/about/  no more copyright issues.

And for the record, I apologize to whoever is the copyright holder of the previous image, as an Open Source enthusiastic I did check before using it and as far as I was aware, the image was under a permissive license, I suppose I was wrong...

**Comment by deliciousbamboo** [comment]
> I did check before using it 

That is not what you said earlier, nice attempt to snail away.

As for your license choice its rude and unprofessional but will look great in the credits.

**Comment by MissAllSunday** [comment]
Look, pal, I said I'm sorry, I deleted the image, I'm no longer using said image nor said image will be used for this project. Don't know what else do you want or need.

I, once again, do apologize for using that image, I now have my own image and thats the image I will use from now on, you can of course agree or disagree with how I chose to license my work.

**Comment by Arantor** [comment]
Ah, so this is where all your bile came from, awesome.

We do have a responsibility to be careful about IP ownership, and as far as it was, it was just a suggestion for SMF at this time. Before it was integrated into SMF properly, proper credits and licensing would have been sorted out.

I realise you're upset with MissAllSunday for IP theft, but there is no excuse for making yourself look in the wrong by bashing everything else. It was a mistake, people do make mistakes - even you, I expect - and MissAllSunday has apologised and rectified the mistake. What more would you like us to do, exactly, other than deal with your bile?

**Comment by NanoSector** [comment]
Sorry for disturbing the drama going on, though I don't think the avatar referenced works out well in the 2.1 theme, in the way of the colours which I don't think would match with the rest of the theme. Just dropping my two cents here, anyone who wants them can pick them up.

**Comment by MissAllSunday** [comment]
The default theme isn't the only theme the default avatar will be used, it should be genderless and it shouldn't be theme-specific, considering that very few themes bothers to change the default images, gray and white goes well with most color combinations.

**Comment by NanoSector** [comment]
That's my point, I don't think the avatar would fit well in many themes due to the colour.

**Comment by MissAllSunday** [comment]
What other color do you suggest?  remember it needs to be genderless and you cannot use a specific color combination.

**Comment by NanoSector** [comment]
Lets start with saying I'm horrible at guessing colours. I think the
background needs to go or have a border and be white.

If I were to pick a type of image, I'd take this:
http://www.susanfinch.com/wp-content/uploads/2012/02/noAvatar.gif

but have the "person" in the image in the form of what we already have. I
might be able to do a mockup.

**Comment by MissAllSunday** [comment]
> Lets start with saying I'm horrible at guessing colours. I think the 
> background needs to go or have a border and be white.
> If I were to pick a type of image, I'd take this: 
> http://www.susanfinch.com/wp-content/uploads/2012/02/noAvatar.gif
> but have the "person" in the image in the form of what we already have. I 
> might be able to do a mockup.

If you're just worry about the background, it can be easily removed, I  
wouldn't go for a border because it won't blend it that well on some  
themes with high contrasting colors.

Making it white instead of transparent seems like a good idea.

**Comment by NanoSector** [comment]
I find that the border looks better (especially if it's the same colour as
the "thing" in the image) but everyone's entitled to his or her opinion. If
it goes without a border I'm fine with it.

**Comment by Arantor** [comment]
Actually the border is what makes it able to work on any background colour, for the same reason why the Windows mouse cursor is white with a black outline.

**Comment by MissAllSunday** [comment]
I created another one, will post the .png on the forum

**Comment by Xarcell** [comment]
I created a default avatar via illustrator. SMF is welcome to use it. In fact, only SMF and any forks of SMF2.1 can use it. I added it to my branch of SMF2.1 release. I'm new to Github, so please forgive me for any Github ignorance.

**Comment by Xarcell** [comment]
Also, I think a default avatar should be in the default theme directory, so that theme designer's have that option to override with there own default avatar that matches the theme.

**Comment by illori** [comment]
you would need to issue a PR for that commit so it can be used/considered. also make sure the _commit_ is signed off.

**Comment by Xarcell** [comment]
I still need a collaborative agreement from the powers that be in order to get this issue taken care of. I am also still open to suggestions, but we shouldn't spend too much time on this, as we can also change the image later. I created a poll that is hopefully more suitable. Poll: http://www.simplemachines.org/community/index.php?topic=517447.0

Please try to get people involved to help make a decision so we can get this taken care of. Thanks.

**Comment by MissAllSunday** [comment]
I still think we should go for a genderless avatar like the one I use:  
https://github.com/MissAllSunday/Breeze/blob/develop/Themes/default/images/breeze/default_user.png

A combiantion of whit with grey seems to work well with all kinds of color  
combinations.

**Comment by Xarcell** [comment]
@MissAllSunday You should make this suggestion in the poll topic for others to see.

**Comment by Arantor** [comment]
I hope that's not the same image that our friendly troll complained about last time :tongue:

**Comment by MissAllSunday** [comment]
Nope, it is not. I created a new one. The problematic one has no border  
and its white with dark grey background, its also has a fatter body since  
its more than a half circle while mine is 1/3 of an oval.

**Comment by MissAllSunday** [comment]
Can we have a contest in the community or something to sort this out?

**Comment by Oldiesmann** [comment]
A topic asking for ideas or suggestions might work better.

**Comment by Xarcell** [comment]
I've been asking for suggestions, ideas, and feedback for concepts I've done for some time. The latest based on just the work I've done is here: http://www.simplemachines.org/community/index.php?topic=517447.0

But feel free to create your own.

**Comment by XinYenFon** [comment]
I think with #1160 we don't need extra default avatar, Gravatar already supplies that.

**Comment by NanoSector** [comment]
@Antes: We still need a default avatar in the case that Gravatar is disabled.

**Comment by XinYenFon** [comment]
Since we have default avatar I think its safe to say we can close this no? :P
