### ISSUE TITLE
php 8.1 notice: preg_replace_callback(): Passing null to parameter #3 ($subject) of type array|string is deprecated

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#7212]
#### Description
Error message:
```
Notice
: preg_replace_callback(): Passing null to parameter #3 ($subject) of type array|string is deprecated in
F:\github\SMF2.1\Sources\Load.php
on line
111


Notice
: preg_replace_callback(): Passing null to parameter #3 ($subject) of type array|string is deprecated in
F:\github\SMF2.1\Sources\Load.php
on line
111
```

### Steps to reproduce
Startpage

### Environment (complete as necessary)
- Version/Git revision: latest
- Database Type: pg
- Database Version:
- PHP Version: 8.1

### Additional information/references
https://github.com/SimpleMachines/SMF2.1/blob/facf3470c0fff837c83a486d799646c40097fae5/Sources/Load.php#L111
https://www.php.net/manual/en/function.preg-replace-callback.php

**Comment by mobasuite** [comment]
same problem

**Comment by Sesquipedalian** [comment]
There are probably a few other places where this error would be generated. I'll submit a PR for this soon.
