### ISSUE TITLE
Fix missing values in log_actions

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#7223]
Running the upgrade script downloaded from GH today, about an hour ago. Doing this on an already 2.1 forum. The upgrade gets stuck on Fix missing values in log_actions. Been sitting here about an hour. I have restarted the script and to no avail. It stays on this step and does not move.

https://www.simplemachines.org/community/index.php?topic=580182.0

### Steps to reproduce
1. Download GH .zip
2.  Update an existing 2.1 forum

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by sbulen** [comment]
I'll take a look at this.  ATM I cannot reproduce, but @smfbigguy has shared some info so I have some data to work with.

Likely related to #7215
