### ISSUE TITLE
You should pick relatively simple questions

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#723]
$txt['setup_verification_questions_desc'] = '<span class="smalltext">If you want users to answer verification questions in order to stop spam bots you should setup a number of questions in the table below. You should pick relatively simple questions; answers are not case sensitive. You may use BBC in the questions for formatting, to remove a question simply delete the contents of that line.</span>';

i thought it was a really really bad idea to pick a relatively simple question ... i think this needs a bit of a rewrite.

**Comment by NanoSector** [comment]
On top of that, "You may use BBC in the questions for formatting, to remove a question simply delete the contents of that line."
I don't think the comma suits there very well, since removing has nothing to do with using BBC.
[/pickymode]

**Comment by Oldiesmann** [comment]
Those last two sentences should really be split up into four - "... questions. Answers ... sensitive. You ... formatting. To remove ..."
