### ISSUE TITLE
 database value you're trying to insert does not exist: board

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7238]
#### Description
/cron.php
/Sources/tasks/CreatePost-Notify.php (Line 126) 

The database value you're trying to insert does not exist: board
Function: execute

### Environment (complete as necessary)
- Version/Git revision: 4502804a8
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 7.4

### Additional information/references

Also:
8: Undefined index: board
 /Sources/tasks/CreatePost-Notify.php (Line 126)

**Comment by jdarwood007** [comment]
The database entry for this background tasks exists.  So I verified, topicOptions does not contain a board.

So we either should
- End this task and ignore it as invalid
- Try to lookup the board based on the id (which does exist)

**Comment by BrickOzp** [comment]
How old is this task? What are the other data in the task?

From the code it looks like $topicOptions['board'] is always added to CreatePost-Notify tasks

**Comment by sbulen** [comment]
Do you know how to reproduce this?  I cannot reproduce this with the current code.

I have never seen this behavior in 2.1....

**Comment by sbulen** [comment]
Can you post the backtrace?

**Comment by jdarwood007** [comment]
@sbulen I sent you the data that was there.  This may or may not be related to the customize site.  Let me know what you think.  It looks like its from a new post notification for SMF, but it is related to a mod.

**Comment by sbulen** [comment]
Yes, those are definitely generated by the cust site.  Looks like mod subscription notifications.  No board.  

I haven't been able to replicate yet, but yeah makes sense...

**Comment by sbulen** [comment]
Heh heh heh....

If you include a thank you in the mod description, e.g., thanks to @BrickOzp for all the help!!!, it tries to send a mentions notification when the mod is updated, and this error is triggered.

Definitely a cust site thing.  Possibly an SMF thing as well, e.g., we may need to be able to disable mentions under specific circumstances - such as "posts" on the cust site.

Cust site uses SMF code for posts, e.g., to honor bbc.

**Comment by jdarwood007** [comment]
Ok, so we believe this is related to the customize site and not an issue in SMF?

We can track something for the customize site to fix this as well.

**Comment by sbulen** [comment]
I'm pretty sure the fix is 100% on the cust site.  SMF already lets you specify which bbc to honor.  Cust site is gonna need to filter.  I don't think we ever want the cust site to honor mentions.

**Comment by jdarwood007** [comment]
The only odd part is we are using standard API calls to createPost.  So in theory, that means any 3rd party API call to createPost would trigger this?

**Comment by sbulen** [comment]
If missing critical data, yes.

It would be better to detect/delete malformed task requests, and report a single error.  I.e., not 3000/hour...

Not sure that's a hard 2.1.0 requirement.  But a good idea.

**Comment by jdarwood007** [comment]
Yea, about the only thing I would say if it believes the data is invalid, is to remove the task.  Because it can never complete, cron keeps claiming it and trying again, only to fail the exact same way.

**Comment by sbulen** [comment]
It does look pretty simple & safe to look for critical info, & if not set, log an error & return true in CreatePost-Notify.php.

When tasks return true, they are deleted by cron.
