### ISSUE TITLE
A message is deleted but does not disappear from the Recent Messages list 

### ISSUE THREAD

**Issue by vsc55** [SimpleMachines/SMF#7241]
#### Description
After deleting a new message, it is not removed from the Recent Messages list, it still appears in the list.
As it is crazy if we click on the message, it will tell us that the message does not exist. 

### Steps to reproduce
1. Create Message
2. Delete Message 

### Environment (complete as necessary)
- Database Type: MySQL
- Database Version: 10.3.29-MariaDB
- PHP Version: 7.4.1 

### Additional information/references

**Comment by vsc55** [comment]
False alarm.
It seems to take a while to update the list.

**Comment by tinoest** [comment]
It’s probably the cache mechanism you have enabled keeping it there. Assuming you have caching enabled. 

Removing a message should probably clear that cache.
