### ISSUE TITLE
Wrong description for dropdown button in Package Manager

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#725]
Screenshot should say it all.
http://i.imgur.com/1K6BMAy.png

Along with that, upon loading the page you can see the Emulation Support dropdown collapse with an animation.

**Comment by Arantor** [comment]
Several other places use the same description, which is generic to the smc_Toggle implementation.

**Comment by illori** [comment]
it was updated in some areas on the board index already to "Hide"

**Comment by NanoSector** [comment]
Haven't tested it (can't do so now) but would the code not display the same text (Hide) in all cases if it was that way? Thanks for taking the time.

**Comment by illori** [comment]
See the second commit I fixed that

**Comment by NanoSector** [comment]
Oh sorry forgot that there was a second commit :P

**Comment by Arantor** [comment]
A PR would be nice :P

**Comment by illori** [comment]
no idea why i did not make a PR on this... and it caused a headache due to it.

**Comment by illori** [comment]
#745 fixes this

**Comment by Oldiesmann** [comment]
This was actually fixed in #726, but GitHub didn't associate that PR with this bug for some reason.
