### ISSUE TITLE
Undefined charset for some usernames

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7257]
#### Description
This is being produced on sm.org
Notice
: Undefined offset: 5 in
/Sources/Subs-Charset.php
on line
352

Also repeated for:
: Undefined offset: 13 in
: Undefined offset: 6 in
: Undefined offset: 10 in
: Undefined offset: 2 in

### Environment (complete as necessary)
- Version/Git revision: latest git
- Database Type: mysql
- Database Version: 7.4
- PHP Version: 7.4

### Additional information/references
@Sesquipedalian Marked this for 2.1.1, but I will leave that up to you if we should get it fixed for 2.1.0.

**Comment by Sesquipedalian** [comment]
Do those error messages all literally end with "in" and then an empty string, or did you remove the value?

**Comment by Sesquipedalian** [comment]
Never mind. I figured it out.
