### ISSUE TITLE
Long button text wraps

### ISSUE THREAD

**Issue by BrickOzp** [SimpleMachines/SMF#7265]
#### Description
If a anchor is styled as a button and the button text is long the text will wrap outside of the button.

### Steps to reproduce
1. Go to the package manager and have some mods that can only be installed in emulated mode.
2. This happens if viewed in a lower resolution device.
![image](https://user-images.githubusercontent.com/2890167/150760723-d7cf1fcb-32ee-456b-bfc2-22acf8c3ce36.png)

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references
Adding overflow: hidden; will hide the text outside of the button

**Comment by DiegoAndresCortes** [comment]
Does it solve it replacing _height_ with **min-height** ??
I can't reproduce the exact behavior as your screenshot.

**Comment by BrickOzp** [comment]
Yes, 
![image](https://user-images.githubusercontent.com/2890167/151117673-91588a9a-770c-496f-9928-11d0b2f528ad.png)
