### ISSUE TITLE
On upgrade the table smf_qanda is not created

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#727]
The table smf_qanda is not exist after update ...

**Comment by emanuele45** [comment]
qanda?
What table is it? :confused:

**Comment by jdarwood007** [comment]
Q and A? SMF never had such a table.  Are you saying those questions for registration are missing?

**Comment by PortaMx** [comment]
Copied form install_2_1_mysql.sql
#

# Table structure for table `qanda`

#

CREATE TABLE {$db_prefix}qanda (
  id_question smallint(5) unsigned NOT NULL auto_increment,
  lngfile varchar(255) NOT NULL default '',
  question varchar(255) NOT NULL default '',
  answers text NOT NULL,
  PRIMARY KEY (id_question),
  KEY lngfile (lngfile)
) ENGINE=MyISAM;

This is missing in the update.
Seems to need for spam detection ...

**Comment by emanuele45** [comment]
Ohh...my repo was quite old... :innocent:

**Comment by PortaMx** [comment]
Admin - Anti-Spam:
Table 'smf_qanda' doesn't exist
File: Sources\ManageSettings.php
Line: 730

**Comment by jdarwood007** [comment]
My bad, I guess we do have such a name..  Its a ugly table name but whatever.

**Comment by illori** [comment]
if the old Q and A were not set this will just error out and stop the upgrader from completing

Creating qanda table...done
failed!!
Error!
Error retrieving information on step: Creating qanda table (Item: 46)

**Comment by Oldiesmann** [comment]
It's amazing what an extra } will do :tongue: 

Fixed the bug caused by the fix for this bug :smile:
