### ISSUE TITLE
upgrade: insert of attachments_21_done get done undepped if the logic before was success

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#7288]
#### Description
While testing the upgrade process of pg,
i stumble a cross the issue that the insert:
```sql
INSERT INTO {$db_prefix}settings (variable, value) VALUES ('attachments_21_done', '1');
```
"entrey already exists"

got runned in my second time execute of upgrade (runned before successfull).

Question should i only add a ignore to the sql command,
or is this behavior not wanted that the insert command is called,
when the attachments are already converted?

### Steps to reproduce
1.  upgrade process run twice on postgres
2. 

### Environment (complete as necessary)
- Version/Git revision: latest
- Database Type: pg
- Database Version: 14
- PHP Version: 7.4.1

### Additional information/references
https://github.com/SimpleMachines/SMF2.1/blob/39d0943785d2e95231736810f0e732f91c798491/other/upgrade_2-1_postgresql.sql#L725
![grafik](https://user-images.githubusercontent.com/1782906/152101063-7b737914-ed86-49aa-920f-7908ecae8fc1.png)

**Comment by Sesquipedalian** [comment]
I think adding an ignore to the SQL command will be fine.
