### ISSUE TITLE
Issues when saving server settings

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#7290]
#### Description
- `2: Illegal offset type in isset or empty`
- `8: Undefined index: maintenance`

### Steps to reproduce
1. Admin > Maintenance > Server
2. Change the value of any setting in the area and will generate at least one of the errors above

**Comment by Sesquipedalian** [comment]
I think I know what is causing this, although for some reason I am not receiving any error messages myself, despite the fact that $db_show_debug is true and therefore error reporting is set to E_ALL.
