### ISSUE TITLE
Q/A PHP error

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7304]
#### Description
I upgraded an old 2.1 RC2/3 (somewhere in git) forum.  I am getting a PHP error from the Q/A anti-spam logic.

foreach() argument must be of type array|object, bool given
Sources/Subs-Editor.php

### Steps to reproduce
1. The "answers" column in the database should be "false"
2. View anything that triggers the Q/A anti-spam logic.

### Environment (complete as necessary)
- Version/Git revision: latest
- Database Type: N/A
- Database Version: N/A
- PHP Version: N/a

### Additional information/references
Seems simple enough to add a is_array logic before we do the foreach.  I think this will only happen for some situations from upgrades.

**Comment by Sesquipedalian** [comment]
Just to be sure I understand correctly, do you mean that the value of the `answers` column in the database is the literal string `false`?

**Comment by jdarwood007** [comment]
Yes.  The value in the database is the literal "false"
