### ISSUE TITLE
SMF 2.1.0 throws Parse error: syntax error, unexpected ')' on PHP 7.0

### ISSUE THREAD

**Issue by prbt2016** [SimpleMachines/SMF#7308]
Hello,

I was  in the process of manual installation of SMF 2.1.0 on CentOS Linux 7.7.1908 with PHP 7.0.33, MYSQL 5.6.46, Apache 2.2.34.

However I encountered an error i.e : 

After Database population step when I click on 'Continue' button the following error is thrown i.e on following URL

(http://{{URL}}/{{TO}}/{{SMF}}/install.php?step=4)

`Parse error: syntax error, unexpected ')' in /{{PATH}}/{{TO}}/{{SMF}}/Sources/Load.php on line 2999 `

Could you please replicate the issue at your end and fix this?.

**Comment by BrickOzp** [comment]
Confirmed. Seems to be a thing in PHP 7.0
There is a trailing comma on line 2998 that is causing this.
Also affecting 7.1 and 7.2. 7.3 and 7.4 is not affected.

**Comment by ghost** [comment]
I still get the same exact error even after removing the trailing comma and reuploading the fixed Load.php 6 times on my server.

**Comment by BrickOzp** [comment]
Could you verify some how that the file is changed? ssh or file explorer etc.
For me the error went away with the comma.

**Comment by ghost** [comment]
I confirm that the error is now gone. For some reasons the file showed as updated but it took until I delete it before re-uploading before the error finally disappear.

**Comment by prbt2016** [comment]
Hello,
Thanks for the fix. It is working fine.
Regards.
