### ISSUE TITLE
Should lint against all supported PHP versions

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#7311]
Right now our workflow for checking incoming changes includes a call to phplint, but it only checks against whatever default version it is running. We should check syntax for all supported versions so that we can avoid issues like #7308 in the future.

**Comment by Sesquipedalian** [comment]
@live627, you've done work on this stuff before and you're quite clever about it. Would you mind taking this on for us?

**Comment by jdarwood007** [comment]
I would suggest we use [matrix](https://docs.github.com/en/actions/using-workflows/advanced-workflow-features#using-a-build-matrix) to run this so we can run parallel jobs and it seems easy to maintain our list of php versions
https://github.com/SimpleMachines/SimpleDesk/blob/smf21/.github/workflows/Syntax-Check.yml

I'm using it in SimpleDesk and it seems to work well.  Although I'm not running linter, just a script that runs the syntax check.

**Comment by live627** [comment]
phplint spawns a php process in parallel via [Symfony/Process](https://symfony.com/doc/2.0/components/process.html) to check syntax—doing it serially is too slow.
