### ISSUE TITLE
Posting attachments, restrictions not shown to user

### ISSUE THREAD

**Issue by LexArma** [SimpleMachines/SMF#7317]
The UI does not reveal size limits to the user, until it is too late. 

At first you only see "Restrictions: X attachments remaining" which tells you how many attachments you can add to your post. 
But no size limits.

![Limits1](https://user-images.githubusercontent.com/39050447/153772518-8921846d-db87-4634-a21f-f48827d36704.PNG)

When you select your first attachment, you are shown the limit for the whole post. 
But still no size limit for the individual attachments. 

![Limits2](https://user-images.githubusercontent.com/39050447/153772519-ba171472-1c8a-4073-9390-6fceb008547c.PNG)

It would be useful to know your limits, before you try to add attachments that don't fit. 

Issue taken from the forum: https://www.simplemachines.org/community/index.php?topic=580708.0

**Comment by Sesquipedalian** [comment]
This was apparently an intentional decision (#4004) to work around a bug in dropzone.js (#4001). I don't know if that workaround is still necessary. Perhaps @sbulen can comment more fruitfully on this.

**Comment by sbulen** [comment]
Yeah, its been a while.  The problem is dropzone's math was "pure", eg, 1024x1024 = 1M & that x1024=1G.

So 1000M != 1G.   So the numbers are displayed differently between dz and smf.  It was very confusing, the numbers all looked wrong.

From #4001:

> Dropzone will never display 4 digits to the left of the decimal point, it tries to shoehorn everything into GB, MB, KB, etc., using a strict base of 1024, while ONLY displaying 1-3 digits to the left of the decimal point... It won't display 1M until you go up to 1024K, & it does fine of course with 999K.
> 
> Thus, it gets confused with values of 1000K-1023K (or MB, or GB)... It has problems with all these edge conditions.
> 
> I believe the applicable code is here:
> https://github.com/enyo/dropzone/blob/master/dist/dropzone.js#L834
> 
> We don't have that code in SMF, we have the minimized version, dropzone.min.js.

Maybe more recent versions of dz are more flexible???   This was 5 years ago....

**Comment by LexArma** [comment]
I'm sorry - but I'm not really following. If we can always show the settings correctly to the Admin, surely we can echo them correctly to the user too in the same format? 
![AttachmentLimits](https://user-images.githubusercontent.com/39050447/154199156-abe1cdf1-bcfe-4223-a1ef-aba6b1a66b76.PNG)

And all I think this would really need, is adding all the set limits back to the restrictions shown - When now it only shows one restriction. ~~I just realized this has also stopped the filetype restrictions from being shown completely. Sorry, this was my mistake~~ 
We do not need the limits to be automatically recalculating anything, just showing so the user knows what they are allowed to do.

**Comment by sbulen** [comment]
If you look at the screenshots in #4001 you'll see what the problem was that led to the removal of those stats.  1000K was displayed as 1K.

The dz display was buggy.

It's possible dz has fixed that - it was 5 years ago....

**Comment by LexArma** [comment]
Yes, I looked at it and saw that - But we did show those restrictions before we ever had anything to do with dz I believe, so what is stopping us from doing it now?

**Comment by sbulen** [comment]
What stopped us 5 years ago was dz.  We use dz.

dz does the math that was problematic.

**Comment by LexArma** [comment]
But what I am trying to say is that simply showing the limits requires no math.
We have the limits, we know it's in KB. We don't need conversions or calculations, but I promise you people will be annoyed if they don't know what they can upload and need to find out by experimenting.

**Comment by sbulen** [comment]
As explained above, IIRC, the issue 5 yrs ago was with the math associated with display of the numbers in K/M/G.

E.g., if given 2,000,000, does that display as 2M, 1.9M, etc.   It was showing 2K.

**Comment by LexArma** [comment]
Well, I just fixed this for my own board by echoing $modSettings['attachmentPostLimit'] and $modSettings['attachmentSizeLimit'] and adding KB to the end. Always showing KB a lot smaller issue than not showing them at all. This has the added benefit of being exactly what dz seems to do for the post limit as well, so we speak the same language now.
![AttachmentLimits2](https://user-images.githubusercontent.com/39050447/154313680-2e166c87-79af-490c-91d3-0bcbb4044816.PNG)

**Comment by Sesquipedalian** [comment]
After looking into this, it doesn't seem like dropzone.js was to blame. From what I can tell, the problem was simply that prior to #4004, we were using `comma_format()` to format the numbers, but then used `%1$d` instead of `%1$s` in the $txt strings that we `sprintf`-ed the values into. That caused everything after the comma to be truncated.
