### ISSUE TITLE
Enhancement: Better handling of user default tz on upgrade

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7324]
#### Description
Just placing this out there...  We've done so much tweaking & fixing with timezones, we may have missed something obvious.

Timezones are "new" in 2.1.  And everything defaults to UTC, _even at the individual user smf_member record level_.  

Let's say you upgrade a forum and want to change the forum default, for this new feature.  Fine, you changed it.  But it doesn't take effect - all users are still on UTC...  Why?

Whatever you do at the forum level almost doesn't matter, because, in the user profile, the tz value is hard-coded _in the DB_ to 'UTC'.  And there is no easy way to update all of your users.

I was looking at this on the support forum & there really must be a better way:
https://www.simplemachines.org/community/index.php?msg=4111262

It's set as the default at the DB level:
https://github.com/SimpleMachines/SMF2.1/blob/02fe31c8f0458014eb84caf800183eb262f3b7f7/other/upgrade_2-1_mysql.sql#L2386
https://github.com/SimpleMachines/SMF2.1/blob/02fe31c8f0458014eb84caf800183eb262f3b7f7/other/install_2-1_mysql.sql#L738

Thinking aloud here, but things to consider:
 - Setting default timezone in upgrader
 - Setting default timezone in installer
 - Defaulting users to some form of 'use forum default'
 - Providing a mechanism for an admin to set all users to 'use forum default'
 - We may also consider removing/zeroing out the old user offset (at least ensuring it's not used anywhere)

### Steps to reproduce
1. Upgrade your existing forum...
2. Everybody is on UTC

### Environment (complete as necessary)
- Version/Git revision: 2.1.1

**Comment by Sesquipedalian** [comment]
Please test to confirm that #7336 fixes this issue.
