### ISSUE TITLE
Invalid HTML?

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#733]
In my repo there is a:

```
Line 41, Column 8: end tag for "ul" which is not finished
```

Is it only me?

**Comment by Oldiesmann** [comment]
What page are you accessing at that time? The board index?

**Comment by emanuele45** [comment]
> What page are you accessing at that time? The board index?
> 
> That one in particular the BI, but it's present in any page.

**Comment by illori** [comment]
seems some errors related to https://github.com/SimpleMachines/SMF2.1/commit/b0179a5b1cd3946ff9c0c778c7dcc876a1f334d2 i believe

i can duplicate the issue but only for guests, validating local html it comes out fine.

actually it only validates as admin, not as a user that does not show the new features in the top bar.

**Comment by illori** [comment]
actually with updated source, i can no longer duplicate this issue using opera validation or web developer plugin for firefox to validate

**Comment by emanuele45** [comment]
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/index.template.php#L185
No maintenance
No mod reports
No unapproved member
means

```
<ul class="floatleft">
</ul>
```

that gives the above error.

**Comment by illori** [comment]
well i did have one open mod report which seems to have its own bugs related to this in it.

**Comment by Oldiesmann** [comment]
Trying to figure out the best way to fix this. I'd rather not do one huge conditional, but that might be our best option.

Alternately, we can do something like this:

``` php
        // If the user is logged in, display the time, or a maintenance warning for admins.
        if ($context['user']['is_logged'])
        {
                $context['open_ul'] = false;

                // Is the forum in maintenance mode?
                if ($context['in_maintenance'] && $context['user']['is_admin'])
                {
                        $context['open_ul'] = true;
                        echo '
                        <ul class="floatleft">
                                <li class="notice">', $txt['maintain_mode_on'], '<br /></li>';
                }

                if (!empty($context['open_mod_reports']) && $context['show_open_reports'])
                {
                        if (!$context['open_ul'])
                        {
                                echo '
                        <ul class="floatleft">';
                                $context['open_ul'] = true;
                        }

                        echo '
                                <li class="modnotice"><a href="', $scripturl, '?action=moderate;area=reports">', $txt['mod_reports_waiting'], '</a>: <span class="amt">', $context['open_mod_reports'], '</span></li>';
                }

                // Are there any members waiting for approval?
                if (!empty($context['unapproved_members']))
                {
                        if (!$context['open_ul'])
                        {
                                echo '
                        <ul class="floatleft">';
                                $context['open_ul'] = true;
                        }

                        echo '
                                <li class="modnotice"><a href="', $scripturl, '?action=admin;area=viewmembers;sa=browse;type=approve">', $txt['approve_members_waiting'], '</a>: <span class="amt">', $context['unapproved_members'], '</span></li>';
                }

                if ($context['open_ul'])
                        echo '
                        </ul>';
        }
        // Otherwise they're a guest. Ask them to either register or login.
        else
                echo '
                        <ul class="floatleft">
                                <li>', sprintf($txt[$context['can_register'] ? 'welcome_guest_register' : 'welcome_guest'], $txt['guest_title'], $scripturl . '?action=login'), '</li>
                        </ul>';
```

That's also a bit messy and seems redundant.

**Comment by illori** [comment]
haha

// If the user is logged in, display the time, or a maintenance warning for admins.

the time as since been moved so that comment is a bit outdated

also i think your idea will effect the placement of the search box on the right side

**Comment by Arantor** [comment]
Better idea: move the profile menu up there and get it out of the main menu.

We get to put the user's name (and maybe their avatar) up out the way, we get to put the profile menu directly under it, bada-bing-bada-boom.
