### ISSUE TITLE
Custom profile fields that use multilanguage entities such as {location} are not translated in search for members

### ISSUE THREAD

**Issue by dhmyrdal** [SimpleMachines/SMF#7330]
#### Description
A simple omission of searching for a $TXT[] here...
Custom profile fields that use multilanguage entities such as {location} are not translated in search for members.
They are visible as they should be in the admin overview, but not in the search for members drop-down.

Search:
![image](https://user-images.githubusercontent.com/53157424/154171030-0a135d43-483f-4ece-bef4-7679c04afb4d.png)

Admin config:
![image](https://user-images.githubusercontent.com/53157424/154171514-b69237f7-53ce-49cc-bf72-a1f2b0029ab0.png)

Admin overview (translate OK):
![image](https://user-images.githubusercontent.com/53157424/154171600-9cfa2c16-d475-40bc-be89-96697fddd254.png)

### Steps to reproduce
1. Create a custom profile field, and use any existing or custom language string in curly brackets. ie {location} and make it searchable.
2. See that it translate OK in admin, but not in search menu.

### Environment (complete as necessary)
- Version/Git revision: 2.1.1
- Database Type: mySQL Maria
- Database Version:
- PHP Version:

### Additional information/references

**Comment by DiegoAndresCortes** [comment]
Like #7315
Missing the token function

somewhere around here?
https://github.com/SimpleMachines/SMF2.1/blob/a2d261dc6006013272de1fe76ffccdd76aacd783/Sources/Memberlist.php#L578

**Comment by Sesquipedalian** [comment]
I will add a fix for this in #7318.
