### ISSUE TITLE
Add gender option

### ISSUE THREAD

**Issue by dhmyrdal** [SimpleMachines/SMF#7331]
A simple request - we have today 3 options for "gender":
Gender:
{gender_0}  - "None"
{gender_1} - "Male"
{gender_2} - "Female"

I propose that {gender_3} "Non-binary" is added to the list. 
I know that "None" can be renamed, but that somehow makes it har to state "none of your business" :-)

**Comment by DiegoAndresCortes** [comment]
These are custom fields, so they are editable in the admin center (under custom fields) and also translatable!
