### ISSUE TITLE
"Logout" button in Subs broken, uses malformed link

### ISSUE THREAD

**Issue by James-Gryphon** [SimpleMachines/SMF#7333]
When I turned on the "login_main_menu" option in my custom theme, I quickly found out that the Logout button is broken. On further investigation, it appears the Logout button is constructed like this:

`			'logout' => array(
				'title' => $txt['logout'],
				'href' => $scripturl . '?action=login' . $context['session_var'] . '=' . $context['session_id'],
				'show' => !$user_info['is_guest'] && !empty($settings['login_main_menu']),
				'sub_buttons' => array(
				),
				'is_last' => !$context['right_to_left'],
			),
`
The result is that the action link is for "logine3dfw89ehfa98gh98arghaohg" (or such like, depending on the session), and clicking it, instead of logging you out, tosses the "Not found" error (Sorry, this section isn't available at this time).

**Comment by Sesquipedalian** [comment]
Missing `;`. Should be an easy fix.
