### ISSUE TITLE
ScEditor 3.1.1 available

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#7340]
SCEditor 3.1 was released in December (followed by 3.1.1 a couple days later to fix a bug). I'm not sure how much work is needed to update it for SMF though. Full changelog is at https://www.sceditor.com/posts/version-3-1-0-released/

**Comment by live627** [comment]
no need. There are no relevant bug fixes there.

Also this will greatly increase the patch size. 2.1.2 seems to be a quite
big-ish patch already.

**Comment by Oldiesmann** [comment]
This was more of an FYI thing, not a "let's do this now" thing. If there aren't any relevant bug fixes then we can skip the new version.
