### ISSUE TITLE
Ignore Boards issue

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7343]
#### Description
"I was curious, because I am also ignoring the language boards here (those languages I do not speak).

Just went to my profile and the ignore boards flags were showing. Then I changed 1 board and saved .... and now all ignored board settings are gone from the profile(!)

Same happens on my 2.1 test forum... I feel this may be a bug... "

### Additional information/references
From the forum:
https://www.simplemachines.org/community/index.php?topic=580844.0

**Comment by sbulen** [comment]
I have confirmed this bug.  It doesn't seem to be saving updates, in fact, it seems to wipe them all out.

**Comment by Bopske** [comment]
Yep, that’s what I saw. Settings were fine from before the upgrade, but changing them afterwards wipes them all..
