### ISSUE TITLE
Undefined variable: cache_accelerator

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#7351]
#### Description
This error appears on switching cache type

### Steps to reproduce
1. Go to Maintenance -> Server Settings -> Caching
2. Select SQLite3, or something else, then save

### Environment (complete as necessary)
- Version/Git revision: 2.1.1

### Additional information/references
Sources/ManageServer.php, Line 800

**Comment by Sesquipedalian** [comment]
Confirmed.
