### ISSUE TITLE
Transfer Attachments, fails with database error

### ISSUE THREAD

**Issue by LexArma** [SimpleMachines/SMF#7353]
Transferring attachments from one attachment folder to another fails due to a datase error. 

> 'The database value you're trying to insert does not exist: start'

### Steps to reproduce
1. Have attachments in multiple folders
2. Try to use the "Transfer Attachments" feature in File Maintenance to join folder contents to one.

### Additional information/references
From the forum https://www.simplemachines.org/community/index.php?topic=581082.0

**Comment by LexArma** [comment]
According to the original reporter, this is no longer an issue with 2.1.2. Needs to be confirmed, but may not need fixing separately anymore.

**Comment by sbulen** [comment]
I have confirmed this works with current code.
