### ISSUE TITLE
Package manager link to SM DL site not working

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#7361]
#### Description
When I go to "Admin" > ("Main" > ) "Package Manager" > "Add Packages" > "Download new packages" and click on the "[ Browse ]" link next to "Simple Machines Download Site" (`https://[...]/index.php?action=admin;area=packages;get;sa=browse;server=3`), I get a vacuous "Unable to connect to the server. Please try using [this URL](https://download.simplemachines.org/browse.php?api=v1;smf_version=2.1.1/index.php) instead.", and that URL only shows a blank page (and looks kinda broken).

### Steps to reproduce
1. See above 😉 

### Environment (complete as necessary)
- Version/Git revision: some commit that was HEAD in the last 48 hours.
- Database Type: pg / any
- Database Version: 9.6 / any
- PHP Version: 7.0 / any

### Additional information/references

**Comment by jdarwood007** [comment]
This is a issue with the site not SMF.  I will look at it when i can.
