### ISSUE TITLE
html_to_bbc tweak needed?

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7363]
#### Description
The upgrader & the editor attempt to clean up html & simplify to bbc, using the html_to_bbc routine.

We have seen a couple instances where it couldn't deal with line breaks, specifically, the space in `<br />`.

Needs more research & testing, but I think there is a pattern here.  

### Additional information/references
See the solution here:
https://www.simplemachines.org/community/index.php?msg=4113748

Possibly related:
https://www.simplemachines.org/community/index.php?msg=4114007

**Comment by sbulen** [comment]
UPDATE:  I just did some testing on an upgraded forum and the `<br />` seems to work fine before & after the upgrade.  It works in signatures & in posts.  

I'll leave this up here in case anyone has ideas why it appears to cause issues under some circumstances.  If no input, I'll close out in a couple weeks...

Only thing I can think of is that that particular format of the br tag is part of xhtml, isn't it???  I wonder if some browsers can have that disabled???  Is it possible a DOCTYPE conflict is getting introduced somehow?

**Comment by Sesquipedalian** [comment]
Well, html_to_bbc isn't used on signatures during the upgrade. In fact, we don't change signatures at all during the upgrade.

**Comment by Sesquipedalian** [comment]
It looks like the problem for signatures is in Profile-Modify.php. I'll test a bit more, but I think this is going to be a quick fix.

**Comment by sbulen** [comment]
I have not been able to figure out that post issue...  Spent a bit too much time trying to reproduce, but I don't get that behavior at all...  

So...  Once #7371 merges I think we can close this.
