### ISSUE TITLE
Youtube BBC - should we really be modifying the user input?

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7364]
#### Description
I've never used the youtube bbc before.  I just learned that when we apply the youtube bbc tag, we delete the youtube domain out of the URL.  

E.g., when adding the bbc tag to `https://youtu.be/SFHXdqRCZPc` , it becomes `[youtube]SFHXdqRCZPc[/youtube]`

It seems very odd to me that we actually modify the user input, deleting a portion of it...  Kinda philosophically, I don't think we should be changing or modifying the actual user input.  

**_I really think users should be able to add/remove BBC tags at will, and this breaks that rule..._**  

Further, if we left the URL alone, users of older youtube mods will find most of their links supported as-is, without needing to putz with the database.  

### Additional information/references
https://www.simplemachines.org/community/index.php?topic=580733.msg4114155#msg4114155

**Comment by Sesquipedalian** [comment]
This is SCEditor's standard behaviour. We could try to override SCEditor with our own code, I suppose, but that level of change would arguably fall outside the scope of a point release.
