### ISSUE TITLE
Language strings with misuse of capitalisation

### ISSUE THREAD

**Issue by isaak654** [SimpleMachines/SMF#7365]
#### Description
This was reported in the Bug Reports board:
https://www.simplemachines.org/community/index.php?topic=581162.0

**Comment by Bopske** [comment]
Please note that if there are going to be many changes to language strings to standardize capitalization, this will result in a large number af string update requirements in Crowdin… even though the content of the strings remains unchanged…

**Comment by Dzonny** [comment]
That is not a problem, it's a few seconds job in Crowdin, and as our branches on Crowdin are automatically synced from here it will be just a small change in a string where is needed.
We should fix those kinds of capitalization errors right away it doesn't require a lot of time.

**Comment by Bopske** [comment]
Not concerned about the technical side, but the amount of update requests that will be going to the translators.. 
it is not that obvious to the translator in Crowdin what was changed to the source strings. It may be wise to put a warning on the translators board on SMF beforehand …

**Comment by sbulen** [comment]
I do not think this is an issue.

It is fairly common to capitalize significant subjects in important headers & buttons & links, etc.   I see the same practice on numerous sites, including GitHub, XenForo forums, etc., etc.
