### ISSUE TITLE
BLOB, TEXT, GEOMETRY or JSON column 'credits' can't have a default value

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#7366]
#### Description
--Description Here--

### Steps to reproduce
1. attempted to upgrade a 2.1 RC4 installation to the github version...
2. error in step 4, database changes

### Environment (complete as necessary)
- Version/Git revision: 2.1.2 github download from 1-MAR
- Database Type: mySQL
- Database Version:
- PHP Version: 7.4

### Additional information/references
Database Changes
Executing database changes
Please be patient - this may take some time on large forums. The time elapsed increments from the server to show progress is being made.
Executing: "Package Manager New Features" (7 of 71)
Error!
BLOB, TEXT, GEOMETRY or JSON column 'credits' can't have a default value

I suspect this may be related to a recent commit
https://github.com/SimpleMachines/SMF2.1/pull/7346

**Comment by Kindred-999** [comment]
note: the credits column in log_packages is varchar(255) before attempting this upgrade

commenting out this code resulted in a successful upgrade
---# ALTER TABLE {$db_prefix}log_packages
---# ADD COLUMN credits TEXT NOT NULL DEFAULT '';

**Comment by albertlast** [comment]
when i take the test case from #7346 https://dbfiddle.uk/?rdbms=mariadb_10.3&fiddle=664b05272751062e3981ddb055ea7744
then we see,
that pg and mariadb got the issue not only mysql,
reason why this slip throw the test.
mysql 5.5 works also with default
so this issue is mysql >=5.6

**Comment by albertlast** [comment]
tested to use of expression method
```sql
ALTER TABLE {$db_prefix}log_packages
 ADD COLUMN credits TEXT NOT NULL DEFAULT ('');
```
 mention in: https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html

works fine in all pg version and mariadb versions but in mysql works this only in 8.0,
 below it doesn't work.

**Comment by Oldiesmann** [comment]
Is there a reason we must have it as "NOT NULL"?
