### ISSUE TITLE
Cookie “_ga” will be soon treated as cross-site cookie against ....  because the scheme does not match.

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#7370]
#### Description
Cookie “_ga” will be soon treated as cross-site cookie against “https://test2.turtleshellprod.com/index.php?action=profile;area=alerts_popup;counter=0;u=1” because the scheme does not match.

### Steps to reproduce
1.  watch browser console on any forum page
2. 

### Environment (complete as necessary)
- Version/Git revision: March 1 GitHub build of 2.1.2
- Database Type: mySQL
- Database Version:
- PHP Version: 7.4

### Additional information/references

**Comment by live627** [comment]
uh   huh

**Comment by Sesquipedalian** [comment]
I don't see that happening on any other SMF 2.1.1 forum that I visit. I do, however, see warnings like this in the log when I visit https://test2.turtleshellprod.com/index.php:

> [Warning] The page at https://test2.turtleshellprod.com/index.php was allowed to display insecure content from http://test2.turtleshellprod.com/Themes/FX-Sabers/images/fx-sabers-logo.png. (index.php, line 92)

I was viewing as a guest, so SMF didn't send me a cookie, but the warnings I did see suggest that your problem is simply that you have inconsistent use of HTTP vs. HTTPS going on.

**Comment by jdarwood007** [comment]
_ga is most likely google analytics.  I suspect your have a cookie from them.   Your getting that error though because you have some http content trying to load on your site:
```
Mixed Content: The page at 'https://test2.turtleshellprod.com/index.php?PHPSESSID=67cf6422f859e883a04b678e1e8b1be7;action=login' was loaded over HTTPS, but requested an insecure element 'http://test2.turtleshellprod.com/Themes/FX-Sabers/images/fx-sabers-logo.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html```

**Comment by Kindred-999** [comment]
Well, you are correct that I mis entered the logo.  However, this error still triggers after correcting that.

I do have a ga cookie -- although I am uncertain why since I don't THINK I ever set a google analytics cookie for the test or test2 subdomains.    But, it's probably not an SMF error after all - as you say
