### ISSUE TITLE
Not all board pages contain page numbers in titles

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#7373]
#### Description
It's very strange, but some board pages do not have page numbers in their titles.

### Examples
https://www.simplemachines.org/community/index.php?board=147.0 (title: SMF 2.0.x Support) - no page number, it's good because it's the first page
https://www.simplemachines.org/community/index.php?board=147.25 (title: SMF 2.0.x Support) - no page number, it's bad because it's the second page
https://www.simplemachines.org/community/index.php?board=147.50 (title: SMF 2.0.x Support - Page 3) - there's a page number, it's good
https://www.simplemachines.org/community/index.php?board=147.75 (title: SMF 2.0.x Support) - no page number, it's bad because it's the fourth page
https://www.simplemachines.org/community/index.php?board=147.225 (title: SMF 2.0.x Support - Page 10) - there's a page number, it's good
https://www.simplemachines.org/community/index.php?board=147.259 (title: SMF 2.0.x Support) - no page number, it's bad
https://www.simplemachines.org/community/index.php?board=147.275 (title: SMF 2.0.x Support - Page 12) - there's a page number, it's good

Another example: the "Modification and Packages" board has a page number on the latest page only - https://www.simplemachines.org/community/index.php?board=59.2700

### Environment (complete as necessary)
- Version/Git revision: 2.1.1

### Thoughts
I think it has something to do with the pagination of the topics displayed on the board pages. If the topics are small, the page number is displayed in the board title. If the topics are large, the problems begin.
![](https://user-images.githubusercontent.com/229402/156710862-336cfc1b-f242-4fc3-8b2a-f3377296c90f.png)

**Comment by dragomano** [comment]
Possible solution:

Subs.php, constructPageIndex function, replace
```$context['current_page'] = $start / $num_per_page;```
with
```
if (!isset($context['current_page']))
	$context['current_page'] = $start / $num_per_page;
```

**Comment by sbulen** [comment]
This is specific to the tab title, right?
![image](https://user-images.githubusercontent.com/23568484/156930796-edd58bed-d4b5-49b5-ab16-7db42b94612a.png)

I think you're right, the page numbers on the topic lists appear to be throwing it off.

We should consider getting rid of it altogether.  It is not really helpful, as the page itself displays the page numbers quite clearly.  It just looks like clutter to me, TBH.

**Comment by live627** [comment]
what about seo?

**Comment by Sesquipedalian** [comment]
What about it? If there's a concern in that regard, please explain what the problem would be.

**Comment by dragomano** [comment]
As far as I know, now all pages of boards except the first are closed from indexing with `<meta name="robots" content="noindex">`. Good or bad, not the point. Nevertheless, pages should not have the same titles. For comparison, board pages in XenForo are not closed from indexing and look like this:

`https://xenforo.com/community/forums/xenforo-questions-and-support.25/`, title: "XenForo questions and support | XenForo Community" - the first page
`https://xenforo.com/community/forums/xenforo-questions-and-support.25/page-2`, title: "XenForo questions and support | Page 2 | XenForo Community" - the second page.

P. S. Now imagine if a user migrates from XenForo to SMF where the page titles look different - "Title - Page 1 - Forum Name". Why not, for example, add a standard option (or just a language string) to change the delimiter ("-") in titles?

![xenforo](https://user-images.githubusercontent.com/229402/157196613-826a93b9-87ed-4f41-a199-bdfa2b7ca178.png)
![smf](https://user-images.githubusercontent.com/229402/157196621-498d8ac7-edac-4e0b-889b-198b78bff567.png)
