### ISSUE TITLE
Poor handling of case conversion for some languages

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#7388]
For most languages, $smcFunc['strtoupper'],  $smcFunc['strtolower'],  $smcFunc['ucwords'], and  $smcFunc['ucfirst'] work fine. But there are some cases where they do the wrong thing. 

The most problematically affected are Turkish, Lithuanian, and Greek:

- Turkish has special rules for case mapping between `ı`, `i`, `I`, and `İ`.
- Lithuanian has special rules for the dots above `i` and `j` when the characters also have accent marks above them.
- Greek requires special handling for lower case sigma, using `σ` when it occurs in the middle of a word, but `ς` at the end of a word.

Additionally, $smcFunc['ucwords'] and  $smcFunc['ucfirst'] do the wrong thing when handling characters that have separate upper case vs. title case versions. They also get easily confused when they encounter things like punctuation marks. (These problems aren't as big a deal as the ones above, but if we can fix them we might as well.)

The underlying cause of these problems is that we rely on the mbstring extension to do these job for us, but the mbstring extension is not locale-aware and therefore never applies the special rules that are needed in these situations.

The ideal solution would be to use the intl extension's functions for these tasks, but many hosts don't have that extensions installed, so we'll need to use our polyfills in Subs-Charset.php when it isn't. I'll also need to expand those polyfills a bit, since they also currently mishandle a few of these situations.

Probably related: https://www.simplemachines.org/community/index.php?topic=581362.0, although some of the details in that report remain unclear due to communication barriers.

**Comment by chopinesque** [comment]
It is a bit more complex when it comes to [Greek regarding accents](https://www.translatum.gr/forum/index.php?topic=358982.0).

**Comment by Sesquipedalian** [comment]
Thanks. I will look into correcting that, too, @chopinesque. 🙂

**Comment by albertlast** [comment]
I'm not sure if smf should invest time in this, when no plug'n'play solution exists...
Exists maybe a js approache for this issue?

**Comment by chopinesque** [comment]
In my opinion, the simplest solution for css `text-transform` is simply not to use it and have separate language strings if capitalization or other case is needed. The other solution is to make sure that tags enclosing language strings contain/change the appropriate language elements accordingly.

**Comment by jdarwood007** [comment]
I wonder if we can patch this in loadLanguage?

```
				// setlocale is required for basename() & pathinfo() to work properly on the selected language
				if (!empty($txt['lang_locale']) && !empty($modSettings['global_character_set']))
					setlocale(LC_CTYPE, $txt['lang_locale'] . '.' . $modSettings['global_character_set']);
```

setlocale allows additional params to try as locales so maybe we could do:
```
				// setlocale is required for basename() & pathinfo() to work properly on the selected language
				if (!empty($txt['lang_locale']) && !empty($modSettings['global_character_set']))
					setlocale(LC_CTYPE, $txt['lang_locale'] . '.' . $modSettings['global_character_set'], $txt['lang_locale'] . '.UTF8', $txt['lang_locale']);
```

Which may get it to set the right locale here by forcing UTF-8 as an option if the initial one didn't load.

**Comment by jdarwood007** [comment]
FYI, Is my previous issue https://github.com/SimpleMachines/SMF2.1/issues/7027 related to this?
I touched on a issue with ucfirst.  I did come up with a workaround, so I suspect it could be tested.

**Comment by Sesquipedalian** [comment]
> In my opinion, the simplest solution for css `text-transform` is simply not to use it and have separate language strings if capitalization or other case is needed. The other solution is to make sure that tags enclosing language strings contain/change the appropriate language elements accordingly.

Unfortunately, there is nothing that we can do about bugs in various browsers' implementations of CSS text transformation. We could perhaps add some language-specific checks in the theme files in order to disable CSS text transformation on the elements that normally use it. For the default theme, that might be manageable, since it only uses CSS text transformation for buttons and for the previous & next topic links. But there's nothing we can do about custom themes.

----------

> I wonder if we can patch this in loadLanguage?
> 
> ```
> 				// setlocale is required for basename() & pathinfo() to work properly on the selected language
> 				if (!empty($txt['lang_locale']) && !empty($modSettings['global_character_set']))
> 					setlocale(LC_CTYPE, $txt['lang_locale'] . '.' . $modSettings['global_character_set']);
> ```
> 
> setlocale allows additional params to try as locales so maybe we could do:
> 
> ```
> 				// setlocale is required for basename() & pathinfo() to work properly on the selected language
> 				if (!empty($txt['lang_locale']) && !empty($modSettings['global_character_set']))
> 					setlocale(LC_CTYPE, $txt['lang_locale'] . '.' . $modSettings['global_character_set'], $txt['lang_locale'] . '.UTF8', $txt['lang_locale']);
> ```
> 
> Which may get it to set the right locale here by forcing UTF-8 as an option if the initial one didn't load.

That's a good idea, and I will add it to the PR I'm working on.

> FYI, Is my previous issue #7027 related to this?
> I touched on a issue with ucfirst. I did come up with a workaround, so I suspect it could be tested.

 Unfortunately, that wouldn't be sufficient to solve all the issues I mentioned above. Fundamentally, mbstring simply isn't adequate for these tasks in all languages, which is one of the reasons why the intl extension exists. But I'm making very good progress on a more comprehensive solution. 🙂

**Comment by Sesquipedalian** [comment]
Two quick questions for @chopinesque about Greek conventions when words are converted to all uppercase letters:

1. Am I correct to understand that the diaeresis (`¨`) should retained, even though accents are discarded?
2. Are the accents (and breathing marks, if applicable) kept for the first letter, or are they discarded there, too?

**Comment by chopinesque** [comment]
1. The rules here are complex. For example, in some cases where in lowercase there is no diaeresis (because it is not needed due to the presence of an accent), it is needed in [all caps](https://www.translatum.gr/forum/index.php?topic=7167.0) to indicate that the [diphthong](https://en.wikiversity.org/wiki/Greek_Language/Diphthongs) is pronounced as two phonemes and not a single one (as the accent is always dropped in all caps). So, unless there is some linguistic module that can deal with such, I would suggest simply dropping diaeresis in all caps in all cases.
2. They are kept only if we have a Sentence case, i.e. only the first letter is capital. In all caps they are dropped.

**Comment by Sesquipedalian** [comment]
Thanks. That helps a lot.

**Comment by replikacep** [comment]
Is the problem resolved?

**Comment by dragomano** [comment]
If the forum language is Turkish, the problem still exists:
```php
$value = 'Image';
var_dump($smcFunc['strtolower']($value) === strtolower($value)); // false
```

**Comment by Sesquipedalian** [comment]
> If the forum language is Turkish, the problem still exists:
> 
> ```php
> 
> $value = 'Image';
> 
> var_dump($smcFunc['strtolower']($value) === strtolower($value)); // false
> 
> ```

If the current language is Turkish, then false is the intended result of that comparison.

In Turkish, the lowercase form of `I` is `ı` rather than `i`. The result of `$smcFunc['strtolower']('Image')` will be `ımage` when the current language is Turkish, which is correct. In contrast, the result of `strtolower('Image')` will always be `image`, which is incorrect when the current language is Turkish.

**Comment by Sesquipedalian** [comment]
More information is needed. 

1. What is the output of each function call? 
2. What locale is being used with setlocale()? SMF offers multiple variants of the locale string to the setlocale() call, so that the system can choose the first variant that matches whatever it has installed.

**Comment by dragomano** [comment]
For my task it was necessary to get the same result for all languages - "image", so I stopped at the use of `strtolower`.

**Comment by jdarwood007** [comment]
strtolower is dependant on what locale is running.  You can verify this by setting the locale to en-us and trying it again.

You can try this to see if it works
```
$value = 'Image';
mb_convert_case($value, MB_CASE_UPPER, 'UTF-8');
```

**Comment by Sesquipedalian** [comment]
> For my task it was necessary to get the same result for all languages - "image", so I stopped at the use of `strtolower`.

I see. So your goal is to convert the string to lowercase while ignoring localization rules. That is the exact opposite of the purpose that `$smcFunc['strtolower']()` is designed for.

Based on that, I would say that `$smcFunc['strtolower']()` is working correctly, and the problem is just that you should use a different function for your task.
