### ISSUE TITLE
Nit: Altering start value in url can result in fractional page numbers

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7389]
#### Description
This will happen if you enter a value beyond the range of the list you are viewing as the "start" value in the URL...

This can happen anywhere we use constructPageIndex() - browsing topics, memberlists, etc., whenever the start value requested in the URL > the max value for that list.

![image](https://user-images.githubusercontent.com/23568484/159147834-647922cc-c1fd-406b-8667-91522c2744c7.png)

![image](https://user-images.githubusercontent.com/23568484/159147816-76fb3840-020e-4081-baa0-a117434052d4.png)

### Steps to reproduce
1. Browse the memberlist.  
2. In your browser URL, add ";start=3000001" to the end of the URL.  (Any value beyond the actual range of the list in question.)

(Don't make it TOOOOOO big or the fraction disappears due to rounding... 🙄)

### Additional information/references
Lowest of low priority...  You can ONLY get the odd behavior if you manually edit the URL.  
But... Sometimes folks manually edit the URL...

**Comment by live627** [comment]
> (Don't make it TOOOOOO big or the fraction disappears due to rounding...
🙄)

32-bit floating point precision sure is fun to fiddle with, especially in
video games.

**Comment by sbulen** [comment]
Dupe of #7522 - closing
