### ISSUE TITLE
Package Manager - "Install Mod" don't replace the readme.txt file in temp folder

### ISSUE THREAD

**Issue by Stefan1200-de** [SimpleMachines/SMF#7399]
#### Description
If you want to install the second mod (compressed with ZIP), the readme.txt file of the first mod will be still displayed.
You have to delete the contents of Packages/temp before you click on "Install Mod" to see the real readme.txt file.

### Steps to reproduce
1. Install any mod using the Package Manager of SMF 2.1.1
2. If you installed the first mod, click on "Install Mod" of the second mod.
3. Now you see the readme.txt file of the first mod, instead of the second mod.

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1.1
- Database Type: MariaDB
- Database Version: 10.4.24
- PHP Version: 7.4.28

### Additional information/references
If you delete the contents of Packages/temp before you click on "Install Mod", you will always see the right readme.txt file.
The directory Packages/temp has 777 permissions.

**Comment by LexArma** [comment]
Haven't seen this happen, and believe I've been doing package installs/uninstalls a lot lately. Is the old readme in the temp folder still? If not, this is more likely to end up not being an SMF issue at all.

**Comment by Stefan1200-de** [comment]
Well, today I can't reproduce it. Yesterday I had it multiple times.
I close this issue.
