### ISSUE TITLE
Undefined index: allow_no_censored

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#740]
i am not sure what is causing this. my test "regular user" on an upgraded 2.1 [from older 2.1's] gets this error on the board index

8: Undefined index: allow_no_censored
http://localhost:8080/github2.1/index.php?http://localhost:8080/github2.1/
File: C:/wamp/www/github2.1/Sources/Load.php
Line: 2428

also i have noticed several times the url gets duplicated like that in the error log

if i check the url i am using in my browser it is not doubled like that at all.

**Comment by Arantor** [comment]
Yeah, line 2428-9 should be:

```
    if ((!empty($options['show_no_censored']) && !empty($modSettings['allow_no_censored']) && !$force) || empty($modSettings['censor_vulgar']) || trim($text) === '')
        return $text;
```
