### ISSUE TITLE
Setting for signatures affects the `url` BBC in entire posts

### ISSUE THREAD

**Issue by isaak654** [SimpleMachines/SMF#7404]
#### Description
This was reported on the Bug Reports board (relevant details are on page 4):
https://www.simplemachines.org/community/index.php?topic=580848.60

If you disable `url` BBC, all links in topics stop working and not just in the signature:
![Capturar](https://user-images.githubusercontent.com/12372772/160886009-2d6fd39e-198c-46ab-a626-7a75db4a2572.PNG)

So signatures should be separate from posts when it comes to the `url` BBC.

**Comment by DiegoAndresCortes** [comment]
@BrickOzp Do you think #7068 is related to this issue?
