### ISSUE TITLE
pacman & pg: indexes not removed when mods uninstalled

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7417]
#### Description
If you install a mod on a pg forum that creates indexes on existing tables, all is OK.  But when you uninstall that mod, the indexes remain.  

Columns and tables are removed properly, but indexes are not.  

### Steps to reproduce
1. Create a pg forum
2. Install a mod that creates indexes on existing tables
3. Uninstall the mod; the indexes remain

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: pg
- Database Version: 14
- PHP Version: 8.0.13

### Additional information/references

**Comment by albertlast** [comment]
could you provide a exampe mod?

**Comment by sbulen** [comment]
No, the one I was looking at isn't approved yet.

But anything that adds an index to an existing table.  It would be easy to mock one up.

**_NOTE that if submitting a PR, we will want to see proof of testing on pg & mysql.  Before & after screenshots._**

**Comment by jdarwood007** [comment]
Shouldn't need a mod.  Should be able to sample this with a simple script that can be executed via SSI.  For the notes on #7418 I would ensure your ssi script for now calls the select db to be safe to not fall into the bugs found with that logic.

**Comment by sbulen** [comment]
...As long as the SSI script reproduces what pacman would do within the app.  pacman saves off the DB changes on install, and uses that info for deinstall.  There is no custom deinstall script; pacman does that automatically.  That is what is failing here.

**Comment by jdarwood007** [comment]
you are correct on that.  My bad.

**Comment by sbulen** [comment]
My theory is that pacman cannot find the indexes...   IIRC, pg ignores the index names you provide & builds its own.  Pacman likely saved off the names you provided.   Just a theory at this point.

**Comment by albertlast** [comment]
how is pacman?

**Comment by Arantor** [comment]
> Shouldn't need a mod. Should be able to sample this with a simple script that can be executed via SSI. For the notes on #7418 I would ensure your ssi script for now calls the select db to be safe to not fall into the bugs found with that logic.

No, that’s not a viable repro situation.

For the package manager to know to remove something, it must be logged during install. Running the SSI file separately does not tag the DB ops against the install to know when to uninstall.

Needs a mod that calls the relevant DB ops during install.

**Comment by sbulen** [comment]
> how is pacman?

Pacman fails, per the initial writeup, above.

**Comment by Arantor** [comment]
Oh, and the SSI file needs to be triggered with `<database>` not `<code>` for the magic to work where the abstraction library registers changes. `<code>` is not expected to log such things.

**Comment by jdarwood007** [comment]
@sbulen 
Will this work for a test file? I ripped out parts from Packages.php that do the logic for the database stuff.  In the end, you should be left with the original tables.  Otherwise the changes will still persist if it fails.

It does fail if you have to specify a character limit in mysql as well and don't specify a name, but I think we can fix that logic easily to strip out (###) matches.

```
<?php
require_once('SSI.php');
db_extend('Packages');
global $context, $user_info, $db_package_log, $ssi_on_error_method;
$context['user']['is_admin'] = $user_info['is_admin'] = true;
$ssi_on_error_method = 'ssi_on_error_method';
set_error_handler('error_handler');

// Add a index with a name and a length on a text field.
// !!! WORKS ON MySQL 8
$smcFunc['db_add_index'](
	'{db_prefix}log_packages',
	[
		'name' => 'idx_hash',
		'columns' => [
			'sha256_hash (64)'
		],
	]
);
/*
// Add a index without a name and a length on a text field.
// ERRORS because the name contains ()
$smcFunc['db_add_index'](
	'{db_prefix}log_packages',
	[
		'columns' => [
			'sha256_hash (64)'
		],
	]
);
*/
// Add a index with a name  on a varchar field without a length
// !!! WORKS ON MySQL 8
$smcFunc['db_add_index'](
	'{db_prefix}log_packages',
	[
		'name' => 'idx_credits',
		'columns' => [
			'credits'
		],
	]
);
// Add a index without a name on a varchar field without a length
// !!! WORKS ON MySQL 8
$smcFunc['db_add_index'](
	'{db_prefix}log_packages',
	[
		'columns' => [
			'credits'
		],
	]
);



// !!! SNIPPED FROM Packages.php
			// If there are some database changes we might want to remove then filter them out.
			if (!empty($db_package_log))
			{
				// We're really just checking for entries which are create table AND add columns (etc).
				$tables = array();

				usort($db_package_log, function($a, $b)
				{
					if ($a[0] == $b[0])
						return 0;
					return $a[0] == 'remove_table' ? -1 : 1;
				});

				foreach ($db_package_log as $k => $log)
				{
					if ($log[0] == 'remove_table')
						$tables[] = $log[1];
					elseif (in_array($log[1], $tables))
						unset($db_package_log[$k]);
				}
				$db_changes = $smcFunc['json_encode']($db_package_log);
			}
			else
				$db_changes = '';

// !!! SIMPLIFIED FROM Packages.php
		$db_changes = $smcFunc['json_decode']($db_changes, true);

// !!! SNIPPED FROM Packages.php
	// If there's database changes - and they want them removed - let's do it last!
	if (!empty($db_changes) /*&& !empty($_POST['do_db_changes'])*/)
	{
		// We're gonna be needing the package db functions!
		db_extend('packages');

		foreach ($db_changes as $change)
		{
			if ($change[0] == 'remove_table' && isset($change[1]))
				$smcFunc['db_drop_table']($change[1]);
			elseif ($change[0] == 'remove_column' && isset($change[2]))
				$smcFunc['db_remove_column']($change[1], $change[2]);
			elseif ($change[0] == 'remove_index' && isset($change[2]))
				$smcFunc['db_remove_index']($change[1], $change[2]);
		}
	}
	
function ssi_on_error_method(): void
{
	global $context;

	echo "\n" . 'A fatal error has occurred in SMF' . "\n";
	echo "---------------------------------------------\n";
	echo $context['error_message'];
	echo "\n---------------------------------------------\n";

	die();
}

function error_handler($error_level, $error_string, $file, $line): void
{
	global $db_show_debug;

	// Error was suppressed with the @-operator.
	if (error_reporting() == 0 || error_reporting() == (E_ERROR | E_PARSE | E_CORE_ERROR | E_COMPILE_ERROR | E_USER_ERROR | E_RECOVERABLE_ERROR))
		return;

	// Pass this to SMF, but don't let it output anything.
	$og = $db_show_debug;
	$db_show_debug = false;
	smf_error_handler($error_level, $error_string, $file, $line);
	$db_show_debug = $og;

	echo $error_level % 255 == E_ERROR ? 'Error' : ($error_level % 255 == E_WARNING ? 'Warning' : 'Notice'), ': ', $error_string, ' in ', $file, ' on line ', $line, "\n";
}
```

**Comment by jdarwood007** [comment]
In DbPackages-Mysql in the smf_db_add_index function
change the name logic to this:
```
		// No need for primary.
		if (isset($index_info['type']) && $index_info['type'] == 'primary')
			$index_info['name'] = '';
		else
			$index_info['name'] = trim(implode('_', preg_replace('~(\(\d+\))~', '', $index_info['columns'])));
```

It seems to make it work when you specify no name and have a length in the index.

**Comment by jdarwood007** [comment]
I spent more time testing.  I've got some fixes I'm working on and will send up for these issues.
