### ISSUE TITLE
smf_db_list_columns defaults and nulls

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7418]
I've been working more with SMF's smf_db_list_columns and smf_db_change_column functions and have come to the conclusion we don't have it working right yet for defaults.  I'm starting this to allow a discussion and present the bug.

To start, PHP has a horrible handling for NULLs.  take for example this:
```
<?php
$a = null;

var_dump(isset($a));
var_dump(is_null($a));
var_dump(isset($b));
var_dump(is_null($b));
```

PHP will report $a is not set but is null.  However for $b, PHP will report $b is not set, but throw a variable undefined error on is_null, then return true.  This is documented in PHP's manual,  but I find it a very horrible syntax that is_null will throw a variable undefined error.   If the variable your checking is in an array, you can use array_key_exists as this works as expected.

Now onto MySQL at least.  The default column has some oddities that require checking the null column.
1. If default is "NULL" and the nullable column is set to "NOT NULL", then the field is required to have a value in it and can not contain null.  In PMA this shows up as "NONE"
2. If the default is "NULL" and the nullable column is "NULL", then the column can contain nulls.
3. The value can either be a int or a string as well.  Thanks to PHP's loose type handling, this is only a problem if you want to do a strict type check.  But it makes it more difficult for us to do checks against because if we do strict type checks, it can fail between the '0' === 0.

This creates issues when you are checking and comparing columns.  I don't think SMF's code is up to snuff on getting this all right.  I've wrote some code, but I dislike the changes.  This is the sample of the changes for list_columns
```
				$default = null;
				// Column is nullalbe and the default is NULL.
				if (is_null($row['Default']) && $row['Null'] == 'YES')
					$default = null;
				// Column is not nullable and the default is set to null, meaning no default.
				elseif (is_null($row['Default']) && $row['Null'] == 'NO')
					$default = false;
				elseif (isset($row['Default']) && $row['Default'] == '\'\'')
					$default = '';
				elseif (isset($row['Default']))
					$default = stripslashes($row['Default']);
```

However the code changes for change_columns is:
```
		if (!array_key_exists('default', $column_info))
			$default = $old_info['default'];
		elseif ($old_info['default'] === false)
			$column_info['default'] = null;

[...]

		// Fix the default.
		$default = '';
		if (is_null($column_info['default']) && empty($column_info['not_null']))
			$default = 'NULL';
		elseif (isset($column_info['default']))
			$default = '\'' . $smcFunc['db_escape_string']($column_info['default'], self::$db_connection) . '\'';
```

It is fairly ugly, but it does the work.  Anyone else have a better opinion on trying to get this right?

**Comment by jdarwood007** [comment]
I got to thinking.  We are trying to complicate the default too much.

The list_columns should return the proper default for a default match.  Simply be, if Default is NULL, we make it null, otherwise we strip away the quotes and thats that. We would try to do a is_numeric test.
MySQL does allow you to use a default with no quotes if a is a number.  I haven't tested everything, but I assume all ints and decimal formats are fine.
```
CREATE TABLE `test`.`test` ( `test` float NOT NULL DEFAULT 3.01 ) ENGINE = InnoDB;
```
You can't use a default of something like 3.01f, with or without strings.

Thus I think to have the list_columns handle this all safely I think its best if we ensure to our best knowledge, the proper values and make them type safe.

```
			// Handle null safely.
			if (array_key_exists('Default', $row) && (is_null($row['Default']) || $row['Default'] = 'NULL'))
				$default = null;
			// Do a int check.
			elseif (isset($row['Default']) && is_numeric($row['Default']))
				$default = strpos($row['Default'], '.') ? floatval($row['Default']) : intval($row['Default']);
			// Get rid of quotes around the value and any escaped values.
			else
				$default = stripslashes($row['Default']);
```

For change_column (and add_column),  I think we need to change the fallback check to do safe null check as well
```
	if (!array_key_exists($column_info['default']))
		$column_info['default'] = $old_info['default'];
```

Then finally where we prepare the query:
```
	// Fix the default.
	$default = '';
	// Make it null.
	if (is_null($column_info['default']))
		$default = 'NULL';
	// Numbers don't need quotes.
	elseif (is_numeric($row['default']))
		$default = strpos($row['default'], '.') ? floatval($row['default']) : intval($row['default'])
	// Non empty string.
	elseif (!empty($row['default']))
		$default = '\'' . $smcFunc['db_escape_string']($column_info['default']) . '\'';
```

No testing has been done yet.  I think this gets the default handled right.

This is ignoring the NOT NULL checks on the column, since those don't mater.  But the mod author will have to know to pass the default and not null properly to get the expected output.  We can provide notes on that.

```
CREATE TABLE `test` (
  `FloatTest` float NOT NULL DEFAULT '3.01',
  `NullableDefaultNull` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `NullDefaultBlank` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '',
  `NullDefaultValue` varchar(1) DEFAULT 'a',
  `NotNullDefaultBlank` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
  `NotNullBlankValue` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'a'
)
```

MySQL will return the following for that (at least in 8.0)
```
SELECT column_name "Field", COLUMN_TYPE "Type", is_nullable "Null", COLUMN_KEY "Key" , column_default "Default", extra "Extra" FROM information_schema.columns WHERE table_name = 'test' ORDER BY ordinal_position;
+---------------------+------------+------+-----+---------+-------+
| Field               | Type       | Null | Key | Default | Extra |
+---------------------+------------+------+-----+---------+-------+
| FloatTest           | float      | NO   |     | 3.01    |       |
| NullableDefaultNull | varchar(1) | YES  |     | NULL    |       |
| NullDefaultBlank    | varchar(1) | YES  |     |         |       |
| NullDefaultValue    | varchar(1) | YES  |     | a       |       |
| NotNullDefaultBlank | varchar(1) | NO   |     |         |       |
| NotNullBlankValue   | varchar(1) | NO   |     | a       |       |
+---------------------+------------+------+-----+---------+-------+
```

Which on the float test it becomes a float, the NullableDefaultNull it becomes NULL, NullDefaultBlank would just pass '' and NullDefaultValue would pass 'a'.  The last two would do the same except send the "NOT NULL".

**Comment by sbulen** [comment]
Simpler is better.  Yes, when we query a column, e.g., the default value, we must explicitly check for null vs blank string.  And substitute a token of sorts (e.g, 'NULL') where necessary...  I had to do that for my smf_db_compare.php utility.

(I confess that the php logic makes sense to me...)

**Comment by jdarwood007** [comment]
We shouldn't sub a string of 'NULL' for the literal of NULL.  Thats two different things in reality.  I work with SQL Server and SSMS does this though when I use the editor (lazy fixing sometimes while doing db work).

I've got something I'm working on that I think fixes it all the right way.  I just need to do more testing.  Also discovered some other bugs with regards to table name handling causing issues.  For instance.  If you use db_create_table command and run it twice (using the overwrite), it will try to issue a drop_table command. But that will fail under some circumstances (mine was while running via SSI), because the table name it passes is no longer the cleaned name.  I notice another issue is we run db_list_tables to find all table, but we assume in the code (with no way to change it), the database smf is in.  Even if you intend to call it for another database.  The fix here is to find our db name from the table call if it can and then pass that into list_tables.
