### ISSUE TITLE
pacman: Legacy NULL setting doesn't work

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7420]
#### Description
When the NOT_NULL setting was added to pacman, the prior NULL setting was kept around for legacy support.

It doesn't appear to be working.  We should either make it work or remove it.

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: mysql (didn't check pg)

### Additional information/references
**_NOTE that if submitting a PR, we will want to see proof of testing on pg & mysql. Before & after screenshots._**

**Comment by jdarwood007** [comment]
DbPackages-(mysql|postgresql).php

for the smf_db_create_query_column function


Add this before the return
``` 
	// Backwards compatible with the nullable column.
	if (isset($column['null']) && !isset($column['not_null']))
		$column['not_null'] = !$column['null'];
```

I think it fixes it?
