### ISSUE TITLE
8: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by vsc55** [SimpleMachines/SMF#7426]
#### Description
When accessing this url an error is reported:
https://youforo/index.php?action=admin;area=logs;sa=errorlog;filter=id_member;value=0

### Steps to reproduce
1. Go Admin > Rgister > Log Error
2. Click Filter User

### Environment (complete as necessary)
- Version/Git revision: 2.1.1
- Database Type: Mysql
- PHP Version: 7.4.1

**Comment by isaak654** [comment]
I assume that the commit to evaluate here is https://github.com/vsc55/SMF2.1/commit/7e409a6af64616239838ed949fd77da1dd4042d2 coming from https://github.com/vsc55/SMF2.1/tree/patch-1

**Comment by isaak654** [comment]
PR: https://github.com/SimpleMachines/SMF2.1/pull/7427
