### ISSUE TITLE
Spaces in URLs cause issues

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7441]
#### Description
Note this works fine in 2.0.  Not sure what changed.

This has been reported multiple times in the forum.  This can also affect migrated forums, e.g., pix that displayed fine in 2.0 simply disappear in 2.1 (if there was a space in the name).  

Note that spaces in _directories_ has been reported as well.

### Steps to reproduce
1. Add a link to an image that has a space in the filename.  It is not displayed in 2.1.

e.g.,:
`[img]https://blahblah.com/forum/pix/Another Night Task.jpg[/img]`

### Additional information/references
From the forum:
https://www.simplemachines.org/community/index.php?topic=582068.0

Note similar issue with directories:
https://www.simplemachines.org/community/index.php?topic=580741.0

**Comment by LexArma** [comment]
Quite honestly, not sure if this worth putting much effort in to - Fixing this would be supporting behaviour that goes against accepted standards that define that a URL must not contain a literal space.

**Comment by jdarwood007** [comment]
If its contained inside the image bbc, doing a url encode should be acceptable.

**Comment by sbulen** [comment]
> If its contained inside the image bbc, doing a url encode should be acceptable.

Yep.  I suspect that's what 2.0 does.

What bugs me is that folks have them in their 2.0 forums, upgrade to 2.1 and the images disappear.  You shouldn't lose content in the upgrade.

**Comment by Sesquipedalian** [comment]
It's technically wrong, but yes, we should support it for backward compatibility with 2.0.x.
