### ISSUE TITLE
Content spoofing, action=helpadmin;help=payload

### ISSUE THREAD

**Issue by LexArma** [SimpleMachines/SMF#7444]
Admin help popup apparently allows for easy content spoofing. 
Reported here https://www.simplemachines.org/community/index.php?topic=582136
Confirmed to work on simplemachines.org https://www.simplemachines.org/community/index.php?action=helpadmin;help=Content%20Spoofing%20Bug

**Comment by Arantor** [comment]
It’s always done this. Historically it even relied on this functionality, not sure if any current use still does though.

Note that you can’t force this into the body of a pop up since there’s no way to trigger either reqOverlayDiv or reqWin from any user content normally, and it’s proofed against XSS.

**Comment by nixoeen** [comment]
It's true that it cannot be used for XSS attacks, but Content Spoofing can still be used for phishing or similar attacks. Here are some additional information:
https://owasp.org/www-community/attacks/Content_Spoofing

A solution could be having a checksum with a static secure salt.

$checksum_salt = "v(Fkx_&j7<T6j!;+"; // A random text in the config file
$help = "Help Text!"; // Text which is going to be shown
$checksum = md5($text.$checksum_salt); // Checksum as an argument

So the URL would be like:
https://www.simplemachines.org/community/index.php?action=helpadmin;help=Help%20Text!&checksum=0bfdb5c95e5ecea96e1b2427665dfe5c

This way, we can check if the text is really generated by the website owner and not by users.

**Comment by Arantor** [comment]
Adding that in all the places it would be required is high effort. Better to just not accept arbitrary payload and fix the places that it is relied on, if any.

Note that this also needs patching in 2.0 as well as 2.1.
