### ISSUE TITLE
Cannot Browse SM Package Server

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7447]
#### Description
From this report on the forum:
https://www.simplemachines.org/community/index.php?topic=582160.0

If you attempt to browse the Simple Machines Third Party Mod Site here:
![image](https://user-images.githubusercontent.com/23568484/167186766-4262803e-7643-4681-a5ca-75449c14ac25.png)

You get:
![image](https://user-images.githubusercontent.com/23568484/167186883-6b2692e8-febb-431c-bb8a-aaa080ec2dde.png)

### Environment (complete as necessary)
- Version/Git revision:  All 2.x, including current

**Comment by Sesquipedalian** [comment]
Given that an error message comes up when one goes to the suggested the URL, my guess is that this is a problem on simplemachines.org rather than a problem in SMF. (I can always be wrong, though.)

**Comment by sbulen** [comment]
At work, can't look very close...   I'm on the fence, initially thought the url looked wrong.  That may have just been trying to do too much on my phone... 🙄

**Comment by jdarwood007** [comment]
It is from the server side.  Patched it.
