### ISSUE TITLE
FILTER_SANITIZE_STRING Deprecated in PHP 8.1

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#7451]
More of a heads up: FILTER_SANITIZE_STRING Deprecated in PHP 8.1 https://wiki.php.net/rfc/deprecations_php_8_1

Used in
Sources\Profile-Modify.php(1281): if ($row['mask'] == 'nohtml' && ($valueReference != strip_tags($valueReference) || $value != filter_var($value, FILTER_SANITIZE_STRING) || preg_match('/<(.+?)[\s]*\/?[\s]*>/si', $valueReference)))

**Comment by live627** [comment]
https://github.com/SimpleMachines/SMF2.1/issues/7358
