### ISSUE TITLE
quick_actions class is pushed off-screen with long text strings

### ISSUE THREAD

**Issue by isaak654** [SimpleMachines/SMF#7454]
#### Description
Bug report tracked for further investigation:
https://www.simplemachines.org/community/index.php?msg=4123315

Example with Dutch language:
https://www.simplemachines.org/community/index.php?topic=27642.msg4123313#msg4123313

<img alt="quick_actions_class" src="https://user-images.githubusercontent.com/12372772/167316535-a2b98b97-a772-4cd0-965f-ffd76f20ca02.jpg" height="600px">

**Comment by DiegoAndresCortes** [comment]
Can't reproduce.
Tested in firefox and chrome
![Screenshot_18](https://user-images.githubusercontent.com/3318127/198862129-b8ebf32a-cfc6-41cb-b1a4-0b706945b2f1.png)
![Screenshot_17](https://user-images.githubusercontent.com/3318127/198862130-766544a5-845f-4692-95af-4a5c21505146.png)

**Comment by live627** [comment]
Try to chane the text of the GO button

**Comment by DiegoAndresCortes** [comment]
Woah

https://youtu.be/Z--YtlDs-Ro
