### ISSUE TITLE
"Toggle source view" strips hyperlinks in pasted rich-text

### ISSUE THREAD

**Issue by Geremia** [SimpleMachines/SMF#7455]
#### Description
Clicking "Toggle source view" strips hyperlinks in pasted rich-text.

### Steps to reproduce
1. Paste rich-text with hyperlinks into textarea.
2. Click the "Toggle source view" button.

### Environment (complete as necessary)
- Version/Git revision: 2.1.1
- Database Type: Postgres
- Database Version: 10.10
- PHP Version: 7.4.29

### Additional information/references

Copying this:
[![Screenshot 2022-05-08 at 14-41-31 Do married couples need to live sexually](https://user-images.githubusercontent.com/4298614/167316965-94dc7446-8105-441a-bcc5-440dc9a5e041.png)](https://christianity.stackexchange.com/a/56224/1787)
and pasting into the textarea:
![Screenshot 2022-05-08 at 14-43-21 Start new topic](https://user-images.githubusercontent.com/4298614/167317026-7e900f81-16c1-4844-ba26-922aa91821df.png)
gives this, after clicking "Toggle source view":
```bbc
Cappello, S.J., [i]Tractatus Canonico-Moralis de Sacramentis. Vol V. De Matrimonio[/i], p. 805 (quoted in McAuliffe, [i]Catholic Moral Teaching on the Nature and Object of Conjugal Love[/i] p. 77):
```
clicking "Toggle source view" again:
![Screenshot 2022-05-08 at 14-45-34 Start new topic](https://user-images.githubusercontent.com/4298614/167317070-aba9ccea-1126-48a0-a560-e94558319738.png)

**Comment by Sesquipedalian** [comment]
Do the links work if you click on them in the editor immediately after pasting the text?

**Comment by Geremia** [comment]
@Sesquipedalian No.

The HTML of the rich-text I copied:
```html
Cappello, S.J., <a href="https://archive.org/details/Cappello1947N.822840PA" rel="nofollow noreferrer">
<em>Tractatus Canonico-Moralis de Sacramentis. Vol V. De Matrimonio</em></a>, p. 805 (quoted in McAuliffe, 
<a href="https://isidore.co/calibre/#panel=book_details&amp;book_id=5766" rel="nofollow noreferrer">
<em>Catholic Moral Teaching on the Nature and Object of Conjugal Love</em></a> p. 77):
```
Pasting the rich-text copied in Firefox into a Thunderbird email retains the links, however.

Copying the hyperlinks from the editor and pasting that into Thunderbird also retains the hyperlinks.

**Comment by Sesquipedalian** [comment]
That means that those links are not being recognized by the editor as links at all. That is the reason they are not formatted as links when you toggle into source mode.

So the question is, why are these links not recognized as links?

To help diagnose that, first please tell us exactly what URLs those links are supposed to point to. Maybe that will give us a clue.

**Comment by Sesquipedalian** [comment]
Oh, you edited your comment while I was replying. Thanks for the additional information. Based on that, my first idea was wrong.

Next question: what rich text editor is this text being copied from?

**Comment by Geremia** [comment]
@Sesquipedalian I copied it from [here](https://christianity.stackexchange.com/a/56224/1787).

**Comment by Geremia** [comment]
This bug is present in SMF 2.1.2, too.

**Comment by Sesquipedalian** [comment]
That's not surprising. SMF 2.1.2 had already been finalized before this issue report was opened. But we've got it on the milestone for 2.1.3, and @live627 definitely knows what he is doing with SCEditor, so it'll be fixed. 🙂
