### ISSUE TITLE
Changes to admin email notification when a user resets their password

### ISSUE THREAD

**Issue by isaak654** [SimpleMachines/SMF#7460]
#### Description
This was reported on the Bug Reports board:
https://www.simplemachines.org/community/index.php?topic=582238.0

> Currently, when a user resets their SMF password, SMF sends an email to the Admin account(s) stating a new user has joined the forum. I've never understood this as the message is not correct. What the message should say, if one should even be sent at all, is something to the affect of "User xxx just reset their password." Personally, I don't see any value for password reset messages going to Admins anyway and think they should just be a silent entry in the user log for tracking only.
> 
> It's been this way for as long as I've used SMF so I just thought I'd put it in writing in case the devs wanted to deal with it.

> this is only when you have the forum set to email activation. i have seen this happen before. they activate their account with the new email address and the admin gets an email that a new member has been created. has been this was since SMF 2.0 at least.
> 
> this is not just for setting a new password, but when they change their email address as far as i am aware.

**Comment by Sesquipedalian** [comment]
I couldn't find a way to reproduce this when a member changes their password, but I could when they changed their email address.

At any rate, #7476 should take care of all possible situations, because it checks the member's current activation status to make this decision, rather than relying on the presence of a URL parameter.
