### ISSUE TITLE
integrate_manage_subscriptions runs too late to be useful

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#7461]
integrate_manage_subscriptions exists notionally to allow adding subactions to the manage-paid-subscriptions area in ManagePaid.php. However, it runs too late to actually do this.

The hook allows adding to the sub actions array in the root of ManagePaidSubscriptions but by the time the hook runs, the subaction will have already been validated against the known list and unknown subactions will have been removed.

The call needs to be moved before $_REQUEST['sa'] is sanitised.

**Comment by Arantor** [comment]
Case in point: https://www.simplemachines.org/community/index.php?msg=4124407 cannot be made hooks only for this reason. (And another, but this is an actual dealbreaker if I wanted to keep the paidsubs code under area=paidsubscribe)

**Comment by DiegoAndresCortes** [comment]
It appears is worse than that.

@dragomano pointed this out here: #7380 
PR was closed: #7398

**Comment by Arantor** [comment]
I didn’t look beyond the one case I cared about but I can’t say I’m surprised.
