### ISSUE TITLE
Two minor bugs with mentions

### ISSUE THREAD

**Issue by woodholly** [SimpleMachines/SMF#7462]
#### Description
Hard to explain, see examples.

### Steps to reproduce
1. Create two users with usernames: BestUser and BestUserNumberTwo
2. Create post mentioning @BestUserNumberTwo
3. System appoints BestUser and creates invalid link mentioning BestUser , not BestUserNumberTwo

Second bug:
1. Create user with username: best.user@gmail.com
2. Create post mentioning him: @best.user@gmail.com
3. Invalid "mailto:" link created :)

### Environment (complete as necessary)
- Version/Git revision: 2.1RC3, I bet it fails in 2.1 too

**Comment by Sesquipedalian** [comment]
I cannot reproduce the first report, but I can reproduce the second one.

**Comment by woodholly** [comment]
@Sesquipedalian hmm, try to create post with this: @BestUserblabla but do not register BestUserblabla user.

**Comment by isaak654** [comment]
Other mentions issues were described in the following thread:
https://www.simplemachines.org/community/index.php?topic=582378.0

**Comment by Sesquipedalian** [comment]
> @Sesquipedalian hmm, try to create post with this: @BestUserblabla but do not register BestUserblabla user.

Nope. No mention was created at all.

**Comment by woodholly** [comment]
and BestUser should be registered, for me it creates mention like this:
```
<a href="....">BestUser</a>blabla
```
but this is in RC3

**Comment by Sesquipedalian** [comment]
> this is in RC3

That explains a lot. Upgrade your forum to SMF 2.1.2, and then check whether the issue persists for you. If it does, then post in the [SMF 2.1 support board](https://www.simplemachines.org/community/index.php?board=254.0) so that someone can help you figure out what is causing the issue on your forum.
