### ISSUE TITLE
TypeError on manageattachments URL with php 8.1 and SMF 2.1.2

### ISSUE THREAD

**Issue by isaak654** [SimpleMachines/SMF#7466]
#### Description
This was reported on the Bug Reports board:
https://www.simplemachines.org/community/index.php?topic=582308.0

**Comment by sbulen** [comment]
I haven't been able to duplicate this.  This looks like their attachment directory was not properly converted to JSON somehow.

**Comment by sbulen** [comment]
I am going to close this we we cannot reproduce & never heard back.
