### ISSUE TITLE
sha1_file(/blah/blah/attachments/23993_heapbigblahblah): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7468]
#### Description
Reported in the  forum here:
https://www.simplemachines.org/community/index.php?topic=582243.0
https://www.simplemachines.org/community/index.php?topic=582241.0

I have seen one of these in my forum after our 2.1 upgrade.  In my instance, this file referenced an avatar that had been recently deleted.  I don't think the check to see if the file exists is working somehow.

I get this consistently attempting to download non-existent attachments in 2.1.2.

IP addresses appear to refer to bots; this appears to be crawl activity where reported.  

![image](https://user-images.githubusercontent.com/23568484/169203367-8ae71b71-914a-4991-8bd1-ab8fbaf5714e.png)

### Environment (complete as necessary)
- Version/Git revision: 2.1.2
- Database Type: mysql
- Database Version: 5.6
- PHP Version: 7.4

**Comment by jdarwood007** [comment]
I got these as well and it seemed to be non normal attachments (typically avatars).  Seems the upgrader didn't handle them all the way properly.

**Comment by sbulen** [comment]
This is not an upgrader issue.

The logic is failing when the file is not found.  In my case, they were deleted.  I think web crawlers think they're still there.

**Comment by jdarwood007** [comment]
Ahh.  Well it should fail the query then as the entry in the attachments table should also not exist.

**Comment by Sesquipedalian** [comment]
Please test #7470, gentlemen.

**Comment by sbulen** [comment]
But it's much more fun to bicker over details...  😈

**Comment by sbulen** [comment]
(And yes, @jdarwood007 is correct, this is what happens when the rec exists & the file doesn't...)

**Comment by klikr** [comment]
Not important development-wise, but I thought these error messages were attack attempts, and I blocked the IPs from my server via fail2ban.

**Comment by sbulen** [comment]
Since these are caused by crawlers hitting old links, it's possible they will recur.  Just another bot.

It's also possible you are preventing your site from being indexed properly.   Make sure it's a crawler you don't care about.
