### ISSUE TITLE
Uncaught ValueError after SMF 2.1.2 upgrade (Vietnamese)

### ISSUE THREAD

**Issue by isaak654** [SimpleMachines/SMF#7475]
#### Description
It was reported here:
https://www.simplemachines.org/community/index.php?msg=4125080

> After upgrade to version 2.1.2, I use Vietnamese language package and get this issue:
> `PHP Fatal error:  Uncaught ValueError: Missing format specifier at end of string in /Themes/default/Display.template.php:695`
> 
> I have already tested with English language, everything works well.

https://github.com/SimpleMachines/SMF/blob/8b19aab2abe65e50ee3bb04bc6bde646c47d9118/Themes/default/Display.template.php#L695

**Comment by Oldiesmann** [comment]
Not something that can be dealt with on GitHub. It's a problem with that specific language. The appropriate people are looking into it.
