### ISSUE TITLE
Attachment preview issue with error "Not a valid attachment ID"

### ISSUE THREAD

**Issue by isaak654** [SimpleMachines/SMF#7484]
Some references with reproducible steps: 
https://www.simplemachines.org/community/index.php?msg=4125831
https://www.simplemachines.org/community/index.php?msg=4125947
https://www.simplemachines.org/community/index.php?msg=4125940
https://www.simplemachines.org/community/index.php?msg=4125985

**Comment by sbulen** [comment]
~~I believe these were all explained in that thread, & this issue can be closed.~~

**Comment by sbulen** [comment]
Correction/clarification:  2.1.2 and current GH behave very differently...  Some of the issues reported above are valid for current GH, but not for 2.1.2.  Hence some of the confusion.
