### ISSUE TITLE
smf/simple/master

### ISSUE THREAD

**Issue by Bmgxyzp** [SimpleMachines/SMF#7485]
#### Description
--Description Here--

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by Bmgxyzp** [comment]
[](https://github.com/Bmgxyzp)

**Comment by sbulen** [comment]
Appears to have been opened in error.

**Comment by DiegoAndresCortes** [comment]
They are bots I think, seen it before

**Comment by Bmgxyzp** [comment]
no im human

**Comment by jdarwood007** [comment]
This provides no useful information not a issue report.
