### ISSUE TITLE
Database error installing mod

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7492]
#### Description

```
Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys
File: /Packages/temp/install-sd.php
Line: 47

CREATE TABLE smf_helpdesk_role_permissions
(
`id_role` smallint(5) unsigned NOT NULL DEFAULT 0,
`permission` varchar(40) NOT NULL ,
`add_type` tinyint(3) unsigned NOT NULL DEFAULT 0,
PRIMARY KEY (id_role,permission(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci


CREATE TABLE smf_helpdesk_preferences
(
`id_member` mediumint(8) unsigned NOT NULL DEFAULT 0,
`variable` varchar(30) NOT NULL ,
`value` text NOT NULL ,
PRIMARY KEY (id_member,variable(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
```

### Steps to reproduce
1.  Install SimpleDesk from attached file
2. Fails

### Environment (complete as necessary)
- Version/Git revision: [5c1766b](https://github.com/SimpleMachines/SMF/commit/5c1766bd571bbddb12b9ae749e5400bf8382cc9c)
- Database Type: Mysql
- Database Version: 8.0
- PHP Version: 8.0

### Additional information/references
Related to #7424

@sbulen Looks like a BC issue?
There is no collation specified, so its possible i'm defaulting to mb4.  PMA doesn't make it clear which collation is being used.

I was able to work around it by specifying a (30) in the indexes.
[SimpleDesk_2.1.0-broken.zip](https://github.com/SimpleMachines/SMF/files/8790252/SimpleDesk_2.1.0-broken.zip)

**Comment by sbulen** [comment]
Why are you specifying a length of 191 when the fields are only 30 & 40 bytes?  That's likely the problem.

Collation is specified, should be ok there.

**Comment by jdarwood007** [comment]
I didn't specify 191.  Thats what happened when I try to install it.

So perhaps if they don't specify a size we need to determine if the column is greater than 191 and then force it to stay at 191?

**Comment by sbulen** [comment]
Correct - only specify 191 when the field is longer than that....   E.g., varchar(192) or TEXT or MEDIUMTEXT, etc.

**Comment by jdarwood007** [comment]
Then thats likely the error.  I need to tell it to only do 191 when it exceeds the size.  I will make up a PR tomorrow or next week.
