### ISSUE TITLE
Disabling the option "Allow guests to browse the forum" results in log errors

### ISSUE THREAD

**Issue by isaak654** [SimpleMachines/SMF#7493]
Reference: https://www.simplemachines.org/community/index.php?topic=582440.0

### Steps to reproduce

Requirement: SMF 2.1.2

1. Have a topic in your forum with an attachment that is visible to guests
2. Click to download the attachment
3. Copy the download link
4. Close the forum for guests
5. Logout (or use an incognito window)
6. Try to download the link by pasting the copied link

Result:
a login page stripped of all css and around 90 errors in the log:

>     Guest
>     2a02:a213:a701:c080:e978:66ac:9e70:3ea9
>     7582d457acd4349c6806adc18fe2249d
>     https://test.fjr-club.nl/index.php?action=dlattach;attach=22387
>     /home/deb77453/domains/fjr-club.nl/public_html/test/Sources/Subs-Auth.php (Line 224)  Backtrace information
> 
>     Type of error: Undefined
>     Error messageSelect
>     8: Undefined index: login
> 
>     Guest
>     2a02:a213:a701:c080:e978:66ac:9e70:3ea9
>     7582d457acd4349c6806adc18fe2249d
>     https://test.fjr-club.nl/index.php?action=dlattach;attach=22387
>     /home/deb77453/domains/fjr-club.nl/public_html/test/Themes/default/Login.template.php (Line 291)  Backtrace information
> 
>     Type of error: Undefined
>     Error messageSelect
>     8: Undefined index: one_hour

#### Note: the forum's owner suddenly reopened the test forum to guests, so you can't rely on the attachment links above. It would be advisable to try reproducing the issue in a separate forum with guest browsing disabled.

**Comment by Bopske** [comment]
Forum owner (me) stated clearly that this is a test forum (being used for other things) This error can be easily reproduced in any test forum without any mods.
If so desired I can close the forum again.

**Comment by DiegoAndresCortes** [comment]
I couldn't yet reproduce this.
Any other settings playing along with it? I only checked/unchecked 'Allow guests to browse the forum', didn't return any errors when visiting the forum as a guest or browsing it as the admin.
