### ISSUE TITLE
Encoded entity &amp; is displayed in attachments titles

### ISSUE THREAD

**Issue by isaak654** [SimpleMachines/SMF#7494]
#### Description
https://www.simplemachines.org/community/index.php?topic=582507.0

<img alt="Screen Shot 2022-05-28 at 11 33 43 AM" src="https://user-images.githubusercontent.com/12372772/171159006-b963a1e7-4af6-43bb-a996-e82802805a2b.jpg" height="250px">

According to the author, it's only on 2.1.x not 2.0.x

**Comment by isaak654** [comment]
Is it fixed in 2.1.3?

**Comment by BrickOzp** [comment]
2.1 do htmlspecialchars before store the filename.
2.0 seems to not have done this since I have attachments without encoding.

2.1 do a second htmlspecialchars when the attachment is retrieved.
