### ISSUE TITLE
"Not a valid attachment ID" errors for inserted attachments after previously receiving a valid error

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7496]
#### Description
"Not a valid attachment ID" errors for inserted attachments after previously receiving a valid error.

### Steps to reproduce
1. Start a new topic; enter a subject, but leave the body blank
2. Add some attachments
3. Upload the attachments (do not insert)
4. Press "Preview"
5. You will get the "The message body was left empty" error
6. Insert the images, maybe even add text
7. Press "Preview"
8. You will see the "Not a valid attachment ID" errors

You get different issues if you press "Post" vs "Preview".  "Post" in step 4 discards the uploaded attachments entirely.
### Environment (complete as necessary)
- Version/Git revision: 2.1.2
- Database Type: mysql
- Database Version: 8
- PHP Version: 8

### Additional information/references
![image](https://user-images.githubusercontent.com/23568484/171461825-c18cd95d-b02f-42dc-8515-3a730f746c8e.png)

**Comment by Oldiesmann** [comment]
See also #7484 ...

**Comment by sbulen** [comment]
Those other posts/that other issue are all from the same thread, and the explanations are in the thread. Most weren't reproducible in vanilla code, only smorg.

Some folks were complaining about issues with bbc still existing after deleting the attachment.  And as explained there, that would require manual cleanup.  

This happens with current code.

**Comment by sbulen** [comment]
Actually...  Just tried a few things...  There is a big difference in behavior between 2.1.2 and current GitHub code.  

Current GitHub code:  @Oldiesmann is correct - you can reproduce the issue with a simple upload/insert/preview.

2.1.2:  The only way to reproduce the issue is via the complicated set of instructions above.  

The reason smorg is not OK is that smorg is using more current GH code.
