### ISSUE TITLE
Can't sort Sent PM's by User

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#7508]
#### Description
https://www.simplemachines.org/community/index.php?topic=582802.0

### Steps to reproduce
1.  Go to the pms > Sent items
2. Attempt to sort by user

**Comment by Oldiesmann** [comment]
Works fine on my forums and for me on simplemachines.org. Might be related to the server configuration.

**Comment by DiegoAndresCortes** [comment]
I find it strange that it works for you on simplemachines, but I get the issue there.
I have 60 pages of messages in the sent items area.

**Comment by Oldiesmann** [comment]
I've got 18 pages and it doesn't cause any problems for me on simplemachines or my seniors site (though I only have one page there).

**Comment by live627** [comment]
22 pages in convo mode—works
56 pages for one at a time—fails
same story for all at once
