### ISSUE TITLE
Cannot enable 2fa

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#7513]
Tried to enable 2FA on my localhost with a fresh copy of SMF 2.1.2 via Google Authenticator app. (windows 11, php 7.2)

It doesn't work. It used to work with previous RC versions on my localhost.

![2fa](https://user-images.githubusercontent.com/17809451/176107453-7d78a13d-0469-452e-abc5-8cc6050c6aa8.png)

**Comment by Oldiesmann** [comment]
It worked fine on my test board. Double check to make sure the code didn't expire - when I enabled it on my test board the code that Authy generated expired within a few seconds of the time it showed up.

**Comment by asmith20002** [comment]
Apparently it had something to do with my windows time. Even though the time was displaying correctly both on windows tray and on my SMF forum, but it I had to turn on "daylight saving" for it to be completely in sync.

It's working fine now.
