### ISSUE TITLE
CURLOPT_POSTFIELDSIZE does not exist in PHP Subscriptions-PayPal.php

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#7521]
Noticed in my logs on PHP 8.0
PHP Fatal error:  Uncaught Error: Undefined constant "CURLOPT_POSTFIELDSIZE" in Sources\Subscriptions-PayPal.php:146

Affects SMF 2.1.x and SMF 2.0.x

Found this mentioning it does not exist.
https://stackoverflow.com/questions/34971617/warning-curl-setopt-expects-parameter-2-to-be-long-string-given

**Comment by Oldiesmann** [comment]
Interesting. It's still listed as an option in the libcurl documentation. https://curl.se/libcurl/c/CURLOPT_POSTFIELDSIZE.html

**Comment by Oldiesmann** [comment]
It's still part of the C API apparently. Don't know why PHP chooses to not implement it. https://curl.se/libcurl/c/CURLOPT_POSTFIELDSIZE.html

**Comment by live627** [comment]
See the link that @VBGAMER45 posted

> There is no such option as `CURLOPT_POSTFIELDSIZE` in PHP. That is automatically set for you internally when you specify `CURLOPT_POSTFIELDS`.

https://stackoverflow.com/a/34971666/4710434
