### ISSUE TITLE
logActions can get invalid id_member when called from Scheduled tasks

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#7546]
When triggering _removeMembersFromGroups_ using a scheduled task, it calls logAction > logActions to log the changes.
When using a scheduled task, id_member might be 0, causing the following:

```
The database value you're trying to insert does not exist: id_member
Function: logActions
```

Culprit: 
https://github.com/SimpleMachines/SMF/blob/release-2.1/Sources/Logging.php#L539-L542

**Comment by DiegoAndresCortes** [comment]
I can't reproduce it, it's very possible I caused it

**Comment by DiegoAndresCortes** [comment]
I think I found the issue?
@live627 @sbulen  I suppose that $user_info['id'] is **0**, when the scheduled task is calling certain functions?

I edited the content of the issue to describe it.
I think a solution could be to replace
```
else
			$memID = $user_info['id'];
```

With
```
else
			$memID = !empty($user_info['id']) ? $user_info['id'] : $log['extra']['member'];
```
That should always return a valid action (self action if using s scheduled I guess).
And the query below should have _ignore_ to prevent any issues when no users are found.

**Comment by DiegoAndresCortes** [comment]
I tried to replicate the error but no success. 
It's quite strange as even when the error happens, the code execution doesn't stop/doesn't fail, it just throws the error and continues.

**Comment by jdarwood007** [comment]
I opened #7740 which has more tracing on this.  Its because $user_info is null because cron.php does not setup the user data.  The missing extra data causes the check to fall back to trying to use the user_info which is null.

**Comment by DiegoAndresCortes** [comment]
@jdarwood007 Would the initial solution work?

https://github.com/SimpleMachines/SMF/issues/7546#issuecomment-1299439817

**Comment by jdarwood007** [comment]
It should.  We just need to handle the case where $user_info is null because we are running from cron that didn't even populate it as guest data.
