### ISSUE TITLE
Wrong value type sent to the database. Array of integers expected. (preview_attachments) 

### ISSUE THREAD

**Issue by mobasuite** [SimpleMachines/SMF#7582]
#### Description
Wrong value type sent to the database. Array of integers expected. (preview_attachments) 

### Steps to reproduce
1. v2.1.3
2. fresh upgrade

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version: alt-php81

### Additional information/references

**Comment by sbulen** [comment]
Cannot reproduce - & I've done numerous installs & upgrades in various environments.

How exactly did you upgrade?  Please provide step-by-step details.

Also, please specify the requested environment information.

Steps to reproduce error.  Source program/line.  Etc...

**Comment by mobasuite** [comment]
I've managed to solve it somehow.

**Comment by andrew-davie** [comment]
I have this issue.
Caused by creating a post with an attachment, no content.
Then it complained there was no content in the message. I added some text, and clicked post.
Now it displays only as "Wrong value type sent to the database. Array of integers expected. (preview_attachments)"
I also have no way to delete/remove.

SMF 2.1.4
ProCurve Theme

**Comment by andrew-davie** [comment]
Further info - this is particulary annoying as I'm admin and it's screwed up my admin access to the forums.
Here's the backtrace...

<img width="629" alt="Screenshot 2024-06-30 at 11 37 04 PM" src="https://github.com/SimpleMachines/SMF/assets/16424075/51e98570-bd17-4f1e-8014-990ce326f311">

I tested in private window visiting the forum and all is working as expected for a guest.

AFTER verifying as my logged-in admin I could not access any posts/forums, I logged out and back in again, and all is working as expect.  So, some sort of session bug cured by log out/in, it looks like.  At least we have a bit of a backtrace here.

**Comment by DiegoAndresCortes** [comment]
@andrew-davie I cannot reproduce the issue with the steps you provided.
New Post/Topic > Upload attachment > Post >  The message body was left empty > Add text > Post > No issues.

**Comment by andrew-davie** [comment]
> @andrew-davie I cannot reproduce the issue with the steps you provided. New Post/Topic > Upload attachment > Post > The message body was left empty > Add text > Post > No issues.


Fair enough. The only thing slightly different is that it was a reply to an existing post so I wasn't exactly clear.
The backtrace should at least show what's wrong, though. Anyway I hope never to see it again, but there's definitely a bug in there somewhere. Thanks for looking, and especially thank you for the wonderful forum software.
