### ISSUE TITLE
Verification questions not configured properly. Please report this error to an administrator.

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7597]
#### Description
I am getting these errors in my log occasionally.  These errors are usually, but not always, for guests.  Sometimes it looks like it's during a search, sometimes during a preview...

But the verification questions are in fact configured properly...

There was a recent PR that uniquely ID'd the error recently.  I don't think this PR caused the error, but I do think it made it easier to identify exactly which edit is failing:  #7536 

Prior to that PR, the error was the "you don't have access" one.  However, it was not logged.  Since #7536, it's getting logged.

It looks like when you just change the language in the middle of a captcha test, it's missing the $_REQUEST part of this test:
https://github.com/SimpleMachines/SMF/blob/aa2f168c69e5286222bae88a11c36edd3ce9368f/Sources/Subs-Editor.php#L2115

### Steps to reproduce
1. Have verification questions setup for guest search.
2. Do a guest search, but answer the verification questions incorrectly, so you are provided error messages.
3. Change languages in the dropdown in the top menu bar.

### Environment (complete as necessary)
- Version/Git revision:  Current GH
- Database Type: mysql
- Database Version: 5.6
- PHP Version: 7.4

### Additional information/references
Backtrace of all variants of this error include the Post.php line 1651 & the Subs-Editor.php line 2116:
![image](https://user-images.githubusercontent.com/23568484/199634748-3d88b23b-71e9-4d2c-ac50-c2c591148dbd.png)

**Comment by live627** [comment]
> There was a recent PR that uniquely ID'd the error recently. I don't think this PR caused the error, but I do think it made it easier to identify exactly which edit is failing: #7536

I took a peek at the PR in question and saw that it removed `false` as the second parameter, which means that now it is logged.

**Comment by sbulen** [comment]
Yep.

I think that's a good thing though...   Previously folks were just getting "you're not allowed" errors, which made no sense.   And hid the bug from us...  We can fix it, now we know about it!

**Comment by sbulen** [comment]
I added this to 2.1.4 as big forums might see this a lot...
