### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by vsc55** [SimpleMachines/SMF#7601]
#### Description
2: Invalid argument supplied for foreach()
Type: general
Level: 2
File (/var/www/html/Sources/Subs.php) in line 4545
URL:  https://foro/index.php?action=dlattach;attach=2433

**Comment by sbulen** [comment]
Steps to reproduce?

I don't think we've seen this.

Environment information - verison of SMF, PHP, etc.?

**Comment by vsc55** [comment]
### Steps to reproduce
I don't know exactly how it happened, I saw it in the error logs.
It could be caused by creating a new subforum but I can't confirm it.

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1.2
- Database Type: MariaDB
- Database Version: 10.3.32
- PHP Version: 7.4.1
