### ISSUE TITLE
Tooltip on Category buttons on hover

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7607]
#### Description
The upshrink/downshrink buttons attempt to show "Show Category" when collapsed & "Hide Category" when not.

But it always says "Show Category"...

### Steps to reproduce
1. Hover over the Show/Hide Category buttons
2. Expand/Collapse

### Environment (complete as necessary)
- Version/Git revision: Current
- Database Type: MySQL
- Database Version: 8
- PHP Version: 8.1

 ### Additional information/references
https://www.smfhelper.com/index.php?topic=1194.0

**Comment by DiegoAndresCortes** [comment]
This does work as intended... If you refresh the page.
It does not have any javascript at the moment, to handle the title.

**Comment by DiegoAndresCortes** [comment]
I tested in Moderation and it does handle the change correctly, something is interfering then.

**Comment by DiegoAndresCortes** [comment]
I have a solution without editing the board template

**Comment by sbulen** [comment]
I think I would be OK with changes that update the template - ** IF ** the change brings consistency.  

In most instances, the hover works.  

I'm OK with any change, even to a template, if it is consistent with how these hovers normally work.
