### ISSUE TITLE
Attachment undefined href

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7625]
#### Description
From my forums error log.  I haven't tried to reproduce this.  But it seems some data is missing.
/Sources/Subs.php (Line 1809)

Type of error: Undefined
Error message
2: Undefined array key "href"

**Comment by live627** [comment]
very helpful and vague. Maybe try posting the uri and the backtrace.

**Comment by jdarwood007** [comment]
There was no relevant url.  It was somebody trying to post in a board.  The code seems to indicate this lines of code:
```
					// No image. Show a link.
					else
						$returnContext .= '<a href="' . $currentAttachment['href'] . '" class="bbc_link">' . $smcFunc['htmlspecialchars'](!empty($data) ? $data : $currentAttachment['name']) . '</a>';
```

Looking back at the code, parseAttachBBC loads the $currentAttachment, which does work and tries to load data by calling loadAttachmentContext.  It does a check that it is not a string (as a string indicates error), but it doesn't check its not a empty array.
However I didn't receive an error about undefined 'name'.  Just href.  So I can't be certain that is what we are seeing here.  But it would be my guess a failed upload of some sorts.

**Comment by dragomano** [comment]
https://www.simplemachines.org/community/index.php?msg=4150101

![sshot-1](https://user-images.githubusercontent.com/229402/230724074-032e8974-b97f-4f62-85a2-8af01bb9a8a7.png)

**Comment by Bopske** [comment]
I can confirm that fix works...
