### ISSUE TITLE
MySQL 8.0 pacman case sensitivity issue reading information_schema

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7626]
#### Description
Upon reinstalling a mod, you may get errors:
```
Database Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ',,,,,,)
			SELECT ,,,,,,
			FROM smf_message_bookmarks_old' at line 1

```
But the root cause is earlier in the error log:
`2: Undefined array key "column_name"`

In DbPackages-mysql.php, line 257:
https://github.com/SimpleMachines/SMF/blob/79970ebbe29b11c8dfe0d7e3ef2f9a7f000e70a0/Sources/DbPackages-mysql.php#L257

### Steps to reproduce
1. Mysql 8 - attempt to reinstall a mod, keeping the data from the prior installation

### Environment (complete as necessary)
- Version/Git revision:  2.1.3
- Database Type: mysql
- Database Version: 8
- PHP Version: 8.1

### Additional information/references
From the forum:
https://www.simplemachines.org/community/index.php?msg=4131633

In this pic, you can see that DbPackages-mysql.php is looking for 'column_name', but what is returned from a query to INFORMATION_SCHEMA is 'COLUMN_NAME':
![pacman_issue](https://user-images.githubusercontent.com/23568484/203238752-d21c7275-9b25-4afa-ab24-87328bd6b9a3.png)

**Comment by live627** [comment]
> ### Steps to reproduce
> 
> 1. Mysql 8 - attempt to reinstall a mod, keeping the data from the prior installation

2. It must `db_create_table` with mode `update`
