### ISSUE TITLE
Add user to group is not logged correct

### ISSUE THREAD

**Issue by BrickOzp** [SimpleMachines/SMF#7628]
#### Description
The logging when adding a user to a group is not correct.

### Steps to reproduce
1. Add a user to a group
2. Look at the error log.
3. It is logged as 'Added "" to the "<member group>" group' and by the added user, not by the user doing the adding

Expected
3. Logged as 'Added "<added user>" to the "<member group>" group' and by the user doing the adding

### Environment (complete as necessary)
- Version/Git revision: 2.1.3
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by DiegoAndresCortes** [comment]
Mmmm it's possible this is related to #7546 ?
My tests only ever had issues when logging the group changes, nothing else seemed to trigger it, but very inconsistent behavior.

**Comment by BrickOzp** [comment]
No, this is just a mistake to include the member_affected instead of member in the logging array
