### ISSUE TITLE
Gravatars are enabled even when avatars are disabled

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7635]
#### Description
Gravatars should be governed by avatar permissions.  There are no separate gravatar permissions.  On a forum with gravitars enabled, but a usergroup has no avatar permissions, that group can still use gravitars.  

![image](https://user-images.githubusercontent.com/23568484/204879237-d49dd378-f6ed-49ab-8234-b0084e50fb1b.png)

![image](https://user-images.githubusercontent.com/23568484/204879849-2698e906-2ceb-4c8d-bcad-3c458912aaf1.png)

### Steps to reproduce
1. Disable avatars for one membergroup
2. Enable gravitars globally
3. Logon as a member of that membergroup - gravitars are allowed

### Environment (complete as necessary)
- Version/Git revision: 2.1.3
- Database Type: MySQL
- Database Version: 8.0
- PHP Version: 8.1

### Additional information/references
From the forum:
https://www.simplemachines.org/community/index.php?topic=584338.0

**Comment by DiegoAndresCortes** [comment]
Needs closing too @Sesquipedalian
