### ISSUE TITLE
Accessing The Ban List Produces Undefined Array Key "sa"

### ISSUE THREAD

**Issue by TwitchisMental** [SimpleMachines/SMF#7640]
#### Description
Get 4 errors in error log when trying to access the ban list.

### Steps to reproduce
1.  Fresh Install of 2.1.3
2.  Access the Ban List from the "Administration Center"  This only happens when using the icon on the "Administration Center" page.
3.  Check error log after and see 4 errors. 2: Undefined array key "sa"

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1.3
- Database Type: MariaDB
- Database Version: 8.0.23
- PHP Version: 8.0.23

### Additional information/references
#0: smf_error_handler()
    Called from [C:\xampp8.0\htdocs\smf\Sources\ManageBans.php on line 72](https://127.0.0.1/smf/index.php?action=admin;area=logs;sa=errorlog;file=QzpceGFtcHA4LjBcaHRkb2NzXHNtZlxTb3VyY2VzXE1hbmFnZUJhbnMucGhw;line=72)
    #1: Ban()
    Called from [C:\xampp8.0\htdocs\smf\Sources\Admin.php on line 499](https://127.0.0.1/smf/index.php?action=admin;area=logs;sa=errorlog;file=QzpceGFtcHA4LjBcaHRkb2NzXHNtZlxTb3VyY2VzXEFkbWluLnBocA==;line=499)
    #2: AdminMain()
    Called from [C:\xampp8.0\htdocs\smf\index.php on line 191](https://127.0.0.1/smf/index.php?action=admin;area=logs;sa=errorlog;file=QzpceGFtcHA4LjBcaHRkb2NzXHNtZlxpbmRleC5waHA=;line=191)

**Comment by sbulen** [comment]
Confirmed this was introduced in 2.1.3.
