### ISSUE TITLE
"Simple Machines Download Site" package server not working

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#7644]
#### Description
When trying to browse the "Simple Machines Download Site" package server under Admin -> Main -> Package Manager -> Add Packages -> Download new packages -> Package servers, it displays an error message: "Unable to connect to the server. Please try using [this URL](https://download.simplemachines.org/browse.php?api=v1;smf_version=2.1.2/index.php) instead."; also note that link is broken.

### Environment (complete as necessary)
- Version/Git revision: 2.1.2 and 2.1.3
- Database Type: postgres / any
- Database Version: any?
- PHP Version: any?

**Comment by jdarwood007** [comment]
This is fixed.  It was a issue with our site.
