### ISSUE TITLE
Word boundaries have changed in MySQL 8.0.4, affecting some searches

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#7654]
#### Description
MySQL 8.0.4 changed the implementation of its regex engine from Henry Spencer's implementation to International Components for Unicode (ICU). This involves some non-backward compatible changes, which are listed [in the documentation](https://dev.mysql.com/doc/refman/8.0/en/regexp.html#regexp-compatibility).

> The Spencer library supports word-beginning and word-end boundary markers (`[[:<:]]` and `[[:>:]]` notation). ICU does not. For ICU, you can use `\b` to match word boundaries; double the backslash because MySQL interprets it as the escape character within strings.

@albertlast is there a function to detect MySQL version? Could you create a pull request that adds a new function to Search.php that returns correct word boundaries for each database version? I can then add a commit to it that applies that new function to the relevant code, if you're okay with that.

### Steps to reproduce
1. Enable the option to search whole words
2. Create a search for whatever
3. > Hello darkness, my old friend
   > I've come to talk with you again
   > Because a vision softly creeping
   > Left its seeds while I was sleeping
   > And the vision that was planted in my brain
   > Still remains
   > Within the sound of silence

### Environment (complete as necessary)
- Version/Git revision: I like burritos
- Database Type: MySQL
- Database Version: 8
- PHP Version: Not relevant

### Additional information/references
https://www.simplemachines.org/community/index.php?topic=584449.0
https://stackoverflow.com/questions/59998409/error-code-3685-illegal-argument-to-a-regular-expression

**Comment by albertlast** [comment]
we got some places where the db version get checked:
https://github.com/SimpleMachines/SMF/blob/79970ebbe29b11c8dfe0d7e3ef2f9a7f000e70a0/Sources/Subs-Db-mysql.php#L1068-L1086
this are mostly feature based approache (so that the calling programm didn't need to know under which circumnstance this feature get available).
how ever want to check this issue has to do also checks with mariadb,
for me i got no env with this complexity also regex is for me unkown topic.

**Comment by live627** [comment]
I have added my fix to https://github.com/SimpleMachines/SMF/pull/7651, which also makes this work on pgsql.
