### ISSUE TITLE
Notification mail template is inconsistent with "Immediately" notification setting

### ISSUE THREAD

**Issue by sagamusix** [SimpleMachines/SMF#7655]
#### Description

Continued from https://www.simplemachines.org/community/index.php?topic=584475.0

Even if you set the notification settings to "Immediately" rather than "Immediately - First time only", the mail template says the following:

> More replies may be posted, but you won't receive any more notifications for this topic until you visit it.

I certainly got a bit confused because I got more than one mail, but I also didn't get a mail for every reply. This sentence should probably be omitted from the mail if notifications are set to "Immediate". Maybe it should also mention that not every reply will trigger an immediate mail notification, as SMF tries to avoid being too spammy.

**Comment by nc3man** [comment]
I checked the value of _$frequency_   in CreatePost-Notify.php for the **Immediately** setting. It is non-empty, equal to 1. For **Immediately (but only for the first unread message)** _$frequency=2_. So the following change to line 540 in CreatePost-Notify.php works for smf 2.1.2. I tested it under both conditions.
`	$message_type = (!empty($frequency) && $frequency==2) ? 'notify_boards_once' : 'notify_boards';`

**Comment by nc3man** [comment]
Realizing this is low priority since it's just a sentence in a notification email, but I'm surprised this hasn't been assigned since it was noted ~4 months ago and the fix is evidently simple.

**Comment by Sesquipedalian** [comment]
> I'm surprised this hasn't been assigned since it was noted ~4 months ago

I can't speak to that, but if you want to submit a PR to fix it, I'm sure the dev team would appreciate it.

**Comment by nc3man** [comment]
I'm not sure what a PR is. It is already a GitHub issue. If you can tell me
what a PR is in this context, I'll be happy to submit and further raise the
issue. Does it involve $$$ 😉? I'm sensitive to people's time and resources.
Thanks

**Comment by smfbigguy** [comment]
PR = Pull request. He is asking if you would like to submit a fix for this problem. No money allowed. :)

**Comment by nc3man** [comment]
Funny ... in my work PR means "purchase request" and it definitely involves $$$. Sure, I can offer the one line fix as a git PR :)

**Comment by DiegoAndresCortes** [comment]
This one should be closed too @Sesquipedalian
