### ISSUE TITLE
Notification query needs tuning - can encounter MAX_JOIN_SIZE issues

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7661]
#### Description
One of the main notifications queries sometimes goes all cartesian & causes the following error in the logs: 
`Database Error: The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay`

Adding an index on id_board on log_notify addresses the issue.

From the forum:
https://www.simplemachines.org/community/index.php?topic=584569.0

The query may be found here:
https://github.com/SimpleMachines/SMF/blob/d3a8569377639fd559068477a05c5cf2bc0579fb/Sources/tasks/CreatePost-Notify.php#L124

### Steps to reproduce
1. I think we've only seen this happen when the host has put a strict low value on MAX_JOIN_SIZE.   (7000000 in the forum example.)

### Environment (complete as necessary)
- Version/Git revision:  2.1.3
- Database Type:  MySQL
- Database Version:  8.0
- PHP Version: 8.1

### Additional Information:
![Screenshot 2022-12-27 173916](https://user-images.githubusercontent.com/23568484/209744458-2d01ee54-5a27-4607-b6c3-1f3ab93c15b7.png)

**Comment by albertlast** [comment]
sql command

```sql
SELECT
	ln.id_member, ln.id_board, ln.id_topic, ln.sent,
	mem.email_address, mem.lngfile, mem.pm_ignore_list,
	mem.id_group, mem.id_post_group, mem.additional_groups,
	mem.time_format, mem.time_offset, mem.timezone,
	b.member_groups, t.id_member_started, t.id_member_updated
FROM smf_log_notify AS ln
	INNER JOIN smf_members AS mem ON (ln.id_member = mem.id_member)
	LEFT JOIN smf_topics AS t ON (t.id_topic = ln.id_topic)
	LEFT JOIN smf_boards AS b ON (b.id_board = ln.id_board OR b.id_board = t.id_board)
WHERE ln.id_member != 13639
	AND ln.id_topic = 181 OR ln.id_board = 26516

**Comment by sbulen** [comment]
### I compared 5 different queries, with & without the index:
 Q1 - Existing
 Q2 - Subquery (to try & force it to do the log_notify query first)
 Q3 - Union (from albertlast in the forum)
 Q4 - Union (inner joins)
 Q5 - Union (inner joins, separate board & topic queries)

Adding an index to the existing query yielded the best results - by far.

Query 5 yielded the best results without adding an index.

I think the simplest solution is the best: just add the index.

## Results:

### Query 1 - Existing
**_With index:_**
![Q1_PLAIN_IX_TIME](https://user-images.githubusercontent.com/23568484/209859092-071d091b-4444-41a3-9a88-4493e70bc03d.png)
![Q1_PLAIN_IX_EXPLAIN](https://user-images.githubusercontent.com/23568484/209859102-3b64e823-77fa-45a9-ac76-b361f77344f9.png)

**_Without index:_**
![Q1_PLAIN_NOIX_TIME](https://user-images.githubusercontent.com/23568484/209859127-38789178-1d4c-4332-a85a-942cdd3a3f65.png)
![Q1_PLAIN_NOIX_EXPLAIN](https://user-images.githubusercontent.com/23568484/209859138-e97c1421-64bd-470a-a641-fdc2521127ea.png)

### Query 2 - Subquery
**_With index:_**
![Q2_SUBQ_IX_TIME](https://user-images.githubusercontent.com/23568484/209859159-50b48370-dd2e-426d-8e4a-4d16fbd2c587.png)
![Q2_SUBQ_IX_EXPLAIN](https://user-images.githubusercontent.com/23568484/209859168-f2253bcc-05ee-4485-913e-c97fc4265b44.png)

**_Without index:_**
![Q2_SUBQ_NOIX_TIME](https://user-images.githubusercontent.com/23568484/209859193-088cf716-ac7a-419b-88ab-2e5d242c7560.png)
![Q2_SUBQ_NOIX_EXPLAIN](https://user-images.githubusercontent.com/23568484/209859201-a35eacb6-3d58-42f8-ba92-7eaface166a2.png)

### Query 3 - Union
**_With index:_**
![Q3_UNION_IX_TIME](https://user-images.githubusercontent.com/23568484/209859240-08741d05-d9cf-47e7-883f-ee3fd17cdb02.png)

**_Without index:_**
![Q3_UNION_NOIX_TIME](https://user-images.githubusercontent.com/23568484/209859254-83a70ef0-8b01-4106-8696-88fe936d1283.png)

### Query 4 - Union with inner joins
**_With index:_**
![Q4_UNION_IX_TIME](https://user-images.githubusercontent.com/23568484/209859262-9a43d64e-bb1a-4abf-be25-ddbd3e4e48f0.png)

**_Without index:_**
![Q4_UNION_NOIX_TIME](https://user-images.githubusercontent.com/23568484/209859273-5e5515cc-8462-4153-9c64-32c6f4ef255d.png)

### Query 5 - Union with separate board & topic queries
**_With index:_**
![Q5_UNION_IX_TIME](https://user-images.githubusercontent.com/23568484/209861845-f74fbcd6-2ded-4b52-8143-daf530bd0671.png)

**_Without index:_**
![Q5_UNION_NOIX_TIME](https://user-images.githubusercontent.com/23568484/209861857-53eab479-cbb8-4a59-8628-310915408975.png)

## Raw Queries:
```
SELECT
	ln.id_member, ln.id_board, ln.id_topic, ln.sent,
	mem.email_address, mem.lngfile, mem.pm_ignore_list,
	mem.id_group, mem.id_post_group, mem.additional_groups,
	mem.time_format, mem.time_offset, mem.timezone,
	b.member_groups, t.id_member_started, t.id_member_updated
FROM smf_log_notify AS ln
	INNER JOIN smf_members AS mem ON (ln.id_member = mem.id_member)
	LEFT JOIN smf_topics AS t ON (t.id_topic = ln.id_topic)
	LEFT JOIN smf_boards AS b ON (b.id_board = ln.id_board OR b.id_board = t.id_board)
WHERE ln.id_member != 13639
	AND ln.id_topic = 181 OR ln.id_board = 26516;
```

```
SELECT
	ln.id_member, ln.id_board, ln.id_topic, ln.sent,
	mem.email_address, mem.lngfile, mem.pm_ignore_list,
	mem.id_group, mem.id_post_group, mem.additional_groups,
	mem.time_format, mem.time_offset, mem.timezone,
	b.member_groups, t.id_member_started, t.id_member_updated
FROM smf_members AS mem
	INNER JOIN 
	(
		SELECT id_member, id_board, id_topic, sent
		FROM smf_log_notify
		WHERE id_member != 13639
			AND id_topic = 181 OR id_board = 26516
	) AS ln ON (ln.id_member = mem.id_member)
	LEFT JOIN smf_topics AS t ON (t.id_topic = ln.id_topic)
	LEFT JOIN smf_boards AS b ON (b.id_board = ln.id_board OR b.id_board = t.id_board)
```

```
SELECT
	ln.id_member, ln.id_board, ln.id_topic, ln.sent,
	mem.email_address, mem.lngfile, mem.pm_ignore_list,
	mem.id_group, mem.id_post_group, mem.additional_groups,
	mem.time_format, mem.time_offset, mem.timezone,
	b.member_groups, t.id_member_started, t.id_member_updated
FROM smf_log_notify AS ln
	INNER JOIN smf_members AS mem ON (ln.id_member = mem.id_member)
	LEFT JOIN smf_topics AS t ON (t.id_topic = ln.id_topic)
	LEFT JOIN smf_boards AS b ON (b.id_board = t.id_board)
WHERE ln.id_member != 13639
	AND ln.id_topic = 181
UNION ALL
SELECT
	ln.id_member, ln.id_board, ln.id_topic, ln.sent,
	mem.email_address, mem.lngfile, mem.pm_ignore_list,
	mem.id_group, mem.id_post_group, mem.additional_groups,
	mem.time_format, mem.time_offset, mem.timezone,
	b.member_groups, null, null
FROM smf_log_notify AS ln
	INNER JOIN smf_members AS mem ON (ln.id_member = mem.id_member)
	LEFT JOIN smf_boards AS b ON (b.id_board = ln.id_board)
WHERE ln.id_member != 13639
	AND ln.id_board = 26516
```

```
SELECT
	ln.id_member, ln.id_board, ln.id_topic, ln.sent,
	mem.email_address, mem.lngfile, mem.pm_ignore_list,
	mem.id_group, mem.id_post_group, mem.additional_groups,
	mem.time_format, mem.time_offset, mem.timezone,
	b.member_groups, t.id_member_started, t.id_member_updated
FROM smf_log_notify AS ln
	INNER JOIN smf_members AS mem ON (ln.id_member = mem.id_member)
	INNER JOIN smf_topics AS t ON (t.id_topic = ln.id_topic)
	INNER JOIN smf_boards AS b ON (b.id_board = t.id_board)
WHERE ln.id_member != 13639
	AND ln.id_topic = 181
UNION ALL
SELECT
	ln.id_member, ln.id_board, ln.id_topic, ln.sent,
	mem.email_address, mem.lngfile, mem.pm_ignore_list,
	mem.id_group, mem.id_post_group, mem.additional_groups,
	mem.time_format, mem.time_offset, mem.timezone,
	b.member_groups, null, null
FROM smf_log_notify AS ln
	INNER JOIN smf_members AS mem ON (ln.id_member = mem.id_member)
	INNER JOIN smf_boards AS b ON (b.id_board = ln.id_board)
WHERE ln.id_member != 13639
	AND ln.id_board = 26516
```

```
SELECT
	ln.id_member, ln.id_board, ln.id_topic, ln.sent,
	mem.email_address, mem.lngfile, mem.pm_ignore_list,
	mem.id_group, mem.id_post_group, mem.additional_groups,
	mem.time_format, mem.time_offset, mem.timezone,
	b.member_groups, t.id_member_started, t.id_member_updated
FROM smf_topics AS t 
	INNER JOIN smf_log_notify AS ln ON (t.id_topic = ln.id_topic)
	INNER JOIN smf_members AS mem ON (ln.id_member = mem.id_member)
	INNER JOIN smf_boards AS b ON (b.id_board = t.id_board)
WHERE ln.id_member != 13639
	AND t.id_topic = 181
UNION ALL
SELECT
	ln.id_member, ln.id_board, ln.id_topic, ln.sent,
	mem.email_address, mem.lngfile, mem.pm_ignore_list,
	mem.id_group, mem.id_post_group, mem.additional_groups,
	mem.time_format, mem.time_offset, mem.timezone,
	b.member_groups, null, null
FROM smf_boards AS b 
	INNER JOIN smf_log_notify AS ln ON (b.id_board = ln.id_board)
	INNER JOIN smf_members AS mem ON (ln.id_member = mem.id_member)
WHERE ln.id_member != 13639
	AND b.id_board = 26516
```

**Comment by albertlast** [comment]
the amount of rows doesn't look good to me for an performance test,
could you go higher? somthing in a more smf.org size

**Comment by sbulen** [comment]
The above tests are on a live board with 40k users & 245k posts.   Real data.  Mid-sized board.  

You can do the comparisons also!  Queries are above!

**Comment by albertlast** [comment]
the base is real, yea,
but i see "showing rows 0",
which mean that no return happening.

a real world example is better than i trying to simulate this in beahvior.

**Comment by albertlast** [comment]
created a test case where return amount is ~4k rows,
pg 14 in ms:
| Query # | 4k rows | emtpy | 4k rows index | empty index | 
| -------------- | --------- | ----------| ---------- |  ---------- |
| 1 | 43 | 0.37 | 45 |  0.10 |
| 2 | 44 | 0.37 | 57 | 0.05 |
| 3 | 5 | 0.33 | 5 | 0.07 |
| 4 | 4 | 0.35 | 4 | 0.07 |
| 5 | 4 |  0.08 | 4 |  0.09 |

**Comment by sbulen** [comment]
OK, you got me curious, so I rebuilt my pg large db for a side by side comparison.  

Very similar DBs, pg 14 & mysql 8.0.20, both with ~2.5M posts, 1K boards, 30K users, 300K topics.  Both have ~2.5M log_notify records, random distribution.  Result set ~2900 rows for both, with the exact same queries.  I think this is unusually high, even for a very large forum.  But makes for a good test...

|Query|MySQL wo/ix|MySQL w/ix|PG wo/ix|PG w/ix|
|-|-|-|-|-|
|1|2.08 s|1.09 s|0.20 s|0.08 s|
|2|2.05 s|1.06 s|0.20 s|0.08 s|
|3|0.89 s|0.03 s|0.18 s|0.07 s|
|4|0.84 s|0.02 s|0.21 s|0.07 s|
|5|0.83 s|0.03 s|0.21 s|0.07 s|

As expected, overall pg performs way better.

The UNION queries helped MySQL a lot, but not really pg.  For both, the different UNION query variants didn't make much of a difference.

Unexpected, but mysql 8 had a slight edge over pg on the UNION queries when the index was added.

So...  It may make sense to do both the IX and a UNION query.  It will certainly be beneficial for very large forums, especially on MySQL.

**Comment by sbulen** [comment]
~We've seen a variation of this on another forum, so the issue was not a one-off.  (https://www.simplemachines.org/community/index.php?topic=586123.0)~

EDIT:  That forum topic is unrelated.

Flagging for 2.1.5 to at least draw some further discussion.

**Comment by live627** [comment]
These solutions seem a little over engineered to me. Why not simply modify the predicate depending on the alert type?

		$request = $smcFunc['db_query']('', '
			SELECT
				ln.id_member, ln.id_board, ln.id_topic, ln.sent,
				mem.email_address, mem.lngfile, mem.pm_ignore_list,
				mem.id_group, mem.id_post_group, mem.additional_groups,
				mem.time_format, mem.time_offset, mem.timezone,
				t.id_member_started, t.id_member_updated
			FROM {db_prefix}log_notify AS ln
				JOIN {db_prefix}members AS mem ON (ln.id_member = mem.id_member)
				LEFT JOIN {db_prefix}topics AS t ON (t.id_topic = ln.id_topic)
			WHERE ' . ($type == 'topic' ? 'ln.id_board = {int:board}' : 'ln.id_topic = {int:topic}'),
			array(
				'member' => $posterOptions['id'],
				'topic' => $topicOptions['id'],
				'board' => $topicOptions['board'],
			)
		);

**Comment by sbulen** [comment]
It's been a while, but IIRC, the challenge is you can have both.  A single post may trigger a set of topic notifications as well as a set of board notifications.  The logic in that task is built around that, and works from a common list/query.  

The problem is scalability...  I think these users with strict MAX_JOIN_SIZE are basically the canaries in the coal mine for us here, letting us know we need to tune this query.

**Comment by sbulen** [comment]
Similar report here, same query:  https://www.simplemachines.org/community/index.php?topic=586169.0

**Comment by sbulen** [comment]
My input on this old guy is that it should be a priority for 3.0 as well.

Tuning the notification query is important - we have seen it can be a problem.

**Comment by jdarwood007** [comment]
@sbulen,
Why is your id_topic so low, but id_board so high?  Seems like its flipped.

**Comment by sbulen** [comment]
Possibly.  It's been a while.  

I did have a very large DB generated by populate for a while there.  I had also mocked up some data to  test via scripts.  Note in the EXPLAIN it was returning boards.

I don't think I have that particular test environment around any longer.
