### ISSUE TITLE
Language in url can cause invalid redirects

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7671]
#### Description
When language is added to the url after a XML action, it can cause a invalid redirect.

### Steps to reproduce
1. Visit a topic
2. Quick edit the topic
3. Add ;language=english to the url
4. Your redirected to the xml action

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by jeffythedragonslayer** [comment]
can confirm - when I follow these steps at https://www.simplemachines.org/community/index.php?topic=585414.0, this is what I get:

![image](https://user-images.githubusercontent.com/13253146/226147727-9d12abb6-0131-4a39-b1e1-c4fdd81afbd8.png)
