### ISSUE TITLE
an unnecessary "&quote;" destroyed the bbc url and iurl code in custom warning templates

### ISSUE THREAD

**Issue by The4Apes** [SimpleMachines/SMF#7674]
#### Description
If i create or modify a custom warning template and save it, the url oder iurl code like `[url=http://simplemachines.org]text[/url]` will be changed to `[url=&quot;http://simplemachines.org&quot;]text[/url]`
`&quot;` will be added when saving the code, the modified code is stored in database and also used in the message for the member, when you warning a member.
The link in the message that the member receives has this format `<a href="http://&amp;quot;http://simplemachines.org&amp;quot;" class="bbc_link" target="_blank" rel="noopener">text</a>` and will not work.
I think the cause is to find in Subs-Post.php, but i don't know where exactly.

### Steps to reproduce
1. create a custom warning template with url like `[url=http://simplemachines.org]text[/url]`
2. save it
3. open it again to edit, or warning a member and use this template
4. check the message the member received

### Environment (complete as necessary)
- Version/Git revision: 2.1.13

### Additional information/references
Workaround: Delete the `&quot;` entities from the custom warning templates directly in database table "log_comments"

**Comment by Sesquipedalian** [comment]
The link does work, actually. 

However, you are right that when the admin edits an existing warning template, the `&quot;` entities are not being converted back to `"` characters.

The bug here seems to be that entities are not being decoded correctly when the existing template string is displayed to the admin.

**Comment by The4Apes** [comment]
You are wrong or misunderstand me.
Please read the Description above again, i've added a few things and fixed the code formatting.
`&quot;` will be added when saving the code, the wrong code is so stored in database and used, when you warning a member.
The link doesn't work, it can't. Because of this bug the link in the message, that the member receives, has this format `<a href="http://&amp;quot;http://simplemachines.org&amp;quot;" class="bbc_link" target="_blank" rel="noopener">text</a>`
