### ISSUE TITLE
Failed redirect when a guest tries to download an attachment 

### ISSUE THREAD

**Issue by Techie-GSC** [SimpleMachines/SMF#7690]
EDIT: RESOLVED! SEE COMMENT BELOW!

#### Description
When a guest tries to download an attachment with no permission, it will not redirect the user to the login page correctly and will produce unneeded error logs such as `2: Undefined array key "session_id"`

### Steps to reproduce
1. A Guest (When the permission to view forum in settings is off) inputs the URL to downlaod an attachment (E.G. `https://*/forum/index.php?action=dlattach;attach=10`
2. The form will not redirect the guest, and the URL will remain the same while the following screen is displayed: https://prnt.sc/wCu2Z-nNr10e

### Environment (complete as necessary)
SMF v. 2.1.3

EDIT: Upon closer look, it seems like the `loadTheme()` function in Security.php Line 117ish isn't being called properly - which would (I think...?) Result in this issue.

**Comment by Techie-GSC** [comment]
Solved! The **main** index.php falsely states the entire theme does not need to be loaded to download attachments. While this is true in most cases, it will cause errors is a guest attempts to download an attachment when the option to let guests browse the forum is OFF.

index.php line 229:
`	// Attachments don't require the entire theme to be loaded.
	if (isset($_REQUEST['action']) && $_REQUEST['action'] == 'dlattach' && empty($maintenance))
		detectBrowser();
	// Load the current theme.  (note that ?theme=1 will also work, may be used for guest theming.)
	else
		loadTheme();`

**Comment by DiegoAndresCortes** [comment]
Is the guest not able to download attachments, or not able to browse the forum?
See #7589

**Comment by Techie-GSC** [comment]
> Is the guest not able to download attachments, or not able to browse the forum? See #7589

It seems to be a similar issue to #7493

**Comment by DiegoAndresCortes** [comment]
Did you try the fix for that issue?
If so, we could close this. It will be included in the next patch.

**Comment by Techie-GSC** [comment]
I must be blind, but I cannot see the fix for the issue? Could you post a direct link?

**Comment by DiegoAndresCortes** [comment]
Here: https://github.com/SimpleMachines/SMF/pull/7589/files

**Comment by Techie-GSC** [comment]
Yes, that fixes the solution. You can close this issue.
