### ISSUE TITLE
Emoticons problem

### ISSUE THREAD

**Issue by JerryCrazy** [SimpleMachines/SMF#7695]
Hello SMF Team

A friend of mine upgraded SMF 2.0.17 to 2.1.3, after some small configuration changes, everything is more or less fine, but I have a problem with the emoticons.

In the configuration, the smileys packs appear well, but SCEditor refuses to display the emoticons bar, and emoticons do not appear in messages.

The result in the page for posting messages :
"emoticons": [],
"emoticonsDescriptions": [],
"emoticonsEnabled": false,

Have you ever seen this kind of problem after a migration?
Do you have any ideas?

I've tried everything I can with the permissions, but it doesn't seem to have made a difference.

Thank you for help
If you have any ideas...

- Version:  2.1.3
- Database Type: SQL
- PHP Version: 7.4.33

**Comment by Sesquipedalian** [comment]
Your question appears to be a support request rather than a bug report. You should go to https://www.simplemachines.org/community/index.php and ask for help in the SMF 2.1 Support board.

**Comment by JerryCrazy** [comment]
OK, thank you.

For me, this is also a bug in addition to being a support request. ;)

**Comment by JerryCrazy** [comment]
I found out what the problem was

In "Smileys and Message Icons", if "Enable customized smileys" is disabled,
I did not see the options referring to smileys.
The option that interests me here is "Edit smiley".
No more smiley faces had a GIF or PNG assigned (the fields were empty), I have reassigned the file names.
And I re-disabled "Enable customized smileys".
