### ISSUE TITLE
Add/Edit Board "Allowed Groups" issue

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#7724]
SMF 2.1.3
With default permission profile

When you add or edit board if you uncheck all membergroups and post groups from "Allowed Groups"
The board is still visible on main display clicking on the board results in an error of the board being off limits. Along with topics inside that board visible in other areas.

Looks like an issue with smf_board_permissions_view not being cleared/set correctly.

**Comment by jdarwood007** [comment]
Try with this PR: https://github.com/SimpleMachines/SMF/pull/7540
I think it may fix that.

**Comment by VBGAMER45** [comment]
@jdarwood007  I have the 2.13 with this PR: 7540 was included in 2.1.3
I think that condition if statement added broke it in 2.1.3 taking it out fixes the issue.
	if (!empty($boardOptions['deny_groups']) || !empty($boardOptions['access_groups'])) {


Think it is the second part. I haven't look at the last PR 7540 at that issue in depth.

**Comment by jdarwood007** [comment]
I got it mixed up with #7692

**Comment by VBGAMER45** [comment]
Ah your right. You can close this. Looks like a duplicate of that issue. Tested that fix and it works.
