### ISSUE TITLE
8192: Use of "parent" in callables is deprecated

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#7725]
#### Description
General error in /Sources/minify/src/JS.php, Line 118

### Steps to reproduce
1. Install SMF 2.1.3 on PHP 8.2
2. Enable option "Minimize CSS and JavaScript files"
3. Use the forum for a while

### Possible solution
The error no longer appeared after I downloaded the latest version of [Minify](https://github.com/matthiasmullie/minify) and [Path converter](https://github.com/matthiasmullie/path-converter)

**Comment by jeffythedragonslayer** [comment]
https://github.com/SimpleMachines/SMF/blob/release-2.1/Sources/minify/src/JS.php#L118

**Comment by Sesquipedalian** [comment]
It would be great if you could submit a PR to update those libraries to the latest version, @dragomano.
