### ISSUE TITLE
integrate_error_types function call not working

### ISSUE THREAD

**Issue by Randem06** [SimpleMachines/SMF#7755]
#### Description
I have attempted to use this integrated function to no avail until I changed the line in Errors.php in the function log_error

$known_error_types += $other_error_types;
to
$known_error_types = array_merge($known_error_types, $other_error_types);

### Steps to reproduce
1.  Call the hook integrate_error_types in Errors.php
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by Sesquipedalian** [comment]
Yup. Because both arrays use numeric keys, the `+=` operator causes the values in the second array to overwrite some of the values in the first, rather than appending the second array's values to the first. Using `array_merge()` as suggested will produce the expected results.
