### ISSUE TITLE
Export PMs/Profile data error.

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7763]
#### Description
These are being logged in the PHP error log

PHP Fatal error:  Uncaught ValueError: array_combine(): Argument #1 ($keys) and argument #2 ($values) must have the same number of elements in /Sources/News.php:2649
Stack trace:
#0 /Sources/News.php(2649): array_combine(Array, Array)
#1 /Sources/tasks/ExportProfileData.php(242): getXmlPMs('smf', true)
#2 /Sources/tasks/ExportProfileData.php(552): ExportProfileData_Background->exportXml(Array)
#3 /Sources/tasks/ExportProfileData.php(120): ExportProfileData_Background->exportXmlXslt(Array)
#4 /cron.php(249): ExportProfileData_Background->execute()
#5 /cron.php(131): perform_task(Array)
#6 {main}
  thrown in /Sources/News.php on line 2649

### Steps to reproduce
1. Unknown, being logged in the error logs.
2. 

### Environment (complete as necessary)
- Version/Git revision: 2.1.4
- Database Type: 
- Database Version:
- PHP Version:

### Additional information/references
These are being logged on SimpleMachines website.  No more information is available

**Comment by Sesquipedalian** [comment]
I'll take a look.

EDIT: Oh man, I remember this gnarly query. This is might get ugly before it gets better.

**Comment by Sesquipedalian** [comment]
It seems that there is a way to end up with a mismatch between the number of recipient IDs and the number of recipient names in the query that gets all the PM data in getXmlPMs().

I haven't started working on a fix yet, but I suspect that we'll have to break up that query into two separate ones.

**Comment by jdarwood007** [comment]
Is the mismatch due to a deleted account?  That would at least make sense why you have more ids than names.

**Comment by Sesquipedalian** [comment]
That's my suspicion, yes, but there could be other ways to get into this inconsistent state. I haven't had a chance to dig into it further, so I can't say at this point.

**Comment by Sesquipedalian** [comment]
I have not been able to reproduce the error yet. I've tried sending PMs to accounts, then deleting those accounts, and then exporting profile data with PMs included, but that doesn't produce the error. It doesn't matter if there was a single recipient or multiple recipients, any number of which were subsequently deleted. All that ever happens is that the deleted recipients are left out of the recipients list, and if there are no existing recipients, then the PM itself is left out of the export.

At this point, I am back to square one. 😕

**Comment by Sesquipedalian** [comment]
I figured it out. 

It seems that we allow commas in member names, but the query in question concatenates member names using a comma. I checked on simplemachines.org, and there are some registered members that do in fact have commas in their names.

At any rate, I should have a fix submitted soon.
