### ISSUE TITLE
Language switcher loses post preview and attachments; error with new attachment UI

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#7764]
#### Description
Not really surprising and not really a common use case, but:
1. When switching language in 2.1.4 (or 2.1.3) via the top-right dropdown while watching a post preview, the draft is lost
2. When switching language in 2.1.3 via the top-right dropdown while watching a post preview with an attachment, the (uploaded, but not yet posted) attachment is also lost
3. When switching language in 2.1.4 via the top-right dropdown while watching a post preview with an attachment, I get the following error page:
```
{"files":false,"generalErrors":false}
```
You have to manually adjust the URL to use the forum again (for example going back to `/`), so like with point 2, your uploaded, but not yet posted attachment is discarded in the process.

The URL in the 2.1.4 case of point 3 is `https://[myforum]/index.php?action=uploadAttach;sa=add;[hex-id];board=1`

### Environment (complete as necessary)
- Version/Git revision: 2.1.4
- Database Type: postgres/any
- Database Version: probably any
- PHP Version: probably any

**Comment by jdarwood007** [comment]
I noticed this as well, its because of the attachments is being tracked in $_SESSION['old_url'])
Adding `uploadAttach` to `$no_stat_actions` on index.php should resolve this.
