### ISSUE TITLE
2.1.4 template editor, breaks files

### ISSUE THREAD

**Issue by LexArma** [SimpleMachines/SMF#7769]
Built in template editor creates 0byte files. 

Reported here by NorfolkGreg https://www.simplemachines.org/community/index.php?topic=586142.0
Apparently confirmed by Sir Osis of Liver
I have not tried this myself yet. 

### Steps to reproduce
1. Edit Index.template.php through the admin panel editor
2. Observe the file on the server, 2 users have reported the file to end up empty taking up 0bytes

**Comment by sbulen** [comment]
In my opinion, the proper solution is to remove the template editor entirely...

**Comment by Sesquipedalian** [comment]
> In my opinion, the proper solution is to remove the template editor entirely...

Yeah, it has always seemed like an odd feature to me. If someone is editing templates, they need some level of technical knowledge, and anyone who has such knowledge will almost certainly want to work on the files directly.

Conversely, I think the feature that lets admins edit language strings in the UI makes excellent sense and should be promoted more. Lots of admins want to adjust language strings, and all they need to know is how to speak the language in question. Having a UI that lets them do that without touching the files themselves is exactly what they need. ... But I digress.

**Comment by sbulen** [comment]
The problem with editing the language strings is that you lose those updates when you refresh the languages....   Which is often needed, as strings are often added in patches.  In theory, we should all be refreshing our languages regularly....  It's safest to leave 'em alone.  

Note SMF has an open CVE that considers the ability to edit templates, etc., a huge risk...  Long, recent, internal discussion on that one...

**Comment by Sesquipedalian** [comment]
I haven't been able to reproduce this problem. I made the same edits described in the original report, and the changes were saved without issue.

**Comment by sbulen** [comment]
For the record, neither can I.

**Comment by jdarwood007** [comment]
The fix in #7773 should do it.  Typically the 0 kb file has been because of a race condition where the file is in use and we want to write to it.  The crash occurs resulting in nothing being wrote to the file because of it being blank.

**Comment by LexArma** [comment]
While we are on it, package manager creates backup files when editing, would it be a terribly bad idea to have something similar (and perhaps even a one click roll back) with all file editing options? Just mentioning this as food for thought.
