### ISSUE TITLE
Can't create NEW post

### ISSUE THREAD

**Issue by KrillinsWorld** [SimpleMachines/SMF#7780]
#### Description
I am getting a database error when trying to create a new post in our forums. With these newer version, it is getting really troublesome navigating these pages. You guys forgot to keep it SIMPLE in SMF!

The error message box reads,

DATABASE ERROR:

Field 'edit_reason' doesn't have a default value
File: /home/dh_5chm9u/krillinsworld.com/forum/Sources/Subs-Post.php
Line: 1897

### Steps to reproduce
1. Create a new post.
2. Spend 15 - 20 minutes creating the post.
3. Click [POST]
4. Why would a NEW post need a "REASON TO EDIT?"

### Environment (complete as necessary)
- SMF Version: 2.1.4
- Database Type: MariaDB
- Database Version: (Unknown)
- PHP Version: 8

### Additional information/references
(NONE)

**Comment by albertlast** [comment]
when you look at your error message: "Field 'edit_reason' doesn't have a default value"
than you should notice this field doesn't exists in smf, see here: https://github.com/SimpleMachines/SMF/blob/release-2.1/other/install_2-1_mysql.sql
so you added an addon or modified by hand.

So you forgot to keep your setup SIMPLE in your ENV.

**Comment by LexArma** [comment]
That is true, but this is also an easy thing to fix. The error does not say a new post needs a reason to edit, it just says the post includes a field for the reason to edit, which can't be empty because it has no default value defined in the database. Solution, give it a default value of NULL, so that the default IS empty.

**Comment by Sesquipedalian** [comment]
As explained above, this is not a bug in SMF but rather a problem with a modification you made or installed

For assistance with your problem, please post in the support forums at simplemachines.org.

**Comment by KrillinsWorld** [comment]
Sorry, we have been using SMF since 2004 or 2005. Blaming a mod which has nothing to do with "Creating A New Post" is a rather weak defense. Any mods we may have used are mainly cosmetic (themes) or just requesting more information in the user registration process. Nothing more. We have not used or installed any mods in more than a decade! But I do agree with LexArma's comment about giving the VALUE of "reason for edit" a value of "NULL." should have been implemented when this was rolled out.

As for my comment regarding the new lay out, I am not sorry I said something. After using SMF for more than 15 years, this sudden change and burring options within option within options is very frustrating for us when we are in a hurry. As we do need to focus our time with in other areas. As it seems lately we spend far too much time reporting problems.

As for my environment. This is out of my realm of control. All we do is apply updates as needed. But this is in the hands of our hosting company. There was a time where one of my hosting companies we could not even host SMF on their servers, so we hosted them ourselves. SMF was such a PIA to us due to people registering with fake accounts and posting adult material in the forms. But this was solved with the user-self-activation process, then this problem went by the wayside. But registration is and has been closed at our forums due to other reasons.

So remember, when you point the finger at another, you have three more pointing back at you. But we are waiting for a solution to this problem as it has been sort of "verbalized" but yet nothing has been presented for a fix. I am not digging through this code to find the query just to add a "NULL" in the prepared statement. Two weeks and there is nothing here but ridicule?

-Krillin

**Comment by tinoest** [comment]
> Sorry, we have been using SMF since 2004 or 2005. Blaming a mod which has nothing to do with "Creating A New Post" is a rather weak defense. Any mods we may have used are mainly cosmetic (themes) or just requesting more information in the user registration process. Nothing more. We have not used or installed any mods in more than a decade! But I do agree with LexArma's comment about giving the VALUE of "reason for edit" a value of "NULL." should have been implemented when this was rolled out.
> 
> As for my comment regarding the new lay out, I am not sorry I said something. After using SMF for more than 15 years, this sudden change and burring options within option within options is very frustrating for us when we are in a hurry. As we do need to focus our time with in other areas. As it seems lately we spend far too much time reporting problems.
> 
> As for my environment. This is out of my realm of control. All we do is apply updates as needed. But this is in the hands of our hosting company. There was a time where one of my hosting companies we could not even host SMF on their servers, so we hosted them ourselves. SMF was such a PIA to us due to people registering with fake accounts and posting adult material in the forms. But this was solved with the user-self-activation process, then this problem went by the wayside. But registration is and has been closed at our forums due to other reasons.
> 
> So remember, when you point the finger at another, you have three more pointing back at you. But we are waiting for a solution to this problem as it has been sort of "verbalized" but yet nothing has been presented for a fix. I am not digging through this code to find the query just to add a "NULL" in the prepared statement. Two weeks and there is nothing here but ridicule?
> 
> -Krillin

I think you missed the point. This is not a bug with the SMF core code. Therefore there is nothing to change in SMF itself.

You can either remove the column from your DB, which if you still have the mod which created it installed will break your forum, or you can edit the column to have a default of NULL.

I don’t know what mod you used but it’s the mod author at fault here not SMF.

**Comment by live627** [comment]
Y'all pointing fingers so much that you end up as pretzels xD

**Comment by Sesquipedalian** [comment]
> Sorry, we have been using SMF since 2004 or 2005. [...]
> -Krillin

This is not the place to ask for support. For assistance with your problem, please post in the support forums at simplemachines.org.

**Comment by LexArma** [comment]
> Any mods we may have used are mainly cosmetic (themes) or just requesting more information in the user registration process. Nothing more. We have not used or installed any mods in more than a decade! But I do agree with LexArma's comment about giving the VALUE of "reason for edit" a value of "NULL." should have been implemented when this was rolled out.

I do believe you misunderstood me. This is caused by a mod, and what I meant was that this is easy for you to fix yourself. I even told you what to do.

**Comment by KrillinsWorld** [comment]
I have changed the value to enable null. I do apologize as I thought "reason for editing" was a default feature within SMF. Thank you for your assistance in this matter.

-Krillin

**Comment by LexArma** [comment]
All good, there is actually a "reason for editing" option built in to 2.1, but it's a little different and should not cause the issue you saw.
