### ISSUE TITLE
Mobile View overflow issue.

### ISSUE THREAD

**Issue by TwitchisMental** [SimpleMachines/SMF#7783]
#### Description
See here - https://www.simplemachines.org/community/index.php?topic=586347
Basically when viewing SMF on a mobile screen like an iPhone there is an extra space to the right.
Can be replicated on the simplemachines.org aswell.

### Steps to reproduce
1.  View a clean install of SMF from a mobile device or with the screen resolution of 375 x 812.
2.  You will see black space to the right. If on desktop you will see a horizontal scroll bar pop up and be able to scroll right to see a blank space.

### Environment (complete as necessary)
- Version/Git revision:
- Database Type: MariaDB
- Database Version: 10.4.28
- PHP Version: 8.0.28

### Additional information/references

The issue seems to be resolved by adding an overflow: hidden.

Responsive.css line 180.
```

@media screen and (max-width: 720px)
#top_section .inner_wrap, #wrapper, #header, #footer .inner_wrap {
  width: 100%;
}
```

change to

```
@media screen and (max-width: 720px)
#top_section .inner_wrap, #wrapper, #header, #footer .inner_wrap {
  width: 100%;
  overflow: hidden;
}
```

**Comment by sbulen** [comment]
I'm fairly sure this isn't an SMF issue.  It's caused by the ad mod on the smorg site.

**Comment by Sesquipedalian** [comment]
> I'm fairly sure this isn't an SMF issue.  It's caused by the ad mod on the smorg site.

This is correct.

**Comment by TwitchisMental** [comment]
Woopsies should've doubled checked locally. My bad.
