### ISSUE TITLE
Upgrader: Old protected_alter logic is producing deprecation warnings

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7799]
#### Description

The upgrader is producing deprecation warnings when upgrading from SMF 2.0.x or prior.  This logic is coming from the protected_alter function in upgrade.php:
https://github.com/SimpleMachines/SMF/blob/4d7fbd840b244b1940b41e1023e366d2b7ad4dbc/other/upgrade.php#L2597

The errors look like:
> *  +++  Renaming table columns.Error: strpos(): Passing null to parameter # 1 ($haystack) of type string is deprecated File: D:\wamp64\www\yabbse\upgrade.php Line: 2597.Error: strpos(): Passing null to parameter # 1 ($haystack) of type string is deprecated File: D:\wamp64\www\yabbse\upgrade.php Line: 2597

I haven't looked too closely yet...  It appears to think $row['Info'] is null, which doesn't make sense to me...

But the bigger question is:  **_Do we even need the protected alter function???_**

I am not quite sure what that old function is there to do...

### Steps to reproduce
1.  Perform an upgrade using PHP 8.1 or PHP 8.2
2. Run the upgrade from the command line - so errors are preserved/displayed
3. Run an upgrade from 2.0 or prior

### Environment (complete as necessary)
- Version/Git revision:  Current
- Database Type: MySQL
- Database Version: 8.0
- PHP Version: 8.2 (confirmed in 8.1 also)
- WAMP - haven't tried linux yet...

**Comment by jdarwood007** [comment]
Looks like the function is designed to look for if the alter command is currently processing.  Such as we add a column to the messages table, this may take a while (longer than timeout), then a timeout occurs, the script then runs again and we reach here telling it to not execute the command a second time.  So it checks the process list to see if it can find the command running.  If it can, it doesn't try to send it again.

mysql> SHOW FULL PROCESSLIST;
| Id      | User            | Host      | db   | Command | Time    | State                  | Info                  |
 | --------- | ----------------- | ----------- | ------ | --------- | --------- | ------------------------ | ----------------------- | 
|       5 | event_scheduler | localhost | NULL | Daemon  | 1614649 | Waiting on empty queue | NULL                  |
| 1599695 | jeremy          | localhost | NULL | Query   |       0 | init                   | SHOW FULL PROCESSLIST |

2 rows in set (0.00 sec)

Seems that Info can be null.  Best solution is to exclude it or ensure that we filter it by checking for Command <> 'Daemon' and User <> 'event_scheduler'

**Comment by sbulen** [comment]
Thanks, helpful.  Sounds like a fix is easy.

**Comment by sbulen** [comment]
This can be closed
