### ISSUE TITLE
Calendar - events dropped when there are multiple overlapping events

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7803]
#### Description
Odd one from the forum...  But it can be verified.  If you have multiple overlapping events, then the various date range views seem to inexplicably drop some of the events.  

Any event on its own is displayed perfectly, no matter what the view.  But as soon as there are multiple, some may get dropped.

### Steps to reproduce
0. Forum & user timezone to EDT
1. Add an all-day event, for 3 days, from Aug 3 - Aug 5
2. Add an all-day event, on Aug 5.
3. Choose list view, Aug 3 - Aug 10, both events show properly for Aug 5
4. Choose list view, Aug 5 - Aug 12, only the 3 day event is shown.  The Aug 5 event is dropped from the list...

There are similar variations in month view, week view, etc.  

### Environment (complete as necessary)
- Version/Git revision: 2.1.4
- Database Type: mysql
- Database Version: 8.0
- PHP Version: 8.2

### Additional information/references
From the forum:  https://www.simplemachines.org/community/index.php?topic=586490.0

**Comment by indyrcpilot** [comment]
Is there any kind of workaround for this issue?

Thanks... 
Chuck

**Comment by Sesquipedalian** [comment]
Not yet. Someone has to take the time to figure out the cause and how to fix it. So far, @sbulen has figured out enough to be able to describe how we can consistently reproduce the problem. Next we have to figure out *why* it happens. Then we can figure out how to solve it.

As our investigation proceeds, you will see activity about it posted here.

**Comment by indyrcpilot** [comment]
Thanks for the response.
Could I revert back to a previous version until this is resolved, or would that cause other issues?
Thanks...
Chuck

**Comment by Sesquipedalian** [comment]
I believe all versions of 2.1 are affected, and downgrading to 2.0 is not possible.

**Comment by indyrcpilot** [comment]
Ok, thanks for letting me know.

**Comment by Sesquipedalian** [comment]
@indyrcpilot, please test the changes in #7820 and let us know if they solve the issue for you. 

Since only one line of code is changed, you can just change that line manually in your installed copy of the Subs-Calendar.php file to test it.

**Comment by indyrcpilot** [comment]
It looks like that solved the problem I was seeing with an event not showing up on the calendar properly.

Thank you! 😊

Chuck

**Comment by Sesquipedalian** [comment]
Excellent
