### ISSUE TITLE
Posts ending in [@ cause "Uninitialized string offset" errors

### ISSUE THREAD

**Issue by Daaaav** [SimpleMachines/SMF#7818]
#### Description
If a post **ends with the characters `[@`** (opening square bracket followed by an @ sign), you'll get the error "Uninitialized string offset 6" (different number depending on the length of the post), in Sources/Subs.php (Line 3485).

```php
		if ($smileys !== false && $tag === null && isset($itemcodes[$message[$pos + 1]]) && $message[$pos + 2] == ']' && !isset($disabled['list']) && !isset($disabled['li']))
```

### Steps to reproduce
1. Post or preview a post such as `asdf[@`
2. Observe the error log

### Environment (complete as necessary)
- Version/Git revision: 2.1.4
- Database Type: any?
- Database Version: any?
- PHP Version: 8.1.20 and 8.2.6

### Additional information/references
https://www.simplemachines.org/community/index.php?topic=586582.0 (note that the OP might have something else specifically causing the error for them)

**Comment by jdarwood007** [comment]
Its actually `[@` that causes it.  Any incomplete item code causes it.  `'[*`', `[+`, `[x`, `[#`, `[o`, `[O`, `[0`
