### ISSUE TITLE
Quote selected text does not parse `[member]` BBC

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#7837]
The fix is to change  the output in parse_bbc

from

```
<a class="mention" href="https://www.simplemachines.org/community/index.php?action=profile;u=154736">@live627</a>
```

to

```
<a data-mention="154736" data-type="mention" class="mention" href="https://www.simplemachines.org/community/index.php?action=profile;u=154736">@live627</a>
```

**Comment by jdarwood007** [comment]
This was broken in 2.1.3.  It was mentioned in the beta topic (msg 4138946) and I mentioned that fix.

SCeditor needs changed to do
```
			return '<a href="' + smf_scripturl +'?action=profile;u='+ attrs.defaultattr + '" class="mention" data-type="mention" data-mention="'+ attrs.defaultattr + '">@'+ content.replace('@','') +'</a>';
```

The bug was introduced in #7463

**Comment by live627** [comment]
-- https://github.com/SimpleMachines/SMF/pull/7614

From https://www.simplemachines.org/community/index.php?topic=584161.0

---

I believe this is a different, unreported, issue.

**Comment by live627** [comment]
- #7614

From https://www.simplemachines.org/community/index.php?topic=584161.0

---

I believe this is a different, unreported, issue.
