### ISSUE TITLE
3.0 autoloader calls integrate_autoload hook needlessly

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#7850]
SMF 3.0's autoloader calls the integrate_autoload hook every time. It should only need to do that once.

This behaviour could cause a performance hit.

**Comment by live627** [comment]
Inherited from 2.1—you can see the duplicate hook calls in the debug info
when using object oriented mods

**Comment by Sesquipedalian** [comment]
> Inherited from 2.1

So it is. That weighs against the idea that the hook calls are responsible for any performance degradation compared to 2.1. Nevertheless, avoiding unnecessary hook calls is still a good idea.
