### ISSUE TITLE
Sources/Config::checkCron()

### ISSUE THREAD

**Issue by tyrsson** [SimpleMachines/SMF#7858]
#### Description
If this is a non issue please feel free to close this.

in reference:
https://github.com/SimpleMachines/SMF/blob/76dfb27b28bc580faf3078388a9843141150a782/Sources/Config.php#L3140

lines 3131 and 3140 use 84600 instead of 86400

line 3140
```
'yesterday' => time() - 84600,
```
leaves you 1800 seconds in today does it not? Not sure if this is by design or a typo.

### Steps to reproduce
No reproduction needed, check source.

### Environment (complete as necessary)
- version 3.0 Alpha-1:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by Sesquipedalian** [comment]
Typo. Please feel free to submit a PR to correct it.

**Comment by tyrsson** [comment]
Will do soon as I get home this evening.
