### ISSUE TITLE
mhash deprecated in php 8.1

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7860]
#### Description

We only keep it around for legacy logon checks...  But even that may need to go.

https://www.simplemachines.org/community/index.php?topic=587369.0

**Comment by jdarwood007** [comment]
We do a function exists check.

Moreover, the logic doesn't currently work right:
```
		// None of the below cases will be used most of the time (because the salt is normally set.)
		if (!empty($modSettings['enable_password_conversion']) && $user_settings['password_salt'] == '')
[...]
		// If the salt is set let's try some other options
		elseif (!empty($modSettings['enable_password_conversion']) && $user_settings['password_salt'] != '')
[...]
		// The hash should be 40 if it's SHA-1, so we're safe with more here too.
		elseif (!empty($modSettings['enable_password_conversion']) && strlen($user_settings['passwd']) == 32)
[...]
```

There is no way for that last elseif to every be executed because the first two would always be satisfied.

**Comment by sbulen** [comment]
Given it's deprecated, I think even the conditional reference should go.
https://php.watch/versions/8.1/ext-hash-mhash-deprecated

**Comment by Oldiesmann** [comment]
We could just use hash() instead...  https://www.php.net/function.hash

**Comment by jdarwood007** [comment]
I have something in the works. I fixed the issue I mentioned and switched to a switch style based on character length.  Should optimize it a bit as well because of that.

**Comment by Sesquipedalian** [comment]
Just need to make this substitution:

Find:
```
			if (strlen(User::$profiles[User::$my_id]['passwd']) == 64 && function_exists('mhash') && defined('MHASH_SHA256'))
				$other_passwords[] = bin2hex(mhash(MHASH_SHA256, $_POST['passwrd']));
```

Replace:
```
			if (strlen(User::$profiles[User::$my_id]['passwd']) == 64)
				$other_passwords[] = hash('sha256', $_POST['passwrd']);
```
