### ISSUE TITLE
Poll::getMostRecent() results in database error

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#7868]
#### Description
Attempting to call ServerSideIncludes::recentPoll() if the query doesn't return any results.

### Steps to reproduce
Browse to ssi_examples.php and look at the "Recent Poll" section

Fatal error: Uncaught TypeError: mysqli_fetch_row(): Argument #1 ($result) must be of type mysqli_result, string given in C:\wamp64\www\smf3\Sources\Db\APIs\MySQL.php on line 275
TypeError: mysqli_fetch_row(): Argument #1 ($result) must be of type mysqli_result, string given in C:\wamp64\www\smf3\Sources\Db\APIs\MySQL.php on line 275

Picture of the errors with backtrace:
![image](https://github.com/SimpleMachines/SMF/assets/89023/e99efce8-6ab3-4294-ab11-acb3c36bdb1b)

### Environment (complete as necessary)
- Version/Git revision: 3.0 Alpha 1 (latest git version)
- Database Type: MariaDB
- Database Version: 11.1.2
- PHP Version: 8.2.12

### Additional information/references

**Comment by Oldiesmann** [comment]
Update on this: I added a poll and am still getting the same error when viewing the Recent Poll thing in SSI. Going to do some more digging and see if I can figure out what's going on.

**Comment by Oldiesmann** [comment]
After further debugging, I finally figured out the problem. The query is generating this warning:
`Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause`

Since the mysqli_query returns false instead of an object, and we're not skipping errors, SMF returns the error message, resulting in us passing a string to db_fetch_row.

The simplest solution to this would be to simply throw a `GROUP BY p.id_poll` at the end of that query, but there might be a better way to rewrite it.

**Comment by albertlast** [comment]
you got two issues in one,
sql is wrong (from mysql pov)
and programm code which handle the sql error wrong.

**Comment by Oldiesmann** [comment]
Yes, the entirety of database error handling is messed up. However, adding GROUP BY p.id_poll in the query before the ORDER BY at least makes this error go away (unless there's a better way to write that query, but it's a bit confusing due to all of the checks done to ensure it's something you can see and isn't a locked poll)
