### ISSUE TITLE
BBC Button Status

### ISSUE THREAD

**Issue by mcblaber** [SimpleMachines/SMF#787]
I'm going to go ahead here and reference my old mantis report - http://dev.simplemachines.org/mantis/view.php?id=3936

It was mentioned that SCEditor 1.4.1 included the functionality to show the BBC icon state in real time. So now that we have updated the editor to 1.4.4 (#599) could we expect to see this functionality in the future? I'm assuming the functionality exists with the new editor version so it shouldn't too much work to fit this into 2.1. 

Signed-off-by: Colin shadow82x@simplemachines.org

**Comment by emanuele45** [comment]
It's enough to add something in the css attached to:

```
.sceditor-button.active
```

(Don't know exactly what).

**Comment by Arantor** [comment]
Since that one was merged, I believe this one can now be closed.
