### ISSUE TITLE
Visual layout in articles and social networks

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#7871]
Hello..
1- When we add a text, we want to support it with images. It would be great if we could add images to the centre, right side, left side, etc. by sizing.
2 - Can the title be flexible so that the top image can be placed on the left, centre and right side?
3 - Text colours can be black
4 - Adding icons of social networks. X(twitter), Mastodon , Pixelfed , vs.

**Comment by Sesquipedalian** [comment]
1. Take a look at the [float] BBCode.
2. Topic titles are plain text. There are no plans to change that.
3. The text in your posts can be any colour you choose, unless the forum admin has disabled the option to choose custom text colours.
4. There are modifications that you can install for that.

**Comment by ghost** [comment]
I meant the area where the site name is located

**Comment by jdarwood007** [comment]
We provide support at our community forums: https://www.simplemachines.org/community/index.php
