### ISSUE TITLE
Calendar Events not showing on board index.

### ISSUE THREAD

**Issue by TwitchisMental** [SimpleMachines/SMF#7873]
#### Description
When enabling the Calendar, any events, holidays, etc do not show on the board index. 

### Steps to reproduce
1.  Enable the Calendar
2.  Choose the "show on board index and calendar" option for holidays, birthdays, events.
3.   Save and look at the board index.

### Environment (complete as necessary)
- SMF Version: 3.0 Alpha 1
- Database Type: MariaDB
- Database Version: 10.4.28
- PHP Version:   8.1.17

### Additional information/references

**Comment by Sesquipedalian** [comment]
I cannot reproduce this. They show up for me.

**Comment by TwitchisMental** [comment]
> I cannot reproduce this. They show up for me.

Okay made sure that I had the latest version and changed the "Max days in advance on board index" setting to a bit further out, I now see the calendar in info center.  This can be closed. PEBKEC error lol.
