### ISSUE TITLE
Theme Variant Selection Gets Fatal Error

### ISSUE THREAD

**Issue by TwitchisMental** [SimpleMachines/SMF#7874]
#### Description
If you add a variant to a theme and go to select that variant you get an error.
Fatal error: Uncaught Error: Class "Theme" not found

### Steps to reproduce
1.  Add the theme variants setting to your theme.
  `Theme::$current->settings['theme_variants'] = array('light', 'dark');`
2.  Go to UCP > Forum Profile > Look and Layout > Change Theme.
3. You will get the error.

### Environment (complete as necessary)
- SMF Version: 3.0 Alpha 1
- Database Type: MariaDB 
- Database Version:  10.4.28
- PHP Version: 8.1.17

### Additional information/references

**Comment by Sesquipedalian** [comment]
Does your theme file have the following statement near the top?

```
use SMF\Theme;
```

If not, you can either add that statement, or else you can change your inline code to `SMF\Theme::$current->settings['theme_variants'] = array('light', 'dark');`.

**Comment by TwitchisMental** [comment]
Okay yes it does have use SMF\Theme; on line 16.

Changing the variant setting to "SMF\Theme::$current->settings['theme_variants'] = array('light', 'dark');"  does make it work.

Edit: If I remove the SMF\Theme part though it still errors out.

**Comment by Sesquipedalian** [comment]
Do you have other occurrences of `Theme::$current->settings['foo']` (without the namespace) in your theme's `init()` function? If so, do they work?

**Comment by TwitchisMental** [comment]
Yes I have the avatars on board index enabled. `Theme::$current->settings['avatars_on_boardIndex'] = true;`

That works as it should.

**Comment by Sesquipedalian** [comment]
Hm. Then something odd is happening. If `Theme::$current->settings['avatars_on_boardIndex'] = true;` works as expected, then `Theme::$current->settings['theme_variants'] = array('light', 'dark');` should work, too. It's even more confusing to hear that `SMF\Theme::$current->settings['theme_variants'] = array('light', 'dark');` does work in the same file. 

Could you share a copy of the theme file? It would help if I could see exactly what you have.

**Comment by TwitchisMental** [comment]
[SMF3.zip](https://github.com/SimpleMachines/SMF/files/13329072/SMF3.zip)

There you go.

**Comment by Sesquipedalian** [comment]
Thanks. Found the problem. I'll submit a PR shortly.

**Comment by TwitchisMental** [comment]
You're welcome, happy to help :).

**Comment by Sesquipedalian** [comment]
Please give #7876 a try.

**Comment by TwitchisMental** [comment]
That fixes it :) .

**Comment by Sesquipedalian** [comment]
Excellent
