### ISSUE TITLE
Admin Search error

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7878]
#### Description
Trying to search in ACP causes a fatal error

( ! ) Fatal error: Uncaught Error: Class "SMF\Cache\APIs\Utils" not found in /Sources/Cache/APIs/MemcacheImplementation.php on line 182
--

### Steps to reproduce
1. Go to ACP
2. Search for anything

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references
I have a dirty env, so  hopefully not related to my own work, but I don't recall messing with this file.  Will verify when I can get a cleaned env.

**Comment by Sesquipedalian** [comment]
Sounds like the file is missing a `use SMF\Utils;` statement.
