### ISSUE TITLE
New post notification fails in SMF 3

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#7889]
#### Description
Noticed this error in the log for my test board. This was generated when I replied to the welcome topic earlier.

```
	AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Class "SMF\\Tasks\\BackgroundTask" not found in /.../Sources/tasks/CreatePost_Notify.php:36
Stack trace:
#0 /.../Sources/TaskRunner.php(555): require_once()
#1 /.../Sources/TaskRunner.php(208): SMF\\TaskRunner->performTask()
#2 /.../cron.php(29): SMF\\TaskRunner->execute()
#3 {main}
 thrown in /.../Sources/tasks/CreatePost_Notify.php on line 36', referer: https://smf3.oldiesmann.us/index.php?PHPSESSID=jtag0moqjee600jndqj9v2bfn4&topic=1.msg2;topicseen
``` 

### Steps to reproduce
1. Create a new post
2. 

### Environment (complete as necessary)
- Version/Git revision: Latest SMF 3 from Gitub
- Database Type: MariaDB
- Database Version: 10.6.12
- PHP Version: 8.1.2

### Additional information/references

**Comment by Sesquipedalian** [comment]
I can't reproduce this. Are you still seeing it, @Oldiesmann?

**Comment by Oldiesmann** [comment]
Not getting it now. Something else might have fixed it in the mean time. Visual Studio Code doesn't show any problems there either.

**Comment by Oldiesmann** [comment]
Got it again while trying to send a PM to my regular user account.
```
    AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Class "SMF\\Tasks\\BackgroundTask" not found in /.../Sources/tasks/CreatePost_Notify.php:35\nStack trace:
#0 /.../Sources/TaskRunner.php(553): require_once()
#1 /.../Sources/TaskRunner.php(209): SMF\\TaskRunner->performTask()
#2 /.../cron.php(30): SMF\\TaskRunner->execute()
#3 {main}
 thrown in /.../Sources/tasks/CreatePost_Notify.php on line 35', referer: https://smf3.oldiesmann.us/index.php?action=pm;sa=send
```

**Comment by Sesquipedalian** [comment]
Have you been flipping back and forth between 2.1 and 3.0 on that server?

**Comment by Oldiesmann** [comment]
No. This board was only 2.1 long enough for - me to install it. After that I deleted most of the files and replaced them with 3.0 files and edited the version in the settings table in the database. I do have 2.1 forums on this server as well but they're all separate from one another.

**Comment by Sesquipedalian** [comment]
This might be a silly question, but Sources/tasks/BackgroundTask.php does exist, right?

**Comment by Oldiesmann** [comment]
Yes, it's definitely there.
![image](https://github.com/SimpleMachines/SMF/assets/89023/cec81858-57b4-4e48-8678-5e6030d6a4e9)

**Comment by Sesquipedalian** [comment]
Can you show me the database row for that task in the background_tasks table?

**Comment by Oldiesmann** [comment]
There are three of them.
![image](https://github.com/SimpleMachines/SMF/assets/89023/5eb0e566-8cb9-41d7-83c8-f9997baa683c)

**Comment by Sesquipedalian** [comment]
Hm... Is your server's file system case sensitive?

**Comment by Oldiesmann** [comment]
This is on a Linux server so yes

**Comment by jdarwood007** [comment]
@Oldiesmann I think your meant to test #7917 as it should fix it.

**Comment by Oldiesmann** [comment]
I'll take a look when I get a chance.
