### ISSUE TITLE
3.1

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#7895]
#### Description
Cannot find database source script! Please check file Db/APIs/mysql.php is within your forum source directory.
It's installed the same as I've always done my upgrades.

### Steps to reproduce
1.  Fresh Install
2.  Try to Install

### Environment (complete as necessary)
- Version/Git revision: [d7f5e0d](https://github.com/SimpleMachines/SMF/commit/d7f5e0db6ada87be2713b41088709edd99335a1e)
- Database Type: MySQL 8.0
- Database Version: MySQL 8.0
- PHP Version: 8.2

### Additional information/references

**Comment by jdarwood007** [comment]
Duplicate of #7849

**Comment by ghost** [comment]
still does'nt work

**Comment by Sesquipedalian** [comment]
We didn't close this report because the problem is fixed. We closed it because it is a duplicate of another issue report, and we don't need multiple reports for the same issue.

**Comment by ghost** [comment]
okay
