### ISSUE TITLE
Adding a category doesn't work in SMF 3

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#7908]
#### Description
I have no idea what's going on with this one, but when you try to add a new category in SMF 3, it just doesn't work. No errors, no unusual pages. The category just doesn't get created at all. It also doesn't seem to matter whether caching is enabled or not.

### Steps to reproduce
1. Go to Admin -> Forum -> Boards and Categories -> Create New Category
2. Fill in relevant details and click the button to create the category.

You'll get redirected to the list of boards and categories like usual but the new one is nowhere to be seen.

### Environment (complete as necessary)
- Version/Git revision: Latest
- Database Type: MariaDB
- Database Version: 10.6.12
- PHP Version: 8.2.13

### Additional information/references

**Comment by Sesquipedalian** [comment]
I can confirm. I have no idea why it is happening yet, though.

**Comment by Sesquipedalian** [comment]
In my tests, the new category is created in the database, but it doesn't show up in the UI. I will continue investigating.

**Comment by jdarwood007** [comment]
Look at line 694 in Category.php.  The query is based on boards table.  So a category with no boards is missed.  The logic needs reworked to pull both categories and boards (2 queries) or rework the logic that the boards is the left join and if we get no board data, skip it on the foreach loop.
