### ISSUE TITLE
Type hinting needed in DatabaseApi classes

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#7916]
Neither SMF\Db\DatabaseApiInterface, nor any of the classes that implement it, use typed parameters and return values. They really should. Implementing them will probably expose a number of obscured bugs, but that's a good thing.

**Comment by jdarwood007** [comment]
In addition, we should start adding `declare(strict_types = 1);` to the top of the files that are fully typed.
https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.strict
