### ISSUE TITLE
Trying to run scheduled task now leads to an error in SMF 3

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#7925]
#### Description
Tried to run the "Fetch Simple Machines Files" task on my SMF 3 test board (trying to debug an issue with that) and ended up with a blank screen instead. It appears something is trying to pass a timestamp to call_user_func instead of a function name, but I haven't had a chance to look into this further since it's late here

### Steps to reproduce
1. Go to Admin -> Maintenance -> Scheduled Tasks
2. Check the first box next to a task and click "Run Task Now"

### Environment (complete as necessary)
- Version/Git revision: latest SMF 3 from GitHub
- Database Type: PostgreSQL
- Database Version: 14.9
- PHP Version: 8.3.0

### Additional information/references
```
	AH01071: Got error 'PHP message: PHP Fatal error: Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, function "1701577560" not found or invalid function name in /.../Sources/Tasks/GenericScheduledTask.php:33
Stack trace:
#0 /.../Sources/Tasks/GenericScheduledTask.php(33): call_user_func()
#1 /.../Sources/TaskRunner.php(341): SMF\\Tasks\\GenericScheduledTask->execute()
#2 /.../Sources/Actions/Admin/Tasks.php(176): SMF\\TaskRunner->runScheduledTasks()
#3 [internal function]: SMF\\Actions\\Admin\\Tasks->tasks()
#4 /.../Sources/Actions/Admin/Tasks.php(109): call_user_func()
#5 /.../Sources/Actions/Admin/Tasks.php(562): SMF\\Actions\\Admin\\Tasks->execute()
#6 [internal function]: SMF\\Actions\\Admin\\Tasks::call()
#7  /...', referer: https://smf3pg.oldiesmann.us/index.php?action=admin;area=scheduledtasks;dc473199=d9e0b9c32ce43c309f6c693eed701711
```

**Comment by Oldiesmann** [comment]
Here's the full stack trace from xdebug on my local Windows test board (via wampserver64)
![image](https://github.com/SimpleMachines/SMF/assets/89023/b5cf00cc-4ac6-4d6d-b7b8-334d8b1c5383)

**Comment by Sesquipedalian** [comment]
Confirmed. I wonder when this started...
