### ISSUE TITLE
latest-news.js is butchered in SMF 3

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#7929]
#### Description
Viewing the admin center in SMF 3, you just see the standard "You are unable to connect to simplemachines.org's latest news file." placeholder instead of the latest news.

### Steps to reproduce
1. Go to the admin center
2. Look at where the latest news should be

### Environment (complete as necessary)
- Version/Git revision: latest
- Database Type: MariaDB (also occurs with PostgreSQL)
- Database Version:
- PHP Version: 8.3.0

### Additional information/references
A comparison of the latest-news file in 2.1 and 3 shows that in SMF 3, there's a "2002" and blank line before the window.smfAnnouncements definition and a blank line and a "0" at the end of the code after the window.setInnerHTML call.

Here's what I see in SMF 3:
```
2002

window.smfAnnouncements = [
	{
		subject: 'SMF 2.1.4 has been released',
		href: 'https://www.simplemachines.org/community/index.php?topic=586097.0',
		time: 'Jun 10, 2023, 05:21 PM',
		author: 'shawnb61',
		message: 'SMF 2.1.4 includes security updates and numerous bug fixes. We recommend updating as soon as possible.'
	},
...
}

if (document.getElementById('credits'))
	setInnerHTML(document.getElementById('credits'), getInnerHTML(document.getElementById('credits')).replace(/anyone we may have missed/, '<span title="And you thought you had escaped the credits, hadn\'t you, Zef Hemel?">anyone we may have missed</span>'));

0
```

**Comment by Sesquipedalian** [comment]
I suspect that is a bug in the script on simplemachines.org that generates the file, rather than a bug in SMF.

@jdarwood007

**Comment by jdarwood007** [comment]
Doesn't appear to be a bug in the site code.  Change the http 1.1 request to a 1.0 request and it works. 
This is because of a chunked transfer: https://stackoverflow.com/questions/70958954/apache-adds-data-to-output-of-javascript-file

We could go back to 1.0 (easiest), or workout how to properly handle chunked
https://stackoverflow.com/questions/3289574/how-to-handle-chunked-encoding-request-properly

**Comment by jdarwood007** [comment]
Also FYI, when reading the headers.  Multiple transfer encodings can be sent:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding

Shouldn't be too difficult to implant this.  We have to switch the body to fgets for this, but we then can read out things in chunks and shove it back into the body.
