### ISSUE TITLE
[3.0] Cannot join group from Group Membership section of profile

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#7949]
#### Description
There are two different but related bugs here. If you create a group that someone can request to join (or one that they can join/leave at will), you can't join it from the Group Membership section of the profile, even if you're an admin.

There are two bugs here:
* This code isn't checking whether the person can join/request to join the group before hitting the permission check:
https://github.com/SimpleMachines/SMF/blob/de43b89cc5ac90c7b000e6ae1fc4f29bcb403b42/Sources/Actions/Profile/GroupMembership.php#L175C1-L178C4
```php
        // Let's be extra cautious...
        if (!User::$me->is_owner || empty(Config::$modSettings['show_group_membership'])) {
            User::$me->isAllowedTo('manage_membergroups');
        }
```

* The "is_admin" check in allowedTo() is failing for admins when the above permission check is run (as I said, if I go to my profile as an admin, then go to the Group Membership section and try to join a group, I'm still told I can't modify or manage membergroups.

### Steps to reproduce
1. Create a new group and set its type to either "Requestable" or "Free"
2. Go to the group membership page in your profile (click username -> My Groups) and try to join the newly created group, either as a regular user or as an admin.

### Environment (complete as necessary)
- Version/Git revision: Latest
- Database Type: MariaDB
- Database Version: 11
- PHP Version: 8.3

### Additional information/references

**Comment by jdarwood007** [comment]
I started to look into this.  The first issue is that in Group.php and Profile.php we are doing an array merge, which removes the key association.  But logic in GroupMembership.php assumes this, in many places.  So I started to fix that.  The only way around that this to use the union (+=).  It should be noted that the union causes items to the right to be ignored.

I haven't finished working through it, but that at least has some logic to work, more is still broken.
