### ISSUE TITLE
X on top of HTML all over the website

### ISSUE THREAD

**Issue by Julian367** [SimpleMachines/SMF#7955]
#### Description
--Description Here--
Importing SSI.php outside SMF forum to use auth cause a x all over the website. 
```
x<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><link rel="stylesheet" type="text/css" 
```

### Steps to reproduce
1.  import "forum/SSI.php"
2. 

### Environment (complete as necessary)
- Version/Git revision:  2.0.19
- Database Type: MYSQL
- Database Version: 8
- PHP Version: 8.1

### Additional information/references

**Comment by Sesquipedalian** [comment]
It sounds like you have an "x" character outside of the PHP tags in one of your files somewhere. The most likely cause is a typo while manually editing a file. You'll need to check over your own recently edited files in order to find it.

**Comment by Julian367** [comment]
@Sesquipedalian Thanks for the reply.
Could it also be caused by the theme files?
Update
Found the problem. It was on index.template.php.
