### ISSUE TITLE
[3.0]: Query Datatyp doesn't match error case 

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#7969]
### Basic Information

# Expected behavior:
-------------------
Both db code do on an error case (when return value is false),
collect the error message and return this:
https://github.com/SimpleMachines/SMF/blob/e31624b3a96f62b2b52eeb6bc7631eda3449c0f9/Sources/Db/APIs/MySQL.php#L244-L246
error return a string

query function is defined that it return bool or object,
which result in an db error case also in a datatyp error.

I'm not sure in which direction the problem should be solved,
add datatype? or write the error message somewhere else and return false?
throw an exception?
# Actual behavior:
-------------------
TypeError: SMF\Db\APIs\PostgreSQL::query(): Return value must be of type object|bool, string returned in F:\github\SMF2.1\Sources\Db\APIs\PostgreSQL.php on line 320

### Steps to reproduce

1. create any smf query error (like wrong table name)

![grafik](https://github.com/SimpleMachines/SMF/assets/1782906/520e02d3-6622-43a5-b861-6010187c8dbb)

### Version/Git revision

3.0 Alpha 1

### Database Engine

All

**Comment by jdarwood007** [comment]
I would say we wouldn't be returning an error string here.  It should return false, the code can call for the error message when handling the false.

**Comment by albertlast** [comment]
and where put the error message?

**Comment by jdarwood007** [comment]
Well something like:
```
$result = Db::query('', '...QUERY...');
if ($result === false)
	throw new \Exception(Db::error());
```
