### ISSUE TITLE
[3.0]: Undefined $forum_uuid

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7979]
### Basic Information

# Expected behavior:
-------------------
```
			if ((string) $forum_uuid === Config::$modSettings['forum_uuid']) {
				self::$namespace = $forum_uuid->getBinary();
```

Undefined variable '$forum_uuid'.

# Actual behavior:
-------------------
No undefined

### Version/Git revision

fbde11e21

### Database Engine

All

### Additional Information

@Sesquipedalian I am trying to figure out what it was meant for and I'm unsure.

Related to PR #7966

**Comment by Sesquipedalian** [comment]
Silly mistake on my part. I'll submit the fix shortly.
