### ISSUE TITLE
[3.0]: Cannot view PM's in action or popup

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#7981]
### Basic Information

# Expected behavior:
Reading the PM's

# Actual behavior:
```
Fatal error: Uncaught TypeError: Cannot assign string to property SMF\PersonalMessage\Received::$labels of type array
SMF\PersonalMessage\Received->customPropertySet('labels', '-1') 
Sources\DynamicPropertyHelper.php on line 193
```

### Steps to reproduce

1.
2.

### Version/Git revision

3.0 Alpha 1

### Database Engine

MySQL

### Database Version

5.7.33

### PHP Version

8.1

### Additional Information

- No pm labels in my tables.

- Contents of pm_recipients:
![Screenshot_12](https://github.com/SimpleMachines/SMF/assets/3318127/bef9c7ae-c67b-493d-a351-5ce77b2be572)

**Comment by Oldiesmann** [comment]
I can't reproduce this on my test board.
![image](https://github.com/SimpleMachines/SMF/assets/89023/12a6bb09-5c9a-4187-bf20-5b50fc94f76f)
![image](https://github.com/SimpleMachines/SMF/assets/89023/b45ef294-be6c-41a0-8aca-6ad7fdafae0d)

**Comment by DiegoAndresCortes** [comment]
I fixed it doing this:

```
	protected static function queryData(array $selects, array $params = [], array $joins = [], array $where = [], array $order = [], array $group = [], int|string $limit = 0)
	{
		self::$messages_request = Db::$db->query(
			'',
			'SELECT
				' . implode(', ', $selects) . '
			FROM {db_prefix}pm_recipients AS pmr' . (empty($joins) ? '' : '
				' . implode("\n\t\t\t\t", $joins)) . (empty($where) ? '' : '
			WHERE (' . implode(') AND (', $where) . ')') . (empty($order) ? '' : '
			ORDER BY ' . implode(', ', $order)) . (empty($group) ? '' : '
			LIMIT ' . $limit),
			$params,
		);

		while ($row = Db::$db->fetch_assoc(self::$messages_request)) {
			$row['labels'] = [$row['labels']];
			yield $row;
		}
		Db::$db->free_result(self::$messages_request);
	}
```

Not sure what is a better fix to make labels an array from the query.
This is in Received.php btw

**Comment by Sesquipedalian** [comment]
@DiegoAndresCortes: There isn't supposed to be a labels column in the pm_recipients table. The upgrade from 2.0 to 2.1 was supposed to remove that for you, so apparently something went wrong during your upgrade process. At any rate, you should simply delete that column from your table.
