### ISSUE TITLE
[3.0]: "Undefined array key" errors when logging in with TFA

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#7983]
### Basic Information

# Expected behavior:
-------------------
No errors in the error log when doing normal things like logging in with TFA

# Actual behavior:
-------------------
These two errors appear each time you go to "action=logintfa", resulting in 4 errors in the error log each time you log in with TFA

```
2: Undefined array key "dataset"
2: Undefined array key ""
```

Both point to line 4635 in Sources/User.php

### Steps to reproduce

1. Set up TFA on your account
2. Log in with TFA enabled

### Version/Git revision

0fd130d

### Database Engine

All

### Database Version

MariaDB 10.6.12

### PHP Version

8.3.0

**Comment by Sesquipedalian** [comment]
Fixed in #7982

**Comment by Oldiesmann** [comment]
This is a completely different issue @Sesquipedalian. The issue I fixed caused an error when trying to logout if TFA was enabled. This still occurs with the latest revision (4bc65a0).

**Comment by Sesquipedalian** [comment]
My mistake. 🙂

**Comment by Oldiesmann** [comment]
Did some digging and it appears when you hit logintfa, the information for the user who's logging in isn't actually loaded (presumably because they haven't actually logged in yet). Here's a print_r of `self::$profiles` right before the line where the errors are generated...
```
Array
(
    [1] => Array
        (
        )

    [0] => Array
        (
            [dataset] => basic
            [timezone] => America/New_York
            [time_offset] => 0
        )

)
```
We already check to see if `self::$profiles[$id]` is set here, but we don't make sure it actually has anything in it. It might be better to change the !isset to an !empty on that line.
