### ISSUE TITLE
3.0 Undefined $labels

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7986]
PersonalMesage/Folder.php
```
		// Finally mark the relevant messages as read.
		if ($this->is_inbox && !empty(self::$labels[(int) $this->current_label_id]['unread_messages'])) {
			PM::markRead($display_pms, $this->current_label_id);
		}
```

$labels is never defined in this file.

The usage of $labels is also in Received.php and Rule.php.  I can't find the definition of where $labels come from.

**Comment by Sesquipedalian** [comment]
`self::$labels` should be `Label::$loaded`.
