### ISSUE TITLE
[3.0]: A case against the forgotten file_put_contents

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#7990]
### Basic Information

The error log is outraged and demands that this outrage be stopped :)

The suspect was seen in two separate locations attempting to secure valuable data:

1) BBCodeParser.php:
```php
if (isset($_REQUEST['preview'])) {
    file_put_contents('/tmp/derp.txt', 'data = ' . $data . "\n", FILE_APPEND);
}
```

2) ExportProfileData.php:
```php
file_put_contents('/tmp/derp.xml', $this->stylesheet);
```

### Steps to reproduce

1. Try to post something

3. Try to export any profile data

### Version/Git revision

3.0 Alpha 1

### Database Engine

MySQL

### Database Version

10.11.6-MariaDB

### PHP Version

8.0.30

### Logs

```shell
1) file_put_contents(/tmp/derp.txt): Failed to open stream: No such file or directory

2) file_put_contents(/tmp/derp.xml): Failed to open stream: No such file or directory
```

### Additional Information

Windows

**Comment by Sesquipedalian** [comment]
Oops.
