### ISSUE TITLE
[3.0]: Caching fails on board index

### ISSUE THREAD

**Issue by Sesquipedalian** [SimpleMachines/SMF#7991]
### Basic Information

Turning on caching causes the board index to die with a fatal error (see logs section below).

### Steps to reproduce

1. Turn on caching
2. Try to view the board index

### Version/Git revision

3.0 Alpha 1

### Database Engine

All

### Logs

```shell
Fatal error: Uncaught TypeError: strlen(): Argument #1 ($string) must be of type string, false given in /Users/jon/Sites/dev/Sources/Cache/CacheApi.php:558 Stack trace: #0 /Users/jon/Sites/dev/Sources/Cache/CacheApi.php(558): strlen(false) #1 /Users/jon/Sites/dev/Sources/Cache/CacheApi.php(512): SMF\Cache\CacheApi::put('boardindex-late...', Array, 60) #2 /Users/jon/Sites/dev/Sources/Actions/BoardIndex.php(92): SMF\Cache\CacheApi::quickGet('boardindex-late...', '', Array, Array) #3 /Users/jon/Sites/dev/Sources/Actions/BoardIndex.php(275): SMF\Actions\BoardIndex->execute() #4 [internal function]: SMF\Actions\BoardIndex::call() #5 /Users/jon/Sites/dev/Sources/Forum.php(260): call_user_func('SMF\\Actions\\Boa...') #6 /Users/jon/Sites/dev/index.php(144): SMF\Forum->execute() #7 {main} thrown in /Users/jon/Sites/dev/Sources/Cache/CacheApi.php on line 558
```

### Additional Information

This is the due to the caching system really not being designed for strict types.

**Comment by Sesquipedalian** [comment]
The best solution is probably to implement JsonSerializable in SMF\Board, SMF\Category, or both, and then use the jsonSerialize() method to control what is included in the JSON data.

**Comment by Sesquipedalian** [comment]
Ugh. The more I look at this, the nastier it gets. The cache system isn't designed for strict types, and it also isn't designed for caching objects. I am beginning to suspect that we are going to have to rip out a bunch of the guts and replace them.

**Comment by jdarwood007** [comment]
To cache objects, it has to be serialized not json encoded.  That said, I set the types for caching to mixed, so it should pass any type.  So even if we back off the strict typing, this would still be a problem if we are json encoding the data to be cached.
