### ISSUE TITLE
[3.0]: Actions\Admin\Permissions::$permission_groups

### ISSUE THREAD

**Issue by tyrsson** [SimpleMachines/SMF#8007]
### Basic Information

This is referencing the permissions hook issue originally brought up by @dragomano here:

https://github.com/SimpleMachines/SMF/pull/7931#issuecomment-1886241722

Possibly caused by missing 'membergroup' key
`	public static array $permission_groups `

I'm assuming that previously there was a 'membergroup' key present...

### Steps to reproduce

1.
2.

### Version/Git revision

Most recent revision

### Database Engine

MySQL

### Logs

```shell
Listed in linked reply
```

**Comment by dragomano** [comment]
At the moment I've found a way around this with [simple key existence check](https://github.com/dragomano/Light-Portal/commit/374931c593fb2c0aa2afa505f469a5e3ce455eb8#diff-2a87993377f6adf2a9f274383fe2e1d6fb8b8f562b32635230df6a0c8e69dff8).
