### ISSUE TITLE
[3.0]: TypeError on adding new languages

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#8014]
### Basic Information

Error: `Argument #1 ($array) must be of type array, string given, called in Sources\PackageManager\XmlArray.php on line 233
File: XmlArray.php

### Steps to reproduce

1. Go to Languages -> Add language
2. Try to add a new language

### Version/Git revision

3.0 Alpha 1

### Database Engine

MySQL

### Database Version

10.11.6-MariaDB

### PHP Version

8.0.30

### Additional Information

![sshot-18](https://github.com/SimpleMachines/SMF/assets/229402/f22ead81-0b89-4cb1-94f8-a556da09ae14)

**Comment by jdarwood007** [comment]
I see the issue.  $array in the `exist` method is an empty string.  You can't pass that to _path.  Looks like it should just do a false return because it doesn't exist.

Will send a PR shortly.
