### ISSUE TITLE
[2.1.4]: Renaming a ban fails with Database Error if name is too long

### ISSUE THREAD

**Issue by sagamusix** [SimpleMachines/SMF#8019]
### Basic Information

Trying to rename a ban will fail with an opaque Database error if the name is too long, even though the input field itself has no length limit. Reading the admin error logs reveals the problem: `Database Error: Data too long for column 'name' at row 1` (source location: ManageBans.php, line 1564)

### Steps to reproduce

1. Edit an existing ban
2. Rename the ban name to something moderately lengthy
3. Observe Database Error.

### Expected result

The input field should be limited to maximum permitted length.

### Version/Git revision

2.1.4

### Database Engine

MySQL

**Comment by albertlast** [comment]
@Sesquipedalian i guess the issue should be closed by the pr.

**Comment by Sesquipedalian** [comment]
Indeed. Thanks for noticing this, @albertlast. GitHub's feature to automatically close issues seems to have become quite unreliable lately.
