### ISSUE TITLE
Admin saving options...

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#802]
When saving an admin screen - in cases where the "SAVE" returns the admin to the same screen as the save was triggered, there is no feedback that the options were actually saved. The screen refreshes (quickly) but if you were not paying close attention to notice the blink/refresh, it looks like nothing happened after pressing save.

There is no feedback, but the successful save is implied on other admin screens when you are returned to a different screen from the original saved screen (usually one level above it in hierarchy)

There should be some sort of acknowledgement displayed - that the save was successful.

**Comment by Arantor** [comment]
I think this is all done but if not, please flag as new issue.
