### ISSUE TITLE
[3.0]: htmlspecialcharsRecursive receives integers

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#8026]
### Basic Information

In certain places, htmlspecialcharsRecursive and htmlspecialchars receive integers.
For example, in the registration process, the following data is sent as a unix timestamp:

https://github.com/SimpleMachines/SMF/blob/fc6b11d9591122d5a2d0d02b2c2cf96668106c96/Sources/Actions/Register2.php#L301-L308

There might be more places.
It seems it always has received integers too, either intentionally or by accident.
Should it skip integers, convert them, or keep accepting them?

### Steps to reproduce

1. Attempt to register a new account
2. `Uncaught TypeError: SMF\Utils::htmlspecialcharsRecursive(): Argument #1 ($var) must be of type array|string, int given`

### Version/Git revision

3.0 Alpha 1

### Database Engine

MySQL

### PHP Version

8.1

**Comment by jdarwood007** [comment]
Check The comment on #8021.  I believe this should resolve it.  At least it did in my testing.

**Comment by DiegoAndresCortes** [comment]
Yes, looks good
