### ISSUE TITLE
[3.0]: Alert::fetch() $to_fetch is receiving integers

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#8027]
### Basic Information

When fetching a specific alert:
https://github.com/SimpleMachines/SMF/blob/fc6b11d9591122d5a2d0d02b2c2cf96668106c96/Sources/Actions/Profile/ShowAlerts.php#L57

It sends the alert id. But fetch is expecting a boolean or an array in $to_fetch and receives neither.
This will cause for Alert:loadForMember to fail in this check:
https://github.com/SimpleMachines/SMF/blob/fc6b11d9591122d5a2d0d02b2c2cf96668106c96/Sources/Alert.php#L846

Thus returning the entire list of alerts and always grabbing the oldest one when you go to ?action=profile;area=showalerts;alert=2;

### Steps to reproduce

1. Receive some alerts
2. Click on any alert, all of them go to the oldest one's _target_href_

### Expected result

It should redirect to the correct alert.

### Actual result

It redirects to the wrong alert.

### Version/Git revision

3.0 Alpha 1

### Database Engine

MySQL

### PHP Version

8.1

### Additional Information

Two possible solutions (for me anyways).

- Cast the single alert where this happens, in an array:
`$alerts = Alert::fetch(User::$me->id, [$alert_id]);`

- Add integer to the types of $to_fetch for both Alert::fetch and Alert:loadForMember

**Comment by jdarwood007** [comment]
I came across this as well, I have a fix for it in #8021 
If a separate PR that fixes this merges first, I can remove the fix from my PR.

**Comment by DiegoAndresCortes** [comment]
Your solution is fine.

The second solution might account for a usage of fetch_alerts from backcompat?

**Comment by jdarwood007** [comment]
This may work for that:
```
	function fetch_alerts(
		int $memID,
		bool|array|int $to_fetch = false,
		int $limit = 0,
		int $offset = 0,
		bool $with_avatar = false,
		bool $show_links = false,
	): array {
		if (!is_bool($to_fetch) && !is_array($to_fetch)) {
			$to_fetch = (array) $to_fetch;
		}

		return SMF\Alert::fetch($memID, $to_fetch, $limit, $offset, $with_avatar, $show_links);
	}
```

If it's not bool or array, cast it.  I discussed with @Tyrsson that we would have casting issues for backward compact code.

**Comment by jdarwood007** [comment]
The int solution doesn't work because I looked at the fetch code.  It didn't seem targeted to handle $to_fetch as an int.  Seemed like it was better off then just ensuring we passed the array.

**Comment by DiegoAndresCortes** [comment]
It worked on my test, it just casts as array and before only failed the boolean check.
In any case the proposed solution for fetch_alerts is good imo.

**Comment by jdarwood007** [comment]
You are right.  To fix it the other way both `fetch()` and `loadForMember()` need to be updated to accept ints.  @Sesquipedalian Any opinion of which direction the fix should go?  Add int as an accepted type, or force things to be an array?

**Comment by Sesquipedalian** [comment]
It's better to cast the argument to an accepted type before passing it to the function, rather than expanding the list of accepted types.

**Comment by tyrsson** [comment]
Well, for the back compat mapping functions. Imho the typing needs expanded for the fetch_alerts function.

Then just check it against is_int and cast it. Since the back compat is the layer that needs to maintain old behaviour and translate it to what the new typing. Bool and Array is covered by the typing already, adding int is the outlier. It's the only type check that needs to occur.

> This may work for that:
> 
> ```
> 	function fetch_alerts(
> 		int $memID,
> 		bool|array|int $to_fetch = false,
> 		int $limit = 0,
> 		int $offset = 0,
> 		bool $with_avatar = false,
> 		bool $show_links = false,
> 	): array {
> 		if (is_int($to_fetch)) {
> 			$to_fetch = (array) $to_fetch;
> 		}
> 
> 		return SMF\Alert::fetch($memID, $to_fetch, $limit, $offset, $with_avatar, $show_links);
> 	}
> ```
> 
> If it's not bool or array, cast it. I discussed with @Tyrsson that we would have casting issues for backward compact code.

The typing only needs expanded for the back compat function signature. Only the int type needs checked.

**Comment by jdarwood007** [comment]
Any issue then with what I've done?  In the PR I have it as:
```
	if (!is_bool($to_fetch) && !is_array($to_fetch)) {
			$to_fetch = (array) $to_fetch;
		}
```
We may end up having to remove some of these strict types from the compact and forcing them before sending them into the native functions.  It adds more work, but its the only way to ensure proper compat occurs.

**Comment by tyrsson** [comment]
I suggested my change in the quote.
`		if (is_int($to_fetch)) {
			$to_fetch = (array) $to_fetch;
		}`

The typing already validates the two types you are checking against. Those checks are not needed.

If its bool, the underlying can handle it.
If its array the underlying can handle it.

The problem condition is is_int, which then needs cast to array.

**Comment by jdarwood007** [comment]
Well if we drop the typing, so lets say a 'string' can come in, because 2.1 wasn't typed.  Then this would say it is not an array and doesn't look like a bool (we could try to check that), then cast it over to an array.  Although I guess I should also then do instead `$to_fetch [(int) $to_fetch];` to ensure its a int.

**Comment by tyrsson** [comment]
Are we going to drop the typing? I really do not care either way.

I realize the array may contain a value that is not the correct type. How many values should be the max number passed? 1? if so why are we even passing an array? It should just handle int.

In the event we get an array should we iterate all values and make sure they are all cast to int or bool?

Take your pick. Matters not to me.

**Comment by tyrsson** [comment]
@jdarwood007 As per our discord discussion yesterday. I think we just fix the typing for the incoming and let the underlying method handle?

**Comment by jdarwood007** [comment]
I think I added the proper fix to the strict types PR
