### ISSUE TITLE
[3.0] Backards compat strict type error

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#8028]
@Tyrsson 

Sources/Board.php
```
public static $info;
```

Set the type to self.
Refresh the forum

```
( ! ) Fatal error: Uncaught Error: Cannot access uninitialized non-nullable property SMF\Board::$info by reference in /Sources/BackwardCompatibility.php on line 67
```

We may have this issue with other areas.  I suspect we will have to make these variables nullable.

**Comment by tyrsson** [comment]
At the moment I do not see a way around them not being nullable. None of them will be set to anything other than null, ie no value assigned (unless the defining class sets a default) before exportStatic executes.

**Comment by jdarwood007** [comment]
@Sesquipedalian Any issues if we start using and converting to more null usage?  Strict typing is going to require it.  It should in theory produce the same results as uninitialized and null essentially mean the same thing.  The only side effect I'm aware of is if you call PHP's `gettype`, it will return null if currently null, rather than the actual type.

**Comment by Sesquipedalian** [comment]
I foresee no issues with that.
