### ISSUE TITLE
Likes permissions

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#804]
I didn't bother putting any enforcement in at this stage (heck I seem to have managed to forget even a session check, which I'll fix momentarily), over whether the user is liking their own posts or not, nor have I worried about adding permissions for such.

I honestly don't think we need to make a big deal out of this, and I don't want to multiply options for the sake of multiplying out options. What, exactly, _do_ we need?

**Comment by mcblaber** [comment]
I think just a general permission would be sufficient:
"Permission to like a post?"

I agree with the fact that I don't think we need any permissions on whether or not a user can like their own posts. Heck, even facebook allows you to like your own content.

**Comment by ChasLarge** [comment]
Will there be any way to disable the "Like" feature for Admins? I cannot see my members taking to this feature. They've found it very contentious on other sites.

**Comment by Xarcell** [comment]
Enable/Disable Likes.
Cannot Like Own Post(to keep people from spamming their own posts with likes, which leads to the next one).
Most Liked Topics/Posts/Users In Stats Page.
Sort Posts In Message Index By Likes.

That's all I can think of.

**Comment by Oldiesmann** [comment]
I think stats and simple any/own permissions should be enough (and possibly an "enable likes" option if people feel it's really necessary, which I don't).

**Comment by Hristo-** [comment]
The first 2 things I will want to do after installing 2.1 is to change the speed and remove the drop down effect of the menus (I find them annoyingly slow) and the other thing is to turn off the likes. So personally all I need is an option to disable it. IMHO in a long run likes are bad for the community and there are no exceptions I can think off right now.

**Comment by MissAllSunday** [comment]
This has been implemented.

cannot like own content.
can_see
can_like
