### ISSUE TITLE
[3.0]: Problems with loading default language strings when using additional languages

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#8043]
### Basic Information

When installing additional language packs, the forum does not load lines from English if they are not present in the additional language.

### Steps to reproduce

1. Extract files of additional language pack
2. Select this language in the settings
3. Open index.{language}.php, comment $txt['admin']
`//$txt['admin']`
5. Refresh page and you will see empty item in the menu:
![sshot-12](https://github.com/SimpleMachines/SMF/assets/229402/c7fb7998-aa57-4725-84f6-2c9afdf633dc)

### Version/Git revision

3.0 Alpha 1

### Database Engine

MySQL

### Database Version

MariaDB-10.6.11

### PHP Version

8.0.30

### Logs

```shell
`Undefined array key "admin"`
```

### Additional Information

Somewhere, there's a line missing `self::load($template, 'english', false);`

**Comment by jdarwood007** [comment]
@Sesquipedalian See https://github.com/SimpleMachines/SMF/pull/7853/commits/13ae296bea64b278903b17cb3262a609c116a89a
I don't know if its the right fix, but it does fix it.

**Comment by Sesquipedalian** [comment]
> @Sesquipedalian See https://github.com/SimpleMachines/SMF/pull/7853/commits/13ae296bea64b278903b17cb3262a609c116a89a
> 
> I don't know if its the right fix, but it does fix it.

LGTM

**Comment by jdarwood007** [comment]
Perfect. It will be resolved then when we merge the language PR.
