### ISSUE TITLE
[3.0]: Class "SMF_BackgroundTask" not found

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#8046]
### Basic Information

SMF 2.1 mods use background tasks with the SMF_BackgroundTask class, but in 3.0 there is no such class anymore. As a result, such mods do not work even in compatibility mode.

### Steps to reproduce

1. Test any mod with background tasks extend SMF_BackgroundTask

### Version/Git revision

3.0 Alpha 1

### Database Engine

MySQL

### Database Version

MariaDB-10.6.11

### PHP Version

8.0.30

### Additional Information

It should to put `class_alias('SMF\\Tasks\\BackgroundTask', 'SMF_BackgroundTask');` into Subs-Compat.php:

```php
if (!empty(SMF\Config::$backward_compatibility)) {
	class_alias('SMF\\Tasks\\BackgroundTask', 'SMF_BackgroundTask');
```

**Comment by jdarwood007** [comment]
Wouldn't it make more sense to put it into TaskRunner.php?

**Comment by dragomano** [comment]
Yes it's possible
