### ISSUE TITLE
[2.1, 3.0]: Wrong position for $context['error_code'] in template

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#8049]
### Basic Information

Errors.template.php, function template_fatal_error:
```php
<div ', $context['error_code'], 'class="padding">
```
Result HTML (for example, on 404 error):
```html
<div 404class="padding">
```
As a result, the padding class is not recognized and does not work.

### Steps to reproduce

1. Open non-exist action
2. Open browser's devtools and select the message block

### Expected result

`<div class="padding">`

or maybe

`<div class="padding error_404">`

### Actual result

`<div 404class="padding">`

### Version/Git revision

2.1.4, 3.0 Alpha 1

### Database Engine

MySQL

### Database Version

MariaDB-10.6.11

### PHP Version

8.0.30

**Comment by jdarwood007** [comment]
@DiegoAndresCortes and @TwitchisMental,  Can you add this to the theme PR (#7933)?

**Comment by DiegoAndresCortes** [comment]
Can you assign it to me I'll check it in a few weeks

**Comment by DiegoAndresCortes** [comment]
Minor version is inverted in title of the issue btw
