### ISSUE TITLE
[3.0]: Undefined array key "passwrd1" when changing password

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#8055]
### Basic Information

Undefined array key "passwrd1" in Sources/Profile.php, line 2170

### Steps to reproduce

1. Type a new password
2. Type current password
3. Save

### Version/Git revision

3.1 Alpha 1

### Database Engine

All

### PHP Version

8.0.30

**Comment by DiegoAndresCortes** [comment]
I was actually still on #7853

**Comment by DiegoAndresCortes** [comment]
Well it turns out I can still reproduce it.
It's inconsistent however, hopefully someone else can also reproduce this... 

And sometimes the 'Current Password' field doesn't show up, I'm a bit confused with this one.

**Comment by DiegoAndresCortes** [comment]
See this for example.
I tried to change the password and all three inputs are correct, but the return is this field in red, no error, what does it mean?
![Screenshot_324](https://github.com/SimpleMachines/SMF/assets/3318127/57403882-7299-4ba1-9c5c-2c35d2b807cf)

**Comment by jdarwood007** [comment]
@Sesquipedalian I can reproduct this as well

```
				// Set the save variable.
				$this->new_data[$db_key] = $_POST[$key];

				// And update the user profile.
				$this->data[$key] = $this->new_data[$key];

```

Seems that $db_key is `passwd` and $key is `passwd1`.  `$this->new_data[$db_key]` and `$this->data[$key]` do not exist.  However `$_POST[$key]` exists and has the encrypted password.
