### ISSUE TITLE
[3.0]: Can't move or place boards in desired position

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#8067]
### Basic Information

When moving boards with the arrows they always remain in the same position.
I'm sometimes able to move a board to a different category and place it **after** another board but never _before_. It's quite inconsistent on this erratic behavior as well.

And editing boards to move them doesn't work either.
I did not get any errors during this 'move' operations so I didn't investigate more.

### Steps to reproduce

1. Add a bunch of boards
2. Attempt to move them to different positions

### Expected result

Boards should be moved to the position you select using the arrows, or the select dropdown when editing boards.

### Actual result

They remain in the same position OR they move to the wrong position.

### Version/Git revision

3.0 Alpha 1

### Database Engine

MySQL

### Database Version

8.0.36

### PHP Version

8.1

**Comment by Sesquipedalian** [comment]
Hm. In my tests, the results were also erratic, but somewhat _differently_ erratic than what you describe, @DiegoAndresCortes. The boards always moved, but not always to the right place.

More investigation will be needed.
