### ISSUE TITLE
[3.0]: Unable to load the 'Settings.' language file.

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#8068]
### Basic Information

This is generated in the error log.
From previous discussion, I assume it should be loading ThemeStrings instead.

However, in the areas where it's needed it appears to be already loaded so the calls to load Settings language file could be dropped instead of replaced.

### Version/Git revision

3.0 Alpha 1

### Database Engine

MySQL

### PHP Version

8.1

**Comment by Sesquipedalian** [comment]
I'm not seeing this. Please provide more information about how to reproduce this.

**Comment by Oldiesmann** [comment]
@Sesquipedalian if you go to the Theme Settings section of your profile, that error will pop up in your error log.

**Comment by Sesquipedalian** [comment]
> @Sesquipedalian if you go to the Theme Settings section of your profile, that error will pop up in your error log.

Hm. I'm still not seeing any errors about that. There must be something more going on.

Also, I assume you mean the Theme Settings section of the Admin Centre. If not, please clarify. 🙂

**Comment by Oldiesmann** [comment]
Sorry. I meant the "Look and Layout" section of the profile, not the Theme Settings section.
