### ISSUE TITLE
[3.0]: Language files are not removed on mods deleting

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#8094]
### Basic Information

![sshot-7](https://github.com/SimpleMachines/SMF/assets/229402/88433c01-9f0a-4db0-8a54-bfdc6c0c5b29)

### Steps to reproduce

1. Install any mod with hooks and language files for SMF 2.1
2. Try to uninstall it

### Expected result

`<remove-dir name="$languagedir/modname" />`

I think that we need to check both paths on deleting: `$boarddir/Languages`, and `$themedir/languages` (if compatibility mode is enabled)

### Version/Git revision

3.0 Alpha 2

### Database Engine

MySQL

### Database Version

10.11.6-MariaDB

### PHP Version

8.0.30

**Comment by jdarwood007** [comment]
You are correct, I will look into this when I get a chance unless somebody else gets a chance.  This may not be the cleanest logic, but would only need to be done when we are running in compatibility mode.

**Comment by Sesquipedalian** [comment]
I cannot reproduce this myself.

@dragomano, does the issue still exist for you? Perhaps more recent changes have solved it already, but I don't know.

**Comment by dragomano** [comment]
What mods did you use for testing?

P. S. I have installed the current version for testing and got an error on the Package manage index area - "Fatal error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, string given in PackageManager\PackageManager.php:1639", fix - replace "$items = Utils::jsonDecode($data['data'], true);" with "$items = Utils::jsonDecode($data['data'], true) ?? [];"

**Comment by Sesquipedalian** [comment]
Several of my own. Can you give me a mod that does produce the error? Then I can figure out what is causing it.

**Comment by dragomano** [comment]
Try to install the Simillar Topics, in the compatibility mode.
