### ISSUE TITLE
[2.1] Obsolete code in build_query_board

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#8096]
In the `build_query_board()` in Subs.php, these 2 lines seem to be obsolete. Judging by the code above, they are trying to replace `b.` which is not there. Leftover legacy code?

https://github.com/SimpleMachines/SMF/blob/7f226101fcecb6cff4f00051ea5b4837ee0741b0/Sources/Subs.php#L7831-L7832

**Comment by jdarwood007** [comment]
They are related helpers.  When we use query_see_board, it has a b. prefix as we typically alias smf_boards with this.  m and t are aliases for smf_messages and smf_topics.  This just makes it easier to use them without having to join in smf_boards just to handle query_see_board.  @albertlast added this in 2.1

**Comment by asmith20002** [comment]
But isn't `build_query_board()` function the one which is responsible for creating the `query_see_board` ?  The `query_see_board` is getting created right above the referenced lines and it doesn't have `b.` prefix. I think it's because those `b.` prefixes were in 2.0 now in 2.1 we have `EXISTS`.


https://github.com/SimpleMachines/SMF/blob/7f226101fcecb6cff4f00051ea5b4837ee0741b0/Sources/Subs.php#L7805-L7829

**Comment by jdarwood007** [comment]
There is a b. reference in that query.  Last line of the query.

**Comment by asmith20002** [comment]
*facepalm*
