### ISSUE TITLE
[3.0]: Spelling mistakes or other mistakes in the language strings

### ISSUE THREAD

**Issue by gregorklaric** [SimpleMachines/SMF#8097]
### Basic Information

Spelling mistakes or other mistakes in the language strings

![2024-02-10 14_21_14-Install php - Simple Machines - Crowdin translation](https://github.com/SimpleMachines/SMF/assets/17081410/46f17736-8059-4811-8215-383fd0f95f32)
![2024-02-10 15_41_48-Packages php - Simple Machines - Crowdin translation](https://github.com/SimpleMachines/SMF/assets/17081410/2368f091-7411-4900-b93b-c94eab6981ee)
![2024-02-10 15_50_25-PersonalMessage php - Simple Machines - Crowdin translation](https://github.com/SimpleMachines/SMF/assets/17081410/80106248-e17c-44b4-886e-f6f2fef976f9)
![2024-02-10 17_29_55-All Strings - Simple Machines - Crowdin translation](https://github.com/SimpleMachines/SMF/assets/17081410/cf373e47-994e-4338-a820-4003bd7244ba)
![2024-02-10 11_20_45-Admin php - Simple Machines - Crowdin translation](https://github.com/SimpleMachines/SMF/assets/17081410/fd450e74-d0c8-4023-b62d-c869c559d235)
![2024-02-10 12_43_27-Errors php - Simple Machines - Crowdin translation](https://github.com/SimpleMachines/SMF/assets/17081410/7be5d682-7b62-45b1-b3fe-047e5338375f)

### Version/Git revision

3.0 Crowding strings

### Database Engine

MySQL

**Comment by gregorklaric** [comment]
Another one:

![2024-02-12 08_54_57-Admin php - Simple Machines - Crowdin translation](https://github.com/SimpleMachines/SMF/assets/17081410/7af526a8-a741-4164-bd3a-9bf4e9116d79)

**Comment by Sesquipedalian** [comment]
> ![2024-02-10 17_29_55-All Strings - Simple Machines - Crowdin translation](https://private-user-images.githubusercontent.com/17081410/303860388-cf373e47-994e-4338-a820-4003bd7244ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NTE2MjAsIm5iZiI6MTcwNzg1MTMyMCwicGF0aCI6Ii8xNzA4MTQxMC8zMDM4NjAzODgtY2YzNzNlNDctOTk0ZS00MzM4LWE4MjAtNDAwM2JkNzI0NGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE5MDg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MTViNWEyYzFkZTQ1NDMxZTJmY2Q3NjFmOWM5Yzg1MWEzYTI2M2I0NzNmYmU5ZmY2MmRjMzYzZjEzZDJkNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y_s6YorPbnkh9AfmVNUUTjwHp0YUbFcw2wQABQ_T3Lc)

This one is a strange case. The value of the 'num_birthdays' parameter that is passed to Lang::$txt['calendar_click_all'] will always be at least 10. That means that for languages whose 'one' rule only matches the value 1 (such as English), the 'one' case will never be used and wouldn't make any sense anyway.

Honestly, though, inserting the numerical value into this string is superfluous. The string is only used to create a "Click here to see all" link, and the number of birthdays in the list is irrelevant to that purpose. So I think I will just turn Lang::$txt['calendar_click_all'] into a simple string saying 'Show all' and leave it at that.
