### ISSUE TITLE
[3.0]: Compilation failed: two named subpatterns have the same name (PCRE2_DUPNAMES not set)

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#8107]
### Basic Information

Receiving an error while attempting to use `updateSettingsFile`.

### Steps to reproduce

Create a test script:
```
<?php
use \SMF\Db\DatabaseApi AS Db;
require_once('SSI.php');
SMF\Config::updateSettingsFile( $config_vars = ['language' => 'en_US'] );
```

### Expected result

No error

### Actual result

( ! ) Warning: preg_match(): Compilation failed: two named subpatterns have the same name (PCRE2_DUPNAMES not set) at offset 74 in /Sources/Config.php on line 1986

### Version/Git revision

f89b85543

### Database Engine

All

### Additional Information

@Sesquipedalian I got this while working on the PR for the new installer/upgrader.

**Comment by Sesquipedalian** [comment]
Fixed
