### ISSUE TITLE
Main menu appears BEHIND the linktree text

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#812]
with build from 6Nov
http://test2.turtleshellprod.com/index.php

Additionally the pop-up boxes for help grey out the background, but also grey out the foreground and have the text appearsing behind the text which is already on the screen, rather than overlaying it with a non-transparent color

**Comment by Arantor** [comment]
Browser?

**Comment by Kindred-999** [comment]
sorry...   IE 9 (forced to use that at the office)

**Comment by Arantor** [comment]
Can I get screenshots of this please? I'm currently running IE10 and I don't trust the backwards compatibility features I can get to give me something that actually _runs_ as IE9 (been bitten by this in the past)

**Comment by Kindred-999** [comment]
hmmmm.... how do I attach an image?
ah well... link: http://test2.turtleshellprod.com/index.php?topic=8.0 see attachments

**Comment by emanuele45** [comment]
> hmmmm.... how do I attach an image?
> 
> Drag&drop into the area below the one you write into.

**Comment by Kindred-999** [comment]
I tried...  it didn't do it.   Anyway, linked attachments show the issue

**Comment by emanuele45** [comment]
> I tried... it didn't do it. Anyway, linked attachments show the issue
> 
> Just FYI (not being snarky, better say it :P), usually its loaded in
> background and then replaced into the textarea, it uses amazonaws
> network (in case you have javascript or some domain blocked) and it
> loads the code directly into the textarea when it's finished.
> Or maybe some browers problem or whatever, who knows, it's laready
> difficult to debug SMF knowing the code, so debug github is... kind out
> of my league...

**Comment by Kindred-999** [comment]
lol... no snark detected. :)
I think it's another browser issues with IE9 (or my office has blocked those domains)
And no... I don't expect you (or anyone here) to be debugging GitHub. LOL!
Luckily, we have alternate technologies. :)

**Comment by Arantor** [comment]
Yeah, IE9 doesn't support drag 'n' drop (and Github don't care because real devs don't use IE9 _and_ Github)

**Comment by Oldiesmann** [comment]
They've got that part covered with the "or selecting them" thing :wink:

**Comment by illori** [comment]
is this still an issue?
