### ISSUE TITLE
upgrade did not turn OFF maintenance mode...

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#813]
Ran the upgrade utility... selected the option to put the forum in maintenance mode.

When I went back to the forum after finishing the upgrade and cruised around, I was not notified that the forum was in maintenance mode until I went into the admin section.

So, two issues:
1- upgrade did not turn off maintenance mode after finishing the upgrade
2- I was not warned that the forum was still in maintenance mode until I was in the admin section

**Comment by Arantor** [comment]
There is actually a message at the top of the page that mentions it but it needs to be more prominent. Plus the fact I need to take it out of the header as I need the space for something else.

**Comment by Arantor** [comment]
Interestingly, the upgrader is actually quite clear on this point, it actually pushes it back from maintenance=2 to maintenance=1 intentionally. Whether this is a good thing or not is unclear.

I wonder if it might not be better to leave it at maintenance = 1 while the admin explores what's changed and then reopen the board afterwards. It's not like it isn't very blatantly obvious now.

**Comment by illori** [comment]
maybe worth adding in the upgrader a note that the forum is not open to the public once the upgrade is complete?

**Comment by Arantor** [comment]
The maintenance mode warning includes this already, actually.

**Comment by illori** [comment]
ok, then i guess it is less of an issue.

**Comment by Arantor** [comment]
Basically I transplanted the one from the admin panel to everywhere, so it even includes a link to the place where it gets disabled.

**Comment by illori** [comment]
sounds to me like this has been resolved, so we can close this?
