### ISSUE TITLE
`composer lint-fix` doesn't work on windows commandline

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#8162]
https://github.com/SimpleMachines/SMF/blob/b11d8c4178b3d8e18a5243c33174524d216b8e4e/composer.json#L17
![Untitled](https://github.com/SimpleMachines/SMF/assets/431799/70ef0e2a-84f6-4252-b991-055f43764f5f)
same result with the  terminal provided by sourcvtrree
![Untitled](https://github.com/SimpleMachines/SMF/assets/431799/f34eee67-b6d7-4cd4-aeb5-51995d2049da)

**Comment by Sesquipedalian** [comment]
The --name-only option for git diff has been around for a long time. Maybe the version of git that you are using on the command line is very outdated?

**Comment by tyrsson** [comment]
Its worked for me via the vscode powershell integration. Im not sure if any changes have been made since I used it last that might have it broken though.

**Comment by Oldiesmann** [comment]
I'll have to try it on Windows and see if it works for me there. When I do `git help diff` on Linux, the `--name-only` option is one of the ones listed
