### ISSUE TITLE
First line of query gets cut off in query log

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#8170]
Queries in the view query action have their first few characters cut off. The ones at the bottom of every page are unaffected .
![Screenshot 2024-04-05 at 05-54-38 My Community](https://github.com/SimpleMachines/SMF/assets/431799/a7dd3b71-b0e5-44b9-a912-01adbf19c1a0)

I see two ways to fix this

1. fix the trimming algorithm
2. prepend newlines to each query in the code like in 2.x

**Comment by Sesquipedalian** [comment]
> 1. fix the trimming algorithm

This seems like there better approach to me.
