### ISSUE TITLE
$txt['debug_query_which_took_at']

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#8171]
Our translators [are having problems understanding](https://crowdin.com/editor/simple-machines-21-beta/1532/en-pt?view=comfortable&filter=basic&value=0#252478) what "... at n into request" is supposed to mean:
https://github.com/SimpleMachines/SMF/blob/40ee34ae6a45cdeb768e8b4659486d08c2d29722/Languages/en_US/General.php#L1142-L1145

Is it describing stack depth? Time elapsed? Bytes transmitted or received? Character position within the request? Something else?

**Comment by live627** [comment]
I cannot comment there because Crowdin has never fixed their shit but yes,
time elapsed in seconds. That commenter is right that it's clunky,  but
it's a debug string not normally visible.
