### ISSUE TITLE
[3.0]: Upgrade doesn't work

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#8191]
### Basic Information

After fixing the upgrader to call Sapi::httpsOn() instead of Config::httpsOn() (or commenting out those three lines of code), the upgrader now just shows a blank line with a "Click here to try again" link

### Steps to reproduce

1. Apply changes from #8189 or comment out the three relevant lines of code
2. Attempt to upgrade your forum

### Expected result

Upgrade should run as normal

### Actual result

Upgrade shows but instead of being able to begin the process you get a blank line followed by "Click here to try again".
![image](https://github.com/SimpleMachines/SMF/assets/89023/2de08007-acb4-4f21-a7d5-0b6c3a2104d2)

### Version/Git revision

492d519

### Database Engine

All

### Database Version

10.11.7-MariaDB-1:10.11.7+maria~ubu2204

### PHP Version

8.3.6

### Additional Information

Something is causing template_error_msg() to be loaded, but $upcontext['error_msg'] isn't set when the function is called. I haven't looked into it further than that.

**Comment by DiegoAndresCortes** [comment]
Should maybe wait for #8093 instead of fixing it on the current upgrader?

**Comment by Sesquipedalian** [comment]
> Should maybe wait for #8093 instead of fixing it on the current upgrader?

The work happening in #8093 will be a lot easier if we can base it off of working code.
