### ISSUE TITLE
[3.0] Installer needs General language file?

### ISSUE THREAD

**Issue by DiegoAndresCortes** [SimpleMachines/SMF#8221]
The installer uses formatMessage for `$txt['install_welcome_desc']` but this method will fail when it attempts to get $txt['lang_locale'] because the general language file is not loaded in the installer.

**Comment by Sesquipedalian** [comment]
Well, that's an easy thing to fix.

**Comment by DiegoAndresCortes** [comment]
After fixing it, my installer times out in step 2

**Comment by DiegoAndresCortes** [comment]
Without your pull request I get the following (and the db is created):

`Uncaught Error: Typed static property SMF\User::$me must not be accessed before initialization in \Sources\Db\APIs\MySQL.php:258 Stack trace: #0 \install.php(1495): SMF\Db\APIs\MySQL->query('', 'SELECT id_event...', Array) #1 \install.php(179): DatabasePopulation() #2 {main} thrown in \Sources\Db\APIs\MySQL.php on line 258`

**Comment by Sesquipedalian** [comment]
> Without your pull request I get the following (and the db is created):
> 
> 
> 
> `Uncaught Error: Typed static property SMF\User::$me must not be accessed before initialization in \Sources\Db\APIs\MySQL.php:258 Stack trace: #0 \install.php(1495): SMF\Db\APIs\MySQL->query('', 'SELECT id_event...', Array) #1 \install.php(179): DatabasePopulation() #2 {main} thrown in \Sources\Db\APIs\MySQL.php on line 258`

Yes, that is one of the errors fixed by the PR.

**Comment by DiegoAndresCortes** [comment]
Yup, times out with the PR on step 2. I don’t have errors or warnings.

**Comment by Sesquipedalian** [comment]
> After fixing it, my installer times out in step 2

Do you mean that you applied the whole PR and then the installer timed out?

**Comment by Sesquipedalian** [comment]
Odd. I can't test at the moment, but could you try reverting the change to the user agent constant (the only other change in install.php) and then test again?

**Comment by DiegoAndresCortes** [comment]
Reverted the line, no more time out but two issues:

` Warning: Undefined array key "theme_guests" in \Sources\Theme.php on line 203`

`Uncaught Error: Typed static property SMF\User::$me must not be accessed before initialization in \Theme.php:207 Stack trace: #0 \Sources\ErrorHandler.php(598): SMF\Theme::load() #1 \Sources\ErrorHandler.php(296): SMF\ErrorHandler::setupFatalContext('Please try agai...') #2 \Sources\Db\APIs\MySQL.php(267): SMF\ErrorHandler::fatal('Please try agai...', false) #3 \install.php(1495): SMF\Db\APIs\MySQL->query('', 'SELECT id_event...', Array) #4 \install.php(179): DatabasePopulation() #5 {main} thrown in \Sources\Theme.php on line 207`

**Comment by Sesquipedalian** [comment]
Latest commits to #8204 should fix those.

**Comment by DiegoAndresCortes** [comment]
Got a few more


`Warning: Undefined array key "default_timezone" in \Sources\User.php on line 5126`

`Warning: Undefined array key "BAN_CHECK_IP" in \Sources\User.php on line 4682`

`Warning: Undefined array key "time_format" in \Sources\User.php on line 4700`

`
Fatal error: Uncaught TypeError: Cannot assign null to property SMF\User::$time_format of type string in \Sources\User.php:4700 Stack trace: #0 \Sources\User.php(4594): SMF\User->setProperties() #1 \Sources\User.php(2558): SMF\User->__construct(NULL, NULL) #2 \Sources\Theme.php(2372): SMF\User::load() #3 \Sources\Theme.php(260): SMF\Theme->initialize() #4 \Sources\ErrorHandler.php(598): SMF\Theme::load() #5 \Sources\ErrorHandler.php(296): SMF\ErrorHandler::setupFatalContext('Please try agai...') #6 \Sources\Db\APIs\MySQL.php(267): SMF\ErrorHandler::fatal('Please try agai...', false) #7 \install.php(1495): SMF\Db\APIs\MySQL->query('', 'SELECT id_event...', Array) #8 \install.php(179): DatabasePopulation() #9 {main} thrown in \Sources\User.php on line 4700`

**Comment by Sesquipedalian** [comment]
I've added another commit to #8204 to fix those, too.

**Comment by DiegoAndresCortes** [comment]
Another round

`Warning: Undefined array key "avatar_url" in \Sources\User.php on line 2860`

`Warning: Undefined array key "smiley_sets_known" in \Sources\Theme.php on line 2607`

`Fatal error: Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, null given in \Sources\Theme.php:2607 Stack trace: #0 \Sources\Theme.php(2607): explode(',', NULL) #1 \Sources\Theme.php(2375): SMF\Theme->fixSmileySet() #2 \Sources\Theme.php(260): SMF\Theme->initialize() #3 \Sources\ErrorHandler.php(598): SMF\Theme::load() #4 \Sources\ErrorHandler.php(296): SMF\ErrorHandler::setupFatalContext('Please try agai...') #5 \Sources\Db\APIs\MySQL.php(267): SMF\ErrorHandler::fatal('Please try agai...', false) #6 \install.php(1495): SMF\Db\APIs\MySQL->query('', 'SELECT id_event...', Array) #7 \install.php(179): DatabasePopulation() #8 {main} thrown in \Sources\Theme.php on line 2607`

**Comment by Sesquipedalian** [comment]
I've amended the commit to fix those as well

**Comment by DiegoAndresCortes** [comment]
I'm afraid they keep coming. Might need to set all of the $modSettings keys to a default value instead?

**Comment by DiegoAndresCortes** [comment]
The one that errored out (no warning), was this one:
`Utils::$context['news_lines'] = array_filter(explode("\n", str_replace("\r", '', trim(addslashes(Config::$modSettings['news'])))));`
But still had various warnings from others.

**Comment by Sesquipedalian** [comment]
Alright, I've backed up and taken another approach. The initial error that you are encountering on line 1495 of install.php will still happen, but now it will simply die rather than trying to load all the usual stuff needed to display a fatal error message in a theme template.

Solving that initial error can be the subject of a separate PR.

**Comment by Sesquipedalian** [comment]
Actually, I've decided to move the fixes for this installer issue into their own PR (#8223) rather than tacking them onto the fixes for the upgrader. Please test that PR to see if it solves the issue for you, @DiegoAndresCortes.

You will most likely still run into the issue on line 1495 of install.php, but we'll need to deal with that once it can be isolated from the cascade of other problems that followed it.

**Comment by DiegoAndresCortes** [comment]
I’ll test later today
