### ISSUE TITLE
[3.0]: Adding calendar event can cause max_execution_time to be exceeded

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#8232]
### Basic Information

When adding a new recurring event, it's possible for it to hit PHP's max_execution_time. We should add the standard SMF timeout handling stuff (like what we do for creating search indexes, etc.) to this as well.

### Steps to reproduce

1. Create a new event in the calendar that repeats a lot of times (every day or month "forever" did it for me)
2. You'll eventually run into max_execution_time

### Expected result

Event actually posts

### Actual result

PHP timeout

### Version/Git revision

68b6c73

### Database Engine

All

### Database Version

10.11.8-MariaDB-ubu2204

### PHP Version

8.3.7

### Logs

```shell
AH01071: Got error 'PHP message: PHP Fatal error: Maximum execution time of 30 seconds exceeded in /.../Sources/Calendar/RecurrenceIterator.php on line 806', referer: .../index.php?action=calendar;sa=post
```

### Additional Information

We should probably look into adding the standard "timeout protection" functionality (like with creating search indexes for example) to handle this. Although it's not likely to have an event running every month or day for the next 6 years (based on the current max year of 2030), we should do our best to support it if possible.

**Comment by Sesquipedalian** [comment]
Can you tell me the start date, duration, and recurrence rule settings that you used when you encountered this? 

I did a lot of testing with events that recurred forever, and I never ran into this.

**Comment by Oldiesmann** [comment]
I was able to trigger it easily with this setup - start today, go all day, repeat monthly "forever". Max date in the admin center is still 2030.
![image](https://github.com/SimpleMachines/SMF/assets/89023/aa9fff7b-8c67-4d08-b9d1-6e7dd8c25c0b)

**Comment by Sesquipedalian** [comment]
Confirmed. A fix will be submitted shortly.
