### ISSUE TITLE
[3.0]: Undefined variable $is_os

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#8239]
### Basic Information

[Sources/Sapi.php](forum/index.php?action=admin;area=logs;sa=errorlog;file=L2hvbWUvbXN1aXRlL3B1YmxpY19odG1sL2ZvcnVtL1NvdXJjZXMvU2FwaS5waHA=;line=119) (Line 119)

### Steps to reproduce

1. Spamming the same errors in error_log
2. Using latest git commit
3. My database is not using an older smf version.

### Expected result

is_os php variable is defined.

### Actual result

Error log is being spspammer

### Version/Git revision

3.0 Alpha 1

### Database Engine

MySQL

### Database Version

8.1.16

### PHP Version

7.3

**Comment by Sesquipedalian** [comment]
At which line is the error being thrown?

**Comment by Sesquipedalian** [comment]
Also, SMF 3.0 requires PHP 8 or higher. PHP 7.x is not supported.

**Comment by ghost** [comment]
> At which line is the error being thrown?

119

**Comment by ghost** [comment]
> Also, SMF 3.0 requires PHP 8 or higher. PHP 7.x is not supported.

Switched to 8.3, still geting The error

**Comment by Oldiesmann** [comment]
What operating system is your server using? It would appear that the `PHP_OS_FAMILY` constant is reporting "Unknown" (unless you happen to be running on a server powered by Solaris or a BSD variant).

**Comment by ghost** [comment]
No idea, i'm renting the server, would it be possible to add a case for "Unknown"

**Comment by ghost** [comment]
; cPanel-generated php ini directives, do not edit
; Manual editing of this file may result in unexpected behavior.
; To make changes to this file, use the cPanel MultiPHP INI Editor (Home >> Software >> MultiPHP INI Editor)
; For more information, read our documentation (https://go.cpanel.net/EA4ModifyINI)

asp_tags = Off
display_errors = On
max_execution_time = 30
max_input_time = 60
max_input_vars = 1000
memory_limit = 512M
post_max_size = 1024M
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/alt-php83"
upload_max_filesize = 1024M
zlib.output_compression = On

**Comment by jdarwood007** [comment]
A `$is_os = false;` should be added to the start of the foreach, which will clear the error.  Whatever check is performing this isn't sending the right os check, a backtrace should be obtained to figure out where and correct the call.

**Comment by ghost** [comment]
implemented that, and now my error log is cleaner.

**Comment by jdarwood007** [comment]
Bug is still in code, reopen this so we know to fix it.

**Comment by Sesquipedalian** [comment]
Closed in a12b034
