### ISSUE TITLE
[3.0]: "You have an error in your SQL syntax" trying to update profile

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#8248]
### Basic Information

Trying to turn on quick moderation checkboxes, get a database error.

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 12
File: D:\wamp64\www\80van30\Sources\Profile.php
Line: 1593 

### Steps to reproduce

1. Install 3.0
2. Attempt to udpate profile - turning on quick moderation checkboxes

### Expected result

Checkboxes

### Actual result

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 12
File: D:\wamp64\www\80van30\Sources\Profile.php
Line: 1593 

### Version/Git revision

3.0 Alpha 1 - current GH

### Database Engine

MySQL

### Database Version

8.4.0

### PHP Version

8.3.8

**Comment by Oldiesmann** [comment]
Here's the query... Looks like we're missing a ) somewhere.

```
DELETE FROM smf_themes
WHERE id_member = 1
AND (
	(
		id_theme = 1
		AND variable IN (''
	)
	OR (
		id_theme != 1
		AND variable IN ('show_children', 'topics_per_page', 'messages_per_page', 'view_newest_first', 'show_no_avatars', 'show_no_signatures', 'posts_apply_ignore_list', 'return_to_post', 'no_new_reply_warning', 'auto_notify', 'wysiwyg_default', 'drafts_autosave_enabled', 'drafts_show_saved_enabled', 'display_quick_mod', 'popup_messages', 'view_newest_pm_first', 'pm_remove_inbox_label', 'calendar_default_view', 'calendar_start_day'
	)
```
