### ISSUE TITLE
[2.1 & 3.0]:  Merged topic link is broken

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#8249]
### Basic Information

From the forum:
https://www.simplemachines.org/community/index.php?topic=589081.0

Confirmed issue is in both 2.1 & 3.0.

### Steps to reproduce

1.  Merge two topics
2.  Uncheck the "auto redirect" checkbox

### Expected result

Properly working link in the "merged" topic.

### Actual result

Link in the merged topic is broken:
`<a href="//" https:="" localhost="" 80van30="" index.php?topic="3.0""" class="bbc_link">asdfasdf</a>`

When reproducing, it's important to uncheck the auto redirect box.

Different browsers show wildly different behavior:
- Chrome reports the error above
- FF just ignores the link
- Edge says the link is not found and adds a 2nd https// in front...

### Version/Git revision

3.0 Alpha 1 - current GH

### Database Engine

All

### Database Version

8.4.0

### PHP Version

8.3.8

### Additional Information

From the forum:

https://www.simplemachines.org/community/index.php?msg=4175401

**Comment by Sesquipedalian** [comment]
It's a malformed BBC bug.
