### ISSUE TITLE
[3.0]: Server Settings link fails

### ISSUE THREAD

**Issue by Krashsite** [SimpleMachines/SMF#8254]
### Basic Information

Cannot access Server Settings in ACP from main menu

### Steps to reproduce

1. Admin > Main > Maintenance > Server Settings
2.

### Expected result

Open server settings

### Actual result

Session verification failed

### Version/Git revision

3.0 Alpha 6-21-24 

### Database Engine

MySQL

### Database Version

10.6.18-MariaDB-cll-lve

### PHP Version

8.3.8

### Logs

```shell
No forum or server errors
```

### Additional Information

Works correctly from Maintenance dropmenu

**Comment by Krashsite** [comment]
The link actually loads Server Settings but it doesn't load General page, displays error instead.  Click on General and it loads correctly, as do the other links.

![session_ver_ss1](https://github.com/SimpleMachines/SMF/assets/4709239/07a3bbf2-7444-4460-882f-415cc3c7407a)

**Comment by Sesquipedalian** [comment]
Work on the admin control panel is scheduled for Alpha 4, so we'll make sure to deal with this at that point.
