### ISSUE TITLE
[3.0]: Reports link fails

### ISSUE THREAD

**Issue by Krashsite** [SimpleMachines/SMF#8255]
### Basic Information

Cannot access Reports in ACP from main menu

### Steps to reproduce

1.Admin > Main > Maintenance > Reports
2.

### Expected result

Open Reports

### Actual result

WSOD

### Version/Git revision

3.0 Alpha 6-21-24

### Database Engine

MySQL

### Database Version

10.6.18-MariaDB-cll-lve

### PHP Version

8.3.8

### Logs

```shell
No forum or server errors
```

### Additional Information

Same result from Maintenance dropmenu

**Comment by Oldiesmann** [comment]
Odd that you don't get an error in your server log. I get this on my test board (looking at the log for the appropriate domain)

```
AH01071: Got error 'PHP message: PHP Fatal error: Declaration of SMF\\Actions\\Admin\\Reports::load(): SMF\\Actions\\Admin\\Reports must be compatible with SMF\\ActionInterface::load(): static in /.../Sources/Actions/Admin/Reports.php on line 618', referer: ../index.php?action=admin
```

**Comment by Krashsite** [comment]
Had to dick around with php settings in DirectAdmin, now I'm seeing same error -

Fatal error: Declaration of SMF\Actions\Admin\Reports::load(): SMF\Actions\Admin\Reports must be compatible with SMF\ActionInterface::load(): static in /home/thekrash/domains/thekrashsite.com/public_html/smf30/Sources/Actions/Admin/Reports.php on line 618

**Comment by Sesquipedalian** [comment]
Work on the admin control panel is scheduled for Alpha 4, so we'll make sure to deal with this at that point.
