### ISSUE TITLE
[2.1 & 3.0]: Likes should be added to DB using 'ignore' instead of 'insert'

### ISSUE THREAD

**Issue by GL700Wing** [SimpleMachines/SMF#8263]
### Basic Information

Clicking the _'Like'_ button twice in quick succession can occasionally generate an _"Duplicate entry for key smf_user_likes"_ error message.

The fix is to change the database "insert" actions to "ignore" actions.

### Steps to reproduce

Double-click the 'Like' button

### Expected result

Like count is updated, no error message generated

### Actual result

_"Duplicate entry for key smf_user_likes"_ error message.

### Version/Git revision

SMF 2.1.4

### Database Engine

All

### Additional Information

https://www.simplemachines.org/community/index.php?topic=587508.0

**Comment by Oldiesmann** [comment]
I'll keep this in mind when I work on the user-facing side of reactions

**Comment by Sesquipedalian** [comment]
This is a quick fix. I'll slip it into 2.1.5. 

As for 3.0, we'll leave that to @Oldiesmann and his current project.
