### ISSUE TITLE
upgrading from 06Nov build to 07Nov build errors

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#828]
Upgrade.php fails on:
Error!
Error retrieving information on step: Updating log_packages (Item: 56)

restart - pick up from previous step:
Error!
Error retrieving information on step: Adding "profile_password_own"

Now it's stuck and won't get beyond this one...
Executing: "Updating profile permissions..." (20 of 21)

**Comment by Kindred-999** [comment]
Also, while upgrading, the $maintenance seems to be moved to the bottom of the Settings.php file, making a recovery out of maintenance mode difficult to find the setting (it should be up top, with the other maintenance settings

**Comment by Arantor** [comment]
@Oldiesmann Seems related to the new permissions you added to the installer/upgrader yesterday?

**Comment by emanuele45** [comment]
Actually I feel the upgrade is still broken:
https://github.com/SimpleMachines/SMF2.1/blob/6b5c5fe49514f88ae4ee7bac9fa9d446b72f5bd9/other/upgrade_2-1_mysql.sql#L535
and indentation is a bit... odd. :stuck_out_tongue:
