### ISSUE TITLE
minor:  Enter p/w for moderator section, have to enter again for admin section

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#829]
In theory, if the password was just checked, either to enter the moderation section or to enter the admin section, shouldn't the entry be saved and you don't have to re-enter it on viewing the other sections of the forum?

I know that, if you just logged in, with a fresh session (not a forever cookie), the admin query does not trigger asking for the password again....

**Comment by Arantor** [comment]
I believe they're actually stored separately off hand, so that you can log into just the moderation section and not admin.

But I also know that there's a lot of people not very enthusiastic about the entire concept of moderator security.

**Comment by Kindred-999** [comment]
oh, I like that concept...   I just figured that - if I entered my password ONCE, it would be good for all checks.

As I said... it's a minor thing and you can close this if it is FAD

**Comment by Arantor** [comment]
Oh, it's not something we should just close. It should be fixed, even if we don't just nuke moderation security ;)

**Comment by Kindred-999** [comment]
seems that this has been forgotten for 2 years.   Are we abandoning the issue? :-/

**Comment by XinYenFon** [comment]
I support the idea of nuking mod security actually.

**Comment by MissAllSunday** [comment]
No, I would be reticent to remove the moderation security or merge it with the admin one.

**Comment by Arantor** [comment]
Ok, but why? This is a confusing feature, to the point where I can see people calling it a bug. Help me understand what value it brings, to overcome the perception of that.

**Comment by MissAllSunday** [comment]
I consider it to be a good thing to be forced to enter your password every time you enter a delicate part of a forum. no matter how many times you already did or didn't do. It should be reinforced more by using 2FA every time you want to enter the admin panel or even the moderation panel.

But hey... you will come up with a bazillion of reasons why I'm wrong and you're right so I might as well leave. This isn't even something I can decide on.

**Comment by XinYenFon** [comment]
@MissAllSunday what ? Try not to bore people to death... Even my steam account only asking 2FA when i login from different PC.

**Comment by MissAllSunday** [comment]
Like I said, not my call, I'm merely stating my very own and unique opinion on this...

**Comment by Arantor** [comment]
Nope, I don't see it as wrong. I just wanted to understand the value of it as I'm one of the people who never quite understood the value of doing it before, especially when people might consider it a bug rather than a feature.

I see the value of 2FA as a thing that can be opted into (but not mandatory for admins, because that would be the first thing I remove, as I don't have a mobile device handy most of the time where that would actually help me).

I'm not sure I see the value here. I see that you do. If you see the value in it, and your reasons are valid, and it seems like they are, then stick with it. I have faith in your judgement even if I don't always understand your position. Here I do. Keep it.

**Comment by sbulen** [comment]
Am I thinking about this too simply?   
  -  Moderator activity should be protected & have a set of permissions associated with it.
  -  Admin activity should be protected & have a set of permissions associated with it.
  -  If there is 100% overlap between moderator & admin protections, you can do away with one, and have the other assume the combined set of rights.  
  -  Today, we don't do this...  If logged in as a moderator, we do not assume you have authority to do all admin tasks, & vice-versa.   
  -  Further, the permissions settings are not hierarchical in nature.  I.e., it's not designed from the ground up to think "if you can do this, you can do that, too".  

As long as we allow them to be set differently, we keep them separate.  If, in the future, we re-defined the roles & the approach to role-based security, maybe a different answer.  

In the meantime, my suggestion is to leave it as-is & close this out.  

And consider hierarchical (or hybrid) elements in the security model for SMF3.

**Comment by XinYenFon** [comment]
@sbulen actually this is only for mod center, its not really protecting/preventing any mod action. I suggest to leave this as is and collect real-usage data from forums and decide its fate in next version.

**Comment by jdarwood007** [comment]
Since I implanted this, my feedback.

We should leave it in.  However we could disable it by default for new installs and upgrades.
This leaves the logic in place for this to be done, but allows what most forums would see as logical.

Thoughts?
