### ISSUE TITLE
[3.0]: ipv6 logging/expansion correct?

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#8341]
### Basic Information

This doesn't feel right to me, but I may be off base...  If so, please feel free to close out...  I don't yet have a lot of familiarity with ipv6...

My test environment uses 127.0.0.1 as the host IP address.  My apache supports ipv6.   When looking at IP addresses getting logged, I would have expected one of:
 - 127.0.0.1
 - 0:0:0:0:0:ffff:7f00:0001
 - ::ffff:7f00:1
 - 0000:0000:0000:0000:0000:ffff:7f00:0001

But instead I'm seeing a lot of ::1:
![image](https://github.com/user-attachments/assets/926e93d4-db6d-4b9c-9fc1-add4c5706fd1)

### Steps to reproduce

1. Post anything on localhost
2. View the IP in the DB

### Expected result

An IP address of any variant of 127.0.0.1 as shown above.

### Actual result

I am seeing ::1

### Version/Git revision

3.0 Alpha 2 - current GH

### Database Engine

All

### Database Version

8.4

### PHP Version

8.3.8

**Comment by jdarwood007** [comment]
::1 is localhost.  i.e. 127.0.0.1.

**Comment by sbulen** [comment]
Hmmm...   I'll close... Not sure it makes sense to me, but I'll take your word for it!

**Comment by DiegoAndresCortes** [comment]
I can confirm what Sleepy says, I added ::1 to my /hosts in a macbook to speed up nginx because it wanted to read both using local domains.

**Comment by tyrsson** [comment]
From the IBM site:

> Loopback address
The loopback address is 0:0:0:0:0:0:0:1. You can abbreviate the address as ::1. The loopback address is used by a node to send a packet to itself.
