### ISSUE TITLE
[3.0]: Issue with Quick Edit

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#8358]
### Basic Information

Quick Edit feature does not work properly.

Possible solution:

`QuoteFast.php`, replace
```php
$query_customizations['where'][] = 't.locked = {int:not_locked}' . ($bq == '0=1' ? '' : ' OR m.' . $bq);
```
with
```php
$query_customizations['where'][] = 't.locked = {int:not_locked}' . ($bq == '0=1' ? '' : ' OR 1=' . $bq);
```

### Steps to reproduce

1. Click "Quick Edit" button for any message

### Version/Git revision

3.0 Alpha 2

### Database Engine

All

### Database Version

11.2.2-MariaDB

### PHP Version

8.4.1

### Logs

```shell
Database Error: Unknown column 'm.1' in 'where clause'
```

**Comment by jdarwood007** [comment]
@live627 From PR #8335
