### ISSUE TITLE
Some Markdown bugs

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#8360]
source fille https://github.com/live627/smf-ultimate-menu/blob/master/README.md

![Screenshot 2024-12-15 at 02-08-30 lorem ipsum egestas integer](https://github.com/user-attachments/assets/e38d4398-1e18-44fb-9a18-249e45802fde)
![Screenshot 2024-12-15 at 02-08-30 lorem ipsum egestas integer](https://github.com/user-attachments/assets/5c3ca636-71d1-47ef-9cbf-b1b3ca34364a)

**Comment by live627** [comment]
another one, single fenced code block gets   split

https://github.com/live627/check-pr-signoff-action/blob/main/README.md

![Screenshot 2024-12-15 at 02-21-36 lorem ipsum egestas integer](https://github.com/user-attachments/assets/f69f768a-a875-4b68-a09d-d210540b35d4)

**Comment by live627** [comment]
and here is smiley in bbc code block

![Screenshot 2024-12-15 at 02-35-21 lorem ipsum egestas integer  - Page 2](https://github.com/user-attachments/assets/5df8e62f-2c18-4083-8ee4-efa205c92d83)

**Comment by Oldiesmann** [comment]
I need to pay more attention to development around here... I didn't even know SMF3 supported markdown now :stuck_out_tongue:
