### ISSUE TITLE
[2.1, 3.0]: Constant SID is deprecated

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#8365]
### Basic Information

This error occurs periodically and is related to the code where the constant is used.

Example:

```php
if (defined('SID') && SID != '')
```

### Version/Git revision

3.0 Alpha 2

### Database Engine

All

### Database Version

11.2.2-MariaDB

### PHP Version

8.4.1

**Comment by jdarwood007** [comment]
I can't find any information about SID being deprecated.

**Comment by jdarwood007** [comment]
I found it:

> Changing the value of the [session.use_only_cookies](https://www.php.net/manual/en/session.configuration.php#ini.session.use-only-cookies), [session.use_trans_sid](https://www.php.net/manual/en/session.configuration.php#ini.session.use-trans-sid), [session.trans_sid_tags](https://www.php.net/manual/en/session.configuration.php#ini.session.trans-sid-tags), [session.trans_sid_hosts](https://www.php.net/manual/en/session.configuration.php#ini.session.trans-sid-hosts), and [session.referer_check](https://www.php.net/manual/en/session.configuration.php#ini.session.referer-check) INI settings is deprecated. The [SID](https://www.php.net/manual/en/session.constants.php#constant.sid) constant is also deprecated.

https://www.php.net/manual/en/migration84.deprecated.php

**Comment by jdarwood007** [comment]
Looks like they haven't documented it yet: https://github.com/php/doc-en/issues/3872
Even PHP watch didn't document this, which is why I didn't catch it as I tend to read that to know what to look out for.

**Comment by tyrsson** [comment]
I know the project is using php-cs-fixer but there is more than likely something like this for it.
https://github.com/PHPCompatibility/PHPCompatibility

**Comment by live627** [comment]
Does anyone know if any search engines such as googlebot accept cookies?

(This question actually is relevant)

**Comment by live627** [comment]
Got the answer from Gemini or whatever they call it next.

![Screenshot 2024-12-25 at 04-51-10 Does anyone know if any search engines such as googlebot send cookies - Google Search](https://github.com/user-attachments/assets/135246bc-7c29-4441-a4bf-6428ffde52a0)
1

**Comment by Sesquipedalian** [comment]
IIRC, we can just replace `SID` with `session_id()` and be done with it.

**Comment by jdarwood007** [comment]
@live627 I wouldn't trust that answer. Google is known to have its bots parse and execute Javascript and mimic user actions to test its analytics and AdSense (checking if ads only show for bots). Some of that would require passing cookies, as the site may otherwise use a cookie to know whether something is from a bot or not.
