### ISSUE TITLE
Undefined index: complex_preg_chars

### ISSUE THREAD

**Issue by AaronVanGeffen** [SimpleMachines/SMF#843]
8: Undefined index: complex_preg_chars
/smf/index.php?action=profile;area=account;u=1
File: /var/www/smf/Sources/Profile-Modify.php(502) : runtime-created function
Line: 4

Forum is running in UTF-8 mode. Don't have time to dive into this one myself, sorry.

**Comment by Arantor** [comment]
This one's down to me just adding the 2.0 patch, naively assuming that certain underlying things would be carried forward from 2.0 like $context['server']['complex_preg_chars'] ;)
