### ISSUE TITLE
PM navigation issues (mostly convo mode)

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#850]
As per http://dev.simplemachines.org/mantis/view.php?id=4800 and more pertinently, http://www.simplemachines.org/community/index.php?topic=441946.0
- Prev/next convo links
- Delete popup message is wrong (as also referenced in other Mantis issues)
- Redirect navigation is incorrect after deletion

**Comment by Oldiesmann** [comment]
Fixed the "delete popup message is wrong" part of it. The other two will require more effort.

**Comment by Arantor** [comment]
Closed as apparently not important enough to fix.
