### ISSUE TITLE
No 'view profile summary' permission denies paid subscriptions

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#852]
As per http://dev.simplemachines.org/mantis/view.php?id=4903

If the user does not have permission to view their own profile, the paid subs area is also hidden. This is because in the profile area, every area explicitly must have a permission check, no permission defined = not allowed (e.g. ban page has no 'own' permission defined so it cannot ever be called for the user's own profile; they can't ban themselves)

A simple, if inelegant, fix would be to introduce a dummy permission, granted to the user if paid subs is enabled just inside the permissions checking area, and then this dummy permission checked for that page.

**Comment by illori** [comment]
similar to this if this permission is not given, the users can not access the layout and preferences section of their profile.

may also apply to notifications/personal messaging/buddies/ignore list

off topic note, why do we need the personal messaging stuff in the profile and in the my messages area?

**Comment by Arantor** [comment]
Off topic: I don't know. It's on my to-do list to deal with.

In the case of layout/preferences, that's kind of related to your profile. I think half the problem is the wording of the permission (which, you'll note from the original report, is the Simple Permissions wording)

**Comment by illori** [comment]
even the classic permission "Edit additional profile settings" i would think would just be for the "forum profile" page and not much else.

**Comment by Arantor** [comment]
Yup. Even though Suki added a bunch of permissions, we don't have ones for those - and frankly I think we're getting into overkill if we did that sort of thing. Just like adding an actual permission for 'accessing paid subs' would be overkill.

But I can envisage a situation where folks don't actually go to their own profile anyway (with the user CP stuff I talked about), so it would have to be tied to something else like a dummy permission.

**Comment by illori** [comment]
could it be possible to remove it from this permission and make these pages available to anyone that is not a guest?

**Comment by Arantor** [comment]
As I already said, the profile code _demands_ every area to have a permission if you want to enter it. Specifically the code actually indicates a permission name to be used, if no permission is stated, you automatically do not have the ability to do that. E.g. as I said no permission is indicated for the ban page for 'own', so that you cannot ever access the 'ban this user' page for your own account.

Possible, sure, but not without breaking backwards compatibility, not without relying on mods not to screw it up - or we do it with a dummy permission which is ugly but is workable.

**Comment by Arantor** [comment]
#861 deals with this. Anything that used to be profile_view_own is now tied to a new quasi-permission, is_not_guest, and removed from being a regular permission, profile_view_any is now simply profile_view.

Means that paid subscriptions now can't be hidden via permissions ;)
