### ISSUE TITLE
Maintenance move topics needs more options

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#853]
Right now, maintenance / topics allows for quite selective deletion of topics but it doesn't allow for the same flexibility for moving topics.

On top of 'from' and 'top' boards, it needs to be able to select old topics, whether to include sticky/locked topics. (Should probably ignore moved notices)

Originally from http://www.simplemachines.org/community/index.php?topic=475556.0

**Comment by Arantor** [comment]
Is this one all done now?

**Comment by Oldiesmann** [comment]
Unless I missed something, it should be.

**Comment by Oldiesmann** [comment]
Looking over this again... It looks like I got everything with my PR, so I'll go ahead and close it.
