### ISSUE TITLE
issue with likes/unlike

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#864]
go to a thread with a logged in user, like a post, like the same post with another account so you should have 2 likes.

now view the likes by clicking on the link "1 other person" so you can view the popup...

close the popup, the post gives you can option to unlike the post, now refresh the page and it now looks like you can like the thread again, so click on like again. the message changes to 1 person likes this, so you did unlike the post not like. the only issue i see here is that between page loads it does not seem to keep the like status for the like/unlike text and image

also when like changes back to like when it should be unlike the message under like changes to 2 people like this so it is not tracking that _you_ liked the message before.

**Comment by Arantor** [comment]
Is this still an issue?

**Comment by illori** [comment]
looks fixed.
