### ISSUE TITLE
Theme URLs aren't set properly in a fresh install

### ISSUE THREAD

**Issue by AaronVanGeffen** [SimpleMachines/SMF#868]
Theme URLs aren't set properly when doing a fresh install, e.g. they become http://127.0.0.1/smf/Themes/default

My guess is $boardurl isn't updated yet when populating the theme table – looking at Settings.php afterwards, $boardurl looks fine, though.

**Comment by illori** [comment]
i cant duplicate this on my localhost install. all the paths are correct for themes and otherwise.

**Comment by AaronVanGeffen** [comment]
Did you reset your Settings.php before testing? That is, setting $boardurl to 'http://127.0.0.1/smf'?

**Comment by illori** [comment]
no, i did not change anything but do a clean install in a new db.

**Comment by Arantor** [comment]
Now that's been merged, we should probably re-test before closing this.

**Comment by NanoSector** [comment]
Just replicated, still happens. Fresh 2.1 install on Ubuntu 13.10 with Apache 2.4.6, PHP 5.5.3. Also happens in SMF 2.0.

**Comment by Oldiesmann** [comment]
Is boardurl being set properly when this issue occurs?

**Comment by NanoSector** [comment]
Yes it is.

**Comment by Oldiesmann** [comment]
I honestly cannot understand why that would happen. The install SQL file uses {$boardurl}/Themes/default and similar. $boardurl there is replaced with whatever is in Settings.php.

**Comment by Xarcell** [comment]
I had this problem when I first forked 2.1. It was because of the location of the Settings.php & install.php not being in the root directory.

**Comment by Arantor** [comment]
That's absolutely and completely intentional that the Settings.php and installer files are not in the root directory. You're supposed to move them out of other/ and into your root directory before installation, so that user credentials don't accidentally get committed, and so that the removal of the installer/upgrader on completion of those tasks doesn't confuse the repo.

**Comment by AaronVanGeffen** [comment]
That's also not how this problem originally arose for me.

**Comment by NanoSector** [comment]
@Xarcell: If you don't have those in your root directory you wouldn't be able to install and use SMF to begin with.

**Comment by Xarcell** [comment]
@Yoshi2889 I know that, I wasn't sure if AaronVanGeffen did. You can install SMF with some modifications to those files. While it was never 100% correct, I managed to get it to work and have all those files in an "install" folder. That was almost a year ago and I don't quite remember exactly what I did, but during working out the process, I was getting the same error mentioned here.

**Comment by NanoSector** [comment]
Just reinstalled SMF 2.0. Running on Ubuntu 13.10.

With help of @illori I made sure Apache wasn't the problem;

```
rick@rick-K53E:/etc/apache2/sites-available$ sudo service apache2 restart
 * Restarting web server apache2                                                AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
                                                                         [ OK ]
```

Added "ServerName localhost" to my apache2.conf...

```
rick@rick-K53E:/etc/apache2$ sudo service apache2 restart
 * Restarting web server apache2                                         [ OK ]
```

That's solved. Reinstalled SMF, nothing.

Went into the source of the page, found this:

```
    <link rel="stylesheet" type="text/css" href="http://127.0.0.1/smf/Themes/default/css/index.css?fin20" />
    <script type="text/javascript" src="http://127.0.0.1/smf/Themes/default/scripts/script.js?fin20"></script>
    <script type="text/javascript" src="http://127.0.0.1/smf/Themes/default/scripts/theme.js?fin20"></script>
```

My $boardurl = 'http://localhost/smf20';
Note the numbers; they're missing in the bit of HTML.

Installed to localhost/smf... And it works. As a final resort to see if it doesn't just default to /smf in the URLs, a last install to /smftest... Also works.

A dump of the HTML however shows me that it defaults to /smf in the URLs as I suspected:

```
    <link rel="stylesheet" type="text/css" href="http://127.0.0.1/smf/Themes/default/css/index.css?fin20" />
    <script type="text/javascript" src="http://127.0.0.1/smf/Themes/default/scripts/script.js?fin20"></script>
    <script type="text/javascript" src="http://127.0.0.1/smf/Themes/default/scripts/theme.js?fin20"></script>
```

Also note that it uses 127.0.0.1 instead of localhost.

I can't find in the installer where it messes with 127.0.0.1 as I used localhost during every install; only instance I found is where it finds out whether SMF is installed already.

Hope this gives a better view on this.

**Comment by AaronVanGeffen** [comment]
Settings.php uses 127.0.0.1 in its default $boardurl. That's my best bet on the source of the problem: effectively, the updated $boardurl doesn't end up in the global scope after Settings.php is reloaded.

**Comment by Arantor** [comment]
I've just run through a number of installations in testing an unrelated issue and each time it completed successfully with the correct $boardurl - and each time I went back to the master Settings.php from other/ and it's worked consistently. If it re-occurs with current files, we'll reopen this but as far as I'm concerned this is working correctly.

**Comment by piffall** [comment]
It is possible that APC (Alternative PHP Cache) cause this.

Settings.php is cached with:

``` php
$boardurl = "http://127.0.0.1/smf";
```

Try to install with apc disabled, adding a .htaccess

``` apache
php_flag apc.cache_by_default Off
```

**Comment by AaronVanGeffen** [comment]
I wasn't using APC at the time, but all the same, there might have been a race condition with the Zend opcode cache...

**Comment by Arantor** [comment]
Yeah, we did subsequently find an issue with Zend OpCache that should have long since been fixed.

I don't think we've seen it since with APC though.

**Comment by greysondn** [comment]
How to fix this without reinstalling...?

**Comment by AaronVanGeffen** [comment]
Easiest way is to use the repair_settings.php script found in /other/tools

**Comment by greysondn** [comment]
```
sites # ls smf/
agreement.txt  avatars  index.php    news_readme.html  readme.html       Settings.php  Sources           ssi_examples.shtml  subscriptions.php
attachments    cache    license.txt  Packages          Settings_bak.php  Smileys       ssi_examples.php  SSI.php             Themes
```

It's not in the latest `.tar.gz` linked from the SMF site.(I double-checked the archive downloaded.)

**Comment by illori** [comment]
repair_settings.php is not in other/tools it is in the tools repo or on sm.org

**Comment by Arantor** [comment]
And this is deliberate because leaving it in the main install would be a serious security risk.

**Comment by CryptoCanary** [comment]
I had an issue with SMF wanting to insert "http://127.0.0.1/smf/" in my HTML. Even with $boardurl changed. I changed the value in the database to correct this. There is a "smf_themes" table in the newly created database. Both "theme_url" and "images_url" need modified to point to the SMF install.

**Comment by Arantor** [comment]
Yes, but where did you have this trouble? SMF 2.0? 2.1 from a current Github packag?

**Comment by CryptoCanary** [comment]
Sorry, 2.0.9 and yes it was current. I only installed yesterday. I did find where this is set in the admin. A similar issue happened for smileys and avitars. It was looking for them in http://127.0.0.1..." also by default. By my mistake, I might have told it to do this from the install. I just thought my post might help someone with the issue also. :) cheers!

**Comment by illori** [comment]
please do not report issues with 2.0.9 here. this tracker is specifically for 2.1.

**Comment by greysondn** [comment]
Happened again.

New forum for a client on 2.0.11 using the install zip from SMF main site

I don't mind the extra legwork, but I still don't understand the actual explanation for why this happens.

Edit: Needs tested in 2.1 ; my bad, hadn't realized that the repo had been more-or-less renamed here. Where to report errors in (ostensibly) stable?

**Comment by soheil-zz** [comment]
SOLUTION:
1. Change `theme_url` and `images_url` from 127.0.0.1 to your domain in `smf_themes` table in your database.
2. Purge cache by changing `Chaching Level` to `No chaching` in Server Settings > Caching (change back to recommended setting afterwards.)

**Comment by verymilan** [comment]
@soheil how can i do this?

```
update forum_themes set theme_url=’forum.domain.tk’ where '127.0.0.1/smf';
```

does not work... .
I just installed the latest release on the page, got this 127.0.0.1 missrouting and 

```
forum.domain/forum.domain/index.php?action=login2 
```

on login button for example -.-

**Comment by greysondn** [comment]
The fix is up above, along with where to find it. They've thus far failed to explain why it happens, however.

**Comment by killermosi** [comment]
This issue is still present on 2.0.14, and most likely is something environment-related.

The `repair_settings.php` tool fixed the issue.

Since this happens every time I install SMF on this particular machine, is there an installation log or something that can help track down the issue?

**Comment by illori** [comment]
Please don't report SMF 2.0 issues on github. Github is only for 2.1.
