### ISSUE TITLE
Upgrading "verification questions"

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#882]
Executing: "Upgrading "verification questions" feature" (19 of 23)

Error!
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' Write this site's name without www & dots & com, serialize(array(mmobro' at line 4

Anti-Spam Question : Write this site's name without www & dots & com
Answer: mmobrowser

Upgrade to MySQLi selected.

**Comment by Arantor** [comment]
Yeah, it doesn't like the ' in there. Need to rewrite that to use db_insert rather than bare insert queries.
