### ISSUE TITLE
Contact icons in mini profile displayed in column

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#889]
http://test2.turtleshellprod.com/index.php?topic=6.msg11#msg11

I have filled in all of the IM type fields.
The icons are displayed in a column rather than a row.
(and ICQ is displayed as the alt-text not as the icon)

(additionally, my custom profile field with an icon seems to have disappeared after the upgrade was run)

**Comment by illori** [comment]
on your forum the image for irq is pointing to http://test2.turtleshellprod.com/images/graph_16x16.gif where on my test install it is pointing to http://status.icq.com/online.png?img=5&icq=123456 [just a random number i put in]

``` php

echo '
                                <li class="im_icons">
                                    <ol>';
                            }
                    echo '
                                        <li>', $custom['value'], '</li>';
```

that code seems to putting each im_icon in its own li which seems to be causing this issue.

**Comment by Kindred-999** [comment]
ummm.... no it's not....

```
<li>
<a class="icq new_win" title="ICQ Messenger - 1234" target="_blank" href="http://www.icq.com/whitepages/about_me.php?uin=1234">
<img height="18" width="18" alt="ICQ Messenger - 1234" src="http://status.icq.com/online.png?img=5&icq=1234">
</a>
</li>
```

The graph icon was one of the custom profile fields...   and I realized why it stopped showing (whe I blew away the previous installation, I killed the images directory as well.oops -- so THAT is not a bug.)
BUt the ICQ icon definitely seems to NOT display....
and the rest of the icons show in a column

**Comment by Arantor** [comment]
Well, the ICQ icon is stored offsite - and the URL appears to not work now (because it used to use the ICQ server's own thing for the reason that it would be able to show offline vs online)

**Comment by illori** [comment]
http://status.icq.com/online.gif?img=5&icq=1231123 is the link for 2.0 for ICQ and it seems to work just fine.

but i would be in favor of dropping linking to ICQ and just using an image instead.

**Comment by Arantor** [comment]
So, the icon is now not offsite, alignment should be fixed.

Do we know if there is still an issue with the upgrader damaging custom fields?

**Comment by illori** [comment]
kindred said above he deleted his images folder so the upgrader did nothing to the custom profile fields.

**Comment by Arantor** [comment]
In which case, the upgrader isn't a problem and therefore we can knock this one out of the park.
