### ISSUE TITLE
Child board....

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#891]
1- I thought we were renaming child board to sub-board
2- adding a sub-board seems to have the on2 permanently set to on... even when there are NO posts in the sub-board.
http://test2.turtleshellprod.com/index.php#c3

**Comment by Arantor** [comment]
No, we weren't because of the amount of people who deeply resented the idea of doing so in 2.1.

The other bug is a legitimate one of mine, I thought I'd fixed that but obviously not :P

**Comment by Arantor** [comment]
So, do we want to rename it or not?

**Comment by illori** [comment]
i dont really care either way, just would make documenting child/sub-boards a bit harder

**Comment by Kindred-999** [comment]
I've seen another rash of people looking to change the name....  
Personally, the term "child/parent" makes complete sense to me... but others seem to think it actually refers to real children....

**Comment by Arantor** [comment]
It makes complete sense to me too - in a technical context. The thing is, as I said, most of our users are _not_ technically minded.
