### ISSUE TITLE
DbExtra-mysqli.php missing

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#898]
i dont know if a 2.1 bug or repair_settings.php bug.

if you run repair_settings.php on 2.1 it complains that DbExtra-mysqli.php does not exist and it does not in 2.1.

**Comment by XinYenFon** [comment]
I actually reported it https://github.com/SimpleMachines/tools/issues/6 but don't know which place is more relevant for it.

**Comment by Arantor** [comment]
One isn't needed directly, the internal method for db_extend (which is what loads it after all) just loads the stock -mysql one because nothing's changed.

As such, closing this report and we'll fix it in repair_settings itself (ideally by having it use db_extend in the first place)
