### ISSUE TITLE
attachment directory paths can not be changed in admin panel

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#899]
using a wampserver on localhost if i attempt to rename an attachments directory path i get an error 
Oops, there seems to be a problem.
F:\wamp\www\github2.1/attachments: Unable to move or rename. Please verify that the path is correct or that this directory does not contain any sub-directories.

where that path does exist

also repair_settings.php does not fix the base directory paths.

when attempting to change the base directory paths in the admin panel, after changing the first path successfully each additional path change results in a database error

The database value you're trying to insert does not exist: value
Function: updateSettings
action=admin;area=manageattachments;sa=attachpaths;e47999d4=0e11b84e01355ed3483e7cc1987fa62e
File: F:/wamp/www/github2.1/Sources/Subs.php
Line: 473

Undefined offset: 0
action=admin;area=manageattachments;sa=attachpaths;e47999d4=0e11b84e01355ed3483e7cc1987fa62e
File: F:/wamp/www/github2.1/Sources/ManageAttachments.php
Line: 2188

Undefined index: current_base_dir
action=admin;area=manageattachments;sa=attachpaths;e47999d4=0e11b84e01355ed3483e7cc1987fa62e
File: F:/wamp/www/github2.1/Sources/ManageAttachments.php
Line: 2164

**Comment by MissAllSunday** [comment]
Also, you can quite happily add the main boarddir as an attachment dir then you can delete it and it will delete the main index.php file :P

**Comment by Oldiesmann** [comment]
The first issue is because PHP's rename() function returned false. It's possible that the "/" messed it up since you're on Windows. Is that how the directory path was specified in the settings?

The second string of errors is because $_POST['current_base_dir'] isn't set (all three errors are due to that). I'm looking into that one.

MissAllSunday - that definitely should not be possible. Thanks for pointing that out.

**Comment by illori** [comment]
i am trying to change my second base directory path from C:\wamp\www\github2.1\attachments_1 to F:\wamp\www\github2.1\attachments_1

the first path [with similar naming] was able to be changed just fine but the additional 2 i have i can not get renamed.

**Comment by Oldiesmann** [comment]
I'm not sure what to say about that Illori. The error is because `$_POST['current_base_dir']` wasn't set, but that should never happen if you have base directories set up.

**Comment by illori** [comment]
well i have 3 setup [from prior testing] and i was only able to change the path in one of the 3.

**Comment by MissAllSunday** [comment]
It seems the problem with deleting the main index.php file hasn't been solved.  Haven't really look at the problem closely but heres how to reproduce it:

clean the "current" path text field, click on "add path" this create a new empty field, then click on save and the index.php file gets deleted.
I'll take a closer look.

**Comment by Oldiesmann** [comment]
Yeah, I do see that it's still possible. If the specified path isn't a directory, SMF checks to see if `$boarddir . DIRECTORY_SEPERATOR . $path` is a directory. If it is, the path is set to that instead, and index.php and .htaccess in $path are deleted, without even verifying whether the path is equal to boarddir.

**Comment by Arantor** [comment]
If you're going to compare to $boarddir, be sure to realpath() both first.

**Comment by Oldiesmann** [comment]
That should fix the remaining issue with index.php getting deleted.

**Comment by illori** [comment]
after a reformat and drive letters changing, i still can not change the path in the admin panel for attachments. trying to change the base directory paths does not save them, one of the 3 is set as the current one. i cant even change that one. click save and it reverts back to the old path that is incorrect. 

there is a message that says a directory exists at that path so unable to move. sounds like only repair_settings.php can fix this... why have the option to list the full path in the admin panel if you can not change it to an existing directory that is "correct" ?

also at one point i did get the error about "Undefined index: current_base_dir" that is reported in the initial issue.
