### ISSUE TITLE
username checks (registration and login)

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#90]
I'm not sure if this is a bug since there it's a regexp...
In Register.php there is:
`if (preg_match('~[<>&"\'=\\\]~', preg_replace('~&#(?:\\d{1,7}|x[0-9a-fA-F]{1,6});~', '',`
while in LogInOut.php:
`if (preg_match('~[<>&"\'=\\\]~', preg_replace('~(&#(\\d{1,7}|x[0-9a-fA-F]{1,6});)~', '',`
The two patterns of the preg_replace are slightly different.

Is it correct?
One of the two is wrong? If so which one should we use?

**Comment by Spuds** [comment]
They are really the same ... the first has no capture groups and the second has two .... If the backreferences in the second are not being used then they could be dropped.

**Comment by joshuaadickerson** [comment]
As Spuds said, the one from Register.php should be used since there are no backreferences being used:

```
// No funky symbols either.
if (preg_match('~[<>&"\'=\\\]~', preg_replace('~(&#(\\d{1,7}|x[0-9a-fA-F]{1,6});)~', '', $_POST['user'])) != 0)
{
    $context['login_errors'] = array($txt['error_invalid_characters_username']);
    return;
}
```
