### ISSUE TITLE
password permission

### ISSUE THREAD

**Issue by emanuele45** [SimpleMachines/SMF#902]
I find odd that admins have power to prevent me from changing my own password.

IMHO, change password should not affect own (i.e. always allowed) and the any should be under Member administration (well...I'd go as far as to say that also delete any should be there, but since is connected to the own it make sense to have it under profile).
Oh, and the password can still be changed with a password reminder.

Also, change password/any give also the permission to change email, but giving edit account settings any doesn't allow to change neither the email nor the password, just the visibility of the email. It looks confusing to be honest, by the name I would expect it to be a "master" permission for all the actions in that page, but is not.

**Comment by Arantor** [comment]
There are legitimate cases where that would be an advantage, e.g. bridges where the systems are not kept in sync.

You're right about the password reminder, does that do any checks against the user account requesting a new password vs groups that could otherwise change their password?

**Comment by emanuele45** [comment]
Though bridges should not be checked against permissions...in that case a modSettings would be better (enable/disable) because permissions do no affect in any way admins for example and would break the bridge anyway...

**Comment by Arantor** [comment]
That's very true, just sayin' there was a legitimate reason you might want to do ;)
