### ISSUE TITLE
Install misses smf_categories

### ISSUE THREAD

**Issue by BurkeKnight** [SimpleMachines/SMF#941]
Table smf_categories doesn't exist after new install.

Even after the fix here:
https://github.com/SimpleMachines/SMF2.1/pull/940

**Comment by Arantor** [comment]
Did you actually install it after that was added?

**Comment by Arantor** [comment]
It would have been nice if people had actually given me the error message that actually is spewed during the installer which would have cleared this matter up as opposed to guessing.
