### ISSUE TITLE
minor: Password flood error generates multiple undefined/general PHP errors 

### ISSUE THREAD

**Issue by HoverClub** [SimpleMachines/SMF#944]
If the password flood check fails (load.php, line 310) the resulting fatal_lang_error tries to load the theme which relies on the permissions being available - they haven't been loaded yet so multiple PHP errors are generated as the code loads templates, etc..  

Backtrace:
smf_main->loadUserSettings->validatePasswordFlood (fails)->fatal_lang_error->LoadTheme->isAllowed['admin_forum'] 

A possible fix might be to return false for any permission if the permissions are not available (security.php line 921 - allowedTo, etc.    if (empty($user_info) OR empty($user_info['permissions'])) return false; ?

Example of the issue:
http://www.simplemachines.org/community/index.php?topic=513216.msg3627169#msg3627169

**Comment by HoverClub** [comment]
I've also just found other errors from $user_info itself not being populated - all through the failed flood check as above.  

Could  $user_info be populated with the default guest values at the start of loadUserSettings (then replaced by any "real" member data) or is that likely to cause other issues?

**Comment by Oldiesmann** [comment]
I think returning false if $user_info or $user_info['permissions'] are empty should be enough. There's no point in populating an array with a bunch of dummy data just to avoid PHP errors when there are easier ways around it.

**Comment by emanuele45** [comment]
In loadTheme $user_info is already populated as far as I can see (loadUserSettings is called before loadTheme).

And if $user_info contains data, but 'permissions' is not an array, it means there is something wrong somewhere else, because loadUserSettings initialize 'permissions' as an empty array.

**Comment by HoverClub** [comment]
If the flood test (during loadUserSettings) fails then it bails out to fatal_lang_error BEFORE loadUserSettings has populated the $user_info array.  It then spews out around 70 PHP errors/warnings every time a flood check fails - that's a pain for admins looking at logs and trying to work out what's gone wrong.  

A lot of the system won't work properly if $user_info isn't valid so surely it should be populated as early as possible (and certainly, as in this case, before any function that can bypass the normal load sequence, is called)?

**Comment by emanuele45** [comment]
Then, if $user_info is empty and allowedTo returns false.

**Comment by HoverClub** [comment]
It's not enough only fixing permission checks  ..... template_header->setupThemeContext requires $user_info[groups], $user_info[is_guest], $user_info[language], etc., etc.  All these irrelevant errors are generated because a failed flood check bypasses the normal load sequence.

**Comment by emanuele45** [comment]
It has been like that for years and no errors have ever been reported.
Why you are the only one encountering this problem?

I tested the flood check few times (I just repeated again the test now, introducing 6/7 times and repeated it again), but I was not able to reproduce the error you reported. 

Dunno, maybe others can see things I can't.

**Comment by HoverClub** [comment]
No doubt is has been there for years.  I'm not the only person to report it - see my first comment for a link.  I found it because I have 3 users who are unable to login - the flood check rejects them on their FIRST login attempt.  I haven't found the reason for this yet (other than it's cookie related) BUT it doesn't affect this particular issue.  If the flood check fails (for whatever reason) then I think I've clearly described where these errors come from.

Most sites don't see failed flood checks so won't see this issue and, even if they do, they are non-critical errors so are probably just ignored. As I said, this is a minor issue - if it's not worth fixing then that's OK by me.

**Comment by Arantor** [comment]
Every time this comes up, it seems to be on fairly heavily modded setups and I still think it's because of a dodgy mod calling for $user_info details before it's initialised.

**Comment by Oldiesmann** [comment]
Reopening for further investigation as per @Arantor.

**Comment by Oldiesmann** [comment]
I believe this should be fixed now. The ultimate issue here is that loadTheme() was trying to set initial $context['user'] info based on $user_info, which wasn't even set at that point. I changed it to only do that if $user_info isn't empty, but have also set it up to still define $context['user'] in that case since some parts of the theme depend on it.
