### ISSUE TITLE
Undefined index: show_last_edit 

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#950]
edit a post using the full edit page

Notice: Undefined index: show_last_edit in F:\wamp\www\github2.1\Themes\default\Post.template.php on line 361

**Comment by Arantor** [comment]
show_last_edit does not exist anywhere else in the codebase.

@Oldiesmann Think this is something you were looking at?

**Comment by Oldiesmann** [comment]
Yeah, it's related to the edit reason thing I stuck in there. It's just me mis-typing a setting name somewhere. I'll fix it shortly :)
