### ISSUE TITLE
Add Language panel is somewhat broken

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#955]
![2013-11-30 15_39_32-edit languages](https://f.cloud.github.com/assets/1280380/1648906/62ce28e0-59cd-11e3-9c7e-13062610ca38.png)

Searching for all languages doesn't work as it tells you nothing is found, but that could be the case because IIRC no language packs were pushed for 2.1.

Other than that the "The following languages were found." looks broken as it needs a header. I also think everything below that including the message itself should be hidden when nothing is found.

As for header name, I feel it should be something like "Available languages" or similar.

**Comment by Oldiesmann** [comment]
The "no files could be found" is indeed because there aren't any language packs for 2.1 yet. I'll look into the header thing and see what we can do about that. It shouldn't be showing that if no files were found.

**Comment by Oldiesmann** [comment]
Fixed the issues with the header and install instructions being shown even when there weren't any languages. I'll look into why the info box is missing a top border.

**Comment by Arantor** [comment]
Because the infobox is used elsewhere directly under catbg and titlebg so having a top border would be problematic. description is in a similar boat.
