### ISSUE TITLE
End Admin Session to redirect to board index/portal

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#956]
I was wondering why it redirects you back to the login screen. Usually if you end the session you want to exit the thing you end the session for, thus exit the admin panel.
IMO therefore it should redirect to the board index instead of the ACP. Thoughts?

**Comment by illori** [comment]
i really dont see a need to change it, and @MissAllSunday i dont see a PR for that commit?

the same would also apply to end moderation center session

**Comment by Arantor** [comment]
I agree with changing it. (PR plz :))

**Comment by NanoSector** [comment]
The same would indeed apply to the moderation centre, forgot that one also has such a button.

**Comment by MissAllSunday** [comment]
I haven't send a PR because I want to add a couple more fixes

I'll do the moderation centre too, thanks for point it :)

**Comment by NanoSector** [comment]
Thanks Suki :)

**Comment by NanoSector** [comment]
By the way, food for thought, but is it possible and wanted to perhaps add a message saying "Hey ho you've been kicked out the ACP, now get yer community rolling"?

(In all seriousness I was thinking of a message like "Your admin panel session has now been ended.")

Might be worth it to provide some feedback to users.

**Comment by Arantor** [comment]
That reminds me awfully of what you see in MyBB and other systems where you get the interstitial page of 'Thank you for logging in, please wait while we redirect you', and we'd be encouraged then to put them everywhere.

**Comment by NanoSector** [comment]
I don't agree; the effect of logging in is immediately visible upon the next page load, whereas the effect of ending your admin session isn't, hence it might be a good idea to provide feedback to the user.

**Comment by Arantor** [comment]
So, by that same logic, we should have an interstitial page on logging out of the forum too, yes?

**Comment by NanoSector** [comment]
No, because logging out is also something on which you can easily see the effect.

**Comment by Arantor** [comment]
Not necessarily it isn't.

**Comment by NanoSector** [comment]
It is, you can't post (in all boards), your username won't show up in the header, ...

But if you don't think this idea will work, feel free to disregard it.

**Comment by Oldiesmann** [comment]
I really really really don't want to see any sort of redirectional screen in SMF. I absolutely hate that feature and have never understood its purpose. Loading an extra page just to say "whatever you tried to do was successful, now we're going to redirect you to where you want to go" is a waste of resources.

**Comment by NanoSector** [comment]
Then you misunderstand because I mean a simple message on the board index.

**Comment by Oldiesmann** [comment]
That's a bit different, but i still don't think it's necessary. If people can't figure out why they're redirected to the board index when they choose "End admin session", then that's not really our concern.

**Comment by NanoSector** [comment]
It is, we provide the software and we specify how clear it is to the users.

**Comment by Arantor** [comment]
I'd be extremely surprised if users actually complained. I don't generally think our users are that lacking.
