### ISSUE TITLE
Group Requests: History and Accountability

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#969]
Requestable groups just delete the request once resolved. So if User A applies to join a group and it's accepted, they're just moved. (It's possible, but somewhat unlikely, that the change will be logged in the profile log) Or if the request is denied, nothing happens.

Nothing, that is, except the request is deleted. There is no history of requests made by a user, no history of whether those requests were accepted or denied, nor even accountability - if a user is promoted and it shouldn't have been done, there's no log to say _who_ approved the change. (Under the right circumstances it might be in the profile log but that's not a good get-out clause)

This is by design, the code is very clear on this point: log_group_requests doesn't even have columns to store resolution status, and the code comment even says about how it's 'removing the evidence'.

So it's not _technically_ a bug report because it is how it was designed but I'd certainly argue it needs amendment.

**Comment by Oldiesmann** [comment]
I definitely agree that it should be changed. If someone applies to a group and is declined membership, then applies again, a different mod/admin could approve the request not knowing that a previous request was declined. Having accountability and logs could be quite useful.

**Comment by Arantor** [comment]
Currently working on this. I'm about 50% done thus far.

**Comment by Xarcell** [comment]
I agree also.
