### ISSUE TITLE
memcache(d)

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#979]
are we supporting memcache or memcached? the cache page mentions both. when you click the ? next to memcache it mentions memcached. it is a bit confusing.

**Comment by Arantor** [comment]
Technically they're the same thing.

Memcache is the name of the system, there are two different libraries that access it, one called memcache, one called memcached. Technically, just to help matters, memcached is the name of the daemon that runs the service.

memcached is the correct name as far as I can tell. The capitalisation is all over the show even on memcached.org so I have no idea which is correct. But we should fix all public facing entries to be 'memcached'.
