### ISSUE TITLE
Post/Preview reversed

### ISSUE THREAD

**Issue by Arantor** [SimpleMachines/SMF#996]
Originally tracked as http://dev.simplemachines.org/mantis/view.php?id=4998

2.0 has them as Post / Preview / Spell Check, while 2.1 reverses this to Spell Check / Save Draft / Preview / Post.

The Mantis issue flags up some arguments in favour of leaving it as this, and there is an argument about reverting it to the 2.0 behaviour.

More feedback please :)

**Comment by illori** [comment]
the one that annoys me the most is in the error log where the buttons are reversed and i go to clear the log to end up clicking the button to delete selected errors but i had not selected any.

**Comment by Hristo-** [comment]
When I saw that 2.1 will reverse the buttons I did that on my 2.0.\* forum (purely with css) thinking that it will be better for the members when I have to upgrade. An year latter I have to say I like the new order better.

But there are some things I still do not like, especially the new place of the Submit Vote button. Most of the time it will be way out of sight.
![submit_vote](https://f.cloud.github.com/assets/6107569/1695615/575b8786-5eb5-11e3-937b-0f59019aaffe.png)

**Comment by Oldiesmann** [comment]
Ouch. Nice find Hristo. We'll see what we can do about that instance anyway.

**Comment by Arantor** [comment]
The one thing I will note with the buttons is that the tabindex still has the standard order, so tabbing out of the post box will take you to post, then preview etc.

**Comment by Xarcell** [comment]
I prefer it the way it is. My reasoning for this is that I prefer the buttons within the strongest action to be from right to left. Post being the most important, so it should be the furthest to the right, next I would say "Preview" because it causes a page reload. Between "Save Draft" and "Spell Check" it doesn't matter as much, but the current order is the most accurate IMO.

So in 2.1, I would leave it as it is.

**Comment by NanoSector** [comment]
Any ideas?

Today I hit myself on the error log; I kept hitting the Clear Selected Messages button instead of Clear Log, and wondered why it wasn't doing anything. The new order at the Post section also confuses me.
