### ISSUE TITLE
Liberation Sans font

### ISSUE THREAD

**Issue by Hristo-** [SimpleMachines/SMF#998]
2.1 uses "Segoe UI", "Helvetica Neue", "Liberation Sans", "Nimbus Sans L", Arial, sans-serif. Segoe UI comes with Vista and above also with Office 2007. Helvetica Neue obviously is for Mac. Liberation Sans is the default SMF2.1 (and Elkarte) font on XP. I still think that this font is really awful. Am I the only one who thinks that? Here 2 examples how it alway looked on my screen (this is from FF, in Chrome it's even worse)
![liberation_sans1](https://f.cloud.github.com/assets/6107569/1696365/1ff72576-5ec3-11e3-8898-1567f9c919bc.png)
![liberation_sans2](https://f.cloud.github.com/assets/6107569/1696366/202f7c6e-5ec3-11e3-943f-677303139772.png)

**Comment by Arantor** [comment]
So what would you suggest instead?

**Comment by Hristo-** [comment]
I only can suggest the obvious - to be removed. That will make Arial the default font on XP. I'm not a typographer, but as I see they consider Arial a low quality font. It looks much better than Liberation Sans, but it will be mostly the only option for XP because sans-serif is not common on that OS.

That said, if you ask for replacement for Liberation Sans as a fallback for Arial on XP unfortunately I'm not the one who can give an educated recommendation.

This is a good reference too:
http://archive.is/lnOT

**Comment by Hristo-** [comment]
Apparently Sans-serif is standard on XP (micross.ttf), but for some reason even if it's the only one declared for use the browser uses Arial.

**Comment by Oldiesmann** [comment]
According to http://www.kathymarks.com/archives/2006/11/best_fonts_for_the_web_1.html Arial is the best sans-serif font for the web on Windows (along with Tahoma and Verdana among others), so we should probably just skip out on Liberation Sans since it looks so bad.

**Comment by AaronVanGeffen** [comment]
Liberation Sans isn't a default font on Windows, for what it's worth. It's a typeface with the exact same metrics as Arial found in most Linux distributions.

Most Linux distros use Liberation Sans whenever Arial is requested, so I guess leaving it out of the CSS won't do much harm.

**Comment by Hristo-** [comment]
@Oldiesmann Personally I find it OK. I do not know why so many typographers consider it of low readability. Whether it's only bias against Microsoft (since Arial is poorer copy of Helvetica) or it has solid base, I do not know. The fact is Arial has huge support on Win and also supports a lot of Unicode characters.

@AaronVanGeffen Your quite right that Liberation Sans is not part of XP as I assumed. Now I see it came with Libre Office.

That lowers significantly the number of affected users. I do not know if it looks better on Linux than on Windows, but still it could be a problem. If not removing/replacing it, just moving it after sans-serif should be enough.

**Comment by emanuele45** [comment]
If you search in one of the hidden boards you should be able to find Ant's rationale behind the choice, and I think Liberation Sans was mean to cover exactly Linux distributions.

**Comment by Arantor** [comment]
I find it absolutely hilarious to note that Github uses Helvetica, Arial in that order... so a lot of people who come here will have already seen Arial and not even noticed it.

**Comment by Hristo-** [comment]
Accidentally found the reason why this font looks OK for some users and bad for others. It's due to methods used for smoothing edges of screen fonts. By default XP is set to standard, while 7 is set to ClearType. Changing it to ClearType makes it look OK. Also IE7+ uses ClearType smoothing by default even if the OS is set to Standard. Obviously the fond is much more dependent to this setting than other fonts.

**Comment by Arantor** [comment]
So do I get the feeling we should leave this alone?

**Comment by illori** [comment]
lets see what the users think and change as needed after beta.

**Comment by Arantor** [comment]
I don't have a problem with that. Just want a few more comments from interested parties before I close this one.

**Comment by Hristo-** [comment]
~18% use XP at the moment. Do not know how many of them installed Libre/OpenOffice instead of the paid MS Office so I only can guess that this will be a problem maybe for 1-4% of the users. Just a guess.

**Comment by Arantor** [comment]
If they're still using XP at this point, it's quite possible they're also still using IE which allows for ClearType as per your research, meaning I'm not even sure it's as high as that.

**Comment by Hristo-** [comment]
XP allows only up to IE8 and none of the people I know still uses IE on XP, because many sites look bad on IE8 nowadays. But still it's a guess. illori has a good point IMO.

**Comment by Arantor** [comment]
How about I move Liberation Sans down after Arial in the list? Sounds like would solve all the issues.

**Comment by Hristo-** [comment]
This will solve the potential problem for Windows, of course. I guess if it causes some kind of problems under Linux it will be reported.

**Comment by Arantor** [comment]
Well, that's the thing... if Arial is somehow installed, it will use that but if not it will just go down the list until it hits a font that's actually installed.

**Comment by Hristo-** [comment]
As I see ~70% of Linux users has installed Arial. But considering that Nimbus Sans L is widely used (over 98%), that should not be a problem unless Arial looks really bad on Linux.
